---------- Collectibles ----------

local C_ID = "5.100."
EID.descriptions[languageCode].AdditionalInformations = {
	[C_ID .. 2] = "Isaac shoots 3 tears at once", -- The Inner Eye
	[C_ID .. 5] = "Tears get a boomerang effect", -- My Reflection
	[C_ID .. 8] = "Shoots normal tears", -- Brother Bobby
	[C_ID .. 9] = "All fly enemies are friendly", -- Skatole
	[C_ID .. 11] = "Isaac respawns with full health on death", -- 1up!
	[C_ID .. 13] = "{{Poison}} Touching enemies poisons them#{{BlackHeart}} Poisoned enemies can drop Black Hearts", -- The Virus
	[C_ID .. 21] = "Reveals icons on the map#Does not reveal the layout of the map", -- The Compass
	[C_ID .. 33] = "{{Timer}} Flight for the room#{{MomsHeart}} Kills Mom's Foot and Mom's Heart instantly#{{Warning}} Kills Isaac when used on Satan", -- The Bible
	[C_ID .. 36] = "Spawns one poop and knocks back enemies#Can be placed next to a pit and destroyed with a bomb to make a bridge", -- The Poop
	[C_ID .. 37] = "Drops a large bomb below Isaac which deals {VAR:1} damage", -- Mr. Boom
	[C_ID .. 38] = "Shoots 10 tears in a circle around Isaac#The tears copy Isaac's tear effects, plus 25 damage", -- Tammy's Head
	[C_ID .. 39] = "{{Petrify}} Petrifies all enemies in the room for 4 seconds", -- Mom's Bra
	[C_ID .. 40] = "Causes an explosion at Isaac's location#Deals {VAR:1} damage", -- Kamikaze!
	[C_ID .. 41] = "{{Fear}} Fears all enemies in the room for 5 seconds", -- Mom's Pad
	[C_ID .. 42] = "Using the item and firing in a direction throws the head#{{Poison}} The head explodes on impact and poisons enemies", -- Bob's Rotten Head
	[C_ID .. 44] = "Teleports Isaac into a random room, except I AM ERROR rooms", -- Teleport!
	[C_ID .. 46] = "+8% room clear reward chance#Better chance to win while gambling", -- Lucky Foot
	[C_ID .. 47] = "{{Collectible168}} On use, start aiming a crosshair#A missile lands on the crosshair after 1.5 seconds#It deals 20x Isaac's damage", -- Doctor's Remote
	[C_ID .. 49] = "The next shot is replaced with a beam#It deals {VAR:1}x Isaac's damage over {VAR:2} seconds", -- Shoop da Whoop!
	[C_ID .. 52] = "{{Bomb}} Isaac shoots bombs instead of tears#{{Damage}} Those bombs deal 5x Isaac's damage + 30", -- Dr. Fetus
	[C_ID .. 53] = "Pickups are attracted to Isaac", -- Magneto
	[C_ID .. 54] = "Reveals the floor layout#Does not reveal room icons", -- Treasure Map
	[C_ID .. 55] = "{VAR:LUCKCHANCE}% chance to shoot an extra tear backwards", -- Mom's Eye
	[C_ID .. 56] = "Spills a pool of creep#The creep deals 24 damage per second", -- Lemon Mishap
	[C_ID .. 57] = "Mid-range fly orbital", -- Distant Admiration
	[C_ID .. 60] = "Allows Isaac to cross 1-tile gaps", -- The Ladder
	[C_ID .. 62] = "{{HealingRed}} Killing 13 enemies heals half a heart", -- Charm of the Vampire
	[C_ID .. 63] = "{{Battery}} Active items can be overcharged to two full charges", -- The Battery
	[C_ID .. 64] = "{{Shop}} Shop items cost 50% less", -- Steam Sale
	[C_ID .. 65] = "Spawns 6 Troll Bombs near the center of the room", -- Anarchist Cookbook
	[C_ID .. 66] = "{{Slow}} Slows enemies down for 8 seconds", -- The Hourglass
	[C_ID .. 67] = "Shoots normal tears", -- Sister Maggy
	[C_ID .. 68] = "Isaac shoots lasers instead of tears", -- Technology
	[C_ID .. 69] = "{{Chargeable}} Chargeable tears#{{Damage}} Damage scales with charge time, up to 4x#{{Tears}} Max charge time is 2.5x tear delay", -- Chocolate Milk
	[C_ID .. 71] = "The tear height up and range down = slight range up", -- Mini Mush
	[C_ID .. 72] = "{{NameC33}} is added to all item pools", -- Rosary
	[C_ID .. 73] = "Lv1: Orbital#Lv2: Shooting orbital#Lv3: Meat Boy#Lv4: Super Meat Boy", -- Cube of Meatr
	[C_ID .. 75] = "{{Pill}} Changes bad pills into good pills#{{BloodDonationMachine}} Blood Donation Machines give more {{Coin}} coins", -- PHD
	[C_ID .. 76] = "{{SecretRoom}} Opens all secret room entrances", -- X-Ray Vision
	[C_ID .. 78] = "Using the item has a high chance to replace the floor's boss with a horseman", -- Book of Revelations
	[C_ID .. 81] = "Isaac respawns with 1 heart container on death#{{Warning}} Sets Isaac's heart containers to 1 when picked up", -- Dead Cat
	[C_ID .. 83] = "{VAR:ONUSEEFFECT}#{VAR:ROOMEFFECT}#{{IND}}Allows Isaac to destroy rocks by walking into them", -- The Nail
	[C_ID .. 84] = "Opens a trapdoor to the next floor#{{LadderRoom}} 10% chance to open a crawlspace trapdoor", -- We Need To Go Deeper!
	[C_ID .. 86] = "Monstro falls on an enemy and deals 120 damage#{{Warning}} Monstro falls on Isaac if the room has no enemies", -- Monstro's Tooth
	[C_ID .. 87] = "{VAR:LUCKCHANCE}% chance to shoot in 4 directions", -- Loki's Horns
	[C_ID .. 88] = "Charges forward in the direction Isaac is shooting", -- Little Chubby
	[C_ID .. 89] = "{{Slow}} {VAR:LUCKCHANCE}% chance to shoot slowing tears", -- Spider Bite
	[C_ID .. 91] = "Reveals the room type of adjacent rooms#{{SecretRoom}} Can reveal Secret and Super Secret Rooms",
	[C_ID .. 93] = "{VAR:TIMEDEFFECT}#{{IND}}{{HealingRed}} Killing 2 enemies heals half a heart#{{IND}}{{Fear}} Fears all enemies in the room", -- The Gamekid
	[C_ID .. 94] = "{{Coin}} Spawns a random coin every 2 rooms", -- Sack of Pennies
	[C_ID .. 95] = "Shoots lasers", -- Robo-Baby
	[C_ID .. 96] = "{{HalfHeart}} Spawns a half Red Heart every 3 rooms", -- Little C.H.A.D.
	[C_ID .. 98] = "{{SoulHeart}} Spawns 1 Soul Heart every {VAR:RANGE} rooms", -- The Relic
	[C_ID .. 99] = "{{Slow}} Shoots slowing tears", -- Little Gish
	[C_ID .. 100] = "Shoots homing tears", -- Little Steven

	[C_ID .. 103] = "{{Poison}} {VAR:LUCKCHANCE}% chance to shoot poison tears", -- The Common Cold
	[C_ID .. 104] = "Tears split in two on contact#Split tears deal half damage", -- The Parasite
	[C_ID .. 105] = "Rerolls pedestal items in the room", -- The D6
	[C_ID .. 107] = "{VAR:ROOMEFFECT}#{{IND}}Isaac's body separates from his head and attacks enemies with {VAR:1} contact damage per second", -- The Pinking Shears
	[C_ID .. 108] = "Reduces most damage taken to half a heart", -- The Wafer
	[C_ID .. 109] = "↑ {{Damage}} +0.04 Damage for every {{Coin}} coin Isaac has", -- Money = Power
	[C_ID .. 110] = "{{Petrify}} {VAR:LUCKCHANCE}% chance to shoot petrifying tears", -- Mom's Contacts
	[C_ID .. 111] = "{{Poison}} Deals 5 damage to enemies nearby and poisons them#The poison deals Isaac's damage 6 times", -- The Bean
	[C_ID .. 112] = "Speeds up all other orbitals", -- Guardian Angel
	[C_ID .. 113] = "Shoots enemies that get close to him", -- Demon Baby
	[C_ID .. 114] = "Isaac's tears are replaced by a throwable knife#{{Damage}} The knife deals 2x Isaac's damage while held and 6x at the furthest possible distance", -- Mom's Knife
	[C_ID .. 116] = "{{Battery}} Automatically charges the first bar of active items#{{Battery}} Fully recharges the active item on pickup", -- 9 Volt
	[C_ID .. 117] = "Taking damage spawns a bird that attacks enemies", -- Dead Bird
	[C_ID .. 118] = "{{Chargeable}} Isaac's tears are replaced by a chargeable blood beam#{{Damage}} It deals {VAR:1}x Isaac's damage over {VAR:2} seconds", -- Brimstone
	[C_ID .. 122] = "When on half a Red Heart or less:#{VAR:EFFECTLIST}", -- Whore of Babylon
	[C_ID .. 123] = "{{Timer}} Spawns a random familiar for the room", -- Monster Manual
	[C_ID .. 124] = "Triggers a random active item effect#Chooses the effect from a fixed list of items", -- Dead Sea Scrolls
	[C_ID .. 125] = "Homing bombs", -- Bobby-Bomb
	[C_ID .. 126] = "↑ {{Damage}} +1.2 Damage for the room#{{Warning}} Deals 1 heart of damage to Isaac#{{Heart}} Removes Red Hearts first", -- Razor Blade
	[C_ID .. 127] = "Rerolls and restarts the entire floor", -- Forget Me Now
	[C_ID .. 128] = "Long range fly orbital", -- Forever Alone
	[C_ID .. 130] = "While held:#{{Speed}} Sets your Speed to at least 1.5#Flight#Upon use, dashes in the direction of Isaac's movement", -- A Pony
	[C_ID .. 131] = "{{Bomb}} Spawns 1 bomb pickup every 3 rooms", -- Bomb Bag
	[C_ID .. 132] = "{{Damage}} Tears deal more damage the further they travel", -- A Lump of Coal
	[C_ID .. 133] = "{{SoulHeart}} Converts 1 heart container into 3 Soul Hearts", -- Guppy's Paw
	[C_ID .. 134] = "{{Chest}} 33% chance to replace the room clear reward with a chest#33% chance to spawn no room clear reward", -- Guppy's Tail
	[C_ID .. 135] = "{{Coin}} Hurts Isaac for half a heart and spawns 1-2 coins#{{Heart}} Removes Red Hearts first", -- IV Bag
	[C_ID .. 136] = "Spawns a decoy Isaac that attracts enemies and explodes after 5 seconds", -- Best Friend
	[C_ID .. 137] = "Isaac's bombs no longer explode automatically#Upon use, detonates all of Isaac's bombs at once", -- Remote Detonator
	[C_ID .. 139] = "{{Trinket}} Isaac can hold 2 trinkets", -- Mom's Purse
	[C_ID .. 140] = "{{Poison}} Isaac's bombs poison enemies caught in the blast", -- Bob's Curse
	[C_ID .. 142] = "{{SoulHeart}} Isaac gains 1 Soul Heart when damaged down to half a heart#Can only happen once per room#Exiting and re-entering the room allows the effect to trigger again", -- Scapular
	[C_ID .. 144] = "{{Coin}} Picks up nearby coins#Spawns random pickups every 3-4 coins", -- Bum Friend
	[C_ID .. 147] = "{{Timer}} For the room, Isaac can break rocks and Secret Room walls by walking into them", -- Notched Axe
	[C_ID .. 148] = "Taking damage spawns {VAR:RANGE} blue flies", -- Infestation
	[C_ID .. 149] = "Isaac's tears are shot in an arc#{{Poison}} The tears explode and poison enemies where they land", -- Ipecac
	[C_ID .. 150] = "{{Damage}} {VAR:LUCKCHANCE}% chance to shoot teeth that deal 3.2x Isaac's damage", -- Tough Love
	[C_ID .. 151] = "Tears have a 1/6 chance to spawn a blue fly when hitting an enemy", -- The Mulligan
	[C_ID .. 152] = "Replaces Isaac's right eye tears with a continuous laser#{{Damage}} It deals 3x Isaac's damage per second", -- Technology 2
	[C_ID .. 153] = "Isaac shoots 4 tears at once", -- Mutant Spider
	[C_ID .. 155] = "Floats around the room", -- The Peeper
	[C_ID .. 156] = "{{Battery}} Taking damage adds 1 charge to the active item", -- Habit
	[C_ID .. 157] = "↑ {{Damage}} Taking damage grants a damage up#Applies up to 6 times per floor#Lasts for the whole floor", -- Bloody Lust
	[C_ID .. 158] = "Spawns a {{SoulHeart}} Soul Heart, {{Rune}} rune or {{Card}} card#{VAR:EFFECTLIST}", -- Crystal Ball
	[C_ID .. 160] = "Spawns 5 beams of light near enemies#Each beam deals 8x Isaac's damage + 160 over 0.8 seconds", -- Crack the Sky
	[C_ID .. 161] = "{{Player4}} Respawn as ??? (Blue Baby) on death", -- Ankh
	[C_ID .. 162] = "Taking damage has a {VAR:LUCKCHANCE}% chance to make Isaac temporarily invincible", -- Celtic Cross
	[C_ID .. 163] = "Shoots spectral tears", -- Ghost Baby
	[C_ID .. 164] = "Throws a blue flame#It deals contact damage, blocks enemy tears, and despawns after 2 seconds", -- The Candle
	[C_ID .. 166] = "Rerolls all pickups in the room", -- D20
	[C_ID .. 167] = "Shoots two tears in a V-shaped pattern", -- Harlequin Baby
	[C_ID .. 168] = "Instead of shooting tears, aim a crosshair#A rocket lands on the crosshair after 1.5 seconds#{{Damage}} Rockets deal 20x Isaac's damage", -- Epic Fetus
	[C_ID .. 169] = "Tears pierce killed enemies if there is leftover damage", -- Polyphemus
	[C_ID .. 170] = "Stomps on a nearby enemy every 4 seconds", -- Daddy Longlegs
	[C_ID .. 171] = "{{Slow}} Slows down enemies for 4 seconds", -- Spider Butt
	[C_ID .. 173] = "{{SoulHeart}} {VAR:1}% chance that Red Hearts spawn as Soul Hearts instead", -- Mitre
	[C_ID .. 174] = "Shoots random tears", -- Rainbow Baby
	[C_ID .. 175] = "Opens all doors in the room, including {{SecretRoom}}{{SuperSecretRoom}}Secret Rooms, {{ChallengeRoom}}{{BossRushRoom}}Challenge Rooms, and the Mega Satan door", -- Dad's Key
	[C_ID .. 177] = "{{Coin}} Spend 1 coin for a chance to spawn a pickup", -- Portable Slot
	[C_ID .. 178] = "Taking damage spills a pool of creep#The creep deals 24 damage per second", -- Holy Water
	[C_ID .. 180] = "Isaac farts when damaged#{{Poison}} The fart poisons enemies", -- The Black Bean
	[C_ID .. 181] = "{{Speed}} Sets your Speed to at least 1.5#Flight while held#Using the item dashes in the direction of Isaac's movement, leaving behind beams of light", -- White Pony
	[C_ID .. 186] = "{{Warning}} Deals 1 heart of damage to Isaac#{{Heart}} Removes Red Hearts first", -- Blood Rights
	[C_ID .. 187] = "Moving swings the hairball around#The ball grows when it kills an enemy#It deals more damage the bigger it is", -- Guppy's Hairball
	[C_ID .. 188] = "Mirrors Isaac's movement#Shoots towards Isaac", -- Abel
	[C_ID .. 191] = "Isaac's tears get random effects every 2-3 seconds", -- 3 Dollar Bill
	[C_ID .. 198] = "Spawns 1 pickup of each type", -- Box
	[C_ID .. 199] = "Chests contain more pickups", -- Mom's Key
	[C_ID .. 200] = "{{Charm}} {VAR:LUCKCHANCE}% chance to shoot charming tears", -- Mom's Eyeshadow
	
	[C_ID .. 201] = "{{Confusion}} {VAR:LUCKCHANCE}% chance to shoot concussive tears", -- Iron Bar
	[C_ID .. 202] = "{{Petrify}} Touching enemies petrifies them and turns them gold#Isaac deals contact damage based on his coin count#{{Coin}} Killing a golden enemy spawns coins#Poop spawned by Isaac has a high chance to be golden poop", -- Midas' Touch
	[C_ID .. 203] = "Pickups spawned are doubled if possible", -- Humbleing Bundle
	[C_ID .. 204] = "Taking damage has a 50% chance to spawn a random pickup", -- Fanny Pack
	[C_ID .. 205] = "{{Battery}} Using an uncharged active item fully recharges it at the cost of 2 hearts#Only works when the item has no charges", -- Sharp Plug
	[C_ID .. 206] = "Isaac's head becomes an orbital that shoots, doesn't take damage and deals {VAR:1} contact damage per second", -- Guillotine
	[C_ID .. 207] = "Lv1: Orbital#{{Charm}} Lv2: Orbital that shoots charmed tears#{{Charm}} Lv3: Bandage Girl#{{Charm}} Lv4: Super Bandage Girl", -- Ball of Bandages
	[C_ID .. 208] = "Champion enemy chance goes from 5% to 20%#Doesn't increase chance of champion bosses", -- Champion Belt
	[C_ID .. 209] = "{{Confusion}} Explosions concuss and damage every enemy in the room", -- Butt Bombs
	[C_ID .. 210] = "After 1 second of inactivity, Isaac becomes invincible", -- Gnawed Leaf
	[C_ID .. 211] = "Taking damage spawns {VAR:RANGE} blue spiders", -- Spiderbaby
	[C_ID .. 212] = "50% chance to revive with half a heart on death", -- Guppy's Collar
	[C_ID .. 213] = "Isaac's tears destroy enemy shots", -- Lost Contact
	[C_ID .. 214] = "{{Timer}} When taking damage Isaac leaves a trail of blood creep for the room#The creep deals 6 damage per second", -- Anemic
	[C_ID .. 217] = "{VAR:LUCKCHANCE}% chance to spawn a blue spider when shooting tears", -- Mom's Wig
	[C_ID .. 218] = "{{HealingRed}} 50% chance to heal half a heart every minute", -- Placenta
	[C_ID .. 219] = "{{Heart}} Taking damage has a {VAR:1}% chance to spawn a Red Heart", -- Old Bandage
	[C_ID .. 220] = "Isaac's bombs shoot 10 tears in a circle when they explode", -- Sad Bombs
	[C_ID .. 221] = "Isaac's tears bounce off enemies and obstacles", -- Rubber Cement
	[C_ID .. 222] = "Holding the fire buttons causes tears to hover in midair#Releasing the fire buttons shoots them in the direction they were fired", -- Anti-Gravity
	[C_ID .. 223] = "Immunity to explosions, rock waves, and stomp attacks#{{HealingRed}} Getting hit by explosions heals 1 heart", -- Pyromaniac
	[C_ID .. 224] = "Tears split up in 4 on hit#Split tears deal half damage", -- Cricket's Body
	[C_ID .. 225] = "{{SoulHeart}} Taking damage has a chance to spawn a Soul Heart#{{HalfHeart}} Enemies have a chance to drop a half Red Heart on death", -- Gimpy
	[C_ID .. 227] = "{{Coin}} Taking damage spawns 1-2 coins", -- Piggy Bank
	[C_ID .. 228] = "{{Fear}} 15% chance to shoot fear tears", -- Mom's Perfume
	[C_ID .. 229] = "{{Chargeable}} Tears are charged and released in a shotgun style attack", -- Monstro's Lung
	[C_ID .. 230] = "↓ {{EmptyHeart}} Removes all heart containers#{{Fear}} 15% chance to shoot fear tears", -- Abaddon
	[C_ID .. 231] = "{{Slow}} {VAR:LUCKCHANCE}% chance to shoot slowing tears#{{Slow}} Isaac leaves a trail of slowing creep", -- Ball of Tar
	[C_ID .. 232] = "{{Slow}} Taking damage slows all enemies in the room permanently", -- Stop Watch
	[C_ID .. 233] = "Isaac's tears orbit around him", -- Tiny Planet
	[C_ID .. 234] = "Killing an enemy spawns a blue spider", -- Infestation 2
	[C_ID .. 236] = "Touching an enemy turns it into poop", -- E. Coli
	[C_ID .. 238] = "{{Warning}} Getting both parts of the key opens a big golden door#{{EternalHeart}} +2% chance for Eternal Hearts", -- Key Piece 1
	[C_ID .. 239] = "{{Warning}} Getting both parts of the key opens a big golden door#{{EternalHeart}} +2% chance for Eternal Hearts", -- Key Piece 2
	[C_ID .. 241] = "Doubles all room clear rewards#33% chance for no room clear reward", -- Contract from Below
	[C_ID .. 242] = "50% chance to block enemy shots", -- Infamy
	[C_ID .. 243] = "Blocks enemy shots coming from the direction Isaac is shooting", -- Trinity Shield
	[C_ID .. 244] = "Occasionally shoot lasers in addition to Isaac's tears", -- Tech.5
	[C_ID .. 245] = "Isaac shoots 2 tears at once", -- 20/20
	[C_ID .. 246] = "{{SecretRoom}} Reveals secret room locations on the map", -- Blue Map
	[C_ID .. 247] = "Familiars deal double damage", -- BFFS!
	[C_ID .. 248] = "Blue spiders and flies deal double damage", -- Hive Mind
	[C_ID .. 249] = "Allows Isaac to choose between 2 items after beating a boss", -- There's Options
	[C_ID .. 250] = "{{Bomb}} All bomb drops become double bombs", -- Bogo Bombs
	[C_ID .. 251] = "Isaac can carry 2 cards#Turns all pills into cards", -- Starter Deck
	[C_ID .. 252] = "Isaac can carry 2 pills#Turns all cards into pills", -- Little Baggy
	[C_ID .. 256] = "{{Burning}} Isaac's bombs leave a flame where they explode", -- Hot Bombs
	[C_ID .. 257] = "{{Burning}} Isaac's tears light enemies on fire#{VAR:LUCKCHANCE}% chance for tears to explode on enemy impact#{{Warning}} The explosion can hurt Isaac", -- Fire Mind
	[C_ID .. 258] = "Rerolls all of Isaac's items and stats on pickup and at every new floor", -- Missing No.
	[C_ID .. 259] = "{{Fear}} {VAR:LUCKCHANCE}% chance to shoot fear tears", -- Dark Matter
	[C_ID .. 260] = "{{CurseBlind}} Immune to curses", -- Black Candle
	[C_ID .. 261] = "↓ Tears deal less damage the further they travel", -- Proptosis
	[C_ID .. 262] = "Taking damage down to 1 heart damages all enemies in the room", -- Missing Page 2
	[C_ID .. 264] = "Attacks enemies when Isaac takes damage", -- Smart Fly
	[C_ID .. 265] = "10% chance to damage all enemies in the room when it is hit by an enemy tear", -- Dry Baby
	[C_ID .. 266] = "{{Slow}} Leaves slowing creep#Spawns 1-2 friendly spiders after clearing a room", -- Juicy Sack
	[C_ID .. 267] = "Shoots lasers#Moves in the direction Isaac is shooting", -- Robo-Baby 2.0
	[C_ID .. 268] = "Spawns blue flies when Isaac shoots", -- Rotten Baby
	[C_ID .. 269] = "Leaves creep which deals 6 damage per second", -- Headless Baby
	[C_ID .. 270] = "Chases enemies#{{HealingRed}} Heals Isaac for half a heart when it kills an enemy", -- Leech
	[C_ID .. 271] = "Spawns a random pickup every 5-6 rooms", -- Mystery Sack
	[C_ID .. 272] = "Friendly exploding fly#The explosion deals {VAR:1} damage#{{Warning}} The explosion can hurt Isaac", -- BBF
	[C_ID .. 273] = "Dashes in the direction Isaac is shooting#Explodes when it hits an enemy#{{Poison}} The explosion deals {VAR:1} damage and poisons enemies#{{Warning}} The explosion can hurt Isaac", -- Bob's Brain
	[C_ID .. 274] = "Taking damage spawns one midrange orbital for the room", -- Best Bud
	[C_ID .. 275] = "{{Chargeable}} Familiar that charges and shoots a {{Collectible118}} blood beam#It deals {VAR:1} damage over 0.63 seconds", -- Lil Brimstone
	[C_ID .. 276] = "Isaac becomes invincible#Spawns a heart familiar that follows Isaac#{{Warning}} If the heart familiar gets hit, Isaac takes damage", -- Isaac's Heart
	[C_ID .. 277] = "{{Fear}} Chases and fears enemies", -- Lil Haunt
	[C_ID .. 278] = "{{Heart}} Picks up nearby Red Hearts#{{SoulHeart}} Spawns a Soul Heart or spider for every 1.5 Red Hearts picked up", -- Dark Bum
	[C_ID .. 279] = "Large orbital", -- Big Fan
	[C_ID .. 280] = "Randomly spawns blue spiders in hostile rooms", -- Sissy Longlegs
	[C_ID .. 281] = "Decoy familiar#Enemies target him instead of Isaac", -- Punching Bag
	[C_ID .. 282] = "Allows Isaac to jump over gaps and obstacles", -- How to Jump
	[C_ID .. 283] = "Reroll all pickups and pedestal items in the room, and all of Isaac's passive items", -- D100
	[C_ID .. 284] = "Reroll all of Isaac's passive items", -- D4
	[C_ID .. 285] = "Reroll all enemies in the room", -- D10
	[C_ID .. 286] = "Triggers the effect of the rune or card Isaac holds without using it", -- Blank Card
	[C_ID .. 287] = "{{Timer}} Grants one of these effects for the floor:#{{NameC54}}#{{NameC1}}#{{NameC246}}", -- Book of Secrets
	[C_ID .. 289] = "Throws a red flame#It deals contact damage, blocks enemy tears, and disappears when it has dealt damage or blocked shots 5 times", -- Red Candle
	[C_ID .. 290] = "{{Heart}} Picking up Red Hearts while at full health stores up to 4 of them in the Jar#Using the item drops all stored hearts on the floor", -- The Jar
	[C_ID .. 291] = "Turns all non-boss enemies into poop#Instantly kills poop enemies and bosses", -- Flush!
	[C_ID .. 293] = "{{Collectible118}} Shoot a 4-way blood beam#They each deal {VAR:1} damage over 1.33 seconds", -- Head of Krampus
	[C_ID .. 294] = "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger {{NameC484}} when swapping it with a different active item and picking it up again", -- Butter Bean
	[C_ID .. 295] = "Deals 2x Isaac's damage to all enemies#{{Coin}} Costs 1 coin", -- Magic Fingers
	[C_ID .. 296] = "{{Heart}} Converts 2 Soul/Black Hearts into 1 heart container", -- Converter
	[C_ID .. 297] = "{{NoLB}}Spawns rewards based on floor:#B1: 2{{SoulHeart}}; B2: 2{{Bomb}} + 2{{Key}}#{{NoLB}}C1: Boss item; C2: C1 + 2{{SoulHeart}}#D1: 4{{SoulHeart}}; D2: 20{{Coin}}#W1: 2 Boss items#W2: {{NameC33}}#???/Void: Nothing#Sheol: Devil item + 1{{BlackHeart}}#Cathe: Angel item + 1{{EternalHeart}}#{{NoLB}}Dark Room: Unlocks {{NameC523}}#Chest: 1{{Coin}}", -- Pandora's Box
	[C_ID .. 299] = "↑ {{Speed}} Slowly gain speed while in hostile rooms#At 2 speed, Isaac becomes invincible and deals contact damage#Afterwards, lose the Taurus speed boost for the room", -- Taurus

	[C_ID .. 300] = "Touching enemies deals contact damage", -- Aries
	[C_ID .. 301] = "Taking damage reduces all future damage in the room to half a heart", -- Cancer
	[C_ID .. 302] = "Isaac can destroy rocks by walking into them", -- Leo
	[C_ID .. 303] = "Taking damage can make Isaac temporarily invincible#{{Luck}} 100% chance at 10 luck#{{Pill}} Converts negative pills into positive ones", -- Virgo
	[C_ID .. 304] = "Balances Isaac's stats#Future stat changes will be spread across all stats", -- Libra
	[C_ID .. 308] = "Isaac leaves a trail of creep#The creep deals 6 damage per second", -- Aquarius
	[C_ID .. 309] = "Increases tear knockback", -- Pisces
	[C_ID .. 311] = "{{Player12}} When dead, respawn as Dark Judas with a x2 damage multiplier", -- Judas' Shadow
	[C_ID .. 312] = "All Red Hearts heal double their value", -- Maggy's Bow
	[C_ID .. 313] = "Negates the first hit taken once per room", -- Holy Mantle
	[C_ID .. 314] = "Isaac can destroy rocks by walking into them", -- Thunder Thighs
	[C_ID .. 315] = "Isaac's tears attract enemies, pickups and trinkets", -- Strange Attractor
	[C_ID .. 316] = "Charged wave of {VAR:1} tears#{{Warning}} Taking damage while partially charged teleports Isaac to a random room", -- Cursed Eye
	[C_ID .. 317] = "Isaac's tears leave creep#The creep deals 30 damage per second", -- Mysterious Liquid
	[C_ID .. 318] = "Close combat familiar", -- Gemini
	[C_ID .. 319] = "Bounces around the room#Low accuracy tears that deal Isaac's damage", -- Cain's Other Eye
	[C_ID .. 320] = "Controllable fly", -- ???'s Only Friend
	[C_ID .. 321] = "Draggable ball that can destroy rocks", -- Samson's Chains
	[C_ID .. 322] = "Mimics your baby familiars' tears#If you have none, shoots normal 3.5 damage tears", -- Mongo Baby
	[C_ID .. 323] = "Shoots 8 tears in all directions#The tears copy Isaac's tear effects#Recharges by shooting tears", -- Isaac's Tears
	[C_ID .. 324] = "Teleports Isaac to the {{TreasureRoom}} Treasure, {{SecretRoom}} Secret, {{SuperSecretRoom}} Super Secret or {{ErrorRoom}} I AM ERROR Room", -- Undefined
	[C_ID .. 325] = "{{Timer}} Isaac's head turns into a stationary familiar for the room#The head shoots 3.5 damage tears#The body is controlled separately and still shoots Isaac's tears", -- Scissors
	[C_ID .. 326] = "Holding down the USE button empties the charge bar#Isaac is temporarily invincible when the charge bar is empty#{{Warning}} Holding it for too long deals damage to Isaac", -- Breath of Life
	[C_ID .. 327] = "Taking damage at half a Red Heart or none makes Isaac temporarily invincible", -- The Polaroid
	[C_ID .. 328] = "Taking damage at half a Red Heart or none damages all enemies in the room", -- The Negative
	[C_ID .. 329] = "Replaces Isaac's tears with one giant controllable tear", -- The Ludovico Technique
	[C_ID .. 331] = "{{Damage}} Tears gain an aura that deals 4.5x Isaac's damage per second", -- Godhead
	[C_ID .. 332] = "{{Player11}} When dead, revive as Lazarus (Risen)", -- Lazarus' Rags
	[C_ID .. 333] = "Full mapping effect", -- The Mind
	[C_ID .. 335] = "Grants an aura that repels enemies and projectiles", -- The Soul
	[C_ID .. 337] = "{{Slow}} Slows down every 4th room#13% chance to speed up the room instead", -- Broken Watch
	[C_ID .. 338] = "Throwable boomerang#{{Petrify}} Petrifies enemies and deals 2x Isaac's damage#Can grab and bring back items", -- The Boomerang
	[C_ID .. 347] = "Duplicates all item pedestals and pickups in the room", -- Diplopia
	[C_ID .. 348] = "{{Pill}} Triggers the effect of the pill Isaac holds without using it", -- Placebo
	[C_ID .. 349] = "{{Coin}} {VAR:1}% chance to spawn a random coin", -- Wooden Nickel
	[C_ID .. 350] = "{{Poison}} Entering a room poisons all enemies#Enemies killed leave a puddle of creep#The creep deals 30 damage per second", -- Toxic Shock
	[C_ID .. 351] = "{{Petrify}} Petrifies all enemies in the room#{{Poison}} Deals 5 damage and poisons any enemies nearby#Sends a rock wave in the direction Isaac is moving#The rock wave can open secret rooms and break rocks", -- Mega Bean
	[C_ID .. 352] = "{{Warning}} Firing the cannon reduces Isaac's health down to half a heart#Shoots a large piercing + spectral tear that does 10x Isaac's damage", -- Glass Cannon
	[C_ID .. 353] = "Bombs explode in a cross-shaped pattern", -- Bomber Boy
	[C_ID .. 356] = "{{Battery}} Using an active item triggers its effect twice", -- Car Battery
	[C_ID .. 357] = "{{Timer}} Duplicates all your familiars for the room#{{Collectible113}} Grants a Demon Baby for the room if Isaac has no familiars", -- Box of Friends
	[C_ID .. 358] = "Isaac shoots 2 tears at once diagonally", -- The Wiz
	[C_ID .. 359] = "Increases knockback", -- 8 Inch Nails
	[C_ID .. 360] = "Shoots tears with the same tear rate, damage and effects as Isaac", -- Incubus
	[C_ID .. 361] = "Shoots tears with the same damage and effects as Isaac#Shoots at half the rate of other familiars", -- Fate's Reward
	[C_ID .. 362] = "35% chance to spawn a pickup every room", -- Lil Chest
	[C_ID .. 363] = "Blocks and attracts enemy shots#{{EternalHeart}} Blocking 10 shots in one room spawns an Eternal Heart", -- Sworn Protector
	[C_ID .. 364] = "Midrange fly orbital", -- Friend Zone
	[C_ID .. 365] = "Moves along walls/obstacles", -- Lost Fly
	[C_ID .. 366] = "Isaac's bombs scatter into {VAR:RANGE} tiny bombs", -- Scatter Bombs
	[C_ID .. 367] = "Isaac's bombs stick to enemies#Killing an enemy with a bomb spawns blue spiders", -- Sticky Bombs
	[C_ID .. 368] = "↑ {{Tears}} Shooting in one direction gradually decreases tear delay up to 200% and decreases accuracy", -- Epiphora
	[C_ID .. 369] = "Tears can travel through one side of the screen and come out the other side", -- Continuum
	[C_ID .. 371] = "{{Warning}} Taking damage spawns 6 Troll Bombs#The Troll Bombs inherit Isaac's bomb effects", -- Curse of the Tower
	[C_ID .. 372] = "Every 30 seconds while in an uncleared room, the familiar can:#{{Battery}} Spawn a Battery (max 2 per room)#{{Battery}} Add one charge to the active item (max 2 per room)#{{Petrify}} Petrify all enemies in the room", -- Charged Baby
	[C_ID .. 373] = "↑ {{Damage}} Consecutive tear hits on enemies grant +25% damage (max +100%)#Missing has a chance to reset the multiplier", -- Dead Eye
	[C_ID .. 374] = "{VAR:LUCKCHANCE}% chance to shoot holy tears, which spawn a beam of light on hit#{{Damage}} The beam deals 4x Isaac's damage", -- Holy Light
	[C_ID .. 375] = "Grants immunity to explosions, rock wave attacks and Mom and Satan's stomp attacks#25% chance to reflect enemy shots", -- Host Hat
	[C_ID .. 376] = "Buying an item from a Shop restocks it instantly", -- Restock
	[C_ID .. 377] = "Spider enemies no longer target or deal contact damage to Isaac", -- Bursting Sack
	[C_ID .. 378] = "Holding a fire button for 2.35 seconds spawns a lit Butt Bomb", -- No. 2
	[C_ID .. 380] = "{{Coin}} Single-key doors must be opened with coins instead of keys", -- Pay To Play
	[C_ID .. 381] = "Grants a random item at the start of the next run", -- Eden's Blessing
	[C_ID .. 382] = "Can be thrown at enemies to capture them#{{Friendly}} Using the item after capturing an enemy spawns it as a friendly companion", -- Friendly Ball
	[C_ID .. 383] = "Splits all of Isaac's tears currently on screen in a circle of 6 tears", -- Tear Detonator
	[C_ID .. 384] = "{{Chargeable}} Launches and bounces around the room with speed based on charge amount#Deals 5-90 contact damage per second depending on speed", -- Lil Gurdy
	[C_ID .. 385] = "{{Coin}} Picks up nearby coins#Levels up after getting 6, 12, and 24 coins#Lv2: Chance to spawn item after room clears#Lv3: Shoots tears that can spawn coins on hit#Lv4: Chases enemies, occasionally dropping bombs, can spawn item on coin pickup", -- Bumbo
	[C_ID .. 386] = "Rerolls any obstacle into another random obstacle (e.g. poop, pots, TNT, red poop, stone blocks etc.)", -- D12
	[C_ID .. 387] = "{{Slow}} Familiar surrounded by a huge aura of light that slows down enemies and projectiles in it", -- Censer
	[C_ID .. 388] = "{{Key}} Picks up nearby keys#{{Chest}} Spawns random chests in return", -- Key Bum
	[C_ID .. 389] = "{{Rune}} Spawns a random rune every 5-6 rooms", -- Rune Bag
	[C_ID .. 390] = "Shoots Sacred Heart tears", -- Seraphim
	[C_ID .. 391] = "{{Charm}} Taking damage charms all enemies in the room", -- Betrayal
	[C_ID .. 392] = "Grants a random zodiac item effect every floor", -- Zodiac
	[C_ID .. 393] = "{{Poison}} 15% chance to shoot poison tears#{{Poison}} Poison enemies on contact#{{BlackHeart}} Poisoned enemies have a chance to drop a Black Heart on death", -- Serpent's Kiss
	[C_ID .. 394] = "Isaac automatically shoots tears at a movable red target on the ground", -- Marked
	[C_ID .. 395] = "{{Chargeable}} Isaac's tears are replaced by a chargeable laser ring#Ring size increases with charge amount", -- Tech X
	[C_ID .. 396] = "Creates up to two portals to travel between#Can be placed in different rooms", -- Ventricle Razor
	[C_ID .. 397] = "Isaac's tears always travel along a beam of light in front of him", -- Tractor Beam
	[C_ID .. 398] = "{{Shrink}} Tears can shrink enemies#Shrunken enemies can be crushed and killed by walking over them", -- God's Flesh
	[C_ID .. 399] = "{{Chargeable}} Shooting tears for 2.35 seconds and releasing the fire button creates a black brimstone ring around Isaac#It deals 30x Isaac's damage over 2 seconds#{{BlackHeart}} Enemies killed by the black ring have a 5% chance to drop a Black Heart", -- Maw of the Void

	[C_ID .. 400] = "Isaac holds a spear in front of him#{{Fear}} The spear deals twice his damage and can fear enemies on contact", -- Spear of Destiny
	[C_ID .. 401] = "25% chance to shoot sticky bomb tears#Sticky bomb tears do not deal damage on hit and explode after a few seconds", -- Explosivo
	[C_ID .. 402] = "All items are chosen from random item pools", -- Chaos
	[C_ID .. 403] = "Displays tear damage and health bars of all enemies#Inflicts random status effects to enemies on contact#Randomly spawns batteries", -- Spider Mod
	[C_ID .. 404] = "When hit, 10% chance to fart and {{Charm}} charm, {{Poison}} poison or knockback enemies", -- Farting Baby
	[C_ID .. 405] = "Bounces around the room#Applies random status effects to enemies on contact", -- GB Bug
	[C_ID .. 406] = "Multiplies Isaac's damage, tears, range and speed stats by between x0.5 and x2#The multipliers are rerolled each use", -- D8
	[C_ID .. 407] = "↑ Boosts one of Isaac's stats depending on the color of the aura#Taking damage removes the effect, and gives Isaac a new effect in the next room#{{ColorYellow}}Yellow{{CR}} = ↑ {{Speed}} +0.5 Speed#{{ColorBlue}}Blue{{CR}} = ↑ {{Tears}} -4 Tear delay#{{ColorRed}}Red{{CR}} = ↑ {{Damage}} +4 Damage#{{ColorOrange}}Orange{{CR}} = ↑ {{Range}} +7.5 Range, ↑ +1 Tear height", -- Purity
	[C_ID .. 408] = "Taking damage creates a black brimstone ring around Isaac#It deals 30x Isaac's damage over 2 seconds#{{BlackHeart}} Enemies killed by the ring have a 15% chance to drop a Black Heart", -- Athame
	[C_ID .. 409] = "{{EmptyHeart}} When Isaac has no Red Hearts:#Flight#Every 40 seconds while in a hostile room, gain a shield for 10 seconds", -- Empty Vessel
	[C_ID .. 410] = "{VAR:LUCKCHANCE}% chance to shoot an eye#The eye moves in a straight line and shoots tears in the same direction as Isaac", -- Evil Eye
	[C_ID .. 411] = "↑ {{Damage}} +0.5 Damage for each enemy killed in the room#Caps at +5 Damage after 10 kills", -- Lusty Blood
	[C_ID .. 412] = "Taking damage 15 times spawns a permanent demon familiar#After two familiars, it takes 30 instead of 15#Caps at 4 familiars", -- Cambion Conception
	[C_ID .. 413] = "Picking up 15 hearts spawns a permanent angelic familiar#Caps at 5 familiars#{{SoulHeart}} If all familiars have been granted, spawns a Soul Heart instead", -- Immaculate Conception
	[C_ID .. 414] = "{{TreasureRoom}} Allows Isaac to choose between 2 items in treasure rooms", -- More Options
	[C_ID .. 415] = "If Isaac has no damaged heart containers:#{VAR:EFFECTLIST}#Taking any damage removes the effect for the room", -- Crown Of Light
	[C_ID .. 416] = "Allows Isaac to carry two runes/cards/pills", -- Deep Pockets
	[C_ID .. 417] = "Bounces around the room surrounded by a damaging aura that deals 1.29x Isaac's damage per second#↑ {{Damage}} x1.5 Damage multiplier while standing in the aura", -- Succubus
	[C_ID .. 418] = "Each one of Isaac's tears gets a different effect", -- Fruit Cake
	[C_ID .. 419] = "Teleports Isaac to a room that has not been cleared yet#Hierarchy: {VAR:TEXT}", -- Teleport 2.0
	[C_ID .. 420] = "Walking in a circle draws a pentagram on the floor, which deals 130 damage over 4 seconds", -- Black Powder
	[C_ID .. 421] = "{{Charm}} Charms and deals 5 damage to all enemies in close range", -- Kidney Bean
	[C_ID .. 422] = "Brings Isaac back to the previous room and reverses all actions done in the room the item was used in", -- Glowing Hour Glass
	[C_ID .. 423] = "Surrounds Isaac with a large halo that deals his damage on contact per second#Chance to reflect enemy projectiles", -- Circle of Protection
	[C_ID .. 424] = "Pickups have a chance to be replaced with a {{GrabBag}}sack:#{{Coin}}: 10%, {{Bomb}}{{Key}}{{Pill}}{{Rune}}{{Battery}}: 20%#{{GrabBag}} Spawns a sack", -- Sack Head
	[C_ID .. 425] = "{{Slow}} Spawns a slowing cone of light in front of Isaac", -- Night Light
	[C_ID .. 427] = "Spawns a pushable TNT barrel#Using the item a second time in the same room remotely detonates the barrel", -- Mine Crafterr
	[C_ID .. 429] = "{{Coin}} Hitting an enemy with a tear has a 5% chance to spawn a Penny", -- Head of the Keeper
	[C_ID .. 430] = "{{Damage}} Shoots tears at nearby enemies that deal Isaac's damage", -- Papa Fly
	[C_ID .. 431] = "Tears that pass through it are doubled and gain a range + shot speed boost", -- Multidimensional Baby
	[C_ID .. 432] = "{{Charm}} Isaac's bombs have a 25% chance to drop a random pickup and a 15% chance to charm enemies when they explode", -- Glitter Bombs
	[C_ID .. 433] = "{{Fear}} Taking damage fears all enemies in the room and spawns a friendly black charger", -- My Shadow
	[C_ID .. 434] = "Killing an enemy adds a blue fly to the jar, up to 20 flies#Using the item releases all the flies", -- Jar of Flies
	[C_ID .. 435] = "Shoots 4 tears in a cross pattern", -- Lil Loki
	[C_ID .. 436] = "{{Tears}} Taking damage grants a Tears up for the duration of the room", -- Milk!
	[C_ID .. 437] = "Restarts a room and respawns all enemies#Can be used to get multiple room clear rewards from a single room#If used after a Greed fight, rerolls the room into a normal Shop/Secret Room", -- D7
	[C_ID .. 439] = "{{Trinket}} Doubles trinket effects", -- Mom's Box
	[C_ID .. 440] = "Isaac occasionally stops firing and charges an attack that releases a burst of tears and a kidney stone", -- Kidney Stone
	[C_ID .. 441] = "{{Timer}} Fires a huge Mega Satan blood beam for 15 seconds#The beam persists between rooms and floors", -- Mega Blast
	[C_ID .. 442] = "While at 1 full Red Heart:#{VAR:EFFECTLIST}", -- Dark Prince's Crown
	[C_ID .. 443] = "{{Damage}} {VAR:LUCKCHANCE}% chance to shoot razor blades that deal 4x Isaac's damage", -- Apple!
	[C_ID .. 444] = "Isaac shoots a cluster of tears every 15 tears#Tears in the cluster deal double damage", -- Lead Pencil
	[C_ID .. 445] = "{{SecretRoom}}{{SuperSecretRoom}} A wolf howls in rooms adjacent to a Secret/Super Secret Room#{{LadderRoom}} A dog barks in rooms with a crawlspace under a rock", -- Dog Toothh
	[C_ID .. 446] = "{{Poison}} While firing, Isaac is surrounded by a green aura that poisons enemies", -- Dead Tooth
	[C_ID .. 447] = "Firing without pause for 7.5 seconds spawns a poop cloud#The cloud deals Isaac's damage 5 times a second#The cloud lasts 15 seconds and can be moved by shooting it", -- Linger Bean
	[C_ID .. 448] = "Upon taking damage:#{{Heart}} 25% chance to spawn a Red Heart#{{Collectible214}} 10% chance to get ↑ {{Range}} +5 Range and leave a trail of blood creep for the room", -- Shard of Glass
	[C_ID .. 449] = "{{Confusion}} Enemy bullets have a 25% chance to be reflected as concussive tears", -- Metal Plate
	[C_ID .. 450] = "Every 20 tears, Isaac shoots a coin tear that deals double damage#{{Petrify}} Enemies hit with the coin get petrified and turn into gold#{{Coin}} Killing a gold enemy drops 1-4 coins#{{Warning}} Firing a coin tear costs 1 coin", -- Eye of Greed
	[C_ID .. 451] = "{{Card}} Card effects are doubled or enhanced", -- Tarot Cloth
	[C_ID .. 452] = "Taking damage shoots 10 tears in a circle around Isaac#The tears deal Isaac's damage + 25", -- Varicose Veins
	[C_ID .. 453] = "Tears shatter into 1-3 small bone shards upon hitting anything", -- Compound Fracture
	[C_ID .. 454] = "Spawns a {{Rune}} rune, {{Card}} card or {{Pill}} pill on pickup#Allows Isaac to carry 2 runes/cards/pills", -- Polydactyly
	[C_ID .. 455] = "{{Luck}} Spawns a Lucky Penny", -- Dad's Lost Coin
	[C_ID .. 457] = "20% chance to negate damage taken", -- Cone Head
	[C_ID .. 458] = "{{Trinket}} Allows Isaac to carry 2 trinkets", -- Belly Button
	[C_ID .. 459] = "20% chance to shoot a sticky booger#{{Damage}} Boogers deal Isaac's damage once a second and stick for {VAR:1} seconds#{{Luck}} Not affected by luck", -- Sinus Infection
	[C_ID .. 460] = "{{Confusion}} 5% chance to shoot concussive tears#Makes the screen slightly darker", -- Glaucoma
	[C_ID .. 461] = "{VAR:LUCKCHANCE}% chance to shoot egg sacks#{{Slow}} Egg sacks spawn slowing creep and a blue spider or fly on hit", -- Parasitoid
	[C_ID .. 462] = "Hitting an enemy makes the tear homing and doubles its damage", -- Eye of Belial
	[C_ID .. 463] = "Isaac's tears can destroy rocks and open doors", -- Sulfuric Acid
	[C_ID .. 464] = "Champion enemies drop whatever pickup Isaac needs the most", -- Glyph of Balance
	[C_ID .. 465] = "Allows Isaac to shoot tears in any direction", -- Analog Stick
	[C_ID .. 466] = "{{Poison}} The first enemy killed in a room explodes and poisons all nearby enemies#Enemies that die while poisoned also explode and poison nearby enemies", -- Contagion
	[C_ID .. 467] = "{{Damage}} Constantly deals 10% of Isaac's damage in the direction it points", -- Finger!
	[C_ID .. 468] = "{{Friendly}} After it deals {VAR:1} damage, it is absorbed by Isaac, increasing his contact damage and spawning friendly Chargers", -- Shade
	[C_ID .. 469] = "Leaves a trail of creep#The creep deals 6 damage per second#Enemies that touch the cloud can be hit by a holy light beam", -- Depression
	[C_ID .. 470] = "Bounces around the room#Stops moving when Isaac shoots#Blocks projectiles when stopped", -- Hushy
	[C_ID .. 471] = "{{Chargeable}} Charges a shotgun attack similar to {{NameC229}}#Each tear deals 3.5 damage", -- Lil Monstro
	[C_ID .. 472] = "Other familiars follow it#Stops moving when Isaac shoots#Teleports back to Isaac when he stops shooting", -- King Baby
	[C_ID .. 473] = "Very slowly charges forwards", -- Big Chubby
	[C_ID .. 475] = "{{Warning}} Kills Isaac 3 seconds later", -- Plan C
	[C_ID .. 476] = "Duplicates a random pickup in the room", -- D1
	[C_ID .. 477] = "Consumes all pedestal items in the room#Active items: Their effects activate, and will activate with every future use of Void#↑ Passive items grant two random stat ups", -- Void
	[C_ID .. 478] = "Pauses all enemies in the room until Isaac shoots#Touching a paused enemy still deals damage to Isaac#Enemies unpause after 30 seconds", -- Pause
	[C_ID .. 479] = "{{Trinket}} Consumes Isaac's held trinkets and grants their effects permanently#Increases the spawn rate of trinkets", -- Smelter
	[C_ID .. 480] = "Converts pickups into blue flies or spiders#Doubles all blue flies and spiders#Spawns 1 blue fly or spider if Isaac has none", -- Compost
	[C_ID .. 481] = "{{Timer}} Random tear effects for the room#{{Blank}} Corrupts all sprites and music in the room", -- Dataminer
	[C_ID .. 482] = "Changes your character to a random character#Removes the most recent item collected", -- Clicker
	[C_ID .. 483] = "Affects the whole floor#Explodes all objects#{VAR:EFFECTLIST}#Opens secret rooms#Opens Boss Rush and Hush regardless of time", -- Mama Mega!
	[C_ID .. 484] = "Upon use, pushes enemies away and spawns a rock wave around Isaac#The rock wave can open rooms and break rocks", -- Wait What?
	[C_ID .. 485] = "50% chance to double all items, pickups and chests in room#50% chance to remove items / pickups in room and spawn 1 coin", -- Crooked Penny
	[C_ID .. 486] = "Hurts Isaac without removing health#Triggers any on-hit item effects", -- Dull Razor
	[C_ID .. 487] = "{{EmptyHeart}} Removes 1 heart container for:#{VAR:EFFECTLIST}#{{IND}}{{NameC73}}#{VAR:ROOMEFFECT}#{{IND}}{{Collectible214}} Leave a trail of blood creep", -- Potato Peeler
	[C_ID .. 488] = "Grants a random item effect for the room", -- Metronome
	[C_ID .. 489] = "Triggers a random dice effect each use", -- D Infinity
	[C_ID .. 490] = "Spawns 2 random items depending on the current room's item pool#Starts with no charges", -- Eden's Soul
	[C_ID .. 491] = "{{Pill}} Spawns a random pill every {VAR:1} rooms#{{Poison}} Using a pill poisons all enemies in the room", -- Acid Baby
	[C_ID .. 492] = "Highlights the location of {{SecretRoom}} secret rooms, tinted rocks and {{LadderRoom}} crawlspaces", -- YO LISTEN!
	[C_ID .. 493] = "For every empty heart container:#{VAR:EFFECTLIST}", -- Adrenaline
	[C_ID .. 494] = "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half of Isaac's damage", -- Jacob's Ladder
	[C_ID .. 495] = "Chance to shoot a red flame that blocks enemy shots and deals contact damage#The flame disappears after dealing damage or blocking shots 5 times", -- Ghost Pepper
	[C_ID .. 496] = "{VAR:LUCKCHANCE}% chance to shoot a needle#Needles kill normal enemies instantly, bursting them into 10 tears#{{Damage}} Needles deal 3x Isaac's damage against bosses", -- Euthanasia
	[C_ID .. 497] = "{{Confusion}} Entering a room confuses all enemies until Isaac starts shooting", -- Camo Undies
	[C_ID .. 498] = "{{AngelDevilChance}} Spawns both a Devil and Angel Room if either would have spawned#Entering one makes the other disappear", -- Duality

	[C_ID .. 500] = "Spawns a sack every {VAR:RANGE} rooms", -- Sack of Sacks
	[C_ID .. 501] = "{{Heart}} +1 Heart container for every 25 coins gained after getting Greed's Gullet", -- Greed's Gullet
	[C_ID .. 502] = "{{Slow}} Firing occasionally shoots a white creep tear that deals double damage and slows enemies#Taking damage shoots a white creep tear", -- Large Zit
	[C_ID .. 503] = "{VAR:LUCKCHANCE}% chance to shoot tears that instantly kill enemies#Isaac deals 3.5 contact damage", -- Little Horn
	[C_ID .. 504] = "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage", -- Brown Nugget
	[C_ID .. 505] = "{{Friendly}} Entering a hostile room has a chance to spawn a friendly enemy", -- Poke Go
	[C_ID .. 506] = "{{BleedingOut}} Hitting an enemy in the back deals double damage and causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds", -- Backstabber
	[C_ID .. 507] = "{{Damage}} Deals Isaac's damage + 10% of the enemy's max health to all enemies#{{HalfHeart}} Dealing damage with the Straw can spawn half hearts#{{HalfSoulHeart}} Having no heart containers drops Soul Hearts instead", -- Sharp Straw
	[C_ID .. 508] = "{{BleedingOut}} Orbital that causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds#{{Damage}} Deals 3x Isaac's damage per second#Does not block shots", -- Mom's Razor
	[C_ID .. 509] = "Orbital that shoots a tear in a random direction every 2 seconds#Does not block shots", -- Bloodshot Eye
	[C_ID .. 510] = "{{Friendly}} Spawns a friendly delirium version of a boss for the room", -- Delirious
	[C_ID .. 511] = "Orbits a random enemy until that enemy dies", -- Angry Fly
	[C_ID .. 512] = "Throwable black hole, which sucks in everything#Deals 6 damage per second#Destroys nearby rocks#Lasts 6 seconds", -- Black Hole
	[C_ID .. 513] = "{{Charm}} Randomly charms/fears enemies#Taking damage has a random chance to spawn a Rainbow Poop", -- Bozo
	[C_ID .. 514] = "Causes some enemies and projectiles to briefly pause at random intervals#25% chance to double room clear drops", -- Broken Modem
	[C_ID .. 515] = "Spawns a random item from the current room's item pool#Chance to spawn Lump of Coal or The Poop instead", -- Mystery Gift
	[C_ID .. 516] = "Spawns a Sprinkler that shoots the same tears as Isaac in a circle around itself", -- Sprinkler
	[C_ID .. 517] = "Removes the delay between bomb placements", -- Fast Bombs
	[C_ID .. 518] = "Familiar which looks like a random co-op baby#Has random tear effects#Effects change every floor", -- Buddy in a Box
	[C_ID .. 519] = "Transforms into a random familiar every 10 seconds", -- Lil Delirium
	[C_ID .. 520] = "Killing 15 enemies adds 1 charge to the active item", -- Jumper Cables
	[C_ID .. 521] = "Makes one random item in the {{Shop}} Shop or {{DevilRoom}} Devil Room free#Holding the item guarantees one Shop item is on sale", -- Coupon
	[C_ID .. 522] = "Stops all enemy projectiles that come close to Isaac for 3 seconds and throws them away from him afterwards", -- Telekinesis
	[C_ID .. 523] = "Stores all pickups and items from the current room#Using the item again drops everything back on the floor#Allows Isaac to move things between rooms", -- Moving Box
	[C_ID .. 524] = "Isaac's tears are connected with beams of electricity#The beams deal Isaac's damage", -- Technology Zero
	[C_ID .. 525] = "Taking damage spawns a projectile blocking orbital#Caps at 3 orbitals#They deal 35 contact damage per second#Orbitals are destroyed if they take too much damage", -- Leprosy
	[C_ID .. 526] = "Spawns a small horseman familiar that spawns locusts#The horseman and its locust changes every 10 seconds", -- 7 Seals
	[C_ID .. 527] = "Displays a movable cursor for a few seconds, then summons a ghost that will, depending on the cursor position:#Open doors or chests#Fetch an item#50% chance to steal from the Shop / Devil#Attack an enemy until it dies#Explode walls, rocks, shopkeepers, angel statues, machines, beggars", -- Mr. ME!
	[C_ID .. 528] = "Orbital prism#Friendly tears hitting it split into 4", -- Angelic Prism
	[C_ID .. 529] = "Isaac's tears bounce off each other and disappear when they stop moving", -- Pop!
	[C_ID .. 530] = "Killing enemies in the order dictated by the mark {{DeathMark}} above them grants a random pickup or stat increase", -- Death's List
	[C_ID .. 531] = "Isaac's tears fly in an arc and burst into smaller tears on impact", -- Haemolacria
	[C_ID .. 532] = "Isaac's tears progressively slow down, stop, then explode into 8 smaller tears#Tears can merge and become bigger", -- Lachryphagy
	[C_ID .. 533] = "Replaces Isaac's tears with piercing beams of light#The beams deal 33% damage but can hit enemies multiple times", -- Trisagion
	[C_ID .. 534] = "Allows Isaac to hold 2 active items#The items can be swapped using the Drop button ({{ButtonRT}})", -- Schoolbag
	[C_ID .. 535] = "{{HolyMantle}} Entering a boss room grants a Holy Mantle shield (prevents damage once)", -- Blanket
	[C_ID .. 536] = "Sacrifices up to 2 familiars and spawns a devil item for each sacrifice#{{Coin}} Turns blue spiders/flies into coins", -- Sacrificial Altar
	[C_ID .. 537] = "{{Pill}} Spawns a random pill on pickup#Fires a line of creep#The type of creep changes with each pill use", -- Lil Spewer
	[C_ID .. 538] = "{{Collectible479}} Taking damage has a 10% chance to consume Isaac's held trinket and grant its effects permanently", -- Marbles
	[C_ID .. 539] = "{{Friendly}} Taking damage spawns a friendly enemy#Spawns stronger friends the more rooms are cleared without taking damage", -- Mystery Egg
	[C_ID .. 540] = "Isaac's tears bounce off the floor and cause splash damage on every bounce", -- Flat Stone
	[C_ID .. 542] = "Reflects enemy projectiles", -- Slipped Rib
	[C_ID .. 543] = "Taking damage spawns a white poop#While inside the poop's aura:#{VAR:EFFECTLIST}#{{IND}}Chance to block damage", -- Hallowed Ground
	[C_ID .. 544] = "Levitates in front of Isaac#Deals 6x Isaac's damage per second", -- Pointy Rib
	[C_ID .. 545] = "{{Friendly}} Spawns a bone orbital or friendly bony per enemy killed in the room (up to 8)", -- Book of the Dead
	[C_ID .. 546] = "{{Petrify}} Grants an aura that petrifies enemies", -- Dad's Ring
	[C_ID .. 547] = "{{Trinket21}} Spawns the Mysterious Paper trinket", -- Divorce Papers
	[C_ID .. 548] = "Boomerang-like familiar#Can grab and bring back pickups", -- Jaw Bone
	[C_ID .. 549] = "{{EmptyBoneHeart}} Replaces all of Isaac's Red Heart containers with 6 empty Bone Hearts#Upon losing a Bone Heart:#{VAR:EFFECTLIST}#{{IND}}Shoots 8 bone tears in all directions", -- Brittle Bones
	[C_ID .. 550] = "Mom's Foot constantly tries to stomp Isaac#Using the item stops the stomping for the room (or one Boss Rush wave)#{{Warning}} (Try to beat Boss Rush with it!)", -- Broken Shovel
	[C_ID .. 551] = "Completes Mom's Shovel#{{Warning}} Use the shovel on the mound of dirt in the \"Dark Room\"", -- Broken Shovel
	[C_ID .. 552] = "Spawns a trapdoor to the next floor#10% chance for {{LadderRoom}} crawlspace trapdoor#{{Warning}} Use the shovel on the mound of dirt in the \"Dark Room\"", -- Mom's Shovel
}


---------- Trinkets ----------

local T_ID = "5.350."
local additionalTrinketInformations = {
	[T_ID .. 1] = "{{Coin}} Taking damage spawns 1 coin", -- Swallowed Penny
	[T_ID .. 2] = "50% chance to get drops from poop", -- Petrified Poop
	[T_ID .. 3] = "{{Battery}} -1 Charge needed for active items", -- AAA Battery
	[T_ID .. 4] = "{{Collectible44}} Using an active item teleports Isaac to a random room", -- Broken Remote
	[T_ID .. 5] = "2x chance for champion enemies", -- Purple Heart
	[T_ID .. 6] = "{{Coin}} Attracts coins to Isaac", -- Broken Magnet
	[T_ID .. 7] = "{{Collectible33}} Higher chance to find The Bible in {{Shop}} Shops and {{Library}} Libraries", -- Rosary Bead
	[T_ID .. 8] = "{{Timer}} {VAR:LUCKCHANCE}% chance upon taking damage:#{VAR:ITEMDESCRIPTION}", -- Cartridge
	[T_ID .. 9] = "Isaac's tears pulsate#Affects tear hitbox", -- Pulse Worm
	[T_ID .. 10] = "Isaac's tears move in waves", -- Wiggle Worm
	[T_ID .. 11] = "Isaac's tears move in spirals with high speed", -- Ring Worm
	[T_ID .. 12] = "50% wider tears#Increases knockback", -- Flat Worm
	[T_ID .. 13] = "{{Shop}} Allows Isaac to take 1 Shop item for free", -- Store Credit
	[T_ID .. 14] = "Immune to creep and floor spikes", -- Callus
	[T_ID .. 15] = "{{Coin}} Destroying rocks spawns coins", -- Lucky Rock
	[T_ID .. 16] = "Mom's Foot stomps a random spot in the room every {VAR:1} seconds", -- Mom's Toenail
	[T_ID .. 17] = "{{BlackHeart}} +10% chance for random Soul Hearts to spawn as Black Hearts", -- Black Lipstick
	[T_ID .. 18] = "{{EternalHeart}} +3% chance for Eternal Hearts", -- Bible Tract
	[T_ID .. 19] = "{{GoldenChest}} Gold chests can be opened for free", -- Paper Clip
	[T_ID .. 20] = "{{BlackHeart}} Spawns 1 Black Heart when Isaac's health is reduced to half a heart#{{Warning}} Disappears after spawning 3 Black Hearts", -- Monkey Paw
	[T_ID .. 21] = "Randomly grants the effect of:#{VAR:TEXT}", -- Mysterious Paper
	[T_ID .. 22] = "{{Heart}} Decreases spawn rate of hearts to 20%#{{BlackHeart}} All Heart pickups turn into Black Hearts#{{Key}} Increases the drop chance of keys", -- Daemon's Tail
	[T_ID .. 23] = "{{Player10}} Respawn as The Lost on death", -- Missing Poster
	[T_ID .. 24] = "{{Coin}} 20% higher chance for coins to spawn from poop#Picking up coins makes Isaac fart", -- Butt Penny
	[T_ID .. 25] = "Isaac farts or spawns poop every 30 seconds", -- Mysterious Candy
	[T_ID .. 26] = "Isaac's tears move in angular patterns", -- Hook Worm
	[T_ID .. 28] = "{{Player4}} 22% chance to respawn as ??? (Blue Baby) on death", -- Broken Ankh
	[T_ID .. 29] = "Taking damage spawns 1 blue fly", -- Fish Head
	[T_ID .. 30] = "{{Poison}} {VAR:LUCKCHANCE}% chance to shoot poison tears", -- Pinky Eye
	[T_ID .. 31] = "{VAR:LUCKCHANCE}% chance to shoot piercing + spectral tears", -- Push Pin
	[T_ID .. 32] = "25% chance for a random mushroom effect per room#Can reveal special rooms on the minimap", -- Liberty Cap
	[T_ID .. 33] = "{{HalfHeart}} Having half a Red Heart or less grants {{NameC100}}", -- Umbilical Cord
	[T_ID .. 34] = "{{UnknownHeart}} 10% chance for the room clear reward to be a random heart#{{Heart}} 33% chance for a bonus heart from chests, tinted rocks, and destroyed machines", -- Child's Heart
	[T_ID .. 36] = "{{Key}} 10% chance for the room clear reward to be a key#{{Key}} 33% chance for a bonus key from chests, tinted rocks, and destroyed machines", -- Rusted Key
	[T_ID .. 38] = "+10% chance for heart drops to be {{SoulHeart}} Soul Hearts, {{BlackHeart}} Black Hearts or {{EmptyBoneHeart}} Bone Hearts", -- Mom's Pearl
	[T_ID .. 40] = "{{Timer}} Taking damage has a {VAR:LUCKCHANCE}% chance to grant ↑ {{Damage}} +1.8 damage for the room", -- Red Patch
	[T_ID .. 41] = "{{Bomb}} 10% chance for the room clear reward to be a bomb#{{Bomb}} 33% chance for a bonus bomb from chests, tinted rocks, and destroyed machines#{{Warning}} Removes {{Trinket53}} Tick", -- Match Stick
	[T_ID .. 42] = "+8% room clear reward chance#33% chance for an extra pickup from chests, tinted rocks, and destroyed machines", -- Lucky Toe
	[T_ID .. 43] = "When damaged down to half a heart or less, Isaac is teleported to a random room", -- Cursed Skull
	[T_ID .. 44] = "{{Pill}} 10% chance for the room clear reward to be a pill#{{Pill}} 33% chance for a bonus pill from chests, tinted rocks, and destroyed machines", -- Safety Cap
	[T_ID .. 45] = "{{Card}} 10% chance for the room clear reward to be a card#{{Card}} 33% chance for a bonus card from chests, tinted rocks, and destroyed machines", -- Ace of Spades
	[T_ID .. 46] = "{{HealingRed}} Clearing a room has a {VAR:LUCKCHANCE}% chance to heal half a heart", -- Isaac's Fork
	[T_ID .. 48] = "Taking damage has a {VAR:LUCKCHANCE}% chance to deal 40 damage to all enemies in the room", -- A Missing Page
	[T_ID .. 49] = "{{HalfHeart}} Picking up a coin has a 50% chance to spawn a half Red Heart", -- Bloody Penny
	[T_ID .. 50] = "{{Bomb}} Picking up a coin has a 50% chance to spawn a bomb", -- Burnt Penny
	[T_ID .. 51] = "{{Key}} Picking up a coin has a 50% chance to spawn a key", -- Flat Penny
	[T_ID .. 52] = "{{Coin}} Picking up a coin has a 50% chance to add another coin to the counter", -- Counterfeit Penny
	[T_ID .. 53] = "{{HealingRed}} Heals 1 heart when entering a {{BossRoom}} Boss Room#-15% boss health#{{Warning}} Once picked up, it can't be removed#Only removeable with {{Trinket41}} Match Stick or gulping", -- Tick
	[T_ID .. 54] = "Familiar with piercing tears", -- Isaac's Head
	[T_ID .. 55] = "{{EternalHeart}} Entering a new floor grants +1 Eternal Heart", -- Maggy's Faith
	[T_ID .. 56] = "{{DevilRoom}} Reduces all devil deal prices to 1 heart container#Doesn't reduce 3 Soul Heart prices", -- Judas' Tongue
	[T_ID .. 57] = "Familiar that bounces around the room#Shoots in the same direction as Isaac", -- ???'s Soul
	[T_ID .. 58] = "{{Timer}} Killing an enemy has a {VAR:LUCKCHANCE}% chance to grant ↑ {{Damage}} +0.5 damage for the room", -- Samson's Lock
	[T_ID .. 59] = "Entering a new floor has a {VAR:LUCKCHANCE}% chance to reveal map icons", -- Cain's Eye
	[T_ID .. 60] = "{{Collectible117}} Killing an enemy has a {VAR:LUCKCHANCE}% chance to spawn a Dead Bird", -- Eve's Bird Foot
	[T_ID .. 61] = "{{RedChest}} Turns all chests into Red Chests", -- The Left Hand
	[T_ID .. 62] = "Crawlspace rocks and tinted rocks blink every 10 seconds", -- Shiny Rock
	[T_ID .. 63] = "{{Bomb}} Turns Troll Bombs into bomb pickups", -- Safety Scissors
	[T_ID .. 64] = "Grants a random worm effect every 3 seconds", -- Rainbow Worm
	[T_ID .. 67] = "Taking damage has a 50% chance to trigger one of these effects:#{VAR:TEXT}", -- Cracked Dice
	[T_ID .. 68] = "Isaac attracts pickups and enemies", -- Super Magnet
	[T_ID .. 69] = "Randomly camouflages Isaac#{{Confusion}} Confuses enemies", -- Faded Polaroid
	[T_ID .. 70] = "Occasionally spawns a blue spider in hostile rooms", -- Louse
	[T_ID .. 71] = "Isaac's bombs leave damaging creep", -- Bob's Bladder
	[T_ID .. 72] = "{{Battery}} 6.66% chance for the room clear reward to be a battery#{{Battery}} +10% chance for random pickups to be a battery#{{Battery}} 5% chance to add 1 charge to held active item when clearing a room", -- Watch Battery
	[T_ID .. 73] = "{{Bomb}} 10% chance for exploding bombs to drop a bomb pickup", -- Blasting Cap
	[T_ID .. 74] = "{{LadderRoom}} +0.5% chance to reveal a crawlspace when breaking a rock", -- Stud Finder
	[T_ID .. 75] = "Grants a random trinket effect every room", -- Error
	[T_ID .. 76] = "↑ 50% chance for chests to spawn extra pickups#↓ 50% chance for chests to contain a single fly", -- Poker Chip
	[T_ID .. 77] = "Increases knockback", -- Blister
	[T_ID .. 78] = "Status effects applied to enemies last twice as long", -- Second Hand
	[T_ID .. 79] = "Using a {{Rune}} rune, {{Card}} card or {{Pill}} pill has a 25% chance to spawn a copy of that rune, card or pill", -- Endless Nameless
	[T_ID .. 80] = "↑ {{Damage}} +{VAR:1} Damage for each \"Evil up\" item held", -- Black Feather
	[T_ID .. 81] = "Invincibility frames after taking damage last twice as long", -- Blind Rage
	[T_ID .. 82] = "{{TreasureRoom}} Future Treasure Rooms have +15% chance to let Isaac choose between two items", -- Golden Horse Shoe
	[T_ID .. 83] = "{{Shop}} Lets Isaac open Shops for free", -- Store Key
	[T_ID .. 84] = "{{Coin}} 5% more coins and fewer hearts from room clear rewards#Greed and Super Greed no longer appear in {{Shop}} Shops or {{SecretRoom}} Secret Rooms", -- Rib of Greed
	[T_ID .. 85] = "{{DonationMachine}} Using a Donation Machine has a 33% chance to:#{{HealingRed}} Heal 1 heart (40%)#{{Coin}} Give 1 coin (40%)#{{Luck}} Grant +1 luck (15%)#{{Beggar}} Spawn a Beggar (5%)", -- Karma
	[T_ID .. 86] = "Destroying poop spawns 1 blue fly", -- Lil Larva
	[T_ID .. 87] = "{{HealingRed}} Using a key heals half a heart#{{Heart}} Turns half hearts into full hearts", -- Mom's Locket
	[T_ID .. 88] = "Prevents active items from spawning", -- NO!
	[T_ID .. 89] = "Familiars stay closer to Isaac", -- Child Leash
	[T_ID .. 90] = "Poop explodes for 100 damage when destroyed", -- Brown Cap
	[T_ID .. 91] = "33% chance for Black Poops to spawn#{{BlackHeart}} Destroying Black Poop has a 5% chance to spawn a Black Heart", -- Meconium
	[T_ID .. 92] = "↑ x1.33 Stat multiplier for the stats that are above 1 {{Speed}} speed, 3.5 {{Damage}} damage, 23.75 {{Range}} range, 1 {{Shotspeed}} shot speed", -- Cracked Crown
	[T_ID .. 93] = "15% chance per room for all fly enemies to become friendly", -- Used Diaper
	[T_ID .. 94] = "Doubles all blue fly / spider spawns", -- Fish Tail
	[T_ID .. 95] = "{{Poison}} {VAR:LUCKCHANCE}% chance to shoot poison tooth tears#The tooth deals 2x Isaac's damage", -- Black Tooth
	[T_ID .. 96] = "{VAR:LUCKCHANCE}% chance for homing tears#Isaac's tears move quickly in a spiral pattern", -- Ouroboros Worm
	[T_ID .. 97] = "Taking damage {VAR:RANGE} times spawns a projectile blocking familiar#Disappears after spawning 2 familiars", -- Tonsil
	[T_ID .. 98] = "10% chance to shoot a sticky tear#50% chance for it to be homing#{{Damage}} Boogers deal Isaac's damage once per second#Boogers stick for {VAR:1} seconds", -- Nose Goblin
	[T_ID .. 99] = "10% chance to shoot bouncing tears", -- Super Ball
	[T_ID .. 100] = "Holding a fully charged active item grants:#{VAR:EFFECTLIST}", -- Vibrant Bulb
	[T_ID .. 101] = "Holding a completely uncharged active item grants:#{VAR:EFFECTLIST}", -- Dim Bulb
	[T_ID .. 102] = "{{SecretRoom}} +1 extra Secret Room per floor while held", -- Fragmented Card
	[T_ID .. 103] = "Turns single pickups into double pickups when Isaac's {{Coin}} coin, {{Bomb}} bomb and {{Key}} key counts are equal", -- Equality!
	[T_ID .. 104] = "{VAR:1}% chance to get destroyed and spawn a pedestal item when hit", -- Wish Bone
	[T_ID .. 105] = "{{Collectible22}} {VAR:1}% chance to get destroyed and spawn Lunch when hit", -- Bag Lunch
	[T_ID .. 106] = "Increases the radius of friendly creep", -- Lost Cork
	[T_ID .. 107] = "Taking damage depletes Red Hearts before Soul/Black Hearts#This red heart damage does not reduce Devil/Angel Room chances", -- Crow Heart
	[T_ID .. 108] = "Getting hit by 1-9 explosions destroys the trinket and drops a random {{UnknownHeart}} heart, {{Coin}} coin, {{Key}} key and {{Trinket}} trinket#Taking damage isn't required", -- Walnut
	[T_ID .. 109] = "Familiars are stuck in one spot and cannot move", -- Duct Tape
	[T_ID .. 110] = "{{Shop}} Shops appear in the Womb", -- Silver Dollar
	[T_ID .. 111] = "{{TreasureRoom}} Treasure Rooms appear in the Womb", -- Bloody Crown
	[T_ID .. 112] = "{{RestockMachine}} Restock boxes always spawn in {{TreasureRoom}} Treasure Rooms", -- Pay To Win
	[T_ID .. 113] = "Entering a hostile room spawns an exploding attack fly #The fly deals 2x Isaac's damage + explosion damage", -- Locust of War
	[T_ID .. 114] = "{{Poison}} Entering a hostile room spawns a poison attack fly#The fly deals 2x Isaac's damage", -- Locust of Pestilence
	[T_ID .. 115] = "{{Slow}} Entering a hostile room spawns a slowing attack fly#The fly deals 2x Isaac's damage", -- Locust of Famine
	[T_ID .. 116] = "Entering a hostile room spawns an attack fly#The fly deals 4x Isaac's damage", -- Locust of Death
	[T_ID .. 117] = "Entering a hostile room spawns 1-4 attack flies#Each fly deals 2x Isaac's damage", -- Locust of Conquest
	[T_ID .. 118] = "{{Timer}} Killing an enemy has a 5% chance to grant flight for the room", -- Bat Wing
	[T_ID .. 119] = "{{HealingRed}} Entering a new floor heals half a heart", -- Stem Cell
	[T_ID .. 120] = "{{Battery}} Entering an uncleared boss room fully recharges active items", -- Hairpin
	[T_ID .. 121] = "{{Collectible313}} Grants a Holy shield that prevents damage once per floor", -- Wooden Cross
	[T_ID .. 122] = "Using an active item drops it on a pedestal on the ground#Taking damage has a 2% chance to drop one of Isaac's passive items", -- Butter!
	[T_ID .. 123] = "Angel bosses drop angel items instead of Key Pieces", -- Filigree Feather
	[T_ID .. 124] = "The last door used stays open", -- Door Stop
	[T_ID .. 125] = "Connects all familiars with beams of electricity#The beams deal 6 damage", -- Extension Cord
	[T_ID .. 126] = "Picking up a coin spawns a blue fly", -- Rotten Penny
	[T_ID .. 127] = "Grants all familiars homing shots", -- Baby-Bender
	[T_ID .. 128] = "{{EmptyBoneHeart}} Taking damage has a {VAR:1}% chance to grant a Bone Heart", -- Finger Bone
}
EID:updateDescriptionsViaTable(additionalTrinketInformations, EID.descriptions[languageCode].AdditionalInformations)


---------- Cards ----------

local Card_ID = "5.300."
local additionalCardInformations = {
	[Card_ID .. 1] = "Teleports Isaac to the first room of the floor", -- 0 - The Fool
	[Card_ID .. 3] = "Mom's Foot stomps on an enemy#Mom's Foot stomps Isaac if there are no enemies", -- II - The High Priestess
	[Card_ID .. 5] = "{{BossRoom}} Teleports Isaac to the Boss Room", -- IV - The Emperor
	[Card_ID .. 9] = "Spawns a random {{UnknownHeart}} heart, {{Coin}} coin, {{Bomb}} bomb and {{Key}} key", -- VIII - Justice
	[Card_ID .. 10] = "{{Shop}} Teleports Isaac to the Shop", -- IX - The Hermit
	[Card_ID .. 11] = "{{Slotmachine}} Spawns a Slot Machine#{{FortuneTeller}} 25% chance for it to be a Fortune Telling Machine", -- X - Wheel of Fortune
	[Card_ID .. 15] = "{{DonationMachine}} Spawns a Blood Donation Machine", -- XIV - Temperance
	[Card_ID .. 17] = "Spawns 6 Troll Bombs", -- XVI - The Tower
	[Card_ID .. 18] = "{{TreasureRoom}} Teleports Isaac to the Treasure Room", -- XVII - The Stars
	[Card_ID .. 19] = "{{SecretRoom}} Teleports Isaac to the Secret Room", -- XVIII - The Moon
	[Card_ID .. 21] = "{{Beggar}} Spawns a Beggar#{{DemonBeggar}} 33% chance for it to be a Devil Beggar#2% chance for it to be a Key Master or Bomb Bum", -- XX - Judgement
	[Card_ID .. 23] = "{{Bomb}} Doubles Isaac's number of bombs", -- 2 of Clubs
	[Card_ID .. 24] = "{{Coin}} Doubles Isaac's number of coins", -- 2 of Diamonds
	[Card_ID .. 25] = "{{Key}} Doubles Isaac's number of keys", -- 2 of Spades
	[Card_ID .. 26] = "{{HealingRed}} Doubles Isaac's number of Red Hearts {{ColorSilver}}(not containers){{CR}}", -- 2 of Hearts
	[Card_ID .. 27] = "{{Bomb}} Turns all pickups into random bombs", -- Ace of Clubs
	[Card_ID .. 28] = "{{Coin}} Turns all pickups into random coins", -- Ace of Diamonds
	[Card_ID .. 29] = "{{Key}} Turns all pickups into random keys", -- Ace of Spades
	[Card_ID .. 30] = "{{UnknownHeart}} Turns all pickups into random hearts", -- Ace of Hearts
	[Card_ID .. 31] = "{{AngelDevilChance}} Teleports Isaac to the Devil or Angel Room", -- Joker
	[Card_ID .. 32] = "Destroy all rocks in the room", -- Hagalaz
	[Card_ID .. 33] = "Duplicates all pickups in room", -- Jera
	[Card_ID .. 34] = "Spawns a trapdoor to the next floor#{{LadderRoom}} 8% chance for a crawlspace trapdoor", -- Ehwaz
	[Card_ID .. 35] = "{{CurseCursed}} Removes all curses for the floor", -- Dagaz
	[Card_ID .. 37] = "Rerolls all pedestal items in the room", -- Perthro
	[Card_ID .. 40] = "Triggers a random rune effect#25% chance to duplicate itself when used", -- Blank Rune
	[Card_ID .. 41] = "Converts all pedestal items in the room into random stat ups#Converts all pickups in the room into blue flies", -- Black Rune
	[Card_ID .. 42] = "Using the card throws it in the direction Isaac is moving#Instantly kills ANY enemy it touches (except Delirium)", -- Chaos Card
	[Card_ID .. 43] = "Makes all items and pickups in a {{Shop}} Shop or {{DevilRoom}} Devil Room free", -- Credit Card
	[Card_ID .. 44] = "Displays \"helpful\" tips on use", -- Rules Card
	[Card_ID .. 45] = "Fills the whole room with poop", -- A Card Against Humanity
	[Card_ID .. 46] = "Instantly kills Isaac and spawns 10 pickups or items on the floor#Spawned items will use the current room's item pool", -- Suicide King
	[Card_ID .. 47] = "Open all doors in the room", -- Get Out Of Jail Free Card
	[Card_ID .. 48] = "Uses Isaac's active item for free", -- ? Card
	[Card_ID .. 49] = "Rerolls all item pedestals and pickups in the room", -- Dice Shard
	[Card_ID .. 50] = "Two of Mom's Hands come down and grab an enemy each", -- Emergency Contact
	[Card_ID .. 51] = "{{HolyMantle}} Holy Mantle shield for the room (prevents damage once)#25% chance to spawn another Holy Card", -- Holy Card
	[Card_ID .. 52] = "{VAR:ROOMEFFECT}#Allows Isaac to destroy rocks by walking into them", -- Huge Growth
	[Card_ID .. 54] = "{VAR:ROOMEFFECT}#{{Slow}} Slow down enemies", -- Era Walk
}
EID:updateDescriptionsViaTable(additionalCardInformations, EID.descriptions[languageCode].AdditionalInformations)


---------- Pills ----------

local Pill_ID = "5.70."
local additionalPillInformations = {
    [Pill_ID .. 1] = "{{Poison}} Isaac farts and poisons nearby enemies", -- Bad Gas
    [Pill_ID .. 2] = "{{Warning}} Deals 1 heart of damage to Isaac#Becomes a Full Health pill at 1 heart or less", -- Bad Trip
    [Pill_ID .. 4] = "Swaps Isaac's number of {{Bomb}} bombs and {{Key}} keys", -- Bombs are Key
    [Pill_ID .. 5] = "Isaac quickly spawns 5 lit bombs", -- Explosive Diarrhea
    [Pill_ID .. 7] = "Becomes a Health Up pill at 0 or 1 heart containers", -- Health Down
    [Pill_ID .. 10] = "Eating 3 grants the Adult transformation:#{VAR:EFFECTLIST}", -- Puberty
    [Pill_ID .. 20] = "Teleports Isaac to a random room#{{ErrorRoom}} Small chance to teleport Isaac to the I AM ERROR room", -- Telepills
    [Pill_ID .. 21] = "{{Battery}} Fully recharges the active item", -- 48 Hour Energy!
    [Pill_ID .. 22] = "{{Warning}} Drains all but one heart container", -- Hematemesis
    [Pill_ID .. 23] = "Prevents Isaac from moving and shooting for 2 seconds", -- Paralysis
    [Pill_ID .. 24] = "{{SecretRoom}} Opens all secret room entrances on the floor", -- I can see forever!
    [Pill_ID .. 25] = "{{Charm}} Charms all enemies in the room", -- Pheromones
    [Pill_ID .. 26] = "{{CurseLost}} Hides the map for the floor", -- Amnesia
    [Pill_ID .. 27] = "Spawns a large puddle on the ground which damages enemies", -- Lemon Party
    [Pill_ID .. 28] = "{{Timer}} Isaac shoots diagonally for 30 seconds", -- R U A Wizard?
    [Pill_ID .. 29] = "{{Timer}} Reduces all damage taken to half a heart for the room", -- Percs!
    [Pill_ID .. 30] = "{{Timer}} Increases all damage taken to a full heart for the room", -- Addicted!
    [Pill_ID .. 31] = "Isaac spawns poop behind him for 2 seconds", -- Re-Lax
    [Pill_ID .. 32] = "{{CurseMaze}} Curse of the Maze effect for the floor", -- ???
    [Pill_ID .. 33] = "Doesn't affect his hitbox", -- One makes you larger
    [Pill_ID .. 34] = "Also decreases his hitbox", -- One makes you small
    [Pill_ID .. 35] = "Spawns 1 blue spider for each poop in the room", -- Infested!
    [Pill_ID .. 36] = "Spawn 1 blue spider for each enemy in the room#Spawns 1-3 blue spiders if there are no enemies in the room", -- Infested?
    [Pill_ID .. 38] = "{{Timer}} Pixelates the screen 3 times over 30 second", -- Retro Vision
    [Pill_ID .. 40] = "Spawns a pool of slippery creep", -- X-Lax
    [Pill_ID .. 41] = "{{Slow}} Spawns a pool of slowing creep", -- Something's wrong...
    [Pill_ID .. 42] = "{{Slow}} Slows all enemies in the room", -- I'm Drowsy...
    [Pill_ID .. 43] = "Speeds up all enemies in the room", -- I'm Excited!!
    [Pill_ID .. 44] = "{{Trinket}} Consumes Isaac's trinket and grants its effects permanently", -- Gulp!
    [Pill_ID .. 45] = "{{Collectible149}} Shoots one Ipecac tear", -- Horf!
    [Pill_ID .. 47] = "Spawns the last pill used before Vurp!", -- Vurp!
}
EID:updateDescriptionsViaTable(additionalPillInformations, EID.descriptions[languageCode].AdditionalInformations)