---------------------------------------
-----  Basic Czech descriptions -----
---------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

local languageCode = "cs_cz"

-- init cz table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "Czech"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts

---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "Smutná Cibulka", "↑ +0.7 Více Slz"},
	{"2", "Třetí Oko", "Trojitý výstřel#↓ Méně Slz"},
	{"3", "Ohnutá Lžíce", "Naváděné Slzy"},
	{"4", "Cricketova Hlava", "↑ +0.5 Větší Poškození#↑ +50% Násobič Poškození"},
	{"5", "Můj Odraz", "Dává slzám bumerangový efekt#↑ +1.5 Větší Dostřel#↑ +0.6 Větší Rychlost Střel#↑ +1 Výška Slz"},
	{"6", "Číslo Jedna", "↑ +1.5 Více Slz#↓ -17.62 Menší Dostřel#↑ +0.76 Výška Slz"},
	{"7", "Krev Mučedníka", "↑ +1 Větší Poškození#↑ +50% pokud máte aktivní efekt Belialovy Knihy nebo Ďábelské Karty"},
	{"8", "Bráška Bobby", "Spojenec s normalními slzami#Uděluje 3.5 poškození za slzu"},
	{"9", "Skatol", "Všechny nepřátelské mouchy jsou nyní přátelské"},
	{"10", "Kruh z Much", "+2 orbitální mouchy#Blokuje nepřátelské střely"},
	{"11", "1 Život!", "↑ +1 život#Znovuzrození s plným zdravím"},
	{"12", "Kouzelná Houba", "↑ +1 Zvýšení Zdraví#Plné zdraví#↑ +0.3 Větší Poškození#↑ +50% Násobič Poškození#↑ +5.25 Větší Dostřel#↑ +0.3 Zvýšení Rychlosti#↑ +0.5 Výška Slz#Zvětšení"},
	{"13", "Virus", "Jedovatý dotek#↓ -0.1 Snížení Rychlosti#Z nepřátel mohou spadnout Černá Srdce, pokud jsou otráveni"},
	{"14", "Steroidový Vztek", "↑ +0.6 Zvýšení Rychlosti#↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"15", "<3", "↑ +1 Zvýšení Zdraví#Plné zdraví"},
	{"16", "Syrová Játra", "↑ +2 Zvýšení Zdraví#Plné zdraví"},
	{"17", "Kostlivcův Klíč", "+99 Klíčů"},
	{"18", "Dolar", "+99 penízků"},
	{"19", "Bum!", "+10 Bomb"},
	{"20", "Transcendence", "Létání!"},
	{"21", "Kompas", "Zobrazí všechny ikony na mapě#Nezobrazuje rozložení mapy"},
	{"22", "Oběd", "↑ +1 Zvýšení Zdraví"},
	{"23", "Večeře", "↑ +1 Zvýšení Zdraví"},
	{"24", "Dezert", "↑ +1 Zvýšení Zdraví"},
	{"25", "Snídaně", "↑ +1 Zvýšení Zdraví"},
	{"26", "Shnilé Maso", "↑ +1 Zvýšení Zdraví"},
	{"27", "Vařečka", "↑ +0.3 Zvýšení Rychlosti"},
	{"28", "Pásek", "↑ +0.3 Zvýšení Rychlosti"},
	{"29", "Mámino Spodní Prádlo", "↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"30", "Máminy Podpatky", "↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"31", "Mámina Rtěnka", "↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"32", "Drátěný Věšák na Kabáty", "↑ +0.7 Více Slz"},
	{"33", "Bible", "Létání pro aktuální místnos#Okamžitě zabije Máminu Nohu a Mámino Srdce#!!! Zabije VÁS při použití na Satana"},
	{"34", "Belialova Kniha", "↑ +2 Větší Poškození#↑ +12.5% Šance na Ďábelskou/Andělskou místnost#↑ +50% Násobič Poškození pokud máte Krev Mučedníka"},
	{"35", "Necronomicon", "Uděluje 40 poškození všem nepřátelům v místnosti"},
	{"36", "Hovno", "Vytvoří jedno hovínko a odstrčí nepřátele zpět#Lze umístit vedle jámy a zničit bombou, aby se vytvořil most"},
	{"37", "Pan Bum", "Shodí pod hráče velkou bombu, která způsobí 110 poškození"},
	{"38", "Tammyho Hlava", "Vystřelí 10 slz v kruhu kolem Isaaca"},
	{"39", "Mámina Podprsenka", "Zmrazí všechny nepřátele v aktuální místnosti na 4 sekundy"},
	{"40", "Kamikaze!", "Způsobí explozi v místě hráče#Způsobí 40 poškození"},
	{"41", "Mámina Vložka", "Po dobu 5 sekund se nepřátelé budou bát v aktuální místnosti"},
	{"42", "Bobova Shnilá Hlava", "Vrhací jedovatá bomba"},
	{"43", "", "<předmět neexistuje>"},
	{"44", "Teleport!", "Teleportuje Isaaca do náhodné místnosti kromě místností JÁ JSEM ERROR"},
	{"45", "Mňamka Srdce", "Vyléčí 1 Červené Srdce"},
	{"46", "Šťastná Noha", "↑ +1 Zvýšení Štěstí#Lepší šance na výhru při hraní hazardních her#Zvyšuje šanci o 8% na odměnu z vyklizení místnosti"},
	{"47", "Doktorův Dálkový Ovladač", "Epický Zárodek na vyžádání!#Řiditelné Nálety"},
	{"48", "Amorův Šíp", "Průrazné slzy"},
	{"49", "Shoop da Whoop!", "Laser s vysokým poškozením"},
	{"50", "Steven", "↑ +1 Větší Poškození"},
	{"51", "Pentagram", "↑ +1 Větší Poškození#↑ +10% Šance na Ďábelskou/Andělskou místnost"},
	{"52", "Doktor Zárodek", "Bomby namísto slz#Každá bomba způsobí 5x vaše poškození + 30#↓ Zpoždění Slz x 2.5"},
	{"53", "Magneto", "Magneticky přitahuje pickupy"},
	{"54", "Mapa Pokladů", "Odhalí rozložení patra#Nezobrazuje ikony místností"},
	{"55", "Mámino Oko", "50% šance vystřelit slzu dozadu#Šance je 100% při 2 Štěstí"},
	{"56", "Citronová Nehoda", "Vytvoří kaluž limonády#Způsobí 24 poškození kontaktem za sekundu"},
	{"57", "Vzdálený Obdiv", "Orbitální muška střední vzdálenosti#Uděluje 75 kontaktního poškození za sekundu"},
	{"58", "Kniha Stínů", "Nesmrtelnost na 10 sekund"},
	{"59", "", "<předmět neexistuje>"},
	{"60", "Žebřík", "Choďte přes malé mezery"},
	{"61", "", "<předmět neexistuje>"},
	{"62", "Okouzlení Upíra", "Vyléčí půl srdce každých 13 zabitých nepřátel"},
	{"63", "Baterie", "Aktivní předměty lze nyní nabít dvakrát"},
	{"64", "Výprodej na Steamu", "-50% na předměty v obchodě#Pokud tuto položku získáte dvakrát, bude vše zdarma"},
	{"65", "Anarchistická Kuchařka", "Vytvoří 6 trollích bomb blízko středu místnosti"},
	{"66", "Přesýpací Hodiny", "Zpomaluje nepřátele na 8 sekund"},
	{"67", "Ségra Maggy", "Spojenec s normalními slzami#Uděluje 3.5 poškození za slzu"},
	{"68", "Technologie", "Slzy jsou nyní lasery"},
	{"69", "Čokoládové Mléko", "Nabíjecí slzy#↑ Až 400% Poškození#↓ Méně Slz"},
	{"70", "Růstové Hormony", "↑ +1 Větší Poškození#↑ +0.4 Zvýšení Rychlosti"},
	{"71", "Mini Houbička", "↑ +0.3 Zvýšení Rychlosti#↓ -4.25 Menší Dostřel*#↑ +1.5 Výška Slz*#(*oba se sčítají do mírného Většího Dostřelu)#↑ Zmenšení"},
	{"72", "Růženec", "+3 Duševní Srdce#{{Collectible33}}Bible je přidána do všech skupin předmětů"},
	{"73", "Kostka Masa", "LVL1: Orbitální maso#LVL2: Orbitální a střílející maso#LVL3: Masový Kluk LVL1#LVL4: Masový Kluk LVL2"},
	{"74", "Čtvrťák", "+25 penízků"},
	{"75", "PHD", "Lepší pilulky#Vytvoří 1 Pilulku#Vyléčí 2 Červená Srdce#Více peněz ze Strojů na Darování Krve"},
	{"76", "Rentgenové Vidění", "Odhalí vchody do tajných místností"},
	{"77", "Můj Malý Jednorožec", "Nesmrtelnost#40 kontaktního poškození"},
	{"78", "Kniha Zjevení", "+1 Duševní Srdce#Vyšší šance na jezdce při použití#↑ +17.5% Šance na Ďábelskou/Andělskou místnost"},
	{"79", "Značka", "↑ +1 Větší Poškození#↑ +0.2 Zvýšení Rychlosti#+1 Duševní Srdce"},
	{"80", "Pakt", "↑ +0.5 Větší Poškození#↑ +0.7 Více Slz#+2 Duševní Srdce"},
	{"81", "Mrtvá Kočka", "↑ +9 životů#Znovuzrození pouze s 1 životem#↓ Nastaví vaše životy na 1 Červené Srdce#Postavy, které nemohou mít Červené Srdce, se nastaví na 1 Duševní/Černé Srdce"},
	{"82", "Lord Podzemí", "Létání#↑ +0.3 Zvýšení Rychlosti"},
	{"83", "Hřebík", "+1 Duševní Srdce#↑ +0.7 Větší Poškození#↓ -0.18 Snížení Rychlosti#Udělujete kontaktní poškození#Rozdrcujete kameny"},
	{"84", "Musíme Jít Hlouběji!", "Vytvoří padací dvířka pro přeskočení patra#10% šance na padací dvířka vedoucí do průlezu"},
	{"85", "Balíček Karet", "Vytvoří 1 Kartu"},
	{"86", "Monstrův Zub", "Vyvolejte Monstro na jedno dupnutí"},
	{"87", "Lokiho Rohy", "25% šance na vystřelení ve 4 směrech#100% šance při 7 Štěstí"},
	{"88", "Malý Tlouštík", "Spojenec, který se vystřelí dopředu#Způsobuje 52.5 kontaktního poškození za sekundu"},
	{"89", "Pavoučí Kousnutí", "25% šance vystřelit zpomalující slzy#100% šance při 15 Štěstí"},
	{"90", "Malý Kamínek", "↑ +1 Větší Poškození#↑ +0.2 Více Slz#↓ -0.2 Snížení Rychlosti"},
	{"91", "Horníkova Helma", "Odhalí typ místnosti sousedních místností#Může také odhalit Tajné Místnosti, Super Tajné Místnosti a Mini-Boss Místnosti"},
	{"92", "Super Obvaz", "↑ +1 Zvýšení Zdraví#+2 Duševní Srdce#Vyléčí 1 Červené Srdce"},
	{"93", "Gamekid", "Krátká nesmrtelnost#Všichni nepřátelé se bojí#Způsobujete 40 kontaktního poškození#Dva sežraní nepřátelé vám doplní půl srdce"},
	{"94", "Pytel Peněz", "Každé 2 místnosti vytvoří náhodný penízek"},
	{"95", "Robo-Děcko", "Laserové slzy#Uděluje 3.5 poškození za slzu"},
	{"96", "Malý C.H.A.D.", "Vytvoří půl srdce každé 3 místnosti"},
	{"97", "Kniha Hříchu", "Vytvoří náhodný pickup"},
	{"98", "Relikvie", "Vytvoří 1 Duševní Srdce každých 5-6 místností"},
	{"99", "Malý Gish", "Zpomalující slzy#Uděluje 3.5 poškození za slzu"},
	{"100", "Malý Steven", "Naváděné slzy#Uděluje 3.5 poškození za slzu"},
	{"101", "Svatozář", "↑ +1 Zvýšení Zdraví#↑ +0.3 Větší Poškození#↑ +0.2 Více Slz#↑ +0.25 Větší Dostřel#↑ +0.3 Zvýšení Rychlosti#↑ +0.5 Výška Slz"},
	{"102", "Mámina Lahvička s Pilulky", "Vytvoří 1 Pilulku"},
	{"103", "Běžná Chřipka", "25% šance vystřelit Jedovaté slzy#100% šance při 12 Štěstí"},
	{"104", "Parazit", "Slzy se při kontaktu rozdělí na dvě části#Rozdělené slzy způsobí poloviční poškození"},
	{"105", "D6", "Zamíchá předměty v aktuální místnosti"},
	{"106", "Pan Mega", "↑ Poškození bomb x2.25#+5 Bomb"},
	{"107", "Velké Nůžky", "Létání#Tvé tělo útočí na nepřátele s 82.5 kontaktního poškození za sekundu"},
	{"108", "Oplatka", "Veškeré utrpěné poškození se sníží na polovinu srdce"},
	{"109", "Peníze = Síla", "↑ +0.04 Větší Poškození za každý penízek, který máte"},
	{"110", "Mámina Čočka", "20% šance vystřelit Mrazivé Slzy#↑ +0.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"111", "Fazole", "Jedovatý prd"},
	{"112", "Anděl Strážný", "Orbitální andílek#Zrychluje všechny orbitální spojence#Blokuje střely#Uděluje 105 kontaktního poškození za sekundu"},
	{"113", "Démoní Děcko", "Automaticky střílí#Uděluje 3 poškození za slzu"},
	{"114", "Mámin Nůž", "Kontrolovatelný útok nožem#Nůž způsobí 2x poškození Isaaca při držení a 6x poškození v co největší vzdálenosti"},
	{"115", "Ouija Deska", "Spektrální slzy"},
	{"116", "9 Voltovka", "-1 nabití pro aktivní předměty#Plně nabije váš aktivní předmět"},
	{"117", "Mrtvý Pták", "Vytvoří mrtvého ptáka, když dostanete zasáh#Bird Uděluje 4 kontaktního poškození za sekundu"},
	{"118", "Leviatanův Kříž", "Nabijte krvavý laser, který způsobuje konstantní poškození"},
	{"119", "Sáček s Krví", "↑ +1 Zvýšení Zdraví#↑ +0.3 Zvýšení Rychlosti#Vyléčí 4 Srdce"},
	{"120", "Zvláštní Houba", "↑ +1.7 Více Slz#↑ +0.3 Zvýšení Rychlosti#↓ -10% Menší Poškození#↓ -0.4 dodatečné Menší Poškození"},
	{"121", "Zvláštní Houba", "↑ +1 Prázdné místo pro Srdce#↑ +0.3 Větší Poškození#↑ +0.25 Větší Dostřel#↓ -0.1 Snížení Rychlosti#↑ +0.5 Výška Slz"},
	{"122", "Děvka Babylonská", "!!! Když máte půl Červeného Srdce nebo méně:#↑ +1.5 Větší Poškození#↑ +0.3 Zvýšení Rychlosti"},
	{"123", "Manuál na Příšery", "Náhodný spojenec pro aktuální místnost"},
	{"124", "Svitky od Mrtvého Moře", "Náhodný efekt aktivního předmětu"},
	{"125", "Polda-Bomba", "Naváděné bomby#+5 Bomb"},
	{"126", "Žiletka", "↑ +1.2 Větší Poškození pro aktuální místnost#↓ Způsobí vám 1 poškození#Upřednostňuje Červené Srdce"},
	{"127", "Zapomeň na Mě", "{{Warning}} JEDNORÁZOVÉ POUŽITÍ {{Warning}}#Zamíchá celé patro"},
	{"128", "Navždy Sám", "Orbitální muška#Daleko od vás#Uděluje 30 kontaktního poškození za sekundu"},
	{"129", "Kbelík Sádla", "↑ +2 Prázdné místa pro srdce#↓ -0.2 Snížení Rychlosti#Vyléčí polovinu srdce"},
	{"130", "Poník", "Uděluje létání při držení předmětu#Nastaví vaši rychlost na 1.5 pokud máte méně než 1.5#Vzlétne ve směru použití"},
	{"131", "Pytel Bomb", "Každé 2-3 místnosti vytvoří bombu"},
	{"132", "Hrouda Uhlí", "Více Poškození na základě procestované vzdálenosti slzy"},
	{"133", "Guppyho Tlapka", "!!! Přeměň:#1 místo pro Srdce na 3 Duševní Srdce"},
	{"134", "Guppyho Ocas", "33% šance, že odměna za pročištěnou místnost bude truhla#33% šance na žádnou odměnu za pročištěnou místnost"},
	{"135", "IV Vak", "Přenosná krevní banka#Půl srdce = 1-3 penízků"},
	{"136", "Nejlepší Kámoš", "Explodující Návnada#Přitahuje nepřátele"},
	{"137", "Dálková Rozbuška", "Odpalte bomby na požádání#+5 Bomb"},
	{"138", "Stigmata", "↑ +1 Zvýšení Zdraví#↑ +0.3 Větší Poškození"},
	{"139", "Mámina Kabelka", "Nyní můžete mít 2 trinkety"},
	{"140", "Bobova Kletba", "Jedovaté bomby#+5 Bomb"},
	{"141", "Král Krásy", "Vytvoří 7 náhodných penízků"},
	{"142", "Škapulíř", "Při příjmutí poškození až do zbývající poloviny srdce, dostanete 1 Duševní Srdce#(Jednou za místnost)"},
	{"143", "Rychlokoule", "↑ +0.3 Zvýšení Rychlosti#↑ +0.2 Větší Rychlost Střel"},
	{"144", "Žebrácký Kámoš", "Převádí penízky na pickupy"},
	{"145", "Guppyho Hlava", "Vytvoří 2-4 modré mouchy"},
	{"146", "Modlitební Obrázek", "+1 Srdce Věčnosti"},
	{"147", "Notchův Krumpáč", "Na dotek rozbíjí kameny v aktuální místnosti"},
	{"148", "Zamoření", "Vytvoří mouchy, když dostanete zásah"},
	{"149", "Ipekak", "Výbušné jedovaté slzy#↑ +40 Větší Poškození#↓ Méně Slz"},
	{"150", "Tvrdá Láska", "10% šance vystřelit zuby#Zuby udělují 3.2x tvého poškození#100% šance při 9 Štěstí"},
	{"151", "Mulligan", "1/6 šance na vytvoření mouchy při zasáhnutí nepřítele"},
	{"152", "Technologie 2", "Permanentní laserový útok!#↓ -35% Menší Poškození"},
	{"153", "Mutantní Pavouk", "Čtyř výstřel!#↓ Méně Slz"},
	{"154", "Chemické Oloupání", "↑ +2 Větší Poškození pro levé oko"},
	{"155", "Kukadlo", "Poletuje po místnosti#Uděluje 17.1 kontaktního poškození za sekundu"},
	{"156", "Hábit", "+1 nabití při utrpení zásahu"},
	{"157", "Krvavá Chtíč", "↑ Větší Poškození pokaždé co dostanete zásah#Aplikuje se až 6krát za patro#Trvá po celé patro"},
	{"158", "Křišťálová Koule", "Odhaluje celou mapu#Vytvoří náhodnou Kartu nebo Duševní Srdce"},
	{"159", "Přízrak Soumraku", "Létání#Spektrální slzy"},
	{"160", "Prolomení Oblohy", "V blízkosti nepřátel vytvoří 5 paprsků světla#Způsobuje vaše poškození+20"},
	{"161", "Anch", "Znovuzroďte se jako ??? (Blue Baby) po smrti"},
	{"162", "Keltský Kříž", "Šance na nesmrtelnost, když Isaac utrpí zásah"},
	{"163", "Duchařské dítě", "Spojenec se spektrálními slzami#Uděluje 3.5 poškození za slzu"},
	{"164", "Svíčka", "Vyhodíte modrý plamen#Způsobuje kontaktní poškození#Blokuje nepřátelské slzy#Po 2 sekundách zmizí"},
	{"165", "Kočka s Devíti Ocasy", "↑ +1 Větší Poškození#↑ +0.23 Větší Rychlost Střel"},
	{"166", "D20", "Zamíchá pickupy"},
	{"167", "Dítě Harlekýn", "Vystřelí dvě slzy ve tvaru písmene V#Uděluje 4 poškození za střelu"},
	{"168", "Epický Zárodek", "Kontrolovatelný nálet místo slz#Uděluje 20násobek vašeho poškození"},
	{"169", "Polyfémos", "↑ +100% Větší Poškození#↑ +4 dodatečné Větší Poškození#↓ Méně Slz#Slzy pokračují i ​​po zabití nepřítele"},
	{"170", "Taťka Dlouhonožka", "Dupe na nepřátele#Uděluje 40 poškození za sekundu"},
	{"171", "Pavoučí Prdel", "Zpomalí nepřátele na 4 sekundy#10 poškození všem nepřátelům"},
	{"172", "Obětní Dýka", "Orbitální dýka#Blokuje nepřátelské střely#Uděluje 225 poškození za sekundu"},
	{"173", "Mitra", "Větší šance k nalezení Duševních Srdcí"},
	{"174", "Duhové Dítě", "Střílí náhodné slzy#Uděluje 3-5 poškození za střelu"},
	{"175", "Tátův Klíč", "Otevírá všechny dveře v místnosti, včetně {{SecretRoom}}{{SuperSecretRoom}}Tajných Místností, {{ChallengeRoom}}{{BossRushRoom}}Vyzyvatelských Místností, a Mega Satan dveří"},
	{"176", "Kmenové Buňky", "↑ +1 Zvýšení Zdraví#↑ +0.16 Větší Rychlost Střel"},
	{"177", "Přenosný Automat", "Přenosný Hrací Automat"},
	{"178", "Svěcená Voda", "Při utrpení zásahu po sobě zanechá poškozující kaluž#Uděluje 24 poškození za sekundu"},
	{"179", "Osud", "Létání#+1 Srdce Věčnosti"},
	{"180", "Černá Fazole", "Při doteku prdíš"},
	{"181", "Bílý Poník", "Uděluje létání při držení předmětu#Nastaví vaši rychlost na 1.5 pokud máte méně než 1.5#Svaté vzlétnutí ve směru použití"},
	{"182", "Nejsvětější Srdce", "↑ +1 Zvýšení Zdraví#Plné zdraví#↑ 230% + 1 Větší Poškození#↓ -0.4 Méně Slz#↓ -0.25 Menší Rychlost Střel#↑ +0.38 Větší Dostřel#↑ +0.75 Výška Slz#Naváděné slzy"},
	{"183", "Párátka", "↑ +0.7 Více Slz#↑ +0.16 Větší Rychlost Střel"},
	{"184", "Svatý Grál", "Uděluje létání#↑ +1 Zvýšení Zdraví"},
	{"185", "Mrtvá Holubice", "Létání#Spektrální slzy"},
	{"186", "Pokrevní Práva", "↑ Udělí 40 poškození každému nepříteli#↓ Způsobí vám 1 poškození#Upřednostňuje Červené Srdce"},
	{"187", "Guppyho Chlupatá Koule", "Rostoucí koule z chlupů#Houpe se kolem tebe#Roste, když zabije nepřítele#Větší koule způsobí větší poškození"},
	{"188", "Ábel", "Zrcadlí váš pohyb#Střílí směrem k hráči#Uděluje 3.5 poškození za slzu"},
	{"189", "SMB Super Fanoušek", "↑ +1 Zvýšení Zdraví#Plné zdraví#↑ +0.3 Větší Poškození#↑ +0.2 Více Slz#↑ +0.5 Větší Dostřel#↑ +0.2 Zvýšení Rychlosti#↑ +1 Výška Slz"},
	{"190", "Pyro", "+99 Bomb"},
	{"191", "3 Dolarová Bankovka", "Náhodný efekt slzy každé 2-3 sekundy"},
	{"192", "Telepatie pro Blbečky", "Naváděné slzy pro aktuální místnost"},
	{"193", "MASO!", "↑ +1 Zvýšení Zdraví#↑ +0.3 Větší Poškození"},
	{"194", "Magická Koule 8", "↑ +0.16 Větší Rychlost Střel#+1 Karta"},
	{"195", "Mámina Peněženka", "Vytvoří 4 Pilulky"},
	{"196", "Mačkátko", "Vytvoří 2 Duševní Srdce#↑ +0.4 Více Slz"},
	{"197", "Ježíšův Džus", "↑ +0.5 Větší Poškození#↑ +0.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"198", "Krabice", "Vytvoří 1 pickup od každého druhu"},
	{"199", "Mámin Klíč", "+2 Klíče#Více věcí z truhel"},
	{"200", "Máminy Oční Stíny", "10% šance vystřelit okouzlující slzy"},
	{"201", "Železná Cihla", "↑ +0.3 Větší Poškození#10% šance vystřelit matoucí slzy"},
	{"202", "Midasův Dotek", "Proměňuje nepřátele ve zlato při dotyku#Způsobuje kontaktní poškození na základě počtu vašich penízků#Při zabíjení zlatých nepřátel padají penízky"},
	{"203", "Skromný Balíček", "Zdvojnásobuje všechny pickupy"},
	{"204", "Ledvinka", "50% šance na náhodný pickup při zásahu nepřítelem"},
	{"205", "Ostrá Zástrčka", "-2 Srdce = Plné nabití předmětu při stisknutí mezerníku#!!! Funguje pouze v případě, že položka nemá žádné nabití!"},
	{"206", "Gilotina", "↑ +1 Větší Poškození#↑ Více Slz#Vaše Hlava je nyní orbitální#Budete střílet z hlavy#Hlava uděluje kontaktní poškození 105"},
	{"207", "Koule z Obvazů", "LVL1: Orbitální koule#LVL2: Orbitální a střílející koule#LVL3: Obvazová Holka LVL1#LVL4: Obvazová Holka LVL2"},
	{"208", "Pás Šampionů", "↑ +1 Větší Poškození#!!! +15% šance na objevení šampionů"},
	{"209", "Prdelní Bomby", "↑ +5 Bomb#Výbuchy udělí poškození a zmatou každého nepřítele v místnosti"},
	{"210", "Ohlodaný List", "Nesmrtelnost, když stojíte 1 sekundu na místě"},
	{"211", "Pavoučí Miláček", "Při utrpení poškození vytvoří 1-2 pavouky"},
	{"212", "Guppyho Obojek", "↑ 50% šance na oživení"},
	{"213", "Ztracená Čočka", "Štítované slzy#Slzy blokují nepřátelské střely#↓ -0.16 Menší Rychlost Střel"},
	{"214", "Anémie", "↑ +5 Větší Dostřel#Po utrpení zásahu zanechává na zemi poškozující kaluž"},
	{"215", "Kozí Hlava", "↑ 100% šance na {{DevilRoom}}Ďábelskou/{{AngelRoom}}Andělskou Místnost"},
	{"216", "Obřadní Róba", "↑ +1 Větší Poškození#+3 Černé Srdce"},
	{"217", "Maminčina Paruka", "Náhodná šance na vytvoření modrého pavouka při střílení slz#Vyléčí 1 Červené Srdce"},
	{"218", "Placenta", "↑ +1 Zvýšení Zdraví#Šance vyléčit půl srdce každou minutu"},
	{"219", "Starý Obvaz", "↑ +1 Prázdné místo pro Srdce#Náhodná šance na vytvoření Červených Srdcí, když dostanete zásah"},
	{"220", "Smutné Bomby", "Výbuch slz!#+5 Bomb"},
	{"221", "Gumový Cement", "Poskakující slzy"},
	{"222", "Anti-Gravitace", "Podržením tlačítek pro střelbu se ve vzduchu budou vznášet slzy#Po uvolnění budou všechny slzy vystřeleny směrem, kterým byly vystřeleny původně#↑ -2 Zpoždění Slz"},
	{"223", "Pyromaniak", "Výbuchy tě léčí#+5 Bomb"},
	{"224", "Cricketovo Tělo", "↑ +1 Více Slz#↓ -10 Menší Dostřel#Slzy se při zásahu rozdělují na 4#Rozdělené slzy způsobí poloviční poškození"},
	{"225", "Fetišista", "Šance na vytvoření Duševního Srdce, když dostanete poškození#Monstra mají šanci vytvořit půl Červeného Srdce po zabití"},
	{"226", "Černý Lotus", "↑ +1 Zvýšení Zdraví#+1 Duševní Srdce#+1 Černé Srdce"},
	{"227", "Prasátko", "+3 penízky#Při utrpení zásahu vytvoří 1-2 penízky#0-1 penízků za Keepera"},
	{"228", "Maminčin Parfém", "15% šance vystřelit zastrašující slzy#↑ +1 Více Slz"},
	{"229", "Monstrovo Plíce", "Slzy lze nyní nabít a vystřelit ve stylu brokovnice#↓ 4.3x Zpoždění Slz"},
	{"230", "Abaddón", "↑ +1.5 Větší Poškození#↑ +0.2 Zvýšení Rychlosti#Zastrašující slzy#↓ Odstraňuje všechny místa na srdce#+6 Černých Srdcí"},
	{"231", "Koule Dehtu", "10% šance vystřelit zpomalující slzy#100% při 18 Štěstí#Zanechává po sobě zpomalující kaluž"},
	{"232", "Stopky", "Permanentní efekt zpomalení#(aktivuje se při zásahu)#↑ +0.3 Zvýšení Rychlosti"},
	{"233", "Maličká Planeta", "Slzy kolem tebe obíhají#↑ O Hodně Větší Dostřel!#↑ +7 Výška Slz#Spektrální slzy"},
	{"234", "Zamoření 2", "Vytvoří pavouky, když zabijete nepřítele"},
	{"235", "", "<předmět neexistuje>"},
	{"236", "E. Coli", "Při dotyku proměníte nepřátele v hovno"},
	{"237", "Dotek Smrti", "Střílíte kosy!#↑ +1.5 Větší Poškození#↓ -0.3 Méně Slz#Průrazné slzy"},
	{"238", "První Část Klíče", "!!! Část klíče od dveří k Mega Satanovi!#Více {{AngelRoom}}Andělských Místností"},
	{"239", "Druhá Část Klíče", "!!! Část klíče od dveří k Mega Satanovi!#Více {{AngelRoom}}Andělských Místností"},
	{"240", "Experimentální Léčba", "Všechny Statistiky ↑/↓ o náhodné číslo"},
	{"241", "Smlouva z Podzemí", "Zdvojnásobuje všechny odměny za pročištěnou místnost#33% šance na žádnou odměnu za pročištěnou místnost#Neovlivňuje režim Greed Mode"},
	{"242", "Hanba", "50% šance na zablokování nepřátelských slz"},
	{"243", "Štít Nejsvětější Trojice", "Štít blokující nepřátelské slzy"},
	{"244", "Tech.5", "Střílejte náhodné laserové výstřely"},
	{"245", "20/20", "Zdvojnásobí všechny vaše střely"},
	{"246", "Modrá Mapa", "Odhaluje tajné místnosti"},
	{"247", "NEJKY!", "Vaši spojenci působí dvojnásobné poškození"},
	{"248", "Úlové Myšlení", "Modří pavouci/mouchy působí dvojnásobné poškození"},
	{"249", "Jsou Tu Možnosti", "Namísto 1 se objeví 2 Boss předměty#!!! Vzít lze pouze jeden"},
	{"250", "1+1 Bomby", "Všechny bomby se stanou dvojitými bombami"},
	{"251", "Začátečnický Balíček", "Můžete mít u sebe 2 Karty#Promění všechny Pilulky na Karty#Vytvoří 1 Kartu"},
	{"252", "Malý Pytlík", "Můžete mít u sebe 2 Pilulky#Promění všechny Karty na Pilulky#Vytvoří 1 Pilulku"},
	{"253", "Kouzelný Strup", "↑ +1 Zvýšení Štěstí#↑ +1 Zvýšení Zdraví"},
	{"254", "Krevní Sraženina", "↑ +1 Větší Poškození#↑ +5 Větší Dostřel#!!! Platí pouze pro levé oko"},
	{"255", "Šroub", "↑ +0.5 Více Slz#↑ +0.2 Větší Rychlost Střel"},
	{"256", "Horké Bomby", "Hořící bomby#+5 Bomb"},
	{"257", "Ohnivá Mysl", "Slzy zapalují nepřátele#Šance, že slzy vybouchnou při zásahu nepřítele#100% šance výbuchu při 13 Štěstí#!!! Výbuch vám může ublížit!"},
	{"258", "Chybějící č.", "Zamíchá všechny vaše předměty a statistiky při vyzvednutí tohoto předmětu a pokaždé, když změníte patro"},
	{"259", "Temná Hmota", "↑ +1 Větší Poškození#33% šance vystřelit zastrašující slzy"},
	{"260", "Černá Svíčka", "Imunita vůči Prokletí#+1 Černé Srdce#+15% šance na Ďábelskou/Andělskou Místnost"},
	{"261", "Proptóza", "↑ +100% Větší Poškození#↓ Udělené poškození se snižuje podle uražené vzdálenosti slzy"},
	{"262", "Chybějící Kapitola 2", "+1 Černé Srdce#Když zdraví klesne na 1 Srdce, udělí poškození všem nepřátelům v místnosti"},
	{"263", "", "<předmět neexistuje>"},
	{"264", "Chytrá Muška", "Orbitální moucha#Když dostanete zásah, zaútočí na nepřátele#Uděluje 22.5 poškození za sekundu"},
	{"265", "Vysušené Dítě", "Když jej zasáhnou nepřátelské slzy, má 10% šanci poškodit všechny nepřátele v místnosti"},
	{"266", "Šťavnatý Kokon", "Zanechává po sobě zpomalující kaluž#Po vyčištění místnosti vytvoří 1-2 přátelské pavouky"},
	{"267", "Robo-Děcko 2.0", "Střílí lasery#Uděluje 3.5 poškození za střelu#Pohybuje se ve směru, kterým střílíte"},
	{"268", "Shnilé Děcko", "Když hráč střílí, vytváří se modré mouchy"},
	{"269", "Bezhlavé Dítě", "Zanechává po sobě kaluž udělující 6 poškození za sekundu"},
	{"270", "Pijavice", "Vyléčí polovinu Srdce, když zabije nepřítele#Uděluje 3.2 poškození za sekundu"},
	{"271", "Tajemný Pytel", "Každých pár pokojů vytvoří náhodné pickupy"},
	{"272", "VKM", "Přátelská explodující moucha#Exploze způsobí 60 poškození"},
	{"273", "Bobův Mozek", "Společník jakožto vrhací bomba#Exploze způsobí 60 poškození"},
	{"274", "Nejlepší Kámoš", "Když dostanete zásah, získáte orbitální mušku střední vzdálenosti#Uděluje 75 poškození za sekundu"},
	{"275", "Maličký Leviatan", "Střílí krvavý laser#Jeho rána uděluje 31.5 poškození za sekundu"},
	{"276", "Isaacovo Srdce", "Získáte nezranitelné tělo#!!! Když je zasaženo Srdce, utrpíte poškození"},
	{"277", "Maličký Bubák", "Přátelský společenský duch#Uděluje 4 poškození za sekundu a způsobuje strach"},
	{"278", "Temný Žebrák", "Převádí 1.5 Červených Srdcí na Duševní/Černé srdce nebo pavouka"},
	{"279", "Velký Fanda", "Velká tlustá orbitální moucha#Uděluje 30 poškození za sekundu"},
	{"280", "Sissy Dlouhonožka", "Náhodně vytváří modré pavouky pokud je v nepřátelské místnosti"},
	{"281", "Boxovací Pytel", "Společník sloužící jakožto návnada#Místo na vás se nepřátelé zaměří na něj"},
	{"282", "Jak Skákat", "Umožňuje vám skákat"},
	{"283", "D100", "Zamíchá všechny pickupy, předměty a všechny vaše pasivní předměty"},
	{"284", "D4", "Zamíchá všechny vaše pasivní předměty"},
	{"285", "D10", "Zamíchá všechny nepřátele v místnosti"},
	{"286", "Prázdná Karta", "Napodobuje efekty vaší držené Karty"},
	{"287", "Kniha Tajemství", "Odhaluje části mapy"},
	{"288", "Bedna Plná Pavouků", "Vytvoří 1-4 modré pavouky"},
	{"289", "Červená Svíčka", "Vyhodíte červený plamen#Plamen přetrvává, dokud pětkrát nezpůsobí 23 poškození nebo pětkrát nezablokuje střelu"},
	{"290", "Sklenice", "Uloží až 4 Červené Srdce pro pozdější použití"},
	{"291", "Spláchnout!", "!!! Instantně zabíjí Hovnové nepřátele a bosse!#Proměňuje nepřátele v hovna"},
	{"292", "Satanská Bible", "+1 Černé Srdce"},
	{"293", "Krampusova Hlava", "Vystřelí krvavé lasery ve všech 4 směrech"},
	{"294", "Máslová Fazole", "Odrazí blízké nepřátele a jejich střely#10% šance na proměnění se v silnější {{Collectible484}}Počkat Co? při výměně za jiný aktivní předmět a opětovném sebrání"},
	{"295", "Kouzelné Prstíky", "Udělí 2x poškození hráče celé místnosti#Cena: 1 penízek"},
	{"296", "Konvertor", "!!! Přemění:#2 Duševní/Černé Srdce na 1 plné Místo pro Červené Srdce"},
	{"297", "Pandořina Skříňka", "!!! JEDNORÁZOVÉ POUŽITÍ, vytváří předměty podle patra:#B1: 2 Duševní Srdce#B2: 2 Bomby a 2 Klíče#C1: 1 Boss předmět#C2: B1+C1#D1: 4 Duševní Srdce#D2: 20 mincí#W1: 2 Boss předměty#W2: {{Collectible33}} Bible#???/Void: Nic#Sheol: 1 Ďábelský předmět + 1 Černé Srdce#Dark Room: Odemyká {{Collectible523}} Krabici na Stěhování#Cat: 1 Andělský předmět + 1 Srdce Věčnosti#Chest: 1 penízek"},
	{"298", "Jednorožčí Kopyto", "Nesmrtelnost a +0.28 Zvýšení Rychlosti na 6 sekund"},
	{"299", "Býk", "Budete zrychlovat v nepřátelských místnostech!#Nesmrtelnost pokud jste dostatečně rychlí#↓ -0.3 Snížení Rychlosti"},
	{"300", "Beran", "↑ +0.25 Zvýšení Rychlosti#Váš dotyk uděluje nepřátelům poškození"},
	{"301", "Rak", "+3 Duševní Srdce#Utrpíte pouze polovinu poškození v místnosti, ve které jste byli zasaženi"},
	{"302", "Lev", "Ničí kameny, když přes ně chodíte#Zvětšení"},
	{"303", "Panna", "Šance získat nesmrtelnost při zásahu#Převádí negativní Pilulky na pozitivní"},
	{"304", "Váha", "+6 Penízků / Klíčů / Bomb#Vyrovnává vaše statistiky!#!!! Každá další nově změněná statistika ovlivní i ostatní statistiky"},
	{"305", "Štír", "Jedovaté slzy"},
	{"306", "Střelec", "↑ +0.2 Zvýšení Rychlosti#Průrazné slzy"},
	{"307", "Kozoroh", "↑ +1 Zvýšení Zdraví / Klíč / Bomba / Penízek#↑ +0.5 Větší Poškození#↑ +0.1 Zvýšení Rychlosti#↑ +1.5 Větší Dostřel#↑ +1 Více Slz"},
	{"308", "Vodnář", "Zanecháváte po sobě stopu kaluže#Kaluž uděluje 6 poškození za sekundu"},
	{"309", "Ryba", "↑ +1 Více Slz#Slzy více odrážejí nepřátele"},
	{"310", "Evina Řasenka", "↑ +100% Větší Poškození#↓ -50% Méně Slz#↓ -0.5 Menší Rychlost Střel"},
	{"311", "Judasův Stín", "Když zemřete, znovuzrodíte se jako Černý Judas#↑ (Poškození x 2)"},
	{"312", "Maggyina Mašle", "↑ +1 Zvýšení Zdraví#Vyléčí 1 Červené Srdce#Všechna Červená Srdce nyní léčí dvojnásobek své hodnoty"},
	{"313", "Svatý Plášť", "Ignoruje první zásah v každé místnosti"},
	{"314", "Stehna Jako Hrom", "↑ +1 Zvýšení Zdraví#↓ -0.4 Snížení Rychlosti#Ničí kameny, když přes ně chodíte"},
	{"315", "Podivný Přitahovák", "Magnetické slzy#Ovlivňuje nepřátele, pickupy a trinkety"},
	{"316", "Prokleté Oko", "Nabitá salva slz#!!! Pokud vás něco zasáhne při nabíjení, teleportuje vás do náhodné místnosti"},
	{"317", "Záhadná Kapalina", "Slzy po sobě zanechávají kaluž#Kaluž uděluje 30 poškození za sekundu"},
	{"318", "Blíženec", "Spojenec pro blízký souboj#Uděluje 6 kontaktního poškození za sekundu "},
	{"319", "Cainovo Druhé Oko", "Odráží se po místnosti#Střílí směrem k Isaacovi#Jeho poškození se rovná vašemu poškození"},
	{"320", "Jediný Přítel ???", "Ovladatelná moucha#Uděluje 5 kontaktního poškození za sekundu"},
	{"321", "Samsonovy Řetězy", "Přetahovatelná koule, která dokáže ničit kameny#Uděluje 10.7 kontaktního poškození za sekundu"},
	{"322", "Divné Dítě", "Kopíruje efekt jednoho z vašich spojenců#Působí dvojnásobné poškození"},
	{"323", "Isaacovy Slzy", "Při použití vystřelíte 8 slz ve všech směrech#Nabíjí se při střílení"},
	{"324", "Nedefinováno", "Teleportuje vás do {{TreasureRoom}}Pokladnice, {{SecretRoom}}Tajné, {{SuperSecretRoom}}Super Tajné nebo JÁ JSEM ERROR Místnosti"},
	{"325", "Nůžky", "Uřízne vám hlavu#Hlava se změní na nehybného spojence#Ovládejte své tělo odděleně"},
	{"326", "Dech Života", "Pro nesmrtelnost podržte mezerník, dokud nebude nabíjecí lišta prázdná#!!! Nedržte to příliš dlouho!"},
	{"327", "Polaroid", "Nesmrtelnost při zásahu pokud máte půl Červeného Srdce nebo méně"},
	{"328", "Negativ", "Způsobí poškození všem nepřátelům v místnosti při zásahu pokud máte půl Červeného Srdce nebo méně"},
	{"329", "Technika Ludovico", "Kontrolovatelná Slza"},
	{"330", "Sójové Mléko", "↑ O HODNĚ Více Slz: (zdržení /4) - 2#↓ -80% Menší Poškození"},
	{"331", "Božství", "Naváděné slzy#↑ +0.5 Větší Poškození#↑ +1.2 Větší Dostřel#↓ -0.3 Méně Slz#↓ -30% Menší Rychlost Střel#↑ +0.8 Výška Slz#Slzy získávají poškozující auru"},
	{"332", "Lazarovy Hadry", "Když zemřete, znovuzrodíte se jako Lazarus (Povstaný)"},
	{"333", "Mysl", "Úplné mapování"},
	{"334", "Tělo", "↑ +3 Zvýšení Zdraví"},
	{"335", "Duše", "+2 Duševní Srdce#Poskytuje auru, která odpuzuje nepřátele a střely"},
	{"336", "Mrtvá Cibule", "Průrazné + spektrální slzy#↑ +0.25 Větší Dostřel#↓ -0.4 Menší Rychlost Střel#↑ +50% Zvětšení Slz"},
	{"337", "Rozbité Hodinky", "Zpomaluje nebo zrychluje každou 4. místnost"},
	{"338", "Bumerang", "Vrhací bumerang#Omráčí nepřátele a uděluje 2x vaše poškození při zásahu#Může sebrat předměty"},
	{"339", "Spínací Špendlík", "↑ +5.25 Větší Dostřel#↑ +0.16 Větší Rychlost Střel#↑ +0.5 Výška Slz#+1 Černé Srdce"},
	{"340", "Kofeinová Pilulka", "↑ +0.3 Zvýšení Rychlosti#↑ Zmenšení#Při sebrání vám dá náhodnou Pilulku"},
	{"341", "Roztrhaná Fotografie", "↑ +0.7 Více Slz#↑ +0.16 Větší Rychlost Střel"},
	{"342", "Modrý Klobouček", "↑ +1 Zvýšení Zdraví#↑ +0.7 Více Slz#↓ -16% Menší Rychlost Střel"},
	{"343", "Klíč od Petlice", "↑ +1 Zvýšení Štěstí#+1 Duševní Srdce#Vytvoří 2 Klíče"},
	{"344", "Knížečkové Zápalky", "+1 Černé Srdce#Vytvoří 2-3 Bomby"},
	{"345", "Syntetický Olej", "↑ +1 Větší Poškození#↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz"},
	{"346", "Svačina", "↑ +1 Zvýšení Zdraví"},
	{"347", "Diplopie", "!!! JEDNORÁZOVÉ POUŽITÍ !!!#Duplikuje všechny předměty/pickupy v aktuální místnosti"},
	{"348", "Placebo", "Napodobuje efekty vaší držené Pilulky"},
	{"349", "Dřevěný Niklák", "50% šance na vytvoření náhodného penízku"},
	{"350", "Toxický Šok", "Na začátku každé místnosti otrávíte každého nepřítele#Zabití nepřátelé po sobě zanechají poškozující kaluž"},
	{"351", "Mega Fazole", "Zmrazíte všechny nepřátele v aktuální místnosti#Uděluje 5 poškození a otráví všechny nepřátele v okolí#Vyšle vlnu bodců po místnosti#!!! Lze použít k otevření tajných místností"},
	{"352", "Skleněné Dělo", "↓ Sníží vaše zdraví na polovinu srdce#Vystřelí jednu velkou průraznou spektrální slzu ((Poškození+1) x 10)"},
	{"353", "Bomber Kluk", "+5 Bomb#Bomby nyní vybuchují ve tvaru kříže"},
	{"354", "Crack Jacks Popkorn", "↑ +1 Zvýšení Zdraví#Vytvoří jeden náhodný trinket"},
	{"355", "Máminy Perly", "↑ +1.25 Větší Dostřel#↑ +1 Zvýšení Štěstí#↑ +0.5 Výška Slz"},
	{"356", "Autobaterie", "Způsobí, že se váš aktivní předmět při použití aktivuje dvakrát"},
	{"357", "Krabice s Kamarády", "Duplikuje vaše spojence pro aktuální místnost#Pokud žádné spojence nemáte, objeví se {{Collectible113}}Démoní Děcko pro aktuální místnost"},
	{"358", "Čaroděj", "Střílíte 2 slzy najednou diagonálně, podobně jako JSI ČARODĚJ?#Spektrální slzy"},
	{"359", "8 Palcové Hřebíky", "↑ +1.5 Větší Poškození#Slzy více odrážejí nepřátele"},
	{"360", "Inkubus", "Střílí stejné slzy jako Isaac, z hlediska poškození, statistik a efektů"},
	{"361", "Odměna Osudu", "Vystřeluje slzy a kopíruje vaše poškození"},
	{"362", "Maličká Truhla", "Každých pár místností vytvoří náhodný pickup"},
	{"363", "Zapřísáhlý Ochránce", "Orbitální spojenec#Uděluje 105 kontaktního poškození za sekundu#Blokuje a přitahuje střely#Zablokováním 10 slz v jedné místnosti vytvoří Srdce Věčnosti"},
	{"364", "Prátelská Zóna", "Orbitální moucha#Uděluje 45 kontaktního poškození za sekundu"},
	{"365", "Ztracená Moucha", "Pohybuje se po stěnách/překážkách v místnosti#Uděluje 105 kontaktního poškození za sekundu"},
	{"366", "Rozptylové Bomby", "+5 Bomb#Způsobí, že vaše bomby explodují a poté vytvoří další 2-4 malé bomby"},
	{"367", "Lepkavé Bomby", "+5 Bomb#Když bomba zabije nepřítele, vytvoří modré pavouky#Vaše bomby se přilepí na nepřátele"},
	{"368", "Epifora", "Střelba jedním směrem postupně snižuje Zpoždění Slz až o 200 %"},
	{"369", "Kontinuum", "↑ +2.25 Větší Dostřel#↑ +1.5 Výška Slz#Slzy procházejí stěnami a objevují se z protější stěny"},
	{"370", "Panenka", "↑ +0.7 Více Slz#↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz#Po sebrání vytvoří 3 náhodná srdce"},
	{"371", "Prokletí Věže", "Pokaždé, když dostanete zásah, vyšlete 6 trollích bomb#Tyto bomby jsou ovlivněny bombovými předměty"},
	{"372", "Nabité Dítě", "Náhodná šance na vytvoření baterie nebo zmrazení všech nepřátel v místnosti#Šance přidat jedno nabití k vašemu aktivnímu předmětu"},
	{"373", "Ostrostřelec", "↑ +25% Větší Poškození za každou slzu, která úspěšně zasáhne nepřítele (max +100%)#Šance ztratit násobitel, když minete"},
	{"374", "Posvátné Světlo", "10% šance na vystřelení Posvaté slzy, která při zásahu vyšle paprsek světla#Paprsek způsobí 4x vaše poškození#50% šance při 9 Štěstí"},
	{"375", "Klobouk Hostitele", "Poskytuje imunitu proti výbuchům a imunitu proti dupání Mámy a Satanovy nohy#20% šance k zablokování slz"},
	{"376", "Doplnění Zásob", "Vytvoří 3 náhodné pickupy#Obchody okamžitě doplňují zásoby při nakupování"},
	{"377", "Prasklý Kokon", "Pavoučí nepřátelé již necílí na Isaaca ani mu nezpůsobují kontaktní poškození"},
	{"378", "Číslo Dva", "Střílení slz po dobu 3 sekund vytvoří Prdelní Bombu"},
	{"379", "Duplexní Pupila", "Slzy dostanou mnohem větší hitbox#Spektrální slzy"},
	{"380", "Zaplať za Hraní", "+5 penízků#Dveře můžete otevřít pomocí penízků namísto klíčů"},
	{"381", "Edenovo Požehnání", "↑ +0.7 Více Slz#Dá vám náhodný předmět na začátku vaší další hry"},
	{"382", "Kamarádská Koule", "Můžete vrhnout na nepřátele k jejich zachycení#Při dalším použití se znovu objeví stejný nepřítel jakožto přátelský společník"},
	{"383", "Slzní Rozbuška", "Odpalte všechny slzy aktuálně na obrazovce, což způsobí, že se každá rozdělí na 6 dalších slz, které se budou šířit do kruhu"},
	{"384", "Maličký Gurdy", "Vystřelí se a bude létat po místnosti#Uděluje 90 kontaktního poškození za sekundu"},
	{"385", "Bumbo", "Picks up nearby coins#Levels up after getting 6, 12, and 24 coins#LVL2: Chance to spawn item after room clears#LVL3: Fires tears that can drop coins on hit#LVL4: Chases enemies, occasionally dropping bombs, and can spawn item on coin pickup"},
	{"386", "D12", "Zamíchá jakýkoli objekt na jiný náhodný typ objektu (např. hovno, vázy, TNT, červené hovno, kamenné bloky atd.)"},
	{"387", "Kadidelnice", "Vytváří obrovskou světelnou auru, která zpomaluje nepřátele a projektily uvnitř"},
	{"388", "Klíčový Žebrák", "Převádí klíče na náhodné truhly"},
	{"389", "Pytel Run", "Vytvoří náhodnou runu každých 5-6 místností"},
	{"390", "Serafim", "Střílí slzy Nejsvětějšího Srdce#Uděluje 10 poškození za střelu"},
	{"391", "Zrada", "Pokaždé, když Isaac utrpí poškození, okouzlí každého nepřítele v místnosti"},
	{"392", "Zvěrokruh", "Dává vám náhodný efekt předmětu zvěrokruhu v každém patře"},
	{"393", "Hadí Polibek", "15% šance vystřelit jedovaté slzy#Otrávíte nepřátele při kontaktu#Nepřátelé, kteří byli otráveni, mají šanci vytvořit při smrti Černé Srdce"},
	{"394", "Označený", "Slzy automaticky míří na červený terč na zemi, který ovládá hráč#↑ +0.7 Více Slz#↑ +3.15 Větší Dostřel#↑ +0.3 Výška Slz"},
	{"395", "Tech X", "Získáte schopnost nabíjet a vystřelovat střely jakožto laserový prsten, který se pohybuje po místnosti"},
	{"396", "Komorová Břitva", "Vytvoří až dva portály pro cestování mezi nimi#Lze umístit do různých místností"},
	{"397", "Vlečný Paprsek", "Isaacovy slzy nyní putují přímo vpřed podle paprsku světla, ale budou se také pohybovat do stran v závislosti na pohybu vašeho hráče.#↑ +0.5 Více Slz#↑ +5.25 Větší Dostřel#↑ +0.16 Větší Rychlost Střel#↑ +0.5 Výška Slz"},
	{"398", "Boží Maso", "Slzy mohou nepřátele zmenšit#Scvrklé nepřátele lze rozdrtit a zabít tím, že po nich přejdete"},
	{"399", "Chřtán Prázdnoty", "↑ +1 Větší Poškození#Po 3 sekundách střílení slz se na Isaacově hlavě objeví červený kříž. Po uvolnění tlačítka střelby vytvoří prsten s černým laserem#Nepřátelé zabití černým prstenem mají šanci vytvořit Černé Srdce"},
	{"400", "Kopí Osudu", "Vytvoří před vámi kopí#Uděluje dvakrát vaše poškození#Šance zastrašit nepřátele při kontaktu"},
	{"401", "Výbušnina", "25% šance na vystřelení přilepující se bombové slzy#Přilepující se bombové slzy nezpůsobí poškození při zásahu"},
	{"402", "Chaos", "Předměty budou nyní vybírány z náhodných skupin předmětů#Vytvoří 1-6 náhodných pickupů"},
	{"403", "Pavoučí Bot", "Umožňuje vám vidět poškození způsobené slzami a ukazatele zdraví všech nepřátel#Vyvolává náhodný stavový efekt při kontaktu#Náhodně vytváří baterie"},
	{"404", "Prdící Děcko", "Blokuje projektily#Pokud je zasaženo, prdne si, což nepřátele okouzlí, otráví nebo odrazí zpět"},
	{"405", "Chyba Rozbíjející Hru", "Poskakuje po místnosti#Uděluje 120 kontaktního poškození za sekundu a aplikuje náhodný stavový efekt"},
	{"406", "D8", "Zamíchá vaše statistiky#Ovlivní pouze poškození, slzy, dosah a rychlost"},
	{"407", "Čistota", "↑ Zvyšuje jednu z vašich statistik v závislosti na barvě aury kolem vás#Když utrpíte poškození, získáte novou auru#{{ColorRed}}Červená{{CR}} = +4 Větší Poškození#{{ColorBlue}}Modrá{{CR}} = -4 Zpoždění Slz#{{ColorYellow}}Žlutá{{CR}} = +0.5 Zvýšení Rychlosti#{{ColorOrange}}Oranžová{{CR}} = +7.5 Větší Dostřel, +1 Výška Slz"},
	{"408", "Athame", "Když utrpíte poškození, objeví se kolem Isaaca prsten černého laseru#Nepřátelé zabití laserem mají šanci vytvořit Černé Srdce"},
	{"409", "Prázdná Nádoba", "+2 Černé Srdce#Když Isaac nemá Červené Srdce, získáte létání a šanci aktivovat štít"},
	{"410", "Oko Zla", "3.33% šance vystřelit oko, které střílí slzy stejným směrem jako Isaac"},
	{"411", "Chutná Krev", "↑ +0.5 Větší Poškození za každého zabitého nepřítele v aktuální místnosti#Maximálně +5 Větší Poškození po 10 zabitích"},
	{"412", "Početí Kambionu", "Po 15 utrpeného poškození získá Isaac stálého společenského démona#Max až 4 společníci"},
	{"413", "Neposkvrněné Početí", "Po sebrání 15 srdcí získá Isaac trvalého andělského společníka#Max až 5 společníků"},
	{"414", "Více Možností", "Dva předměty se nyní objeví ve všech {{TreasureRoom}}Pokladnicích#Můžete si vybrat pouze jeden"},
	{"415", "Koruna Světla", "+2 Duševní Srdce#Pokud nemáte žádné poškozené místa s Červenými Srdci:#↑ +100% Větší Poškození#↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz#↓ -0.3 Menší Rychlost Střel#Deaktivuje se pro aktuální místnost, pokud utrpíte poškození"},
	{"416", "Hluboké Kapsy", "Umožňuje vám nosit dvě karty/pilulky/runy"},
	{"417", "Sukuba", "Poskakuje po místnosti s poškozující aurou, která každou sekundu působí 129 % vašeho poškození#↑ +50 % poškození, když stojíte v auře"},
	{"418", "Ovocný Dort", "S každou slzou, kterou vystřelíte, vám poskytne jiný efekt pro další slzu"},
	{"419", "Teleport 2.0", "Teleportuje vás do jiné náhodné místnosti, která ještě nebyla prozkoumána#Hierarchie: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> JÁ JSEM ERROR"},
	{"420", "Černý Prášek", "Chůze v kruhu vytvoří na podlaze symbol pentagramu, který působí 10 poškození za tik"},
	{"421", "Červená Fazole", "Aplikuje efekt okouzlení na všechny nepřátele v blízkém dosahu a způsobí jim 5 poškození"},
	{"422", "Zářící Přesýpací Hodiny", "Přetočte čas a vraťte se zpět do předchozí místnosti, ve stejném stavu, ve kterém jste byli v tu chvíli"},
	{"423", "Kruh Ochrany", "Velký kruh kolem vás, způsobující poškození při kontaktu každou sekundu#Šance na odražení nepřátelských projektilů"},
	{"424", "Pytel na Hlavu", "Pickupy mají 33% šanci, že budou nahrazeny pytlíkem#Vytvoří pytlík"},
	{"425", "Noční Světlo", "Vytváří před vámi kužel světla, který zpomaluje nepřátele a projektily uvnitř něj#Odstraňuje Prokletí Temnoty pro aktuální patro"},
	{"426", "Posedlý Fanoušek", "Sleduje váš přesný pohyb s 3 sekundovým zpožděním#Uděluje 30 kontaktního poškození za sekundu"},
	{"427", "Mine Crafťák", "Vytvoří tlačitelný TNT barel#Pokud jej použijete podruhé ve stejné místnosti, zatímco tam je poslední TNT barel, na dálku exploduje"},
	{"428", "Pyžamo", "+4 Duševní Srdce#Plně obnoví vaše červená srdce"},
	{"429", "Keeperova Hlava", "Nepřátelé mají 5% šanci vytvořit penízek při zasažení vaší slzou"},
	{"430", "Táta Moucha", "Sleduje váš přesný pohyb s 1 sekundovým zpožděním#Střílí slzy na nepřátele poblíž, jeho slzy působí poškození rovnající se vašemu poškození"},
	{"431", "Multidimenzionální Dítě", "Sleduje váš přesný pohyb s 2 sekundovým zpožděním#Slzy, které jím projdou, se rozdělí a získají zvýšení rychlosti"},
	{"432", "Třpytivé Bomby", "+5 Bomb#Bomby mají šanci vytvořit náhodné pickupy, když explodují"},
	{"433", "Můj Stín", "Pokaždé, když utrpíte poškození, aplikujete efekt zastrašení na všechny nepřátele a vytvoříte přátelského černého červa#Červ uděluje 5 poškození za sekundu"},
	{"434", "Sklenice Much", "Pokaždé, když zabijete nepřítele, bude do nádoby přidána modrá muška#Max 20 much#Použití předmětu uvolní všechny mouchy"},
	{"435", "Maličký Loki", "Vystřelí 4 slzy do kříže#Uděluje 3.5 poškození za slzu"},
	{"436", "Mléko!", "Po utrpení poškození získáte Více Slz pro zbytek místnosti"},
	{"437", "D7", "Obnovuje všechny nepřátele v místnosti#Umožňuje vám nahromadit odměny za pročištěné místnosti#!!! Pokud se použije v boji proti Greedovi, může místnost přehodit na Obchod"},
	{"438", "Dudlík", "+1 Duševní Srdce#↑ +0.7 Více Slz#↑ Velmi Zmenšuje Isaaca a snižuje velikost jeho hitboxu"},
	{"439", "Mámina Krabička", "Vytvoří náhodný trinket#↑ +1 Štěstí při držení předmětu#Při držení předmětu zdvojnásobí účinek trinketů"},
	{"440", "Ledvinový Kámen", "Náhodně při střelbě přestanete střílet a uvolníte salvu slz a ledvinový kámen#↓ -0.2 Snížení Rychlosti#↓ -17 Menší Dostřel#↑ +2 Výška Slz"},
	{"441", "Mega Výstřel", "Vystřelí obrovský Mega Satanský laser na 15 sekund#Laser přetrvává mezi místnostmi a patry"},
	{"442", "Koruna Temného Prince", "!!! Zatímco máte přesně 1 plné Červené Srdce:#↑ +1.5 Větší Dostřel#↑ +0.75 Více Slz#↑ +0.2 Větší Rychlost Střel#↑ +1 Výška Slz#Nefunguje s postavami bez Červených životů"}, -- Dark Princes Crown (apostrophe added to the name in Repentance)
	{"443", "Jablko!", "Náhodně vystřelíte žiletku, která způsobí 400% poškození#↑ +0.3 Více Slz"},
	{"444", "Tužka", "Každých 15 vystřelených slz vystřelíte shluk slz#Každá slza ve shluku způsobí dvojnásobné poškození"},
	{"445", "Psí Zub", "↑ +0.3 Větší Poškození#↑ +0.1 Zvýšení Rychlosti#Vlk zavyje pokud stoupíte do místnosti, která je vedle {{SecretRoom}}{{SuperSecretRoom}}Tajné Místnosti#Při vstupu do místnosti s padacími dvířky vedoucí do průlezu pod kamenem se ozve štěkání"},
	{"446", "Mrtvý Zub", "Při střelbě získáte zelenou auru, která otráví všechny nepřátele v ní#Jed působí vaše poškození"},
	{"447", "Loudavá Fazole", "Při střelbě bez pauzy se každých 7.5 sekund vytvoří smradlavý oblak#Oblak způsobí 3.5 poškození pětkrát za sekundu#Oblak setrvává 15 sekund#Střelbou s ním lze pohybovat"},
	{"448", "Střípek Skla", "Při poškození máte šanci získat ↑ +5 Větší Dostřel a zanechat stopu krvavé kaluže, nebo vytvořit Červené Srdce"},
	{"449", "Kovový Plát", "+1 Duševní Srdce#Nepřátelské střely mají 25% šanci, že se odrazí jako matoucí slzy"},
	{"450", "Greedovo Oko", "Každých 20 slz vystřelte penízkovou slzu, která promění nepřátele ve zlato#To stojí 1 penízek#Zasažení nepřátelé po smrti vytvoří penízek"},
	{"451", "Tarotový Ubrus", "Vytvoří náhodnou kartu nebo runu při vyzvednutí#Zdvojnásobí účinek jakékoli použité karty"},
	{"452", "Křečové Žíly", "Při utrpení poškození vystřelte 10 slz v kruhu kolem sebe#Slzy způsobí 125% vašeho poškození"},
	{"453", "Otevřená Zlomenina", "Kostní slzy#Slzy se při zasažení čehokoli roztříští na 1-3 menší kostní úlomky#↑ +1.5 Větší Dostřel#↑ +1 Výška Slz"},
	{"454", "Polydaktylie", "Můžete nosit dvě karty, runy nebo pilulky#Při vyzvednutí vytvoří kartu, pilulku nebo runu"},
	{"455", "Tátova Ztracená Mince", "↑ +1.5 Větší Dostřel#↑ +1 Výška Slz#Vytvoří šťastný penízek"},
	{"456", "Plesnivý Chléb", "↑ +1 Zvýšení Zdraví"},
	{"457", "Kuželová Hlava", "+1 Duševní Srdce#20% šance na ignorování poškození"},
	{"458", "Pupík", "Vytvoří náhodný trinket při vyzvednutí#Udělí 1 místo na trinkety navíc"},
	{"459", "Sinusová Infekce", "20% šance vystřelit přilepující se jedovaté slzy#Uděluje vaše poškození každou sekundu#Drží se na nepříteli 60 sekund"},
	{"460", "Glaukom", "5% šance na vystřelení matoucí slzy"},
	{"461", "Parazitoid", "15% šance na vystřelení kokonu s vejci#Při zásahu se objeví zpomalující kaluž#Po zásahu vytvoří modrého pavouka nebo mouchu"},
	{"462", "Oko Beliála", "↑ +1.5 Větší Dostřel#↑ +1 Výška Slz#Poskytuje průrazné slzy#Po zasažení prvního nepřítele dále slza působí dvojnásobné poškození a získá naváděcí efekt"},
	{"463", "Kyselina Sírová", "↑ +0.3 Větší Poškození#Slzy mají šanci zničit kameny a otevřít dveře"},
	{"464", "Symbol Rovnováhy", "+2 Duševní Srdce#Šampioni častěji vytvářejí pickupy po jejich smrti"},
	{"465", "Analogová Páčka", "↑ +0.3 Více Slz#Umožňuje vám střílet slzy diagonálně střelbou ve dvou směrech"},
	{"466", "Nákaza", "První zabitý nepřítel v místnosti exploduje a otráví všechny okolní nepřátele"},
	{"467", "Prst!", "Uděluje konstantních 10 % vašeho poškození nepřátelům ve směru, na který prst ukazuje"},
	{"468", "Stínovač", "Sleduje váš přesný pohyb s 1 sekundovým zpožděním#Uděluje 30 kontaktního poškození za sekundu"},
	{"469", "Deprese", "Zanechává po sobě stopu kaluže#Kaluž uděluje 6 poškození za sekundu#Nepřátelé, kteří se dotknou mraku, mohou vytvořit Posvátný Světelný paprsek"},
	{"470", "Hushy", "Poskakuje po místnosti#Způsobuje kontaktní poškození#Při střelbě se přestane pohybovat#Když se zastaví, může blokovat projektily"},
	{"471", "Maličký Monstro", "Nabíjí své slzy a střílí ve stylu brokovnice {{Collectible229}}Monstrových Plic#Uděluje 3.5 poškození za slzu"},
	{"472", "Královské Dítě", "Ostatní spojenci ho následují#Přestane se pohybovat, když střílíte#Když přestanete střílet, teleportují se zpět k vám"},
	{"473", "Velký Tlouštík", "Spojenec, který se velmi pomalu vystřelí dopředu#Uděluje 40.5 kontaktního poškození za sekundu"},
	{"474", "Mandle", "Blokuje nepřátelské projektily"},
	{"475", "Plán C", "!!! JEDNO POUŽITÍ !!!#Způsobí 9,999,999 poškození všem nepřátelům a zabije vás o 3 sekundy později"},
	{"476", "D1", "Duplikuje 1 náhodný pickup v aktuální místnosti"},
	{"477", "Prázdnota", "!!! Při použití zkonzumujte všechny předměty v místnosti#Aktivní předmět: Jeho efekt bude přidán k efektu Prázdnoty (Skložení efektů)#↑ Pasivní předmět: Malé vylepšení náhodné statistiky"},
	{"478", "Pauza", "Zmrazí všechny nepřátele v místnosti, dokud nezačnete znovu střílet#Kontakt se zmrzlým nepřítelem vám ublíží#Nepřátelé se po 30 sekundách rozmrazí"},
	{"479", "Tavící Pec", "Spotřebuje váš trinket a přidá vám jeho efekt trvale#Objevuje se více trinketů"},
	{"480", "Kompost", "Převádí pickupy na modré mouchy nebo pavouky#Zdvojnásobuje vaše současné modré mouchy/pavouky#Vytváří 1 modrou mušku nebo pavouka, pokud žádného nemáte"},
	{"481", "Data Těžič", "Při použití ↑/↓ malé vylepšení náhodné statistiky#Slzy mají náhodný efekt pro aktuální místnost#Posere všechny textury"},
	{"482", "TV Ovladač", "Promění vás v jinou postavu#Odstraní poslední předmět, který jste sebrali"},
	{"483", "Máma Mega!", "!!! JEDNO POUŽITÍ !!!#Ovlivňuje celé patro#Všechny objekty explodují#Uděluje 200 poškození všem nepřátelům#Otevírá dveře do Boss Rush, Hush a všech Tajných Místností"},
	{"484", "Počkat Co?", "Po použití odstrčí nepřátele a vytvoří vlnu kamení#Dokáže otevřít místnosti a rozbít kameny"},
	{"485", "Pokřivená Mince", "50% šance na zdvojnásobení všech předmětů, pickupy a truhel v místnosti#50% šance na odstranění předmětů/pickupů/truhly v místnosti a vytvoření 1 mince"},
	{"486", "Tupá Žiletka", "Zraní vás, aniž by vám udělila poškození#Může spustit určité efekty předmětů"},
	{"487", "Škrabka na Brambory", "Odebere jedno místo s Červeným Srdcem a dá vám ↑ +0,2 poškození a {{Collectible73}}Kostku Masa"},
	{"488", "Metronom", "Udělí vám efekt náhodného předmětu pro aktuální místnost"},
	{"489", "D Nekonečno", "Náhodný efekt hracích kostek při každém použití"},
	{"490", "Edenova Duše", "!!! JEDNO POUŽITÍ !!!#Vytvoří 2 náhodné předměty v závislosti na aktuální skupině předmětů v místnosti"},
	{"491", "LSD Dítě", "Každé 3 místnosti vytvoří náhodnou pilulku#Použití pilulky otráví všechny nepřátele v místnosti"},
	{"492", "HEJ POSLOUCHEJ!", "↑ +1 Zvýšení Štěstí#Zvýrazňuje umístění Tajných Místností, zbarvených kamenů a padacích dvířek vedoucí do průlezu"},
	{"493", "Adrenalin", "Za každé prázdné místo na Srdce:#↑ +0.2 Větší Poškození"},
	{"494", "Jacobův Žebřík", "Slzy při zásahu způsobí 1-2 jiskry elektřiny#Jiskry způsobí polovinu vašeho poškození"},
	{"495", "Paprička Duchů", "Šance vystřelit červený plamen, který blokuje nepřátelské výstřely a působí kontaktní poškození#Plamen zůstane, dokud pětkrát nezpůsobí poškození nebo nezablokuje střelu"},
	{"496", "Eutanazie", "3,33% šance na vystřelení jehly#100% šance při 15 Štěstí#Jehly okamžitě zabijí normální nepřátele a roztříští je do 10 slz#Jehly způsobí 3x poškození Bossům"},
	{"497", "Kamuflážní Spodní Prádlo", "Zmate všechny nepřátele a maskuje vás při vstupu do místnosti, dokud nezačnete střílet"},
	{"498", "Dualita", "Vytvoří dveře do {{DevilRoom}}Ďábelské a {{AngelRoom}}Andělské Místnosti#Při vstupu do prvních dveří zmizí druhé"},
	{"499", "Eucharistie", "↑ 100% šance na {{AngelRoom}}Anďělksou Místnost"},
	{"500", "Pytel Pytlů", "Vytvoří pytlík každých 5-6 místností"},
	{"501", "Greedovo Jícen", "Za každých 25 penízků vám přidá 1 místo pro Srdce#Greed získá další místo na Penízkové Srdce"},
	{"502", "Velký Jebák", "Při střelbě občas vystřelte bílou slzu s bílou kaluží, která způsobí dvojnásobné poškození#Při utrpení poškození vystřelte bílou slzu"},
	{"503", "Malý Roh", "5% šance vystřelit slzu, která okamžitě zabijí nepřátele#Při kontaktu s nepřáteli působíte 3.5 poškození"},
	{"504", "Hnědá Hrudka", "Vytvoří mouchu, která stojí na místě a střílí na nepřátele#Každý výstřel způsobí 2 poškození"},
	{"505", "Poke Go", "Možnost vytvoření očarovaného nepřítele při vstupu do nepřátelské místnosti"},
	{"506", "Bodač do Zad", "Pokud slzy zasáhnou nepřítele do zad, způsobí jim dvojnásobné poškození a také krvácení, které každých 5 sekund způsobí 10% poškození z maximálního zdraví nepřítele."},
	{"507", "Ostré Brčko", "Způsobí vaše poškození + 10 % maximálního zdraví nepřítele#Ovlivňuje všechny nepřátele v místnosti#Šance vytvoření půlky srdcí, když způsobí poškození"},
	{"508", "Maminčina Žiletka", "Orbitální žiletka, která způsobuje krvácení, které způsobí 10% poškození maximálního zdraví nepřítele každých 5 sekund#Uděluje 300% poškození při kontaktu za sekundu#Neblokuje střely"},
	{"509", "Krví Podlité Oko", "Orbitální oko, které vystřelí slzu každé 2 sekundy v náhodném směru#Uděluje 3.5 poškození za slzu#Uděluje 30 kontaktního poškození za sekundu"},
	{"510", "Blouznivec", "Vytvoří přátelskou verzi Bosse Deliria pro aktuální místnost"},
	{"511", "Naštvaná Moucha", "Obíhá kolem náhodného nepřítele, dokud tento nepřítel nezemře#Uděluje 30 kontaktního poškození za sekundu ostatním nepřátelům"},
	{"512", "Černá Díra", "Vrhatelná černá díra, která všechno nasává#Uděluje 0.4 poškození každý tik#Zničí okolní kameny#Vydrží 6 sekund"},
	{"513", "Klaun Bozo", "↑ +0.1 Větší Poškození#+1 Duševní Srdce#Náhodná šance na okouzlení/zastrašení nepřítele#Náhodná šance na vytvoření duhového hovínka při utrpení poškození"},
	{"514", "Rozbitý Modem", "Způsobuje, že se náhodní nepřátelé 'lagují' v náhodných intervalech, což způsobí jejich krátké zamrznutí#Šance na zmrazení a odstranění nepřátelských střel#25% šance na zdvojnásobení odměn z místnosti"},
	{"515", "Tajemný Dárek", "!!! JEDNO POUŽITÍ !!!#Vytvoří náhodný předmět ze skupiny předmětů aktuální místnosti#Šance místo toho vytvořit Hroudu Uhlí nebo Hovna"},
	{"516", "Rozstřikovač", "Vytvoří Rozstřikovač, který se otáčí v kruhu a rozstřikuje vaše slzy na všechny strany"},
	{"517", "Rychlé Bomby", "+7 Bomb#Umožňuje vám rychle umisťovat bomby"},
	{"518", "Kamarád v Bedně", "Spojenec, který vypadá jako náhodné Dítě z coopu#Má náhodný efekt slz#Každé patro se náhodně mění"},
	{"519", "Maličký Delirium", "Spojenec, který se každých 10 sekund promění v dalšího náhodného spojence"},
	{"520", "Startovací Kabely", "+1 nabití na váš aktivní předmět za každých 15 zabitých nepřátel"},
	{"521", "Kupón", "Při použití udělá jeden náhodný předmět v {{Shop}}Obchodě nebo {{DevilRoom}}Ďábelské Místnosti zcela zdarma"},
	{"522", "Telekineze", "Nepřátelské střely blízko vás jsou drženy na místě po dobu 3 sekund#Poté jsou od vás odhozeny#Po 3 sekundách se předmět znovu nabije"},
	{"523", "Stěhovací Krabice", "Při použití uloží všechny pickupy z aktuální místnosti#Opětovným použitím je vrátíte zpět na podlahu#To vám umožní přesouvat věci mezi místnostmi"},
	{"524", "Technologie Nula", "Slzy budou spojeny elektřinou#Poškození elektřinou se rovná vašemu poškození"},
	{"525", "Lepra", "Utrpené poškození vytvoří orbitální kouli blokující střely#Maximálně 3 koule současně#Koule jsou zničeny, pokud utrpí příliš velké poškození"},
	{"526", "Pečeť 7", "Vytvoří malého jezdce, který vytváří jeho speciální kobylky#Jezdec se mění každých 10 sekund"},
	{"527", "Pan JÁ!", "!!! Spojenec, který za vás může dělat úkoly:#Otevírání dveří a truhel, přinášení předmětů, kradení z obchodu / od ďábla, bojuje s nepřáteli, exploduje a aktivuje nášlapné desky"},
	{"528", "Andělský Hranol", "Orbitální hranol#Slzy, které na něj dopadají, se rozdělí na 4"},
	{"529", "Plup!", "Slzy se budou chovat jako kulečníkové koule"},
	{"530", "Seznam Smrti", "Uděluje vám odměnu, pokud zabijete nepřátele v pořadí, ve kterém jsou označeni"},
	{"531", "Hemolakrie", "Slzy létají obloukem#Slzy při dopadu propukají v další menší slzy#↓ Méně Slz#↑ 31% Větší Poškození"},
	{"532", "Lachryfagie", "Slzy se při cestování zpomalují#Po zastavení explodují v 8 menších slzách#Slzy mohou být střeleny do jiných slz, čímž se zvětší"},
	{"533", "Trisagion", "Střílíte průrazné záblesky světla#Udělují 33% poškození, ale mohou zasáhnout nepřátele několikrát"},
	{"534", "Školní Aktovka", "Umožňuje vám držet 2 aktivní předměty#Přepínejte mezi nimi stisknutím tlačítka Drop (tlačítko držte za \"The Forgotten\")"},
	{"535", "Přikrývka", "+1 Duševní Srdce#Léčí 1 Červené Srdce#Uděluje štít při vstupu do místnosti s Bossem"},
	{"536", "Obětní Oltář", "!!! JEDNO POUŽITÍ !!!#Obětujte 1-2 spojence, abyste vytvořili Ďábelský předmět#Proměňte své modré pavouky/mouchy na penízky"},
	{"537", "Maličký Plivač", "Vytvoří náhodnou pilulku#Spojenec, který střílí řadu kaluží#Typ kaluže se změní pokaždé, když hráč použije pilulku"},
	{"538", "Kuličky", "Vytvoří 3 náhodné trinkety#Utrpení poškození může spotřebovat váš trinket a přidá vám jeho efekt trvale"},
	{"539", "Tajemné Vejce", "Když dostanete zásah, vytvořte okouzleného nepřítele#Vytvoří silnější přátele, čím více místností je vyčištěno bez poškození"},
	{"540", "Plochý Kámen", "Slzy se odrážejí od podlahy#Slzy způsobují poškození při každém odrazu"},
	{"541", "Kostní Dřeň", "+1 Kostěné Srdce#Vytvoří 3 Červené Srdce"},
	{"542", "Vyklouzlé Žebro", "Orbitální kost#Odráží střely"},
	{"543", "Posvátná Země", "Vytvoří bílé hovínko, když utrpíte poškození# (Bílé hovínko má auru ↑ Více Slz a může blokovat poškození)"},
	{"544", "Špičaté Žebro", "Ostré žebro, které levituje před Isaacem#Uděluje vaše poškození šestkrát za sekundu"},
	{"545", "Kniha Mrtvých", "Za každého zabitého nepřítele v aktuální místnosti vytvoří orbitální kost nebo okouzleného kostlivce"},
	{"546", "Tátův Prsten", "Poskytuje auru, která zmrazí nepřátele na místě"},
	{"547", "Rozvodové Papíry", "+1 Kostěné Srdce#↑ +0.7 Více Slz#Vytvoří trinket Tajemný Papír"},
	{"548", "Čelistní Kost", "Spojenec jakožto bumerang#Uděluje 7 kontaktního poškození#Umí přinést pickupy"},
	{"549", "Křehké Kosti", "Nahradí všechna vaše místa s Červenými Srdci za 6 Kostěných Srdcí#Při ztrátě Kostěného Srdce:#Vystřelí 8 kostních slz ve všech směrech#↑ +0.5 Více Slz trvale"},
	{"550", "Rozbitá Lopata", "Mámina Noha na vás bude neustále šlapat#Použití zastaví Máminu Nohu pro aktuální pokoj#!!! (Zkuste s tímto předmětem porazit Boss Rush!)"},
	{"551", "Rozbitá Lopata", "Druhá část rozbité lopaty#!!! Použijte lopatu na kopec hlíny v \"Dark Room\""},
	{"552", "Mámina Lopata", "Vytvoří padací dvířka do dalšího patra#!!! Použijte lopatu na kopec hlíny v \"Dark Room\"#!!! Odemyká něco hustého"},
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "Spolknutý Penízek", "Vytvoří 1 penízek, když dostanete zásah"},
	{"2", "Zkamenělé Hovínko", "50% šance na odměnu z ničení hoven"},
	{"3", "AAA Baterie", "-1 potřebné nabití pro aktivní předměty"},
	{"4", "Rozbitý Ovladač", "Náhodně vás teleportuje při použití aktivního předmětu"},
	{"5", "Fialové Srdce", "2x šance na nepřátelské šampiony"},
	{"6", "Rozbitý Magnet", "Magnet na peníze"},
	{"7", "Korálek z Růžence", "50% větší šance na {{AngelRoom}}Andělskou Místnost#Větší šance k nalezení {{Collectible33}}Bible v {{Shop}}Obchodech a {{Library}}Knihovnách"},
	{"8", "Kazeta", "5% šance na efekt Gamekidu při zásahu"},
	{"9", "Pulzující Červ", "Pulzující slzy#Ovlivňuje hitbox slz"},
	{"10", "Vrtící Červ", "Slzy se pohybují ve vlnách#↑ +0.3 Více Slz"},
	{"11", "Kroužící Červ", "Slzy se vysokou rychlostí pohybují ve spirálách"},
	{"12", "Plochý Červ", "50% širší slzy#Slzy více odrážejí nepřátele"},
	{"13", "Obchodní Kredit", "Jeden předmět z obchodu je zdarma"},
	{"14", "Mozol", "Zabraňuje poškození z kaluží a bodáků"},
	{"15", "Zdárný Kámen", "Ničením kamenů vytváří penízky"},
	{"16", "Mámin Nehet", "Mámina Noha dupe na nepřátele každých 60 sekund"},
	{"17", "Černá Rtěnka", "+1% šance na Černá Srdce"}, -- base chance is 0.5%
	{"18", "Trakt z Bible", "+3% šance na Srdce Věčnosti"}, -- base chance is 1.667%
	{"19", "Kancelářská Svorka", "Odemyká truhly bez použití klíčů"},
	{"20", "Opičí Tlapka", "Když jste na polovině srdce, vytvoří 1 Černé Srdce#!!! 3 použití"},
	{"21", "Tajemný Papír", "Náhodně imituje {{Collectible327}}Polaroid,#{{Blank}} {{Collectible328}}Negativ,#{{Blank}} {{Trinket48}}Chybějící Kapitolu nebo {{Trinket23}}Pohřešující Plakát"},
	{"22", "Démonův Ocas", "Snižuje šanci na vytvoření srdcí na 20%#Větší šance na klíče#Spadlé Srdce se mění na Černé Srdce"},
	{"23", "Pohřešující Plakát", "Znovuzrodíte se jako \"The Lost\", když zemřete v {{SacrificeRoom}}Obětovní Místnosti#Pokud je odemčený, znovuzrodíte se za něj i mimo Obětovní Místnosti"},
	{"24", "Prdelní Penízek", "O 20% větší šance na penízky z ničení hoven#Když vezmete penízek, prdnete si#Prd pouze odráží nepřátele"},
	{"25", "Tajemná Sladkost", "Prdněte si nebo vytvořte hovno každých 30 sekund"},
	{"26", "Hákový Červ", "Slzy se pohybují v hranatých vzorech#↑ +10 Větší Dostřel"},
	{"27", "Bičový Červ", "↑ +0.5 Větší Rychlost Střel"},
	{"28", "Rozbitý Anch", "22% šance na znovuzrození jako \"Blue Baby\""},
	{"29", "Rybí Hlava", "Při zásahu vytvoří 1 modrou mušku"},
	{"30", "Zrudlé Oko", "10% šance na vystřelení jedovatých slz"},
	{"31", "Špendlík", "10% šance na vystřelení spektrálních slz"},
	{"32", "Klobouček Svobody", "25% šance na náhodný efekt houby za místnost#Může odhalit speciální místnosti na minimapě"},
	{"33", "Pupeční Šňůra", "Když utrpíte poškození až k polovině Červeného Srdce, dostanete#{{Blank}} {{Collectible100}}Malého Stevena pro konkrétní místnost"},
	{"34", "Dětské Srdce", "10% šance na náhodné srdce jakožto odměnu za vyčištění místnosti#Šance na bonusové srdce z truhel, zbarvených kamenů a rozbitých strojů"},
	{"35", "Zakřivený Roh", "↑ +2 Větší Poškození"},
	{"36", "Zrezivělý Klíč", "10% šance na klíč jakožto odměnu za vyčištění místnosti#Šance na bonusový klíč z truhel, zbarvených kamenů a rozbitých strojů"},
	{"37", "Kozí Kopyto", "↑ +0.15 Zvýšení Rychlosti"},
	{"38", "Mámina Perla", "+10% šance na Duševní, Černé a Kostěné Srdce"}, -- base chance is 10%
	{"39", "Rakovina", "↑ -2 Zpoždění Slz"},
	{"40", "Červená Záplata", "20% šance na získání +1.8 Větší Poškození, když dostanete zásah#100% šance při 8 Štěstí#Efekt trvá pro aktuální místnost"},
	{"41", "Zápalka", "10% šance na bombu jakožto odměnu za vyčištění místnosti#Šance na bonusovou bombu z truhel, zbarvených kamenů a rozbitých strojů#!!! Odstraňuje {{Trinket53}}Klíště"},
	{"42", "Šťastný Palec u Nohy", "↑ +1 Zvýšení Štěstí#+8% šance na odměnu z vyčištěné místnosti#Extra pickupy z truhel, zbarvených kamenů a rozbitých strojů"},
	{"43", "Prokletá Lebka", "Když utrpíte poškození až k polovině Červeného Srdce nebo méně, teleportuje vás do náhodné místnosti"},
	{"44", "Bezpečnostní Uzávěr", "10% šance na pilulku jakožto odměnu za vyčištění místnosti#Šance na bonusovou pilulku z truhel, zbarvených kamenů a rozbitých strojů"},
	{"45", "Pikové Eso", "10% šance na kartu jakožto odměnu za vyčištění místnosti#Šance na bonusovou kartu z truhel, zbarvených kamenů a rozbitých strojů"},
	{"46", "Isaacova Vidlička", "10% šance na vyléčení poloviny srdce po vyčištění místnosti"},
	{"47", "", "<předmět neexistuje>"},
	{"48", "Chybějící Kapitola", "Když dostanete zásah, máte 5% šanci na udělení 40 poškození všem nepřátelům v místnosti"},
	{"49", "Krvavý Penízek", "50% šance na vytvoření půlky srdce, když vezmete penízek"},
	{"50", "Spálený Penízek", "50% šance na vytvoření bomby, když vezmete penízek"},
	{"51", "Plochý Penízek", "50% šance na vytvoření klíče, když vezmete penízek"},
	{"52", "Padělaný Penízek", "50% šance na získání +1 penízku, když vezmete penízek"},
	{"53", "Klíště", "-15% životů Bossů#Vyléčí 1 Červené Srdce při vstupu do {{BossRoom}}Boss Místnosti#!!! Pokud Klíště vezmete, nemůžete ho položit#Lze odstranit pouze {{Trinket41}}Zápalkou nebo spolknutím"},
	{"54", "Isaacova Hlava", "Spojenec s průraznými slzami#Uděluje 3.5 poškození za slzu"},
	{"55", "Maggyina Víra", "Získejte 1 Srdce Večnosti na začátku každého patra"},
	{"56", "Judasův Jazyk", "Snižuje ceny Dohod s Ďáblem ze 2 srdcí na 1 srdce"},
	{"57", "Duše ???", "Společník, který skáče po místnosti#Střílí stejným směrem jako hráč#Uděluje 3.5 poškození za slzu"},
	{"58", "Samsonova Kadeř", "1/15 šance na +0.5 Větší Poškození při zabití nepřítele#100% šance při 10 Štěstí#Efekt trvá pro aktuální místnost"},
	{"59", "Cainovo Oko", "25% šance odhalit ikony na mapě na začátku nového patra#100% šance při 3 Štěstí"},
	{"60", "Eveina Ptačí Noha", "5% šance na vytvoření {{Collectible117}}Mrtvého Ptáka při zabití nepřítele#100% šance při 8 Štěstí"},
	{"61", "Levá Ruka", "Přemění všechny truhly na červené truhly"},
	{"62", "Lesklý Kamínek", "Kameny skrývající průlez a zbarvené kameny budou blikat každých 10 sekund"},
	{"63", "Bezpečnostní Nůžky", "Přemění všechny trollí bomby na bomby jakožto pickupy"},
	{"64", "Duhový Červ", "Náhodný červí efekt každé 3 sekundy"},
	{"65", "Tasemnice", "↑ Zdvojnásobí váš dostřel#-50% Výška Slz"},
	{"66", "Líný Červ", "↓ -0.4 Menší Rychlost Střel#↑ +4 Větší Dostřel#↑ +2 Výška Slz"},
	{"67", "Prasklá Kostka", "50% na použití {{Collectible105}}D6, {{Collectible406}}D8, {{Collectible386}}D12 nebo {{Collectible166}}D20 při utrpení zásahu"},
	{"68", "Super Magnet", "Magnet na pickupy a nepřátele"},
	{"69", "Vybledlý Polaroid", "Náhodně maskuje hráče#Mate nepřátele"},
	{"70", "Veš", "Šance na vytvoření 1 modrého pavouka, když jste v nepřátelské místnosti"},
	{"71", "Bobův Měchýř", "Bomby po sobě zanechávají kaluž"},
	{"72", "Baterka do Hodinek", "6.66% šance na baterku jakožto odměnu za vyčištění místnosti#+10% šance, aby se z pickupů stala baterka#5% šance k přidání 1 nabití k aktivnímu předmětu po vyčištění místnosti"},
	{"73", "Rozbuška", "10% šance na vytvoření bomby jakožto pickup po explodování bomby"},
	{"74", "Detektor Kovů", "0.5% šance na odhalení průlezu po zničení kamene"},
	{"75", "Chyba", "Efekt náhodného trinketu každou místnost"},
	{"76", "Pokerový Žeton", "Truhly mají 50/50 šanci k vytvoření extra pickupů NEBO zlé mouchy"},
	{"77", "Puchýř", "Slzy více odrážejí nepřátele"},
	{"78", "Vteřinová Ručička", "2x delší statusové efekty na nepřátelích"},
	{"79", "Nekonečný Bezejmenný", "25% šance, že když použijete pilulku/kartu, tak se vytvoří kopie této karty/pilulky"},
	{"80", "Černé Pírko", "↑ +0.2 Větší Poškození za každý držený předmět zla"},
	{"81", "Slepý Hněv", "Nesmrtelnost trvá po zásahu 2x déle"},
	{"82", "Zlatá Podkova", "+15% šance, aby {{TreasureRoom}}Pokladnice obsahovala dva předměty v budoucích patrech#Můžete si vybrat pouze jeden"},
	{"83", "Klíč od Obchodu", "Otevřete {{Shop}}Obchody zadarmo"},
	{"84", "Greedovo Žebro", "Greed a Super Greed se nemohou objevit v {{Shop}}Obchodech nebo {{SecretRoom}}Tajných Místnostech#O 5% více penízků a méně srdcí jakožto odměny z vyčištěných místností"},
	{"85", "Karma", "Používaní Darovacích Strojů může vyléčit 1 srdce, dát 1 penízek, dát +1 Zvýšení Štěstí nebo vytvořit Žebráka"},
	{"86", "Malá Larva", "Zničení hovna vytvoří 1 modrou mouchu"},
	{"87", "Maminčin Medailon", "Vyléčí půlku srdce když používáte klíče#Přeměňuje půlky srdcí na celé srdce"},
	{"88", "NE!", "Zabraňuje objevení aktivních předmětů"},
	{"89", "Dětské Vodítko", "Společníci zůstávají blíže k vám"},
	{"90", "Hnědá Rozbuška", "Hovna explodují a udělí 100 poškození při zničení"},
	{"91", "Smolka", "33% na vytvoření Černých Hoven#5% šance na vytvoření Černého Srdce, když zničíte Černé Hovno"},
	{"92", "Nakřáplá Koruna", "↑ Zvýšení statistik z vašich předmětů je o 33% více efektivnější#↑ +0.2 Více Slz#↑ -1 Zpoždění Slz"},
	{"93", "Použitá Plenka", "15% šance za místnost, aby se všechny nepřátelské Mouchy staly přátelské"},
	{"94", "Rybí Ocas", "Zdvojnásobí všechny vytvořené Modré Mouchy / Pavouky"},
	{"95", "Černý Zub", "3% šance na vystřelení jedovatých zubů"},
	{"96", "Červ Ouroboros", "Slzy se rychle pohybují ve spirálové paterně#Spektrální slzy#↑ +4 Větší Dostřel#↑ +2 Výška Slz"},
	{"97", "Mandle", "Dostanete společníka blokujícího střely po tom co utrpíte 12-20x poškození#Až +2 společníci"},
	{"98", "Golbin z Nosu", "10% šance vystřelit naváděné přilepující se jedovaté slzy#Uděluje vaše poškození každou sekundu#Drží se na nepříteli 60 sekund"},
	{"99", "Super Míček", "10% šance na vystřelení skákající slzy"},
	{"100", "Živá Žárovka", "!!! Při držení plně nabitého aktivního předmětu:#↑ +0.5 Větší Poškození#↑ +0.25 Zvýšení Rychlosti#↑ +0.75 Větší Dostřel#↑ +0.2 Více Slz#↑ +0.1 Větší Rychlost Střel#↑ +1 Zvýšení Štěstí"},
	{"101", "Ztlumená Žárovka", "!!! Při držení úplně vybitého aktivního předmětu:#↑ +1.5 Větší Poškození#↑ +0.5 Zvýšení Rychlosti#↑ +1.5 Větší Dostřel#↑ +0.4 Více Slz#↑ +0.3 Větší Rychlost Střel	#↑ +2 Zvýšení Štěstí"},
	{"102", "Roztržená Karta", "+1 extra {{SecretRoom}}Tajná Místnost za patro pokud trinket držíte"},
	{"103", "Rovnost!", "!!! Když počet penízků, klíčů a bomb je roven:#Promění pickupy na jejich dvojité verze"},
	{"104", "Kost Přání", "2% šance na vytvoření předmětu, když dostanete zásah#Trinket bude poté zničen"},
	{"105", "Oběd v Sáčku", "2% šance na vytvoření {{Collectible22}}Obědu, když dostanete zásah#Trinket bude poté zničen"},
	{"106", "Ztracený Korek", "Zvětší dosah jakékoli kaluže, kterou vytvoříte"},
	{"107", "Vraní Srdce", "Utrpené poškození bude ignorovat Duševní/Černá Srdce, což způsobí, že vaše Červená Srdce budou vyčerpány jako první"},
	{"108", "Vlašský Ořech", "Po zásahu 1-9 výbuchy vytvoří klíč, penízek, srdce a náhodný trinket#Není vyžadováno dostávat poškození#Trinket bude poté zničen"},
	{"109", "Lepící Páska", "Způsobí, že se každý spojenec přestane pohybovat"},
	{"110", "Stříbrný Dolar", "{{Shop}}Obchody se nyní objevují ve Womb"},
	{"111", "Krvavá Koruna", "{{TreasureRoom}}Pokladnice se nyní objevují ve Womb"},
	{"112", "Zaplať za Výhru", "Doplňovací boxy se vždy objeví v {{TreasureRoom}}Pokladnicích"},
	{"113", "Kobylka Války", "Vytvoří explodující útočící kobylku, když vejdete do nepřátelské místnosti#Kobylka uděluje dvojnásobek vašeho poškození + poškození exploze"},
	{"114", "Kobylka Moru", "Vytvoří jedovatou útočící kobylku, když vejdete do nepřátelské místnosti#Kobylka uděluje dvojnásobek vašeho poškození"},
	{"115", "Kobylka Hladomoru", "Vytvoří zpomalující útočící kobylku, když vejdete do nepřátelské místnosti#Kobylka uděluje dvojnásobek vašeho poškození"},
	{"116", "Kobylka Smrti", "Vytvoří útočící kobylku, když vejdete do nepřátelské místnosti#Kobylka uděluje čtyřnásobek vašeho poškození"},
	{"117", "Kobylka Podmanění", "Vytvoří 1-4 útočící kobylky, když vejdete do nepřátelské místnosti#Kobylka uděluje dvojnásobek vašeho poškození"},
	{"118", "Netopýří Křídlo", "5% šance k získání létání po zabití nepřítele#Přetrvává pro aktuální místnost"},
	{"119", "Kmenová Buňka", "Vyléčí půl srdce při cestě do dalšího patra"},
	{"120", "Sponka do Vlasů", "Plně dobíjí váš aktivní předmět na začátku souboje s bossem"},
	{"121", "Dřevěný Kříž", "Chrání vás před prvním poškozením, které utrpíte za každé patro"},
	{"122", "Máslo!", "Použitím aktivního předmětu jej upustíte, poté ho můžete opět sebrat#Při utrpení poškození máte 2% šanci, že upustíte jeden z vašich pasivních předmětů"},
	{"123", "Filigránové Peříčko", "Způsobí, že vás Andělští bossové po jejich zabití namísto Částí Klíčů odmění normálními Andělskými předměty"},
	{"124", "Zarážka za Dveře", "Poslední dveře, které jste použili, zůstanou otevřené"},
	{"125", "Prodlužovačka", "Propojuje vaše spojence paprsky elektřiny#Způsobí 6 poškození na paprsek"},
	{"126", "Zkažený Penízek", "Vytvoří modrou mouchu, když vezmete penízek"},
	{"127", "Dětská Ohýbací Lžička", "Uděluje vašim spojencům naváděné střely"},
	{"128", "Kost Prstu", "2% šance na získání Kostěného Srdce když utrpíte poškození"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "0 - Blázen", "Teleportuje vás zpět na start"},
	{"2", "I - Mág", "Naváděné slzy pro aktuální místnost"},
	{"3", "II - Velekněžka", "Mámina Noha dupne na nepřítele!"},
	{"4", "III - Císařovna", "↑ +2.35 Větší Poškození & +0.3 Zvýšení Rychlosti pro aktuální místnost"},
	{"5", "IV - Císař", "Teleportuje vás do {{BossRoom}}Boss Místnosti"},
	{"6", "V - Velekněz", "Vytvoří 2 Duševní Srdce"},
	{"7", "VI - Zamilovaní", "Vytvoří 2 Červené Srdce"},
	{"8", "VII - Vůz", "Nesmrtelnost + kontaktní poškození na 6 sekund"},
	{"9", "VIII - Spravedlnost", "Vytvoří 1 bombu, 1 klíč, 1 penízek a 1 srdce"},
	{"10", "IX - Poustevník", "Teleportuje vás do {{Shop}}Obchodu"},
	{"11", "X - Kolo Štěstí", "Vytvoří Hrací Automat nebo Věštecký Stroj"},
	{"12", "XI - Síla", "↑ +1 Zvýšení Zdraví#↑ +0.3 Větší Poškození#↑ +50% Větší Poškození#↑ +5.25 Větší Dostřel#↑ +0.5 Výška Slz#↑ +0.3 Zvýšení Rychlosti#pro aktuální místnost"},
	{"13", "XII - Viselec", "Uděluje vám létání pro aktuální místnost"},
	{"14", "XIII - Smrt", "Způsobí 40 poškození všem nepřátelům v místnosti"},
	{"15", "XIV - Umírněnost", "Vytvoří Stroj na Darování Krve#Vytvoří Ďábelského Žebráka v Greed Modu"},
	{"16", "XV - Ďábel", "↑ +2 Větší Poškození pro aktuální místnost"},
	{"17", "XVI - Věž", "Vytvoří 6 trollích bomb"},
	{"18", "XVII - Hvězda", "Teleportuje vás do {{TreasureRoom}}Pokladnice"},
	{"19", "XVIII - Měsíc", "Teleportuje vás do {{SecretRoom}}Tajné Místnosti"},
	{"20", "XIX - Slunce", "Způsobí 100 poškození všem nepřátelům v místnosti#Plné zdraví#Odhalí celou mapu"},
	{"21", "XX - Soud", "Vytvoří Žebráka nebo Ďábelského Žebráka"},
	{"22", "XXI - Svět", "Odhalí celou mapu a zobrazí všechny typy místností"},
	{"23", "Křížová 2", "Duplikuje vaše bomby"},
	{"24", "Kárová 2", "Duplikuje vaše peníze"},
	{"25", "Piková 2", "Duplikuje vaše klíče"},
	{"26", "Srdcová 2", "Duplikuje vaše červené srdce#Má pouze efekt léčení"},
	{"27", "Křížové Eso", "Přemění všechny pickupy na bomby"},
	{"28", "Kárové Eso", "Přemění všechny pickupy na penízky"},
	{"29", "Pikové Eso", "Přemění všechny pickupy na klíče"},
	{"30", "Srdcové Eso", "Přemění všechny pickupy na srdce"},
	{"31", "Žolík", "Teleportuje vás do {{DevilRoom}}Ďábelské nebo {{AngelRoom}}Andělské Místnosti"},
	{"32", "Hagalaz", "Zničí všechny kameny v místnosti"},
	{"33", "Jera", "Duplikuje všechny pickupy v místnosti"},
	{"34", "Ehwaz", "Vytvoří padací dvířka"},
	{"35", "Dagaz", "+1 Duševní Srdce#Odstraňuje prokletí"},
	{"36", "Ansuz", "Kompletní mapování pro aktuální patro"},
	{"37", "Perthro", "Zamíchá všechny předměty na podstavcích"},
	{"38", "Berkano", "Vytvoří 3 modré pavouky a 3 modré mouchy"},
	{"39", "Algiz", "Nesmrtelnost na 30 sekund"},
	{"40", "Slepá Runa", "Efekt náhodné runy#25% šance na vytvoření další Slepé Runy"},
	{"41", "Černá Runa", "Způsobí 40 poškození všem nepřátelům#Náhodné zvýšení statistiky za každý předmět na podstavci v místnosti#(Zničí všechny podstavce v místnosti)"},
	{"42", "Karta Chaosu", "Vrhací instantně zabíjející karta"},
	{"43", "Kreditka", "Odebere cenu ze všech položek v aktuálním Obchodě nebo Ďábelské Dohodě, takže bude vše zdarma"},
	{"44", "Pravidla", "Ukáže \"pomocné\" tipy"},
	{"45", "Karta Proti Lidskosti", "Naplní celou místnost hovnama"},
	{"46", "Sebevražedný Král", "Okamžitě vás zabije a vytvoří 10 různých předmětů"},
	{"47", "Karta Dostaň se z Věžení", "Otevře všechny dveře v aktuální místnosti"},
	{"48", "? Karta", "Zdarma použije váš aktivní předmět"},
	{"49", "Úlomek Kostky", "Zamíchá předměty a pickupy v aktuální místnosti"},
	{"50", "Nouzový Kontakt", "Dvě Máminy Ruce sestoupí a popadnou nepřítele"},
	{"51", "Svatá Karta", "Dostanete efekt Svatého Pláště na jednu místnost#(Jednou zabrání poškození)#25% šance na vytvoření další Svaté Karty"},
	{"52", "Obrovský Růst", "↑ +7 Větší Poškození#↑ +30 Větší Dostřel#Ničí kameny, když přes ně chodíte#Zvětšení#Efekt trvá pro aktuální místnost"},
	{"53", "Starověké Odvolání", "Při použití vytvoří 3 náhodné karty"},
	{"54", "Krok Věků", "Zpomalte nepřátele#↑ +0.5 Zvýšení Rychlosti#↓ -1 Menší Rychlost Střel#Efekt trvá pro aktuální místnost"},
}

---------- Pills ----------
EID.descriptions[languageCode].unidentifiedPill = "Neznámá Pilulka"

EID.descriptions[languageCode].pills={
	{"0", "Hnusnej Plyn", "Vytvoří Mrak plynu"},
	{"1", "Ošklivé Zakopnutí", "Způsobí vám 1 poškození"},
	{"2", "Koule z Ocele", "+2 Duševní Srdce"},
	{"3", "Bomby Jsou Klíče", "Vymění počet bomb za počet klíčů"},
	{"4", "Výbušný Průjem", "Vytvoří 5 trollích bomb na vaší pozici"},
	{"5", "Plné zdraví", "Plné zdraví"},
	{"6", "Snížení Zdraví", "↓ Snížení Zdraví"},
	{"7", "Zvýšení Zdraví", "↑ Zvýšení Zdraví"},
	{"8", "Našel Jsem Pilulky", "Bez efektu"},
	{"9", "Puberta", "Snězení 3 pilulek vám poskytne transformaci na Dospělého (+1 Červené Srdce)"},
	{"10", "Pěkná Moucha", "Přidá 1 orbitální mouchu"},
	{"11", "Menší Dostřel", "↓ -2 Menší Dostřel"},
	{"12", "Větší Dostřel", "↑ +2.5 Větší Dostřel"},
	{"13", "Snížení Rychlosti", "↓ -0.12 Snížení Rychlosti"},
	{"14", "Zvýšení Rychlosti", "↑ +0.15 Zvýšení Rychlosti"},
	{"15", "Méně Slz", "↓ -0.28 Méně Slz"},
	{"16", "Více Slz", "↑ +0.35 Více Slz"},
	{"17", "Snížení Štěstí", "↓ -1 Snížení Štěstí"},
	{"18", "Zvýšení Štěstí", "↑ +1 Zvýšení Štěstí"},
	{"19", "Telepilule", "Teleportuje vás do náhodné místnosti"},
	{"20", "48 Hodinová Energie!", "Plně nabije váš aktivní předmět#Vytvoří 1-2 baterie"},
	{"21", "Hematemeze", "Vyčerpá všechny vaše červené srdce až na 1 celé#Vytvoří 1-4 Červené Srdce"},
	{"22", "Paralýza", "Nemůžeš se pohnout na 2 sekundy"},
	{"23", "Vidím Navždy!", "Otevírá vchody do tajných místností v aktuálním patře"},
	{"24", "Feromony", "Okouzlí všechny nepřátele v místnosti"},
	{"25", "Amnézie", "Skryje mapu patra"},
	{"26", "Citronová Párty", "Na zemi vytvoří velkou limonádovou louži, která poškozuje nepřátele"},
	{"27", "JSI ČARODĚJ?", "Střílejte diagonálně po dobu 30 sekund"},
	{"28", "Lék Proti Bolesti!", "Utrpíte pouze poloviční poškození pro aktuální místnost"},
	{"29", "Závislák!", "Utrpíte plné poškození pro aktuální místnost"},
	{"30", "Re-Lax", "Při chůzi vytvářite hovna po dobu 2 sekund"},
	{"31", "???", "Efekt prokletí Bludiště pro aktuální patro"},
	{"32", "Jedna Tě Udělá Větším", "Zvětšení#Nemá vliv na váš hitbox"},
	{"33", "Jedna Tě Udělá Menším", "Zmenšení#Váš hitbox je menší"},
	{"34", "Zamoření!", "Vytvoří 1 modrého pavouka za každé hovno v místnosti"},
	{"35", "Zamoření?", "Vytvoří 1 modrého pavouka za každého nepřítele v místnosti#Vytvoří 1-3 modré pavouky, když se v místnosti žádný nepřítel nenachází"},
	{"36", "Pilulka Energie!", "Krátká nesmrtelnost#Udělujete kontaktní poškození"},
	{"37", "Retro Vize", "Rozpixeluje obrazovku po dobu 30 sekund"},
	{"38", "Přátelé až do Konce!", "Vytvoří 3 modré mouchy"},
	{"39", "X-Lax", "Vytvoří za vámi klouzavou hovnovou kaluž"},
	{"40", "Něco je Špatně...", "Vytvoří zpomalující kaluž"},
	{"41", "Jsem Ospalý...", "Zpomalí všechny nepřátele v místnosti"},
	{"42", "Jsem Vzrušený!!!", "Zrychlí všechny nepřátele v místnosti"},
	{"43", "Spolk!", "Spotřebuje aktuálně držený trinket a získáte jeho účinek natrvalo"},
	{"44", "Blink!", "Vystřelí jednu {{Collectible149}}Ipekak slzu"},
	{"45", "Mám Pocit, Jako Bych Kráčel po Slunečním Svitu!", "Krátká nesmrtelnost"},
	{"46", "Krk!", "Vytvoří posledně použitou pilulku"},
} 

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Další Odměna za Obětování]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "50% šance na 1 penízek#100% šance na 1 Bombu, pokud jste zabili Bosse v Basementu 1 pod 1 minutu"},
	{"2", "", "50% šance na 1 penízek#100% šance na 1 Bombu, pokud jste zabili Bosse v Basementu 1 pod 1 minutu"},
	{"3", "", "67% šance na zvýšenou šanci na {{AngelRoom}}Andělskou Místnost"},
	{"4", "", "50% šance na 1 náhodnou truhlu"},
	{"5", "", "33% šance na 3 penízky#67% šance na zvýšenou šanci na {{AngelRoom}}Andělskou Místnost"},
	{"6", "", "33% šance na teleportování do {{AngelRoom}}Andělské Místnosti#Teleportuje vás do {{DevilRoom}}Ďábelské Místnosti pokud se do ní již na tomto patře vytvořili dveře#67% šance na 1 náhodnou truhlu"},
	{"7", "", "33% šance na 1 náhodný předmět z {{AngelRoom}}Andělské Místnosti#67% šance na 1 Duševní Srdce"},
	{"8", "", "100% šance na 7 trollích bomb"},
	{"9", "", "100% šance na zrození \"Uriela\""},
	{"10", "", "50% šance na 7 Duševních Srdcí#50% šance na 30 penízků"},
	{"11", "", "100% šance na zrození \"Gabriela\""},
	{"12", "", "50% šance na teleportování do \"Dark Room\""},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Efekty Kostek]"

EID.descriptions[languageCode].dice={
	{"1", "", "Zamíchá všechny vaše pasivní a aktivní předměty na náhodný předmět ze skupiny předmětů, ze které byl získán"},
	{"2", "", "Zamíchá všechny pickupy v místnosti"},
	{"3", "", "Zamíchá všechny pickupy a trinkety na celém patře#Neovlivňuje {{DevilRoom}}Ďábelskou nebo {{AngelRoom}}Andělskou Místnost"},
	{"4", "", "Zamíchá všechny předměty na podstavcích na patře#Neovlivňuje {{DevilRoom}}Ďábelskou nebo {{AngelRoom}}Andělskou Místnost"},
	{"5", "", "Zamíchá a restartuje aktuální patro"},
	{"6", "", "Zamíchá všechny předměty, pickupy, trinkety a předměty na podstavcích, včetně všeho na patře"}
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations = {
	"",				    -- 0 = none
	"Guppy",			-- 1
	"Houbák",			-- 2
	"Beelzebub",		-- 3
	"Spojený",			-- 4
	"Feťák",			-- 5
	"Ano Mami?",		-- 6
	"A Sakra",			-- 7
	"Bob",				-- 8
	"Leviatan",			-- 9
	"Serafim",			-- 10
	"Super Žebrák",		-- 11
	"Knihomol",			-- 12
	"Pavoučátko",		-- 13
	"Dospělý",			-- 14
	"Dupal"			    -- 15
}


---------- MISC ----------

EID.descriptions[languageCode].VoidText = "Pokud absorbujete, získáte:"
EID.descriptions[languageCode].VoidNames = {"Rychlost", "Slzy", "Poškození", "Dostřel", "Rychlost Střel", "Štěstí"}

EID.descriptions[languageCode].CollectionPageInfo = "Tento předmět je potřeba sebrat, aby se ukázal ve vaší sbírce!"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Demo Jméno Objektu",
	DemoObjectTransformation = "Demo Transformace",
	DemoObjectText = "Tento text je v češtině#Velmi skvělý a dlouhý popis pro simulaci zalomení řádků způsobených šířkou textového pole EID!#\1 Toto je také skvělý řádek#Tento řádek vás miluje {{Heart}}",
}
