--------------------------------------
-----  Basic German descriptions  ----
--------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

local languageCode = "de"

-- init de table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "German (WIP) (AB+)"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts

---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "The Sad Onion", "↑ +0.7 Mehr Tränen"},
	{"2", "The Inner Eye", "Dreifachschuss#↓ Weniger Tränen"},
	{"3", "Spoon Bender", "Gegnerjagende Tränen"},
	{"4", "Cricket's Head", "↑ +0.5 Schaden#↑ +50% Multiplizierter Schaden"},
	{"5", "My Reflection", "Gibt Tränen einen Bumerang Effekt#↑ +1.5 Reichweite#↑ x1.6 Schussgeschwindigkeit#↑ +1 Schusshöhe"},
	{"6", "Number One", "↑ +1.5 Mehr Tränen#↓ -17.62 Reichweite#↑ +0.76 Schusshöhe"},
	{"7", "Blood of the Martyr", "↑ +1.0 Schaden#↑ +50% wenn du Book of Belial besitzt"},
	{"8", "Brother Bobby", "Normaler Tränenschießender Begleiter#Macht 3.5 Schaden pro Träne"},
	{"9", "Skatole", "Alle Feindlichen Fliegen werden Freundlich"},
	{"10", "Halo of Flies", "+2 Spielerumkreisende Fliegen#Blockiert Gegnergeschosse"},
	{"11", "1up!", "↑ +1 Leben#Belebt mit vollen Herzen wieder"},
	{"12", "Magic Mushroom", "↑ +1 Herzcontainer#↑ +0.3 Schaden#↑ +50% Multiplizierter Schaden#↑ +5.25 Reichweite#↑ +0.3 Geschwindigkeit#↑ +0.5 Schusshöhe#Volle Herzen"},
	{"13", "The Virus", "Giftige Berührung#↓ -0.1 Geschwindigkeit#Gegner können Schwarze Herzen beim vergiften fallen lassen"},
	{"14", "Roid Rage", "↑ +0.6 Geschwindigkeit#↑ +5.25 Reichweite#↑ +0.5 Schusshöhe"},
	{"15", "<3", "↑ +1 Herzcontainer#Füllt alle Herzcontainer"},
	{"16", "Raw Liver", "↑ +2 Herzcontainer#Füllt alle Herzcontainer"},
	{"17", "Skeleton Key", "+99 Schlüssel"},
	{"18", "A Dollar", "+99 Münzen"},
	{"19", "Boom!", "+10 Bomben"},
	{"20", "Transcendence", "Du bekommst Körperlos und kannst Fliegen!"},
	{"21", "The Compass", "Enthüllt alle Symbole auf der Karte#Zeigt nicht den Kartenentwurf"},
	{"22", "Lunch", "↑ +1 Herzcontainer"},
	{"23", "Dinner", "↑ +1 Herzcontainer"},
	{"24", "Dessert", "↑ +1 Herzcontainer"},
	{"25", "Breakfast", "↑ +1 Herzcontainer"},
	{"26", "Rotten Meat", "↑ +1 Herzcontainer"},
	{"27", "Wooden Spoon", "↑ +0.3 Geschwindigkeit"},
	{"28", "The Belt", "↑ +0.3 Geschwindigkeit"},
	{"29", "Mom's Underwear", "↑ +5.25 Reichweite#↑ +0.5 Schusshöhe"},
	{"30", "Mom's Heels", "↑ +5.25 Reichweite#↑ +0.5 Schusshöhe"},
	{"31", "Mom's Lipstick", "↑ +5.25 Reichweite#↑ +0.5 Schusshöhe"},
	{"32", "Wire Coat Hanger", "↑ +0.7 Mehr Tränen"},
	{"33", "The Bible", "Flug für den jetzigen Raum#Besitzt die fähigkeit Mom's Foot und Mom's Heart zu töten#! Tötet DICH wenn The Bible bei Satan genutzt wird!"},
	{"34", "The Book of Belial", "↑ +2 Schaden#↑ +12.5% Teufelsdeal chance#↑ +50% Multiplizierter Schaden wenn du Blood of the Martyr besitzt"},
	{"35", "The Necronomicon", "Fügt allem im jetzigen Raum 40 Schaden zu"},
	{"36", "The Poop", "Erzeugt einen Kackhaufen#Kann vor einer Grube platziert und zerstört werden um eine Brücke zu erschaffen"},
	{"37", "Mr. Boom", "Platziert eine Bombe unter den Spieler die 110 Schaden verursacht"},
	{"38", "Tammy's Head", "Feuert 10 Tränen in einem Kreis um Isaac herum"},
	{"39", "Mom's Bra", "Friert alle Gegner im jetzigen Raum für 4 sekunden ein"},
	{"40", "Kamikaze!", "Verursacht eine Explosion bei der Spielerposition"},
	{"41", "Mom's Pad", "Verängstigt alle Gegner im jetzigen Raum für 5 Sekunden"},
	{"42", "Bob's Rotten Head", "Giftige Wurfbombe"},
	{"43", "", "<item existiert nicht>"},
	{"44", "Teleport!", "Teleportiert Isaac in einen zufälligen Raum außer den I AM ERROR Raum"},
	{"45", "Yum Heart", "Heile 1 Herz"},
	{"46", "Lucky Foot", "↑ +1.0 Glück#Bessere Chancen bei Glücksspielen#Erhöhte chance auf Belohnungen beim abschließen eines Raumes"},
	{"47", "Doctor's Remote", "Epic Fetus auf Nachfrage!#Kontrollierbarer Luftangriff!"},
	{"48", "Cupid's Arrow", "Piercende Tränen"},
	{"49", "Shoop da Whoop!", "Brimstone Laser mit sehr hohen Schaden"},
	{"50", "Steven", "↑ +1 Schaden"},
	{"51", "Pentagram", "↑ +1.0 Schaden#↑ +10% Devil Deal chance"},
	{"52", "Dr. Fetus", "Bombentränen!"},
	{"53", "Magneto", "Pick-Ups werden magnetisch angezogen"},
	{"54", "Treasure Map", "Zeigt den Kartenentwurf"},
	{"55", "Mom's Eye", "Chance eine Träne nach hinten zu schießen#Chance ist auf 100% bei 2 Glückpunkten"},
	{"56", "Lemon Mishap", "Kreiert einen Limo-Pfütze#Macht 66 Kontaktschaden pro sekunde"},
	{"57", "Distant Admiration", "Mittelklassig-Spielerumkreisende Fliege#Macht 75 Kontaktschaden pro sekunde"},
	{"58", "Book of Shadows", "Unverwundbarkeit für 10 sekunden"},
	{"59", "", "<item does not exist>"},
	{"60", "The Ladder", "Erlaubt es über schmale Gruben zu laufen"},
	{"61", "", "<item does not exist>"},
	{"62", "Charm of the Vampire", "Heilt ein halbes Herz nach jedem 13 getöteten Gegner"},
	{"63", "The Battery", "Spacebar Items können zweimal aufgeladen werden"},
	{"64", "Steam Sale", "-50% auf Shopitems#Zwei Steam Sale macht alles im Shop kostenlos"},
	{"65", "Anarchist Cookbook", "Erzeugt 6 Troll Bomben in der nähe der mitte des Raumes"},
	{"66", "The Hourglass", "Macht Gegner langsamer für 8 sekunden"},
	{"67", "Sister Maggy", "Normaler Tränenschießender Begleiter#Macht 3.5 Schaden pro Träne"},
	{"68", "Technology", "Tränen werden ausgetauscht mit Laser"},
	{"69", "Chocolate Milk", "Aufladbare Tränen#↑ Bis zu 400% Schaden#↓ Weniger Tränen"},
	{"70", "Growth Hormones", "↑ +1.0 Schaden#↑ +0.4 Geschwindigkeit"},
	{"71", "Mini Mush", "↑ +0.3 Geschwindigkeit#↓ -4.25 Reichweite*#↑ +1.5 Schusshöhe*#(*beides zusammen ergibt mehr Reichweite)#↑ Kleiner"},
	{"72", "Rosary", "+3 Seelenherzen#The Bible ist häufiger zu finden"},
	{"73", "Cube of Meat", "LVL1: Spielerumkreisender Fleischwürfel#LVL2: Spielerumkreisender Schießender Kopf#LVL3: Meat Boy Level 1#LVL4: Meat Boy Level 2"},
	{"74", "A Quarter", "+25 Münzen"},
	{"75", "PHD", "Bessere Pillen# +1 Pille#Heilt 2 Herzen#Mehr Geld von Blutspendemaschinen"},
	{"76", "X-Ray Vision", "Zeigt versteckte Räume"},
	{"77", "My Little Unicorn", "Unverwundbarkeit#Macht 40 Kontaktschaden"},
	{"78", "Book of Revelations", "+1 Seelenherz#Höhere Horsemen (Boss) chance beim nutzen#↑ +17.5% Devil Deal chance"},
	{"79", "The Mark", "↑ +1.0 Schaden#↑ +0.2 Geschwindigkeit#+1 Seelenherz"},
	{"80", "The Pact", "↑ +0.5 Schaden#↑ +0.7 Mehr Tränen#+2 Seelenherzen"},
	{"81", "Dead Cat", "↑ +9 Leben#Belebt mit einem Herzcontainer wieder"},
	{"82", "Lord of the Pit", "Flug#↑ +0.3 Geschwindigkeit"},
	{"83", "The Nail", "+1 Seelenherz#↑ +0.7 Schaden#↓ -0.18 Geschwindigkeit#Macht Kontaktschaden#Kann Steine zerstören"},
	{"84", "We Need To Go Deeper!", "Spawns a trapdoor to skip the floor#10% chance for crawlspace trapdoor"},
	{"85", "Deck of Cards", "Erzeigt 1 Karte"},
	{"86", "Monstro's Tooth", "Rufe Monstro zum zerquetschen von Gegnern"},
	{"87", "Loki's Horns", "Chance in 4 Richtungen zu schießen"},
	{"88", "Little Chubby", "Begleiter, der nach vorn stürmt #Macht 52.5 Kontaktschaden pro sekunde"},
	{"89", "Spider Bite", "Chance Verlangsamungstränen zu schießen"},
	{"90", "The Small Rock", "↑ +1 Schaden#↑ +0.2 Mehr Tränen#↓ -0.2 Geschwindigkeit"},
	{"91", "Spelunker Hat", "Zeigt was hinter Türen ist"},
	{"92", "Super Bandage", "↑ +1 Herzcontainer#+2 Seelenherzen"},
	{"93", "The Gamekid", "Unverwundbarkeit + Kontaktschaden#Regeneriert Herzen beim essen von Gegnern"},
	{"94", "Sack of Pennies", "Lässt in jeden zweiten Raum zufällig münzen fallen"},
	{"95", "Robo-Baby", "Lasertränen#Macht 3.5 Schaden pro Schuss"},
	{"96", "Little C.H.A.D.", "Erzeugt ein halbes Herz in jeden dritten Raum"},
	{"97", "The Book of Sin", "Erzeugt ein zufälliges Pick-Up"},
	{"98", "The Relic", "Erzeugt 1 Seelenherz in jeden vierten Raum"},
	{"99", "Little Gish", "Verlangsamungstränen#Macht 3.5 Schaden pro Schuss"},
	{"100", "Little Steven", "Gegnerjagende Tränen#Macht 3.5 Schaden pro Schuss"},
	{"101", "The Halo", "↑ +1 Herzcontainer#↑ +0.3 Schaden#↑ +0.2 Mehr Tränen#↑ +0.25 Reichweite#↑ +0.3 Geschwindigkeit#↑ +0.5 Schusshöhe"},
	{"102", "Mom's Bottle of Pills", "Lässt 1 Pille fallen"},
	{"103", "The Common Cold", "Chance vergiftungstränen zu schießen"},
	{"104", "The Parasite", "Tränen halbieren sich bei Kontakt#Geteilte Tränen machen halben Schaden"},
	{"105", "The D6", "Ändert zufällig Podestitems im jetzigen Raum"},
	{"106", "Mr. Mega", "↑ x2.25 Bombenschaden#+5 Bomben"},
	{"107", "The Pinking Shears", "Flug#Dein Körper attackiert Gegner mit 82.5 Kontaktschaden pro sekunde"},
	{"108", "The Wafer", "Aller Schaden ist reduziert auf ein halbes Herz"},
	{"109", "Money = Power", "↑ +0.04 Schaden für jede Münze die du besitzt"},
	{"110", "Mom's Contacts", "Chance frierende Tränen zu schießen#↑ +0.25 Reichweite#↑ +0.5 Schusshöhe"},
	{"111", "The Bean", "Vergiftender Furz!"},
	{"112", "Guardian Angel", "Spielerumkreisender Engel#Macht alle Spielerumkreisende Begleiter schneller#Blockiert Gegnerschüsse#Macht 105 Kontaktschaden pro sekunde"},
	{"113", "Demon Baby", "Auto-firing turret#Deals 3 Schaden pro Schuss"},
	{"114", "Mom's Knife", "Kontrollierbarer Messerattacke"},
	{"115", "Ouija Board", "Spektraltränen"},
	{"116", "9 Volt", "-1 Aufladung für aktive Items#Lädt dein aktives Item vollständig auf"},
	{"117", "Dead Bird", "Erzeugt einen Vogel wenn du getroffen wirst#Der Vogel macht 4 Kontaktschaden pro sekunde"},
	{"118", "Brimstone", "Aufladbarer Brimstone Laser mit sehr hohen Schaden"},
	{"119", "Blood Bag", "↑ +1 Herzcontainer#↑ +0.3 Geschwindigkeit#Heilt 5 Herzen"},
	{"120", "Odd Mushroom", "↑ +1.7 Mehr Tränen#↑ +0.3 Geschwindigkeit#↓ -10% Schaden"},
	{"121", "Odd Mushroom", "↑ +1 Leerer Herzcontainer#↑ +0.3 Schaden#↑ +0.25 Reichweite#↓ -0.1 Geschwindigkeit#↑ +0.5 Schusshöhe"},
	{"122", "Whore of Babylon", "!!! Wenn du ein halbes Herz oder weniger hast:#↑ +1.5 Schaden#↑ +0.3 Geschwindigkeit"},
	{"123", "Monster Manual", "Zufälliger Begleiter für den jetzigen Raum"},
	{"124", "Dead Sea Scrolls", "Zufälliger Item-Effekt (Aktives Item)"},
	{"125", "Bobby-Bomb", "Gegnerjagende Bomben#+5 Bomben"},
	{"126", "Razor Blade", "↑ +1.2 Schaden für den jetzigen Raum#↓ Macht dir 1 Herz Schaden"},
	{"127", "Forget Me Now", "{{Warning}} EINMAL NUTZBAR {{Warning}}#Ändert zufällig den ganzen Flur"},
	{"128", "Forever alone", "Spielerumkreisende Fliege#Sehr weit entfernt#Macht 30 Kontaktschaden pro sekunde"},
	{"129", "Bucket of Lard", "↑ +2 Leere Herzcontainer#↓ -0.2 Geschwindigkeit#heilt ein halbes Herz"},
	{"130", "A Pony", "Gibt flug solange es gehalten wird#Setzt deine Geschwindigkeit auf 1.5 wenn du weniger als 1.5 hast#Sprinte in eine Richtung beim benutzen"},
	{"131", "Bomb Bag", "Lässt 1 Bomben Pick-up in paar Räume fallen"},
	{"132", "A Lump of Coal", "Mehr Schaden basierend auf der zurückgelegten Entfernung der Träne"},
	{"133", "Guppy's Paw", "!!! Konvertiert #1 Rotes Herz zu 3 Seelenherzen"},
	{"134", "Guppy's Tail", "Mehr Kisten tauchen auf"},
	{"135", "IV Bag", "Portable Blutspendemaschine#Ein halbes Herz = 1-3 Münzen"},
	{"136", "Best Friend", "Explodierender Köder#Lockt Gegner an"},
	{"137", "Remote Detonator", "Kontrollier wann Bomben Explodieren#+5 Bomben"},
	{"138", "Stigmata", "↑ +1 Herzcontainer#↑ +0.3 Schaden"},
	{"139", "Mom's Purse", "Du kannst nun 2 Schmuckstücke halten"},
	{"140", "Bob's Curse", "Vergiftende Bomben#+5 Bomben"},
	{"141", "Pageant Boy", "Erzeugt 7 zufällige Münzen"},
	{"142", "Scapular", "Lässt 1 Seelenherz fallen wenn du nurnoch ein halbes Herz hast#(Einmal pro Raum!)"},
	{"143", "Speed Ball", "↑ +0.3 Geschwindigkeit#↑ +0.2 Schussgeschwindigkeit"},
	{"144", "Bum Friend", "Konvertiert Münzen zu Pick-ups"},
	{"145", "Guppy's Head", "Erzeugt 2-4 Blaue Fliegen"},
	{"146", "Prayer Card", "+1 Ewiges Herz"},
	{"147", "Notched Axe", "Zerbricht Steine im jetzigen Raum"},
	{"148", "Infestation", "Erzeugt Fliegen wenn du getroffen wirst"},
	{"149", "Ipecac", "Explodierende Tränen"},
	{"150", "Tough Love", "Chance Zähne zu schießen#Zähne machen 3.2x deines Schadens"},
	{"151", "The Mulligan", "1/6 chance eine Fliege zu erzeugen wenn Tränen einen Gegner treffen"},
	{"152", "Technology 2", "Permanente laser attacke!#↓ -35% Schaden"},
	{"153", "Mutant Spider", "Quad Schuss!#↓ Tränen"},
	{"154", "Chemical Peel", "↑ +2 Schaden aus dem linken Auge"},
	{"155", "The Peeper", "Fliegt im Raum herum#Macht 17.1 Kontaktschaden pro sekunde"},
	{"156", "Habit", "+1 Aufladung wenn man getroffen wird"},
	{"157", "Bloody Lust", "↑ Schaden jedes mal wenn du getroffen wirst#Kann bis zu 6 mal pro Flur aktiviert werden#Hält an für den gesamten Flur"},
	{"158", "Crystal Ball", "Enthüllt die ganze Karte#Lässt zufällig eine Karte oder Seelenherz fallen"},
	{"159", "Spirit of the Night", "Flug#Gibt Spektraltränen"},
	{"160", "Crack the Sky", "Erzeugt 5 Lichtstrahlen neben Gegner#Macht deinen Schaden +20"},
	{"161", "Ankh", "Werde beim Tod als ??? (Blue Baby) wiederbelebt"},
	{"162", "Celtic Cross", "Chance für Unverwundbarkeit wenn du getroffen wirst"},
	{"163", "Ghost Baby", "Spektraltränen Begleiter#Macht 3.5 Schaden pro Träne"},
	{"164", "The Candle", "Erzeugt eine Blaue Fliege#Macht Kontaktschaden#Blockiert Gegnergeschosse#Verschwindet nach 2 sekunden"},
	{"165", "Cat-o-nine-tails", "↑ +1 Schaden#↑ +23% Schussgeschwindigkeit"},
	{"166", "D20", "Ändert zufällig alle Pick-ups im Raum"},
	{"167", "Harlequin Baby", "Tränenschießender Begleiter#Schießt Tränen in V-Formation#Macht 4 Schaden pro Träne"},
	{"168", "Epic Fetus", "Ersetzt Tränen mit einem kontrollierbaren Luftangriff"},
	{"169", "Polyphemus", "Mega-Tränen!#↑ Schaden#↓ Weniger Tränen"},
	{"170", "Daddy Longlegs", "Stampft auf Gegner#Macht 40 Schaden pro sekunde"},
	{"171", "Spider Butt", "macht Gegner langsamer für 4 sekunden#10 Schaden an alle Gegner"},
	{"172", "Sacrificial Dagger", "Spielerumkreisendes Messer#Blockiert Gegnergeschosse#Macht 225 Schaden pro sekunde"},
	{"173", "Mitre", "Höhere chance Seelenherzen zu finden"},
	{"174", "Rainbow Baby", "Normaler Tränenschießender Begleiter#Schießt zufällige Tränen#Macht 3.5 Schaden pro sekunde"},
	{"175", "Dad's Key", "Öffnet alle Türen im jetzigen Raum, inklusive Geheimräume"},
	{"176", "Stem Cells", "↑ +1 Herzcontainer#↑ +0.16 Schussgeschwindigkeit"},
	{"177", "Portable Slot", "Portable Münzautomat"},
	{"178", "Holy Water", "Hinterlässt Gegnerschadende pfützen wenn du getroffen wirst#Macht 24 Schaden pro sekunde"},
	{"179", "Fate", "Flug#+1 Ewiges Herz"},
	{"180", "The Black Bean", "Furze wenn du getroffen wirst"},
	{"181", "White Pony", "Ermöglicht Flug beim halten#Setzt deine Geschwindigkeit auf 1.5 wenn du langsamer als 1.5 bist#Heiliger Sturm beim benutzen"},
	{"182", "Sacred Heart", "Gegnerjagende Tränen#↑ +1 Herzcontainer#↑ x2.3 Multiplizierter Schaden#↓ -0.4 Tränen#↓ -25% Schussgeschwindigkeit#↑ +4.125 Reichweite"},
	{"183", "Tooth Picks", "↑ +0.7 Tränen.#↑ +16% Schussgeschwindigkeit"},
	{"184", "Holy Grail", "Flug#↑ +1 Herzcontainer"},
	{"185", "Dead Dove", "Flug#Spektraltränen"},
	{"186", "Blood Rights", "Macht jeden Gegner im Raum 40 Schaden#Macht dir 1 Schaden beim benutzen"},
	{"187", "Guppy's Hairball", "Wachsender Haarkneul#Schwingt um dich herum#Wächst wenn es einen Gegner tötet#Je größer desto stärker"},
	{"188", "Abel", "Spiegelt deine Bewegungen#Schießt in die Richtung des Spielers#Macht 3.5 Schaden pro Schuss"},
	{"189", "SMB Super Fan", "↑ +1 Herzcontainer#↑ +0.3 Schaden#↑ +0.2 Tränen#↑ +0.5 Reichweite#↑ +0.2 Geschwindigkeit#↑ +1.0 Schusshöhe#Füllt alle Herzen"},
	{"190", "Pyro", "+99 Bomben"},
	{"191", "3 Dollar Bill", "Zufälliger Träneneffekt jede 2-3 sekunden"},
	{"192", "Telepathy For Dummies", "Gegnerjagende Tränen im jetzigen Raum"},
	{"193", "MEAT!", "↑ +1 Herzcontainer#↑ +0.3 Schaden"},
	{"194", "Magic 8 Ball", "↑ +0.16 Schussgeschwindigkeit#+1 Karte"},
	{"195", "Mom's Coin Purse", "Gibt 4 Pillen"},
	{"196", "Squeezy", "Erzeugt 2 Seelenherzen#↑ +0.4 Tränen"},
	{"197", "Jesus Juice", "↑ +0.5 Schaden#↑ +0.25 Reichweite.#↑ +0.5 Schusshöhe"},
	{"198", "Box", "Erzeugt 1 pick-up von jeder Sorte"},
	{"199", "Mom's Key", "+2 Schlüssel#Mehr sachen aus Kisten"},
	{"200", "Mom's Eyeshadow", "Chance charmante Tränen zu schießen"},
	{"201", "Iron Bar", "↑ +0.3 Schaden#Chance Erschütternde Tränen zu schießen"},
	{"202", "Midas' Touch", "Gegner verwandeln sich bei berührung in Gold#Macht Kontaktschaden basierend auf Münzanzahl#Goldene Gegner lassen Münzen fallen"},
	{"203", "Humbleing Bundle", "Dupliziert alle pick-ups"},
	{"204", "Fanny Pack", "50% chance ein zufälliges pick-up fallen zu lassen bei Schaden"},
	{"205", "Sharp Plug", "-2 Heartcontainer = Lädt dein Item auf beim drücken der Spacebar#!!! Funktioniert nur wenn das Item keine ladung hat!"},
	{"206", "Guillotine", "↑ +1 Schaden#↑ Tränen#Dein Kopf umkreist nun deinen Körper#Schüsse kommen noch von deinem Kopf#Der Kopf macht 105 Kontaktschaden"},
	{"207", "Ball of Bandages", "LVL1: Spielerumkreisender Pflasterball#LVL2: Schießender Pflasterball#LVL3: Bandage Girl#LVL4: Bandage Girl LVL2"},
	{"208", "Champion Belt", "↑ +1 Schaden#!!! Mehr Championgegner tauchen auf"},
	{"209", "Butt Bombs", "↑ +5 Bomben#Explosionen erschüttern Gegner und machen Schaden im ganzen Raum"},
	{"210", "Gnawed Leaf", "Unverwundbar bei inaktivität"},
	{"211", "Spiderbaby", "Erzeugt 1-2 Spinnen bei Schaden"},
	{"212", "Guppy's Collar", "↑ 50% wiederbelebungschance"},
	{"213", "Lost Contact", "Schützende Träne#Tränen blockieren Gegnergeschosse#↓ -16% Schussgeschwindigkeit"},
	{"214", "Anemic", "↑ +5 Reichweite#Hinterlässt Gegnerschadende pfützen wenn du getroffen wirst"},
	{"215", "Goat Head", "↑ 100% chance für Teufel-{{DevilRoom}} / Engel-{{AngelRoom}} Räume"},
	{"216", "Ceremonial Robes", "↑ +1 Schaden#+3 Schwarze Herzen"},
	{"217", "Mom's Wig", "Zufällige chance blaue Spinnen zu erzeugen beim schießen#Heilt 1 rotes Herz"},
	{"218", "Placenta", "↑ +1 Herzcontainer#Regeneriert langsam dein Leben"},
	{"219", "Old Bandage", "↑ +1 Leerer Herzcontainer#Zufällige chance rote Herzen bei Schaden fallen zu lassen"},
	{"220", "Sad Bombs", "Tränenexplosion!#+5 Bomben"},
	{"221", "Rubber Cement", "Springende Tränen"},
	{"222", "Anti-Gravity", "↑ +2 Tränen#Anti-Gravitationstränen"},
	{"223", "Pyromaniac", "Explosionen heilen dich#+5 Bomben"},
	{"224", "Cricket's Body", "↑ +1 Tränen#↓ -10 Reichweite#Tränen teilen sich bei Kollision in 4#Geteilte Tränen machen halben Schaden"},
	{"225", "Gimpy", "Chance Seelen/Schwarze Herzen fallen zu lassen bei Schaden#Chance ein Halbes Herz fallen zu lassen beim töten eines Gegners"},
	{"226", "Black Lotus", "↑ +1 Herzcontainer#+1 Seelenherz#+1 Schwarzes Herz"},
	{"227", "Piggy Bank", "+3 Münzen#Lässt 1-2 Münzen fallen bei Schaden#Lässt 0-1 Münzen fallen beim Charakter 'Keeper'"},
	{"228", "Mom's Perfume", "Chance Furchttränen zu schießen#↑ +1 Tränen"},
	{"229", "Monstro's Lung", "Tränen werden aufgeladen und in Shotgun-Style geschossen"},
	{"230", "Abaddon", "↑ +1.5 Schaden#↑ +0.2 Geschwindigkeit#Furchttränen#↓ Entfernt alle Herzcontainer#+6 Schwarze Herzen"},
	{"231", "Ball of Tar", "Chance Verlangsamungstränen zu schießen#Hinterlässt Verlangsamungspfützen"},
	{"232", "Stop Watch", "Permanenter Verlangsamungseffekt#(Aktiviert bei Spielerschaden)#↑ +0.3 Geschwindigkeit"},
	{"233", "Tiny Planet", "Deine Tränen umkreisen Isaac#↑ +7.0 Tränenhöhe#Spektraltränen"},
	{"234", "Infestation 2", "Erzeugt Spinnen beim töten von Gegnern"},
	{"235", "", "<item does not exist>"},
	{"236", "E. Coli", "Bei berührung verwandeln Gegner sich in Kackhaufen"},
	{"237", "Death's Touch", "Sensentränen!#↑ +1.5 Schaden#↓ -0.3 Tränen#Piercende Tränen"},
	{"238", "Key Piece 1", "! Schlüsselstück für Mega Satan !#Mehr Engelräume{{AngelRoom}} tauchen auf"},
	{"239", "Key Piece 2", "! Schlüsselstück für Mega Satan !#Mehr Engelräume{{AngelRoom}} tauchen auf"},
	{"240", "Experimental Treatment", "Alle Stats bekommen einen zufälligen Wert ↑/↓ "},
	{"241", "Contract from Below", "Doppelt alle fallenden Pick-ups#Funktioniert nicht im Greed Modus"},
	{"242", "Infamy", "50% chance Tränen zu blockieren"},
	{"243", "Trinity Shield", "Blockiert Gegnergeschosse"},
	{"244", "Tech.5", "Feuert zufällige Lasertränen"},
	{"245", "20/20", "Verdoppelt alle deine Schüsse"},
	{"246", "Blue Map", "Zeigt Geheimräume"},
	{"247", "BFFS!", "Deine Begleiter machen doppelten Schaden"},
	{"248", "Hive Mind", "Blaue Fliegen/Spinnen machen doppelten Schaden"},
	{"249", "There's Options", "Es tauchen 2 Boss-Items auf anstatt nur 1#! Nur EIN ITEM kann genommen werden !"},
	{"250", "BOGO Bombs", "Doppelt alle fallenden Bomben-Pick-ups"},
	{"251", "Starter Deck", "Du kannst zwei Karten halten#Konvertiert alle Pillen zu Karten#Spawnt eine Karte"},
	{"252", "Little Baggy", "Du kannst zwei Pillen halten#Konvertiert alle Karten zu Pillen#Spawnt eine Pille"},
	{"253", "Magic Scab", "↑ +1 Glück#↑ +1 Herzcontainer"},
	{"254", "Blood Clot", "↑ +1 Schaden#↑ +5 Reichweite#! Zählt nur für das linke Auge !"},
	{"255", "Screw", "↑ +0.5 Tränen#↑ +0.2 Schussgeschwindigkeit"},
	{"256", "Hot Bombs", "Brennende Bomben#+5 Bomben"},
	{"257", "Fire Mind", "Chance für explodierende Tränen#Tränen bringen Gegner zum brennen"},
	-- Translated till here!!!!
	{"258", "Missing No.", "Rerolls all your items and stats on pickup and every time you change the floor"},
	{"259", "Dark Matter", "↑ +1 Damage up#33% chance to shoot Fear tears"},
	{"260", "Black Candle", "Immunity to Curses#+1 Black Heart#+15% Devil/Angel Room chance"},
	{"261", "Proptosis", "↑ +100% Damage up#↓ Dealt damage decreases for traveled distance of the tear"},
	{"262", "Missing Page 2", "+1 Black Heart#When down to 1 Heart, damages all enemies in the room"},
	{"263", "", "<item does not exist>"},
	{"264", "Smart Fly", "Orbital#When you get hit it attacks enemies#Deals 22.5 damage per second"},
	{"265", "Dry Baby", "When its hit by enemy tears, it has a 10% chance to damage all enemies in the room"},
	{"266", "Juicy Sack", "Leaves slowing creep#Spawns 1-2 friendly spiders after clearing a room"},
	{"267", "Robo-Baby 2.0", "Shoots lasers#Deals 3.5 damage per shot#Moves in the direction you shoot"},
	{"268", "Rotten Baby", "Spawns blue flies when the player is shooting"},
	{"269", "Headless Baby", "Leaves creep which deals 6 damage per second"},
	{"270", "Leech", "Heals half a heart when it kills an enemy#3.2 damage per second"},
	{"271", "Mystery Sack", "Drops random pickups every few rooms"},
	{"272", "BBF", "Friendly exploding fly#The explosion deals 60 damage"},
	{"273", "Bob's Brain", "Throwable bomb familiar#The explosion deals 60 damage"},
	{"274", "Best Bud", "When getting hit, gain one midrange orbital#Orbital deals 75 damage per second"},
	{"275", "Lil Brimstone", "Shoots a brimstone laser#Shot deals 31.5 damage per second"},
	{"276", "Isaac's Heart", "Gain an invulnerable body#!!! When the heart familiar gets hit you take damage"},
	{"277", "Lil Haunt", "Friendly ghost familiar#Deals 4 damage per second"},
	{"278", "Dark Bum", "Converts 1.5 Red Hearts into a Soul/Black Heart or spider"},
	{"279", "Big Fan", "Big fat orbital#Deals 30 damage per second"},
	{"280", "Sissy Longlegs", "Randomly spawns blue spiders when in a hostile room"},
	{"281", "Punching Bag", "Decoy familiar#Enemies will target him instead"},
	{"282", "How to Jump", "Allows you to jump"},
	{"283", "D100", "Reroll all pickups, pedestals and all your held passive items"},
	{"284", "D4", "Reroll all your held passive items"},
	{"285", "D10", "Reroll all enemies in the room"},
	{"286", "Blank Card", "Mimic effects of your held card"},
	{"287", "Book of Secrets", "Reveals parts of the map"},
	{"288", "Box of Spiders", "Spawn 1-4 blue spiders"},
	{"289", "Red Candle", "Throw a red flame#The flame stays until it has dealt damage or blocked shots 5 times"},
	{"290", "The Jar", "Stores up to 4 Red Heart pickups for later usage"},
	{"291", "Flush!", "!!! Instakills Poop enemies & bosses!#Turns enemies into poop"},
	{"292", "Satanic Bible", "+1 Black Heart"},
	{"293", "Head of Krampus", "Shoot brimstone lasers in all 4 directions"},
	{"294", "Butter Bean", "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger {{Collectible484}}Wait What? when swapping it with a different active item and picking it up again"},
	{"295", "Magic Fingers", "Damages the whole room with 2x the player damage#Price: 1 coin"},
	{"296", "Converter", "!!! Convert:#2 Soul/Black Hearts into 1 Red Heart Container"},
	{"297", "Pandora's Box", "!!! SINGLE USE, spawns items based on floor:#B1: 2 Soul Hearts#B2: 2 bombs and 2 keys#C1: 1 Boss item#C2: B1+C1#D1: 4 Soul Hearts#D2: 20 coins#W1: 2 Boss items#W2: {{Collectible33}}The Bible#???/Void: Nothing#Sheol: 1 Devil item + 1 Black Heart#Dark Room: Unlocks {{Collectible523}}Moving Box#Cat: 1 Angel item + 1 Eternal Heart#Chest: 1 coin"},
	{"298", "Unicorn Stump", "Invincibility and +0.28 speed up for 6 seconds"},
	{"299", "Taurus", "Get faster in hostile rooms!#Invincibility when fast enough#↓ -0.3 Speed down"},
	{"300", "Aries", "↑ +0.25 Speed up#Touching enemies hurts them"},
	{"301", "Cancer", "+3 Soul Hearts#Halves taken damage in room when you already got hit"},
	{"302", "Leo", "Destroy rocks when walking over them#Size up"},
	{"303", "Virgo", "Chance to get invincibility when hit#Converts negative pills into positive ones"},
	{"304", "Libra", "+6 Coins / Keys / Bombs#Balances your stats!#!!! Every stats up afterwards will affect other stats too"},
	{"305", "Scorpio", "Poison tears"},
	{"306", "Sagittarius", "↑ +0.2 Speed up#Piercing tears"},
	{"307", "Capricorn", "↑ +1 Health / Key / Bomb / Coin#↑ +0.5 Damage up#↑ +0.1 Speed up#↑ +1.5 Range up#Tears up"},
	{"308", "Aquarius", "Leave trail of creep#Creep deals 6 damage per second"},
	{"309", "Pisces", "↑ -1 Tear Delay#Increases knockback"},
	{"310", "Eve's Mascara", "↑ +100% Damage up#↓ -50% Tears down#↓ -0.5 Shot speed down"},
	{"311", "Judas' Shadow", "When dead, respawn as Black Judas#↑ (Damage x 2)"},
	{"312", "Maggy's Bow", "↑ +1 Health up#Heals 1 Red Heart#All Red Hearts now heal double their value"},
	{"313", "Holy Mantle", "Ignore the first hit in every room"},
	{"314", "Thunder Thighs", "↑ +1 Health up#↓ -0.4 Speed down#Destroy rocks when walking over them"},
	{"315", "Strange Attractor", "Magnetic tears#Affects enemies, pickups and trinkets"},
	{"316", "Cursed Eye", "Charged wave of tears#!!! When hit while partially charged, teleports you to a random room#Does not teleport if you have {{Collectible260}}Black Candle"},
	{"317", "Mysterious Liquid", "Tears leave creep#Creep deals 30 damage per second"},
	{"318", "Gemini", "Close combat familiar#Deals 6 contact damage per second"},
	{"319", "Cain's Other Eye", "Bounces around the room#Shoots towards Isaac#His damage equals your damage"},
	{"320", "???'s Only Friend", "Controllable Fly#Deals 5 contact damage per second"},
	{"321", "Samson's Chains", "Draggable ball that can destroy rocks#Deals 10.7 contact damage per second"},
	{"322", "Mongo Baby", "Copies the effect of one of your familiars#Deals double its damage"},
	{"323", "Isaac's Tears", "Shoot 8 tears in all directions when used#Charges when shooting"},
	{"324", "Undefined", "Teleports you to the {{TreasureRoom}}Treasure, {{SecretRoom}}Secret, {{SuperSecretRoom}}Super Secret or I AM ERROR Room"},
	{"325", "Scissors", "Cut off your head#Head turns into stationary familiar#Control your body separately"},
	{"326", "Breath of Life", "Hold down space until chargebar is empty for invincibility#!!! Don't hold it for too long!"},
	{"327", "The Polaroid", "Invincibility when getting hit and at half a Red Heart or none"},
	{"328", "The Negative", "Damages all enemies in the room when getting hit and at half a Red Heart or none"},
	{"329", "The Ludovico Technique", "Controllable Tear"},
	{"330", "Soy Milk", "↑ Very high Tears up: (delay /4) - 2#↓ -80% Damage down"},
	{"331", "Godhead", "Homing tears#↑ +0.5 Damage up#↑ +1.2 Range up#↓ -0.3 Tears down#↓ -0.3 Shot Speed down#↑ +0.8 Tear Height#Tears gain a damaging aura"},
	{"332", "Lazarus' Rags", "When dead, revive as Lazarus (Risen)"},
	{"333", "The Mind", "Full mapping effect"},
	{"334", "The Body", "↑ +3 Health up"},
	{"335", "The Soul", "+2 Soul Hearts#Grants an aura that repels enemies and projectiles"},
	{"336", "Dead Onion", "Piercing + spectral tears#↑ +0.25 Range up#↓ -0.4 Shot Speed down#↓ -0.5 Tear Height#↑ +50% Tear size"},
	{"337", "Broken Watch", "Slows down or speeds up every 4th room"},
	{"338", "The Boomerang", "Throwable boomerang#Stuns enemies and deals 2x your damage on hit#Can grab items"},
	{"339", "Safety Pin", "↑ +5.25 Range up#↑ +0.16 Shot Speed up#↑ +0.5 Tear Height#+1 Black Heart"},
	{"340", "Caffeine Pill", "↑ +0.3 Speed up#↑ Size down#Spawns a random pill when picked up"},
	{"341", "Torn Photo", "↑ +0.7 Tears up#↑ +0.16 Shot Speed up"},
	{"342", "Blue Cap", "↑ +1 Health up#↑ +0.7 Tears up#↓ -16% Shot Speed down"},
	{"343", "Latch Key", "↑ +1 Luck up#+1 Soul Heart#Spawns 2 keys"},
	{"344", "Match Book", "+1 Black Heart#Spawns 2-3 Bomb pickups"},
	{"345", "Synthoil", "↑ +1 Damage up#↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"346", "A Snack", "↑ +1 Health up"},
	{"347", "Diplopia", "!!! SINGLE USE !!!#Duplicates any pedestals/ consumables in the current room"},
	{"348", "Placebo", "Copies the effect of the pill you are currently holding"},
	{"349", "Wooden Nickel", "50% chance to spawn a random coin"},
	{"350", "Toxic Shock", "At the start of every room every enemy gets a poison effect#Killed enemies leave puddle of creep"},
	{"351", "Mega Bean", "Freeze all enemies in the current room#Deals 5 damage and poison any enemies nearby#Sends wave of spikes across the room#!!! Can be used to open secret rooms"},
	{"352", "Glass Cannon", "↓ Reduces your health to half a heart#Fires one large piercing spectral tear ((DMG+1) x 10)"},
	{"353", "Bomber Boy", "+5 bombs#Bombs will now explode in a cross-shaped pattern"},
	{"354", "Crack Jacks", "↑ +1 Health up#Spawns random trinket on the floor"},
	{"355", "Mom's Pearls", "↑ +1.25 Range up#↑ +1 Luck up#↑ +0.5 Tear Height"},
	{"356", "Car Battery", "Causes your active item to activate twice when used"},
	{"357", "Box of Friends", "Duplicate your familiars for the current room#If you have no familiars, {{Collectible113}}Demon Baby will spawn for the current room"},
	{"358", "The Wiz", "Fire 2 tears at once diagonally, similar to R U A WIZARD#Spectral tears"},
	{"359", "8 Inch Nails", "↑ +1.5 Damage up#Increases knockback"},
	{"360", "Incubus", "Shoots the same tears as Isaac in terms of damage, stats and effects"},
	{"361", "Fate's Reward", "Fires tears and copies your tear damage"},
	{"362", "Lil Chest", "Spawns a random pickup every few rooms"},
	{"363", "Sworn Protector", "Orbital familiar#Deals 105 contact damage per second#Blocks and attracts bullets#Blocking 10 tear in one room drops an Eternal Heart"},
	{"364", "Friend Zone", "Orbital familiar#Deals 45 contact damage per second"},
	{"365", "Lost Fly", "Moves along walls/obstacles in the room#Deals 105 contact damage per second"},
	{"366", "Scatter Bombs", "+5 bombs#Causes your bombs to explode into 2-4 tiny bombs"},
	{"367", "Sticky Bombs", "+5 bombs#When a bomb kills an enemy, it spawns blue spiders#Causes your bombs to stick to enemies"},
	{"368", "Epiphora", "Shooting in one direction gradually decreases your tear delay by up to 200%"},
	{"369", "Continuum", "↑ +2.25 Range up#↑ +1.5 Tear Height#Spectral tears#Tears travel through walls and appear out of the opposite wall"},
	{"370", "Mr. Dolly", "↑ +0.7 Tears up#↑ +5.25 Range up#↑ +0.5 Tear Height#Spawns 3 random hearts when picked up"},
	{"371", "Curse of the Tower", "Spawn 6 troll bombs every time you get hit#These are affected by bomb items"},
	{"372", "Charged Baby", "Random chance to drop a battery or freeze all enemies in the room#Chance to add one charge to your active item"},
	{"373", "Dead Eye", "↑ +25% Damage up for every tear that successfully hits an enemy (max +100%)#Chance to lose the multiplier when you miss"},
	{"374", "Holy Light", "10% chance to shoot Holy tears, which will spawn a beam of light on hit#The beam deals 4x your damage#50% chance at 9 Luck"},
	{"375", "Host Hat", "Grants explosion immunity and immunity from Mom's and Satan's foot stomps#20% chance to block tears"},
	{"376", "Restock", "Spawns 3 random Pickups#Shops instantly restock their items when you buy them"},
	{"377", "Bursting Sack", "Spider enemies no longer target or deal contact damage to Isaac"},
	{"378", "No. 2", "Firing tears for 3 seconds drops a Butt Bomb"},
	{"379", "Pupula Duplex", "Tears get a much larger hitbox#Spectral tears"},
	{"380", "Pay To Play", "+5 coins#You can open doors with coins instead of keys"},
	{"381", "Eden's Blessing", "↑ +0.7 Tears up#Gives you a random item at the start of your next run"},
	{"382", "Friendly Ball", "Can be thrown at enemies to capture them#Next usage will re-spawn the same enemy as a friendly companion"},
	{"383", "Tear Detonator", "Detonate any tears currently on the screen, causing each one to split into 6 more tears which will spread in a circle"},
	{"384", "Lil Gurdy", "Will launch and slide around the room#Deals 90 contact damage per second"},
	{"385", "Bumbo", "Picks up nearby coins#Levels up after getting 6, 12, and 24 coins#LVL2: Chance to spawn item after room clears#LVL3: Fires tears that can drop coins on hit#LVL4: Chases enemies, occasionally dropping bombs, and can spawn item on coin pickup"},
	{"386", "D12", "Rerolls any grid object into another random type of object (e.g. poop, pots, TNT, red poop, stone blocks etc.)"},
	{"387", "Censer", "Creates a huge aura of light that slows down enemies and projectiles inside of it"},
	{"388", "Key Bum", "Converts Keys into random chests"},
	{"389", "Rune Bag", "Drops a random rune every 5-6 rooms"},
	{"390", "Seraphim", "Fires Sacred Heart tears#Deals 10 damage per shot"},
	{"391", "Betrayal", "Every time Isaac takes damage, every enemy in the room gets charmed"},
	{"392", "Zodiac", "Gives you a random zodiac item effect every floor"},
	{"393", "Serpent's Kiss", "15% chance to shoot poison tears#Poison enemies on contact#Enemies that were poisoned have a chance to drop a Black Heart on death"},
	{"394", "Marked", "Fire tears automatically directed at a red target on the ground which is controlled by the player#↑ +0.7 Tears up#↑ +3.15 Range up#↑ +0.3 Tear Height"},
	{"395", "Tech X", "Gain the ability to charge and fire a laser ring that travels across the room"},
	{"396", "Ventricle Razor", "Creates up to two portals to travel between them#Can be placed in different rooms"},
	{"397", "Tractor Beam", "Isaac's tears now travel directly forwards following a beam of light, but will also move sideways based on your player movement#↑ +0.5 Tears up#↑ +5.25 Range up#↑ +0.16 Shot Speed up#↑ +0.5 Tear Height"},
	{"398", "God's Flesh", "Tears can shrink enemies#Shrunk enemies can be crushed and killed by walking over them"},
	{"399", "Maw of the Void", "↑ +1 Damage up#After firing tears for 3 seconds, a red cross appears on Isaac's head. Upon releasing the fire button, creates a black brimstone ring#Enemies killed with the black ring have a chance to drop Black Hearts"},
	{"400", "Spear of Destiny", "Spawns a spear in front of you#Deals 2 times your damage#Chance to fear enemies on contact"},
	{"401", "Explosivo", "25% chance to shoot sticky bomb tears#Sticky bomb tears do not deal damage on hit"},
	{"402", "Chaos", "Pedestals will now be chosen from random item pools#Spawns 1-6 random pickups"},
	{"403", "Spider Mod", "Allows you to see your tear damage and the health bars of all enemies#Inflicts a random status effect on contact#Will randomly drop batteries"},
	{"404", "Farting Baby", "Blocks projectiles#If hit, it will fart, which will charm, poison or knockback enemies"},
	{"405", "GB Bug", "Bounces around the room#Deals 120 damage per second and applies a random status effect"},
	{"406", "D8", "Reroll your stats#Will only affect damage, tears, range and speed"},
	{"407", "Purity", "↑ Boost one of your stats depending on the color of the aura around you#When you take damage, you will get a new aura#{{ColorRed}}Red{{CR}} = +4 Damage#{{ColorBlue}}Blue{{CR}} = -4 Tear Delay#{{ColorYellow}}Yellow{{CR}} = +0.5 Speed up#{{ColorOrange}}Orange{{CR}} = +7.5 Range up, +1 Tear Height"},
	{"408", "Athame", "When you take damage, a black brimstone ring will appear around Isaac#Enemies killed with it have a chance to drop a Black Heart"},
	{"409", "Empty Vessel", "+2 Black Hearts#When Isaac has no Red Hearts, gain flight and chance to trigger a shield"},
	{"410", "Evil Eye", "3.33% chance to shoot an eye across the screen which fires tears in the same direction as Isaac"},
	{"411", "Lusty Blood", "↑ +0.5 Damage up for each enemy killed in current room#Maximum of +5 Damage up after 10 kills"},
	{"412", "Cambion Conception", "After taking damage 15 times, Isaac gains a permanent demon familiar#Up to 4 familiars possible"},
	{"413", "Immaculate Conception", "After picking up 15 hearts, Isaac gains a permanent angelic familiar#Up to 5 familiars possible"},
	{"414", "More Options", "Two items now spawn in all {{TreasureRoom}}Treasure Rooms#You can only choose one"},
	{"415", "Crown Of Light", "+2 Soul Hearts#If you don't have any damaged Red Heart containers:#↑ +100% Damage up#↑ +5.25 Range up#↑ +0.5 Tear Height#↓ -0.3 Shot Speed down#Deactivates for the current room when damaged at all"},
	{"416", "Deep Pockets", "Allows you to carry two cards/pills/runes"},
	{"417", "Succubus", "Bounces around the room with a damaging aura, dealing 129% of your damage every second#↑ +50% damage while standing in the aura,"},
	{"418", "Fruit Cake", "Gives you a different tear effect with every tear that you fire"},
	{"419", "Teleport 2.0", "Teleports you to another random room that has not been explored yet#Hierarchy: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> Error-Room"},
	{"420", "Black Powder", "Walking in a circle will spawn a pentagram symbol on the floor, which deals 10 damage per tick"},
	{"421", "Kidney Bean", "Applies charm effect to any enemies in close range and deals 5 damage to them"},
	{"422", "Glowing Hour Glass", "Rewind time and put you back in the previous room, in the same state you were in at that moment"},
	{"423", "Circle of Protection", "Large halo around you, dealing your damage on contact every second#Chance to reflect enemy projectiles"},
	{"424", "Sack Head", "Pickups have a 33% chance to be replaced with a sack#Spawns a sack"},
	{"425", "Night Light", "Spawns a cone of light in front of you that slows enemies and projectiles inside of it"},
	{"426", "Obsessed Fan", "Follows your exact movement on a 3 second delay#Deals 30 contact damage per second"},
	{"427", "Mine Crafter", "Spawns a pushable TNT barrel#If used a second time in the same room while the last TNT barrel is still there, it will remotely explode"},
	{"428", "PJs", "+4 Soul Hearts#Fully restores your red health"},
	{"429", "Head of the Keeper", "Enemies have a 5% chance to drop a Penny when hit with your tears"},
	{"430", "Papa Fly", "Follows your movement pattern on a 1 second delay#Fires tears at nearby enemies that deal damage equal to your damage"},
	{"431", "Multidimensional Baby", "Follows your movement pattern on a 2 second delay#Tears that pass through it will split up and gain a speed boost"},
	{"432", "Glitter Bombs", "+5 bombs#Bombs have a chance to drop random pickups when they explode"},
	{"433", "My Shadow", "Each time you take damage, it will apply a fear effect to all enemies and spawn a friendly black charger#The charger deals 5 damage per second"},
	{"434", "Jar of Flies", "Every time you kill an enemy a blue fly will be added to the Jar#Up to 20 flies#Using the item will release all the flies"},
	{"435", "Lil Loki", "Shoots 4 tears in a cross pattern#Deals 3.5 damage per shot"},
	{"436", "Milk!", "After taking damage, you gain a Tears up for the rest of the room"},
	{"437", "D7", "Respawn all enemies of the room#Allows you to farm room clear rewards#!!! If used in a Greed fight, it can reroll the room into a Shop"},
	{"438", "Binky", "+1 Soul Heart#↑ +0.75 Tears up#↑ Makes Isaac very small, reducing his hitbox size"},
	{"439", "Mom's Box", "Spawns a random trinket#↑ +1 Luck while held#While held, doubles the effect of trinkets"},
	{"440", "Kidney Stone", "Randomly while firing you will stop firing and release a burst of tears and a kidney stone#↓ -0.2 Speed down#↓ -17 Range down#↑ +2 Tear Height"},
	{"441", "Mega Blast", "Fires a huge Mega Satan laser for 15 seconds#The laser persists between rooms and floors"},
	{"442", "Dark Prince's Crown", "!!! While at 1 full Red Heart:#↑ +1.5 Range up#↑ +0.75 Tears up#↑ +0.2 Shot Speed up#↑ +1 Tear Height#Does not work with characters without red HP"}, -- Dark Princes Crown (apostrophe added to the name in Repentance)
	{"443", "Apple!", "Randomly fire razor blades which deal 400% damage#↑ +0.3 Tears up"},
	{"444", "Lead Pencil", "Every 15 tears fired, you fire a cluster of tears#Each tear in the cluster deals double damage"},
	{"445", "Dog Tooth", "↑ +0.3 Damage up#↑ +0.1 Speed up#A wolf howls if you enter a room next to a {{SecretRoom}}{{SuperSecretRoom}}Secret Room#A barking sound will play when entering a room with a crawlspace under a rock"},
	{"446", "Dead Tooth", "While firing, you get a green aura that poisons any enemies in it#The poison deals your damage"},
	{"447", "Linger Bean", "While firing without pause, spawns a poop cloud every 7.5 seconds#The cloud deals 3.5 damage 5 times a second#Cloud lasts 15 seconds#Can be moved by shooting it"},
	{"448", "Shard of Glass", "When taking damage, chance to get ↑ +5 Range and leave a trail of blood creep, or spawn a Red Heart"},
	{"449", "Metal Plate", "+1 Soul Heart#Enemy bullets have a 25% chance to be reflected as concussive tears"},
	{"450", "Eye of Greed", "Every 20 tears, shoot a coin tear that turns enemies into gold#This costs 1 coin#Hit enemies drop a coin"},
	{"451", "Tarot Cloth", "Drops a random card or rune on pickup#Doubles the effect of any card used"},
	{"452", "Varicose Veins", "When taking damage, fire 10 tears in a circle around you#The tears deal 125% your damage"},
	{"453", "Compound Fracture", "Bone tears#Tears shatter into 1-3 smaller bone shards upon hitting anything#↑ +1.5 Range up#↑ +1 Tear Height"},
	{"454", "Polydactyly", "You can carry two cards, runes or pills#Spawns a card, pill or rune on pickup"},
	{"455", "Dad's Lost Coin", "↑ +1.5 Range up#↑ +1 Tear Height#Spawns a lucky penny"},
	{"456", "Moldy Bread", "↑ +1 Health up"},
	{"457", "Cone Head", "+1 Soul Heart#20% chance to ignore damage"},
	{"458", "Belly Button", "Spawns a random trinket on pickup#Grants 1 extra trinket slot"},
	{"459", "Sinus Infection", "20% chance to shoot sticky poison tears#Deals your damage each second#Sticks for 60 seconds"},
	{"460", "Glaucoma", "5% chance to shoot concussive tears#Makes the screen slightly darker"},
	{"461", "Parasitoid", "15% chance to shoot egg sacks#Spawns slowing creep on hit#Spawns a blue spider or fly on hit"},
	{"462", "Eye of Belial", "↑ +1.5 Range up#↑ +1 Tear Height#Grants piercing tears#After hitting the first enemy, the tear deals double damage and gains a homing effect"},
	{"463", "Sulfuric Acid", "↑ +0.3 Damage up#Chance to destroy rocks and open doors with your tears"},
	{"464", "Glyph of Balance", "+2 Soul Hearts#Champion enemies drop pickups more frequently"},
	{"465", "Analog Stick", "↑ +0.3 Tears up#Allows you to fire tears diagonally by firing in two directions"},
	{"466", "Contagion", "First killed enemy in the room will explode and poison all nearby enemies"},
	{"467", "Finger!", "Deals constant 10% of your damage to enemies in the direction the finger points at"},
	{"468", "Shade", "Follows your movement delayed by 1 seconds#Deals 30 contact damage per second"},
	{"469", "Depression", "Leaves trail of creep#Creep deals 6 damage per second#Enemies touching the cloud can spawn a holy light beam"},
	{"470", "Hushy", "Bounces around the room#Deals contact damage#Will stop moving when you are shooting#When stopped, it can block projectiles"},
	{"471", "Lil Monstro", "Chargable shotgun attack similar to {{Collectible229}}Monstro's Lung#Each tear deals 3.5 damage"},
	{"472", "King Baby", "Other familiars follow it#Stops moving when you are shooting#Will teleport back to you when you stop shooting"},
	{"473", "Big Chubby", "Charges forwards very slow#Deals 40.5 contact damage per second"},
	{"474", "Tonsil", "Blocks enemy projectiles"},
	{"475", "Plan C", "!!! SINGLE USE !!!#Deals 9,999,999 damage to all enemies and kills you 3 seconds later"},
	{"476", "D1", "Duplicates 1 random pickup in the current room"},
	{"477", "Void", "!!! When used, consume any pedestal items in the room#Active item: Its effect will be added to Void's effect (Stacking the effects)#↑ Passive item: Small stat upgrade to a random stat"},
	{"478", "Pause", "Freezes all enemies in the room until you start shooting again#Touching a frozen enemy will hurt you#Enemies unfreeze after 30 seconds"},
	{"479", "Smelter", "Consumes your trinket and gives you the effect permanently#More trinkets appear"},
	{"480", "Compost", "Converts pickups into blue flies or spiders#Doubles your current blue flies/spiders#Spawns 1 blue fly or spider when you dont have any"},
	{"481", "Dataminer", "When used, ↑/↓ small amount on random stat#Random tear effect for current room#Fucks up all sprites"},
	{"482", "Clicker", "Transforms you into a different character#Removes the last item you collected"},
	{"483", "Mama Mega!", "!!! SINGLE USE !!!#Affects whole floor#Explodes all objects#Deals 200 damage to all enemies#Opens the door to Boss Rush, Hush and all secret rooms"},
	{"484", "Wait What?", "Upon use, pushes enemies away and spawn a wave of rocks#Can open rooms and break rocks"},
	{"485", "Crooked Penny", "50% chance to double all items, consumables and chests in room#50% chance to remove items / pickups in room and spawn 1 coin"},
	{"486", "Dull Razor", "Hurts you without damaging you#Can trigger item effects"},
	{"487", "Potato Peeler", "Removes one Red Heart Container and gives you ↑ +0.2 Damage up and a {{Collectible73}}Cube of Meat"},
	{"488", "Metronome", "Grants a random item's effect for the current room"},
	{"489", "D Infinity", "Random dice effect each use"},
	{"490", "Eden's Soul", "!!! SINGLE USE !!!#Spawns 2 random items depending on the current rooms item pool"},
	{"491", "Acid Baby", "Drops a random pill every 3 rooms#Using a pill poisons all enemies in the room"},
	{"492", "YO LISTEN!", "↑ +1 Luck up#Highlights the location of secret rooms, tinted rocks and crawlspaces"},
	{"493", "Adrenaline", "For every empty heart container:#↑ +0.2 Damage up"},
	{"494", "Jacob's Ladder", "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half your damage"},
	{"495", "Ghost Pepper", "Chance to shoot a red flame that blocks enemy shots and deals contact damage#The flame stays until it has dealt damage or blocked shots 5 times"},
	{"496", "Euthanasia", "3.33% chance to shoot needles#100% chance at 15 Luck#Needles kill normal enemies instantly, bursting them into 10 tears#Needles deal 3x damage against bosses"},
	{"497", "Camo Undies", "Confuse all enemies and camouflage yourself when entering a room until you start shooting"},
	{"498", "Duality", "Spawns {{DevilRoom}}Devil AND {{AngelRoom}}Angel Room doors#When entering one, the other disappears"},
	{"499", "Eucharist", "100% chance to find an {{AngelRoom}}Angel Room"},
	{"500", "Sack of Sacks", "Spawns a sack every 5-6 rooms"},
	{"501", "Greed's Gullet", "Gives you 1 heart container for every 25 coins#The Keeper will gain additional Coin Hearts"},
	{"502", "Large Zit", "While firing, occasionally shoot a white creep tear that deals double damage#Shoot a white creep tear when damaged"},
	{"503", "Little Horn", "5% chance to shoot tears that instantly kill enemies#Running into enemies will deal 3.5 damage to them"},
	{"504", "Brown Nugget", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
	{"505", "Poke Go", "Chance to spawn a charmed enemy when entering a hostile room"},
	{"506", "Backstabber", "If tears hit an enemy in the back, they do double damage and cause bleeding, which deals 10% damage of the enemy's max health every 5 seconds"},
	{"507", "Sharp Straw", "Deals your damage + 10% of the enemy's max health#Affects all enemies in the room#Chance to drop half hearts when it deals damage"},
	{"508", "Mom's Razor", "Orbital that causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds#Deals 300% your damage on contact per second#Does not block shots"},
	{"509", "Bloodshot Eye", "Orbital that shoots a tear every 2 seconds in a random direction#Deals 3.5 damage per tear#Deals 30 contact damage per second"},
	{"510", "Delirious", "Spawns a friendly white delirium version of a boss for the current room"},
	{"511", "Angry Fly", "Orbits around a random enemy until that enemy dies#Deals 30 contact damage per second to other enemies"},
	{"512", "Black Hole", "Throwable black hole, which sucks in everything#Deals 0.4 damage every tick#Destroys nearby rocks#Lasts 6 seconds"},
	{"513", "Bozo", "↑ +0.1 Damage up#+1 Soul Heart#Random chance to charm/fear an enemy#Random chance to spawn a rainbow poop upon taking damage"},
	{"514", "Broken Modem", "Causes random enemies to 'lag' at random intervals, causing them to shortly freeze#Chance to freeze and remove enemy bullets#25% chance to double room clear drops"},
	{"515", "Mystery Gift", "!!! SINGLE USE !!!#Spawns a random item from the current room's item pool#Chance to spawn Lump of Coal or The Poop instead"},
	{"516", "Sprinkler", "Spawns a Sprinkler that rotates in a circle, spraying your tears in all directions"},
	{"517", "Fast Bombs", "+7 Bombs#Allows you to rapidly place bombs on the ground"},
	{"518", "Buddy in a Box", "Familiar which looks like a random coop Baby#Has a random tear effect#Will be randomized every floor"},
	{"519", "Lil Delirium", "A familiar that transforms into other random familiars every 10 seconds"},
	{"520", "Jumper Cables", "+1 charge for your active item for every 15 enemies killed"},
	{"521", "Coupon", "When used, causes one random item in the {{Shop}}Shop or {{DevilRoom}}Devil Room to become free#While held, guarantees one Shop item will be on sale"},
	{"522", "Telekinesis", "Enemy projectiles close to you are held in place for 3 seconds#They get thrown away from you afterwards#Recharges after 3 seconds"},
	{"523", "Moving Box", "When used, stores all pickups from the current room#Using it again will put them back on the floor again#This allows you to move things between rooms"},
	{"524", "Technology Zero", "Tears will be connected with beams of electricity#Electricity damage equals your damage"},
	{"525", "Leprosy", "Taking damage will spawn a projectile blocking orbital#Max 3 orbitals at the same time#Orbitals are destroyed if they take too much damage"},
	{"526", "7 Seals", "Spawns small horsemen familiars that spawn their respective locusts#Horsemen changes every 10 seconds"},
	{"527", "Mr. ME!", "!!! Familiar that can do tasks for you:#Opening doors & chests, Bring items, Steal from the shop / Devil, fight enemies, explode, and activate pressure plates"},
	{"528", "Angelic Prism", "Orbital prism#Tears hitting it will split into 4"},
	{"529", "Pop!", "Tears will behave like billiard balls"},
	{"530", "Death's List", "Grants a reward if you kill enemies in the order they are marked in"},
	{"531", "Haemolacria", "Tears fly in an arc#Tears burst into smaller tears on impact#↓ Tears down#↑ 31% Damage up"},
	{"532", "Lachryphagy", "Tears slow down while traveling#Upon stopping, they explode in 8 smaller tears#Tears can be fired in other tears, making them bigger"},
	{"533", "Trisagion", "Fire piercing blasts of light#They deal 33% damage but can hit enemies multiple times"},
	{"534", "Schoolbag", "Allows holding 2 active items#Switch between them by pressing the Drop button (hold button as \"The Forgotten\")"},
	{"535", "Blanket", "+1 Soul Heart#Heals 1 Red Heart#Grants a shield when entering a boss room"},
	{"536", "Sacrificial Altar", "!!! SINGLE USE !!!#Sacrifice 1-2 familiars to spawn a Devil item#Turns your blue spiders/flies into coins"},
	{"537", "Lil Spewer", "Spawns a random pill#Familiar that fires a line of creep#Creep type changes everytime the player uses a pill"},
	{"538", "Marbles", "Spawns 3 random trinkets#Taking damage can add the effect of your trinket permanently"},
	{"539", "Mystery Egg", "Spawn a charmed enemy when you get hit#Spawns stronger friends the more rooms are cleared without taking damage"},
	{"540", "Flat Stone", "Tears bounce off the floor#Tears cause splash damage on every bounce"},
	{"541", "Marrow", "+1 Bone Heart#Spawns 3 Red Hearts"},
	{"542", "Slipped Rib", "Orbital#Reflects projectiles"},
	{"543", "Hallowed Ground", "Spawn white poop when you get hit#(White poop has a ↑ Tears up aura and can block damage)"},
	{"544", "Pointy Rib", "Nail that levitates in front of Isaac#Deals your damage 6 times per second"},
	{"545", "Book of the Dead", "Spawns a bone orbital or charmed bony per enemy killed in the current room"},
	{"546", "Dad's Ring", "Grants an aura that freezes enemies in place"},
	{"547", "Divorce Papers", "+1 Bone Heart#↑ +0.7 Tears up#Spawns a Mysterious Paper trinket"},
	{"548", "Jaw Bone", "Boomerang-like familiar#Deals 7 contact damage#Can retrieve pickups"},
	{"549", "Brittle Bones", "Replaces all your Red Heart containers with 6 Bone Hearts#Upon losing a Bone Heart:#Fires 8 bone tears in all directions#↑ +0.5 Tears up permanently"},
	{"550", "Broken Shovel", "Mom's Foot will constantly attack you#Using it stops Mom's Foot for current room#!!! (Try to beat Boss Rush with it!)"},
	{"551", "Broken Shovel", "Second part of a broken shovel#!!! Use the shovel on the hill of dirt in the \"Dark Room\""},
	{"552", "Mom's Shovel", "Spawns trapdoor to next floor#!!! Use the shovel on the hill of dirt in the \"Dark Room\"#!!! Unlocks something cool"},
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "Swallowed Penny", "Spawns 1 coin when you get hit"},
	{"2", "Petrified Poop", "50% chance to get drops from poop"},
	{"3", "AAA Battery", "-1 charge needed for active items"},
	{"4", "Broken Remote", "Randomly teleports you, when using an item"},
	{"5", "Purple Heart", "2x chance for champion enemies"},
	{"6", "Broken Magnet", "Coin magnet"},
	{"7", "Rosary Bead", "50% higher {{AngelRoom}}Angel Room chance#Higher chance to find {{Collectible33}}The Bible in {{Shop}}Shops and {{Library}}Libraries"},
	{"8", "Cartridge", "5% chance for Gamekid effect on hit"},
	{"9", "Pulse Worm", "Pulsating tears#Affects tear hitbox"},
	{"10", "Wiggle Worm", "Tears move in waves#↑ +0.3 Tears up"},
	{"11", "Ring Worm", "Tears move in spirals with high speed"},
	{"12", "Flat Worm", "50% wider tears#Increases knockback"},
	{"13", "Store Credit", "One shop item for free"},
	{"14", "Callus", "Prevents damage from creep and spikes"},
	{"15", "Lucky Rock", "Destroying rocks spawns coins"},
	{"16", "Mom's Toenail", "Mom's Foot stomps enemies every 60 seconds"},
	{"17", "Black Lipstick", "+1% chance for Black Hearts"}, -- base chance is 0.5%
	{"18", "Bible Tract", "+3% chance for Eternal Hearts"}, -- base chance is 1.667%
	{"19", "Paper Clip", "Unlock chests without using keys"},
	{"20", "Monkey Paw", "When on half a heart, spawns 1 Black Heart#!!! 3 time usage"},
	{"21", "Mysterious Paper", "Randomly imitates {{Collectible327}}The Polaroid,#{{Blank}} {{Collectible328}}The Negative,#{{Blank}} {{Trinket48}}A Missing Page or {{Trinket23}}Missing Poster"},
	{"22", "Daemon's Tail", "Decreases spawn rate of hearts to 20%#Key drop chance increased#Heart pickups turn into Black Hearts"},
	{"23", "Missing Poster", "Respawn as \"The Lost\" when dying in a {{SacrificeRoom}}Sacrifice Room#If he is unlocked, you revive as him even outside Sacrifice Rooms"},
	{"24", "Butt Penny", "20% higher chance for coins to spawn from poop#Fart when picking up coins#The fart only knocks back enemies"},
	{"25", "Mysterious Candy", "Fart or spawn poop every 30 seconds"},
	{"26", "Hook Worm", "Tears move in angular patterns#↑ +10 Range"},
	{"27", "Whip Worm", "↑ +0.5 Shot Speed up"},
	{"28", "Broken Ankh", "22% chance to respawn as \"Blue Baby\""},
	{"29", "Fish Head", "Spawn 1 blue fly when getting hit"},
	{"30", "Pinky Eye", "10% chance to shoot poison tears"},
	{"31", "Push Pin", "10% chance to shoot piercing spectral tears"},
	{"32", "Liberty Cap", "25% chance for a random mushroom effect per room#Can reveal special rooms on the minimap"},
	{"33", "Umbilical Cord", "When damaged to half a Red Heart, you gain#{{Blank}} {{Collectible100}}Little Steven for the current room"},
	{"34", "Child's Heart", "10% chance for the room clear reward to be a random heart#Chance for a bonus heart from chests, tinted rocks and destroyed machines"},
	{"35", "Curved Horn", "↑ +2 Damage up"},
	{"36", "Rusted Key", "10% chance for the room clear reward to be a key#Chance for a bonus key from chests, tinted rocks and destroyed machines"},
	{"37", "Goat Hoof", "↑ +0.15 Speed up"},
	{"38", "Mom's Pearl", "+10% chance for Soul, Black, and Bone Hearts"}, -- base chance is 10%
	{"39", "Cancer", "↑ -2 Tear Delay"},
	{"40", "Red Patch", "20% chance to get +1.8 Damage up when getting hit#100% chance at 8 Luck#Effect lasts for current room"},
	{"41", "Match Stick", "10% chance for the room clear reward to be a bomb#Chance for a bonus bomb from chests, tinted rocks and destroyed machines#!!! Removes {{Trinket53}}Tick"},
	{"42", "Lucky Toe", "↑ +1 Luck up#+8% room clear reward chance#Extra pickups from chests, tinted rocks, and destroyed machines"},
	{"43", "Cursed Skull", "When damaged down to half a heart or less, teleport to a random room"},
	{"44", "Safety Cap", "10% chance for the room clear reward to be a pill#Chance for a bonus pill from chests, tinted rocks and destroyed machines"},
	{"45", "Ace of Spades", "10% chance for the room clear reward to be a card#Chance for a bonus card from chests, tinted rocks and destroyed machines"},
	{"46", "Isaac's Fork", "10% chance for healing half a heart after clearing a room"},
	{"47", "", "<Item does not exist>"},
	{"48", "A Missing Page", "When hit, 5% chance to deal 40 damage to all enemies in the room"},
	{"49", "Bloody Penny", "50% chance to drop half a heart when picking up coins"},
	{"50", "Burnt Penny", "50% chance to drop a bomb when picking up coins"},
	{"51", "Flat Penny", "50% chance to drop a key when picking up coins"},
	{"52", "Counterfeit Penny", "50% chance to get +1 coin when picking up coins"},
	{"53", "Tick", "-15% boss health#Heals 1 Red Heart when entering a {{BossRoom}}Boss Room#!!! Once picked up, it can't be removed#Only removeable with {{Trinket41}}Match Stick or gulping"},
	{"54", "Isaac's Head", "Familiar with piercing tears#Deals 3.5 damage per tear"},
	{"55", "Maggy's Faith", "Get 1 Eternal Heart at the start of every floor"},
	{"56", "Judas' Tongue", "Reduces Devil deal prices from 2 heart containers to 1"},
	{"57", "???'s Soul", "Familiar that bounces around the room#Shoots in the same direction as the player#Deals 3.5 damage per tear"},
	{"58", "Samson's Lock", "1/15 chance for +0.5 Damage up when killing an enemy#100% chance at 10 Luck#Effect lasts for current room"},
	{"59", "Cain's Eye", "25% chance to reveal map icons at start of new floor#100% chance at 3 Luck"},
	{"60", "Eve's Bird Foot", "5% chance to spawn a {{Collectible117}}Dead Bird when killing an enemy#100% chance at 8 Luck"},
	{"61", "The Left Hand", "Turns all chests into red chests"},
	{"62", "Shiny Rock", "Crawlspace rocks and tinted rocks blink every 10 seconds"},
	{"63", "Safety Scissors", "Turns troll bombs into bomb pickups"},
	{"64", "Rainbow Worm", "Random worm effect every 3 seconds"},
	{"65", "Tape Worm", "↑ Doubles your Range#-50% Tear Height"},
	{"66", "Lazy Worm", "↓ -0.4 Shot Speed down#↑ +4 Range up#↑ +2 Tear Height"},
	{"67", "Cracked Dice", "50% chance to use the {{Collectible105}}D6, {{Collectible406}}D8, {{Collectible386}}D12, or {{Collectible166}}D20 when getting hit"},
	{"68", "Super Magnet", "Magnet for pickups and enemies"},
	{"69", "Faded Polaroid", "Camouflages the player randomly#Confuses enemies"},
	{"70", "Louse", "Chance to spawn 1 spider while in a hostile room"},
	{"71", "Bob's Bladder", "Bombs leave creep"},
	{"72", "Watch Battery", "6.66% chance for the room clear reward to be a battery#+10% chance for random pickups to be a battery#5% chance to add 1 charge to held active item when clearing a room"},
	{"73", "Blasting Cap", "10% chance for exploding bombs to drop a bomb pickup"},
	{"74", "Stud Finder", "0.5% chance to reveal a crawlspace when breaking rocks"},
	{"75", "Error", "Random trinket effect every room"},
	{"76", "Poker Chip", "Chests have a 50/50 chance to spawn extra pickups OR an enemy fly"},
	{"77", "Blister", "Increases knockback"},
	{"78", "Second Hand", "2x longer status effects on enemies"},
	{"79", "Endless Nameless", "25% chance when using pills/cards to drop a copy of the pill/card"},
	{"80", "Black Feather", "↑ +0.2 Damage up for each evil item held"},
	{"81", "Blind Rage", "Invincibility lasts 2x longer after getting hit"},
	{"82", "Golden Horse Shoe", "+15% chance for {{TreasureRoom}}Treasure Rooms to have two items on future floors#You can only choose one"},
	{"83", "Store Key", "Open {{Shop}}Shops for free"},
	{"84", "Rib of Greed", "Greed and Super Greed no longer appear in {{Shop}}Shops or {{SecretRoom}}Secret Rooms#5% more coins and less hearts from room clear rewards"},
	{"85", "Karma", "Using a Donation Machine can heal 1 heart, give 1 coin, grant +1 Luck up, or spawn a Beggar"},
	{"86", "Lil Larva", "Destroying poop spawns 1 blue fly"},
	{"87", "Mom's Locket", "Heal half a heart when using keys#Turns half hearts into full hearts"},
	{"88", "NO!", "Prevents active items from spawning"},
	{"89", "Child Leash", "Familiars stay closer to you"},
	{"90", "Brown Cap", "Poop explodes for 100 damage when destroyed"},
	{"91", "Meconium", "33% chance for Black Poops to spawn#5% chance to spawn a Black Heart when Black Poop is destroyed"},
	{"92", "Cracked Crown", "↑ Stat increases of your items are 33% more effective#↑ +0.2 Tears up#↑ -1 Tear Delay"},
	{"93", "Used Diaper", "15% chance per room for all Fly enemies to become friendly"},
	{"94", "Fish Tail", "Doubles all Blue Fly / Spider spawns"},
	{"95", "Black Tooth", "3% chance to shoot poison tooth tears"},
	{"96", "Ouroboros Worm", "Tears move quickly in a spiral pattern#Spectral tears#↑ +4 Range up#↑ +2 Tear Height"},
	{"97", "Tonsil", "Get a projectile blocking familiar after taking damage 12-20 times#Up to +2 Familiars possible"},
	{"98", "Nose Goblin", "10% chance to shoot homing sticky poison tears#Deals your damage each second#Sticks for 60 seconds"},
	{"99", "Super Ball", "10% chance to shoot bouncy tears"},
	{"100", "Vibrant Bulb", "!!! While holding a fully charged active item:#↑ +0.5 Damage#↑ +0.25 Speed#↑ +0.75 Range#↑ +0.2 Tears#↑ +0.1 Shot speed#↑ +1 Luck"},
	{"101", "Dim Bulb", "!!! While holding a completely uncharged active item:#↑ +1.5 Damage#↑ +0.5 Speed#↑ +1.5 Range#↑ +0.4 Tears#↑ +0.3 Shot Speed#↑ +2 Luck"},
	{"102", "Fragmented Card", "+1 extra {{SecretRoom}}Secret Room per floor while held"},
	{"103", "Equality!", "!!! When coin, key and bomb count are equal:#Turns single consumables into double consumables"},
	{"104", "Wish Bone", "2% chance to spawn a pedestal item when hit#Gets destroyed afterwards"},
	{"105", "Bag Lunch", "2% chance to spawn {{Collectible22}}Lunch when hit#Gets destroyed afterwards"},
	{"106", "Lost Cork", "Increases the radius of any creep you produce"},
	{"107", "Crow Heart", "Damage taken will ignore Soul/Black Hearts, causing your Red Heart containers to be depleted first"},
	{"108", "Walnut", "Drops a key, coin, heart, and random trinket after getting hit by 1-9 explosions#Taking damage isn't required#Gets destroyed afterwards"},
	{"109", "Duct Tape", "Causes any familiar you have to stop moving"},
	{"110", "Silver Dollar", "{{Shop}}Shops now appear in the Womb"},
	{"111", "Bloody Crown", "{{TreasureRoom}}Treasure Rooms now appear in the Womb"},
	{"112", "Pay To Win", "Restock boxes will always spawn in {{TreasureRoom}}Treasure Rooms"},
	{"113", "Locust of War", "Spawn an exploding attack fly when entering a hostile room#The fly deals double your damage + explosion damage"},
	{"114", "Locust of Pestilence", "Spawn a poison attack fly when entering a hostile room#The fly deals double your damage"},
	{"115", "Locust of Famine", "Spawn a slowing attack fly when entering a hostile room#The fly deals double your damage"},
	{"116", "Locust of Death", "Spawn an attack fly when entering a hostile room#The fly deals 4 times your damage"},
	{"117", "Locust of Conquest", "Spawns 1-4 attack flies when entering a hostile room#Each fly deals double your damage"},
	{"118", "Bat Wing", "5% chance to gain flight after killing an enemy#Persists for the current room"},
	{"119", "Stem Cell", "Heals half a heart upon traveling to the next floor"},
	{"120", "Hairpin", "Fully recharges your active item at the start of a boss fight"},
	{"121", "Wooden Cross", "Protects you from the first damage you take for every floor"},
	{"122", "Butter!", "Using your active item will drop it back on a pedestal on the ground#When taking damage, 2% chance to drop one of your passive items"},
	{"123", "Filigree Feather", "Causes the Angel bosses to drop normal items instead of Key Pieces"},
	{"124", "Door Stop", "The last door you used stays open"},
	{"125", "Extension Cord", "Connects your familiars with beams of electricity#Deals 6 damage per beam"},
	{"126", "Rotten Penny", "Spawns a blue fly when picking up a coin"},
	{"127", "Baby-Bender", "Grants your familiars homing shots"},
	{"128", "Finger Bone", "2% chance to gain a Bone Heart when taking damage"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "0 - The Fool", "Teleports you back to the start"},
	{"2", "I - The Magician", "Homing tears for current room"},
	{"3", "II - The High Priestess", "Mom's Foot stomps on an enemy!"},
	{"4", "III - The Empress", "↑ +2.35 Damage & +0.3 Speed for current room"},
	{"5", "IV - The Emperor", "Teleports you to the {{BossRoom}}Boss Room"},
	{"6", "V - The Hierophant", "Drops 2 Soul Hearts"},
	{"7", "VI - The Lovers", "Drops 2 Red Hearts"},
	{"8", "VII - The Chariot", "Invincibility + contact damage for 6 seconds"},
	{"9", "VIII - Justice", "Spawns 1 bomb, 1 key, 1 coin, 1 heart"},
	{"10", "IX - The Hermit", "Teleports you to the {{Shop}}Shop"},
	{"11", "X - Wheel of Fortune", "Spawns a Slot or Fortune Machine"},
	{"12", "XI - Strength", "↑ +1 Health up#↑ +0.3 Damage up#↑ +50% Damage#↑ +5.25 Range up#↑ +0.5 Tear Height#↑ +0.3 Speed up#For current room"},
	{"13", "XII - The Hanged Man", "Grants flight for current room"},
	{"14", "XIII - Death", "Deals 40 damage to all enemies in the room"},
	{"15", "XIV - Temperance", "Spawns a Blood Donation Machine#Spawns a Devil Beggar in Greed Mode"},
	{"16", "XV - The Devil", "↑ +2 Damage up for current room"},
	{"17", "XVI - The Tower", "Spawns 6 troll bombs"},
	{"18", "XVII - The Stars", "Teleports you to the {{TreasureRoom}}Treasure Room"},
	{"19", "XVIII - The Moon", "Teleports you to the {{SecretRoom}}Secret Room"},
	{"20", "XIX - The Sun", "Deals 100 damage to all enemies#Full health#Reveals entire map"},
	{"21", "XX - Judgement", "Spawns a Beggar or Devil Beggar"},
	{"22", "XXI - The World", "Reveals the entire map and shows all roomtypes"},
	{"23", "2 of Clubs", "Duplicate your bombs"},
	{"24", "2 of Diamonds", "Duplicate your money"},
	{"25", "2 of Spades", "Duplicate your keys"},
	{"26", "2 of Hearts", "Duplicate your Red Hearts#Only has a healing effect"},
	{"27", "Ace of Clubs", "Turns all pickups into bombs"},
	{"28", "Ace of Diamonds", "Turns all pickups into coins"},
	{"29", "Ace of Spades", "Turns all pickups into keys"},
	{"30", "Ace of Hearts", "Turns all pickups into hearts"},
	{"31", "Joker", "Teleports you to the {{DevilRoom}}Devil or {{AngelRoom}}Angel Room"},
	{"32", "Hagalaz", "Destroy all rocks in the room"},
	{"33", "Jera", "Duplicate all pickups in room"},
	{"34", "Ehwaz", "Spawns a trapdoor"},
	{"35", "Dagaz", "+1 Soul Heart#Removes curse effects"},
	{"36", "Ansuz", "Full mapping for this floor"},
	{"37", "Perthro", "Reroll all pedestal items"},
	{"38", "Berkano", "Summons 3 blue spiders and 3 blue flies"},
	{"39", "Algiz", "Invincibility for 30 seconds"},
	{"40", "Blank Rune", "Random rune effect#25% chance to drop itself again"},
	{"41", "Black Rune", "Deals 40 damage to all enemies#Converts all pedestal items in the room into random stat ups#Converts all pickups in the room into blue flies"},
	{"42", "Chaos Card", "Throwable instant kill-card"},
	{"43", "Credit Card", "Removes the price from all items in the current shop or Devil deal, making everything free"},
	{"44", "Rules Card", "Displays \"helpful\" tips on use"},
	{"45", "A Card Against Humanity", "Fills the whole room with poop"},
	{"46", "Suicide King", "Instantly kills you and spawns 10 pickup / Collectibles on the floor"},
	{"47", "Get Out Of Jail Free Card", "Open all doors in the current room"},
	{"48", "? Card", "Activates your active item for free"},
	{"49", "Dice Shard", "Rerolls pedestals and pickups in current room"},
	{"50", "Emergency Contact", "Two of Mom's Hands come down and grab an enemy"},
	{"51", "Holy Card", "Grants the Holy Mantle effect for one room#(Prevents damage once)#25% chance to spawn another Holy Card"},
	{"52", "Huge Growth", "↑ +7 Damage up#↑ +30 Range up#Destroy rocks when walking over them#Size up#Effect lasts for current room"},
	{"53", "Ancient Recall", "Spawns 3 random cards when used"},
	{"54", "Era Walk", "Slow down enemies#↑ +0.5 Speed up#↓ -1 Shot Speed down#Effect lasts for current room"},
}

---------- Pills ----------
EID.descriptions[languageCode].unidentifiedPill = "Unidentifizierte Pille"

EID.descriptions[languageCode].pills={
	{"0", "Bad Gas", "Spawns a Gas cloud"},
	{"1", "Bad Trip", "Deals 1 heart of damage to you"},
	{"2", "Balls of Steel", "+2 Soul Hearts"},
	{"3", "Bombs are Key", "Switches number of bombs with keys"},
	{"4", "Explosive Diarrhea", "Spawns 5 troll bombs at your position"},
	{"5", "Full Health", "Full health"},
	{"6", "Health Down", "↓ Health down"},
	{"7", "Health Up", "↑ Health up"},
	{"8", "I Found Pills", "No effect"},
	{"9", "Puberty", "Eating 3 will give you Adult transformation (+1 Red Heart)"},
	{"10", "Pretty Fly", "Adds 1 fly orbital"},
	{"11", "Range Down", "↓ -2 Range down"},
	{"12", "Range Up", "↑ +2.5 Range up"},
	{"13", "Speed Down", "↓ -0.12 Speed down"},
	{"14", "Speed Up", "↑ +0.15 Speed up"},
	{"15", "Tears Down", "↓ -0.28 Tears down"},
	{"16", "Tears Up", "↑ +0.35 Tears up"},
	{"17", "Luck Down", "↓ -1 Luck down"},
	{"18", "Luck Up", "↑ +1 Luck up"},
	{"19", "Telepills", "Teleport to random room"},
	{"20", "48 Hour Energy!", "Fully recharges your active item#Drops 1-2 batteries"},
	{"21", "Hematemesis", "Drains all but one heart container#Spawns 1-4 Red Hearts"},
	{"22", "Paralysis", "You can't move for 2 seconds"},
	{"23", "I can see forever!", "Opens secret room entrances on current floor"},
	{"24", "Pheromones", "Charms all enemies in room"},
	{"25", "Amnesia", "Hides the floor map"},
	{"26", "Lemon Party", "Spawns large puddle on the ground which damages enemies"},
	{"27", "R U A Wizard?", "Shoot diagonally for 30 seconds"},
	{"28", "Percs!", "Take only half the damage for current room"},
	{"29", "Addicted!", "Take full heart damage for current room"},
	{"30", "Re-Lax", "Spawn poop while walking for 2 seconds"},
	{"31", "???", "Curse of the Maze effect for current floor"},
	{"32", "One makes you larger", "You grow bigger#Doesn't affect your hitbox"},
	{"33", "One makes you small", "You get smaller#Your hitbox gets smaller"},
	{"34", "Infested!", "Spawn 1 blue spider per poop in room"},
	{"35", "Infested?", "Spawn 1 blue spider per enemy in room#Spawns 1-3 blue spiders when no enemy is in the room"},
	{"36", "Power Pill!", "Short invincibility effect"},
	{"37", "Retro Vision", "Pixelates the screen for 30 seconds"},
	{"38", "Friends Till The End!", "Spawns 3 blue flies"},
	{"39", "X-Lax", "Spawn pool of slippery creep"},
	{"40", "Something's wrong...", "Spawn pool of slowing creep"},
	{"41", "I'm Drowsy...", "Slow all enemies in room"},
	{"42", "I'm Excited!!!", "Speed up for all enemies in room"},
	{"43", "Gulp!", "Consume current trinket and gain its effect permanently"},
	{"44", "Horf!", "Shoots one {{Collectible149}}Ipecac tear"},
	{"45", "Feels like I'm walking on sunshine!", "Short invincibility"},
	{"46", "Vurp!", "Spawns last used pill"},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Nächste Opferungsbelohung]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "50% chance for 1 coin#100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
	{"2", "", "50% chance for 1 coin#100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
	{"3", "", "67% chance for increased {{AngelRoom}}Angel Room chance"},
	{"4", "", "50% chance for 1 random chest"},
	{"5", "", "33% chance for 3 coins#67% chance for increased {{AngelRoom}}Angel Room chance"},
	{"6", "", "33% chance for a teleport to the {{AngelRoom}}Angel Room#Teleports to the {{DevilRoom}}Devil Room instead if its door was spawned on the current floor#67% chance for random chest"},
	{"7", "", "33% chance for 1 random {{AngelRoom}}Angel Room item#67% chance for 1 Soul Heart"},
	{"8", "", "100% chance for 7 troll bombs"},
	{"9", "", "100% chance to spawn \"Uriel\""},
	{"10", "", "50% chance for 7 Soul Hearts#50% chance for 30 coins"},
	{"11", "", "100% chance to spawn \"Gabriel\""},
	{"12", "", "50% chance to teleport to the \"Dark Room\""},
}


---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Würfel Effekt]"

EID.descriptions[languageCode].dice={
	{"1", "", "Rerolls all your passive and active items into a random item from the room pool it was acquired from"},
	{"2", "", "Rerolls all pickups in the room"},
	{"3", "", "Rerolls all pickups and trinkets on the entire floor#Does not affect the {{DevilRoom}}Devil or {{AngelRoom}}Angel Room"},
	{"4", "", "Rerolls all pedestal items on the floor#Does not affect the {{DevilRoom}}Devil or {{AngelRoom}}Angel Room"},
	{"5", "", "Rerolls and restarts the current floor"},
	{"6", "", "Rerolls all your items, pickups, trinkets and pedestal items, including everything on the floor"},
}


---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Beelzebub",		-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Yes Mother?",		-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}
