---------------------------------------
-----  Basic German descriptions  -----
---------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  !!! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

local languageCode = "de"

-- init de table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "German (WIP)"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts

---------- Collectibles ----------

EID.descriptions[languageCode].collectibles={
	{"1", "Die traurige Zwiebel", "↑ +0.7 Tränen"},
	{"2", "Das innere Auge", "↓ {{Tears}} Tränen runter#Dreifacher Schuss"},
	{"3", "Löffelbieger", "Zielsuchschüsse"},
	{"4", "Grillenkopf", "↑ {{Damage}} +0.5 Schaden#↑ {{Damage}} x1.5 Schadens-Multiplikator"},
	{"5", "Mein Spiegelbild", "↑ {{Range}} +1.5 Reichweite#↑ +1 Tränenhöhe#↑ {{Shotspeed}} +0.6 Schusstempo#Bumerang-Tränen"},
	{"6", "Nummer Eins", "↑ {{Tears}} +1.5 Tränen#↑ +0.76 Tränenhöhe#↓ {{Range}} -17.62 Reichweite"},
	{"7", "Blut des Märtyrers", "↑ {{Damage}} +1 Schaden#{{Collectible34}} x1.5 Schadens-Multiplikator wenn \"Das Buch Belial\" oder \"XV - Der Teufel\" Effekt aktiv ist"},
	{"8", "Bruder Bobby", "Schießt normale Tränen#Verursacht 3.5 Schaden pro Träne"},
	{"9", "Skatol", "Alle feindlichen Fliegen werden freundlich"},
	{"10", "Fliegen-Halo", "+2 Orbitale Fliegen#Blockiert feindliche Projektile"},
	{"11", "1-Up!", "↑ +1 Leben#Isaac wird beim Tod mit voller Gesundheit wiederbelebt"},
	{"12", "Fliegenpilz", "↑ {{Heart}} +1 Gesundheit#↑ {{Speed}} +0.3 Tempo#↑ {{Damage}} +0.3 Schaden#↑ {{Damage}} x1.5 Schadens-Multiplikator#↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe#Größe hoch#{{Heart}} Volle Gesundheit"},
	{"13", "Das Virus", "↓ {{Speed}} -0.1 Tempo#{{Poison}} Vergiftet Feinde bei Berührung#{{BlackHeart}} 20% Chance, dass vergiftete Feinde beim Tod Schwarze Herzen fallen lassen"},
	{"14", "Toben auf Steroiden", "↑ {{Speed}} +0.6 Tempo#↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"15", "<3", "↑ {{Heart}} +1 Gesundheit#{{Heart}} Volle Gesundheit"},
	{"16", "Rohe Leber", "↑ {{Heart}} +2 Gesundheit#{{Heart}} Volle Gesundheit"},
	{"17", "Skelettschlüssel", "{{Key}} +99 Schlüssel"},
	{"18", "Ein Dollar", "{{Coin}} +99 Münzen"},
	{"19", "Bumm!", "{{Bomb}} +10 Bomben"},
	{"20", "Transzendenz", "Flug"},
	{"21", "Der Kompass", "Enthüllt Symbole auf der Karte#Zeigt nicht das Karten-Layout"},
	{"22", "Mittagessen", "↑ {{Heart}} +1 Gesundheit"},
	{"23", "Abendessen", "↑ {{Heart}} +1 Gesundheit"},
	{"24", "Dessert", "↑ {{Heart}} +1 Gesundheit"},
	{"25", "Frühstück", "↑ {{Heart}} +1 Gesundheit"},
	{"26", "Verdorbenes Fleisch", "↑ {{Heart}} +1 Gesundheit"},
	{"27", "Holzlöffel", "↑ {{Speed}} +0.3 Tempo"},
	{"28", "Der Gürtel", "↑ {{Speed}} +0.3 Tempo"},
	{"29", "Mamas Unterwäsche", "↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"30", "Mamas Stöckelschuhe", "↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"31", "Mamas Lippenstift", "↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"32", "Drahtkleiderbügel", "↑ {{Tears}} +0.7 Tränen"},
	{"33", "Die Bibel", "{{Timer}} Flug für diesen Raum#{{MomsHeart}} Tötet sofort Mamas Fuss und Mamas Herz#{{Warning}} Tötet Isaac wenn gegen Satan eingesetzt"},
	{"34", "Das Buch Belial", "{{AngelDevilChance}} +12.5% Teufels-/Engelsraum Chance, wenn getragen#{{Timer}} Erhalte für diesen Raum:#↑ {{Damage}} +2 Schaden#{{Collectible7}} x1.5 Schadens-Multiplikator wenn Isaac \"Blut des Märtyrers\" besitzt"},
	{"35", "Das Necronomicon", "Fügt allen Feinden im Raum 40 Schaden zu"},
	{"36", "Der Schiss", "Lässt einen Kot erscheinen und stößt Feinde zurück#Kann neben einer Grube platziert und mit einer Explosion zerstört werden um eine Brücke zu erschaffen"},
	{"37", "Mr. Bumm", "Platziert eine große Bombe die 110 Schaden verursacht"},
	{"38", "Tammys Kopf", "Schießt 10 Tränen in einem Kreis um Isaac herum#Die Tränen kopieren Isaac's Tränen-Effekte und verursachen +25 Schaden"},
	{"39", "Mamas BH", "Versteinert alle Feinde im Raum für 4 Sekunden"},
	{"40", "Kamikaze!", "Verursacht eine Explosion an Isaacs Position#Verursacht 40 Schaden"},
	{"41", "Mamas Slipeinlage", "{{Fear}} Verängstigt alle Feinde im Raum für 5 Sekunden"},
	{"42", "Bobs verfaulter Kopf", "Wirft den Kopf in Schussrichtung#{{Poison}} Der Kopf explodiert beim Einschlag und vergiftet Feinde"},
	{"43", "", "<Gegenstand existiert nicht>"},
	{"44", "Teleportieren!", "Teleportiert Isaac in einen zufälligen Raum, außer I AM ERROR Räume"},
	{"45", "Leckeres Herz", "{{Heart}} Heilt 1 Herz"},
	{"46", "Glückspfote", "↑ {{Luck}} +1 Glück#+8% Chance auf Belohnung nach dem Abschließen eines Raumes#Höhere Gewinnchance bei Glücksspielen"},
	{"47", "Doktor-Fernbedienung", "{{Collectible168}} Bei Benutzung wird ein Fadenkreuz gesteuert#Eine Rakete schlägt nach 1.5 Sekunden beim Fadenkreuz ein#Verursacht 20x Isaacs Schaden"},
	{"48", "Amors Pfeil", "Durchdringende Tränen"},
	{"49", "Zack-di-wupp!", "{{Collectible118}} Der nächste Schuss wird mit einem sehr starken Strahl ersetzt"},
	{"50", "Steven", "↑ {{Damage}} +1 Schaden"},
	{"51", "Pentagramm", "↑ {{Damage}} +1 Schaden#{{AngelDevilChance}} +10% Teufels-/Engelsraum Chance"},
	{"52", "Dr. Fötus", "↓ {{Tears}} x2.5 Tränenverzögerungs-Multiplikator#{{Bomb}} Isaac schießt Bomben anstatt Tränen#{{Damage}} Diese Bomben verursachen 5x Isaacs Schaden + 30"},
	{"53", "Magneto", "Verbrauchsgut wird von Isaac angezogen"},
	{"54", "Schatzkarte", "Deckt den Grundriss des Stockwerks auf#Deckt keine Raum-Symbole auf"},
	{"55", "Mamas Auge", "50% Chance, eine zusätzliche Träne nach hinten zu schießen#{{Luck}} 100% Chance ab 2 Glück"},
	{"56", "Zitronen-Missgeschick", "Kreiert eine Pfütze#Die Pfütze verursacht Feinden bei Kontakt 24 Schade pro Sekunde"},
	{"57", "Ferne Bewunderung", "Orbitale Fliege#Verursacht bei Kontakt 75 Schaden pro Sekunde"},
	{"58", "Buch der Schatten", "{{Timer}} Unverwundbarkeit für 10 Sekunden"},
	{"59", "", "<Gegenstand existiert nicht>"},
	{"60", "Die Leiter", "Erlaubt es Isaac, ein Feld breite Lücken zu überqueren"},
	{"61", "", "<Gegenstand existiert nicht>"},
	{"62", "Zauber des Vampirs", "{{HalfHeart}} Das Töten von 13 Feinden heilt ein halbes Herz"},
	{"63", "Die Batterie", "{{Battery}} Aktive Gegenstände können bis zu zwei vollen Ladungen überladen werden"},
	{"64", "Steam-Angebot", "{{Shop}} Laden-Gegenstände kosten 50% weniger#Besitzt man diesen Gegenstand zwei mal, sind alle Laden-Gegenstände kostenlos"},
	{"65", "Anarchisten-Kochbuch", "Lässt 6 Troll-Bomben in der Nähe der Raum-Mitte erscheinen"},
	{"66", "Die Sanduhr", "{{Slow}} Verlangsamt Feinde für 8 Sekunden"},
	{"67", "Schwester Maggy", "Schießt normale Tränen#Verursacht 3.5 Schaden pro Träne"},
	{"68", "Technologie", "Isaac schießt Laser statt Tränen"},
	{"69", "Schokoladenmilch", "{{Chargeable}} Aufladbare Tränen#{{Damage}} Schaden skaliert mit der Ladezeit, bis zu 4x#{{Tears}} Maximale Ladezeit hat 2.5x Tränenverzögerung"},
	{"70", "Wachstumshormone", "↑ {{Speed}} +0.4 Tempo#↑ {{Damage}} +1 Schaden"},
	{"71", "Minipilz", "↑ {{Speed}} +0.3 Tempo#↑ +1.5 Tränenhöhe#↑ Größe runter#↓ {{Range}} -4.25 Reichweite#Die Tränenhöhe hoch und Reichweite runter = wenig Reichweite hoch"},
	{"72", "Rosenkranz", "{{SoulHeart}} +3 Seelenherzen#{{Collectible33}} Die Bibel wird allen Gegenstandspools hinzugefügt"},
	{"73", "Fleischwürfel", "Lv1: Satellit#Lv2: Schießender Satellit#Lv3: Meat Boy#Lv4: Super Meat Boy"},
	{"74", "Ein Vierteldollar", "{{Coin}} +25 Münzen"},
	{"75", "PHD", "{{Heart}} Heilt 2 Herzen#{{Pill}} Lässt 1 Pille erscheinen#{{Pill}} Wandelt schlechte Pillen in gute Pillen um#{{BloodDonationMachine}} Blutspendemaschinen und {{Collectible135}} Infusionsbeutel geben mehr {{Coin}} Münzen"},
	{"76", "Röntgenblick", "{{SecretRoom}} Öffnet alle Geheimraum-Eingänge"},
	{"77", "Mein kleines Einhorn", "{{Timer}} Erhalte für 6 Sekunden:#↑ {{Speed}} +0.28 Tempo#Unverwundbarkeit#Isaac kann nicht schießen, verursacht aber bei Kontakt 40 Schaden pro Sekunde"},
	{"78", "Buch der Offenbarungen", "{{SoulHeart}} +1 Seelenherz#{{AngelDevilChance}} +17.5% Teufels-/Engelsraum Chance, wenn getragen#Benutzung des Gegenstands hat eine hohe Chance, den Boss des Stockwerks durch einen Reiter zu ersetzen"},
	{"79", "Das Zeichen", "↑ {{Speed}} +0.2 Tempo#↑ {{Damage}} +1 Schaden#{{SoulHeart}} +1 Seelenherz"},
	{"80", "Der Pakt", "↑ {{Tears}} +0.7 Tränen#↑ {{Damage}} +0.5 Schaden#{{SoulHeart}} +2 Seelenherzen"},
	{"81", "Tote Katze", "↑ +9 Leben#Isaac wird nach dem Tod mit einem Herzcontainer wiederbelebt#{{Warning}} Setzt Isaacs Herzcontainer auf 1 beim Aufheben"},
	{"82", "Herr der Höllengrube", "↑ {{Speed}} +0.3 Tempo#Flug"},
	{"83", "Der Nagel", "Bei Benutzung:#{{SoulHeart}} +1 Seelenherz#{{Timer}} Erhalte für diesen Raum:#↑ {{Damage}} +0.7 Schaden#↓ {{Speed}} -0.18 Tempo#Isaac verursacht bei Kontakt 40 Schaden pro Sekunde#Ermöglicht Isaac, Steine durch Hineinlaufen zu zerstören"},
	{"84", "Wir müssen tiefer!", "Öffnet eine Falltür zum nächsten Stockwerk#{{LadderRoom}} 10% Chance, eine Falltür zu einem Kriechkeller zu öffnen"},
	{"85", "Kartenspiel", "{{Card}} Lässt 1 Karte erscheinen"},
	{"86", "Monstros Zahn", "Monstro fällt auf einen Feind und verursacht 120 Schaden#{{Warning}} Monstro fällt auf Isaac, wenn im Raum keine Feinde sind"},
	{"87", "Lokis Hörner", "25% Chance, in 4 Richtungen zu schießen#{{Luck}} 100% Chance bei 7 Glück"},
	{"88", "Dickerchen", "Stürmt vorwärts in Isaacs Schussrichtung#Verursacht bei Kontakt 52.5 Schaden pro Sekunde"},
	{"89", "Spinnenbiss", "{{Slow}} 25% Chance, verlangsamende Tränen zu schießen#{{Luck}} 100% Chance bei 15 Glück"},
	{"90", "Der kleine Felsen", "↑ {{Tears}} +0.2 Tränen#↑ {{Damage}} +1 Schaden#↓ {{Speed}} -0.2 Tempo"},
	{"91", "Höhlenforscher-Hut", "Zeigt den Raumtyp angrenzender Räume an#{{SecretRoom}} Kann Geheim- und Supergeheimräume aufdecken"},
	{"92", "Superverband", "↑ {{Heart}} +1 Gesundheit#{{Heart}} Heilt 1 Herz#{{SoulHeart}} +2 Seelenherzen"},
	{"93", "Das Zocker-Kid", "{{Timer}} Erhalte für 6.5 Sekunden:#Unverwundbarkeit#Isaac kann nicht schießen, verursacht aber bei Kontakt 40 Schaden pro Sekunde#{{HalfHeart}} Das Töten von 2 Feinden heilt ein halbes Herz#{{Fear}} Verängstigt alle Feinde im Raum"},
	{"94", "Sack voller Pennies", "{{Coin}} Lässt alle 2 Räume eine zufällige Münze erscheinen"},
	{"95", "Robo-Baby", "Schießt Laser#Verursacht 3.5 Schaden pro Schuss"},
	{"96", "Kleiner C.H.A.D.", "{{HalfHeart}} Lässt alle 3 Räume ein halbes Rotes Herz erscheinen"},
	{"97", "Das Buch der Sünde", "Lässt ein zufälliges Verbrauchsgut erscheinen"},
	{"98", "Das Relikt", "{{SoulHeart}} Lässt alle 5-6 Räume ein Seelenherz erscheinen"},
	{"99", "Kleiner Gish", "{{Slow}} Schießt verlangsamende Tränen#Verursacht 3.5 Schaden pro Träne"},
	{"100", "Kleiner Steven", "Schießt zielsuchende Tränen#Verursacht 3.5 Schaden pro Träne"},
	{"101", "Der Heiligenschein", "↑ {{Heart}} +1 Gesundheit#↑ {{Speed}} +0.3 Tempo#↑ {{Tears}} +0.2 Tränen#↑ {{Damage}} +0.3 Schaden#↑ {{Range}} +0.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"102", "Mamas Pillenflasche", "{{Pill}} Lässt 1 Pille erscheinen"},
	{"103", "Die Erkältung", "{{Poison}} 25% Chance, giftige Tränen zu schießen#{{Luck}} 100% Chance bei 12 Glück"},
	{"104", "Der Parasit", "Tränen teilen sich bei Kontakt in zwei auf#Geteilte Tränen verursachen halben Schaden"},
	{"105", "Der W6", "Würfelt Podest-Gegenstände im Raum neu"},
	{"106", "Mr. Mega", "↑ {{Bomb}} x1.83 Bombenschaden#{{Bomb}} +5 Bomben"},
	{"107", "Die Zackenschere", "{{Timer}} Erhalte für diesen Raum:#Flug#Isaacs Körper trennt sich vom Kopf, attackiert Feinde und verursacht bei Kontakt 82.5 Schaden pro Sekunde"},
	{"108", "Die Hostie", "Reduziert den meisten erlittenen Schaden auf ein halbes Herz#{{Player14}} Funktioniert nicht für Hüter"},
	{"109", "Money = Power", "↑ {{Damage}} +0.04 Schaden for every {{Coin}} coin Isaac has"},
	{"110", "Mom's Contacts", "↑ {{Range}} +0.25 Reichweite#↑ +0.5 Tränenhöhe#20% chance to shoot petrifying tears#{{Luck}} 50% chance at 20 Glück"},
	{"111", "The Bean", "{{Poison}} Farts a poison cloud#The poison deals Isaac's damage 6 times"},
	{"112", "Guardian Angel", "Orbital#Speeds up all other orbitals#Blocks projectiles#Deals 105 contact damage per second"},
	{"113", "Demon Baby", "Shoots enemies that get close to him#Deals 3 damage per tear"},
	{"114", "Mom's Knife", "Isaac's tears are replaced by a throwable knife#{{Damage}} The knife deals 2x Isaac's damage while held and 6x at the furthest possible distance"},
	{"115", "Ouija Board", "Spectral tears"},
	{"116", "9 Volt", "{{Battery}} Automatically charges the first bar of active items#{{Battery}} Fully recharges the active item on pickup"},
	{"117", "Dead Bird", "Getting hit spawns a bird#The bird deals 4.3 contact damage per second"},
	{"118", "Brimstone", "↓ {{Tears}} x3 Tränenverzögerungs-Multiplikator#{{Chargeable}} Isaac's tears are replaced by a chargeable blood beam"},
	{"119", "Blood Bag", "↑ {{Heart}} +1 Gesundheit#↑ {{Speed}} +0.3 Tempo#{{Heart}} Heals 4 hearts"},
	{"120", "Odd Mushroom (Thin)", "↑ {{Speed}} +0.3 Tempo#↑ {{Tears}} +1.7 Tränen#↓ {{Damage}} x0.9 Schadens-Multiplikator#↓ {{Damage}} -0.4 Schaden"},
	{"121", "Odd Mushroom (Large)", "↑ {{EmptyHeart}} +1 Empty heart container#↑ {{Damage}} +0.3 Schaden#↑ {{Range}} +0.25 Reichweite#↑ +0.5 Tränenhöhe#↓ {{Speed}} -0.1 Tempo"},
	{"122", "Whore of Babylon", "When on half a Red Heart or less:#↑ {{Speed}} +0.3 Tempo#↑ {{Damage}} +1.5 Schaden"},
	{"123", "Monster Manual", "{{Timer}} Spawns a random familiar für diesen Raum"},
	{"124", "Dead Sea Scrolls", "Triggers a random active item effect"},
	{"125", "Bobby-Bomb", "{{Bomb}} +5 Bomben#Homing Bomben"},
	{"126", "Razor Blade", "↑ {{Damage}} +1.2 Schaden für diesen Raum#{{Warning}} Deals 1 heart of damage to Isaac#{{Heart}} Removes Red Hearts first"},
	{"127", "Forget Me Now", "{{Warning}} SINGLE USE {{Warning}}#Rerolls and restarts the entire floor"},
	{"128", "Forever Alone", "Long range fly orbital#Deals 30 contact damage per second"},
	{"129", "Bucket of Lard", "↑ {{EmptyHeart}} +2 Empty heart containers#↓ {{Speed}} -0.2 Tempo#{{HalfHeart}} Heals half a heart"},
	{"130", "A Pony", "{{Speed}} Sets your Tempo to at least 1.5#Flug while held#Using the item dashes in the direction of Isaac's movement"},
	{"131", "Bomb Bag", "{{Bomb}} Spawns 1 bomb pickup every 2-3 rooms"},
	{"132", "A Lump of Coal", "{{Damage}} Tränen deal more damage the further they travel"},
	{"133", "Guppy's Paw", "{{SoulHeart}} Converts 1 heart container into 3 Seelenherzen"},
	{"134", "Guppy's Tail", "{{Chest}} 33% chance to replace the room clear reward with a chest#33% chance to spawn no room clear reward"},
	{"135", "IV Bag", "{{Coin}} Hurts Isaac for half a heart and spawns 1-2 Münzen"},
	{"136", "Best Friend", "Spawns a decoy Isaac that attracts enemies and explodes after 5 seconds"},
	{"137", "Remote Detonator", "{{Bomb}} +5 Bomben#Isaac's Bomben no longer explode automatically#Using the item detonates all of Isaac's Bomben at once"},
	{"138", "Stigmata", "↑ {{Heart}} +1 Gesundheit#↑ {{Damage}} +0.3 Schaden"},
	{"139", "Mom's Purse", "{{Trinket}} Isaac can hold 2 trinkets"},
	{"140", "Bob's Curse", "{{Bomb}} +5 Bomben#{{Poison}} Isaac's Bomben poison enemies caught in the blast"},
	{"141", "Pageant Boy", "{{Coin}} Spawns 7 random Münzen"},
	{"142", "Scapular", "{{SoulHeart}} Isaac gains 1 Seelenherz when damaged down to half a heart#Can only happen once per room#Exiting and re-entering the room allows the effect to trigger again"},
	{"143", "Tempo Ball", "↑ {{Speed}} +0.3 Tempo#↑ {{Shotspeed}} +0.2 Schusstempo"},
	{"144", "Bum Friend", "{{Coin}} Picks up nearby Münzen#Spawns random pickups in return"},
	{"145", "Guppy's Head", "Spawns 2-4 blue flies"},
	{"146", "Prayer Card", "{{EternalHeart}} +1 Eternal Heart"},
	{"147", "Notched Axe", "Allows Isaac to break rocks and Secret Room walls by walking into them"},
	{"148", "Infestation", "Taking damage spawns 1-3 blue flies"},
	{"149", "Ipecac", "↑ {{Damage}} +40 Schaden#↓ {{Tears}} Tränen#Isaac's tears are fired in an arc#{{Poison}} The tears explode and poison enemies where they land"},
	{"150", "Tough Love", "{{Damage}} 10% chance to shoot teeth that deal 3.2x Isaac's damage#{{Luck}} 100% chance at 9 Glück"},
	{"151", "The Mulligan", "Hitting an enemy with a tear has a 1/6 chance to spawn a fly"},
	{"152", "Technology 2", "↓ {{Tears}} x2 Tränenverzögerungs-Multiplikator#↓ {{Damage}} x0.65 Schadens-Multiplikator#Replaces Isaac's right eye tears with a continuous laser#{{Damage}} The laser deals 20% of Isaac's damage per tick"},
	{"153", "Mutant Spider", "↓ {{Tears}} Tränen#Isaac shoots 4 tears at once"},
	{"154", "Chemical Peel", "↑ {{Damage}} +2 Schaden for the left eye"},
	{"155", "The Peeper", "Floats around the room#Deals 17.1 contact damage per second"},
	{"156", "Habit", "{{Battery}} Taking damage adds 1 charge to the active item"},
	{"157", "Bloody Lust", "↑ {{Damage}} Taking damage grants a damage up#Applies up to 6 times per floor#Lasts for the whole floor"},
	{"158", "Crystal Ball", "Spawns a {{SoulHeart}} Seelenherz, {{Rune}} rune or {{Card}} card#{{Timer}} Full mapping effect for the floor (except {{SuperSecretRoom}} Super Secret Room)"},
	{"159", "Spirit of the Night", "Spectral tears#Flug"},
	{"160", "Crack the Sky", "Spawns 5 beams of light near enemies#Deals Isaac's damage + 20"},
	{"161", "Ankh", "{{Player4}} Respawn as ??? (Blue Baby) on death"},
	{"162", "Celtic Cross", "Taking damage has a 20% chance to make Isaac temporarily invincible#{{Luck}} 100% chance at 27 Glück"},
	{"163", "Ghost Baby", "Shoots spectral tears#Deals 3.5 damage per tear"},
	{"164", "The Candle", "Throws a blue flame#The flame deals contact damage, blocks enemy tears, and despawns after 2 seconds"},
	{"165", "Cat-o-nine-tails", "↑ {{Damage}} +1 Schaden#↑ {{Shotspeed}} +0.23 Schusstempo"},
	{"166", "D20", "Rerolls all pickups in the room"},
	{"167", "Harlequin Baby", "Shoots two tears in a V-shaped pattern#Deals 4 damage per tear"},
	{"168", "Epic Fetus", "Instead of tears, aim a crosshair#A rocket lands on the crosshair after 1.5 seconds#Rockets deal 20x Isaac's damage"},
	{"169", "Polyphemus", "↑ {{Damage}} +4 Schaden#↑ {{Damage}} x2 Schadens-Multiplikator#↓ {{Tears}} Tränen#Tränen pierce killed enemies if there is leftover damage"},
	{"170", "Daddy Longlegs", "Randomly stomps on an enemy#Deals 40 damage per second"},
	{"171", "Spider Butt", "{{Slow}} Slows down enemies for 4 seconds#Deals 10 damage to all enemies"},
	{"172", "Sacrificial Dagger", "Orbital#Blocks enemy shots#Deals 225 damage per second"},
	{"173", "Mitre", "{{SoulHeart}} Higher chance to find Seelenherzen"},
	{"174", "Rainbow Baby", "Shoots random tears#Deals 3-5 damage per tear"},
	{"175", "Dad's Key", "Opens all doors in the room, including {{SecretRoom}}{{SuperSecretRoom}}Secret Rooms, {{ChallengeRoom}}{{BossRushRoom}}Challenge Rooms, and the Mega Satan door"},
	{"176", "Stem Cells", "↑ {{Heart}} +1 Gesundheit#↑ {{Shotspeed}} +0.16 Schusstempo"},
	{"177", "Portable Slot", "Portable slot machine#{{Coin}} Spend 1 coin for a chance to spawn a pickup"},
	{"178", "Holy Water", "Taking damage spills a pool of creep#The creep deals 24 damage per second"},
	{"179", "Fate", "{{EternalHeart}} +1 Eternal Heart#Flug"},
	{"180", "The Black Bean", "Isaac farts when damaged#{{Poison}} The fart poisons enemies"},
	{"181", "White Pony", "{{Speed}} Sets your Tempo to at least 1.5#Flug while held#Using the item dashes in the direction of Isaac's movement, leaving behind beams of light"},
	{"182", "Sacred Heart", "↑ {{Heart}} +1 Gesundheit#↑ {{Damage}} x2.3 Schadens-Multiplikator#↑ {{Damage}} +1 Schaden#↑ {{Range}} +0.38 Reichweite#↑ +0.75 Tränenhöhe#↓ {{Tears}} -0.4 Tränen#↓ {{Shotspeed}} -0.25 Schusstempo#{{Heart}} Volle Gesundheit#Zielsuchschüsse"},
	{"183", "Tooth Picks", "↑ {{Tears}} +0.7 Tränen#↑ {{Shotspeed}} +0.16 Schusstempo"},
	{"184", "Holy Grail", "↑ {{Heart}} +1 Gesundheit#Flug"},
	{"185", "Dead Dove", "Spectral tears#Flug"},
	{"186", "Blood Rights", "Deals 40 damage to every enemy#{{Warning}} Deals 1 heart of damage to Isaac#{{Heart}} Removes Red Hearts first"},
	{"187", "Guppy's Hairball", "Moving swings the hairball around#The ball grows when it kills an enemy#The ball deals more damage the bigger it is"},
	{"188", "Abel", "Mirrors Isaac's movement#Shoots towards Isaac#Deals 3.5 damage per tear"},
	{"189", "SMB Super Fan", "↑ {{Heart}} +1 Gesundheit#↑ {{Speed}} +0.2 Tempo#↑ {{Tears}} +0.2 Tränen#↑ {{Damage}} +0.3 Schaden#↑ {{Range}} +0.5 Reichweite#↑ +1 Tränenhöhe#{{Heart}} Volle Gesundheit"},
	{"190", "Pyro", "{{Bomb}} +99 Bomben"},
	{"191", "3 Dollar Bill", "Isaac's tears get random effects every 2-3 seconds"},
	{"192", "Telepathy For Dummies", "{{Timer}} Zielsuchschüsse für diesen Raum"},
	{"193", "MEAT!", "↑ {{Heart}} +1 Gesundheit#↑ {{Damage}} +0.3 Schaden"},
	{"194", "Magic 8 Ball", "↑ {{Shotspeed}} +0.16 Schusstempo#{{Card}} Spawns a card"},
	{"195", "Mom's Coin Purse", "{{Pill}} Spawns 4 pills"},
	{"196", "Squeezy", "↑ {{Tears}} +0.4 Tränen#{{SoulHeart}} Spawns 2 Seelenherzen"},
	{"197", "Jesus Juice", "↑ {{Damage}} +0.5 Schaden#↑ {{Range}} +0.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"198", "Box", "Spawns 1 pickup of each type"},
	{"199", "Mom's Key", "{{Key}} +2 Schlüssel#Chests contain more pickups"},
	{"200", "Mom's Eyeshadow", "{{Charm}} 10% chance to shoot charming tears#{{Luck}} 100% chance at 27 Glück"},
	{"201", "Iron Bar", "↑ {{Damage}} +0.3 Schaden#{{Confusion}} 10% chance to shoot concussive tears#{{Luck}} 100% chance at 27 Glück"},
	{"202", "Midas' Touch", "Touching enemies petrifies them and turns them gold#Isaac deals contact damage based on his coin count#{{Coin}} Killing a golden enemy spawns Münzen#Poop spawned by Isaac has a high chance to be golden poop"},
	{"203", "Humbleing Bundle", "Pickups spawned are doubled if possible"},
	{"204", "Fanny Pack", "Taking damage has a 50% chance to spawn a random pickup"},
	{"205", "Sharp Plug", "{{Battery}} Using an uncharged active item fully recharges it at the cost of 2 hearts#Only works when item has no charges"},
	{"206", "Guillotine", "↑ {{Tears}} -1 Tränenverzögerung#↑ {{Damage}} +1 Schaden#Isaac's head becomes an orbital that shoots, doesn't take damage and deals 105 contact damage per second"},
	{"207", "Ball of Bandages", "Lv1: Orbital#{{Charm}} Lv2: Orbital that shoots charmed tears#{{Charm}} Lv3: Bandage Girl#{{Charm}} Lv4: Super Bandage Girl"},
	{"208", "Champion Belt", "↑ {{Damage}} +1 Schaden#+15% chance for champion enemies"},
	{"209", "Butt Bomben", "{{Bomb}} +5 Bomben#{{Confusion}} Explosions concuss and damage every enemy in the room"},
	{"210", "Gnawed Leaf", "Standing still for 1 second makes Isaac invincible"},
	{"211", "Spiderbaby", "Taking damage spawns 1-2 blue spiders"},
	{"212", "Guppy's Collar", "50% chance to revive with half a heart on death"},
	{"213", "Lost Contact", "↓ {{Shotspeed}} -0.15 Schusstempo#Isaac's tears destroy enemy shots"},
	{"214", "Anemic", "↑ {{Range}} +5 Reichweite#{{Timer}} When taking damage Isaac leaves a trail of blood creep für diesen Raum"},
	{"215", "Goat Head", "{{AngelDevilChance}} 100% chance for Devil/Angel Rooms to open"},
	{"216", "Ceremonial Robes", "↑ {{Damage}} +1 Schaden#{{BlackHeart}} +3 Black Hearts"},
	{"217", "Mom's Wig", "{{Heart}} Heals 1 heart#5% chance to spawn a blue spider when shooting tears#{{Luck}} 100% chance at 10 Glück"},
	{"218", "Placenta", "↑ {{Heart}} +1 Gesundheit#{{HalfHeart}} 50% chance to heal half a heart every minute"},
	{"219", "Old Bandage", "↑ {{EmptyHeart}} +1 Empty heart container#{{Heart}} Taking damage has a chance to spawn a Red Heart"},
	{"220", "Sad Bomben", "{{Bomb}} +5 Bomben#Isaac's Bomben shoot 10 tears in a circle when they explode"},
	{"221", "Rubber Cement", "Isaac's tears bounce off enemies and obstacles"},
	{"222", "Anti-Gravity", "↑ {{Tears}} -2 Tränenverzögerung#Holding the fire buttons causes tears to hover in midair#Releasing the fire buttons shoots them in the direction they were fired"},
	{"223", "Pyromaniac", "{{Bomb}} +5 Bomben#{{Heart}} Getting hit by explosions heals 1 heart instead of damaging Isaac#Immune to rock wave attacks and Mom and Satan's stomp attacks"},
	{"224", "Cricket's Body", "↑ {{Tears}} -1 Tränenverzögerung#↑ {{Tearsize}} x1.2 Tear size#↓ {{Range}} -10 Reichweite#Tränen split up in 4 on hit#Split tears deal half damage"},
	{"225", "Gimpy", "{{SoulHeart}} Taking damage has a chance to spawn a Seelenherz#{{HalfHeart}} Enemies have a chance to drop a half Red Heart on death"},
	{"226", "Black Lotus", "↑ {{Heart}} +1 Gesundheit#{{SoulHeart}} +1 Seelenherz#{{BlackHeart}} +1 Black Heart"},
	{"227", "Piggy Bank", "{{Coin}} +3 Münzen#{{Coin}} Taking damage spawns 1-2 Münzen#{{Player14}} 0-1 Coin as Keeper"},
	{"228", "Mom's Perfume", "↑ {{Tears}} -1 Tränenverzögerung#{{Fear}} 15% chance to shoot fear tears"},
	{"229", "Monstro's Lung", "↓ {{Tears}} x4.3 Tränenverzögerungs-Multiplikator#{{Chargeable}} Tränen are charged and released in a shotgun style attack"},
	{"230", "Abaddon", "↑ {{Speed}} +0.2 Tempo#↑ {{Damage}} +1.5 Schaden#↓ {{EmptyHeart}} Removes all heart containers#{{BlackHeart}} +6 Black Hearts#{{Fear}} 15% chance to shoot fear tears"},
	{"231", "Ball of Tar", "{{Slow}} 10% chance to shoot slowing tears#{{Luck}} 100% chance at 18 Glück#{{Slow}} Isaac leaves a trail of slowing creep"},
	{"232", "Stop Watch", "↑ {{Speed}} +0.3 Tempo#{{Slow}} Taking damage slows all enemies in the room permanently"},
	{"233", "Tiny Planet", "↑ +7 Tränenhöhe#Spectral tears#Isaac's tears orbit around him"},
	{"234", "Infestation 2", "Killing an enemy spawns a blue spider"},
	{"235", "", "<item does not exist>"},
	{"236", "E. Coli", "Touching an enemy turns it into poop"},
	{"237", "Death's Touch", "↑ {{Damage}} +1.5 Schaden#↑ {{Tearsize}} x2 Tear size#↓ {{Tears}} -0.3 Tränen#Durchdringende Tränen"},
	{"238", "Key Piece 1", "{{Warning}} Getting both parts of the key opens a big golden door#{{AngelChance}} +25% Angel Room chance#{{EternalHeart}} +2% chance for Eternal Hearts"},
	{"239", "Key Piece 2", "{{Warning}} Getting both parts of the key opens a big golden door#{{AngelChance}} +25% Angel Room chance#{{EternalHeart}} +2% chance for Eternal Hearts"},
	{"240", "Experimental Treatment", "↑ Increases 4 random stats#↓ Decreases 2 random stats"},
	{"241", "Contract from Below", "Doubles all room clear rewards#33% chance for no room clear reward"},
	{"242", "Infamy", "50% chance to block enemy shots"},
	{"243", "Trinity Shield", "Blocks enemy shots coming from the direction Isaac is shooting"},
	{"244", "Tech.5", "Occasionally shoot lasers in addition to Isaac's tears"},
	{"245", "20/20", "Isaac shoots 2 tears at once"},
	{"246", "Blue Map", "{{SecretRoom}} Reveals secret room locations on the map"},
	{"247", "BFFS!", "Familiars deal double damage"},
	{"248", "Hive Mind", "Blue spiders and flies deal double damage"},
	{"249", "There's Options", "Allows Isaac to choose between 2 items after beating a boss"},
	{"250", "Bogo Bomben", "{{Bomb}} All bomb drops become double Bomben"},
	{"251", "Starter Deck", "{{Card}} Spawns 1 card on pickup#Isaac can carry 2 cards#Turns all pills into cards"},
	{"252", "Little Baggy", "{{Pill}} Spawns 1 pill on pickup#Isaac can carry 2 pills#Turns all cards into pills"},
	{"253", "Magic Scab", "↑ {{Heart}} +1 Gesundheit#↑ {{Luck}} +1 Glück"},
	{"254", "Blood Clot", "↑ {{Damage}} +1 Schaden for the left eye#↑ {{Range}} +5 Reichweite for the left eye#↑ +0.5 Tränenhöhe"},
	{"255", "Screw", "↑ {{Tears}} +0.5 Tränen#↑ {{Shotspeed}} +0.2 Schusstempo"},
	{"256", "Hot Bomben", "{{Bomb}} +5 Bomben#{{Burning}} Isaac's Bomben leave a flame where they explode"},
	{"257", "Fire Mind", "{{Burning}} Isaac's tears light enemies on fire#10% chance for tears to explode on enemy impact#{{Luck}} 100% chance at 13 Glück#{{Warning}} The explosion can hurt Isaac"},
	{"258", "Missing No.", "Rerolls all of Isaac's items and stats on pickup and at every new floor"},
	{"259", "Dark Matter", "↑ {{Damage}} +1 Schaden#{{Fear}} 33% chance to shoot fear tears#{{Luck}} 100% chance at 20 Glück"},
	{"260", "Black Candle", "{{CurseBlind}} Immune to curses#{{BlackHeart}} +1 Black Heart#{{AngelDevilChance}} +15% Teufels-/Engelsraum Chance"},
	{"261", "Proptosis", "↑ {{Damage}} x2 Schadens-Multiplikator#↓ Tränen deal less damage the further they travel"},
	{"262", "Missing Page 2", "{{BlackHeart}} +1 Black Heart#Taking damage down to 1 heart damages all enemies in the room"},
	{"263", "", "<item does not exist>"},
	{"264", "Smart Fly", "Orbital#Attacks enemies when Isaac takes damage#Deals 22.5 damage per second"},
	{"265", "Dry Baby", "10% chance to damage all enemies in the room when it is hit by an enemy tear"},
	{"266", "Juicy Sack", "{{Slow}} Leaves slowing creep#Spawns 1-2 friendly spiders after clearing a room"},
	{"267", "Robo-Baby 2.0", "Shoots lasers#Deals 3.5 damage per shot#Moves in the direction Isaac is shooting"},
	{"268", "Rotten Baby", "Spawns blue flies when Isaac shoots"},
	{"269", "Headless Baby", "Leaves creep which deals 6 damage per second"},
	{"270", "Leech", "Chases enemies#{{HalfHeart}} Heals Isaac for half a heart when it kills an enemy#Deals 3.2 damage per second"},
	{"271", "Mystery Sack", "Spawns a random pickup every few rooms"},
	{"272", "BBF", "Friendly exploding fly#The explosion deals 60 damage#{{Warning}} The explosion can hurt Isaac"},
	{"273", "Bob's Brain", "Dashes in the direction Isaac is shooting#Explodes when it hits an enemy#{{Poison}} The explosion deals 60 damage and poisons enemies#{{Warning}} The explosion can hurt Isaac"},
	{"274", "Best Bud", "Taking damage spawns one midrange orbital für diesen Raum#The orbital deals 75 damage per second"},
	{"275", "Lil Brimstone", "{{Chargeable}} Familiar that charges and shoots a {{Collectible118}} blood beam#Deals 3.5 damage per tick, for a total of 31.5 damage"},
	{"276", "Isaac's Heart", "Isaac becomes invincible#Spawns a heart familiar that follows Isaac#{{Warning}} If the heart familiar gets hit, Isaac takes damage"},
	{"277", "Lil Haunt", "{{Fear}} Chases and fears enemies#Deals 4 damage per second"},
	{"278", "Dark Bum", "{{Heart}} Picks up nearby Red Hearts#{{SoulHeart}} Spawns a Seelenherz or spider for every 1.5 Red Hearts picked up"},
	{"279", "Big Fan", "Large orbital#Deals 30 damage per second"},
	{"280", "Sissy Longlegs", "Randomly spawns blue spiders in hostile rooms"},
	{"281", "Punching Bag", "Decoy familiar#Enemies target him instead of Isaac"},
	{"282", "How to Jump", "Allows Isaac to jump over gaps and obstacles"},
	{"283", "D100", "Reroll all pickups and pedestal items in the room, and all of Isaac's passive items"},
	{"284", "D4", "Reroll all of Isaac's passive items"},
	{"285", "D10", "Reroll all enemies in the room"},
	{"286", "Blank Card", "Triggers the effect of the rune or card Isaac holds without using it"},
	{"287", "Book of Secrets", "{{Timer}} Grants one of these effects for the floor:#{{Collectible54}} Treasure Map#{{Collectible21}} Compass#{{Collectible246}} Blue Map"},
	{"288", "Box of Spiders", "Spawns 1-4 blue spiders"},
	{"289", "Red Candle", "Throws a red flame#The flame disappears when it has dealt damage or blocked shots 5 times"},
	{"290", "The Jar", "{{Heart}} Picking up Red Hearts while at full health stores up to 4 of them in the Jar#Using the item drops all stored hearts on the floor"},
	{"291", "Flush!", "Turns all non-boss enemies into poop#Instantly kills poop enemies and bosses"},
	{"292", "Satanic Bible", "{{BlackHeart}} +1 Black Heart"},
	{"293", "Head of Krampus", "{{Collectible118}} Shoot a 4-way blood beam"},
	{"294", "Butter Bean", "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger {{Collectible484}} Wait What? when swapping it with a different active item and picking it up again"},
	{"295", "Magic Fingers", "Deals 2x Isaac's damage to all enemies#{{Coin}} Costs 1 coin"},
	{"296", "Converter", "{{Heart}} Converts 2 Soul/Black Hearts into 1 heart container"},
	--NOTE FOR LOCALIZERS: There is code to highlight the text of your current floor
	--For it to work, only use line breaks or semicolons to separate floor details, and use the same order as English
	{"297", "Pandora's Box", "{{Warning}} SINGLE USE {{Warning}} Spawns rewards based on floor:#B1: 2{{SoulHeart}}; B2: 2{{Bomb}} + 2{{Key}}#C1: Boss item; C2: B1+C1#D1: 4{{SoulHeart}}; D2: 20{{Coin}}#W1: 2 Boss items#W2: {{Collectible33}} The Bible#???/Void: Nothing#Sheol: Devil item + 1{{BlackHeart}}#Cathe: Angel item + 1{{EternalHeart}}#Dark Room: Unlocks {{Collectible523}} Moving Box; Chest: 1{{Coin}}"},
	{"298", "Unicorn Stump", "{{Timer}} Receive for 6 seconds:#↑ {{Speed}} +0.28 Tempo#Unverwundbarkeit#Isaac can't shoot (No contact damage)"},
	{"299", "Taurus", "↓ {{Speed}} -0.3 Tempo#↑ {{Speed}} Slowly gain speed while in hostile rooms#At 2 speed, Isaac becomes invincible and deals contact damage#Afterwards, lose the Taurus speed boost für diesen Raum"},
	{"300", "Aries", "↑ {{Speed}} +0.25 Tempo#Touching enemies deals contact damage"},
	{"301", "Cancer", "{{SoulHeart}} +3 Seelenherzen#Taking damage reduces all future damage in the room to half a heart"},
	{"302", "Leo", "Size up#Isaac can destroy rocks by walking into them"},
	{"303", "Virgo", "Taking damage can make Isaac temporarily invincible#{{Luck}} 100% chance at 10 Glück#{{Pill}} Converts negative pills into positive ones"},
	{"304", "Libra", "+6 {{Coin}} Münzen, {{Bomb}} Bomben and {{Key}} Schlüssel#Balances Isaac's stats#Future stat changes will be spread across all stats"},
	{"305", "Scorpio", "{{Poison}} Poison tears"},
	{"306", "Sagittarius", "↑ {{Speed}} +0.2 Tempo#Durchdringende Tränen"},
	{"307", "Capricorn", "↑ {{Heart}} +1 Gesundheit#↑ {{Speed}} +0.1 Tempo#↑ {{Tears}} -1 Tränenverzögerung#↑ {{Damage}} +0.5 Schaden#↑ {{Range}} +1.5 Reichweite#+1 {{Coin}} coin, {{Bomb}} bomb and {{Key}} key"},
	{"308", "Aquarius", "Isaac leaves a trail of creep#The creep deals 6 damage per second"},
	{"309", "Pisces", "↑ {{Tears}} -1 Tränenverzögerung#↑ {{Tearsize}} x1.25 Tear size#Increases tear knockback"},
	{"310", "Eve's Mascara", "↑ {{Damage}} x2 Schadens-Multiplikator#↓ {{Tears}} x0.5 Tear multiplier#↓ {{Shotspeed}} -0.5 Schusstempo"},
	{"311", "Judas' Shadow", "{{Player12}} When dead, respawn as Dark Judas with a 2x damage multiplier"},
	{"312", "Maggy's Bow", "↑ {{Heart}} +1 Gesundheit#{{Heart}} Heals 1 heart#All Red Hearts heal double their value"},
	{"313", "Holy Mantle", "Negates the first hit taken once per room"},
	{"314", "Thunder Thighs", "↑ {{Heart}} +1 Gesundheit#↓ {{Speed}} -0.4 Tempo#Isaac can destroy rocks by walking into them"},
	{"315", "Strange Attractor", "Isaac's tears attract enemies, pickups and trinkets"},
	{"316", "Cursed Eye", "Charged wave of 4 tears#{{Warning}} Taking damage while partially charged teleports Isaac to a random room#{{Collectible260}} Black Candle removes the teleportation effect"},
	{"317", "Mysterious Liquid", "Isaac's tears leave creep#The creep deals 30 damage per second"},
	{"318", "Gemini", "Close combat familiar#Deals 6 contact damage per second"},
	{"319", "Cain's Other Eye", "Bounces around the room#Shoots towards Isaac#{{Damage}} Deals the same damage as Isaac"},
	{"320", "???'s Only Friend", "Controllable fly#Deals 37.5 contact damage per second"},
	{"321", "Samson's Chains", "Draggable ball that can destroy rocks#Deals 10.7 contact damage per second"},
	{"322", "Mongo Baby", "Mimics one of your familiars tears#Cycles through which familiar to mimic every shot"},
	{"323", "Isaac's Tränen", "Shoots 8 tears in all directions#The tears copy Isaac's tear effects#Recharges by shooting tears"},
	{"324", "Undefined", "Teleports Isaac to the {{TreasureRoom}} Treasure, {{SecretRoom}} Secret, {{SuperSecretRoom}} Super Secret or {{ErrorRoom}} I AM ERROR Room"},
	{"325", "Scissors", "{{Timer}} Isaac's head turns into a stationary familiar für diesen Raum#The body is controlled separately"},
	{"326", "Breath of Life", "Holding down the USE button empties the charge bar#Isaac is temporarily invincible when the charge bar is empty#{{Warning}} Holding it for too long deals damage to Isaac"},
	{"327", "The Polaroid", "Taking damage at half a Red Heart or none makes isaac temporarily invincible"},
	{"328", "The Negative", "Taking damage at half a Red Heart or none damages all enemies in the room"},
	{"329", "The Ludovico Technique", "Replaces Isaac's tears with one giant controllable tear"},
	{"330", "Soy Milk", "↑ {{Tears}} Tränen up: (delay/4)-2#↓ {{Damage}} x0.2 Schadens-Multiplikator#↓ {{Tearsize}} x0.5 Tear size"},
	{"331", "Godhead", "↑ {{Damage}} +0.5 Schaden#↑ {{Range}} +1.2 Reichweite#↑ +0.8 Tränenhöhe#↓ {{Tears}} -0.3 Tränen#↓ {{Shotspeed}} -0.3 Schusstempo#Zielsuchschüsse#{{Damage}} Tränen gain an aura that deals 4.5x Isaac's damage per second"},
	{"332", "Lazarus' Rags", "{{Player11}} When dead, revive as Lazarus (Risen)"},
	{"333", "The Mind", "Full mapping effect"},
	{"334", "The Body", "↑ {{Heart}} +3 Gesundheit"},
	{"335", "The Soul", "{{SoulHeart}} +2 Seelenherzen#Grants an aura that repels enemies and projectiles"},
	{"336", "Dead Onion", "↑ {{Range}} +0.25 Reichweite#↑ {{Tearsize}} x1.5 Tear size#↓ -0.5 Tränenhöhe#↓ {{Shotspeed}} -0.4 Schusstempo#Piercing + spectral tears"},
	{"337", "Broken Watch", "{{Slow}} Slows down every 4th room#13% chance to speed up the room instead"},
	{"338", "The Boomerang", "Throwable boomerang#Petrifies enemies and deals 2x Isaac's damage#Can grab and bring back items"},
	{"339", "Safety Pin", "↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe#↑ {{Shotspeed}} +0.16 Schusstempo#{{BlackHeart}} +1 Black Heart"},
	{"340", "Caffeine Pill", "↑ {{Speed}} +0.3 Tempo#↑ Größe runter#{{Pill}} Spawns a random pill"},
	{"341", "Torn Photo", "↑ {{Tears}} +0.7 Tränen#↑ {{Shotspeed}} +0.16 Schusstempo"},
	{"342", "Blue Cap", "↑ {{Heart}} +1 Gesundheit#↑ {{Tears}} +0.7 Tränen#↓ {{Shotspeed}} -0.16 Schusstempo"},
	{"343", "Latch Key", "↑ {{Luck}} +1 Glück#{{SoulHeart}} +1 Seelenherz#{{Key}} Spawns 2 Schlüssel"},
	{"344", "Match Book", "{{BlackHeart}} +1 Black Heart#{{Bomb}} Spawns 3 Bomben"},
	{"345", "Synthoil", "↑ {{Damage}} +1 Schaden#↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe"},
	{"346", "A Snack", "↑ {{Heart}} +1 Gesundheit"},
	{"347", "Diplopia", "{{Warning}} SINGLE USE {{Warning}}#Duplicates all item pedestals and pickups in the room"},
	{"348", "Placebo", "{{Pill}} Triggers the effect of the pill Isaac holds without using it"},
	{"349", "Wooden Nickel", "{{Coin}} 56% chance to spawn a random coin"},
	{"350", "Toxic Shock", "{{Poison}} Entering a room poisons all enemies#Enemies killed leave a puddle of creep#The creep deals 30 damage per second"},
	{"351", "Mega Bean", "Petrifies all enemies in the room#{{Poison}} Deals 5 damage and poisons any enemies nearby#Sends a rock wave in the direction Isaac is moving#The rock wave can open secret rooms and break rocks"},
	{"352", "Glass Cannon", "{{Warning}} Firing the cannon reduces Isaac's health down to half a heart#Shoots a large piercing + spectral tear that does 10x Isaac's damage"},
	{"353", "Bomber Boy", "{{Bomb}} +5 Bomben#Bomben explode in a cross-shaped pattern"},
	{"354", "Crack Jacks", "↑ {{Heart}} +1 Gesundheit#{{Trinket}} Spawns a trinket"},
	{"355", "Mom's Pearls", "↑ {{Range}} +1.25 Reichweite#↑ +0.5 Tränenhöhe#↑ {{Luck}} +1 Glück"},
	{"356", "Car Battery", "{{Battery}} Using an active item triggers its effect twice"},
	{"357", "Box of Friends", "{{Timer}} Duplicates all your familiars für diesen Raum#{{Collectible113}} Grants a Demon Baby für diesen Raum if Isaac has no familiars"},
	{"358", "The Wiz", "Spectral tears#Isaac shoots 2 tears at once diagonally"},
	{"359", "8 Inch Nails", "↑ {{Damage}} +1.5 Schaden#Increases knockback"},
	{"360", "Incubus", "Shoots tears with the same tear rate, damage and effects as Isaac"},
	{"361", "Fate's Reward", "Shoots tears with the same damage and effects as Isaac#Shoots at half the rate of other familiars"},
	{"362", "Lil Chest", "Spawns a random pickup every few rooms"},
	{"363", "Sworn Protector", "Orbital#Deals 105 contact damage per second#Blocks and attracts enemy shots#{{EternalHeart}} Blocking 10 shots in one room spawns an Eternal Heart"},
	{"364", "Friend Zone", "Midrange fly orbital#Deals 45 contact damage per second"},
	{"365", "Lost Fly", "Moves along walls/obstacles#Deals 105 contact damage per second"},
	{"366", "Scatter Bomben", "{{Bomb}} +5 Bomben#Isaac's Bomben scatter into 2-4 tiny Bomben"},
	{"367", "Sticky Bomben", "{{Bomb}} +5 Bomben#Isaac's Bomben stick to enemies#Killing an enemy with a bomb spawns blue spiders"},
	{"368", "Epiphora", "↑ {{Tears}} Shooting in one direction gradually decreases tränenverzögerung up to 200%"},
	{"369", "Continuum", "↑ {{Range}} +2.25 Reichweite#↑ +1.5 Tränenhöhe#Spectral tears#Tränen can travel through one side of the screen and come out the other side"},
	{"370", "Mr. Dolly", "↑ {{Tears}} +0.7 Tränen#↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe#{{UnknownHeart}} Spawns 3 random hearts"},
	{"371", "Curse of the Tower", "{{Warning}} Taking damage spawns 6 Troll-Bomben#The Troll-Bomben inherit Isaac's bomb effects"},
	{"372", "Charged Baby", "Every 30 seconds while in an uncleared room, the familiar can:#{{Battery}} Spawn a Battery (max 2 per room)#{{Battery}} Add one charge to the active item (max 2 per room)#Petrify all enemies in the room"},
	{"373", "Dead Eye", "↑ {{Damage}} Consecutive tear hits on enemies grant +25% damage (max +100%)#Missing has a chance to reset the multiplier"},
	{"374", "Holy Light", "10% chance to shoot holy tears, which spawn a beam of light on hit#{{Luck}} 50% chance at 9 Glück#{{Damage}} The beam deals 4x Isaac's damage"},
	{"375", "Host Hat", "Grants immunity to explosions, rock wave attacks and Mom and Satan's stomp attacks#25% chance to reflect enemy shots"},
	{"376", "Restock", "Spawns 3 random pickups#Buying an item from a shop restocks it instantly"},
	{"377", "Bursting Sack", "Spider enemies no longer target or deal contact damage to Isaac"},
	{"378", "No. 2", "Holding a fire button for 2.35 seconds spawns a lit Butt Bomb"},
	{"379", "Pupula Duplex", "↑ {{Tearsize}} x2 Tear size#Spectral tears"},
	{"380", "Pay To Play", "{{Coin}} +5 Münzen#{{Coin}} Single-key doors must be opened with Münzen instead of Schlüssel"},
	{"381", "Eden's Blessing", "↑ {{Tears}} +0.7 Tränen#Grants a random item at the start of the next run"},
	{"382", "Friendly Ball", "Can be thrown at enemies to capture them#Using the item after capturing an enemy spawns it as a friendly companion"},
	{"383", "Tear Detonator", "Splits all of Isaac's tears currently on screen in a circle of 6 tears"},
	{"384", "Lil Gurdy", "{{Chargeable}} Launches and bounces around the room with speed based on charge amount#Deals 5-90 contact damage per second depending on speed"},
	{"385", "Bumbo", "{{Coin}} Picks up nearby Münzen#Levels up after getting 6, 12, and 24 Münzen#Lv2: Chance to spawn item after room clears#Lv3: Shoots tears that can spawn Münzen on hit#Lv4: Chases enemies, occasionally dropping Bomben, can spawn item on coin pickup"},
	{"386", "D12", "Rerolls any obstacle into another random obstacle (e.g. poop, pots, TNT, red poop, stone blocks etc.)"},
	{"387", "Censer", "{{Slow}} Familiar surrounded by a huge aura of light that slows down enemies and projectiles in it"},
	{"388", "Key Bum", "{{Key}} Picks up nearby Schlüssel#{{Chest}} Spawns random chests in return"},
	{"389", "Rune Bag", "{{Rune}} Spawns a random rune every 5-6 rooms"},
	{"390", "Seraphim", "Shoots Sacred Heart tears#Deals 10 damage per tear"},
	{"391", "Betrayal", "{{Charm}} Taking damage charms all enemies in the room"},
	{"392", "Zodiac", "Grants a random zodiac item effect every floor"},
	{"393", "Serpent's Kiss", "{{Poison}} 15% chance to shoot poison tears#{{Poison}} Poison enemies on contact#{{BlackHeart}} Poisoned enemies have a chance to drop a Black Heart on death"},
	{"394", "Marked", "↑ {{Tears}} +0.7 Tränen#↑ {{Range}} +3.15 Reichweite#↑ +0.3 Tränenhöhe#Isaac automatically shoots tears at a movable red target on the ground"},
	{"395", "Tech X", "{{Chargeable}} Isaac's tears are replaced by a chargeable laser ring#Ring size increases with charge amount"},
	{"396", "Ventricle Razor", "Creates up to two portals to travel between#Can be placed in different rooms"},
	{"397", "Tractor Beam", "↑ {{Tears}} +0.5 Tränen#↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe#↑ {{Shotspeed}} +0.16 Schusstempo#Isaac's tears always travel along a beam of light in front of him"},
	{"398", "God's Flesh", "Tränen can shrink enemies#Shrunken enemies can be crushed and killed by walking over them"},
	{"399", "Maw of the Void", "↑ {{Damage}} +1 Schaden#{{Chargeable}} Shooting tears for 2.35 seconds and releasing the fire button creates a black brimstone ring around Isaac#{{BlackHeart}} Enemies killed by the black ring have a chance to drop Black Hearts"},
	{"400", "Spear of Destiny", "Isaac holds a spear in front of him#{{Fear}} The spear deals twice his damage and can fear enemies on contact"},
	{"401", "Explosivo", "25% chance to shoot sticky bomb tears#Sticky bomb tears do not deal damage on hit and explode after a few seconds"},
	{"402", "Chaos", "All items are chosen from random Gegenstandspools#Spawns 1-6 random pickups"},
	{"403", "Spider Mod", "Displays tear damage and health bars of all enemies#Inflicts random status effects to enemies on contact#Randomly spawns batteries"},
	{"404", "Farting Baby", "Blocks projectiles#When hit, 10% chance to fart and {{Charm}} charm, {{Poison}} poison or knockback enemies"},
	{"405", "GB Bug", "Bounces around the room#Deals 120 damage per second and applies random status effects to enemies on contact"},
	{"406", "D8", "Multiplies Isaac's damage, tears, range and speed stats by between 0.5x and 2x#The multipliers are rerolled each use"},
	{"407", "Purity", "↑ Boosts one of Isaac's stats depending on the color of the aura#Taking damage removes the effect, and gives Isaac a new effect in the next room#{{ColorYellow}}Yellow{{CR}} = ↑ {{Speed}} +0.5 Tempo#{{ColorBlue}}Blue{{CR}} = ↑ {{Tears}} -4 Tränenverzögerung#{{ColorRed}}Red{{CR}} = ↑ {{Damage}} +4 Schaden#{{ColorOrange}}Orange{{CR}} = ↑ {{Range}} +7.5 Reichweite, ↑ +1 Tränenhöhe"},
	{"408", "Athame", "Taking damage creates a black brimstone ring around Isaac#{{BlackHeart}} Enemies killed by the ring have a 15% chance to drop a Black Heart"},
	{"409", "Empty Vessel", "{{BlackHeart}} +2 Black Hearts#{{EmptyHeart}} When Isaac has no Red Hearts:#Flug#Every 40 seconds while in a hostile room, gain a shield for 10 seconds"},
	{"410", "Evil Eye", "3.33% chance to shoot an eye#{{Luck}} 10% chance at 20 Glück#The eye moves in a straight line and shoots tears in the same direction as Isaac"},
	{"411", "Lusty Blood", "↑ {{Damage}} +0.5 Schaden for each enemy killed in the room#Caps at +5 Schaden after 10 kills"},
	{"412", "Cambion Conception", "Taking damage 15 times spawns a permanent demon familiar#After two familiars, it takes 30 instead of 15#Caps at 4 familiars"},
	{"413", "Immaculate Conception", "Picking up 15 hearts spawns a permanent angelic familiar#Caps at 5 familiars#{{SoulHeart}} If all familiars have been granted, spawns a Seelenherz instead"},
	{"414", "More Options", "{{TreasureRoom}} Allows Isaac to choose between 2 items in treasure rooms"},
	{"415", "Crown Of Light", "{{SoulHeart}} +2 Seelenherzen#If Isaac has no damaged heart containers:#↑ {{Damage}} x2 Schadens-Multiplikator#↑ {{Range}} +5.25 Reichweite#↑ +0.5 Tränenhöhe#↓ {{Shotspeed}} -0.3 Schusstempo#Taking any damage removes the effect für diesen Raum"},
	{"416", "Deep Pockets", "Allows Isaac to carry two runes/cards/pills"},
	{"417", "Succubus", "Bounces around the room surrounded by a damaging aura that deals 1.29x Isaac's damage per second#↑ {{Damage}} x1.5 Schadens-Multiplikator while standing in the aura"},
	{"418", "Fruit Cake", "Each one of Isaac's tears gets a different effect"},
	{"419", "Teleport 2.0", "Teleports Isaac to a room that has not been cleared yet#Hierarchy: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}{{BossRushRoom}}>{{IsaacsRoom}}{{BarrenRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}>{{ErrorRoom}}"},
	{"420", "Black Powder", "Walking in a circle draws a pentagram on the floor, which deals 10 damage per tick"},
	{"421", "Kidney Bean", "{{Charm}} Charms and deals 5 damage to all enemies in close range"},
	{"422", "Glowing Hour Glass", "Brings Isaac back to the previous room and reverses all actions done in the room the item was used in"},
	{"423", "Circle of Protection", "Surrounds Isaac with a large halo that deals his damage on contact per second#Chance to reflect enemy projectiles"},
	{"424", "Sack Head", "Pickups have a 33% chance to be replaced with a sack#Spawns a sack"},
	{"425", "Night Light", "{{Slow}} Spawns a slowing cone of light in front of Isaac"},
	{"426", "Obsessed Fan", "Mimics Isaac's exact movement on a 3 second delay#Deals 30 contact damage per second"},
	{"427", "Mine Crafter", "Spawns a pushable TNT barrel#Using the item a second time in the same room remotely detonates the barrel"},
	{"428", "PJs", "{{Heart}} Volle Gesundheit#{{SoulHeart}} +4 Seelenherzen"},
	{"429", "Head of the Keeper", "{{Coin}} Hitting an enemy with a tear has a 5% chance to spawn a Penny"},
	{"430", "Papa Fly", "Mimics Isaac's movement on a 1 second delay#Shoots tears at nearby enemies that deal Isaac's damage"},
	{"431", "Multidimensional Baby", "Mimics Isaac's movement on a 2 second delay#Tränen that pass through it are doubled and gain a range + shot speed boost"},
	{"432", "Glitter Bomben", "{{Bomb}} +5 Bomben#{{Charm}} Isaac's Bomben have a 25% chance to drop a random pickup and a 15% chance to charm enemies when they explode"},
	{"433", "My Shadow", "{{Fear}} Taking damage fears all enemies in the room and spawns a friendly black charger#The charger deals 5 damage per second"},
	{"434", "Jar of Flies", "Killing an enemy adds a blue fly to the jar, up to 20 flies#Using the item releases all the flies"},
	{"435", "Lil Loki", "Shoots 4 tears in a cross pattern#Deals 3.5 damage per tear"},
	{"436", "Milk!", "{{Tears}} Taking damage grants a Tränen up for the duration of the room"},
	{"437", "D7", "Restarts a room and respawns all enemies#Can be used to get multiple room clear rewards from a single room#If used after a Greed fight, rerolls the room into a normal Shop/Secret Room"},
	{"438", "Binky", "↑ {{Tears}} +0.75 Tränen#↑ Größe runter#{{SoulHeart}} +1 Seelenherz"},
	{"439", "Mom's Box", "{{Trinket}} Spawns a random trinket#While held:#↑ {{Luck}} +1 Glück#{{Trinket}} Doubles trinket effects"},
	{"440", "Kidney Stone", "↑ +2 Tränenhöhe#↓ {{Speed}} -0.2 Tempo#↓ {{Range}} -17 Reichweite#Isaac occasionally stops firing and charges an attack that releases a burst of tears and a kidney stone"},
	{"441", "Mega Blast", "{{Timer}} Fires a huge Mega Satan blood beam for 15 seconds#The beam persists between rooms and floors"},
	{"442", "Dark Prince's Crown", "While at 1 full Red Heart:#↑ {{Tears}} +0.75 Tränen#↑ {{Range}} +1.5 Reichweite#↑ +1 Tränenhöhe#↑ {{Shotspeed}} +0.2 Schusstempo"}, -- Dark Princes Crown (apostrophe added to the name in Repentance)
	{"443", "Apple!", "↑ {{Tears}} +0.3 Tränen#{{Damage}} 6.66% chance to shoot razor blades that deal 4x Isaac's damage#{{Luck}} 100% chance at 14 Glück"},
	{"444", "Lead Pencil", "Isaac shoots a cluster of tears every 15 tears#Tränen in the cluster deal double damage"},
	{"445", "Dog Tooth", "↑ {{Speed}} +0.1 Tempo#↑ {{Damage}} +0.3 Schaden#{{SecretRoom}}{{SuperSecretRoom}} A wolf howls in rooms adjacent to a Secret/Super Secret Room#{{LadderRoom}} A dog barks in rooms with a crawlspace under a rock"},
	{"446", "Dead Tooth", "{{Poison}} While firing, Isaac is surrounded by a green aura that poisons enemies"},
	{"447", "Linger Bean", "Firing without pause for 7.5 seconds spawns a poop cloud#The cloud deals Isaac's damage 5 times a second#The cloud lasts 15 seconds and can be moved by shooting it"},
	{"448", "Shard of Glass", "Upon taking damage:#{{Heart}} 25% chance to spawn a Red Heart#{{Collectible214}} 10% chance to get ↑ {{Range}} +5 Reichweite and leave a trail of blood creep für diesen Raum"},
	{"449", "Metal Plate", "{{SoulHeart}} +1 Seelenherz#{{Confusion}} Enemy bullets have a 25% chance to be reflected as concussive tears"},
	{"450", "Eye of Greed", "Every 20 tears, Isaac shoots a coin tear that deals double damage#Enemies hit with the coin get petrified and turn into gold#{{Coin}} Killing a gold enemy drops 1-4 Münzen#{{Warning}} Firing a coin tear costs 1 coin"},
	{"451", "Tarot Cloth", "{{Card}} Spawns a card#{{Card}} Card effects are doubled or enhanced"},
	{"452", "Varicose Veins", "Taking damage shoots 10 tears in a circle around Isaac#The tears deal Isaac's damage + 25"},
	{"453", "Compound Fracture", "↑ {{Range}} +1.5 Reichweite#↑ +1 Tränenhöhe#Tränen shatter into 1-3 small bone shards upon hitting anything"},
	{"454", "Polydactyly", "Spawns a {{Rune}} rune, {{Card}} card or {{Pill}} pill on pickup#Allows Isaac to carry 2 runes/cards/pills"},
	{"455", "Dad's Lost Coin", "↑ {{Range}} +1.5 Reichweite#↑ +1 Tränenhöhe#{{Luck}} Spawns a Lucky Penny"},
	{"456", "Moldy Bread", "↑ {{Heart}} +1 Gesundheit"},
	{"457", "Cone Head", "{{SoulHeart}} +1 Seelenherz#20% chance to negate damage taken"},
	{"458", "Belly Button", "{{Trinket}} Allows Isaac to carry 2 trinkets#{{Trinket}} Spawns a random trinket"},
	{"459", "Sinus Infection", "20% chance to shoot a sticky booger#{{Damage}} Boogers deal Isaac's damage once a second and stick for 60 seconds#{{Luck}} Not affected by Glück"},
	{"460", "Glaucoma", "{{Confusion}} 5% chance to shoot concussive tears#Makes the screen slightly darker"},
	{"461", "Parasitoid", "15% chance to shoot egg sacks#{{Luck}} 50% chance at 5 Glück#{{Slow}} Egg sacks spawn slowing creep and a blue spider or fly on hit"},
	{"462", "Eye of Belial", "↑ {{Range}} +1.5 Reichweite#↑ +1 Tränenhöhe#Durchdringende Tränen#Hitting an enemy makes the tear homing and doubles its damage"},
	{"463", "Sulfuric Acid", "↑ {{Damage}} +0.3 Schaden#Isaac's tears can destroy rocks and open doors"},
	{"464", "Glyph of Balance", "{{SoulHeart}} +2 Seelenherzen#Champion enemies drop whatever pickup Isaac needs the most"},
	{"465", "Analog Stick", "↑ {{Tears}} +0.3 Tränen#Allows Isaac to shoot tears in any direction"},
	{"466", "Contagion", "{{Poison}} The first enemy killed in a room explodes and poison all nearby enemies"},
	{"467", "Finger!", "{{Damage}} Constantly deals 10% of Isaac's damage in the direction it points"},
	{"468", "Shade", "Follows Isaac's movement on a 1 second delay#Deals 30 contact damage per second#After it deals 600 damage, it is absorbed by Isaac, increasing his contact damage"},
	{"469", "Depression", "Leaves a trail of creep#The creep deals 6 damage per second#Enemies that touch the cloud can be hit by a holy light beam"},
	{"470", "Hushy", "Bounces around the room#Deals contact damage#Stops moving when Isaac shoots#Blocks projectiles when stopped"},
	{"471", "Lil Monstro", "{{Chargeable}} Charges a shotgun attack similar to {{Collectible229}} Monstro's Lung#Each tear deals 3.5 damage"},
	{"472", "King Baby", "Other familiars follow it#Stops moving when Isaac shoots#Teleports back to Isaac when he stops shooting"},
	{"473", "Big Chubby", "Very slowly charges forwards#Blocks shots#Deals 40.5 contact damage per second"},
	{"474", "Tonsil", "Blocks enemy projectiles"},
	{"475", "Plan C", "{{Warning}} SINGLE USE {{Warning}}#Deals 9,999,999 damage to all enemies#{{Warning}} Kills Isaac 3 seconds later"},
	{"476", "D1", "Duplicates a random pickup in the room"},
	{"477", "Void", "Consumes all pedestal items in the room#Active items: Their effects activate, and will activate with every future use of Void#↑ Passive items grant two random stat ups"},
	{"478", "Pause", "Pauses all enemies in the room until Isaac shoots#Touching a paused enemy still deals damage to Isaac#Enemies unpause after 30 seconds"},
	{"479", "Smelter", "{{Trinket}} Consumes Isaac's held trinkets and grants their effects permanently#Increases the spawn rate of trinkets"},
	{"480", "Compost", "Converts pickups into blue flies or spiders#Doubles all blue flies and spiders#Spawns 1 blue fly or spider if Isaac has none"},
	{"481", "Dataminer", "↑ Random stat up#↓ Random stat down#{{Timer}} Random tear effect für diesen Raum#{{Blank}} Corrupts all sprites and music in the room"},
	{"482", "Clicker", "Changes your character to a random character#Removes the most recent item collected"},
	{"483", "Mama Mega!", "{{Warning}} SINGLE USE {{Warning}}#Affects the whole floor#Explodes all objects#Deals 200 damage to all enemies#Opens the door to Boss Rush, Hush and all secret rooms#Having a golden bomb when using the item consumes it and allows for another use of Mama Mega"},
	{"484", "Wait What?", "Upon use, pushes enemies away and spawns a rock wave around Isaac#The rock wave can open rooms and break rocks"},
	{"485", "Crooked Penny", "50% chance to double all items, pickups and chests in room#50% chance to remove items / pickups in room and spawn 1 coin"},
	{"486", "Dull Razor", "Hurts Isaac without removing health#Triggers any on-hit item effects"},
	{"487", "Potato Peeler", "{{EmptyHeart}} Removes 1 heart container for:#↑ {{Damage}} +0.2 Schaden#{{Collectible73}} A Cube of Meat#{{Timer}} Erhalte für diesen Raum:#↑ {{Range}} +5 Reichweite#{{Collectible214}} Leave a trail of blood creep"},
	{"488", "Metronome", "Grants a random item effect für diesen Raum"},
	{"489", "D Infinity", "Triggers a random dice effect each use"},
	{"490", "Eden's Soul", "{{Warning}} SINGLE USE {{Warning}}#Spawns 2 random items depending on the current room's Gegenstandspool#Starts with no charges"},
	{"491", "Acid Baby", "{{Pill}} Spawns a random pill every 3 rooms#{{Poison}} Using a pill poisons all enemies in the room"},
	{"492", "YO LISTEN!", "↑ {{Luck}} +1 Glück#Highlights the location of {{SecretRoom}} secret rooms, tinted rocks and {{LadderRoom}} crawlspaces"},
	{"493", "Adrenaline", "For every empty heart container:#↑ {{Damage}} +0.2 Schaden"},
	{"494", "Jacob's Ladder", "Tränen spawn 1-2 sparks of electricity on impact#Sparks deal half of Isaac's damage"},
	{"495", "Ghost Pepper", "Chance to shoot a red flame that blocks enemy shots and deals contact damage#The flame disappears after dealing damage or blocking shots 5 times"},
	{"496", "Euthanasia", "3.33% chance to shoot a needle#{{Luck}} 100% chance at 15 Glück#Needles kill normal enemies instantly, bursting them into 10 tears#{{Damage}} Needles deal 3x Isaac's damage against bosses"},
	{"497", "Camo Undies", "{{Confusion}} Entering a room confuses all enemies until Isaac starts shooting"},
	{"498", "Duality", "{{AngelDevilChance}} Spawns both an Angel and Devil Room if either would have spawned#Entering one makes the other disappear"},
	{"499", "Eucharist", "{{AngelChance}} 100% chance for Angel Rooms to spawn"},
	{"500", "Sack of Sacks", "Spawns a sack every 5-6 rooms"},
	{"501", "Greed's Gullet", "{{Heart}} +1 Heart container for every 25 Münzen gained after getting Greed's Gullet#{{Player14}} Keeper can gain additional coin containers"},
	{"502", "Large Zit", "{{Slow}} Firing occasionally shoots a white creep tear that deals double damage and slows enemies#Taking damage shoots a white creep tear"},
	{"503", "Little Horn", "5% chance to shoot tears that instantly kill enemies#{{Luck}} 20% chance at 15 Glück#Isaac deals 3.5 contact damage"},
	{"504", "Brown Nugget", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
	{"505", "Poke Go", "Entering a hostile room has a chance to spawn a charmed enemy"},
	{"506", "Backstabber", "{{BleedingOut}} Hitting an enemy in the back deals double damage and causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds"},
	{"507", "Sharp Straw", "{{Damage}} Deals Isaac's damage + 10% of the enemy's max health to all enemies#{{HalfHeart}} Dealing damage with the Straw can spawn half hearts#{{HalfSoulHeart}} Having no heart containers drops Seelenherzen instead"},
	{"508", "Mom's Razor", "{{BleedingOut}} Orbital that causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds#{{Damage}} Deals 3x Isaac's damage per second#Does not block shots"},
	{"509", "Bloodshot Eye", "Orbital that shoots a tear in a random direction every 2 seconds#Deals 3.5 damage per tear#Deals 30 contact damage per second#Does not block shots"},
	{"510", "Delirious", "{{Timer}} Spawns a friendly delirium version of a boss für diesen Raum"},
	{"511", "Angry Fly", "Orbits a random enemy until that enemy dies#Deals 30 contact damage per second to other enemies"},
	{"512", "Black Hole", "Throwable black hole, which sucks in everything#Deals 0.4 damage every tick#Destroys nearby rocks#Lasts 6 seconds"},
	{"513", "Bozo", "↑ {{Damage}} +0.1 Schaden#{{SoulHeart}} +1 Seelenherz#{{Charm}} Randomly charms/fears enemies#Taking damage has a random chance to spawn a Rainbow Poop"},
	{"514", "Broken Modem", "Causes some enemies and projectiles to briefly pause at random intervals#25% chance to double room clear drops"},
	{"515", "Mystery Gift", "{{Warning}} SINGLE USE {{Warning}}#Spawns a random item from the current room's Gegenstandspool#Chance to spawn Lump of Coal or The Poop instead"},
	{"516", "Sprinkler", "Spawns a Sprinkler that shoots the same tears as Isaac in a circle around itself"},
	{"517", "Fast Bomben", "{{Bomb}} +7 Bomben#Removes the delay between bomb placements"},
	{"518", "Buddy in a Box", "Familiar which looks like a random co-op baby#Has random tear effects#Effects change every floor"},
	{"519", "Lil Delirium", "Transforms into a random familiar every 10 seconds"},
	{"520", "Jumper Cables", "Killing 15 enemies adds 1 charge to the active item"},
	{"521", "Coupon", "Makes one random item in the {{Shop}} Shop or {{DevilRoom}} Devil Room free#Holding the item guarantees one Shop item is on sale"},
	{"522", "Telekinesis", "Stops all enemy projectiles that come close to Isaac for 3 seconds and throws them away from him afterwards"},
	{"523", "Moving Box", "Stores all pickups and items from the current room#Using the item again drops everything back on the floor#Allows Isaac to move things between rooms"},
	{"524", "Technology Zero", "Isaac's tears are connected with beams of electricity#The beams deal the same damage as Isaac"},
	{"525", "Leprosy", "Taking damage spawns a projectile blocking orbital#Caps at 3 orbitals#Orbitals are destroyed if they take too much damage"},
	{"526", "7 Seals", "Spawns a small horseman familiar that spawns locusts#The horseman and its locust changes every 10 seconds"},
	{"527", "Mr. ME!", "Displays a movable cursor for a few seconds, then summons a ghost that will, depending on the cursor position:#Open doors or chests#Fetch an item#50% chance to steal from the shop / devil#Attack an enemy until it dies#Explode walls, rocks, shopkeepers, angel statues, machines, beggars"},
	{"528", "Angelic Prism", "Orbital prism#Friendly tears hitting it split into 4"},
	{"529", "Pop!", "Isaac's tears bounce off each other and disappear when they stop moving"},
	{"530", "Death's List", "Killing enemies in the order dictated by the mark {{DeathMark}} above them grants a random pickup or stat increase"},
	{"531", "Haemolacria", "↑ {{Damage}} x1.31 Schadens-Multiplikator#↓ {{Tears}} x2 Tränenverzögerungs-Multiplikator#↓ {{Tears}} +10 Tränenverzögerung#Isaac's tears fly in an arc and burst into smaller tears on impact"},
	{"532", "Lachryphagy", "Isaac's tears progressively slow down, stop, then explode into 8 smaller tears#Tränen can merge and become bigger"},
	{"533", "Trisagion", "Replaces Isaac's tears with piercing beams of light#The beams deal 33% damage but can hit enemies multiple times"},
	{"534", "Schoolbag", "Allows Isaac to hold 2 active items#The items can be swapped using the Drop button ({{ButtonRT}})"},
	{"535", "Blanket", "{{Heart}} Heals 1 heart#{{SoulHeart}} +1 Seelenherz#{{HolyMantle}} Entering a boss room grants a Holy Mantle shield (prevents damage once)"},
	{"536", "Sacrificial Altar", "{{Warning}} SINGLE USE {{Warning}}#Sacrifices up to 2 familiars and spawns a devil item for each sacrifice#{{Coin}} Turns blue spiders/flies into Münzen"},
	{"537", "Lil Spewer", "{{Pill}} Spawns a random pill on pickup#Fires a line of creep#The type of creep changes with each pill use"},
	{"538", "Marbles", "{{Trinket}} Spawns 3 random trinkets#{{Collectible479}} Taking damage can remove Isaac's held trinket and grant its effects permanently"},
	{"539", "Mystery Egg", "Taking damage spawns a charmed enemy#Spawns stronger friends the more rooms are cleared without taking damage"},
	{"540", "Flat Stone", "Isaac's tears bounce off the floor and cause splash damage on every bounce"},
	{"541", "Marrow", "{{Heart}} Spawns 3 Red Hearts#{{EmptyBoneHeart}} +1 Bone Heart"},
	{"542", "Slipped Rib", "Orbital#Reflects enemy projectiles"},
	{"543", "Hallowed Ground", "Taking damage spawns a white poop#While inside the poop's aura:#↑ {{Tears}} x0.5 Tränenverzögerungs-Multiplikator#Chance to block damage"},
	{"544", "Pointy Rib", "Levitates in front of Isaac#Deals 6x Isaac's damage per second"},
	{"545", "Book of the Dead", "Spawns a bone orbital or charmed bony per enemy killed in the room"},
	{"546", "Dad's Ring", "Grants an aura that petrifies enemies"},
	{"547", "Divorce Papers", "↑ {{Tears}} +0.7 Tränen#{{EmptyBoneHeart}} +1 Bone Heart#{{Trinket21}} Spawns the Mysterious Paper trinket"},
	{"548", "Jaw Bone", "Boomerang-like familiar#Deals 7 contact damage#Can grab and bring back pickups"},
	{"549", "Brittle Bones", "{{EmptyBoneHeart}} Replaces all of Isaac's Red Heart containers with 6 empty Bone Hearts#Upon losing a Bone Heart:#↑ {{Tears}} +0.5 Tränen#Shoots 8 bone tears in all directions"},
	{"550", "Broken Shovel", "Mom's Foot constantly tries to stomp Isaac#Using the item stops the stomping für diesen Raum#{{Warning}} (Try to beat Boss Rush with it!)"},
	{"551", "Broken Shovel", "Completes Mom's Shovel#{{Warning}} Use the shovel on the mound of dirt in the \"Dark Room\""},
	{"552", "Mom's Shovel", "Spawns a trapdoor to the next floor#10% chance for {{LadderRoom}} crawlspace trapdoor#{{Warning}} Use the shovel on the mound of dirt in the \"Dark Room\""},
}

---------- Modifiers ----------

-- Effect of Car battery on Active Items
-- these all need way more consistency with the original effect text and spellchecking
EID.descriptions[languageCode].carBattery = {
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- Trinkets ----------

EID.descriptions[languageCode].trinkets={
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- Cards ----------

EID.descriptions[languageCode].cards={
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- Pills ----------

EID.descriptions[languageCode].unidentifiedPill = "Unidentifizierte Pille"

EID.descriptions[languageCode].pills={
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- Sacrifice Room ----------

EID.descriptions[languageCode].sacrificeHeader = "[Nächste Opferungsbelohung]"

EID.descriptions[languageCode].sacrifice={
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- Dice Room ----------

EID.descriptions[languageCode].diceHeader = "[Würfel Effekte]"

EID.descriptions[languageCode].dice={
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- Transformations ----------

EID.descriptions[languageCode].transformations = {
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
}

---------- MISC ----------

EID.descriptions[languageCode].VoidText = "Wenn absorbiert, erhalte:"
-- {1} will become the number text (like "{1} Tränen" -> "+0.5 Tränen")
EID.descriptions[languageCode].VoidNames = {"{1} Tempo", "{1} Tränen", "{1} Schaden", "{1} Reichweite", "{1} Schusstempo", "{1} Glück"}
	-- Not yet Translated!
	-- Copy & Paste entries from en_us and continue translating from that
