------------------------------------------------------------------
-----  Basic English descriptions based on Platinumgod.co.uk -----
------------------------------------------------------------------

-- FORMAT: Item ID | Name| Description
-- '#' = starts new line of text

--Special character markup:
-- ↑ = Up Arrow   |  ↓ = Down Arrow    | ! = Warning

-- init en_us table
EID.descriptions["en_us"] = {}
EID.descriptions["en_us"].custom = {} -- table for custom entity descriptions

EID.descriptions["en_us"].collectibles={
	{"1", "The Sad Onion", "↑ +0.7 Tears up"},
	{"2", "The Inner Eye", "Triple shot#↓ Tears down"},
	{"3", "Spoon Bender", "Homing tears"},
	{"4", "Cricket's Head", "↑ +0.5 Damage up#↑ +50% Damage Multiplier"},
	{"5", "My Reflection", "Gives tears a boomerang effect#↑ +1.5 Range up#↑ +0.6 Shot Speed up#↑ +1 Tear Height"},
	{"6", "Number One", "↑ +1.5 Tears up#↓ -17.62 Range down#↑ +0.76 Tear Height"},
	{"7", "Blood of the Martyr", "↑ +1.0 Damage up#↑ +50% if you have Book of Belial"},
	{"8", "Brother Bobby", "Normal tear familiar#Deals 3.5 Damage per tear"},
	{"9", "Skatole", "All fly enemies are friendly"},
	{"10", "Halo of Flies", "+2 fly orbitals#Blocks enemy projectiles"},
	{"11", "1up!", "↑ +1 life#Respawn with full health"},
	{"12", "Magic Mushroom", "↑ +1 Health up#↑ +0.3 Damage up#↑ +50% Damage Multiplier#↑ +5.25 Range up#↑ +0.3 Speed up#↑ +0.5 Tear Height#Full health!"},
	{"13", "The Virus", "Poison touch#↓ -0.1 Speed down#Enemies can drop black hearts if poisoned"},
	{"14", "Roid Rage", "↑ +0.6 Speed up#↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"15", "<3", "↑ +1 Health up#Full health"},
	{"16", "Raw Liver", "↑ +2 Health up#Full health"},
	{"17", "Skeleton Key", "+99 Keys"},
	{"18", "A Dollar", "+99 Coins"},
	{"19", "Boom!", "+10 Bombs"},
	{"20", "Transcendence", "Flight!"},
	{"21", "The Compass", "Reveals all icons on the map#Does not show the layout of the map"},
	{"22", "Lunch", "↑ +1 Health up"},
	{"23", "Dinner", "↑ +1 Health up"},
	{"24", "Dessert", "↑ +1 Health up"},
	{"25", "Breakfast", "↑ +1 Health up"},
	{"26", "Rotten Meat", "↑ +1 Health up"},
	{"27", "Wooden Spoon", "↑ +0.3 Speed up"},
	{"28", "The Belt", "↑ +0.3 Speed up"},
	{"29", "Mom's Underwear", "↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"30", "Mom's Heels", "↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"31", "Mom's Lipstick", "↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"32", "Wire Coat Hanger", "↑ +0.7 Tears up"},
	{"33", "The Bible", "Flight for current room#Kills Mom Foot and Moms heart instantly#!!! Kills YOU when used on Satan"},
	{"34", "The Book of Belial", "↑ +2 Damage up#↑ +12.5% devil deal chance#↑ +50% Damage Multiplier if you have Blood of the Martyr"},
	{"35", "The Necronomicon", "Deal 40 damage to everything in the room"},
	{"36", "The Poop", "Spawns one poop#Can be placed next to a pit and destroyed with a bomb to make a bridge"},
	{"37", "Mr. Boom", "Drops a large bomb below the player which deals 110 damage"},
	{"38", "Tammy's Head", "Fires 10 tears in a circle around Isaac"},
	{"39", "Mom's Bra", "Freeze all enemies in the current room for 4 secs"},
	{"40", "Kamikaze!", "Causes an explosion at the players location#Deals 40 damage"},
	{"41", "Mom's Pad", "Fears all enemies in the current room for 5 secs"},
	{"42", "Bob's Rotten Head", "Throwable poison bomb"},
	{"43", "", "<item does not exist>"},
	{"44", "Teleport!", "Teleports Isaac into a random room except I AM ERROR rooms"},
	{"45", "Yum Heart", "Heal 1 red heart"},
	{"46", "Lucky Foot", "↑ +1.0 Luck up#Better chance to win while gambling#Increases room clearing drop chance"},
	{"47", "Doctor's Remote", "Epic Fetus on demand!#Controllable Airstrikes"},
	{"48", "Cupid's Arrow", "Piercing tears"},
	{"49", "Shoop da Whoop!", "High damage brimstone laser"},
	{"50", "Steven", "↑ +1 Damage up"},
	{"51", "Pentagram", "↑ +1.0 Damage up#↑ +10% Devil deal chance"},
	{"52", "Dr. Fetus", "Bomb tears!"},
	{"53", "Magneto", "Magnetic attraction for Pick-ups"},
	{"54", "Treasure Map", "Reveals the floor-layout"},
	{"55", "Mom's Eye", "Chance to shoot a tear backwards#Chance is 100% at 2 Luck"},
	{"56", "Lemon Mishap", "Drop a pool of lemonade#Deals 66 contact Damage per second"},
	{"57", "Distant Admiration", "Mid-range fly orbital#Deals 75 contact Damage per second"},
	{"58", "Book of Shadows", "Invincibility for 10 secs"},
	{"59", "", "<item does not exist>"},
	{"60", "The Ladder", "Walk over small gaps"},
	{"61", "", "<item does not exist>"},
	{"62", "Charm of the Vampire", "Heals half a heart every 13 enemies killed"},
	{"63", "The Battery", "Spacebar items can now be charged up twice"},
	{"64", "Steam Sale", "-50% on shop items#Getting this item two times will make everything free"},
	{"65", "Anarchist Cookbook", "Spawn 6 troll bombs near the center of the room"},
	{"66", "The Hourglass", "Slow down enemies for 8 secs"},
	{"67", "Sister Maggy", "Normal tear familiar#Deals 3.5 Damage per tear"},
	{"68", "Technology", "Tears are now lasers"},
	{"69", "Chocolate Milk", "Chargeable tears#↑ up to 400% Damage#↓ Tears down"},
	{"70", "Growth Hormones", "↑ +1.0 Damage up#↑ +0.4 Speed up"},
	{"71", "Mini Mush", "↑ +0.3 Speed up#↓ -4.25 Range down*#↑ +1.5 Tear height*#(*both add up to a slight Range up)#↑ Size down"},
	{"72", "Rosary", "+3 Soul Hearts#Bible is more common"},
	{"73", "Cube of Meat", "LVL1: Orbital#LVL2: Shooting orbital#LVL3: Meat boy LVL 1#LVL4: Meat boy LVL 2"},
	{"74", "A Quarter", "+25 coins"},
	{"75", "PHD", "Better pills# +1 pill#Heals 2 hearts#More money from Blood Donation Machines"},
	{"76", "X-Ray Vision", "Reveals secret rooms entrances"},
	{"77", "My Little Unicorn", "Invincibility#40 contact damage"},
	{"78", "Book of Revelations", "+1 Soul heart#Higher horsemen chance if used#↑ +17.5% devil deal chance"},
	{"79", "The Mark", "↑ +1.0 Damage up#↑ +0.2 Speed up#+1 Soul Heart"},
	{"80", "The Pact", "↑ +0.5 Damage up#↑ +0.7 Tears up#+2 Soul Hearts"},
	{"81", "Dead Cat", "↑ +9 Lives#Respawn with 1 Heart#↓ Sets your red heart count to 1"},
	{"82", "Lord of the Pit", "Flight#↑ +0.3 Speed up"},
	{"83", "The Nail", "+1 Soul heart#↑ +0.7 Damage up#↓ -0.18 Speed down#Deal contact Damage#Crush rocks"},
	{"84", "We Need To Go Deeper!", "Spawns a trapdoor to skip the floor#10% chance for crawlspace trapdoor"},
	{"85", "Deck of Cards", "Spawns 1 Card"},
	{"86", "Monstro's Tooth", "Summon Monstro for one stomp"},
	{"87", "Loki's Horns", "Chance to fire in 4 directions"},
	{"88", "Little Chubby", "Familiar that charges forward#Deals 52.5 contact damage per second"},
	{"89", "Spider Bite", "Chance to shoot slowing tears"},
	{"90", "The Small Rock", "↑ +1 Damage up#↑ +0.2 Tears up#↓ -0.2 Speed down"},
	{"91", "Spelunker Hat", "Reveals the room type of adjacent rooms#Can also reveal Secret Rooms, Super Secret Rooms, and Mini-Boss Rooms"},
	{"92", "Super Bandage", "↑ +1 Health up#+2 Soul heart"},
	{"93", "The Gamekid", "Invincibility +contact damage#Eating an enemy regenerates health"},
	{"94", "Sack of Pennies", "Drops a random coin every 2 rooms"},
	{"95", "Robo-Baby", "Laser tears#Deals 3.5 damage per shot"},
	{"96", "Little C.H.A.D.", "Drops half a heart every 3 rooms"},
	{"97", "The Book of Sin", "Spawns a random Pick-Up"},
	{"98", "The Relic", "Spawns 1 Soul heart every 5-6 rooms"},
	{"99", "Little Gish", "Slowing tears#Deals 3.5 damage per shot"},
	{"100", "Little Steven", "Homing tears#Deals 3.5 damage per shot"},
	{"101", "The Halo", "↑ +1 Health up#↑ +0.3 Damage up#↑ +0.2 Tears up#↑ +0.25 Range up#↑ +0.3 Speed up#↑ +0.5 Tear Height"},
	{"102", "Mom's Bottle of Pills", "Spawns 1 Pill"},
	{"103", "The Common Cold", "Chance to shoot Poison tears"},
	{"104", "The Parasite", "Tears split in two on contact#Splitted tears deal half damage"},
	{"105", "The D6", "Rerolls pedestals in current room"},
	{"106", "Mr. Mega", "↑ Bomb damage x2.25#+5 Bombs"},
	{"107", "The Pinking Shears", "Flight#Your body attacks enemies with 82.5 contact damage per second"},
	{"108", "The Wafer", "All damage taken is reduced to half a heart"},
	{"109", "Money = Power", "↑ +0.04 Damage up for every coin you have"},
	{"110", "Mom's Contacts", "Chance to shoot Freezing Tears#↑ +0.25 Range up#↑ +0.5 Tear Height"},
	{"111", "The Bean", "Poison fart"},
	{"112", "Guardian Angel", "Orbital#Speeds up all orbitals#Blocks projectiles#Deals 105 contact damage per second"},
	{"113", "Demon Baby", "Auto-firing turret#Deals 3 damage per shot"},
	{"114", "Mom's Knife", "Controllable knife attack#The knife deals 2x Isaac's damage while held and 6x damage at the furthest possible distance"},
	{"115", "Ouija Board", "Spectral tears"},
	{"116", "9 Volt", "-1 Charge for active items#Fully charges current item"},
	{"117", "Dead Bird", "Spawns a bird when you get hit#Bird deals 4 contact damage per second"},
	{"118", "Brimstone", "Charge a blood laser that deals constant damage"},
	{"119", "Blood Bag", "↑ +1 Health up#↑ +0.3 Speed up#Heals 5 Hearts"},
	{"120", "Odd Mushroom", "↑ +1.7 Tears up#↑ +0.3 Speed up#↓ -10% Damage down#↓ -0.4 additional Damage down"},
	{"121", "Odd Mushroom", "↑ +1 Empty heart container#↑ +0.3 Damage up#↑ +0.25 Range up#↓ -0.1 Speed down#↑ +0.5 Tear Height"},
	{"122", "Whore of Babylon", "!!! When on Half a red heart or less:#↑ +1.5 Damage up#↑ +0.3 Speed up"},
	{"123", "Monster Manual", "Random familiar for current room"},
	{"124", "Dead Sea Scrolls", "Random active item effect"},
	{"125", "Bobby-Bomb", "Homing bombs#+5 Bombs"},
	{"126", "Razor Blade", "↑ +1.2 Damage up for current Room#↓ Deals 1 heart of damage to you"},
	{"127", "Forget Me Now", "{{Warning}} ONE TIME USAGE {{Warning}}#Reroll entire floor"},
	{"128", "Forever alone", "Fly orbital#Far away#Deals 30 contact damage per second"},
	{"129", "Bucket of Lard", "↑ +2 Empty heart container#↓ -0.2 Speed down#Heals half a heart"},
	{"130", "A Pony", "Grants flight while held#Sets your speed to 1.5 if you have less than 1.5#Dash in a direction on use"},
	{"131", "Bomb Bag", "Drops 1 Bomb Pick-up every 2-3 rooms"},
	{"132", "A Lump of Coal", "More Damage based on traveled distance of the tear"},
	{"133", "Guppy's Paw", "!!! Convert:#1 Red heart to 3 Soul hearts"},
	{"134", "Guppy's Tail", "More chests appear"},
	{"135", "IV Bag", "Portable blood bank#Half a heart = 1-3 Coin"},
	{"136", "Best Friend", "Exploding Decoy#Attracts enemies"},
	{"137", "Remote Detonator", "Detonate bombs on demand#+5 bombs"},
	{"138", "Stigmata", "↑ +1 Health up#↑ +0.3 Damage up"},
	{"139", "Mom's Purse", "You can now hold 2 trinkets"},
	{"140", "Bob's Curse", "Poison bombs#+5 bombs"},
	{"141", "Pageant Boy", "Spawns 7 random coins"},
	{"142", "Scapular", "When damaged down to half a heart, you gain 1 Soul heart#(Once per room)"},
	{"143", "Speed Ball", "↑ +0.3 Speed up#↑ +0.2 Shot Speed up"},
	{"144", "Bum Friend", "Converts Coins into Pick-ups"},
	{"145", "Guppy's Head", "Spawns 2-4 blue flies"},
	{"146", "Prayer Card", "+1 eternal heart"},
	{"147", "Notched Axe", "Break rocks in current room on touch"},
	{"148", "Infestation", "Spawn flies when you get hit"},
	{"149", "Ipecac", "Explosive poison tears#↑ +40 Damage up#↓ Tears down"},
	{"150", "Tough Love", "Chance to shoot teeth#Teeth deal 3.2x your damage"},
	{"151", "The Mulligan", "1/6 chance to spawn a fly when tears hit an enemy"},
	{"152", "Technology 2", "Permanent laser attack!#↓ -35% Damage down"},
	{"153", "Mutant Spider", "Quad Shot!#↓ Tears down"},
	{"154", "Chemical Peel", "↑ +2 Damage up for left eye"},
	{"155", "The Peeper", "Floats around the room#Deals 17.1 contact damage per second"},
	{"156", "Habit", "+1 Charge when you get hit"},
	{"157", "Bloody Lust", "↑ Damage up every time you get hit#Applies up to 6 times per floor#Lasts for whole floor"},
	{"158", "Crystal Ball", "Reveal full map#Drops random Card or soul heart"},
	{"159", "Spirit of the Night", "Flight#Spectral tears"},
	{"160", "Crack the Sky", "Spawns 5 beams of light near enemies#Deals your damage+20"},
	{"161", "Ankh", "Respawn as ??? (Blue Baby) on death"},
	{"162", "Celtic Cross", "Chance for invincibility when Isaac gets hit"},
	{"163", "Ghost Baby", "Spectral tears familiar#Deals 3.5 damage per shot"},
	{"164", "The Candle", "Spawns a blue fire#Deals contact damage#Blocks enemy tears#Despawns after 2 seconds"},
	{"165", "Cat-o-nine-tails", "↑ +1 Damage up#↑ +0.23 Shot speed up"},
	{"166", "D20", "Reroll Pick-ups"},
	{"167", "Harlequin Baby", "Shoots two tears in a V-shaped pattern#Deals 4 damage per shot"},
	{"168", "Epic Fetus", "Controllable airstrike instead of tears#Deals 20 times your damage"},
	{"169", "Polyphemus", "Mega Tears!#↑ +100% Damage up#↑ +4 additional Damage up#↓ Tears down"},
	{"170", "Daddy Longlegs", "Stomps on enemies#Deals 40 damage per second"},
	{"171", "Spider Butt", "Slows down enemies for 4 seconds#10 Damage to all enemies"},
	{"172", "Sacrificial Dagger", "Orbital knife#Blocks enemy shots#Deals 225 damage per second"},
	{"173", "Mitre", "Higher chance to find soul hearts"},
	{"174", "Rainbow Baby", "Shoots random tears#Deals 3-5 damage per shot"},
	{"175", "Dad's Key", "Opens all doors in the current room, including secret rooms"},
	{"176", "Stem Cells", "↑ +1 Health up#↑ +0.16 Shot Speed up"},
	{"177", "Portable Slot", "Portable slot machine"},
	{"178", "Holy Water", "Leaves pool of creep when you get hit#Deals 24 damage per second"},
	{"179", "Fate", "Flight#+1 eternal heart"},
	{"180", "The Black Bean", "Fart when touched"},
	{"181", "White Pony", "Grants flight while hold#Sets your speed to 1.5 if you have less than 1.5#Holy Dash on use"},
	{"182", "Sacred Heart", "Homing tears#↑ +1 Health up#↑ 230% + 1 Damage up#↓ -0.4 Tears down#↓ -0.25 Shot Speed down#↑ +4.125 Range up"},
	{"183", "Tooth Picks", "↑ +0.7 Tears up.#↑ +0.16 Shot Speed up"},
	{"184", "Holy Grail", "Grants flight#↑ +1 Health up"},
	{"185", "Dead Dove", "Flight#Spectral tears"},
	{"186", "Blood Rights", "Deal 40 Damage to every enemy#Deals 1 damage to you on use"},
	{"187", "Guppy's Hairball", "Growing hairball#Swings around you#Grows when it kills an enemy#Bigger ball deals more damage"},
	{"188", "Abel", "Mirrors your movement#Shoots towards the player#Deals 3.5 damage per shot"},
	{"189", "SMB Super Fan", "↑ +1 Health up#↑ +0.3 Damage up#↑ +0.2 Tears up#↑ +0.5 Range up#↑ +0.2 Speed up#↑ +1.0 Tear Height#Full health"},
	{"190", "Pyro", "+99 Bombs"},
	{"191", "3 Dollar Bill", "Random tear effect every 2-3 seconds"},
	{"192", "Telepathy For Dummies", "Homing tears for current room"},
	{"193", "MEAT!", "↑ +1 Health up#↑ +0.3 Damage up"},
	{"194", "Magic 8 Ball", "↑ +0.16 Shot speed up#+1 card"},
	{"195", "Mom's Coin Purse", "Drops 4 Pills"},
	{"196", "Squeezy", "Spawns 2 Soul hearts#↑ +0.4 Tears up"},
	{"197", "Jesus Juice", "↑ +0.5 Damage up#↑ +0.25 Range up.#↑ +0.5 Tear Height"},
	{"198", "Box", "Spawns 1 pickup of each kind"},
	{"199", "Mom's Key", "+2 Keys#More drops from chests"},
	{"200", "Mom's Eyeshadow", "Chance to shoot charming tears"},
	{"201", "Iron Bar", "↑ +0.3 Damage up#Chance to shoot concussive tears"},
	{"202", "Midas' Touch", "Turn enemies into gold on touch#Deals contact damage based on your coin count#Golden enemies drop coins"},
	{"203", "Humbleing Bundle", "Doubles all pickups"},
	{"204", "Fanny Pack", "50% chance to drop a random pickup when you get hit"},
	{"205", "Sharp Plug", "-2 Hearts = Fully charges item when pressing space#!!! Only works when item has no charges!"},
	{"206", "Guillotine", "↑ +1 Damage up#↑ Tears up#Your Head is now an orbital#You will shoot from the head#The head deals 105 contact damage"},
	{"207", "Ball of Bandages", "LVL1: Orbital#LVL2: Shooting orbital#LVL3: Bandage girl#LVL4: Bandage girl LVL2"},
	{"208", "Champion Belt", "↑ +1 Damage up#!!! More champions appear"},
	{"209", "Butt Bombs", "↑ +5 Bombs#Explosions concuss and damage every enemy in the room"},
	{"210", "Gnawed Leaf", "Invincible when standing still for 1 second"},
	{"211", "Spiderbaby", "Spawn 1-2 spiders when getting hit"},
	{"212", "Guppy's Collar", "↑ 50% reviving chance"},
	{"213", "Lost Contact", "Shielded tears#Tears block enemy shots#↓ -0.16 Shot Speed down"},
	{"214", "Anemic", "↑ +5 Range up#Leave creep on floor when getting hit"},
	{"215", "Goat Head", "↑ 100% chance for Devil{{DevilRoom}} / Angel{{AngelRoom}} rooms"},
	{"216", "Ceremonial Robes", "↑ +1 Damage up#+3 Black hearts"},
	{"217", "Mom's Wig", "Random chance to spawn blue spider when shooting tears#Heals 1 red heart on pickup"},
	{"218", "Placenta", "↑ +1 Health up#Regenerate health slowly"},
	{"219", "Old Bandage", "↑ +1 Empty heart container#Random chance to drop red hearts when getting hit"},
	{"220", "Sad Bombs", "Tear explosion!#+5 Bombs"},
	{"221", "Rubber Cement", "Bouncing tears"},
	{"222", "Anti-Gravity", "↑ +2 Tears up#Anti-Gravity tears"},
	{"223", "Pyromaniac", "Explosions heal you#+5 Bombs"},
	{"224", "Cricket's Body", "↑ +1 Tears up#↓ -10 Range down#Tears split up in 4 on hit#Splitted tears deal half damage"},
	{"225", "Gimpy", "Chance to drop Soul/Black heart when getting hit#Chance to spawn a half red heart when killing an enemy"},
	{"226", "Black Lotus", "↑ +1 Health up#+1 Soul heart#+1 Black heart"},
	{"227", "Piggy Bank", "+3 Coins#Drop 1-2 coins when getting hit#Drops 0-1 for Keeper"},
	{"228", "Mom's Perfume", "Chance to shoot fearing tears#↑ +1 Tears up"},
	{"229", "Monstro's Lung", "Tears can now be charged and released in a shotgun style attack"},
	{"230", "Abaddon", "↑ +1.5 Damage up#↑ +0.2 Speed up#Fear tears#↓ Removes all red hearts#+6 Black hearts"},
	{"231", "Ball of Tar", "Chance to shoot slowing tears#Leave slowing creep"},
	{"232", "Stop Watch", "Permanent slow effect#(activated when getting hit)#↑ +0.3 Speed up"},
	{"233", "Tiny Planet", "Tears orbit around you#↑ +7.0 Tear Height#Spectral tears"},
	{"234", "Infestation 2", "Spawn spiders when you kill an enemy"},
	{"235", "", "<item does not exist>"},
	{"236", "E. Coli", "On touch, turn enemies into poop"},
	{"237", "Death's Touch", "Scythe tears!#↑ +1.5 Damage up#↓ -0.3 Tears down#Piercing tears"},
	{"238", "Key Piece 1", "!!! Key piece for Mega Satan door!#More Angel rooms{{AngelRoom}} appear"},
	{"239", "Key Piece 2", "!!! Key piece for Mega Satan door!#More Angel rooms{{AngelRoom}} appear"},
	{"240", "Experimental Treatment", "All Stats ↑/↓ a random number"},
	{"241", "Contract from Below", "Doubles all pickup drops#Doesn't affect Greed mode"},
	{"242", "Infamy", "50% chance to block tears"},
	{"243", "Trinity Shield", "Tear blocking shield"},
	{"244", "Tech.5", "Fire random laser-type tears"},
	{"245", "20/20", "Doubles all your shots"},
	{"246", "Blue Map", "Reveals secret rooms"},
	{"247", "BFFS!", "Your familiars deal double damage"},
	{"248", "Hive Mind", "Blue Spiders/flies deal double damage"},
	{"249", "There's Options", "2 Boss items spawn instead of 1#!!! Only one can be taken"},
	{"250", "BOGO Bombs", "Double all bomb-drops"},
	{"251", "Starter Deck", "You can carry 2 Cards#Turns all Pills into Cards"},
	{"252", "Little Baggy", "You can carry 2 Pills#Turns all Cards into Pills"},
	{"253", "Magic Scab", "↑ +1 Luck up#↑ +1 Health up"},
	{"254", "Blood Clot", "↑ +1 Damage up#↑ +5 Range up#!!! Applies only for the left eye"},
	{"255", "Screw", "↑ +0.5 Tears up#↑ +0.2 Shot Speed up"},
	{"256", "Hot Bombs", "Burning bombs#+5 Bombs"},
	{"257", "Fire Mind", "Chance for exploding tears#Tears light enemies on fire"},
	{"258", "Missing No.", "Rerolls all your items and stats on pickup and every time you change the floor"},
	{"259", "Dark Matter", "↑ +1 Damage up#Chance to shoot fearing tears"},
	{"260", "Black Candle", "Immunity to Curses#+1 Black heart#Higher Devil{{DevilRoom}} / Angel{{AngelRoom}} room chance"},
	{"261", "Proptosis", "↑ +100% Damage up#↓ Dealt damage decreases for traveled distance of the tear"},
	{"262", "Missing Page 2", "+1 black heart#When down to 1 Heart, damages all enemies in the room"},
	{"263", "", "<item does not exist>"},
	{"264", "Smart Fly", "Orbital#When you get hit it attacks enemies#Deals 22.5 damage per second"},
	{"265", "Dry Baby", "When its hit by enemy tears, it has a 10% chance to damage all enemies in the room"},
	{"266", "Juicy Sack", "Leaves slowing creep#Spawns 1-2 friendly spiders after clearing a room"},
	{"267", "Robo-Baby 2.0", "Shoots lasers#Deals 3.5 damage per shot#Moves in the direction you shoot"},
	{"268", "Rotten Baby", "Spawns blue flies when the player is shooting"},
	{"269", "Headless Baby", "Leaves creep which deals 6 damage per second"},
	{"270", "Leech", "Heals half a heart when it kills an enemy#3.2 damage per second"},
	{"271", "Mystery Sack", "Drops random pickups every few rooms"},
	{"272", "BBF", "Friendly exploding fly#The explosion deals 60 Damage"},
	{"273", "Bob's Brain", "Throwable bomb familiar#The explosion deals 60 Damage"},
	{"274", "Best Bud", "When getting hit, gain one midrange orbital#Orbital deals 75 damage per second"},
	{"275", "Lil Brimstone", "Shoots a brimstone laser#Shot deals 31.5 damage per second"},
	{"276", "Isaac's Heart", "Gain an invulnerable body#!!! When the heart familiar gets hit you take damage"},
	{"277", "Lil Haunt", "Friendly ghost familiar#Deals 4 damage per second"},
	{"278", "Dark Bum", "!!! Converts:#1,5 Red hearts into 1 soul heart or a spider"},
	{"279", "Big Fan", "Big fat orbital#Deals 30 damage per second"},
	{"280", "Sissy Longlegs", "Randomly spawns blue spiders when in a hostile room"},
	{"281", "Punching Bag", "Decoy familiar#Enemies will target him instead"},
	{"282", "How to Jump", "Allows you to jump"},
	{"283", "D100", "Reroll all pickups, pedestals and all your held passive items"},
	{"284", "D4", "Reroll all your held passive items"},
	{"285", "D10", "Reroll all enemies in the room"},
	{"286", "Blank Card", "Mimic effects of your held card"},
	{"287", "Book of Secrets", "Reveals parts of the map"},
	{"288", "Box of Spiders", "Spawn 1-4 blue spiders"},
	{"289", "Red Candle", "Throw red fire#The flame persists until it delt damage 5 times"},
	{"290", "The Jar", "Stores up to 4 Red heart pickups for later usage"},
	{"291", "Flush!", "!!! Insta kills Poop enemies & bosses!#Turns enemies into poop"},
	{"292", "Satanic Bible", "+1 Black heart"},
	{"293", "Head of Krampus", "Shoot brimstone lasers in all 4 directions"},
	{"294", "Butter Bean", "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger \"Wait What?\" when swapping it with a different active item and picking it up again"},
	{"295", "Magic Fingers", "Damages the whole room with 2x the player damage#Price: 1 coin"},
	{"296", "Converter", "!!! Convert:#2 Soul/Black hearts into 1 red heart"},
	{"297", "Pandora's Box", "!!! SINGLE USE !#!!! Drops things based on floor its activated on:#B1: 2 Soul Hearts#B2: 2 keys and bombs#C1: 1 Boss item#C2: B1+C1#D1: 4 Soul hearts#D2: 20 Coins#W1: 2 Boss items#W2: Bible#Sheol: 1 Devil item + Black heart#Cat: 1 Angel item + Soul heart#Chest: 1 Coin"},
	{"298", "Unicorn Stump", "Invincibility and +0.28 speed up for 6 seconds"},
	{"299", "Taurus", "Get faster in hostile rooms!#Invincibility when fast enough#↓ -0.3 Speed down"},
	{"300", "Aries", "↑ +0.25 Speed up#Touching enemies hurts them"},
	{"301", "Cancer", "+3 Soul hearts#Halves taken damage in room when you already got hit"},
	{"302", "Leo", "Destroy rocks when walking over them"},
	{"303", "Virgo", "Chance to get invincibility when hit#Converts negative pills into positive ones"},
	{"304", "Libra", "+6 Coins / Keys / Bombs#Balances your stats!#!!! Every stats up afterwards will affect other stats too"},
	{"305", "Scorpio", "Poison tears"},
	{"306", "Sagittarius", "↑ +0.2 Speed up#Piercing tears"},
	{"307", "Capricorn", "↑ +1 Health / Key / Bomb / Coin#↑ +0.5 Damage up#↑ +0.1 Speed up#↑ +1.5 Range up#Tears up"},
	{"308", "Aquarius", "Leave trail of creep#Creep deals 6 damage per second"},
	{"309", "Pisces", "↑ Tears up#Knockback tears"},
	{"310", "Eve's Mascara", "↑ +100% Damage#↓ Tears down#↓ -0.5 Shot speed down"},
	{"311", "Judas' Shadow", "When dead, respawn as Black Judas#↑ (Damage x 2)"},
	{"312", "Maggy's Bow", "↑ +1 Health up#Heals one heart#All red hearts now heal double their value"},
	{"313", "Holy Mantle", "Ignore the first hit in every room"},
	{"314", "Thunder Thighs", "↑ +1 Health up#↓ -0.4 Speed down#Destroy rocks when walking over them"},
	{"315", "Strange Attractor", "Magnetic tears#Affects enemies, pickups and trinkets"},
	{"316", "Cursed Eye", "Charged wave of tears#When charging and getting hit, teleports you to a random room"},
	{"317", "Mysterious Liquid", "Tears leave creep#Creep deals 30 damage per second"},
	{"318", "Gemini", "Close combat familiar#Deals 6 contact damage per second"},
	{"319", "Cain's Other Eye", "Bounces around the room#Shoots towards Isaac#His damage equals your damage"},
	{"320", "???'s Only Friend", "Controllable Fly#Deals 5 contact damage per second"},
	{"321", "Samson's Chains", "Draggable ball that can destroy rocks#Deals 10.7 contact damage per second"},
	{"322", "Mongo Baby", "Copies the effect of one of your familiars#Deals double its damage"},
	{"323", "Isaac's Tears", "Shoot 8 tears in all directions when used#Charges when shooting"},
	{"324", "Undefined", "Teleports you to:#{{SecretRoom}}{{SuperSecretRoom}}Secret-, Error- or {{TreasureRoom}}Item-rooms"},
	{"325", "Scissors", "Cut off your head#Head turns into stationary familiar#Control your body separately"},
	{"326", "Breath of Life", "Hold down space till chargebar is empty for invincibility#!!! Don't hold it for too long!"},
	{"327", "The Polaroid", "Invincibility when getting hit and at half a red heart or none"},
	{"328", "The Negative", "Damages all enemies in the room when getting hit and at half a red heart or none"},
	{"329", "The Ludovico Technique", "Controllable Tear"},
	{"330", "Soy Milk", "↑ Very high Tears up: (delay /4) - 2#↓ -80% Damage down"},
	{"331", "Godhead", "Homing tears#↑ +0.5 Damage up#↑ +1.2 Range up#↓ -0.3 Tears down#↓ -30% Shot Speed down#↑ +0.8 Tear Height#Tears gain a damaging aura"},
	{"332", "Lazarus' Rags", "When dead, revive as Lazarus (Risen)"},
	{"333", "The Mind", "Full mapping effect"},
	{"334", "The Body", "↑ +3 Health up"},
	{"335", "The Soul", "+2 Soul Hearts#Grants an aura that repels enemies and projectiles"},
	{"336", "Dead Onion", "Piercing + spectral tears#↑ +0.25 Range up#↓ -0.4 Shot Speed down#↑ +50% Tear size"},
	{"337", "Broken Watch", "Slows down or speeds up every 4th room"},
	{"338", "The Boomerang", "Throwable boomerang#Stuns enemies and deals 2x your damage on hit#Can grab items"},
	{"339", "Safety Pin", "↑ +5.25 Range up#↑ +0.16 Shot Speed up#+1 Black Heart#↑ +0.5 Tear Height"},
	{"340", "Caffeine Pill", "↑ +0.3 Speed up#↑ Player Size down#Gives you a random pill when picked up"},
	{"341", "Torn Photo", "↑ +0.7 Tears up#↑ +0.16 Shot Speed up"},
	{"342", "Blue Cap", "↑ +1 Health up#↑ +0.7 Tears up#↓ -16% Shot Speed down"},
	{"343", "Latch Key", "↑ +1 Luck up#+1 Soul Heart#Spawns 2 keys"},
	{"344", "Match Book", "+1 Black Heart#Spawns 2-3 Bomb pickups"},
	{"345", "Synthoil", "↑ +1.0 Damage up#↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"346", "A Snack", "↑ +1 Health up"},
	{"347", "Diplopia", "!!! SINGLE USE !#Duplicates any pedestals/ consumables in the current room"},
	{"348", "Placebo", "Copies the effect of the pill you are currently holding"},
	{"349", "Wooden Nickel", "50% chance to spawn a random coin"},
	{"350", "Toxic Shock", "At the start of every room every enemy gets a poison effect#Killed enemies leave puddle of creep"},
	{"351", "Mega Bean", "Freeze all enemies in the current room#Deals 5 damage and poison any enemies nearby#Sends wave of spikes across the room#!!! Can be used to open secret rooms"},
	{"352", "Glass Cannon", "↓ Reduces your health to half a heart#Fires one large piercing spectral tear ((DMG+1) X 10)"},
	{"353", "Bomber Boy", "+5 bombs#Bombs will now explode in a cross-shaped pattern"},
	{"354", "Crack Jacks", "↑ +1 Health up#Spawns random trinket on the floor"},
	{"355", "Mom's Pearls", "↑ +1.25 Range up#↑ +1 Luck up#↑ +0.5 Tear Height"},
	{"356", "Car Battery", "Causes your spacebar item to activate twice when used"},
	{"357", "Box of Friends", "Duplicate your familiars for the current room"},
	{"358", "The Wiz", "Fire 2 tears at once diagonally, similar to R U A WIZARD#Spectral tears"},
	{"359", "8 Inch Nails", "↑ +1.5 Damage up#Increases knockback"},
	{"360", "Incubus", "Shoots the same tears as Isaac in terms of damage, stats and effects"},
	{"361", "Fate's Reward", "Fires tears and copies your tear damage"},
	{"362", "Lil Chest", "Spawns a random pickup every few rooms"},
	{"363", "Sworn Protector", "Orbital familiar#Deals 105 contact damage per second#Blocks and attracts bullets#Blocking 10 tear in one room drops an eternal heart"},
	{"364", "Friend Zone", "Orbital familiar#Deals 45 contact damage per second"},
	{"365", "Lost Fly", "Moves along walls/obstacles in the room#Deals 105 contact damage per second"},
	{"366", "Scatter Bombs", "+5 bombs#Causes your bombs to explode into 2-4 tiny bombs"},
	{"367", "Sticky Bombs", "+5 bombs#When a bomb kills an enemy, it spawns blue spiders#Causes your bombs to stick to enemies"},
	{"368", "Epiphora", "Shooting in one direction increases your fire rate by up to 200%"},
	{"369", "Continuum", "↑ +2.25 Range up#↑ +1.5 Tear Height#Tears travel through walls and appear out of the opposite wall"},
	{"370", "Mr. Dolly", "↑ +0.7 Tears up#↑ +5.25 Range up#↑ +0.5 Tear Height#Spawns 3 random hearts when picked up"},
	{"371", "Curse of the Tower", "Spawn 6 troll bombs every time you get hit#These are affected by bomb items"},
	{"372", "Charged Baby", "Random chance to drop a battery or freeze all enemies in the room#Chance to add one charge to your spacebar item"},
	{"373", "Dead Eye", "↑ +12.5% damage up for every tear that successfully hits an enemy(max. +100%)"},
	{"374", "Holy Light", "Random chance to fire a Holy tear, which will spawn a beam of light on hit#The beam deals 4x your damage"},
	{"375", "Host Hat", "20% chance to block tears#Get immune to explosions/Stomps from Mom's and Satan's foot"},
	{"376", "Restock", "Spawns 3 random Pickups#Shops instantly restock their items when you buy them"},
	{"377", "Bursting Sack", "Spider enemies no longer target or deal contact damage to Isaac"},
	{"378", "No. 2", "Firing tears for 3 seconds drops a Butt Bomb"},
	{"379", "Pupula Duplex", "Tears get a much larger hitbox#Spectral tears"},
	{"380", "Pay To Play", "+5 coins#You can open doors with coins instead of keys"},
	{"381", "Eden's Blessing", "↑ +0.7 Tears up#Gives you a random item at the start of your next run"},
	{"382", "Friendly Ball", "Can be thrown at enemies to capture them#Next usage will re-spawn the same enemy as a friendly companion"},
	{"383", "Tear Detonator", "Detonate any tears currently on the screen, causing each one to split into 6 more tears which will spread in a circle"},
	{"384", "Lil Gurdy", "Will launch and slide around the room#Deals 90 contact damage per second"},
	{"385", "Bumbo", "Picks up any near-by coins#Every 6 coins it levels up, except for level 4 which takes 12 coins#Level 2: can drop random pickups#Level 3: Fires tears in the same direction as Isaac#Level 4: Doesn't fire tears but will chase enemies. Will also randomly drop bombs#after Level 4: will continue collect coins and drop random pickups"},
	{"386", "D12", "Re-rolls any grid object into another random type of object (e.g. poop, pots, TNT, red poop, stone blocks etc.)"},
	{"387", "Censer", "Creates a huge aura of light that slows down enemies and projectiles inside of it"},
	{"388", "Key Bum", "Collects keys, giving random chests in return"},
	{"389", "Rune Bag", "Drops a random rune every 5-6 rooms"},
	{"390", "Seraphim", "Fires Sacred Heart tears#Deals 10 damage per shot"},
	{"391", "Betrayal", "Every time Isaac takes damage, every enemy in the room gets charmed"},
	{"392", "Zodiac", "Gives you a random zodiac item effect every floor"},
	{"393", "Serpent's Kiss", "Random chance to shoot poison tears#Poison enemies on contact#Enemies that were poisoned have a chance to drop a black heart on death"},
	{"394", "Marked", "Fire tears automatically directed at a red target on the ground which is controlled by the player#↑ +0.7 Tears up#↑ +3.15 Range up#↑ +0.3 Tear Height"},
	{"395", "Tech X", "Gain the ability to charge and fire a laser ring that travels across the room"},
	{"396", "Ventricle Razor", "Creates up to two portals to travel between them#Can be placed in different rooms"},
	{"397", "Tractor Beam", "Isaac's tears now travel directly forwards following a beam of light, but will also move sideways based on your player movement#↑ +0.5 Tears up#↑ +5.25 Range up#↑ +0.16 Shot Speed up#↑ +0.5 Tear Height"},
	{"398", "God's Flesh", "Tears can shrink enemies#Shrunk enemies can be crushed and killed by walking over them"},
	{"399", "Maw Of The Void", "↑ +1.0 Damage up#After firing tears for 3 seconds, a red cross appears on Isaac's head. Upon releasing the fire button, creates a black brimstone ring#Enemies killed with the black ring have a chance to drop Black hearts"},
	{"400", "Spear Of Destiny", "Spawns a spear in front of you#Deals 2 times your damage#Chance to fear enemies on contact"},
	{"401", "Explosivo", "Chance to fire sticky bomb tears"},
	{"402", "Chaos", "Pedestals will now be chosen from random itempools#Spawns 1-6 random pickups"},
	{"403", "Spider Mod", "Allows you to see your tear damage and the health bars of all enemies#Inflicts a random status effect on contact#Will randomly drop batteries"},
	{"404", "Farting Baby", "Blocks projectiles#If hit, it will fart, which will charms, poison or knockback enemies"},
	{"405", "GB Bug", "Bounces around the room#Deals 120 damage per second and applies a random status effect"},
	{"406", "D8", "Reroll your stats#Will only affect damage, tears, range and speed"},
	{"407", "Purity", "↑ Boost one of your stats depending on the color of the aura around you#When you take damage, you will get a new aura#{{ColorRed}}Red{{CR}} = +4.0 Damage#{{ColorBlue}}Blue{{CR}} = -4 Tear Delay#{{ColorYellow}}Yellow{{CR}} = +0.5 Speed up#{{ColorOrange}}Orange{{CR}} = +7.5 Range up, +1 Tear height"},
	{"408", "Athame", "When you take damage, a black brimstone ring will appear around Isaac#Enemies killed with it have a chance to drop a black heart"},
	{"409", "Empty Vessel", "+2 Black Hearts#When Isaac has no red hearts, gain flight and chance to trigger a shield"},
	{"410", "Evil Eye", "Chance to fire an eye across the screen which fires tears in the same direction as Isaac"},
	{"411", "Lusty Blood", "↑ +0.5 Damage up for each enemy killed in current room#Maximum of +5 Damage up after 10 kills"},
	{"412", "Cambion Conception", "After taking damage 15 times, Isaac gains a permanent demon familiar#Up to 4 familiars possible"},
	{"413", "Immaculate Conception", "After picking up 15 hearts, Isaac gains a permanent angelic familiar#Up to 5 familiars possible"},
	{"414", "More Options", "Two items now spawn in all treasure rooms#You can only choose one"},
	{"415", "Crown Of Light", "+2 Soul Hearts#↑ Damage X 2 if you don't have any damaged red heart containers#Deactivates for the current room when damaged regardless of heart containers"},
	{"416", "Deep Pockets", "Allows you to carry two cards/pills/runes"},
	{"417", "Succubus", "Bounces around the room with a damaging aura, dealing 129% of your damage every second#↑ +50% damage while standing in the aura,"},
	{"418", "Fruit Cake", "Gives you a different tear effect with every tear that you fire"},
	{"419", "Teleport 2.0", "Teleports you to another random room that has not been explored yet#Hierarchy: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> Error-Room"},
	{"420", "Black Powder", "Walking in a circle will spawn a pentagram symbol on the floor, which deals 10 damage per tick"},
	{"421", "Kidney Bean", "Applies charm effect to any enemies in close range and deals 5 damage to them"},
	{"422", "Glowing Hour Glass", "Rewind time and put you back in the previous room, in the same state you were in at that moment"},
	{"423", "Circle of Protection", "Large halo around you, dealing your damage on contact every second#Chance to reflect enemy projectiles"},
	{"424", "Sack Head", "Pickups have a 33% chance to be replaced with a sack#Spawns a sack"},
	{"425", "Night Light", "Spawns a cone of light in front of you that slows enemies and projectiles inside of it"},
	{"426", "Obsessed Fan", "Follows your exact movement on a 3 second delay#Deals 30 contact damage per second"},
	{"427", "Mine Crafter", "Spawns a pushable TNT barrel#If used a second time in the same room while the last TNT barrel is still there, it will remotely explode"},
	{"428", "PJs", "+4 Soul Hearts#Fully restores your red health"},
	{"429", "Head of the Keeper", "Enemies have a 5% chance to drop a Penny when hit with your tears"},
	{"430", "Papa Fly", "Follows your movement pattern on a 1 second delay#Fires tears at nearby enemies that deal damage equal to your damage"},
	{"431", "Multidimensional Baby", "Follows your movement pattern on a 2 second delay#Tears that pass through it will split up and gain a speed boost"},
	{"432", "Glitter Bombs", "+5 bombs#Bombs have a chance to drop random pickups when they explode"},
	{"433", "My Shadow", "Each time you take damage, it will apply a fear effect to all enemies and spawn a friendly black charger#The charger deals 5 damage per second"},
	{"434", "Jar of Flies", "Every time you kill an enemy a blue fly will be added to the Jar#Up to 20 flies#Using the item will release all the flies"},
	{"435", "Lil Loki", "Shoots 4 tears in a cross pattern#Deals 3.5 damage per shot"},
	{"436", "Milk!", "After taking damage, you gain a Tears up for the rest of the room"},
	{"437", "D7", "Respawn all enemies of the room#Allows you to farm room clear rewards#!!! If used in a greed fight, it can reroll the room into a Shop"},
	{"438", "Binky", "+1 Soul heart#↑ +0.7 Tears up#↑ Makes Isaac very small, reducing his hitbox size"},
	{"439", "Mom's Box", "Spawns a random trinket#↑ +1 Luck while held#While held, doubles the effect of trinkets"},
	{"440", "Kidney Stone", "Randomly while firing you will stop firing and release a burst of tears and a kidney stone#↓ -0.2 Speed down#↓ -17 Range down#↑ +2.0 Tear height"},
	{"441", "Mega Blast", "Fires a huge Mega Satan laser for 15 seconds#The laser persists between rooms and floors"},
	{"442", "Dark Princes Crown", "!!! While at 1 full red heart:#↑ +1.5 Range up#↑ +0.75 Tears up#↑ +0.2 Shot Speed up#(Doesnt work with characters without red HP)"},
	{"443", "Apple!", "Randomly fire razor blades which deal 400% damage#↑ +0.3 Tears up"},
	{"444", "Lead Pencil", "Every 15 tears fired, you fire a cluster of tears#Each tear in the cluster deals double damage"},
	{"445", "Dog Tooth", "↑ +0.3 Damage up#↑ +0.1 Speed up#A wolf howls, if you enter a room next to a secret room#A barking sound will play when entering a room with a crawl space in it"},
	{"446", "Dead Tooth", "While firing, you get a green aura that poisons any enemies in it#The poison deals your damage"},
	{"447", "Linger Bean", "While firing without pause, spawns a poop cloud every 7.5 seconds#The cloud deals 3.5 damage 5 times a second#Cloud lasts 15 seconds#Can be moved by shooting it"},
	{"448", "Shard of Glass", "When taking damage, chance to get ↑ +5 Range and leave a trail of blood creep, or spawn a red heart"},
	{"449", "Metal Plate", "+1 Soul Heart#Enemy bullets have a 25% chance to be reflected as concussive tears"},
	{"450", "Eye of Greed", "Every 20 tears, shoot a coin tear that turns enemies into gold#This costs 1 coin#Hit enemies drop a coin"},
	{"451", "Tarot Cloth", "Drops a random card or rune on pickup#Doubles the effect of any card used"},
	{"452", "Varicose Veins", "When taking damage, fire 10 tears in a circle around you#The tears deal 125% your damage"},
	{"453", "Compound Fracture", "Bone tears#Tears shatter into 1-3 smaller bone shards upon hitting anything#↑ +1.5 Range up#↑ +1.0 Tear height"},
	{"454", "Polydactyly", "You can carry two cards, runes or pills#Spawns a random card, pill or rune on pickup"},
	{"455", "Dad's Lost Coin", "↑ +1.5 Range up#Spawns a lucky penny"},
	{"456", "Moldy Bread", "↑ +1 Health up"},
	{"457", "Cone Head", "+1 Soul Heart#20% Chance to ignore damage"},
	{"458", "Belly Button", "Spawns a random trinket on pickup#Grants 1 extra trinket slot"},
	{"459", "Sinus Infection", "Sticky poison Tears#Deals your damage each tick#Sticks till the enemy dies"},
	{"460", "Glaucoma", "Chance to fire concussive tears"},
	{"461", "Parasitoid", "Chance to fire egg sacks#Spawns slowing creep on hit#Spawns a blue spider or fly on hit"},
	{"462", "Eye of Belial", "↑ +1.5 Range up#↑ +1.0 Tear height#Grants piercing tears#After hitting the first enemy, the tear deals double damage and gains a homing effect"},
	{"463", "Sulfuric Acid", "↑ +0.3 Damage up#Chance to destroy rocks and open doors with your tears"},
	{"464", "Glyph of Balance", "+2 Soul Hearts#Champion enemies drop pickups more frequently"},
	{"465", "Analog Stick", "↑ +0.3 Tears up#Allows you to fire tears diagonally by firing in two directions"},
	{"466", "Contagion", "First killed enemy in the room will explode and poison all nearby enemies"},
	{"467", "Finger!", "Deals constant 10% of your damage to enemies in the direction the finger points at"},
	{"468", "Shade", "Follows your movement delayed by 1 seconds#Deals 30 contact damage per second"},
	{"469", "Depression", "Leaves trail of creep#Creep deals 6 damage per second#Enemies touching the cloud can spawn a holy light beam"},
	{"470", "Hushy", "Bounces around the room#Deals contact damage#Will stop moving when you are shooting#When stopped, it can block projectiles"},
	{"471", "Lil Monstro", "Chargable Shotgun attack#(Similar to monstros lung)#Each tear deals 3.5 damage"},
	{"472", "King Baby", "Other familiars follow it#Stops moving when you are shooting#Will teleport back to you when you stop shooting"},
	{"473", "Big Chubby", "Charges forwards very slow#Deals 40.5 contact damage per second"},
	{"474", "Tonsil", "Blocks enemy projectiles"},
	{"475", "Plan C", "!!! SINGLE USE ! #Deals 9,999,999 damage to all enemies and kills you 3 seconds later"},
	{"476", "D1", "Duplicates 1 random Pick-Up in the current room"},
	{"477", "Void", "!!! When used, consume any pedestal items in the room#Active item: Its effect will be added to Void's effect (Stacking the effects)#↑ Passive item: Small stat upgrade to a random stat"},
	{"478", "Pause", "Freezes all enemies in the room until you start shooting again#Touching a frozen enemy will hurt you#Enemies unfreeze after 30 seconds"},
	{"479", "Smelter", "Consumes your trinket and gives you the effect permanently#More trinkets appear"},
	{"480", "Compost", "Converts pickups into blue flies or spiders#Doubles your current blue flies/spiders#Spawns 1 blue fly or spider when you dont have any"},
	{"481", "Dataminer", "When used, ↑/↓ small amount on random stat#Random tear effect for current room#Fucks up all sprites"},
	{"482", "Clicker", "Transforms you into a different character#Removes the last item you collected"},
	{"483", "Mama Mega!", "!!! SINGLE USE ! #Affects whole floor#Explodes all objects#Deals 200 damage to all enemies#Opens boss rush / hush door / secret rooms"},
	{"484", "Wait What?", "Upon use, pushes enemies away and spawn a wave of rocks#Can open rooms and break rocks"},
	{"485", "Crooked Penny", "50% chance to double all items, consumables and chests in room#50% chance to remove items / pickups in room and spawn 1 coin"},
	{"486", "Dull Razor", "Hurts you without damaging you#Can trigger item effects"},
	{"487", "Potato Peeler", "Removes one red heart container and gives you ↑ +0.2 Damage up and a \"Cube of Meat\""},
	{"488", "Metronome", "Gives you a random item effect each room"},
	{"489", "D infinity", "Random Dice-effect each usage"},
	{"490", "Eden's Soul", "!!! SINGLE USE !#Spawns 2 random items depending on the current rooms item pool"},
	{"491", "Acid Baby", "Drops a random pill every 3 rooms#Using a pill poisons all enemies in the room"},
	{"492", "YO LISTEN!", "↑ +1 Luck up#Highlights the location of secret rooms, tinted rocks and trapdoors"},
	{"493", "Adrenaline", "For every empty heart container:#↑ +0.2 Damage up"},
	{"494", "Jacob's Ladder", "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half your damage"},
	{"495", "Ghost Pepper", "Chance to shoot Fire instead of tears#The fire stays till it has dealt damage 5 times"},
	{"496", "Euthanasia", "Chance to fire needles#Needles kill normal enemies instantly#Otherwise they deal 3 times your damage"},
	{"497", "Camo Undies", "Confuse all enemies and camouflage yourself when entering a room until you start shooting"},
	{"498", "Duality", "Spawns Devil-{{DevilRoom}} AND Angel{{AngelRoom}}-Room doors#When entering one, the other disappears"},
	{"499", "Eucharist", "100% chance to find an Angel{{AngelRoom}} Room"},
	{"500", "Sack of Sacks", "Spawns a sack every 5-6 rooms"},
	{"501", "Greed's Gullet", "Gives you 1 heart container for every 25 coins#The Keeper will gain additional Coin-Hearts"},
	{"502", "Large Zit", "Chance to fire a Creep leaving tear that deals double damage"},
	{"503", "Little Horn", "Chance to fire tears that instantly kill enemies#Running into enemies will deal 3.5 damage to them"},
	{"504", "Brown Nugget", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
	{"505", "Poke Go", "Chance to spawn a charmed enemy when entering a hostile room"},
	{"506", "BackStabber", "Tears can cause bleeding, which deals 10% damage of the enemies total health every 5 seconds"},
	{"507", "Sharp Straw", "Deals your damage + 10% damage equal to the maximum health of the enemy#Affects all enemies in the room#Chance to drop half hearts when it deals damage"},
	{"508", "Mom's Razor", "Orbital that causes bleeding, which deals 10% damage of the enemies total health every 5 seconds.#Deals 300% your damage on contact per second"},
	{"509", "Bloodshot Eye", "Orbital that shoots a tear every 2 seconds in a random direction#Deals 3.5 damage per tear#Deals 30 contact damage per second"},
	{"510", "Delirious", "Spawns a friendly white delirium version of a boss for the current room"},
	{"511", "Angry Fly", "Orbits around a random enemy until that enemy dies#Deals 30 contact damage per second to other enemies"},
	{"512", "Black Hole", "Throwable black hole, which sucks in everything#Deals 0.4 damage every tick#Destroys nearby rocks#Lasts 6 seconds"},
	{"513", "Bozo", "↑ +0.1 Damage up#+1 Soul Heart#Random chance to charm/fear an enemy#Random chance to spawn a rainbow poop upon taking damage"},
	{"514", "Broken Modem", "Causes random enemies to 'lag' at random intervals, causing them to shortly freeze#25% chance to double room clear drops"},
	{"515", "Mystery Gift", "!!! SINGLE USE !#Spawns a random item from the current room's item pool#Chance to spawn Lump of Coal or The Poop instead"},
	{"516", "Sprinkler", "Spawns a Sprinkler that rotates in a circle, spraying your tears in all directions"},
	{"517", "Fast Bombs", "+7 Bombs#Allows you to rapidly place bombs on the ground"},
	{"518", "Buddy in a Box", "Familiar which looks like a random coop Baby#Has a random tear effect#Will be randomized every floor"},
	{"519", "Lil Delirium", "A familiar that transforms into other random familiars every 10 seconds"},
	{"520", "Jumper Cables", "+1 charge for your active item for every 15 enemies killed"},
	{"521", "Coupon", "When used, causes one random item in the Shop{{Shop}}- or Devil{{DevilRoom}}- room to become free"},
	{"522", "Telekinesis", "Enemy projectiles close to you are held in place for 3 seconds#They get thrown away from you afterwards#Recharges after 3 seconds"},
	{"523", "Moving Box", "When used, stores all Pick-Ups from the current room#Using it again will put them back on the floor again#This allows you to move things between rooms"},
	{"524", "Technology Zero", "Tears will be connected with beams of electricity#Electricity damage equals your damage"},
	{"525", "Leprosy", "Taking damage will spawn a projectile blocking orbital#Max. 3 Orbitals at the same time#Orbitals are destroyed, if they take too much damage"},
	{"526", "7 Seals", "Spawns small horsemen familiars that spawn their respective locusts#Horsemen changes every 10 seconds"},
	{"527", "Mr. ME!", "!!! Familiar that can do tasks for you:#Opening doors & chests, Bring items, Steal from the shop / devil, fight enemies, explode, and activate pressure plates"},
	{"528", "Angelic Prism", "Orbital prism#Tears hitting it will split into 4"},
	{"529", "Pop!", "Tears will behave like billiard balls"},
	{"530", "Death's List", "Grants a reward if you kill enemies in the order they are marked in"},
	{"531", "Haemolacria", "Tears fly in an arc#Tears burst into smaller tears on impact#↓ Tears down#↑ 31% Damage up"},
	{"532", "Lachryphagy", "Tears slow down while traveling#Upon stopping, they explode in 8 smaller tears#Tears can be fired in other tears, making them bigger"},
	{"533", "Trisagion", "Fire white blasts of light#(Holy Brimstone)"},
	{"534", "Schoolbag", "Allows holding 2 active items#Switch between them by pressing the Drop button (hold button as \"The Forgotten\")"},
	{"535", "Blanket", "+1 Soul Heart#Heals 1 Red Heart#Grants a shield when entering a boss room"},
	{"536", "Sacrificial Altar", "!!! ONE TIME USAGE !#Sacrifice 1-2 familiars to spawn an item from the Devil{{DevilRoom}} room itempool#Turns your blue spiders/flies into coins"},
	{"537", "Lil Spewer", "Spawns a random pill#Familiar that fires a line of creep#Creeptype changes everytime the player uses a pill"},
	{"538", "Marbles", "Spawns 3 random trinkets#Taking damage can add the effect of your trinket permanently"},
	{"539", "Mystery Egg", "Spawn a charmed enemy when you get hit#Spawns stronger friends the more rooms are cleared without taking damage"},
	{"540", "Flat Stone", "Tears bounce off the floor#Tears cause splash damage on every bounce"},
	{"541", "Marrow", "+1 Bone Heart#Spawns 3 Red Hearts"},
	{"542", "Slipped Rib", "Orbital#Reflects projectiles"},
	{"543", "Hallowed Ground", "Spawn white poop when you get hit#(White poop has a ↑ Tears up aura and can block damage)"},
	{"544", "Pointy Rib", "Nail that levitates in front of isaac#Deals your damage 6 times per second"},
	{"545", "Book of the Dead", "Spawns a bone orbital or charmed bony per enemy killed in the current room"},
	{"546", "Dad's Ring", "Grants an aura that freezes enemies in place"},
	{"547", "Divorce Papers", "+1 Bone Heart#↑ +0.7 Tears up#Spawns a Mysterious Paper trinket"},
	{"548", "Jaw Bone", "Boomerang-like Familiar#Deals 7 contact damage#Can retrieve pickups"},
	{"549", "Brittle Bones", "Replaces all your red heart containers with 6 bone Hearts#Losing a bone heart fires Bonetears in all directions and adds ↑ +0.5 tears up permanently"},
	{"550", "Broken Shovel", "Moms foot will constantly attack you#Using it stops moms foot for current room#!!! (Try to beat Bossrush with it!)"},
	{"551", "Broken Shovel", "Second part of a broken shovel#!!! Use the shovel on the hill of dirt in the \"Dark Room\""},
	{"552", "Mom's Shovel", "Spawns trapdoor to next floor#!!! Use the shovel on the hill of dirt in the \"Dark Room\"#!!! Unlocks something cool"},
}

---------- Trinkets ----------
EID.descriptions["en_us"].trinkets={
	{"1", "Swallowed Penny", "Drop 1 coin when you get hit"},
	{"2", "Petrified Poop", "50% more drops from poop"},
	{"3", "AAA Battery", "-1 charge needed for spacebar items"},
	{"4", "Broken Remote", "Randomly teleports you, when using an item"},
	{"5", "Purple Heart", "More champion enemies#Higher chance for boss challenge rooms ({{BossRushRoom}})"},
	{"6", "Broken Magnet", "Coin magnet"},
	{"7", "Rosary Bead", "Higher angel{{AngelRoom}} room chances#Higher chance to find the Bible {{Collectible33}}"},
	{"8", "Cartridge", "Chance for Gamekid effect on hit"},
	{"9", "Pulse Worm", "Pulsating tears#Affects tear hitbox"},
	{"10", "Wiggle Worm", "Tears move in waves#↑ +0.3 Tears up"},
	{"11", "Ring Worm", "Tears move in spirals with high speed"},
	{"12", "Flat Worm", "50% wider tears"},
	{"13", "Store Credit", "One shop item for free"},
	{"14", "Callus", "Prevents damage from creep and spikes"},
	{"15", "Lucky Rock", "Destroying rocks spawns coins"},
	{"16", "Mom's Toenail", "Mom's foot stomps enemies every 60 seconds"},
	{"17", "Black Lipstick", "More black hearts appear"},
	{"18", "Bible Tract", "More eternal hearts appear"},
	{"19", "Paper Clip", "Unlock chests without using keys"},
	{"20", "Monkey Paw", "When on half a heart, spawns a black heart#!!! 3 time usage"},
	{"21", "Mysterious Paper", "Imitates \"Polaroid\", \"The Negative\", \"Missing Page\" and \"Missing Poster\""},
	{"22", "Daemon's Tail", "Decreases spawnrate of hearts to 20%#Key drop chance increased#Heart-Pickups turn into black hearts"},
	{"23", "Missing Poster", "Respawn as \"The Lost\" when dying in a sacrifice room {{SacrificeRoom}} #If he is unlocked, you revive as him even outside sacrifice rooms"},
	{"24", "Butt Penny", "Fart when picking up coins#Farts knockback enemies"},
	{"25", "Mysterious Candy", "Fart or spawn poop every 30 seconds"},
	{"26", "Hook Worm", "Tears move in angular patterns#↑ +10 Range"},
	{"27", "Whip Worm", "↑ +0.5 Shot Speed up"},
	{"28", "Broken Ankh", "22% chance to respawn as \"Blue Baby\""},
	{"29", "Fish Head", "Spawn a blue fly when getting hit"},
	{"30", "Pinky Eye", "10% chance to shoot poison tears"},
	{"31", "Push Pin", "10% chance to shoot piercing spectral tears"},
	{"32", "Liberty Cap", "Random mushroom effect per room#Can reveal special rooms on the minimap"},
	{"33", "Umbilical Cord", "When down to half a heart, you get little Steven"},
	{"34", "Child's Heart", "More red hearts drop"},
	{"35", "Curved Horn", "↑ +2 Damage up"},
	{"36", "Rusted Key", "More keys appear"},
	{"37", "Goat Hoof", "↑ +0.15 Speed up"},
	{"38", "Mom's Pearl", "More Soul Hearts drop"},
	{"39", "Cancer", "↑ Tears up"},
	{"40", "Red Patch", "↑ Chance to get +1.8 Damage up when getting hit"},
	{"41", "Match Stick", "More Bombs appear#!!! Removes \"The Tick\""},
	{"42", "Lucky Toe", "↑ +1 Luck up#Chance to get more drops"},
	{"43", "Cursed Skull", "When damaged down to half a heart or less, teleport to a random room"},
	{"44", "Safety Cap", "More pills appear"},
	{"45", "Ace of Spades", "More cards appear"},
	{"46", "Isaac's Fork", "Chance for healing half a heart after clearing a room"},
	{"47", "", "<Item does not exist>"},
	{"48", "A Missing Page", "When getting hit, chance to damage all enemies in the room"},
	{"49", "Bloody Penny", "50% chance to drop half a heart when picking up coins"},
	{"50", "Burnt Penny", "50% chance to drop a bomb when picking up coins"},
	{"51", "Flat Penny", "50% chance to drop a key when picking up coins"},
	{"52", "Counterfeit Penny", "50% chance to get +1 coin when picking up coins"},
	{"53", "Tick", "-15% boss-health#Heals 1 red heart when entering a boss room ({{BossRoom}})#!!! Once picked up, it can't be removed#Only removeable with {{Trinket41}}Match Stick or gulping"},
	{"54", "Isaac's Head", "Familiar with piercing tears#Deals 3.5 damage per tear"},
	{"55", "Maggy's Faith", "Get one eternal heart at the start of every floor"},
	{"56", "Judas' Tongue", "Reduces devil deal prices from 2 heart containers into 1"},
	{"57", "???'s Soul", "Familiar that bounces around the room#Shoots in the same direction as the player#Deals 3.5 damage per tear"},
	{"58", "Samson's Lock", "↑ 1/15 Chance for +0.5 Damage up when killing an enemy#Effect lasts for current room"},
	{"59", "Cain's Eye", "25% chance to reveal map icons at start of new floor"},
	{"60", "Eve's Bird Foot", "Chance to spawn a dead bird when killing an enemy"},
	{"61", "The Left Hand", "Turns all chests into red chests"},
	{"62", "Shiny Rock", "Crawlspace rocks and tinted rocks blink every 10 seconds"},
	{"63", "Safety Scissors", "Turns troll bombs into bomb pickups"},
	{"64", "Rainbow Worm", "Random worm effect every 3 seconds"},
	{"65", "Tape Worm", "↑ Doubles your Range#-50% Tear height"},
	{"66", "Lazy Worm", "↓ -0.4 Shot Speed down#↑ +4 Range up"},
	{"67", "Cracked Dice", "Chance to trigger a random dice effect when getting hit"},
	{"68", "Super Magnet", "Magnet for pickups and enemies"},
	{"69", "Faded Polaroid", "Camouflages the player randomly#Confuses enemies"},
	{"70", "Louse", "Chance to spawn a spider while in a hostile room"},
	{"71", "Bob's Bladder", "Bombs leave creep"},
	{"72", "Watch Battery", "More batteries appear#5% chance to add 1 charge to held active item when clearing a room"},
	{"73", "Blasting Cap", "Exploding bombs can drop bomb-pickups"},
	{"74", "Stud Finder", "Higher chance to reveal Crawlspaces when breaking rocks"},
	{"75", "Error", "Random trinket effect every room"},
	{"76", "Poker Chip", "Chests have a 50/50 chance to spawn extra pickups OR nothing/enemy"},
	{"77", "Blister", "Increases knockback"},
	{"78", "Second Hand", "Longer status effects on enemies"},
	{"79", "Endless Nameless", "25% chance when using pills/cards to drop a copy of the pill/card"},
	{"80", "Black Feather", "↑ +0.2 Damage up for each evil item held"},
	{"81", "Blind Rage", "Invincibility lasts longer after getting hit"},
	{"82", "Golden Horse Shoe", "+15% to get double item room on next floor"},
	{"83", "Store Key", "Open shops {{Shop}} for free"},
	{"84", "Rib of Greed", "Greed/Super Greed no longer appear in shops#More coins appear"},
	{"85", "Karma", "Using a Donation machine can heal you or spawn a beggar"},
	{"86", "Lil Larva", "Destroying poop spawns a blue fly"},
	{"87", "Mom's Locket", "Heal half a heart when using keys#Turns half hearts into full hearts"},
	{"88", "NO!", "Very low chance for spacebar items in item rooms"},
	{"89", "Child Leash", "Familiars stay closer to you"},
	{"90", "Brown Cap", "Poop explodes when destroyed"},
	{"91", "Meconium", "Increases chance for Black Poops to spawn#Chance to spawn a black heart when black poop is destroyed"},
	{"92", "Cracked Crown", "↑ Stat increases of your items are 33% more effective#↑ +0.2 Tears up#↑ -1 Tear Delay"},
	{"93", "Used Diaper", "Chance for Fly enemies to become friendly"},
	{"94", "Fish Tail", "Doubles all blue Fly / Spider spawns"},
	{"95", "Black Tooth", "Randomly shoot poison Tooth tears"},
	{"96", "Ouroboros Worm", "Tears move quickly in a spiral pattern#Spectral tears#↑ +4 Range"},
	{"97", "Tonsil", "Chance to get a projectile blocking familiar after taking damage 12-20 times#Up to +2 Familiars possible"},
	{"98", "Nose Goblin", "Chance to shoot sticky poison tears"},
	{"99", "Super Ball", "Chance to shoot bouncy tears"},
	{"100", "Vibrant Bulb", "!!! While holding a fully charged active item:#↑ +0.5 Damage#↑ +0.25 Speed#↑ +0.75 Range#↑ +0.2 Tears#↑ +0.1 Shot speed#↑ +1 Luck"},
	{"101", "Dim Bulb", "!!! While holding an uncharged active item:#↑ +1.5 Damage#↑ +0.5 Speed#↑ +1.5 Range#↑ +0.4 Tears#↑ +0.3 Shot Speed#↑ +2 Luck"},
	{"102", "Fragmented Card", "+1 extra secret room per floor while held"},
	{"103", "Equality!", "!!! When coin, key and bomb-count are equal:#Turns half consumables into double consumables"},
	{"104", "Wish Bone", "Chance to spawn a pedestal item when getting hit#Gets destroyed afterwards"},
	{"105", "Bag Lunch", "Chance to spawn Lunch {{Collectible22}} when getting hit#Gets destroyed afterwards"},
	{"106", "Lost Cork", "Increases the radius of any creep you produce"},
	{"107", "Crow Heart", "Damage taken will ignore soul / black hearts, causing your red heart containers to be depleted first"},
	{"108", "Walnut", "Chance to drop random pickup / trinket when getting hit by an explosion#Gets destroyed afterwards"},
	{"109", "Duct Tape", "Causes any familiar you have to stop moving"},
	{"110", "Silver Dollar", "Shops {{Shop}} will now appear in the womb"},
	{"111", "Bloody Crown", "Item rooms {{TreasureRoom}} now appear in the womb"},
	{"112", "Pay To Win", "Restock boxes will always spawn in item rooms ({{TreasureRoom}})"},
	{"113", "Locust of War", "Spawn an exploding attack fly when entering a hostile room#The fly deals double your damage + explosion damage"},
	{"114", "Locust of Pestilence", "Spawn a poison attack fly when entering a hostile room#The fly deals double your damage"},
	{"115", "Locust of Famine", "Spawn a slowing attack fly when entering a hostile room#The fly deals double your damage"},
	{"116", "Locust of Death", "Spawn an attack fly when entering a hostile room#The fly deals 4 times your damage"},
	{"117", "Locust of Conquest", "Spawns 1-4 attack flies when entering a hostile room#Each fly deals double your damage"},
	{"118", "Bat Wing", "Chance to gain flight after killing an enemy#Persists for the current room"},
	{"119", "Stem Cell", "Heals half a heart upon traveling to the next floor"},
	{"120", "Hairpin", "Fully recharges your active item at the start of a boss fight"},
	{"121", "Wooden Cross", "Protects you from the first damage you take for every floor"},
	{"122", "Butter!", "Using your active item will drop it back on a pedestal on the ground#When taking damage, 2% chance to drop one of your passive items"},
	{"123", "Filigree Feather", "Causes the Angel bosses to drop normal items instead of Key Pieces"},
	{"124", "Door Stop", "The last door you used stays open"},
	{"125", "Extension Cord", "Connects your familiars with beams of electricity#Deals 6 damage per beam"},
	{"126", "Rotten Penny", "Spawns a blue fly when picking up a coin"},
	{"127", "Baby-Bender", "Grants your familiars homing shots"},
	{"128", "Finger Bone", "2% chance to gain a Bone Heart when taking damage"},
}

---------- Cards ----------
EID.descriptions["en_us"].cards={
	{"1", "0 - The Fool", "Teleports you back to the start"},
	{"2", "I - The Magician", "Homing tears for current room"},
	{"3", "II - The High Priestess", "Moms Foot stomps on an enemy!"},
	{"4", "III - The Empress", "↑ +2.35 Damage & +0.3 Speed for current room"},
	{"5", "IV - The Emperor", "Teleports you to the bossroom ({{BossRoom}})"},
	{"6", "V - The Hierophant", "Drops 2 Soul hearts"},
	{"7", "VI - The Lovers", "Drops 2 red hearts"},
	{"8", "VII - The Chariot", "Invincibility + contact damage for 6 seconds"},
	{"9", "VIII - Justice", "Spawns 1 bomb, 1 key, 1 coin, 1 heart"},
	{"10", "IX - The Hermit", "Teleports you to the shop {{Shop}}"},
	{"11", "X - Wheel of Fortune", "Spawns a Slot- or Fortune Machine"},
	{"12", "XI - Strength", "↑ +1 Health up#↑ +0.3 Damage up#↑ +50% Damage#↑ +5.25 Range up#↑ +0.3 Speed up#For current room"},
	{"13", "XII - The Hanged Man", "Grants flight for current room"},
	{"14", "XIII - Death", "Deals 40 damage to all enemies in the room"},
	{"15", "XIV - Temperance", "Spawns a Blood Donation Machine"},
	{"16", "XV - The Devil", "↑ +2 Damage up for current room"},
	{"17", "XVI - The Tower", "Spawns 6 troll bombs"},
	{"18", "XVII - The Stars", "Teleports you to the item room ({{TreasureRoom}})"},
	{"19", "XVIII - The Moon", "Teleports you to the secret room ({{SecretRoom}})"},
	{"20", "XIX - The Sun", "Deals 100 damage to all enemies#Full health#Reveals entire map"},
	{"21", "XX - Judgement", "Spawns a beggar"},
	{"22", "XXI - The World", "Reveals the entire map and shows all roomtypes"},
	{"23", "2 of Clubs", "Duplicate your bombs"},
	{"24", "2 of Diamonds", "Duplicate your money"},
	{"25", "2 of Spades", "Duplicate your keys"},
	{"26", "2 of Hearts", "Duplicate your red hearts#Only has a healing effect"},
	{"27", "Ace of Clubs", "Turns all pickups into bombs"},
	{"28", "Ace of Diamonds", "Turns all pickups into coins"},
	{"29", "Ace of Spades", "Turns all pickups into keys"},
	{"30", "Ace of Hearts", "Turns all pickups into hearts"},
	{"31", "Joker", "Teleports you to the devil{{DevilRoom}} or angel{{AngelRoom}} room"},
	{"32", "Hagalaz", "Destroy all rocks in the room"},
	{"33", "Jera", "Duplicate all pickups in room"},
	{"34", "Ehwaz", "Spawns a trapdoor"},
	{"35", "Dagaz", "+1 Soul Heart#Removes curse effects"},
	{"36", "Ansuz", "Full mapping for this floor"},
	{"37", "Perthro", "Reroll all pedestal items"},
	{"38", "Berkano", "Summons 3 blue spiders and 3 blue flies"},
	{"39", "Algiz", "Invincibility for 30 seconds"},
	{"40", "Blank Rune", "Random rune effect#25% chance to drop itself again"},
	{"41", "Black Rune", "Deals 40 damage to all enemies#Random stat up for every pedestal items in the room#(Destroys all pedestals in room)"},
	{"42", "Chaos Card", "Throwable instant kill-card"},
	{"43", "Credit Card", "Removes the price from all items in the current shop or devil deal, making everything free"},
	{"44", "Rules Card", "Displays \"helpful\" tips on use"},
	{"45", "A Card Against Humanity", "Fills the whole room with poop"},
	{"46", "Suicide King", "Instantly kills you and spawns 10 pickup / Collectibles on the floor"},
	{"47", "Get Out Of Jail Free Card", "Open all doors in the current room"},
	{"48", "? Card", "Activates your spacebar item for free"},
	{"49", "Dice Shard", "Rerolls pedestals and pickups in current room"},
	{"50", "Emergency Contact", "Two of Mom's Hands come down and grab an enemy"},
	{"51", "Holy Card", "Grants the Holy Mantle effect for one room#(Next damage you take is 0)#25% Chance to spawn another holy card"},
	{"52", "Huge Growth", "↑ +7 Damage up#↑ +30 Range up#↑ +Size up#Crush Rocks!#Effect lasts for current room"},
	{"53", "Ancient Recall", "Spawns 3 random cards when used"},
	{"54", "Era Walk", "Slow down enemies#↓ -0.5 Speed down#-1 Shot Speed down#Effect lasts for current room"},
}


---------- Pills ----------

EID.descriptions["en_us"].unidentifiedPill = "Unidentified Pill"

EID.descriptions["en_us"].pills={
	{"0", "Bad Gas", "Spawns a Gas cloud"},
	{"1", "Bad Trip", "Deals 1 heart of damage to you"},
	{"2", "Balls of Steel", "+2 Soul Hearts"},
	{"3", "Bombs are Key", "Switches number of bombs with keys"},
	{"4", "Explosive Diarrhea", "Spawns 5 troll bombs at your position"},
	{"5", "Full Health", "Full Health"},
	{"6", "Health Down", "↓ Health down"},
	{"7", "Health Up", "↑ Health up"},
	{"8", "I Found Pills", "No effect"},
	{"9", "Puberty", "Eating 3 will give you Adult transformation (+1 Red Heart)"},
	{"10", "Pretty Fly", "Adds 1 fly orbital"},
	{"11", "Range Down", "↓ -2 Range down"},
	{"12", "Range Up", "↑ +2.5 Range up"},
	{"13", "Speed Down", "↓ -0.12 Speed down"},
	{"14", "Speed Up", "↑ +0.15 Speed up"},
	{"15", "Tears Down", "↓ -0.28 Tears down"},
	{"16", "Tears Up", "↑ +0.35 Tears up"},
	{"17", "Luck Down", "↓ -1 Luck down"},
	{"18", "Luck Up", "↑ +1 Luck up"},
	{"19", "Telepills", "Teleport to random room"},
	{"20", "48 Hour Energy!", "Recharges your active item#Drops 1-2 batteries"},
	{"21", "Hematemesis", "Drains all but one heart container#Spawns 1-4 red hearts"},
	{"22", "Paralysis", "You can't move for 2 seconds"},
	{"23", "I can see forever!", "Opens secret room entrances on current floor"},
	{"24", "Pheromones", "Charms all enemies in room"},
	{"25", "Amnesia", "Hides the floor map"},
	{"26", "Lemon Party", "Spawns large puddle on the ground which damages enemies"},
	{"27", "R U A Wizard?", "Shoot diagonally for 30 seconds"},
	{"28", "Percs!", "Take only half the damage for current room"},
	{"29", "Addicted!", "Take full heart damage for current room"},
	{"30", "Re-Lax", "Spawn poop while walking for 2 seconds"},
	{"31", "???", "Curse of the maze effect for current floor"},
	{"32", "One makes you larger", "You grow bigger#Doesn't affect your hitbox"},
	{"33", "One makes you small", "You get smaller#Your hitbox gets smaller"},
	{"34", "Infested!", "Spawn 1 blue spider per poop in room"},
	{"35", "Infested?", "Spawn 1 blue spider per enemy in room#Spawns 1-3 blue spiders when no enemy is in the room"},
	{"36", "Power Pill!", "Short invincibility effect"},
	{"37", "Retro Vision", "Pixelates the screen for 30 seconds"},
	{"38", "Friends Till The End!", "Spawns 3 blue flies"},
	{"39", "X-Lax", "Spawn pool of slippery creep"},
	{"40", "Something's wrong...", "Spawn pool of slowing creep"},
	{"41", "I'm Drowsy...", "Slow all enemies in room"},
	{"42", "I'm Excited!!!", "Speed up for all enemies in room"},
	{"43", "Gulp!", "Consume current trinket and gain its effect permanently"},
	{"44", "Horf!", "Shoots one ipecac tear"},
	{"45", "Feels like I'm walking on sunshine!", "Short invincibility"},
	{"46", "Vurp!", "Spawns last used pill"},
} 

---------- Sacrifice Room ----------
EID.descriptions["en_us"].sacrificeHeader = "[Next Sacrifice Room payout]"

EID.descriptions["en_us"].sacrifice={
	{"1", "", "50% chance for 1 Coin#100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
	{"2", "", "50% chance for 1 Coin#100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
	{"3", "", "67% chance for increased Angel{{AngelRoom}} Room chance"},
	{"4", "", "50% chance for 1 random Chest"},
	{"5", "", "33% chance for 3 Coin#67% chance for increased Angel{{AngelRoom}} Room chance"},
	{"6", "", "33% chance for teleport to Angel{{AngelRoom}} Room#Teleports to Devil Room{{DevilRoom}} when its door was spawned on this floor already#67% chance for random Chest"},
	{"7", "", "33% chance for 1 random Angel{{AngelRoom}} Room item#67% chance for 1 soul heart"},
	{"8", "", "100% chance for 7 troll bombs"},
	{"9", "", "100% chance to spawn \"Uriel\" boss"},
	{"10", "", "50% chance for 7 soul hearts#50% chance for 30 coins"},
	{"11", "", "100% chance to spawn \"Gabriel\" boss"},
	{"12", "", "50% chance to teleport to \"Dark Room\" floor"},
}

---------- Dice Room ----------
EID.descriptions["en_us"].diceHeader = "[Dice effect]"

EID.descriptions["en_us"].dice={
	{"1", "", "Rerolls all of your items#(only affect collectibles)"},
	{"2", "", "Rerolls all pickups in the room"},
	{"3", "", "Rerolls all pickups on the entire floor"},
	{"4", "", "Rerolls all pedestal items on the floor#Doesnt affect Devil deals"},
	{"5", "", "Reroll and restart the current floor"},
	{"6", "", "Reroll all of your items and all the pickups & items on the entire floor"}
}

---------- Transformations ----------
EID.descriptions["en_us"].transformations = {
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Lord of the Flies",-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Mom",				-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}
