---------------------------------------
-----  Basic English descriptions -----
---------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

local languageCode = "en_us"

-- init en_us table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "English"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = {{name="default"}, {name="inverted"}, {name="borderless"}}

---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "The Sad Onion", "↑ {{Tears}} +0.7 Tears up"},
	{"2", "The Inner Eye", "Triple shot#↓ {{Tears}} Tears down"},
	{"3", "Spoon Bender", "Homing tears"},
	{"4", "Cricket's Head", "↑ {{Damage}} +0.5 Damage up#↑ {{Damage}} +50% Damage Multiplier"},
	{"5", "My Reflection", "Gives tears a boomerang effect#↑ {{Range}} +1.5 Range up#↑ {{Shotspeed}} +0.6 Shot Speed up#↑ +1 Tear Height"},
	{"6", "Number One", "↑ {{Tears}} +1.5 Tears up#↓ {{Range}} -17.62 Range down#↑ +0.76 Tear Height"},
	{"7", "Blood of the Martyr", "↑ {{Damage}} +1 Damage up#{{Collectible34}} +50% Damage if you have Book of Belial or Devil Card effect active"},
	{"8", "Brother Bobby", "Normal tear familiar#Deals 3.5 damage per tear"},
	{"9", "Skatole", "All fly enemies are friendly"},
	{"10", "Halo of Flies", "+2 fly orbitals#Blocks enemy projectiles"},
	{"11", "1up!", "↑ +1 life#Respawn with full health"},
	{"12", "Magic Mushroom", "↑ +1 Health up#Full health#↑ {{Damage}} +0.3 Damage up#↑ {{Damage}} +50% Damage Multiplier#↑ {{Range}} +5.25 Range up#↑ {{Speed}} +0.3 Speed up#↑ +0.5 Tear Height#Size up"},
	{"13", "The Virus", "{{Poison}} Poison touch#↓ {{Speed}} -0.1 Speed down#{{BlackHeart}} Enemies can drop Black Hearts if poisoned"},
	{"14", "Roid Rage", "↑ {{Speed}} +0.6 Speed up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"15", "<3", "↑ {{Heart}} +1 Health up#{{Heart}} Full health"},
	{"16", "Raw Liver", "↑ {{Heart}} +2 Health up#{{Heart}} Full health"},
	{"17", "Skeleton Key", "{{Key}} +99 Keys"},
	{"18", "A Dollar", "{{Coin}} +99 coins"},
	{"19", "Boom!", "{{Bomb}} +10 Bombs"},
	{"20", "Transcendence", "Flight!"},
	{"21", "The Compass", "Reveals icons on the map#Does not show the layout of the map"},
	{"22", "Lunch", "↑ {{Heart}} +1 Health up"},
	{"23", "Dinner", "↑ {{Heart}} +1 Health up"},
	{"24", "Dessert", "↑ {{Heart}} +1 Health up"},
	{"25", "Breakfast", "↑ {{Heart}} +1 Health up"},
	{"26", "Rotten Meat", "↑ {{Heart}} +1 Health up"},
	{"27", "Wooden Spoon", "↑ {{Speed}} +0.3 Speed up"},
	{"28", "The Belt", "↑ {{Speed}} +0.3 Speed up"},
	{"29", "Mom's Underwear", "↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"30", "Mom's Heels", "↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"31", "Mom's Lipstick", "↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"32", "Wire Coat Hanger", "↑ {{Tears}} +0.7 Tears up"},
	{"33", "The Bible", "Flight for current room#{{MomsHeart}} Kills Mom's Foot and Mom's Heart instantly#!!! Kills YOU when used on Satan"},
	{"34", "The Book of Belial", "↑ {{Damage}} +2 Damage up#{{Collectible7}} +50% Damage if you have Blood of the Martyr#{{AngelDevilChance}} +12.5% Devil/Angel Room chance while held"},
	{"35", "The Necronomicon", "Deal 40 damage to all enemies in the room"},
	{"36", "The Poop", "Spawns one poop and knocks back enemies#Can be placed next to a pit and destroyed with a bomb to make a bridge"},
	{"37", "Mr. Boom", "Drops a large bomb below the player which deals 110 damage"},
	{"38", "Tammy's Head", "Fires 10 tears in a circle around Isaac"},
	{"39", "Mom's Bra", "Freeze all enemies in the current room for 4 seconds"},
	{"40", "Kamikaze!", "Causes an explosion at the players location#Deals 40 damage"},
	{"41", "Mom's Pad", "{{Fear}} Fears all enemies in the current room for 5 seconds"},
	{"42", "Bob's Rotten Head", "{{Poison}} Throwable poison bomb"},
	{"43", "", "<item does not exist>"},
	{"44", "Teleport!", "Teleports Isaac into a random room except I AM ERROR rooms"},
	{"45", "Yum Heart", "Heal 1 Red Heart"},
	{"46", "Lucky Foot", "↑ {{Luck}} +1 Luck up#+8% room clear reward chance#Better chance to win while gambling"},
	{"47", "Doctor's Remote", "{{Collectible168}} On use, start aiming a crosshair#A missile lands on the crosshair after 1.5 seconds#Deals 20 times your damage"},
	{"48", "Cupid's Arrow", "Piercing tears"},
	{"49", "Shoop da Whoop!", "High damage brimstone laser"},
	{"50", "Steven", "↑ {{Damage}} +1 Damage up"},
	{"51", "Pentagram", "↑ {{Damage}} +1 Damage up#{{AngelDevilChance}} +10% Devil/Angel Room chance"},
	{"52", "Dr. Fetus", "{{Bomb}} Bomb tears#Each bomb deals 5x your damage + 30#↓ {{Tears}} Tear Delay x 2.5"},
	{"53", "Magneto", "Magnetic attraction for pickups"},
	{"54", "Treasure Map", "Reveals the floor layout#Does not show room icons"},
	{"55", "Mom's Eye", "50% chance to shoot a tear backwards#100% chance at 2 Luck"},
	{"56", "Lemon Mishap", "Drop a pool of lemonade#Deals 24 contact damage per second"},
	{"57", "Distant Admiration", "Mid-range fly orbital#Deals 75 contact damage per second"},
	{"58", "Book of Shadows", "Invincibility for 10 seconds"},
	{"59", "", "<item does not exist>"},
	{"60", "The Ladder", "Walk over small gaps"},
	{"61", "", "<item does not exist>"},
	{"62", "Charm of the Vampire", "{{HalfHeart}} Heals half a heart every 13 enemies killed"},
	{"63", "The Battery", "Active items can now be charged up twice"},
	{"64", "Steam Sale", "{{Shop}} -50% on Shop items#Getting this item two times will make everything free"},
	{"65", "Anarchist Cookbook", "Spawn 6 troll bombs near the center of the room"},
	{"66", "The Hourglass", "{{Slow}} Slow down enemies for 8 seconds"},
	{"67", "Sister Maggy", "Normal tear familiar#Deals 3.5 damage per tear"},
	{"68", "Technology", "Tears are now lasers"},
	{"69", "Chocolate Milk", "{{Chargeable}} Chargeable tears#↑ {{Damage}} Up to 400% Damage#↓ {{Tears}} Tears down"},
	{"70", "Growth Hormones", "↑ {{Damage}} +1 Damage up#↑ {{Speed}} +0.4 Speed up"},
	{"71", "Mini Mush", "↑ {{Speed}} +0.3 Speed up#↓ {{Range}} -4.25 Range down*#↑ +1.5 Tear Height*#(*both add up to a slight Range up)#↑ Size down"},
	{"72", "Rosary", "{{SoulHeart}} +3 Soul Hearts#{{Collectible33}} The Bible is added to all item pools"},
	{"73", "Cube of Meat", "LVL1: Orbital#LVL2: Shooting orbital#LVL3: Meat Boy LVL1#LVL4: Meat Boy LVL2"},
	{"74", "A Quarter", "{{Coin}} +25 coins"},
	{"75", "PHD", "{{Pill}} Better pills#Spawns 1 pill on pickup#{{Heart}} Heals 2 Red Hearts#{{BloodDonationMachine}} More money from Blood Donation Machines and {{Collectible135}} IV Bag"},
	{"76", "X-Ray Vision", "{{SecretRoom}} Reveals secret rooms entrances"},
	{"77", "My Little Unicorn", "Invincibility and +0.28 Speed up for 6 seconds#Deal 40 contact damage per second while invincible"},
	{"78", "Book of Revelations", "{{SoulHeart}} +1 Soul Heart#Higher Horseman boss chance if used#{{AngelDevilChance}} +17.5% Devil/Angel Room chance while held"},
	{"79", "The Mark", "↑ {{Damage}} +1 Damage up#↑ {{Speed}} +0.2 Speed up#{{SoulHeart}} +1 Soul Heart"},
	{"80", "The Pact", "↑ {{Damage}} +0.5 Damage up#↑ {{Tears}} +0.7 Tears up#{{SoulHeart}} +2 Soul Hearts"},
	{"81", "Dead Cat", "↑ +9 lives#Respawn with 1 HP#↓ Sets your Red Heart containers to 1#!!! Characters that can't have Red Hearts get set to 1 Soul/Black Heart"},
	{"82", "Lord of the Pit", "Flight#↑ {{Speed}} +0.3 Speed up"},
	{"83", "The Nail", "{{SoulHeart}} +1 Soul Heart#↑ {{Damage}} +0.7 Damage up#↓ {{Speed}} -0.18 Speed down#Deal 40 contact damage per second#Destroy rocks when walking over them"},
	{"84", "We Need To Go Deeper!", "Spawns a trapdoor to the next floor#{{LadderRoom}} 10% chance for crawlspace trapdoor"},
	{"85", "Deck of Cards", "{{Card}} Spawns 1 Card"},
	{"86", "Monstro's Tooth", "Summon Monstro to fall on an enemy and deal 120 damage"},
	{"87", "Loki's Horns", "25% chance to shoot in 4 directions#{{Luck}} 100% chance at 7 Luck"},
	{"88", "Little Chubby", "Familiar that charges forward#Deals 52.5 contact damage per second"},
	{"89", "Spider Bite", "{{Slow}} 25% chance to shoot slowing tears#{{Luck}} 100% chance at 15 Luck"},
	{"90", "The Small Rock", "↑ {{Damage}} +1 Damage up#↑ {{Tears}} +0.2 Tears up#↓ {{Speed}} -0.2 Speed down"},
	{"91", "Spelunker Hat", "Reveals the room type of adjacent rooms#{{SecretRoom}} Can also reveal Secret and Super Secret Rooms"},
	{"92", "Super Bandage", "↑ {{Heart}} +1 Health up#{{SoulHeart}} +2 Soul Hearts#{{Heart}} Heals 1 Red Heart"},
	{"93", "The Gamekid", "Short invincibility#{{Fear}} Fears all enemies#Deal 40 contact damage per second#{{HalfHeart}} Two eaten enemies replenish half a heart"},
	{"94", "Sack of Pennies", "{{Coin}} Drops a random coin every 2 rooms"},
	{"95", "Robo-Baby", "Laser tears#Deals 3.5 damage per shot"},
	{"96", "Little C.H.A.D.", "{{HalfHeart}} Drops half a heart every 3 rooms"},
	{"97", "The Book of Sin", "Spawns a random pickup"},
	{"98", "The Relic", "{{SoulHeart}} Spawns 1 Soul Heart every 5-6 rooms"},
	{"99", "Little Gish", "{{Slow}} Slowing tears#Deals 3.5 damage per shot"},
	{"100", "Little Steven", "Homing tears#Deals 3.5 damage per shot"},
	{"101", "The Halo", "↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.3 Damage up#↑ {{Tears}} +0.2 Tears up#↑ {{Range}} +0.25 Range up#↑ {{Speed}} +0.3 Speed up#↑ +0.5 Tear Height"},
	{"102", "Mom's Bottle of Pills", "{{Pill}} Spawns 1 Pill"},
	{"103", "The Common Cold", "{{Poison}} 25% chance to shoot Poison tears#{{Luck}} 100% chance at 12 Luck"},
	{"104", "The Parasite", "Tears split in two on contact#Split tears deal half damage"},
	{"105", "The D6", "Rerolls pedestals in current room"},
	{"106", "Mr. Mega", "↑ Bomb damage x2.25#{{Bomb}} +5 Bombs"},
	{"107", "The Pinking Shears", "Flight#Your body attacks enemies with 82.5 contact damage per second"},
	{"108", "The Wafer", "All damage taken is reduced to half a heart"},
	{"109", "Money = Power", "↑ {{Damage}} +0.04 Damage up for every {{Coin}}coin you have"},
	{"110", "Mom's Contacts", "20% chance to shoot petrifying tears#↑ +0.25 Range up#↑ +0.5 Tear Height"},
	{"111", "The Bean", "{{Poison}} Poison fart#The poison deals your damage 6 times"},
	{"112", "Guardian Angel", "Orbital#Speeds up all orbitals#Blocks projectiles#Deals 105 contact damage per second"},
	{"113", "Demon Baby", "Auto-firing turret#Deals 3 damage per shot"},
	{"114", "Mom's Knife", "Controllable knife attack#The knife deals 2x Isaac's damage while held and 6x damage at the furthest possible distance"},
	{"115", "Ouija Board", "Spectral tears"},
	{"116", "9 Volt", "-1 charge needed for active items#{{Battery}} Fully recharges your active item"},
	{"117", "Dead Bird", "Spawns a bird when you get hit#Bird deals 4 contact damage per second"},
	{"118", "Brimstone", "{{Chargeable}} Charge a blood laser that deals constant damage"},
	{"119", "Blood Bag", "↑ {{Heart}} +1 Health up#↑ {{Speed}} +0.3 Speed up#{{Heart}} Heals 4 Hearts"},
	{"120", "Odd Mushroom (Thin)", "↑ {{Tears}} +1.7 Tears up#↑ {{Speed}} +0.3 Speed up#↓ {{Damage}} -38% Damage Multiplier#Penalty shrinks as you get Damage Ups from other items"},
	{"121", "Odd Mushroom (Large)", "↑ {{EmptyHeart}} +1 Empty heart container#↑ {{Damage}} +0.3 Damage up#↑ {{Range}} +0.25 Range up#↓ {{Speed}} -0.1 Speed down#↑ +0.5 Tear Height"},
	{"122", "Whore of Babylon", "!!! When on half a Red Heart or less:#↑ {{Damage}} +1.5 Damage up#↑ {{Speed}} +0.3 Speed up"},
	{"123", "Monster Manual", "Random familiar for current room"},
	{"124", "Dead Sea Scrolls", "Random active item effect"},
	{"125", "Bobby-Bomb", "Homing bombs#{{Bomb}} +5 Bombs"},
	{"126", "Razor Blade", "↑ {{Damage}} +1.2 Damage up for current Room#↓ Deals 1 heart of damage to you#Prioritizes Red Hearts"},
	{"127", "Forget Me Now", "{{Warning}} SINGLE USE {{Warning}}#Reroll entire floor"},
	{"128", "Forever Alone", "Fly orbital#Far away#Deals 30 contact damage per second"},
	{"129", "Bucket of Lard", "↑ +2 Empty heart container#↓ -0.2 Speed down#Heals half a heart"},
	{"130", "A Pony", "Grants flight while held#{{Speed}} Sets your speed to 1.5 if you have less than 1.5#Dash in a direction on use"},
	{"131", "Bomb Bag", "{{Bomb}} Drops 1 Bomb pickup every 2-3 rooms"},
	{"132", "A Lump of Coal", "{{Damage}} Tears deal more Damage the further they travel"},
	{"133", "Guppy's Paw", "!!! On use, convert:#1 heart container to 3 Soul Hearts"},
	{"134", "Guppy's Tail", "{{Chest}} 33% chance for room clear reward to be a chest#33% chance for no room clear reward"},
	{"135", "IV Bag", "Portable blood bank#Half a heart = 1-3 coins#{{Player14}} 0-1 coin as Keeper"},
	{"136", "Best Friend", "Exploding Decoy#Attracts enemies"},
	{"137", "Remote Detonator", "Detonate bombs on demand#{{Bomb}} +5 bombs"},
	{"138", "Stigmata", "↑ +1 Health up#↑ {{Damage}} +0.3 Damage up"},
	{"139", "Mom's Purse", "{{Trinket}} You can now hold 2 trinkets"},
	{"140", "Bob's Curse", "{{Poison}} Poison bombs#{{Bomb}} +5 bombs"},
	{"141", "Pageant Boy", "{{Coin}} Spawns 7 random coins"},
	{"142", "Scapular", "{{SoulHeart}} Once per room, when down to half a heart, you gain 1 Soul Heart"},
	{"143", "Speed Ball", "↑ {{Speed}} +0.3 Speed up#↑ {{Shotspeed}} +0.2 Shot Speed up"},
	{"144", "Bum Friend", "{{Coin}} Collects coins from the floor#Spawns random pickups in return"},
	{"145", "Guppy's Head", "Spawns 2-4 blue flies"},
	{"146", "Prayer Card", "{{EternalHeart}} +1 Eternal Heart"},
	{"147", "Notched Axe", "Break rocks in current room on touch"},
	{"148", "Infestation", "Spawn flies when you get hit"},
	{"149", "Ipecac", "{{Poison}} Explosive poison tears#↑ {{Damage}} +40 Damage up#↓ {{Tears}} Tears down"},
	{"150", "Tough Love", "10% chance to shoot teeth#{{Damage}} Teeth deal 3.2x your damage#{{Luck}} 100% chance at 9 Luck"},
	{"151", "The Mulligan", "1/6 chance to spawn a fly when tears hit an enemy"},
	{"152", "Technology 2", "Replaces your right eye with a continuous laser#Laser deals 20% of your damage#↓ {{Damage}} -35% Damage down#↓ {{Tears}} Tear Delay x 2"},
	{"153", "Mutant Spider", "Quad Shot!#↓ {{Tears}} Tears down"},
	{"154", "Chemical Peel", "↑ {{Damage}} +2 Damage up for left eye"},
	{"155", "The Peeper", "Floats around the room#Deals 17.1 contact damage per second"},
	{"156", "Habit", "{{Battery}} +1 charge when you get hit"},
	{"157", "Bloody Lust", "↑ {{Damage}} Damage up every time you get hit#Applies up to 6 times per floor#Lasts for whole floor"},
	{"158", "Crystal Ball", "Reveal full map#Drops random Card or Soul Heart"},
	{"159", "Spirit of the Night", "Flight#Spectral tears"},
	{"160", "Crack the Sky", "Spawns 5 beams of light near enemies#Deals your damage + 20"},
	{"161", "Ankh", "{{Player4}} Respawn as ??? (Blue Baby) on death"},
	{"162", "Celtic Cross", "Chance for invincibility when Isaac gets hit"},
	{"163", "Ghost Baby", "Spectral tears familiar#Deals 3.5 damage per shot"},
	{"164", "The Candle", "Throw a blue flame#Deals contact damage#Blocks enemy tears#Despawns after 2 seconds"},
	{"165", "Cat-o-nine-tails", "↑ {{Damage}} +1 Damage up#↑ {{Shotspeed}} +0.23 Shot speed up"},
	{"166", "D20", "Reroll pickups"},
	{"167", "Harlequin Baby", "Shoots two tears in a V-shaped pattern#Deals 4 damage per shot"},
	{"168", "Epic Fetus", "Instead of tears, aim a crosshair#A missile lands on the crosshair after 1.5 seconds#Deals 20 times your damage"},
	{"169", "Polyphemus", "↑ {{Damage}} +100% Damage up#↑ {{Damage}} +4 additional Damage up#↓ {{Tears}} Tears down#Tears keep going after killing an enemy"},
	{"170", "Daddy Longlegs", "Stomps on enemies#Deals 40 damage per second"},
	{"171", "Spider Butt", "Slows down enemies for 4 seconds#10 damage to all enemies"},
	{"172", "Sacrificial Dagger", "Orbital knife#Blocks enemy shots#Deals 225 damage per second"},
	{"173", "Mitre", "{{SoulHeart}} Higher chance to find Soul Hearts"},
	{"174", "Rainbow Baby", "Shoots random tears#Deals 3-5 damage per shot"},
	{"175", "Dad's Key", "Opens all doors in the room, including {{SecretRoom}}{{SuperSecretRoom}}Secret Rooms, {{ChallengeRoom}}{{BossRushRoom}}Challenge Rooms, and the Mega Satan door"},
	{"176", "Stem Cells", "↑ {{Heart}} +1 Health up#↑ {{Shotspeed}} +0.16 Shot Speed up"},
	{"177", "Portable Slot", "Portable slot machine"},
	{"178", "Holy Water", "Leaves pool of creep when you get hit#Deals 24 damage per second"},
	{"179", "Fate", "Flight#{{EternalHeart}} +1 Eternal Heart"},
	{"180", "The Black Bean", "Fart when touched"},
	{"181", "White Pony", "Grants flight while held#{{Speed}} Sets your speed to 1.5 if you have less than 1.5#Holy Dash on use"},
	{"182", "Sacred Heart", "↑ +1 Health up#Full health#↑ 230% + 1 Damage up#↓ -0.4 Tears down#↓ -0.25 Shot Speed down#↑ +0.38 Range up#↑ +0.75 Tear Height#Homing tears"},
	{"183", "Tooth Picks", "↑ {{Tears}} +0.7 Tears up#↑ {{Shotspeed}} +0.16 Shot Speed up"},
	{"184", "Holy Grail", "Flight#↑ +1 Health up"},
	{"185", "Dead Dove", "Flight#Spectral tears"},
	{"186", "Blood Rights", "↑ Deal 40 damage to every enemy#↓ Deals 1 heart of damage to you#Prioritizes Red Hearts"},
	{"187", "Guppy's Hairball", "Growing hairball#Swings around you#Grows when it kills an enemy#Bigger ball deals more damage"},
	{"188", "Abel", "Mirrors your movement#Shoots towards the player#Deals 3.5 damage per shot"},
	{"189", "SMB Super Fan", "↑ +1 Health up#Full health#↑ +0.3 Damage up#↑ +0.2 Tears up#↑ +0.5 Range up#↑ +0.2 Speed up#↑ +1 Tear Height"},
	{"190", "Pyro", "{{Bomb}} +99 Bombs"},
	{"191", "3 Dollar Bill", "Random tear effect every 2-3 seconds"},
	{"192", "Telepathy For Dummies", "Homing tears for current room"},
	{"193", "MEAT!", "↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.3 Damage up"},
	{"194", "Magic 8 Ball", "↑ {{Shotspeed}} +0.16 Shot speed up#{{Card}} +1 card"},
	{"195", "Mom's Coin Purse", "{{Pill}} Drops 4 Pills"},
	{"196", "Squeezy", "{{SoulHeart}} Spawns 2 Soul Hearts#↑ {{Tears}} +0.4 Tears up"},
	{"197", "Jesus Juice", "↑ +0.5 Damage up#↑ +0.25 Range up#↑ +0.5 Tear Height"},
	{"198", "Box", "Spawns 1 pickup of each kind"},
	{"199", "Mom's Key", "{{Key}} +2 Keys#More drops from chests"},
	{"200", "Mom's Eyeshadow", "{{Charm}} 10% chance to shoot charming tears"},
	{"201", "Iron Bar", "↑ {{Damage}} +0.3 Damage up#{{Confusion}} 10% chance to shoot concussive tears"},
	{"202", "Midas' Touch", "Turn enemies into gold on touch#Deals contact damage based on your coin count#{{Coin}} Golden enemies drop coins#High chance for effects that spawn Poop to spawn Golden Poop"},
	{"203", "Humbleing Bundle", "Doubles all pickups"},
	{"204", "Fanny Pack", "50% chance to drop a random pickup when you get hit"},
	{"205", "Sharp Plug", "{{Battery}} On use, fully recharges your active item at the cost of 2 Hearts#!!! Only works when item has no charges!"},
	{"206", "Guillotine", "↑ {{Damage}} +1 Damage up#↑ {{Tears}} Tears up#Your head is now an orbital which doesn't take damage and deals 105 contact damage#You will still shoot from the head"},
	{"207", "Ball of Bandages", "LVL1: Orbital#LVL2: Shooting orbital#LVL3: Bandage Girl LVL1#LVL4: Bandage Girl LVL2"},
	{"208", "Champion Belt", "↑ {{Damage}} +1 Damage up#!!! +15% chance for champion enemies"},
	{"209", "Butt Bombs", "{{Bomb}} +5 Bombs#{{Confusion}} Explosions concuss and damage every enemy in the room"},
	{"210", "Gnawed Leaf", "Invincible when standing still for 1 second"},
	{"211", "Spiderbaby", "Spawn 1-2 spiders when getting hit"},
	{"212", "Guppy's Collar", "50% chance to revive with half a heart on death"},
	{"213", "Lost Contact", "Shielded tears#Tears block enemy shots#↓ {{Shotspeed}} -0.15 Shot Speed down"},
	{"214", "Anemic", "↑ {{Range}} +5 Range up#Leave a trail of damaging creep after taking damage"},
	{"215", "Goat Head", "{{AngelDevilChance}} 100% chance for Devil/Angel Rooms"},
	{"216", "Ceremonial Robes", "↑ {{Damage}} +1 Damage up#{{BlackHeart}} +3 Black Hearts"},
	{"217", "Mom's Wig", "Random chance to spawn blue spider when shooting tears#{{Heart}} Heals 1 Red Heart"},
	{"218", "Placenta", "↑ {{Heart}} +1 Health up#{{HalfHeart}} Chance to heal half a heart every minute"},
	{"219", "Old Bandage", "↑ {{EmptyHeart}} +1 Empty heart container#{{Heart}} Random chance to drop Red Hearts when getting hit"},
	{"220", "Sad Bombs", "Bomb explosions also fire 10 tears in a circle#{{Bomb}} +5 Bombs"},
	{"221", "Rubber Cement", "Bouncing tears"},
	{"222", "Anti-Gravity", "Holding the fire buttons causes tears to hover in midair#When released, they will all shoot in the direction they were fired#↑ {{Tears}} -2 Tear Delay"},
	{"223", "Pyromaniac", "Explosions heal you#{{Bomb}} +5 Bombs"},
	{"224", "Cricket's Body", "Tears split up in 4 on hit#Split tears deal half damage#↑ {{Tears}} +1 Tears up#↓ {{Range}} -10 Range down"},
	{"225", "Gimpy", "{{SoulHeart}} Chance to spawn a Soul Heart when taking damage#{{HalfHeart}} Monsters have a chance to drop a Half Red Heart on death"},
	{"226", "Black Lotus", "↑ {{Heart}} +1 Health up#{{SoulHeart}} +1 Soul Heart#{{BlackHeart}} +1 Black Heart"},
	{"227", "Piggy Bank", "{{Coin}} +3 coins#Spawns 1-2 coins when getting hit#{{Player14}} 0-1 coin as Keeper"},
	{"228", "Mom's Perfume", "{{Fear}} 15% chance to shoot Fear tears#↑ {{Tears}} +1 Tears up"},
	{"229", "Monstro's Lung", "{{Chargeable}} Tears are charged and released in a shotgun style attack#↓ {{Tears}} 4.3x Tear Delay up"},
	{"230", "Abaddon", "↑ {{Damage}} +1.5 Damage up#↑ {{Speed}} +0.2 Speed up#{{Fear}} Fear tears#↓ {{EmptyHeart}} Removes all heart containers#{{BlackHeart}} +6 Black Hearts"},
	{"231", "Ball of Tar", "{{Slow}} 10% chance to shoot slowing tears#{{Luck}} 100% chance at 18 Luck#Leave trail of slowing creep"},
	{"232", "Stop Watch", "{{Slow}} Upon getting hit, slow all enemies in the room permanently#↑ +0.3 Speed up"},
	{"233", "Tiny Planet", "Tears orbit around you#↑ {{Range}} Range way up!#↑ +7 Tear Height#Spectral tears"},
	{"234", "Infestation 2", "Spawn spiders when you kill an enemy"},
	{"235", "", "<item does not exist>"},
	{"236", "E. Coli", "On touch, turn enemies into poop"},
	{"237", "Death's Touch", "Scythe tears!#↑ +1.5 Damage up#↓ -0.3 Tears down#Piercing tears"},
	{"238", "Key Piece 1", "!!! Key piece for Mega Satan door!#{{AngelChance}} 25% higher Angel Room chance"},
	{"239", "Key Piece 2", "!!! Key piece for Mega Satan door!#{{AngelChance}} 25% higher Angel Room chance"},
	{"240", "Experimental Treatment", "All Stats ↑/↓ a random number"},
	{"241", "Contract from Below", "Doubles all room clear rewards#33% chance for no room clear reward#{{GreedMode}} Doesn't affect Greed Mode"},
	{"242", "Infamy", "50% chance to block tears"},
	{"243", "Trinity Shield", "Tear blocking shield"},
	{"244", "Tech.5", "Occasionally fire lasers in addition to your tears"},
	{"245", "20/20", "Doubles all your shots"},
	{"246", "Blue Map", "{{SecretRoom}} Reveals secret rooms"},
	{"247", "BFFS!", "Your familiars deal double damage"},
	{"248", "Hive Mind", "Blue Spiders and Flies deal double damage"},
	{"249", "There's Options", "2 Boss items spawn instead of 1#!!! Only one can be taken"},
	{"250", "Bogo Bombs", "{{Bomb}} All bomb drops become double bombs"},
	{"251", "Starter Deck", "{{Card}} You can carry 2 Cards#Turns all Pills into Cards#Spawns 1 card on pickup"},
	{"252", "Little Baggy", "{{Pill}} You can carry 2 Pills#Turns all Cards into Pills#Spawns 1 pill on pickup"},
	{"253", "Magic Scab", "↑ {{Luck}} +1 Luck up#↑ {{Heart}} +1 Health up"},
	{"254", "Blood Clot", "↑ {{Damage}} +1 Damage up#↑ {{Range}} +5 Range up#!!! Applies only for the left eye"},
	{"255", "Screw", "↑ {{Tears}} +0.5 Tears up#↑ {{Shotspeed}} +0.2 Shot Speed up"},
	{"256", "Hot Bombs", "{{Burning}} Burning bombs#{{Bomb}} +5 Bombs"},
	{"257", "Fire Mind", "{{Burning}} Tears light enemies on fire#Chance for tears to explode on enemy impact#100% chance to explode at 13 Luck#!!! The explosion can hurt you!"},
	{"258", "Missing No.", "Rerolls all your items and stats on pickup and every time you change the floor"},
	{"259", "Dark Matter", "↑ {{Damage}} +1 Damage up#{{Fear}} 33% chance to shoot Fear tears"},
	{"260", "Black Candle", "{{CurseBlind}} Immunity to Curses#{{BlackHeart}} +1 Black Heart#{{AngelDevilChance}} +15% Devil/Angel Room chance"},
	{"261", "Proptosis", "↑ {{Damage}} +100% Damage up#↓ Tears deal less Damage the further they travel"},
	{"262", "Missing Page 2", "{{BlackHeart}} +1 Black Heart#When down to 1 Heart, damages all enemies in the room"},
	{"263", "", "<item does not exist>"},
	{"264", "Smart Fly", "Orbital#When you get hit, it attacks enemies#Deals 22.5 damage per second"},
	{"265", "Dry Baby", "When its hit by enemy tears, it has a 10% chance to damage all enemies in the room"},
	{"266", "Juicy Sack", "Leaves slowing creep#Spawns 1-2 friendly spiders after clearing a room"},
	{"267", "Robo-Baby 2.0", "Shoots lasers#Deals 3.5 damage per shot#Moves in the direction you shoot"},
	{"268", "Rotten Baby", "Spawns blue flies when the player is shooting"},
	{"269", "Headless Baby", "Leaves creep which deals 6 damage per second"},
	{"270", "Leech", "{{HalfHeart}} Heal half a heart when it kills an enemy#3.2 damage per second"},
	{"271", "Mystery Sack", "Drops random pickups every few rooms"},
	{"272", "BBF", "Friendly exploding fly#The explosion deals 60 damage"},
	{"273", "Bob's Brain", "Throwable bomb familiar#The explosion deals 60 damage"},
	{"274", "Best Bud", "When you get hit, gain one midrange orbital for the room#Orbital deals 75 damage per second"},
	{"275", "Lil Brimstone", "{{Collectible118}} Familiar that charges to shoot a brimstone laser#Shot deals 31.5 damage per second"},
	{"276", "Isaac's Heart", "Gain an invulnerable body#!!! When the heart familiar gets hit you take damage"},
	{"277", "Lil Haunt", "Friendly ghost familiar#Deals 4 damage per second"},
	{"278", "Dark Bum", "{{Heart}} Collects Red Hearts from the floor#Every 1.5 hearts, spawns a Soul/Black Heart or spider"},
	{"279", "Big Fan", "Big fat orbital#Deals 30 damage per second"},
	{"280", "Sissy Longlegs", "Randomly spawns blue spiders when in a hostile room"},
	{"281", "Punching Bag", "Decoy familiar#Enemies will target him instead"},
	{"282", "How to Jump", "Allows you to jump"},
	{"283", "D100", "Reroll all pickups, pedestals and all your held passive items"},
	{"284", "D4", "Reroll all your held passive items"},
	{"285", "D10", "Reroll all enemies in the room"},
	{"286", "Blank Card", "Mimic effects of your held card"},
	{"287", "Book of Secrets", "Gain one of these effects for the floor: #{{Collectible54}} Treasure Map#{{Collectible21}} Compass #{{Collectible246}} Blue Map"},
	{"288", "Box of Spiders", "Spawn 1-4 blue spiders"},
	{"289", "Red Candle", "Throw a red flame#The flame stays until it has dealt damage or blocked shots 5 times"},
	{"290", "The Jar", "{{Heart}} Stores up to 4 Red Heart pickups for later usage"},
	{"291", "Flush!", "Turns all non-boss enemies into poop#Instantly kills poop enemies and bosses"},
	{"292", "Satanic Bible", "{{BlackHeart}} +1 Black Heart"},
	{"293", "Head of Krampus", "Shoot brimstone lasers in all 4 directions"},
	{"294", "Butter Bean", "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger {{Collectible484}}Wait What? when swapping it with a different active item and picking it up again"},
	{"295", "Magic Fingers", "Damages the whole room with 2x the player damage#{{Coin}} Price: 1 coin"},
	{"296", "Converter", "Converts 2 Soul or Black Hearts into 1 Red Heart Container"},
	--NOTE FOR LOCALIZERS: There is code to highlight the text of your current floor
	--For it to work, only use line breaks or semicolons to separate floor details, and use the same order as English
	{"297", "Pandora's Box", "{{Warning}} SINGLE USE, spawns items based on floor:#B1: 2 {{SoulHeart}}; B2: 2 {{Bomb}} & 2 {{Key}}#C1: 1 {{BossRoom}} item; C2: B1+C1#D1: 4 {{SoulHeart}}; D2: 20 {{Coin}}#W1: 2 {{BossRoom}} items#W2: {{Collectible33}} The Bible#???/Void: Nothing#Sheol: 1 {{DevilRoom}} item + 1 {{BlackHeart}}#Cathe: 1 {{AngelRoom}} item + 1 {{EternalHeart}}#Dark Room: {{Collectible523}} Unlocks Moving Box; Chest: 1 {{Coin}}"},
	{"298", "Unicorn Stump", "Invincibility and +0.28 speed up for 6 seconds#No contact damage"},
	{"299", "Taurus", "↓ {{Speed}} -0.3 Speed down#↑ {{Speed}} Slowly gain speed while in hostile rooms#{{Collectible77}} At 2 speed, gain invincibility and deal contact damage#Afterwards, lose the Taurus speed boost for the room"},
	{"300", "Aries", "↑ {{Speed}} +0.25 Speed up#Touching enemies hurts them"},
	{"301", "Cancer", "{{SoulHeart}} +3 Soul Hearts#Halves taken damage in room when you already got hit"},
	{"302", "Leo", "Destroy rocks when walking over them#Size up"},
	{"303", "Virgo", "Chance to get invincibility when hit#{{Pill}} Converts negative pills into positive ones"},
	{"304", "Libra", "+6 Coins, Keys, and Bombs#Balances your stats!#!!! Every stats up afterwards will affect other stats too"},
	{"305", "Scorpio", "{{Poison}} Poison tears"},
	{"306", "Sagittarius", "↑ {{Speed}} +0.2 Speed up#Piercing tears"},
	{"307", "Capricorn", "↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.5 Damage up#↑ {{Speed}} +0.1 Speed up#↑ {{Range}} +1.5 Range up#↑ {{Tears}} Tears up#+1 Bomb, Coin, and Key"},
	{"308", "Aquarius", "Leave trail of creep#Creep deals 6 damage per second"},
	{"309", "Pisces", "↑ {{Tears}} -1 Tear Delay#Increases knockback"},
	{"310", "Eve's Mascara", "↑ {{Damage}} +100% Damage up#↓ {{Tears}} -50% Tears down#↓ {{Shotspeed}} -0.5 Shot speed down"},
	{"311", "Judas' Shadow", "{{Player12}} When dead, respawn as Dark Judas#{{Damage}} He has a 2x Damage Multiplier"},
	{"312", "Maggy's Bow", "↑ {{Heart}} +1 Health up#{{Heart}} Heals 1 Red Heart#All Red Hearts now heal double their value"},
	{"313", "Holy Mantle", "Ignore the first hit in every room"},
	{"314", "Thunder Thighs", "↑ {{Heart}} +1 Health up#↓ {{Speed}} -0.4 Speed down#Destroy rocks when walking over them"},
	{"315", "Strange Attractor", "Magnetic tears#Affects enemies, pickups and trinkets"},
	{"316", "Cursed Eye", "Charged wave of tears#!!! When hit while partially charged, teleports you to a random room#{{Collectible260}} Does not teleport if you have Black Candle"},
	{"317", "Mysterious Liquid", "Tears leave creep#Creep deals 30 damage per second"},
	{"318", "Gemini", "Close combat familiar#Deals 6 contact damage per second"},
	{"319", "Cain's Other Eye", "Bounces around the room#Shoots towards Isaac#{{Damage}} His damage equals your damage"},
	{"320", "???'s Only Friend", "Controllable Fly#Deals 5 contact damage per second"},
	{"321", "Samson's Chains", "Draggable ball that can destroy rocks#Deals 10.7 contact damage per second"},
	{"322", "Mongo Baby", "Copies the effect of one of your familiars#Deals double its damage"},
	{"323", "Isaac's Tears", "Shoot 8 tears in all directions when used#Recharges by shooting"},
	{"324", "Undefined", "Teleports you to the {{TreasureRoom}} Treasure, {{SecretRoom}} Secret, {{SuperSecretRoom}} Super Secret or I AM ERROR Room"},
	{"325", "Scissors", "Cut off your head#Head turns into stationary familiar#Control your body separately"},
	{"326", "Breath of Life", "Hold down space until chargebar is empty for invincibility#!!! Don't hold it for too long or you will start taking damage!"},
	{"327", "The Polaroid", "Invincibility when getting hit and at half a Red Heart or none"},
	{"328", "The Negative", "Damages all enemies in the room when getting hit and at half a Red Heart or none"},
	{"329", "The Ludovico Technique", "Instead of firing tears, you control one giant tear"},
	{"330", "Soy Milk", "↑ {{Tears}} Very high Tears up: (delay /4) - 2#↓ {{Damage}} -80% Damage down"},
	{"331", "Godhead", "Homing tears#↑ {{Damage}} +0.5 Damage up#↑ {{Range}} +1.2 Range up#↓ {{Tears}} -0.3 Tears down#↓ {{Shotspeed}} -0.3 Shot Speed down#↑ +0.8 Tear Height#Tears gain a damaging aura"},
	{"332", "Lazarus' Rags", "{{Player11}} When dead, revive as Lazarus (Risen)"},
	{"333", "The Mind", "Full mapping effect"},
	{"334", "The Body", "↑ {{Heart}} +3 Health up"},
	{"335", "The Soul", "{{SoulHeart}} +2 Soul Hearts#Grants an aura that repels enemies and projectiles"},
	{"336", "Dead Onion", "Piercing + spectral tears#↑ {{Range}} +0.25 Range up#↓ {{Shotspeed}} -0.4 Shot Speed down#↓ -0.5 Tear Height#↑ {{Tearsize}} +50% Tear size"},
	{"337", "Broken Watch", "Slows down or speeds up every 4th room"},
	{"338", "The Boomerang", "Throwable boomerang#Stuns enemies and deals 2x your damage on hit#Can grab items"},
	{"339", "Safety Pin", "↑ {{Range}} +5.25 Range up#↑ {{Shotspeed}} +0.16 Shot Speed up#↑ +0.5 Tear Height#{{BlackHeart}} +1 Black Heart"},
	{"340", "Caffeine Pill", "↑ {{Speed}} +0.3 Speed up#↑ Size down#{{Pill}} Spawns a random pill when picked up"},
	{"341", "Torn Photo", "↑ {{Tears}} +0.7 Tears up#↑ {{Shotspeed}} +0.16 Shot Speed up"},
	{"342", "Blue Cap", "↑ {{Heart}} +1 Health up#↑ {{Tears}} +0.7 Tears up#↓ {{Shotspeed}} -16% Shot Speed down"},
	{"343", "Latch Key", "↑ {{Luck}} +1 Luck up#{{SoulHeart}} +1 Soul Heart#{{Key}} Spawns 2 keys"},
	{"344", "Match Book", "{{BlackHeart}} +1 Black Heart#{{Bomb}} Spawns 2-3 Bomb pickups"},
	{"345", "Synthoil", "↑ {{Damage}} +1 Damage up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"346", "A Snack", "↑ {{Heart}} +1 Health up"},
	{"347", "Diplopia", "!!! SINGLE USE !!!#Duplicates any pedestals and consumables in the current room"},
	{"348", "Placebo", "{{Pill}} Copies the effect of the pill you are currently holding"},
	{"349", "Wooden Nickel", "50% chance to spawn a random coin"},
	{"350", "Toxic Shock", "{{Poison}} At the start of every room every enemy gets a poison effect#Killed enemies leave puddle of creep"},
	{"351", "Mega Bean", "Freeze all enemies in the current room#Deals 5 damage and poison any enemies nearby#Sends wave of spikes across the room#!!! Can be used to open secret rooms"},
	{"352", "Glass Cannon", "↓ Reduces your health to half a heart#Fires one large piercing spectral tear ((DMG+1) x 10)"},
	{"353", "Bomber Boy", "{{Bomb}} +5 bombs#Bombs will now explode in a cross-shaped pattern"},
	{"354", "Crack Jacks", "↑ {{Heart}} +1 Health up#{{Trinket}} Spawns random trinket on the floor"},
	{"355", "Mom's Pearls", "↑ {{Range}} +1.25 Range up#↑ {{Luck}} +1 Luck up#↑ +0.5 Tear Height"},
	{"356", "Car Battery", "Causes your active item to activate twice when used"},
	{"357", "Box of Friends", "Duplicate your familiars for the current room#If you have no familiars, {{Collectible113}}Demon Baby will spawn for the current room"},
	{"358", "The Wiz", "Fire 2 tears at once diagonally, similar to R U A WIZARD#Spectral tears"},
	{"359", "8 Inch Nails", "↑ {{Damage}} +1.5 Damage up#Increases knockback"},
	{"360", "Incubus", "Shoots the same tears as Isaac in terms of damage, stats and effects"},
	{"361", "Fate's Reward", "Familiar that fires tears with your damage and tear effects"},
	{"362", "Lil Chest", "Spawns a random pickup every few rooms"},
	{"363", "Sworn Protector", "Orbital familiar#Deals 105 contact damage per second#Blocks and attracts bullets#Blocking 10 tears in one room drops an Eternal Heart"},
	{"364", "Friend Zone", "Orbital familiar#Deals 45 contact damage per second"},
	{"365", "Lost Fly", "Moves along walls/obstacles in the room#Deals 105 contact damage per second"},
	{"366", "Scatter Bombs", "{{Bomb}} +5 bombs#Causes your bombs to explode into 2-4 tiny bombs"},
	{"367", "Sticky Bombs", "{{Bomb}} +5 bombs#When a bomb kills an enemy, it spawns blue spiders#Causes your bombs to stick to enemies"},
	{"368", "Epiphora", "Shooting in one direction gradually decreases your tear delay by up to 200%"},
	{"369", "Continuum", "↑ {{Range}} +2.25 Range up#↑ +1.5 Tear Height#Spectral tears#Tears travel through walls and appear out of the opposite wall"},
	{"370", "Mr. Dolly", "↑ {{Tears}} +0.7 Tears up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height#{{UnknownHeart}} Spawns 3 random hearts when picked up"},
	{"371", "Curse of the Tower", "Spawn 6 troll bombs every time you get hit#These are affected by bomb items"},
	{"372", "Charged Baby", "Every 30 seconds while in an uncleared room, does a random effect:#Spawn a Battery (max 2 per room)#Add one charge to your active item (max 2 per room)#Freeze all enemies in the room"},
	{"373", "Dead Eye", "↑ {{Damage}} +25% Damage up for every tear that successfully hits an enemy (max +100%)#Chance to lose the multiplier when you miss"},
	{"374", "Holy Light", "10% chance to shoot Holy tears, which will spawn a beam of light on hit#The beam deals 4x your damage#50% chance at 9 Luck"},
	{"375", "Host Hat", "Grants explosion immunity and immunity from Mom's and Satan's foot stomps#20% chance to block tears"},
	{"376", "Restock", "Spawns 3 random Pickups#Shops instantly restock their items when you buy them"},
	{"377", "Bursting Sack", "Spider enemies no longer target or deal contact damage to Isaac"},
	{"378", "No. 2", "Firing tears for 3 seconds drops a Butt Bomb"},
	{"379", "Pupula Duplex", "Tears get a much larger hitbox#Spectral tears"},
	{"380", "Pay To Play", "{{Coin}} +5 coins#You now open single-key doors with coins instead of keys"},
	{"381", "Eden's Blessing", "↑ {{Tears}} +0.7 Tears up#Gives you a random item at the start of your next run"},
	{"382", "Friendly Ball", "Can be thrown at enemies to capture them#Next usage will re-spawn the same enemy as a friendly companion"},
	{"383", "Tear Detonator", "Detonate any tears currently on the screen, causing each one to split into 6 more tears which will spread in a circle"},
	{"384", "Lil Gurdy", "{{Chargeable}} Will launch and slide around the room with speed based on charge amount#Deals 5-90 contact damage per second depending on speed"},
	{"385", "Bumbo", "Picks up nearby coins#Levels up after getting 6, 12, and 24 coins#LVL2: Chance to spawn item after room clears#LVL3: Fires tears that can drop coins on hit#LVL4: Chases enemies, occasionally dropping bombs, and can spawn item on coin pickup"},
	{"386", "D12", "Rerolls any grid object into another random type of object (e.g. poop, pots, TNT, red poop, stone blocks etc.)"},
	{"387", "Censer", "Creates a huge aura of light that slows down enemies and projectiles inside of it"},
	{"388", "Key Bum", "Converts Keys into random chests"},
	{"389", "Rune Bag", "{{Rune}} Drops a random rune every 5-6 rooms"},
	{"390", "Seraphim", "Fires Sacred Heart tears#Deals 10 damage per shot"},
	{"391", "Betrayal", "{{Charm}} Every time Isaac takes damage, every enemy in the room gets charmed"},
	{"392", "Zodiac", "Gives you a random zodiac item effect every floor"},
	{"393", "Serpent's Kiss", "{{Poison}} 15% chance to shoot poison tears#{{Poison}} Poison enemies on contact#{{BlackHeart}} Enemies that were poisoned have a chance to drop a Black Heart on death"},
	{"394", "Marked", "Fire tears automatically directed at a red target on the ground which is controlled by the player#↑ {{Tears}} +0.7 Tears up#↑ {{Range}} +3.15 Range up#↑ +0.3 Tear Height"},
	{"395", "Tech X", "{{Chargeable}} Change your tears to a chargeable laser ring that travels across the room#Larger ring size with longer charge"},
	{"396", "Ventricle Razor", "Creates up to two portals to travel between them#Can be placed in different rooms"},
	{"397", "Tractor Beam", "Your tears now travel directly in front of where you're facing, even as you move or turn#↑ {{Tears}} +0.5 Tears up#↑ {{Range}} +5.25 Range up#↑ {{Shotspeed}} +0.16 Shot Speed up#↑ +0.5 Tear Height"},
	{"398", "God's Flesh", "Tears can shrink enemies#Shrunk enemies can be crushed and killed by walking over them"},
	{"399", "Maw of the Void", "↑ {{Damage}} +1 Damage up#{{Chargeable}} After firing tears for 3 seconds, a red cross appears on Isaac's head. Upon releasing the fire button, creates a black brimstone ring#{{BlackHeart}} Enemies killed with the black ring have a chance to drop Black Hearts"},
	{"400", "Spear of Destiny", "Spawns a spear in front of you#Deals 2 times your damage#Chance to fear enemies on contact"},
	{"401", "Explosivo", "25% chance to shoot sticky bomb tears#Sticky bomb tears do not deal damage on hit"},
	{"402", "Chaos", "Pedestals will now be chosen from random item pools#Spawns 1-6 random pickups"},
	{"403", "Spider Mod", "Allows you to see your tear damage and the health bars of all enemies#Inflicts a random status effect on contact#Will randomly drop batteries"},
	{"404", "Farting Baby", "Familiar that blocks projectiles#When hit, 10% chance to fart, which will charm, poison or knockback enemies"},
	{"405", "GB Bug", "Bounces around the room#Deals 120 damage per second and applies a random status effect"},
	{"406", "D8", "Reroll your stats#Will only affect damage, tears, range and speed"},
	{"407", "Purity", "↑ Boost one of your stats depending on the color of the aura around you#When you take damage, you lose the aura for the room, and will get a new aura next room#{{ColorRed}}Red{{CR}} = {{Damage}} +4 Damage#{{ColorBlue}}Blue{{CR}} = {{Tears}} -4 Tear Delay#{{ColorYellow}}Yellow{{CR}} = {{Speed}} +0.5 Speed up#{{ColorOrange}}Orange{{CR}} = {{Range}} +7.5 Range up, +1 Tear Height"},
	{"408", "Athame", "When you take damage, a black brimstone ring will appear around Isaac#{{BlackHeart}} Enemies killed with it have a chance to drop a Black Heart"},
	{"409", "Empty Vessel", "{{BlackHeart}} +2 Black Hearts#When Isaac has no Red Hearts:#Gain flight#Every 40 seconds while in a hostile room, gain a shield for 10 seconds"},
	{"410", "Evil Eye", "3.33% chance to shoot an eye across the screen which fires tears in the same direction as Isaac"},
	{"411", "Lusty Blood", "↑ {{Damage}} +0.5 Damage up for each enemy killed in current room#Maximum of +5 Damage up after 10 kills"},
	{"412", "Cambion Conception", "After taking damage 15 times, Isaac gains a permanent demon familiar#Up to 4 familiars possible"},
	{"413", "Immaculate Conception", "After picking up 15 hearts, Isaac gains a permanent angelic familiar#Up to 5 familiars possible#A Soul Heart will spawn instead if you've gotten all 5"},
	{"414", "More Options", "{{TreasureRoom}} Two items now spawn in all Treasure Rooms#You can only choose one"},
	{"415", "Crown Of Light", "{{SoulHeart}} +2 Soul Hearts#If you don't have any damaged Red Heart containers:#↑ {{Damage}} +100% Damage up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height#↓ {{Shotspeed}} -0.3 Shot Speed down#Deactivates for the current room when damaged at all"},
	{"416", "Deep Pockets", "Allows you to carry two cards/pills/runes"},
	{"417", "Succubus", "Bounces around the room with a damaging aura, dealing 129% of your damage every second#↑ {{Damage}} +50% Damage while standing in the aura"},
	{"418", "Fruit Cake", "Gives you a different tear effect with every tear that you fire"},
	{"419", "Teleport 2.0", "Teleports you to another random room that has not been cleared yet#Hierarchy: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> Error-Room"},
	{"420", "Black Powder", "Walking in a circle will spawn a pentagram symbol on the floor, which deals 10 damage per tick"},
	{"421", "Kidney Bean", "{{Charm}} Applies charm effect to any enemies in close range and deals 5 damage to them"},
	{"422", "Glowing Hour Glass", "Rewind time and put you back in the previous room, in the same state you were in at that moment"},
	{"423", "Circle of Protection", "Large halo around you, dealing your damage on contact every second#Chance to reflect enemy projectiles"},
	{"424", "Sack Head", "Pickups have a 33% chance to be replaced with a sack#Spawns a sack"},
	{"425", "Night Light", "Spawns a cone of light in front of you that slows enemies and projectiles inside of it"},
	{"426", "Obsessed Fan", "Follows your exact movement on a 3 second delay#Deals 30 contact damage per second"},
	{"427", "Mine Crafter", "Spawns a pushable TNT barrel#If used a second time in the same room while the last TNT barrel is still there, it will remotely explode"},
	{"428", "PJs", "{{SoulHeart}} +4 Soul Hearts#Fully restores your red health"},
	{"429", "Head of the Keeper", "{{Coin}} Enemies have a 5% chance to drop a Penny when hit with your tears"},
	{"430", "Papa Fly", "Follows your movement pattern on a 1 second delay#Fires tears at nearby enemies that deal damage equal to your damage"},
	{"431", "Multidimensional Baby", "Follows your movement pattern on a 2 second delay#Tears that pass through it will split up and gain a speed boost"},
	{"432", "Glitter Bombs", "{{Bomb}} +5 bombs#Bombs have a chance to drop random pickups or charm enemies when they explode#"},
	{"433", "My Shadow", "Each time you take damage, it will apply a fear effect to all enemies and spawn a friendly black charger#The charger deals 5 damage per second"},
	{"434", "Jar of Flies", "Every time you kill an enemy a blue fly will be added to the Jar#Up to 20 flies#Using the item will release all the flies"},
	{"435", "Lil Loki", "Shoots 4 tears in a cross pattern#Deals 3.5 damage per shot"},
	{"436", "Milk!", "{{Tears}} After taking damage, you gain a Tears up for the rest of the room"},
	{"437", "D7", "Respawn all enemies of the room#Allows you to farm room clear rewards#!!! If used in a Greed fight, it can reroll the room into a Shop"},
	{"438", "Binky", "{{SoulHeart}} +1 Soul Heart#↑ {{Tears}} +0.75 Tears up#↑ Size down"},
	{"439", "Mom's Box", "{{Trinket}} Spawns a random trinket#While held, doubles the effect of trinkets#↑ {{Luck}} +1 Luck while held"},
	{"440", "Kidney Stone", "Occasionally, you stop firing and have to charge an attack that releases a burst of tears and a kidney stone#↓ -0.2 Speed down#↓ -17 Range down#↑ +2 Tear Height"},
	{"441", "Mega Blast", "Fires a huge Mega Satan laser for 15 seconds#The laser persists between rooms and floors"},
	{"442", "Dark Prince's Crown", "!!! While at 1 full Red Heart:#↑ {{Range}} +1.5 Range up#↑ {{Tears}} +0.75 Tears up#↑ {{Shotspeed}} +0.2 Shot Speed up#↑ +1 Tear Height#Does not work with characters without Red Hearts"}, -- Dark Princes Crown (apostrophe added to the name in Repentance)
	{"443", "Apple!", "Randomly fire razor blades which deal 400% damage#↑ {{Tears}} +0.3 Tears up"},
	{"444", "Lead Pencil", "Every 15 tears fired, you fire a cluster of tears#Each tear in the cluster deals double damage"},
	{"445", "Dog Tooth", "↑ {{Damage}} +0.3 Damage up#↑ {{Speed}} +0.1 Speed up#{{SecretRoom}} A wolf howls if you enter a room next to a Secret/Super Secret Room#{{LadderRoom}} A barking sound will play when entering a room with a crawlspace under a rock"},
	{"446", "Dead Tooth", "While firing, you get a green aura that poisons any enemies in it#The poison deals your damage"},
	{"447", "Linger Bean", "While firing without pause, spawns a poop cloud every 7.5 seconds#The cloud deals 3.5 damage 5 times a second#Cloud lasts 15 seconds#Can be moved by shooting it"},
	{"448", "Shard of Glass", "Upon taking damage:#{{Heart}} 25% chance to drop a Red Heart#{{Collectible214}} 10% chance to get ↑ +5 Range and leave a trail of blood creep for the current room"},
	{"449", "Metal Plate", "{{SoulHeart}} +1 Soul Heart#{{Confusion}} Enemy bullets have a 25% chance to be reflected as concussive tears"},
	{"450", "Eye of Greed", "Every 20 tears, shoot a coin tear that deals double damage#Hit enemies temporarily turn to gold#Gold enemies drop 1-4 coins if killed#!!! The coin tear costs 1 coin"},
	{"451", "Tarot Cloth", "{{Card}} Drops a random card#{{Card}} Doubles the effect of any card used"},
	{"452", "Varicose Veins", "When taking damage, fire 10 tears in a circle around you#The tears deal your damage + 25"},
	{"453", "Compound Fracture", "Bone tears#Tears shatter into 1-3 smaller bone shards upon hitting anything#↑ +1.5 Range up#↑ +1 Tear Height"},
	{"454", "Polydactyly", "You can carry two cards, runes or pills#Spawns a card, pill or rune on pickup"},
	{"455", "Dad's Lost Coin", "↑ {{Range}} +1.5 Range up#↑ +1 Tear Height#Spawns a lucky penny"},
	{"456", "Moldy Bread", "↑ {{Heart}} +1 Health up"},
	{"457", "Cone Head", "{{SoulHeart}} +1 Soul Heart#20% chance to ignore damage"},
	{"458", "Belly Button", "{{Trinket}} Spawns a random trinket on pickup#{{Trinket}} Grants 1 extra trinket slot"},
	{"459", "Sinus Infection", "20% chance to shoot sticky poison tears#Deals your damage each second#Sticks for 60 seconds"},
	{"460", "Glaucoma", "{{Confusion}} 5% chance to shoot concussive tears#Makes the screen slightly darker"},
	{"461", "Parasitoid", "15% chance to shoot egg sacks#{{Slow}} Spawns slowing creep on hit#Spawns a blue spider or fly on hit"},
	{"462", "Eye of Belial", "↑ {{Range}} +1.5 Range up#↑ +1 Tear Height#Grants piercing tears#After hitting the first enemy, the tear deals double damage and gains a homing effect"},
	{"463", "Sulfuric Acid", "↑ {{Damage}} +0.3 Damage up#Chance to destroy rocks and open doors with your tears"},
	{"464", "Glyph of Balance", "{{SoulHeart}} +2 Soul Hearts#Drops from champion enemies will be modified to be whatever pickup you need the most"},
	{"465", "Analog Stick", "↑ {{Tears}} +0.3 Tears up#Allows you to fire tears diagonally"},
	{"466", "Contagion", "{{Poison}} First killed enemy in the room will explode and poison all nearby enemies"},
	{"467", "Finger!", "{{Damage}} Deals constant 10% of your damage to enemies in the direction the finger points at"},
	{"468", "Shade", "Follows your movement delayed by 1 second#Deals 30 contact damage per second"},
	{"469", "Depression", "Leaves trail of creep#Creep deals 6 damage per second#Enemies touching the cloud can spawn a holy light beam"},
	{"470", "Hushy", "Bounces around the room#Deals contact damage#Will stop moving when you are shooting#When stopped, it can block projectiles"},
	{"471", "Lil Monstro", "{{Chargeable}} Familiar with chargeable shotgun attack similar to {{Collectible229}} Monstro's Lung#Each tear deals 3.5 damage"},
	{"472", "King Baby", "Other familiars follow it#Stops moving when you are shooting#Will move back to you when you stop shooting"},
	{"473", "Big Chubby", "Charges forwards very slow#Deals 40.5 contact damage per second"},
	{"474", "Tonsil", "Blocks enemy projectiles"},
	{"475", "Plan C", "!!! SINGLE USE !!!#Deals 9,999,999 damage to all enemies and kills you 3 seconds later"},
	{"476", "D1", "Duplicates 1 random pickup in the current room"},
	{"477", "Void", "!!! When used, consumes all pedestal items in the room#Active item: Its effect activates, and will activate every future use of Void#↑ Passive item: Small stat upgrade to two random stats"},
	{"478", "Pause", "Freezes all enemies in the room until you start shooting again#Touching a frozen enemy will still hurt you#Enemies unfreeze after 30 seconds"},
	{"479", "Smelter", "{{Trinket}} Consumes your trinket and gives you the effect permanently#More trinkets appear"},
	{"480", "Compost", "Converts pickups into blue flies or spiders#Doubles your current blue flies/spiders#Spawns 1 blue fly or spider when you don't have any"},
	{"481", "Dataminer", "When used, ↑/↓ small amount on random stat#Random tear effect for current room#Corrupts all sprites and music for current room"},
	{"482", "Clicker", "Transforms you into a different character#Removes the last item you collected"},
	{"483", "Mama Mega!", "!!! SINGLE USE !!!#Affects whole floor#Explodes all objects#Deals 200 damage to all enemies#Opens the door to Boss Rush, Hush and all secret rooms#!!! If you have a Golden Bomb, consumes it on use instead of Mama Mega"},
	{"484", "Wait What?", "Upon use, pushes enemies away and spawn a wave of rocks#Can open rooms and break rocks"},
	{"485", "Crooked Penny", "50% chance to double all items, consumables and chests in room#50% chance to remove items / pickups in room and spawn 1 coin"},
	{"486", "Dull Razor", "Hurts you without damaging you#Can trigger item effects"},
	{"487", "Potato Peeler", "Removes one Red Heart Container and gives you: #↑ {{Damage}} +0.2 Damage#{{Collectible73}} A Cube of Meat"},
	{"488", "Metronome", "Grants a random item's effect for the current room"},
	{"489", "D Infinity", "Random dice effect each use"},
	{"490", "Eden's Soul", "!!! SINGLE USE !!!#Spawns 2 random items depending on the current room's item pool#Starts with no charges"},
	{"491", "Acid Baby", "{{Pill}} Drops a random pill every 3 rooms#{{Poison}} Using a pill poisons all enemies in the room"},
	{"492", "YO LISTEN!", "↑ {{Luck}} +1 Luck up#Highlights the location of {{SecretRoom}} secret rooms, tinted rocks and crawlspaces"},
	{"493", "Adrenaline", "For every empty heart container:#↑ +0.2 Damage up"},
	{"494", "Jacob's Ladder", "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half your damage"},
	{"495", "Ghost Pepper", "Chance to shoot a red flame that blocks enemy shots and deals contact damage#The flame stays until it has dealt damage or blocked shots 5 times"},
	{"496", "Euthanasia", "3.33% chance to shoot needles#100% chance at 15 Luck#Needles kill normal enemies instantly, bursting them into 10 tears#Needles deal 3x damage against bosses"},
	{"497", "Camo Undies", "When you enter a room, camouflage yourself and confuse all enemies until you start shooting"},
	{"498", "Duality", "{{AngelDevilChance}} If an Angel or Devil room would spawn, both will spawn#When entering one, the other disappears"},
	{"499", "Eucharist", "{{AngelChance}} 100% chance to find an {{AngelRoom}}Angel Room"},
	{"500", "Sack of Sacks", "Spawns a sack every 5-6 rooms"},
	{"501", "Greed's Gullet", "Gain 1 Heart Container for every 25 coins you gain after picking up Greed's Gullet#{{Player14}} Keeper can gain additional Coin Hearts"},
	{"502", "Large Zit", "While firing, occasionally shoot a white creep tear that deals double damage#Shoot a white creep tear when damaged"},
	{"503", "Little Horn", "5% chance to shoot tears that instantly kill enemies#Running into enemies will deal 3.5 damage to them"},
	{"504", "Brown Nugget", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
	{"505", "Poke Go", "Chance to spawn a charmed enemy when entering a hostile room"},
	{"506", "Backstabber", "If tears hit an enemy in the back, they do double damage and cause bleeding, which deals 10% damage of the enemy's max health every 5 seconds"},
	{"507", "Sharp Straw", "{{Damage}} Deals your damage + 10% of the enemy's max health#Affects all enemies in the room#{{HalfHeart}} Chance to drop half hearts when it deals damage#{{HalfSoulHeart}} Can drop half Soul Hearts instead if you don't have red HP"},
	{"508", "Mom's Razor", "Orbital that causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds#Deals 300% your damage on contact per second#Does not block shots"},
	{"509", "Bloodshot Eye", "Orbital that shoots a tear every 2 seconds in a random direction#Deals 3.5 damage per tear#Deals 30 contact damage per second#Does not block shots"},
	{"510", "Delirious", "Spawns a friendly white delirium version of a boss for the current room"},
	{"511", "Angry Fly", "Orbits around a random enemy until that enemy dies#Deals 30 contact damage per second to other enemies"},
	{"512", "Black Hole", "Throwable black hole, which sucks in everything#Deals 0.4 damage every tick#Destroys nearby rocks#Lasts 6 seconds"},
	{"513", "Bozo", "↑ +0.1 Damage up#+1 Soul Heart#Random chance to charm/fear an enemy#Random chance to spawn a rainbow poop upon taking damage"},
	{"514", "Broken Modem", "Causes random enemies and projectiles to 'lag' at random intervals, causing them to shortly freeze#25% chance to double room clear drops"},
	{"515", "Mystery Gift", "!!! SINGLE USE !!!#Spawns a random item from the current room's item pool#Chance to spawn Lump of Coal or The Poop instead"},
	{"516", "Sprinkler", "Spawns a Sprinkler that rotates in a circle, spraying your tears in all directions"},
	{"517", "Fast Bombs", "{{Bomb}} +7 Bombs#Allows you to rapidly place bombs on the ground"},
	{"518", "Buddy in a Box", "Familiar which looks like a random coop Baby#Has a random tear effect#Will be randomized every floor"},
	{"519", "Lil Delirium", "A familiar that transforms into other random familiars every 10 seconds"},
	{"520", "Jumper Cables", "+1 charge for your active item for every 15 enemies killed"},
	{"521", "Coupon", "When used, causes one random item in the {{Shop}} Shop or {{DevilRoom}} Devil Room to become free#{{Shop}} While held, guarantees one Shop item will be on sale"},
	{"522", "Telekinesis", "Enemy projectiles close to you are held in place for 3 seconds#They get thrown away from you afterwards#Recharges after 3 seconds"},
	{"523", "Moving Box", "When used, stores all pickups from the current room#Using it again will put them back on the floor again#This allows you to move things between rooms"},
	{"524", "Technology Zero", "Tears will be connected with beams of electricity#Electricity damage equals your damage"},
	{"525", "Leprosy", "Taking damage will spawn a projectile blocking orbital#Max 3 orbitals at the same time#Orbitals are destroyed if they take too much damage"},
	{"526", "7 Seals", "Spawns small horsemen familiars that spawn their respective locusts#Horseman changes every 10 seconds"},
	{"527", "Mr. ME!", "!!! Usable familiar that can do tasks for you:#Open doors or chests#Fetch an item#50% chance to steal from the shop / Devil#Attack an enemy until it dies#Explode walls, rocks, shopkeepers, angel statues, machines, beggars"},
	{"528", "Angelic Prism", "Orbital prism#Tears hitting it will split into 4"},
	{"529", "Pop!", "Tears will behave like billiard balls"},
	{"530", "Death's List", "Grants a pickup or stat increase if you kill enemies in the order they are marked in"},
	{"531", "Haemolacria", "Tears fly in an arc#Tears burst into smaller tears on impact#↓ Tears down#↑ 31% Damage up"},
	{"532", "Lachryphagy", "Tears slow down while traveling#Upon stopping, they explode in 8 smaller tears#Tears can be fired in other tears, making them bigger"},
	{"533", "Trisagion", "Fire piercing blasts of light#{{Damage}} They deal 33% damage but can hit enemies multiple times"},
	{"534", "Schoolbag", "Allows holding 2 active items#Switch between them with the Drop button ({{ButtonRT}})"},
	{"535", "Blanket", "{{SoulHeart}} +1 Soul Heart#{{Heart}} Heals 1 Red Heart#{{Collectible313}} Grants a shield when entering a boss room"},
	{"536", "Sacrificial Altar", "!!! SINGLE USE !!!#Sacrifice 1-2 familiars to spawn a Devil item#Turns your blue spiders/flies into coins"},
	{"537", "Lil Spewer", "{{Pill}} Spawns a random pill on pickup#Familiar that fires a line of creep#Creep type changes everytime the player uses a pill"},
	{"538", "Marbles", "{{Trinket}} Spawns 3 random trinkets#{{Collectible479}} Taking damage can add the effect of your trinket permanently"},
	{"539", "Mystery Egg", "Spawn a charmed enemy when you get hit#Spawns stronger friends the more rooms are cleared without taking damage"},
	{"540", "Flat Stone", "Tears bounce off the floor#Tears cause splash damage on every bounce"},
	{"541", "Marrow", "{{EmptyBoneHeart}} +1 Bone Heart#{{Heart}} Spawns 3 Red Hearts"},
	{"542", "Slipped Rib", "Orbital#Reflects projectiles"},
	{"543", "Hallowed Ground", "Spawn white poop when you get hit#While inside the poop's aura:#↑ {{Tears}} -50% Tear Delay#Chance to block damage"},
	{"544", "Pointy Rib", "Nail that levitates in front of Isaac#Deals your damage 6 times per second"},
	{"545", "Book of the Dead", "Spawns a bone orbital or charmed bony per enemy killed in the current room"},
	{"546", "Dad's Ring", "Grants an aura that freezes enemies in place"},
	{"547", "Divorce Papers", "{{EmptyBoneHeart}} +1 Bone Heart#↑ {{Tears}} +0.7 Tears up#{{Trinket21}} Spawns a Mysterious Paper trinket"},
	{"548", "Jaw Bone", "Boomerang-like familiar#Deals 7 contact damage#Can retrieve pickups"},
	{"549", "Brittle Bones", "{{EmptyBoneHeart}} Replaces all your Red Heart containers with 6 empty Bone Hearts#Upon losing a Bone Heart:#Fires 8 bone tears in all directions#↑ {{Tears}} +0.5 Tears up permanently"},
	{"550", "Broken Shovel", "Mom's Foot will constantly attack you#Using it stops Mom's Foot for current room#!!! (Try to beat Boss Rush with it!)"},
	{"551", "Broken Shovel", "Second part of a broken shovel#!!! Use the shovel on the hill of dirt in the \"Dark Room\""},
	{"552", "Mom's Shovel", "Spawns a trapdoor to the next floor#10% chance for {{LadderRoom}}crawlspace trapdoor#!!! Use the shovel on the hill of dirt in the \"Dark Room\"#!!! Unlocks something cool"},
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "Swallowed Penny", "{{Coin}} Spawns 1 coin when you get hit"},
	{"2", "Petrified Poop", "50% chance to get drops from poop"},
	{"3", "AAA Battery", "-1 charge needed for active items"},
	{"4", "Broken Remote", "Teleports you when you use an active item"},
	{"5", "Purple Heart", "2x chance for champion enemies"},
	{"6", "Broken Magnet", "Coin magnet"},
	{"7", "Rosary Bead", "{{AngelChance}} 50% higher Angel Room chance#{{Collectible33}} Higher chance to find The Bible in {{Shop}} Shops and {{Library}} Libraries"},
	{"8", "Cartridge", "{{Collectible93}} 5% chance for Gamekid effect on hit"},
	{"9", "Pulse Worm", "Pulsating tears#Affects tear hitbox"},
	{"10", "Wiggle Worm", "Tears move in waves#↑ {{Tears}} +0.3 Tears up"},
	{"11", "Ring Worm", "Tears move in spirals with high speed"},
	{"12", "Flat Worm", "50% wider tears#Increases knockback"},
	{"13", "Store Credit", "{{Shop}} One shop item for free"},
	{"14", "Callus", "Prevents damage from creep and spikes"},
	{"15", "Lucky Rock", "{{Coin}} Destroying rocks spawns coins"},
	{"16", "Mom's Toenail", "Mom's Foot stomps enemies every 60 seconds"},
	{"17", "Black Lipstick", "{{BlackHeart}} +1% chance for Black Hearts"}, -- base chance is 0.5%
	{"18", "Bible Tract", "{{EternalHeart}} +3% chance for Eternal Hearts"}, -- base chance is 1.667%
	{"19", "Paper Clip", "Unlock chests without using keys"},
	{"20", "Monkey Paw", "{{BlackHeart}} When on half a heart, spawns 1 Black Heart#!!! 3 time usage"},
	{"21", "Mysterious Paper", "Randomly imitates: #{{Collectible327}} The Polaroid#{{Collectible328}} The Negative#{{Trinket48}} A Missing Page#{{Trinket23}} Missing Poster"},
	{"22", "Daemon's Tail", "{{Heart}} Decreases spawn rate of hearts to 20%#{{BlackHeart}} Heart pickups turn into Black Hearts#{{Key}} Key drop chance increased"},
	{"23", "Missing Poster", "{{Player10}} Respawn as The Lost on death#If he isn't unlocked, die in a {{SacrificeRoom}} Sacrifice Room while holding this trinket to unlock him"},
	{"24", "Butt Penny", "{{Coin}} 20% higher chance for coins to spawn from poop#Fart when picking up coins#The fart only knocks back enemies"},
	{"25", "Mysterious Candy", "Fart or spawn poop every 30 seconds"},
	{"26", "Hook Worm", "Tears move in angular patterns#↑ {{Range}} +10 Range"},
	{"27", "Whip Worm", "↑ {{Shotspeed}} +0.5 Shot Speed up"},
	{"28", "Broken Ankh", "{{Player4}} 22% chance to respawn as ??? (Blue Baby) on death"},
	{"29", "Fish Head", "Spawn 1 blue fly when getting hit"},
	{"30", "Pinky Eye", "{{Poison}} 10% chance to shoot poison tears"},
	{"31", "Push Pin", "10% chance to shoot piercing spectral tears"},
	{"32", "Liberty Cap", "25% chance for a random mushroom effect per room#Can reveal special rooms on the minimap"},
	{"33", "Umbilical Cord", "When damaged to half a Red Heart, you gain: #{{Collectible100}} Little Steven for the current room"},
	{"34", "Child's Heart", "{{Heart}} 10% chance for the room clear reward to be a random heart#Chance for a bonus heart from chests, tinted rocks and destroyed machines"},
	{"35", "Curved Horn", "↑ {{Damage}} +2 Damage up"},
	{"36", "Rusted Key", "{{Key}} 10% chance for the room clear reward to be a key#{{Key}} Chance for a bonus key from chests, tinted rocks and destroyed machines"},
	{"37", "Goat Hoof", "↑ {{Speed}} +0.15 Speed up"},
	{"38", "Mom's Pearl", "+10% chance for random heart drops to be:#{{SoulHeart}} Soul Heart#{{BlackHeart}} Black Heart or#{{EmptyBoneHeart}} Bone Heart"}, -- base chance is 10%
	{"39", "Cancer", "↑ {{Tears}} -2 Tear Delay"},
	{"40", "Red Patch", "{{Damage}} 20% chance to get +1.8 Damage up when getting hit#{{Luck}} 100% chance at 8 Luck#Effect lasts for current room"},
	{"41", "Match Stick", "{{Bomb}} 10% chance for the room clear reward to be a bomb#{{Bomb}} Chance for a bonus bomb from chests, tinted rocks and destroyed machines#!!! Removes {{Trinket53}}Tick"},
	{"42", "Lucky Toe", "↑ {{Luck}} +1 Luck up#+8% room clear reward chance#Extra pickups from chests, tinted rocks, and destroyed machines"},
	{"43", "Cursed Skull", "When damaged down to half a heart or less, teleport to a random room"},
	{"44", "Safety Cap", "{{Pill}} 10% chance for the room clear reward to be a pill#{{Pill}} Chance for a bonus pill from chests, tinted rocks and destroyed machines"},
	{"45", "Ace of Spades", "{{Card}} 10% chance for the room clear reward to be a card#{{Card}} Chance for a bonus card from chests, tinted rocks and destroyed machines"},
	{"46", "Isaac's Fork", "{{HalfHeart}} 10% chance for healing half a heart after clearing a room"},
	{"47", "", "<Item does not exist>"},
	{"48", "A Missing Page", "When hit, 5% chance to deal 40 damage to all enemies in the room"},
	{"49", "Bloody Penny", "{{HalfHeart}} 50% chance to drop half a heart when picking up coins"},
	{"50", "Burnt Penny", "{{Bomb}} 50% chance to drop a bomb when picking up coins"},
	{"51", "Flat Penny", "{{Key}} 50% chance to drop a key when picking up coins"},
	{"52", "Counterfeit Penny", "{{Coin}} 50% chance to get +1 coin when picking up coins"},
	{"53", "Tick", "-15% boss health#{{BossRoom}} Heals 1 Red Heart when entering a Boss Room#!!! Once picked up, it can't be removed#Only removeable with {{Trinket41}} Match Stick or gulping"},
	{"54", "Isaac's Head", "Familiar with piercing tears#Deals 3.5 damage per tear"},
	{"55", "Maggy's Faith", "{{EternalHeart}} Get 1 Eternal Heart at the start of every floor"},
	{"56", "Judas' Tongue", "{{DevilRoom}} Reduces Devil deal prices from 2 heart containers to 1"},
	{"57", "???'s Soul", "Familiar that bounces around the room#Shoots in the same direction as the player#Deals 3.5 damage per tear"},
	{"58", "Samson's Lock", "{{Damage}} 1/15 chance for +0.5 Damage up when killing an enemy#{{Luck}} 100% chance at 10 Luck#Effect lasts for current room"},
	{"59", "Cain's Eye", "25% chance to reveal map icons at start of new floor#100% chance at 3 Luck"},
	{"60", "Eve's Bird Foot", "{{Collectible117}} 5% chance to spawn a Dead Bird when killing an enemy#{{Luck}} 100% chance at 8 Luck"},
	{"61", "The Left Hand", "Turns all chests into red chests"},
	{"62", "Shiny Rock", "Crawlspace rocks and tinted rocks blink every 10 seconds"},
	{"63", "Safety Scissors", "Turns troll bombs into bomb pickups"},
	{"64", "Rainbow Worm", "Random worm effect every 3 seconds"},
	{"65", "Tape Worm", "↑ {{Range}} Doubles your Range#-50% Tear Height"},
	{"66", "Lazy Worm", "↓ {{Shotspeed}} -0.4 Shot Speed down#↑ {{Range}} +4 Range up#↑ +2 Tear Height"},
	{"67", "Cracked Dice", "When getting hit, 50% chance to use the:#{{Collectible105}} D6#{{Collectible406}} D8#{{Collectible386}} D12 or #{{Collectible166}} D20"},
	{"68", "Super Magnet", "Magnet for pickups and enemies"},
	{"69", "Faded Polaroid", "Camouflages the player randomly#Confuses enemies"},
	{"70", "Louse", "Chance to spawn 1 spider while in a hostile room"},
	{"71", "Bob's Bladder", "Bombs leave creep"},
	{"72", "Watch Battery", "6.66% chance for the room clear reward to be a battery#+10% chance for random pickups to be a battery#5% chance to add 1 charge to held active item when clearing a room"},
	{"73", "Blasting Cap", "10% chance for exploding bombs to drop a bomb pickup"},
	{"74", "Stud Finder", "0.5% chance to reveal a {{LadderRoom}} crawlspace when breaking rocks"},
	{"75", "Error", "Random trinket effect every room"},
	{"76", "Poker Chip", "Chests have a 50/50 chance to spawn extra pickups OR an enemy fly"},
	{"77", "Blister", "Increases knockback"},
	{"78", "Second Hand", "2x longer status effects on enemies"},
	{"79", "Endless Nameless", "25% chance when using pills/cards to drop a copy of the pill/card"},
	{"80", "Black Feather", "↑ {{Damage}} +0.2 Damage up for each \"Evil up\" item held"},
	{"81", "Blind Rage", "Invincibility lasts 2x longer after getting hit"},
	{"82", "Golden Horse Shoe", "{{TreasureRoom}} +15% chance for Treasure Rooms to have two items on future floors#You can only choose one"},
	{"83", "Store Key", "{{Shop}} Open Shops for free"},
	{"84", "Rib of Greed", "5% more coins and less hearts from room clear rewards#Greed and Super Greed no longer appear in {{Shop}}Shops or {{SecretRoom}}Secret Rooms"},
	{"85", "Karma", "{{DonationMachine}} Using a Donation Machine can:#{{Heart}} Heal 1 heart#{{Coin}} Give 1 coin#{{Luck}} Grant +1 Luck up#{{Beggar}} Spawn a Beggar"},
	{"86", "Lil Larva", "Destroying poop spawns 1 blue fly"},
	{"87", "Mom's Locket", "Heal half a heart when using keys#Turns half hearts into full hearts"},
	{"88", "NO!", "Prevents active items from spawning"},
	{"89", "Child Leash", "Familiars stay closer to you"},
	{"90", "Brown Cap", "Poop explodes for 100 damage when destroyed"},
	{"91", "Meconium", "33% chance for Black Poops to spawn#5% chance to spawn a Black Heart when Black Poop is destroyed"},
	{"92", "Cracked Crown", "↑ Stat increases of your items are 33% more effective#↑ +0.2 Tears up#↑ -1 Tear Delay"},
	{"93", "Used Diaper", "15% chance per room for all Fly enemies to become friendly"},
	{"94", "Fish Tail", "Doubles all Blue Fly / Spider spawns"},
	{"95", "Black Tooth", "3% chance to shoot poison tooth tears"},
	{"96", "Ouroboros Worm", "Tears move quickly in a spiral pattern#Spectral tears#↑ {{Range}} +4 Range up#↑ +2 Tear Height"},
	{"97", "Tonsil", "Get a projectile blocking familiar after taking damage 12-20 times#Up to +2 Familiars possible"},
	{"98", "Nose Goblin", "10% chance to shoot homing sticky poison tears#Deals your damage each second#Sticks for 60 seconds"},
	{"99", "Super Ball", "10% chance to shoot bouncy tears"},
	{"100", "Vibrant Bulb", "!!! While holding a fully charged active item:#↑ {{Damage}} +0.5 Damage#↑ {{Speed}} +0.25 Speed#↑ {{Range}} +0.75 Range#↑ {{Tears}} +0.2 Tears#↑ {{Shotspeed}} +0.1 Shot speed#↑ {{Luck}} +1 Luck"},
	{"101", "Dim Bulb", "!!! While holding a completely uncharged active item:#↑ {{Damage}} +1.5 Damage#↑ {{Speed}} +0.5 Speed#↑ {{Range}} +1.5 Range#↑ {{Tears}} +0.4 Tears#↑ {{Shotspeed}} +0.3 Shot Speed#↑ {{Luck}} +2 Luck"},
	{"102", "Fragmented Card", "{{SecretRoom}} +1 extra Secret Room per floor while held"},
	{"103", "Equality!", "!!! When coin, key and bomb count are equal:#Turns single consumables into double consumables"},
	{"104", "Wish Bone", "2% chance to spawn a pedestal item when hit#Gets destroyed afterwards"},
	{"105", "Bag Lunch", "{{Collectible22}} 2% chance to spawn Lunch when hit#Gets destroyed afterwards"},
	{"106", "Lost Cork", "Increases the radius of any creep you produce"},
	{"107", "Crow Heart", "Damage taken will ignore Soul/Black Hearts, causing your Red Heart containers to be depleted first"},
	{"108", "Walnut", "Drops a key, coin, heart, and random trinket after getting hit by 1-9 explosions#Taking damage isn't required#Gets destroyed afterwards"},
	{"109", "Duct Tape", "Causes any familiar you have to stop moving"},
	{"110", "Silver Dollar", "{{Shop}} Shops now appear in the Womb"},
	{"111", "Bloody Crown", "{{TreasureRoom}} Treasure Rooms now appear in the Womb"},
	{"112", "Pay To Win", "{{RestockMachine}} Restock boxes will always spawn in {{TreasureRoom}} Treasure Rooms"},
	{"113", "Locust of War", "Spawn an exploding attack fly when entering a hostile room#The fly deals double your damage + explosion damage"},
	{"114", "Locust of Pestilence", "Spawn a poison attack fly when entering a hostile room#The fly deals double your damage"},
	{"115", "Locust of Famine", "Spawn a slowing attack fly when entering a hostile room#The fly deals double your damage"},
	{"116", "Locust of Death", "Spawn an attack fly when entering a hostile room#The fly deals 4 times your damage"},
	{"117", "Locust of Conquest", "Spawns 1-4 attack flies when entering a hostile room#Each fly deals double your damage"},
	{"118", "Bat Wing", "5% chance to gain flight after killing an enemy#Persists for the current room"},
	{"119", "Stem Cell", "Heals half a heart upon traveling to the next floor"},
	{"120", "Hairpin", "Fully recharges your active item at the start of a boss fight"},
	{"121", "Wooden Cross", "{{Collectible313}} Protects you from the first damage you take for every floor"},
	{"122", "Butter!", "Using your active item will drop it back on a pedestal on the ground#When taking damage, 2% chance to drop one of your passive items"},
	{"123", "Filigree Feather", "Causes the Angel bosses to drop normal items instead of Key Pieces"},
	{"124", "Door Stop", "The last door you used stays open"},
	{"125", "Extension Cord", "Connects your familiars with beams of electricity#Deals 6 damage per beam"},
	{"126", "Rotten Penny", "Spawns a blue fly when picking up a coin"},
	{"127", "Baby-Bender", "Grants your familiars homing shots"},
	{"128", "Finger Bone", "{{EmptyBoneHeart}} 2% chance to gain a Bone Heart when taking damage"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "0 - The Fool", "Teleports you back to the start"},
	{"2", "I - The Magician", "Homing tears for current room"},
	{"3", "II - The High Priestess", "Mom's Foot stomps on an enemy!"},
	{"4", "III - The Empress", "For current room grants: #↑ {{Damage}} +2.35 Damage up#↑ {{Speed}} +0.3 Speed up"},
	{"5", "IV - The Emperor", "{{BossRoom}} Teleports you to the Boss Room"},
	{"6", "V - The Hierophant", "{{SoulHeart}} Drops 2 Soul Hearts"},
	{"7", "VI - The Lovers", "{{Heart}} Drops 2 Red Hearts"},
	{"8", "VII - The Chariot", "Invincibility + contact damage for 6 seconds"},
	{"9", "VIII - Justice", "Spawns 1 bomb, 1 key, 1 coin, 1 heart"},
	{"10", "IX - The Hermit", "{{Shop}} Teleports you to the Shop"},
	{"11", "X - Wheel of Fortune", "Spawns a {{Slotmachine}} Slot or {{FortuneTeller}} Fortune Machine"},
	{"12", "XI - Strength", "For current room grants: #↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.3 Damage up#↑ {{Damage}} +50% Damage#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height#↑ {{Speed}} +0.3 Speed up"},
	{"13", "XII - The Hanged Man", "Grants flight for current room"},
	{"14", "XIII - Death", "Deals 40 damage to all enemies in the room"},
	{"15", "XIV - Temperance", "{{DonationMachine}} Spawns a Blood Donation Machine#{{GreedMode}} Spawns a Devil Beggar in Greed Mode"},
	{"16", "XV - The Devil", "↑ {{Damage}} +2 Damage up for current room"},
	{"17", "XVI - The Tower", "Spawns 6 troll bombs"},
	{"18", "XVII - The Stars", "{{TreasureRoom}} Teleports you to the Treasure Room"},
	{"19", "XVIII - The Moon", "{{SecretRoom}} Teleports you to the Secret Room"},
	{"20", "XIX - The Sun", "Deals 100 damage to all enemies#Full health#Reveals entire map"},
	{"21", "XX - Judgement", "Spawns a Beggar or Devil Beggar"},
	{"22", "XXI - The World", "Reveals the entire map and shows all room types"},
	{"23", "2 of Clubs", "{{Bomb}} Duplicate your bombs"},
	{"24", "2 of Diamonds", "{{Coin}} Duplicate your money"},
	{"25", "2 of Spades", "{{Key}} Duplicate your keys"},
	{"26", "2 of Hearts", "{{Heart}} Duplicate your Red Hearts#Only has a healing effect"},
	{"27", "Ace of Clubs", "{{Bomb}} Turns all pickups into bombs"},
	{"28", "Ace of Diamonds", "{{Coin}} Turns all pickups into coins"},
	{"29", "Ace of Spades", "{{Key}} Turns all pickups into keys"},
	{"30", "Ace of Hearts", "{{Heart}} Turns all pickups into hearts"},
	{"31", "Joker", "{{AngelDevilChance}} Teleports you to the Devil or Angel Room"},
	{"32", "Hagalaz", "Destroy all rocks in the room"},
	{"33", "Jera", "Duplicate all pickups in room"},
	{"34", "Ehwaz", "Spawns a trapdoor to the next floor#8% chance for {{LadderRoom}}crawlspace trapdoor"},
	{"35", "Dagaz", "{{SoulHeart}} +1 Soul Heart#{{CurseCursed}} Removes curse effects"},
	{"36", "Ansuz", "Full mapping for this floor"},
	{"37", "Perthro", "Reroll all pedestal items"},
	{"38", "Berkano", "Summons 3 blue spiders and 3 blue flies"},
	{"39", "Algiz", "Invincibility for 30 seconds"},
	{"40", "Blank Rune", "Random rune effect#25% chance to drop itself again"},
	{"41", "Black Rune", "Deals 40 damage to all enemies#Converts all pedestal items in the room into random stat ups#Converts all pickups in the room into blue flies"},
	{"42", "Chaos Card", "Throwable instant kill-card"},
	{"43", "Credit Card", "Removes the price from all items in the current {{Shop}} shop or {{DevilRoom}} Devil deal, making everything free"},
	{"44", "Rules Card", "Displays \"helpful\" tips on use"},
	{"45", "A Card Against Humanity", "Fills the whole room with poop"},
	{"46", "Suicide King", "Instantly kills you and spawns 10 pickup / Collectibles on the floor"},
	{"47", "Get Out Of Jail Free Card", "Open all doors in the current room"},
	{"48", "? Card", "Activates your active item for free"},
	{"49", "Dice Shard", "Rerolls pedestals and pickups in current room"},
	{"50", "Emergency Contact", "Two of Mom's Hands come down and grab an enemy"},
	{"51", "Holy Card", "{{Collectible313}} Grants the Holy Mantle effect for one room#(Prevents damage once)#25% chance to spawn another Holy Card"},
	{"52", "Huge Growth", "↑ {{Damage}} +7 Damage up#↑ {{Range}} +30 Range up#Destroy rocks when walking over them#Size up#Effect lasts for current room"},
	{"53", "Ancient Recall", "{{Card}} Spawns 3 random cards when used"},
	{"54", "Era Walk", "{{Slow}} Slow down enemies#↑ {{Speed}} +0.5 Speed up#↓ {{Shotspeed}} -1 Shot Speed down#Effect lasts for current room"},
}

---------- Pills ----------
EID.descriptions[languageCode].unidentifiedPill = "Unidentified Pill"

EID.descriptions[languageCode].pills={
	{"0", "Bad Gas", "Spawns a gas cloud"},
	{"1", "Bad Trip", "Deals 1 heart of damage to you#Becomes a Full Health pill if you have 1 heart or less"},
	{"2", "Balls of Steel", "{{SoulHeart}} +2 Soul Hearts"},
	{"3", "Bombs are Key", "Switches number of bombs with keys"},
	{"4", "Explosive Diarrhea", "Spawns 5 bombs over a period of five seconds at your position"},
	{"5", "Full Health", "Full health"},
	{"6", "Health Down", "↓ {{Heart}} Health down#Becomes a Health Up pill if you have 0 or 1 Heart Containers"},
	{"7", "Health Up", "↑ {{EmptyHeart}} +1 Empty heart container"},
	{"8", "I Found Pills", "No effect"},
	{"9", "Puberty", "No effect#Eating 3 will give you the Adult transformation (+1 Red Heart)"},
	{"10", "Pretty Fly", "Adds 1 fly orbital"},
	{"11", "Range Down", "↓ {{Range}} -2 Range down"},
	{"12", "Range Up", "↑ {{Range}} +2.5 Range up"},
	{"13", "Speed Down", "↓ {{Speed}} -0.12 Speed down"},
	{"14", "Speed Up", "↑ {{Speed}} +0.15 Speed up"},
	{"15", "Tears Down", "↓ {{Tears}} -0.28 Tears down"},
	{"16", "Tears Up", "↑ {{Tears}} +0.35 Tears up"},
	{"17", "Luck Down", "↓ {{Luck}} -1 Luck down"},
	{"18", "Luck Up", "↑ {{Luck}} +1 Luck up"},
	{"19", "Telepills", "Teleports you to a random room#Small chance to teleport you to the I AM ERROR room"},
	{"20", "48 Hour Energy!", "Fully recharges your active item#Drops 1-2 batteries"},
	{"21", "Hematemesis", "Drains all but one heart container#Spawns 1-4 Red Hearts"},
	{"22", "Paralysis", "You can't move for 2 seconds"},
	{"23", "I can see forever!", "{{SecretRoom}} Opens secret room entrances on current floor"},
	{"24", "Pheromones", "{{Charm}} Charms all enemies in the room"},
	{"25", "Amnesia", "{{CurseLost}} Hides the floor map"},
	{"26", "Lemon Party", "Spawns a large puddle on the ground which damages enemies"},
	{"27", "R U A Wizard?", "Shoot diagonally for 30 seconds"},
	{"28", "Percs!", "Take only half the damage for current room"},
	{"29", "Addicted!", "Take full heart damage for current room"},
	{"30", "Re-Lax", "Spawn poop while walking for 2 seconds"},
	{"31", "???", "{{CurseMaze}} Curse of the Maze effect for current floor"},
	{"32", "One makes you larger", "You grow bigger#Doesn't affect your hitbox"},
	{"33", "One makes you small", "You get smaller#Your hitbox gets smaller"},
	{"34", "Infested!", "Spawn 1 blue spider per poop in room"},
	{"35", "Infested?", "Spawn 1 blue spider per enemy in room#Spawns 1-3 blue spiders when no enemy is in the room"},
	{"36", "Power Pill!", "Short invincibility effect"},
	{"37", "Retro Vision", "Pixelates the screen for 30 seconds"},
	{"38", "Friends Till The End!", "Spawns 3 blue flies"},
	{"39", "X-Lax", "Spawn pool of slippery creep"},
	{"40", "Something's wrong...", "{{Slow}} Spawn pool of slowing creep"},
	{"41", "I'm Drowsy...", "{{Slow}} Slow all enemies in room"},
	{"42", "I'm Excited!!!", "Speed up for all enemies in room"},
	{"43", "Gulp!", "{{Trinket}} Consume current trinket and gain its effect permanently"},
	{"44", "Horf!", "{{Collectible149}} Shoots one Ipecac tear"},
	{"45", "Feels like I'm walking on sunshine!", "Short invincibility effect"},
	{"46", "Vurp!", "Spawns last used pill"},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Next Sacrifice Room payout]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "{{Coin}} 50% chance for 1 coin#{{Bomb}} 100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
	{"2", "", "{{Coin}} 50% chance for 1 coin#{{Bomb}} 100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
	{"3", "", "{{AngelChance}} 67% chance for increased Angel Room chance"},
	{"4", "", "{{Chest}} 50% chance for 1 random chest"},
	{"5", "", "{{Coin}} 33% chance for 3 coins#{{AngelChance}} 67% chance for increased Angel Room chance"},
	{"6", "", "{{AngelRoom}} 33% chance for a teleport to the Angel Room#{{DevilRoom}} Teleports to the Devil Room instead if its door was spawned on the current floor#{{Chest}} 67% chance for random chest"},
	{"7", "", "{{AngelRoom}} 33% chance for 1 random Angel Room item#{{SoulHeart}} 67% chance for 1 Soul Heart"},
	{"8", "", "100% chance for 7 troll bombs"},
	{"9", "", "100% chance to spawn \"Uriel\""},
	{"10", "", "{{SoulHeart}} 50% chance for 7 Soul Hearts#{{Coin}} 50% chance for 30 coins"},
	{"11", "", "100% chance to spawn \"Gabriel\""},
	{"12", "", "50% chance to teleport to the \"Dark Room\""},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Dice Room effects]"

EID.descriptions[languageCode].dice={
	{"1", "", "Rerolls all your passive and active items into a random item from the room pool it was acquired from"},
	{"2", "", "Rerolls all pickups in the room"},
	{"3", "", "Rerolls all pickups and trinkets on the entire floor#Does not affect the {{DevilRoom}}Devil or {{AngelRoom}}Angel Room"},
	{"4", "", "Rerolls all pedestal items on the floor#Does not affect the {{DevilRoom}}Devil or {{AngelRoom}}Angel Room"},
	{"5", "", "Rerolls and restarts the current floor"},
	{"6", "", "Rerolls all your items, pickups, trinkets and pedestal items, including everything on the floor"},
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Beelzebub",		-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Yes Mother?",		-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}


---------- MISC ----------

EID.descriptions[languageCode].VoidText = "If absorbed, gain:"
EID.descriptions[languageCode].VoidNames = {"Speed up", "Tears up", "Damage up", "Range up", "Shot Speed up", "Luck up"}

EID.descriptions[languageCode].CollectionPageInfo = "This item needs to be picked up for the collection page!"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Demo Object Name",
	DemoObjectTransformation = "Demo Transformation",
	DemoObjectText = "This text is in english#A very cool and long description to simulate linebreaks caused by EID textbox width!#{{Collectible4}} This is also a cool line#{{Heart}} This line loves you#{{AngelDevilChance}} This line can be your angel or your devil#\1 {{Damage}} +1 Stat Change up",
}
