	
------------------------------------------------------------------
-----  Basic French descriptions based on Platinumgod.co.uk -----
------------------------------------------------------------------

-- Transformations: uses the number next to the transformation entry (can be found at the bottom of this file)
-- Item ID | transformation id| Description text 
-- '#' = starts new line of text
-- Example:  69|1|+1.0 Tears up |Example Item#Example Second Line

-- French letter rendercheck : 
 --print("ùÙûÛüÜÿŸ àÀâÂæÆçÇ éÉèÈêÊëË ïÏîÎôÔœŒ")

--Special character markup:
-- \1 = Up Arrow   |  \2 = Down Arrow    | \3 = Warning !   | \6 = health   |  \5 Key   |   \015 = Coin   |  \8\189 = Bomb
descriptarray={{"1","0","\1 +0.7 Cadence de tir"},
{"2","0","Triple tir#\2 Cadence de tir"},
{"3","0","Larmes à tête chercheuse"},
{"4","0","\1 +0.5 Dégât(s)#\1 +50% Multiplicateur de Dégât(s) #+ Recul"},
{"5","0","Donne un effet boomerang aux larmes#\1 +1.5 Portée#\1 +0.6 Vitesse des larmes#\1 +1 Hauteur des larmes"},
{"6","0","\1 +1.5 Cadence de tir#\2 -15.78 Portée#\1 +0.45 Hauteur des larmes"},
{"7","0","\1 +1.0 Dégât(s)#\1 +50% si vous possédez Book of Belial"},
{"8","4","Familier à larmes normales"},
{"9","3","Toutes les mouches ennemies sont vos amies"},
{"10","3","+2 mouches orbitales"},
{"11","2","\1 +1 Vie#Réapparaissez avec tous vos coeurs"},
{"12","2","\1 +1 Coeur Max#\1 +0.3 Dégât(s)#\1 +50% Multiplicateur de Dégât(s)#\1 +5.25 Portée#\1 +0.3 Vitesse#\1 +0.5 Hauteur des larmes#Soin complet!"},
{"13","5","Toucher empoisonné#\2 -0.1 Vitesse#Les ennemis empoisonnés peuvent laisser un coeur noir"},
{"14","5","\1 +0.6 Vitesse#\1 +5.25 Portée#\1 +0.5 Hauteur des larmes"},
{"15","0","\1 +1 Coeur Max#Soin complet"},
{"16","0","\1 +2 Coeurs Max#Soin complet"},
{"17","0","+99 Clefs"},
{"18","0","+99 Pièces"},
{"19","0","+10 Bombes"},
{"20","0","Envol!"},
{"21","0","Révèle les icônes de la carte#Ne révèle pas la disposition des salles"},
{"22","0","\1 +1 Coeur Max"},
{"23","0","\1 +1 Coeur Max"},
{"24","0","\1 +1 Coeur Max"},
{"25","0","\1 +1 Coeur Max"},
{"26","0","\1 +1 Coeur Max"},
{"27","0","\1 +0.3 Vitesse"},
{"28","0","\1 +0.3 Vitesse"},
{"29","6","\1 +5.25 Portée#\1 +0.5 Hauteur des larmes"},
{"30","6","\1 +5.25 Portée#\1 +0.5 Hauteur des larmes"},
{"31","6","\1 +5.25 Portée#\1 +0.5 Hauteur des larmes"},
{"32","0","\1 +0.7 Cadence de tir"},
{"33","10","Vol pour la salle actuelle#Tue le pied de Maman et le coeur de Maman instantanément#\3 Vous tue si utilisée sur Satan"},
{"34","12","\1 +2 Dégât(s)#\1 +12.5% chances de devil deal#\1 +50% Multiplicateur de Dégât(s) si vous avez Blood of the Martyr"},
{"35","12","Inflige 40 Dégât(s) à tous les ennemis de la salle"},
{"36","7","Lâche un caca sur le sol#Peut-être placé face à un précipice et explosé pour créer un pont"},
{"37","0","Lâche une grosse bombe sous le joueur qui inflige 110 Dégât(s)"},
{"38","0","Tire 10 larmes autour d'Isaac"},
{"39","6","Paralyse tous les ennemis dans la pièce pendant 4 secondes"},
{"40","0","Crée une explosion à l'emplacement d'Isaac"},
{"41","6","Effraie tous les ennemis dans la salle pendant 5 secondes"},
{"42","8","Bombe empoisonnée pouvant être lancée"},
{"43","0","<Cet objet n'existe pas>"},
{"44","0","Téléporte Isaac dans une salle aléatoire"},
{"45","0","Vous soigne d'un coeur"},
{"46","0","\1 +1.0 Chance#Plus de chances de gagner aux jeux de hasard"},
{"47","0","Epic Fetus à la demande!#Bombardement contrôlable"},
{"48","0","Larmes transperçantes"},
{"49","0","Laser Brimstone à hauts dégât(s)"},
{"50","0","\1 +1 Dégât(s)"},
{"51","9","\1 +1.0 Dégât(s)#\1 +10% chances de Devil Deal"},
{"52","0","Vos larmes sont des bombes!"},
{"53","0","Attire les collectibles vers Isaac"},
{"54","0","Révèle la disposition des salles de l'étage"},
{"55","6","Chance aléatoire de tirer une larme derrière vous"},
{"56","0","Laisse une flaque de limonade"},
{"57","3","Mouche orbitale à portée moyenne"},
{"58","12","Invincibilité pendant 10 secondes"},
{"59","0","<Cet objet n'exsite pas>"},
{"60","0","Marchez par-dessus les petits précipices"},
{"61","0","<Cet objet n'existe pas>"},
{"62","0","Tous les 13 ennemis tués, soignez-vous d'un coeur"},
{"63","0","Les objets activables peuvent maintenant être chargés deux fois"},
{"64","0","-50% pour les objets du magasin#En posséder deux rendra le magasin gratuit"},
{"65","12","Invoque 6 bombes trolles dans la salle"},
{"66","0","Ralentit tous les ennemis pendant 8 secondes"},
{"67","4","Familier à larmes normales"},
{"68","0","Vos larmes sont maintenant des lasers"},
{"69","0","Larmes chargées"},
{"70","5","\1 +1.0 Dégât(s)#\1 +0.4 Vitesse"},
{"71","2","\1 +0.3 Vitesse#\2 -4.25 Portée#\1 +1.5 Hauteur des larmes#(Ajoute une faible portée)"},
{"72","10","+3 coeurs bleus#Bible apparaît plus souvent"},
{"73","0","LVL1: Orbital#LVL2: Orbital tirant des larmes#LVL3: Meat boy LVL 1#LVL4: Meat boy LVL 2"},
{"74","0","+25 Pièces"},
{"75","0","Meilleures pilules# +1 pilule"},
{"76","0","Révèle l'emplacement des salles secrètes"},
{"77","0","Invincibilité + Dégât(s) de corps à corps"},
{"78","12","+1 Coeur bleu#Plus de chances d'affronter un boss cavalier de l'Apocalypse#\1 +17.5% de chances de Devil Deal"},
{"79","9","\1 +1.0 Dégât(s)#\1 +0.2 Vitesse#+1 Coeur bleu"},
{"80","9","\1 +0.5 Dégât(s)#\1 +0.7 Cadence de tir#+2 Coeurs bleus"},
{"81","1","\1 #Réduit votre nombre de réceptacles de coeurs rouges à 1#+9 Vies#Réapparaissez avec un coeur rouge"},
{"82","0","Envol#\1 +0.3 Vitesse"},
{"83","9","+1 Coeur bleu#\1 +0.7 Dégât(s)#\1 -0.18 Vitesse#Écrasez les rochers"},
{"84","0","Fait apparaître une trappe menant à l'étage suivant#10% de chances de trouver une échelle de cordes"},
{"85","0","Fait apparaître une carte"},
{"86","0","Fait atterrir Monstro Après quoi, il s'en va"},
{"87","0","Chance de tirer dans 4 directions à la fois"},
{"88","0","Familier chargeant vers l'avant"},
{"89","13","Ralentit les ennemis"},
{"90","0","\1 +1 Dégât(s)#\1 +0.2 Cadence de tir#\2 -0.2 Vitesse"},
{"91","0","Révèle ce qui se cache derrière les portes"},
{"92","0","\1 +1 Coeur Max#+2 Coeurs bleus"},
{"93","0","Invincibilité + Dégâts au corps à corps#Manger un ennemi régénère de la santé"},
{"94","0","Lâche une pièce aléatoire toutes les 2 salles"},
{"95","0","Familier tirant des lasers"},
{"96","0","Lâche un demi coeur toutes les 3 salles"},
{"97","12","Lâche un collectible aléatoire"},
{"98","0","Lâche un coeur bleu toutes les 4 salles"},
{"99","0","Larmes ralentissantes"},
{"100","4","Larmes à tête chercheuse"},
{"101","10","\1 +1 Coeur Max#\1 +0.3 Dégât(s)#\1 +0.2 Cadence de tir#\1 +0.25 Portée#\1 +0.3 Vitesse#\1 +0.5 Hauteur des larmes"},
{"102","6","Fait apparaître une pilule"},
{"103","0","Chance de tirer des larmes empoisonnées"},
{"104","0","Les larmes se séparent au contact d'un objet ou d'un ennemi"},
{"105","0","Change l'objet de piédestal dans la salle actuelle"},
{"106","0","\1 x2.25 Dégâts des bombes#+5 Bombes"},
{"107","0","Envol#Votre corps attaque les ennemis"},
{"108","0","Vous perdez au plus un demi coeur en recevant des dégâts"},
{"109","0","\1 +0.04 Dégât(s) pour chaque pièce que vous possédez"},
{"110","6","Larmes paralysantes#\1 +0.25 Portée"},
{"111","0","Pet empoisonné"},
{"112","10","Orbital#Augmente la vitesse de vos orbitaux"},
{"113","0","Tourelle automatique"},
{"114","6","Couteau contrôlable"},
{"115","0","Larmes spectrales"},
{"116","0","-1 Charge nécessaire pour les objets activables#Charge complètement l'objet tenu"},
{"117","0","Fait apparaître un oiseau quand vous vous faites toucher"},
{"118","9","Charge un laser de sang qui fait des dégâts constants"},
{"119","0","\1 +1 Coeur Max#\1 +0.3 Vitesse#Vous soigne 5 coeurs"},
{"120","2","\1 +1.7 Cadence de tir#\1 +0.3 Vitesse#\2 Dégât(s)"},
{"121","2","\1 +1 Réceptacle de coeur vide#\1 +0.3 Dégât(s)#\1 +0.25 Portée#\2 -0.1 Vitesse#\1 +0.5 Hauteur des larmes"},
{"122","0","\3 Lorsqu'il vous reste un demi coeur ou moins:#\1 +1.5 Dégât(s)#\1 +0.3 Vitesse"},
{"123","12","Familier aléatoire pour la salle actuelle"},
{"124","0","Objet activable aléatoire"},
{"125","0","Bombes à tête chercheuse#+5 Bombes"},
{"126","0","\1 +1.2 Dégât(s)#\2 -1 Coeur"},
{"127","0","\3 USAGE UNIQUE \3#Relance l'étage entier"},
{"128","3","Mouche orbitale#Très éloignée"},
{"129","0","\1 +2 Coeurs Max#\2 -0.2 Vitesse#Vous soigne d'un demi coeur"},
{"130","0","Vous donne le vol si vous le tenez#Dashez dans une direction"},
{"131","0","Lâche une bombe toutes les 2 salles"},
{"132","0","Les dégâts de vos larmes augmentent avec la distance parcourue"},
{"133","1","\3 Convertit:#1 Un coeur rouge pour 3 coeurs bleus"},
{"134","1","Les coffres sont plus nombreux"},
{"135","0","Banque de sang portable#Un demi coeur = 1 Pièce#S'attaque d'abord aux coeurs rouges"},
{"136","0","Balise explosive#Attire les ennemis"},
{"137","0","Faites exploser les bombes manuellement#+5 Bombes"},
{"138","0","\1 +1 Coeur Max#\1 +0.3 Dégât(s)"},
{"139","6","Vous pouvez maintenant tenir 2 Trinkets"},
{"140","8","Bombes empoisonnées#+5 Bombes"},
{"141","0","Fait apparaître 7 pièces aléatoires"},
{"142","0","Quand des dégâts vous mettent à un demi coeur, recevez un coeur bleu#(Une seule fois par salle)"},
{"143","5","\1 +0.3 Vitesse#\1 +0.2 Vitesse des larmes"},
{"144","11","Convertit les pièces en des objets collectables"},
{"145","1","Fait apparaître de 2 à 4 mouches bleues"},
{"146","0","+1 Coeur éternel"},
{"147","0","Détruit les rochers dans la salle"},
{"148","3","Fait apparaître des mouches quand vous vous faites toucher"},
{"149","8","Larmes explosives"},
{"150","0","Chance de tirer des dents infligeant plus de dégâts"},
{"151","3","Une chance sur 6 de faire apparaître une mouche bleue quand une larme touche un ennemi"},
{"152","0","Laser permanent!#\2 -35% Dégât(s)"},
{"153","13","Quadruple tir!#\2 Cadence de tir"},
{"154","0","\1 +2 Dégât(s) pour l'oeil gauche"},
{"155","0","Voyage autour de la salle#Inflige des dégâts au corps à corps"},
{"156","0","+1 Charge quand vous vous faites toucher"},
{"157","0","\1 Dégât quand vous vous faites toucher#Valable pour l'étage entier"},
{"158","0","Révèle toute la carte#Fait apparaître une carte aléatoire ou un coeur bleu"},
{"159","9","Envol#Larmes spectrales"},
{"160","0","Rayons de lumières tombant du ciel!"},
{"161","0","Réapparaissez en tant que ??? (Blue Baby)"},
{"162","0","Chance de devenir invincible en vous faisant toucher"},
{"163","0","Familier à larmes spectrales"},
{"164","0","Fait apparaître un feu bleu"},
{"165","0","\1 +1 Dégât(s)#\1 +0.23 Vitesse des larmes"},
{"166","0","Transforme les collectibles de la pièce en d'autres collectibles aléatoires"},
{"167","4","Tire deux larmes en 'V'"},
{"168","0","Bombardements contrôlables à la place de vos larmes"},
{"169","0","Méga larmes!#\1 Dégât(s)#\2 Cadence de tir"},
{"170","0","Écrase les ennemis"},
{"171","13","Ralentit les ennemis#Inflige des dégâts à tous les ennemis"},
{"172","0","Couteau orbital"},
{"173","10","Plus de chances de trouver des coeurs bleus"},
{"174","0","Tire des larmes aléatoires"},
{"175","0","Ouvre toutes les portes de la salle, y compris les salles secrètes et Méga-Satan"},
{"176","0","\1 +1 Coeur Max#\1 +0.16 Vitesse des larmes"},
{"177","0","Machine de jeu portable"},
{"178","0","Laisse une flaque lorsque vous vous faites toucher"},
{"179","0","Envol#+1 Coeur éternel"},
{"180","0","Pet lorsque vous vous faites toucher"},
{"181","0","Vous permet de voler tant que vous le tenez#Dash sacré"},
{"182","0","Larmes à tête chercheuse#\1 +1 Coeur Max#\1 Dégâts grandement augmentés!#\2 -0.4 Cadence de tir#\2 -0.25 Vitesse des larmes#\1 +0.375 Portée"},
{"183","0","\1 +0.7 Cadence de tir.#\1 +0.16 Vitesse des larmes"},
{"184","10","Envol#\1 +1 Coeur Max"},
{"185","10","Envol#Larmes spectrales"},
{"186","0","Inflige 40 de dégâts à tous les ennemis#-1 coeur par utilisation"},
{"187","1","Boule de poil#Se balance autour de vous#Grandit en tuant un ennemi"},
{"188","0","Imite vos mouvements#Tire vers Isaac"},
{"189","0","\1 +1 Coeur Max#\1 +0.3 Dégât(s)#\1 +0.2 Cadence de tir#\1 +0.5 Portée#\1 +0.2 Vitesse#\1 +1.0 Hauteur des larmes#Soin complet"},
{"190","0","+99 Bombes"},
{"191","0","Effet de larme aléatoire"},
{"192","12","Larmes à tête chercheuse pour la salle actuelle"},
{"193","0","\1 +1 Coeur Max#\1 +0.3 Dégât(s)"},
{"194","0","\1 +0.16 Vitesse des larmes#+1 carte"},
{"195","6","Lâche 4 pilules"},
{"196","0","+2 Coeurs bleus#\1 +0.4 Cadence de tir"},
{"197","0","\1 +0.5 Dégât(s)#\1 +0.25 Portée.#\1 +0.5 Hauteur des larmes"},
{"198","0","Lâche un collectible de chaque type"},
{"199","6","+2 Clefs#Les coffres sont plus abondants"},
{"200","6","Larmes séductrices"},
{"201","0","\1 +0.3 Dégât(s)#Rend les ennemis confus"},
{"202","0","Les ennemis qui vous touchent se transforment en or#Les ennemis en or laissent tomber des pièces"},
{"203","0","Double tous les collectibles"},
{"204","0","Lâche un collectible aléatoire quand vous vous faites toucher"},
{"205","0","-2 coeurs = Recharge complètement votre objet quand vous appuyez sur la barre d'espace#\3 Ne fonctionne que si votre objet n'est pas chargé!"},
{"206","0","\1 +1 Dégât(s)#\1 Cadence de tir#Votre tête est maintenant un orbital#Vos larmes partent de votre tête"},
{"207","0","LVL1: Orbital#LVL2: Orbital tirant des larmes pouvant charmer les ennemis#LVL3: Bandage Girl#LVL4: Bandage Girl LVL2"},
{"208","0","\1 +1 Dégât(s)#\3 Les ennemis d'élite sont plus fréquents"},
{"209","7","\1 +5 Bombes#Les explosions font des dégâts et rendent confus tous les ennemis dans la salle"},
{"210","0","Invincible si vous restez immobile plus d'une seconde"},
{"211","13","Fait apparaître des araignées bleues quand vous vous faites toucher"},
{"212","1","\1 50% de chance de revivre"},
{"213","0","Larmes bouclier#\2 -0.15 Vitesse des larmes"},
{"214","0","\1 +5 Portée#Laissez une flaque sur le sol en vous faisant toucher"},
{"215","0","\1 100% de chance de trouver un Devil Deal / Angel Room"},
{"216","0","\1 +1 Dégât(s)#+3 Coeurs noirs"},
{"217","6","Chance aléatoire de faire apparaître une araignée bleue en tirant des larmes"},
{"218","0","Régénère lentement votre santé#\1 +1 Coeur Max"},
{"219","0","\1 +1 Réceptacle de coeur vide#Chance aléatoire de faire tomber un coeur rouge en vous faisant toucher"},
{"220","0","Explosion de larmes!#+5 Bombes"},
{"221","0","Larmes rebondissantes"},
{"222","0","\1 Cadence de tir#Larmes anti-gravité"},
{"223","0","Les explosions vous soignent#+5 Bombes"},
{"224","0","\1 -1 Cadence de tir#\2 -10.0 Portée#En rencontrant un objet / un ennemi, les larmes se divisent en 4"},
{"225","0","Chance de faire tomber un coeur bleu/noir en vous faisant toucher"},
{"226","0","\1 +1 Coeur Max#+1 Coeur bleu#+1 Coeur noir"},
{"227","0","+3 Pièces#Faites tomber une pièce en vous faisant toucher"},
{"228","6","Larmes apeurantes#\1 Cadence de tir"},
{"229","0","Les larmes peuvent maintenant être chargées pour lâcher un amas de larmes"},
{"230","9","\1 +1.5 Dégât(s)#\1 +0.2 Vitesse#Larmes apeurantes#\2 Enlève tous vos coeurs rouges#+6 Coeurs noirs"},
{"231","0","Laisse une flaque ralentissante#Larmes ralentissantes"},
{"232","0","Quand vous vous faites toucher, tous les ennemis de la salle sont ralentis"},
{"233","0","Les larmes orbitent autour de vous#\1 +7.0 Hauteur des larmes"},
{"234","0","Fait apparaître des araignées quand vous tuez un ennemi"},
{"235","0","<Cet objet n'existe pas>"},
{"236","7","Les ennemis qui vous touchent se transforment en caca"},
{"237","0","Larmes en forme de faux!#Les faux transpercent les ennemis#\1 +1.5 Dégât(s)#\2 -0.3 Cadence de tir"},
{"238","0","\3 Fragment de clef pour la porte de Mega Satan!#Les Angel Rooms sont plus fréquentes"},
{"239","0","\3 Fragment de clef pour la porte de Mega Satan!#Les Angel Rooms sont plus fréquentes"},
{"240","5","Augmente et diminue vos stats de manière aléatoire \1\2"},
{"241","0","Double tous les drops d'objets collectables"},
{"242","0","Chance de bloquer les projectiles"},
{"243","0","Bouclier anti-projectiles"},
{"244","0","Tire des lasers aléatoires"},
{"245","0","Double vos larmes"},
{"246","0","Révèle les salles secrètes"},
{"247","0","Vos familiers font plus de dégâts"},
{"248","3","Les mouches et araignées bleues font plus de dégâts"},
{"249","0","2 objets au lieu de 1 en récompense de boss#\3 Seul l'un d'entre eux peut être pris"},
{"250","0","Double tous les drops de bombes"},
{"251","0","Vous pouvez transporter 2 cartes#Transforme toutes les pilules en cartes"},
{"252","0","Vous pouvez transporter 2 pilules#Transforme toutes les cartes en pilules"},
{"253","0","\1 +1 Chance#\1 +1 Coeur Max"},
{"254","0","\1 +1 Dégât(s)#\1 +5 Portée#\3 Ne s'applique qu'à l'oeil gauche"},
{"255","0","\1 +0.5 Cadence de tir#\1 +0.2 Vitesse des larmes"},
{"256","0","Bombes incandescentes#+5 Bombes"},
{"257","0","Les larmes sont en feu#Chance de tirer des larmes explosives"},
{"258","0","Change tous vos objets lors du passage à l'étage suivant"},
{"259","0","\1 +1 Dégât(s)#Larmes apeurantes"},
{"260","0","Immunité aux malédictions#+1 Coeur noir"},
{"261","0","\1 +100% Dégât(s)#\2 Plus vos larmes parcourent de distance, moins elles font de dégâts"},
{"262","0","+1 Coeur noir#Quand réduit à 1.5 coeurs, inflige des dégâts à tous les ennemis dans la salle"},
{"263","0","<Cet objet n'existe pas>"},
{"264","3","Orbital pouvant charger les ennemis"},
{"265","0","Si touché par une larme ennemie, inflige des dégâts à tous les ennemis dans la salle"},
{"266","0","Lâche une flaque ralentissante#Peut faire apparaître des araignées bleues en terminant une salle"},
{"267","0","Tire des lasers"},
{"268","4","Fait apparaître des mouches bleues"},
{"269","4","Laisse une flaque"},
{"270","0","Vous soigne d'un demi coeur en tuant un ennemi"},
{"271","0","Laisse tomber des collectibles aléatoires"},
{"272","3","Mouche alliée explosive"},
{"273","8","Familier explosif pouvant être lancé"},
{"274","3","Fait apparaître un orbital à moyenne portée en vous faisant toucher"},
{"275","0","Tire un laser Brimstone"},
{"276","0","Votre corps est invulnérable#\3 Vous recevez des dégâts quand le coeur se fait toucher par un ennemi"},
{"277","0","Familier fantôme qui attaque les ennemis et les apeure"},
{"278","11","\3 Convertit:#1,5 coeurs rouges en un coeur bleu. Peut faire apparaître une araignée bleue ou rouge à la place"},
{"279","3","Orbital obèse"},
{"280","0","Fait apparaître des araignées bleues"},
{"281","0","Les ennemis vont se ruer sur lui"},
{"282","12","Vous permet de sauter"},
{"283","0","Relance tous les objets sur piédestales, les collectibles et les objets que vous tenez"},
{"284","0","Relance tous les objets que vous tenez"},
{"285","0","Change tous les ennemis de la salle en d'autres ennemis aléatoires"},
{"286","0","Copie l'effet de la carte que vous tenez"},
{"287","12","Révèle une partie de la carte"},
{"288","13","Fait apparaître 2-4 araignées bleues"},
{"289","0","Lancez une flamme rouge"},
{"290","0","Peut stocker jusqu'à 4 coeurs rouges"},
{"291","7","\3 Tue instantanément les ennemis en forme de caca (boss compris)!#Transforme les ennemis en caca"},
{"292","12","+1 Coeur noir"},
{"293","0","Tire un laser Brimstone dans 4 directions"},
{"294","0","Repousse les ennemis proches"},
{"295","0","Inflige des dégâts à toute la salle (en fonction de votre stat de dégâts)#Prix: 1 Pièce"},
{"296","0","\3 Convertit:#2 Coeur bleus/noir en un coeur rouge"},
{"297","0","\3 UTILISATION UNIQUE \3#\3 Laisse tomber des objets en fonction de l'étage:#B1: 2 Coeurs bleus#B2: 2 Clefs et bombes#C1: 1 Objet de boss#C2: B1+C1#D1: 4 Coeurs bleus#D2: 30 Pièces#W1: 2 Objets de boss#W2: Bible#Sheol: 1 Objet démoniaque + Coeur noir#Cat: 1 Objet angélique + Coeur bleu#Chest: 1 Pièce"},
{"298","0","Invincibilité et accélération temporaire"},
{"299","0","Vous êtes plus rapides dans les salles hostiles!#Une fois que vous êtes assez rapide, invincibilité"},
{"300","0","\1 +0.25 Vitesse#Toucher un ennemi lui inflige des dégâts"},
{"301","0","+3 Coeurs bleus#Une fois touché, les dégâts suivants ne peuvent excéder un demi coeur"},
{"302","0","Détruis les rochers!"},
{"303","0","Chance de devenir invincible en vous faisant toucher"},
{"304","0","+6 Pièces / Clefs / Bombes#Équilibre vos stats!#\3 Chaque augmentation de stat va aussi affecter les autres stats"},
{"305","0","Larmes empoisonnées"},
{"306","0","\1 +0.2 Vitesse#Larmes transperçantes"},
{"307","0","\1 +1 Coeur Max / Clef / Bombe / Pièce#\1 +0.5 Dégât(s)#\1 +0.1 Vitesse#\1 +1.5 Portée"},
{"308","0","Laissz une trainée qui inflige des dégâts"},
{"309","0","\1 Cadence de tir#Larmes avec recul"},
{"310","0","\1 Dégât(s) X 2#\2 Cadence de tir#\2 Vitesse des larmes"},
{"311","0","Une fois mort, réapparaîssez en Black Judas#\1 (Dégât(s) X 2)"},
{"312","0","\1 +1 Coeur Max#Les coeurs rouges vous soignent de deux coeurs"},
{"313","10","Ignorez le premier dégât reçu dans chaque salle"},
{"314","0","\1 +1 Coeur Max#-0.4 Vitesse#Vous pouvez détruire les rochers!"},
{"315","0","Larmes magnétiques"},
{"316","0","Vague de larmes chargée#Si vous vous faîtes toucher en chargeant vos larmes, vous téléporte dans une salle aléatoire"},
{"317","0","Les larmes laissent une flaque qui inflige des dégâts"},
{"318","0","Familier expert en combat rapproché"},
{"319","0","Rebondit à travers la salle#Tire vers Isaac#Ses dégâts sont égaux aux vôtres"},
{"320","3","Mouche contrôlable"},
{"321","0","Boulet enchaîné#Le boulet inflige des dégâts aux ennemis, peut bloquer les projectiles et détruire les rochers"},
{"322","4","Copie l'effet d'un de vos familiers"},
{"323","0","Explosion de larmes#Se charge quand vous tirez"},
{"324","0","Vous téléporte vers:#Salles / Error / Objets / Secrètes"},
{"325","0","Détache votre tête#La tête est stationnaire#Controllez votre corps séparément"},
{"326","0","Maintenez la barre d'espace jusqu'à ce que l'objet soit déchargé#Vous rend invincible#\3 Ne maintenez pas trop longtemps!"},
{"327","0","Si vous avez moins d'un demi coeur rouge et que vous vous faites toucher, vous rend invincible"},
{"328","0","Si vous avez moins d'un demi coeur rouge et que vous vous faites toucher, inflige des dégâts à tous les ennemis de la salle"},
{"329","0","Larme contrôlable"},
{"330","0","\1 Très grande cadence de tir: (délai /4) - 2#\2 -80% Dégât(s)"},
{"331","0","Larmes à tête chercheuse#\1 +0.5 Dégât(s)#\1 +1.2 Portée#\2 -0.3 Cadence de tir#\2 -0.3 Vitesse des larmes#\1 +0.8 Hauteur des larmes"},
{"332","0","En mourant, réapparaîssez en tant que Lazarus et gagnez un objet bonus"},
{"333","0","Dévoile toute la carte complète"},
{"334","0","\1 +3 Coeurs Max"},
{"335","0","+2 Coeurs bleus#Les projectiles ont maintenant une grande chance d'éviter Isaac"},
{"336","0","Larmes spectrales et transperçantes#\2 -0.25 Portée#\2 -0.4 Vitesse des larmes"},
{"337","0","Accélère ou ralentit les salles#Fait effet toutes les 4 salles"},
{"338","0","Rend les ennemis confus#Peut attraper des objets"},
{"339","0","\1 +5.25 Portée#\1 +0.16 Vitesse des larmes#+1 Coeur noir#\1 +0.5 Hauteur des larmes"},
{"340","0","\1 +0.3 Vitesse#\1 Isaac rapetissit#Donne une pilule aléatoire"},
{"341","0","\1 +0.7 Cadence de tir#\1 +0.16 Vitesse des larmes"},
{"342","2","\1 +1 Coeur Max#\1 +0.7 Cadence de tir#\2 -0.16 Vitesse des larmes"},
{"343","0","\1 +1 Chance#+1 Coeur bleu#Fait apparaître 2 Clefs"},
{"344","0","+1 Coeur noir#+3 Bombes"},
{"345","5","\1 +1.0 Dégât(s)#\1 +5.25 Portée#\1 +0.5 Hauteur des larmes"},
{"346","0","\1 +1 Coeur Max"},
{"347","0","\3 USAGE UNIQUE \3#Duplique tous les objets sur piédestal et collectibles dans la salle"},
{"348","0","Copie l'effet de la pilule que vous tenez"},
{"349","0","50% de chance de lâcher une pièce aléatoire"},
{"350","0","À l'entrée chaque salle, empoisonne tous les ennemis"},
{"351","0","Paralyse tous les ennemis dans la salle#Inflige des dégâts et empoisonne tous les ennemis proches#Envoie une vague de rochers dans la salle#\3 Peut ouvrir les salles secrètes"},
{"352","0","\2 Réduis votre santé à un demi coeur#Tire une énorme larme spectrale et transperçante ((DMG+1) X 10)"},
{"353","0","+5 Bombes#Les bombes vont maintenant créer des explosions en forme de croix"},
{"354","0","\1 +1 Coeur Max#Fait apparaître un trinket aléatoire dans la salle"},
{"355","6","\1 +1.25 Portée#\1 +1 Chance#\1 +0.5 Hauteur des larmes"},
{"356","0","Les objets activables font effet deux fois à chaque utilisation"},
{"357","0","Duplique tous vos familiers dans la salle"},
{"358","0","Tire 2 larmes en même temps en diagonale, similaire à R U A WIZARD#Larmes spectrales"},
{"359","0","\1 +1.5 Dégât(s)#Recul augmenté"},
{"360","0","Tire les mêmes larmes qu'Isaac en terme de dégât(s), stats et effets"},
{"361","0","Tire des larmes infligeant les mêmes dégâts que celles d'Isaac"},
{"362","0","Lâche un collectible aléatoire au bout de quelques salles"},
{"363","10","Inflige des dégâts au corps à corps#Attire et bloque les projectiles#Bloquer un projectile peut faire apparaître un coeur éternel"},
{"364","3","Inflige des dégâts au corps à corps"},
{"365","3","Se déplace le long des murs et des obstacles#Inflige des dégâts au corps à corps"},
{"366","0","+5 Bombes#Vos bombes lâchent 4 petites bombes après explosion"},
{"367","0","+5 Bombes#Quand une bombe tue un ennemi, elle fait apparaître des araignées bleues#Vos bombes se collent aux ennemis"},
{"368","0","Tirer dans la même direction augmente votre cadence de tir"},
{"369","0","\1 +2.25 Portée#\1 +1.5 Hauteur des larmes#Les larmes traversent les murs et réapparaissent depuis le mur opposé"},
{"370","0","\1 +0.7 Cadence de tir#\1 +5.25 Portée#\1 +0.5 Hauteur des larmes#Fait apparaître 3 coeurs aléatoires"},
{"371","0","Fait apparaître 6 bombes trolles à chaque fois que vous vous faites toucher#Ces bombes prennent en compte vos effets de bombes"},
{"372","0","Chance aléatoire de faire tomber une batterie ou de paralyser tous les ennemis dans la salle#Chance d'ajouter une charge à votre objet"},
{"373","0","\1 +12.5% Dégât(s) pour chaque larme qui touche un ennemi(max. +100%)"},
{"374","0","Chance aléatoire de tirer une larme sacrée qui fera apparaître un halo de lumière divine sur l'ennemi touché"},
{"375","0","Chance aléatoire de dévier les projectiles#Immunités aux explosions et aux écrasements de Satan et Mom's Foot"},
{"376","0","Les boutiques vous proposent un autre objet du même type quand vous en achetez un#engendre 3 ramasser"}, -- GOOGLE TRANSLATE ON LAST PART!
{"377","0","Les araignées ennemies n'infligent plus de dégâts à Isaac"},
{"378","0","Tirer des larmes pendant 3 secondes fait apparaître un caca explosif sous Isaac"},
{"379","0","Les larmes ont une hitbox plus large#Larmes spectrales"},
{"380","0","+5 Pièces#Vous pouvez ouvrir les portes avec une pièce au lieu d'une clef"},
{"381","0","\1 +0.7 Cadence de tir#Vous donne un objet aléatoire au début de votre prochaine partie"},
{"382","0","Peut être lancée sur les ennemis pour les capturer#La prochaine utilisation fera apparaître un monstre allié de la même famille"},
{"383","0","Fait détonner toutes les larmes de la salle, chacune d'entre elles va se diviser en 6 larmes se dispersant dans 6 directions"},
{"384","0","Va charger à travers la salle, infligeant des dégâts aux ennemis"},
{"385","0","Va ramasser les pièces proches# Toutes les 6 pièces, il gagne un niveau, excepté pour atteindre le Niveau 4 (12 pièces)#Niveau 2: Lâche des collectibles#Niveau 3: Tire des larmes dans la même direction qu'Isaac#Niveau 4: Ne tire plus de larmes mais va poursuivre les ennemis# Peut aussi lâcher des bombes#Niveau 4+: Va continuer à prendre des pièces mais fera apparaître des collectibles et coffres aléatoires"},
{"386","0","Transforme n'importe quel rocher en un objet aléatoire (ex: cacas, pots, TNT, cacas rouges, blocs incassables, etc)"},
{"387","0","Crée une énorme aura de lumière qui ralentit les ennemis qui y entrent"},
{"388","11","Ramasse les clefs, offrant des coffres aléatoires en échange"},
{"389","0","Lâche une rune aléatoire toutes les 3 salles"},
{"390","0","Tire des larmes sacrées"},
{"391","0","Chaque fois qu'Isaac reçoit des dégats, provoque un effet séduction sur toute la salle"},
{"392","0","Vous donne l'effet d'un signe du zodiaque aléatoire# L'effet change à chaque étage"},
{"393","0","Chance aléatoire d'empoisonner les ennemis#Empoisonne les ennemis au toucher#Les ennemis qui meurent en étant sous l'effet du poison peuvent lâcher un coeur noir"},
{"394","0","Les larmes sont tirées automatiquement en direction d'une cible rouge contrôllée par le joueur#\1 +0.7 Cadence de tir#\1 +0.3 Hauteur des larmes#\1 +3.15 Portée"},
{"395","0","Les larmes sont maintenant des cercles de lasers dont la taille varie en fonction du temps de charge"},
{"396","0","Crée jusqu'à 2 portails vous permettant de vous téléporter de l'un vers l'autre"},
{"397","0","Les larmes d'Isaac suivent à présent un rayon de lumière, et bougeront en fonction des mouvements d'Isaac#\1 +0.5 Cadence de tir#\1 +5.25 Portée#\1 +0.16 Vitesse des larmes#\1 +0.5 Hauteur des larmes"},
{"398","2","Les larmes ont une chance de rétrécir les ennemis#Marcher sur un ennemi rétréci le tue"},
{"399","9","\1 +1.0 Dégât(s)#\1 +0.5 Hauteur des larmes#Après avoir tiré pendant 3 secondes, une croix rouge apparaît sur le front d'Isaac# Arrêter de tirer libère un halo noir infligeant des dégâts aux ennemis touchés# Les ennemis tués avec le halo noir ont une chance de faire tomber un coeur noir"},
{"400","0","Fait apparaître une lance devant Isaac infligeant le double de dégâts des larmes d'Isaac"},
{"401","0","Les larmes ont une chance de se transformer en bombe collante qui s'accroche aux ennemis avant d'exploser après quelques secondes"},
{"402","0","Mélange tous les objets sur piédestal que vous trouverez# Ceux-ci ne sont plus liés à une salle spécifique# Lâche également 1-6 collectibles"},
{"403","13","Affiche les dégâts que vous infligez aux ennemis ainsi que leur barre de vie#Inflige un statut aléatoire aux ennemis touchés#Peut lâcher des batteries"},
{"404","0","Bloque les projectiles#Si un projectile le touche, il inflige des dégâts et charme les ennemis proches"},
{"405","0","Inflige un effet de statut aléatoire aux ennemis au corps à corps"},
{"406","0","Mélange vos stats#N'affecte que les dégâts, la cadence de tir, la portée et la vitesse d'Isaac"},
{"407","0","\1 Booste une stat d'Isaac en fonction de la couleur de l'aura#Recevoir des dégâts change la couleur de l'aura#Rouge = +4.0 Dégât(s)#Bleue = -4 Cadence de tir#Jaune = +0.5 Vitesse#Orange = +7.5 Portée"},
{"408","0","Quand Isaac reçoit des dégâts, fait apparaître un halo noir autour d'Isaac qui inflige des dégâts aux ennemis#Les ennemis tués par le halo noir ont une chance de lâcher un coeur noir"},
{"409","0","+2 coeurs noirs#Quand Isaac n'a plus de coeur rouge, il peut voler et a une chance de recevoir un bouclier anti-dégâts"},
{"410","0","En tirant, Isaac a une chance de tirer un oeil qui va lui-même tirer des larmes"},
{"411","0","\1 Chaque fois qu'Isaac tue un ennemi, il gagne des dégâts pour la durée de la salle#Jusqu'à 5 de dégâts bonus (9 kills maximum)"},
{"412","0","En recevant suffisamment de dégâts, Isaac obtient un familier démoniaque"},
{"413","0","En ramassant suffisamment de coeurs, Isaac obtient un familier angélique"},
{"414","0","Les items rooms contiennent maintenant 2 objets#Vous ne pouvez en choisir qu'un"},
{"415","0","+2 Coeurs bleus#\1 Dégât(s) X 2 si vous ne possédez pas de réceptacle de coeur vide"},
{"416","0","Vous permet de transporter 2 cartes/pilules/runes à la fois"},
{"417","0","Rebondit à travers la pièce# Possède une aura infligeant des dégâts aux ennemis#\1 +50% en dégâts en restant dans l'aura"},
{"418","0","Chaque larme possède un effet aléatoire différent"},
{"419","0","Vous téléporte dans une salle inexplorée#Dans l'ordre: Salles classiques, Salle super secrète, Shop, Item Room, Salle secrète, Curse Room, Sacrifice Room, Devil/Angel Room, I Am Error"},
{"420","0","Faire un cercle en marchant va créer un pentagram sur le sol qui inflige 10 points de dégâts aux ennemis par tick de dégâts"},
{"421","0","Applique un effet de charme à tous les ennemis à portée"},
{"422","0","Remonte le temps et vous ramène à la salle explorée précédemment, dans le même état que vous étiez à ce moment-là"},
{"423","0","Forme un épais halo autour d'Isaac qui inflige des dégâts#Chance de dévier les projectiles"},
{"424","0","Tous les collectibles ont une chance d'être remplacés par des sacs de collectibles"},
{"425","0","Cône de lumière qui ralentit les ennemis et les projectiles"},
{"426","3","Suit les mouvements d'Isaac avec un délai de 3 secondes#Inflige des dégâts au corps-à-corps aux ennemis"},
{"427","0","Place un tonneau de TNT pouvant être poussé#Si réutilisé, fait exploser le tonneau placé précédemment"},
{"428","0","+4 Coeurs bleus#Soigne tous vos coeurs rouges"},
{"429","0","Les larmes qui touchent un ennemi ont une chance de faire tomber une pièce"},
{"430","3","Suit les mouvements d'Isaac avec un délai de 3 secondes#Tire des larmes infligeant les mêmes dégâts que celles d'Isaac aux ennemis"},
{"431","0","Suit les mouvements d'Isaac avec un délai de 3 secondes#Les larmes d'Isaac qui passent au travers seront dédoublées et feront plus de dégâts"},
{"432","0","Les bombes lâchent des collectibles aléatoires en explosant (clefs, bombes, ...)"},
{"433","0","Quand Isaac prend des dégâts, inflige un effet de peur à tous les ennemis et fait apparaître un familier des ombres qui se battra pour vous#Le familier meurt s'il prend trop de dégâts"},
{"434","3","Ajoute une mouche bleue dans le vase pour chaque ennemi tué#Peut contenir jusqu'à 20 mouches#Utiliser le vase va libérer toutes les mouches"},
{"435","0","Tire 4 larmes dans les 4 directions"},
{"436","0","En recevant des dégâts, augmente la cadence de tir d'Isaac"},
{"437","0","Fait réapparaître tous les ennemis de la salle afin d'obtenir une nouvelle fois la récompense pour avoir terminé la salle#\3 Si utilisé contre Greed, peut transformer la salle en un Shop"},
{"438","0","+1 Coeur bleu#\1 +0.7 Cadence de tir#\1 Rapetissit Isaac, diminuant sa hitbox"},
{"439","0","Fait tomber un trinket aléatoire#\1 +1 Chance tant qu'il est tenu#Double les effets des trinkets"},
{"440","0","En tirant, chance d'arrêter de tirer pour lâcher un amas de larmes et de caillots#\2 -0.2 Vitesse#\2 -15 Portée#\1 +2.0 Hauteur des larmes"},
{"441","0","Tire un gigantesque laser de Méga Satan pendant 15 secondes#Le laser persiste endéans les 15 secondes, même si vous changez de salle ou d'étage"},
{"442","0","\3 En possédant 1 coeur rouge:#\1 +1.5 Portée#\1 +0.7 Cadence de tir#\1 +0.2 Shoot Vitesse#(Ne fonctionne pas avec The Lost)"},
{"443","0","Permet de parfois tirer des lames de rasoir infligeant 400% de dégâts#\1 +0.4 Cadence de tir"},
{"444","0","Toutes les 15 larmes tirées, vous lancez une grappe de larmes#Chaque larme de la grappe inflige le double de dégâts de vos larmes"},
{"445","0","\1 +0.3 Dégât(s)#\1 +0.1 Vitesse#Un hurlement de loup retentit lorsque vous entrez dans une salle voisine à une salle secrète / dans une salle possédant une trappe"},
{"446","0","En tirant, vous créez une aura verte qui empoisonne les ennemis"},
{"447","0","En tirant, peut faire apparaître un nuage de pet"},
{"448","0","En recevant des dégâts, chance d'obtenir:#\1 +5 Portée#Vous laissez une traînée de sang qui inflige des dégâts"},
{"449","0","+1 Coeur bleu#Les larmes ennemies ont une chance d'être déviées"},
{"450","0","Les larmes peuvent changer les ennemis en or"},
{"451","0","Lâche une carte ou rune aléatoire#Double leur utilisation"},
{"452","0","Chaque fois que vous recevez des dégâts, tire 10 larmes puissantes dans toutes les directions"},
{"453","0","Larmes en os#Au contact d'un objet, d'un ennemi ou d'un mur, les os se séparent en petits os#\1 +1.5 Portée"},
{"454","0","Vous pouvez tenir deux cartes / runes / pilules à la fois#Lâche une carte / rune / pilule aléatoire"},
{"455","0","\1 +1.5 Portée#Lâche un lucky penny"},
{"456","0","\1 +1 Coeur Max"},
{"457","0","+1 Coeur bleu#Chance d'ignorer les dégâts"},
{"458","0","Lâche un trinket aléatoire#Vous pouvez transporter deux trinkets à la fois"},
{"459","0","Larmes empoisonnées collantes jusqu'à ce que la cible saute, se téléporte ou meure"},
{"460","0","Chance de tirer des larmes assommantes"},
{"461","0","Chance de tirer des larmes ralentissantes et collantes#Fait apparaître une araignée/mouche en touchant un ennemi"},
{"462","0","Larmes perçantes#Après avoir touché un ennemi, vos larmes gagnent le double de dégâts et sont à tête chercheuse"},
{"463","0","\1 +0.3 Dégât(s)#Chance de tirer des larmes qui détruisent les rochers"},
{"464","0","+2 Coeurs bleus#Les ennemis d'élite lâchent des collectibles plus souvent"},
{"465","0","\1 +2 Cadence de tir#Vous permet de tirer en diagonale"},
{"466","0","Le premier ennemi tué va exploser et empoisonner les ennemis proches"},
{"467","0","Inflige de faibles dégâts constants aux ennemis qu'il pointe"},
{"468","0","Suit les mouvements d'Isaac avec un délai de 3 secondes#Inflige des dégâts au corps à corps"},
{"469","0","Laisse une traînée de larmes#Les ennemis qui touchent le nuage peuvent faire apparaître une lumière divine"},
{"470","0","Rebondit à travers la salle#Inflige des dégâts au corps à corps#Quand vous tirez, il cesse de bouger"},
{"471","0","Charge ses tirs#Lâche une grappe de larmes#(Similaire à Montro's Lung)"},
{"472","0","Vos autres familiers le suivent#Quand vous tirez, il cesse de bouger#Se retéléporte sur vous quand vous cessez de tirer"},
{"473","0","Charge lentement vers l'avant#Inflige des dégâts au corps à corps"},
{"474","0","Bloque les projectiles"},
{"475","0","\3 USAGE UNIQUE \3 #Inflige 9.999.999 dégâts à tous les ennemis puis vous tue 3 secondes après"},
{"476","0","Duplique un collectible aléatoire dans la salle"},
{"477","0","\3 Consomme tous les objets sur piédestal de la salle#Objets activables: les prochaines utilisations de Void auront l'effet de l'objet avalé (se cumule avec les autres objets)#\1 Objets passifs: Deux stats aléatoires sont augmentées"},
{"478","0","Paralyse tous les ennemis dans la salle jusqu'à ce que vous tiriez#Les ennemis paralysés peuvent toujours vous blesser"},
{"479","0","Détruit votre trinket et vous en octroie son effet de manière permanente"},
{"480","0","Fait apparaître une araignée/mouche pour chaque collectible dans la salle#Détruit tous les collectibles"},
{"481","0","Quand utilisé \1/\2 une petite quantité de stats aléatoires#Effet de larmes aléatoire pour la salle#Chamboule tous les sprites"},
{"482","0","Vous transforme en un autre personnage aléatoire#Fait disparaître le dernier objet récupéré"},
{"483","0","\3 USAGE UNIQUE \3 #Affecte l'étage entier#Détruit tous les rochers, pots, tonneaux, ...#Inflige 200 de dégâts à tous les ennemis#Ouvre: Salles secrètes / Boss Rush / Hush"},
{"484","0","Quand utilisé, repousse les ennemis et crée une vague de rochers"},
{"485","0","50% de chances de doubler les objets, collectibles et coffres de la salle#50% de chances de tout retirer et de laisser une pièce"},
{"486","0","Vous blesse sans vous retirer de coeur#Peut permettre d'activer l'effet de certains objets"},
{"487","0","Retire un coeur max et vous octroie \1 +0.2 dégât(s) et un 'Cube of Meat'"},
{"488","0","Active l'effet d'un objet aléatoire"},
{"489","0","Effet de dé aléatoire"},
{"490","0","\3 USAGE UNIQUE \3#Fait apparaître deux objets aléatoires en fonction de la salle dans laquelle vous vous trouvez"},
{"491","0","Lâche une pilule aléatoire toutes les 2 salles#Utiliser une pilule inflige des dégâts aux ennemis"},
{"492","0","\1 +1 Chance#Indique la localisation des rochers marqués, salles secrètes et échelles de cordes"},
{"493","5","Pour chaque réceptacle de coeur vide :#\1 +0.2 Dégât(s)"},
{"494","0","Larmes électriques#Les larmes font apparaître de 1 à 2 étincelles électriques en touchant quelque chose"},
{"495","0","Chance de tirer une flamme à la place d'une larme"},
{"496","5","Chance de tirer des seringues#Les seringues tuent les ennemis normaux en un coup"},
{"497","0","Camouflage au début de chaque salle#Le camouflage s'estompe quand Isaac tire des larmes"},
{"498","0","Fait apparaître les portes de Devil Deal et Angel Room#En entrant dans une, l'autre disparaît"},
{"499","0","\1 100% de chances de trouver une Angel Room"},
{"500","0","Peut lâcher des sacs"},
{"501","0","Vous donne un coeur max pour chaque tranche de 25 pièces#Keeper gagnera une pièce max (vie) supplémentaire"},
{"502","0","Chance de tirer une larme infligeant 200% de dégâts et laissant une traînée qui inflige des dégâts"},
{"503","0","Chance de tirer des larmes qui tuent instantanément les ennemis"},
{"504","0","Fait apparaître une mouche qui tire sur les ennemis"},
{"505","0","Fait apparaître un ennemi charmé aléatoire au début de chaque salle"},
{"506","0","Quand les larmes touchent le dos des ennemis, elles infligent le double de dégâts et provoquent saignement#Le saignement inflige 10% de dégâts sur la vie max de l'ennemi toutes les 5 secondes"},
{"507","0","Inflige vos dégâts + 10% de la vie max des ennemis#Concerne tous les ennemis de la salle#Chance de faire apparaître des demi-coeurs en infligeant des dégâts"},
{"508","6","Orbital causant un saignement#Le saignement inflige 10% de la vie max des ennemis sous forme de dégâts pendant 5 secondes"},
{"509","0","Toutes les 2 secondes, tire une larme dans une direction aléatoire"},
{"510","0","Fait apparaître une transformation Delirium d'un boss aléatoire#Ce boss est un allié"},
{"511","3","Tourne autour d'une ennemi aléatoire jusqu'à sa mort#Inflige des dégâts au corps à corps"},
{"512","0","Trou noir aspirant tout sur son passage"},
{"513","0","\1 +0.1 Dégât(s)#+1 coeur bleu#Chance aléatoire de séduire ou apeurer un ennemi#Chance de faire apparaître un caca arc-en-ciel en recevant des dégâts"},
{"514","0","Fait lagger les ennemis, les paralysant brièvement à des moments aléatoires"},
{"515","0","\3 USAGE UNIQUE \3#Fait apparaître un objet aléatoire correspondant à la salle d'utilisation#Chance de faire apparaître 'Lump Of Coal' ou 'The Poop' à la place"},
{"516","0","Fait apparaître un arroseur qui tourne sur lui-même tout en tirant des copies conformes de vos larmes#Synergie avec tous les types de larmes (Brimstone, lasers, ...)"},
{"517","0","+7 Bombes#Vous permet de rapidement poser les bombes sur le sol"},
{"518","0","Vous donne un familier ressemblant à un familier coop aléatoire#Possède un effet de larmes aléatoire#L'effet change à chaque étage"},
{"519","0","Un familier qui se transforme en un autre familier aléatoire toutes les 10 secondes"},
{"520","0","+1 charge sur l'objet actif tous les 15 ennemis tués"},
{"521","0","Rend un objet aléatoire du Shop gratuit"},
{"522","0","Les projectiles proches de vous sont gardés en lévitation pendant 3 secondes#Sont repoussés une fois ce délai écoulé#Se recharge après 2 secondes"},
{"523","0","Stocke les collectibles de la salle#Le réutiliser lâchera les collectibles stockés#Vous permet de déplacer les collectibles de salle en salle"},
{"524","0","Les larmes sont connectées entre elles par un rayon électrique"},
{"525","0","Prendre des dégâts fait apparaître un orbital#Max. 3 Orbitaux en même temps#Les orbitaux peuvent être détruits s'ils reçoivent trop de dégâts"},
{"526","0","Fait apparaître un Cavalier de l'Apocalypse aléatoire#Ce cavalier fait apparaître une mouche propre à lui"},
{"527","0","\3 Familier pouvant réaliser des tâches pour vous:#Ouvrir des portes/coffres, apporter des objets, voler au magasin / Devil Deal, combattre les ennemis, exploser et activer les interrupteurs"},
{"528","0","Les larmes qui traversent le prisme se divisent en 4"},
{"529","0","Les larmes vont se comporter comme des boules de billard"},
{"530","0","Octroie une récompense si vous tuez les ennemis dans l'ordre#Une marque indique quel ennemi tuer en priorité"},
{"531","0","Les larmes font des lobs#Se divisent en de plus petites larmes en touchant un ennemi"},
{"532","0","Les larmes ralentissent avec la distance#Une fois à l'arrêt, elle se divisent#Les larmes peuvent fusionner et créer des larmes plus grosses"},
{"533","0","Tire des rayons de lumière blanche#(Holy Brimstone)"},
{"534","0","Vous permet de tenir deux objets activables#Passez de l'un à l'autre avec CTRL (avec 'The Forgotten', maintenir CTRL)"},
{"535","0","+1 Coeur bleu#Donne un bouclier en entrant dans une salle de boss"},
{"536","0","Sacrifie un familier pour faire apparaître un objet de Devil Deal#Peut être utilisé 2 fois"},
{"537","0","+1 Pilule aléatoire#Familier laissant une traînée#Change la nature de la traînée lors de la consommation d'une pilule"},
{"538","0","Fait apparaître 3 trinkets aléatoires#Recevoir des dégâts peut vous octroyer l'effet du trinket tenu de manière permanente"},
{"539","0","Fait apparaître un ennemi envoûté en recevant des dégâts#Plus vous terminez de salles sans prendre de dégâts, plus l'ennemi envoûté sera puissant"},
{"540","0","Larmes rebondissantes faisant des dégâts d'éclaboussement à chaque rebond"},
{"541","0","+1 Coeur d'os#Fait apparaître 3 coeurs rouges"},
{"542","0","Orbital#Dévie les projectiles"},
{"543","0","Un caca blanc avec une aura apparaît quand Isaac reçoit des dégâts#\1 Cadence de tir dans l'aura"},
{"544","0","Clou lévitant devant Isaac#Inflige 6 fois vos dégâts"},
{"545","12","Fait apparaître un os orbital ou un squelette envoûté pour chaque ennemi tué dans la salle"},
{"546","0","Offre une aura qui paralyse les ennemis"},
{"547","0","+1 Coeur d'os#\1 +0.7 Cadence de tir#Fait apparaître un trinket papier mystérieux"},
{"548","0","Familier boomerang#Inflige 2x les dégâts d'Isaac"},
{"549","0","Remplace tous vos coeurs par 6 coeurs d'os#Perdre un coeur d'os lance des os dans toutes les directions"},
{"550","0","Mom's Foot ne cessera de vous viser#Utiliser cet objet empêchera Mom's Foot de vous tomber dessus#\3 (Essayez de terminer le Boss Rush avec la pelle en votre possession)"},
{"551","0","Deuxième partie d'une pelle brisée#\3 Utilisez la pelle près de la pile de terre dans la 'Dark Room'"},
{"552","6","Fait apparaître une trappe vers l'étage suivant#\3 Utilisez la pelle près de la pile de terre dans la 'Dark Room'#\3 Débloque quelque chose de cool"}
}

---------- Trinkets ----------
trinketdescriptions={{"1","Lâche une pièce quand vous vous faites toucher"},
{"2","Plus de chances d'obtenir des récompenses en détruisant les cacas"},
{"3","-1 charge nécessaire pour les objets activables"},
{"4","Vous téléporte dans une salle aléatoire quand vous utilisez un objet"},
{"5","Ennemis d'élite plus fréquents#Plus de chances de trouver des challenges rooms"},
{"6","Aimant à pièces"},
{"7","Plus de chances de trouver une Angel Room"},
{"8","Chance de devenir Pacman en vous faisant toucher"},
{"9","Larmes vibrantes#Affecte la hitbox des larmes"},
{"10","Les larmes font des vagues#\1 Cadence de tir"},
{"11","Les larmes bougent en spirale"},
{"12","Larmes plus grosses"},
{"13","Un objet du Shop gratuit"},
{"14","Les pics et flaques ne vous infligent plus de dégâts"},
{"15","Détruire un rocher fait tomber une pièce"},
{"16","Mom's foot tombe sur les ennemis toutes les 60 secondes"},
{"17","Coeurs noirs plus fréquents"},
{"18","Coeurs blancs plus fréquents"},
{"19","Ouvre les coffres sans consommer de clef"},
{"20","En tombant à 1/2 coeur rouge, fait apparaître un coeur noir#\3 3 utilisations"},
{"21","Imite 'Polaroid', 'The Negative','Missing Poster' et 'Missing Page'#Faible chance d'activation"},
{"22","\3 Convertit tous les coeurs collectibles en coeurs noirs#Le taux de drop de coeurs est réduit"},
{"23","Réapparaîssez en 'The Lost' lorsque vous mourez dans une salle du sacrifice#Débloque 'The Lost' si vous ne le possédez pas encore"},
{"24","Pétez en ramassant des pièces"},
{"25","Pétez ou faites apparaître un caca toutes les 30 secondes"},
{"26","Les larmes bougent en faisant des angles"},
{"27","\1 +0.5 Vitesse des larmes"},
{"28","22% de réapparaître en tant que 'Blue Baby' en mourant"},
{"29","Fait apparaître une mouche en vous faisant toucher"},
{"30","Chance de tirer des larmes empoisonnées"},
{"31","Chance de tirer des larmes transperçantes"},
{"32","Effet de champignon aléatoire à chaque salle#Chance de révéler les salles spéciales en changeant de salle"},
{"33","En tombant à 1/2 coeur rouge, fait apparaître 'Little Steven'"},
{"34","Coeurs rouges plus fréquents"},
{"35","\1 +2 Dégâts"},
{"36","Clefs et coffres plus fréquents"},
{"37","\1 +0.15 Vitesse"},
{"38","Coeurs bleus plus fréquents"},
{"39","\1 Cadence de tir"},
{"40","\1 Chance de gagner +1.8 dégâts en vous faisant toucher"},
{"41","Bombes plus fréquentes#\3 Enlève 'The Tick'"},
{"42","\1 +1 Chance"},
{"43","En tombant à 1/2 coeur, vous téléporte dans une salle déjà visitée"},
{"44","Pilules plus fréquentes"},
{"45","Cartes plus fréquentes"},
{"46","Chance de régénérer 1/2 coeur en vidant une salle"},
{"47","<inutilisé>"},
{"48","Chance d'infliger 40 de dégâts à tous les ennemis en vous faisant toucher"},
{"49","Ramasser des pièces fait apparaître des demi-coeurs rouges"},
{"50","Ramasser des pièces fait apparaître des bombes"},
{"51","Ramasser des pièces fait apparaître des clefs"},
{"52","Chance d'obtenir une pièce supplémentaire en ramassant des pièces"},
{"53","Les boss ont -15% de vie#Soigne un coeur rouge en rentrant dans une salle de boss"},
{"54","Familier à larmes transperçantes"},
{"55","Obtenez un coeur blanc en changeant d'étage"},
{"56","Réduit le prix des Devil Deals"},
{"57","Familier bondissant à travers la salle#tire dans la même direction qu'Isaac"},
{"58","\1 Chance de ganger +0.5 dégâts en tuant un ennemi"},
{"59","25% de chances de révéler les icônes sur la carte au début de chaque étage"},
{"60","Chance de faire apparaître un oiseau mort en tuant un ennemi"},
{"61","Transforme tous les coffres en coffres rouges"},
{"62","Les rochers marqués / cachant une trappe brillent"},
{"63","Transforme les bombes trolles en bombes normales"},
{"64","Effet de ver aléatoire"},
{"65","\1 Double votre portée"},
{"66","\2 -0.4 Vitesse des larmes#\1 +4 Portée"},
{"67","Effet de dé aléatoire en vous faisant toucher"},
{"68","Aimant pour collectibles et ennemis"},
{"69","Peut camoufler le joueur#Être camouflé rend les ennemis confus"},
{"70","Chance de faire apparaître des araignées bleues dans les salles hostiles"},
{"71","Les bombes laissent du résidu sur le sol infligeant des dégâts"},
{"72","Batteries plus fréquentes"},
{"73","Les bombes qui explosent peuvent faire tomber une bombe collectable"},
{"74","Échelles de corde plus fréquentes"},
{"75","Effet de trinket aléatoire à chaque salle"},
{"76","50% de chances de doubler les récompenses des coffres#50% de chances d'ouvrir un coffre vide ou contenant un ennemi"},
{"77","Augmente le recul de vos larmes"},
{"78","Effets de statuts plus longs sur les ennemis (empoisonnements, brûlures, ...)"},
{"79","Utiliser une pilule/carte peut faire tomber une autre pilule/carte"},
{"80","\1 +0.2 dégâts pour chaque objet démoniaque en votre possession"},
{"81","L'invincibilité dure plus longtemps"},
{"82","+15% de chances d'avoir 2 item rooms à l'étage suivant"},
{"83","Ouvre les Shops gratuitement"},
{"84","Greed/Super Greed n'apparaîssent plus dans les Shops"},
{"85","Utiliser une machine de donation peut vous soigner ou faire apparaître un mendiant"},
{"86","Détruire un caca fait apparaître une mouche bleue"},
{"87","Utiliser une clef soigne d'un demi-coeur rouge#Les demi-coeurs sur le sol se transforment en coeurs entiers"},
{"88","Chances diminuées de trouver un objet activable dans les item rooms"},
{"89","Les familiers sont plus proches les uns des autres"},
{"90","Les cacas explosent quand ils sont détruits"},
{"91","Cacas noirs plus fréquents"},
{"92","\1 Les augmentations de stats de vos objets sont 33% plus efficaces#\1 +0.2 Cadence de tir"},
{"93","Les mouches ennemies sont inoffensives"},
{"94","Double les apparitions de mouches/araignées bleues"},
{"95","Chance de tirer des dents empoisonnées"},
{"96","Les larmes bougent rapidement en spirale"},
{"97","Recevoir des dégâts peut faire apparaître un familier#Jusqu'à 2 familiers possibles"},
{"98","Chance de tirer des larmes empoisonnées collantes#Ces larmes se détachent quand l'ennemi saute/se téléporte/meurt"},
{"99","Chance de tirer des larmes rebondissantes"},
{"100","\3 En tenant un objet activable pleinement chargé:#\1 +0.25 Vitesse#\1 +0.75 Portée#\1 +0.2 Cadence de tir#\1 +0.10 Vitesse des larmes#\1 +0.5 Dégâts#\1 +1 Chance"},
{"101","\3 En tenant un objet activable complètement déchargé:#\1 +0.5 Vitesse#\1 +1.5 Portée#\1 +0.4 Cadence de tir#\1 +0.3 Vitesse des larmes#\1 +1.5 Dégâts#\1 +2 Chance"},
{"102","+1 Secret Room supplémentaire à chaque étage"},
{"103","\3 En possédant le même nombre de pièces, clefs et bombes:#Transforme les moitiés de consommables en double consommables"},
{"104","Chance de faire apparaître un objet sur piédestal en vous faisant toucher#S'autodétruit après coup"},
{"105","Chance de faire apparaître un objet donnant un coeur max supplémentaire#S'autodétruit après coup"},
{"106","Aumgente la taille des flaques que vous créez"},
{"107","Vous faire toucher affectera vos coeurs rouges avant vos coeurs bleus/noirs"},
{"108","En vous faisant toucher, lâche un trinket/collectible aléatoire#S'autodétruit après coup"}, -- Needs update that its only drops when hit by an explosion
{"109","Vos orbitaux ne bougent plus"},
{"110","Les Shops apparaîssent maintenant dans le Womb"},
{"111","Les item rooms apparaîssent maintenant dans le Womb"},
{"112","Les item rooms possèderont d'office une machine de relance"},
{"113","Fait apparaître une mouche explosive en rentrant dans une salle hostile"},
{"114","Fait apparaître une mouche empoisonnée en rentrant dans une salle hostile"},
{"115","Fait apparaître une mouche qui ralentit les ennemis en rentrant dans une salle hostile"},
{"116","Fait apparaître une mouche infligeant 4X vos dégâts en rentrant dans une salle hostile"},
{"117","Fait apparaître 2-5 mouches bleues en rentrant dans une salle hostile"},
{"118","Chance de voler en recevant des dégâts#Ne dure que pour une seule salle"},
{"119","Soigne d'un demi-coeur en changeant d'étage"},
{"120","Recharge complètement votre objet activable en entrant dans une salle de boss"},
{"121","Vous protège du premier coup reçu à chaque étage"},
{"122","Utiliser votre objet actif le place sur un piédestal"},
{"123","Oblige les anges à lâcher un objet au lieu de morceaux de clefs"},
{"124","La dernière porte que vous ouvrez reste ouverte"},
{"125","Vos familiers sont connectés par un rayon électrique"},
{"126","Fait apparaître une mouche bleue en ramassant une pièce"},
{"127","Les larmes de vos familiers sont à tête chercheuse"},
{"128","Petite chance d'obtenir un coeur d'os en recevant des dégâts"}
}

---------- Cards ----------
cardDescriptions={{"1","Vous téléporte à la salle de départ"},
{"2","Larmes à tête chercheuse pour la salle"},
{"3","Mom's Foot tombe sur un ennemi!"},
{"4","\1 +2.35 Dégâts & +0.3 vitesse pour la salle"},
{"5","Vous téléporte à la salle de boss"},
{"6","Lâche 2 coeurs bleus"},
{"7","Lâche 2 coeurs rouges"},
{"8","Invincibilité et dégâts au corps à corps pendant 6 secondes"},
{"9","Lâche une clef, une bombe, une pièce et un coeur"},
{"10","Vous téléporte au Shop"},
{"11","Fait apparaître une machine de casino"},
{"12","\1 +1 Vie Max#\1 +0.3 Dégâts#\1 +0.3 Vitesse#Pour la salle actuelle"},
{"13","Vous permet de voler dans la salle actuelle"},
{"14","Inflige 40 de dégâts à tous les ennemis de la salle"},
{"15","Fait apparaître une machine de don du sang"},
{"16","\1 +2 Dégâts pour la salle"},
{"17","Fait apparaître des bombes trolles"},
{"18","Vous téléporte à l'Item Room"},
{"19","Vous téléporte à la salle secrète"},
{"20","Inflige 100 de dégâts à tous les ennemis de la salle#Soin complet#Révèle toute la carte"},
{"21","Fait apparaître un mendiant"},
{"22","Révèle l'entièreté de l'étage"},
{"23","Double vos bombes"},
{"24","Double votre argent"},
{"25","Double vos clefs"},
{"26","Double vos coeurs rouges#Ne fonctionne que quand utilisé comme soin"},
{"27","Transforme tous les collectibles en bombes"},
{"28","Transforme tous les collectibles en pièces"},
{"29","Transforme tous les collectibles en clefs"},
{"30","Transforme tous les collectibles en coeurs rouges"},
{"31","Vous téléporte à la salle de Devil Deal/Angel Room"},
{"32","Détruit tous les rochers de la salle"},
{"33","Double tous les collectibles de la salle"},
{"34","Fait apparaître une trappe"},
{"35","+1 Coeur Bleu#Annule toutes les malédictions"},
{"36","Révèle l'entièreté de l'étage"},
{"37","Change les objets sur piédestal présents dans la salle"},
{"38","Fait apparaître 3 mouches bleues et 3 araignées bleues"},
{"39","Invincibilité pendant 30 secondes"},
{"40","Effet de rune aléatoire"},
{"41","Inflige 40 de dégâts à tous les ennemis dans la salle#Stat aléatoire augmentée pour chaque objet sur piédestal présent dans la salle#(Détruis tous les objets sur piédestal présents dans la salle)"},
{"42","Lancer de carte tuant n'importe quel ennemi en un coup"},
{"43","Rend tous les objets à la vente (Shop, Black Market ou Devil Deal) gratuits"},
{"44","Donne des conseils 'utiles'"},
{"45","Remplit la salle de cacas"},
{"46","Vous tue instantanément et fait apparaître 10 collectibles dans la salle"},
{"47","Ouvre toutes les portes de la salle"},
{"48","Utilise votre objet activable sans le décharger"},
{"49","Change les objets sur piédestal et collectibles dans la salle"},
{"50","2 mains de Mom tombent du ciel sur un ennemi et les paralysent"},
{"51","Vous donne l'effet de Holy Mantle pour la salle#(Annule les prochains dégâts reçus)"},
{"52","\1 +7 Dégâts#\1 +30 Portée#\1 Taille +#Écrasez les rochers#L'effet s'estompe en changeant de salle#Avec Kepper, permet de gagner une pièce max si vous ne possédez qu'une seule pièce"},
{"53","Lâche 3 cartes aléatoires"},
{"54","Ralentit les ennemis et les larmes d'Isaac et augmente sa vitesse#L'effet s'estompe en changeant de salle"}}


---------- Pills ----------

unidentifiedPillMessage = "- Pilule non identifiée"

pillDescriptions={
{"0","Fait apparaître un nuage de gaz"},
{"1","Inflige 1 coeur de dégâts"},
{"2","+2 Coeurs Bleus"},
{"3","Inverse le nombre de bombes avec le nombre de clefs"},
{"4","Lâche 5 bombes trolles"},
{"5","Soin complet"},
{"6","\2 -1 Coeur Max"},
{"7","\1 +1 Coeur Max"},
{"8","Aucun effet"},
{"9","En manger 3 vous donnera un coeur max supplémentaire"},
{"10","Ajoute une mouche orbitale pouvant bloquer les projectiles"},
{"11","\2 -2 Portée"},
{"12","\1 +2.5 Portée"},
{"13","\2 -0.12 Vitesse"},
{"14","\1 +0.15 Vitesse"},
{"15","\2 -0.28 Cadence de tir"},
{"16","\1 +0.35 Cadence de tir"},
{"17","\2 -1 Chance"},
{"18","\1 +1 Chance"},
{"19","Vous téléporte dans une salle aléatoire"},
{"20","Recharge votre objet activable#Lâche 1-2 batteries"},
{"21","Supprime tous vos coeurs rouges sauf 1#Lâche 1 à 4 coeurs rouges"},
{"22","Paralysé pendant quelques secondes"},
{"23","Ouvre les salles secrètes de l'étage"},
{"24","Envoûte tous les ennemis dans la salle"},
{"25","Cache le plan de l'étage"},
{"26","Lâche une grosse flaque sur le sol qui inflige des dégâts aux ennemis"},
{"27","Tirez en diagonale pendant 60 secondes"},
{"28","Ne perdez pas plus de 1/2 coeur à la fois en recevant des dégâts#L'effet s'estompe en changeant de salle"}, -- One Room Wafer
{"29","Perdez un coeur rouge"},
{"30","Fait apparaître des cacas sur votre passage pendant 2 secondes"},
{"31","Effet 'Curse of the Maze' pour la salle (franchir une porte peut vous téléporter dans une autre salle)"},
{"32","Isaac grandit#N'affecte pas sa hitbox"},
{"33","Isaac rapetissit#Diminue sa hitbox"},
{"34","Fait appraître une araignée bleue pour chaque caca dans la salle"},
{"35","Fait apparaître une araignée bleue pour chaque ennemi dans la salle#Fait apparaître 1-3 araignées quand aucun ennemi n'est dans la salle"},
{"36","Courte invincibilité"},
{"37","Pixellise l'écran pendant 30 secondes"},
{"38","Fait appraître 3 mouches bleues"},
{"39","Fait apparaître une flaque glissante"},
{"40","Fait appraître une flaque qui ralentit les ennemis"},
{"41","Ralentit tous les ennemis dans la salle"},
{"42","Accélère tous les ennemis dans la salle"},
{"43","Consomme votre trinket actuel et vous donne son effet de façon permanente"},
{"44","Tire une larme d'Isaac"},
{"45","Courte invincibilité"},
{"46","Lâche une copie de la dernière pilule consommée"}
} 

---------- Sacrifice Room ----------
sacrificeDescriptionHeader = "[Prochaine récompense de sacrifice]"

sacrificeDescriptions={
{"1","50% chances d'avoir 1 pièce#100% chances d'avoir 1 bombe, en étant au premier étage et en ayant vaincu le premier boss en moins d'une minute"},
{"2","50% chances d'avoir 1 pièce#100% chances d'avoir 1 bombe, en étant au premier étage et en ayant vaincu le premier boss en moins d'une minute"},
{"3","67% chances d'augmenter les probabilités d'avoir une Angel Room à la fin du combat de boss"},
{"4","50% chances d'avoir 1 coffre aléatoire"},
{"5","33% chances d'avoir 3 pièces#67% d'augmenter les probabilités d'avoir une Angel Room à la fin du combat de boss"},
{"6","33% chances de vous téléporter au Devil Deal ou à l'Angel Room#67% chances d'avoir un coffre aléatoire"},
{"7","33% chances d'avoir 1 objet d'Angel Room#67% chances d'avoir 1 coeur bleu"},
{"8","100% chances de faire apparaître 7 bombes trolles"},
{"9","100% chances de faire apparaître le boss 'Uriel'"},
{"10","50% chances d'avoir 7 coeurs bleus#50% chances d'avoir 30 pièces"},
{"11","100% chance de faire apparaître le boss 'Gabriel'"},
{"12","50% chances de vous téléporter à la Dark Room"}
}
---------- Dice Room ----------
diceDescriptionHeader = "[Effet de Dé]"

diceDescriptions={
{"1","Transforme tous vos objets#(n'affecte que les collectibles)"},
{"2","Transforme tous les collectibles dans la salle"},
{"3","Transforme tous les collectibles de l'étage"},
{"4","Transforme tous les objets sur piédestal de l'étage#N'affecte pas les Devil Deals"},
{"5","Transforme l'étage entier et le relance"},
{"6","Transforme tous vos objets, les objets sur piédestal et collectibles de l'étage"}
}

---------- Transformations ----------
transformations = {
"",					-- 0 = none
"Guppy",			-- 1
"Fun Guy",			-- 2
"Lord of the Flies",-- 3
"Conjoined",		-- 4
"Spun",				-- 5
"Mom",				-- 6
"Oh crap",			-- 7
"Bob",				-- 8
"Leviathan",		-- 9
"Seraphim",			-- 10
"Super Bum",		-- 11
"Bookworm",			-- 12
"Spider Baby"		-- 13
}
