---------------------------------------
-----  Basic Italian descriptions  ----
---------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

local languageCode = "it"

-- init it table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "Italian"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts


---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "La Cipolla Triste", "↑ {{Tears}} +0.7 Lacrime"},
	{"2", "Il Terzo Occhio", "↓ {{Tears}} Meno lacrime#Isaac spara 3 lacrime alla volta"},
	{"3", "Piega-cucchiai", "Lacrime a ricerca"},
	{"4", "Testa di Cricket", "↑ {{Damage}} +0.5 Danni#↑ {{Damage}} x1.5 Moltiplicatore Danni"},
	{"5", "Il Mio Riflesso", "↑ {{Range}} +1.5 Gittata#↑ +1 Altezza Lacrime#↑ {{Shotspeed}} +0.6 Velocità Colpi#Le lacrime ottengono un effetto boomerang"},
	{"6", "La Numero Uno", "↑  +1.5 Lacrime#↓ -15.78 Gittata#↑ +0.45 Altezza Lacrime"},
	{"7", "Sangue Del Martire", "↑ {{Damage}} +1 Danni#{{Collectible34}} x1.5 Moltiplicatore Danni se sono attivi gli effetti di \"Il Libro di Belial\" o di \"XV - Il Diavolo\""},
	{"8", "Fratello Bobby", "Spara lacrime normali#Infligge 3.5 danni a lacrima"},
	{"9", "Scatolo", "Tutte le mosche nemiche sono amichevoli"},
	{"10", "Aureola Di Mosche", "+2 Mosche orbitali#Blocca i proiettili nemici"},
	{"11", "1up!", "↑ +1 vita#Una volta morto Isaac resuscita con la salute al massimo"},
	{"12", "Fungo Magico", "↑ {{Heart}} +1 Salute#↑ {{Speed}} +0.3 Velocità#↑ {{Damage}} +0.3 Danni#↑ {{Damage}} x1.5 Moltiplicatore Danni#↑ {{Range}} +5.25 Range#↑ +0.5 Altezza Lacrime#Aumento taglia#{{Heart}} Salute al massimo"},
	{"13", "Il Virus", "↓ {{Speed}} -0.1 Velocità#{{Poison}} Toccare i nemici li avvelena#{{BlackHeart}} I nemici avvelenati possono lasciare Cuori Neri"},
	{"14", "Iniezione di Ferocia", "↑ {{Speed}} +0.6 Velocità#↑ {{Range}} +5.25 Gittata#↑ +0.5 Altezza Lacrime"},
	{"15", "<3", "↑ {{Heart}} +1 Salute#{{Heart}} Salute al massimo"},
	{"16", "Fegato Crudo", "↑ {{Heart}} +2 Salute#{{Heart}} Salute al massimo"},
	{"17", "Passepartout", "{{Key}} +99 Chiavi"},
	{"18", "Un Dollaro", "{{Coin}} +99 Monete"},
	{"19", "Bum!", "{{Bomb}} +10 Bombe"},
	{"20", "Trascendenza", "Volo"},
	{"21", "La Bussola", "Rivela tutte le icone sulla mappa#Non mostra il layout della mappa"},
	{"22", "Pranzo", "↑ {{Heart}} +1 Salute"},
	{"23", "Cena", "↑ {{Heart}} +1 Salute"},
	{"24", "Dessert", "↑ {{Heart}} +1 Salute"},
	{"25", "Colazione", "↑ {{Heart}} +1 Salute"},
	{"26", "Carne Marcia", "↑ {{Heart}} +1 Salute"},
	{"27", "Mestolo", "↑ {{Speed}} +0.3 Velocità"},
	{"28", "La Cintura", "↑ {{Speed}} +0.3 Velocità"},
	{"29", "Mutande di Mamma", "↑ {{Range}} +5.25 Gittata#↑ +0.5 Altezza Lacrime"},
	{"30", "Tacchi di Mamma", "↑ {{Range}} +5.25 Gittata#↑ +0.5 Altezza Lacrime"},
	{"31", "Rossetto di Mamma", "↑ {{Range}} +5.25 Gittata#↑ +0.5 Altezza Lacrime"},
	{"32", "Gruccia di Ferro", "↑ {{Tears}} +0.7 Lacrime"},
	{"33", "La Bibbia", "{{Timer}} Volo per la stanza#{{MomsHeart}} Uccide Mamma, Cuore di Mamma e \"È Vivo!\" all'istante#{{Warning}} Se usato contro Satana uccide Isaac all'istante"},
	{"34", "Il Libro di Belial", "{{AngelDevilChance}} +12.5% di chance di una Stanza del Diavolo/dell'Angelo mentre viene tenuto#{{Timer}} Ricevi per la stanza:#↑ {{Damage}} +2 Danni#{{Collectible7}} x1.5 Moltiplicatore Danni se Isaac possiede \"Sangue del Martire\""},
	{"35", "Il Necronomicon", "Infligge 40 danni a tutti i nemici nella stanza"},
	{"36", "La Cacca", "Genera una cacca e respinge i nemici#Può essere piazzata vicino a una fossa e distrutta con una bomba per creare un ponte"},
	{"37", "Sig. Bum", "Lascia una grossa bomba ai piedi di Isaac che infligge 110 danni"},
	{"38", "Testa di Tammy", "Spara 10 lacrime in cerchio attorno ad Isaac#Le lacrime copiano gli effetti delle lacrime di Isaac, e fanno 25 danni in più"},
	{"39", "Reggiseno di Mamma", "Pietrifica tutti i nemici nella stanza per 4 secondi"},
	{"40", "Kamikaze!", "Produce un'esplosione nella posizione di Isaac#Infligge 40 danni"},
	{"41", "Assorbente di Mamma", "{{Fear}} Spaventa tutti i nemici nella stanza per 5 secondi"},
	{"42", "Testa Marcia di Bob", "Usare l'oggetto e sparare in una direzione fa scagliare la testa#{{Poison}} La testa esplode nel luogo in cui atterra e avvelena i nemici colpiti dall'esplosione"},
	{"43", "", "<L'oggetto non esiste>"},
	{"44", "Teletrasporto!", "Teletrasporta Isaac in una stanza casuale che non sia una stanza I AM ERROR"},
	{"45", "Cuore Gustoso", "{{Heart}} Cura 1 cuore"},
	{"46", "Piede Fortunato", "↑ {{Luck}} +1 Fortuna#+8% di chance di una ricompensa a completamento stanza#Più alte chance di vittoria nel gioco d'azzardo"},
	{"47", "Telecomando del Dottore", "{{Collectible168}} Se usato, appare un mirino direzionabile#Un missile colpisce il mirino dopo 1.5 secondi#Infligge i danni di Isaac x20"},
	{"48", "Freccia di Cupido", "Lacrime perforanti"},
	{"49", "Shoop da Whoop!", "{{Collectible118}}Usare l'oggetto e sparare in una direzione aziona un raggio di Zolfo Fuso dai danni ingenti"},
	{"50", "Steven", "↑ {{Damage}} +1 Danni"},
	{"51", "Pentagramma", "↑ {{Damage}} +1 Danni#{{AngelDevilChance}} +10% di chance di una Stanza del Diavolo/dell'Angelo)"},
	{"52", "Dr. Fetus", "↓ {{Tears}} x2.5 Moltiplicatore del delay tra lacrime#{{Bomb}} Isaac spara bombe al posto delle lacrime#{{Damage}} Tali bombe infliggono x5 di danni delle lacrime di Isaac + 30"},
	{"53", "Magneto", "Isaac attrae a sé i consumabili"},
	{"54", "Mappa del Tesoro", "Rivela il layout del piano#Non rivela le icone delle stanze"},
	{"55", "Occhio di Mamma", "50% di chance di sparare una lacrima in più all'indietro#{{Luck}} 100% di chance con 2 di Fortuna"},
	{"56", "Limonata Accidentale", "Versa una pozza di liquido#TIl liquido infligge 24 danni da contatto al secondo"},
	{"57", "Ammiratore Segreto", "Mosca orbitale a medio raggio#Infligge 75 danni da contatto al secondo"},
	{"58", "Libro delle Ombre", "{{Timer}} Invincibilità per 10 secondi"},
	{"59", "", "<L'oggetto non esiste>"},
	{"60", "La Scala", "Permette ad Isaac di superare varchi da 1 casella"},
	{"61", "", "<L'oggetto non esiste>"},
	{"62", "Fascino del Vampiro", "{{HalfHeart}} Uccidere 13 nemici cura di mezzo cuore"},
	{"63", "La Batteria", "{{Battery}} Gli oggetti attivi possono essere doppiamente carichi e venire usati due volte di fila"},
	{"64", "Saldi di Steam", "{{Shop}} Gli oggetti del Negozio costano il 50% in meno#Avere 2 Saldi Steam renderà tutto gratis"},
	{"65", "Ricette dell'Anarchico", "Evoca 6 Bombe Troll intorno al centro della stanza"},
	{"66", "La Clessidra", "{{Slow}} Rallenta i nemici per 8 secondi"},
	{"67", "Sorella Maggy", "Spara lacrime normali#Infligge 3.5 danni a lacrima"},
	{"68", "Tecnologia", "Isaac spara laser al posto delle lacrime"},
	{"69", "Latte al Cioccolato", "{{Chargeable}} Lacrime caricabili#{{Damage}} I danni scalano con il tempo di carica, fino a x4#{{Tears}} Tempo massimo di carica è x2.5 del delay tra lacrime"},
	{"70", "Ormoni della Crescita", "↑ {{Speed}} +0.4 Velocità#↑ {{Damage}} +1 Danni"},
	{"71", "Mini Fungo", "↑ {{Speed}} +0.3 Velocità#↑ +1.5 Altezza Lacrime#↑ Riduzione taglia#↓ {{Range}} -4.25 Gittata#Aumento Altezza Lacrime e meno Gittata = leggero aumento di Gittata"},
	{"72", "Rosario", "{{SoulHeart}} +3 Cuori Celesti#{{Collectible33}} La Bibbia viene aggiunta a tutti i pool degli oggetti"},
	{"73", "Cubo di Carne", "Lv1: Orbitale#Lv2: Orbitale che spara#Lv3: Meat Boy#Lv4: Super Meat Boy"},
	{"74", "Un Quarto", "{{Coin}} +25 Monete"},
	{"75", "Dottorato", "{{Heart}} Cura 2 cuori#{{Pill}} Genera 1 pillola#{{Pill}} Converte le pillole negative in positive#{{BloodDonationMachine}} Le Macchine di Donazione Sangue e {{Collectible135}} Flebo concedono più {{Coin}} monete"},
	{"76", "Vista a Raggi-X", "{{SecretRoom}} Apre tutte le entrate per le stanze segrete"},
	{"77", "Il mio Piccolo Unicorno", "{{Timer}} Ricevi per 6 secondi:#↑ {{Speed}} +0.28 Velocità#Invincibilità#Isaac non può sparare ma infligge 40 danni da contatto al secondo"},
	{"78", "Libro dell'Apocalisse", "{{SoulHeart}} +1 Cuore Celeste#{{AngelDevilChance}} +17.5% di chance di una Stanza del Diavolo/dell'Angelo mentre viene tenuto#Più alte chance di boss Cavalieri se usato"},
	{"79", "Il Marchio", "↑ {{Speed}} +0.2 Velocità#↑ {{Damage}} +1 Danni#{{SoulHeart}} +1 Cuore Celeste"},
	{"80", "Il Patto", "↑ {{Tears}} +0.7 Lacrime#↑ {{Damage}} +0.5 Danni#{{SoulHeart}} +2 Cuori Celesti"},
	{"81", "Gatto Morto", "↑ +9 Vite#Una volta morto Isaac resuscita con 1 portacuori#{{Warning}} Quando viene raccolto imposta i portacuori di Isaac ad 1"},
	{"82", "Signore dell'Abisso", "↑ {{Speed}} +0.3 Velocità#Volo"},
	{"83", "Il Chiodo", "Se usato:#{{SoulHeart}} +1 Cuore Celeste#{{Timer}} Ricevi per la stanza:#↑ {{Damage}} +0.7 Danni#↓ {{Speed}} -0.18 Velocità#Isaac infligge 40 danni da contatto al secondo#Permette ad Isaac di distruggere le rocce camminandoci sopra"},
	{"84", "Scaviamo più a Fondo!", "Apre una botola per il prossimo piano#{{LadderRoom}} 10% di possibilità di aprire una botola con una Stanza Cunicolo"},
	{"85", "Mazzo di Carte", "{{Card}} Genera una Carta"},
	{"86", "Dente di Monstro", "Monstro cade su un nemico e infligge 120 danni#{{Warning}} Se la stanza non ha nemici Monstro cade su Isaac"},
	{"87", "Corna di Loki", "25% di chance di sparare in 4 direzioni#{{Luck}} 100% di chance con 7 di Fortuna"},
	{"88", "Cicciottella", "Si lancia nella direzione in cui Isaac sta sparando#Infligge 52.5 danni di contatto al secondo"},
	{"89", "Morso di Ragno", "{{Slow}} 25% di chance di sparare lacrime rallentanti#{{Luck}} 100% di chance con 15 di Fortuna"},
	{"90", "La Pietruzza", "↑ {{Tears}} +0.2 Lacrime#↑ {{Damage}} +1 Danni#↓ {{Speed}} -0.2 Velocità"},
	{"91", "Casco da Minatore", "Rivela il tipo di stanza delle stanze adiacenti#{{SecretRoom}} Può rivelare Stanze Segrete e Super Segrete"},
	{"92", "Super Cerotto", "↑ {{Heart}} +1 Salute#{{Heart}} Cura 1 cuore#{{SoulHeart}} +2 Cuori Celesti"},
	{"93", "Il Gamekid", "{{Timer}} Ricevi per 6.5 secondi:#Invincibilità#Isaac non può sparare ma infligge 40 danni da contatto al secondo#{{HalfHeart}} Uccidere 2 nemici cura di mezzo cuore#{{Fear}} Spaventa tutti i nemici nella stanza"},
	{"94", "Sacco di Penny", "{{Coin}} Genera una moneta casuale ogni 2 stanze"},
	{"95", "Robo-Bebè", "Spara laser#Infligge 3.5 danni a colpo"},
	{"96", "Piccola C.H.A.D.", "{{HalfHeart}} Genera mezzo Cuore Rosso ogni 3 stanze"},
	{"97", "Il Libro del Peccato", "Genera un consumabile casuale"},
	{"98", "La Reliquia", "{{SoulHeart}} Evoca 1 Cuore Celeste per ogni 5-6 stanze"},
	{"99", "Piccolo Gish", "{{Slow}} Spara proiettili rallentanti#Infligge 3.5 danni a lacrima"},
	{"100", "Piccolo Steven", "Spara proiettili a ricerca#Infligge 3.5 danni a lacrima"},
	{"101", "L'Aureola", "↑ {{Heart}} +1 Salute#↑ {{Speed}} +0.3 Velocità#↑ {{Tears}} +0.2 Lacrime#↑ {{Damage}} +0.3 Danni#↑ {{Range}} +0.25 Gittata#↑ +0.5 Altezza Lacrime"},
	{"102", "Boccetta di Mamma", "{{Pill}} Genera 1 pillola"},
	{"103", "Il Raffreddore", "{{Poison}} 25% di chance di sparare lacrime velenose#{{Luck}} 100% di chance con 12 di Fortuna"},
	{"104", "Il Parassita", "Al contatto le lacrime si scindono in due#Le lacrime scisse infliggono metà dei danni"},
	{"105", "Il D6", "Rimpiazza i piedistalli nella stanza attuale"},
	{"106", "Mr. Mega", "↑ {{Bomb}} x1.83 danni delle bombe#{{Bomb}} +5 Bombe"},
	{"107", "Forbici Seghettate", "{{Timer}} Ricevi per la stanze:#Volo#Il corpo di Isaac si separa dalla testa e attacca i nemici con 82.5 danni da contatto al secondo"},
	{"108", "L'Ostia", "Riduce la maggior parte dei danni presi a mezzo cuore#Non funziona con il Mercante o il Mercante Corrotto"},
	{"109", "Soldi = Forza", "↑ +0.04 Danni per ogni {{Coin}} moneta che ha Isaac"},
	{"110", "Lentine di Mamma", "↑ {{Range}} +0.25 Gitttata#↑ +0.5 Altezza Lacrime#20% di chance di sparare lacrime pietrificanti#{{Luck}} 50% di chance con 20 di Fortuna"},
	{"111", "Il Fagiolo", "{{Poison}} Scorreggia una nube velenosa#Il veleno infligge i danni di Isaac per 6 volte"},
	{"112", "Angelo Custode", "Orbitale#Velocizza tutti gli altri orbitali#Blocca i proiettili#Infligge 105 danni da contatto al secondo"},
	{"113", "Bebè Demone", "Spara ai nemici che gli si avvicinano#Infligge 3 danni a lacrima"},
	{"114", "Coltello di Mamma", "Le lacrime di Isaac vengono sostituite da un coltello lanciabile#{{Damage}} Il coltello infligge i danni di Isaac x20 mentre viene tenuto e x6 alla massima distanza possibile"},
	{"115", "Tavola Ouija", "Lacrime spettrali"},
	{"116", "9 Volt", "{{Battery}} Carica automaticamente la prima barra degli oggetti attivi#{{Battery}} Quando viene raccolto ricarica completamente l'oggetto attivo"},
	{"117", "Uccello Morto", "Venire colpito genera un uccello#L'uccello infligge 4.3 danni da contatto al secondo"},
	{"118", "Zolfo Fuso", "↓ {{Tears}} x3 Moltiplicatore del delay delle lacrime#{{Chargeable}} Le lacrime di Isaac sono sostituite da un raggio di sangue caricabile"},
	{"119", "Sacca di sangue", "↑ {{Heart}} +1 Salute#↑ +0.3 Velocità#{{Heart}} Cura di 4 cuori"},
	{"120", "Buffungo (Piccolo)", "↑ {{Speed}} +0.3 Velocità#↑ {{Tears}} +1.7 Lacrime#↓ {{Damage}} x0.9 Moltiplicatore Danni#↓ {{Damage}} -0.4 Danni"},
	{"121", "Buffungo (Grande)", "↑ {{EmptyHeart}} +1 Portacuore#↑ {{Damage}} +0.3 Danni#↑ {{Range}} +0.25 Gittata#↑ +0.5 Altezza Lacrime#↓ {{Speed}} -0.1 Velocità"},
	{"122", "Meretrice di Babilonia", "Quando sei a mezzo Cuore Rosso o meno:#↑ {{Speed}} +0.3 Velocità#↑ {{Damage}} +1.5 Danni"},
	{"123", "Manuale dei Mostri", "{{Timer}} Genera un familgio casuale per la stanza"},
	{"124", "Pergamene del Mar Morto", "Attiva un effetto di un oggetto attivo casuale"},
	{"125", "Bobby-Bomba", "{{Bomb}} +5 Bombe#Bombe a ricerca"},
	{"126", "Lametta", "↑ {{Damage}} +1.2 Danni#{{Warning}} Infligge 1 cuore di danni ad Isaac#{{Heart}} Rimuove per primi i Cuori Rossi"},
	{"127", "NonTiRicordarDiMe", "{{Warning}} MONOUSO {{Warning}}#Rimpiazza e fa ripartire l'intero piano"},
	{"128", "Forever Alone", "Mosca orbitale a lunga distanza#Infligge 30 danni da contatto al secondo"},
	{"129", "Secchio di Lardo", "↑ {{EmptyHeart}} +2 Portacuori vuoti#↓ {{Speed}} -0.2 Velocità#{{HalfHeart}} Cura di mezzo cuore"},
	{"130", "Un Pony", "Volo#scatto in una direzione"},
	{"131", "Sacco di Bombe", "Lascia una bomba ogni 2 stanze"},
	{"132", "Un Pezzo di Carbone", "Più danno in base a quanta distanza ha viaggiato la lacrima"},
	{"133", "Zampa di Guppy", "Converte:#1 Cuore rosso in 3 Cuori d'anima"},
	{"134", "Coda di Guppy", "Appaiono più casse!"},
	{"135", "Flebo", "Banca del sangue portatile#Metà cuore = 1 Moneta"},
	{"136", "Amici del Cuore", "Fantoccio Esplosivo#Attrae nemici"},
	{"137", "Detonatore", "Detona Bombe a comando#+5 Bombe"},
	{"138", "Stimmate", "↑ {{Heart}} +1 Salute#↑ +0.3 Danni"},
	{"139", "Borsetta di Mamma", "Ora puoi portare 2 trinket!"},
	{"140", "Maledizione di Bob", "Bombe Velenose#+5 Bombe"},
	{"141", "Reginello", "Evoca 7 Monete casuali"},
	{"142", "Scapolare", "Quando danneggiato fino a Metà cuore, ottieni 1 Cuore Spirito#(Una volta per stanza)"},
	{"143", "Speed Ball", "+0.3 Velocità Aumentata#+0.2 Velocità di tiro"},
	{"144", "Amico Scrocco", "Converte Monete in consumabili"},
	{"145", "Testa di Guppy", "Evoca 2-4 mosche blu"},
	{"146", "Santino", "+1 Cuore eterno"},
	{"147", "Piccone Minatorio", "Rompe le rocce della stanza attuale"},
	{"148", "Infestazione", "Evoca mosche quando vieni colpito"},
	{"149", "Ipecac", "Lacrime esplosive"},
	{"150", "Amor Duro", "Possibilità di sparare denti"},
	{"151", "Mosca al Naso", "1/6 possibilità di evocare una mosca quando le Lacrime colpiscono un nemico"},
	{"152", "Tecnologia 2", "Laser permanente!#-35% Danno Diminuito"},
	{"153", "Ragno Mutante", "Colpo quadruplo!#Lacrime diminuite"},
	{"154", "Esfoliazione Chimica", "↑ +2 Danni per l'occhio sinistro"},
	{"155", "Il Guardone", "Fluttua nella stanza#Infligge danno da contatto"},
	{"156", "Soggolo", "+1 Carica quando vieni colpito"},
	{"157", "Sangue Furente", "Danni quando vieni colpito#Dura tutto il piano"},
	{"158", "Sfera di Cristallo", "Rivela l'intera mappa#Lascia una Carta casuale o un Cuore Spirito"},
	{"159", "Spirito della Notte", "Volo#Lacrime Spettrali"},
	{"160", "Apriti Cielo", "Raggi di luce dal cielo!"},
	{"161", "Ankh", "Rinasci come ??? (Blue Baby)"},
	{"162", "Croce Celtica", "Possibilità di Invincibilità quando Isaac viene colpito"},
	{"163", "Bebè Fantasma", "Ha Lacrime Spettrali"},
	{"164", "La Candela", "Evoca una fiamma blu"},
	{"165", "Gatto a Nove Code", "↑ +1 Danni#↑ +0.23 Velocità di tiro"},
	{"166", "D20", "Rerolla consumabili"},
	{"167", "Bebè Arlecchino", "Spara due Lacrime in una traiettoria a forma di V"},
	{"168", "Epic Fetus", "Epic Fetus!!"},
	{"169", "Polifemo", "Mega Lacrime!#Danni#Lacrime diminuite"},
	{"170", "Papà Gambalunga", "Salta sui nemici"},
	{"171", "Chiappe Ragnesche", "Rallenta i nemici#Danneggia i nemici"},
	{"172", "Lama Sacrificale", "Coltello Orbitale"},
	{"173", "Mitra", "Maggiore possibilità di trovare Cuori d'anima"},
	{"174", "Bimbo Arcobaleno", "Spara Lacrime Casuali"},
	{"175", "Chiave di Papà", "Apre tutte le porte nella stanza attuale, incluse quelle segrete"},
	{"176", "Cellule staminali", "↑ {{Heart}} +1 Salute#↑ +0.16 Velocità di tiro"},
	{"177", "Slot Portatile", "slot machine portatile"},
	{"178", "Acqua Santa", "Lascia una pozzanghera di schifo quando vieni colpito"},
	{"179", "Destino", "+1 Cuore eterno#Volo"},
	{"180", "Il Fagiolo Nero", "Scorreggia quando toccato"},
	{"181", "Pony Bianco", "Volo#Scatto Sacro"},
	{"182", "Sacro Cuore", "↑ Lacrime a Ricerca#↑ {{Heart}} +1 Salute#↑ Moltiplicatore danni 2.3x#↓ -0.4 Lacrime diminuite#↓ -0.25 Velocità di sparo Diminuita#↑ +0.375 Gittata"},
	{"183", "Stuzzicadenti", "↑ +0.7 Lacrime.#↑ +0.16 Velocità di tiro"},
	{"184", "Sacro Graal", "Volo#↑ {{Heart}} +1 Salute"},
	{"185", "Colomba Morta", "Volo#Lacrime Spettrali"},
	{"186", "Eredità di Sangue", "Infliggi 40 danni a tutti i nemici#Costo: 1 Cuore Rosso di danno"},
	{"187", "Palla di Pelo di Guppy", "Palle di pelo che crescono#Ti oscilla attorno"},
	{"188", "Abele", "Copia i tuoi movimenti#Spara verso Isaac"},
	{"189", "Super Fan di SMB", "↑ {{Heart}} +1 Salute#↑ +0.3 Danni#↑ +0.2 Lacrime#↑ +0.5 Gittata#↑ +0.2 Velocità Aumentata#↑ +1.0 Altezza Lacrime#Vita Piena"},
	{"190", "Bombarolo", "+99 Bombe"},
	{"191", "Banconota da 3 Dollari", "Effetti Lacrime casuali"},
	{"192", "Telepatia per Negati", "Lacrime a Ricerca per la stanza attuale"},
	{"193", "CARNE!", "↑ {{Heart}} +1 Salute#↑ +0.3 Danni"},
	{"194", "Palla Magica", "↑ +0.16 Velocità di tiro#+1 carta"},
	{"195", "Borsellino di Mamma", "Lascia 4 Pillole"},
	{"196", "Anti-stress", "Evoca 2 Cuori Spirito#↑ +0.4 Lacrime"},
	{"197", "Succhino di Cristo", "↑ +0.5 Danni#↑ +0.25 Gittata.#↑ +0.5 Altezza Lacrime"},
	{"198", "Scatola", "Evoca 1 consumabile di ogni tipo"},
	{"199", "Chiave di Mamma", "+2 Chiavi#Più oggetti dalle casse"},
	{"200", "Ombretto di Mamma", "Lacrime ammalianti"},
	{"201", "Lingotto di Ferro", "↑ +0.3 Danni#Possibilità di sparare lacrime stordenti"},
	{"202", "Tocco di Mida", "Trasforma i nemico in oro al contatto#Nemici dorati lasciano Monete"},
	{"203", "Offerta Imperdibile", "Raddoppia tutti i consumabili"},
	{"204", "Marsupio", "Lascia un consumabile casuale quando vieni colpito"},
	{"205", "Presa Diretta", "-2 Cuori = Carica al massimo un oggetto quando premi Spacebar#Funziona solo quando l'oggetto non è carico!"},
	{"206", "Ghigliottina", "↑ +1 Danni#↑ -1.0 Lacrime#La tua testa ora è un orbitale#Spari dalla testa"},
	{"207", "Palla di Cerotti", "LVL1: Orbitale#LVL2: Orbitale che spara#LVL3: Bandage girl#LVL4: Bandage girl LVL2!!"},
	{"208", "Cintura del Campione", "↑ +1 Danni#↓ Appaiono più campioni"},
	{"209", "Bombe Popò", "+5 Bombe#Danneggia ogni nemico nella stanza"},
	{"210", "Foglia Mangiucchiata", "Invincibile stando fermo per 1 secondo"},
	{"211", "Bimboragno", "Evoca ragni quando vieni colpito"},
	{"212", "Collare di Guppy", "50% Possibilità di rinascere"},
	{"213", "Lentina Persa", "Lacrime schermate"},
	{"214", "Anemia", "↑ +5 Gittata#Lascia pozze sul terreno quando vieni colpito"},
	{"215", "Testa di Capra", "100% possibilità di stanza del Diavolo/Angelo"},
	{"216", "Vesti Cerimoniali", "↑ +1 Danni#+3 Cuori Neri"},
	{"217", "Parrucca di Mamma", "Possibilità casuale di evocare un ragno blu quando spari Lacrime"},
	{"218", "Placenta", "Rigenera lentamente vita#+1 Salute Aumentata"},
	{"219", "Cerotto Vecchio", "↑ +1 Portacuori vuoto#Possibilità casuale di lasciare cuori quando vieni colpito"},
	{"220", "Bombe Tristi", "Esplosione Lacrime!#+5 Bombe"},
	{"221", "Mastice", "Lacrime Rimbalzanti"},
	{"222", "Anti-Gravità", "Lacrime#Lacrime Anti-Gravità"},
	{"223", "Piromane", "Le esplosioni ti curano!#+5 Bombe"},
	{"224", "Corpo di Cricket", "↑ -1 Intervallo fra le lacrime (Lacrime)#↓ -10.0 Gittata#↑ Lacrime si dividono in 4 quando colpiscono"},
	{"225", "Latex", "Possibilità di lasciare Cuore Nero/dell'anima quando vieni colpito"},
	{"226", "Loto Nero", "↑ {{Heart}} +1 Salute#↑ +1 Cuore Spirito#↑ +1 Cuore Nero"},
	{"227", "Salvadanaio", "+3 Monete#lascia una Moneta quando vieni colpito"},
	{"228", "Profumo di Mamma", "Colpi terrificanti#Lacrime"},
	{"229", "Polmone di Monstro", "Lacrime possono essere caricate e rilasciate in un attacco in stile shotgun"},
	{"230", "Abaddon", "↑ +1.5 Danni#↑ +0.2 Velocità Aumentata#Lacrime terrificanti#↓ Rimuove tutti i Cuori rossi#↑ +6 Cuori Neri"},
	{"231", "Palla di Catrame", "Lascia una pozza rallentante#Lacrime rallentanti"},
	{"232", "Cipollotto", "Effetto rallentante permanente (attivato quando vieni colpito)"},
	{"233", "Pianetino", "Lacrime orbitano attorno Isaac#+7.0 Altezza Lacrime"},
	{"234", "Infestazione 2", "Evoca ragno quando uccidi nemici"},
	{"235", "", "<L'oggetto non esiste>"},
	{"236", "E. Coli", "Al tocco, trasforma i nemici in cacca"},
	{"237", "Tocco Mortale", "Lacrime falce!#↑ +1.5 Danni#↓ -0.3 Lacrime diminuite"},
	{"238", "Pezzo di Chiave 1", "Pezzo di chiave per la porta di Mega Satana!#Appaiono più stanze degli angeli"},
	{"239", "Pezzo di Chiave 2", "Pezzo di chiave per la porta di Mega Satana!#Appaiono più stanze degli angeli"},
	{"240", "Trattamento Sperimentale", "Tutte le statistiche +/- numeri a caso"},
	{"241", "Contratto con gli Abissi", "Raddoppia tutti i drop consumabili"},
	{"242", "Infamia", "Possibilità di bloccare lacrime"},
	{"243", "Scutum Fidei", "Scudo blocca-lacrime"},
	{"244", "Tecn. 0.5", "Spara lacrime laser casuali"},
	{"245", "Dieci Decimi", "Raddoppia i tuoi colpi"},
	{"246", "Mappa Blu", "Rivela stanze segrete"},
	{"247", "AMICI PER LA PELLE!", "I tuoi famigli infliggono più danni"},
	{"248", "Mente Alveare", "Ragni blu/mosche infliggono il doppio dei danni"},
	{"249", "Ci sono alternative", "2 oggetti dei boss appaiono invece di 1#Puoi prenderne solo uno"},
	{"250", "Bombe 2x1", "Raddoppia tutti i drop di bombe"},
	{"251", "Mazzo Introduttivo", "Puoi portare due carte#Trasforma tutte le pillole in carte"},
	{"252", "Portapillole", "Puoi portare due pillole#Trasforma tutte le carte in pillola"},
	{"253", "Scabbia Magica", "↑ +1 Fortuna#↑ {{Heart}} +1 Salute"},
	{"254", "Grumo di Sangue", "↑ +1 Danni#↑ +5 Gittata#Si applica solo all'occhio sinistro"},
	{"255", "Vite", "↑ +0.5 Lacrime#↑ +0.2 Velocità di tiro"},
	{"256", "Bombe Incendiarie", "Bombe brucianti#+5 Bombe"},
	{"257", "Mente in Fiamme", "Lacrime in fiamme#Possibilità Lacrime esplosive"},
	{"258", "Missing No.", "Rerolla tutti i tuoi oggetti quando cambi piano"},
	{"259", "Materia Oscura", "+1 Danni#Colpi terrificanti"},
	{"260", "Candela Nera", "Immunità alle maledizioni#+1 Cuore Nero"},
	{"261", "Proptosi", "↑ +100% Danni#Il danno inflitto diminuisce a seconda della distanza percorsa"},
	{"262", "Pagina Mancante 2", "↑ +1 Cuore Nero#Quando sotto 1.5 Cuori, Danneggia i nemici nella stanza"},
	{"263", "", "<L'oggetto non esiste>"},
	{"264", "Moscastuta", "Orbitale che può caricare verso i nemici"},
	{"265", "Bebè Asciutto", "Quando colpito da lacrime nemiche, può danneggiare tutti i nemici nella stanza"},
	{"266", "Sacca Colante", "Lascia una pozza rallentante"},
	{"267", "Robo-Bebè 2.0", "Spara laser"},
	{"268", "Bebè Marcio", "Evoca mosche blu"},
	{"269", "Bebè Decapitato", "Lascia una pozza di sangue"},
	{"270", "Sanguisuga", "Cura metà cuore quando uccide un nemico"},
	{"271", "Sacco delle Meraviglie", "Lascia consumabili casuali"},
	{"272", "BMF", "Mosca esplosiva amichevole"},
	{"273", "Cervello di Bob", "Famiglio bomba lanciabile"},
	{"274", "Scudiero", "Quando vieni colpito, vieni evocato come orbitale"},
	{"275", "Mini Zolfo Fuso", "Spara un laser di brimstone"},
	{"276", "Cuore di Isaac", "Ottieni un corpo invulnerabile#Prendi danno quando il famiglio viene colpito"},
	{"277", "Mini Tormento", "Famiglio fantasma amichevole"},
	{"278", "Scroccoscuro", "Converte:#1,5 Cuore rossi in 1 Cuore Spirito"},
	{"279", "Grande Fan", "Grande orbitale grasso e lento"},
	{"280", "Sorellina Gambalunga", "Evoca ragni blu"},
	{"281", "Sacco da Boxe", "I nemici punteranno lui invece di te"},
	{"282", "Come Saltare", "Ti permette di saltare"},
	{"283", "D100", "Rerolla tutti i consumabili, piedistalli e tutti gli oggetti tenuti"},
	{"284", "D4", "Rerolla tutti gli oggetti mantenuti"},
	{"285", "D10", "Rerolla tutti i nemici nella stanza"},
	{"286", "Carta Vuota", "Imita l'effetto della carta che hai come prima nello slot."},
	{"287", "Libro dei Segreti", "Rivela casualmente parti della mappa"},
	{"288", "Scatola di Ragni", "Evoca 2-4 ragni blu"},
	{"289", "Candela Rossa", "Lancia una fiamma rossa."},
	{"290", "La Giara di Vetro", "Puoi conservare dei cuori rossi per utilizzarli in seguito."},
	{"291", "Sciacquone!", "Uccide all'istante tutti i nemici di cacca!#Trasforma i nemici in cacca"},
	{"292", "Bibbia Satanica", "+1 Cuore Nero"},
	{"293", "Testa di Krampus", "Spara un brimstone in 4 direzioni"},
	{"294", "Fagiolo di Lima", "Respinge tutti i nemici vicini"},
	{"295", "Dita Magiche", "Danneggia tutti i nemici nella stanza#Prezzo: 1 Moneta"},
	{"296", "Convertitore", "Converte:#2 Cuori d'anima o Cuori Neri in 1 Cuore rosso"},
	{"297", "Vaso di Pandora", "Uso singolo! Cambia effetto in base al piano, effetto:#P1: 2 Cuori d'anima#P2:2 Chiavi e 2 Bombe#P3: 1 oggetto del Boss#P4: P1+P3#P5:4 Cuori d'anima#P6: 30 Monete#P7:2 oggetti del Boss#P8: La Bibbia#Sheol: 1 oggetto del patto del diavolo+ 1 Cuore Nero#Cattedrale: 1 oggetto del patto con gli angeli+ 1 Cuore Spirito#Cassa: 1 Moneta"},
	{"298", "Moncherino di Unicorno", "Invincibilità temporanea e Velocità Aumentata"},
	{"299", "Toro", "Ti rende lentamente piùveloce nelle stanze ostili!#Invincibilitàquando raggiungi il massimo della velocità"},
	{"300", "Ariete", "+0.25 di Velocità#Se tocchi i nemici potresti fargli male"},
	{"301", "Cancro", "+3 Cuori d'anima#Quando vieni danneggiato per la prima volta i danni successivi vengono dimezzati"},
	{"302", "Leone", "Rompi la rocce!"},
	{"303", "Vergine", "Hai la possibilità di diventare invincibile dopo aver preso danno#Converte le pillole negative in pillole positive"},
	{"304", "Bilancia", "+6 Monete / Chiavi / Bombe#Bilancia le tue statistiche!"},
	{"305", "Scorpione", "Lacrime avvelenate"},
	{"306", "Sagittario", "↑ +0.2 di Velocità#Lacrime Perforanti"},
	{"307", "Capricorno", "↑ +1 Cuore / Chiave / Bomba / Moneta#↑ +0.5 di Danno#↑ +0.1 di Velocità#↑ +1.5 di Gittata"},
	{"308", "Acquario", "Lascia una pozza d'acqua sotto i piedi"},
	{"309", "Pesci", "Lacrime#Le lacrime respingono i nemici"},
	{"310", "Mascara di Eva", "Danno raddoppiato#Lacrime diminuite# Velocità delle lacrime Diminuita"},
	{"311", "Ombra di Giuda", "Quando muori, ritorni in vita come Judas Nero#(Danno Raddoppiato)"},
	{"312", "Fiocco di Madda", "↑ {{Heart}} +1 Salute#Tutti i cuori curano il doppio"},
	{"313", "Manto Sacro", "Annulla il primo danno preso in una stanza"},
	{"314", "Coscione", "↑ +1 Vita#↓ -0.4 di Velocità#Puoi rompere le rocce!"},
	{"315", "Calamita Strana", "Lacrime Magnetiche"},
	{"316", "Occhio Maledetto", "Carica e lancia una serie Lacrime#Se vieni colpito mentre carichi le lacrime, vieni teletrasportato in una stanza casuale"},
	{"317", "Liquido Misterioso", "Le lacrime rilasciano una pozza"},
	{"318", "Gemelli", "Evoca un gemello siamese che fa danno ai nemici"},
	{"319", "L'Altro Occhio di Caino", "Gira per tutta la stanza#Spara verso Isaac#Il danno delle lacrime è uguale a quello di Isaac"},
	--NOTE FOR LOCALIZERS: There is code to highlight the text of your current floor
	--For it to work, only use line breaks or semicolons to separate floor details, and use the same order as English
	{"320", "L'Unico Amico di ???", "Mosca Controllabile"},
	{"321", "Catene di Sansone", "Catena + Palla#La palla distrugge le rocce e danneggia i nemici"},
	{"322", "Bebè Scemotto", "Copia l'effetto di un tuo famiglio#Se non ne hai uno sparerà lacrime normali"},
	{"323", "Lacrime di Isaac", "Spara lacrime in 8 direzioni#Si ricarica sparando"},
	{"324", "Indefinito", "Ti può teletrasportare in:#Una stanza segreta / Una stanza errore / Una stanza degli oggetti"},
	{"325", "Forbici", "Taglia la tua testa#La testa rimane ferma#Puoi controllare solo il corpo"},
	{"326", "Alito di Vita", "Se svuoti la barra della carica tenendo premuto spazio guadagni l'invincibilità#Non tenerlo premuto troppo!"},
	{"327", "La Polaroid", "Diventi invincibile quando rimani a metàcuore"},
	{"328", "Il Negativo", "Fàdanno a tutta la stanza quando rimani con mezzo cuore"},
	{"329", "Il Trattamento Ludovico", "Lacrime telecomandate"},
	{"330", "Latte di Soia", "Aumento altissimo del numero Lacrime sparate: (lacrime /4) - 2#-80% del Danno"},
	{"331", "Divinità", "Lacrime a Ricerca#+0.5 di Danno# +1.2 di Gittata# -0.3 Lacrime# -0.3 di Velocità di sparo#+0.8 dell' Altezza Lacrime"},
	{"332", "Bende di Lazzaro", "Quando muori ritorni in vita come Lazarus ed ottieni un oggetto extra"},
	{"333", "La Mente", "Rivela tutta la mappa"},
	{"334", "Il Corpo", "↑ +3 di salute"},
	{"335", "L'Anima", "↑ +2 Cuori d'anima#I proiettili potrebbero curvare per non colpire Isaac"},
	{"336", "Cipolla Morta", "Lacrime Perforanti + Lacrime Spettrali#↓ -0.25 di Gittata#↓ -0.4 di Velocità di sparo"},
	{"337", "Cipollotto Rotto", "Rallenta o velocizza le stanze"},
	{"338", "Il Boomerang", "Stordisce i nemici#Puòprendere gli oggetti"},
	{"339", "Spilla da Balia", "↑ +5.25 di Gittata#↑ +0.16 di Velocità di sparo#↑ +1 Cuore Nero#↑ +0.5 di Altezza Lacrime"},
	{"340", "Pillola di Caffeina", "↑ +0.3 di Velocità#Ti rende più piccolo#Ti dona una pillola casuale"},
	{"341", "Foto Strappata", "↑ +0.7 Lacrime#↑ +0.16 di Velocità di sparo"},
	{"342", "Cappello Blu", "↑ +1 Vita#↑ +0.7 Lacrime#↓ -0.16 di Velocità di sparo"},
	{"343", "Chiave dell'Ometto", "↑ +1 di Fortuna#↑ +1 Cuore Spirito#+2 Chiavi"},
	{"344", "Scatola di Cerini", "↑ +1 Cuore Nero#+3 Bombe"},
	{"345", "Sintolio", "↑ +1.0 di Danno#↑ +5.25 di Gittata#↑ +0.5 di Altezza Lacrime"},
	{"346", "Uno Snack", "↑ +1 Vita"},
	{"347", "Diplopia", "Uso singolo!#Duplica un piedistallo o un consumabile nella stanza."},
	{"348", "Placebo", "Copia l'effetto della prima pillola presente nello slot"},
	{"349", "Nichelino di Legno", "Rilascia al 50% una moneta casuale"},
	{"350", "Shock Tossico", "Quando entri in una stanza, avveleni tutti i nemici"},
	{"351", "Mega Fagiolo", "Blocca tutti i nemici nella stanza#Danneggia ed avvelena tutti i nemici vicini#Genera una scia di spie nella stanza#Puòaprire le stanze segrete"},
	{"352", "Cannone di Vetro", "Rimani con mezzo cuore#Lancia una grossa lacrima perforante che fa:((danno+1) X 10)"},
	{"353", "Bomber Boy", "+5 Bombe#Le bombe esplodono in croce"},
	{"354", "Crack Jack", "↑ +1 Vita#Rilascia un trinket casuale sul piano"},
	{"355", "Perle di Mamma", "↑ +1.25 di Gittata#↑ +0.5 di Altezza Lacrime#↑ +1 di Fortuna"},
	{"356", "Batteria per Auto", "Quando usi un attivo, effetto si applica due volte"},
	{"357", "Scatola degli Amici", "Duplica i tuoi famigli nella stanza corrente"},
	{"358", "Il Genio", "Spara due lacrime in diagonale#Lacrime Spettrali"},
	{"359", "Chiodo schiaccia Chiodo", "↑ +1.5 di Danno#I nemici vengono respinti dalle lacrime"},
	{"360", "Incubo", "Spara una copia esatta delle lacrime di isaac, alla stessa velocità e gittata"},
	{"361", "Dono del Destino", "Lancia una lacrima che fa lo stesso danno di Isaac"},
	{"362", "Bauletto", "Rilascia un consumabile casuale ogni 5 stanze"},
	{"363", "Eterno Protettore", "Fa danno da contatto#Blocca le lacrime#Bloccando una lacrima può rilasciare un cuore eterno"},
	{"364", "Friend Zone", "Fa danno da contatto"},
	{"365", "Mosca Smarrita", "Si muove attorno alla stanza o a degli ostacoli#Fa danno da contatto"},
	{"366", "Bomba a Grappolo", "+5 Bombe#Quando la bomba esplode rilascia 4 bombe piccole"},
	{"367", "Bombe Appiccicose", "Quando una bomba uccide un nemico, evoca ragni blu#La bomba si attacca ai nemici"},
	{"368", "Epifora", "Sparare in una direzione fissa aumenterà in numero Lacrime"},
	{"369", "Continuum", "↑ +2.25 di Gittata#↑ +1.5 di Altezza Lacrime#Le lacrime attraversano il muro e ricompaiono sul lato opposto della stanza."},
	{"370", "Sig. Bambolotto", "+0.7 Lacrime##5.25 di Gittata#+0.5 di Altezza delle Lacrime#Evoca 3 Cuori casuali quando raccogli questo oggetto"},
	{"371", "Maledizione della Torre", "Evoca 6 troll Bomb quando vieni colpito"},
	{"372", "Bebè Carico", "Casualmente rilascia una batteria o blocca tutti i nemici nella stanza#Casualmente aggiunge una carica all'oggetto attivo"},
	{"373", "Cecchino", "↑ +25% di danno per ogni lacrima che colpisce il nemico(max. +100%)"},
	{"374", "Luce Sacra", "Possibilità di lanciare una lacrima sacra, la lacrima attiva l'effetto di Crepa il cielo"},
	{"375", "Cascospite", "Puòbloccare le lacrime#Rende immune alle esplosioni"},
	{"376", "Rifornimento", "Rifornisce i negozi dopo gli acquisti"},
	{"377", "Sacca Brulicante", "I ragni ignorano Isaac e non gli fanno danno da contatto"},
	{"378", "La Numero Due", "Sparare lacrime per 3 secondi fa comparire una Culomba(Bomba Cacca) "},
	{"379", "Pupula Duplex", "Le lacrime sono più grandi#+Lacrime Spettrali"},
	{"380", "Pay to Play", "+5 Monete#Puoi aprire le porte utilizzando le monete al posto delle chiavi"},
	{"381", "Benedizione di Eden", "↑ +0.7 Lacrime#Dona un oggetto casuale all'inizio delle prossima partita"},
	{"382", "Sfera Amikè", "Puoi catturare un nemico#La prossima volta che attivi questo oggetto rilascerai il nemico precedentemente catturato che combatterà per te"},
	{"383", "Detonatore di Lacrime", "Fa esplodere le tue lacrime, dividendole in 6 lacrime che partono in cerchio"},
	{"384", "Mini Gastrina", "Dopo essere stato caricato e rilasciato questo famiglio rimbalza per tutta la stanza facendo danno da contatto."},
	{"385", "Bumbo", "Raccoglie tutte le monete nelle vicinanze. Ogni 6 monete aumenta di livello, per raggiungere il livello 4 necessita di 12 monete#Livello 2: può rilasciare un consumabile casuale#Livello 3: Spara lacrime nella stessa direzione di Isaac #Livello 4: Non spara piùlacrime, ma si avvicina lentamente ai nemici e gli fa danno da contatto. Casualmente rilascia delle bombe sotto i nemici#Dopo il livello 4: Continua a rilasciare collezionabili"},
	{"386", "D12", "Cambia casualmente le rocce in altri oggetti di scenario(cacche, TNT, ecc."},
	{"387", "Incensiere", "Crea un cerchio di luce che rallenta in nemici che vi entrano in contatto"},
	{"388", "Scrocchiave", "Raccoglie Chiavi, dopo un certo numero di chiavi rilascia una cassa casuale"},
	{"389", "Sacco di Rune", "Rilascia una runa casuale ogni 3 stanze"},
	{"390", "Serafino", "Spara lacrime sacre."},
	{"391", "Tradimento", "Quando Isaac subisce un danno in una stanza tutti i nemici vengono ammalianti"},
	{"392", "Zodiaco", "Dona l'effetto di un segno zodiacale casuale ad ogni piano"},
	{"393", "Bacio del Serpente", "Casualmente Isaac sparerà una lacrima avvelenata#I nemici quando vengono avvelenati alla morte hanno la possibilità di rilasciare un cuore nero."},
	{"394", "Mirino", "Isaac sparerà di continuo le lacrime verso un bersaglio controllato dal giocatore #+0.7 Lacrime#+0.3 Altezza delle Lacrime#+3.15 di Gittata"},
	{"395", "Tecn. X", "Colpo Caricato. Spara un cerchio laser che percorre tutta la stanza."},
	{"396", "Bisturi", "Crea due portali che possono essere utilizzati per fuggire dalle stanze"},
	{"397", "Raggio Traente", "Le lacrime di Isaac vengono attratte da un raggio luminoso#+0.5 Lacrime#+5.25 di Gittata#+0.16 di Velocità di sparo#+0.5 Altezza delle Lacrime"},
	{"398", "Trip Divino", "Alcune lacrime renderanno alcuni nemici piùpiccoli#Se Isaac passa sopra i nemici piccoli li uccide"},
	{"399", "Fauci dell'Oblio", "↑ +1.0 di Danno#↑ +0.5 di Altezza delle Lacrime#Dopo aver sparato lacrime per 3 secondi, sulla testa di Isaac comparirà una croce rossa. Se si smette di sparare comparirà un raggio nero attorno ad Isaac che farà lo stesso danno di Isaac e se uccide un nemico c'è la possibilità che questo rilasci un cuore nero"},
	{"400", "Lancia del Destino", "Compare una spada che fa due volte il danno base di Isaac"},
	{"401", "Explosivo", "Le lacrime casualmente si attaccheranno ai nemici esplodendo dopo pochi secondi."},
	{"402", "Caos", "Gli oggetti sui piedistalli verranno scelti casualmente# Rilascia casualmente da 1 a 6 consumabili"},
	{"403", "Ragno Moddato", "Permette di visualizzare il danno fatto ai nemici#Se un nemico ci passa sopra, gli verrà inflitto uno stato casuale#Dona casualmente una batteria"},
	{"404", "Bebè Scoreggione", "Blocca le lacrime#Se blocca una lacrima c'è un alta possibilità che questo famiglio scorreggi."},
	{"405", "Bug Rompigioco", "Applica un effetto casuale a chi vi entra in contatto"},
	{"406", "D8", "Mischia le tue statistiche#Ha effetto solo sulle statistiche di danno, lacrime, gittata e velocità"},
	{"407", "Purezza", "Dona un aura colorata ad Isaac, a seconda dell'aura vi sono vantaggi diversi#Quando ricevi danno cambi aura#Rosso = +4.0 di Danno#Blue = -4 di Intervallo fra le lacrime#Giallo = +0.5 di Velocità#Arancione = +7.5 di Gittata"},
	{"408", "Athame", "Quando Isaac verrà danneggiato comparirà un anello nero che farà lo stesso danno di Isaac. Se i nemici vengono uccisi dall'anello hanno la possibilità di rilasciare un cuore nero"},
	{"409", "Recipiente Vuoto", "+2 Cuori Neri#Quando Isaac non ha cuori rossi, attiva il volo e la possibilità di ottenere uno scudo"},
	{"410", "Malocchio", "Isaac casualmente sparerà un occhio che sparerà le sue stesse lacrime alla stessa cadenza e nella stessa direzione"},
	{"411", "Sangue assetato", "Uccidendo i nemici Isaac guadagna danno extra per tutta la stanza#massimo +5 di Danno"},
	{"412", "Immorale Concezione", "Dopo aver preso molti danni comparirà un famiglio demoniaco"},
	{"413", "Immacolata Concezione", "Dopo aver presso molti cuori comparirà un famiglio angelico"},
	{"414", "Più Alternative", "Compariranno il doppio degli oggetti nella stanza degli oggetti, se ne può prendere solo uno"},
	{"415", "Corona di Luce", "+2 Cuori d'anima#Raddoppia il danno se si hanno tutti i cuori rossi pieni"},
	{"416", "Tasche profonde", "Permette di portare con se 2 carte/pillole/Rune"},
	{"417", "Succuba", "#Rimbalza per tutta la stanza facendo danno con la sua aura#Quando Isaac entra nell'aura riceve il 50% del danno in più"},
	{"418", "Torta di Canditi", "Rende le lacrime casuali"},
	{"419", "Teletrasporto 2.0", "Ti teletrasporta in una stanza casuale di qualsiasi tipo che non hai ancora esplorato"},
	{"420", "Polvere nera", "Creando un cerchio con la scia che Isaac rilascia sotto i piedi comparirà un pentacolo che farà danno alle entità al suo interno"},
	{"421", "Fagiolo rene", "Ammalia tutti i nemici vicini"},
	{"422", "Clessidra Luminosa", "Fa tornare indietro il tempo tornando alla stanza precedente#Dopo 5 utilizzi si trasforma in una semplice clessidra"},
	{"423", "Cerchio Protettivo", "Dona un cerchio bianco attorno ad Isaac, Che fa danno da contatto#Riflette casualmente i colpi"},
	{"424", "Testa di Sacco", "Trasforma casualmente i consumabili in sacchetti"},
	{"425", "Luce Notturna", "Crea un cono di luce di fronte ad Isaac, che rallenta i nemici e le lacrime. "},
	{"426", "Fan Ossessionato", "Copia i movimenti di Isaac con un ritardo di 3 secondi#fa danno da contatto ai nemici"},
	{"427", "Blocco di TNT", "Rilascia una TNT spostabile"},
	{"428", "Pigiamino", "+4 Cuori d'anima#Ricarica tutti i cuori rossi"},
	{"429", "Testa del Mercante", "Le lacrime possono rilasciare monete dopo aver colpito il nemico"},
	{"430", "Papà Mosca", "Copia i movimenti di Isaac con un ritardo di 3 secondi#spara Lacrime ai nemici vicini che fanno lo stesso danno delle Lacrime di Isaac"},
	{"431", "Bebè Multidimensionale", "Copia i movimenti di Isaac con un ritardo di 3 secondi#Le lacrime passanti per il baby si raddoppieranno e incrementeranno in danno"},
	{"432", "Bombe Glitterate", "Bombe lasciano consumabili quando esplodono (es. Chiavi, Monete, Bombe)"},
	{"433", "La Mia Ombra", "Ogni volta che subisci danni, La Mia Ombra applicherà terrore a tutti i nemici nella stanza ed evocherà un famiglio nero che attaccherà al posto tuo#Il famiglio morirà se viene danneggiato troppo"},
	{"434", "Barattolo di Mosche", "Ogni volta che uccidi un nemico una mosca blu sarà aggiunta alla Giara#contiene fino a 20 mosche#Usare la Giara rilascerà tutte le mosche"},
	{"435", "Mini Loki", "Spara 4 Lacrime in una traiettoria a croce"},
	{"436", "Latte!", "Dopo aver subito danni aumenta il numero Lacrime per il resto della stanza"},
	{"437", "D7", "Rievoca tutti i nemici, permettendoti di collezionare tutti i premi di fine stanza più volte# se usato in un combattimento greed, può essere usato per trasformare la stanza in un negozio"},
	{"438", "Ciuccio", "+1 Cuore Spirito#↑ +0.7 Lacrime#Rende Isaac molto piccolo, riducendo la sua hitbox"},
	{"439", "Scatola di Mamma", "Lascia un trinket casuale sul terreno#+1 Fortuna mentre lo tieni#Mentre lo tieni, raddoppia gli effetti dei trinket"},
	{"440", "Calcoli Renali", "Casualmente Isaac smette di sparare ed incomincia a caricare un colpo, una volta rilasciato saprerà un calcolo ed un getto continuo Lacrime#-0.2 di Velocità#-15 di Gittata#+2.0 di Altezza delle Lacrime"},
	{"441", "Mega Sbotto", "Spara il MegaBrimstone di MegaSatana per 15 secondi# Il MegaBrimstone rimane attivo anche la cambio di stanza"},
	{"442", "Corona del Principe delle Tenebre", "Garantisce il doppio del danno quando hai un solo cuore rosso pieno"},
	{"443", "Mela!", "Probabilità di sparare una lametta che fa il 400% del tuo danno al posto che una lacrima#↑ +0.4 Lacrime"},
	{"444", "Matita", "Ogni 15 lacrime sparate rilasci un ammasso di lacrime#Ogni lacrima dell'ammasso fa il doppio del tuo danno"},
	{"445", "Canino", "↑ +0.3 di Danni#↑ +0.1 di Velocità#L'ululato di un lupo ti indicherà dove sono le stanze segrete, le stanze super segrete e le intercapedini"},
	{"446", "Dente Marcio", "Mentre spari si crea un aura verde attorno ad Isaac che avvelena i nemici che la toccano"},
	{"447", "Fagiolo Aleggiante", "Crea casualmente una cacca arcobaleno mentre spari"},
	{"448", "Scheggia di Vetro", "Quando vieni danneggiato ottieni +5 di Gittata e rilasci una pozza di sangue sotto i piedi"},
	{"449", "Placca di Metallo", "+1 Cuore Spirito#Le lacrime possono essere bloccate"},
	{"450", "Occhio di Avarizia", "Le lacrime possono trasformare i nemici in oro"},
	{"451", "Tappetino del Cartomante", "Ti dona una una carta o una runa casuale#Raddoppia gli effetti di tutte le carte"},
	{"452", "Vene Varicose", "Ogni volta che prendi danno rilascia attorno ad Isaac 10 lacrime"},
	{"453", "Frattura Esposta", "Spara Ossa#Quando le ossa cadono o colpiscono un nemico si spezzano ed i frammenti possono colpire i nemici#+1.5 di Gittata"},
	{"454", "Polidattilia", "Puoi portare 2 Pillole/Rune/Carte#Dona un consumabile casuale"},
	{"455", "Moneta Perduta di Papà", "↑ +1.5 di Gittata#Rilascia una moneta fortunata"},
	{"456", "Spuntino di Mezzanotte", "↑ +1 Vita"},
	{"457", "Testa Conica", "+1 Cuore Spirito#Può bloccare le lacrime"},
	{"458", "Ombelico", "Dona un Trincket o un consumabile casuale#Puoi portare due trinket"},
	{"459", "Sinusite", "Casualmente spari una lacrima che si attacca al nemico e gli fa un danno periodico."},
	{"460", "Glaucoma", "Possibilità di sparare una lacrima che stordisce i nemici."},
	{"461", "Parassitoide", "Possibilità di sparare lacrime che rallentano i nemici#Evoca un ragno o una mosca blue ad ogni colpo"},
	{"462", "Occhio di Belial", "Possibilità di sparare lacrime perforanti##Dopo aver colpito il nemico le lacrime ottengono il doppio del danno e diventano a ricerca"},
	{"463", "Acido Solforico", "↑ +0.3 Danni#Possibilità di sparare lacrime corrosive"},
	{"464", "Glifo dell'Equilibrio", "+2 Cuori d'anima#Le stanze rilasciano più spesso consumabili che ti servono"},
	{"465", "Levetta Analogica", "-2 di Intervallo fra le lacrime #Puoi sparare le lacrime in 8 direzioni anzichè 4"},
	{"466", "Contagio", "Il primo nemico esplode avvelenando tutti quelli vicini, se i nemici avvelenati muoiono per il veleno danno vita ad una reazione a catena"},
	{"467", "Dito!", "Fa un piccolo danno nella direzione in cui viene puntato#Applica gli effetti presenti sulle lacrime di Isaac"},
	{"468", "Ombra", "Segue i tuoi movimenti con una ritardo di 3 secondi#fa danno da contatto"},
	{"469", "Depressione", "Lascia una pozza d'acqua sotto di esso#I nemici che toccano la nuvola vengono colpiti dall'effetto di Crepa il cielo"},
	{"470", "Calmina", "Salta per la stanza#Fa danno da contatto#Rimane fermo quando Isaac incomincia a sparare"},
	{"471", "Mini Monstro", "Carica un colpo#Attacco Shotgun"},
	{"472", "Re Bebè", "Viene seguito dagli altri famigli#Rimane fermo quando Isaac incomincia a sparare#Si teletrasporta da te quando smetti di sparare"},
	{"473", "Cicciottona", "Viene sparato lentamente in una direzione#Fa danno da contatto"},
	{"474", "Tonsilla", "Blocca i Proiettili"},
	{"475", "Piano C", "Uso singolo!#Fa 9,999,999 a tutti i nemici nella stanza e ti uccide dopo 3 secondi"},
	{"476", "D1", "Evoca 1-3 mosche o ragni blue#Trasforma i consumabili in mosche o ragni blue"},
	{"477", "Vuoto", "Quando usato, consuma ogni piedistallo nella stanza#Oggetto attivo: Il suo effetto verrà aggiunto al Vuoto (Accumulando gli effetti)#Oggetto passivo: Piccolo incremento di una statistica casuale"},
	{"478", "Pausa", "Blocca tutti i nemici nella stanza, se Isaac spara delle lacrime l'effetto si annulla#Toccare i nemici bloccati ti farà danno"},
	{"479", "Fonderia", "Assorbe un trinket e ti dona permanentemente il suo effetto"},
	{"480", "Compost", "Evoca 1 mosca o un ragno blue per ogni consumabile che distrugge"},
	{"481", "Dataminer", "Bugga letteralmente il gioco, donano effetti casuali a tutto#Sfanculizza la grafica del gioco"},
	{"482", "Telecomando", "Ti trasforma in un personaggio casuale#50% di possibilità di perdere l'ultimo oggetto che hai preso"},
	{"483", "Mamma Mega!", "Uso singolo!#Si attiva durante tutto il piano corrente#Distrugge tutti gli oggetti sullo scenario#Fa 200 danni a tutti i nemici#Può aprire tutte le stanze"},
	{"484", "Aspè, Cosa?", "Evoca una serie di spuntoni di roccia"},
	{"485", "Penny Storto", "Possibilità del 50% di ottenere il doppio degli oggetti, dei consumabili e le casse#Possibilità del 50% di trasformare un oggetto o un consumabile in una moneta)"},
	{"486", "Lametta Smussata", "Attiva tutti gli effetti che si applicano dopo aver preso danno, senza effettivamente danneggiarti"},
	{"487", "Pela Patate", "Rimuove un cuore rosso e ti dona +0.2 di Danno ed un cubo di carne"},
	{"488", "Metronomo", "Ti dona l'effetto di un oggetto casuale per la stanza corrente"},
	{"489", "D Infinito", "Effetto di un dado casuale"},
	{"490", "Anima di Eden", "Uso singolo!#Evoca 2 piedistalli con un oggetto casuale"},
	{"491", "Bebè Acido", "Dona una pillola casuale ogni 2 stanze#Usare una pillola danneggia un nemico"},
	{"492", "YO SENTI QUA!", "+1 di Fortuna#Vola verso le stanze segrete e le intercapedini"},
	{"493", "Adrenalina", "Per ogni cuore rosso vuoto dona +0,2 di Danno ed un aumento delle dimensioni"},
	{"494", "Scala di Giacobbe", "Lacrime Elettriche"},
	{"495", "Peperoncino Fantasma", "Possibilità di sparare un fuoco"},
	{"496", "Eutanasia", "Possibilità di sparare una siringa"},
	{"497", "Mutande Camo", "Quando entri in una stanza sei invisibile finchè non spari"},
	{"498", "Dualismo", "Evoca contemporaneamente le due stanze dei patti#Quando ne scegli una l'altra scompare"},
	{"499", "Eucaristia", "Possibilità del 100% di patto con l'angelo"},
	{"500", "Sacco di Sacchi", "Casualmente rilascia dei sacchetti"},
	{"501", "Gozzo di Avarizia", "Dona un cuore rosso ogni 25 monete"},
	{"502", "Brufolone", "Possibilità di sparare una lacrima che lascia una pozza che rallenta i nemici"},
	{"503", "Piccolo Corno", "Possibilità di sparare una lacrima che uccide all'istante il nemico"},
	{"504", "Pepita Marrone", "Evoca una mosca che spara ai nemici#Scompare quando si cambia stanza"},
	{"505", "Pokè Go", "Casualmente evoca un nemico ammaliato che combatte per te"},
	{"506", "Pugnalatore", "Le lacrime fanno sanguinare i nemici"},
	{"507", "Cannuccia Appuntita", "Questo oggetto fa un danno a tutta la stanza pari al danno di Isaac più il 10% della vita massima del nemico"},
	{"508", "Rasoio di Mamma", "Orbitale che causa sanguinamento"},
	{"509", "Occhio Insanguinato", "Spara delle lacrime ogni 2 secondi verso una direzione casuale"},
	{"510", "Delirante", "Evoca la versione Delirium di un boss che combatterà per te"},
	{"511", "Moscarrabbiata", "Orbita attorno ad un nemico fichè non muore#Fa danno da contatto"},
	{"512", "Buco Nero", "Crea un buco nero che attira tutto verso di se"},
	{"513", "Pagliaccio", "+0.1 di Danno#+1 Cuore Spirito#Casualmente ammalia o terrorizza i nemici#Possibilità di rilasciare una cacca arcobaleno quando si prende danno"},
	{"514", "Modem Sfasciato", "Fa laggare i nemici e le lacrime nemiche"},
	{"515", "Dono Segreto", "Uso singolo!#Evoca un oggetto casuale"},
	{"516", "Irrigatore", "Evoca un irrigatore che spare in circolo una copia esatta delle lacrime di Isaac"},
	{"517", "Bombe Leste", "+7 Bombe#Puoi posizionare rapidamente le bombe"},
	{"518", "Amico in Scatola", "Ti dona un famiglio casuale tra quelli della coop#Il famiglio e le lacrime di questo cambiano ad ogni piano"},
	{"519", "Mini Delirio", "Ogni 10 secondi si trasforma in un famiglio casuale"},
	{"520", "Morsetti", "+1 carica all'attivo ogni 15 nemici uccisi"},
	{"521", "Coupon", "Rende gratis un oggetto a pagamento."},
	{"522", "Telecinesi", "Blocca tutte le lacrime che viaggiano verso Isaac per 3 secondi, poi le rimanda indietro#Si ricarica in 2 secondi"},
	{"523", "Scatola per Traslochi", "Quando viene utilizzato immagazzina al suo interno fino a 6 oggetti."},
	{"524", "Tecnologia Zero", "Le lacrime vengono connesse da un raggio laser"},
	{"525", "Lebbra", "Prendere danno evoca un orbitale#Max. 3 orbitali alla volta#Questi orbitali possono essere distrutti se prendono troppo danno"},
	{"526", "7 sigilli", "Evoca un piccolo cavaliere dell'apocalisse che cambia forma ogni 10 secondi, ogni forma ha un effetto legato al boss a cui è associato"},
	{"527", "Mr. GUARDI!", "Evoca un famiglio che può:#Aprire le porte e le casse, Trasportare da te gli oggetti, Rubare oggetti dai negozi e dal patto con il diavolo, Uccidere i nemici, Esplodere, ed attivare i bottoni"},
	{"528", "Prisma Angelico", "Le lacrime che colpiscono il prisma si dividono in 4 lacrime colorate"},
	{"529", "Pop!", "Le lacrime si comportano come palle da biliardo"},
	{"530", "Lista Nera", "Garantisce un dono se uccidi i nemici nell'ordine corretto"},
	{"531", "Emolacria", "Le lacrime scoppiano in lacrime più piccole all'impatto #La lacrima viene sparata in modo simile all'Ipecac"},
	{"532", "Lacrifagia", "Le lacrime rallentano durante il tragitto. #Una volta ferme scoppiano in lacrime più piccole. #Se si spara ad una lacrima rallentata, questa diventerà più grande, aumentando dimensioni e danni."},
	{"533", "Trisagion", "Spara un raggio di Luce. #(Brimstone sacro)"},
	{"534", "Zainetto", "Permette di portare due attivi."},
	{"535", "Copertina", "+1 Cuore d' anima#Dona uno scudo quando entri nella stanza del Boss"},
	{"536", "Altare Sacrificale", "Sacrifica due o più famigli e dona un oggetto del patto con il diavolo#Può essere utilizzando due volte"},
	{"537", "Mini Conato", "+1 Pillola casuale#Famiglio che carica in linea retta e rilascia una pozza"},
	{"538", "Biglie", "Crea 3 Trincket casuali#Prendere danno può donarti permanente l'effetto dei tuoi trinket"},
	{"539", "Uovo Misterioso", "Evoca un nemico infatuato quando colpito"},
	{"540", "Sasso Piatto", "Lacrime Rimbalzanti#Danno ad area all'impatto"},
	{"541", "Midollo", "+1 Cuore d'ossa#Genera 3 cuori rossi"},
	{"542", "Costola Fluttuante", "Orbitale#Riflette i proiettili"},
	{"543", "Terra Consacrata", "Crea una cacca bianca quando prendi danno#Garantisce un aura di aumento delle lacrime "},
	{"544", "Costola Appuntita", "Arma corpo a corpo"},
	{"545", "Libro dei Morti", "Evoca un orbitale d'ossa o uno scheletro infatuato per ogni nemico ucciso#L'effetto dura per la stanza attuale"},
	{"546", "Anello di Papà", "Un aura che pietrifica i nemici al contatto"},
	{"547", "Documenti per il Divorzio", "↑ +1 Cuore d'ossa#↑ +0.7 Lacrime#Genera il trinket Foglio Misterioso"},
	{"548", "Mandibola", "Famiglio Boomerang#Doppio del danno"},
	{"549", "Osteogenesi Imperfetta", "Rimpiazza tutti i tuoi cuori con cuori d'ossa#Perdere un cuore d'ossa cause spara delle ossa in tutte le direzioni"},
	{"550", "Pala Rotta", "I piedi di mamma ti attaccano#Usarlo ferma i piedi di mamma per la stanza corrente#Sconfiggi la boss rush con questo!"},
	{"551", "Pala Rotta", "Seconda parte della pala di mamma#Ora arriva alla dark room"},
	{"552", "Pala di Mamma", "Crea una botola per il prossimo piano#Usa questa pala su una zolla di terra nella dark room#Sblocca cose belle!"},
}


---------- Modifiers ----------

-- Effect of Car battery on Active Items
-- these all need way more consistency with the original effect text and spellchecking
EID.descriptions[languageCode].carBattery = {
	[58] = "Dura 20 secondi", -- Book of Shadows
	[66] = "Dura 16 secondi", -- The Hourglass
	[77] = "Dura 12 secondi", -- My Little Unicorn
	[93] = "Dura 13 secondi", -- The Gamekid
	[111] = "Infligge il doppio dei danni", -- The Bean
	[124] = "Attiva due effetti", -- Dead Sea Scrolls
	[145] = "Genera 4-7 mosche blu", -- Guppy's Head
	[171] = "Infligge 10 danni extra", -- Spider Butt
	[293] = "Raddoppia i danni dei soffi", -- Head of Krampus
	[298] = "Dura 12 secondi", -- Unicorn Stump
	[351] = "Infligge il doppio dei danni", -- Mega Bean
	[383] = "Divide le lacrime divise -> 6x più lacrime", -- Tear Detonator
	[421] = "Infligge il doppio dei danni", -- Kidney Bean
	[427] = "Genera due blocchi TNT", -- Mine Crafter
	[477] = "Attiva due volte ogni oggetto assorbito", -- Void
	[482] = "Cambia due volte il personaggio e rimuove due oggetti", -- Clicker
	[485] = "25% di possibilità di quadruplicare oggetti e consumabili, 75% di possibilità di rimuoverli", -- Crooked Penny
	[486] = "Attiva due volte gli effetti degli oggetti che si attivano venendo colpiti", -- Dull Razor
	[488] = "Conferisce gli effetti di due oggetti", -- Metronome
	[489] = "Attiva gli effetti di due dadi. Non si può prevedere il secondo dado", -- D Infinity
	[523] = "Scambia il contenuto della scatola con i consumabili della stanza", -- Moving Box
	[550] = "Ferma i pestoni per due stanze o ondate della Boss Rush e delle Sfide {{ChallengeRoom}} {{BossRushRoom}}", -- Broken Shovel
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "Penny Ingerito", "Lasci soldi quando vieni colpito"},
	{"2", "Cacca Pietrificata", "Più tesori dalle cacche!"},
	{"3", "Pila AAA", "Rimuove una carica massima dal tuo oggetto attivo"},
	{"4", "Telecomando Rotto", "Ti teletrasporta casualmente quando usi un oggetto"},
	{"5", "Cuore Viola", "Più Campioni nemici#maggiore possibilità di stanze sfida contro i Boss"},
	{"6", "Magnete Rotto", "Magnete per monete"},
	{"7", "Rosario", "Maggiore possibilità di stanze dell'angelo"},
	{"8", "Cartuccia", "Possibilità di un effetto Gamekid sul colpo"},
	{"9", "Verme Pulsante", "Lacrime oscillanti#Influenza solo gli hitbox"},
	{"10", "Verme Ondulato", "Le lacrime si muovono ad onde"},
	{"11", "Verme Anello", "Le lacrime si muovo a spirale"},
	{"12", "Verme Piatto", "Lacrime più grandi"},
	{"13", "Buono Acquisto", "Un oggetto del negozio gratis"},
	{"14", "Callo", "Spine / Pozze non ti danneggiano più"},
	{"15", "Pietra Fortunata", "Quando distruggi una roccia lasciano monete"},
	{"16", "Unghia dei Piedi di Mamma", "Il piede di mamma schiaccia i nemici ogni 60 secondi"},
	{"17", "Rossetto Nero", "Più cuori neri"},
	{"18", "Passo della Bibbia", "Più cuori eterni"},
	{"19", "Graffetta", "Apri le casse dorate senza chiavi"},
	{"20", "Zampa di Scimmia", "Quando hai mezzo cuore, lascia un cuore nero#3 utilizzi"},
	{"21", "Foglio Misterioso", "Imita Polaroid, negativo e pagina mancante"},
	{"22", "Coda del Demonio", "Converte i tesori:#Cuori in utilizzabili"},
	{"23", "Volantino 'Smarritò", "Rinasci come the lost morendo nella stanza del sacrificio"},
	{"24", "Penny Popò", "Scorreggia quando prendi soldi"},
	{"25", "Caramella Misteriosa", "Lascia cacche casualmente "},
	{"26", "Verme Uncino", "Le lacrime si muovono con una traiettoria angolare"},
	{"27", "Verme Frusta", "+0.5 Velocità di tiro"},
	{"28", "Ankh Rotto", "Possibilità di rinascere come blue baby"},
	{"29", "Testa di Pesce", "Evoca un moscerino blu quando vieni colpito"},
	{"30", "Congiuntivite", "Spara casualmente lacrime velenose"},
	{"31", "Puntina", "Spara casualmente lacrime perforanti"},
	{"32", "Fungo della Libertà", "Effetto di funghi casuali per ogni stanza"},
	{"33", "Cordone Ombelicale", "Quando scendi a metà cuore, ottieni piccolo steven"},
	{"34", "Cuore di Bambino", "Più possibilità di trovare cuori rossi"},
	{"35", "Corno Ricurvo", "+2 Danni"},
	{"36", "Chiave Arrugginita", "Appaiono più casse e chiavi"},
	{"37", "Zoccolo di Capra", "+0.15 Velocità aumentata"},
	{"38", "Perla di Mamma", "Più possibilità di trovare cuori dell'anima"},
	{"39", "Cancro", "Lacrime"},
	{"40", "Toppa Rossa", "Possibilità di ottenere +1.8 ai danni quando vieni colpito"},
	{"41", "Fiammifero", "Appaiono più bombe#Rimuove \"La zecca\""},
	{"42", "Alluce Fortunato", "+1 fortuna aumentata"},
	{"43", "Teschio Maledetto", "Quando vieni danneggiato fino a metà cuore, ti teletrasporta all'ultima stanza visitata"},
	{"44", "Tappino di Sicurezza", "Appaiono più pillole"},
	{"45", "Asso di Picche", "Appaiono più carte"},
	{"46", "Forchetta di Isaac", "Possibilità di recuperare mezzo cuore dopo aver ripulito una stanza"},
	{"47", "", "<inutilizzato>"},
	{"48", "Una Pagina Mancante", "Quando vieni colpito, possibilità di ottenere l'effetto del necronomicon"},
	{"49", "Penny Sanguinolento", "Lascia mezzo cuore quando raccogli monete"},
	{"50", "Penny Bruciato", "Lascia bombe quando raccogli monete"},
	{"51", "Penny Appiattito", "Lascia chiavi quando raccogli monete"},
	{"52", "Penny Contraffatto", "Possibilità di ottenere monete extra quando raccogli monete"},
	{"53", "Zecca", "-15% vita dei boss#Recupera 1 cuore rosso quando entri in una stanza del boss"},
	{"54", "Testa Di Isaac", "Famiglio con lacrime penetranti"},
	{"55", "Fede di Madda", "Ottieni un cuore eterno all'inizio di ogni piano"},
	{"56", "Lingua di Giuda", "Riduce il prezzo dei patti col diavolo"},
	{"57", "Anima di ???", "Famiglio che rimbalza per la stanza#spara nella stessa direzione del giocatore"},
	{"58", "Ciocca di Sansone", "Possibilità di +0.5 danno in più quando uccidi un nemico"},
	{"59", "Occhio di Caino", "25% possibilità di rivelare le icone sulla mappa ogni piano"},
	{"60", "Zampa d'Uccello di Eva", "Possibilità di evocare un uccello morto quando uccidi un nemico"},
	{"61", "La Mano Sinistra", "Trasforma casse in casse rosse"},
	{"62", "Pietra Brillante", "Rocce che nascondono cunicoli e rocce dipinte si illuminano ogni 60 secondi"},
	{"63", "Forbicine", "Trasforma troll bombs in bombe"},
	{"64", "Verme Arcobaleno", "Effetti di vermi casuali"},
	{"65", "Verme Solitario", "Gittata X 2"},
	{"66", "Verme Pigro", "-0.4 Velocità di sparo diminuita#+4 Gittata"},
	{"67", "Dado Incrinato", "Effetti di dadi casuali quando vieni colpito"},
	{"68", "Super Magnete", "Magnete per utilizzabili"},
	{"69", "Polaroid Sbiadita", "Traveste casualmente il giocatore#confonde i nemici"},
	{"70", "Pidocchio", "Possibilità di evocare un ragno in una stanza ostile"},
	{"71", "Vescica di Bob", "Bombe lasciano pozze"},
	{"72", "Batteria dell'Orologio", "Possibilità di trovare più batterie"},
	{"73", "Minicicciolo", "Far esplodere bombe lascia bombe"},
	{"74", "Rilevatore", "Appaiono piùrocce che nascondono cunicoli"},
	{"75", "Errore", "Effetti di trinket casuali in ogni stanza"},
	{"76", "Fiche da Poker", "50/50 possibilità di utilizzabili extra O niente/nemici dalle casse"},
	{"77", "Vescicola", "Aumenta la spinta"},
	{"78", "Lancetta dei Secondi", "Aumenta la durata degli effetti degli stati"},
	{"79", "Senza Nome, Senza Fine", "Possibilità che quando usi pillole/carte lascino una copia della pillola/carta"},
	{"80", "Piuma Nera", "↑ +0.2 Danni per ogni oggetto cattivo che possiedi"},
	{"81", "Furia Cieca", "Invincibilità dura di più"},
	{"82", "Ferro di Cavallo Dorato", "+15% possibilità di ottenere oggetti doppi nel prossimo piano"},
	{"83", "Chiave del Negozio", "Apre i negozi gratuitamente"},
	{"84", "Costola di Avarizia", "Greed/Super Greed non appaiono più nei negozi"},
	{"85", "Karma", "Usare una Donation Machine può curarti o evocare un mendicante"},
	{"86", "Piccola Larva", "Distruggere cacche evoca mosche blu"},
	{"87", "Ciondolo di Mamma", "Cura mezzo cuore quando usi una chiave#Mezzi cuori vengono evocati come cuori pieni"},
	{"88", "NO!", "Abbassa le probabilità di trovare oggetti attivi nelle stanze degli oggetti"},
	{"89", "Guinzaglio per Bambini", "I famigli rimangono tutti vicini"},
	{"90", "Ministercolo", "Le cacche quando vengono distrutte esplodono"},
	{"91", "Meconio", "Aumenta le probabilità di trovare una cacca nera"},
	{"92", "Corona Incrinata", "Statistica casuale aumentata quando ottenuto"},
	{"93", "Pannolino Usato", "Mosche amichevoli"},
	{"94", "Coda di Pesce", "Raddoppia tutte le mosche blu / Evoca ragni"},
	{"95", "Dente Nero", "Spara casualmente denti velenosi"},
	{"96", "Verme Uroboro", "Le lacrime si muovono più velocemente e in una traiettoria a spirale"},
	{"97", "Tonsilla", "Possibilità di ottenere un famiglio quando vieni colpito#+2 Famigli massimi possibili"},
	{"98", "Pepita Verde", "Possibilità di sparare lacrime avvelenate appiccicose"},
	{"99", "Super Palla", "Possibilità di sparare lacrime rimbalzanti"},
	{"100", "Lampadina Vivida", "+1 a tutte le statistiche quando hai un oggetto attivo carico al massimo"},
	{"101", "Lampadina Fioca", "+0.5 Velocità, +1.5 Gittata, +0.3 Velocità d'attacco, +0.4 Lacrime, +1.5 Danno quando hai un oggetto attivo scarico"},
	{"102", "Carta Stracciata", "+1 stanza segreta extra per piano quando hai questo oggetto"},
	{"103", "Uguaglianza!", "Mezzi consumabili possono trasformarsi in completi"},
	{"104", "Osso dei Desideri", "Possibilità di evocare un piedistallo per oggetti quando vieni colpito#Viene poi distrutto"},
	{"105", "Sacchetto per il Pranzo", "Possibilità di lasciare un oggetto che aumenta la vita quando vieni colpito#Viene poi distrutto"},
	{"106", "Tappo di Sughero Smarrito", "Aumenta il raggio delle pozze che crei"},
	{"107", "Cuore di Corvo", "Il danno preso ignora cuori spirituali / neri , attingendo ai tuoi cuori rossi"},
	{"108", "Noce", "Lascia un consumabile / trinket casuale quando vieni colpito#Viene poi distrutto"},
	{"109", "Nastro Adesivo", "Ferma tutti i tuoi orbitali"},
	{"110", "Dollaro D'Argento", "I negozi ora appaiono nell'utero"},
	{"111", "Corona Sanguinolenta", "Stanze degli oggetti ora appaiono nell'utero"},
	{"112", "Pay To Win", "Box dei rifornimenti saranno sempre presenti nelle stanze degli oggetti"},
	{"113", "Locusta della Guerra", "Evoca una mosca esplosiva entrando in una stanza ostile"},
	{"114", "Locusta della Pestilenza", "Evoca una mosca velenosa entrando in una stanza ostile"},
	{"115", "Locusta della Carestia", "Evoca una mosca rallentate entrando in una stanza ostile"},
	{"116", "Locusta dela Morte", "Evoca una mosca che infligge il doppio dei tuoi danni entrando in una stanza ostile"},
	{"117", "Locusta della Conquista", "Evoca una mosca che infligge il doppio dei tuoi danni entrando in una stanza ostile"},
	{"118", "Ali di Pipistrello", "Possibilità di ottenere delle ali quando prendi danni#Durano per il resto della stanza"},
	{"119", "Cellula Staminale", "Cura mezzo cuore quando passi al prossimo piano"},
	{"120", "Forcina per Capelli", "Carica a massimo i tuoi oggetti attivi quando entri nella stanza di un boss"},
	{"121", "Croce di Legno", "Ti protegge dal primo danno che prendi ogni piano"},
	{"122", "Burro!", "Usare il tuo oggetto attivo ne lascerà una copia su un piedistallo all'interno della stanza"},
	{"123", "Piuma di Filigrana", "I boss Angeli lasciano oggetti normali invece che pezzi di chiavi"},
	{"124", "Fermaporte", "L'ultima porta che hai attraversato rimane aperta"},
	{"125", "Prolunga", "Connette i tuoi famigli con un raggio elettrico"},
	{"126", "Penny Marcio", "Crea una mosca blu quando predi una moneta"},
	{"127", "Piega-cucchiaini", "Dona le lacrime a ricerca ai tuoi famigli"},
	{"128", "Falangi", "Piccola possibilità di generare un cuore d'ossa quando prendi danno"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "0 - Il Matto", "Ti teletrasporta all'inizio"},
	{"2", "I - Il Bagatto", "Lacrime a ricerca per la stanza attuale"},
	{"3", "II - La Papessa", "Il piede di mamma schiaccia un nemico!"},
	{"4", "III - L'Imperatrice", "↑ +danni & +velocità per la stanza attuale"},
	{"5", "IV - L'Imperatore", "Ti teletrasporta alla stanza del boss"},
	{"6", "V - Il Papa", "Lascia 2 cuori dell'anima"},
	{"7", "VI - Gli Amanti", "Lascia 2 cuori rossi"},
	{"8", "VII - Il Carro", "Invincibilità + danni al contatto"},
	{"9", "VIII - Giustizia", "Lascia 1 bomba, 1 chiave, 1 moneta, 1 cuore"},
	{"10", "IX - L'Eremita", "Ti teletrasporta al negozio"},
	{"11", "X - Ruota della Fortuna", "Evoca una Slot / Fortune Machine"},
	{"12", "XI - Forza", "↑ +1 vita aumentata#↑ +0.3 danni aumentati#↑ +0.3 velocità aumentata#per la stanza attuale"},
	{"13", "XII - L'Appeso", "Volo per la stanza attuale"},
	{"14", "XIII - Morte", "Infligge 40 danni a tutti i nemici nella stanza"},
	{"15", "XIV - Temperanza", "Evoca una macchina per le donazioni di sangue"},
	{"16", "XV - Il Diavolo", "↑ +2 danni aumentati per la stanza attuale"},
	{"17", "XVI - La Torre", "Evoca troll bombs"},
	{"18", "XVII - Le Stelle", "Ti teletrasporta nella stanza degli oggetti"},
	{"19", "XVIII - La Luna", "Ti teletrasporta nella stanza segreta"},
	{"20", "XIX - Il Sole", "Infligge 100 danni a tutti i nemici#Vita massima#rivela l'intera mappa"},
	{"21", "XX - Il Giudizio", "Evoca un mendicante"},
	{"22", "XXI - Il Mondo", "Rivela la mappa e mostra le icone"},
	{"23", "2 di Fiori", "Duplica le tue Bombe"},
	{"24", "2 di Quadri", "Duplica i tuoi Soldi"},
	{"25", "2 di Picche", "Duplica le tue Chiavi"},
	{"26", "2 di Cuori", "Duplica i tuoi Cuori rossi"},
	{"27", "Asso di Fiori", "Trasforma tutti i consumabili in bombe"},
	{"28", "Asso di Quadri", "Trasforma tutti i consumabili in monete"},
	{"29", "Asso di Picche", "Trasforma tutti i consumabili in chiavi"},
	{"30", "Asso di Cuori", "Trasforma tutti i consumabili in cuori"},
	{"31", "Joker", "Ti teletrasporta nella stanza del diavolo / angelo"},
	{"32", "Hagalaz", "Distrugge tutte le rocce nella stanza"},
	{"33", "Jera", "Duplica tutti i consumabili in una stanza"},
	{"34", "Ehwaz", "Evoca una botola"},
	{"35", "Dagaz", "+1 Cuore dell'anima#Rimuove gli effetti delle maledizioni"},
	{"36", "Ansuz", "Visione completa della mappa per questo piano"},
	{"37", "Perthro", "Rerolla tutti gli oggetti sui piedistalli"},
	{"38", "Berkano", "Evoca 3 ragni blu e 3 mosche blu"},
	{"39", "Algiz", "Invincibilità per 30 secondi"},
	{"40", "Runa Muta", "Effetti casuali delle rune"},
	{"41", "Runa Nera", "Infligge 40 danni a tutti i nemici#Statistica casuale aumentata per ogni piedistallo nella stanza#(Distrugge tutti i piedistalli nella stanza)"},
	{"42", "Carta del Caos", "Carta della morte istantanea lanciabile"},
	{"43", "Carta di Credito", "Rimuove il prezzo dagli oggetti nel negozio e patti col diavolo attuali, rendendo tutto gratis!"},
	{"44", "Carta delle Regole", "Mostra \"utili\" consigli quando lo usi"},
	{"45", "Cards Against Humanity", "Riempie la stanza attuale con la CACCA!"},
	{"46", "Re Suicida", "Ti uccide istantaneamente ed evoca 10 consumabili / Collezionabili sul pavimento."},
	{"47", "Carta Esci Gratis di Prigione", "Apre tutte le porte nella stanza attuale"},
	{"48", "Carta ?", "Attiva i tuoi oggetti attivi gratis!"},
	{"49", "Scheggia di Dado", "Rerolla piedistalli e consumabili nella stanza attuale"},
	{"50", "Contatto di Emergenza", "Due mani di mamma calano e prendono un nemico"},
	{"51", "Carta Sacra", "Garantisce l'effetto del Manto Sacro per la stanza attuale#(I prossimi danni che prendi saranno 0)"},
	{"52", "Crescita Gigante", "↑ +7 danni aumentati#↑ +30 gittata aumentata#↑ +dimensioni aumentate#L'effetto dura per la stanza attuale"},
	{"53", "Richiamo Antico", "Evoca tre carte casuali quando usato"},
	{"54", "Passo Epocale", "Rallenta i nemici e le lacrime ma ti garantisce velocità aumentata#L'effetto dura per la stanza attuale"},
}

---------- Pills ----------
EID.descriptions[languageCode].unidentifiedPill = "Pillola non identificata"

EID.descriptions[languageCode].pills={
	{"0", "Gas Nocivo", "Fai una scorreggia"},
	{"1", "Brutto Trip", "Ti danneggia"},
	{"2", "Palle D'Acciaio", "+2 Cuori d'anima"},
	{"3", "Le Bombe sono Chiavi", "Scambia le bombe con le chiavi"},
	{"4", "Diarrea Esplosiva", "Lascia dietro di te una fila di bombe"},
	{"5", "Salute al Massimo", "Cura Totale"},
	{"6", "Meno Salute", "↓ Vita Diminuita"},
	{"7", "Più Salute", "↑ Vita Aumentata"},
	{"8", "Ho trovato delle Pillole", "Ottieni il nulla"},
	{"9", "Pubertà", "Prendendone 3 si diventa adulti"},
	{"10", "Moscarina", "Aggiunge una mosca che gira attorno a te"},
	{"11", "Meno Gittata", "↓ -2 Gittata"},
	{"12", "Più Gittata", "↑ +2.5 Gittata"},
	{"13", "Meno Velocità", "↓ -0.12 Velocità"},
	{"14", "Più Velocità", "↑ +0.15 Velocità Aumentata"},
	{"15", "Meno Lacrime", "↓ -0.28 Lacrime"},
	{"16", "Più Lacrime", "↑ +0.35 Lacrime"},
	{"17", "Meno Fortuna", "↓ -1 Fortuna"},
	{"18", "Più Fortuna", "↑ +1 Fortuna"},
	{"19", "Telepillole", "Ti teletrasporta in una stanza casuale"},
	{"20", "Energia per 48 Ore!", "Ricarica completa#Rilascia 1 o 2 batterie"},
	{"21", "Ematemesi", "Rimani con un solo cuore rosso#Rilascia da 1 a 4 cuori rossi"},
	{"22", "Paralisi", "Non puoi muoverti per 5 secondi"},
	{"23", "Ho visto tutto!", "Apre tutte le stanze segrete presenti sul piano"},
	{"24", "Feromoni", "Fa innamorare tutti i nemici nella stanza"},
	{"25", "Amnesia", "Oscura la mappa"},
	{"26", "Limonata", "Evoca una grande chiazza di limonata che fa danno ai nemici"},
	{"27", "Ma 6 1 Mago?", "Isaac spara in diagonale per un minuto"},
	{"28", "Percocet!", "Ottieni sempre mezzo cuore di danno quando vieni colpito nella stanza "},
	{"29", "Astinenza!", "Ottieni sempre un cuore di danno quando vieni colpito nella stanza"},
	{"30", "Re-Lax", "Lascia dietro di te una fila di cacca"},
	{"31", "???", "Ottieni la maledizione del perduto per tutto il piano"},
	{"32", "Una ti rende più grande", "Diventi più grande"},
	{"33", "Una ti rende più piccolo", "Diventi più piccolo"},
	{"34", "Infestato!", "Trasforma tutte le cacche presenti nella stanza in mosche blu"},
	{"35", "Infestato?", "Trasforma tutti i nemici presenti nella stanza in ragni blu"},
	{"36", "Pillola del Potere!", "Invincibilità temporanea"},
	{"37", "Rétro Visione", "Pixelizza lo schermo per 30 secondi#Puo essere annullato chiudendo e riaprendo la partita"},
	{"38", "Amici fino alla Fine!", "Evoca 3 mosche blu"},
	{"39", "Liqui-Lax", "Genera una chiazza di cacca che fa scivolare i nemici"},
	{"40", "Qualcosa Non Quadra...", "Genera una chiazza nera che rallenta i nemici"},
	{"41", "Ho Sonno...", "Rallenta tutti i nemici nella stanza"},
	{"42", "Sono Euforico!!!", "Velocizza tutti i nemici nella stanza"},
	{"43", "Gulp!", "Consuma il tuo trinket e ti dona permanentemente il suo effetto"},
	{"44", "Orf!", "Spara una lacrima di Ipecac"},
	{"45", "Baciato dal Sole!", "Invincibilità temporanea"},
	{"46", "Vurp!", "Evoca l'ultima pillola utilizzata"},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Prossimi Drop Stanza del Sacrificio]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "50% chance per 1 Moneta#100% chance per 1 Bomba, sul B1 se hai sconfitto il Boss in meno di un minuto"},
	{"2", "", "50% chance per 1 Moneta#100% chance per 1 Bomba, sul B1 se hai sconfitto il Boss in meno di un minuto"},
	{"3", "", "67% chance di aumento possibilità della Stanza{{AngelRoom}} dell'Angelo"},
	{"4", "", "50% chance per 1 Forziere casuale"},
	{"5", "", "33% chance per 3 Monete#67% chance di aumento possibilità della Stanza{{AngelRoom}} dell'Angelo"},
	{"6", "", "33% chance di teletrasporto alla Stanza dell'Angelo{{AngelRoom}}/Patto col{{DevilRoom}} Diavolo#67% chance di un forziere casuale"},
	{"7", "", "33% chance di 1 oggetto della stanza dell'{{AngelRoom}} Angelo#67% chance di 1 cuore dell'anima"},
	{"8", "", "100% chance per 7 Bombe troll"},
	{"9", "", "100% chance di evocare il boss\"Uriel\""},
	{"10", "", "50% chance di 7 cuori dell'anima#50% chance per 30 Monete"},
	{"11", "", "100% chance di evocare il boss \"Gabriel\""},
	{"12", "", "50% chance di teletrasporto al piano della \"Stanza Oscura\""},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Effetto dadi]"

EID.descriptions[languageCode].dice={
	{"1", "", "Rerolla tutti i tuoi oggetti#(ha effetto solo sui collezionabili)"},
	{"2", "", "Rerolla tutti i consumabili nella stanza"},
	{"3", "", "Rerolla tutti i consumabili nell'intero piano"},
	{"4", "", "Rerolla tutti gli oggetti dei piedistalli che si trovano a terra#Ad eccezione dei Patti col Diavolo"},
	{"5", "", "Rerolla e ricomincia il piano"},
	{"6", "", "Rerolla tutti i tuoi oggetti, tutti i consumabili & gli oggetti su tutto il piano"},
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Beelzebub",		-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Yes Mother?",		-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}


---------- MISC ----------

EID.descriptions[languageCode].VoidText = "Se assorbito, si ottengono:"
-- {1} will become the number text (like "{1} Tears" -> "+0.5 Tears")
EID.descriptions[languageCode].VoidNames = {"{1} Velocità", "{1} Lacrime", "{1} Danni", "{1} Gittata", "{1} Velocità Colpi", "{1} Fortuna"}

EID.descriptions[languageCode].CollectionPageInfo = "Questo oggetto deve essere raccolto per la collezione!"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Nome Oggetto Demo",
	DemoObjectTransformation = "Trasformazione Demo",
	DemoObjectText = "Questo testo è in italiano#Una lunga descrizione molto figa per simulare linebreak causati dalla larghezza del testo nell'EID!#{{Collectible4}} Anche questa è una riga figa#{{Heart}} Questa riga ti ama#{{AngelDevilChance}} Questa riga può essere il tuo angelo o il tuo diavolo#\1 {{Damage}} +1 Aumento di Statistica",
}

-- the ItemReminder description will predict the abilities of items with a header like "Item Name Result"
EID.descriptions[languageCode].ItemReminder = {
	ResultHeader = " Esito",
	InventoryEmpty = "(Il PG non ha oggetti)",
	CategoryNames = {
		Overview = "Panoramica Inventario",
		Special = "Speciale",
		Actives = "Oggetti attivi tenuti",
		Pockets = "Oggetti secondari tenuti",
		Trinkets = "Ninnoli tenuti",
		Passives = "Oggetti passivi tenuti"
	}
}

-- https://wofsauge.github.io/IsaacDocs/rep/enums/RoomType.html
-- Includes Repentance room types for localization convenience
EID.descriptions[languageCode].RoomTypeNames = { "Stanza Normale", "Negozio", "Stanza I AM ERROR", "Stanza dei Tesori", "Stanza Boss", "Stanza Miniboss", "Stanza Segreta", "Stanza Super Segreta", "Stanza Arcade", "Stanza Maledetta", "Stanza Sfida", "Biblioteca", "Stanza dei Sacrifici", "Stanza del Diavolo", "Stanza dell'Angelo", "Stanza Cunicolo", "Stanza Boss Rush", "Stanza di Isaac", "Stanza Spoglia", "Stanza del Baule", "Stanza del Dado", "Mercato Nero", "Anticamera", "Planetario", "Entrata Teletrasporto", "Uscita Teletrasporto", "Botola Percorso Alternativo", "Stanza Chiave Blu", "Stanza Ultra Segreta",
-- Not technically room types but still potentially useful to have localized
[666] = "Stanza dell'Angelo/del Diavolo", [1024] = "Stanza Rossa", [1025] = "Stanza Rossa Speciale" }

-- currently used for D1
EID.descriptions[languageCode].PickupNames = {
	["5.0"] = "None",

	["5.10"] = "{{Heart}} Cuore",
	["5.10.1"] = "{{Heart}} Cuore", ["5.10.2"] = "{{HalfHeart}} Mezzo Cuore", ["5.10.3"] = "{{SoulHeart}} Cuore Celeste", ["5.10.4"] = "{{EternalHeart}} Cuore Eterno", ["5.10.5"] = "{{Heart}} Double Heart", ["5.10.6"] = "{{BlackHeart}} Cuore Nero", ["5.10.7"] = "{{GoldHeart}} Cuore D'Oro", ["5.10.8"] = "{{HalfSoulHeart}} Mezzo Cuore Celeste", ["5.10.9"] = "{{Heart}} Scappo Cuore", ["5.10.10"] = "{{BlendedHeart}} Cuore Fuso", ["5.10.11"] = "{{EmptyBoneHeart}} Cuore Ossuto", ["5.10.12"] = "{{RottenHeart}} Cuore Marcio",

	["5.20"] = "{{Coin}} Moneta",
	["5.20.1"] = "{{Crafting8}} Penny", ["5.20.2"] = "{{Crafting9}} Nichelino", ["5.20.3"] = "{{Crafting10}} Decino", ["5.20.4"] = "{{Crafting8}} Doppio Penny", ["5.20.5"] = "{{Crafting11}} Penny Fortunato", ["5.20.6"] = "{{Crafting9}} Nichelino Appiccicoso", ["5.20.7"] = "{{Crafting26}} Penny Dorato",

	["5.30"] = "{{Key}} Chiave",
	["5.30.1"] = "{{Crafting12}} Chiave", ["5.30.2"] = "{{Crafting13}} Chiave Dorata", ["5.30.3"] = "{{Crafting12}} Portachiavi", ["5.30.4"] = "{{Crafting14}} Chiave Carica",

	["5.40"] = "{{Bomb}} Bomba",
	["5.40.1"] = "{{Crafting15}} Bomba", ["5.40.2"] = "{{Crafting15}} Doppia Bomba", ["5.40.3"] = "{{Crafting15}} Bomba Troll", ["5.40.4"] = "{{Crafting16}} Bomba Dorata", ["5.40.5"] = "{{Crafting15}} Mega Bomba Troll", ["5.40.7"] = "{{Crafting17}} Giga Bomba",

	["5.90"] = "{{Battery}} Batteria",
	["5.90.0"] = "{{Crafting19}} Mini Batteria", --AB+ didn't have subtypes for batteries
	["5.90.1"] = "{{Crafting19}} Mini Batteria", ["5.90.2"] = "{{Crafting18}} Micro Batteria", ["5.90.3"] = "{{Crafting20}} Mega Batteria", ["5.90.4"] = "{{Crafting28}} Batteria Dorata",

	["5.50"] = "{{Chest}} Baule", ["5.51"] = "{{BombChest}} Baule Detonabile", ["5.52"] = "{{SpikedChest}} Baule Spinoso", ["5.53"] = "{{EternalChest}} Baule Eterno", ["5.54"] = "{{MimicChest}} Baule Imitante", ["5.55"] = "{{OldChest}} Vecchio Baule", ["5.56"] = "{{WoodenChest}} Baule di Legno", ["5.57"] = "{{MegaChest}} Mega Baule", ["5.58"] = "{{HauntedChest}} Baule Infestato", ["5.60"] = "{{GoldenChest}} Baule Dorato", ["5.360"] = "{{RedChest}} Baule Rosso",

	["5.69"] = "{{GrabBag}} ", ["5.69.1"] = "{{GrabBag}} Piglia Sacco", ["5.69.2"] = "{{BlackSack}} Sacco Nero",

	["5.70"] = "{{Pill}} Pillola",
	["5.300"] = "{{Card}} Carta",
	["5.301"] = "{{Rune}} Runa", -- not a real id
	["5.350"] = "{{Trinket}} Ninnolo",

}

EID.descriptions[languageCode].ConditionalDescs = {
	["5.100.81"] = "Personaggi che non hanno Cuori Rossi non possono avere Cuori Rossi vengono portati ad 1 Cuore Nero/Celeste", -- Dead Cat
	["5.100.241"] = "{{GreedMode}} Non influenza la Modalità Avido", -- Contract From Below
	["5.100.135 (Keeper)"] = "{{Player14}} Genera 0-1 monete se si gioca il Mercante", -- IV Bag Keeper
	["5.100.135 (PHD)"] = "{{Collectible75}} Genera 2-3 monete se si ha il Dottorato", -- IV Bag PHD
	["5.100.442"] = "Non ha effetti per i personaggi che non possono avere Cuori Rossi", -- Dark Prince's Crown
	["5.300.15"] = "{{DemonBeggar}} Genera uno Scroccacuori", -- Temperance (Greed Mode effect)
	["5.350.23"] = "{{Warning}} Morire in una {{SacrificeRoom}} Stanza dei Sacrifici mentre si possiede questo ninnolo sblocca Lo Smarrito", -- Missing Poster (Unlock The Lost)
}

EID.descriptions[languageCode].BFFSSynergies = {
	["NoEffect"] = "Nessun Effetto",
	["DoubleDamage"] = "Danni raddoppiati",
	["5.100.273"] = "Raddoppia i danni da impatto e aumenta di 25 i danni da esplosione", -- Bob's Brain
	["5.100.266"] = "Genera un Ragno Blu in più", -- Juicy Sack
	["5.100.360"] = "Spara lacrime che infliggono il 200% in più dei danni", -- Incubus
	["5.100.417"] = "Aumenta il raggio, ma non i danni", -- Succubus
	["5.100.537"] = "Aumenta le dimensioni della pozza, ma non i sanni", -- Lil Spewer
	["5.100.539"] = "Genera una variante campione del nemico", -- Mystery Egg
}
