------------------------------------------------------------------
-----  Basic polish descriptions based on Platinumgod.co.uk -----
------------------------------------------------------------------

-- FORMAT: Item ID | Name| Description
-- '#' = starts new line of text

--Special character markup:
-- ↑ = Up Arrow   |  ↓ = Down Arrow    | ! = Warning

-- init pl table
EID.descriptions["pl"] = {}
EID.descriptions["pl"].custom = {} -- table for custom entity descriptions

EID.descriptions["pl"].collectibles={
    {"1", "The Sad Onion", "↑ +0.7 Szybkostrzelności"},
    {"2", "The Inner Eye", "Potrójne strzały#↓ Mniejsza Szybkostrzelność"},
    {"3", "Spoon Bender", "Samonaprowadzające siê łzy"},
    {"4", "Cricket's Head", "↑ +0.5 Obrażeń#↑ Mnoży obrażenia +50% #+ łzy odrzucają wrogów"},
    {"5", "My Reflection", "Daje twoim łzom efekt boomeranga#↑ +1.5 Zasiêgu#↑ +0.6 Prêdkości Strzał#↑ +1 Wysokości lotu łez"},
    {"6", "Number One", "↑ +1.5 Szybkostrzelności#↓ -15.78 Zasiêgu#↑ +0.45 Wysokości lotu łez"},
    {"7", "Blood of the Martyr", "↑ +1.0 Obrażeń#↑ Mnoży obrażenia +50% jeśli posiadasz Book of Belial"},
    {"8", "Brother Bobby", "Familiar strzelający normalnymi łzami"},
    {"9", "Skatole", "Napotkane wrogie muchy stają siê przyjazne"},
    {"10", "Halo of Flies", "+2 Muchy orbitujące"},
    {"11", "1up!", "↑ +1 Życie#Odradzasz siê z pełnym zdrowiem"},
    {"12", "Magic Mushroom", "↑ +1 Serce#↑ +0.3 Obrażeń#↑ Mnoży obrażenia +50%#↑ +5.25 Zasiêgu#↑ +0.3 Szybkości#↑ +0.5 Wysokości lotu łez#Odnawia twoje serca do pełna!"},
    {"13", "The Virus", "Trujący dotyk#↓ -0.1 Szybkości#Wrogowie mogą upuścić czarne serca jeśli zostaną zatruci"},
    {"14", "Roid Rage", "↑ +0.6 Szybkości#↑ +5.25 Zasiêgu#↑ +0.5 Wysokości lotu łez"},
    {"15", "<3", "↑ +1 Serce#Leczy twoje serca do pełna"},
    {"16", "Raw Liver", "↑ +2 Serca#Leczy twoje serca do pełna"},
    {"17", "Skeleton Key", "+99 Kluczy"},
    {"18", "A Dollar", "+99 Monet"},
    {"19", "Boom!", "+10 Bomb"},
    {"20", "Transcendence", "Latanie!"},
    {"21", "The Compass", "Ujawnia wszystkie ikony na mapie#Nie pokazuje układu mapy"},
    {"22", "Lunch", "↑ +1 Serce"},
    {"23", "Dinner", "↑ +1 Serce"},
    {"24", "Dessert", "↑ +1 Serce"},
    {"25", "Breakfast", "↑ +1 Serce"},
    {"26", "Rotten Meat", "↑ +1 Serce"},
    {"27", "Wooden Spoon", "↑ +0.3 Szybkości"},
    {"28", "The Belt", "↑ +0.3 Szybkości"},
    {"29", "Mom's Underwear", "↑ +5.25 Zasiêgu#↑ +0.5 Wysokości lotu łez"},
    {"30", "Mom's Heels", "↑ +5.25 Zasiêgu#↑ +0.5 do Wysokości lotu łez"},
    {"31", "Mom's Lipstick", "↑ +5.25 Zasiêgu#↑ +0.5 do Wysokości lotu łez"},
    {"32", "Wire Coat Hanger", "↑ +0.7 Szybkostrzelności"},
    {"33", "The Bible", "Otrzymujesz Latanie na aktualny pokój#Natychmiast zabija Mamê i Serce matki#!!! Zabija CIEBIE kiedy użyjesz go podczas walki z Szatanem"},
    {"34", "The Book of Belial", "↑ +2 Obrażeń#↑ +12.5% szans na Devil Deal Room#↑ Mnoży obrażenia +50% jeśli posiadasz Blood of the Martyr"},
    {"35", "The Necronomicon", "Zadaje 40 obrażeń wszystkim w pokoju"},
    {"36", "The Poop", "Upuszcza kupê na podłogê#Może zostać położony obok dołu i zniszczony żeby zrobić most"},
    {"37", "Mr. Boom", "Upuszcza wielką bombê pod graczem która zadaje 110 obrażeń"},
    {"38", "Tammy's Head", "Wystrzeliwuje 10 łez w krêgu wokół Isaaca"},
    {"39", "Mom's Bra", "Zamraża wszystkich wrogów w aktualnym pokoju na 4 sekundy"},
    {"40", "Kamikaze!", "Powoduje eksplozje w miejscu gdzie znajduje sie gracz"},
    {"41", "Mom's Pad", "Straszy wszystkich wrogów w aktualnym pokoju na 5 sekund"},
    {"42", "Bob's Rotten Head", "Trująca bomba do rzucania"},
    {"43", "", "<przedmiot nie istnieje>"},
    {"44", "Teleport!", "Teleportuje Isaaca do losowego pokoju"},
    {"45", "Yum Heart", "Leczy 1 serce"},
    {"46", "Lucky Foot", "↑ +1.0 Szczêścia#Lepsza szansa na wygraną podczas hazardu"},
    {"47", "Doctor's Remote", "Epic Fetus na żądanie!#Kontrolowany Airstrike (Nalot bombowy) "},
    {"48", "Cupid's Arrow", "Twoje łzy przenikają przez wrogów"},
    {"49", "Shoop da Whoop!", "Laser zadający duże obrażenia "},
    {"50", "Steven", "↑ +1 Obrażeń"},
    {"51", "Pentagram", "↑ +1.0 Obrażeń#↑ +10% szans na Devil Deal Room"},
    {"52", "Dr. Fetus", "Bombowe łzy!"},
    {"53", "Magneto", "Przyciąga pick-upy do gracza"},
    {"54", "Treasure Map", "Ujawnia układ piêtra"},
    {"55", "Mom's Eye", "Losowa szansa na wystrzelenie łzy w tył"},
    {"56", "Lemon Mishap", "Upuszcza kałużê lemoniady"},
    {"57", "Distant Admiration", "Mucha orbitująca na średni zasiêg"},
    {"58", "Book of Shadows", "Niewrażliwość na 10 sekund"},
    {"59", "", "<przedmiot nie istnieje>"},
    {"60", "The Ladder", "Możesz przejść przez pojedynczy dół"},
    {"61", "", "<przedmiot nie istnieje>"},
    {"62", "Charm of the Vampire", "Leczy ciê o połowê serca co 13 zabitych wrogów"},
    {"63", "The Battery", "Przedmioty na spacji mogą zostać naładowane 2 razy"},
    {"64", "Steam Sale", "-50% na przedmioty ze sklepu#Zdobycie dwóch sprawi że wszystko bêdzie darmowe"},
    {"65", "Anarchist Cookbook", "Tworzy 6 troll bomb w losowych miejscach w pokoju"},
    {"66", "The Hourglass", "Spowalnia wrogów na 8 sekund"},
    {"67", "Sister Maggy", "Familiar strzelający normalnymi łzami"},
    {"68", "Technology", "Zamiast łez strzelasz laserkiem"},
    {"69", "Chocolate Milk", "Ładowane łzy"},
    {"70", "Growth Hormones", "↑ +1.0 Obrażeń#↑ +0.4 Szybkości"},
    {"71", "Mini Mush", "↑ +0.3 Szybkości#↓ -4.25 Zasiêgu*#↑ +1.5 Wysokości lotu łez"},
    {"72", "Rosary", "+3 Serca Duszy#Wiêksza szansa na pojawienie siê Biblii"},
    {"73", "Cube of Meat", "LVL1: Orbitujące miêsko#LVL2: Orbitujące strzelające miêsko#LVL3: Meat boy LVL 1#LVL4: Meat boy LVL 2"},
    {"74", "A Quarter", "+25 monet"},
    {"75", "PHD", "Lepsze Pigułki# +1 Pigułka"},
    {"76", "X-Ray Vision", "Odkrywa sekretne pokoje"},
    {"77", "My Little Unicorn", "Niewrażliwość + zadajesz obrażenia kontaktowe"},
    {"78", "Book of Revelations", "+1 Serce Duszy#Wiêksza szansa na Jeźdźca#↑ +17.5% szans na Devil Deal Room"},
    {"79", "The Mark", "↑ +1.0 Obrażeń#↑ +0.2 Szybkości#+1 Serce Duszy"},
    {"80", "The Pact", "↑ +0.5 Obrażeń#↑ +0.7 Szybkostrzelności#+2 Serca Duszy"},
    {"81", "Dead Cat", "↑ +9 Żyć#Odradzasz siê z 1 Sercem"},
    {"82", "Lord of the Pit", "Latanie#↑ +0.3 Szybkości"},
    {"83", "The Nail", "+1 Serce Duszy#↑ +0.7 Obrażeń#↓ -0.18 Szybkości#Rozwalasz kamienie"},
    {"84", "We Need To Go Deeper!", "Tworzy klapê w podłodze dziêki której możesz pominąć piêtro#10% szans na klapê do Crawl Space"},
    {"85", "Deck of Cards", "Tworzy 1 Kartê"},
    {"86", "Monstro's Tooth", "Przyzywa Monstro który skacze na losowego wroga"},
    {"87", "Loki's Horns", "Szansa na wystrzelenie łez w 4 strony"},
    {"88", "Little Chubby", "Familiar który szarżuje na przód"},
    {"89", "Spider Bite", "Łzy mają teraz szanse na spowolnienie wrogów"},
    {"90", "The Small Rock", "↑ +1 Obrażeń#↑ +0.2 Szybkostrzelności#↓ -0.2 Szybkości"},
    {"91", "Spelunker Hat", "Ujawnia Sekretny Pokój jeśli jesteś obok niego"},
    {"92", "Super Bandage", "↑ +1 Serce#+2 Serca Duszy"},
    {"93", "The Gamekid", "Niewrażliwość + obrażenia kontaktowe#Zjedzenie wroga odnawia trochê Serca"},
    {"94", "Sack of Pennies", "Upuszcza losową monete co 2 pokoje"},
    {"95", "Robo-Baby", "Familiar z laserowymi łzami"},
    {"96", "Little C.H.A.D.", "Upuszcza połowê Serca co 3 pokoje"},
    {"97", "The Book of Sin", "Tworzy losowy Pick-Up"},
    {"98", "The Relic", "Tworzy 1 Serce Duszy co 4 pokoje"},
    {"99", "Little Gish", "Familiar który strzela spowalniającymi łzami"},
    {"100", "Little Steven", "Samonaprowadzające siê łzy"},
    {"101", "The Halo", "↑ +1 Serce#↑ +0.3 Obrażeń#↑ +0.2 Szybkostrzelności#↑ +0.25 Zasiêgu#↑ +0.3 Szybkości#↑ +0.5 Wysokości lotu Łez"},
    {"102", "Mom's Bottle of Pills", "Tworzy 1 Pigułkê"},
    {"103", "The Common Cold", "Szansa na zatrucie przeciwnika łzą"},
    {"104", "The Parasite", "Łzy rozdzielają siê gdy dotkną celu"},
    {"105", "The D6", "Przelosowuje przedmioty na piedestałach w pokoju"},
    {"106", "Mr. Mega", "↑ Obrażenia od bomb zwiêkszone x2.25#+5 Bomb"},
    {"107", "The Pinking Shears", "Latanie#Twoje oddzielone ciało zadaje obrażenia przez dotyk"},
    {"108", "The Wafer", "Każde otrzymane obrażenia są zredukowane do pół serca"},
    {"109", "Money = Power", "↑ +0.04 Obrażeń zwiêkszone za każdą posiadaną monetê"},
    {"110", "Mom's Contacts", "Zamrażające łzy#↑ +0.25 Zasiêgu"},
    {"111", "The Bean", "Trujący pierd"},
    {"112", "Guardian Angel", "Orbitujący#Przyśpiesza wszystkie orbitujące"},
    {"113", "Demon Baby", "Samo-strzelający Familiar"},
    {"114", "Mom's Knife", "Nóż zamiast łez"},
    {"115", "Ouija Board", "Łzy widmo"},
    {"116", "9 Volt", "-1 Ładowanie trzymanego przedmiotu#W pełni naładowuje aktualny przedmiot"},
    {"117", "Dead Bird", "Uwalnia ptaka gdy otrzymasz obrażenia"},
    {"118", "Brimstone", "Ładuje potêżny laser zamiast łez"},
    {"119", "Blood Bag", "↑ +1 Serce#↑ +0.3 Szybkości#Leczy 5 serc"},
    {"120", "Odd Mushroom", "↑ +1.7 Szybkostrzelności#↑ +0.3 Szybkości#↓ Mniejsze obrażenia"},
    {"121", "Odd Mushroom", "↑ +1 Pusty kontener życia#↑ +0.3 Obrażeń#↑ +0.25 Zasiêgu#↓ -0.1 Mniejsza szybkość#↑ +0.5 Wysokości lotu łez"},
    {"122", "Whore of Babylon", "!!! Kiedy masz pół serca lub mniej:#↑ +1.5 Obrażeń#↑ +0.3 Szybkości"},
    {"123", "Monster Manual", "Losowy Familiar na pokój"},
    {"124", "Dead Sea Scrolls", "Losowy efekt aktywnych przedmiotów"},
    {"125", "Bobby-Bomb", "Samonaprowadzające bomby#+5 Bomb"},
    {"126", "Razor Blade", "↑ +1.2 Obrażeń#↓ -1 Serc"},
    {"127", "Forget Me Now", "!!! JEDNORAZOWY !!!#Przelosowuje całe piêtro"},
    {"128", "Forever alone", "Latający orbitujący Familiar#Duża odległość"},
    {"129", "Bucket of Lard", "↑ +2 Serc#↓ -0.2 Szybkości#Leczy pół serca"},
    {"130", "A Pony", "Zapewnia latanie póki jest trzymany#Szarżuje w danym kierunku"},
    {"131", "Bomb Bag", "Upuszcza 1 bombê co drugi pokój"},
    {"132", "A Lump of Coal", "Wiêksze obrażenia zależnie od przebytego przez łzê dystansu"},
    {"133", "Guppy's Paw", "!!! Zamiana:#1 Serce na Serce Duszy"},
    {"134", "Guppy's Tail", "Pojawia siê wiêcej skrzynek"},
    {"135", "IV Bag", "Przenośny Bank Krwi#Pół Serca = 1 Moneta"},
    {"136", "Best Friend", "Wybuchowy wabik#Wabi przeciwników"},
    {"137", "Remote Detonator", "Wysadza bomby na rozkaz#+5 bomb"},
    {"138", "Stigmata", "↑ +1 Serce#↑ +0.3 Obrażeń"},
    {"139", "Mom's Purse", "Możesz teraz trzymać 2 trinkety"},
    {"140", "Bob's Curse", "Trujące bomby#+5 Bomb"},
    {"141", "Pageant Boy", "Upuszcza 7 losowych monet"},
    {"142", "Scapular", "Kiedy Twoje życie spadnie do Pół Serca, dostajesz 1 Serce Duszy#(Jedno na pokój)"},
    {"143", "Speed Ball", "↑ +0.3 Szybkości#↑ +0.2 Prêdkość łez"},
    {"144", "Bum Friend", "Przerabia monety na Pick-upy"},
    {"145", "Guppy's Head", "Pojawia 2-4 niebieskich much"},
    {"146", "Prayer Card", "+1 Wieczne Serce"},
    {"147", "Notched Axe", "Niszczy obiekty (kamienie itp.) w pokoju"},
    {"148", "Infestation", "Pojawia muchy gdy otrzymasz obrażenia"},
    {"149", "Ipecac", "Wybuchowe łzy"},
    {"150", "Tough Love", "Szansa na strzelenie zêbem"},
    {"151", "The Mulligan", "1/6 szansy na pojawienie muchy gdy trafiasz przeciwnika"},
    {"152", "Technology 2", "Permanentny laser!#↓ -35% Obrażeń"},
    {"153", "Mutant Spider", "Poczwórny strzał!#↓ Szybkostrzelność spada"},
    {"154", "Chemical Peel", "↑ +2 Obrażeń z lewego oka"},
    {"155", "The Peeper", "Lata dookoła pokoju#Dotykając zadaje obrażenia"},
    {"156", "Habit", "+1 Naładowanie gdy otrzymasz obrażenia"},
    {"157", "Bloody Lust", "↑ Wzrastają obrażenia przy zranieniu#Pozostaje na całe piêtro"},
    {"158", "Crystal Ball", "Odkrywa całą mapê#Upuszcza losową kartê lub Serce Duszy"},
    {"159", "Spirit of the Night", "Latanie#Widmowe łzy"},
    {"160", "Crack the Sky", "Promienie światła z nieba!"},
    {"161", "Ankh", "Odrodzisz siê jako ??? (Blue Baby)"},
    {"162", "Celtic Cross", "Szansa na nietykalność na kilka sekund po otrzymaniu obrażeń"},
    {"163", "Ghost Baby", "Familiar z widmowymi łzami"},
    {"164", "The Candle", "Wystrzeliwuje niebieski płomień"},
    {"165", "Cat-o-nine-tails", "↑ +1 Obrażeń#↑ +0.23 Prêdkość łez"},
    {"166", "D20", "Przelosowuje Pick-upy"},
    {"167", "Harlequin Baby", "Familiar który strzela w kształcie litery V dwoma łzami"},
    {"168", "Epic Fetus", "Kontrolowany zrzut pocisku zamiast łez"},
    {"169", "Polyphemus", "Mega łzy!#↑ Obrażenia wzrastają#↓ Szybkostrzelność spada"},
    {"170", "Daddy Longlegs", "Depcze przeciwników"},
    {"171", "Spider Butt", "Spowalnia przeciwników#Zadaje przeciwnikom obrażenia"},
    {"172", "Sacrificial Dagger", "Orbitujący nóż"},
    {"173", "Mitre", "Wiêksza szansa na Serca Dusz"},
    {"174", "Rainbow Baby", "Strzela losowymi łzami"},
    {"175", "Dad's Key", "Otwiera wszystkie drzwi w pokoju, nawet Secret Room"},
    {"176", "Stem Cells", "↑ +1 Serce#↑ +0.16 Prêdkość łez"},
    {"177", "Portable Slot", "Przenośna maszyna losująca"},
    {"178", "Holy Water", "Zostawia kałużê zadającą obrażenia przeciwnikom, gdy otrzymasz cios"},
    {"179", "Fate", "Latanie#+1 Wieczne Serce"},
    {"180", "The Black Bean", "Pierdzisz gdy otrzymasz obrażenia"},
    {"181", "White Pony", "Daje latanie gdy go trzymasz#Źwiêta szarża"},
    {"182", "Sacred Heart", "Samonaprowadzające łzy#↑ +1 Serce#↑ Obrażenia wysoko w górê#↓ -0.4 Szybkostrzelność#↓ -0.25 Prêdkość łez#↑ +0.375 Zasiêg"},
    {"183", "Tooth Picks", "↑ +0.7 Szybkostrzelność#↑ +0.16 Prêdkość łez"},
    {"184", "Holy Grail", "Latanie#↑ +1 Serce"},
    {"185", "Dead Dove", "Latanie#Widmowe łzy"},
    {"186", "Blood Rights", "Zadaje 40 obrażeń wszystkim przeciwnikom#-1 Czerwone serce gdy używasz"},
    {"187", "Guppy's Hairball", "Rosnąca kupka włosów#Przywiązana do Ciebie#Rośnie gdy zabije"},
    {"188", "Abel", "Odtwarza twoje ruchy#Strzela w twoim kierunku"},
    {"189", "SMB Super Fan", "↑ +1 Serce#↑ +0.3 Obrażenia#↑ +0.2 Szybkostrzelność#↑ +0.5 Zasiêg#↑ +0.2 Szybkość#↑ +1.0 Wysokość lotu łez#Pełne życie"},
    {"190", "Pyro", "+99 Bomb"},
    {"191", "3 Dollar Bill", "Losowy efekt łez"},
    {"192", "Telepathy For Dummies", "Samonaprowadzające łzy na pokój"},
    {"193", "MEAT!", "↑ +1 Serce#↑ +0.3 Obrażeń"},
    {"194", "Magic 8 Ball", "↑ +0.16 Prêdkość łez#+1 Karta"},
    {"195", "Mom's Coin Purse", "Upuszcza 4 tabletki"},
    {"196", "Squeezy", "+2 Serca Dusz#↑ +0.4 Szybkostrzelność"},
    {"197", "Jesus Juice", "↑ +0.5 Obrażeń#↑ +0.25 Zasiêg#↑ +0.5 Wysokość lotu łez"},
    {"198", "Box", "Upuszcza po jednym z każdego rodzaju pick-upu"},
    {"199", "Mom's Key", "+2 Klucze#Wiêcej rzeczy ze skrzynek"},
    {"200", "Mom's Eyeshadow", "Urocze łzy"},
    {"201", "Iron Bar", "↑ +0.3 Obrażeń#Ogłuszające łzy"},
    {"202", "Midas' Touch", "Zamieniasz przeciwników w złoto dotykiem#Złoci przeciwnicy upuszczają monety"},
    {"203", "Humbleing Bundle", "Podwaja Pick-upy"},
    {"204", "Fanny Pack", "Upuszczasz losowy Pick-up gdy zostaniesz ranny"},
    {"205", "Sharp Plug", "-2 Serce = Naładowuje cały przedmiot pod spacją#!!! Działa tylko gdy przedmiot jest nienaładowany!"},
    {"206", "Guillotine", "↑ +1 Obrażeń#↑ Szybkostrzelność#Twoja głowa teraz orbituje wokół ciała#Strzelasz z głowy"},
    {"207", "Ball of Bandages", "LVL1: Orbitująca kulka#LVL2: Strzelająca orbitująca kulka#LVL3: Familiar ganiający przeciwników#LVL4: Wiêkszy Familiar"},
    {"208", "Champion Belt", "↑ +1 Obrażeń#!!! Wiêcej Championów"},
    {"209", "Butt Bombs", "↑ +5 Bomb#Wybuchy ogłuszają i zadają obrażenia każdemu przeciwnikowi w pokoju"},
    {"210", "Gnawed Leaf", "Jesteś nietykalny jeśli stoisz nieruchomo conajmniej 1 sekundê"},
    {"211", "Spiderbaby", "Pojawia pająki gdy obrywasz"},
    {"212", "Guppy's Collar", "↑ 50% szansy odrodzenia"},
    {"213", "Lost Contact", "Łzy z tarczą#↓ -0.15 Prêdkość łez"},
    {"214", "Anemic", "↑ +5 Zasiêg#Zostawiasz pod sobą kałużê gdy otrzymujesz cios"},
    {"215", "Goat Head", "↑ 100% szans na Devil/Angel rooms"},
    {"216", "Ceremonial Robes", "↑ +1 Obrażeń#+3 Czarnych serc"},
    {"217", "Mom's Wig", "Szansa na pojawienie pająków gdy strzelasz"},
    {"218", "Placenta", "Regeneruje powoli serca#↑ +1 Serce"},
    {"219", "Old Bandage", "↑ +1 Pusty kontener na serce#Losowa szansa na upuszczenie serca gdy obrywasz"},
    {"220", "Sad Bombs", "Wybuch łez!#+5 Bomb"},
    {"221", "Rubber Cement", "Odbijające siê łzy"},
    {"222", "Anti-Gravity", "↑ Szybkostrzelność#Anty grawitacyjne łzy"},
    {"223", "Pyromaniac", "Wybuchy Ciê leczą#+5 Bomb"},
    {"224", "Cricket's Body", "↑ +1 Szybkostrzelność #↓ -10.0 Zasiêg#Łzy rozdzielają siê na cztery po zniszczeniu"},
    {"225", "Gimpy", "Szansa na upuszczenie Serca Duszy/Czarnego kiedy otrzymujesz cios"},
    {"226", "Black Lotus", "↑ +1 Serce#+1 Serce Duszy#+1 Czarne serce"},
    {"227", "Piggy Bank", "+3 Monety#Upuszczasz monetê gdy obrywasz"},
    {"228", "Mom's Perfume", "Pociski strachu#↑ Szybkostrzelność"},
    {"229", "Monstro's Lung", "Łzy mogą być teraz naładowane i wypuszczone w stylu strzelby"},
    {"230", "Abaddon", "↑ +1.5 Obrażeń#↑ +0.2 Szybkości#Łzy strachu#↓ Usuwa wszystkie czerwone serca#+6 Czarnych Serc"},
    {"231", "Ball of Tar", "Zostawiasz spowalniającą kałużê#Spowalniające łzy"},
    {"232", "Stop Watch", "Permanentny efekt spowolnienia (aktywowany przez otrzymanie ciosu)"},
    {"233", "Tiny Planet", "Łzy orbitują wokół Ciebie#↑ +7.0 Wysokość lotu łez"},
    {"234", "Infestation 2", "Pojawia pająki gdy obrywasz"},
    {"235", "", "<item does not exist>"},
    {"236", "E. Coli", "Dotykiem zamieniasz przeciwników w gówno"},
    {"237", "Death's Touch", "Kosy zamiast łez!#↑ +1.5 Obrażeń#↓ -0.3 Szybkostrzelność"},
    {"238", "Key Piece 1", "!!! Kawałek klucza do drzwi Mega Satan!#Wiêcej Angel Room'ów"},
    {"239", "Key Piece 2", "!!! Kawałek klucza do drzwi Mega Satan!#Wiêcej Angel Room'ów"},
    {"240", "Experimental Treatment", "Przelosowuje Twoje statystyki"},
    {"241", "Contract from Below", "Podwaja wszystkie Pick-up'y"},
    {"242", "Infamy", "Szansa na zablokowanie łez"},
    {"243", "Trinity Shield", "Tarcza blokująca łzy"},
    {"244", "Tech.5", "Strzelasz losowo laserowym typem łez"},
    {"245", "20/20", "Podwaja twoje strzały"},
    {"246", "Blue Map", "Odkrywa Secret Room'y"},
    {"247", "BFFS!", "Twoje Familiary zadają wiêksze obrażenia"},
    {"248", "Hive Mind", "Niebieskie pająki/muchy zadają podwójnie wiêcej obrażeń"},
    {"249", "There's Options", "2 Przedmioty za pokonanie Bossa zamiast 1#!!! Tylko jeden może być wziêty"},
    {"250", "BOGO Bombs", "Podwaja wszystkie pojawienia siê bomb"},
    {"251", "Starter Deck", "Możesz trzymać 2 karty#Zamienia wszystkie tabletki w karty"},
    {"252", "Little Baggy", "Możesz trzymać 2 tabletki#Zamienia wszystkie karty w tabletki"},
    {"253", "Magic Scab", "↑ +1 Szczêście#↑ +1 Serce"},
    {"254", "Blood Clot", "↑ +1 Obrażeń#↑ +5 Zasiêg#!!! Tylko w jednym oku"},
    {"255", "Screw", "↑ +0.5 Szybkostrzelność#↑ +0.2 Prêdkość łez"},
    {"256", "Hot Bombs", "Płonące bomby#+5 Bomb"},
    {"257", "Fire Mind", "Ponące łzy#Szansa że eksplodują"},
    {"258", "Missing No.", "Przelosowuje Twoje przedmioty z każdym przejściem na nowe piêtro"},
    {"259", "Dark Matter", "↑ +1 Obrażeń#Przerażające pociski"},
    {"260", "Black Candle", "Odporność na klątwy#+1 Czarne Serce"},
    {"261", "Proptosis", "↑ +100% Obrażeń#↓ Obrażenia spadają wraz z przebytym dystansem łez"},
    {"262", "Missing Page 2", "+1 Czarne Serce#Kiedy twoje zdrowie spadnie do 1.5 Serca, zadajesz obrażenia wszystkim w pokoju"},
    {"263", "Smart Fly", "<item does not exist>"},
    {"264", "Dry Baby", "Orbitujący który szarżuje na przeciwników"},
    {"265", "Juicy Sack", "Kiedy oberwiesz łzą przeciwnika jest szansa że zadasz obrażenia wszystkim w pokoju"},
    {"266", "Robo-Baby 2.0", "Zostawiasz spowalniającą kałużê#Szansa na pojawienie siê niebieskich pająków gdy zabijesz wszystkich w pokoju"},
    {"267", "Rotten Baby", "Familiar który strzela laserem"},
    {"268", "Headless Baby", "Pojawia niebieskie muchy"},
    {"269", "Leech", "Zostawia kałużê"},
    {"270", "Mystery Sack", "Familiar który leczy pół serca gdy zabije przeciwnika"},
    {"271", "BBF", "Upuszcza losowe Pick-up'y"},
    {"272", "Bob's Brain", "Przyjazna wybuchowa mucha która odbija siê po pokoju"},
    {"273", "Best Bud", "Familiar który wystrzeliwuje siê wraz z twoimi łzami i wybucha"},
    {"274", "Lil Brimstone", "Kiedy otrzymujesz cios, dostajesz orbitującego Familiara"},
    {"275", "Isaac's Heart", "Familiar który strzela Brimstonowym laserem"},
    {"276", "Lil Haunt", "Familiar który bêdzie przyjmował obrażenia za Ciebie (Twoje ciało jest niewrażliwe)"},
    {"277", "Dark Bum", "Familiar który gania za przeciwnikami"},
    {"278", "Big Fan", "!!! Konwertuje:#1,5 Czerwonego serca na 1 Serce Duszy"},
    {"279", "Sissy Longlegs", "Duży gruby orbitujący Familiar"},
    {"280", "Punching Bag", "Pojawia niebieskie pająki"},
    {"281", "How to Jump", "Familiar którego przeciwnicy bêdą obierali za cel"},
    {"282", "D100", "Pozwala ci skakać"},
    {"283", "D4", "Przelosowuje wszystkie Pick-up'y, piedestały i twoje trzymane przedmioty"},
    {"284", "D10", "Przelosowuje twoje trzymane przedmioty"},
    {"285", "Blank Card", "Przelosowuje przeciwników w pokoju"},
    {"286", "Book of Secrets", "Odtwarza efekt twojej trzymanej karty, nie zużywając jej"},
    {"287", "Box of Spiders", "Ujawnia czêści mapy"},
    {"288", "Red Candle", "Pojawia 2-4 niebieskie pająki"},
    {"289", "The Jar", "Rzuca czerwony płomień"},
    {"290", "Flush!", "Może przechować do 4 czerwonych serc"},
    {"291", "Satanic Bible", "!!! Zabija przeciwników-kupy!#Zamienia normalnych przeciwników w kupy"},
    {"292", "Head of Krampus", "+1 Czarne serce"},
    {"293", "Butter Bean", "Strzela Brimstonowym laserem w 4 kierunkach"},
    {"294", "Magic Fingers", "Odrzuca pobliskich przeciwników"},
    {"295", "Converter", "Zadaje obrażenia na cały pokój#Koszt: 1 moneta"},
    {"296", "Pandora's Box", "!!! Konwertuje:#2 Serce Duszy/Czarne w 1 Czerwone Serce"},
    {"297", "Unicorn Stump", "!!! JEDNORAZOWY !!!#!!! Upuszcza przedmioty związane z piêtrem na którym jest użyty:#B1: 2 Serca Duszy#B2: 2 Klucze i bomby#C1: 1 Przedmiot z bossa#C2: 2 Serca Duszy + 1 Przedmiot z bossa#D1: 4 Serca Duszy#D2: 30 Monet#W1: 2 Przedmioty z bossów#W2: Biblia#Sheol: 1 Przedmiot z Devil Room + Czarne Serce#Cat: 1 Przedmiot z Angel Room + Serce Duszy#Chest: 1 Moneta"},
    {"298", "Taurus", "Nieśmiertelność i wiêksza szybkość na 5 sekund #Nie możesz strzelać podczas trwania"},
    {"299", "Aries", "Jesteś szybszy w pokoju z przeciwnikami!#Daje nietykalność gdy jesteś wystarczająco szybki"},
    {"300", "Cancer", "↑ +0.25 Szybkość#Dotykanie przeciwników ich rani"},
    {"301", "Leo", "+3 Serca Dusz#Po otrzymaniu obrażeń, każde nastêpne w tym samym pokoju zabiorą tylko pół serca"},
    {"302", "Virgo", "Niszcz skały!"},
    {"303", "Libra", "Szansa na bycie nieśmiertelnym gdy otrzymasz obrażenia"},
    {"304", "Scorpio", "+6 Monet / Kluczy / Bomb#Balansuje twoje statystyki!#!!! Każde nastêpne podniesienie statystyk wpłynie również na inne"},
    {"305", "Sagittarius", "Trujące łzy"},
    {"306", "Capricorn", "↑ +0.2 Szybkość#Penetrujące łzy"},
    {"307", "Aquarius", "↑ +1 Serce / Klucz / Bomba / Moneta#↑ +0.5 Obrażeń#↑ +0.1 Szybkość#↑ +1.5 Zasiêg"},
    {"308", "Pisces", "Zostawiasz za sobą kałużê zadającą obrażenia"},
    {"309", "Eve's Mascara", "↑ Szybkostrzelność#Odrzucające łzy"},
    {"310", "Judas' Shadow", "↑ Obrażenia X 2#↓ Szybkostrzelność spada#↓ Prêdkość łez spada"},
    {"311", "Maggy's Bow", "Po śmierci odradzasz siê jako Black Judas#↓ (Obrażenia X 2)"},
    {"312", "Holy Mantle", "↑ +1 Serce#Wszystkie czerwone serca leczą teraz dwa kontenery"},
    {"313", "Thunder Thighs", "Ignoruje pierwsze otrzymane obrażenia w każdym pokoju"},
    {"314", "Strange Attractor", "↑ +1 Serce#-0.4 Szybkość#Możesz niszczyć skały!"},
    {"315", "Cursed Eye", "Magnetyczne łzy"},
    {"316", "Mysterious Liquid", "Ładowalna fala łez#Kiedy ładujesz i otrzymasz obrażenia, teleportuje cie do innego pokoju"},
    {"317", "Gemini", "Łzy zostawiają kałużê zadającą obrażenia"},
    {"318", "Cain's Other Eye", "Bliski, walczący familiar"},
    {"319", "???'s Only Friend", "Odbija siê po pokoju#Strzela w twoją stronê#Zadaje obrażenia takie same jak ty"},
    {"320", "Samson's Chains", "Kontrolowana mucha"},
    {"321", "Mongo Baby", "Kula na łańcuchu#Może niszczyć skały i ranić przeciwników"},
    {"322", "Isaac's Tears", "Kopiuje efekt jednego z twoich familiarów"},
    {"323", "Undefined", "Wystrzeliwujesz falê łez#Ładuje siê podczas strzelania"},
    {"324", "Scissors", "Teleportuje cie do:#Secret room / Error room / Item room"},
    {"325", "Breath of Life", "Odcina ci głowê#Twoja głowa stacjonuje#Kontrolujesz swoje ciało oddzielnie"},
    {"326", "The Polaroid", "Trzymanie spacji sprawia że jesteś nieśmiertelny#!!! Nie trzymaj za długo!"},
    {"327", "The Negative", "Nieśmiertelność gdy obrywasz lub gdy twoje zdrowie spada do pół serca"},
    {"328", "The Ludovico Technique", "Efekt Necronomiconu gdy otrzymasz cios lub gdy twoje zdrowie spada do pół serca"},
    {"329", "Soy Milk", "Duża kontrolowana łza"},
    {"330", "Godhead", "↑ Bardzo zwiêksza szybkostrzelność#↓ -80% Obrażeń"},
    {"331", "Lazarus' Rags", "Samonaprowadzające łzy#↑ +0.5 Obrażeń#↑ +1.2 Zasiêg#↓ -0.3 Szybkostrzelność#↓ -0.3 Prêdkość łez#↑ +0.8 Wysokość lotu łez"},
    {"332", "The Mind", "Po śmierci odradzasz siê jako Lazarus"},
    {"333", "The Body", "Odkrywa całą mapê"},
    {"334", "The Soul", "↑ +3 Serca"},
    {"335", "Dead Onion", "+2 Serca Dusz#Odpycha od ciebie pociski"},
    {"336", "Broken Watch", "Penetrujące + Widmowe łzy#↓ -0.25 Zasiêg#↓ -0.4 Prêdkość łez"},
    {"337", "The Boomerang", "Spowalnia lub przyśpiesza pokoje"},
    {"338", "Safety Pin", "Rzut bumerangiem który unieruchamia przeciwników#Może zabierać przedmioty"},
    {"339", "Caffeine Pill", "↑ +5.25 Zasiêg#↑ +0.16 Prêdkość łez#+1 Czarne Serce#↑ +0.5 Wysokość lotu łez"},
    {"340", "Torn Photo", "↑ +0.3 Szybkość#↑ Zmniejsza Isaaca#Upuszcza losową pigułkê"},
    {"341", "Blue Cap", "↑ +0.7 Szybkostrzelność#↑ +0.16 Prêdkość łez"},
    {"342", "Latch Key", "↑ +1 Serce#↑ +0.7 Szybkostrzelność#↓ -0.16 Prêdkość łez"},
    {"343", "Match Book", "↑ +1 Szczêście#+1 Serce Duszy#Pojawia 2 klucze"},
    {"344", "Synthoil", "+1 Czarne Serce#+3 Bomby"},
    {"345", "A Snack", "↑ +1.0 Obrażeń#↑ +5.25 Zasiêg#↑ +0.5 Wysokość lotu łez"},
    {"346", "Diplopia", "↑ +1 Serce"},
    {"347", "Placebo", "!!! JEDNORAZOWY !!!#Duplikuje piedestały / pick-up'y w pokoju"},
    {"348", "Wooden Nickel", "Kopiuje efekt trzymanej tabletki"},
    {"349", "Toxic Shock", "50% szansy na upuszczenie losowej monety"},
    {"350", "Mega Bean", "Przy wejściu do pokoju zatruwa wszystkich obecnych przeciwników"},
    {"351", "Glass Cannon", "Zamraża wrogów w pokoju#Zadaje obrażenia i truje przeciwników w pobliżu#Wysyła falê kolców#!!! Może być użyte do otwarcia Secret Room'u"},
    {"352", "Bomber Boy", "↓ Redukuje twoje zdrowie do pół serca#Wypuszcza jedną wielką penetrującą widmową łzê zadającą ogromne obrażenia ((Obrażenia+1) X 10)"},
    {"353", "Crack Jacks", "+5 Bomb#Bomby bêdą wybuchać w kształcie krzyżyka"},
    {"354", "Mom's Pearls", "↑ +1 Serce#Pojawia losowy trinket"},
    {"355", "Car Battery", "↑ +1.25 Zasiêg#↑ +1 Szczêście#↑ +0.5 Wysokość lotu łez"},
    {"356", "Box of Friends", "Sprawia że twój przedmiot pod spacjê uruchamia siê podwójnie"},
    {"357", "The Wiz", "Duplikuje twoich familiar'ów na jeden pokój"},
    {"358", "8 Inch Nails", "Strzelasz dwoma łzami rozbierznie#Widmowe łzy"},
    {"359", "Incubus", "↑ +1.5 Obrażeń#Zwiêksza odrzut"},
    {"360", "Fate's Reward", "Familiar który strzela takimi samymi łzami jak Isaac z taką samą siłą, szybkością itd."},
    {"361", "Lil Chest", "Strzela łzami z taką samą siłą jak ty"},
    {"362", "Sworn Protector", "Upuszcza Pick-up co kilka pokoi"},
    --[[ End Of translations
    {"363", "Sworn Protector", "Orbital familiar#Deals 105 contact damage per second#Blocks and attracts bullets#Blocking 10 tear in one room drops an eternal heart"},
    {"364", "Friend Zone", "Orbital familiar#Deals 45 contact damage per second"},
    {"365", "Lost Fly", "Moves along walls/obstacles in the room#Deals 105 contact damage per second"},
    {"366", "Scatter Bombs", "+5 bombs#Causes your bombs to explode into 2-4 tiny bombs"},
    {"367", "Sticky Bombs", "+5 bombs#When a bomb kills an enemy, it spawns blue spiders#Causes your bombs to stick to enemies"},
    {"368", "Epiphora", "Shooting in one direction increases your fire rate by up to 200%"},
    {"369", "Continuum", "↑ +2.25 Range up#↑ +1.5 Tear Height#Tears travel through walls and appear out of the opposite wall"},
    {"370", "Mr. Dolly", "↑ +0.7 Tears up#↑ +5.25 Range up#↑ +0.5 Tear Height#Spawns 3 random hearts when picked up"},
    {"371", "Curse of the Tower", "Spawn 6 troll bombs every time you get hit#These are affected by bomb items"},
    {"372", "Charged Baby", "Random chance to drop a battery or freeze all enemies in the room#Chance to add one charge to your spacebar item"},
    {"373", "Dead Eye", "↑ +12.5% damage up for every tear that successfully hits an enemy(max. +100%)"},
    {"374", "Holy Light", "Random chance to fire a Holy tear, which will spawn a beam of light on hit#The beam deals 4x your damage"},
    {"375", "Host Hat", "20% chance to block tears#Get immune to explosions/Stomps from Mom's and Satan's foot"},
    {"376", "Restock", "Spawns 3 random Pickups#Shops instantly restock their items when you buy them"},
    {"377", "Bursting Sack", "Spider enemies no longer target or deal contact damage to Isaac"},
    {"378", "No. 2", "Firing tears for 3 seconds drops a Butt Bomb"},
    {"379", "Pupula Duplex", "Tears get a much larger hitbox#Spectral tears"},
    {"380", "Pay To Play", "+5 coins#You can open doors with coins instead of keys"},
    {"381", "Eden's Blessing", "↑ +0.7 Tears up#Gives you a random item at the start of your next run"},
    {"382", "Friendly Ball", "Can be thrown at enemies to capture them#Next usage will re-spawn the same enemy as a friendly companion"},
    {"383", "Tear Detonator", "Detonate any tears currently on the screen, causing each one to split into 6 more tears which will spread in a circle"},
    {"384", "Lil Gurdy", "Will launch and slide around the room#Deals 90 contact damage per second"},
    {"385", "Bumbo", "Picks up any near-by coins#Every 6 coins it levels up, except for level 4 which takes 12 coins#Level 2: can drop random pickups#Level 3: Fires tears in the same direction as Isaac#Level 4: Doesn't fire tears but will chase enemies. Will also randomly drop bombs#after Level 4: will continue collect coins and drop random pickups"},
    {"386", "D12", "Re-rolls any grid object into another random type of object (e.g. poop, pots, TNT, red poop, stone blocks etc.)"},
    {"387", "Censer", "Creates a huge aura of light that slows down enemies and projectiles inside of it"},
    {"388", "Key Bum", "Collects keys, giving random chests in return"},
    {"389", "Rune Bag", "Drops a random rune every 5-6 rooms"},
    {"390", "Seraphim", "Fires Sacred Heart tears#Deals 10 damage per shot"},
    {"391", "Betrayal", "Every time Isaac takes damage, every enemy in the room gets charmed"},
    {"392", "Zodiac", "Gives you a random zodiac item effect every floor"},
    {"393", "Serpent's Kiss", "Random chance to shoot poison tears#Poison enemies on contact#Enemies that were poisoned have a chance to drop a black heart on death"},
    {"394", "Marked", "Fire tears automatically directed at a red target on the ground which is controlled by the player#↑ +0.7 Tears up#↑ +3.15 Range up#↑ +0.3 Tear Height"},
    {"395", "Tech X", "Gain the ability to charge and fire a laser ring that travels across the room"},
    {"396", "Ventricle Razor", "Creates up to two portals to travel between them#Can be placed in different rooms"},
    {"397", "Tractor Beam", "Isaac's tears now travel directly forwards following a beam of light, but will also move sideways based on your player movement#↑ +0.5 Tears up#↑ +5.25 Range up#↑ +0.16 Shot Speed up#↑ +0.5 Tear Height"},
    {"398", "God's Flesh", "Tears can shrinking enemies#Shrunk enemies can be crushed and killed by walking over them"},
    {"399", "Maw Of The Void", "↑ +1.0 Damage up#After firing tears for 3 seconds, a red cross appears on Isaac's head. Upon releasing the fire button, creates a black brimstone ring#Enemies killed with the black ring have a chance to drop Black hearts"},
    {"400", "Spear Of Destiny", "Spawns a spear in front of you#Deals 2 times your damage#Chance to fear enemies on contact"},
    {"401", "Explosivo", "Chance to fire sticky bombtears"},
    {"402", "Chaos", "Pedestals will now be chosen from random itempools#Spawns 1-6 random pickups"},
    {"403", "Spider Mod", "Allows you to see your tear damage and the health bars of all enemies#Inflicts a random status effect on contact#Will randomly drop batteries"},
    {"404", "Farting Baby", "Blocks projectiles#If hit, it will fart, which will charms, poison or knockback enemies"},
    {"405", "GB Bug", "Bounces around the room#Deals120 damage per second and applies a random status effect"},
    {"406", "D8", "Reroll your stats#Will only affect damage, tears, range and speed"},
    {"407", "Purity", "↑ Boost one of your stats depending on the color of the aura around him#When you take damage, you will get a new aura#Red = +4.0 Damage#Blue = -4 Tear Delay#Yellow = +0.5 Speed up#Orange = +7.5 Range up, +1 Tear height"},
    {"408", "Athame", "When you take damage, a black brimstone ring will appear around Isaac#Enemies killed with it have a chance to drop a black heart"},
    {"409", "Empty Vessel", "+2 Black Hearts#When Isaac has no red hearts, gain flight and chance to trigger a shield"},
    {"410", "Evil Eye", "Chance to fire an eye across the screen which fires tears in the same direction as Isaac"},
    {"411", "Lusty Blood", "↑ +0.5 Damage up for each enemy killed in current room#Maximum of +5 Damage up after 10 kills"},
    {"412", "Cambion Conception", "After taking damage 15 times, Isaac gains a permanent demon familiar#Up to 4 familiars possible"},
    {"413", "Immaculate Conception", "After picking up 15 hearts, Isaac gains a permanent angelic familiar#Up to 5 familiars possible"},
    {"414", "More Options", "Two items now spawn in all treasure rooms#You can only choose one"},
    {"415", "Crown Of Light", "+2 Soul Hearts#↑ Damage X 2 if you don't have any damaged red heart containers"},
    {"416", "Deep Pockets", "Allows you to carry two cards/pills/runes"},
    {"417", "Succubus", "Bounces around the room with a damaging aura, dealing 129% of your damage every second#↑ +50% damage while standing in the aura,"},
    {"418", "Fruit Cake", "Gives you a different tear effect with every tear that you fire"},
    {"419", "Teleport 2.0", "Teleports you to another random room that has not been explored yet#Hierarchy: Normal Rooms, Boss, Super Secret Room, Shop, Item Room, Special rooms, Devil/Angel Room, I Am Error"},
    {"420", "Black Powder", "Walking in a circle will spawn a pentagram symbol on the floor, which deals 10 damage per tick"},
    {"421", "Kidney Bean", "Applies charm effect to any enemies in close range and deals 5 damage to them"},
    {"422", "Glowing Hour Glass", "Rewind time and put you back in the previous room, in the same state you were in at that moment"},
    {"423", "Circle of Protection", "Large halo around you, dealing your damage on contact every second#Chance to reflect enemy projectiles"},
    {"424", "Sack Head", "Pickups have a 33% chance to be replaced with a sack#Spawns a sack"},
    {"425", "Night Light", "Spawns a cone of light in front of you that slows enemies and projectiles inside of it"},
    {"426", "Obsessed Fan", "Follows your exact movement on a 3 second delay#Deals 30 contact damage per second"},
    {"427", "Mine Crafter", "Spawns a pushable TNT barrel#If used a second time in the same room while the last TNT barrel is still there, it will remotely explode"},
    {"428", "PJs", "+4 Soul Hearts#Fully restores your red health"},
    {"429", "Head of the Keeper", "Enemies have a 5% chance to drop a Penny when hit with your tears"},
    {"430", "Papa Fly", "Follows your movement pattern on a 3 second delay#Fires tears at nearby enemies that deal damage equal to your damage"},
    {"431", "Multidimensional Baby", "Follows your movement pattern on a 3 second delay#Tears that pass through it will split up and gain a speed boost"},
    {"432", "Glitter Bombs", "+5 bombs#Bombs have a chance to drop random pickups when they explode"},
    {"433", "My Shadow", "Each time you take damage, it will apply a fear effect to all enemies and spawn a friendly black charger#The charger deals 5 damage per second"},
    {"434", "Jar of Flies", "Every time you kill an enemy a blue fly will be added to the Jar#Up to 20 flies#Using the item will release all the flies"},
    {"435", "Lil Loki", "Shoots 4 tears in a cross pattern#Deals 3.5 damage per shot"},
    {"436", "Milk!", "After taking damage, you gain a Tears up for the rest of the room"},
    {"437", "D7", "Respawn all enemies of the room#Allows you to farm room clear rewards#!!! If used in a greed fight, it can reroll the room into a Shop"},
    {"438", "Binky", "+1 Soul heart#↑ +0.7 Tears up#↑ Makes Isaac very small, reducing his hitbox size"},
    {"439", "Mom's Box", "Spawns a random trinket#↑ +1 Luck while held#While held, doubles the effect of trinkets"},
    {"440", "Kidney Stone", "Randomly while firing you will stop firing and release a burst of tears and a kidney stone#↓ -0.2 Speed down#↓ -17 Range down#↑ +2.0 Tear height"},
    {"441", "Mega Blast", "Fires a huge Mega Satan laser for 15 seconds#The laser persists between rooms and floors"},
    {"442", "Dark Princes Crown", "!!! While at 1 full red heart:#↑ +1.5 Range up#↑ +0.7 Tears up#↑ +0.2 Shoot Speed up#(Doesnt work with the Lost)"},
    {"443", "Apple!", "Randomly fire razor blades which deal 400% damage#↑ +0.3 Tears up"},
    {"444", "Lead Pencil", "Every 15 tears fired, you fire a cluster of tears#Each tear in the cluster deals double damage"},
    {"445", "Dog Tooth", "↑ +0.3 Damage up#↑ +0.1 Speed up#A wolf howls, if you enter a room next to a secret room#A barking sound will play when entering a room with a crawl space in it"},
    {"446", "Dead Tooth", "While firing, you get a green aura that poisons any enemies in it#The poison deals your damage"},
    {"447", "Linger Bean", "While firing, randomly spawns a poop cloud#The cloud deals your damage 5 times a second"},
    {"448", "Shard of Glass", "When taking damage, chance to get ↑ +5 Range and leave a trail of blood creep, or spawn a red heart"},
    {"449", "Metal Plate", "+1 Soul Heart#Enemy bullets have a 25% chance to be reflected as homing tears"},
    {"450", "Eye of Greed", "Tears can turn enemies into gold"},
    {"451", "Tarot Cloth", "Drops a random card or rune on pickup#Doubles the effect of any card used"},
    {"452", "Varicose Veins", "When taking damage, fire 10 tears in a circle around you#The tears deal 125% your damage"},
    {"453", "Compound Fracture", "Bone tears#Tears shatter into 1-3 smaller bone shards upon hitting anything#↑ +1.5 Range up#↑ +1.0 Tear height"},
    {"454", "Polydactyly", "You can carry two cards, runes or pills#Spawns a random card, pill or rune on pickup"},
    {"455", "Dad's Lost Coin", "↑ +1.5 Range up#Spawns a lucky penny"},
    {"456", "Moldy Bread", "↑ +1 Health up"},
    {"457", "Cone Head", "+1 Soul Heart#20% Chance to ignore damage"},
    {"458", "Belly Button", "Spawns a random trinket on pickup#Grants 1 extra trinket slot"},
    {"459", "Sinus Infection", "Sticky poison Tears#Deals your damage each tick#Sticks till the enemy dies"},
    {"460", "Glaucoma", "Chance to fire concussive tears"},
    {"461", "Parasitoid", "Chance to fire egg sacks#Spawns slowing creep on hit#Spawns a blue spider or fly on hit"},
    {"462", "Eye of Belial", "↑ +1.5 Range up#↑ +1.0 Tear height#Grants piercing tears#After hitting the first enemy, the tear deals double damage and gains a homing effect"},
    {"463", "Sulfuric Acid", "↑ +0.3 Damage up#Chance to destroy rocks and open doors with your tears"},
    {"464", "Glyph of Balance", "+2 Soul Hearts#Champion enemies drop pickups more frequently"},
    {"465", "Analog Stick", "↑ +0.3 Tears up#Allows you to fire tears diagonally by firing in two directions"},
    {"466", "Contagion", "First killed enemy in the room will explode and poison all nearby enemies"},
    {"467", "Finger!", "Deals constant 10% of your damage to enemies in the direction the finger points at"},
    {"468", "Shade", "Follows your movement delayed by 1 seconds#Deals 30 contact damage per second"},
    {"469", "Depression", "Leaves trail of creep#Creep deals 6 damage per second#Enemies touching the cloud can spawn a holy light beam"},
    {"470", "Hushy", "Bounces around the room#Deals contact damage#Will stop moving when you are shooting#When stopped, it can block projectiles"},
    {"471", "Lil Monstro", "Chargable Shotgun attack#(Similar to monstros lung)#Each tear deals 3.5 damage"},
    {"472", "King Baby", "Other familiars follow it#Stops moving when you are shooting#Will teleport back to you when you stop shooting"},
    {"473", "Big Chubby", "Charges forwards very slow#Deals 40.5 contact damage per second"},
    {"474", "Tonsil", "Blocks enemy projectiles"},
    {"475", "Plan C", "!!! SINGLE USE ! #Deals 9,999,999 damage to all enemies and kills you 3 seconds later"},
    {"476", "D1", "Duplicates 1 random Pick-Up in the current room"},
    {"477", "Void", "!!! When used, consume any pedestal items in the room#Active item: Its effect will be added to Void's effect (Stacking the effects)#↑ Passive item: Small stat upgrade to a random stat"},
    {"478", "Pause", "Freezes all enemies in the room until you start shooting again#Touching a frozen enemy will hurt you"},
    {"479", "Smelter", "Consumes your trinket and gives you the effect permanently#More trinkets appear"},
    {"480", "Compost", "Converts pickups into blue flies or spiders"},
    {"481", "Dataminer", "When used, ↑/↓ small amount on random stat#Random tear effect for current room#Fucks up all sprites"},
    {"482", "Clicker", "Transforms you into a different character#Removes the last item you collected"},
    {"483", "Mama Mega!", "!!! SINGLE USE ! #Affects whole floor#Explodes all objects#Deals 200 damage to all enemies#Opens boss rush / hush door / secret rooms"},
    {"484", "Wait What?", "Upon use, pushes enemies away and spawn a wave of rocks#Can open rooms and break rocks"},
    {"485", "Crooked Penny", "50% chance to double all items, consumables and chests in room#50% chance to remove items / pickups in room and spawn 1 coin"},
    {"486", "Dull Razor", "Hurts you without damaging you#Can trigger item effects"},
    {"487", "Potato Peeler", "Removes one red heart container and gives you ↑ +0.2 Damage up and a \"Cube of Meat\""},
    {"488", "Metronome", "Gives you a random item effect each room"},
    {"489", "D infinity", "Random Dice-effect each usage"},
    {"490", "Eden's Soul", "!!! SINGLE USE !#Spawns 2 random items depending on the current rooms item pool"},
    {"491", "Acid Baby", "Drops a random pill every 3 rooms#Using a pill poisons all enemies in the room"},
    {"492", "YO LISTEN!", "↑ +1 Luck up#Highlights the location of secret rooms, tinted rocks and trapdoors"},
    {"493", "Adrenaline", "For every empty heart container:#↑ +0.2 Damage up"},
    {"494", "Jacob's Ladder", "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half your damage"},
    {"495", "Ghost Pepper", "Chance to shoot Fire instead of tears#The fire stays till it has dealt damage 5 times"},
    {"496", "Euthanasia", "Chance to fire needles#Needles kill normal enemies instantly#Otherwise they deal 3 times your damage"},
    {"497", "Camo Undies", "Confuse all enemies and camouflage yourself when entering a room until you start shooting"},
    {"498", "Duality", "Spawns Devil AND Angelroom doors#When entering one, the other disappears"},
    {"499", "Eucharist", "100% chance to find an Angel Room"},
    {"500", "Sack of Sacks", "Spawns a sack every 5-6 rooms"},
    {"501", "Greed's Gullet", "Gives you 1 heart container for every 25 coins#The Keeper will gain additional Coin-Hearts"},
    {"502", "Large Zit", "Chance to fire a Creep leaving tear that deals double damage"},
    {"503", "Little Horn", "Chance to fire tears that instantly kill enemies#Running into enemies will deal 3.5 damage to them"},
    {"504", "Brown Nugget", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
    {"505", "Poke Go", "Chance to spawn a charmed enemy when entering a hostile room"},
    {"506", "BackStabber", "Tears can cause bleeding, which deals 10% damage of the enemies total health every 5 seconds"},
    {"507", "Sharp Straw", "Deals your damage + 10% damage equal to the maximum health of the enemy#Affects all enemies in the room#Chance to drop half hearts when it deals damage"},
    {"508", "Mom's Razor", "Orbital that causes bleeding, which deals 10% damage of the enemies total health every 5 seconds.#Deals 300% your damage on contact per second"},
    {"509", "Bloodshot Eye", "Orbital that shoots a tear every 2 seconds in a random direction#Deals 3.5 damage per tear#Deals 30 contact damage per second"},
    {"510", "Delirious", "Spawns a friendly white delirium version of a boss for the current room"},
    {"511", "Angry Fly", "Orbits around a random enemy until that enemy dies#Deals 30 contact damage per second to other enemies"},
    {"512", "Black Hole", "Throwable black hole, which sucks in everything#Deals 0.4 damage every tick#Destroys nearby rocks#Lasts 6 seconds"},
    {"513", "Bozo", "↑ +0.1 Damage up#+1 Soul Heart#Random chance to charm/fear an enemy#Random chance to spawn a rainbow poop upon taking damage"},
    {"514", "Broken Modem", "Causes random enemies to 'lag' at random intervals, causing them to shortly freeze#25% chance to double room clear drops"},
    {"515", "Mystery Gift", "!!! SINGLE USE !#Spawns a random item from the current room's item pool#Chance to spawn Lump of Coal or The Poop instead"},
    {"516", "Sprinkler", "Spawns a Sprinkler that rotates in a circle, spraying your tears in all directions"},
    {"517", "Fast Bombs", "+7 Bombs#Allows you to rapidly place bombs on the ground"},
    {"518", "Buddy in a Box", "Familiar which looks like a random coop Baby#Has a random Teareffect#Will be randomized every floor"},
    {"519", "Lil Delirium", "A familiar that transforms into other random familiars every 10 seconds"},
    {"520", "Jumper Cables", "+1 charge for your active item for every 15 enemies killed"},
    {"521", "Coupon", "When used, causes one random item in the shop or devil room to become free"},
    {"522", "Telekinesis", "Enemy projectiles close to you are held in place for 3 seconds#They get thrown away from you afterwards#Recharges after 3 seconds"},
    {"523", "Moving Box", "When used, stores all Pick-Ups from the current room#Using it again will put them back on the floor again#This allows you to move things between rooms"},
    {"524", "Technology Zero", "Tears will be connected with beams of electricity#Electricity damage equals your damage"},
    {"525", "Leprosy", "Taking damage will spawn a projectile blocking orbital#Max. 3 Orbitals at the same time#Orbitals are destroyed, if they take too much damage"},
    {"526", "7 Seals", "Spawns small horsemen familiars that spawn their respective locusts#Horsemen changes every 10 seconds"},
    {"527", "Mr. ME!", "!!! Familiar that can do tasks for you:#Opening doors & chests, Bring items, Steal from the shop / devil, fight enemies, explode, and activate pressure plates"},
    {"528", "Angelic Prism", "Orbital prism#Tears hitting it will split into 4"},
    {"529", "Pop!", "Tears will behave like billiard balls"},
    {"530", "Death's List", "Grants a reward if you kill enemies in the order they are marked in"},
    {"531", "Haemolacria", "Tears fly in an arc#Tears burst into smaller tears on impact#↓ Tears down#↑ 31% Damage up"},
    {"532", "Lachryphagy", "Tears slow down while traveling#Upon stopping, they explode in 8 smaller tears#Tears can be fired in other tears, making them bigger"},
    {"533", "Trisagion", "Fire white blasts of light#(Holy Brimstone)"},
    {"534", "Schoolbag", "Allows to hold 2 active items#Switch between them by pressing CTRL (hold CTRL as \"The Forgotton\")"},
    {"535", "Blanket", "+1 Soul Heart#Heals 1 Red Heart#Grants a shield when entering a boss room"},
    {"536", "Sacrificial Altar", "!!! ONE TIME USAGE !#Sacrifice 1-2 familiars to spawn an item from the Devil room itempool#Turns your blue spiders/flies into coins"},
    {"537", "Lil Spewer", "Spawns a random pill#Familiar that fires a line of creep#Creeptype changes everytime the player uses a pill"},
    {"538", "Marbles", "Spawns 3 random trinkets#Taking damage can add the effect of your trinket permanently"},
    {"539", "Mystery Egg", "Spawn a charmed enemy when you get hit#Spawns stronger friends the more rooms are cleared without taking damage"},
    {"540", "Flat Stone", "Tears bounce of the floor#Tears cause splash damage on every bounce"},
    {"541", "Marrow", "+1 Bone Heart#Spawns 3 Red Hearts"},
    {"542", "Slipped Rib", "Orbital#Reflects projectiles"},
    {"543", "Hallowed Ground", "Spawn white poop when you get hit#(White poop has a ↑ Tears up aura and can block damage)"},
    {"544", "Pointy Rib", "Nail that levitates in front of isaac#Deals 6 times your damage"},
    {"545", "Book of the Dead", "Spawns a bone orbital or charmed bony per enemy killed in the current room"},
    {"546", "Dad's Ring", "Grants an aura that freezes enemies in place"},
    {"547", "Divorce Papers", "+1 Bone Heart#↑ +0.7 Tears up#Spawns a Mysterious Paper trinket"},
    {"548", "Jaw Bone", "Boomerang-like Familiar#Deals 7 contact damage#Can retrieve pickups"},
    {"549", "Brittle Bones", "Replaces all your red heart containers with 6 bone Hearts#Losing a bone heart fires Bonetears in all directions and adds ↑ +0.5 tears up permanently"},
    {"550", "Broken Shovel", "Moms foot will constantly attack you#Using it stops moms foot for current room#!!! (Try to beat Bossrush with it!)"},
    {"551", "Broken Shovel", "Second part of a broken shovel#!!! Use the shovel on the hill of dirt in the \"Dark Room\""},
    {"552", "Mom's Shovel", "Spawns trapdoor to next floor#!!! Use the shovel on the hill of dirt in the \"Dark Room\"#!!! Unlocks something cool"}]]--
}

---------- Trinkets ----------
EID.descriptions["pl"].trinkets={
--[[    {"1", "Swallowed Penny", "Drop 1 coin when you get hit"},
    {"2", "Petrified Poop", "50% more drops from poop"},
    {"3", "AAA Battery", "-1 charge needed for spacebar items"},
    {"4", "Broken Remote", "Randomly teleports you, when using an item"},
    {"5", "Purple Heart", "More champion enemies#Higher chance for boss challenge rooms"},
    {"6", "Broken Magnet", "Coin magnet"},
    {"7", "Rosary Bead", "Higher angel room chances"},
    {"8", "Cartridge", "Chance for Gamekid effect on hit"},
    {"9", "Pulse Worm", "Pulsating tears#Affects tear hitbox"},
    {"10", "Wiggle Worm", "Tears move in waves#↑ +0.3 Tears up"},
    {"11", "Ring Worm", "Tears move in spirals with high speed"},
    {"12", "Flat Worm", "50% wider tears"},
    {"13", "Store Credit", "One shop item for free"},
    {"14", "Callus", "Prevents damage from creep and spikes"},
    {"15", "Lucky Rock", "Destroying rocks spawns coins"},
    {"16", "Mom's Toenail", "Mom's foot stomps enemies every 60 seconds"},
    {"17", "Black Lipstick", "More black hearts appear"},
    {"18", "Bible Tract", "More eternal hearts appear"},
    {"19", "Paper Clip", "Unlock chests without using keys"},
    {"20", "Monkey Paw", "When on half a heart, spawns a black heart#! 3 time usage"},
    {"21", "Mysterious Paper", "Imitates \"Polaroid\", \"The Negative\", \"Missing Page\" and \"Missing Poster\""},
    {"22", "Daemon's Tail", "!!! Convert drops:#Hearts to pickups#Decreases spawnrate of hearts"},
    {"23", "Missing Poster", "Respawn as \"The Lost\" when dying in a sacrifice room.#If he is unlocked, you revive as him even outside sacrifice rooms"},
    {"24", "Butt Penny", "Fart when picking up coins#Farts knockback enemies"},
    {"25", "Mysterious Candy", "Fart or spawn poop every 30 seconds"},
    {"26", "Hook Worm", "Tears move in angular patterns#↑ +10 Range"},
    {"27", "Whip Worm", "↑ +0.5 Shot Speed up"},
    {"28", "Broken Ankh", "22% chance to respawn as \"Blue Baby\""},
    {"29", "Fish Head", "Spawn a blue fly when getting hit"},
    {"30", "Pinky Eye", "Randomly shoot poison tears"},
    {"31", "Push Pin", "Randomly shoot piercing tears"},
    {"32", "Liberty Cap", "Random mushroom effect per room#Can reveal special rooms on the minimap"},
    {"33", "Umbilical Cord", "When down to half a heart, you get little Steven"},
    {"34", "Child's Heart", "More red hearts drop"},
    {"35", "Curved Horn", "↑ +2 Damage up"},
    {"36", "Rusted Key", "More keys appear"},
    {"37", "Goat Hoof", "↑ +0.15 Speed up"},
    {"38", "Mom's Pearl", "More Soul Hearts drop"},
    {"39", "Cancer", "↑ Tears up"},
    {"40", "Red Patch", "↑ Chance to get +1.8 Damage up when getting hit"},
    {"41", "Match Stick", "More Bombs appear#! Removes \"The Tick\""},
    {"42", "Lucky Toe", "↑ +1 Luck up#Chance to get more drops"},
    {"43", "Cursed Skull", "When damaged down to half a heart, teleport to a random room"},
    {"44", "Safety Cap", "More pills appear"},
    {"45", "Ace of Spades", "More cards appear"},
    {"46", "Isaac's Fork", "Chance for healing half a heart after clearing a room"},
    {"47", "", "<Item does not exist>"},
    {"48", "A Missing Page", "When getting hit, chance to damage all enemies in the room"},
    {"49", "Bloody Penny", "50% chance to drop half a heart when picking up coins"},
    {"50", "Burnt Penny", "50% chance to drop a bomb when picking up coins"},
    {"51", "Flat Penny", "50% chance to drop a key when picking up coins"},
    {"52", "Counterfeit Penny", "50% chance to get +1 coin when picking up coins"},
    {"53", "Tick", "-15% boss-health#Heals 1 red heart when entering a boss room"},
    {"54", "Isaac's Head", "Familiar with piercing tears#Deals 3.5 damage per tear"},
    {"55", "Maggy's Faith", "Get one eternal heart at the start of every floor"},
    {"56", "Judas' Tongue", "Reduces devil deal prices"},
    {"57", "???'s Soul", "Familiar that bounces around the room#Shoots in the same direction as the player#Deals 3.5 damage per tear"},
    {"58", "Samson's Lock", "↑ 1/15 Chance for +0.5 Damage up when killing an enemy#Effect lasts for current room"},
    {"59", "Cain's Eye", "Chance to reveal map icons at start of new floor"},
    {"60", "Eve's Bird Foot", "Chance to spawn a dead bird when killing an enemy"},
    {"61", "The Left Hand", "Turns all chests into red chests"},
    {"62", "Shiny Rock", "Crawlspace rocks and tinted rocks blink every 10 seconds"},
    {"63", "Safety Scissors", "Turns troll bombs into bomb pickups"},
    {"64", "Rainbow Worm", "Random worm effect every 3 seconds"},
    {"65", "Tape Worm", "↑ Doubles your Range"},
    {"66", "Lazy Worm", "↓ -0.4 Shoot Speed down#↑ +4 Range up"},
    {"67", "Cracked Dice", "Chance to trigger a random dice effect when getting hit"},
    {"68", "Super Magnet", "Magnet for pickups and enemies"},
    {"69", "Faded Polaroid", "Camouflages the player randomly#Confuses enemies"},
    {"70", "Louse", "Chance to spawn a spider while in a hostile room"},
    {"71", "Bob's Bladder", "Bombs leave creep"},
    {"72", "Watch Battery", "More batteries appear"},
    {"73", "Blasting Cap", "Exploding bombs can drop bomb-pickups"},
    {"74", "Stud Finder", "More Crawlspaces appear"},
    {"75", "Error", "Random trinket effect every room"},
    {"76", "Poker Chip", "Chests have a 50/50 chance to spawn extra pickups OR nothing/enemy"},
    {"77", "Blister", "Increases knockback"},
    {"78", "Second Hand", "Longer status effects on enemies"},
    {"79", "Endless Nameless", "Chance when using pills/cards to drop a copy of the pill/card"},
    {"80", "Black Feather", "↑ +0.2 Damage up for each evil item held"},
    {"81", "Blind Rage", "Invincibility lasts longer after getting hit"},
    {"82", "Golden Horse Shoe", "+15% to get double item room on next floor"},
    {"83", "Store Key", "Open shops for free"},
    {"84", "Rib of Greed", "Greed/Super Greed no longer appear in shops#More coins appear"},
    {"85", "Karma", "Using a Donation machine can heal you or spawn a beggar"},
    {"86", "Lil Larva", "Destroying poop spawns a blue fly"},
    {"87", "Mom's Locket", "Heal half a heart when using keys#Turns half hearts into full hearts"},
    {"88", "NO!", "Very low chance for spacebar items in item rooms"},
    {"89", "Child Leash", "Familiars stay closer to you"},
    {"90", "Brown Cap", "Poop explodes when destroyed"},
    {"91", "Meconium", "Increases chance for Black Poops to spawn#Chance to spawn a black heart when black poop is destroyed"},
    {"92", "Cracked Crown", "↑ Stat increases of your items are 33% more effective#↑ +0.2 Tears up#↑ -1 Tear Delay"},
    {"93", "Used Diaper", "Fly enemies are friendly"},
    {"94", "Fish Tail", "Doubles all blue Fly / Spider spawns"},
    {"95", "Black Tooth", "Randomly shoot poison Tooth tears"},
    {"96", "Ouroboros Worm", "Tears move quickly in a spiral pattern#Spectral tears#↑ +4 Range"},
    {"97", "Tonsil", "Chance to get a projectile blocking familiar after taking damage 12-20 times#Up to +2 Familiars possible"},
    {"98", "Nose Goblin", "Chance to shoot sticky poison tears"},
    {"99", "Super Ball", "Chance to shoot bouncy tears"},
    {"100", "Vibrant Bulb", "!!! While holding a fully charged active item:#↑ +0.5 Damage#↑ +0.25 Speed#↑ +0.75 Range#↑ +0.2 Tears#↑ +0.1 Shot speed#↑ +1 Luck"},
    {"101", "Dim Bulb", "!!! While holding an uncharged active item:#↑ +1.5 Damage#↑ +0.5 Speed#↑ +1.5 Range#↑ +0.4 Tears#↑ +0.3 Shot Speed#↑ +2 Luck"},
    {"102", "Fragmented Card", "+1 extra secret room per floor while held"},
    {"103", "Equality!", "!!! When coin, key and bomb-count are equal:#Turns half consumables into double consumables"},
    {"104", "Wish Bone", "Chance to spawn a pedestal item when getting hit#Gets destroyed afterwards"},
    {"105", "Bag Lunch", "Chance to spawn a health up item when getting hit#Gets destroyed afterwards"},
    {"106", "Lost Cork", "Increases the radius of any creep you produce"},
    {"107", "Crow Heart", "Damage taken will ignore spirit / black hearts, causing your red heart containers to be depleted first"},
    {"108", "Walnut", "Chance to drop random pickup / trinket when getting hit by an explosion#Gets destroyed afterwards"},
    {"109", "Duct Tape", "Causes any familiar you have to stop moving"},
    {"110", "Silver Dollar", "Shops will now appear in the womb"},
    {"111", "Bloody Crown", "Item rooms now appear in the womb"},
    {"112", "Pay To Win", "Restock boxes will always spawn in item rooms"},
    {"113", "Locust of War", "Spawn an exploding attack fly when entering a hostile room#The fly deals double your damage + explosion damage"},
    {"114", "Locust of Pestilence", "Spawn a poison attack fly when entering a hostile room#The fly deals double your damage"},
    {"115", "Locust of Famine", "Spawn a slowing attack fly when entering a hostile room#The fly deals double your damage"},
    {"116", "Locust of Death", "Spawn an attack fly when entering a hostile room#The fly deals 4 times your damage"},
    {"117", "Locust of Conquest", "Spawns 1-4 attack flies when entering a hostile room#Each fly deals double your damage"},
    {"118", "Bat Wing", "Chance to gain flight after killing an enemy#Persists for the current room"},
    {"119", "Stem Cell", "Heals half a heart upon traveling to the next floor"},
    {"120", "Hairpin", "Fully recharges your active item at the start of a boss fight"},
    {"121", "Wooden Cross", "Protects you from the first damage you take for every floor"},
    {"122", "Butter!", "Using your active item will drop it back on a pedestal on the ground"},
    {"123", "Filigree Feather", "Causes the Angel bosses to drop normal items instead of Key Pieces"},
    {"124", "Door Stop", "The last door you used stays open"},
    {"125", "Extension Cord", "Connects your familiars with beams of electricity#Deals 6 damage per beam"},
    {"126", "Rotten Penny", "Spawns a blue fly when picking up a coin"},
    {"127", "Baby-Bender", "Grants your familiars homing shots"},
    {"128", "Finger Bone", "Small chance to gain a Bone Heart when taking damage"},]]--
}

---------- Cards ----------
EID.descriptions["pl"].cards={
--[[    {"1", "0 - The Fool", "Teleports you back to the start"},
    {"2", "I - The Magician", "Homing tears for current room"},
    {"3", "II - The High Priestess", "Moms Foot stomps on an enemy!"},
    {"4", "III - The Empress", "↑ +2.35 Damage & +0.3 Speed for current room"},
    {"5", "IV - The Emperor", "Teleports you to the bossroom"},
    {"6", "V - The Hierophant", "Drops 2 Soul hearts"},
    {"7", "VI - The Lovers", "Drops 2 red hearts"},
    {"8", "VII - The Chariot", "Invincibility + contact damage for 6 seconds"},
    {"9", "VIII - Justice", "Spawns 1 bomb, 1 key, 1 coin, 1 heart"},
    {"10", "IX - The Hermit", "Teleports you to the shop"},
    {"11", "X - Wheel of Fortune", "Spawns a Slot- or Fortune Machine"},
    {"12", "XI - Strength", "↑ +1 Health up#↑ +0.3 Damage up#↑ +50% Damage#↑ +5.25 Range up#↑ +0.3 Speed up#for current room"},
    {"13", "XII - The Hanged Man", "Grants flight for current room"},
    {"14", "XIII - Death", "Deals 40 damage to all enemies in the room"},
    {"15", "XIV - Temperance", "Spawns a Blood Donation Machine"},
    {"16", "XV - The Devil", "↑ +2 Damage up for current room"},
    {"17", "XVI - The Tower", "Spawns 6 troll bombs"},
    {"18", "XVII - The Stars", "Teleports you to the item room"},
    {"19", "XVIII - The Moon", "Teleports you to the secret room"},
    {"20", "XIX - The Sun", "Deals 100 damage to all enemies#Full health#Reveals entire map"},
    {"21", "XX - Judgement", "Spawns a beggar"},
    {"22", "XXI - The World", "Reveals the entire map and shows all roomtypes"},
    {"23", "2 of Clubs", "Duplicate your bombs"},
    {"24", "2 of Diamonds", "Duplicate your money"},
    {"25", "2 of Spades", "Duplicate your keys"},
    {"26", "2 of Hearts", "Duplicate your red hearts#Only has a healing effect"},
    {"27", "Ace of Clubs", "Turns all pickups into bombs"},
    {"28", "Ace of Diamonds", "Turns all pickups into coins"},
    {"29", "Ace of Spades", "Turns all pickups into keys"},
    {"30", "Ace of Hearts", "Turns all pickups into hearts"},
    {"31", "Joker", "Teleports you to the devil / angel room"},
    {"32", "Hagalaz", "Destroy all rocks in the room"},
    {"33", "Jera", "Duplicate all pickups in room"},
    {"34", "Ehwaz", "Spawns a trapdoor"},
    {"35", "Dagaz", "+1 Soul Heart#Removes curse effects"},
    {"36", "Ansuz", "Full mapping for this floor"},
    {"37", "Perthro", "Reroll all pedestal items"},
    {"38", "Berkano", "Summons 3 blue spiders and 3 blue flies"},
    {"39", "Algiz", "Invincibility for 30 seconds"},
    {"40", "Blank Rune", "Random rune effect#25% chance to drop itself again"},
    {"41", "Black Rune", "Deals 40 damage to all enemies#Random stat up for every pedestal items in the room#(Destroys all pedestals in room)"},
    {"42", "Chaos Card", "Throwable instant kill-card"},
    {"43", "Credit Card", "Removes the price from all items in the current shop or devil deal, making everything free"},
    {"44", "Rules Card", "Displays \"helpful\" tips on use"},
    {"45", "A Card Against Humanity", "Fills the whole room with poop"},
    {"46", "Suicide King", "Instantly kills you and spawns 10 pickup / Collectibles on the floor"},
    {"47", "Get Out Of Jail Free Card", "Open all doors in the current room"},
    {"48", "? Card", "Activates your spacebar item for free"},
    {"49", "Dice Shard", "Rerolls pedestals and pickups in current room"},
    {"50", "Emergency Contact", "Two of Mom's Hands come down and grab an enemy"},
    {"51", "Holy Card", "Grants the Holy Mantle effect for one room#(Next damage you take is 0)#25% Chance to spawn another holy card"},
    {"52", "Huge Growth", "↑ +7 Damage up#↑ +30 Range up#↑ +Size up#Crush Rocks!#Effect lasts for current room"},
    {"53", "Ancient Recall", "Spawns 3 random cards when used"},
    {"54", "Era Walk", "Slow down enemies#↓ -0.5 Speed down#-1 Shot Speed down#Effect lasts for current room"},]]--
}


---------- Pills ----------

EID.descriptions["pl"].unidentifiedPill = nil--"Unidentified Pill"

EID.descriptions["pl"].pills={
--[[    {"1", "Bad Trip", "Spawns a Gas cloud"},
    {"2", "Balls of Steel", "Deals 1 heart of damage to you"},
    {"3", "Bombs are Key", "+2 Soul Hearts"},
    {"4", "Explosive Diarrhea", "Switches number of bombs with keys"},
    {"5", "Full Health", "Spawns 5 troll bombs at your position"},
    {"6", "Health Down", "Full Health"},
    {"7", "Health Up", "↓ Health down"},
    {"8", "I Found Pills", "↑ Health up"},
    {"9", "Puberty", "No effect"},
    {"10", "Pretty Fly", "Eating 3 will give you Adult transformation (+1 Red Heart)"},
    {"11", "Range Down", "Adds 1 fly orbital"},
    {"12", "Range Up", "↓ -2 Range down"},
    {"13", "Speed Down", "↑ +2.5 Range up"},
    {"14", "Speed Up", "↓ -0.12 Speed down"},
    {"15", "Tears Down", "↑ +0.15 Speed up"},
    {"16", "Tears Up", "↓ -0.28 Tears down"},
    {"17", "Luck Down", "↑ +0.35 Tears up"},
    {"18", "Luck Up", "↓ -1 Luck down"},
    {"19", "Telepills", "↑ +1 Luck up"},
    {"20", "48 Hour Energy!", "Teleport to random room"},
    {"21", "Hematemesis", "Recharges your active item#Drops 1-2 batteries"},
    {"22", "Paralysis", "Drains all but one heart container#Spawns 1-4 red hearts"},
    {"23", "I can see forever!", "You can't move for a few seconds"},
    {"24", "Pheromones", "Opens secret room entrances on current floor"},
    {"25", "Amnesia", "Charms all enemies in room"},
    {"26", "Lemon Party", "Hides the floor map"},
    {"27", "R U A Wizard?", "Spawns large puddle on the ground which damages enemies"},
    {"28", "Percs!", "Shoot diagonally for 30 seconds"},
    {"29", "Addicted!", "Take only half the damage for current room"},
    {"30", "Re-Lax", "Take full heart damage for current room"},
    {"31", "???", "Spawn poop while walking for 2 seconds"},
    {"32", "One makes you larger", "Curse of the maze effect for current floor"},
    {"33", "One makes you small", "You grow bigger#Doesn't affect your hitbox"},
    {"34", "Infested!", "You get smaller#Your hitbox gets smaller"},
    {"35", "Infested?", "Spawn 1 blue spider per poop in room"},
    {"36", "Power Pill!", "Spawn 1 blue spider per enemy in room#Spawns 1-3 blue spiders when no enemy is in the room"},
    {"37", "Retro Vision", "Short invincibility effect"},
    {"38", "Friends Till The End!", "Pixelates the screen for 30 seconds"},
    {"39", "X-Lax", "Spawns 3 blue flies"},
    {"40", "Something's wrong...", "Spawn pool of slippery creep"},
    {"41", "I'm Drowsy...", "Spawn pool of slowing creep"},
    {"42", "I'm Excited!!!", "Slow all enemies in room"},
    {"43", "Gulp!", "Speed up for all enemies in room"},
    {"44", "Horf!", "Consume current trinket and gain its effect permanently"},
    {"45", "Feels like I'm walking on sunshine!", "Shoots one ipecac tear"},
    {"46", "Vurp!", "Short invincibility"},]]--
} 

---------- Sacrifice Room ----------
EID.descriptions["pl"].sacrificeHeader = nil--"[Next Sacrifice Room payout]"

EID.descriptions["pl"].sacrifice={
--[[    {"1", "", "50% chance for 1 Coin#100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
    {"2", "", "50% chance for 1 Coin#100% chance for 1 Bomb, when on B1 and killed the Boss under 1 minute"},
    {"3", "", "67% chance for increased Angel Room chance"},
    {"4", "", "50% chance for 1 random Chest"},
    {"5", "", "33% chance for 3 Coin#67% chance for increased Angel Room chance"},
    {"6", "", "33% chance for teleport to Angel/Devil Room#67% chance for random Chest"},
    {"7", "", "33% chance for 1 random Angel Room item#67% chance for 1 soul heart"},
    {"8", "", "100% chance for 7 troll bombs"},
    {"9", "", "100% chance to spawn \"Uriel\" boss"},
    {"10", "", "50% chance for 7 soul hearts#50% chance for 30 coins"},
    {"11", "", "100% chance to spawn \"Gabriel\" boss"},
    {"12", "", "50% chance to teleport to \"Dark Room\" floor"},]]--
}

---------- Dice Room ----------
EID.descriptions["pl"].diceHeader = nil--"[Dice effect]"

EID.descriptions["pl"].dice={
--[[    {"1", "", "Rerolls all of your items#(only affect collectibles)"},
    {"2", "", "Rerolls all pickups in the room"},
    {"3", "", "Rerolls all pickups on the entire floor"},
    {"4", "", "Rerolls all pedestal items on the floor#Doesnt affect Devil deals"},
    {"5", "", "Reroll and restart the current floor"},
    {"6", "", "Reroll all of your items and all the pickups & items on the entire floor"}]]--
}

---------- Transformations ----------
EID.descriptions["pl"].transformations = {
--[[    "",					-- 0 = none
    "Guppy",			-- 1
    "Fun Guy",			-- 2
    "Lord of the Flies",-- 3
    "Conjoined",		-- 4
    "Spun",				-- 5
    "Mom",				-- 6
    "Oh Crap",			-- 7
    "Bob",				-- 8
    "Leviathan",		-- 9
    "Seraphim",			-- 10
    "Super Bum",		-- 11
    "Bookworm",			-- 12
    "Spider Baby",		-- 13
    "Adult",			-- 14
    "Stompy"			-- 15]]--
}