----------------------------------------------------
-----  Basic Brazilian Portuguese descriptions  -----
----------------------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

-- Brazilian Portuguese letters: ãÃ áÁ àÀ âÂ çÇ éÉ êÊ íÍ õÕ óÓ ôÔ úÚ

local languageCode = "pt_br"

-- init pt_br table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "Brazilian Portuguese (WIP)"
EID.descriptions[languageCode].alternativeLanguageCodes = {"pt-BR", "brazilian"}

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts

---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "", "↑ {{Tears}} +0.7 Lágrimas"},
	{"2", "", "Tiro triplo#↓ {{Tears}} Lágrimas"},
	{"3", "", "Lágrimas teleguiada."},
	{"4", "", "↑ {{Damage}} +0.5 Dano#↑ {{Damage}} +50% Multiplicador de Dano"},
	{"5", "", "Efeito bumerangue às lágrimas#↑ {{Range}} +1,5 Alcance#↑ {{Shotspeed}} +0,6 Velocidade de Disparo"},
	{"6", "", "↑ {{Tears}} +1.5 Lágrimas#↓ {{Range}} -17.62 Alcance#↑ +0.76 Altura da Lágrima"},
	{"7", "", "↑ {{Damage}} +1 Dano#↑ {{Collectible34}} +50% Dano se você tem o Book of Belial ou o efeito do Devil Card ativo"},
	{"8", "", "Atira lágrimas normais (3.5 de dano)"},
	{"9", "", "Todos as moscas inimigas são amigáveis"},
	{"10", "", "+2 Moscas orbitais#Bloqueia projéteis inimigos"},
	{"11", "", "↑ +1 Vida#Renascer com saúde total"},
	{"12", "", "↑ {{Heart}} +1 Saúde#Saúde cheia#↑ {{Damage}} +0.3 Dano#↑ {{Damage}} +50% Multiplicador de Dano#↑ {{Range}} +5.25 Alcance#↑ {{Speed}} +0.3 Velocidade#↑ +0.5 Altura da Lágrima#Aumenta o tamanho do personagem"},
	{"13", "", "{{Poison}} Toque venenoso#↓ {{Speed}} -0.1 Velocidade#{{BlackHeart}} Inimigos podem soltar Corações Negros se envenenados"},
	{"14", "", "↑ {{Speed}} +0.6 Velocidade#↑ {{Range}} +5.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"15", "", "↑ {{Heart}} +1 Saúde#{{Heart}} Saúde máxima"},
	{"16", "", "↑ {{Heart}} +2 Saúde#{{Heart}} Saúde máxima"},
	{"17", "", "{{Key}} +99 Chaves"},
	{"18", "", "{{Coin}} +99 Moedas"},
	{"19", "", "{{Bomb}} +10 Bombas"},
	{"20", "", "Voo"},
	{"21", "", "Revela os ícones no mapa#Não mostra o layout do mapa"},
	{"22", "", "↑ {{Heart}} +1 Saúde"},
	{"23", "", "↑ {{Heart}} +1 Saúde"},
	{"24", "", "↑ {{Heart}} +1 Saúde"},
	{"25", "", "↑ {{Heart}} +1 Saúde"},
	{"26", "", "↑ {{Heart}} +1 Saúde"},
	{"27", "", "↑ {{Speed}} +0.3 Velocidade"},
	{"28", "", "↑ {{Speed}} +0.3 Velocidade"},
	{"29", "", "↑ {{Range}} +5.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"30", "", "↑ {{Range}} +5.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"31", "", "↑ {{Range}} +5.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"32", "", "↑ {{Tears}} +0.7 Lágrimas"},
	{"33", "", "Voo para o sala atual#{{MomsHeart}} Mata o Pé da Mãe e o Coração da Mãe instantaneamente#!!! Mata VOCÊ quando usado no Satan"},
	{"34", "", "↑ {{Damage}} +2 Dano#{{Collectible7}} +50% Multiplicador de Dano se você tiver o Blood of the Martyr#↑ {{AngelDevilChance}} +12.5% Chance da Sala do Diabo/Anjo enquanto segurar"},
	{"35", "", "Cause 40 de dano a todos os inimigos na sala atual"},
	{"36", "", "Solte um cocô e empurre os inimigos#Pode ser colocado próximo a um poço e destruído com uma bomba para fazer uma ponte"},
	{"37", "", "Solta uma grande bomba abaixo do jogador, que causa 110 de dano"},
	{"38", "", "Dispara 10 lágrimas em um círculo ao redor do personagem"},
	{"39", "", "Congele todos os inimigos na sala atual por 4 segundos"},
	{"40", "", "Causa uma explosão no local do jogador#Causa 40 de dano"},
	{"41", "", "Causa medo a todos os inimigos na sala atual por 5 segundos."},
	{"42", "", "{{Poison}} Bomba venenosa arremessável"},
	{"43", "", "<item does not exist>"},
	{"44", "", "Teleporta o personagem para uma sala aleatória"},
	{"45", "", "{{Heart}} Cure 1 Coração Vermelho"},
	{"46", "", "↑ {{Luck}} +1 Sorte#Aumenta a chance de ganhar em jogos e em máquinas"},
	{"47", "", "{{Collectible168}} Ao usar, comece a apontar uma mira#Um míssil cai na mira após 1.5 segundos#Causa 20x o seu dano"},
	{"48", "", "Lágrimas que atravessam inimigos"},
	{"49", "", "Dispara um laser da boca do personagem"},
	{"50", "", "↑ {{Damage}} +1 Dano"},
	{"51", "", "↑ {{Damage}} +1.0 Dano#↑ {{AngelDevilChance}} +10% de chance de Sala do Diabo/Anjo"},
	{"52", "", "{{Bomb}} Lágrimas de bomba#{{Damage}} Cada bomba causa 5x o seu dano + 30#↓ {{Tears}} Atraso de lágrima x 2.5"},
	{"53", "", "Atrai pickups magneticamente"},
	{"54", "", "Revela o layout do andar#Não mostra os ícones das salas"},
	{"55", "", "50% de chance de disparar uma lágrima para trás#{{Luck}} 100% de chance com 2 de Sorte"},
	{"56", "", "Derrama uma poça de limonada#Causa 24 de dano por segundo"},
	{"57", "", "Mosca orbital de média distância#Causa 75 de dano ao contato por segundo"},
	{"58", "", "Invencibilidade por 10 segundos"},
	{"59", "", "<item does not exist>"},
	{"60", "", "Caminhe por pequenas lacunas"},
	{"61", "", "<item does not exist>"},
	{"62", "", "{{HalfHeart}} Cura Meio Coração a cada 13 inimigos mortos"},
	{"63", "", "Agora, os itens ativos podem ser carregados duas vezes"},
	{"64", "", "{{Shop}} 50% de desconto em itens de loja#Conseguir dois deixará tudo de graça"},
	{"65", "", "Gera 6 bombas trolls próximo ao centro da sala"},
	{"66", "", "{{Slow}} Diminua a velocidade dos inimigos por 8 segundos"},
	{"67", "", "Familiar que dispara lágrimas normais#Causa 3.5 de dano por lágrima"},
	{"68", "", "Lágrimas agora são lasers"},
	{"69", "", "{{Chargeable}} Lágrimas carregadas#↑ {{Damage}} Até 400% de Dano#↓ {{Tears}} Lágrimas"},
	{"70", "", "↑ {{Damage}} +1 Dano#↑ {{Speed}} +0.4 Velocidade"},
	{"71", "", "↑ {{Speed}} +0.3 Velocidade#↓ {{Range}} -4.25 Alcance#↑ +1.5 Altura da Lágrima#Diminui seu tamanho"},
	{"72", "", "{{SoulHeart}} +3 Corações de Alma#{{Collectible33}} The Bible é adicionada a todos os tipos de salas que contem itens"},
	{"73", "", "LVL1: Orbital#LVL2: Orbital que dispara#LVL3: Meat Boy LVL1#LVL4: Meat Boy LVL2"},
	{"74", "", "{{Coin}} +25 Moedas"},
	{"75", "", "{{Pill}} Pílulas melhores#{{Pill}} Gera uma pílula ao pegar#{{Pill}} Pílulas identificadas#{{Heart}} Cura 2 Corações#{{DonationMachine}} Mais dinheiro da Blood Donation Machines e {{Collectible135}} IV Bag"},
	{"76", "", "{{SecretRoom}}Revela as entradas das Salas Secretas"},
	{"77", "", "Invencibilidade e +0.28 Velocidade por 6 segundos#Causa 40 de dano ao contato enquanto invencível"},
	{"78", "", "{{SoulHeart}} +1 Coração de Alma#Alta chance de Chefes Cavaleiros#↑ {{AngelDevilChance}} +17.5% oportunidade de Sala do Diabo/Anjo enquanto segurar"},
	{"79", "", "↑ {{Damage}} +1 Dano#↑ {{Speed}} +0.2 Velocidade#{{SoulHeart}} +1 Coração de Alma"},
	{"80", "", "↑ {{Damage}} +0.5 Dano#↑ {{Tears}} +0.7 Lágrimas#{{SoulHeart}} +2 Corações de Alma"},
	{"81", "", "↑ +9 Vidas#Renascer com 1 Coração#↓ Define seus contêineres de Coração Vermelho para 1#!!! Personagens que não podem ter Corações Vermelhos ficam com 1 Coração de Alma/Negro"},
	{"82", "", "Voar#↑ {{Speed}} +0.3 Velocidade"},
	{"83", "", "{{SoulHeart}} +1 Coração de Alma#↑ {{Damage}} +0.7 Dano#↓ {{Speed}} -0.18 Velocidade#Causa 40 de dano ao contato por segundo#Destrói pedras ao andar sobre elas"},
	{"84", "", "Cria um alçapão para o próximo andar#{{LadderRoom}} 10% de chance de criar um alçapão com escada"},
	{"85", "", "{{Card}} Gera 1 carta"},
	{"86", "", "Invoca o Monstro que cai em um inimigo e causa 120 de dano"},
	{"87", "", "25% de chance de disparar lagrimas em 4 direções#{{Luck}} 100% de chance com 7 de Sorte"},
	{"88", "", "Familiar que avança para frente#Causa 52.5 de dano ao contato por segundo"},
	{"89", "", "{{Slow}} 25% de chance de disparar lagrimas de lentidão#100% de chance com 15 de Sorte"},
	{"90", "", "↑ {{Damage}} +1 Dano#↑ {{Tears}} +0.2 Lágrimas#↓ {{Speed}} -0.2 Velocidade"},
	{"91", "", "Revela o tipo de salas adjacentes#{{SecretRoom}} Pode revelar Salas Secretas e Salas Super Secretas"},
	{"92", "", "↑ {{Heart}} +1 Saúde#{{SoulHeart}} +2 Corações de Alma"},
	{"93", "", "Curta invencibilidade#{{Fear}} Amedrontra todos os inimigos#Causa 40 de Dano ao contato por segundo#{{HalfHeart}} Dois inimigos comidos reabastecem Meio Coração"},
	{"94", "", "{{Coin}} Solta moedas aleatórias a cada 2 salas"},
	{"95", "", "Familiar que dispara lasers#Causa 3.5 de dano por disparo"},
	{"96", "", "{{HalfHeart}} Solta Meio Coração a cada 3 salas"},
	{"97", "", "Gera um pickup aleatório"},
	{"98", "", "{{SoulHeart}} Gera 1 Coração de Alma a cada 4 salas"},
	{"99", "", "{{Slow}} Lágrimas que causam lentidão#Causa 3.5 de dano por disparo"},
	{"100", "", "Lágrimas teleguiadas#Causa 3.5 de dano por disparo"},
	{"101", "", "↑ {{Heart}} +1 Saúde#↑ {{Damage}} +0.3 Dano#↑ {{Tears}} +0.2 Lágrimas#↑ {{Range}} +0.25 Alcance#↑ {{Speed}} +0.3 Velocidade#↑ +0.5 Altura da Lágrima"},
	{"102", "", "{{Pill}} Solta uma pílula aleatória"},
	{"103", "", "{{Poison}} 25% de chance de disparar lágrimas que envenenam#{{Luck}} 100% com 12 de Sorte"},
	{"104", "", "Lágrimas se dividem em duas ao contato#Lágrimas divididas causam metade do dano"},
	{"105", "", "Troca os itens dos pedestais na sala atual"},
	{"106", "", "↑ Dano de bombas x2.25#{{Bomb}} +5 Bombas"},
	{"107", "", "Voar#Seu corpo ataca os inimigos com 82 de dano por segundo"},
	{"108", "", "Todo dano recebido é reduzido para Meio Coração"},
	{"109", "", "↑ {{Damage}} +0.04 Dano para cada {{Coin}} moeda que você tem#↑ +3.96 Dano com 99 moedas"},
	{"110", "", "20% de chance de disparar lágrimas que petrificam#↑ {{Range}} +0.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"111", "", "{{Poison}} Peido venenoso#O veneno causa 6 vezes o seu dano"},
	{"112", "", "Orbital#Acelera todos os orbitais#Bloqueia projéteis#Causa 105 de dano ao contato por segundo"},
	{"113", "", "Torreta de disparo automático#Causa 3 de dano por disparo"},
	{"114", "", "{{Chargeable}} Carregável#Cencede uma faca controlável#A faca causa 2x seu dano enquanto segurar e 6x quando arremessado a distância máxima"},
	{"115", "", "Lágrimas espectrais"},
	{"116", "", "-1 carga necessária para itens ativáveis#{{Battery}} Recarrega completamente seu item ativo"},
	{"117", "", "Gera um pássaro quando você é atingido#Causa 4 de dano por segundo"},
	{"118", "", "{{Chargeable}} Carregável#Troca lágrimas por brimstone (*13 seu dano atual)"},
	{"119", "", "↑ {{Heart}} +1 Saúde#↑ {{Speed}} +0.3 Velocidade#{{Heart}} Cura 5 Corações"},
	{"120", "", "↑ {{Tears}} +1.7 Lágrimas#↑ {{Speed}} +0.3 Velocidade#↓ {{Damage}} -38% Multiplicador de Dano#A penalidade diminui à medida que você obtém aumentos de dano de outros itens"},
	{"121", "", "↑ {{EmptyHeart}} +1 Contêiner de Coração Vazio#↑ {{Damage}} +0.3 Dano#↑ {{Range}} +0.25 Alcance#↓ {{Speed}} -0.1 Velocidade#↑ +0.5 Altura da Lágrima"},
	{"122", "", "!!! Quando estiver com meio Coração Vermelho ou menos#↑ {{Damage}} +1.5 Dano#↑ {{Speed}} +0.3 Velocidade"},
	{"123", "", "Concede um familiar aleatório para a sala atual"},
	{"124", "", "Efeito aleatório de um item ativo"},
	{"125", "", "Bombas Teleguiadas#{{Bomb}} +5 Bombas"},
	{"126", "", "↑ {{Damage}} +1.2 Dano#↓ -1 Saúde"},
	{"127", "", "Troca to o andar"},
	{"128", "", "Mosca orbital#Far away#Causa 30 de de dano ao contato por segundo"},
	{"129", "", "↑ {{EmptyHeart}} +2 Contêineres de Coração Vazio#↓ {{Speed}} -0.2 Velocidade#{{HalfHeart}} Cura Meio Coração"},
	{"130", "", "Concede voo enquanto segura#Arrancada em uma direção cruzando a tela (40 de dano ao contato)#{{Speed}} Define sua velocidade para 1.5 se você tem menos que 1.5"},
	{"131", "", "{{Bomb}} Solta 1 bomba coletável a cada 2-3 salas"},
	{"132", "", "{{Damage}} Lágrimas causam mais dano quanto mais elas viajam"},
	{"133", "", "!!! Ao usar converte#1 Contêiner de Coração Vermelho em 3 Corações de Alma"},
	{"134", "", "{{Chest}} 33% de chance da recompesa por limpar a sala ser um baú#33% de chance de não receber nenhuma recompensa ao limpar a sala"},
	{"135", "", "Banco de sangue portátil#Metade de um Coração = 1-3 Moedas#{{Player14}} 0-1 moeda como Keeper"},
	{"136", "", "Armadilha explosiva#Atrai inimigos"},
	{"137", "", "Detonar bombas sob demanda#{{Bomb}} +5 Bombas"},
	{"138", "", "↑ {{Heart}} +1 Saúde#↑ {{Damage}} +0.3 Dano"},
	{"139", "", "{{Trinket}} Agora você pode segurar 2 trinkets"},
	{"140", "", "{{Poison}} Bombas venenosas#{{Bomb}} +5 Bombas"},
	{"141", "", "{{Coin}} Gera 7 moedas aleatórias"},
	{"142", "", "{{SoulHeart}} Uma vez por sala, quando ficar com Meio Coração, você ganha 1 Coração de Alma"},
	{"143", "", "↑ {{Speed}} +0.3 Velocidade#↑ {{Shotspeed}} +0.2 Velocidade de Disparo"},
	{"144", "", "{{Coin}} Coleta moedas do chão#Gera pickups aleatórios em troca"},
	{"145", "", "Solta 2-4 moscas azuis"},
	{"146", "", "{{EternalHeart}} +1 Coração Eterno"},
	{"147", "", "Quebrar todas as pedras na sala atual"},
	{"148", "", "Gera moscas quando você é atingido"},
	{"149", "", "{{Poison}} Lágrimas venenosas explosivas#↑ {{Damage}} +40 Dano#↓ {{Tears}} Lágrimas"},
	{"150", "", "10% de chance de disparar dentes#{{Damage}} Dentes dão X3.2 de dano#{{Luck}} 100% com 9 de Sorte"},
	{"151", "", "16% Chance de gerar uma mosca quando lágrimas atingem um inimigo"},
	{"152", "", "Troca as lágrimas do seu olho direito por um laser contínuo#O laser causa 20% do seu dano#↓ {{Damage}} -35% Dano#↓ {{Tears}} Atraso da Lágrima x 2"},
	{"153", "", "Disparo quádruplo!#↓ {{Tears}} Lágrimas"},
	{"154", "", "↑ {{Damage}} +2 Dano para olho esquerdo"},
	{"155", "", "Familiar que flutua pela sala (8 de dano ao contato)"},
	{"156", "", "{{Battery}} +1 carga quando você for atingido"},
	{"157", "", "!!! Quando você é atingido#↑ {{Damage}} Dano#Dura todo o andar"},
	{"158", "", "Revelar todo o mapa do andar#Solta carta aleatória ou Coração de Alma"},
	{"159", "", "Voo#Lágrimas espectrais"},
	{"160", "", "Gera 5 raios de luz próximos aos inimigos#Causa seu dano + 20"},
	{"161", "", "{{Player4}} Renasce como ??? (Blue Baby) ao morrer"},
	{"162", "", "Chance de invencibilidade quando o personagem é atingido"},
	{"163", "", "Familiar que dispara lágrimas espectrais#Causa 3 de dano por disparo"},
	{"164", "", "Lança uma chama azul#Causa dano ao contato#Bloqueia lágrimas de inimigos#Some após 2 segundos"},
	{"165", "", "↑ {{Damage}} +1 Dano#↑ {{Shotspeed}} +0.23 Velocidade de Disparo"},
	{"166", "", "Troca todos os pickup na sala atual"},
	{"167", "", "Familiar que dispara lagrimas em \"V\"#Causa 4 de dano por disparo"},
	{"168", "", "Em vez de lágrimas, aponta uma mira#Um míssil cai na mira após 1,5 segundos#Causa 20 vezes o seu dano"},
	{"169", "", "↑ {{Damage}} +100% Dano#↑ {{Damage}} +4 Dano Adicional#↓ {{Tears}} Lágrimas#Lágrimas continuam depois de matar um inimigo"},
	{"170", "", "Pisa nos inimigos#Causa 40 de dano por segundo"},
	{"171", "", "Retarda os inimigo por 4 segundos#Causa 10 de dano a todos os inimigos"},
	{"172", "", "Faca orbital#Bloqueia disparos inimigos#Causa 225 de dano por segundo"},
	{"173", "", "{{SoulHeart}} Maior chance de encontrar Corações de Alma"},
	{"174", "", "Familiar que dispara lágrimas de tipo aleatória#Causa 3-5 de dano por disparo"},
	{"175", "", "Abre todas as portas na sala, incluindo {{SecretRoom}}{{SuperSecretRoom}}Salas Secretas, {{ChallengeRoom}}{{BossRushRoom}}Salas de Desafio, e a porta do Mega Satan"},
	{"176", "", "↑ {{Heart}} +1 Saúde#↑ {{Shotspeed}} +0.16 Velocidade de Disparo"},
	{"177", "", "Caça niquel portátio"},
	{"178", "", "Deixa uma poça quando você é atingido#Causa 24 de dano por segundo"},
	{"179", "", "Voo#{{EternalHeart}} +1 Coração Eterno"},
	{"180", "", "Peida quando atingido"},
	{"181", "", "Concede Voo#{{Speed}} Define sua velocidade para 1.5 se você tem menos que 1.5#Holy Dash ao usar"},
	{"182", "", "Lágrimas Teleguiada#↑ {{Heart}} +1 Saúde#{{Heart}} Saúde cheia#↑ {{Damage}} 230% + 1 Dano#↓ {{Tears}} -0.4 Lágrimas#↓ {{Shotspeed}} -0.25 Velocidade de Disparo#↑ {{Range}} +0.38 Alcance"},
	{"183", "", "↑ {{Tears}} +0.7 Lágrimas#↑ {{Shotspeed}} +0.16 Velocidade de Disparo"},
	{"184", "", "Voo#↑ {{Heart}} +1 Saúde"},
	{"185", "", "Voo#Lágrimas espectrais"},
	{"186", "", "!!! -1 Coração Vermelho quando usado#Cause 40 de dano a todos os inimigos"},
	{"187", "", "Bola de pelo em crescimento#Balança ao seu redor#Cresce ao matar um inimigo#Bola maior causa mais dano"},
	{"188", "", "Espelha seu movimento#Atira em direção ao jogador#Causa 3.5 de dano por disparo"},
	{"189", "", "↑ +1 Saúde#↑ +0.3 Dano#↑ +0.2 Lágrimas#↑ +0.5 Alcance#↑ +0.2 Velocidade#↑ +1 Altura da Lágrima#Saúde Máxima"},
	{"190", "", "{{Bomb}} +99 Bombas"},
	{"191", "", "Efeito de lágrima aleatório a cada 2-3 segundos"},
	{"192", "", "Lágrimas teleguiadas para sala atual"},
	{"193", "", "↑ {{Heart}} +1 Saúde#↑ {{Damage}} +0.3 Dano"},
	{"194", "", "↑ {{Shotspeed}} +0.16 Velocidade de Disparo#{{Card}} +1 Carta"},
	{"195", "", "{{Pill}} Solta 4 pílulas"},
	{"196", "", "{{SoulHeart}} +2 Corações de Alma#↑ {{Tears}} +0.4 Lágrimas"},
	{"197", "", "↑ {{Damage}} +0.5 Dano#↑ {{Range}} +0.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"198", "", "Cria 1 pickup de cada tipo"},
	{"199", "", "{{Key}} +2 chaves#Mais itens de baús"},
	{"200", "", "{{Charm}} 10% de chance de lágrimas que encantam inimigos"},
	{"201", "", "↑ {{Damage}} +0.3 Dano#{{Confusion}} 10% de chance de disparar lágrimas que intimidam inimigos"},
	{"202", "", "Transforma inimigos em ouro ao tocar#Causa dano ao contato baseado na quantidade de moedas que você tem#{{Coin}} Inimigos dourados soltam moedas#Alta chance de efeitos que geram Cocôs gerarem Cocôs Dourados"},
	{"203", "", "Duplica todos os pickups"},
	{"204", "", "50% de chance de soltar um pickup aleatório quando for atingido"},
	{"205", "", "{{Battery}} Ao usar, recarrega completamente seu item ativo ao custo de 2 Corações#!!! Só funciona quando o item não tem cargas!"},
	{"206", "", "↑ {{Damage}} +1 Dano#↑ {{Tears}} Lágrimas#Sua cabeça agora é um orbital que não recebe dano e causa 105 de dano ao contato#Você irá disparar pela cabeça"},
	{"207", "", "LVL1: Orbital#LVL2: Orbital que dispara#LVL3: Bandage Girl LVL1#LVL4: Bandage Girl LVL2"},
	{"208", "", "+15% de chance de Inimigos Campeões aparecerem#↑ {{Damage}} +1 Dano"},
	{"209", "", "{{Bomb}} +5 Bombs#{{Confusion}} Explosões confundem e danificam todos os inimigos na sala"},
	{"210", "", "Invencível ao ficar parado por 1 segundo"},
	{"211", "", "Gerar 1-2 aranhas ao ser atingido"},
	{"212", "", "50% de chance de reviver com Meio Coração após morrer"},
	{"213", "", "Lágrimas que protejem#Lágrimas bloqueiam projéteis inimigos#↓ {{Shotspeed}} -0.15 Velocidade de Disparo"},
	{"214", "", "↑ {{Range}} +5 Alcance#Deixa em rastro que causa dano após receber dano"},
	{"215", "", "↑ {{AngelDevilChance}} 100% de chance de gerar Salas do Diabo/Anjo"},
	{"216", "", "↑ {{Damage}} +1 Dano#{{BlackHeart}} +3 Corações Negros"},
	{"217", "", "Chance aleatória de gerar uma aranha azul ao disparar lágrimas#{{Heart}} Cura 1 Coração"},
	{"218", "", "↑ {{Heart}} +1 Saúde#{{HalfHeart}} chance de curar Meio Coração a cada minuto"},
	{"219", "", "↑ {{EmptyHeart}} +1 Contêiner de Coração Vazio#{{Heart}} Chance de gerar Corações Vermelhos ao ser atingido"},
	{"220", "", "Explosões de bombas também disparam 10 lágrimas em um círculo#{{Bomb}} +5 Bombas"},
	{"221", "", "Lágrimas ricocheteiam nas paredes, inimigos e objetos"},
	{"222", "", "Segurar o botão de disparo faz com que as lágrimas fiquem paradas no ar#Ao soltar, todas elas dispararão na direção que foram disparadas#↑ {{Tears}} -2 Atraso da Lágrima"},
	{"223", "", "Explosões curam o personagem#{{Bomb}} +5 Bombas"},
	{"224", "", "Lágrimas divididas em 4 ao acertar#Lágrimas divididas cusam metade do dano#↑ {{Tears}} +1 Lágrimas#↓ {{Range}} -10.0 Alcance"},
	{"225", "", "{{SoulHeart}} Chance de soltar um Coração de Alma ao ser atingido#{{HalfHeart}} Inimigos tem a chance de soltar Meio Coração ao morrerem"},
	{"226", "", "↑ {{Heart}} +1 Saúde#{{SoulHeart}} +1 Coração de Alma#{{BlackHeart}} +1 Coração Negro"},
	{"227", "", "{{Coin}} +3 Moedas#Gera uma moeda ao ser atingido#{{Player14}} 0-1 moeda como Keeper"},
	{"228", "", "{{Fear}} 15% de cahnce de disparar lagrimas de medo#↑ {{Tears}} +1 Lágrimas"},
	{"229", "", "{{Chargeable}} As lágrimas agora podem ser carregadas e disparadas com maior força#↓ {{Tears}} 4.3x Atraso da Lágrima"},
	{"230", "", "↑ {{Damage}} +1.5 Dano#↑ {{Speed}} +0.2 Velocidade#{{Fear}} Lágrimas que amedrontam inimigos#↓ {{EmptyHeart}} Remove todos os Espçoes de Corações#{{BlackHeart}} +6 Corações Negros"},
	{"231", "", "Deixe um rastro de lentidão#{{Slow}} 10% de chance de lágrimas lentas#{{Luck}} 100% de chance com 18 de Sorte"},
	{"232", "", "{{Slow}} Ao ser atingido, desacelera todos os inimigos na sala permanentemente#↑ {{Speed}} +0.3 Velocidade"},
	{"233", "", "Lágrimas orbitam em torno do personagem#↑ +7 Altura da Lágrima#↑ {{Range}} Alcance#Lágrimas espectrais"},
	{"234", "", "Gera aranhas quando você mata um inimigo"},
	{"235", "", "<item does not exist>"},
	{"236", "", "Ao ser atingido, transforme o inimigo em cocô"},
	{"237", "", "Lágrimas de foices#↑ {{Damage}} +1.5 Dano#↑ Tamanho da Lágrima#↓ {{Tears}} -0.3 Lágrimas#Lágrimas atravessam inimigos"},
	{"238", "", "!!! Peça de chave para a porta do Mega Satan!#{{AngelRoom}} Chance de Sala do Anjo 25% maior"},
	{"239", "", "!!! Peça de chave para a porta do Mega Satan!#{{AngelRoom}} Chance de Sala do Anjo 25% maior"},
	{"240", "", "Todas as estatísticas ↑/↓ aleatoriamente"},
	{"241", "", "Duplica todas as recompensas ao limpar a sala#33% de chance de não receber recompensa por limpar a sala#{{GreedMode}} Não afeta o Modo Greed"},
	{"242", "", "50% de chance de bloquear lágrimas"},
	{"243", "", "Escudo que bloqueia projéteis"},
	{"244", "", "Ocasionalmente, dispare lasers além de suas lágrimas"},
	{"245", "", "Duplica todos os seus disparos"},
	{"246", "", "{{SecretRoom}} Revela Salas Secretas"},
	{"247", "", "Seus familiares causam o dobro de dano"},
	{"248", "", "Aranhas e Moscas Azuis causam o dobro do dano"},
	{"249", "", "2 itens de Boss aparecem em vez de 1#!!! Apenas um pode ser pego"},
	{"250", "", "{{Bomb}} Todos os drops de bombas se tornam bombas duplas"},
	{"251", "", "{{Card}} Você pode carregar 2 cartas#{{Card}} Transforma todas as pílulas em cartas#{{Card}} Solta uma carta ao pegar"},
	{"252", "", "{{Pill}} Você pode carregar 2 pílulas#{{Pill}} Transforma todas as cartas em pílulas#{{Pill}} Solta uma pílula ao pegar"},
	{"253", "", "↑ {{Luck}} +1 Sorte#↑ {{Heart}} +1 Saúde"},
	{"254", "", "↑ {{Damage}} +1 Dano#↑ {{Range}} +5 Alcance#!!! Aplica-se apenas ao olho esquerdo"},
	{"255", "", "↑ {{Tears}} +0.5 Lágrimas#↑ {{Shotspeed}} +0.2 Velocidade de Disparo"},
	{"256", "", "{{Burning}} Efeito de fogo em bombas#{{Bomb}} +5 Bombas"},
	{"257", "", "{{Burning}} Lágrimas flamejantes#Chance de lágrimas explodirem#{{Luck}} 100% de chance com 13 de Sorte#!!! A explosão pode te machucar!"},
	{"258", "", "Troca todos os seus itens e status ao pegar e toda vez que você troca de andar"},
	{"259", "", "↑ {{Damage}} +1 Dano#{{Fear}} Lágrimas que amedrontam inimigos"},
	{"260", "", "{{CurseCursed}} Imunidade a maldições#{{BlackHeart}} +1 Coração Negro#{{DevilChanceAB}} / {{AngelChanceAB}} +15% chance de Sala do Diabo/Anjo"},
	{"261", "", "↑ {{Damage}} +100% Dano#↓ {{Damage}} Lágrimas causam menos dano à medida que viajam"},
	{"262", "", "{{BlackHeart}} +1 Coração Negro#Quando ficar com 1 Coração, causa dano a todos os inimigos na sala"},
	{"263", "", "<item does not exist>"},
	{"264", "", "Orbital#Quando você for atingido ele atacará os inimigos#Causa 22.5 de dano por segundo"},
	{"265", "", "Quando ele for atingido por lágrimas inimigas, tem 10% de chance de causar dano em todos os inimigos na sala"},
	{"266", "", "Deixa um rastro de lentidão#Gera 1-2 aranhas amigáveis após limpar uma sala"},
	{"267", "", "Atira lasers#Causa 3.5 de dano por disparo#Move em direção aos seus disparos"},
	{"268", "", "Familiar que gera moscas azuis quando o player está disparando"},
	{"269", "", "Deixa um rastro que causa 6 de dano por segundo"},
	{"270", "", "{{HalfHeart}} Cura Meio Coração quando mata um inimigo#Causa 3.2 de dano por segundo"},
	{"271", "", "Solta pickups aleatórios a cada poucas salas"},
	{"272", "", "Mosca amigável explosiva#A explosão causa 60 de dano"},
	{"273", "", "Familiar bomba arremessável#A explosão causa 60 de dano"},
	{"274", "", "Quando você for atingido, ganha um orbital de médio alcance para a sala#Orbital causa 75 de dano por segundo"},
	{"275", "", "{{Collectible118}} Familiar que carrega para disparar um laser brimstone#O disparo causa 31.5 dano por segundo"},
	{"276", "", "Ganhe invulnerabilidade#!!! Quando o familiar coração é atingido, você sofre dano"},
	{"277", "", "Familiar fantasma amigável#Causa 4 de dano por segundo"},
	{"278", "", "{{Heart}} Coleta Corações Vermelhos do chão#A cada 1.5 Corações, gera um Coração de Alma/Negro ou uma aranha"},
	{"279", "", "Orbital grande e gordo#Causa 30 de dano por segundo"},
	{"280", "", "Gera aranhas azuis aleatóriamente ao entrar em uma sala hostíl"},
	{"281", "", "Familiar isca#Os inimigos o atacarão"},
	{"282", "", "Permite pular"},
	{"283", "", "Troca todos os pickups, itens e itens de pedestais na sala"},
	{"284", "", "Troca todos os itens passivos que você estiver segurando"},
	{"285", "", "Troca todos os inimigos na sala"},
	{"286", "", "Imita o efeito da carta que você estiver segurando"},
	{"287", "", "Recebe um desses efeitos para o andar: #{{Collectible54}} Treasure Map#{{Collectible21}} Compass #{{Collectible246}} Blue Map"},
	{"288", "", "Gerar 1-4 aranhas azuis"},
	{"289", "", "Lança uma chama vermelha#A chama persiste até causar dano ou bloquear disparos 5 vezes"},
	{"290", "", "{{Heart}} Armazena até 4 pickups de Corações Vermelhos para uso futuro"},
	{"291", "", "Transforma todos os inimigos não chefes em cocô#Mata instântaneamente inimigos e chefes cocôs"},
	{"292", "", "{{BlackHeart}} +1 Coração Negro"},
	{"293", "", "{{Collectible118}} Atira laser brimstone nas 4 direções"},
	{"294", "", "Afasta inimigos e projéteis próximos#10% de chance de se tornar o mais forte {{Collectible484}}Wait What? Ao trocá-lo por um item ativo diferente e pegá-lo novamente"},
	{"295", "", "Causa dano em toda a sala com 2x o seu dano#{{Coin}} Preço: 1 moeda"},
	{"296", "", "Converte 2 Corações de Alma/Negro em 1 Contêiner de Coração Vermelho"},
	{"297", "", "gera itens com base no andar atual:#Basement 1: 2 {{SoulHeart}}#Basement 2: 2 {{Key}} e 2 {{Bomb}}#Caves 1: 1 {{BossRoom}} Item#Caves 2: B1+C1#Depths 1: 4 {{SoulHeart}}#Depths 2: 20 {{Coin}}#Womb 1: 2 {{BossRoom}} Itens#Womb 2:{{Collectible33}} The Bible#Blue Womb: Nada#Sheol: 1 {{DevilRoom}} item + 1 {{BlackHeart}}#Cathedral: 1 {{AngelRoom}} item + 1 {{EternalHeart}}#Dark Room: Desbloqueia {{Collectible523}} Moving Box#Chest: 1 moeda"},
	{"298", "", "Invencibilidade e +0.28 Velocidade por 6 segundos#Nenhum dano ao contato"},
	{"299", "", "↓ {{Speed}} -0.3 Velocidade#↑ {{Speed}} Ganhe velocidade lentamente enquanto estiver em salas hostis#{{Collectible77}} Com 2 de velocidade, ganha invencibilidade e causa dano ao contato#Depois, perca o aumento de velocidade do Taurus para a sala"},
	{"300", "", "↑ {{Speed}} +0.25 Velocidade#Inflinge dano aos inimigos ao toca-los"},
	{"301", "", "{{SoulHeart}} +3 Corações de Alma#Depois de ser atingido, ganhe redução de dano (-50% do dano recebido)"},
	{"302", "", "Quebra pedras ao andar sobre elas#Aumenta seu tamanho"},
	{"303", "", "Chance de obter invencibilidade ao ser atingido#{{Pill}} Converte pílulas negativas em positivas"},
	{"304", "", "+6 {{Coin}} Moedas, {{Bomb}} Bombas, {{Key}} Chaves#Equilibra suas estatísticas#!!! Todas as estatísticas posteriores também serão afetadas"},
	{"305", "", "{{Poison}} Lágrimas que envenenam"},
	{"306", "", "↑ {{Speed}} +0.2 Velocidade#Lágrimas que atravessam inimigos"},
	{"307", "", "↑ {{Heart}} +1 Saúde#↑ {{Damage}} +0.5 Dano#↑ {{Speed}} +0.1 Velocidade#↑ {{Range}} +1.5 Alcance#↑ {{Tears}} Lágrimas#+1 Chave, Bomba e Moeda"},
	{"308", "", "Deixa um rastro azul#O rastro causa 6 de dano por segundo"},
	{"309", "", "↑ {{Tears}} Lágrimas#Lágrimas com maio recuo"},
	{"310", "", "↑ {{Damage}} +100% Dano#↓ {{Tears}} -50% Lágrimas#↓ {{Shotspeed}} -0.5 Velocidade de Disparo"},
	{"311", "", "{{Player12}} Quando morto, renasce como Judas Negro#{{Damage}} Ele tem 2x Multiplicador de Dano"},
	{"312", "", "↑ {{Heart}} +1 Saúde#{{Heart}} Cura um Coração Vermelho#Agora todos os Corações Vermelhos curam o dobro do seu valor"},
	{"313", "", "Ignore o primeiro dano em todas as salas"},
	{"314", "", "↑ {{Heart}} +1 Saúde#↓ {{Speed}} -0.4 Velocidade#Quebra pedras ao andar sobre elas"},
	{"315", "", "Lágrimas magnéticas#Afeta inimigos, pickups e trinkets"},
	{"316", "", "Onda carregada de lágrimas#!!! Quando atingido enquanto estiver parcialmente carregado, teleporta você para uma sala aleatória#{{Collectible260}} Não te teleporta se você tem a Black Candle"},
	{"317", "", "Lágrimas deixam rastro tóxico#O rastro causa 30 de dano por segundo"},
	{"318", "", "Familiar corpo a corpo#Causa 6 de dano ao contato por segundo"},
	{"319", "", "Salta pela sala#Atira em direção ao personagem#{{Damage}} O dano dele é igual ao seu dano"},
	{"320", "", "Familiar controlável#Causa 5 de dano ao contato por segundo"},
	{"321", "", "Bola arremessável que pode destruir pedras#Causa 10.7 de dano ao contato por segundo"},
	{"322", "", "Copia o efeito de um de seus familiares#Causa o dobro do seu dano"},
	{"323", "", "Quando usado, dispara 8 lágrimas em todas as direções#Recarrega ao disparar"},
	{"324", "", "Teleporta você para#{{TreasureRoom}} Sala do Tesouro, {{SecretRoom}} Sala Secreta, {{SuperSecretRoom}} Sala Super Secreta ou a Sala {{ErrorRoom}} I AM ERROR"},
	{"325", "", "Corta sua cabeça#A cabeça se torna um familiar estacionário#Controle seu corpo separadamente"},
	{"326", "", "Invencibilidade enquanto estiver ativando#!!! Qaundo não estiver com carga, você levará dano"},
	{"327", "", "Invencibilidade ao ser atingido e estiver com Meio Coração Vermelho ou nenhum"},
	{"328", "", "Causa dano a todos os inimigos da sala ao ser atingido e estiver com Meio Coração Vermelho ou nenhum"},
	{"329", "", "Em vez de disparar lágrimas você controla uma lágrima gigante"},
	{"330", "", "↑ {{Ters}} Aumento de lágrimas muito alto (atrasso / 4) -2#↓ {{Damage}} -80% Dano"},
	{"331", "", "Lágrimas teleguiada#Lágrimas ganham uma aura que causa dano aos inimigos#↑ {{Damage}} +0.5 Dano#↑ {{Range}} +1.2 Alcance#↓ {{Tears}} -0.3 Lágrimas#↓ {{Shotspeed}} -0.3 Velocidade de Disparo#↑ {{Tearsize}} 50% Tamanho da Lágrima#↑ +0.5 Altura da Lágrima"},
	{"332", "", "{{Player11}} Ao morrer renasce como Lázaro (Revivido)"},
	{"333", "", "Revela todo o mapa do andar"},
	{"334", "", "↑ {{Heart}} +3 Saúde"},
	{"335", "", " {{SoulHeart}}+2 Corações de Alma#Concede um aura que desvia projéteis e inimigos"},
	{"336", "", "Lágrimas que atravessam inimigos#Lágrimas espectrais#↑ {{Range}} +0.25 Alcance#↓ {{Shotspeed}} -0.4 Velocidade de Disparo#↑ {{TearsizeAB}}+50% Tamanho da Lágrima#↓ -0.5 Altura da Lágrima"},
	{"337", "", "Retarda ou acelera os inimigos a cada 4 salas"},
	{"338", "", "Boomerang arremessável#Atordoa os inimigos e causa 2x seu dano#Pode pegar itens"},
	{"339", "", "↑ {{Tears}} +5.25 Lágrimas#↑ {{Shotspeed}} +0.16 Velocidade de Disparo#{{BlackHeart}} +1 Coração Negro#↑ +0.5 Altura da Lágrima"},
	{"340", "", "↑ {{Speed}} +0.3 Velocidade#↑ Tamanho do personagem reduzido#{{Pill}} Gera uma pílula aleatória quando pego"},
	{"341", "", "↑ {{Tears}} +0.7 lágrimas#↑ {{Shotspeed}} +0.16 Velocidade de Disparo"},
	{"342", "", "↑ {{Heart}} +1 Saúde#↑ {{Tears}} +0.7 lágrimas#↓ {{Shotspeed}} -0.16 Velocidade de Disparo"},
	{"343", "", "↑ {{Luck}} +1 Sorte#{{SoulHeart}} +1 Coração de Alma#{{Key}} +2 Chaves"},
	{"344", "", "+1 {{BlackHeart}} Coração Negro#{{Bomb}} Gera 2-3 Bombas"},
	{"345", "", "↑ {{Damage}} +1 Dano#↑ {{Range}} +5.25 Alcance#↑ +0.5 Altura da Lágrima"},
	{"346", "", "↑ {{Heart}} +1 Saúde"},
	{"347", "", "Duplica todos os itens de pedestal e consumíveis na sala atual"},
	{"348", "", "{{Pill}} Copia o efeito da pílula que você está segurando no momento"},
	{"349", "", "{{Coin}} 50% de chance de soltar uma moeda aleatória"},
	{"350", "", "{{Poison}} No início de cada sala, todo inimigo recebe um efeito de veneno#Inimigos mortos deixam uma poça"},
	{"351", "", "Congele todos os inimigos na sala atual#Causa 5 de dano de envenenamento a qualquer inimigo próximo#Envia uma onda de espinhos pela sala#Pode ser usado para abrir Salas Secretas"},
	{"352", "", "!!! Reduz a sua saúde para Meio Coração#Dispara uma grande lágrima espectral penetrante ((seu dano + 1) x 10)"},
	{"353", "", "{{Bomb}} +5 Bombas#Bombas agora explodem em forma de cruz"},
	{"354", "", "↑ {{Heart}} +1 Saúde#{{Trinket}} Gera um trinket aleatório"},
	{"355", "", "↑ {{Range}} +1.25 Alcance#↑ {{Luck}} +1 Sorte#↑ +0.5 Altura da Lágrima"},
	{"356", "", "Faz com que o seu item ativo seja ativado duas vezes quando usado"},
	{"357", "", "Duplique seus familiares para a sala atual#Se você não tem nenhum familiar, {{Collectible113}} Demon Baby será gerado para a sala atual"},
	{"358", "", "Dispare 2 lágrimas de uma vez na diagonal#Lágrimas espectrais"},
	{"359", "", "↑ {{Damage}} +1.5 Dano#Aumenta o recuo"},
	{"360", "", "Dispara lágrimas com mesmo dano, status e efeitos que as suas"},
	{"361", "", "Familiar que dispara lágrimas com o seu dano e efeitos de lágrima"},
	{"362", "", "Solta um pickup aleatório em algumas salas"},
	{"363", "", "Familiar orbital#Causa 105 de dano ao contato por segundo#Bloqueia e atrai projéteis#Bloquear 10 lágrimas em uma sala solta um Coração Eterno"},
	{"364", "", "Familiar orbital#Causa 45 de dano de contato por segundo"},
	{"365", "", "Move-se pelas paredes e obstáculos na sala#Causa 105 de dano ao contato por segundo"},
	{"366", "", "{{Bomb}} +5 Bombas#Faz com que suas bombas explodam em 4 pequenas bombas"},
	{"367", "", "{{Bomb}} +5 Bombas#Quando uma bomba mata um inimigo gera aranhas azuis#Faz com que suas bombas grudem nos inimigos"},
	{"368", "", "Atirar em uma direção aumenta sua Taxa de Disparo em até 200%"},
	{"369", "", "↑ {{Range}} +2.25 Alcance#↑ +1.5 Altura da Lágrima#Lágrimas espectrais#Suas lágrimas viajam através das paredes e reaparecem na parede oposta"},
	{"370", "", "↑ {{Tears}} +0.7 Lágrimas#↑ {{Range}} +5.25 Alcance#↑ +0.5 Altura da Lágrima#{{UnknownHeart}} Gera 3 tipos de Corações diferentes quando pego"},
	{"371", "", "Gera 6 bombas trolls sempre que você for atingido#É afetado por itens de bombas"},
	{"372", "", "A cada 30 segundos em que estiver em uma sala não limpa, concede um efeito aleatório:#Adiciona uma carga ao seu item ativo (max. de 2 por sala)#Congela todos os inimigos na sala"},
	{"373", "", "↑ {{Damage}} +12.5% Dano ou +25% para cada lágrima que atinge com sucesso um inimigo(max. +100%)"},
	{"374", "", "Chance aleatória de disparar uma lágrima sagrada"},
	{"375", "", "Concede imunidade a explosão e imunidade a pisões da Mãe e Satan#20% de chance de bloquear lágrimas"},
	{"376", "", "Resabastece itens da loja quando compra um item"},
	{"377", "", "As aranhas são inofensivas"},
	{"378", "", "Disparar lágrimas por 3 segundos solta um Butt Bomb"},
	{"379", "", "As lágrimas têm um hitbox muito maior#Lágrimas espectrais"},
	{"380", "", "{{Coin}} +5 Moedas#Você pode abrir portas com moedas ao invés de chaves"},
	{"381", "", "↑ {{Tears}} +0.7 Lágrimas#Fornece um item aleatório no início de sua próxima \"run\""},
	{"382", "", "Pode ser jogado em inimigos para capturá-los#No próximo uso, o inimigo capturado reaparecerá como companheiro"},
	{"383", "", "Detone qualquer lágrima na tela e faz com que cada uma se divida em mais 6 lágrimas que sairão em círculo"},
	{"384", "", "{{Chargeable}} Se lança e desliza ao redor da sala com velocidade baseada na quantidade de cargas#Causa 5-90 de dano ao contato por segundo dependendo da velocidade"},
	{"385", "", "Pega todas as moedas próximas#A cada 6 moedas ele sobe de nível, exceto o nível 4, que leva 12 moedas#LVL1: Apenas pega moedas#LVL2: Solta pickups aleatórios#LVL3: Atira lágrimas#LVL4: Não irá dispara lágrimas. Ele irá perseguir o inimigo e causar dano ao contato. Chance de gerar bombas"},
	{"386", "", "Troca quanquer objeto de cenário em outro tipo de objeto aleatório (ex. cocôs, potes, TNT, cocôs vermelhos, blocos de pedra, etc.)"},
	{"387", "", "Cria uma enorme aura de luz que retarda os inimigos e projéteis dentro dela"},
	{"388", "", "Converte chaves em baús aleatórios"},
	{"389", "", "{{Rune}} Solta uma runa aleatória a cada 5-6 salas"},
	{"390", "", "Atira lágrimas Sacred Heart#Causa 10 de dano por disparo"},
	{"391", "", "{{Charm}} Toda vez que o personagem sofre dano, causa um efeito de charme em todos os inimigos na sala"},
	{"392", "", "Dará a você um efeito aleatório de item zodíaco a cada andar"},
	{"393", "", "{{Poison}} 15% de chance de disparar lágrimas que envenenam#{{Poison}} Cause dano por veneno ao contato#{{BlackHeart}} Inimigos envenenados têm chance de soltar um Coração Negro ao morrerem"},
	{"394", "", "Atira lágrimas direcionadas automaticamente a um alvo vermelho no chão controlado pelo jogador#↑ {{Tears}} +0.7 Lágrimas#↑ {{Range}} +3.15 Alcance#↑ +0.3 Altura da Lágrima"},
	{"395", "", "{{Chargeable}} Troca lágrimas por um laser carregável em forma de anel que atravessa a sala#O anel tem tamanho maior com cargas maiores"},
	{"396", "", "Cria até dois portais para viajar entre eles#Pode ser colocado em salas diferentes"},
	{"397", "", "Agora, suas lágrimas viajam diretamente para a frente do local onde você está olhando mesmo que você se mova ou se vire#↑ {{Tears}} +0.5 Lágrimas#↑ {{Range}} +5.25 Alcance#↑ {{Shotspeed}} +0.16 Velocidade de Disparo#↑ +0.5 Altura da Lágrima"},
	{"398", "", "Lágrimas podem encolher inimigos#Inimigos encolhidos podem ser mortos ao andar sobre eles"},
	{"399", "", "↑ {{Damage}} +1 Dano#↑ +0.5 Altura da Lágrima#{{Chargeable}} Depois de disparar lágrimas por 3 segundos, cria um anel preto danificando os inimigos dentro dele#{{BlackHeart}} Inimigos mortos pelo anel preto têm chance de derrubar Corações Negros"},
	{"400", "", "Cria uma lança na sua frente#Causa 2 vezes o seu dano#Chance de amedrontar inimigos ao contato"},
	{"401", "", "25% de chance de disparar lágrimas de bombas pegajosas#Bombas pegajosas não causam dano ao atingir"},
	{"402", "", "Agora, itens de pedestais serão escolhidos aleatóriamente#Gera 1-6 pickups aleatórios"},
	{"403", "", "Permite que você veja seu dano de lágrima e as barras de saúde de todos os inimigos#Inflige um efeito de status aleatório no contato#Solta baterias aleatoriamente"},
	{"404", "", "Familiar que bloqueia projéteis#Ao ser atingido tem 10% de chance de peidar, o que irá, encantar, envenenar ou empurrar inimigos"},
	{"405", "", "Salta pela sala#Causa 120 de dano por segundo e aplica um efeito de status aleatório"},
	{"406", "", "Troca suas estatísticas#Afetará apenas estatísticas de dano: Lágrimas, Alcance e Velocidade"},
	{"407", "", "↑ Aumente uma das estatísticas do personagem, dependendo da cor da aura ao seu redor#Quando sofrer dano, você perderá a aura nesta sala e receberá uma nova na próxima sala#Vermelha = +4 {{Damage}} Dano#Azul = -4 {{Tears}} Atraso da lágrima#Amarelo = +0.5 {{Speed}} Velocidade#Laranja = +7.5 {{Range}} Alcance"},
	{"408", "", "Quando você recebe dano, um anel preto aparecerá ao redor do personagem, causando dano ao contato##{{BlackHeart}} Inimigos mortos com ele têm a chance de derrubar um Coração Negro"},
	{"409", "", "{{BlackHeart}} +2 Corações Negro#Quando o personagem não tem Corações Vermelhos:#Recebe Voo#A cada 40 segundos em uma sala hostíl recebe um escudo por 10 segundos"},
	{"410", "", "3.33% de chance de disparar um olho através da sala que dispara na mesma direção do personagem"},
	{"411", "", "↑ {{Damage}} +0.5 Dano para cada inimigo morto na sala atual# Máximo de +5 de Dano após 10 mortes"},
	{"412", "", "Depois de sofrer dano 15 vezes, o personagem ganha um familiar demônio permanente#Máximo de 4 familiares"},
	{"413", "", "Depois de pegar 15 Corações, o personagem ganha um familiar angelical permanente#Máximo de 5 familiares"},
	{"414", "", "{{TreasureRoom}} 2 itens surgem em cada Sala do Tesouro#Você pode pegar somente um"},
	{"415", "", "{{SoulHeart}} +2 Coração de Alma#Se você não tem nenhum Contêiner de Coração Vermelho danificado:#↑ {{Damage}} +100% Dano#↑ {{Range}} +5.25 Alcance#↑ +0.5 Tamanho da Lágrima#↓ {{Shotspeed}} -0.3 Velocidade de Disparo#Desativa para a sala atual quando receber um dano completo"},
	{"416", "", "Permite carregar 2 cartas, pílulas ou runas"},
	{"417", "", "Salta ao redor da sala com uma aura que causa 129% do seu dano a cada segundo#↑ {{Damage}} +50% dano enquanto estiver na aura"},
	{"418", "", "Dá a você um efeito de lágrima diferente a cada lágrima que você disparar"},
	{"419", "", "Teleporta você para outra sala aleatória que ainda não foi limpa#Hierarquia: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}{{BossRushRoom}}>{{IsaacsRoom}}{{BarrenRoom}}>{{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}>{{ErrorRoom}}"},
	{"420", "", "Andar em círculo gerará um símbolo de pentagrama no chão (10 de dano ao contato)"},
	{"421", "", "{{Charm}} Encanta quaisquer inimigos próximos e causa 5 de dano a eles"},
	{"422", "", "Qualquer dano sofrido ou consumíveis usados na sala atual serão redefinidos para o estado anterior"},
	{"423", "", "Grande auréola ao seu redor que causa seu dano ao contato a cada segundo#Chance de refletir projéteis inimigos"},
	{"424", "", "Pickups tem 33% de chance de serem substituídos por um saco#Gera um saco"},
	{"425", "", "Gera um cone de luz na sua frente que retarda inimigos e projéteis dentro dele"},
	{"426", "", "Segue seu movimento com um atraso de 3 segundos#Causa 30 de dano ao contato por segundo"},
	{"427", "", "Gera um barril TNT empurrável#Se usado uma segunda vez na mesma sala enquanto o último barril de TNT ainda estiver lá, ele explodirá"},
	{"428", "", "{{SoulHeart}} +4 Corações de Alma#{{Heart}} Restaura totalmente seus Corações Vermelhos"},
	{"429", "", "{{Coin}} Inimigos tem 5% de chance de soltar uma moeda ao serem atingidos por suas lágrimas"},
	{"430", "", "Segue seu padrão de movimento com atraso de 1 segundos#Dispara lágrimas em inimigos próximos que causam dano igual ao seu"},
	{"431", "", "Segue seu padrão de movimento com atraso de 2 segundos#As lágrimas do personagem que passam pelo bebê, se dividem e aceleram"},
	{"432", "", "{{Bomb}} +5 bombas#Bombas tem a chance de soltarem pickups aleatórios ou encantar inimigos quando explodem"},
	{"433", "", "Toda vez que você sofrer dano, causará medo a todos os inimigos na sala e gerará um familiar que atacará por você.#Ele será morto se estiver muito danificado"},
	{"434", "", "Toda vez que você mata um inimigo, uma mosca azul é adicionada ao pote#Guarda até 20 moscas#Usar o item libera todas as moscas"},
	{"435", "", "Dispara 4 lágrimas em um padrão cruzado#Causa 3.5 de dano por disparo"},
	{"436", "", "{{Tears}} Ao sofrer dano você ganha um aumento de Lágrimas para o resto da sala"},
	{"437", "", "Faz ressurgir todos os inimigos da sala#Permite você ganhar as recompensas da sala quando ela for limpa novamente#!!! Se usado em uma luta do Greed, ele pode trocar os itens da Loja"},
	{"438", "", "{{SoulHeart}} +1 Coração de Alma#↑ {{Tears}} +0.75 Lágrimas#↑ Reduz seu tamanho"},
	{"439", "", "{{Trinket}} Solta um trinket aleatório#Enquanto segurar o efeito dos trinkets é dobrado#↑ {{Luck}} +1 Sorte enquanto segura"},
	{"440", "", "As vezes, você para de disparar e tem que carregar um ataque que libera uma explosão de lágrimas e pedras nos rins#↓ {{Speed}} -0.2 Velocidade#↓ {{Range}} -17 Alcance#↑ +2 Altura da Lágrima"},
	{"441", "", "Atira um enorme laser Mega Satan por 15 segundos#O laser persiste entre salas e andares"},
	{"442", "", "!!! Enquanto estiver com 1 Coração Vermelho:#↑ {{Range}} +1.5 Alcance#↑ {{Tears}} +0.75 Lágrimas#↑ {{Shotspeed}} +0.2 Velocidade de Disparo#!!! Não funciona com personagens sem Corações Vermelhos"},
	{"443", "", "Lança aleatoriamente lâminas de barbear que causam 400% de dano#↑ {{Tears}} +0.3 Lágrimas"},
	{"444", "", "A cada 15 lágrimas disparadas, você dispara um conjunto de lágrimas#Cada lágrima no conjunto causa dano duplo"},
	{"445", "", "↑ {{Damage}} +0.3 Dano#↑ {{Speed}} +0.1 Velocidade#{{SecretRoom}} Um lobo uiva se você entrar em uma sala ao lado de uma Sala Secreta/Super Secreta#{{LadderRoom}} Um som de latido tocará ao entrar em uma sala com um alçapão embaixo de uma pedra"},
	{"446", "", "Ao disparar, você obtém uma aura verde que envenena qualquer inimigo ao contato#O veneno causa o mesmo dano que você"},
	{"447", "", "Enquanto disparar sem parar gera uma nuvem de cocô a cada 7.5 segundos#A nuvem causa 3.5 de dano 5 vezes por segundo#A nuvem dura 15 segundos#Pode ser movida ao disparar nela"},
	{"448", "", "Ao receber dano:#{{Heart}}25% de chance de soltar um Coração Vermelho#{{Collectible214}} 10% de chance de obter ↑ +5 de alcance e deixar rastro de sangue na sala atual"},
	{"449", "", "{{SoulHeart}} +1 Coração de Alma#Projéteis inimigos têm 25% de chance de serem desviados como lágrimas que confundem"},
	{"450", "", "A cada 20 lágrimas, dispara uma lágrima de moeda que causa o dobro de dano#Transforma os inimigos em ouro temporariamente#Inimigos transformados em ouro soltam 1-4 moedas se mortos#!!! A lágrima de moeda custa 1 moeda"},
	{"451", "", "{{Card}} Solta uma carta aleatória#{{Card}} Dobra o efeito de cartas"},
	{"452", "", "Ao sofrer dano, atire 10 lágrimas em um círculo ao seu redor#As lágrimas causam seu dano + 25"},
	{"453", "", "Lágrimas de osso#As lágrimas se quebram em 1-3 fragmentos de osso menores ao atingir qualquer coisa#↑ {{Range}} +1.5 Alcance#↑ +1 Altura da Lágrima"},
	{"454", "", "Permite que o personagem carregue duas cartas, runas ou pílulas#Solta uma carta, runa ou pílula aleatória"},
	{"455", "", "↑ {{Range}} +1.5 Alcance#↑ +1 Altura da Lágrima#Solta uma moeda da sorte"},
	{"456", "", "↑ {{Heart}} +1 Saúde"},
	{"457", "", "{{SoulHeart}} +1 Coração de Alma#20% de chance de ignorar danos"},
	{"458", "", "{{Trinket}} Solta um trinket ou pickup aleatório#{{Trinket}} Concede 1 espaço extra para trinkets"},
	{"459", "", "{{Poison}} 20% de chance de disparar lágrimas venenosas que grudam#Causa seu dano a cada segundo#Gruda por 60 segundos"},
	{"460", "", "{{Confusion}} 25% de chance de disparar lágrimas que confundem#Deixa a tela um pouco mais escura"},
	{"461", "", "{{Slow}} 15% de chance de disparar lágrimas lentas e pegajosas#Cria uma aranha ou mosca azul ao acertar um inimigos"},
	{"462", "", "↑ {{Range}} +1.5 Alcance#↑ +1 Altura da Lágrima#Concede lágrimas que atravessam inimigos#Depois de atingir o primeiro inimigo, as lágrimas causam dano duplo e ganha um efeito de teleguiado"},
	{"463", "", "↑ {{Damage}} +0.3 Dano#Chance de destruir pedras e abrir portas com suas lágrimas"},
	{"464", "", "{{SoulHeart}} +2 Corações de Alma#Os inimigos Campeões soltam pickups que você mais precisa"},
	{"465", "", "↑ {{Tears}} +0.3 Lágrimas#Permite disparar lágrimas na diagonal"},
	{"466", "", "{{Poison}} O primeiro inimigo morto na sala explodirá e envenenará todos os inimigos próximos"},
	{"467", "", "{{Damage}} Causa 10% do seu dano aos inimigos constantemente na direção em que o dedo aponta"},
	{"468", "", "Segue seu movimento com um atraso de 1 segundo#Causa 30 de dano ao contato por segundo"},
	{"469", "", "Deixa um rastro#O rastro causa 6 de dano por segundo#Inimigos que tocam na nuvem podem ativar o efeito Crack The Sky"},
	{"470", "", "Salta pela sala#Causa dano ao contato#Para de se mover enquanto você disparar#Quando parado pode bloquear projéteis"},
	{"471", "", "{{Chargeable}} Carrega seus tiros e solte-os como um efeito espingarda similar ao {{Collectible229}} Monstro's Lung#Cada lágrima causa 3.5 de Dano"},
	{"472", "", "Outros familiares o seguem#Enquanto disparar lágrimas, ele para de se mover#Teleportará de volta para você quando parar de disparar"},
	{"473", "", "Charrega para frente muito divagar#Causa 40.5 de dano ao contato por segundo"},
	{"474", "", "Bloqueia projéteis inimigos"},
	{"475", "", "Mata você 3 segundos depois do uso#Causa 9.999.999 de dano a todos os inimigos"},
	{"476", "", "Duplica 1 pickup aleatório na sala atual"},
	{"477", "", "Quando usado, consuma todos os itens de pedestal na sala#Item ativo: Seu efeito ativa e será ativado a cada uso futuro do Void#Item passivo: Pequeno aumento de estatística para duas estatísticas aleatórias"},
	{"478", "", "Congela todos os inimigos na sala até você disparar novamente#Tocar em um inimigo congelado ainda irá ferir você#Os inimigos descongelam após 30 segundos"},
	{"479", "", "{{Trinket}} Consome seu trinket e oferece o efeito permanentemente#Mais trinkets aparecem"},
	{"480", "", "Converte pickups em moscas ou aranhas azuis#Dobras suas moscas/aranhas azuis atuais#Gera 1 mosca ou aranha azul quando você não tem nenhuma"},
	{"481", "", "Quando usado, ↑/↓ pequena quantidade em um status aleatório#Efeito de lágrima aleatório para a sala atual#Corrompe todos os sprites e música na sala atual"},
	{"482", "", "Transforma você em um personagem diferente#Remove o último item que você coletou"},
	{"483", "", "Afeta o andar inteiro#Explode todos os objetos#Causa 200 de dano a todos os inimigos#Abre a porta do Boss Rush, Hush e todas as Salas secretas#!!! Se você tem uma Bomba Dourada, consome ela ao usar em vez da Mama Mega"},
	{"484", "", "Ao usar, empurra os inimigos para longe e gera uma onde de pedras#Pode abrir salas e quebrar pedras"},
	{"485", "", "50% Chance de dobrar todos os itens, consumíveis e baús no sala#50% Chance de remover itens ou pickups na sala e gerar 1 moeda"},
	{"486", "", "Danifica o personagem sem receber o dano#Pode ativar efeitos de itens"},
	{"487", "", "Remove um Contêiner de Coração Vermelho e fornece:#↑ {{Damage}} +0.2 Dano#{{Collectible73}} Um Cube of Meat#↑ {{Range}} +5 Alcance e deixa uma trilha de rastro de sangue na sala atual"},
	{"488", "", "Concede um efeito de item aleatório para a sala atual"},
	{"489", "", "Efeito de dado aleatório a cada uso"},
	{"490", "", "Cria 2 itens aleatórios baseado nos tipos de item da sala atual#Começa com nenhuma carga"},
	{"491", "", "{{Pill}} Solta uma pílula aleatória a cada 3 salas#{{Poison}} Usar pílulas envenenam os inimigos na sala atual"},
	{"492", "", "↑ {{Luck}} +1 Sorte#Destaca a localização de {{SecretRoom}} Salas Secretas, pedras marcadas e alçapões"},
	{"493", "", "Para cada Contêiner de Coração que estiver vazio:#↑ {{Damage}} +0.2 Dano"},
	{"494", "", "Lágrimas geram 1-2 faíscas de eletricidade quando atingem algo#Físcas causam metade do dano"},
	{"495", "", "Chance de disparar uma chama que bloqueia disparos inimigos e causa dano ao contato#A chama fica até que ela tenha causado dano ou bloqueado disparos 5 vezes"},
	{"496", "", "3.33% de chance de disparar agulhas#{{Luck}} 100% de chance com 15 de Sorte#Agulhas matam inimigos normais instântaneamente, explodindo eles em 10 lágrimas#Agulhas causam 3x o dano contra chefes"},
	{"497", "", "Fique camuflado ao entrar em uma sala até começar a disparar"},
	{"498", "", "{{AngelDevilChance}} Gera uma porta da Sala do Diabo E Sala do Anjo#Ao entrar em uma a outra desaparecerá"},
	{"499", "", "{{AngelChance}} 100% chance de gerar Salas do Anjo"},
	{"500", "", "Gera um saco a cada 5-6 salas"},
	{"501", "", "Dá a você um Contêiner de Coração para cada 25 moedas que você tem#{{Player14}} O Keeper ganhará Corações de Moeda adicionais#{{Collectible416}} Recebe 1 Contêiner de Coração para cada 100 moedas que você tem (caso ultrapasse 99)"},
	{"502", "", "Enquanto disparar, ocasionalmente dispara uma lágrimas que deixa um rastro branco que causa o dobro de dano#Dispara uma lágrimas que deixa um rastro branco quando receber dano"},
	{"503", "", "5% de chance de disparar lágrimas que matam inimigos instantaneamente#Correr contra os inimigos causará 3.5 de dano a eles"},
	{"504", "", "Cria uma torre de mosca que dispara nos inimigos#Cada disparo causa 2 de dano"},
	{"505", "", "Chance de gerar um inimigo encantado ao entrar em uma sala hostil"},
	{"506", "", "Lágrimas que causam sangramento (10% do dano total de pontos de vida dos inimigos a cada 5 segundos)"},
	{"507", "", "{{Damage}} Danifique os inimigos com seu dano + 10% do dano igual à vida máxima do inimigo#Afeta todos os inimigos na sala#{{HalfHeart}} Chance de soltar Meio Coração quando causar dano#{{HalfSoulHeart}} Solta Corações de Alma em vez disso se você não tem HP vermelho"},
	{"508", "", "Orbital que causa sangramento que causa 10% do dano total de pontos de vida máximos dos inimigos a cada 5 segundos#Causa 300% do seu dano ao contato#Não bloqueia disparos"},
	{"509", "", "Orbital que dispara uma lágrima a cada 2 segundos em uma direção aleatória#Causa 3.5 de dano por lágrima#Causa 30 de dano ao contato por segundo#Não bloqueia disparos"},
	{"510", "", "Gera uma versão amigável do chefe Delirium branco para a sala atual"},
	{"511", "", "Orbita em torno de um inimigo aleatório até que ele morra#Causa dano ao contato"},
	{"512", "", "Buraco negro jogável que suga todos os inimigos para dentro dele#Inimigos presos levam dano rápidamente"},
	{"513", "", "↑ {{Damage}} +0.1 Dano#{{SoulHeart}} +1 Coração de Alma#Chance aleatória de encantar ou amedrontar um inimigo#Chance de gerar um cocô de arco-íris ao receber dano"},
	{"514", "", "Causa 'lag' em inimigos e projéteis aleatórios para intervalos de tempo aleatórios, paralisando-os#Chance de congelar e remover disparos inimigos#25% de chance de duplicar recompensas ao limpar as salas"},
	{"515", "", "Cria um item aleatório da sala atual"},
	{"516", "", "Gera um Sprinkler que gira em círculo, borrifando lágrimas em todas as direções"},
	{"517", "", "{{Bomb}} +7 Bombas#Permite que você coloque rapidamente bombas no chão"},
	{"518", "", "Dá a você um familiar aleatório#Tem um efeito de lágrima aleatória#Será trocado novamente a cada andar"},
	{"519", "", "Um familiar que se transforma em outro familiar aleatório a cada 10 segundos"},
	{"520", "", "+1 de carga para seu item ativo a cada 15 inimigos mortos"},
	{"521", "", "Quando usado, faz com que um item aleatório da {{Shop}} Loja ou {{DevilRoom}} Sala do Diabo fique gratuito#{{Shop}} Enquanto segurar, garante que um item da Loja estará a venda"},
	{"522", "", "Projéteis inimigos próximos a você são mantidos no lugar por 3 segundos#Recarrega após 2 segundos"},
	{"523", "", "Quando usado, armazena todos os pickups da sala atual#A utilização novamente as colocará no chão"},
	{"524", "", "Lágrimas serão conectadas por raios de eletricidade#Eletricidade causa o mesmo dano que você"},
	{"525", "", "Ao receber dano, irá gerar um orbital que bloqueia projéteis#Máximo de 3 orbitais ao mesmo tempo#Os orbitais podem ser destruídos se sofrerem muito dano"},
	{"526", "", "Dá a você um familiar cavaleiro que gera seu respectivo gafanhoto#O cavaleiro muda a cada 10 segundos"},
	{"527", "", "Familiar usável que faz tarefas para você:#Abre portas ou baús#Traz um item#50% de chance de roubar da Loja ou Sala do Diabo#Ataca um inimigo até ele morrer#Explode pareder, pedras, shopkeepers, estátuas do anjo, máquinas, mendigos"},
	{"528", "", "Prima obrbital#As lágrimas que atingem o prisma se dividirão em 4 novas lágrimas"},
	{"529", "", "Lágrimas se comportarão como bolas de bilhar"},
	{"530", "", "Concede um pickup ou aumento de status se você matar inimigos na ordem em que estão marcados"},
	{"531", "", "Lágrimas voam em um arco#Lágrimas explodem em lágrimas menores com o impacto#↓ {{Tears}} Lágrimas#↑ {{Damage}} 31% Dano"},
	{"532", "", "As lágrimas diminuem enquanto viaja pela sala#Ao parar, eles explodem em 8 lágrimas menores#As lágrimas podem ser disparadas em outras lágrimas, aumentando-as"},
	{"533", "", "Lágrimas são trocadas por feixes de luz#{{Damage}} Causa 33% de dano, mas pode atingir inimigos múltiplas vezes"},
	{"534", "", "Permite segurar 2 itens ativos#Troque entre eles pressionando o botão de Soltar ({{ButtonRT}})"},
	{"535", "", "{{SoulHeart}} +1 Coração de Alma#{{HealingRed}} Cura 1 Coração Vermelho#{{Collectible313}} Concede um escudo ao entrar na sala do chefe"},
	{"536", "", "Sacrifique 1-2 familiares para gerar um item de Acordo com o Diabo"},
	{"537", "", "{{Pill}} +1 Pílula aleatória ao pegar#Familiar que dispara uma linha de rastro#O tipo de rastro muda toda vez que o jogador usa uma pílula"},
	{"538", "", "{{Trinket}} Solta 3 trinkets aleatórios#{{Collectible479}} Ao receber dano, tem a chance de consumir permanentemente o trinket atual"},
	{"539", "", "Ao receber dano, gera um inimigo amigavel#Gera amigáveis mais fortes quanto mais salas forem limpas sem receber dano"},
	{"540", "", "Lágrimas ricocheteiam no chão#As lágrimas causam dano por respingo a cada ricochete"},
	{"541", "", "{{EmptyBoneHeart}} +1 Coração de Osso#{{Heart}} Gera 3 Corações Vermelhos"},
	{"542", "", "Orbital#Reflete projéteis"},
	{"543", "", "Gera um cocô branco quando você recebe dano#Enquanto estiver dentro da aura do cocô:#↑ {{Tears}} -50% Atraso de Lágrimas#Chance de bloquear danos"},
	{"544", "", "Prego que levita na sua frente#Causa seu dano 6 vezes por segundo"},
	{"545", "", "Cria um osso orbital encantado para cada inimigo morto na sala atual"},
	{"546", "", "Concede uma aura que congela os inimigos no lugar"},
	{"547", "", "{{EmptyBoneHeart}} +1 Coração de Osso#↑ {{Tears}} +0.7 Lágrimas#{{Trinket21}} Gera o trinket Mysterious Paper"},
	{"548", "", "Familiar bumerangue#Causa 7 de dano ao contato#Pode recuperar pickups"},
	{"549", "", "{{EmptyBoneHeart}} Substitui todos os seus Contêineres de Coração Vermelho por 6 Corações de Osso Vazios#Perder um Coração de Osso faz disparar Lágrimas de osso em todas as direções#↑ {{Tears}} +0.5 Lágrimas permanentemente"},
	{"550", "", "!!! Primeira parte da pá quebrada#O Pé da Mãe constantemente o ataca#O uso dela para o ataque para a sala atual#(Tente vencer o Boss Rush com ele)"},
	{"551", "", "!!! Segunda parte de uma pá quebrada"},
	{"552", "", "Cria um alçapão para o próximo andar#Desbloqueia algo legal"},
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "", "{{Coin}} Solte moedas quando for atingido"},
	{"2", "", "50% de chance de drops de cocôs"},
	{"3", "", "-1 Carga para itens ativos"},
	{"4", "", "Teleporta você ao usar um item ativo"},
	{"5", "", "Dobra a chance de aparecer inimigos campeões"},
	{"6", "", "Atrai moedas"},
	{"7", "", "{{AngelChance}} Chance 50% maior de Sala do Anjo#{{Collectible33}} Maior chance de achar The Bible em {{Shop}} Lojas e {{Library}} Bibliotecas"},
	{"8", "", "{{Collectible93}} 5% de chance de ativar o efeito Gamekid ao receber dano"},
	{"9", "", "Lágrimas pulsantes#Afeta a hitbox de lágrimas"},
	{"10", "", "Lágrimas se movem em ondas#↑ {{Tears}} +0.3 Lagrimas"},
	{"11", "", "Lágrimas se movem em espiral em alta velocidade"},
	{"12", "", "Lágrimas 50% maiores#Aumenta o recuo"},
	{"13", "", "{{Shop}} Todos os itens de loja são gratuitos#!!! Ao comprar qualquer item de loja com 0 moedas, este trinket desaparece"},
	{"14", "", "Previne dano de espinhos e rastros"},
	{"15", "", "{{Coin}} Destruir pedras gera moedas"},
	{"16", "", "O Pé da Mãe pisa nos inimigos a cada 60 segundos#!!! O Pé da Mãe também pode pisar no personagem!"},
	{"17", "", "{{BlackHeart}} +1% de chance de Corações Negros"},
	{"18", "", "{{EternalHeart}} +3% de chance de Corações Eternos"},
	{"19", "", "Abra baús sem usar chaves"},
	{"20", "", "{{BlackHeart}} Quando estiver com Meio Coração de saúde, gere um Coração Negro#!!! Até 3 usos"},
	{"21", "", "Imita aleatóriamente:#{{Collectible327}} Polaroid#{{Collectible328}} The Negative#{{Trinket48}} A Missing Page#{{Trinket23}} Missing Poster"},
	{"22", "", "{{Heart}} Diminui a chance de aparição de Corações em 20%#{{BlackHeart}} Pickups de Corações se tornam Corações Negros#{{Key}} Aumenta a chance de aparição de chaves"},
	{"23", "", "{{Player10}} Renasce como The Lost quando morrer#Se ele não estiver desbloqueado, morra em uma {{SacrificeRoom}} Sala do Sacrifício enquanto segurar este trinket para desbloqueá-lo"},
	{"24", "", "{{Coin}} Chance 20% maior de cocôs soltarem moedas#Peida ao pegar moedas#O peido somente empurra os inimigos"},
	{"25", "", "Peide ou solte um cocô a cada 30 segundos"},
	{"26", "", "As lágrimas se movem em padrões angulares#↑ {{Range}} +10 Alcance"},
	{"27", "", "↑ {{Shotspeed}} +0.5 Velocidade de Disparo"},
	{"28", "", "{{Player4}} 22% chance de reaparecer como ??? (Blue Baby) ao morrer"},
	{"29", "", "Gera uma mosca azul ao ser atingido"},
	{"30", "", "{{Poison}} 10% de chance de disparar lágrimas que envenenam"},
	{"31", "", "10% de chance de dispara lágrimas espectrais e que atravessam inimigos"},
	{"32", "", "Receba um efeito aleatório de cogumelo por sala#Pode revelar salas especiais no minimapa"},
	{"33", "", "Quando estiver com Meio Coração de saúde, você ganha: #{{Collectible100}} Little Steven para a sala atual"},
	{"34", "", "{{Heart}} 10% de chance da recompensa por limpar a sala ser um Coração Vermelho aleatório#Chance de um Coração bônus para baús, pedras marcadas e máquinas destruídas"},
	{"35", "", "↑ {{Damage}} +2 Dano"},
	{"36", "", "{{Key}} 10% de chance da recompensa por limpar a sala ser uma chave#Chance de uma chave bônus para baús, pedras marcadas e máquinas destruídas"},
	{"37", "", "↑ {{Speed}} +0.15 Velocidade"},
	{"38", "", "+10% de chance para drops aleatórios de coração vermelho serem: #{{SoulHeart}} Coração de Alma#{{BlackHeart}} Coração Negro#{{EmptyBoneHeart}} Coração de Osso"},
	{"39", "", "↑ {{Tears}} -2 Atraso de Lágrimas"},
	{"40", "", "↑ {{Damage}} 20% de chance de ganhar +1.8 Dano ao ser atingido#{{Luck}} 100% de chance com 8 de Sorte#Efeito dura somente para a sala atual"},
	{"41", "", "10% de chance da recompensa por limpar a sala ser uma bomba#{{Bomb}} Chance de uma bomba bônus para baús, pedras marcadas e máquinas destruídas #!!! Remove o trinket {{Trinket53}} The Tick"},
	{"42", "", "↑ {{Luck}} +1 Sorte#+8% chance de recompensa por limpar a sala#Pickups extras para baús, pedras marcadas e máquinas destruídas"},
	{"43", "", "Quando sofrer dano de Meio Coração ou menos, teleporta o personagem para uma sala aleatória"},
	{"44", "", "{{Pill}} 10% de chance da recompensa por limpar a sala ser uma pílula#{{Pill}} Chance de uma pílula bônus para baús, pedras marcadas e máquinas destruídas"},
	{"45", "", "{{Card}} 10% de chance da recompensa por limpar a sala ser uma carta#{{Card}} Chance de uma carta bônus para baús, pedras marcadas e máquinas destruídas"},
	{"46", "", "{{HalfHeart}} 10% de chance de curar Meio Coração depois de matar todos os inimigos de uma sala"},
	{"47", "", "<unused>"},
	{"48", "", "Ao ser atingido, chance de desencadear o efeito Necronomicon"},
	{"49", "", "{{HalfHeart}} 50% de chance de gerar Meio Coração Vermelho ao pegar moedas"},
	{"50", "", "{{Bomb}} 50% de chance de gerar bombas ao pegar moedas"},
	{"51", "", "{{Key}} 50% de chance de gerar chaves ao pegar moedas"},
	{"52", "", "{{Coin}} 50% de chance de gera +1 moeda ao pegar moedas"},
	{"53", "", "!!! Só consiguirá soltá-lo com o trinket {{Trinket41}} Match Stick#-15% da vida dos Chefes#{{BossRoom}} Cura 1 Coração Vermelho ao entrar na Sala do Chefe"},
	{"54", "", "Familiar com lágrimas que atravessam inimigos#Causa 3.5 de dano por lágrima"},
	{"55", "", "{{EternalHeart}} Consiga um Coração Eterno ao iniciar um novo andar"},
	{"56", "", "{{DevilRoom}} Reduz os preços de todos itens do Arcodo com o Diabo de 2 Contêineres de Coração para 1"},
	{"57", "", "Familiar que salta ao redor da sala#Atira na mesma direção que o personagem#Causa 3.5 de dano por lágrima"},
	{"58", "", "↑ {{Damage}} 1/15 de chance de +0.5 Dano ao matar um inimigo na sala atual#{{Luck}} 100% de chance com 10 de Sorte#O efeito dura somente para a sala atual"},
	{"59", "", "25% de chance de revelar ícones do mapa no início do novo andar#{{Luck}} 100% de chance com 3 de Sorte"},
	{"60", "", "{{Collectible117}} 5% de chance de gerar um pássaro morto ao matar um inimigo#{{Luck}} 100% de chance com 8 de Sorte"},
	{"61", "", "Transforma todos os baús em baús vermelhos"},
	{"62", "", "Pedras marcadas e pedras com um alçapão em baixo a cada 10 segundos"},
	{"63", "", "Transforma bombas trolls em bombas coletáveis"},
	{"64", "", "Efeito de minhoca aleatória a cada 3 segundos"},
	{"65", "", "↑ {{Range}} Duplica seu alcance#↓ -50% Altura das lágrimas"},
	{"66", "", "↓ {{Shotspeed}} -0.4 Velocidade de Disparo#↑ {{Range}} +4 Alcance#↑ +2 Tamanho da Lágrima"},
	{"67", "", "Quando for atingido, 50% de chance de usar:#{{Collectible105}} D6#{{Collectible406}} D8#{{Collectible386}} D12 ou #{{Collectible166}} D20"},
	{"68", "", "Ímã para pickup e inimigos"},
	{"69", "", "Camufla o jogador aleatoriamente por alguns segundos#Confunde inimigos"},
	{"70", "", "Chance de gerar uma aranha enquanto estiver em uma sala hostil"},
	{"71", "", "{{Bomb}} Bombas deixam poça venenosa que causa dano aos inimigos ao contato"},
	{"72", "", "{{Battery}} 6.66% de chance da recompensa por limpar a sala ser uma bateria#+10% de chance de pickups aleatórios serem uma bateria#5% de chance de adicionar 1 carga ao item ativo ao limpar uma sala"},
	{"73", "", "10% de chance de soltar uma bomba coletável quando uma bomba explodir"},
	{"74", "", "0.5% de chance de revelar um alçapão ao quebrar pedras"},
	{"75", "", "Efeito de trinket aleatório em todas as salas"},
	{"76", "", "Baús tem 50/50 de chance de gerarem pickup extras ou um inimigo Mosca"},
	{"77", "", "Aumenta o recuo das lágrimas"},
	{"78", "", "Duração dos efeitos em inimigos 2x maior"},
	{"79", "", "25% de chance de ao usar pílulas/cartas solta uma cópia dela no chão"},
	{"80", "", "↑ {{Damage}} +0.2 Dano para cada item maligno que o personagem segurar"},
	{"81", "", "Invencibilidade dura 2x mais ao ser atingido"},
	{"82", "", "{{TreasureRoom}} +15% de chance de ter 2 itens na Sala do Tesouro nos próximos andares#Você pode pegar apenas um"},
	{"83", "", "{{Shop}} Abra Lojas sem usar chaves"},
	{"84", "", "5% mais moedas e menos Corações para a recompensas ao limpar salas#Greed e Super Greed não aparecem mais em {{Shop}}Lojas ou {{SecretRoom}}Salas Secretas"},
	{"85", "", "Usar uma Máquina de Doação pode curá-lo ou gerar um mendigo"},
	{"86", "", "Destruir cocô gera uma mosca azul"},
	{"87", "", "Cura Meio Coração quando você usa chaves#Meios Corações aparecem como Corações Cheios"},
	{"88", "", "Impede que itens ativáveis apareçam"},
	{"89", "", "Familiares se aproximam do personagem"},
	{"90", "", "Cocô explode quando destruído"},
	{"91", "", "Aumenta a chance de o cocô preto aparecer#Chance de gerar um Coração Negro quando o cocô preto é destruido"},
	{"92", "", "↑ Aumento de estatísticas de seus itens são 33% mais eficazes#↑ {{Tears}} +0.2 Lagrimas#↑ {{Tears}} +1 Atraso da lágrima"},
	{"93", "", "15% de chance por sala para todas as Moscas inimigas se tornarem amigáveis"},
	{"94", "", "Dobra todas as Moscas/Aranhas Azuis"},
	{"95", "", "3% de chance de disparar lágrimas de dentes venenosos"},
	{"96", "", "As lágrimas se movem rapidamente em um padrão espiral#Lágrimas espectrais#↑ {{Range}} +4 Alcance#↑ +2 Altura da Lágrima"},
	{"97", "", "Recebe um familiar que bloqueia projéteis após receber dano 12-20 vezes#Máximo de +2 Familiares"},
	{"98", "", "{{Poison}} 10% de chance de disparar lágrimas teleguiadas, pegajosas e venenosas#Causa o seu dano a cada segundo#Gruda por 10 segundos"},
	{"99", "", "10% de chance de disparar lágrimas saltitantes"},
	{"100", "", "!!! Enquanto estiver com o item totalmente carregado:#↑ +0.25 Velocidade#↑ +0.75 Alcance#↑ +0.2 Lagrimas#↑ +0.10 Velocidade de Disparo#↑ +0.5 Dano#↑ +1 Sorte"},
	{"101", "", "!!! Enquanto estiver com o item totalmente descarregado:#↑ +0.5 Velocidade#↑ +1.5 Alcance#↑ +0.4 Lagrimas#↑ +0.3 Velocidade de Disparo#↑ +1.5 Dano#↑ +2 Sorte"},
	{"102", "", "{{SecretRoom}} +1 Sala secreta extra por andar enquanto segurar"},
	{"103", "", "!!! Quando o número de moedas, chaves e bombas são iguais:#Transforma metade dos consumíveis em consumíveis duplos"},
	{"104", "", "Chance de gerar um item de pedestal ao ser atingido#É destruído depois"},
	{"105", "", "{{Collectible22}} 2% de chance de gerar o item Lunch ao ser atingido#É destruído depois"},
	{"106", "", "Aumenta o raio de qualquer fluido que você produz"},
	{"107", "", "O dano recebido ignora os Corações de Alma/Negros, fazendo com que seus Contêineres de Coração Vermelhos se esgote primeiro"},
	{"108", "", "!!!É destruído depois#Chance de soltar um pickup ou trinket ao ser atingido por uma explosão"},
	{"109", "", "Impede que os familiares do personagem se movam"},
	{"110", "", "{{Shop}} As Lojas agora aparecerão no Womb"},
	{"111", "", "{{TreasureRoom}} Salas de Itens agora aparecem no Womb"},
	{"112", "", "{{RestockMachine}} As máquinas de reabastecimento sempre aparecem nas {{TreasureRoom}} Sala do Tesouro"},
	{"113", "", "Gera uma mosca explosiva de ataque ao entrar em uma sala hostil#A mosca causa o dobro do seu dano + dano de explosão"},
	{"114", "", "Gera uma mosca venenosa de ataque ao entrar em uma sala hostil#A mosca causa o dobro do seu dano"},
	{"115", "", "Gera uma mosca de ataque de lentidão ao entrar em uma sala hostil#A mosca causa o dobro do seu dano"},
	{"116", "", "Gera uma mosca de ataque ao entrar em uma sala hostil#A mosca causa quatro vezes o seu dano"},
	{"117", "", "Gera entre 1-4 moscas de ataque ao entrar numa sala hostil#Cada mosca causa o dobro do seu dano"},
	{"118", "", "5% de chance de ganhar voo após matar um inimigo#Persiste para a sala atual"},
	{"119", "", "{{HalfHeart}} Cura Meio Coração Vermelho ao viajar para o próximo andar"},
	{"120", "", "Recarrega totalmente seu item ativo no início de uma batalha contra um chefe"},
	{"121", "", "{{Collectible313}} Protege você do primeiro dano que recebe em cada andar"},
	{"122", "", "Ao usar seu item ativo ele cairá de volta em um pedestal no chão#Ao receber dano há 2% de chance de soltar um dos seus itens passivos"},
	{"123", "", "Faz com que os chefes Anjos deixem itens normais em vez de peças da chave"},
	{"124", "", "A última porta que você usou permanece aberta"},
	{"125", "", "Conecta seus familiares com raios de eletricidade#Causa 6 de dano por raio"},
	{"126", "", "Cria uma mosca azul ao pegar uma moeda"},
	{"127", "", "Concede aos seus familiares disparos teleguiados"},
	{"128", "", "{{EmptyBoneHeart}} 2% de chance de ganhar um Coração de Osso ao receber dano"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "", "Teleporta você de volta ao início"},
	{"2", "", "Lágrimas teleguiadas para o sala atual"},
	{"3", "", "Faz com que o Pé da Mãe pise em um inimigo (300 de dano)"},
	{"4", "", "Concede para a sala atual:#↑ {{Damage}} +2.35 Dano#↑ {{Speed}} +0.3 Velocidade"},
	{"5", "", "{{BossRoom}} Teleporta você para a Sala do Chefe"},
	{"6", "", "{{SoulHeart}} Solta 2 Corações de Alma"},
	{"7", "", "{{Heart}} Solta 2 Corações Vermelhos"},
	{"8", "", "Invencibilidade#Dano ao contato por 6 segundos"},
	{"9", "", "Gera 1 bomba, 1 chave, 1 moeda, 1 coração"},
	{"10", "", "{{Shop}} Teleporta você para a Loja"},
	{"11", "", "Cria uma máquina caça-níqueis ou Fortuna"},
	{"12", "", "Concede para a sala atual:#↑ {{Heart}} +1 Saúde#↑ {{Damage}} +0.3 Dano#↑ {{Damage}} +50% Dano#↑ {{Range}} +5.25 Alcance#↑ {{Speed}} +0.3 Velocidade#↑ +0.5 Altura da Lágrima"},
	{"13", "", "Concede Voo para a sala atual"},
	{"14", "", "Causa 40 de dano a todos os inimigos na sala"},
	{"15", "", "{{DonationMachine}} Cria uma máquina de doação de sangue#{{GreedMode}} Gera um Devil Beggar no Greed Mode"},
	{"16", "", "↑ {{Damage}} +2 Dano na sala atual"},
	{"17", "", "Gera 6 bombas trolls"},
	{"18", "", "{{TreasureRoom}} Teleporta você para a Sala do Tesouro"},
	{"19", "", "{{SecretRoom}} Teleporta você para a Sala Secreta"},
	{"20", "", "Causa 100 de dano a todos os inimigos#Vida completa#Revela o mapa"},
	{"21", "", "Gera um Mendigo ou Mendigo do Diabo"},
	{"22", "", "Revela o mapa inteiro e mostra todos os tipos de salas"},
	{"23", "", "{{Bomb}} Duplique suas bombas"},
	{"24", "", "{{Coin}} Duplique suas moedas"},
	{"25", "", "{{Key}} Duplique suas chaves"},
	{"26", "", "!!! Só tem efeito curativo#{{Heart}} Duplique seus Corações Vermelhos"},
	{"27", "", "{{Bomb}} Transforma todos os pickups em bombas"},
	{"28", "", "{{Coin}} Transforma todos os pickups em moedas"},
	{"29", "", "{{Key}} Transforma todos os pickups em chaves"},
	{"30", "", "{{Heart}} Transforma todos os pickups em Corações"},
	{"31", "", "{{AngelDevilChance}} Teleporta você para Sala do Diabo ou Sala do Anjo"},
	{"32", "", "Destrua todas as pedras na sala"},
	{"33", "", "Duplique todos os pickups na sala"},
	{"34", "", "Cria um alçapão para o próximo andar"},
	{"35", "", "{{SoulHeart}} +1 Coração de Alma#{{CurseCursed}} Remove os efeitos de maldição"},
	{"36", "", "Revela o mapa completo no andar atual"},
	{"37", "", "Trocar todos os itens do pedestal"},
	{"38", "", "Invocar 3 aranhas azuis e 3 moscas azuis"},
	{"39", "", "Invencibilidade por 30 segundos"},
	{"40", "", "Efeito de rúna aleatória#25% de chance de soltar esta runa novamente"},
	{"41", "", "Causa 40 de dano a todos os inimigos#Converte todo os itens de pedestal na sala em itens de aumento de status#Converte todos os pickups na sala em moscas azuis"},
	{"42", "", "Ao usar, arremessa a carta na direção em que você está se movendo#Mata imediatamente QUALQUER inimigo que ela tocar (exceto Delirium)"},
	{"43", "", "Remove o preço de todos os itens da {{Shop}} Loja atual ou {{DevilRoom}} Acordo com o Diabo, tudo fica de graça"},
	{"44", "", "Exibe dicas \"úteis\" sobre o uso"},
	{"45", "", "Preenche toda a sala com cocô"},
	{"46", "", "Mata o personagem e gera muitos pickups, itens e/ou baús na mesma sala"},
	{"47", "", "Abra todas as portas na sala atual"},
	{"48", "", "Ativa seu item ativo gratuitamente"},
	{"49", "", "Trocar itens e pickups na sala atual"},
	{"50", "", "Mãos da Mãe descem e agarram um inimigo"},
	{"51", "", "{{Collectible313}} Concede o efeito Holy Mantle por uma sala#(Proteção contra dano)#25% de chance de gerar outro Holy Card"},
	{"52", "", "!!! Efeito dura para a sala atual#↑ {{Damage}} +7 Dano#↑ {{Range}} +30 Alcance#Aumenta seu tamanho#Quebra pedras ao contato"},
	{"53", "", "{{Card}} Gera 3 cartas aleatórias quando usadas"},
	{"54", "", "{{Slow}} Diminui a velocidade dos inimigos#↓ {{Speed}} -0.5 Velocidade#↓ {{Shotspeed}} -1 Velocidade de Disparo#Efeito dura para a sala atual"},
}


---------- Pills ----------

EID.descriptions[languageCode].unidentifiedPill = "Pílula não identificada"

EID.descriptions[languageCode].pills={
	{"0", "", "Cria uma nuvem de gás"},
	{"1", "", "Causa 1 Coração de dano a você#Se torna uma pílula de Saúde Cheia se você tem 1 coração ou menos"},
	{"2", "", "{{SoulHeart}} +2 Corações de Alma"},
	{"3", "", "Trocar o número de bombas pelo número de chaves"},
	{"4", "", "Solta 5 bombas trolls no local que você está"},
	{"5", "", "{{Heart}} Saúde Máxima"},
	{"6", "", "↓ {{Heart}} Saúde#Se torna uma pílula Health Up se você tem 0 ou 1 Contêiner de Coração"},
	{"7", "", "↑ {{EmptyHeart}} +1 Contêiner de coração vazio"},
	{"8", "", "Sem efeito"},
	{"9", "", "Sem efeito#{{Adult}} Consumir 3 pílulas concederá a transformação Adulto (+1 Contêiner de Coração Vazio)"},
	{"10", "", "Concede 1 mosca orbital"},
	{"11", "", "↓ {{Range}} -2 Alcance"},
	{"12", "", "↑ {{Range}} +2.5 Alcance"},
	{"13", "", "↓ {{Speed}} -0.12 Velocidade"},
	{"14", "", "↑ {{Spedd}} +0.15 Velocidade"},
	{"15", "", "↓ {{Tears}} -0.28 Lágrimas"},
	{"16", "", "↑ {{Tears}} +0.35 Lágrimas"},
	{"17", "", "↓ {{Luck}} -1 Sorte"},
	{"18", "", "↑ {{Luck}} +1 Sorte"},
	{"19", "", "Teletransporta você para uma sala aleatória#{{ErrorRoom}} Baixa chance de te teleportar para a sala I AM ERROR"},
	{"20", "", "Recarregue seu item ativo#{{Battery}} Solta 1-2 bateria"},
	{"21", "", "Drena todos os Contêineres de Corações, exceto um#{{Heart}} Gera 1-4 Corações Vermelhos"},
	{"22", "", "Você não pode se mover por alguns segundos"},
	{"23", "", "{{SecretRoom}} Abra entradas de Salas Secretas no andar atual"},
	{"24", "", "{{Charm}} Encanta todos os inimigos na sala"},
	{"25", "", "{{CurseLost}} Oculta o mapa do andar"},
	{"26", "", "Cria uma grande poça de limonada no chão que causa dano aos inimigos"},
	{"27", "", "Atire na diagonal por 60 segundos"},
	{"28", "", "Tome apenas Meio Coração de dano para a sala atual"},
	{"29", "", "Danos sofridos na sala atual levam um Coração Inteiro"},
	{"30", "", "Gera cocô enquanto caminha por 2 segundos"},
	{"31", "", "{{CurseMaze}} Curse Of The Maze para andar atual"},
	{"32", "", "Aumeta seu tamanho#Não afeta seu hitbox"},
	{"33", "", "Diminue seu tamanho#Seu hitbox fica menor"},
	{"34", "", "Gera 1 aranha azul por cocô na sala"},
	{"35", "", "Gera 1 aranha azul por inimigo na sala#Gera 1-3 aranhas azuis quando nenhum inimigo está na sala"},
	{"36", "", "Curto efeito invencibilidade"},
	{"37", "", "Pixeliza a tela por 30 segundos"},
	{"38", "", "Gera 3 moscas azuis"},
	{"39", "", "Gera uma poça de fluido escorregadio"},
	{"40", "", "{{Slow}} Gera uma poça de fluido de lentidão"},
	{"41", "", "{{Slow}} Atrassa todos os inimigos na sala"},
	{"42", "", "Acelere todos os inimigos na sala"},
	{"43", "", "Consumir trinket atual e obter seu efeito permanentemente"},
	{"44", "", "{{Collectible149}} Atira uma lágrima do Ipecac"},
	{"45", "", "Curto efeito de invencibilidade"},
	{"46", "", "{{Pill}} Gera a última pílula usada"},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Próximo pagamento da Sala de Sacrifício]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "{{Coin}} 50% Chance de 1 moeda#{{Bomb}} 100% Chance de 1 bomba se matar o chefe em menos de 1 minuto em Basement 1"},
	{"2", "", "{{Coin}} 50% Chance de 1 moeda#{{Bomb}} 100% Chance de 1 bomba se matar o chefe em menos de 1 minuto em Basement 1"},
	{"3", "", "{{AngelRoom}} 67% Chance de aumentar a chance da Sala do Anjo"},
	{"4", "", "{{Chest}} 50% Chance de 1 baú aleatório"},
	{"5", "", "{{Coin}} 33% Chance de 3 moedas#{{AngelChance}} 67% Chance de aumentar a chance de Sala do Anjo"},
	{"6", "", "{{AngelRoom}} 33% Chance de se teletransportar para a Sala do Anjo#{{DevilRoom}} Teleporta para a Sala do Diabo se sua porta já foi gerada neste andar#{{Chest}} 67% de chance de 1 baú aleatório"},
	{"7", "", "{{AngelRoom}} 33% Chance de 1 item aleatório da Sala dos Anjo#{{SoulHeart}} 67% Chance de 1 Coração de Alma"},
	{"8", "", "100% Chance de 7 bombas trolls"},
	{"9", "", "100% Chance do chefe Uriel aparecer"},
	{"10", "", "{{SoulHeart}} 50% Chance de 7 Corações da Alma#{{Coin}} 50% de chance de 30 moedas"},
	{"11", "", "100% Chance do chefe Gabriel aparecer"},
	{"12", "", "50% Chance de teletransportar para a Dark Room"},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Efeitos da Sala do Dado]"

EID.descriptions[languageCode].dice={
	{"1", "", "Troca todos os seus itens passivos e ativáveis em itens aleatórios do mesmo tipo de sala que foram adquiridos"},
	{"2", "", "Troca todos os pickups na sala"},
	{"3", "", "Troca todos os pickups e trinkets em todo o andar#Não afeta a {{DevilRoom}}Sala do Diabo ou {{AngelRoom}}Sala do Anjo"},
	{"4", "", "Troca todos os itens de pedestal no andar#Não afeta a {{DevilRoom}}Sala do Diabo ou {{AngelRoom}}Sala do Anjo"},
	{"5", "", "Troca e reinicia o andar atual"},
	{"6", "", "Troca todos os itens, pickups, trinkets e itens de pedestal, incluindo tudo no andar"},
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Beelzebub",		-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Yes Mother?",		-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}

---------- MISC ----------
-- a function that will get applied onto specific descriptions (glitched items, Abyss locusts,...) to pluralize them
-- Each language can do their own algorithm to modify the given text to their needs
EID.descriptions[languageCode].PluralizeFunction = function(text, amount)
	-- TODO: Not Implemented right now...
	return text
end

EID.descriptions[languageCode].VoidText = "Se absorvido, ganha:"
EID.descriptions[languageCode].VoidNames = {"Velocidade", "Lágrimas", "Dano", "Alcance", "Velocidade de Disparo", "Sorte"}

EID.descriptions[languageCode].CollectionPageInfo = "Este item precisa ser pego para a página de coleção!"

EID.descriptions[languageCode].SingleUseInfo = "{{Warning}} USO ÚNICO {{Warning}}"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Nome do Objeto Demo",
	DemoObjectTransformation = "Transformação Demo",
	DemoObjectText = "Este texto está em Português brasileiro#Uma descrição muito legal e longa para simular quebras de linha causadas pela largura da caixa de texto do EID!#{{Collectible4}} Esta também é uma linha legal#{{Heart}} Esta linha ama você#{{AngelDevilChance}} Esta linha pode ser seu anjo ou demônio#\1 {{Damage}} +1 Mudança de Status",
}

-- the ItemReminder description will predict the abilities of items with a header like "Item Name Result"
EID.descriptions[languageCode].ItemReminder = {
	ResultHeader = " Resultado",
}
-- includes Planetarium even though it's unused in AB+ for convenience
EID.descriptions[languageCode].Teleport2RoomNames = { "Sala Normal","Sala do Chefe","Sala Super Secreta","Loja","Sala do Tesouro","Sala de Sacrifício","Sala do Dado","Biblioteca","Sala da Maldição","Sala do Mini-Chefe","Sala do Desafio/Desafio do Chefe","Sala do Isaac","Sala Estéril","Sala do Jogos","Sala do Baú","Planetário","Sala Secreta","Sala Vermelha Especial","Sala do Anjo/Diabo","Sala I AM ERROR" }
EID.descriptions[languageCode].Teleport2GreedRoomNames = { "Sala Principal", "Sala do Chefe", "Loja", "Sala do Tesouro Prateada/Dourada", "Sala da Maldição", "Sala da Saída", "Sala Super Secreta", "Sala do Anjo/Diabo", "Sala I AM ERROR" }

-- Conditional descriptions
-- Strings will be appended to the original description
-- Tables with one entry will completely replace the original description
-- Tables with two or more entries are find-replace pairs
EID.descriptions[languageCode].ConditionalDescs = {
	["5.300.48"] = "Teleporta para a Sala I AM Error#Blank Card e ?-Carta serão destruídas", -- Blank Card + Q Card
}
