----------------------------------------------------
-----  Basic Brazilian Portuguese descriptions  -----
----------------------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

-- Brazilian Portuguese letters: ãÃ áÁ àÀ âÂ çÇ éÉ êÊ íÍ õÕ óÓ ôÔ úÚ

local languageCode = "pt_br"

-- init pt_br table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "Brazilian Portuguese"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts

---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "", "↑ +0.7 lágrimas"},
	{"2", "", "Tiro triplo#↓ lágrimas"},
	{"3", "", "Lágrimas teleguiada."},
	{"4", "", "↑ +0.5 Dano#↑ +50% multiplicador de Dano #+ Recuo"},
	{"5", "", "Efeito bumerangue às lágrimas# ↑ +1,5 Alcance#↑ +0,6 Velocidade de disparo #↑ +1 Altura da lágrima"},
	{"6", "", "↑ +1.5 Lágrimas#↓ -15.78 Alcance#↑ +0.45 Altura da lágrima"},
	{"7", "", "↑ +1 Dano#↑ +50%/1,5 Dano se você tem o Book of Belial"},
	{"8", "", "Atira lágrimas normais (3.5 de dano)"},
	{"9", "", "Todos as moscas inimigas são amigáveis"},
	{"10", "", "+2 Moscas orbitais"},
	{"11", "", "↑ +1 Vida#Renascer com saúde total"},
	{"12", "", "↑ +1 Saúde#↑ +0.3 Dano#↑ +50% Multiplicador de dano#↑ +5.25 Alcance#↑ +0.3 Velocidade#↑ +0.5 Altura da lágrima#Saúde máxima!"},
	{"13", "", "Toque venenoso#↓ -0.1 Velocidade#Inimigos podem soltar Corações Negros se envenenados"},
	{"14", "", "↑ +0.6 Velocidade#↑ +5.25 Alcance#↑ +0.5 Altura da lágrima"},
	{"15", "", "↑ +1 Saúde#Saúde máxima"},
	{"16", "", "↑ +2 Saúde#Saúde máxima"},
	{"17", "", "+99 Chaves"},
	{"18", "", "+99 Moedas"},
	{"19", "", "+10 Bombas"},
	{"20", "", "Voo"},
	{"21", "", "Revela todos os ícones no mapa#Não mostra o layout do mapa"},
	{"22", "", "↑ +1 Saúde"},
	{"23", "", "↑ +1 Saúde"},
	{"24", "", "↑ +1 Saúde"},
	{"25", "", "↑ +1 Saúde"},
	{"26", "", "↑ +1 Saúde"},
	{"27", "", "↑ +0.3 Velocidade"},
	{"28", "", "↑ +0.3 Velocidade"},
	{"29", "", "↑ +5.25 Alcance#↑ +0.5 Altura da lágrima"},
	{"30", "", "↑ +5.25 Alcance#↑ +0.5 Altura da lágrima"},
	{"31", "", "↑ +5.25 Alcance#↑ +0.5 Altura da lágrima"},
	{"32", "", "↑ +0.7 Lágrimas"},
	{"33", "", "Voo para o sala atual#Mata o Pé da Mãe e o Coração da Mãe instantaneamente#!!! Mata VOCÊ quando usado em Satanás"},
	{"34", "", "↑ +2 Dano#↑ +12.5% Chance de Acordo com o Diabo ou Sala do Anjo#↑ +50% Multiplicador de dano se você tiver Blood of the Martyr"},
	{"35", "", "Cause 40 de dano a todos os inimigos na sala atual"},
	{"36", "", "Solte um cocô no chão#Pode ser colocado próximo a um poço e destruído com uma bomba para fazer uma ponte"},
	{"37", "", "Solta uma grande bomba abaixo do jogador, que causa 110 de dano"},
	{"38", "", "Dispara 10 lágrimas em um círculo ao redor do personagem"},
	{"39", "", "Congele todos os inimigos na sala atual por 4 segundos"},
	{"40", "", "Causa uma explosão no local do jogador#Causa 40 de dano"},
	{"41", "", "Causa medo a todos os inimigos na sala atual por 5 segundos."},
	{"42", "", "Bomba venenosa arremessável"},
	{"43", "", "<item does not exist>"},
	{"44", "", "Teleporta o personagem para uma sala aleatória"},
	{"45", "", "Cure 1 Coração Vermelho"},
	{"46", "", "↑ +1 Sorte#Aumenta a chance de ganhar em jogos e em máquinas"},
	{"47", "", "Ataques aéreos controláveis"},
	{"48", "", "Lágrimas penetrantes"},
	{"49", "", "Dispara um laser da boca do personagem"},
	{"50", "", "↑ +1 Dano"},
	{"51", "", "↑ +1.0 Dano#↑ +10% Oportunidade de negócio com diabo"},
	{"52", "", "Lágrimas de bomba!"},
	{"53", "", "Atrai pickups magneticamente"},
	{"54", "", "Revela o layout do andar"},
	{"55", "", "Chance aleatória de atirar uma lágrima para trás"},
	{"56", "", "Derrama uma poça de limonada"},
	{"57", "", "Mosca orbital de média distância"},
	{"58", "", "Invencibilidade por 10 segundos"},
	{"59", "", "<item does not exist>"},
	{"60", "", "Caminhe por pequenas lacunas"},
	{"61", "", "<item does not exist>"},
	{"62", "", "Cura meio coração a cada 13 inimigos mortos"},
	{"63", "", "Agora, os itens de ativação podem ser carregados duas vezes"},
	{"64", "", "50% de desconto em itens de loja#Conseguir dois fará tudo de graça"},
	{"65", "", "Gera 6 bombas trolls em locais aleatórios na sala"},
	{"66", "", "Diminua a velocidade dos inimigos por 8 segundos"},
	{"67", "", "Familiar que atira lágrimas sangrentas (3.5 de dano)"},
	{"68", "", "Lágrimas agora são lasers"},
	{"69", "", "Lágrimas carregadas"},
	{"70", "", "↑ +1 Dano#↑ +0.4 Velocidade"},
	{"71", "", "↑ +0.3 Velocidade#↓ -4.25 Alcance#↑ +1.5 Altura da lágrima#Diminui seu tamanho"},
	{"72", "", "+3 Corações de alma#Bíblia é mais comum"},
	{"73", "", "LVL1: Orbital#LVL2: Orbital e atira#LVL3: Meat Boy LVL1#LVL4: Meat Boy LVL2"},
	{"74", "", "+25 Moedas"},
	{"75", "", "Melhores pílulas# +1 Pílula#Todas as píluas identificadas"},
	{"76", "", "Revela salas secretas"},
	{"77", "", "Invencibilidade temporária#↑ +40 Dano ao contato"},
	{"78", "", "+1 Coração de alma#Maior chance de Cavaleiros#↑ +17.5% oportunidade de Acordo com o diabo ou Sala do Anjo"},
	{"79", "", "↑ +1 Dano#↑ +0.2 Velocidade#+1 Coração de alma"},
	{"80", "", "↑ +0.5 Dano#↑ +0.7 Lágrimas#+2 Coraçãoa de alma"},
	{"81", "", "↑ +9 Vidas#Renascer com 1 coração"},
	{"82", "", "Voar#↑ +0.3 Velocidade"},
	{"83", "", "+1 Coração de Alma#↑ +0.7 Dano#↓ -0.18 Velocidade#Causa dano ao contato#Quebrar pedras"},
	{"84", "", "Cria um alçapão para pular o andar#10% Chance de alçapão Black Market"},
	{"85", "", "Gera 1 carta"},
	{"86", "", "Invocar Monstro para pisar em um inimigo"},
	{"87", "", "Chance de disparar lagrimas em 4 direções"},
	{"88", "", "Familiar que avança no inimigo e causa dano ao toque (3.5 de dano)"},
	{"89", "", "Chance de disparar lagrimas de lentidão"},
	{"90", "", "↑ +1 Dano#↑ +0.2 Lágrimas#↓ -0.2 Velocidade"},
	{"91", "", "Revela o tipo de salas adjacentes#Revela salas secretas"},
	{"92", "", "↑ +1 Saúde#+2 Corações de Alma"},
	{"93", "", "Invencibilidade#↑ +40 Dano ao contato#Cura meio coração vermelho para cada dois inimigos mortos."},
	{"94", "", "Solta moedas aleatórias a cada 2 salas"},
	{"95", "", "Familiar que atira lasers"},
	{"96", "", "Solta meio coração a cada 3 salas"},
	{"97", "", "Gera um pickup aleatório"},
	{"98", "", "Gera 1 Coração de Alma a cada 4 salas"},
	{"99", "", "Familiar que atira lagrimas negras (3.5 de dano)#Dá lentidão ao inimigo atingido"},
	{"100", "", "Familiar que atira lágrimas teleguiadas (3.5 de dano)"},
	{"101", "", "↑ +1 Saúde#↑ +0.3 Dano#↑ +0.2 Lágrimas#↑ +0.25 Alcance#↑ +0.3 Velocidade#↑ +0.5 Altura da lágrima"},
	{"102", "", "Solta uma pílula aleatória"},
	{"103", "", "Chance de atirar lágrimas de veneno"},
	{"104", "", "Lágrimas que se dividem ao contato"},
	{"105", "", "Troca os itens dos pedestais na sala atual"},
	{"106", "", "Bombas com 110 de dano#+5 Bombas#Maior raio de destruição"},
	{"107", "", "Voar#Seu corpo ataca os inimigos"},
	{"108", "", "Todo dano recebido é reduzido para meio coração"},
	{"109", "", "↑ +0.04 Dano para cada moeda que você tem#↑ +3.96 Dano com 99 moedas"},
	{"110", "", "Lágrimas congelantes#↑ +0.25 Alcance"},
	{"111", "", "Peido venenoso"},
	{"112", "", "Acelera todos os orbitais#7 Dano ao contato#Bloqueia tiros"},
	{"113", "", "Familiar que atira em inimigos em seu raio (3.0 de dano)"},
	{"114", "", "{{Chargeable}} Carregável#Cencede uma faca controlável#A faca causa 2x seu dano enquanto segurar e 6x quando arremessado a distância máxima"},
	{"115", "", "Lágrimas espectrais"},
	{"116", "", "Reduz a carga de qualquer item ativador em 1#Todos os itens com 1 de cobrança têm recargas cronometradas"},
	{"117", "", "Gera um pássaro quando você é atingido"},
	{"118", "", "{{Chargeable}} Carregável#Troca lágrimas por brimstone (*13 seu dano atual)"},
	{"119", "", "↑ +1 Saúde#↑ +0.3 Velocidade#Cura 5 corações"},
	{"120", "", "↑ +1.7 Lágrimas#↑ +0.3 Velocidade#↓ -10% Dano#↓ -0.4 Dano adicional"},
	{"121", "", "↑ +1 Espaço de coração vazio#↑ +0.3 Dano#↑ +0.25 Alcance#↓ -0.1 Velocidade#↑ +0.5 Altura da lágrima"},
	{"122", "", "!!! Quando estiver com meio Coração Vermelho ou menos#↑ +1.5 Dano#↑ +0.3 Velocidade"},
	{"123", "", "Concede um familiar aleatório para a sala atual"},
	{"124", "", "Efeito aleatório de um item ativador"},
	{"125", "", "Bombas Teleguiadas#+5 Bombas"},
	{"126", "", "↑ +1.2 Dano#↓ -1 Saúde"},
	{"127", "", "!!! Uso único#Refaz todo o andar com itens e mosntros aleatórios"},
	{"128", "", "Mosca orbital de longa distante"},
	{"129", "", "↑ +2 Saúde#↓ -0.2 Velocidade#Cura meio coração"},
	{"130", "", "Voo#Arrancada em uma direção cruzando a tela (40 de dano ao contato)"},
	{"131", "", "Solta 1 bomba coletável a cada 2-3 salas"},
	{"132", "", "Mais danos com base na distância percorrida da lágrima"},
	{"133", "", "!!! Converter#1 Espaço de Coração Vermelho em 3 Corações de Alma"},
	{"134", "", "Mais baús aparecem"},
	{"135", "", "Banco de sangue portátil#Metade de um coração = 1 Moeda"},
	{"136", "", "Armadilha explosiva#Atrai inimigos"},
	{"137", "", "Detonar bombas#+5 Bombas"},
	{"138", "", "↑ +1 Saúde#↑ +0.3 Dano"},
	{"139", "", "Agora você pode segurar 2 trinkets"},
	{"140", "", "Bombas venenosas#+5 Bombas"},
	{"141", "", "Gera 7 moedas"},
	{"142", "", "!!! Quando o personagem esta com até meio coração:#+1 Coração de Alma#(Uma vez por quarto)"},
	{"143", "", "↑ +0.3 Velocidade#↑ +0.2 Velocidade de disparo"},
	{"144", "", "Converte moedas em pickups"},
	{"145", "", "Solta 2-4 moscas azuis"},
	{"146", "", "+1 Coração Eterno"},
	{"147", "", "Quebrar todas as pedras na sala atual"},
	{"148", "", "Gera moscas quando você é atingido"},
	{"149", "", "Lágrimas venenosas explosivas#↑ +40 Dano#↓ Lágrimas"},
	{"150", "", "Chance de disparar dentes#Dentes dão X3.2 de dano"},
	{"151", "", "16% Chance de gerar uma mosca quando lágrimas atingem um inimigo"},
	{"152", "", "Troca lágrimas por laser#↓ -35% Dano"},
	{"153", "", "Disparo quádruplo!#↓ Lágrimas (atrasso * 2.1 + 3)"},
	{"154", "", "↑ +2 Dano para olho esquerdo"},
	{"155", "", "Familiar que flutua pela sala (8 de dano ao contato)"},
	{"156", "", "!!! Quando atingido#+1 Carga"},
	{"157", "", "!!! Quando você é atingido#↑ Dano#Dura todo o andar"},
	{"158", "", "Revelar todo o mapa do andar#Solta carta aleatória ou Coração de Alma"},
	{"159", "", "Voo#Lágrimas espectrais"},
	{"160", "", "Cria 5 raio de luz (seu dano + 20 ao contato)"},
	{"161", "", "Renascer como Blue Baby com 3 Corações de Alma"},
	{"162", "", "Chance de invencibilidade quando o personagem é atingido"},
	{"163", "", "Familiar que atira lágrimas espectrais"},
	{"164", "", "Gera um fogo azul"},
	{"165", "", "↑ +1 Dano#↑ +0.23 Velocidade de disparo"},
	{"166", "", "Troca todos os pickup na sala atual."},
	{"167", "", "Familiar que atira lagrimas em \"V\""},
	{"168", "", "Troca lagrimas por mísseis controláveis#Causa 20x seu dano"},
	{"169", "", "Lágrimas gigantes#↑ +100% Dano#↑ +4 Dano adicional#↓ Lágrimas"},
	{"170", "", "Pé que pisa nos inimigos aleatoriamente (40 de dano)"},
	{"171", "", "Retarda os inimigos#Danifica todos os inimigos"},
	{"172", "", "Faca orbital (15 de dano)"},
	{"173", "", "Maior chance de encontrar Corações de Alma"},
	{"174", "", "Familiar que atira lágrimas de tipo aleatória"},
	{"175", "", "Abre todas as portas na sala atual, incluindo salas secretas"},
	{"176", "", "↑ +1 Saúde#↑ +0.16 Velocidade de disparo"},
	{"177", "", "Caça niquel portátio"},
	{"178", "", "Deixa uma poça quando é atingido (8 de dano ao contato)"},
	{"179", "", "Voo#+1 Coração Eterno"},
	{"180", "", "Peidar quando é atingido"},
	{"181", "", "#Voo#Arrancada em uma direção cruzando a tela (40 de dano ao contato)#Efeito Crack The Sky"},
	{"182", "", "Lágrimas Teleguiada#↑ +1 Saúde#↑ 230% + 1 Dano#↓ -0.4 Lágrimas#↓ -0.25 Velocidade de disparo#↑ +4.125 Alcance"},
	{"183", "", "↑ +0.7 Lágrimas.#↑ +0.16 Velocidade de disparo"},
	{"184", "", "Voo#↑ +1 Saúde"},
	{"185", "", "Voo#Lágrimas espectrais"},
	{"186", "", "!!! -1 coração vermelho quando usado#Cause 40 de dano a todos os inimigos"},
	{"187", "", "Familiar que cresce ao matar um inimigo#Causa dano ao contato#Quanto maior mais dano!"},
	{"188", "", "Familiar que espelha seus movimentos (3.5 de dano)"},
	{"189", "", "↑ +1 Saúde#↑ +0.3 Dano#↑ +0.2 Lágrimas#↑ +0.5 Alcance#↑ +0.2 Velocidade#↑ +1 Altura da lágrima#Saúde Máxima"},
	{"190", "", "+99 Bombas"},
	{"191", "", "Efeito de lágrima aleatória"},
	{"192", "", "Lágrimas teleguiadas para sala atual"},
	{"193", "", "↑ +1 Saúde#↑ +0.3 Dano"},
	{"194", "", "↑ +0.16 Velocidade de disparo#+1 carta"},
	{"195", "", "Solta 4 pílulas"},
	{"196", "", "+2 Corações de Alma#↑ +0.4 Lágrimas"},
	{"197", "", "↑ +0.5 Dano#↑ +0.25 Alcance.#↑ +0.5 Altura da lágrima"},
	{"198", "", "Cria 1 pickup de cada tipo"},
	{"199", "", "+2 chaves#Mais itens de baús"},
	{"200", "", "Lágrimas encantadoras"},
	{"201", "", "↑ +0.3 Dano#Intimida inimigos"},
	{"202", "", "Transforma inimigos em ouro ao tocar#Inimigos dourados soltam moedas"},
	{"203", "", "Duplica todos os pickups"},
	{"204", "", "Solte um pickup aleatório quando for atingido"},
	{"205", "", "!!! Só funciona quando o item não é carregado#-2 Corações = Carrega totalmente o item de ativação"},
	{"206", "", "Sua cabeça agora é um orbital#↑ +1 Dano#↑ Lágrimas"},
	{"207", "", "LVL1: Orbital#LVL2: Tiro orbital#LVL3: Bandage Girl LVL1#LVL4: Bandage Girl LVL2"},
	{"208", "", "Maior chance de Inimigos Campeões aparecerem#↑ +1 Dano"},
	{"209", "", "Explosões danificam todos os inimigos na sala#Bombas agora são cocôs#↑ +5 Bombas"},
	{"210", "", "Invencível quando parado"},
	{"211", "", "Gerar aranhas ao ser atingido"},
	{"212", "", "↑ 50% de chance de reviver"},
	{"213", "", "Lágrimas bloqueia projéteis inimigos#↓ -0.16 Velocidade de disparo"},
	{"214", "", "Deixa um rastro de sangue no chão ao ser atingido#↑ +5 Alcance"},
	{"215", "", "↑ 100% de chance para {{DevilRoom}} Acordo com o Diabo ou {{AngelRoom}} Sala do Anjo"},
	{"216", "", "↑ +1 Dano#+3 Coraçõe Negro"},
	{"217", "", "Chance de gerar aranha azul ao disparar lágrimas#Cura 1 coração"},
	{"218", "", "Regenera Saúde lentamente#↑ +1 Saúde"},
	{"219", "", "↑ +1 espaço de coração vazio#Chance de gerar Corações Vermelhos ao ser atingido"},
	{"220", "", "Explosão de lágrima!#+5 Bombas"},
	{"221", "", "Lágrimas ricocheteiam nas paredes, inimigos e objetos"},
	{"222", "", "↑ Lágrimas#Lágrimas anti-gravidade"},
	{"223", "", "Explosões curam o personagem#+5 Bombas"},
	{"224", "", "↑ -1 Atraso de lágrima#↓ -10.0 Alcance#Lágrimas divididas em 4 ao acertar"},
	{"225", "", "Chance de soltar Corações Negros/Alma ao ser atingido"},
	{"226", "", "↑ +1 Saúde#+1 Coração de Alma#+1 Coração Negro"},
	{"227", "", "+3 Moedas#Gera uma moeda ao ser atingido"},
	{"228", "", "15% de cahnce de atirar lagrimas de medo#↑ Lágrimas"},
	{"229", "", "As lágrimas agora podem ser carregadas e atiradas com maior força"},
	{"230", "", "↑ +1.5 Dano#↑ +0.2 Velocidade#Lágrimas de medo#↓ Remove todos os corações vermelhos#+6 Corações negro"},
	{"231", "", "Deixe um rastro de lentidão#Lágrimas lentas"},
	{"232", "", "!!! Ativado ao ser atingido#Efeito lento permanente em inimigos#↑ +0.3 Velocidade"},
	{"233", "", "Lágrimas orbitam em torno do personagem#↑ +7 Altura da lágrima"},
	{"234", "", "Gera aranhas quando você mata um inimigo"},
	{"235", "", "<item does not exist>"},
	{"236", "", "Ao ser atingido, transforme o inimigo em cocô"},
	{"237", "", "Tranforma lágrimas em foice#↑ +1.5 Dano#↓ -0.3 Lágrimas"},
	{"238", "", "!!! Peça de chave para a porta do Mega Satan!#Aparecem {{AngelRoom}} Salas do Anjos"},
	{"239", "", "!!! Peça de chave para a porta do Mega Satan!#Aparecem {{AngelRoom}} Salas do Anjos"},
	{"240", "", "Todas as estatísticas ↑/↓ aleatoriamente"},
	{"241", "", "Duplica todos os pickup que aparecem no final de uma sala"},
	{"242", "", "Chance de bloquear as lágrimas"},
	{"243", "", "Escudo que bloqueia projéteis"},
	{"244", "", "Chance de disparar um laser ao atirar"},
	{"245", "", "Duplica seus tiros"},
	{"246", "", "Revela salas secretas"},
	{"247", "", "Seus familiares causam mais dano"},
	{"248", "", "Aranhas/moscas azuis causam o dobro do dano"},
	{"249", "", "!!! Apenas um pode ser pego#2 itens de Boss aparecem em vez de 1"},
	{"250", "", "Dobra todos os dropes de bombas"},
	{"251", "", "Você pode carregar 2 cartas#Transforma todas as pílulas em cartas"},
	{"252", "", "Você pode carregar 2 pílulas#Transforma todas as cartas em comprimidos"},
	{"253", "", "↑ +1 Sorte#↑ +1 Saúde"},
	{"254", "", "!!! Aplica-se apenas ao olho esquerdo#↑ +1 Dano#↑ +5 Alcance"},
	{"255", "", "↑ +0.5 Lágrimas#↑ +0.2 Velocidade de disparo"},
	{"256", "", "Efeito de fogo em bombas#+5 Bombas"},
	{"257", "", "Lágrimas flamejantes#Chance de lágrimas explodirem (seu dano * 2 + 22)"},
	{"258", "", "Quando pegar e toda vez que você mudar de andar:#Muda todos os seus itens e status"},
	{"259", "", "↑ +1 Dano#Lágrimas de medo"},
	{"260", "", "Imunidade a maldições#+1 Coração Negro#+15% chance de Acordo com o Diabo ou Sala do Anjo"},
	{"261", "", "↑ +100% Dano#↓ Dano diminui pela distância percorrida da lágrima"},
	{"262", "", "+1 Coração Negro#Quando estiver um coração e meio, causa dano a todos os inimigos na sala"},
	{"263", "", "<item does not exist>"},
	{"264", "", "Orbital que quando seu personagem é atingido ele irá atacar"},
	{"265", "", "Quando atingido por lágrimas inimigas, pode danificar todos os inimigos na sala"},
	{"266", "", "Deixa um rastro de lentidão#Chance de gerar aranhas amigáveis ao limpar uma sala"},
	{"267", "", "Atira lasers#Causa 3.5 de dano por tiro#Move em direção aos seus tiros"},
	{"268", "", "Familiar que gera moscas azuis"},
	{"269", "", "Familiar que deixa um rastro de sangue#O rastro causa dano aos inimigos (2 de dano ao contato)"},
	{"270", "", "Cura meio coração quando mata um inimigo"},
	{"271", "", "Chance de solta um pickups aleatório"},
	{"272", "", "Familiar que flutua pela sala e explode ao contato com inimigo (causa 60 de dano)"},
	{"273", "", "Familiar que se joga na direção em que o personagem esta atirando#Explode ao contato com o inimigo (causa 60 de dano)"},
	{"274", "", "Ao ser atingido, ganhe um orbital"},
	{"275", "", "Familiar que atira brimstone"},
	{"276", "", "!!! Quando o Isaac's Heart é atingido, você sofre dano#Ganhe invulnerabilidade#"},
	{"277", "", "Familiar que persegue os inimigos e dá dano ao contato#Chance de causar efeito de medo aos inimigos atingidos"},
	{"278", "", "Converte 1.5 Coração Cermelho em 1 Coração de Negro/Alma, aranha, pílula, carta ou runa"},
	{"279", "", "Orbital que bloqueia projéteis#Inflige 2 de dano ao contato"},
	{"280", "", "Gera aranhas azuis"},
	{"281", "", "Os inimigos o atacarão"},
	{"282", "", "Permite pular"},
	{"283", "", "Trocar todos os pickups, itens e itens de pedestais na sala"},
	{"284", "", "Troca todos os itens da sala"},
	{"285", "", "Troca todos os inimigos na sala"},
	{"286", "", "Imitar o efeito da carta que esta segurando"},
	{"287", "", "Chance de obter o efeito de um dos seguintes itens: Treasure Map, Compass, Blue Map"},
	{"288", "", "Gerar 2-4 aranhas azuis"},
	{"289", "", "Gera um fogo vermelho na sua frente#A chama persiste até causar 23 de dano 5 vezes"},
	{"290", "", "Pode armazenar até 4 corações vermelhos"},
	{"291", "", "Transforma inimigos em cocô#Mata Boss de cocô"},
	{"292", "", "+1 Coração Negro"},
	{"293", "", "Atira brimstone nas 4 direções"},
	{"294", "", "Afasta os inimigos próximos"},
	{"295", "", "!!! Preço: 1 moeda#Causa dano a sala inteira"},
	{"296", "", "!!! Converte#2 Corações de Alma/Negro em 1 Coração Vermelho"},
	{"297", "", "!!! Uso único, gera itens com base no andar atual:#Basement 1: 2 Corações de Alma#Basement 2: 2 chaves e 2 bombas#Caves 1: 1 Item de chefe#Caves 2: B1+C1#Depths 1: 4 Corações de Alma#Depths 2: 20 moedas#Womb 1: 2 Items de Boss#Womb 2: Bíblia#Blue Womb: Nada#Sheol: 1 item Diabo + Coração Negro#Cathedral: 1 Item de Anjo + Coração de Alma#Chest: 1 moeda# Dark Room: Nada#The Void: Nada"},
	{"298", "", "!!! Você não pode disparar lágrimas enquanto o item estiver ativo#Invencibilidade por 5 segundos#↑ Velocidade"},
	{"299", "", "↓ -0.3 Velocidade#Enquanto estiver em uma sala hostil, cronometra sua velocidade para iniciar o efeito do My Little Unicorn"},
	{"300", "", "↑ +0.25 Velocidade#Infringe dano aos inimigos ao toca-los"},
	{"301", "", "+3 Corações de alma#Depois de ser atingido, ganhe redução de dano (-50% do dano recebido)"},
	{"302", "", "Quebra pedras ao tocá-las"},
	{"303", "", "Chance de obter invencibilidade ao ser atingido"},
	{"304", "", "+6 Moedas#+6 Bombas#+6 Chaves#Equilibra suas estatísticas (valor médio)#!!! Todas as estatísticas posteriores também serão afetadas"},
	{"305", "", "Lágrimas de veneno"},
	{"306", "", "↑ +0.2 Velocidade#Lágrimas penetrante"},
	{"307", "", "↑ +1 Saúde#+1 Chave#+1 Bomba#+1 Moeda#↑ +0.5 Dano#↑ +0.1 Velocidade#↑ +1.5 Alcance"},
	{"308", "", "Deixa um rastro azul que inflige dano aos inimigos (2 de dano ao contato)"},
	{"309", "", "↑ Lágrimas#Lágrimas com maio recuo"},
	{"310", "", "↑ +2X Dano#↓ -2X Lágrimas#↓ -0.5 Velocidade de disparo"},
	{"311", "", "Quando morto, renasce como Judas Negro"},
	{"312", "", "↑ +1 Saúde#Agora, todos os Corações Vermelhos curam 2 recipientes"},
	{"313", "", "Ignore o primeiro dano em todas as salas"},
	{"314", "", "↑ +1 Saúde#-0.4 Velocidade#Quebrar pedras ao tocá-las"},
	{"315", "", "Inimigos e pickups são atraídos pelas lágrimas"},
	{"316", "", "!!! Ao ser atingido, teleporta você para uma sala aleatória#Onda carregada de lágrimas"},
	{"317", "", "Lágrimas deixam rastro tóxico"},
	{"318", "", "Familiar que causa dano ao contato com o inimigo (3 de dano)"},
	{"319", "", "Salta pela sala#Atira em direção ao personagem#O dano dele é igual ao seu dano"},
	{"320", "", "Familiar controlável#2.5 de dano ao contato com inimigos"},
	{"321", "", "Corrente atrelada ao personagem#Danifica inimigos#Quebra pedras ao tocá-las"},
	{"322", "", "Copia o efeito de um de seus familiares"},
	{"323", "", "Atira lagrima ao redor do personagem"},
	{"324", "", "Teleporta você para#{{SecretRoom}}{{SuperSecretRoom}} Sala Secreta, Sala Error ou {{TreasureRoom}} Sala do Item"},
	{"325", "", "Corta sua cabeça#Controle seu corpo separadamente"},
	{"326", "", "Invencibilidade enquanto estiver ativando#!!! Qaundo não estiver com carga, você levará dano"},
	{"327", "", "Invencibilidade ao ser atingido se estiver com 1 Coração Vermelho e meio#Dá acesso a sala do baú"},
	{"328", "", "Danifica todos os inimigos da sala ao ser atingido se estiver com 1 Coração Vermelho e meio#Dá acesso a Dark Room"},
	{"329", "", "Lágrima controlável"},
	{"330", "", "↑ Altura da lágrima ((atrasso / 4) - 2)#↓ -80% Dano"},
	{"331", "", "Lágrimas teleguiada#Lágrimas ganham aura que danifica os inimigos#↑ +0.5 Dano#↑ +1.2 Alcance#↓ -0.3 Lágrimas#↓ -0.3 Velocidade de disparo#↑ +0.8 Altura da lágrima"},
	{"332", "", "Renascer como Lázaro com +1 item extra"},
	{"333", "", "Revela todo o mapa do andar"},
	{"334", "", "↑ +3 Saúde"},
	{"335", "", "+2 Corações de alma#Projéteis irão desviar do personagem"},
	{"336", "", "Lágrimas penetrantes#Lágrimas espectrais#↑ +0.25 Alcance#↓ -0.4 Velocidade de disparo#↑ +50% Tamanho da lágrima"},
	{"337", "", "Retarda ou acelera os inimigos"},
	{"338", "", "Boomerang arremessável#Atordoa os inimigos e causa 2x seu dano#Pode pegar itens"},
	{"339", "", "↑ +5.25 Lágrimas#↑ +0.16 Velocidade de disparo#+1 Coração negro#↑ +0.5 Altura da lágrima"},
	{"340", "", "↑ +0.3 Velocidade#↑ Tamanho do personagem reduzido#Gera uma pílula aleatória quando pego"},
	{"341", "", "↑ +0.7 lágrimas#↑ +0.16 Velocidade de Disparo"},
	{"342", "", "↑ +1 Saúde#↑ +0.7 lágrimas#↓ -0.16 Velocidade de Disparo"},
	{"343", "", "↑ +1 Sorte#+1 Coração de alma#+2 Chaves"},
	{"344", "", "+1 Coração negro#+3 Bombas"},
	{"345", "", "↑ +1 Dano#↑ +5.25 Alcance#↑ +0.5 Altura da lágrima"},
	{"346", "", "↑ +1 Saúde"},
	{"347", "", "!!! USO ÚNICO#Duplica todos os itens de pedestal ou consumíveis na sala atual"},
	{"348", "", "Copia o efeito da pílula que você está segurando no momento"},
	{"349", "", "50% de chance de largar uma moeda aleatória"},
	{"350", "", "No início de cada sala, todo inimigo recebe um efeito de veneno"},
	{"351", "", "Congele todos os inimigos na sala atual#Causa dano de envenenamento a qualquer inimigo próximo#Envia uma onda de espinhos pela sala#Pode ser usado para abrir salas secretas"},
	{"352", "", "!!! Reduz a sua saúde para meio coração#Dispara uma grande lágrima espectral penetrante ((seu dano + 1) x 10)"},
	{"353", "", "+5 Bombas#Bombas agora explodem em forma de cruz"},
	{"354", "", "↑ +1 Saúde#Gera um trinket aleatória"},
	{"355", "", "↑ +1.25 Alcance#↑ +1 Sorte#↑ +0.5 Altura da lágrima"},
	{"356", "", "Faz com que o seu item de ativação seja ativado duas vezes quando usado"},
	{"357", "", "Duplique seus familiares para a sala atual"},
	{"358", "", "Dispare 2 lágrimas de uma vez na diagonal#Lágrimas espectrais"},
	{"359", "", "↑ +1.5 Dano#Aumenta o recuo"},
	{"360", "", "Dispara lágrimas com mesmo dano e efeitos às suas"},
	{"361", "", "Dispara lágrimas com mesmo dano que às suas"},
	{"362", "", "Larga um pickup aleatório em algumas salas"},
	{"363", "", "Causa dano ao contato (7 de dano)#Atrai projeteis a às bloqueia#Bloquear uma lágrima pode soltar um Coração Eterno"},
	{"364", "", "Causa dano ao contato"},
	{"365", "", "Move-se pelas paredes e obstáculos na sala#Causa dano ao contato"},
	{"366", "", "+5 Bombas#Faz com que suas bombas explodam em 4 pequenas bombas"},
	{"367", "", "+5 Bombas#Quando uma bomba mata um inimigo gera aranhas azuis#Faz com que suas bombas grudem nos inimigos"},
	{"368", "", "Atirar em uma direção aumenta sua taxa de tiro"},
	{"369", "", "↑ +2.25 Alcance#↑ +1.5 Altura da lágrima#Suas lágrimas viajam através das paredes e reaparecem na parede oposta"},
	{"370", "", "↑ +0.7 Lágrimas#↑ +5.25 Alcance#↑ +0.5 Altura da lágrima#Gera 3 tipos de corações diferentes quando pego"},
	{"371", "", "!!! É afetado por itens#Gera 6 bombas trolls sempre que você for atingido"},
	{"372", "", "Chance de soltar uma bateria ou congelar todos os inimigos na sala#Chance de carregar em 1 seu item de ativação"},
	{"373", "", "↑ +12.5% Dano ou +25% para cada lágrima que atinge com sucesso um inimigo(max. +100%)"},
	{"374", "", "Chance aleatória de disparar uma lágrima sagrada"},
	{"375", "", "Chance de desviar projéteis#Imunidade a explosões"},
	{"376", "", "Resabastece itens da loja quando compra um item"},
	{"377", "", "As aranhas são inofensivas"},
	{"378", "", "Disparar lágrimas por 3 segundos solta um Butt Bomb"},
	{"379", "", "As lágrimas têm um hitbox muito maior#Lágrimas espectrais"},
	{"380", "", "+5 Moedas#Você pode abrir portas com moedas ao invés de chaves"},
	{"381", "", "↑ +0.7 Lágrimas#Fornece um item aleatório no início de sua próxima \"run\""},
	{"382", "", "Pode ser jogado em inimigos para capturá-los#No próximo uso, o inimigo capturado reaparecerá como companheiro"},
	{"383", "", "Detone qualquer lágrima na tela e faz com que cada uma se divida em mais 6 lágrimas que sairão em círculo"},
	{"384", "", "Danifica inimigos ao contato"},
	{"385", "", "!!! As moedas pegas não poderão ser usadas#Pega todas as moedas próximas#A cada 6 moedas ele sobe de nível, exceto o nível 4, que leva 12 moedas#LVL1: Apenas pega moedas#LVL2: Solta pickups aleatórios#LVL3: Atira lágrimas#LVL4: Não irá dispara lágrimas. Ele irá perseguir o inimigo e causar dano ao contato. Chance de gerar bombas"},
	{"386", "", "Troca todas as rochas por tipos de objetos aleatórios"},
	{"387", "", "Cria uma enorme aura de luz que retarda os inimigos dentro dela"},
	{"388", "", "Converte chaves em baús aleatórios"},
	{"389", "", "Solta uma runa aleatória a cada 3 salas"},
	{"390", "", "Atira lágrimas Sacred Heart"},
	{"391", "", "Toda vez que o personagem sofre dano, um efeito de charme é aplicado a todos os inimigos na sala"},
	{"392", "", "Dará a você um efeito aleatório de item zodíaco que muda após cada andar"},
	{"393", "", "Chance de envenenar inimigos#Cause dano por veneno ao contato#Inimigos envenenados têm chance de derrubar um Coração Negro ao morrerem"},
	{"394", "", "↑ +0.7 Lágrimas#↑ +0.3 Altura da lágrima#↑ +3.15 Alcance#Atira lágrimas direcionadas automaticamente a um alvo vermelho no chão controlado pelo jogador"},
	{"395", "", "{{Chargeable}} Carregável#Troca lágrimas pela capacidade de carregar e disparar um anel de laser que atravessa a sala"},
	{"396", "", "Cria até dois portais para viajar entre eles"},
	{"397", "", "↑ +0.5 Lágrimas#↑ +5.25 Alcance#↑ +0.16 Velocidade de disparo#↑ +0.5 Altura da lágrima#Agora, as lágrimas viajam diretamente para a frente seguindo um raio de luz"},
	{"398", "", "Agora, as lágrimas têm a chance de aplicar um efeito de encolhimento#Inimigos encolhidos podem ser mortos andando sobre eles"},
	{"399", "", "↑ +1 Dano#↑ +0.5 Altura da lágrima#Depois de disparar lágrimas por 3 segundos, cria um anel preto danificando os inimigos dentro dele# Inimigos mortos pelo anel preto têm chance de derrubar Corações Negros"},
	{"400", "", "Cria uma lança na sua frente (seu dano * 2 ao contato)"},
	{"401", "", "Lágrimas têm chance de se tornar bombas pegajosas"},
	{"402", "", "Agora, itens de pedestais serão escolhidos aleatóriamente#Ao pegá-los, também gerará 1-6 pickups aleatórios"},
	{"404", "", "Bloqueia projéteis#Se um projétil te atingir, ele peidará, causando dano aos inimigos próximos e encantando-os"},
	{"403", "", "Permite que você veja seu dano de lágrima e as barras de saúde de todos os inimigos#Inflige um efeito de status aleatório no contato#dropa baterias aleatoriamente"},
	{"405", "", "Aplica um efeito de status aleatório a todos os inimigos com os quais entra em contato."},
	{"406", "", "Troca suas estatísticas#Afetará apenas estatísticas de dano: Lágrimas, Alcance e Velocidade"},
	{"407", "", "↑ Aumente uma das estatísticas do personagem, dependendo da cor da aura ao seu redor#Quando sofrer dano, você receberá uma nova aura#Vermelha = +4 Dano#Azul = -4 Velocidade da lágrima#Amarelo = +0.5 Velocidade#Laranja = +7.5 Alcance"},
	{"408", "", "Quando você recebe dano, um anel preto aparecerá ao redor do personagem, causando dano ao contato#Inimigos mortos com ele têm a chance de derrubar um Coração Negro"},
	{"409", "", "+2 Corações Negro#Quando o personagem não tem Corações Vermelhos, ganhe Voo e Escudo"},
	{"410", "", "Chance de disparar um olho pela tela, que atira lágrimas na mesma direção que o personagem"},
	{"411", "", "↑ Cada vez que o personagem mata um inimigo, aumenta o dano temporário na sala atual (MAX: +5 de Dano após 9 mortes)"},
	{"412", "", "Depois de sofrer dano suficiente, o personagem ganha um familiar demônio permanente"},
	{"413", "", "Depois de pegar corações suficientes, o personagem ganha um familiar angelical permanente"},
	{"414", "", "!!! Apenas 1 item pode ser pego#2 itens surgem em cada {{TreasureRoom}} Salas do Itens"},
	{"415", "", "+2 Coração de Alma#↑ 2 x Dano se você não tiver nenhum espaço de Coração Vermelho vazio#Desativa para a sala atual quando receber dano"},
	{"416", "", "Permite carregar 2 cartas, pílulas ou runas"},
	{"417", "", "Voa ao redor da sala#Emite uma aura que causa dano de contato aos inimigos#↑ Enquanto estaver na aura, +50% multiplicador de dano"},
	{"418", "", "Dá a você um efeito de lágrima diferente a cada lágrima que você disparar"},
	{"419", "", "Teleporta você para outra sala aleatória que ainda não foi explorada#(Caso tudo esteja explorado) Hierarquia: Sala super Secreta, Loja, Sala do Item, Sala secreta, Sala de Maldição, Salas do sacrifício, Sala do Diabo ou Anjo, I Am Error"},
	{"420", "", "Andar em círculo gerará um símbolo de pentagrama no chão (10 de dano ao contato)"},
	{"421", "", "Aplica efeito de charme a qualquer inimigo à queima-roupa"},
	{"422", "", "Qualquer dano sofrido ou consumíveis usados na sala atual serão redefinidos para o estado anterior"},
	{"423", "", "Dá a Isaac uma grande auréola ao seu redor que causa dano de contato#Chance de bloquear projéteis"},
	{"424", "", "Todos os pickups têm chance de serem substituídos por um saco"},
	{"425", "", "Dá a você um cone de luz na sua frente que retarda qualquer inimigo dentro dele e suas lágrimas"},
	{"426", "", "Segue seu movimento com um atraso de 3 segundos#Causa dano de contato aos inimigos"},
	{"427", "", "Gera um barril TNT empurrável#Se usado uma segunda vez na mesma sala enquanto o último barril de TNT ainda estiver lá, ele explodirá"},
	{"428", "", "+4 Corações de alma#Restaura totalmente seus corações vermelho"},
	{"429", "", "Suas lágrimas têm a chance de solta moedas no chão ao acertar um inimigo"},
	{"430", "", "Segue seu padrão de movimento com atraso de 1 segundos#Dispara lágrimas em inimigos próximos que causam dano igual ao seu"},
	{"431", "", "Segue seu padrão de movimento com atraso de 2 segundos#As lágrimas do personagem que passam pelo bebê dobram e aumenta o dano"},
	{"432", "", "Bombas soltam pickups aleatórios quando explodem"},
	{"433", "", "Toda vez que você sofrer dano, aplicará um efeito de medo a todos os inimigos na sala e gerará um familiar que atacará por você.#Ele será morto se estiver muito danificado"},
	{"434", "", "Toda vez que você mata um inimigo, uma mosca azul é adicionada ao pote#Guarda até 20 moscas#Usar o item libera todas as moscas"},
	{"435", "", "Atira 4 lágrimas cruzadas"},
	{"436", "", "Ao sofrer dano, o leite é derramado (dano ao contato)"},
	{"437", "", "Reinica a sala atual#!!! Se usado em uma luta de Greed, ele pode trocar os itens da Loja"},
	{"438", "", "+1 Coração de alma#↑ +0.7 Lágrimas#↑ Reduz seu tamanho e sua hitbox"},
	{"439", "", "Solta um trinket aleatório#↑ +1 Sorte enquanto segura#Enquanto segurar o efeito dos trinkets é dobrado"},
	{"440", "", "Ao atirar, tem chance de disparar uma explosão de lágrimas#↓ -0.2 Velocidade#↓ -15 Alcance#↑ +2 Altura da lágrima"},
	{"441", "", "Atira um enorme laser Mega Satan por 15 segundos, mesmo entre salas e andares"},
	{"442", "", "!!! Enquanto estiver com 1 coração vermelho#!!! Não funciona com personagens sem corações vermelhos#↑ +1.5 Alcance#↑ +0.75 Lágrimas#↑ +0.2 Velocidade de disparo"},
	{"443", "", "Lança aleatoriamente lâminas de barbear que causam 400% de dano#↑ +0.4 Lágrimas"},
	{"444", "", "A cada 15 lágrimas disparadas, você dispara um conjunto de lágrimas#Cada lágrima no conjunto causa dano duplo"},
	{"445", "", "↑ +0.3 Dano#↑ +0.1 Velocidade#Um lobo uiva se você entrar em uma sala ao lado de uma sala secreta ou com um alçapão"},
	{"446", "", "Ao atirar, você obtém uma aura verde que envenena qualquer inimigo ao contato"},
	{"447", "", "Enquanto dispara, há chance de gerar uma nuvem de cocô"},
	{"448", "", "Ao receber dano, chance de obter ↑ +5 de alcance e deixar rastro de sangue"},
	{"449", "", "+1 Coração de alma#Projéteis inimigas têm chance de serem desviadas"},
	{"450", "", "A cada 20 lágrimas, dispara uma moeda que transforma os inimigos em ouro#Isso custa 1 moeda#Acertar um inimigo solta uma moeda"},
	{"451", "", "Solta uma carta ou runa aleatória#Dobra o efeito de cartas e runas"},
	{"452", "", "Cada vez que sofrer dano, atire 10 lágrimas ao seu redor"},
	{"453", "", "Lágrimas ósseas#As lágrimas se quebram em 1-3 fragmentos ósseos menores ao atingir qualquer coisa#↑ +1.5 Alcance#↑ +1 Altura da lágrima"},
	{"454", "", "Permite que o personagem carregue duas cartas, pílulas ou qualquer combinação de ambas ao mesmo tempo#Solta uma carta ou pílula aleatória"},
	{"455", "", "↑ +1.5 Alcance#Solta uma moeda da sorte"},
	{"456", "", "↑ +1 Saúde"},
	{"457", "", "+1 Coração de alma#Chance de ignorar danos"},
	{"459", "", "Deixa 1 trinket aleatório quando coletado, te dá um espaço de trinket extra"},
	{"458", "", "Solta um trinket ou pickup aleatório#+Espaço extra para trinkets"},
	{"460", "", "Chance de disparar lágrimas concussivas"},
	{"461", "", "Chance de disparar lágrimas lentas e pegajosas#Cria uma aranha ou mosca azul ao acertar um inimigos"},
	{"462", "", "↑ +1.5 Alcance#↑ +1 Altura da lágrima#Concede lágrimas penetrantes#Depois de atingir o primeiro inimigo, as lágrimas causam dano duplo e ganha um efeito de teleguiado"},
	{"463", "", "↑ +0.3 Dano#Chance de atirar lágriams que destroem pedras"},
	{"464", "", "+2 Corações de alma#Os inimigos Campeões largam os pickups com mais frequência"},
	{"465", "", "↑ -2 Atraso de lágrima#Permite disparar lágrimas na diagonal, disparando em duas direções"},
	{"466", "", "O primeiro inimigo morto na sala explodirá e envenenará todos os inimigos próximos"},
	{"467", "", "Causa dano baixo constante aos inimigos na direção em que o dedo aponta"},
	{"468", "", "Segue seu movimento atrasado em 3 segundos#Causa dano ao contato"},
	{"469", "", "Causa dano ao contato#Inimigos que tocam na nuvem podem ativar o efeito Crack The Sky"},
	{"470", "", "Salta pela sala (2 de dano ao contato)#Enquanto disparar lágrimas, ele para de se mover"},
	{"471", "", "Carrega seus tiros e solte-os como um efeito espingarda"},
	{"472", "", "Outros familiares o seguem#Enquanto disparar lágrimas, ele para de se mover#Teleportará de volta para você quando parar de atirar"},
	{"473", "", "Familiar que avança lentamente e danifica os inimigos em seu caminho"},
	{"474", "", "Bloqueia projéteis inimigos"},
	{"475", "", "!!! USO ÚNICO#!!! Mata você 3 segundos depois do uso#Causa 9.999.999 de dano a todos os inimigos"},
	{"476", "", "Duplica 1 pickup aleatório na sala atual"},
	{"477", "", "Quando usado, consuma qualquer item de pedestal na sala#Se é um item ativador: seu efeito será adicionado ao efeito de Vazio (Empilhamento dos efeitos)#Se é item passivo: pequena atualização de estatística para uma estatística aleatória"},
	{"478", "", "Congela todos os inimigos na sala até você atirar novamente#Tocar em um inimigo congelado irá prejudicar você com um status aleatório#Os inimigos descongelam depois de 30 segundos"},
	{"479", "", "Consome seu trinket e oferece o efeito permanentemente"},
	{"480", "", "Dobre a quantidade de moscas e aranhas azuis"},
	{"481", "", "!!! Pode te deixar confuso#Gira os sprites em 90 graus#Quando usado, ↑/↓ em um status aleatório#Efeito de lagrima aleatório para a sala atual"},
	{"482", "", "Mude para outro personagem aleatório#Remove o último item que você coletou"},
	{"483", "", "!!! USO ÚNICO#!!! Afeta o andar inteiro#Explode todos os objetos#Causa 200 de dano a todos os inimigos#Pode abrir o Boss Rush, Sala do Hush ou Salas secretas"},
	{"484", "", "Ao usar, afasta os inimigos e gera uma onda de pedras"},
	{"485", "", "50% Chance de dobrar todos os itens, consumíveis e baús no quarto#50% Chance de remover itens ou pickups na sala e gerar 1 moeda"},
	{"486", "", "Danifica o personagem sem receber o dano"},
	{"487", "", "Remove um espaço de Coração Vermelho e fornece ↑ +0.2 Dano, ↑ +0,5 Alcance e um Cube of Meat"},
	{"488", "", "Dá a você um efeito de item aleatório para a sala atual"},
	{"489", "", "Efeito de dado aleatório"},
	{"490", "", "!!! Uso único#Cria 2 itens aleatórios da sala atual"},
	{"491", "", "Solta uma pílula aleatória a cada 2 quartos#Usar pílulas causa dano aos inimigos"},
	{"492", "", "↑ +1 Sorte#Destaca a localização de salas secretas, pedras marcadas e alçapões"},
	{"493", "", "Para cada recipiente vazio de coração:#↑ +0.2 Dano"},
	{"494", "", "Lágrimas elétricas #Lágrimas geram 1-2 faíscas de eletricidade quando atingem algo"},
	{"495", "", "Chance de disparar fogo ao invés lágrimas"},
	{"496", "", "Chance de disparar agulhas#Agulhas matam inimigos normais instantaneamente"},
	{"497", "", "Fique camuflado ao entrar em uma sala até começar a atirar"},
	{"498", "", "!!! Ao entrar em um, o outro desaparece#Gera uma {{DevilRoom}} Sala do Diabo e uma {{AngelRoom}} Sala do Anjo ao mesmo tempo depois de um chefe"},
	{"499", "", "↑ 100% chance de encontrar a {{AngelRoom}} Sala do Anjo"},
	{"500", "", "Aleatoriamente deixa cair um saco"},
	{"501", "", "!!! Você perderar os espaços se não ter mais moedas#Dá a você um espaço de coração para cada 25 moedas(MAX: +4 espaços de coração com 99 moedas)#O Keeper ganhará Corações de moeda adicionais"},
	{"502", "", "Chance de atirar lagrimas que deixão um rastro (seu dano * 2 ao contato)"},
	{"503", "", "Chance de disparar lágrimas que matam inimigos instantaneamente"},
	{"504", "", "Cria uma torre de mosca que atira nos inimigos"},
	{"505", "", "Chance de gerar um inimigo encantado ao entrar em uma sala hostil"},
	{"506", "", "Lágrimas que causam sangramento (10% do dano total de pontos de vida dos inimigos a cada 5 segundos)"},
	{"507", "", "Danifique os inimigos com seu dano + 10% do dano igual à vida máxima do inimigo#Afeta todos os inimigos na sala#Chance de solta meio coração quando causa dano"},
	{"508", "", "Orbital que causa sangramento (10% do dano total de pontos de vida dos inimigos a cada 5 segundos)"},
	{"509", "", "Atira uma lágrima em uma direção aleatória a cada 2 segundos"},
	{"510", "", "Gera uma versão amigável do chefe Delirium branco para a sala atual"},
	{"511", "", "Orbita em torno de um inimigo aleatório até que ele morra#Causa dano de contato"},
	{"512", "", "Buraco negro jogável que suga todos os inimigos para dentro dele#Inimigos presos levam dano rápidamente"},
	{"513", "", "↑ +0.1 Dano#+1 Coração de alma#Chance aleatória de encantar ou amedrontar um inimigo#Chance de gerar um cocô de arco-íris ao receber dano"},
	{"514", "", "Causa 'lag' em inimigos aleatórios para intervalos de tempo aleatórios, paralisando-os"},
	{"515", "", "!!! Uso único#Cria um item aleatório da sala atual"},
	{"516", "", "Gera um Sprinkler que gira em círculo, borrifando lágrimas em todas as direções"},
	{"517", "", "+7 Bombas#Permite que você coloque rapidamente bombas no chão"},
	{"518", "", "Dá a você um familiar aleatório#Tem um efeito de lágrima aleatória#Será trocado novamente a cada andar"},
	{"519", "", "Um familiar que se transforma em outro familiar aleatório a cada 10 segundos"},
	{"520", "", "+1 de carga para seu item de ativação a cada 15 inimigos mortos"},
	{"521", "", "Quando usado, faz com que um item aleatório da {{Shop}} Loja ou {{DevilRoom}} Sala do Diabo fique gratuito"},
	{"522", "", "Projéteis inimigos próximos a você são mantidos no lugar por 3 segundos#Recarrega após 2 segundos"},
	{"523", "", "Quando usado, armazena todos os pickups da sala atual#A utilização novamente as colocará no chão"},
	{"524", "", "Lágrimas serão conectadas por raios de eletricidade"},
	{"525", "", "Ao ser danificado, irá gerar um orbital (MAX: 3 orbitais)#Esses orbitais podem ser destruídos se sofrerem muito dano"},
	{"526", "", "Dá a você um familiar Harbinger aleatório que muda a cada 10 segundos#Cada precursor se comporta de maneira diferente, com base em qualquer um dos 5 chefes de cavaleiro originais"},
	{"527", "", "Abre portas e baús#Traz itens, rouba da Loja ou Sala do Diabo, luta contra inimigos, explode e ativar placas de pressão"},
	{"528", "", "As lágrimas que atingem o prisma se dividirão em 4 novas lágrimas"},
	{"529", "", "Lágrimas se comportarão como bolas de bilhar"},
	{"530", "", "Concede uma recompensa se você matar inimigos na ordem em que estiverem marcados"},
	{"531", "", "Lágrimas voam em um arco#Lágrimas explodem em lágrimas menores com o impacto"},
	{"532", "", "As lágrimas diminuem enquanto viaja pela sala#Ao parar, eles explodem em lágrimas menores#As lágrimas podem ser disparadas em outras lágrimas, aumentando-as"},
	{"533", "", "Lágrimas são trocadas por feixes de luz"},
	{"534", "", "Permite manter 2 itens de ativação#Troque entre eles pressionando o botão de Soltar"},
	{"535", "", "+1 Coração de alma#Concede um escudo ao entrar na sala do chefe"},
	{"536", "", "!!! USO ÚNICO#Sacrifique 1-2 familiares para gerar um item de Acordo com o Diabo"},
	{"537", "", "+1 Pílula aleatória#Gera um rastro de medo#O tipo de rastro muda toda vez que o jogador usa uma pílula"},
	{"538", "", "Solta 3 trinkets aleatórios#Ao receber dano, tem a chance de consumir permanentemente o trinket atual"},
	{"539", "", "Ao receber dano, gera um inimigo amigavel"},
	{"540", "", "Lágrimas ricocheteiam no chão#As lágrimas causam dano por respingo a cada ricochete"},
	{"541", "", "+1 Coração de osso#Gera 3 corações vermelho"},
	{"542", "", "Reflete projéteis"},
	{"543", "", "Gera um cocô branco quando você recebe dano"},
	{"544", "", "Prego que fica na sua frente (dano ao contato)"},
	{"545", "", "Cria um osso orbital encantado para cada inimigo morto na sala atual"},
	{"546", "", "Concede uma aura que congela os inimigos no lugar"},
	{"547", "", "+1 Coração de osso#↑ +0.7 Lágrimas#Gera o trinket Mysterious Paper"},
	{"548", "", "Familiar bumerangue que causa 2x o seu dano"},
	{"549", "", "Substitui todos os seus espaços de coração vermelho por 6 Corações de Osso#Perder um Coração de Osso faz disparar Lágrimas de osso em todas as direções e concede ↑ +0.5 Lágrimas permanentemente"},
	{"550", "", "!!! Primeira parte da pá quebrada#O Pé da Mãe constantemente o ataca#O uso dela para o ataque para a sala atual#(Tente vencer o Boss Rush com ele)"},
	{"551", "", "!!! Segunda parte de uma pá quebrada"},
	{"552", "", "Cria um alçapão para o próximo andar#Desbloqueia algo legal"},
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "", "Solte moedas quando for atingido"},
	{"2", "", "Mais drops de cocô"},
	{"3", "", "-1 Carga para itens de ativação"},
	{"4", "", "Teleporta o personagem aleatoriamente, ao usar um item de ativação"},
	{"5", "", "Dobra a chance de aparecer inimigos campeões"},
	{"6", "", "Atrai moedas"},
	{"7", "", "Maiores chances de {{AngelRoom}} Sala do Anjo#Maior de achar a {{Collectible33}} The Bible"},
	{"8", "", "Chance de ativar o efeito Gamekid ao receber dano"},
	{"9", "", "Lágrimas pulsantes#Afeta a hitbox de lágrimas"},
	{"10", "", "Lágrimas se movem em ondas#↑ Lagrimas"},
	{"11", "", "Lágrimas se movem em espiral"},
	{"12", "", "Lágrimas maiores"},
	{"13", "", "Todos os itens de loja são gratuitos#!!! Ao comprar qualquer item de loja com 0 moedas, este trinket desaparece"},
	{"14", "", "Enquanto segura este trinket espinhos e rastros de sangue não o machucam"},
	{"15", "", "Destruir rochas gera moedas"},
	{"16", "", "O Pé da Mãe pisa nos inimigos a cada 60 segundos#!!! O Pé da Mãe também pode pisar no personagem!"},
	{"17", "", "Mais Corações Negros aparecerão"},
	{"18", "", "Mais Corações Eternos aparecerão"},
	{"19", "", "Abra baús sem usar chaves"},
	{"20", "", "!!! 3 Usos#Quando estiver com meio coração de saúde, gere um Coração Negro"},
	{"21", "", "Chance de ativar o efeito da Polaroid, The Negative, Missing Page ou Missing Poster"},
	{"22", "", "Diminui a chance de aparição de corações em 20%#Aumenta a chance de aparição de chaves#Pickups de corações se torna Corações Negros"},
	{"23", "", "Reaparecer como The Lost quando morrer em uma {{SacrificeRoom}} Sala do Sacrifício# Se não estiver desbloqueado, você reviverá fora da Sala do Sacrifício"},
	{"24", "", "O personagem peida ao pegar moedas"},
	{"25", "", "Chance de soltar cocô"},
	{"26", "", "As lágrimas se movem em padrões angulares"},
	{"27", "", "↑ +0.5 Velocidade de disparo"},
	{"28", "", "22% chance de reaparecer como Blue Baby"},
	{"29", "", "Gera uma mosca azul ao ser atingido"},
	{"30", "", "Atira lágrimas de veneno aleatoriamente"},
	{"31", "", "Atira lágrimas penetrantes aleatoriamente"},
	{"32", "", "Receba um efeito aleatório de cogumelo por sala#Pode revelar salas especiais no minimapa"},
	{"33", "", "Quando estiver com meio coração de saúde, você ganha o familiar Little Steven"},
	{"34", "", "Mais Corações Vermelhos surgem"},
	{"35", "", "↑ +2 Dano"},
	{"36", "", "Aparecem mais baús e chaves"},
	{"37", "", "↑ +0.15 Velocidade"},
	{"38", "", "Mais Corações de Alma aparecem"},
	{"39", "", "↑ Lágrimas"},
	{"40", "", "↑ Chance de ganhar +1.8 Dano ao ser atingido enquanto estiver na sala"},
	{"41", "", "!!! Remove o trinket The Tick#Maior chance aparecer bombas"},
	{"42", "", "↑ +1 Sorte"},
	{"43", "", "Quando sofrer dano de meio coração ou menor, teleporta o personagem para a última sala visitada"},
	{"44", "", "Aparecem mais pílulas"},
	{"45", "", "Aparecem mais cartas"},
	{"46", "", "Chance de curar meio coração depois de matar todos os inimigos de uma sala"},
	{"47", "", "<unused>"},
	{"48", "", "Ao ser atingido, chance de desencadear o efeito Necronomicon"},
	{"49", "", "Gera meio coração vermelho ao pegar moedas"},
	{"50", "", "Gera bombas ao pegar moedas"},
	{"51", "", "Gera chaves ao pegar moedas"},
	{"52", "", "Chance de gerar moedas extras ao pegar moedas"},
	{"53", "", "!!! Só consiguirá soltá-lo com o trinket Match Stick#-15% da vida dos Chefes#Cura 1 coração vermelho ao entrar na {{BossRoom}} Sala do Chefe"},
	{"54", "", "Concede um familiar com lágrimas penetrantes enquanto segurar"},
	{"55", "", "Consiga um Coração Eterno ao iniciar um novo andar"},
	{"56", "", "Reduz os preços de todas itens do Arcodo com o Diabo para 2 espaços de coração em 1"},
	{"57", "", "Move ao redor da sala#Atira na mesma direção que o personagem"},
	{"58", "", "↑ Chance de +0.5 Dano ao matar um inimigo na sala atual"},
	{"59", "", "25% de chance de revelar ícones do mapa no início do novo andar"},
	{"60", "", "Chance de gerar um pássaro morto ao matar um inimigo (2 de dano ao contato)"},
	{"61", "", "Transforma todos os baús em baús vermelhos"},
	{"62", "", "Pedras marcadas e pedras com Crawlspace a cada 10 segundos"},
	{"63", "", "Transforma bombas trolls em bombas coletáveis"},
	{"64", "", "Efeito de minhoca aleatória"},
	{"65", "", "↑ Duplica seu alcance#↓ -50% Altura das lágrimas"},
	{"66", "", "↓ -0.4 Velocidade de disparo#↑ +4 Alcance"},
	{"67", "", "Chance de ativar o efeito do D6, D20, D8 ou D12"},
	{"68", "", "Ímã para pickup e inimigos"},
	{"69", "", "Camufla o jogador aleatoriamente por alguns segundos#Confunde inimigos"},
	{"70", "", "Chance de gerar uma aranha enquanto estiver em uma sala hostil"},
	{"71", "", "Bombas deixam poça venenosa que causa dano aos inimigos ao contato"},
	{"72", "", "Solta mais baterias#5% de chance de adicionar 1 carga para o item ativador atual ao limpar a sala"},
	{"73", "", "Bombas explosivas podem soltar bombas coletáveis"},
	{"74", "", "Aumenta a chance de encontrar um Crawlspace quando quebrar rochas"},
	{"75", "", "Efeito de trinket aleatório em todas as salas"},
	{"76", "", "50/50 chance de encontrar pickup extras, inimigo ou não recebe nada em baús"},
	{"77", "", "Aumenta o recuo das lágrimas"},
	{"78", "", "Aumenta a duração dos efeitos em inimigos"},
	{"79", "", "25% de chance de ao usar pílulas/cartas solta uma cópia dela no chão"},
	{"80", "", "↑ +0.2 Dano para cada item maligno que o personagem possui"},
	{"81", "", "Invencibilidade dura mais tempo"},
	{"82", "", "+15% de chance de ter 2 itens na {{TreasureRoom}} Sala do Item nos próximos andares#Você pode pegar apenas um"},
	{"83", "", "Abra {{Shop}} Lojas sem usar chaves"},
	{"84", "", "Greed e Super Greed não aparecem mais em {{Shop}} Lojas"},
	{"85", "", "Usar uma Máquina de Doação pode curá-lo ou gerar um mendigo"},
	{"86", "", "Destruir cocô gera uma mosca azul"},
	{"87", "", "Cura metade de um coração quando você usa chaves#Meio coração aparecem como corações cheios"},
	{"88", "", "Chance muito baixa de itens de ativação nas {{TreasureRoom}} Sala do Item"},
	{"89", "", "Familiares se aproximam do personagem"},
	{"90", "", "Cocô explode quando destruído"},
	{"91", "", "Aumenta a chance de o cocô preto aparecer#Chance de gerar um Coração Negro quando o cocô preto é destruido"},
	{"92", "", "↑ Aumento de estatísticas de seus itens são 33% mais eficazes#↑ +0.2 Lagrimas#↑ +1 Velocidade da lágrima"},
	{"93", "", "Moscas Inimigas agora são amigáveis"},
	{"94", "", "O dobro de moscas e aranhas serão geradas"},
	{"95", "", "Atire lágrimas de veneno aleatoriamente"},
	{"96", "", "As lágrimas se movem rapidamente em um padrão espiral#↑ +4 Alcance"},
	{"97", "", "!!! Este processo pode acontecer apenas 2 vezes antes que o familiar seja destruído#Quando atingido, há uma pequena chance de ganhar o familiar Tonsil#Bloqueia os tiros do inimigo"},
	{"98", "", "Chance de atirar lágrimas venenosas"},
	{"99", "", "Chance de atirar lágrimas saltitantes"},
	{"100", "", "!!! Enquanto estiver com o item totalmente carregado:#↑ +0.25 Velocidade#↑ +0.75 Alcance#↑ +0.2 Lagrimas#↑ +0.10 Velocidade de Disparo#↑ +0.5 Dano#↑ +1 Sorte"},
	{"101", "", "!!! Enquanto estiver com o item totalmente descarregado:#↑ +0.5 Velocidade#↑ +1.5 Alcance#↑ +0.4 Lagrimas#↑ +0.3 Velocidade de Disparo#↑ +1.5 Dano#↑ +2 Sorte"},
	{"102", "", "+1 Sala secreta extra por andar"},
	{"103", "", "!!! Quando o número de moedas, chaves e bombas são iguais:#Transforma metade dos consumíveis em consumíveis duplos"},
	{"104", "", "!!! É destruído depois#Chance de gerar um item de pedestal ao ser atingido"},
	{"105", "", "!!! É destruído depois#Chance de gerar o item {{Collectible22}} Lunch ao ser atingido"},
	{"106", "", "Aumenta o raio de qualquer fluido que você produz"},
	{"107", "", "O dano recebido ignora os Corações de Alma/Negros, fazendo com que seus espaços de Coração Vermelhos se esgote primeiro"},
	{"108", "", "!!!É destruído depois#Chance de soltar um pickup ou trinket ao ser atingido por uma explosão"},
	{"109", "", "Impede que os familiares do personagem se movam"},
	{"110", "", "As {{Shop}} Lojas agora aparecerão no Womb"},
	{"111", "", "{{TreasureRoom}} Salas de Itens agora aparecem no Womb"},
	{"112", "", "As máquinas de reabastecimento sempre aparecem nas {{TreasureRoom}} Sala do Item"},
	{"113", "", "Gera uma mosca explosiva de ataque ao entrar em uma sala hostil"},
	{"114", "", "Gera uma mosca venenosa de ataque ao entrar em uma sala hostil"},
	{"115", "", "Gera uma mosca de ataque de lentidão ao entrar em uma sala hostil"},
	{"116", "", "Gera uma mosca de ataque que causa quatro vezes o seu dano ao entrar em uma sala hostil"},
	{"117", "", "Gera entre 2-5 moscas de ataque que causam o dobro do seu dano ao entrar numa sala hostil"},
	{"118", "", "Ao matar um inimigo existe uma pequena chance do personagem ganhar a habilidade de voar para a sala atual"},
	{"119", "", "Cura meio coração vermelho depois de ir para o próximo andar"},
	{"120", "", "Recarrega totalmente seu item ativador no início de uma batalha contra um chefe"},
	{"121", "", "Protege você do primeiro dano que recebe em cada andar"},
	{"122", "", "Ao usar o item de ativação deixará cair em um pedestal#Existe uma pequena chance de soltar um de seus itens passivos#Itens de ativação de uso único poderão ser consumidos"},
	{"123", "", "Faz com que os chefes Anjos deixem itens normais em vez de peças da chave"},
	{"124", "", "A última porta que você usou permanece aberta"},
	{"125", "", "Conecta seus familiares com raios de eletricidade"},
	{"126", "", "Cria uma mosca azul ao pegar uma moeda"},
	{"127", "", "Concede aos seus familiares tiros teleguiados"},
	{"128", "", "2% de chance de ganhar um Coração de osso ao receber dano"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "", "Teleporta você de volta ao início"},
	{"2", "", "Lágrimas teleguiadas para o sala atual"},
	{"3", "", "Faz com que o Pé da Mãe pise em um inimigo (300 de dano)"},
	{"4", "", "↑ +2.35 Dano#↑ +0.3 Velocidade na sala atual"},
	{"5", "", "Teleporta você para a {{BossRoom}} Sala do Chefe"},
	{"6", "", "Solta 2 Corações de Alma"},
	{"7", "", "Solta 2 Corações Vermelhos"},
	{"8", "", "Invencibilidade#Dano de contato por 6 segundos"},
	{"9", "", "Gera 1 bomba, 1 chave, 1 moeda, 1 coração"},
	{"10", "", "Teleporta você para a {{Shop}} Loja"},
	{"11", "", "Cria uma máquina caça-níqueis ou Fortuna"},
	{"12", "", "↑ +1 Saúde#↑ +0.3 Dano#↑ +0.3 Velocidade na sala atual"},
	{"13", "", "Concede Voo para a sala atual"},
	{"14", "", "Causa 40 de dano a todos os inimigos na sala"},
	{"15", "", "Cria uma máquina de doação de sangue"},
	{"16", "", "↑ +2 Dano na sala atual"},
	{"17", "", "Gera bombas trolls"},
	{"18", "", "Teleporta você para a {{TreasureRoom}} Sala do Item"},
	{"19", "", "Teleporta você para a {{SecretRoom}} Sala Secreta"},
	{"20", "", "Causa 100 de dano a todos os inimigos#Vida completa#Revela o mapa"},
	{"21", "", "Gera um Mendigo"},
	{"22", "", "Revela o mapa inteiro e mostra todos os tipos de salas"},
	{"23", "", "Duplique suas bombas"},
	{"24", "", "Duplique suas moedas"},
	{"25", "", "Duplique suas chaves"},
	{"26", "", "!!! Só tem efeito curativo#Duplique seus corações vermelhos"},
	{"27", "", "Transforma todos os pickups em bombas"},
	{"28", "", "Transforma todos os pickups em moedas"},
	{"29", "", "Transforma todos os pickups em chaves"},
	{"30", "", "Transforma todos os pickups em corações"},
	{"31", "", "Teleporta você para {{DevilRoom}} Sala do Diabo ou {{AngelRoom}} Sala do Anjo"},
	{"32", "", "Destrua todas as pedras na sala"},
	{"33", "", "Duplique todos os pickups na sala"},
	{"34", "", "Cria um alçapão para o próximo andar"},
	{"35", "", "+1 coração de alma#Remove os efeitos de maldição"},
	{"36", "", "Revela o mapa completo no andar atual"},
	{"37", "", "Trocar todos os itens do pedestal"},
	{"38", "", "Invocar 3 aranhas azuis e 3 moscas azuis"},
	{"39", "", "Invencibilidade por 30 segundos"},
	{"40", "", "Efeito de rúna aleatória"},
	{"41", "", "Causa 40 de dano a todos os inimigos#Estatísticas aleatórias para todos os itens de pedestal na sala"},
	{"42", "", "Lança uma carta para matar qualquer coisa em seu caminho#Abre todas as portas (não funciona com a porta do Mega Satan)"},
	{"43", "", "Remove o preço de todos os itens da {{Shop}} Loja atual ou transações com o Diabo, tudo fica de graça"},
	{"44", "", "Exibe dicas \"úteis\" sobre o uso"},
	{"45", "", "Preenche toda a sala com cocô"},
	{"46", "", "Mata o personagem e gera muitos pickups, itens e/ou baús na mesma sala"},
	{"47", "", "Abra todas as portas na sala atual"},
	{"48", "", "Ativa seu item de ativação gratuitamente"},
	{"49", "", "Trocar itens e pickups na sala atual"},
	{"50", "", "Mãos da Mãe descem e agarram um inimigo"},
	{"51", "", "Concede o efeito Holy Mantle por uma sala#(Proteção contra dano)#25% de chance de gerar outro Holy Card"},
	{"52", "", "!!! Efeito dura para a sala atual#↑ +7 Dano#↑ +30 Alcance#Aumenta seu tamanho#Quebra pedras ao contato"},
	{"53", "", "Gera 3 cartas aleatórias quando usadas"},
	{"54", "", "Diminui a velocidade dos inimigos#↓ -0.5 Velocidade#↓ -1 Velocidade de disparo"},
}


---------- Pills ----------

EID.descriptions[languageCode].unidentifiedPill = "Pílula não identificada"

EID.descriptions[languageCode].pills={
	{"0", "", "Cria uma nuvem de gás"},
	{"1", "", "Causa 1 coração de dano"},
	{"2", "", "+2 Corações de Alma"},
	{"3", "", "Trocar o número de bombas pelo número de chaves"},
	{"4", "", "Solta 5 bombas trolls"},
	{"5", "", "Saúde Máxima"},
	{"6", "", "↓ Saúde"},
	{"7", "", "↑ Saúde"},
	{"8", "", "Sem efeito"},
	{"9", "", "Consumir 3 pílulas de puberty garantirá a transformação de um adulto."},
	{"10", "", "Concede 1 mosca orbital"},
	{"11", "", "↓ -2 Alcance"},
	{"12", "", "↑ +2.5 Alcance"},
	{"13", "", "↓ -0.12 Velocidade"},
	{"14", "", "↑ +0.15 Velocidade"},
	{"15", "", "↓ -0.28 Lágrimas"},
	{"16", "", "↑ +0.35 Lágrimas"},
	{"17", "", "↓ -1 Sorte"},
	{"18", "", "↑ +1 Sorte"},
	{"19", "", "Teletransporta você para uma sala aleatória"},
	{"20", "", "Recarregue seu item ativador#Solta 1-2 bateria"},
	{"21", "", "Drena todos os espaços de corações, exceto um#Gera 1-4 Corações Vermelhos"},
	{"22", "", "Você não pode se mover por alguns segundos"},
	{"23", "", "Abra entradas de salas secretas no andar atual"},
	{"24", "", "Encanta todos os inimigos no quarto"},
	{"25", "", "Oculta o mapa do andar"},
	{"26", "", "Cria uma grande poça de limonada no chão que causa dano aos inimigos"},
	{"27", "", "Atire na diagonal por 60 segundos"},
	{"28", "", "Tome apenas meio coração de dano para a sala atual"},
	{"29", "", "Danos sofridos na sala atual leva um coração inteiro"},
	{"30", "", "Gera cocô enquanto caminha por 2 segundos"},
	{"31", "", "Curse Of The Maze para andar atual"},
	{"32", "", "Aumeta seu tamanho#Não afeta seu hitbox"},
	{"33", "", "Diminue seu tamanho#Seu hitbox fica menor"},
	{"34", "", "Gera 1 aranha azul por cocô na sala"},
	{"35", "", "Gera 1 aranha azul por inimigo na sala#Gera 1-3 aranhas azuis quando nenhum inimigo está na sala"},
	{"36", "", "Curto efeito invencibilidade"},
	{"37", "", "Pixeliza a tela por 30 segundos"},
	{"38", "", "Gera 3 moscas amigáveis"},
	{"39", "", "Gera uma poça de fluido escorregadio"},
	{"40", "", "Gera uma poça de fluido de lentidão"},
	{"41", "", "Atrassa todos os inimigos na sala"},
	{"42", "", "Acelere todos os inimigos na sala"},
	{"43", "", "Consumir trinket atual e obter seu efeito permanentemente"},
	{"44", "", "Atira uma lágrima explosiva"},
	{"45", "", "Curto efeito de invencibilidade"},
	{"46", "", "Gera a última pílula usada"},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Pagamento da próxima sala de sacrifício]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "50% Chance de 1 moeda#100% Chance de 1 bomba se matar o chefe em menos de 1 minuto em Basement 1"},
	{"2", "", "50% Chance de 1 moeda#100% Chance de 1 bomba se matar o chefe em menos de 1 minuto em Basement 1"},
	{"3", "", "67% Chance de aumentar a chance da {{AngelRoom}} Sala dos Anjos"},
	{"4", "", "50% Chance de 1 baú aleatório"},
	{"5", "", "33% Chance de 3 moedas#67% Chance de aumentar a chance de Sala do Anjo"},
	{"6", "", "33% Chance de se teletransportar para a {{AngelRoom}} Sala do Anjo ou do Diabo quando sua porta já foi gerada neste andar#67% de chance de 1 baú aleatório"},
	{"7", "", "33% Chance de 1 item aleatório da {{AngelRoom}} Sala dos Anjo#67% Chance de 1 Coração de Alma"},
	{"8", "", "100% Chance de 7 bombas trolls"},
	{"9", "", "100% Chance do chefe Uriel aparecer"},
	{"10", "", "50% Chance de 7 Corações da Alma#50% de chance de 30 moedas"},
	{"11", "", "100% Chance do chefe Gabriel aparecer"},
	{"12", "", "50% Chance de teletransportar para a Dark Room"},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Efeito do Dado]"

EID.descriptions[languageCode].dice={
	{"1", "", "!!! Afeta apenas itens passivos#Troca todos os seus itens"},
	{"2", "", "Troca todos os pickups na sala"},
	{"3", "", "Troca todos os pickups em todo o piso"},
	{"4", "", "!!! Não afeta as ofertas do demônio#Troca todos os itens de pedestal no andar"},
	{"5", "", "Troca e reinicia o andar atual"},
	{"6", "", "Troca todos os seus itens#Troca todos os itens e pickups no andar"},
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Beelzebub",		-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Yes Mother?",		-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}

---------- MISC ----------

EID.descriptions[languageCode].VoidText = "Se absorvido, ganha:"
EID.descriptions[languageCode].VoidNames = {"Velocidade", "Lágrimas", "Dano", "Alcance", "Velocidade de Disparo", "Sorte"}

EID.descriptions[languageCode].CollectionPageInfo = "Este item precisa ser pego para a página de coleção!"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Nome do Objeto Demo",
	DemoObjectTransformation = "Transformação Demo",
	DemoObjectText = "Este texto está em português brasileiro#Uma descrição muito legal e longa para simular quebras de linha causadas pela largura da caixa de texto do EID!#\1 Esta também é uma linha legal#Esta linha ama você {{Heart}}",
}
