------------------------------------------------------------------
-----  Basic Spanish descriptions based on Platinumgod.co.uk -----
------------------------------------------------------------------

-- FORMAT: Item ID | Name| Description
-- '#' = starts new line of text

-- Spanish letters:
-- print("áéíóúüñÁÉÍÓÚÜÑ¿¡ |")

--Special character markup:
-- ↑ = Up Arrow   |  ↓ = Down Arrow    | ! = Warning !   | \6 = health   |  \5 Key   |   \015 = Coin   |  \8↑89 = Bomb

-- init spa table
EID.descriptions["spa"] = {}
EID.descriptions["spa"].custom = {} -- table for custom entity descriptions

EID.descriptions["spa"].collectibles={
{"1", "The Sad Onion", "↑ +0,7 de lágrimas"},
{"2", "The Inner Eye", "Disparo triple#↓ Menos lágrimas"},
{"3", "Spoon Bender", "Lágrimas teledirigidas"},
{"4", "Cricket's Head", "↑ +0,5 de daño#↑ +50% de multiplicador de daño #+Empuje"},
{"5", "My Reflection", "Otorga un efecto boomerang a las lágrimas#↑ +1,5 de rango#↑ +0,6 de velocidad de disparo#↑ +1 de tamaño de lágrima"},
{"6", "Number One", "↑ +1,5 de lágrimas#↓ -15,78 de rango#↑ +0,45 de tamaño de lágrima"},
{"7", "Blood of the Martyr", "↑ +1,0 de daño#↑ +50% si tienes El libro de Belial (Book of Belial)"},
{"8", "Brother Bobby", "Familiar de lágrimas normales"},
{"9", "Skatole", "Todas las moscas enemigas son aliadas"},
{"10", "Halo of Flies", "+2 moscas orbitales"},
{"11", "1up!", "↑ +1 de vida#Reaparece con la vida al completo"},
{"12", "Magic Mushroom", "↑ +1 de vida#↑ +0,3 de daño#↑ +50% de multiplicador de daño#↑ +5,25 de rango#↑ +0,3 de velocidad#↑ +0,5 de tamaño de lágrima#¡Vida al completo!"},
{"13", "The Virus", "Toque venenoso#↓ -0,1 de velocidad#Los enemigos pueden soltar corazones negros al morir si están envenenados"},
{"14", "Roid Rage", "↑ +0,6 de velocidad#↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
{"15", "<3", "↑ +1 de vida#Vida al completo"},
{"16", "Raw Liver", "↑ +2 de vida#Vida al completo"},
{"17", "Skeleton Key", "+99 llaves"},
{"18", "A Dollar", "+99 monedas"},
{"19", "Boom!", "+10 bombas"},
{"20", "Transcendence", "¡Vuela!"},
{"21", "The Compass", "Muestra todos los iconos del mapa#No muestra el plano del mapa"},
{"22", "Lunch", "↑ +1 de vida"},
{"23", "Dinner", "↑ +1 de vida"},
{"24", "Dessert", "↑ +1 de vida"},
{"25", "Breakfast", "↑ +1 de vida"},
{"26", "Rotten Meat", "↑ +1 de vida"},
{"27", "Wooden Spoon", "↑ +0,3 de velocidad"},
{"28", "The Belt", "↑ +0,3 de velocidad"},
{"29", "Mom's Underwear", "↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
{"30", "Mom's Heels", "↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
{"31", "Mom's Lipstick", "↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
{"32", "Wire Coat Hanger", "↑ +0,7 de lágrimas"},
{"33", "The Bible", "Vuela en la habitación actual#Mata el Pie de Mamá y el Corazón de Mamá al instante#!!! Te mata al usarlo contra Satán"},
{"34", "The Book of Belial", "↑ +2 de daño#↑ +12.5% de probabilidad de Pacto con el Diablo#↑ +50% de multiplicador de daño si tienes Blood of the Martyr (Sangre del mártir)"},
{"35", "The Necronomicon", "Inflige 40 de daño a todo en la habitación"},
{"36", "The Poop", "Genera una caca en el suelo#Se puede poner al lado de una fosa y destruirla para hacer un puente"},
{"37", "Mr. Boom", "Genera una gran bomba bajo el jugador que inflige 110 de daño"},
{"38", "Tammy's Head", "Dispara 10 lágrimas en círculo alrededor de Isaac"},
{"39", "Mom's Bra", "Congela a todos los enemigos de la habitación actual durante 4 secs"},
{"40", "Kamikaze!", "Provoca una explosión en la ubicación del jugador"},
{"41", "Mom's Pad", "Asusta a todos los enemigos de la habitación actual durante 5 secs"},
{"42", "Bob's Rotten Head", "Bomba venenosa lanzable"},
{"43", "", "<No existe el objeto>"},
{"44", "Teleport!", "Teletransporta a Isaac a una habitación aleatoria"},
{"45", "Yum Heart", "Cura 1 corazón rojo"},
{"46", "Lucky Foot", "↑ +1,0 de suerte#Más probabilidad de ganar al apostar"},
{"47", "Doctor's Remote", "¡Epic Fetus (Feto épico) a la carta!#Ataques aéreos dirigidos"},
{"48", "Cupid's Arrow", "Lágrimas penetrantes"},
{"49", "Shoop da Whoop!", "Rayo de Brimstone (azufre) con gran daño"},
{"50", "Steven", "↑ +1 de daño"},
{"51", "Pentagram", "↑ +1,0 de daño#↑ +10% probabilidad de Pacto con el Diablo"},
{"52", "Dr. Fetus", "¡Lágrimas bomba!"},
{"53", "Magneto", "Acerca los recolectables al jugador"},
{"54", "Treasure Map", "Muestra el plano del mapa"},
{"55", "Mom's Eye", "Posibilidad aleatoria de disparar una lágrima hacia atrás"},
{"56", "Lemon Mishap", "Crea una piscina de limonada"},
{"57", "Distant Admiration", "Mosca orbital de medio alcance"},
{"58", "Book of Shadows", "Invencibilidad durante 10 secs"},
{"59", "", "<No existe el objeto>"},
{"60", "The Ladder", "Camina sobre fosas de 1 cuadrado de distancia"},
{"61", "", "<No existe el objeto>"},
{"62", "Charm of the Vampire", "Cura medio corazón cada 13 enemigos asesinados"},
{"63", "The Battery", "El objeto activable se puede cargar el doble"},
{"64", "Steam Sale", "-50% en la compra de objetos#Tener dos hace que todo sea gratis"},
{"65", "Anarchist Cookbook", "Genera 6 bombas troll en lugares aleatorios de la habitación"},
{"66", "The Hourglass", "Ralentiza a los enemigos durante 8 secs"},
{"67", "Sister Maggy", "Familiar de lágrimas normales"},
{"68", "Technology", "Las lágrimas son láseres"},
{"69", "Chocolate Milk", "Carga las lágrimas"},
{"70", "Growth Hormones", "↑ +1,0 de daño#↑ +0,4 de velocidad"},
{"71", "Mini Mush", "↑ +0,3 de velocidad#↓ -4,25 de rango*#↑ +1,5 de tamaño de lágrima*#(*Ambas aumentan un poco el rango)"},
{"72", "Rosary", "+3 corazones de alma#La Biblia es más común"},
{"73", "Cube of Meat", "NVL1: Orbital#NVL2: Orbital que dispara#NVL3: Meat boy NVL 1#NVL4: Meat boy NVL 2"},
{"74", "A Quarter", "+25 monedas"},
{"75", "PHD", "Mejores píldoras# +1 píldora"},
{"76", "X-Ray Vision", "Muestra las salas secretas"},
{"77", "My Little Unicorn", "Invencibilidad + daño por contacto"},
{"78", "Book of Revelations", "+1 corazón de alma# Más probabilidad de que aparezcan jinetes#↑ +17,5% probabilidad de Pacto con el Diablo"},
{"79", "The Mark", "↑ +1,0 de daño#↑ +0,2 de velocidad#+1 corazón de alma"},
{"80", "The Pact", "↑ +0,5 de daño#↑ +0,7 de lágrimas#+2 corazones de alma"},
{"81", "Dead Cat", "↑ +9 vidas#Revive con 1 corazón"},
{"82", "Lord of the Pit", "Vuela#↑ +0,3 de velocidad"},
{"83", "The Nail", "+1 corazón de alma#↑ +0,7 de daño#↓ -0,18 de velocidad#Rompe rocas"},
{"84", "We Need To Go Deeper!", "Genera una trampilla para saltar el nivel#10% de probabilidad de que se abra una trampilla a una planta secreta"},
{"85", "Deck of Cards", "Genera 1 carta"},
{"86", "Monstro's Tooth", "Invoca a Monstro, y este daña a un enemigo"},
{"87", "Loki's Horns", "Posibilidad de disparar en 4 direcciones"},
{"88", "Little Chubby", "Familiar que carga hacia delante"},
{"89", "Spider Bite", "Ralentiza a los enemigos"},
{"90", "The Small Rock", "↑ +1 de daño#↑ +0,2 de lágrimas#↑ -0,2 de velocidad"},
{"91", "Spelunker Hat", "Muestra lo que hay detrás de las puertas"},
{"92", "Super Bandage", "↑ +1 de vida#+2 corazones de alma"},
{"93", "The Gamekid", "Invencibilidad +daño por contacto#Comerse un enemigo recupera vida"},
{"94", "Sack of Pennies", "Suelta una moneda aleatoria cada 2 habitaciones"},
{"95", "Robo-Baby", "Lágrimas láser"},
{"96", "Little C.H.A.D.", "Suelta medio corazón cada 3 habitaciones"},
{"97", "The Book of Sin", "Genera un recolectable aleatorio"},
{"98", "The Relic", "Suelta 1 corazón de alma cada 4 habitaciones"},
{"99", "Little Gish", "Lágrimas ralentizantes"},
{"100", "Little Steven", "Lágrimas teledirigidas"},
{"101", "The Halo", "↑ + 1 de vida#↑ +0,3 de daño#↑ +0,2 de lágrimas#↑ +0,25 de rango#↑ +0,3 de velocidad#↑ +0,5 de tamaño de lágrima"},
{"102", "Mom's Bottle of Pills", "Genera 1 píldora"},
{"103", "The Common Cold", "Lágrimas venenosas(aleatorio)"},
{"104", "The Parasite", "Las lágrimas se rompen al chocar"},
{"105", "The D6", "Cambia los pedestales de la habitación actual"},
{"106", "Mr. Mega", "↑ x2.25 el daño de bomba #+5 bombas"},
{"107", "The Pinking Shears", "Vuela#Tu cuerpo ataca a los enemigos"},
{"108", "The Wafer", "Todo el daño recibido se reduce a medio corazón"},
{"109", "Money = Power", "↑ +0,04 de daño por cada moneda que tengas"},
{"110", "Mom's Contacts", "Lágrimas congelantes#↑ +0,25 de rango"},
{"111", "The Bean", "Pedo venenoso"},
{"112", "Guardian Angel", "Orbital#Acelera todos los orbitales"},
{"113", "Demon Baby", "Torreta que dispara automáticamente"},
{"114", "Mom's Knife", "Cuchillo controlable"},
{"115", "Ouija Board", "Lágrimas espectrales"},
{"116", "9 Volt", "-1 carga para los objetos activables#Carga al completo el objeto actual"},
{"117", "Dead Bird", "Cuando te golpean genera un pájaro "},
{"118", "Brimstone", "Carga un chorro de sangre que inflige daño constante"},
{"119", "Blood Bag", "↑ +1 de vida#↑ +0,3 de velocidad#Cura 5 corazones"},
{"120", "Odd Mushroom", "↑ +1,7 de lágrimas#↑ +0,3 de velocidad#↓ Menos daño"},
{"121", "Odd Mushroom", "↑ +1 contenedor de corazon vacío#↑ +0,3 de daño#↑ +0,25 de rango#↓ -0,1 de velocidad#↑ +0,5 de tamaño de lágrima"},
{"122", "Whore of Babylon", "!!! Al tener medio corazón:#↑ +1,5 de daño#↑ +0,3 de velocidad"},
{"123", "Monster Manual", "Familiar aleatorio en la habitación actual"},
{"124", "Dead Sea Scrolls", "Efecto de objeto activo aleatorio"},
{"125", "Bobby-Bomb", "Bombas teledirigidas#+5 Bombas"},
{"126", "Razor Blade", "↑ +1,2 de daño#↓ -1 de vida"},
{"127", "Forget Me Now", "!!! UN SOLO USO !#Cambia toda la planta"},
{"128", "Forever alone", "Mosca orbital de larga distancia"},
{"129", "Bucket of Lard", "↑ +2 de vida#↓ -0,2 de velocidad#Cura medio corazón"},
{"130", "A Pony", "Permite volar mientras lo tengas#Embiste en una dirección"},
{"131", "Bomb Bag", "Deja caer 1 bomba cada 2 habitaciones"},
{"132", "A Lump of Coal", "Más daño basado en la distancia que recorra la lágrima"},
{"133", "Guppy's Paw", "!!! Convierte:#1 corazón rojo en 3 corazones de alma"},
{"134", "Guppy's Tail", "Aparecen más cofres"},
{"135", "IV Bag", "Banco de sangre portátil#Medio corazón = 1 moneda"},
{"136", "Best Friend", "Muñeco explosivo#Atrae a los enemigos"},
{"137", "Remote Detonator", "Detona bombas al gusto#+5 bombas"},
{"138", "Stigmata", "↑ +1 de vida#↑ +0,3 de daño"},
{"139", "Mom's Purse", "Puedes tener 2 trinkets"},
{"140", "Bob's Curse", "Bombas venenosas#+5 bombas"},
{"141", "Pageant Boy", "Genera 7 monedas aleatorias"},
{"142", "Scapular", "Si te dañan menos de medio corazón, ganas 1 corazón de alma#(Uno por habitación)"},
{"143", "Speed Ball", "↑ +0,3 de velocidad#↑ +0,2 de velocidad de disparo"},
{"144", "Bum Friend", "Convierte monedas en recolectables"},
{"145", "Guppy's Head", "Genera de 2 a 4 moscas azules"},
{"146", "Prayer Card", "+1 corazón eterno"},
{"147", "Notched Axe", "Rompe las rocas de la habitación actual"},
{"148", "Infestation", "Genera moscas cuando te golpean"},
{"149", "Ipecac", "Lágrimas explosivas"},
{"150", "Tough Love", "Posibilidad de disparar dientes"},
{"151", "The Mulligan", "1/6 probabilidad de generar una mosca al golpear un enemigo"},
{"152", "Technology 2", "¡Láser permanente!#↓ -35% de daño"},
{"153", "Mutant Spider", "¡Disparo cuádruple!#↓ Menos lágrimas"},
{"154", "Chemical Peel", "↑ +2 de daño para el ojo izquierdo"},
{"155", "The Peeper", "Flota por la habitación#Inflige daño por contacto"},
{"156", "Habit", "Te da una carga cuando te golpean"},
{"157", "Bloody Lust", "↑ Más daño cuando te golpean#Dura todo la planta"},
{"158", "Crystal Ball", "Muestra el mapa completo#Genera una carta aleatoria o un corazón de alma"},
{"159", "Spirit of the Night", "Vuela#Lágrimas espectrales"},
{"160", "Crack the Sky", "¡Rayos de luz desde el cielo!"},
{"161", "Ankh", "Reaparece como ??? (Blue Baby(Bebé Azul))"},
{"162", "Celtic Cross", "Probabilidad de ser invencible cuando te golpean"},
{"163", "Ghost Baby", "Familiar de lágrimas espectrales"},
{"164", "The Candle", "Genera una mosca azul"},
{"165", "Cat-o-nine-tails", "↑ +1 daño#↑ +0,23 de velocidad de disparo"},
{"166", "D20", "Cambia los recolectables"},
{"167", "Harlequin Baby", "Dispara dos lágrimas en forma de V"},
{"168", "Epic Fetus", "Ataque aéreo controlable en lugar de lágrimas"},
{"169", "Polyphemus", "¡Mega lágrimas!#↑ Más daño#↓ Menos lágrimas"},
{"170", "Daddy Longlegs", "Cae sobre los enemigos"},
{"171", "Spider Butt", "Ralentiza a los enemigos#Daña a todos los enemigos"},
{"172", "Sacrificial Dagger", "Cuchillo orbital"},
{"173", "Mitre", "Mayor probabilidad de encontrar corazones de alma"},
{"174", "Rainbow Baby", "Dispara lágrimas aleatorias"},
{"175", "Dad's Key", "Abre todas las puertas de la habitación actual, incluyendo las salas secretas"},
{"176", "Stem Cells", "↑ +1 de vida#↑ +0,16 de velocidad de disparo"},
{"177", "Portable Slot", "Tragaperras portátil"},
{"178", "Holy Water", "Deja un rastro de creep cuando te golpean"},
{"179", "Fate", "Vuela#+1 corazón eterno"},
{"180", "The Black Bean", "Te tiras un pedo cuando te tocan"},
{"181", "White Pony", "Permite volar mientras lo tengas#Aparecen rayos de luz al embestir"},
{"182", "Sacred Heart", "Lágrimas teledirigidas#↑ +1 de vida#↑ Más daño#↓ -0,4 de lágrimas#↓ -0,25 de velocidad de disparo#↑ +0,375 de rango"},
{"183", "Tooth Picks", "↑ +0,7 de lágrimas.#↑ +0,16 de velocidad de disparo"},
{"184", "Holy Grail", "↑ +1 de vida#Permite volar"},
{"185", "Dead Dove", "Vuela#Lágrimas espectrales"},
{"186", "Blood Rights", "Inflige 40 de daño a cada enemigo#-1 corazón rojo al usarlo"},
{"187", "Guppy's Hairball", "Bola de pelo creciente#Se mueve a tu alrededor#Crece al matar enemigos"},
{"188", "Abel", "Copia tus movimientos#Dispara hacia el jugador"},
{"189", "SMB Super Fan", "↑ +1 de vida#↑ +0,3 de daño#↑ +0,2 de lágrimas#↑ +0,5 de rango#↑ +0,2 de velocidad#↑ +1,0 de tamaño de lágrima#Vida al completo"},
{"190", "Pyro", "+99 Bombas"},
{"191", "3 Dollar Bill", "Efecto de lágrima aleatorio"},
{"192", "Telepathy For Dummies", "Lágrimas teledirigidas en la habitación actual"},
{"193", "MEAT!", "↑ +1 de vida#↑ +0,3 de daño"},
{"194", "Magic 8 Ball", "↑ +0,16 de velocidad de disparo#+1 carta"},
{"195", "Mom's Coin Purse", "Genera 4 píldoras"},
{"196", "Squeezy", "+2 corazones de alma#↑ +0,4 de lágrimas"},
{"197", "Jesus Juice", "↑ +0,5 de daño#↑ +0,25 de rango.#↑ +0,5 de tamaño de lágrima"},
{"198", "Box", "Genera 1 recolectable de cada tipo"},
{"199", "Mom's Key", "+2 llaves#Los cofres generan más recolectables"},
{"200", "Mom's Eyeshadow", "Lágrimas encantadas"},
{"201", "Iron Bar", "↑ +0,3 de daño#Aturde a los enemigos"},
{"202", "Midas' Touch", "Convierte a los enemigos en oro al tocarlos#Los enemigos dorados dejan caer monedas"},
{"203", "Humbleing Bundle", "Duplica todos los recolectables"},
{"204", "Fanny Pack", "Genera un recolectable aleatorio cuando te golpean"},
{"205", "Sharp Plug", "-2 corazones = Carga el objeto al completo cuando pulsas espacio#!!! Solo funciona si el objeto no está cargado"},
{"206", "Guillotine", "↑ +1 de daño#↑ Más lágrimas#Tu cabeza es un orbital#Disparas desde la cabeza"},
{"207", "Ball of Bandages", "NVL1: Orbital#NVL2: Orbital que dispara#NVL3: Bandage girl#NVL4: Bandage girl NVL2"},
{"208", "Champion Belt", "↑ +1 de daño#!!! Aparecen más campeones"},
{"209", "Butt Bombs", "↑ +5 Bombas#Las explosiones aturden y dañan a todos los enemigos de la habitación"},
{"210", "Gnawed Leaf", "Invencible al quedarse quieto por 1 segundo"},
{"211", "Spiderbaby", "Genera arañas cuando te golpean"},
{"212", "Guppy's Collar", "↑ 50% de probabilidad de revivir"},
{"213", "Lost Contact", "Lágrimas con escudo#↓ -0,15 de velocidad de disparo"},
{"214", "Anemic", "↑ +5 de rango#Deja creep en el suelo cuando te golpean"},
{"215", "Goat Head", "↑ 100% de probabilidad de pacto con el Diablo o el Ángel"},
{"216", "Ceremonial Robes", "↑ +1 de daño#+3 Corazones negros"},
{"217", "Mom's Wig", "Probabilidad aleatoria de generar una araña azul al disparar"},
{"218", "Placenta", "Regenera la vida poco a poco#↑ +1 de vida"},
{"219", "Old Bandage", "↑ +1 contenedor de corazón vacío#Probabilidad aleatoria de dejar caer corazones cuando te golpean"},
{"220", "Sad Bombs", "¡Explosión de lágrimas!#+5 Bombas"},
{"221", "Rubber Cement", "Las lágrimas rebotan"},
{"222", "Anti-Gravity", "↑ Más daño#Lágrimas anti-gravedad"},
{"223", "Pyromaniac", "Las explosiones te curan#+5 Bombas"},
{"224", "Cricket's Body", "↑ Más lágrimas#↓ -10,0 de rango#Las lágrimas se dividen en 4 al impactar"},
{"225", "Gimpy", "Posibilidad de dejar caer corazones de alma o negros cuando te golpean"},
{"226", "Black Lotus", "↑ +1 de vida#+1 corazón de alma#+1 corazón negro"},
{"227", "Piggy Bank", "+3 monedas#Genera una moneda cuando te golpean"},
{"228", "Mom's Perfume", "Las lágrimas asustan a los enemigos#↑ Más daño"},
{"229", "Monstro's Lung", "Las lágrimas pueden cargarse y lanzarse como si fuera una pistola"},
{"230", "Abaddon", "↑ +1,5 de daño#↑ +0,2 de velocidad#Las lágrimas asustan a los enemigos#↓ Elimina todos los corazones rojos#+6 corazones negros"},
{"231", "Ball of Tar", "Deja creep que ralentiza#Las lágrimas ralentizan"},
{"232", "Stop Watch", "Ralentiza automáticamente(se activa por primera vez cuando te golpean)"},
{"233", "Tiny Planet", "Las lágrimas orbitan alrededor de Isaac#↑ +7,0 de tamaño de lágrima"},
{"234", "Infestation 2", "Al matar a un enemigo genera arañas "},
{"235", "", "<El objeto no existe>"},
{"236", "E. Coli", "Al tocar a los enemigos los convierte en caca"},
{"237", "Death's Touch", "¡Dispara guadañas!#↑ +1,5 de daño#↓ -0,3 de lágrimas"},
{"238", "Key Piece 1", "!!! ¡Pieza de llave para la puerte de Mega Satán!#Aparecen más Salas del Ángel"},
{"239", "Key Piece 2", "!!! ¡Pieza de llave para la puerte de Mega Satán!#Aparecen más Salas del Ángel"},
{"240", "Experimental Treatment", "Todas las estadisticas ↑/↓ un número aleatorio"},
{"241", "Contract from Below", "Duplica los recolectables que cojas"},
{"242", "Infamy", "Posibilidad de bloquear lágrimas"},
{"243", "Trinity Shield", "Escudo que bloquea lágrimas"},
{"244", "Tech.5", "Dispara lágrimas láseres de manera aleatoria"},
{"245", "20/20", "Duplica los disparos"},
{"246", "Blue Map", "Muestra las habitaciones secretas"},
{"247", "BFFS!", "Tus familiares infligen más daño"},
{"248", "Hive Mind", "Las moscas y arañas azules duplican su daño"},
{"249", "There's Options", "Aparecen 2 objetos de Jefe en lugar de 1#!!! Solo puede cogerse uno"},
{"250", "BOGO Bombs", "Duplica todas las bombas que cojas"},
{"251", "Starter Deck", "Puedes llevar 2 cartas#Convierte todas las píldoras en cartas"},
{"252", "Little Baggy", "Puedes llevar 2 píldoras#Convierte todas las cartas en píldoras"},
{"253", "Magic Scab", "↑ +1 de suerte#↑ +1 de vida"},
{"254", "Blood Clot", "↑ +1 de daño#↑ +5 de rango#!!! Solo se aplica al ojo izquierdo"},
{"255", "Screw", "↑ +0,5 de lágrimas#↑ +0,2 de velocidad de disparo"},
{"256", "Hot Bombs", "Las bombas queman#+5 Bombas"},
{"257", "Fire Mind", "Las lágrimas están en llamas#Posibilidad de que las lágrimas exploten"},
{"258", "Missing No.", "Cambia todos tus objetos cada vez que cambias de planta"},
{"259", "Dark Matter", "↑ +1 de daño#Las lágrimas asustan a los enemigos"},
{"260", "Black Candle", "Inmune a las maldiciones#+1 corazón negro"},
{"261", "Proptosis", "↑ +100% más de daño#↓ El daño infligido disminuye en función de la distancia recorrida por la lágrima"},
{"262", "Missing Page 2", "+1 corazón negro#Al tener menos de 1 corazón y medio, dañas a todos los enemigos de la habitación"},
{"263", "", "<El objeto no existe>"},
{"264", "Smart Fly", "Orbital que puede cargar contra los enemigos"},
{"265", "Dry Baby", "Al ser golpeado por lágrimas enemigas, puedes dañar a todos los enemigos de la habitación"},
{"266", "Juicy Sack", "Deja creep ralentizante#Posibilidad de generar arañas aliadas al limpiar la habitación"},
{"267", "Robo-Baby 2.0", "Dispara láseres"},
{"268", "Rotten Baby", "Genera moscas azules"},
{"269", "Headless Baby", "Deja creep"},
{"270", "Leech", "Cura medio corazón al matar enemigos"},
{"271", "Mystery Sack", "Genera recolectables aleatorios"},
{"272", "BBF", "Mosca explosiva aliada"},
{"273", "Bob's Brain", "Familiar bomba lanzable"},
{"274", "Best Bud", "Al ser golpeado, ganas un orbital de rango medio"},
{"275", "Lil Brimstone", "Dispara un rayo de brimstone (azufre)"},
{"276", "Isaac's Heart", "Gana un cuerpo invulnerable#!!! Cuando al familiar corazón le golpean te hace daño"},
{"277", "Lil Haunt", "Familiar fantasma aliado"},
{"278", "Dark Bum", "!!! Convierte:#1,5 corazones rojos en 1 corazón de alma"},
{"279", "Big Fan", "Orbital grande"},
{"280", "Sissy Longlegs", "Invoca arañas azules"},
{"281", "Punching Bag", "Los enemigos le atacarán a él en lugar de a ti"},
{"282", "How to Jump", "Permite saltar"},
{"283", "D100", "Cambia todos los recolectabes, pedestales y los objetos que tengas"},
{"284", "D4", "Cambia los objetos que tengas"},
{"285", "D10", "Cambia todos los enemigos de la habitación"},
{"286", "Blank Card", "Copia el efecto de la carta que tengas"},
{"287", "Book of Secrets", "Muestra partes del mapa"},
{"288", "Box of Spiders", "Invoca de 2 a 4 arañas azules"},
{"289", "Red Candle", "Lanza fuego rojo"},
{"290", "The Jar", "Almacena hasta 4 corazones rojos"},
{"291", "Flush!", "!!! Mata a enemigos y jefes caca de manera instantánea#Convierte a los enemigos en caca"},
{"292", "Satanic Bible", "+1 corazón negro"},
{"293", "Head of Krampus", "Dispara un rayo de brimstone (azufre) en las 4 direcciones"},
{"294", "Butter Bean", "Repele a los enemigos cercanos"},
{"295", "Magic Fingers", "Daña toda la habitación#Precio: 1 moneda"},
{"296", "Converter", "!!! Convierte:#2 corazones de alma/negros en un corazón rojo"},
{"297", "Pandora's Box", "!!! ÚNICO USO !#!!! Genera cosas en función del piso en el que se active:#B1: 2 corazones de alma #B2: 2 llaves y bombas#C1: 1 objeto de jefe#C2: B1+C1#D1: 4 corazones de alma#D2: 30 monedas#W1: 2 objetos de jefe#W2: Biblia#Sheol: 1 objeto del diablo+corazón negro#Catedral: 1 objeto de ángel + corazón de alma#Chest(cofre): 1 moneda"},
{"298", "Unicorn Stump", "Invencibilidad y más velocidad temporal"},
{"299", "Taurus", "¡Te hace más rápido en las habitaciones hostiles!#Invencibilidad al alcanzar la velocidad suficiente"},
{"300", "Aries", "↑ +0,25 de velocidad#Tocar a los enemigos les daña"},
{"301", "Cancer", "+3 corazones de alma#Reduce a la mitad el daño que recibas en la habitación tras ser golpeado una vez"},
{"302", "Leo", "¡Rompe las rocas!"},
{"303", "Virgo", "Posibilidad de ser invencible cuando te tocan"},
{"304", "Libra", "+6 monedas / llaves / bombas#¡Equilibra tus estadísticas!#!!! Cada estadística afectará también a otras estadísticas"},
{"305", "Scorpio", "Lágrimas venenosas"},
{"306", "Sagittarius", "↑ +0,2 de velocidad#Lágrimas penetrantes"},
{"307", "Capricorn", "↑ +1 Vida / Llave / Bomba / Moneda#↑ +0,5 de daño#↑ +0,1 de velocidad#↑ +1,5 de rango"},
{"308", "Aquarius", "Deja un rastro de creep"},
{"309", "Pisces", "↑ Más lagrimas#Lágrimas con empuje"},
{"310", "Eve's Mascara", "↑ X2 de daño#↓ Menos lágrimas#↓ Menos velocidad de disparo"},
{"311", "Judas' Shadow", "Al morir, revive como la Sombra de Judas#↓ (X2 de daño)"},
{"312", "Maggy's Bow", "↑ +1 de vida#Todos los corazones rojos curarán 2 contenedores"},
{"313", "Holy Mantle", "Ignora el primer golpe de cada habitación"},
{"314", "Thunder Thighs", "↑ +1 de vida#-0,4 de velocidad#Rompes rocas"},
{"315", "Strange Attractor", "Lágrimas magnéticas"},
{"316", "Cursed Eye", "Ola de lágrimas cargadas#Cuando cargas y te golpean te teletransporta a una habitación aleatoria"},
{"317", "Mysterious Liquid", "Las lágrimas dejan creep"},
{"318", "Gemini", "Familiar unido a ti"},
{"319", "Cain's Other Eye", "Rebota por la habitación#Dispara en la misma dirección que Isaac"},
{"320", "???'s Only Friend", "Mosca controlable"},
{"321", "Samson's Chains", "Bola de acero encadenada a Isaac#Puede dañar enemigos o destruir rocas"},
{"322", "Mongo Baby", "Copia el efecto de uno de tus familiares"},
{"323", "Isaac's Tears", "Potencia las lágrimas#Carga al disparar"},
{"324", "Undefined", "Te teletransporta a:#Habitación Secreta / Error / Sala del tesoro"},
{"325", "Scissors", "Te corta la cabeza#La cabeza no se mueve#Controla tu cuerpo por separado"},
{"326", "Breath of Life", "Mantén hasta que la barra del objeto se vacíe para ser invencible#!!! ¡No mantengas demasiado tiempo!"},
{"327", "The Polaroid", "Invencible cuando te golpean y estás a medio corazón"},
{"328", "The Negative", "Efecto de necronomicón cuando te golpean y estás a medio corazón"},
{"329", "The Ludovico Technique", "Lágrima controlable"},
{"330", "Soy Milk", "↑ Muchas más lágrimas#↓ -80% de daño"},
{"331", "Godhead", "Lágrimas teledirigidas#↑ +0,5 de daño#↑ +1,2 de rango#↓ -0,3 de lágrimas#↓ -0,3 de velocidad de disparo#↑ +0,8 de tamaño de lágrima"},
{"332", "Lazarus' Rags", "Al morir, revive como Lázaro +1 objeto extra"},
{"333", "The Mind", "Visión de mapa al completo"},
{"334", "The Body", "↑ +3 de vida"},
{"335", "The Soul", "+2 corazones de alma#Los proyectiles evitarán a Isaac"},
{"336", "Dead Onion", "Lágrimas espectrales y penetrantes#↓ -0,25 de rango#↓ -0,4 de velocidad de disparo"},
{"337", "Broken Watch", "Ralentiza o acelera las habitaciones"},
{"338", "The Boomerang", "Aturde a los enemigos#Puede coger objetos"},
{"339", "Safety Pin", "↑ +5,25 de rango#↑ +0,16 de velocidad de disparo#+1 corazón negro#↑ +0,5 de tamaño de lágrima"},
{"340", "Caffeine Pill", "↑ +0,3 de velocidad#↑ Hace más pequeño al jugador#Al cogerlo te da una píldora"},
{"341", "Torn Photo", "↑ +0,7 de lágrimas#↑ +0,16 de velocidad de disparo"},
{"342", "Blue Cap", "↑ +1 de vida#↑ +0,7 de lágrimas#↓ -0,16 de velocidad de disparo"},
{"343", "Latch Key", "↑ +1 de suerte#+1 corazón de alma#Genera 2 llaves"},
{"344", "Match Book", "+1 corazón negro#+3 Bombas"},
{"345", "Synthoil", "↑ +1,0 de daño#↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
{"346", "A Snack", "↑ +1 de vida"},
{"347", "Diplopia", "!!! UN SOLO USO !#Duplica los pedestales y consumibles de la habitación actual"},
{"348", "Placebo", "Copia el efecto de la píldora que tienes"},
{"349", "Wooden Nickel", "50% de probabilidad de generar una moneda aleatoria"},
{"350", "Toxic Shock", "Al entar en cada habitación los enemigos se envenenan"},
{"351", "Mega Bean", "Congela a los enemigos#Inflige daño y envenena a los enemigos cercanos#Genera una onda de piedra#!!! Puede usarse para abrir habitaciones secretas"},
{"352", "Glass Cannon", "↓ Reduce tu vida a medio corazón#Dispara una gran lágrima espectral y penetrante ((+1 daño) X 10)"},
{"353", "Bomber Boy", "+5 bombas#Las bombas explotan en forma de cruz"},
{"354", "Crack Jacks", "↑ +1 de vida#Genera un trinket aleatorio"},
{"355", "Mom's Pearls", "↑ +1,25 de rango#↑ +1 de suerte#↑ +0,5 de tamaño de lágrima"},
{"356", "Car Battery", "Hace que tu objeto activable se active dos veces"},
{"357", "Box of Friends", "Duplica los familiares en la habitación actual"},
{"358", "The Wiz", "Dispara 2 lágrimas de manera diagonal, similar a R U A WIZARD#Lágrimas espectrales"},
{"359", "8 Inch Nails", "↑ +1,5 de daño#Aumenta el empuje"},
{"360", "Incubus", "Familiar que dispara las mismas lágrimas que Isaac"},
{"361", "Fate's Reward", "Dispara lágrimas y copia el daño de la lágrima"},
{"362", "Lil Chest", "Deja caer un recolectable cada pocas habitaciones"},
{"363", "Sworn Protector", "Inflige daño por contacto#Bloquear una lágrima puede dejar caer un corazón eterno"},
{"364", "Friend Zone", "Inflige daño por contacto"},
{"365", "Lost Fly", "Mosca que se mueve por las paredes de la habitación#Inflige daño por contacto"},
{"366", "Scatter Bombs", "+5 bombas#Hace que las bombas exploten en 4 bombas pequeñas"},
{"367", "Sticky Bombs", "+5 bombas#Cuando la bomba mata un enemigo, genera un araña azul#Hace que las bombas se peguen a los enemigos"},
{"368", "Epiphora", "Disparar en una única dirección aumenta la cadencia de disparo"},
{"369", "Continuum", "↑ +2.25 de rango#↑ +1,5 de tamaño de lágrima#las lágrimas atraviesan las paredes y aparecen por la pared contraria"},
{"370", "Mr. Dolly", "↑ +0,7 de lágrimas#↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima#Genera 3 corazones aleatorios al cogerlo"},
{"371", "Curse of the Tower", "Genera 6 bombas troll cada vez que te golpean"},
{"372", "Charged Baby", "Posibilidad de dejar caer una batería o de congelar a los enemigos#Puede agregar una carga a tu objeto activable"},
{"373", "Dead Eye", "↑ +12.5% de daño por cada lágrima que golpee a un enemigo(máximo +100%)"},
{"374", "Holy Light", "Posibilidad de disparar una lágrima sagrada, que hará que caigan rayos de luz desde el cielo"},
{"375", "Host Hat", "Posibilidad de evitar lágrimas#Inmune a explosiones y al pie de Mamá"},
{"376", "Restock", "Las tiendas reponen los objetos que compres instantáneamente#genera 3 pick ups"},
{"377", "Bursting Sack", "Las arañas enemigas  ya no dañarán a Isaac"},
{"378", "No. 2", "Disparar durante 3 segundos generará una bomba caca"},
{"379", "Pupula Duplex", "Las lágrimas tienen una hitbox mayor#Lágrimas espectrales"},
{"380", "Pay To Play", "+5 monedas#Abres puertas con monedas en lugar de llaves"},
{"381", "Eden's Blessing", "↑ +0,7 de lágrimas#Objeto aleatorio al inicio de la siguiente partida"},
{"382", "Friendly Ball", "Se lanza a los enemigos para capturarlos# Cuando vuelvas a usarlo revivirá como aliado"},
{"383", "Tear Detonator", "Detona las lágrimas que lances para que se separen en otras 6 lágrimas"},
{"384", "Lil Gurdy", "Rebota por la habitación infligiendo daño por contacto a los enemigos"},
{"385", "Bumbo", "Recoge monedas cercanas. Cada 6 monedas sube de nivel, menos para el nivel 4 que son 12#Nivel 2: suelta recolectables aleatorios#Nivel 3: lanza lágrimas en la misma dirección que Isaac#Nivel 4: ya no dispara, persigue a los enemigos. Puede soltar bombas#Después de nivel 4: recoge monedas y suelta recolectables aleatorios"},
{"386", "D12", "Cambia las rocas en otro tipo de objeto aleatorio (caca, TNT, caca roja, piedras, etc.)"},
{"387", "Censer", "Crea un gran aura de luz que ralentiza a los enemigos que entren en ella"},
{"388", "Key Bum", "Recoge llaves y genera cofres aleatorios a cambio"},
{"389", "Rune Bag", "Genera una runa aleatoria cada 3 habitaciones"},
{"390", "Seraphim", "Dispara lágrimas similares a Corazón sagrado(Sacred Heart)"},
{"391", "Betrayal", "Cada vez que golpean a Isaac, los enemigos de la habitación reciben un efecto encantador"},
{"392", "Zodiac", "Efecto aleatorio de objeto del zodíaco que cambia cada planta"},
{"393", "Serpent's Kiss", "Posibilidad de envenenar a los enemigos#Envenena al tocar#Posibilidad de que los enemigos envenenados dejen caer un corazón negro al caer"},
{"394", "Marked", "Dispara lágrimas automáticamente dirigidas por la mira roja en el suelo#↑ +0,7 de lágrimas#↑ +0,3 de tamaño de lágrima#↑ +3,15 de rango"},
{"395", "Tech X", "Ahora disparas anillos láser con gran daño"},
{"396", "Ventricle Razor", "Crea dos portales para viajar entre ellos"},
{"397", "Tractor Beam", "Las lágrimas viajan en línea recta siguiendo un rayo de luz#↑ +0,5 de lágrimas#↑ +5,25 de rango#↑ +0,16 de velocidad de disparo#↑ +0,5 de tamaño de lágrima"},
{"398", "God's Flesh", "Las lágrimas pueden reducir el tamaño de los enemigos#Puedes pisarlos para matarlos"},
{"399", "Maw Of The Void", "↑ +1,0 de daño#↑ +0,5 de tamaño de lágrima#Tras disparar lágrimas durante 3 segundos, crea un anillo negro que daña a los enemigos que están dentro de él#Los enemigos asesinados con el anillo negro pueden generar corazones negros"},
{"400", "Spear Of Destiny", "Genera una lanza delante tuyo que inflige un daño igual a tu daño duplicado"},
{"401", "Explosivo", "Las lágrimas puede convertirse en bombas pegajosas que se pegan a los enemigos y explotan tras unos segundos"},
{"402", "Chaos", "Puede aparecer cualquier objeto del juego en los pedestales# Al cogerlo, deja caer entre 1-6 recolectables"},
{"403", "Spider Mod", "Te permite ver el daño de la lágrima y la barra de vida de los enemigos#Al tocar a un enemigo lo congela#Dejará caer baterías"},
{"404", "Farting Baby", "Bloquea las lágrimas#Si le golpean se tirará un pedo, lo que dañará y encantará a los enemigos cercanos"},
{"405", "GB Bug", "Familiar que aplica un efecto aleatorio a los enemigos que le toquen"},
{"406", "D8", "Cambia tus estadísticas#Solo afecta al daño, las lágrimas, el rango y la velocidad"},
{"407", "Purity", "↑ Potencia una estadística dependiendo del color del aura que te rodea#Al recibir daño cambia el color de aura#Rojo = +4,0 de daño#Azul = +4 de lágrimas#Amarillo = +0,5 de velocidad#Naranja = +7,5 de rango"},
{"408", "Athame", "Al recibir daño, aparece un anillo negro alrededor de Isaac que inflige daño por contacto#Los enemigos asesinados con ello pueden dejar caer un corazón negro"},
{"409", "Empty Vessel", "+2 corazones negros#Cuando no tengas corazones rojos, te permite volar y de generar un escudo"},
{"410", "Evil Eye", "A veces aparece un ojo que disparará lágrimas en la misma dirección que Isaac"},
{"411", "Lusty Blood", "↑ Cada vez que matas a un enemigo, aumenta el daño de manera temporal#Máximo:+5 de daño al matar 9 veces"},
{"412", "Cambion Conception", "Al recibir suficiente daño, ganas un familiar demoníaco permanente "},
{"413", "Immaculate Conception", "Al recoger suficientes corazones, ganas un familiar angelical permanente"},
{"414", "More Options", "Se generan dos objetos en la Sala del tesoro#Solo puedes escoger uno"},
{"415", "Crown Of Light", "+2 corazones de alma#↑ Más daño X 2 si no tienes ningún contenedor de corazón vacío"},
{"416", "Deep Pockets", "Te permite llevar 2 cartas/píldoras/runas"},
{"417", "Succubus", "Familiar que rebota con un aura que inflige daño a los enemigos que estén dentro de ella#↑ Al quedarse sobre el aura, +50% de multiplicador de daño"},
{"418", "Fruit Cake", "Otorga un efecto de lágrima diferente por cada lágrima que disparas"},
{"419", "Teleport 2.0", "Te teletransporta a una habitación sin explorar#Jerarquía: habitaciones normales, salas súper secretas, tienda, Sala del tesoro, Sala secreta, habitación maldita, Sala del sacrificio, Sala de Diablo/Ángel, Yo soy error (I Am Error)"},
{"420", "Black Powder", "Caminar en círculo forma un símbolo de pentagrama en el suelo, que inflige 10 de daño por tick"},
{"421", "Kidney Bean", "Encanta a los enemigos cercanos"},
{"422", "Glowing Hour Glass", "Viaja en el tiempo y te deja en habitaciones anteriores, de la misma manera que como estabas entonces"},
{"423", "Circle of Protection", "Se crea un gran halo alrededor de Isaac, inflige daño por contacto#Posibilidad de evitar lágrimas"},
{"424", "Sack Head", "Posibilidad de que los recolectables se sustituyan por un saco"},
{"425", "Night Light", "Un cono de luz frente a Isaac que ralentiza a los enemigos y a sus lágrimas"},
{"426", "Obsessed Fan", "Sigue tus movimientos exactos con 3 segundos de retraso#Inflige daño por contacto a los enemigos"},
{"427", "Mine Crafter", "Coloca un barril de TNT#Si no se ha usado el barril y colocas otro en la misma habitación, el primero explotará"},
{"428", "PJs", "+4 corazones de alma#Cura los corazones rojos al completo"},
{"429", "Head of the Keeper", "Las lágrimas pueden dejar caer monedas tras golpear a un enemigo con éxito"},
{"430", "Papa Fly", "Sigue tus movimientos con 3 segundos de retraso#Dispara a los enemigos cercanos e inflige el mismo daño que Isaac"},
{"431", "Multidimensional Baby", "Sigue tus movimientos con 3 segundos de retraso#Las lágrimas que lo traspasen duplicarán el daño"},
{"432", "Glitter Bombs", "Las bombas generan recolectables aleatorios al explotar(llaves, monedas, bombas)"},
{"433", "My Shadow", "Cada vez que te golpean, Mi sombra asustará a los enemigos de la habitación y generará un familiar negro por ti#El familiar morirá al recibir mucho daño"},
{"434", "Jar of Flies", "Cada vez que mates a un enemigo se añadirá una mosca azul al tarro#Máximo 20 moscas#Usar el Tarro de moscas las soltará"},
{"435", "Lil Loki", "Dispara 4 lágrimas en forma de cruz"},
{"436", "Milk!", "Tras ser golpeado, la leche te aumenta las lágrimas para el resto de la habitación"},
{"437", "D7", "Vuelve a generar enemigos y te permite conseguir recompensas al acabar la habitación#!!! Al usarlo en una lucha contra Greed, puede convertir la habitación en una tienda"},
{"438", "Binky", "+1 corazón de alma#↑ +0,7 de lágrimas#↑ Hace que Isaac sea muy pequeño, reduce el tamaño de la hitbox"},
{"439", "Mom's Box", "Deja caer un trinket aleatorio#↑ +1 de suerte#Al tenerlo duplica el efecto de los trinkets"},
{"440", "Kidney Stone", "Al disparar, puede lanzar un grupo de lágrimas y una roca#↓ -0,2 de velocidad#↓ -15 de rango#↑ +2.0 de tamaño de lágrima"},
{"441", "Mega Blast", "Dispara un gran láser de Mega Satán durante 15 segundos#El láser dura los 15 segundos incluso entre habitaciones o plantas"},
{"442", "Dark Princes Crown", "!!! Al tener un corazón rojo lleno:#↑ +1,5 de rango#↑ +0,7 de lágrimas#↑ +0,2 de velocidad de disparo#(No funciona con the Lost (El Perdido))"},
{"443", "Apple!", "Dispara cuchillas que infligen un 400% de daño de manera aleatoria#↑ +0,4 de lágrimas"},
{"444", "Lead Pencil", "Cada 15 lágrimas disparas un grupo de lágrimas#Cada una inflige el doble de daño"},
{"445", "Dog Tooth", "↑ +0,3 de daño#↑ +0,1 de velocidad#Un lobo aúlla si entras en una habitación al lado de la sala secreta o con una trampilla "},
{"446", "Dead Tooth", "Al disparar, recibes un aura verde que envenena a los enemigos que entran"},
{"447", "Linger Bean", "Al disparar, genera una nube de caca aleatoria"},
{"448", "Shard of Glass", "Cuando te golpean, posibilidad de ganar ↑ +5 de rango y deja un rastro de creep sangriento"},
{"449", "Metal Plate", "+1 corazón de alma#Posibilidad de esquivar los proyectiles enemigos"},
{"450", "Eye of Greed", "Las lágrimas pueden transformar a los enemigos en oro"},
{"451", "Tarot Cloth", "Genera una carta o runa aleatoria#Duplica el uso de cualquier carta del tarot"},
{"452", "Varicose Veins", "Cuando te golpean se dispara un círculo de 10 lágrimas con mucho daño"},
{"453", "Compound Fracture", "Lágrimas de hueso#Al golpear a un enemigo, las lágrimas se separan en 1-3 trozos de hueso#↑ +1,5 de rango"},
{"454", "Polydactyly", "Puedes llevar dos cartas, runas o píldoras#Genera una carta, píldora o runa aleatoria al cogerlo"},
{"455", "Dad's Lost Coin", "↑ +1,5 de rango#Deja caer un penique de la suerte"},
{"456", "Moldy Bread", "↑ +1 de vida"},
{"457", "Cone Head", "+1 corazón de alma#Posibilidad de ignorar daño"},
{"458", "Belly Button", "Genera un trinket aleatorio al cogerlo#+Espacio para un trinket adicional"},
{"459", "Sinus Infection", "Lágrimas venenosas que se pegan al enemigo hasta que muere"},
{"460", "Glaucoma", "Posibilidad de disparar lágrimas que aturden"},
{"461", "Parasitoid", "Posibilidad de disparar lágrimas pegajosas ralentizantes#Genera una mosca o araña azul"},
{"462", "Eye of Belial", "Otorga lágrimas penetrantes#Tras golpear al primer enemigo, las lágrimas infligen el doble de daño y se vuelven teledirigidas"},
{"463", "Sulfuric Acid", "↑ +0,3 de daño#Probabilidad de disparar lágrimas que destruyan rocas"},
{"464", "Glyph of Balance", "+2 corazones de alma#Los enemigos campeones generan más recolectables"},
{"465", "Analog Stick", "↑ Más lágrimas#Permite disparar lágrimas en diagonal disparando en dos direcciones"},
{"466", "Contagion", "El primer enemigo asesinado explota y envenena a los enemigos cercanos"},
{"467", "Finger!", "Inflige un pequeño daño constante en la dirección en la que señala el dedo"},
{"468", "Shade", "Sigue tu movimiento con un retraso de 3 segundos#Inflige daño por contacto"},
{"469", "Depression", "Deja un rastro de lágrimas#Los enemigos que toquen la nube pueden activar un efecto similar al de Crack the Sky"},
{"470", "Hushy", "Rebota por la habitación e inflige daño por contacto#Mientras disparas no se mueve"},
{"471", "Lil Monstro", "Carga los disparos como Monstro"},
{"472", "King Baby", "Le siguen otros familiares#Mientras disparas no se mueve#Se teletransporta a ti cuando dejas de disparar"},
{"473", "Big Chubby", "Carga hacia delante lentamente#Inflige daño por contacto"},
{"474", "Tonsil", "Bloquea los proyectiles enemigos"},
{"475", "Plan C", "!!! UN SOLO USO ! #Inflige 9.999.999 de daño a todos los enemigos y te mata 3 segundos después"},
{"476", "D1", "Duplica 1 recolectable aleatorio en la habitación actual"},
{"477", "Void", "!!! Al usarlo, consume cualquier objeto de pedestal en la habitación#Objeto activo: Se añade el efecto al de Void (Vacío)(Conserva los efectos)#↑ Objeto pasivo: Pequeña mejora aleatoria"},
{"478", "Pause", "Congela a los enemigos hasta que vuelvas a disparar#Tocar a un enemigo congelado te hará daño"},
{"479", "Smelter", "Consume el trinket y ganas el efecto de manera permanente"},
{"480", "Compost", "Genera 1 mosca o araña azul por cada recolectable de la habitación"},
{"481", "Dataminer", "Al usarlo, ↑/↓ una pequeña cantidad de una estadística aleatoria#Efecto aleatorio de lágrima para la habitación actual"},
{"482", "Clicker", "Te convierte en otro personaje aleatorio#Elimina el último objeto que hayas cogido"},
{"483", "Mama Mega!", "!!! UN SOLO USO ! #Afecta a toda la planta#Explota todos los objetos#Inflige 200 de daño a todos los enemigos#Abre la Boss rush/puerta de Hush/Sala secreta"},
{"484", "Wait What?", "Al usarlo, empuja a los enemigos y genera una ola de rocas"},
{"485", "Crooked Penny", "50% de probabilidad de duplicar todos los objetos, consumibles y cofres de la habitación#50% de probabilidad de eliminar objetos/recolectables de la habitación y soltar una moneda"},
{"486", "Dull Razor", "Hace que el jugador sufra daño sin perder ningún corazón"},
{"487", "Potato Peeler", "Elimina un contenedor de corazón rojo y te da ↑ +0,2 de daño y \"Cube of Meat\""},
{"488", "Metronome", "Otorga un efecto de objeto aleatorio en la habitación"},
{"489", "D infinity", "Efecto de dado aleatorio"},
{"490", "Eden's Soul", "!!! UN SOLO USO !#Genera 2 objetos aleatorios"},
{"491", "Acid Baby", "Genera una píldora aleatoria cada 2 habitaciones#Usar una píldora daña a los enemigos"},
{"492", "YO LISTEN!", "↑ +1 de suerte#Resalta la localización de salas secretas, rocas marcadas y trampillas"},
{"493", "Adrenaline", "Por cada contenedor de corazón vacío:#↑ +0,2 de daño"},
{"494", "Jacob's Ladder", "Lágrimas eléctricas que al impactar generan rayos de electricidad"},
{"495", "Ghost Pepper", "Probabilidad de disparar fuego en lugar de lágrimas"},
{"496", "Euthanasia", "Puede disparar jeringuillas que matan a los enemigos (menos a los jefes) de un golpe"},
{"497", "Camo Undies", "Al entrar a una habitación te camuflas hasta que disparas"},
{"498", "Duality", "Genera la Sala del Diablo y del Ángel#Cuando entras en una la otra desaparece"},
{"499", "Eucharist", "↑ 100% de probabilidad de encontrar la Sala del Ángel"},
{"500", "Sack of Sacks", "Genera un saco de manera aleatoria"},
{"501", "Greed's Gullet", "Cada 25 monedas te da 1 contenedor de corazón#The Keeper ganará más monedas-corazones"},
{"502", "Large Zit", "Posibilidad de disparar una lágrima que suelte creep y duplica el daño"},
{"503", "Little Horn", "Posibilidad de disparar una lágrima que mata al instante"},
{"504", "Brown Nugget", "Genera una mosca que dispara a los enemigos"},
{"505", "Poke Go", "De manera aleatoria, genera un enemigo encantado al entrar en una habitación hostil"},
{"506", "BackStabber", "Las lágrimas causan sangrado que inflige el 10% de la vida total de los enemigos cada 5 segundos"},
{"507", "Sharp Straw", "Inflige el daño + 10% de daño de la vida máxima del enemigo#Afecta a todos los enemigos de la habitación#Probabilidad de generar medio corazón al infligir daño"},
{"508", "Mom's Razor", "Orbital que causa sangrado,que inflige el 10% de la vida total de los enemigos cada 5 segundos"},
{"509", "Bloodshot Eye", "Dispara una lágrima en una dirección aleatoria cada 2 segundos"},
{"510", "Delirious", "Genera una versión aliada de Delirium en la habitación actual"},
{"511", "Angry Fly", "Orbita alrededor de un enemigo aleatorio hasta que este muere#Inflige daño por contacto"},
{"512", "Black Hole", "Agujero negro lanzable, que lo absorbe todo"},
{"513", "Bozo", "↑ +0,1 de daño#+1 corazón de alma#Posibilidad de encantar/asustar a un enemigo#Posibilidad de generar una caca arcoiris al ser golpeado"},
{"514", "Broken Modem", "Los enemigos se quedan paralizados de manera aleatoria por unos instantes"},
{"515", "Mystery Gift", "!!! UN SOLO USO !#Genera un objeto coleccionable#Probabilidad de generar Lump of Coal (Trozo de carbón) o The Poop (La caca)"},
{"516", "Sprinkler", "Genera una torreta que gira y dispara lágrimas en todas las direcciones"},
{"517", "Fast Bombs", "+7 Bombas#Te permite colocar bombas muy rápido"},
{"518", "Buddy in a Box", "Familiar que cambia de aspecto#Efecto de lágrima aleatorio cada planta"},
{"519", "Lil Delirium", "Familiar que se transforma en otro familiar aleatorio cada 10 segundos"},
{"520", "Jumper Cables", "+1 carga para tu objecto activable cada 15 enemigos asesinados"},
{"521", "Coupon", "Al usarlo, un objeto de la tienda se vuelve gratis"},
{"522", "Telekinesis", "Detiene las lágrimas enemigas que estén cerca, para desviarlas a la dirección contraria.#Se recarga pasados 2 segundos"},
{"523", "Moving Box", "Guarda todos los recolectables de la habitación#Al volverlo usarlo suelta los recolectables#Permite mover objetos entre habitaciones"},
{"524", "Technology Zero", "Las lágrimas están conectadas con rayos de electricidad"},
{"525", "Leprosy", "Recibir daño genera un orbital#Máx. 3 orbitales a la vez#Si reciben demasiado daño, los orbitales pueden destruirse"},
{"526", "7 Seals", "Familiar con la forma y ataque de los jinetes"},
{"527", "Mr. ME!", "!!! Familiar que hace tareas por ti:#Abrir llaves y cofres, traerte objetos, robar de la tienda o del pacto, luchar contra enemigos, explotar y activar placas de presión"},
{"528", "Angelic Prism", "Las lágrimas que pasen por el prisma se separan en 4 nuevas lágrimas"},
{"529", "Pop!", "Las lágrimas son ojos que pueden rebotar entre ellos"},
{"530", "Death's List", "Otorga una recompensa al matar enemigos en el orden que se indica"},
{"531", "Haemolacria", "Las lágrimas salen en forma de arco#Al impactar, explotan en lágrimas más pequeñas"},
{"532", "Lachryphagy", "Las lágrimas se ralentizan mientras viajan#Al parar, explotan en pequeñas lágrimas#Las lágrimas pueden acumularse disparando unas sobre otras"},
{"533", "Trisagion", "Dispara rayos de luz blanca#(Brimstone sagrado)"},
{"534", "Schoolbag", "Te permite tener 2 objetos activables#Cámbialos pulsando CTRL (mantén CTRL si eres \"The Forgotten\")"},
{"535", "Blanket", "+1 corazón de alma#Otorga un escudo al entrar a la Sala del jefe"},
{"536", "Sacrificial Altar", "Sacrifica un familiar para generar un objeto del Diablo#Puede usarse dos veces"},
{"537", "Lil Spewer", "+1 píldora#Familiar que deja un rastro de creep#El tipo de creep cambia cada vez que uses una píldora"},
{"538", "Marbles", "Deja caer 3 trinkets aleatorios#Que te golpeen puede añadir el efecto del trinket permanentemente"},
{"539", "Mystery Egg", "Genera un enemigo encantado cuando te golpean#Genera aliados más fuertes cuantas más habitaciones limpies sin que te golpeen"},
{"540", "Flat Stone", "Las lágrimas rebotan en el suelo#Al salpicar, las lágrimas hacen daño"},
{"541", "Marrow", "+1 corazón de hueso#Genera 3 corazones rojos"},
{"542", "Slipped Rib", "Orbital#Refleja los projectiles"},
{"543", "Hallowed Ground", "Genera una caca blanca cuando te golpean#(La caca blanca tiene un aura que aumenta las lágrimas"},
{"544", "Pointy Rib", "Clavo que levita frente a Isaac#Inflige 6 veces tu daño"},
{"545", "Book of the Dead", "Genera huesos que orbitan a tu alrededor o Bonies aliados#El efecto dura en esta habitación"},
{"546", "Dad's Ring", "Otorga un aura que congela a los enemigos"},
{"547", "Divorce Papers", "+1 un corazón de hueso#↑ +0,7 de lágrimas#Genera el trinket Mysterious Paper"},
{"548", "Jaw Bone", "Familiar tipo boomerang#Inflige el doble del daño"},
{"549", "Brittle Bones", "Remplaza todos los contenedores de corazón por 6 corazones de hueso#Perder un corazón de hueso dispara lágrimas en todas las direcciones"},
{"550", "Broken Shovel", "Los pies de mamá te atacarán constantemente#Al usarlo los pies dejarán de caer en esta habitación#!¡Intenta ganar la Bossrush con esto!"},
{"551", "Broken Shovel", "Segunda parte de la pala rota#Úsala en el montón de tierra en la \"Dark Room\"(La Sala oscura)"},
{"552", "Mom's Shovel", "Genera una trampilla hacia la siguiente planta#Úsala en el montón de tierra en la \"Dark Room\"(La Sala oscura)"},
}

---------- Trinkets ----------
EID.descriptions["spa"].trinkets={
{"1", "Swallowed Penny", "Generas monedas cuando te golpean"},
{"2", "Petrified Poop", "Las cacas dejan caer más recolectables"},
{"3", "AAA Battery", "Se necesita 1 carga menos en los objetos activables"},
{"4", "Broken Remote", "Te teletransporta de manera aleatoria al usar un objeto"},
{"5", "Purple Heart", "Más campeones enemigos#Más salas de desafío de jefe"},
{"6", "Broken Magnet", "Imán de monedas"},
{"7", "Rosary Bead", "Aumenta la probabilidad de abrir la Sala del Ángel"},
{"8", "Cartridge", "Probabilidad de activar el efecto de Gamekid cuando te golpean"},
{"9", "Pulse Worm", "Las lágrimas aumentan y disminuyen su tamaño#Afecta a la hitbox de la lágrima"},
{"10", "Wiggle Worm", "Las lágrimas se mueven en ondas#↑ Más lágrimas"},
{"11", "Ring Worm", "Las lágrimas se mueven en espiral"},
{"12", "Flat Worm", "Lágrimas más grandes"},
{"13", "Store Credit", "Un objeto de la tienda es gratis"},
{"14", "Callus", "Ni los pinchos ni el creep te hacen daño"},
{"15", "Lucky Rock", "Destruir rocas genera monedas"},
{"16", "Mom's Toenail", "El pie de mamá cae sobre los enemigos cada 60 segundos"},
{"17", "Black Lipstick", "Más corazones negros"},
{"18", "Bible Tract", "Más corazones eternos"},
{"19", "Paper Clip", "Desbloquea cofres sin usar llaves"},
{"20", "Monkey Paw", "Al estar a medio corazón, deja caer un corazón negro#!!! 3 usos"},
{"21", "Mysterious Paper", "Imita \"Polaroid\", \"The Negative\", \"Missing Poster\" y \"Missing Page\""},
{"22", "Daemon's Tail", "!!! Convierte:#corazones rojos en corazones negros#Se generan menos corazones"},
{"23", "Missing Poster", "Al morir en la Sala del sacrificio revives como \"The Lost\""},
{"24", "Butt Penny", "Te tiras pedos al coger monedas"},
{"25", "Mysterious Candy", "Te tiras un pedo o generas una caca cada 30 segundos"},
{"26", "Hook Worm", "Las lágrimas se mueven en ángulos rectos"},
{"27", "Whip Worm", "↑ +0,5 de velocidad de disparo"},
{"28", "Broken Ankh", "22% de probabilidad de revivir como \"Blue Baby\""},
{"29", "Fish Head", "Genera una mosca azul cuando te golpean"},
{"30", "Pinky Eye", "Dispara lágrimas envenenadas de manera aleatoria"},
{"31", "Push Pin", "Dispara lágrimas penetrantes de manera aleatoria"},
{"32", "Liberty Cap", "Efecto aleatorio de champiñón en la habitación#Puede revelar las habitaciones especiales en el minimapa"},
{"33", "Umbilical Cord", "Al estar a medio corazón, aparece un pequeño Steven"},
{"34", "Child's Heart", "Genera más corazones rojos"},
{"35", "Curved Horn", "↑ +2 de daño"},
{"36", "Rusted Key", "Aparecen más cofres y llaves"},
{"37", "Goat Hoof", "↑ +0,15 de velocidad"},
{"38", "Mom's Pearl", "Recibes más corazones de alma"},
{"39", "Cancer", "↑ Más lágrimas"},
{"40", "Red Patch", "↑ Probabilidad de recibir +1,8 de daño cuando te golpean"},
{"41", "Match Stick", "Aparecen más bombas#!!! Elimina \"The Tick\" (la garrapata)"},
{"42", "Lucky Toe", "↑ +1 de suerte"},
{"43", "Cursed Skull", "Al estar a medio corazón, te teletransportaa la última habitación"},
{"44", "Safety Cap", "Aparecen más píldoras"},
{"45", "Ace of Spades", "Aparecen más cartas"},
{"46", "Isaac's Fork", "Posibilidad de curarse medio corazón al limpiar la habitación"},
{"47", "", "<unused>"},
{"48", "A Missing Page", "Cuando te golpean, posibilidad de que se produzca el efecto del \"Necronomicon\""},
{"49", "Bloody Penny", "Genera medio corazón al coger monedas"},
{"50", "Burnt Penny", "Genera bombas al coger monedas"},
{"51", "Flat Penny", "Genera monedas al coger llaves"},
{"52", "Counterfeit Penny", "Probabilidad de conseguir más monedas al coger monedas"},
{"53", "Tick", "15% menos de vida del jefe#Cura 1 corazón rojo al entrar a la Sala del jefe"},
{"54", "Isaac's Head", "Familiar con lágrimas penetrantes"},
{"55", "Maggy's Faith", "Recibe un corazón eterno al empezar una nueva planta"},
{"56", "Judas' Tongue", "Reduce los precios del Pacto del Diablo"},
{"57", "???'s Soul", "Familiar que rebota por la habitación#Dispara en la misma dirección que el jugador"},
{"58", "Samson's Lock", "↑ Probabilidad de ganar 0,5 de daño al matar un enemigo"},
{"59", "Cain's Eye", "25% de probabilidad de revelar los iconos del mapa al empezar una nueva planta"},
{"60", "Eve's Bird Foot", "Posibilidad de generar un pájaro muerto al matar un enemigo"},
{"61", "The Left Hand", "Convierte todos los cofres en cofres rojos"},
{"62", "Shiny Rock", "Las rocas especiales brillan cada 10 segundos"},
{"63", "Safety Scissors", "Convierte las bombas troll en bombas"},
{"64", "Rainbow Worm", "Efecto de gusano aleatorio"},
{"65", "Tape Worm", "↑ Duplica el rango"},
{"66", "Lazy Worm", "↓ -0,4 de velocidad de disparo#↑ +4 rango"},
{"67", "Cracked Dice", "Efecto de dado aleatorio cuando te golpean"},
{"68", "Super Magnet", "Imán para recolectables y enemigos"},
{"69", "Faded Polaroid", "Te camufla de manera aleatoria#Desorienta a los enemigos"},
{"70", "Louse", "Posibilidad de generar una araña azul"},
{"71", "Bob's Bladder", "Las bombas sueltan creep"},
{"72", "Watch Battery", "Genera más baterías"},
{"73", "Blasting Cap", "Explotar bombas puede generar más bombas"},
{"74", "Stud Finder", "Aparecen más trampillas"},
{"75", "Error", "Efecto de trinket aleatorio para cada habitación"},
{"76", "Poker Chip", "50% de probabilidad de conseguir más recolectables o 50% de no conseguir nada o un enemigo"},
{"77", "Blister", "Aumenta el empuje"},
{"78", "Second Hand", "Dobla la duración de los efectos en enemigos"},
{"79", "Endless Nameless", "La posibilidad de que al usar una píldora o una carta, esta reaparezca"},
{"80", "Black Feather", "↑ +0,2 de daño por cada objeto del diablo que tengas"},
{"81", "Blind Rage", "La invencibilidad dura más"},
{"82", "Golden Horse Shoe", "+15% de posibilidad de obtener dos Salas del tesoro en la siguiente planta"},
{"83", "Store Key", "Abre las tiendas gratis"},
{"84", "Rib of Greed", "Greed/Super Greed ya no aparece en la tienda"},
{"85", "Karma", "Usar un máquina de donación puede curarte o generar un mendigo"},
{"86", "Lil Larva", "Romper una caca genera una mosca azul"},
{"87", "Mom's Locket", "Cura medio corazón al usar llaves#Los medios corazones aparecen como corazones enteros"},
{"88", "NO!", "Poca probabilidad de que aparezcan objetos activables en la Sala del tesoro"},
{"89", "Child Leash", "Los familiares están más cerca del jugador y entre ellos"},
{"90", "Brown Cap", "La caca explota cuando la destruyes"},
{"91", "Meconium", "Aumenta la probabilidad de que aparezcan cacas negras"},
{"92", "Cracked Crown", "↑ Las estadísticas basadas en objetos de Isaac aumentan son un 33% más efectivas#↑ +0,2 de lágrimas#↑ -1 de retraso de lágrima"},
{"93", "Used Diaper", "Las moscas enemigas son aliadas"},
{"94", "Fish Tail", "Duplica todas las moscas y arañas azules"},
{"95", "Black Tooth", "Posibilidad de disparar un diente negro aleatoriamente"},
{"96", "Ouroboros Worm", "Las lágrimas se mueven rápido en espiral"},
{"97", "Tonsil", "Posibilidad de recibir un familiar cuando te golpean#Hasta 2 familiares"},
{"98", "Nose Goblin", "Probabilidad de disparar lágrimas venenosas que se pegan a los enemigos"},
{"99", "Super Ball", "Probabilidad de disparar lágrimas que rebotan"},
{"100", "Vibrant Bulb", "!!! Al tener un objeto activable cargado al completo:#↑ +0,25 de velocidad#↑ +0,75 de rango#↑ +0,2 de lágrimas#↑ +0,10 de velocidad de disparo#↑ +0,5 de daño#↑ +1 de suerte"},
{"101", "Dim Bulb", "!!! Al tener un objeto activable descargado :#↑ +0,5 de velocidad#↑ +1,5 de rango#↑ +0,4 de lágrimas#↑ +0,3 de velocidad de disparo#↑ +1,5 de daño#↑ +2 de suerte"},
{"102", "Fragmented Card", "+1 sala secreta adicional por planta"},
{"103", "Equality!", "!!! Cuando tienes el mismo número de monedas, llaves y bombas:#Convierte los medios recolectables en dobles"},
{"104", "Wish Bone", "Posibilidad de generar un objeto al ser golpeado#Se acaba destruyendo"},
{"105", "Bag Lunch", "Posibilidad de generar un objeto de vida al ser golpeado#Se acaba destruyendo"},
{"106", "Lost Cork", "Aumenta el radio de cualquier creep que produzcas"},
{"107", "Crow Heart", "Al recibir daño, los corazones rojos son dañados antes que los de alma o negros. No evita perder pacto a causa de eso"},
{"108", "Walnut", "Probabilidad de soltar un recolectable o trinket aleatoreo al ser golpeado por una explosión#Se acaba destruyendo"},
{"109", "Duct Tape", "Hace que los orbitales dejen de moverse"},
{"110", "Silver Dollar", "Ahora aparecen tiendas en el Útero de Mamá"},
{"111", "Bloody Crown", "Ahora aparecen salas del tesoro en el Útero de Mamá"},
{"112", "Pay To Win", "Las máquinas de restock aparecen en la Sala del tesoro. "},
{"113", "Locust of War", "Genera una mosca explosiva al entrar en una habitación"},
{"114", "Locust of Pestilence", "Genera una mosca venenosa al entrar en una habitación"},
{"115", "Locust of Famine", "Genera una mosca que ralentiza al entrar en una habitación"},
{"116", "Locust of Death", "Al entrar a una habitación con enemigos, genera una mosca que inflige cuatro veces tu daño"},
{"117", "Locust of Conquest", "Al entrar a una habitación con enemigos, genera 2-5 moscas que infligen el doble de tu daño"},
{"118", "Bat Wing", "Posibilidad de obtener alas al ser golpeado#Dura esa habitación"},
{"119", "Stem Cell", "Cura medio corazón al cambiar de planta"},
{"120", "Hairpin", "Recarga el objeto activable al completo al entrar en la Sala del jefe"},
{"121", "Wooden Cross", "Te protege del primer daño recibido en cada planta"},
{"122", "Butter!", "Al usar el coleccionable activable, el jugador lo soltará al suelo. "},
{"123", "Filigree Feather", "Hace que los ángeles generen objetos normales en lugar de piezas de llave"},
{"124", "Door Stop", "La última puerta usada se mantendrá abierta"},
{"125", "Extension Cord", "Genera un láser entre los familiares"},
{"126", "Rotten Penny", "Genera una mosca azul al coger monedas"},
{"127", "Baby-Bender", "Las lágrimas de los familiares son teledirigidas"},
{"128", "Finger Bone", "Posibilidad de ganar un corazón de hueso cuando te golpean"},
}

---------- Cards ----------
EID.descriptions["spa"].cards={
{"1", "0 - The Fool", "Te teletransporta de nuevo al inicio"},
{"2", "I - The Magician", "Lágrimas teledirigidas en la habitación actual"},
{"3", "II - The High Priestess", "El Pie de Mamá pisa a un enemigo"},
{"4", "III - The Empress", "↑ +2.35 de daño & +0,3 de velocidad en la habitación actual"},
{"5", "IV - The Emperor", "Teletransporta a la Sala del jefe "},
{"6", "V - The Hierophant", "Suelta 2 corazones de alma"},
{"7", "VI - The Lovers", "Suelta 2 corazones rojos"},
{"8", "VII - The Chariot", "Invencibilidad + daño por contacto durante 6 segundos"},
{"9", "VIII - Justice", "Genera 1 bomba, 1 llave, 1 moneda, 1 corazón"},
{"10", "IX - The Hermit", "Teletransporta a la tienda"},
{"11", "X - Wheel of Fortune", "Genera una tragaperras o una máquina de la fortuna"},
{"12", "XI - Strength", "↑ +1 de vida#↑ +0,3 de daño#↑ +0,3 de velocidad#para la habitación actual"},
{"13", "XII - The Hanged Man", "Permite volar en la habitación actual"},
{"14", "XIII - Death", "Inflige 40 de daño a todos los enemigos de la habitación"},
{"15", "XIV - Temperance", "Genera una máquina de donación de sangre"},
{"16", "XV - The Devil", "↑ +2 de daño en la habitación actual"},
{"17", "XVI - The Tower", "Invoca bombas troll"},
{"18", "XVII - The Stars", "Teletransporta a la Sala del tesoro"},
{"19", "XVIII - The Moon", "Teletransporta a la Sala secreta"},
{"20", "XIX - The Sun", "Inflige 100 de daño a todos los enemigos #Vida al completo#Muestra el mapa completo"},
{"21", "XX - Judgement", "Genera un mendigo"},
{"22", "XXI - The World", "Muestra el mapa completo y los tipos de habitación"},
{"23", "2 of Clubs", "Duplica las bombas"},
{"24", "2 of Diamonds", "Duplica el dinero"},
{"25", "2 of Spades", "Duplica las llaves"},
{"26", "2 of Hearts", "Duplica los corazones rojos #Solo tiene efecto curativo"},
{"27", "Ace of Clubs", "Convierte todos los recolectables en bombas"},
{"28", "Ace of Diamonds", "Convierte todos los recolectables en monedas"},
{"29", "Ace of Spades", "Convierte todos los recolectables en llaves"},
{"30", "Ace of Hearts", "Convierte todos los recolectables en corazones"},
{"31", "Joker", "Teletransporta a la Sala del Diablo/Ángel"},
{"32", "Hagalaz", "Destruye todas las rocas de la habitación"},
{"33", "Jera", "Duplica los recolectables de la habitación"},
{"34", "Ehwaz", "Genera una trampilla"},
{"35", "Dagaz", "+1 corazón de alma#Elimina efectos de maldición"},
{"36", "Ansuz", "Visión completa del mapa en este planta"},
{"37", "Perthro", "Cambia los objetos coleccionables"},
{"38", "Berkano", "Genera 3 arañas azules y 3 moscas azules"},
{"39", "Algiz", "Invencibilidad durante 30 segundos"},
{"40", "Blank Rune", "Efecto de runa aleatorio"},
{"41", "Black Rune", "Inflige 40 de daño a todos los enemigos#Estadística aleatoria por cada objeto coleccionable de la habitación# (Destruye todos los objetos de la habitación)"},
{"42", "Chaos Card", "Carta lanzable que mata al instante"},
{"43", "Credit Card", "Borra el precio de todos los objetos de la tienda actual o el Pacto con el Diablo, haciendo que todo sea gratis"},
{"44", "Rules Card", "Al usarlo muestra \"helpful\" consejos"},
{"45", "A Card Against Humanity", "Llena toda la habitación de caca"},
{"46", "Suicide King", "Te mata instantáneamente y genera 10 recolectables/coleccionables en el suelo"},
{"47", "Get Out Of Jail Free Card", "Abre todas las puertas de la habitación actual"},
{"48", "? Card", "Activa el objeto activable sin gastar cargas "},
{"49", "Dice Shard", "Cambia todos los pedestales y recolectables de la habitación actual"},
{"50", "Emergency Contact", "Dos manos de Mamá caen y cogen a un enemigo"},
{"51", "Holy Card", "Otorga el efecto de Manto Sagrado (Holy Mantle) en una habitación#(El siguiente daño recibido es 0)"},
{"52", "Huge Growth", "↑ +7 de daño#↑ +30 de rango#↑ +Tamaño#Rompe rocas#El efecto es para la habitación actual"},
{"53", "Ancient Recall", "Al usarla genera 3 cartas aleatorias"},
{"54", "Era Walk", "Ralentiza a los enemigos y las lágrimas de Isaac. Aporta más velocidad#El efecto es para la habitación actual"},
}


---------- Pills ----------

EID.descriptions["spa"].unidentifiedPill = "Píldora sin identificar"

EID.descriptions["spa"].pills={
{"0", "Bad Trip", "Genera una nube de gas"},
{"1", "Balls of Steel", "Inflige 1 corazón de daño"},
{"2", "Bombs are Key", "+2 corazones de alma"},
{"3", "Explosive Diarrhea", "Cambia el número de bombas por el de llaves"},
{"4", "Full Health", "Invoca 5 bombas troll"},
{"5", "Health Down", "Vida al completo"},
{"6", "Health Up", "↓ 1 menos de vida"},
{"7", "I Found Pills", "↑ 1 más de vida"},
{"8", "Puberty", "Sin efecto"},
{"9", "Pretty Fly", "Al comer 3 te transformas en Adulto "},
{"10", "Range Down", "Añade 1 mosca orbital"},
{"11", "Range Up", "↓ -2 de rango"},
{"12", "Speed Down", "↑ +2.5 de rango"},
{"13", "Speed Up", "↓ -0,12 de velocidad"},
{"14", "Tears Down", "↑ +0,15 de velocidad"},
{"15", "Tears Up", "↓ -0,28 de lágrimas"},
{"16", "Luck Down", "↑ +0,35 de lágrimas"},
{"17", "Luck Up", "↓ -1 de suerte"},
{"18", "Telepills", "↑ +1 de suerte"},
{"19", "48 Hour Energy!", "Teletransporta a una habitación aleatoria"},
{"20", "Hematemesis", "Recarga tu objeto activable#Genera 1 o 2 baterias"},
{"21", "Paralysis", "Drena todos los corazones menos el último#Genera de 1 a 4 corazones rojos"},
{"22", "I can see forever!", "No puedes moverte durante unos segundos"},
{"23", "Pheromones", "Abre las habitaciones secretas de la planta actual"},
{"24", "Amnesia", "Encanta a todos los enemigos de la habitación"},
{"25", "Lemon Party", "Oculta el mapa"},
{"26", "R U A Wizard?", "Genera charcos que dañan a los enemigos"},
{"27", "Percs!", "Durante 60 segundos disparas en diagonal"},
{"28", "Addicted!", "Solo te hacen la mitad del daño en la habitación actual"},
{"29", "Re-Lax", "Recibe un corazón de daño en la habitación actual"},
{"30", "???", "Genera una caca al andar durante 2 segundos"},
{"31", "One makes you larger", "Maldición del Laberinto (Curse of the maze) en la planta actual"},
{"32", "One makes you small", "Creces#No afecta a la hitbox"},
{"33", "Infested!", "Te haces pequeño#La hitbox se hace más pequeña"},
{"34", "Infested?", "Genera 1 mosca azul por cada caca de la habitación"},
{"35", "Power Pill!", "Genera 1 araña azul por cada enemigo de la habitación#Genera entre 1 y 3 arañas cuando no hay enemigos"},
{"36", "Retro Vision", "Efecto de invencibilidad corto"},
{"37", "Friends Till The End!", "Pixela la pantalla durante 30 segundos"},
{"38", "X-Lax", "Invoca 3 moscas aliadas"},
{"39", "Something's wrong...", "Genera una piscina de creep resbaladizo"},
{"40", "I'm Drowsy...", "Genera una piscina de creep ralentizante"},
{"41", "I'm Excited!!!", "Ralentiza a todos los enemigos de la habitación"},
{"42", "Gulp!", "Acelera a todos los enemigos de la habitación"},
{"43", "Horf!", "Consume el trinket actual y ganas su efecto de manera permanente"},
{"44", "Feels like I'm walking on sunshine!", "Dispara una lágrima de Ipecac"},
{"45", "Vurp!", "Efecto de invencibilidad corto"},
} 

---------- Sacrifice Room ----------
EID.descriptions["spa"].sacrificeHeader = "[Siguiente pago de la Sala del Sacrificio]"

EID.descriptions["spa"].sacrifice={
{"1", "", "50% de probabilidad de 1 moneda#100% de probabilidad de 1 bomba, al matar al Jefe de B1 en menos de 1 minuto"},
{"2", "", "50% de probabilidad de 1 moneda#100% de probabilidad de 1 bomba, al matar al Jefe de B1 en menos de 1 minuto"},
{"3", "", "67% de más de probabilidad de que aparezca la Sala del Ángel en lugar de la del Diablo"},
{"4", "", "50% de probabilidad de 1 cofre aleatorio"},
{"5", "", "33% de probabilidad de 3 monedas#67% más de probabilidad de que aparezca la Sala del Ángel en lugar de la del Diablo"},
{"6", "", "33% de probabilidad de teleportar a la Sala del Ángel/Diablo#67% de probabilidad de un cofre aleatorio"},
{"7", "", "33% de probabilidad de 1 objeto aleatorio de la Sala del Ángel#67% de probabilidad de 1 corazón de alma"},
{"8", "", "100% de probabilidad de generar 7 bombas troll"},
{"9", "", "100% de probabilidad de generar al ángel \"Uriel\""},
{"10", "", "50% de probabilidad de 7 corazones de alma#50% de probabilidad de 30 monedas"},
{"11", "", "100% de probabilidad de generar al ángel \"Gabriel\""},
{"12", "", "50% de probabilidad de teletransportar al piso de la  \"Dark Room\" (Habitación Oscura)"},
}

---------- Dice Room ----------
EID.descriptions["spa"].diceHeader = "[Efecto del dado]"

EID.descriptions["spa"].dice={
{"1", "", "Cambia tus objetos#(no afecta a los recolectables)"},
{"2", "", "Cambia los recolectables de la habitación"},
{"3", "", "Cambia todos los recolectables de la planta"},
{"4", "", "Cambia los objetos de los pedestales de la planta#No afecta los Pactos del Diablo"},
{"5", "", "Cambia y reinicia la planta actual"},
{"6", "", "Cambia todos tus objetos y recolectables, además de los objetos de toda la planta"}
}

---------- Transformations ----------
EID.descriptions["spa"].transformations = {
"",								-- 0 = none
"Guppy",						-- 1
"Fun Guy (Tipo divertido)",		-- 2
"Lord of the Flies (Señor de las moscas)",-- 3
"Conjoined (Unidos)",			-- 4
"Spun (Colocado)",				-- 5
"Mom (Mamá)",					-- 6
"Oh crap (Oh, mierda)",			-- 7
"Bob",							-- 8
"Leviatán",						-- 9
"Serafín",						-- 10
"Super Bum",					-- 11
"Bookworm (Ratón de Biblioteca)",		-- 12
"Spider Baby (Bebé araña)",		-- 13
"Adult",						-- 14
"Stompy"						-- 15
}
