---------------------------------------
-----  Basic Spanish descriptions -----
---------------------------------------

-- FORMAT: Item ID | Name| Description
-- '#' = starts new line of text

--Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning
 
-- init spa table
EID.descriptions["spa"] = {}
EID.descriptions["spa"].custom = {} -- table for custom entity descriptions
 
EID.descriptions["spa"].collectibles={
	{"1", "La cebolla triste", "↑ +0,7 de lágrimas"},
	{"2", "El ojo interno", "Disparo triple#↓ Menos lágrimas"},
	{"3", "Doblador de cucharas", "Lágrimas teledirigidas"},
	{"4", "La cabeza de Cricket", "↑ +0,5 de daño#↑ +50 % de multiplicador de daño #+Empuje"},
	{"5", "Mi reflejo", "Otorga un efecto boomerang a las lágrimas#↑ +1,5 de rango#↑ +0,6 de velocidad de disparo#↑ +1 de tamaño de lágrima"},
	{"6", "Número uno", "↑ +1,5 de lágrimas#↓ -15,78 de rango#↑ +0,45 de tamaño de lágrima"},
	{"7", "Sangre del mártir", "↑ +1,0 de daño#↑ +50 % si tienes Book of Belial (El libro de Belial)"},
	{"8", "Hermano Bobby", "Familiar de lágrimas normales#Lágrimas de 3,5 de daño"},
	{"9", "Escatol", "Todas las moscas enemigas son aliadas"},
	{"10", "Halo de moscas", "+2 moscas orbitales#Bloquea proyectiles enemigos"},
	{"11", "¡1up!", "↑ +1 de vida#Reaparece con la vida al completo"},
	{"12", "Champiñón mágico", "↑ +1 de vida#↑ +0,3 de daño#↑ +50 % de multiplicador de daño#↑ +5,25 de rango#↑ +0,3 de velocidad#↑ +0,5 de tamaño de lágrima#¡Vida al completo!"},
	{"13", "El virus", "Toque venenoso#↓ -0,1 de velocidad#Los enemigos pueden soltar corazones negros al morir si están envenenados"},
	{"14", "Furia de esteroides", "↑ +0,6 de velocidad#↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"15", "<3", "↑ +1 de vida#Vida al completo"},
	{"16", "Hígado crudo", "↑ +2 de vida#Vida al completo"},
	{"17", "Llave de esqueleto", "+99 llaves"},
	{"18", "El dólar", "+99 monedas"},
	{"19", "¡Bum!", "+10 bombas"},
	{"20", "Trascendencia", "¡Vuela!"},
	{"21", "La brújula", "Muestra todos los iconos del mapa#No muestra el plano del mapa"},
	{"22", "Almuerzo", "↑ +1 de vida"},
	{"23", "Cena", "↑ +1 de vida"},
	{"24", "Postre", "↑ +1 de vida"},
	{"25", "Desayuno", "↑ +1 de vida"},
	{"26", "Carne podrida", "↑ +1 de vida"},
	{"27", "Cuchara de madera", "↑ +0,3 de velocidad"},
	{"28", "El cinturón", "↑ +0,3 de velocidad"},
	{"29", "Ropa interior de Mamá", "↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"30", "Tacones de Mamá", "↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"31", "Pintalabios de Mamá", "↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"32", "Percha de alambre", "↑ +0,7 de lágrimas"},
	{"33", "La Biblia", "Vuela en la habitación actual#Mata el Pie de Mamá y el Corazón de Mamá al instante#!!! Te mata al usarlo contra Satán"},
	{"34", "El libro de Belial", "↑ +2 de daño#↑ +12,5% de probabilidad de Pacto con el Diablo#↑ +50% de multiplicador de daño si tienes Blood of the Martyr (Sangre del mártir)"},
	{"35", "El Necronomicón", "Inflige 40 de daño a toda la habitación"},
	{"36", "La caca", "Genera una caca en el suelo#Se puede poner al lado de una fosa y destruirla con una bomba para hacer un puente"},
	{"37", "Sr. Bum", "Genera una gran bomba bajo el jugador que inflige 110 de daño"},
	{"38", "Cabeza de Tammy", "Dispara un círculo de 10 lágrimas alrededor de Isaac"},
	{"39", "Sujetador de Mamá", "Congela a todos los enemigos de la habitación durante 4 segundos"},
	{"40", "¡Kamikaze!", "Provoca una explosión en la ubicación del jugador"},
	{"41", "Compresa de Mamá", "Asusta a todos los enemigos de la habitación actual durante 5 segundos"},
	{"42", "Cabeza podrida de Bob", "Bomba venenosa lanzable"},
	{"43", "", "<No existe el objeto>"},
	{"44", "¡Teletransporte!", "Teletransporta a Isaac a una habitación aleatoria (excepto a la habitación I AM ERROR)"},
	{"45", "Corazón Ñam", "Cura 1 corazón rojo"},
	{"46", "Pie de la suerte", "↑ +1,0 de suerte#Más probabilidad de ganar al apostar#Aumenta las posibilidades de que caiga un recolectable al limpiar una habitación"},
	{"47", "Control remoto del doctor", "¡Epic Fetus (Feto épico) a la carta!#Ataques aéreos dirigidos"},
	{"48", "Flecha de Cupido", "Lágrimas penetrantes"},
	{"49", "¡Shoop da Whoop!", "Rayo de Brimstone (Fuego infernal) con gran daño"},
	{"50", "Steven", "↑ +1 de daño"},
	{"51", "Pentagrama", "↑ +1,0 de daño#↑ +10% probabilidad de Pacto con el Diablo"},
	{"52", "Dr. Fetus", "¡Lágrimas bomba!"},
	{"53", "Imán", "Acerca los recolectables al jugador"},
	{"54", "Mapa del tesoro", "Muestra el plano del mapa"},
	{"55", "Ojo de Mamá", "Posibilidad  de disparar una lágrima hacia atrás#100 % de probabilidad si tienes 2 de suerte"},
	{"56", "Accidente con limón", "Crea una piscina de limonada#Inflige 66 de daño por contacto cada segundo"},
	{"57", "Admiración distante", "Mosca orbital de medio alcance#Inflige 75 de daño por contacto cada segundo"},
	{"58", "Libro de las sombras", "Invencibilidad durante 10 segundos"},
	{"59", "", "<No existe el objeto>"},
	{"60", "La escalera", "Camina sobre fosas de 1 cuadrado de distancia"},
	{"61", "", "<No existe el objeto>"},
	{"62", "Encanto del vampiro", "Cura medio corazón cada 13 enemigos asesinados"},
	{"63", "La batería", "El objeto activable se puede cargar el doble"},
	{"64", "Ofertas de Steam", "-50 % en la compra de objetos#Tener dos hace que todo sea gratis"},
	{"65", "Libro de recetas anarquista", "Genera 6 bombas troll cerca del centro de la habitación"},
	{"66", "El reloj de arena", "Ralentiza a los enemigos durante 8 segundos"},
	{"67", "Hermana Maggy", "Familiar de lágrimas normales#Inflige 3,5 de daño"},
	{"68", "Tecnología", "Las lágrimas son láseres"},
	{"69", "Leche con chocolate", "Carga las lágrimas#↑ Hasta un 400 % más de daño#↓ Menos lágrimas"},
	{"70", "Hormonas de crecimiento", "↑ +1,0 de daño#↑ +0,4 de velocidad"},
	{"71", "Mini Champi", "↑ +0,3 de velocidad#↓ -4,25 de rango*#↑ +1,5 de tamaño de lágrima*#(*Ambas aumentan un poco el rango) ↑ Te haces más pequeño"},
	{"72", "Rosario", "+3 corazones de alma#La Biblia es más común"},
	{"73", "Cubo de carne", "NVL1: Orbital#NVL2: Orbital que dispara#NVL3: Meat boy NVL 1#NVL4: Meat boy NVL 2"},
	{"74", "Una moneda de 25 centavos", "+25 monedas"},
	{"75", "PHD", "Mejores píldoras# +1 píldora#Cura 2 corazones#Más dinero de las máquinas de donación de sangre"},
	{"76", "Visión de rayos X", "Muestra las entradas de salas secretas"},
	{"77", "Mi pequeño unicornio", "Invencibilidad + 40 de daño por contacto"},
	{"78", "Libro de revelaciones", "+1 corazón de alma# Más probabilidad de que aparezcan jinetes#↑ +17,5 % probabilidad de Pacto con el Diablo"},
	{"79", "La marca", "↑ +1,0 de daño#↑ +0,2 de velocidad#+1 corazón de alma"},
	{"80", "El pacto", "↑ +0,5 de daño#↑ +0,7 de lágrimas#+2 corazones de alma"},
	{"81", "Gato muerto", "↑ +9 vidas#Revive con 1 corazón"},
	{"82", "Señor del pozo", "Vuela#↑ +0,3 de velocidad"},
	{"83", "El clavo", "+1 corazón de alma#↑ +0,7 de daño#↓ -0,18 de velocidad#Inflige daño por contacto#Rompe rocas"},
	{"84", "¡Hay que ir más profundo!", "Genera una trampilla para saltar el nivel#10 % de probabilidad de que se abra una trampilla a una planta secreta"},
	{"85", "Baraja de cartas", "Genera 1 carta"},
	{"86", "Diente de Monstro", "Invoca a Monstro y este aplasta a un enemigo"},
	{"87", "Cuernos de Loki", "Posibilidad de disparar en 4 direcciones"},
	{"88", "Pequeño Chubby", "Familiar que carga hacia delante#Inflige 52,5 de daño por contacto cada segundo, 3,5 por tick"},
	{"89", "Mordedura de araña", "Ralentiza a los enemigos"},
	{"90", "La pequeña roca", "↑ +1 de daño#↑ +0,2 de lágrimas#↓ -0,2 de velocidad"},
	{"91", "Casco de espeleólogo", "Muestra lo que hay detrás de las puertas#Salas secretas, ultrasecretas y salas de minijefes"},
	{"92", "Supervendaje", "↑ +1 de vida#+2 corazones de alma"},
	{"93", "La consola", "Invencibilidad +daño por contacto#Comerse un enemigo recupera vida"},
	{"94", "Saco de peniques", "Suelta una moneda aleatoria cada 2 habitaciones"},
	{"95", "Robo-Baby", "Lágrimas láser#Inflige 3,5 de daño"},
	{"96", "Pequeño C.H.A.D.", "Suelta medio corazón cada 3 habitaciones"},
	{"97", "El libro del pecado", "Genera un recolectable aleatorio"},
	{"98", "La reliquia", "Suelta 1 corazón de alma cada 4 habitaciones"},
	{"99", "Pequeño Gish", "Lágrimas ralentizantes#Inflige 3,5 de daño"},
	{"100", "Pequeño Steven", "Lágrimas teledirigidas#Inflige 3,5 de daño"},
	{"101", "El halo", "↑ + 1 de vida#↑ +0,3 de daño#↑ +0,2 de lágrimas#↑ +0,25 de rango#↑ +0,3 de velocidad#↑ +0,5 de tamaño de lágrima"},
	{"102", "El bote de pastillas de Mamá", "Genera 1 píldora"},
	{"103", "Resfriado común", "Lágrimas venenosas (aleatorio)"},
	{"104", "El parásito", "Las lágrimas se rompen al chocar#Las lágrimas partidas infligen la mitad de daño"},
	{"105", "El D6", "Cambia los pedestales de la habitación actual"},
	{"106", "Sr. Mega", "↑ x2,25 el daño de bomba #+5 bombas"},
	{"107", "Las tijeras dentadas", "Vuela#Tu cuerpo ataca a los enemigos e inflige 82,5 de daño por segundo"},
	{"108", "La hostia", "Todo el daño recibido se reduce a medio corazón"},
	{"109", "Dinero = Poder", "↑ +0,04 de daño por cada moneda que tengas"},
	{"110", "Lentillas de Mamá", "Probabilidad de disparar lágrimas congelantes#↑ +0,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"111", "La judía", "Pedo venenoso"},
	{"112", "Ángel de la guarda", "Orbital#Acelera todos los orbitales#Bloquea proyectiles#Inflige 105 de daño por contacto cada segundo"},
	{"113", "Bebé demoníaco", "Torreta que dispara automáticamente#Inflige 3 de daño"},
	{"114", "El cuchillo de Mamá", "Cuchillo controlable#El x2 de daño por contacto, x6 de daño lanzado al máximo"},
	{"115", "Tablero de güija", "Lágrimas espectrales"},
	{"116", "9 voltios", "-1 carga para los objetos activables#Carga al completo el objeto actual"},
	{"117", "Pájaro muerto", "Cuando te golpean genera un pájaro#El pájaro inflige 4 de daño por contacto cada segundo"},
	{"118", "El fuego del infierno", "Carga un chorro de sangre que inflige daño constante"},
	{"119", "Bolsa de sangre", "↑ +1 de vida#↑ +0,3 de velocidad#Cura 5 corazones"},
	{"120", "Champiñón raro", "↑ +1,7 de lágrimas#↑ +0,3 de velocidad#↓ 10 % menos de daño#↓ -0,4 de daño menos adicional"},
	{"121", "Champiñón raro", "↑ +1 contenedor de corazon vacío#↑ +0,3 de daño#↑ +0,25 de rango#↓ -0,1 de velocidad#↑ +0,5 de tamaño de lágrima"},
	{"122", "Puta de Babilonia", "!!! Al tener medio corazón:#↑ +1,5 de daño#↑ +0,3 de velocidad"},
	{"123", "Manual de monstruos", "Familiar aleatorio en la habitación actual"},
	{"124", "Manuscritos del Mar Muerto", "Efecto de objeto activo aleatorio"},
	{"125", "Bobby-Bomba", "Bombas teledirigidas#+5 Bombas"},
	{"126", "Cuchilla de afeitar", "↑ +1,2 de daño en la habitación actual#↓ Te inflige 1 corazón de daño"},
	{"127", "Olvídame ya", "{{Warning}} UN SOLO USO {{Warning}} #Reinicia toda la planta"},
	{"128", "Solo para siempre", "Mosca orbital de larga distancia #Inflige 30 de daño por contacto cada segundo"},
	{"129", "Cubo de manteca", "↑ +2 de contenedores de vida vacíos#↓ -0,2 de velocidad#Cura medio corazón"},
	{"130", "Un poni ", "Permite volar mientras lo tengas#Establece tu velocidad en 1,5 en caso de que tengas menos que eso#Embiste en una dirección"},
	{"131", "Bolsa de bombas", "Deja caer 1 bomba cada pocas habitaciones"},
	{"132", "Un trozo de carbón", "Más daño basado en la distancia que recorra la lágrima"},
	{"133", "Pata de Guppy", "!!! Convierte:#1 corazón rojo en 3 corazones de alma"},
	{"134", "Cola de Guppy", "Aparecen más cofres dorados#Menos llaves"},
	{"135", "Bolsa IV", "Banco de sangre portátil#Medio corazón = 1-3 monedas"},
	{"136", "Mejor amigo", "Muñeco explosivo#Atrae a los enemigos"},
	{"137", "Detonador remoto", "Detona bombas al gusto#+5 bombas"},
	{"138", "Estigma", "↑ +1 de vida#↑ +0,3 de daño"},
	{"139", "Bolso de Mamá", "Puedes tener 2 trinkets"},
	{"140", "Maldición de Bob", "Bombas venenosas#+5 bombas"},
	{"141", "Chico espectacular", "Genera 7 monedas aleatorias"},
	{"142", "Escapulario", "Si te dañan menos de medio corazón, ganas 1 corazón de alma#(Uno por habitación)"},
	{"143", "Bola rápida", "↑ +0,3 de velocidad#↑ +0,2 de velocidad de disparo"},
	{"144", "Amigo vagabundo", "Convierte monedas en recolectables"},
	{"145", "Cabeza de Guppy", "Genera de 2 a 4 moscas azules"},
	{"146", "Carta de rezo", "+1 corazón eterno"},
	{"147", "Hacha de Notch", "Rompe las rocas de la habitación actual al tocarlas"},
	{"148", "Infestación", "Genera moscas cuando te golpean"},
	{"149", "Ipecacuana", "Lágrimas explosivas"},
	{"150", "Amor duro", "Posibilidad de disparar dientes#El diente inflige (x 3,2) tu daño "},
	{"151", "El mulligan", "1/6 de probabilidad de generar una mosca al golpear un enemigo"},
	{"152", "Tecnología 2", "¡Láser permanente!#↓ -35% de daño"},
	{"153", "Araña mutante", "¡Disparo cuádruple!#↓ Menos lágrimas"},
	{"154", "Exfoliación química", "↑ +2 de daño para el ojo izquierdo"},
	{"155", "El mirón", "Flota por la habitación#Inflige 8 de daño por contacto cada segundo"},
	{"156", "Hábito", "Te da una carga cuando te golpean"},
	{"157", "Sed de sangre", "↑ Más daño cuando te golpean#Se aplica hasta 6 veces en cada planta#Dura toda la planta"},
	{"158", "Bola de cristal", "Muestra el mapa completo#Genera una carta aleatoria o un corazón de alma"},
	{"159", "Espíritu de la noche", "Vuela#Lágrimas espectrales"},
	{"160", "Rompe el cielo", "¡5 rayos de luz desde el cielo!#Inflige tu daño +20"},
	{"161", "Anj", "Reaparece como ??? (Blue Baby (Bebé Azul)) al morir"},
	{"162", "Cruz celta", "Probabilidad de ser invencible cuando te golpean"},
	{"163", "Bebé fantasma", "Familiar de lágrimas espectrales#Inflige 3,5 de daño"},
	{"164", "La vela", "Genera un fuego azul#Inflige daño por contacto#Bloquea lágrimas enemigas#Desaparece tras 2 segundos"},
	{"165", "Gato de nueve colas", "↑ +1 daño#↑ +0,23 de velocidad de disparo"},
	{"166", "D20", "Cambia los recolectables"},
	{"167", "Bebé arlequín", "Dispara dos lágrimas en forma de V#Inflige 4 de daño"},
	{"168", "Feto épico", "Ataque aéreo controlable en lugar de lágrimas#Inflige 20 veces tu daño"},
	{"169", "Polifemo", "¡Mega lágrimas!#↑ Aumenta el daño +4 y lo duplica#↓ Menos lágrimas"},
	{"170", "Papi patas largas", "Cae sobre los enemigos#Inflige 40 de daño cada segundo"},
	{"171", "Culo de araña", "Ralentiza a los enemigos cada 4 segundos#10 de daño a todos los enemigos"},
	{"172", "Daga de sacrificio", "Cuchillo orbital#Bloquea los disparos enemigos#Inflige 225 de daño cada segundo"},
	{"173", "Mitra", "Mayor probabilidad de encontrar corazones de alma"},
	{"174", "Bebé arcoiris", "Dispara lágrimas aleatorias#Inflige de 3 a 5 de daño"},
	{"175", "Llave de Papá", "Abre todas las puertas de la habitación actual, incluyendo las salas secretas#Puede abrir la puerta de Mega Satán"},
	{"176", "Células madre", "↑ +1 de vida#↑ +0,16 de velocidad de disparo"},
	{"177", "Tragaperras portátil", "Cambia una moneda por un recolectable aleatorio"},
	{"178", "Agua bendita", "Deja un rastro de creep cuando te golpean#Inflige 24 daño cada segundo"},
	{"179", "Destino", "Vuela#+1 corazón eterno"},
	{"180", "La judía negra", "Te tiras un pedo cuando te tocan"},
	{"181", "Poni blanco", "Permite volar mientras lo tengas#Establece tu velocidad en 1,5 si tienes menos de eso#Aparecen rayos de luz al embestir"},
	{"182", "Corazón sagrado", "Lágrimas teledirigidas#↑ +1 de vida#↑ Más daño#↓ -0,4 de lágrimas#↓ -25 % de velocidad de disparo#↑ +4,125 de rango"},
	{"183", "Palillo de dientes", "↑ +0,7 de lágrimas#↑ +0,16 de velocidad de disparo"},
	{"184", "Santo Grial", "↑ +1 de vida#Permite volar"},
	{"185", "Paloma muerta", "Vuela#Lágrimas espectrales"},
	{"186", "Derecho de sangre", "Inflige 40 de daño a cada enemigo#Te daña al usarlo"},
	{"187", "Bola de pelo de Guppy", "Bola de pelo creciente#Se mueve a tu alrededor#Crece al matar enemigos#Hace más daño cuanto más grande sea"},
	{"188", "Abel", "Copia tus movimientos#Dispara hacia el jugador#Inflige 3,5 de daño"},
	{"189", "Fanático de SMB", "↑ +1 de vida#↑ +0,3 de daño#↑ +0,2 de lágrimas#↑ +0,5 de rango#↑ +0,2 de velocidad#↑ +1,0 de tamaño de lágrima#Vida al completo"},
	{"190", "Pyro", "+99 Bombas"},
	{"191", "Billete de 3 dólares", "Efecto de lágrima aleatorio"},
	{"192", "Telepatía para tontos", "Lágrimas teledirigidas en la habitación actual"},
	{"193", "¡CARNE!", "↑ +1 de vida#↑ +0,3 de daño"},
	{"194", "Bola 8 mágica", "↑ +0,16 de velocidad de disparo#+1 carta"},
	{"195", "Monedero de Mamá", "Genera 4 píldoras"},
	{"196", "Pan comido", "+2 corazones de alma#↑ +0,4 de lágrimas"},
	{"197", "Zumo de Jesús", "↑ +0,5 de daño#↑ +0,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"198", "Caja", "Genera 1 recolectable de cada tipo"},
	{"199", "Llave de Mamá", "+2 llaves#Los cofres generan más recolectables"},
	{"200", "Sombra de ojos de Mamá", "Posibilidad de disparar lágrimas encantadas"},
	{"201", "Barra de hierro", "↑ +0,3 de daño#Posibilidad de aturdir a los enemigos"},
	{"202", "Toque de Midas", "Convierte a los enemigos en oro al tocarlos#Inflige daño de contacto basado en tu dinero#Los enemigos dorados dejan caer monedas"},
	{"203", "Paquete modesto", "Duplica todos los recolectables"},
	{"204", "Riñonera", "50 % de probabilidad de generar un recolectable aleatorio cuando te golpean"},
	{"205", "Enchufe puntual", "-2 corazones = Carga el objeto al completo cuando pulsas espacio#!!! Solo funciona si el objeto no está cargado"},
	{"206", "Guillotina", "↑ +1 de daño#↑ Más lágrimas#Tu cabeza es un orbital#Disparas desde la cabeza#La cabeza inflige daño por contacto"},
	{"207", "Bola de vendas", "NVL1: Orbital#NVL2: Orbital que dispara#NVL3: Bandage girl#NVL4: Bandage girl NVL2"},
	{"208", "Cinturón de campeón", "↑ +1 de daño#!!! Aparecen más campeones"},
	{"209", "Bombas del culo", "↑ +5 Bombas#Las explosiones aturden y dañan a todos los enemigos de la habitación"},
	{"210", "Hoja roída", "Invencible al quedarse quieto por 1 segundo"},
	{"211", "Bebé araña", "Genera una o dos arañas cuando te golpean"},
	{"212", "Collar de Guppy", "↑ 50 % de probabilidad de revivir"},
	{"213", "Lentilla perdida", "Lágrimas con escudo que bloquean los disparos enemigos#↓-0,16 de velocidad de disparo"},
	{"214", "Anémico", "↑ +5 de rango#Deja creep en el suelo cuando te golpean"},
	{"215", "Cabeza de cabra", "↑ 100 % de probabilidad de pacto con el Diablo{{DevilRoom}} o el Ángel{{AngelRoom}}"},
	{"216", "Batas ceremoniales", "↑ +1 de daño#+3 Corazones negros"},
	{"217", "Peluca de Mamá", "Probabilidad aleatoria de generar una araña azul al disparar#Cura 1 corazón al cogerlo"},
	{"218", "Placenta", "Regenera la vida poco a poco#↑ +1 de vida"},
	{"219", "Vendaje viejo", "↑ +1 contenedor de corazón vacío#Probabilidad aleatoria de dejar caer corazones cuando te golpean"},
	{"220", "Bombas tristes", "¡Explosión de lágrimas!#+5 Bombas"},
	{"221", "Cemento de caucho", "Las lágrimas rebotan"},
	{"222", "Anti-Gravedad", "↑ 2 de lágrimas#Lágrimas antigravedad"},
	{"223", "Piromaníaco", "Las explosiones te curan#+5 Bombas"},
	{"224", "El cuerpo de Cricket", "↑ +1 de lágrimas#↓ -10 de rango#Las lágrimas se dividen en 4 al impactar#Las lágrimas partidas infligen la mitad de daño"},
	{"225", "Gimpy", "Posibilidad de dejar caer corazones de alma o negros cuando te golpean#Posibilidad de dejar caer medio corazón rojo al matar a un enemigo"},
	{"226", "Loto negro", "↑ +1 de vida#+1 corazón de alma#+1 corazón negro"},
	{"227", "Hucha de cerdito", "+3 monedas#Genera una o dos monedas cuando te golpean#Genera 0 o 1 con Keeper"},
	{"228", "Perfume de Mamá", "Las lágrimas asustan a los enemigos#↑ +1 de lágrimas"},
	{"229", "El pulmón de Monstro", "Las lágrimas pueden cargarse y lanzarse como si fuera una pistola"},
	{"230", "Abadón", "↑ +1,5 de daño#↑ +0,2 de velocidad#Las lágrimas asustan a los enemigos#↓ Elimina todos los corazones rojos#+6 corazones negros"},
	{"231", "Bola de alquitrán", "Deja creep que ralentiza#Las lágrimas ralentizan"},
	{"232", "Cronómetro", "Ralentiza automáticamente (se activa por primera vez cuando te golpean)#↑ +0,3 de velocidad"},
	{"233", "Planeta enano", "Las lágrimas orbitan a tu alrededor#↑ +7,0 de tamaño de lágrima#Lágrimas espectrales"},
	{"234", "Infestación 2", "Al matar a un enemigo genera arañas "},
	{"235", "", "<El objeto no existe>"},
	{"236", "E. Coli", "Al tocar a los enemigos los convierte en caca"},
	{"237", "Toque mortal", "¡Dispara guadañas!#↑ +1,5 de daño#↓ -0,3 de lágrimas#Lágrimas penetrantes"},
	{"238", "Pieza 1 de llave", "!!! ¡Pieza de llave para la puerta de Mega Satán!#Aparecen más salas del Ángel{{AngelRoom}}"},
	{"239", "Pieza 2 de llave", "!!! ¡Pieza de llave para la puerta de Mega Satán!#Aparecen más salas del Ángel{{AngelRoom}}"},
	{"240", "Tratamiento experimental", "Todas las estadísticas ↑/↓ un número aleatorio"},
	{"241", "Contrato desde abajo", "Duplica los recolectables que cojas#No funciona en el modo Greed"},
	{"242", "Infamia", "50 % de posibilidad de bloquear lágrimas"},
	{"243", "Escudo de la trinidad", "Escudo que bloquea lágrimas"},
	{"244", "Tecnología 5", "Dispara lágrimas láseres aleatorias"},
	{"245", "20/20", "Duplica los disparos"},
	{"246", "Mapa azul", "Muestra las habitaciones secretas"},
	{"247", "¡Mejores amigos!", "Tus familiares infligen más daño"},
	{"248", "Mente colmena", "Las moscas y arañas azules duplican su daño"},
	{"249", "Hay opciones", "Aparecen 2 objetos de jefe en lugar de 1#!!! Solo puede cogerse uno"},
	{"250", "Bombas 2x1", "Duplica todas las bombas que cojas"},
	{"251", "baraja de principiante", "Puedes llevar 2 cartas#Convierte todas las píldoras en cartas"},
	{"252", "Bolsa pequeña", "Puedes llevar 2 píldoras#Convierte todas las cartas en píldoras"},
	{"253", "Costra mágica", "↑ +1 de suerte#↑ +1 de vida"},
	{"254", "Coágulo", "↑ +1 de daño#↑ +5 de rango#!!! Solo se aplica al ojo izquierdo"},
	{"255", "Tornillo", "↑ +0,5 de lágrimas#↑ +0,2 de velocidad de disparo"},
	{"256", "Bombas calientes", "Las bombas queman#+5 Bombas"},
	{"257", "Mente de fuego", "Las lágrimas están en llamas#Posibilidad de que las lágrimas exploten"},
	{"258", "Número perdido", "Cambia todos tus objetos cada vez que cambias de planta"},
	{"259", "Materia oscura", "↑ +1 de daño#Las lágrimas asustan a los enemigos"},
	{"260", "Vela negra", "Inmune a las maldiciones#+1 corazón negro#Más probabilidad de que aparezcan las salas del Diablo{{DevilRoom}} o del Ángel{{AngelRoom}}"},
	{"261", "Proptosis", "↑100 % más de daño#↓ El daño infligido disminuye en función de la distancia recorrida por la lágrima"},
	{"262", "Página perdida 2", "+1 corazón negro#Al tener menos de 1 corazón y medio, dañas a todos los enemigos de la habitación"},
	{"263", "", "<El objeto no existe>"},
	{"264", "Mosca inteligente", "Orbital que puede cargar contra los enemigos#Inflige 22,5 de daño cada segundo#Inflige 1,5 de daño por tick"},
	{"265", "Bebé seco", "Al ser golpeado por lágrimas enemigas, hay un 10% de posibilidad de dañar a todos los enemigos de la habitación"},
	{"266", "Saco jugoso", "Deja creep ralentizante#Posibilidad de generar 1 o 2 arañas aliadas al limpiar la habitación"},
	{"267", "Bebé robot 2.0", "Dispara láseres#Inflige 3,5 de daño por disparo#Se mueve hacia donde disparas"},
	{"268", "Bebé podrido", "Genera moscas azules al disparar"},
	{"269", "Bebé sin cabeza", "Deja creep que inflige 6 de daño cada segundo"},
	{"270", "Sanguijuela", "Cura medio corazón al matar enemigos#3,2 de daño cada segundo"},
	{"271", "Saco misterioso", "Genera recolectables aleatorios cada pocas habitaciones"},
	{"272", "Mosca grande y hermosa", "Mosca explosiva aliada#La explosión inflige 60 de daño"},
	{"273", "Cerebro de Bob", "Familiar bomba lanzable#La explosión inflige 60 de daño"},
	{"274", "Mejor amigo", "Al ser golpeado, ganas un orbital de rango medio#Inflige 75 de daño cada segundo"},
	{"275", "Pequeño fuego infernal", "Dispara un rayo que inflige 2,5 de daño cada segundo hasta un máximo de 20"},
	{"276", "Corazón de Isaac", "Gana un cuerpo invulnerable#!!! Cuando al familiar corazón le golpean te hace daño"},
	{"277", "Pequeño perseguidor", "Familiar fantasma aliado#Inflige 4 de daño cada segundo"},
	{"278", "Vagabundo oscuro", "!!! Convierte:#1,5 corazones rojos en 1 corazón de alma"},
	{"279", "Gran fanático", "Orbital grande#Inflige 30 de daño cada segundo"},
	{"280", "Sissy patas largas", "Invoca arañas azules en habitaciones hostiles"},
	{"281", "Saco de boxeo", "Los enemigos le atacarán a él en lugar de a ti"},
	{"282", "Cómo saltar", "Permite saltar"},
	{"283", "D100", "Cambia todos los recolectabes, pedestales y los objetos que tengas"},
	{"284", "D4", "Cambia los objetos que tengas"},
	{"285", "D10", "Cambia todos los enemigos de la habitación"},
	{"286", "Carta en blanco", "Copia el efecto de la carta que tengas"},
	{"287", "Libro de secretos", "Muestra partes del mapa"},
	{"288", "Caja de arañas", "Invoca de 1 a 4 arañas azules"},
	{"289", "Vela roja", "Lanza fuego rojo#La llama persiste hasta infligir daño 5 veces"},
	{"290", "El tarro", "Almacena hasta 4 corazones rojos para usarlos más tarde"},
	{"291", "¡Flus-flus!", "!!! Mata a enemigos y jefes caca de manera instantánea#Convierte a los enemigos en caca"},
	{"292", "Biblia satánica", "+1 corazón negro"},
	{"293", "Cabeza de Krampus", "Dispara un rayo de brimstone (fuego infernal) en las 4 direcciones"},
	{"294", "Judía de mantequilla", "Repele a los enemigos y proyectiles cercanos#10 % de probabilidad de convertirse en \"Wait What?\" (Espera, ¿qué?) al intercambiarlo por otro objeto activable y volverlo a coger"},
	{"295", "Dedos mágicos", "Daña toda la habitación con el doble de tu daño#Precio: 1 moneda"},
	{"296", "Conversor", "!!! Convierte:#2 corazones de alma/negros en un corazón rojo"},
	{"297", "Caja de Pandora", "!!! ÚNICO USO !#!!! Genera cosas en función del piso en el que se active:#B1: 2 corazones de alma #B2: 2 llaves y bombas#C1: 1 objeto de jefe#C2: B1+C1#D1: 4 corazones de alma#D2: 20 monedas#W1: 2 objetos de jefe#W2: Biblia#Sheol: 1 objeto del diablo+corazón negro#Catedral: 1 objeto de ángel + corazón de alma#Chest(cofre): 1 moneda"},
	{"298", "Muñón de unicornio", "Invencibilidad y +0,28 velocidad que dura hasta 6 segundos"},
	{"299", "Tauro", "¡Te hace más rápido en las habitaciones hostiles!#Invencibilidad al alcanzar la velocidad suficiente"},
	{"300", "Aries", "↑ +0,25 de velocidad#Tocar a los enemigos les daña"},
	{"301", "Cáncer", "+3 corazones de alma#Reduce a la mitad el daño que recibas en la habitación tras ser golpeado una vez"},
	{"302", "Leo", "¡Rompe las rocas al caminar!"},
	{"303", "Virgo", "Posibilidad de ser invencible cuando te tocan#Convierte píldoras negativas en positivas"},
	{"304", "Libra", "+6 monedas / llaves / bombas#¡Equilibra tus estadísticas!#!!! Cada estadística afectará también a otras estadísticas"},
	{"305", "Escorpio", "Lágrimas venenosas"},
	{"306", "Sagitario", "↑ +0,2 de velocidad#Lágrimas penetrantes"},
	{"307", "Capricornio", "↑ +1 Vida / Llave / Bomba / Moneda#↑ +0,5 de daño#↑ +0,1 de velocidad#↑ +1,5 de rango"},
	{"308", "Aquario", "Deja un rastro de creep#El creep inflige 6 de daño cada segundo"},
	{"309", "Piscis", "↑ Más lagrimas#Lágrimas con empuje"},
	{"310", "Máscara de pestañas de Eve", "↑ Duplica el daño#↓ Menos lágrimas#↓ -0,5 de velocidad de disparo"},
	{"311", "Sombra de Judas", "Al morir, revive como un Judas oscuro#↑ (X2 de daño)"},
	{"312", "Lazo de Maggy", "↑ +1 de vida#Todos los corazones rojos curarán 2 contenedores"},
	{"313", "Manto sagrado", "Ignora el primer golpe de cada habitación"},
	{"314", "Piernas gordas", "↑ +1 de vida#-0,4 de velocidad#Rompes rocas al caminar"},
	{"315", "Atrayente extraño", "Lágrimas magnéticas"},
	{"316", "Ojo maldito", "Ola de lágrimas cargadas#Cuando cargas y te golpean te teletransporta a una habitación aleatoria"},
	{"317", "Líquido misterioso", "Las lágrimas dejan creep#El creep inflige 30 de daño cada segundo"},
	{"318", "Géminis", "Familiar unido a ti#Inflige 8 de daño por contacto cada segundo"},
	{"319", "El otro ojo de Caín", "Rebota por la habitación#Dispara en la misma dirección que Isaac#Inflige el mismo daño que tú"},
	{"320", "El único amigo de ???", "Mosca controlable#Inflige 5 de daño por contacto cada segundo"},
	{"321", "Cadenas de Sansón", "Bola de acero encadenada a Isaac#Puede dañar enemigos o destruir rocas#Inflige 10,7 de daño por contacto"},
	{"322", "Bebé basura", "Copia el efecto de uno de tus familiares#Inflige el doble de su daño"},
	{"323", "Lágrimas de Isaac", "Dispara 8 lágrimas en todas las direcciones#Carga al disparar"},
	{"324", "Indefinido", "Te teletransporta a:#Habitación {{SecretRoom}}{{SuperSecretRoom}}Secreta / Error / sala del tesoro{{TreasureRoom}}"},
	{"325", "Tijeras", "Te corta la cabeza#La cabeza no se mueve#Controla tu cuerpo por separado"},
	{"326", "Soplo de vida", "Mantén hasta que la barra del objeto se vacíe para ser invencible#!!! ¡No mantengas demasiado tiempo!"},
	{"327", "La Polaroid", "Invencible cuando te golpean y estás a medio corazón"},
	{"328", "El negativo", "Efecto de Necronomicón cuando te golpean y estás a medio corazón"},
	{"329", "La técnica Ludovico", "Lágrima controlable"},
	{"330", "Leche de soja", "↑ Muchas más lágrimas#↓ -80% de daño"},
	{"331", "Cabeza de Dios", "Lágrimas teledirigidas#↑ +0,5 de daño#↑ +1,2 de rango#↓ -0,3 de lágrimas#↓ -30 % de velocidad de disparo#↑ +0,8 de tamaño de lágrima"},
	{"332", "Trapos de Lázaro", "Al morir, revive como Lázaro"},
	{"333", "La mente", "Visión de mapa al completo"},
	{"334", "El cuerpo", "↑ +3 de vida"},
	{"335", "El alma", "+2 corazones de alma#Genera un aura que repele los proyectiles"},
	{"336", "Cebolla muerta", "Lágrimas espectrales y penetrantes#↑ +0,25 de rango#↓ -0,4 de velocidad de disparo"},
	{"337", "Reloj roto", "Ralentiza o acelera cada cuatro habitaciones"},
	{"338", "El búmeran", "Aturde a los enemigos#Puede coger objetos"},
	{"339", "Imperdible", "↑ +5,25 de rango#↑ +0,16 de velocidad de disparo#+1 corazón negro#↑ +0,5 de tamaño de lágrima"},
	{"340", "Pastilla de cafeína", "↑ +0,3 de velocidad#↑ Hace más pequeño al jugador#Al cogerlo te da una píldora"},
	{"341", "Foto rasgada", "↑ +0,7 de lágrimas#↑ +16 % de velocidad de disparo"},
	{"342", "Gorra azul", "↑ +1 de vida#↑ +0,7 de lágrimas#↓ -16 % de velocidad de disparo"},
	{"343", "Llave de candado", "↑ +1 de suerte#+1 corazón de alma#Genera 2 llaves"},
	{"344", "Libro de cerillas", "+1 corazón negro#Genera de 2 a 3 bombas"},
	{"345", "Synthol", "↑ +1,0 de daño#↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima"},
	{"346", "Libro de cerillas", "↑ +1 de vida"},
	{"347", "Diplopía", "!!! UN SOLO USO #Duplica los pedestales y consumibles de la habitación actual"},
	{"348", "Placebo", "Copia el efecto de la píldora que tienes"},
	{"349", "Níquel de madera", "50 % de probabilidad de generar una moneda aleatoria"},
	{"350", "Choque tóxico", "Al entrar en cada habitación los enemigos se envenenan"},
	{"351", "Mega judía", "Congela a los enemigos#Inflige 5 de daño y envenena a los enemigos cercanos#Genera una onda de piedra#!!! Puede usarse para abrir habitaciones secretas"},
	{"352", "Cañón de vidrio", "↓ Reduce tu vida a medio corazón#Dispara una gran lágrima espectral y penetrante ((+1 daño) X 10)"},
	{"353", "Chico bombardero", "+5 bombas#Las bombas explotan en forma de cruz"},
	{"354", "Bolsa de palomitas", "↑ +1 de vida#Genera un trinket aleatorio"},
	{"355", "Perlas de Mamá", "↑ +1,25 de rango#↑ +1 de suerte#↑ +0,5 de tamaño de lágrima"},
	{"356", "Batería de coche", "Hace que tu objeto activable se active dos veces"},
	{"357", "Caja de amigos", "Duplica los familiares en la habitación actual"},
	{"358", "El mago", "Dispara 2 lágrimas de manera diagonal, similar a Are U a Wizard? (¿Eres un mago?)#Lágrimas espectrales"},
	{"359", "Clavos de 8 pulgadas", "↑ +1,5 de daño#Aumenta el empuje"},
	{"360", "Íncubo", "Familiar que dispara las mismas lágrimas que Isaac"},
	{"361", "Recompensa del destino", "Dispara lágrimas y copia el daño de la lágrima"},
	{"362", "Pequeño cofre", "Deja caer un recolectable cada pocas habitaciones"},
	{"363", "Protector jurado", "Familiar orbital#Inflige 105 de daño por contacto cada segundo#Bloquea y atrae proyectiles#Bloquear una lágrima puede dejar caer un corazón eterno"},
	{"364", "Zona de amistad", "Familiar orbital#Inflige 45 de daño por contacto cada segundo"},
	{"365", "Mosca perdida", "Mosca que se mueve por las paredes de la habitación#Inflige 105 de daño por contacto cada segundo"},
	{"366", "Bombas de dispersión", "+5 bombas#Hace que las bombas exploten en 2-4 bombas pequeñas"},
	{"367", "´Bombas pegajosas ", "+5 bombas#Cuando la bomba mata un enemigo, genera una araña azul#Hace que las bombas se peguen a los enemigos"},
	{"368", "Epífora", "Disparar en una única dirección aumenta la cadencia de disparo hasta un 200 %"},
	{"369", "Continuum", "↑ +2,25 de rango#↑ +1,5 de tamaño de lágrima#Las lágrimas atraviesan las paredes y aparecen por la pared contraria"},
	{"370", "Sr. muñequita", "↑ +0,7 de lágrimas#↑ +5,25 de rango#↑ +0,5 de tamaño de lágrima#Genera 3 corazones aleatorios al cogerlo"},
	{"371", "Maldición de la torre", "Genera 6 bombas troll cada vez que te golpean#Varían en función de tus objetos bomba"},
	{"372", "Bebé cargado", "Posibilidad de dejar caer una batería o de congelar a los enemigos#Puede agregar una carga a tu objeto activable"},
	{"373", "Ojo muerto", "↑ +12,5 % de daño por cada lágrima que golpee a un enemigo (máximo +100 %)#Fallar reinicia el daño"},
	{"374", "Luz sagrada", "Posibilidad de disparar una lágrima sagrada, que hará que caigan rayos de luz desde el cielo#El rayo inflige cuatro veces tu daño"},
	{"375", "Sombrero de Host", "20 % de posibilidad de evitar lágrimas#Inmune a explosiones y al pie de Mamá y de Satán"},
	{"376", "Reabastecimiento", "Las tiendas reponen los objetos que compres instantáneamente#Genera 3 pick ups"},
	{"377", "Saco a rebosar", "Las arañas enemigas ya no dañarán a Isaac"},
	{"378", "Núm. 2", "Disparar durante 3 segundos generará una bomba caca"},
	{"379", "Dúplex pupula", "Las lágrimas tienen una hitbox mayor#Lágrimas espectrales"},
	{"380", "Pagar para jugar", "+5 monedas#Abres puertas con monedas en lugar de llaves"},
	{"381", "Bendición de Edén", "↑ +0,7 de lágrimas#Objeto aleatorio al inicio de la siguiente partida"},
	{"382", "Bola amigable", "Se lanza a los enemigos para capturarlos# Cuando vuelvas a usarlo lo revivirá como aliado"},
	{"383", "Detonador de lágrimas", "Detona las lágrimas que lances para que se separen en otras 6 lágrimas en círculo"},
	{"384", "Pequeño Gurdy", "Rebota por la habitación infligiendo daño por contacto a los enemigos"},
	{"385", "Vagabundo", "Recoge monedas cercanas#Cada 6 monedas sube de nivel, menos para el nivel 4 que son 12#Nivel 2: suelta recolectables aleatorios#Nivel 3: lanza lágrimas en la misma dirección que Isaac#Nivel 4: ya no dispara, persigue a los enemigos. Puede soltar bombas#Después de nivel 4: recoge monedas y suelta recolectables aleatorios"},
	{"386", "D12", "Convierte los objetos similares a rocas en otro tipo de objeto aleatorio (caca, TNT, caca roja, piedras, etc.)"},
	{"387", "Incensario", "Crea una gran aura de luz que ralentiza a los enemigos y proyectiles que entren en ella"},
	{"388", "Vagabundo de llaves", "Recoge llaves y genera cofres aleatorios a cambio"},
	{"389", "Bolsa de runas", "Genera una runa aleatoria cada 7-8 habitaciones#También puede generar piedras de alma"},
	{"390", "Serafín", "Dispara lágrimas similares a Sacred Heart (Corazón sagrado)#Infligen 10 de daño"},
	{"391", "Traición", "Cada vez que golpean a Isaac, los enemigos de la habitación reciben un efecto encantador"},
	{"392", "Zodíaco", "Efecto aleatorio de objeto del zodíaco que cambia cada planta"},
	{"393", "Beso de serpiente", "Posibilidad de envenenar a los enemigos#Envenena al tocar#Posibilidad de que los enemigos envenenados dejen caer un corazón negro al caer"},
	{"394", "Marcado", "Dispara lágrimas automáticamente dirigidas por la mira roja en el suelo#↑ +0,7 de lágrimas#↑ +0,3 de tamaño de lágrima#↑ +3,15 de rango"},
	{"395", "Tecnología X", "Ahora disparas anillos láser con gran daño que viajan a través de la habitación"},
	{"396", "Navaja ventricular", "Crea dos portales para viajar entre ellos#Puede usarse en diferentes habitaciones"},
	{"397", "Rayo tractor", "Las lágrimas viajan en línea recta siguiendo un rayo de luz #↑ +0,5 de lágrimas#↑ +5,25 de rango#↑ +0,16 de velocidad de disparo#↑ +0,5 de tamaño de lágrima"},
	{"398", "Carne de los dioses", "Las lágrimas pueden reducir el tamaño de los enemigos#Puedes pisarlos para matarlos"},
	{"399", "Fauces del vacío", "↑ +1,0 de daño#Tras disparar lágrimas durante 3 segundos, crea un anillo negro que daña a los enemigos que están dentro de él#Los enemigos asesinados con el anillo negro pueden generar corazones negros"},
	{"400", "Lanza del destino", "Genera una lanza delante de ti#Inflige el doble de tu daño#Puede asustar a los enemigos al contacto"},
	{"401", "Explosivo", "Posibilidad de disparar bombas pegajosas"},
	{"402", "Caos", "Puede aparecer cualquier objeto del juego en los pedestales# Al cogerlo, deja caer entre 1-6 recolectables"},
	{"403", "Módulo araña", "Te permite ver el daño de la lágrima y la barra de vida de los enemigos#Al tocar a un enemigo lo congela#Dejará caer baterías"},
	{"404", "Bebé pedorro", "Bloquea los proyectiles#Si le golpean se tirará un pedo, lo que envenenará, empujará o encantará a los enemigos cercanos"},
	{"405", "Error de juego", "Familiar que aplica un efecto aleatorio a los enemigos que le toquen#Inflige 120 de daño cada segundo"},
	{"406", "D8", "Cambia tus estadísticas#Solo afecta al daño, las lágrimas, el rango y la velocidad"},
	{"407", "Pureza", "↑ Potencia una estadística dependiendo del color del aura que te rodea#Al recibir daño cambia el color de aura##{{ColorRed}}Rojo{{CR}} = +4,0 de daño##{{ColorBlue}}Azul{{CR}} = +4 de lágrimas#{{ColorYellow}}Amarillo{{CR}} = +0,5 de velocidad#{{ColorOrange}}Naranja{{CR}} = +7,5 de rango, +1 de tamaño de lágrima"},
	{"408", "Athame", "Al recibir daño, aparece un anillo negro alrededor de Isaac que inflige daño por contacto#Los enemigos asesinados con él pueden dejar caer un corazón negro"},
	{"409", "Recipiente vacío", "+2 corazones negros#Cuando no tengas corazones rojos, te permite volar y generar un escudo"},
	{"410", "Ojo malvado", "A veces aparece un ojo que disparará lágrimas en la misma dirección que Isaac"},
	{"411", "Sangre sedienta", "↑ +0,5 de daño cada vez que matas a un enemigo#Máximo de +5 de daño al matar 10 veces#El daño dura en la habitación actual"},
	{"412", "Concepción de Cambión", "Al recibir daño 15 veces, ganas un familiar demoníaco permanente#Hasta 4 familiares"},
	{"413", "Inmaculada concepción", "Al recoger 15 corazones, ganas un familiar angelical permanente#Hasta 5 familiares"},
	{"414", "Más opciones", "Se generan dos objetos en la sala del tesoro#Solo puedes escoger uno"},
	{"415", "Corona de luz", "+2 corazones de alma#↑ El doble de daño si no tienes ningún contenedor de corazón rojo vacío#Se pierde el efecto en la habitación si te dañan"},
	{"416", "Bolsillos profundos", "Te permite llevar dos cartas,píldoras o runas"},
	{"417", "Súcubo", "Familiar que rebota con un aura que inflige un 129 % de tu daño a los enemigos que estén dentro de ella#↑ Al quedarse sobre el aura, +50 % de multiplicador de daño"},
	{"418", "Tarta de frutas", "Otorga un efecto de lágrima diferente por cada lágrima que disparas"},
	{"419", "Teletransporte 2.0", "Te teletransporta a una habitación sin explorar#Jerarquía: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> (I Am Error)"},
	{"420", "Polvo negro", "Caminar en círculo forma un símbolo de pentagrama en el suelo, que inflige 10 de daño por tick"},
	{"421", "Alubía roja", "Encanta a los enemigos cercanos y les inflige 5 de daño"},
	{"422", "Reloj de arena brillante", "Viaja en el tiempo y te deja en habitaciones anteriores, con las mismas estadísticas que tenías entonces"},
	{"423", "Círculo de protección", "Se crea un gran halo a tu alrededor, inflige daño por contacto#Posibilidad de evitar proyectiles enemigos"},
	{"424", "Cabeza de saco", "33 % de posibilidad de que los recolectables se sustituyan por un saco#Genera un saco"},
	{"425", "Linterna", "Un cono de luz frente a Isaac que ralentiza a los enemigos y a sus lágrimas"},
	{"426", "Fanático obsesionado", "Sigue tus movimientos exactos con 3 segundos de retraso#Inflige 30 de daño por contacto cada segundo"},
	{"427", "Minero profesional", "Coloca un barril de TNT#Si no se ha usado el barril y colocas otro en la misma habitación, el primero explotará"},
	{"428", "Pijama", "+4 corazones de alma#Cura los corazones rojos al completo"},
	{"429", "Cabeza de Keeper", "5 % de posibilidad de que las lágrimas dejen caer monedas tras golpear a un enemigo"},
	{"430", "Mosca papá", "Sigue tus movimientos con 3 segundos de retraso#Dispara a los enemigos cercanos e inflige tu daño"},
	{"431", "Bebé multidimensional", "Sigue tus movimientos con 3 segundos de retraso#Las lágrimas que lo traspasen se dividen y ganan una mejora de velocidad"},
	{"432", "Bombas de purpurina", "#+5 bombas#Las bombas pueden generar recolectables aleatorios al explotar (llaves, monedas, bombas)"},
	{"433", "Mi sombra", "Cada vez que te golpean, asustará a los enemigos de la habitación y generará un familiar negro#El familiar inflige 5 de daño cada segundo"},
	{"434", "Tarro de moscas", "Cada vez que mates a un enemigo se añadirá una mosca azul al tarro#Máximo: 20 moscas#Usar el Tarro de moscas las liberará"},
	{"435", "Pequeño Loki", "Dispara 4 lágrimas en forma de cruz#Inflige 3,5 de daño"},
	{"436", "¡Leche!", "Tras ser golpeado, aumenta las lágrimas para el resto de la habitación"},
	{"437", "D7", "Vuelve a generar enemigos y te permite conseguir recompensas al acabar la habitación#!!! Al usarlo en una lucha contra Greed, puede convertir la habitación en una tienda"},
	{"438", "Chupete", "+1 corazón de alma#↑ +0,7 de lágrimas#↑ Hace que Isaac sea muy pequeño, reduce el tamaño de la hitbox"},
	{"439", "Caja de Mamá", "Deja caer un trinket aleatorio#↑ +1 de suerte#Al tenerlo duplica el efecto de los trinkets"},
	{"440", "Piedra en el riñón", "Al disparar, puede lanzar un grupo de lágrimas y una roca#↓ -0,2 de velocidad#↓ -17 de rango#↑ +2,0 de tamaño de lágrima"},
	{"441", "Mega ráfaga", "Dispara un gran láser de Mega Satán durante 15 segundos#El láser se mantiene entre habitaciones o plantas"},
	{"442", "Corona del príncipe oscuro", "!!! Al tener un corazón rojo lleno:#↑ +1,5 de rango#↑ +0,7 de lágrimas#↑ +0,2 de velocidad de disparo#(No funciona con the Lost (El Perdido))"},
	{"443", "¡Manzana!", "Dispara cuchillas que infligen un 400 % de daño de manera aleatoria#↑ +0,3 de lágrimas"},
	{"444", "Lápiz", "Cada 15 lágrimas disparas un grupo de lágrimas#Cada lágrima inflige el doble de daño"},
	{"445", "Diente de perro", "↑ +0,3 de daño#↑ +0,1 de velocidad#Un lobo aúlla si entras en una habitación al lado de la sala secreta#Un ladrido si hay una trampilla "},
	{"446", "Diente muerto", "Al disparar, recibes un aura verde que envenena a los enemigos que entran#El veneno inflige tu daño"},
	{"447", "Judía persistente", "Al disparar sin parar, genera una nube de caca cada 7,5 segundos#La nube inflige 3,5 de daño 5 veces por segundo#La nube dura 15 segundos#Si le disparas puedes moverla"},
	{"448", "Trozo de vidrio", "Cuando te golpean, posibilidad de ganar ↑ +5 de rango y dejar un rastro de creep sangriento o generar un corazón rojo"},
	{"449", "Placa de metal", "+1 corazón de alma# 25 % de posibilidad de reflejar los proyectiles enemigos en lágrimas que aturden"},
	{"450", "Ojo codicioso", "Cada 20 lágrimas, disparas una lágrima moneda que convierte a los enemigos en oro#Cuesta una moneda#Matar a esos enemigos hará que caiga una moneda"},
	{"451", "Tapete de Tarot", "Genera una carta o runa aleatoria#Duplica el uso de cualquier carta del tarot"},
	{"452", "Venas varicosas", "Cuando te golpean se dispara un círculo de 10 lágrimas#Las lágrimas infligen 125 % de daño"},
	{"453", "Fractura compuesta", "Lágrimas de hueso#Al golpear a un enemigo, las lágrimas se separan en 1-3 trozos de hueso#↑ +1,5 de rango#+1,0 de tamaño de lágrima"},
	{"454", "Polidactilia", "Puedes llevar dos cartas, runas o píldoras#Genera una carta, píldora o runa aleatoria al cogerlo"},
	{"455", "Moneda perdida de Papá", "↑ +1,5 de rango#Deja caer un penique de la suerte"},
	{"456", "Pan mohoso", "↑ +1 de vida"},
	{"457", "Cabeza de cono", "+1 corazón de alma#20 % de posibilidad de ignorar daño"},
	{"458", "Ombligo", "Genera un trinket aleatorio al cogerlo#+Espacio para un trinket adicional"},
	{"459", "Sinusitis", "Lágrimas venenosas que se pegan al enemigo hasta que muere#Inflige tu daño cada tick"},
	{"460", "Glaucoma", "Posibilidad de disparar lágrimas que aturden"},
	{"461", "Parasitoide", "Posibilidad de disparar sacos de huevos# Genera un creep ralentizante al impactar#Genera una mosca o araña azul"},
	{"462", "Ojo de Belial", "↑ +1,5 de rango#↑ +1,0 de tamaño de lágrima#Otorga lágrimas penetrantes#Tras golpear al primer enemigo, las lágrimas infligen el doble de daño y se vuelven teledirigidas"},
	{"463", "Ácido sulfúrico", "↑ +0,3 de daño#Probabilidad de disparar lágrimas que destruyan rocas y abren puertas"},
	{"464", "Glifo de balance", "+2 corazones de alma#Los enemigos campeones generan más recolectables"},
	{"465", "Palanca de control", "↑ +0,3 de lágrimas#Permite disparar lágrimas en diagonal al disparar en dos direcciones"},
	{"466", "Contagio", "El primer enemigo asesinado explota y envenena a los enemigos cercanos"},
	{"467", "¡Dedo!", "Inflige un 10 % de daño constante en la dirección en la que señala el dedo"},
	{"468", "Sombra", "Sigue tu movimiento con un retraso de un segundo#Inflige 30 de daño por contacto"},
	{"469", "Depresión", "Deja un rastro de lágrimas que inflige 6 de daño cada segundo#Los enemigos que toquen la nube pueden hacer caer un rayo de luz sagrada"},
	{"470", "Hushy", "Rebota por la habitación#Inflige daño por contacto#Se para cuando disparas#Cuando está parado puede bloquear proyectiles"},
	{"471", "Pequeño Monstro", "Carga los disparos como Monstro#Cada lágrima inflige 3,5 de daño"},
	{"472", "Rey bebé", "Le siguen otros familiares#No se mueve mientras disparas#Se teletransporta a ti cuando dejas de disparar"},
	{"473", "Gran Chubby", "Carga hacia delante lentamente#Inflige 40,5 de daño por contacto"},
	{"474", "Tonsil", "Bloquea los proyectiles enemigos"},
	{"475", "Plan C", "!!! UN SOLO USO #Inflige 9.999.999 de daño a todos los enemigos y te mata 3 segundos después"},
	{"476", "D1", "Duplica un recolectable aleatorio en la habitación actual"},
	{"477", "Vacío", "!!! Al usarlo, consume cualquier objeto de pedestal en la habitación#Objeto activo: Se añade el efecto al de Vacío(Apilando los efectos)#↑ Objeto pasivo: Pequeña mejora aleatoria"},
	{"478", "Pausa", "Congela a los enemigos hasta que vuelvas a disparar#Tocar a un enemigo congelado te hará daño"},
	{"479", "Horno de fundición", "Consume el trinket y ganas el efecto de manera permanente#Aparecen más trinkets"},
	{"480", "Compost", "Convierte los recolectables en moscas o arañas azules"},
	{"481", "Minero de datos", "Al usarlo, ↑/↓ una pequeña cantidad de una estadística aleatoria#Efecto aleatorio de lágrima para la habitación actual"},
	{"482", "Clicker", "Te convierte en otro personaje aleatorio#Elimina el último objeto que hayas cogido"},
	{"483", "¡Mega Mamá!", "!!! UN SOLO USO#Afecta a toda la planta#Explota todos los objetos#Inflige 200 de daño a todos los enemigos#Abre la Boss rush/puerta de Hush/sala secreta"},
	{"484", "Espera, ¿qué?", "Al usarlo, empuja a los enemigos y genera una ola de rocas#Puede abrir habitaciones o romper piedras"},
	{"485", "Moneda torcida", "50% de probabilidad de duplicar todos los objetos, consumibles y cofres de la habitación#50% de probabilidad de eliminar objetos/recolectables de la habitación y soltar una moneda"},
	{"486", "Cuchilla desafilada", "Hace que el jugador sufra daño sin perder ningún corazón#Puede activar efectos de otros objetos que tengas"},
	{"487", "Pelapatatas", "Elimina un contenedor de corazón rojo y te da ↑ +0,2 de daño y un \"Cube of Meat\" (Cubo de carne)"},
	{"488", "Metrónomo", "Otorga un efecto de objeto aleatorio en la habitación"},
	{"489", "D infinito", "Efecto de dado aleatorio en cada uso"},
	{"490", "Alma de Edén", "!!! UN SOLO USO#Genera 2 objetos aleatorios de la habitación actual"},
	{"491", "Bebé ácido", "Genera una píldora aleatoria cada tres habitaciones#Usar una píldora daña a los enemigos"},
	{"492", "¡EH, OYE!", "↑ +1 de suerte#Resalta la localización de salas secretas, rocas marcadas y trampillas"},
	{"493", "Adrenalina", "Por cada contenedor de corazón vacío:#↑ +0,2 de daño"},
	{"494", "", "Lágrimas eléctricas que al impactar generan rayos#Los rayos infligen la mitad de tu daño"},
	{"495", "Fantasma picante", "Probabilidad de disparar fuego en lugar de lágrimas#El fuego se mantiene hasta infligir daño 5 veces"},
	{"496", "Eutanasia", "Puede disparar jeringuillas que matan a los enemigos normales de un golpe#A los jefes les inflige el triple de tu daño"},
	{"497", "Ropa interior de camuflaje", "Al entrar a una habitación te camuflas hasta que disparas"},
	{"498", "Dualidad", "Genera la sala del Diablo{{DevilRoom}} y del Ángel{{AngelRoom}}#Cuando entras en una la otra desaparece"},
	{"499", "Eucaristía", "↑ 100 % de probabilidad de encontrar la sala del Ángel{{AngelRoom}}"},
	{"500", "Saco de sacos", "Genera un saco cada 5-6 habitaciones"},
	{"501", "Garganta de la codicia", "Cada 25 monedas te da 1 contenedor de corazón#The Keeper ganará más monedas-corazones"},
	{"502", "Espinilla grande", "Posibilidad de disparar una lágrima que suelte creep y duplique el daño"},
	{"503", "Pequeño cuerno", "Posibilidad de disparar una lágrima que mata al instante a enemigos normales#Inflige 3,5 de daño por contacto"},
	{"504", "Pepita marrón", "Genera una mosca torreta que dispara a los enemigos#Cada disparo inflige 2 de daño"},
	{"505", "Poke Go", "De manera aleatoria, genera un enemigo encantado al entrar en una habitación hostil"},
	{"506", "Puñalada trapera", "Las lágrimas causan sangrado que inflige el 10 % de la vida total de los enemigos cada 5 segundos"},
	{"507", "Pajita afilada", "Inflige tu daño + 10 % de la vida máxima del enemigo#Afecta a todos los enemigos de la habitación#Probabilidad de generar medio corazón al infligir daño"},
	{"508", "Maquinilla de afeitar", "Orbital que causa sangrado,que inflige el 10 % de la vida total de los enemigos cada 5 segundos#Inflige 300 % de tu daño por contacto cada segundo"},
	{"509", "Ojos rojos", "Dispara una lágrima en una dirección aleatoria cada 2 segundos#Inflige 3,5 de daño#Inflige 30 de daño por contacto cada segundo"},
	{"510", "Delirante", "Genera una versión aliada de Delirium en la habitación actual"},
	{"511", "Mosca enfadada", "Orbita alrededor de un enemigo aleatorio hasta que este muere#Inflige 30 de daño por contacto cada segundo"},
	{"512", "Agujero negro", "Agujero negro lanzable, que lo absorbe todo#Inflige 0,4 de daño por tick#Destruye rocas cercanas#Dura seis segundos"},
	{"513", "Bozo", "↑ +0,1 de daño#+1 corazón de alma#Posibilidad de encantar/asustar a un enemigo#Posibilidad de generar una caca arcoíris al ser golpeado"},
	{"514", "Módem roto", "Los enemigos se quedan paralizados de manera aleatoria por unos instantes#25 % de probabilidad de generar el doble de recolectables al limpiar la habitación"},
	{"515", "Regalo misterioso", "!!! UN SOLO USO#Genera un objeto aleatorio de la habitación actual#Probabilidad de generar Lump of Coal (Trozo de carbón) o The Poop (La caca)"},
	{"516", "Aspersor", "Genera una torreta que gira y dispara tus lágrimas en todas las direcciones"},
	{"517", "Bombas rápidas", "+7 Bombas#Te permite colocar bombas muy rápido"},
	{"518", "Amigo en una caja", "Familiar que cambia de aspecto#Efecto de lágrima aleatorio cada planta"},
	{"519", "Pequeño Delirium", "Familiar que se transforma en otro familiar aleatorio cada 10 segundos"},
	{"520", "Cables de puente", "+1 carga para tu objecto activable cada 15 enemigos asesinados"},
	{"521", "Cupón", "Al usarlo, un objeto de la tienda{{Shop}} o sala del Diablo{{DevilRoom}} se vuelve gratis"},
	{"522", "Telequinesis", "Detiene los proyectiles enemigos que estén cerca durante 3 segundos#Los lanza lejos de ti#Se recarga pasados 3 segundos"},
	{"523", "Caja de mudanza", "Guarda todos los recolectables de la habitación#Al volver a usarlo suelta los recolectables#Permite mover objetos entre habitaciones"},
	{"524", "Tecnología cero", "Las lágrimas están conectadas con rayos de electricidad#Los rayos infligen tu daño"},
	{"525", "Lepra", "Recibir daño genera un orbital#Máx. 3 orbitales a la vez#Si reciben demasiado daño, los orbitales pueden destruirse"},
	{"526", "Siete sellos", "Familiar con la forma y ataque de los jinetes#El jinete cambia pasados 10 segundos"},
	{"527", "¡Sr. yo!", "!!! Familiar que hace tareas por ti:#Abrir puertas y cofres, traerte objetos, robar de la tienda o del pacto, luchar contra enemigos, explotar y activar placas de presión"},
	{"528", "Prisma angelical", "Prisma orbital#Las lágrimas que pasen por el prisma se separan en cuatro nuevas lágrimas"},
	{"529", "¡Pop!", "Las lágrimas son ojos que pueden rebotar entre ellos"},
	{"530", "Lista de la muerte", "Otorga una recompensa al matar enemigos en el orden que se indica"},
	{"531", "Hemolacria", "Las lágrimas salen en forma de arco#Al impactar, explotan en lágrimas más pequeñas#↓ Menos lágrimas#↑ +31 % de daño"},
	{"532", "Lacrofagia", "Las lágrimas se ralentizan mientras viajan#Al parar, explotan en 8 pequeñas lágrimas#Las lágrimas pueden acumularse disparando unas sobre otras"},
	{"533", "Trisagio", "Dispara rayos de luz blanca#(Brimstone sagrado)"},
	{"534", "Mochila", "Te permite tener 2 objetos activables#Cámbialos pulsando la tecla de soltar objetos (mantén si eres \"The Forgotten\")"},
	{"535", "Manta", "+1 corazón de alma#Cura un corazón rojo#Otorga un escudo al entrar a la sala del jefe"},
	{"536", "Altar de sacrificio", "!!! UN SOLO USO#Sacrifica 1-2 familiares para generar un objeto del Diablo{{DevilRoom}}#Convierte tus moscas o arañas azules en monedas"},
	{"537", "Pequeño Spewer", "+1 píldora#Familiar que deja un rastro de creep#El tipo de creep cambia cada vez que uses una píldora"},
	{"538", "Canicas", "Deja caer 3 trinkets aleatorios#Que te golpeen puede añadir el efecto del trinket permanentemente"},
	{"539", "Huevo misterioso", "Genera un enemigo encantado cuando te golpean#Genera aliados más fuertes cuantas más habitaciones limpies sin que te golpeen"},
	{"540", "Piedra plana", "Las lágrimas rebotan en el suelo#Al salpicar, las lágrimas hacen daño"},
	{"541", "Médula", "+1 corazón de hueso#Genera 3 corazones rojos"},
	{"542", "Costilla deslizante", "Orbital#Refleja los projectiles"},
	{"543", "Tierra sagrada", "Genera una caca blanca cuando te golpean#(La caca blanca tiene un aura que aumenta las lágrimas y puede bloquear daño)"},
	{"544", "Costilla puntiaguda", "Clavo que levita frente a Isaac#Inflige 6 veces tu daño"},
	{"545", "Libro de los muertos", "Genera huesos que orbitan a tu alrededor o Bonies aliados#El efecto dura en esta habitación"},
	{"546", "Anillo de Papá", "Otorga un aura que congela a los enemigos"},
	{"547", "Papeles del divorcio", "+1 un corazón de hueso#↑ +0,7 de lágrimas#Genera el trinket Papel misterioso"},
	{"548", "Mandíbula", "Familiar tipo boomerang#Inflige 7 de daño por contacto#Puede recoger objetos"},
	{"549", "Huesos de cristal", "Remplaza todos los contenedores de corazón por 6 corazones de hueso#Perder un corazón de hueso dispara lágrimas en todas las direcciones#↑ +0,5 lágrimas"},
	{"550", "Pala rota", "Los pies de mamá te atacarán constantemente#Al usarlo los pies dejarán de caer en esta habitación#!¡Intenta ganar la Bossrush con esto!"},
	{"551", "Pala rota", "Segunda parte de la pala rota#Úsala en el montón de tierra en la \"Dark Room\"(La sala oscura)"},
	{"552", "Pala de Mamá", "Genera una trampilla hacia la siguiente planta#Úsala en el montón de tierra en la \"Dark Room\"(La sala oscura)"},
}
 
---------- Trinkets ----------
EID.descriptions["spa"].trinkets={
	{"1", "Moneda tragada", "Generas 1 moneda cuando te golpean"},
	{"2", "Caca petrificada", "Las cacas dejan caer más recolectables"},
	{"3", "Pila AAA", "Se necesita 1 carga menos en los objetos activables"},
	{"4", "Control remoto roto", "Te teletransporta de manera aleatoria al usar un objeto"},
	{"5", "Corazón morado", "Más campeones enemigos#Más salas de desafío de jefe ({{BossRushRoom}})"},
	{"6", "Imán roto", "Imán de monedas"},
	{"7", "Cuenta del rosario", "Aumenta la probabilidad de abrir la sala del Ángel{{AngelRoom}}#Aumenta la probabilidad de encontrar la Biblia {{Collectible33}}"},
	{"8", "Cartucho", "Probabilidad de activar el efecto de The Gamekid al recibir daño"},
	{"9", "Gusano palpitante", "Las lágrimas aumentan y disminuyen su tamaño#Afecta a la hitbox de la lágrima"},
	{"10", "Gusano ondulante", "Las lágrimas se mueven en ondas#↑ +0,3 lágrimas"},
	{"11", "Gusano anillo", "Las lágrimas se mueven en espiral"},
	{"12", "Gusano plano", "Lágrimas más grandes"},
	{"13", "Crédito de tienda", "Un objeto de la tienda es gratis"},
	{"14", "Callo", "Ni los pinchos ni el creep te hacen daño"},
	{"15", "Roca de la suerte", "Destruir rocas genera monedas"},
	{"16", "Uña del pie de Mamá", "El pie de mamá cae sobre los enemigos cada 60 segundos"},
	{"17", "Pintalabios negro", "Más corazones negros"},
	{"18", "Tratado bíblico", "Más corazones eternos"},
	{"19", "Sujetapapeles", "Abre cofres sin usar llaves"},
	{"20", "Pata de mono", "Al estar a medio corazón, deja caer un corazón negro#!!! 3 usos"},
	{"21", "Papel misterioso", "Imita \"Polaroid\", \"The Negative\", \"Missing Poster\" y \"Missing Page\""},
	{"22", "Cola de demonio", "!!! Convierte:#Corazones rojos en corazones negros#Se generan menos corazones"},
	{"23", "Cartel de desaparición", "Al morir en la sala del sacrificio {{SacrificeRoom}} revives como \"The Lost\"#Si lo tienes desbloqueado, revives como él incluso fuera de las salas de sacrificio"},
	{"24", "Moneda de culo", "Te tiras pedos al coger monedas#Los pedos empujan"},
	{"25", "Dulce misterioso", "Te tiras un pedo o generas una caca cada 30 segundos"},
	{"26", "Gusano de gancho", "Las lágrimas se mueven en ángulos rectos"},
	{"27", "Gusano látigo", "↑ +0,5 de velocidad de disparo"},
	{"28", "Anj roto", "22 % de probabilidad de revivir como \"Blue Baby\""},
	{"29", "Cabeza de pez", "Genera una mosca azul cuando te golpean"},
	{"30", "Ojo rosado", "10 % de posibilidad de disparar lágrimas envenenadas"},
	{"31", "Chincheta", "10 % de posibilidad de disparar lágrimas penetrantes de manera aleatoria"},
	{"32", "Hongo de San Juan", "Efecto aleatorio de champiñón en la habitación#Puede revelar las habitaciones especiales en el minimapa"},
	{"33", "Cordón umbilical", "Al estar a medio corazón, aparece un pequeño Steven"},
	{"34", "Corazón de niño", "Genera más corazones rojos"},
	{"35", "Cuerno torcido", "↑ +2 de daño"},
	{"36", "Llave oxidada", "Aparecen más cofres dorados y llaves"},
	{"37", "Pezuña de cabra", "↑ +0,15 de velocidad"},
	{"38", "Perla de mamá", "Recibes más corazones de alma"},
	{"39", "Cáncer", "↑ Más lágrimas"},
	{"40", "Parche rojo", "↑ Probabilidad de hacer +1,8 de daño cuando te golpean"},
	{"41", "Cerilla", "Aparecen más bombas#!!! Elimina \"The Tick\" (la garrapata)"},
	{"42", "Pulgar de la suerte", "↑ +1 de suerte"},
	{"43", "Cráneo maldito", "Si te dañan y estás a medio corazón o menos, te teletransporta a la última habitación"},
	{"44", "Tapa de seguridad", "Aparecen más píldoras"},
	{"45", "As de espadas", "Aparecen más cartas"},
	{"46", "Tenedor de Isaac", "Posibilidad de curarse medio corazón al limpiar la habitación"},
	{"47", "", "<unused>"},
	{"48", "Una página perdida", "Cuando te golpean, posibilidad de dañar a toda la habitación"},
	{"49", "Moneda sangrienta", "50 % de posibilidad de generar medio corazón al coger monedas"},
	{"50", "Moneda quemada", "50 % de posibilidad de generar bombas al coger monedas"},
	{"51", "Moneda plana", "50 % de posibilidad de generar llaves al coger monedas"},
	{"52", "Moneda falsificada", "50 % de probabilidad de conseguir más monedas al coger monedas"},
	{"53", "La garrapata", "15 % menos de vida del jefe#Cura 1 corazón rojo al entrar a la sala del jefe ({{BossRoom}})"},
	{"54", "Cabeza de Isaac", "Familiar con lágrimas penetrantes#Inflige 3,5 de daño"},
	{"55", "La fe de Maggy", "Recibe un corazón eterno al empezar una nueva planta"},
	{"56", "Lengua de Judas", "Reduce los precios del Pacto del Diablo de dos corazones a uno"},
	{"57", "Alma de ???", "Familiar que rebota por la habitación#Dispara en la misma dirección que el jugador#Inflige 3,5 de daño"},
	{"58", "Mechón de Sansón", "↑ 1/15 de probabilidad de ganar 0,5 de daño al matar un enemigo#El efecto dura en la habitación actual"},
	{"59", "Ojo de Caín", "25 % de posibilidad de revelar los iconos del mapa al empezar una nueva planta"},
	{"60", "Pata de pájaro de Eve", "Posibilidad de generar un pájaro muerto al matar un enemigo"},
	{"61", "La mano izquierda", "Convierte todos los cofres en cofres rojos"},
	{"62", "Rocas brillantes", "Las rocas especiales brillan cada 10 segundos"},
	{"63", "Tijeras de seguridad", "Convierte las bombas troll en bombas"},
	{"64", "Gusano arcoíris", "Efecto de gusano aleatorio cada 3 segundos"},
	{"65", "Cinta de gusano", "↑ Duplica el rango#-50 % de tamaño de lágrima"},
	{"66", "Gusano vago", "↓ -0,4 de velocidad de disparo#↑ +4 rango"},
	{"67", "Dado roto", "Efecto de dado aleatorio cuando te golpean"},
	{"68", "Superimán", "Imán para recolectables y enemigos"},
	{"69", "Polaroid descolorida", "Te camufla de manera aleatoria#Desorienta a los enemigos"},
	{"70", "Piojo", "Posibilidad de generar una araña azul"},
	{"71", "La vejiga de Bob", "Las bombas sueltan creep"},
	{"72", "Pila de botón", "Genera más baterías#5 % de posibilidad de que añada una carga al objeto activo cuando limpias una habitación"},
	{"73", "Tapón de explosivos", "Explotar bombas puede generar más bombas"},
	{"74", "Detector de clavos", "Más posibilidad de que aparezcan trampillas al romper rocas"},
	{"75", "Error", "Efecto de trinket aleatorio para cada habitación"},
	{"76", "Ficha de póker", "50 % de probabilidad de conseguir más recolectables o 50 % de no conseguir nada o un enemigo"},
	{"77", "Ampolla", "Aumenta el empuje"},
	{"78", "Segunda mano", "Dobla la duración de los efectos en enemigos"},
	{"79", "Sin nombre y sin fin", "25 % de probabilidad de que, al usar una píldora o una carta, aparezca una copia de la misma"},
	{"80", "Pluma negra", "↑ +0,2 de daño por cada objeto del diablo que tengas"},
	{"81", "Furia ciega", "La invencibilidad dura más"},
	{"82", "Herradura dorada", "+15 % de posibilidad de obtener dos salas del tesoro en la siguiente planta"},
	{"83", "Llave de la tienda", "Abre las tiendas {{Shop}} gratis"},
	{"84", "Costilla de la codicia", "Greed/Super Greed ya no aparece en la tienda#Aparecen más monedas"},
	{"85", "Karma", "Usar una máquina de donación puede curarte o generar un mendigo"},
	{"86", "Pequeña larva", "Romper una caca genera una mosca azul"},
	{"87", "Relicario de Mamá", "Cura medio corazón al usar llaves#Los medios corazones aparecen como corazones enteros"},
	{"88", "¡NO!", "Poca probabilidad de que aparezcan objetos activables en la sala del tesoro"},
	{"89", "Correa de niños", "Los familiares están más cerca del jugador y entre ellos"},
	{"90", "Tapón de caca", "La caca explota cuando la destruyes"},
	{"91", "Meconio", "Aumenta la probabilidad de que aparezcan cacas negras#Al romper una caca negra puede generar un corazón negro"},
	{"92", "Corona rota", "↑ Las estadísticas basadas en objetos de Isaac son un 33 % más efectivas#↑ +0,2 de lágrimas#↑ -1 de retraso de lágrima"},
	{"93", "Pañal usado", "Posibilidad de que las moscas enemigas sean aliadas"},
	{"94", "Cola de pez", "Duplica todas las moscas y arañas azules"},
	{"95", "Diente negro", "Posibilidad de disparar un diente negro aleatoriamente"},
	{"96", "Serpiente Uróboros", "Las lágrimas se mueven rápido en espiral#Lágrimas espectrales#↑ +4 de rango"},
	{"97", "Amígdala", "Posibilidad de recibir un familiar cuando te golpean de 12 a 20 veces#Hasta 2 familiares"},
	{"98", "Nariz de duende", "Probabilidad de disparar lágrimas venenosas que se pegan a los enemigos"},
	{"99", "Superbola", "Probabilidad de disparar lágrimas que rebotan"},
	{"100", "Bombilla encendida", "!!! Al tener un objeto activable cargado al completo:#↑ +0,25 de velocidad#↑ +0,75 de rango#↑ +0,2 de lágrimas#↑ +0,1 de velocidad de disparo#↑ +0,5 de daño#↑ +1 de suerte"},
	{"101", "Bombilla apagada", "!!! Al tener un objeto activable descargado :#↑ +0,5 de velocidad#↑ +1,5 de rango#↑ +0,4 de lágrimas#↑ +0,3 de velocidad de disparo#↑ +1,5 de daño#↑ +2 de suerte"},
	{"102", "Carta fragmentada", "+1 sala secreta adicional por planta"},
	{"103", "¡Equidad!", "!!! Cuando tienes el mismo número de monedas, llaves y bombas:#Convierte los medios recolectables en dobles"},
	{"104", "Hueso de deseo", "Posibilidad de generar un objeto al ser golpeado#Se acaba destruyendo"},
	{"105", "Bolsa del almuerzo", "Posibilidad de generar un objeto de vida {{Collectible22}} al ser golpeado#Se acaba destruyendo"},
	{"106", "Corcho perdido", "Aumenta el radio de cualquier creep que produzcas"},
	{"107", "Corazón de cuervo", "Al recibir daño, los corazones rojos son dañados antes que los de alma o negros"},
	{"108", "Nuez", "Probabilidad de soltar un recolectable o trinket aleatorio al ser golpeado por una explosión#Se acaba destruyendo"},
	{"109", "Cinta adhesiva", "Hace que los orbitales dejen de moverse"},
	{"110", "Moneda de plata", "Ahora aparecen tiendas {{Shop}} en el Útero de Mamá"},
	{"111", "Corona sangrienta", "Ahora aparecen salas del tesoro {{TreasureRoom}} en el Útero de Mamá"},
	{"112", "Paga para ganar", "Las máquinas de restock aparecen en la sala del tesoro ({{TreasureRoom}})"},
	{"113", "Langosta de guerra", "Genera una mosca explosiva al entrar en una habitación#La mosca inflige el doble de tu daño + explosión"},
	{"114", "Langosta de la peste", "Genera una mosca venenosa al entrar en una habitación#La mosca inflige el doble de tu daño"},
	{"115", "Langosta del hambre", "Genera una mosca que ralentiza al entrar en una habitación#La mosca inflige el doble de tu daño"},
	{"116", "Langosta de la muerte", "Al entrar a una habitación con enemigos, genera una mosca que inflige cuatro veces tu daño"},
	{"117", "Langosta de la conquista", "Al entrar a una habitación con enemigos, genera 2-5 moscas que infligen el doble de tu daño"},
	{"118", "Ala de murciélago", "Posibilidad de volar al ser golpeado#Dura esa habitación"},
	{"119", "Célula madre", "Cura medio corazón al cambiar de planta"},
	{"120", "Horquilla", "Recarga el objeto activable al completo al entrar en la sala del jefe"},
	{"121", "Cruz de madera", "Te protege del primer daño recibido en cada planta"},
	{"122", "¡Mantequilla!", "Al usar el coleccionable activable, el jugador lo soltará al suelo"},
	{"123", "Pluma filigrana", "Hace que los ángeles generen objetos normales en lugar de piezas de llave"},
	{"124", "Tope para puerta", "La última puerta usada se mantendrá abierta"},
	{"125", "Cable de extensión", "Genera un láser entre los familiares"},
	{"126", "Moneda podrida", "Genera una mosca azul al coger monedas"},
	{"127", "Bebé doblado", "Las lágrimas de los familiares son teledirigidas"},
	{"128", "Dedo de hueso", "Posibilidad de ganar un corazón de hueso cuando te golpean"},
}
 
---------- Cards ----------
EID.descriptions["spa"].cards={
	{"1", "0 - El loco", "Te teletransporta de nuevo al inicio"},
	{"2", "I - El mago", "Lágrimas teledirigidas en la habitación actual"},
	{"3", "II - La suma sacerdotisa", "El Pie de Mamá pisa a un enemigo"},
	{"4", "III - La emperatriz", "↑ +2,35 de daño & +0,3 de velocidad en la habitación actual"},
	{"5", "IV - El emperador", "Teletransporta a la sala del jefe ({{BossRoom}})"},
	{"6", "V - El hierofante", "Suelta 2 corazones de alma"},
	{"7", "VI - Los amantes", "Suelta 2 corazones rojos"},
	{"8", "VII - El carro", "Invencibilidad + daño por contacto durante 6 segundos"},
	{"9", "VIII - Justicia", "Genera 1 bomba, 1 llave, 1 moneda, 1 corazón"},
	{"10", "IX - El ermitaño", "Teletransporta a la tienda {{Shop}}"},
	{"11", "X - Rueda de la fortuna", "Genera una tragaperras o una máquina de la fortuna"},
	{"12", "XI - Fuerza", "↑ +1 de vida#↑ +0,3 de daño#+50 % de daño#↑5,25 de rango#↑ +0,3 de velocidad#Durante la habitación actual"},
	{"13", "XII - El colgado", "Permite volar en la habitación actual"},
	{"14", "XIII - Muerte", "Inflige 40 de daño a todos los enemigos de la habitación"},
	{"15", "XIV - Templanza", "Genera una máquina de donación de sangre"},
	{"16", "XV - El Diablo", "↑ +2 de daño en la habitación actual"},
	{"17", "XVI - La torre", "Invoca bombas troll"},
	{"18", "XVII - Las estrellas", "Teletransporta a la sala del tesoro ({{TreasureRoom}})"},
	{"19", "XVIII - La luna", "Teletransporta a la sala secreta ({{SecretRoom}})"},
	{"20", "XIX - El sol", "Inflige 100 de daño a todos los enemigos #Vida al completo#Muestra el mapa completo"},
	{"21", "XX - Juicio", "Genera un mendigo"},
	{"22", "XXI - El mundo", "Muestra el mapa completo y los tipos de habitación"},
	{"23", "2 de tréboles", "Duplica las bombas"},
	{"24", "2 de diamantes", "Duplica el dinero"},
	{"25", "2 de picas", "Duplica las llaves"},
	{"26", "2 de corazones", "Duplica los corazones rojos #Solo tiene efecto curativo"},
	{"27", "As de tréboles", "Convierte todos los recolectables en bombas"},
	{"28", "As de diamantes", "Convierte todos los recolectables en monedas"},
	{"29", "As de picas", "Convierte todos los recolectables en llaves"},
	{"30", "As de corazones", "Convierte todos los recolectables en corazones"},
	{"31", "Comodín", "Teletransporta a la sala del Diablo{{DevilRoom}}/Ángel{{AngelRoom}}"},
	{"32", "Hagalaz", "Destruye todas las rocas de la habitación"},
	{"33", "Jera", "Duplica los recolectables de la habitación"},
	{"34", "Ehwaz", "Genera una trampilla"},
	{"35", "Dagaz", "+1 corazón de alma#Elimina efectos de maldición"},
	{"36", "Ansuz", "Visión completa del mapa en esta planta"},
	{"37", "Perthro", "Cambia los objetos coleccionables"},
	{"38", "Berkano", "Genera 3 arañas azules y 3 moscas azules"},
	{"39", "Algiz", "Invencibilidad durante 30 segundos"},
	{"40", "Runa vacía", "Efecto de runa aleatorio#25 % de probabilidad de que vuelva a aparecer"},
	{"41", "Runa negra", "Inflige 40 de daño a todos los enemigos#Estadística aleatoria por cada objeto coleccionable de la habitación# (Destruye todos los objetos de la habitación)"},
	{"42", "Carta del caos", "Carta lanzable que mata al instante"},
	{"43", "Tarjeta de crédito", "Borra el precio de todos los objetos de la tienda actual o el Pacto con el Diablo, haciendo que todo sea gratis"},
	{"44", "Carta de las reglas", "Al usarlo muestra consejos \"útiles\" "},
	{"45", "Carta en contra de la humanidad", "Llena toda la habitación de caca"},
	{"46", "Rey suicida", "Te mata instantáneamente y genera 10 recolectables/coleccionables en el suelo"},
	{"47", "Carta sal de la cárcel gratis", "Abre todas las puertas de la habitación actual"},
	{"48", "Carta ¿?", "Activa el objeto activable sin gastar cargas "},
	{"49", "Dado roto", "Cambia todos los pedestales y recolectables de la habitación actual"},
	{"50", "Contacto de emergencia", "Dos manos de Mamá caen y cogen a un enemigo"},
	{"51", "Carta sagrada", "Otorga el efecto de Manto Sagrado (Holy Mantle) en una habitación#(El siguiente daño recibido es 0)#25 % de probabilidad de generar otra carta sagrada"},
	{"52", "Enorme crecimiento", "↑ +7 de daño#↑ +30 de rango#↑ +Tamaño#Rompe rocas#El efecto es para la habitación actual"},
	{"53", "Memoria antigua", "Al usarla genera 3 cartas aleatorias"},
	{"54", "Paseo de época", "Ralentiza a los enemigos#↓ -0,5 de velocidad#-1 de velocidad de disparo#El efecto es para la habitación actual"},
}
 
 
---------- Pills ----------
 
EID.descriptions["spa"].unidentifiedPill = "Píldora sin identificar"
 
EID.descriptions["spa"].pills={
	{"0", "Vaya pedo", "Genera una nube de gas"},
	{"1", "Mal viaje", "Inflige 1 corazón de daño"},
	{"2", "Bolas de acero", "+2 corazones de alma"},
	{"3", "Las bombas son llaves", "Cambia el número de bombas por el de llaves"},
	{"4", "Diarrea explosiva", "Invoca 5 bombas troll"},
	{"5", "Salud completa", "Vida al completo"},
	{"6", "Menos vida", "↓ 1 menos de vida"},
	{"7", "Más vida", "↑ 1 más de vida"},
	{"8", "Sin efecto", "Sin efecto"},
	{"9", "Pubertad", "Al comer 3 te transformas en Adulto "},
	{"10", "Mosca bonita", "Añade 1 mosca orbital"},
	{"11", "Menos rango", "↓ -2 de rango"},
	{"12", "Más rango", "↑ +2,5 de rango"},
	{"13", "Menos velocidad", "↓ -0,12 de velocidad"},
	{"14", "Más velocidad", "↑ +0,15 de velocidad"},
	{"15", "Menos lágrimas", "↓ -0,28 de lágrimas"},
	{"16", "Más lágrimas", "↑ +0,35 de lágrimas"},
	{"17", "Menos suerte", "↓ -1 de suerte"},
	{"18", "Más suerte", "↑ +1 de suerte"},
	{"19", "¡Teletransporta!", "Teletransporta a una habitación aleatoria"},
	{"20", "¡48 horas de energía!", "Recarga tu objeto activable#Genera 1 o 2 baterías"},
	{"21", "Hematémesis", "Drena todos los corazones menos el último#Genera de 1 a 4 corazones rojos"},
	{"22", "Parálisis", "No puedes moverte durante unos segundos"},
	{"23", "¡Puedo ver para siempre!", "Abre las habitaciones secretas de la planta actual"},
	{"24", "Feromonas", "Encanta a todos los enemigos de la habitación"},
	{"25", "Amnesia", "Oculta el mapa"},
	{"26", "Fiesta de limonada", "Genera charcos que dañan a los enemigos"},
	{"27", "¿Eres un mago?", "Durante 60 segundos disparas en diagonal"},
	{"28", "¡Oxicodona!", "Solo te hacen la mitad del daño en la habitación actual"},
	{"29", "¡Adicto!", "Recibe un corazón de daño en la habitación actual"},
	{"30", "Relaxante", "Genera una caca al andar durante 2 segundos"},
	{"31", "¿¿??", "Maldición del Laberinto (Curse of the maze) en la planta actual"},
	{"32", "Una te hace grande", "Creces#No afecta a la hitbox"},
	{"33", "Una te hace pequeño", "Te haces pequeño#La hitbox se hace más pequeña"},
	{"34", "¡Infestado!", "Genera 1 mosca azul por cada caca de la habitación"},
	{"35", "¿Infestado?", "Genera 1 araña azul por cada enemigo de la habitación#Genera entre 1 y 3 arañas cuando no hay enemigos"},
	{"36", "Píldora de visión", "Efecto de invencibilidad corto"},
	{"37", "¡Visión retro!", "Pixela la pantalla durante 30 segundos"},
	{"38", "¡Amigos hasta el fin!", "Invoca 3 moscas aliadas"},
	{"39", "X-Lax", "Genera una piscina de creep resbaladizo"},
	{"40", "Hay algo mal", "Genera una piscina de creep ralentizante"},
	{"41", "¡Estoy soñoliento!", "Ralentiza a todos los enemigos de la habitación"},
	{"42", "¡Estoy excitado!", "Acelera a todos los enemigos de la habitación"},
	{"43", "¡Glup!", "Consume el trinket actual y ganas su efecto de manera permanente"},
	{"44", "¡Horf!", "Dispara una lágrima de Ipecac"},
	{"45", "¡Es como si caminara sobre el sol!", "Efecto de invencibilidad corto"},
	{"46", "¡Vurp!", "Genera la última píldora usada"},
} 
 
---------- Sacrifice Room ----------
EID.descriptions["spa"].sacrificeHeader = "[Siguiente pago de la sala del Sacrificio]"
 
EID.descriptions["spa"].sacrifice={
	{"1", "", "50 % de probabilidad de 1 moneda#100 % de probabilidad de 1 bomba, al matar al Jefe de B1 en menos de 1 minuto"},
	{"2", "", "50 % de probabilidad de 1 moneda#100 % de probabilidad de 1 bomba, al matar al Jefe de B1 en menos de 1 minuto"},
	{"3", "", "67 % más de probabilidad de que aparezca la sala del Ángel{{AngelRoom}} en lugar de la del Diablo"},
	{"4", "", "50 % de probabilidad de 1 cofre aleatorio"},
	{"5", "", "33 % de probabilidad de 3 monedas#67 % más de probabilidad de que aparezca la sala del Ángel{{AngelRoom}} en lugar de la del Diablo"},
	{"6", "", "33 % de probabilidad de teletransportar a la sala del Ángel{{AngelRoom}}/Diablo{{DevilRoom}}#67 % de probabilidad de un cofre aleatorio"},
	{"7", "", "33 % de probabilidad de 1 objeto aleatorio de la sala del Ángel{{AngelRoom}}#67 % de probabilidad de 1 corazón de alma"},
	{"8", "", "100 % de probabilidad de generar 7 bombas troll"},
	{"9", "", "100 % de probabilidad de generar al ángel \"Uriel\""},
	{"10", "", "50 % de probabilidad de 7 corazones de alma#50 % de probabilidad de 30 monedas"},
	{"11", "", "100 % de probabilidad de generar al ángel \"Gabriel\""},
	{"12", "", "50 % de probabilidad de teletransportar al piso de la  \"Dark Room\" (Habitación Oscura)"},
}
 
---------- Dice Room ----------
EID.descriptions["spa"].diceHeader = "[Efecto del dado]"
 
EID.descriptions["spa"].dice={
	{"1", "", "Cambia tus objetos#(no afecta a los recolectables)"},
	{"2", "", "Cambia los recolectables de la habitación"},
	{"3", "", "Cambia todos los recolectables de la planta"},
	{"4", "", "Cambia los objetos de los pedestales de la planta#No afecta los Pactos del Diablo"},
	{"5", "", "Cambia y reinicia la planta actual"},
	{"6", "", "Cambia todos tus objetos y recolectables, además de los objetos de toda la planta"}
}
 
---------- Transformations ----------
EID.descriptions["spa"].transformations = {
	"",						-- 0 = none
	"Guppy",				-- 1
	"Tipo divertido",		-- 2
	"Señor de las moscas",  -- 3
	"Unidos",				-- 4
	"Colocado",				-- 5
	"Mamá",					-- 6
	"Oh, mierda",			-- 7
	"Bob",					-- 8
	"Leviatán",				-- 9
	"Serafín",				-- 10
	"Supervagabundo",		-- 11
	"Ratón de biblioteca",	-- 12
	"Bebé araña",			-- 13
	"Adulto",				-- 14
	"Colosal"				-- 15
}
