------------------------------------------------------------------
-----  Basic English descriptions based on Platinumgod.co.uk -----
------------------------------------------------------------------

-- FORMAT: Item ID | Name| Description
-- '#' = starts new line of text

--Special character markup:
-- ↑ = Up Arrow   |  ↓ = Down Arrow    | ! = Warning

-- init tr_tr table
EID.descriptions["tr_tr"] = {}
EID.descriptions["tr_tr"].custom = {} -- table for custom entity descriptions

EID.descriptions["tr_tr"].collectibles={
	{"1", "The Sad Onion", "↑ +0.7 Gözyaşı"},
	{"2", "The Inner Eye", "Üçlü atış#↓ Gözyaşı azalır"},
	{"3", "Spoon Bender", "Takip eden gözyaşları"},
	{"4", "Cricket's Head", "↑ +0.5 Hasar#↑ +50% Hasar yüzdesi"},
	{"5", "My Reflection", "Gives tears a boomerang effect#↑ +1.5 Range up#↑ +0.6 Shot Speed up#↑ +1 Tear Height"},
	{"6", "Number One", "↑ +1.5 Tears up#↓ -17.62 Range down#↑ +0.76 Tear Height"},
	{"7", "Blood of the Martyr", "↑ +1.0 Hasar#↑ +50% eğer Book of Belial kitabına sahip isen"},
	{"8", "Brother Bobby", "Normal gözyaşı arkadaşı#Gözyaşı başına 3.5 Hasar verir"},
	{"9", "Skatole", "Bütün sinek düşmanları artık arkadaş canlısı"},
	{"10", "Halo of Flies", "+2 sinek yörüngeci#Düşman ateşini engeller"},
	{"11", "1up!", "↑ +1 hayat#Full can ile tekrar doğarsın"},
	{"12", "Magic Mushroom", "↑ +1 Health up#↑ +0.3 Damage up#↑ +50% Damage Multiplier#↑ +5.25 Range up#↑ +0.3 Speed up#↑ +0.5 Tear Height#Full health!"},
	{"13", "The Virus", "Poison touch#↓ -0.1 Speed down#Enemies can drop black hearts if poisoned"},
	{"14", "Roid Rage", "↑ +0.6 Speed up#↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"15", "<3", "↑ +1 HP#Full can"},
	{"16", "Raw Liver", "↑ +2 Can#Full can"},
	{"17", "Skeleton Key", "+99 Anahtar"},
	{"18", "A Dollar", "+99 Coins"},
	{"19", "Boom!", "+10 Bomba"},
	{"20", "Transcendence", "Uçuş!"},
	{"21", "The Compass", "Haritadaki tüm ikonları açar#Odaların diziliş şeklini göstermez"},
	{"22", "Lunch", "↑ +1 Health up"},
	{"23", "Dinner", "↑ +1 Health up"},
	{"24", "Dessert", "↑ +1 Health up"},
	{"25", "Breakfast", "↑ +1 Health up"},
	{"26", "Rotten Meat", "↑ +1 Health up"},
	{"27", "Wooden Spoon", "↑ +0.3 Hız"},
	{"28", "The Belt", "↑ +0.3 Hız"},
	{"29", "Mom's Underwear", "↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"30", "Mom's Heels", "↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"31", "Mom's Lipstick", "↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"32", "Wire Coat Hanger", "↑ +0.7 Gözyaşı"},
	{"33", "The Bible", "Oda için uçuş#Annenin ayağını ve annenin kalbi bosslarını anında öldürür#!!! Satanda kullanıldığında SENİ öldürür"},
	{"34", "The Book of Belial", "↑ +2 Hasar#↑ +12.5% Şeytan odası şansı#↑ Blood of the Martyr var ise +50% Hasar yüzdesi"},
	{"35", "The Necronomicon", "Odadaki her şeye 40 hasar verir"},
	{"36", "The Poop", "Bir bok çıkartır#Deliğe yerleştirilip bomba ile köprü yapılabilir"},
	{"37", "Mr. Boom", "Oyuncunun olduğu yere 100 hasar veren büyük bir bomba bırakır"},
	{"38", "Tammy's Head", "Isaacin etrafında halka şeklinde 10 gözyaşı atar"},
	{"39", "Mom's Bra", "Odadaki tüm düşmanları 4 saniyeliğine dondurur"},
	{"40", "Kamikaze!", "Causes an explosion at the players location#Deals 40 damage"},
	{"41", "Mom's Pad", "Odadaki tüm düşmanları 5 saniyeliğine korkutur"},
	{"42", "Bob's Rotten Head", "Throwable poison bomb"},
	{"43", "", "<item does not exist>"},
	{"44", "Teleport!", "Teleports Isaac into a random room except I AM ERROR rooms"},
	{"45", "Yum Heart", "Heal 1 red heart"},
	{"46", "Lucky Foot", "↑ +1.0 Luck up#Better chance to win while gambling#Increases room clearing drop chance"},
	{"47", "Doctor's Remote", "Kullanılabilir Epic Fetus!#Kontrol edilebilir hava saldırısı"},
	{"48", "Cupid's Arrow", "Delici gözyaşları"},
	{"49", "Shoop da Whoop!", "Yüksek hasarlı brimstone lazeri"},
	{"50", "Steven", "↑ +1 Hasar"},
	{"51", "Pentagram", "↑ +1.0 Hasar#↑ +10% Şeytan odası şansı"},
	{"52", "Dr. Fetus", "Bomba gözyaşları!"},
	{"53", "Magneto", "Magnetic attraction for Pick-ups"},
	{"54", "Treasure Map", "Odaların diziliş şeklini açar"},
	{"55", "Mom's Eye", "Chance to shoot a tear backwards#Chance is 100% at 2 Luck"},
	{"56", "Lemon Mishap", "Limonata havuzu bırakır#Saniyede 66 dokunma hasarı verir"},
	{"57", "Distant Admiration", "Orta-menzil sinek yörüngeci#Saniyede 75 dokunma hasarı verir"},
	{"58", "Book of Shadows", "10 Saniyeliğine dokunulmazlık"},
	{"59", "", "<item does not exist>"},
	{"60", "The Ladder", "Küçük boşluklar üzerinde yürü"},
	{"61", "", "<item does not exist>"},
	{"62", "Charm of the Vampire", "Heals half a heart every 13 enemies killed"},
	{"63", "The Battery", "Aktif itemler artık iki defa şarj edilebilir"},
	{"64", "Steam Sale", "-50% on shop items#Getting this item two times will make everything free"},
	{"65", "Anarchist Cookbook", "Odanın ortasına yakın 6 troll bombası çıkartır"},
	{"66", "The Hourglass", "8 Saniyeliğine düşmanları yavaşlatır"},
	{"67", "Sister Maggy", "Normal tear familiar#Deals 3.5 Damage per tear"},
	{"68", "Technology", "Gözyaşları artık lazer"},
	{"69", "Chocolate Milk", "Şarj edilebilir gözyaşları#↑ 400%e kadar hasar#↓ Gözyaşı azalır"},
	{"70", "Growth Hormones", "↑ +1.0 Damage up#↑ +0.4 Speed up"},
	{"71", "Mini Mush", "↑ +0.3 Speed up#↓ -4.25 Range down*#↑ +1.5 Tear height*#(*both add up to a slight Range up)#↑ Size down"},
	{"72", "Rosary", "+3 Soul Hearts#Bible is more common"},
	{"73", "Cube of Meat", "LVL1: Yörüngeç#LVL2: Ateş eden yörüngeç#LVL3: Meat boy LVL 1#LVL4: Meat boy LVL 2"},
	{"74", "A Quarter", "+25 Altın"},
	{"75", "PHD", "Daha iyi haplar# +1 hap#2 Kalp iyileştirir#Kan başığı makinalarından daha fazla para"},
	{"76", "X-Ray Vision", "Gizli oda girişlerini gösterir"},
	{"77", "My Little Unicorn", "Invincibility#40 contact damage"},
	{"78", "Book of Revelations", "+1 Ruh kalbi#Kullanılırsa daha yüksek atlı şansı#↑ +17.5% Şeytan odası şansı"},
	{"79", "The Mark", "↑ +1.0 Damage up#↑ +0.2 Speed up#+1 Soul Heart"},
	{"80", "The Pact", "↑ +0.5 Damage up#↑ +0.7 Tears up#+2 Soul Hearts"},
	{"81", "Dead Cat", "↑ +9 Hayat#1 Kalp ile tekrar doğarsın#↓ Kırmızı kalp sayını 1e indirir"},
	{"82", "Lord of the Pit", "Uçuş#↑ +0.3 Hız"},
	{"83", "The Nail", "+1 Soul heart#↑ +0.7 Damage up#↓ -0.18 Speed down#Deal contact Damage#Crush rocks"},
	{"84", "We Need To Go Deeper!", "Katı geçmek için bir tuzak kapısı yaratır#10% şans ile sürünme alanı tuzak kapısı şansı"},
	{"85", "Deck of Cards", "1 Kart çıkartır"},
	{"86", "Monstro's Tooth", "1 vuruş için Monstro çıkartır"},
	{"87", "Loki's Horns", "4 Yönde de ateş etme şansı"},
	{"88", "Little Chubby", "Öne atılan arkadaş#Saniyede 52.5 dokunma hasarı verir"},
	{"89", "Spider Bite", "Yavaşlatma gözyaşı atma şansı"},
	{"90", "The Small Rock", "↑ +1 Hasar#↑ +0.2 Gözyaşı#↓ -0.2 Hız eksilir"},
	{"91", "Spelunker Hat", "Bitişik odaların tiplerini gösterir#Gizli odaları, Süper gizli odaları ve MiniBoss odalarını da göstereblir"},
	{"92", "Super Bandage", "↑ +1 HP#+2 Ruh Kalbi"},
	{"93", "The Gamekid", "Dokunulmazlık + dokunma hasarı#Düşmanı yemek canı iyileştirir"},
	{"94", "Sack of Pennies", "Her 2 odada rastgele bir altın düşürür"},
	{"95", "Robo-Baby", "Lazer gözyaşları#Atış başına 3.5 hasar verir"},
	{"96", "Little C.H.A.D.", "Her 3 odada yarım kırmızı kalp düşürür"},
	{"97", "The Book of Sin", "Rastgele bir pickup çıkartır"},
	{"98", "The Relic", "Spawns 1 Soul heart every 5-6 rooms"},
	{"99", "Little Gish", "Yavaşlatan gözyaşları#Atış başına 3.5 hasar verir"},
	{"100", "Little Steven", "Takip eden gözyaşları#Atış başına 3.5 hasar verir"},
	{"101", "The Halo", "↑ +1 Health up#↑ +0.3 Damage up#↑ +0.2 Tears up#↑ +0.25 Range up#↑ +0.3 Speed up#↑ +0.5 Tear Height"},
	{"102", "Mom's Bottle of Pills", "1 Hap çıkartır"},
	{"103", "The Common Cold", "Zehir gözyaşları atma şansı"},
	{"104", "The Parasite", "Temas ettiğinde gözyaşları ikiye bölünür#Bölünen gözyaşları yarım hasar verir"},
	{"105", "The D6", "Odadaki itemleri değiştirir"},
	{"106", "Mr. Mega", "↑ Bomb damage x2.25#+5 Bombs"},
	{"107", "The Pinking Shears", "Uçuş#Vücudun saniyede 82.5 hasar ile düşmanlara saldırır"},
	{"108", "The Wafer", "Alınan tüm hasarı yarım kalbe indirir"},
	{"109", "Money = Power", "Eldeki her altın için ↑ +0.04 Hasar"},
	{"110", "Mom's Contacts", "Chance to shoot Freezing Tears#↑ +0.25 Range up#↑ +0.5 Tear Height"},
	{"111", "The Bean", "Zehir osuruğu"},
	{"112", "Guardian Angel", "Yörüngeç#Tüm yörüngeçleri hızlandırır#Düşman ateşlerini bloklar#Saniyede 105 dokunma hasarı verir"},
	{"113", "Demon Baby", "Otomatik ateş eden arkadaş#Atış başına 3 hasar verir"},
	{"114", "Mom's Knife", "Kontrol edilebilir bıçak atağı#Bıçak elde iken Isaacin 2x hasarını verir ve en uzağa atıldığında 6x hasar verir"},
	{"115", "Ouija Board", "Hayalet gözyaşları"},
	{"116", "9 Volt", "Aktif itemler için -1 Şarj#Eldeki itemi tamamen şarj eder"},
	{"117", "Dead Bird", "Hasar aldığında kuş çıkartır#Kuş saniyede 4 dokunma hasarı verir"},
	{"118", "Brimstone", "Şarj edip sürekli hasar veren bir kan lazeri atar"},
	{"119", "Blood Bag", "↑ +1 HP#↑ +0.3 Hız#5 Kalp iyileştirir"},
	{"120", "Odd Mushroom", "↑ +1.7 Gözyaşı#↑ +0.3 Hız#↓ -10% Hasar düşer#↓ -0.4 Ekstra hasar düşer"},
	{"121", "Odd Mushroom", "↑ +1 Boş kalp konteynırı#↑ +0.3 Hasar#↑ +0.25 Menzil#↓ -0.1 Hız azalır#↑ +0.5 Gözyaşı yüksekliği"},
	{"122", "Whore of Babylon", "!!! Yarım kırmızı kalpte beya daha azında iken:#↑ +1.5 Hasar#↑ +0.3 Hız"},
	{"123", "Monster Manual", "Random familiar for current room"},
	{"124", "Dead Sea Scrolls", "Rastgele aktif item efekti"},
	{"125", "Bobby-Bomb", "Takip eden bombalar#+5 Bomba"},
	{"126", "Razor Blade", "Oda için ↑ +1.2 hasar#↓ Sana 1 Kalp hasarı verir"},
	{"127", "Forget Me Now", "{{Warning}} TEK KULLANIM {{Warning}}#Tüm katı baştan değiştir"},
	{"128", "Forever alone", "Sinek yörüngeci#Uzakta#Saniyede 30 dokunma hasarı verir"},
	{"129", "Bucket of Lard", "↑ +2 Boş kalp konteynırı#↓ -0.2 Hız düşer#Yarım kalp iyileştirir"},
	{"130", "A Pony", "Elde ike uçuş sağlar#Hızın 1.5tan düşük ise hızını 1.5 yapar#Kullanıldığında bir yönde hızla ilerler"},
	{"131", "Bomb Bag", "Her 2-3 odada 1 Bomba pickupı düşürür"},
	{"132", "A Lump of Coal", "Gözyaşının gittiği mesafeye göre daha çok hasar verir"},
	{"133", "Guppy's Paw", "!!! Çevir:#1 Kırmızı kalp to 3 Ruh kalbi"},
	{"134", "Guppy's Tail", "Daha fazla kasa çıkar"},
	{"135", "IV Bag", "Portatif kan bankası#Yarım kalp = 1-3 Altın"},
	{"136", "Best Friend", "Patlayan bir yanıltıcı#Düşmanları üzerine çeker"},
	{"137", "Remote Detonator", "Bombaları istediğinde patlat#+5 bomba"},
	{"138", "Stigmata", "↑ +1 Health up#↑ +0.3 Damage up"},
	{"139", "Mom's Purse", "You can now hold 2 trinkets"},
	{"140", "Bob's Curse", "Poison bombs#+5 bombs"},
	{"141", "Pageant Boy", "7 Rastgele altın düşürür"},
	{"142", "Scapular", "Yarım kalbe kadar indiğinde, 1 Ruh kalbi kazanırsın#(Odada 1 kere)"},
	{"143", "Speed Ball", "↑ +0.3 Hız#↑ +0.2 Gözyaşı hızı"},
	{"144", "Bum Friend", "Altınları pickuplara çevirir"},
	{"145", "Guppy's Head", "2-4 mavi sinek çıkartır"},
	{"146", "Prayer Card", "+1 ebedi kalp"},
	{"147", "Notched Axe", "Break rocks in current room on touch"},
	{"148", "Infestation", "Spawn flies when you get hit"},
	{"149", "Ipecac", "Explosive poison tears#↑ +40 Damage up#↓ Tears down"},
	{"150", "Tough Love", "Diş atma şansı#Dişler hasarının 3.2x katını verir"},
	{"151", "The Mulligan", "Düşmanlara gözyaşı vurunca 1/6 şans ile sinek çıkartır"},
	{"152", "Technology 2", "Permanent laser attack!#↓ -35% Damage down"},
	{"153", "Mutant Spider", "Dörtlü atış!#↓ Gözyaşı azalır"},
	{"154", "Chemical Peel", "Sol göz için ↑ +2 Hasar"},
	{"155", "The Peeper", "Odada gezer#Saniyede 17.1 hasar verir"},
	{"156", "Habit", "Hasar alınca +1 şarj"},
	{"157", "Bloody Lust", "Her hasar aldığında ↑ Hasar artar #Kat başına 6 defaya kadar#Kat boyunca sürer"},
	{"158", "Crystal Ball", "Reveal full map#Drops random Card or soul heart"},
	{"159", "Spirit of the Night", "Uçuş#Hayalet gözyaşları"},
	{"160", "Crack the Sky", "Düşmanların yakınında 5 Işık hüzmesi çıkartır#Senin hasarın +20 verir"},
	{"161", "Ankh", "Ölünce ??? (Blue Baby) olarak tekrar doğarsın"},
	{"162", "Celtic Cross", "Hasar alınca dokunulmazlık şansı"},
	{"163", "Ghost Baby", "Hayalet gözyaşı arkadaşı#Atış başına 3.5 hasar verir"},
	{"164", "The Candle", "Mavi ateş çıkartır#Dokunma hasarı verir#Düşman gözyaşlarını bloklar#2 Saniye sonra yok olur"},
	{"165", "Cat-o-nine-tails", "↑ +1 Hasar#↑ +0.23 Gözyaşı hızı"},
	{"166", "D20", "Bütün pickupları değiştir"},
	{"167", "Harlequin Baby", "V şeklinde iki gözyaşı atar#Atış başına 4 hasar verir"},
	{"168", "Epic Fetus", "Gözyaşları yerine kontrol edilebilir hava saldırısı#Hasarının 20 katını verir"},
	{"169", "Polyphemus", "Mega Gözyaşları!#↑ +100% Hasar#↑ +4 ekstra hasar#↓ Gözyaşı azalır"},
	{"170", "Daddy Longlegs", "Düşmanların üstüne basar#Saniyede 40 hasar verir"},
	{"171", "Spider Butt", "Slows down enemies for 4 seconds#10 Damage to all enemies"},
	{"172", "Sacrificial Dagger", "Yörüngeç bıçağı#Düşman gözyaşlarını bloklar#Saniyede 225 hasar verir"},
	{"173", "Mitre", "Ruh kalbi bulma şansını arttırır"},
	{"174", "Rainbow Baby", "Rastgele gözyaşı atar#Atış başına 3-5 hasar verir"},
	{"175", "Dad's Key", "Opens all doors in the current room, including secret rooms"},
	{"176", "Stem Cells", "↑ +1 Health up#↑ +0.16 Shot Speed up"},
	{"177", "Portable Slot", "Portatif slot makinesi"},
	{"178", "Holy Water", "Leaves pool of creep when you get hit#Deals 24 damage per second"},
	{"179", "Fate", "Uçuş#+1 ebedi kalp"},
	{"180", "The Black Bean", "Dokunulduğunda osurursun"},
	{"181", "White Pony", "Elde iken uçuş sağlar#Hızın 1.5den küçük ise 1.5 Hız verir#Kullanıldığında kutsal ve hızlı hareket eder"},
	{"182", "Sacred Heart", "Homing tears#↑ +1 Health up#↑ 230% + 1 Damage up#↓ -0.4 Tears down#↓ -0.25 Shot Speed down#↑ +4.125 Range up"},
	{"183", "Tooth Picks", "↑ +0.7 Gözyaşı#↑ +0.16 Gözyaşı hızı"},
	{"184", "Holy Grail", "Grants flight#↑ +1 Health up"},
	{"185", "Dead Dove", "Uçus#Hayalet gözyaşları"},
	{"186", "Blood Rights", "Her düşmana 40 Hasar verir#Kullandımda sana 1 hasar verir"},
	{"187", "Guppy's Hairball", "Büyüyen kıl yumağı#Etrafında salınır#Düşman öldürdüğünde büyür#Büyük yumak daha fazla hasar verir"},
	{"188", "Abel", "Mirrors your movement#Shoots towards the player#Deals 3.5 damage per shot"},
	{"189", "SMB Super Fan", "↑ +1 HP#↑ +0.3 Hasar#↑ +0.2 Gözyaşı#↑ +0.5 Menzil#↑ +0.2 Hız#↑ +1.0 Gözyaşı yüksekliği#Full can"},
	{"190", "Pyro", "+99 Bomba"},
	{"191", "3 Dollar Bill", "Her 2-3 saniyede bir rastgele gözyaşı efekti"},
	{"192", "Telepathy For Dummies", "Homing tears for current room"},
	{"193", "MEAT!", "↑ +1 Health up#↑ +0.3 Damage up"},
	{"194", "Magic 8 Ball", "↑ +0.16 Shot speed up#+1 card"},
	{"195", "Mom's Coin Purse", "4 Hap çıkartır"},
	{"196", "Squeezy", "2 Ruh kalbi çıkartır#↑ +0.4 Gözyaşı"},
	{"197", "Jesus Juice", "↑ +0.5 Damage up#↑ +0.25 Range up.#↑ +0.5 Tear Height"},
	{"198", "Box", "Her tipten 1 pickup düşürür"},
	{"199", "Mom's Key", "+2 Anahtar#Kasalardan daha fazla şey düşer"},
	{"200", "Mom's Eyeshadow", "Aşık eden gözyaşı atma şansı"},
	{"201", "Iron Bar", "↑ +0.3 Hasar#Afallatan gözyaşı atma şansı"},
	{"202", "Midas' Touch", "Dokunduğun düşmanları altına çevir#Elindeki altın sayısına göre dokunma hasarı verir#Altın düşmanlar altın düşürür"},
	{"203", "Humbleing Bundle", "Doubles all pickups"},
	{"204", "Fanny Pack", "Hasar aldığında 50% ihtimal ile rastgele pickup düşürür"},
	{"205", "Sharp Plug", "-2 Hearts = Fully charges item when pressing space#!!! Only works when item has no charges!"},
	{"206", "Guillotine", "↑ +1 Damage up#↑ Tears up#Your Head is now an orbital#You will shoot from the head#The head deals 105 contact damage"},
	{"207", "Ball of Bandages", "LVL1: Yörüngeç#LVL2: Ateş eden yörüngeç#LVL3: Bandage girl#LVL4: Bandage girl LVL2"},
	{"208", "Champion Belt", "↑ +1 Hasar#!!! Şampiyon düşmanlar daha fazla çıkar"},
	{"209", "Butt Bombs", "↑ +5 Bomba#Patlamalar odadaki düşmanları afallatır ve hasar verir"},
	{"210", "Gnawed Leaf", "1 saniye sabit durduğunda dokunulmazlık"},
	{"211", "Spiderbaby", "Spawn 1-2 spiders when getting hit"},
	{"212", "Guppy's Collar", "↑ 50% tekrar doğma şansı"},
	{"213", "Lost Contact", "Korumalı gözyaşları#Gözyaşları düşman ateşlerini bloklar#↓ -0.16 Gözyaşı hızı azalır"},
	{"214", "Anemic", "↑ +5 Range up#Leave creep on floor when getting hit"},
	{"215", "Goat Head", "Şeytan {{DevilRoom}}/ Melek{{AngelRoom}} odası şansı ↑ 100%"},
	{"216", "Ceremonial Robes", "↑ +1 Hasar#+3 Siyah kalp"},
	{"217", "Mom's Wig", "Ateş ederken mavi örümcek çıkarma şansı#Alındığında 1 kalp iyileştirir"},
	{"218", "Placenta", "↑ +1 HP#Yavaşça canını doldurur"},
	{"219", "Old Bandage", "↑ +1 Boş kalp konteynırı#Hasar alındığında kırmızı kalp çıkarma şansı"},
	{"220", "Sad Bombs", "Gözyaşı patlaması!#+5 Bomba"},
	{"221", "Rubber Cement", "Bouncing tears"},
	{"222", "Anti-Gravity", "↑ +2 Gözyaşı#Anti-Yerçekimi gözyaşları"},
	{"223", "Pyromaniac", "Patlamalar seni iyileştirir#+5 Bomba"},
	{"224", "Cricket's Body", "↑ +1 Tears up#↓ -10 Range down#Tears split up in 4 on hit#Splitted tears deal half damage"},
	{"225", "Gimpy", "Hasar alınca Ruh/Siyah kalp çıkarma şansı#Düşman öldürürken yarım kırmızı kalp çıkarma şansı"},
	{"226", "Black Lotus", "↑ +1 HP#+1 Ruh kalbi#+1 Siyah kalp"},
	{"227", "Piggy Bank", "+3 Altın#Hasar aldığında 1-2 altın çıkartır#Keeper için 0-1"},
	{"228", "Mom's Perfume", "Chance to shoot fearing tears#↑ +1 Tears up"},
	{"229", "Monstro's Lung", "Gözyaşları artık şarj edilip pompalı türek tarzında ateş edilebilir"},
	{"230", "Abaddon", "↑ +1.5 Damage up#↑ +0.2 Speed up#Fear tears#↓ Removes all red hearts#+6 Black hearts"},
	{"231", "Ball of Tar", "Yavaşlatma gözyaşı atma şansı#Yavaşlatan havuz sıvısı bırakır"},
	{"232", "Stop Watch", "Permanent slow effect#(activated when getting hit)#↑ +0.3 Speed up"},
	{"233", "Tiny Planet", "Gözyaşları etrafında yörünge yapar#↑ +7.0 Gözyaşı yüksekliği#Hayalet gözyaşı"},
	{"234", "Infestation 2", "Düşman öldürdüğünde mavi örümcek çıkartır"},
	{"235", "", "<item does not exist>"},
	{"236", "E. Coli", "Dokunulduğunda düşmanı boka çevirir"},
	{"237", "Death's Touch", "Orak gözyaşları!#↑ +1.5 Hasar#↓ -0.3 Gözyaşı azalır#Delici gözyaşları"},
	{"238", "Key Piece 1", "!!! Mega Satan odası için anahtar parçası!#Daha fazla Melek odası {{AngelRoom}} çıkar"},
	{"239", "Key Piece 2", "!!! Mega Satan odası için anahtar parçası!#Daha fazla Melek odası {{AngelRoom}} çıkar"},
	{"240", "Experimental Treatment", "All Stats ↑/↓ a random number"},
	{"241", "Contract from Below", "Düşen pickupları iki katına çıkartır#Greed modunda işe yaramaz"},
	{"242", "Infamy", "50% şans ile düşman ateşini bloklar"},
	{"243", "Trinity Shield", "Gözyaşı bloklayan kalkan"},
	{"244", "Tech.5", "Rastgele lazer tipi gözyaşları at"},
	{"245", "20/20", "Doubles all your shots"},
	{"246", "Blue Map", "Gizli odaları gösterir"},
	{"247", "BFFS!", "Your familiars deal double damage"},
	{"248", "Hive Mind", "Blue Spiders/flies deal double damage"},
	{"249", "There's Options", "1 yerine 2 Boss itemi çıkar#!!! Sadece biri seçilebilir"},
	{"250", "BOGO Bombs", "Bütün düşen bombaları iki katına çıkart"},
	{"251", "Starter Deck", "2 Kart taşıyabilirsin#Bütün hapları karta çevirir"},
	{"252", "Little Baggy", "2 Hap taşıyabilirsin#Bütün kartları hapa çevirir"},
	{"253", "Magic Scab", "↑ +1 Luck up#↑ +1 Health up"},
	{"254", "Blood Clot", "↑ +1 Damage up#↑ +5 Range up#!!! Applies only for the left eye"},
	{"255", "Screw", "↑ +0.5 Gözyaşı#↑ +0.2 Gözyaşı hızı"},
	{"256", "Hot Bombs", "Burning bombs#+5 Bombs"},
	{"257", "Fire Mind", "Patlayanb gözyaşı şansı#Gözyaşları düşmanları yakar"},
	{"258", "Missing No.", "Aldığında bütün itemlerini ve özelliklerini değiştirir, kat değişiminde de aynı efekti verir"},
	{"259", "Dark Matter", "↑ +1 Hasar#Korku gözyaşları atma şansı"},
	{"260", "Black Candle", "Lanetlere bağışıklık#+1 Siyah kalp#Daha yüksek Şeytan{{DevilRoom}} / Melek{{AngelRoom}} odası şansı"},
	{"261", "Proptosis", "↑ +100% Damage up#↓ Dealt damage decreases for traveled distance of the tear"},
	{"262", "Missing Page 2", "+1 black heart#When down to 1 Heart, damages all enemies in the room"},
	{"263", "", "<item does not exist>"},
	{"264", "Smart Fly", "Yörüngeç#Hasar aldığında düşmanlara saldırır#Saniyede 22.5 hasar verir"},
	{"265", "Dry Baby", "Düşman tarafından vurulduğunda, 10% şans ile tüm düşmanlara hasar verme şansı#Arkasına saklanılabilir"},
	{"266", "Juicy Sack", "Yavaşlatan sıvı bırakır#Oda temizlendiğinde 1-2 mavi örümcek çıkartır"},
	{"267", "Robo-Baby 2.0", "Lazer atar#Atış başına 3.5 hasar verir#Ateş ettiğin yönde hareket eder"},
	{"268", "Rotten Baby", "Oyuncu ateş ederken mavi sinekler çıkartır"},
	{"269", "Headless Baby", "Saniyede 6 hasar veren bir sıvı bırakır"},
	{"270", "Leech", "Düşman öldürdüğünde yarım siyah kalp verir#Saniyede 3.2 hasar"},
	{"271", "Mystery Sack", "Bir kaç odada bir rastgele pickup düşürür"},
	{"272", "BBF", "Patlayan sinek arkadaşı#Patlama 60 hasar verir"},
	{"273", "Bob's Brain", "Throwable bomb familiar#The explosion deals 60 Damage"},
	{"274", "Best Bud", "When getting hit, gain one midrange orbital#Orbital deals 75 damage per second"},
	{"275", "Lil Brimstone", "Shoots a brimstone laser#Shot deals 31.5 damage per second"},
	{"276", "Isaac's Heart", "Gain an invulnerable body#!!! When the heart familiar gets hit you take damage"},
	{"277", "Lil Haunt", "Hayalet arkadaşı#Saniyede 4 hasar verir"},
	{"278", "Dark Bum", "!!! Converts:#1,5 Red hearts into 1 soul heart or a spider"},
	{"279", "Big Fan", "Büyük şişko martha yörüngeci#Saniyede 30 hasar verir"},
	{"280", "Sissy Longlegs", "Randomly spawns blue spiders when in a hostile room"},
	{"281", "Punching Bag", "Yanıltıcı arkadaş#Düşmanlar artık onu hedefler"},
	{"282", "How to Jump", "Zıplamanı sağlar"},
	{"283", "D100", "Reroll all pickups, pedestals and all your held passive items"},
	{"284", "D4", "Eldeki bütün pasif itemlerini değiştirir"},
	{"285", "D10", "Reroll all enemies in the room"},
	{"286", "Blank Card", "Eldeki kartının efektini kopyalar"},
	{"287", "Book of Secrets", "Reveals parts of the map"},
	{"288", "Box of Spiders", "Spawn 1-4 blue spiders"},
	{"289", "Red Candle", "Throw red fire#The flame persists until it delt damage 5 times"},
	{"290", "The Jar", "Sonra kullanmak üzere 4 kırmızı kalbe kadar içinde saklar"},
	{"291", "Flush!", "!!! Insta kills Poop enemies & bosses!#Turns enemies into poop"},
	{"292", "Satanic Bible", "+1 Black heart"},
	{"293", "Head of Krampus", "4 yönde birden brimstone lazeri atar"},
	{"294", "Butter Bean", "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger \"Wait What?\" when swapping it with a different active item and picking it up again"},
	{"295", "Magic Fingers", "Damages the whole room with 2x the player damage#Price: 1 coin"},
	{"296", "Converter", "!!! Convert:#2 Soul/Black hearts into 1 red heart"},
	{"297", "Pandora's Box", "!!! SINGLE USE !#!!! Drops things based on floor its activated on:#B1: 2 Soul Hearts#B2: 2 keys and bombs#C1: 1 Boss item#C2: B1+C1#D1: 4 Soul hearts#D2: 20 Coins#W1: 2 Boss items#W2: Bible#Sheol: 1 Devil item + Black heart#Cat: 1 Angel item + Soul heart#Chest: 1 Coin"},
	{"298", "Unicorn Stump", "6 Saniye boyunca dokunulmazlık ve +0.28 hız"},
	{"299", "Taurus", "Düşman olan odalarda hızlan!#Yeterince hızlı iken dokunulmazlık#↓ -0.3 Hız eksilir"},
	{"300", "Aries", "↑ +0.25 Speed up#Touching enemies hurts them"},
	{"301", "Cancer", "+3 Soul hearts#Halves taken damage in room when you already got hit"},
	{"302", "Leo", "Destroy rocks when walking over them"},
	{"303", "Virgo", "Chance to get invincibility when hit#Converts negative pills into positive ones"},
	{"304", "Libra", "+6 Coins / Keys / Bombs#Balances your stats!#!!! Every stats up afterwards will affect other stats too"},
	{"305", "Scorpio", "Poison tears"},
	{"306", "Sagittarius", "↑ +0.2 Hız#Delici gözyaşları"},
	{"307", "Capricorn", "↑ +1 Health / Key / Bomb / Coin#↑ +0.5 Damage up#↑ +0.1 Speed up#↑ +1.5 Range up#Tears up"},
	{"308", "Aquarius", "Leave trail of creep#Creep deals 6 damage per second"},
	{"309", "Pisces", "↑ Gözyaşı artar#İttiren gözyaşları"},
	{"310", "Eve's Mascara", "↑ +100% Hasar#↓ Gözyaşı azalır#↓ -0.5 Gözyaşı hızı azalır"},
	{"311", "Judas' Shadow", "Öldüğünde, Kara Judas olarak geri dön#↑ (Hasar x 2)"},
	{"312", "Maggy's Bow", "↑ +1 HP#Tüm kırmızı kalpler artık değerinin iki katı iyileştirir"},
	{"313", "Holy Mantle", "Her odada ilk alınan hasarı görmezden gelir"},
	{"314", "Thunder Thighs", "↑ +1 Health up#↓ -0.4 Speed down#Destroy rocks when walking over them"},
	{"315", "Strange Attractor", "Magnetic tears#Affects enemies, pickups and trinkets"},
	{"316", "Cursed Eye", "Şarj edilen göz yaşı dalgası#Şarj ederken hasar alınırsa, rastgele bir odaya ışınlar"},
	{"317", "Mysterious Liquid", "Gözyaşları sıvı bırakır#Sıvı saniyede 30 hasar verir"},
	{"318", "Gemini", "Yakın dövüş arkadaşı#Saniyede 6 dokunma hasarı verir"},
	{"319", "Cain's Other Eye", "Odada gezer#Isaace doğru ateş eder#Verdiği hasar senin hasarına eşit olur"},
	{"320", "???'s Only Friend", "Controllable Fly#Deals 5 contact damage per second"},
	{"321", "Samson's Chains", "Draggable ball that can destroy rocks#Deals 10.7 contact damage per second"},
	{"322", "Mongo Baby", "Copies the effect of one of your familiars#Deals double its damage"},
	{"323", "Isaac's Tears", "Shoot 8 tears in all directions when used#Charges when shooting"},
	{"324", "Undefined", "Teleports you to:#{{SecretRoom}}{{SuperSecretRoom}}Secret-, Error- or {{TreasureRoom}}Item-rooms"},
	{"325", "Scissors", "Kafanı kes#Kafa sabit bir arkadaşa dönüşür#Vücudunu ayrı kontrol et"},
	{"326", "Breath of Life", "Hold down space till chargebar is empty for invincibility#!!! Don't hold it for too long!"},
	{"327", "The Polaroid", "Yarım kırmızı kalp veya daha altında hasar aldığında dokunulmazlık"},
	{"328", "The Negative", "Damages all enemies in the room when getting hit and at half a red heart or none"},
	{"329", "The Ludovico Technique", "Kontrol edilebilen gözyaşı"},
	{"330", "Soy Milk", "↑ Very high Tears up: (delay /4) - 2#↓ -80% Damage down"},
	{"331", "Godhead", "Homing tears#↑ +0.5 Damage up#↑ +1.2 Range up#↓ -0.3 Tears down#↓ -30% Shot Speed down#↑ +0.8 Tear Height#Tears gain a damaging aura"},
	{"332", "Lazarus' Rags", "Öldüğünde Lazarus (Risen) olarak geri dön"},
	{"333", "The Mind", "Tüm haritayı açar"},
	{"334", "The Body", "↑ +3 HP"},
	{"335", "The Soul", "+2 Ruh Kalbi#Düşmanları ve gözyaşlarını uzaklaştıran bir aura verir"},
	{"336", "Dead Onion", "Piercing + spectral tears#↑ +0.25 Range up#↓ -0.4 Shot Speed down#↑ +50% Tear size"},
	{"337", "Broken Watch", "Her 4 odada bir hızlanır veya yavaşlar"},
	{"338", "The Boomerang", "Atılabilir bumerang#Düşmanları afallatır ve hasarının 2 katını verir#İtemleri alabilir"},
	{"339", "Safety Pin", "↑ +5.25 Range up#↑ +0.16 Shot Speed up#+1 Black Heart#↑ +0.5 Tear Height"},
	{"340", "Caffeine Pill", "↑ +0.3 Hız#↑ Boy küçülür#Alındığında rastgele hap verir"},
	{"341", "Torn Photo", "↑ +0.7 Gözyaşı#↑ +0.16 Gözyaşı hızı"},
	{"342", "Blue Cap", "↑ +1 Health up#↑ +0.7 Tears up#↓ -16% Shot Speed down"},
	{"343", "Latch Key", "↑ +1 Şans#+1 Ruh Kalbi#2 Anahtar çıkartır"},
	{"344", "Match Book", "+1 Black Heart#Spawns 2-3 Bomb pickups"},
	{"345", "Synthoil", "↑ +1.0 Damage up#↑ +5.25 Range up#↑ +0.5 Tear Height"},
	{"346", "A Snack", "↑ +1 Health up"},
	{"347", "Diplopia", "!!! TEK KULLANIM !#Yerdeki itemleri, harcanılabilirleri çiftler"},
	{"348", "Placebo", "Elindeki hapın efektini kopyalar"},
	{"349", "Wooden Nickel", "50% şans ile rastgele altın çıkartır"},
	{"350", "Toxic Shock", "At the start of every room every enemy gets a poison effect"},
	{"351", "Mega Bean", "Odadaki tüm düşmanları dondur#5 Hasar verir ve yakın düşmanları zehirler#Odada dıken dalgaları gönderir#!!! Gizli odaları açmak için kullanılabilir"},
	{"352", "Glass Cannon", "↓ Reduces your health to half a heart#Fires one large piercing spectral tear ((DMG+1) X 10)"},
	{"353", "Bomber Boy", "+5 bomba#Bombalar artık artı şeklinde patlar"},
	{"354", "Crack Jacks", "↑ +1 HP#Yere rastgele bir trinket çıkartır"},
	{"355", "Mom's Pearls", "↑ +1.25 Range up#↑ +1 Luck up#↑ +0.5 Tear Height"},
	{"356", "Car Battery", "Aktif item kullanıldığında iki kere aktive olmasını sağlar"},
	{"357", "Box of Friends", "Oda boyunca arkadaşlarını iki katına çıkartır"},
	{"358", "The Wiz", "Çapraz olarak aynı anda 2 gözyaşı atar, R U A WIZARD hapına benzer şekilde#Hayalet gözyaşları"},
	{"359", "8 Inch Nails", "↑ +1.5 Hasar#Arttırılmış ittirme"},
	{"360", "Incubus", "Shoots the same tears as Isaac in terms of damage, stats and effects"},
	{"361", "Fate's Reward", "Gözyaşlarının kopyası şeklinde ateş eder"},
	{"362", "Lil Chest", "Bir kaç odada bir rastgele pickup çıkartır"},
	{"363", "Sworn Protector", "Yörüngeç arkadaş#Saniyede 105 dokunma hasarı verir#Ateşleri bloklar ver kendine çeker#Bir odada 10 gözyaşı bloklamak ebedi kalp düşürür"},
	{"364", "Friend Zone", "Yörüngeç arkadaş#Saniyede 45 dokunma hasarı verir"},
	{"365", "Lost Fly", "Duvarların ve engellerin etrafında hareket eder#Saniyede 105 dokunma hasarı verir"},
	{"366", "Scatter Bombs", "+5 bombs#Causes your bombs to explode into 2-4 tiny bombs"},
	{"367", "Sticky Bombs", "+5 bomba#Düşman bomba tarafından öldürüldüğünde mavi örümcekler çıkartır#Bombaların düşmana yapışmasını sağlar"},
	{"368", "Epiphora", "Tek bir yönde ateş etmek atış sıklığını 200%e kadar arttırır"},
	{"369", "Continuum", "↑ +2.25 Range up#↑ +1.5 Tear Height#Tears travel through walls and appear out of the opposite wall"},
	{"370", "Mr. Dolly", "↑ +0.7 Tears up#↑ +5.25 Range up#↑ +0.5 Tear Height#Spawns 3 random hearts when picked up"},
	{"371", "Curse of the Tower", "Her hasar aldığında 6 troll bombası düşürür#Bomba itemleri ile sinerji olur"},
	{"372", "Charged Baby", "Random chance to drop a battery or freeze all enemies in the room#Chance to add one charge to your spacebar item"},
	{"373", "Dead Eye", "Düşmana vuran her gözyaşı için ↑ +12.5% hasar (max. +100%)"},
	{"374", "Holy Light", "Random chance to fire a Holy tear, which will spawn a beam of light on hit#The beam deals 4x your damage"},
	{"375", "Host Hat", "20% chance to block tears#Get immune to explosions/Stomps from Mom's and Satan's foot"},
	{"376", "Restock", "Spawns 3 random Pickups#Shops instantly restock their items when you buy them"},
	{"377", "Bursting Sack", "Örümcek düşmanlar artık hedef alıp dokunma hasarı vermezler"},
	{"378", "No. 2", "3 saniye boyunca ateş etmek göt bombası bırakır"},
	{"379", "Pupula Duplex", "Gözyaşları çok büyür#Hayalet gözyaşları"},
	{"380", "Pay To Play", "+5 altın#Odalar artık anahtar değil altın ile açılır"},
	{"381", "Eden's Blessing", "↑ +0.7 Gözyaşı#Sonraki oyununun başında sana rastgele bir item verir"},
	{"382", "Friendly Ball", "Can be thrown at enemies to capture them#Next usage will re-spawn the same enemy as a friendly companion"},
	{"383", "Tear Detonator", "Ekranda bulunan tüm gözyaşlarını patlatır, her birinin 6ya ayrılıp çember şeklinde dağılmasını sağlar"},
	{"384", "Lil Gurdy", "Will launch and slide around the room#Deals 90 contact damage per second"},
	{"385", "Bumbo", "Yakındaki altınları toplar#Her 6 altında seviye atlar, sadece 4. seviye 12 sürer#Level 2: Rastgele pickup bırakır#Level 3: Seninle aynı yönde gözyaşı atar#Level 4: Ateş etmez fakat düşmanları kovalar. Rastgele bomba bırakır#Level 4 Sonrası: altın toplayup rastgele pickup dülşürmeye devam eder"},
	{"386", "D12", "Herhangi bir objeyi farklı tipte bir objeye dönüştürür (örn. bok, testi, TNT, kırmızı bok, taş vs.)"},
	{"387", "Censer", "İçindeki düşmanları ve ateşleri yavaşlatan kocaman bir aura verir"},
	{"388", "Key Bum", "Anahtar toplar, karşılığında rastgele kasalar verir"},
	{"389", "Rune Bag", "Drops a random rune every 5-6 rooms"},
	{"390", "Seraphim", "Sacred Heart gözyaşları atar#Atış başına 10 hasar verir"},
	{"391", "Betrayal", "Hasar alındığında, odadaki her düşmanı aşık eder"},
	{"392", "Zodiac", "Her katta rastgele bir burç itemı efekti verir"},
	{"393", "Serpent's Kiss", "Random chance to shoot poison tears#Poison enemies on contact#Enemies that were poisoned have a chance to drop a black heart on death"},
	{"394", "Marked", "Fire tears automatically directed at a red target on the ground which is controlled by the player#↑ +0.7 Tears up#↑ +3.15 Range up#↑ +0.3 Tear Height"},
	{"395", "Tech X", "Gain the ability to charge and fire a laser ring that travels across the room"},
	{"396", "Ventricle Razor", "Aralarında ışınlanmak için 2 portal yaratılabilir#Portallar farklı odalara yerleştirilebilir"},
	{"397", "Tractor Beam", "Isaac's tears now travel directly forwards following a beam of light, but will also move sideways based on your player movement#↑ +0.5 Tears up#↑ +5.25 Range up#↑ +0.16 Shot Speed up#↑ +0.5 Tear Height"},
	{"398", "God's Flesh", "Gözyaşları düşmanları küçültebilir#Küçülen düşmanlar üzerine yürünerek ezilip öldürülebilir"},
	{"399", "Maw Of The Void", "↑ +1.0 Damage up#After firing tears for 3 seconds, a red cross appears on Isaac's head. Upon releasing the fire button, creates a black brimstone ring#Enemies killed with the black ring have a chance to drop Black hearts"},
	{"400", "Spear Of Destiny", "Önüne bir mızrak koyar#Hasarının 2 katını verir#Temas halinde düşmanları korkutma şansı"},
	{"401", "Explosivo", "Chance to fire sticky bomb tears"},
	{"402", "Chaos", "İtemler artık rastgele havuzdan çekilir#Rastgele 1-6 pickup çıkartır"},
	{"403", "Spider Mod", "Gözyaşı hasarını ve düşmanların canlarını görmeni sağlar#Temas halinde rastgele bir durum efekti uygular#Rastgele pil düşürür"},
	{"404", "Farting Baby", "Blocks projectiles#If hit, it will fart, which will charms, poison or knockback enemies"},
	{"405", "GB Bug", "Bounces around the room#Deals 120 damage per second and applies a random status effect"},
	{"406", "D8", "Özelliklerini değiştirir#Sadece hasar, gözyaşı, menzil ve hızı etkiler"},
	{"407", "Purity", "↑ Boost one of your stats depending on the color of the aura around you#When you take damage, you will get a new aura#{{ColorRed}}Red{{CR}} = +4.0 Damage#{{ColorBlue}}Blue{{CR}} = -4 Tear Delay#{{ColorYellow}}Yellow{{CR}} = +0.5 Speed up#{{ColorOrange}}Orange{{CR}} = +7.5 Range up, +1 Tear height"},
	{"408", "Athame", "When you take damage, a black brimstone ring will appear around Isaac#Enemies killed with it have a chance to drop a black heart"},
	{"409", "Empty Vessel", "+2 Siyah kalp#Isaac kırmızı kalbe sahip değil ise, uçuş kazanır ve kalkan çıkarma şansı kazanır"},
	{"410", "Evil Eye", "Ekran boyunca Isaac ile aynı yönde ateş eden bir göz çıkarma şansı"},
	{"411", "Lusty Blood", "↑ Odada öldürülen her düşman için +0.5 Hasar#Maksimum 10 düşmandan sonra +5 Hasar"},
	{"412", "Cambion Conception", "15 Defa Hasar aldıktan sonra, kalıcı şeytan arkadaşı kazanır#4 arkadaşa kadar mümkündür"},
	{"413", "Immaculate Conception", "15 kalp aldıktan sonra, kalıcı melek arkadaşı kazanır#5 arkadaşa kadar mümkündür"},
	{"414", "More Options", "Hazine odalarında artık 2 item çıkar#Sadece birini seçebilirsin"},
	{"415", "Crown Of Light", "+2 Ruh Kalbi#↑ Yarım/Boş kırmızı kalp konteynırı yoksa Hasar X 2#Odada hasar alınırsa o oda için deaktive olur"},
	{"416", "Deep Pockets", "Allows you to carry two cards/pills/runes"},
	{"417", "Succubus", "Bounces around the room with a damaging aura, dealing 129% of your damage every second#↑ +50% damage while standing in the aura,"},
	{"418", "Fruit Cake", "Her atılan gözyaşı farklı bir efekte sahip olur"},
	{"419", "Teleport 2.0", "Henüz girilmemiş bir odaya ışınlar#Hiyerarşi: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> Error-Odası"},
	{"420", "Black Powder", "Yürürken çember çizmek yerde pentagram sembolü çıkartır, tik başına 10 hasar verir"},
	{"421", "Kidney Bean", "Applies charm effect to any enemies in close range and deals 5 damage to them"},
	{"422", "Glowing Hour Glass", "Zamanı geri alıp bir önceki odaya ışınlar, o andaki haline geri dönersin"},
	{"423", "Circle of Protection", "Etrafında büyük bir hale olur, dokunduğunda senin hasarın kadar hasar verir#Düşman ateşlerini geri yollama şansı"},
	{"424", "Sack Head", "Pickuplar 33% şans ile keseyle değiştirilir#Kese çıkartır"},
	{"425", "Night Light", "Önüne düşmanları ve ateşlerini yavaşlatan bir ışık konisi çıkartır"},
	{"426", "Obsessed Fan", "Follows your exact movement on a 3 second delay#Deals 30 contact damage per second"},
	{"427", "Mine Crafter", "İttirilebilen TNT varili çıkartır#TNT odada iken tekrar kullanıldığında uzaktan detone eder"},
	{"428", "PJs", "+4 Ruh Kalbi#Kırmızı kalplerini fuller"},
	{"429", "Head of the Keeper", "Düşmanlar vurulduğunda 5% şans ile altın düşürür"},
	{"430", "Papa Fly", "Follows your movement pattern on a 1 second delay#Fires tears at nearby enemies that deal damage equal to your damage"},
	{"431", "Multidimensional Baby", "Follows your movement pattern on a 2 second delay#Tears that pass through it will split up and gain a speed boost"},
	{"432", "Glitter Bombs", "+5 bomba#Bombalar patladığında rastgele pickup düşürme şansına sahip olur"},
	{"433", "My Shadow", "Hasar aldığında, tüm düşmanlara korku efekti uygulayıp siyah charger çıkartır#The charger saniyede 5 hasar verir"},
	{"434", "Jar of Flies", "Her öldürdüğün düşmanda kavanoza mavi sinek eklenir#20 sineğe kadar#İtemi kullanmak tüm sinekleri salar"},
	{"435", "Lil Loki", "Artı şeklinde 4 gözyaşı atar#Atış başına 3.5 hasar verir"},
	{"436", "Milk!", "Hasar alındığında, oda boyunca gözyaşın artar"},
	{"437", "D7", "Respawn all enemies of the room#Allows you to farm room clear rewards#!!! If used in a greed fight, it can reroll the room into a Shop"},
	{"438", "Binky", "+1 Ruh Kalbi#↑ +0.7 Gözyaşı#↑ Isaacı çok küçük yapar, daha zor vurulur"},
	{"439", "Mom's Box", "Rastgele bir trinket düşürür#↑ Elde iken +1 Şans#Elde iken, trinketlerin efektlerini iki katına çıkartır"},
	{"440", "Kidney Stone", "Randomly while firing you will stop firing and release a burst of tears and a kidney stone#↓ -0.2 Speed down#↓ -17 Range down#↑ +2.0 Tear height"},
	{"441", "Mega Blast", "15 Saniye boyunca dev bir Mega Satan lazeri atar#Lazer oda ve katlar arasında devam eder"},
	{"442", "Dark Princes Crown", "!!! While at 1 full red heart:#↑ +1.5 Range up#↑ +0.75 Tears up#↑ +0.2 Shot Speed up#(Doesnt work with characters without red HP)"},
	{"443", "Apple!", "Rastgele 400% hasar veren jilet gözyaşları atar#↑ +0.3 Gözyaşı"},
	{"444", "Lead Pencil", "Every 15 tears fired, you fire a cluster of tears#Each tear in the cluster deals double damage"},
	{"445", "Dog Tooth", "↑ +0.3 Hasar#↑ +0.1 Hız#Gizli odaya bitişik bir odaya girdiğinde kurt ulumaya başlar#Sürünme alanı olan bir odaya girğinde köpek havlama sesi duyulur"},
	{"446", "Dead Tooth", "Ateş ederken, İçindeki düşmanları zehirleyen yeşil bir auraya sahip olursun#Zehir seninle aynı hasarı verir"},
	{"447", "Linger Bean", "Durmadan ateş ederken, her 7.5 saniyede bok bulutu çıkartır#Bulut saniyede 5 defa 3.5 hasar verir#Bulut 15 saniye sürer#Ateş ederek oynatılabilir"},
	{"448", "Shard of Glass", "Hasar alırken, ↑ +5 Menzil ve kan sıvısı bırakma veya kırmızı kalp çıkarma şansı"},
	{"449", "Metal Plate", "+1 Ruh Kalbi#Düşman gözyaşları 25% şans ile afallatan gözyaşı olarak geri gönderilir"},
	{"450", "Eye of Greed", "Her 20 gözyaşında bir, düşmanları altına çeviren para gözyaşı atar#Bu 1 altına mal olur#Vurulan düşmanlar altın düşürür"},
	{"451", "Tarot Cloth", "Drops a random card or rune on pickup#Doubles the effect of any card used"},
	{"452", "Varicose Veins", "Hasar alındığında, etrafında halka olarak 10 gözyaşı at#Gözyaşları hasarının 125%ini verir"},
	{"453", "Compound Fracture", "Bone tears#Tears shatter into 1-3 smaller bone shards upon hitting anything#↑ +1.5 Range up#↑ +1.0 Tear height"},
	{"454", "Polydactyly", "İki kart, rune veya hap taşıyabilirsin#Alındığında rastgele kart, rune veya hap düşürür"},
	{"455", "Dad's Lost Coin", "↑ +1.5 Range up#Spawns a lucky penny"},
	{"456", "Moldy Bread", "↑ +1 Health up"},
	{"457", "Cone Head", "+1 Ruh Kalbi#20% şans ile hasarı görmezden gelir"},
	{"458", "Belly Button", "Yere rastgele bir trinket çıkartır#1 ekstra trinket slotu verir"},
	{"459", "Sinus Infection", "Yapışan zehir gözyaşları#Tik başına senin hasarın kadar hasar verir#Düşman ölene kadar yapışık kalır"},
	{"460", "Glaucoma", "Afallatan gözyaşı atma şansı"},
	{"461", "Parasitoid", "Yumurta kesesi atma şansı#Vurduğunda yavaşlatan sıvı çıkartır#Vurduğunda mavi örümcek ya da sinek çıkartır"},
	{"462", "Eye of Belial", "↑ +1.5 Menzil#↑ +1.0 Gözyaşı yüksekliği#Delici gözyaşları verir#İlk düşman vurulduktan sonra, gözyaşı iki katı hasar verir ve takip eden efekt kazanır"},
	{"463", "Sulfuric Acid", "↑ +0.3 Hasar#Gözyaşları ile taşları yok edip kapıları açma şansı"},
	{"464", "Glyph of Balance", "+2 Soul Hearts#Champion enemies drop pickups more frequently"},
	{"465", "Analog Stick", "↑ +0.3 Gözyaşı#İki yönde ateş ederek çapraz ateş etmeyi sağlar"},
	{"466", "Contagion", "Odada öldürülen ilk düşman patlar ve yakındaki düşmanları zehirler"},
	{"467", "Finger!", "Parmağın baktığı yöndeki düşmanlara sürekli hasarının 10%unu uygular"},
	{"468", "Shade", "1 saniye gecikme ile hareketlerini takip eder#Saniyede 30 dokunma hasarı verir"},
	{"469", "Depression", "Sıvı bırakır#Sıvı saniyede 6 hasar verir#Buluta dokunan düşmanların kutsal ışık süzmesi yaratma şansı olur"},
	{"470", "Hushy", "Oda etrafında gezer#Dokunma hasarı verir#Sen ateş ederken durur#Durduğunda ateşleri bloklayabilir"},
	{"471", "Lil Monstro", "Şarj edilebilir pompalı atağı#(monstros lung benzeri)#Her gözyaşı 3.5 hasar verir"},
	{"472", "King Baby", "Other familiars follow it#Stops moving when you are shooting#Will teleport back to you when you stop shooting"},
	{"473", "Big Chubby", "Çok yavaşça ileri hareket eder#Saniyede 40.5 dokunma hasarı verir"},
	{"474", "Tonsil", "Blocks enemy projectiles"},
	{"475", "Plan C", "!!! TEK KULLANIM ! #Tüm düşmanlara 9,999,999 hasar verir ve 3 saniye sonra seni öldürür"},
	{"476", "D1", "Odadaki rastgele 1 pickupı çift yapar"},
	{"477", "Void", "!!! Kullanıldığında, odadaki itemleri yutar#Aktif item: Efekti Void'in efektine eklenir (üstüne biner)#↑ Pasif item: Rastgele bir özellik arttırır"},
	{"478", "Pause", "Tekrar ateş edene kadar odadaki tüm düşmanları dondurur#Donmuş bir düşmana dokunmak sana hasar verir#Düşmanların 30 saniye sonra donması biter"},
	{"479", "Smelter", "Trinketini yutar ve kalıcı olarak sana efektini verir#Daha çok trinket düşmesini sağlar"},
	{"480", "Compost", "Pickupları mavi sineğe veya örümceğe çevirir#O andaki sinek/örümcek sayını ikiye katlar#Hiç yoksa 1 mavi sinek veya örümcek çıkartır"},
	{"481", "Dataminer", "Kullanıldığında, ↑/↓ rastele miktarda özellik değişimi#Oda boyunca rastgele gözyaşı efektı#Görüntünün içine eder"},
	{"482", "Clicker", "Seni başka bir karaktere çevirir#Son aldığın itemi siler"},
	{"483", "Mama Mega!", "!!! TEK KULLANIM ! #Bütün katı etkiler#Bütün objeleri patlatır#Her düşmana 200 hasar verir#Boss rush / hush kapılarını ve gizli odaları açar"},
	{"484", "Wait What?", "Kullanışdığında, düşmanları uzağa ittirir ve taş dalgası çıkartır#Odaları açıp taşları kırabilir"},
	{"485", "Crooked Penny", "50% şansla odadaki tüm itemleri, harcanabilirleri ve kasaları değiştirir#50% şans ile siler ve 1 altın verir"},
	{"486", "Dull Razor", "Canını azaltmadan sana hasar verir#İtem efektleri için"},
	{"487", "Potato Peeler", "Bir kırmızı kalp konteynırını alır ve ↑ +0.2 Hasar ve  \"Cube of Meat\" verir"},
	{"488", "Metronome", "Her odada rastgele item efekti verir"},
	{"489", "D infinity", "Random Dice-effect each usage"},
	{"490", "Eden's Soul", "!!! TEK KULLANIM !#Bulunan odanın havuzundan 2 rastgele item çıkartır"},
	{"491", "Acid Baby", "Drops a random pill every 3 rooms#Using a pill poisons all enemies in the room"},
	{"492", "YO LISTEN!", "↑ +1 Şans#Gizli odaların, işaretli taşların ve tuzak kapılarının yerini gösterir"},
	{"493", "Adrenaline", "For every empty heart container:#↑ +0.2 Damage up"},
	{"494", "Jacob's Ladder", "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half your damage"},
	{"495", "Ghost Pepper", "Gözyaşı yerine ateş atma şansı#Ateş 5 defa hasar verene kadar kalır"},
	{"496", "Euthanasia", "İğne atma şansı#İğneler normal düşmanları anında öldürür#Aksi taktirde hasarının 3 katını verir"},
	{"497", "Camo Undies", "Odaya girdiğinde ateş etmeye başlayana kadar kendini kamuflaj yapar ve düşmanların kafasını karıştırır"},
	{"498", "Duality", "Şeytan-{{DevilRoom}} VE Melek{{AngelRoom}}-Odaso kapıları çıkartır#Birine girince, diğeri kaybolur"},
	{"499", "Eucharist", "100% Melek{{AngelRoom}} Odası bulma şansı"},
	{"500", "Sack of Sacks", "Her 5-6 odada kese çıkartır"},
	{"501", "Greed's Gullet", "Her 25 altın için 1 kalp konteynırı verir#Keeper daha fazla altın kalbine sahip olur"},
	{"502", "Large Zit", "İki katı hasar veren sıvı bırakan gözyaşı atma şansı"},
	{"503", "Little Horn", "Chance to fire tears that instantly kill enemies#Running into enemies will deal 3.5 damage to them"},
	{"504", "Brown Nugget", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
	{"505", "Poke Go", "Düşmanlı odaya girildiğinde aşık bir düşman çıkarma şansı"},
	{"506", "BackStabber", "Gözyaşları kanamaya sebep olabilir, düşmanın canının 10% hasarını her 5 saniye verir"},
	{"507", "Sharp Straw", "Senin hasarın + düşmanın maks canının 10%u hasar verir#Odadaki her düşmanı etkiler#Hasar verdiğinde yarım kalp düşürme şansı"},
	{"508", "Mom's Razor", "Kanamaya sebep olan arkadaş, düşmanın canının 10% hasarını her 5 saniye verir.#Hasarının 300%ünü temas halinde verir"},
	{"509", "Bloodshot Eye", "Orbital that shoots a tear every 2 seconds in a random direction#Deals 3.5 damage per tear#Deals 30 contact damage per second"},
	{"510", "Delirious", "Oda için bossun küçük delirium versiyonunu arkadaş olarak çıkartır"},
	{"511", "Angry Fly", "Öldürene kadar rastgele bir düşmanın etrafında yörünge çizer#Diğer düşmanlara saniyede 30 dokunma hasarı verir"},
	{"512", "Black Hole", "Atılabilir jara delik, her şeyi içine çeker#Her tikte 0.4 hasar verir#Yakındaki taşları yok eder#6 Saniye sürer"},
	{"513", "Bozo", "↑ +0.1 Hasar#+1 Ruh kalbi#Düşmanı aşık etme veya korkutma şansı#Hasar aldığında gökkuşağı boku çıkarma şansı"},
	{"514", "Broken Modem", "Rastgele zamanlarda düşmanlarda 'lag' olmasını sağlar, donarlar#25% şans ile oda ödüllerini iki katına çıkartır"},
	{"515", "Mystery Gift", "!!! TEK KULLANIM !#Bulunduğu odanın havuzundan rastgele bir item çıkartır#Bunun yerine Lump of Coal veya The Poop itemlerini çıkarabilir"},
	{"516", "Sprinkler", "Döçnen bir sulama aleti çıkartır, gözyaşlarını sprey olarak atar"},
	{"517", "Fast Bombs", "+7 Bomba#Sürekli bomba bırakabilmeni sağlar"},
	{"518", "Buddy in a Box", "Rastgele bir coop bebeği gibi gözüken arkadaş#Rastgele bir gözyaşı efektine sahip olur#Her kat değişir"},
	{"519", "Lil Delirium", "10 Saniyede bir başka arkadaşlara dönüşen arkadaş"},
	{"520", "Jumper Cables", "Öldürülen her 15 düşman için aktif itemini +1 şarj doldurur"},
	{"521", "Coupon", "Kullanıldığında,Dükkan{{Shop}}- veya Şeytan{{DevilRoom}}- odası itemini bedava yapar"},
	{"522", "Telekinesis", "Sana yakın olan düşman ateşleri 3 saniye yerınde durur#Sonrasında diper yöne atılır#3 saniye sonra dolar"},
	{"523", "Moving Box", "When used, stores all Pick-Ups from the current room#Using it again will put them back on the floor again#This allows you to move things between rooms"},
	{"524", "Technology Zero", "Tears will be connected with beams of electricity#Electricity damage equals your damage"},
	{"525", "Leprosy", "Hasar almak ateş bloklayan bir arkadaş çıkmasına sebep olur#Aynı anda maks. 3 Arkadaş#Çok hasar aldıklarında yok olurlar"},
	{"526", "7 Seals", "Küçük atlı arkadaşları#10 Saniyede bir değişir"},
	{"527", "Mr. ME!", "!!! Senin için bir şeyler yapabilecek bir arkadaş:#Kapı & kasa aç, İtem getir, dükkandan,şeytandan item çal, düşman ile savaş, patla ve düğmelere bas"},
	{"528", "Angelic Prism", "Arkadaş piramidi#Piramide çarpan gözyaşları 4e katlanır"},
	{"529", "Pop!", "Gözyaşları bilardo topu gibi davranır"},
	{"530", "Death's List", "Düşmanlar işaretli sırada öldürülürlerse ödül verir"},
	{"531", "Haemolacria", "Tears fly in an arc#Tears burst into smaller tears on impact#↓ Tears down#↑ 31% Damage up"},
	{"532", "Lachryphagy", "Gözyaşları hareket ederken yavaşlar#Durduğunda, 8 parçaya ayrılıp patlarlar#Gözyaşları diğer gözyaşlarının içine atılıp daha büyük yapılabilir"},
	{"533", "Trisagion", "Beyaz işik patlamaları atar#(Kutsal Brimstone)"},
	{"534", "Schoolbag", "2 Aktif item tutulmasını sağlar#Drop tuşuna basarak itemler değiştirilebilir"},
	{"535", "Blanket", "+1 Ruh kalbi#1 Kırmızı kalp verir#Boss odasına girerken kalkan verir"},
	{"536", "Sacrificial Altar", "!!! TEK SEFERLİK !#1-2 Arkadaşını feda edip Şeytan{{DevilRoom}} odası itemi çıkartır#Mavi sinek ve örümceklerini altına çevirir"},
	{"537", "Lil Spewer", "Rastgele bir hap verir#Sıvı fırlatan arkadaş#Sıvı tipi oyuncu her hap kullandığında değişir"},
	{"538", "Marbles", "3 rastgele trinket çıkartır#HAsar almak trinketın efektini kalıcı olarak ekleyebilir"},
	{"539", "Mystery Egg", "Hasar aldığında aşık bir düşman çıkartır#Odalar hasar almadan temizlendikçe daha güçlü arkadaşlar çıkartır"},
	{"540", "Flat Stone", "Gözyaşları yerde zıplar#Gözyaşları her zıplamada hasar verir"},
	{"541", "Marrow", "+1 Bone Heart#Spawns 3 Red Hearts"},
	{"542", "Slipped Rib", "Yörüngeç#Düşman ateşlerini geri gönderir"},
	{"543", "Hallowed Ground", "Spawn white poop when you get hit#(White poop has a ↑ Tears up aura and can block damage)"},
	{"544", "Pointy Rib", "Önünde havada duran bir çivi#Saniyede 6 kere hasarına eşit hasar verir"},
	{"545", "Book of the Dead", "Odada öldürülen her düşman için kemik arkadaşı ya da aşık bony çıkartır"},
	{"546", "Dad's Ring", "Düşmanları olduğu yerde donduran bir aura verir"},
	{"547", "Divorce Papers", "+1 Kemik Kalbi#↑ +0.7 Gözyaşı#Mysterious Paper trinketini çıakrtır"},
	{"548", "Jaw Bone", "Bumeragn gibi arkadaş#7 Dokunma hasarı#Pickupları getirebilir"},
	{"549", "Brittle Bones", "Bütün kırmızı kalp konteynırlarını 6 Kemik kalp ile değiştirir#Kemik kalbi kaybetmek her yönde kemik gözyaşı atılmasına sebep olur ve kalıcı ↑ +0.5 gözyaşı ekler"},
	{"550", "Broken Shovel", "Annenin ayağı sürekli sana saldırır#Kullanmak oda için annenin ayağını durdurur#!!! (bununla Bossrush odasını bitirmeyi dene!)"},
	{"551", "Broken Shovel", "broken shovelın ikinci parçası#!!! Küreği \"Dark Room\"un toprak tepeciğinde kullan"},
	{"552", "Mom's Shovel", "Sonraki kata bir tuzak kapısı açar#!!! Küreği \"Dark Room\"un toprak tepeciğinde kullan!!! Havalı bir şey açar"},
}

---------- Trinkets ----------
EID.descriptions["tr_tr"].trinkets={
	{"1", "Swallowed Penny", "Drop 1 coin when you get hit"},
	{"2", "Petrified Poop", "Boklardan 50% fazla şey düşer"},
	{"3", "AAA Battery", "Aktif itemler için -1 şarj gerekir"},
	{"4", "Broken Remote", "İtem kullanırken seni rastgele ışınlar"},
	{"5", "Purple Heart", "Daha fazla şampiyon düşmanlar#boss challenge odaları şansını arttırır({{BossRushRoom}})"},
	{"6", "Broken Magnet", "Altın mıknatısı"},
	{"7", "Rosary Bead", "Melek{{AngelRoom}} odası şansı artar#Bible {{Collectible33}} bulma şansı artar"},
	{"8", "Cartridge", "Hasar aldığında Gamekid efekti şansı"},
	{"9", "Pulse Worm", "Boyu değişlen gözyaşları"},
	{"10", "Wiggle Worm", "Tears move in waves#↑ +0.3 Tears up"},
	{"11", "Ring Worm", "Tears move in spirals with high speed"},
	{"12", "Flat Worm", "50% daha geniş gözyaşları"},
	{"13", "Store Credit", "Bir dükkann itemi bedava"},
	{"14", "Callus", "Sıvıdan ve dikenden gelen hasarı engeller"},
	{"15", "Lucky Rock", "Destroying rocks spawns coins"},
	{"16", "Mom's Toenail", "Annenin ayağı düşmanları her 60 saniye ezer"},
	{"17", "Black Lipstick", "Daha fazla Siyah Kalp"},
	{"18", "Bible Tract", "Daha fazla Rbedi Kalp"},
	{"19", "Paper Clip", "Anahtar kullanmadan kasaları aç"},
	{"20", "Monkey Paw", "Yarım kalpteyken, Siyah Kalp verir#!!! 3 sefer kullanım"},
	{"21", "Mysterious Paper", "\"Polaroid\", \"The Negative\", \"Missing Page\" ve \"Missing Poster\"i taklit eder"},
	{"22", "Daemon's Tail", "Kalp çıkma oranı 20%ye düşer#Anahtar şansı artar#Kalp pickupları siyah kalbe dönüşür"},
	{"23", "Missing Poster", "Feda odasında {{SacrificeRoom}} öldüğünde \"The Lost\" olarak tekrar doğarsın #Eğer karakter açıksa, her odada bu geçerli"},
	{"24", "Butt Penny", "Fart when picking up coins#Farts knockback enemies"},
	{"25", "Mysterious Candy", "30 Saniyede bir osurur veya bok çıkartır"},
	{"26", "Hook Worm", "Tears move in angular patterns#↑ +10 Range"},
	{"27", "Whip Worm", "↑ +0.5 Gözyaşı hızı"},
	{"28", "Broken Ankh", "22% şans ile \"Blue Baby\" olarak tekrar doğarsın"},
	{"29", "Fish Head", "Hasar aldığında mavi sinek çıkartır"},
	{"30", "Pinky Eye", "10% şans ile zehir gözyaşı atar"},
	{"31", "Push Pin", "10% şans ile delici hayalet gözyaşı atar"},
	{"32", "Liberty Cap", "Random mushroom effect per room#Can reveal special rooms on the minimap"},
	{"33", "Umbilical Cord", "When down to half a heart, you get little Steven"},
	{"34", "Child's Heart", "Daha çok kırmızı kalp düşer"},
	{"35", "Curved Horn", "↑ +2 Hasar"},
	{"36", "Rusted Key", "Daha fazla anahtar"},
	{"37", "Goat Hoof", "↑ +0.15 Hız"},
	{"38", "Mom's Pearl", "Daha fazla Ruh Kalbi"},
	{"39", "Cancer", "↑ Gözyaşı artar"},
	{"40", "Red Patch", "↑ Hasar alınca +1.8 hasar şansı"},
	{"41", "Match Stick", "Daha çok bomba#!!! \"The Tick\"i kaldırır"},
	{"42", "Lucky Toe", "↑ +1 Şans#Daha çok pickup düşer"},
	{"43", "Cursed Skull", "Yarım kalp ve altına hasar alındığında, rastgele odaya ışınlar"},
	{"44", "Safety Cap", "Daha çok hap"},
	{"45", "Ace of Spades", "Daha çok kart"},
	{"46", "Isaac's Fork", "Oda temizlerklen yarım kalp iyileştirme şansı"},
	{"47", "", "<Item does not exist>"},
	{"48", "A Missing Page", "When getting hit, chance to damage all enemies in the room"},
	{"49", "Bloody Penny", "50% chance to drop half a heart when picking up coins"},
	{"50", "Burnt Penny", "50% chance to drop a bomb when picking up coins"},
	{"51", "Flat Penny", "50% chance to drop a key when picking up coins"},
	{"52", "Counterfeit Penny", "Altın alırken 50% şans ile +1 altın"},
	{"53", "Tick", "-15% Boss canı#Boss odasına ({{BossRoom}}) girerken 1 kırmızı kalp iyileştirir#!!! Alındığında bırakılamaz#Sadece {{Trinket41}}Match Stick veya yutarak ile çıkarılabilir"},
	{"54", "Isaac's Head", "Delici ateş atan arkadaş#3.5 Hasar"},
	{"55", "Maggy's Faith", "Kat başında 1 ebedi kalp"},
	{"56", "Judas' Tongue", "Şeytan anlaşmalarını 2 kalpten 1e indirir"},
	{"57", "???'s Soul", "Odada gezen arkadaş#Oyuncuyla aynı yöne ateş eder#3.5 Hasar"},
	{"58", "Samson's Lock", "↑ Düşman öldürürken 1/15 Şans ile +0.5 Hasar#Efekt oda için geçerli"},
	{"59", "Cain's Eye", "25% Şans ile kat başında map ikonlarını gösterir"},
	{"60", "Eve's Bird Foot", "Düşman öldürürken ölü kuş çıkarma şansı"},
	{"61", "The Left Hand", "Tüm kasaları kırmızı kasaya çevirir"},
	{"62", "Shiny Rock", "Sürünme alanı tasşkarı ve işaretli taşlar her 10 saniye yanıp söner"},
	{"63", "Safety Scissors", "Troll bombalarını bomba pickupına dönüştürür"},
	{"64", "Rainbow Worm", "Her 3 saniye rastgele solucan efekti"},
	{"65", "Tape Worm", "↑ Doubles your Range#-50% Tear height"},
	{"66", "Lazy Worm", "↓ -0.4 Shot Speed down#↑ +4 Range up"},
	{"67", "Cracked Dice", "Hasar alınca rastgele zar efekti verme şansı"},
	{"68", "Super Magnet", "pickup ve düşmanlar için mıknatıs"},
	{"69", "Faded Polaroid", "Camouflages the player randomly#Confuses enemies"},
	{"70", "Louse", "Düşman odasında örüğmcek çıkarma şansı"},
	{"71", "Bob's Bladder", "Bombalar sıvı bırakır"},
	{"72", "Watch Battery", "Daha fazla pil#Oda temizlendiğinde 5% şans ile tutulan aktif iteme +1 şarj ekler"},
	{"73", "Blasting Cap", "Patlayan bombalar bomba pickupı düşürür"},
	{"74", "Stud Finder", "Taşları kırınca daha fazla sürünme alanı şansı"},
	{"75", "Error", "Her odada farklı trinket efekti"},
	{"76", "Poker Chip", "Kasalar 50/50 şans ile daha fazla şey çıkartır YA DA düşman veya hiç bir şey çıkartmaz"},
	{"77", "Blister", "İttirmeyi arttırır"},
	{"78", "Second Hand", "Düşmanlarda durum efektleri daha fazla sürer"},
	{"79", "Endless Nameless", "25% şansla hap/kart kullanınca kopyasını düşürür"},
	{"80", "Black Feather", "↑ +0.2 Damage up for each evil item held"},
	{"81", "Blind Rage", "Hasar alınca verilen dokunulmazlık daha fazla sürer"},
	{"82", "Golden Horse Shoe", "+15% sonraki katta çift hazine odası"},
	{"83", "Store Key", "Dükkanları {{Shop}} ücretsiz aç"},
	{"84", "Rib of Greed", "Greed/Super Greed artık dükkanlarda çıkmaz#Daha fazla altın"},
	{"85", "Karma", "Bağış makinesi kullanmak seni iyileştirir veya dilenci çıkartır"},
	{"86", "Lil Larva", "Bok parçalamak mavi sinek çıkartır"},
	{"87", "Mom's Locket", "Anahtar kullanırken yarım kalp iyileştir#Yarım kalpleri tam kalp yapar"},
	{"88", "NO!", "Aktif itemlerin çıkma ihtimalini çok fazla düşürür"},
	{"89", "Child Leash", "Arkadaşlar sana daha yakın durur"},
	{"90", "Brown Cap", "Boklar parçalandığında patlar"},
	{"91", "Meconium", "Daha fazla siyah bok#Siyah bok parçalandığında siyah kalp düşürme ihtimali"},
	{"92", "Cracked Crown", "↑ Stat increases of your items are 33% more effective#↑ +0.2 Tears up#↑ -1 Tear Delay"},
	{"93", "Used Diaper", "Sinek düşmanlarının arkadaş olma ihtimali olur"},
	{"94", "Fish Tail", "Bütün çıkan mavi sinek/örümcekleri ikiye katla"},
	{"95", "Black Tooth", "Zehirli diş gözyaşı atma ihtimali"},
	{"96", "Ouroboros Worm", "Gözyaşları hızlıca spiral halinde ilerler#Hayalet gözyaşı#↑ +4 Menzil"},
	{"97", "Tonsil", "12-20 defa hasar alınca bloklayıcı arkadaş verir#2 arkadaşa kadar"},
	{"98", "Nose Goblin", "Yapışkan zehirli gözyaşı atma ihtimali"},
	{"99", "Super Ball", "Seken gözyaşı atma ihtimali"},
	{"100", "Vibrant Bulb", "!!! Şarjı full aktif item tutarken:#↑ +0.5 Hasar#↑ +0.25 Hız#↑ +0.75 Menzil#↑ +0.2 Gözyaşı#↑ +0.1 Atış hızı#↑ +1 Şans"},
	{"101", "Dim Bulb", "!!! While holding an uncharged active item:#↑ +1.5 Damage#↑ +0.5 Speed#↑ +1.5 Range#↑ +0.4 Tears#↑ +0.3 Shot Speed#↑ +2 Luck"},
	{"102", "Fragmented Card", "+1 ekstra gizli oda"},
	{"103", "Equality!", "!!! Altın, anahtar ve bomba sayısı eşit olduğunda:#Yarım pickupları tam yapar"},
	{"104", "Wish Bone", "Hasar alınca item düşürme ihtimali#Sonrasında yok olur"},
	{"105", "Bag Lunch", "Hasar alınca Lunch {{Collectible22}} verme ihtimali#Sonrasında yok olur"},
	{"106", "Lost Cork", "Ürettiğin sıvıların çağını arttırır"},
	{"107", "Crow Heart", "Alınan hasar Mavi/Siyah kalplerini görmezden gelir, önce kırmızıları alır"},
	{"108", "Walnut", "Patlamadan hasar alınca rastgele pickup/trinket düşürme ihtimali#Sonrasında yok olur"},
	{"109", "Duct Tape", ":Arkadaşlarının hareket etmesini bırakmasına sebep olur"},
	{"110", "Silver Dollar", "Shops {{Shop}} will now appear in the womb"},
	{"111", "Bloody Crown", "Item rooms {{TreasureRoom}} now appear in the womb"},
	{"112", "Pay To Win", "Stok kutuları her zaman item odasında({{TreasureRoom}}) bulunur"},
	{"113", "Locust of War", "Düşmanlı odaya girince patlayan atak sineği çıkartır#Sinek hasarının iki katı + patlama hasarı verir"},
	{"114", "Locust of Pestilence", "Düşmanlı odaya girince zehirli atak sineği çıkartır#:Sinek hasarının 2 katını verir"},
	{"115", "Locust of Famine", "Düşmanlı odaya girince yavaşlatan atak sineği çıkartır#:Sinek hasarının 2 katını verir"},
	{"116", "Locust of Death", "Düşmanlı odaya girince atak sineği çıkartırm#Sinek hasarının 4 katını verir"},
	{"117", "Locust of Conquest", "Düşmanlı odaya girince patlayan 1-4 atak sineği çıkartır#Her sinek hasarının 2 katını verir"},
	{"118", "Bat Wing", "Düşman öldürdükten sonra uçuş kazanma şansı#Oda boyunca"},
	{"119", "Stem Cell", "Heals half a heart upon traveling to the next floor"},
	{"120", "Hairpin", "Boss savaşı başlangıcında aktif itemini tamamen şarj eder"},
	{"121", "Wooden Cross", "Her katta aldığın ilk hasardan korur"},
	{"122", "Butter!", "İtemini kullanmak yere bırakmana sebep olur"},
	{"123", "Filigree Feather", "Melek bosslarının anahtar parçaları yerine melek itemleri vermesini sağlar"},
	{"124", "Door Stop", "Son kullandığın kapı açık kalır"},
	{"125", "Extension Cord", "Arkadaşlarını elektrik ile birbirine bağlar#Elektrik başına 6 hasar verir"},
	{"126", "Rotten Penny", "Altın alırken mavi sinek verir"},
	{"127", "Baby-Bender", "Arkadaşların takıp eden gözyaşına sahip olur"},
	{"128", "Finger Bone", "2% chance to gain a Bone Heart when taking damage"},
}

---------- Cards ----------
EID.descriptions["tr_tr"].cards={
	{"1", "0 - The Fool", "Katın başladığı odaya ışınlar"},
	{"2", "I - The Magician", "Oda için takip eden gözyaşları"},
	{"3", "II - The High Priestess", "Annenin ayağı düşmanın üstüne basar!"},
	{"4", "III - The Empress", "↑ Oda için +2.35 Hasar & +0.3 Hız"},
	{"5", "IV - The Emperor", "Boss odasına({{BossRoom}}) ışınlar"},
	{"6", "V - The Hierophant", "2 Mavi Kalp çıkartır"},
	{"7", "VI - The Lovers", "2 Kırmızı Kalp çıkartır"},
	{"8", "VII - The Chariot", "6 saniye boyunca dokunulmazlık + temas hasarı"},
	{"9", "VIII - Justice", "1 bomba, 1 anahtar, 1 altın, 1 kalp"},
	{"10", "IX - The Hermit", "Dükkana{{Shop}} ışınlar"},
	{"11", "X - Wheel of Fortune", "Slot veya fal makinası çıkartır"},
	{"12", "XI - Strength", "↑ +1 HP#↑ +0.3 Hasar#↑ +50% Hasar#↑ +5.25 Menzil#↑ +0.3 Hız#Oda için"},
	{"13", "XII - The Hanged Man", "Oda için uçuş verir"},
	{"14", "XIII - Death", "Tüm düşmanlara 40 hasar verir"},
	{"15", "XIV - Temperance", "Kan bağış makınası çıkartır"},
	{"16", "XV - The Devil", "↑ +2 Hasar oda için"},
	{"17", "XVI - The Tower", "6 troll bombası çıkartır"},
	{"18", "XVII - The Stars", "Hazine odasına({{TreasureRoom}}) ışınlar"},
	{"19", "XVIII - The Moon", "Gizli odaya({{SecretRoom}}) ışınlar"},
	{"20", "XIX - The Sun", "Tüm düşmanlara 100 hasar verir#Full can#Haritayı açar"},
	{"21", "XX - Judgement", "Dilenci çıkartır"},
	{"22", "XXI - The World", "Bütün haritayı açar"},
	{"23", "2 of Clubs", "Bombax2"},
	{"24", "2 of Diamonds", "Altınx2"},
	{"25", "2 of Spades", "Anahtarx2"},
	{"26", "2 of Hearts", "Kırmızı kalpx2#Sadece iyileştirir"},
	{"27", "Ace of Clubs", "Turns all pickups into bombs"},
	{"28", "Ace of Diamonds", "Turns all pickups into coins"},
	{"29", "Ace of Spades", "Turns all pickups into keys"},
	{"30", "Ace of Hearts", "Turns all pickups into hearts"},
	{"31", "Joker", "Şeytan{{DevilRoom}} veya Melek{{AngelRoom}} odasına ışınlar"},
	{"32", "Hagalaz", "Odadaki bütün taşları yok eder"},
	{"33", "Jera", "Odadaki tüm pickupları kopyalar"},
	{"34", "Ehwaz", "Tuzak kapısı çıkartır"},
	{"35", "Dagaz", "+1 Mavi Kalp#Lanet efektlerini kaldırır"},
	{"36", "Ansuz", "Kat için full harita"},
	{"37", "Perthro", "Bütün alınacak itemleri değiştirir"},
	{"38", "Berkano", "3er mavi sinek ve örümcek çıkartır"},
	{"39", "Algiz", "Invincibility for 30 seconds"},
	{"40", "Blank Rune", "Rastgele rune efekti#25% ihtimal ile kendini tekrar çıkartır"},
	{"41", "Black Rune", "Tüm düşmanlara 40 hasar verir#Odadaki tüm itemler için rastgele özellik artar#(İtemleri yok eder)"},
	{"42", "Chaos Card", "Atılabilir tekte öldürme kartı"},
	{"43", "Credit Card", "Odadaki tüm dükkan veya şeytan itemlerinden fiyatı kaldırır, ücretsiz yapar"},
	{"44", "Rules Card", "\"Yardımcı\" önerilerde bulunur"},
	{"45", "A Card Against Humanity", "Bütün odayı bokla doldurur"},
	{"46", "Suicide King", "Seni anında öldürür ve yere 10 pickup/collectible çıkartır"},
	{"47", "Get Out Of Jail Free Card", "Odadaki tüm kapıları açar"},
	{"48", "? Card", "Aktif itemini ücretsiz aktive eder"},
	{"49", "Dice Shard", "Odadaki itemleri ve pickupları değiştirir"},
	{"50", "Emergency Contact", "İki tane annenin eli gelir ve düşmanı alır"},
	{"51", "Holy Card", "Grants the Holy Mantle effect for one room#(Next damage you take is 0)#25% Chance to spawn another holy card"},
	{"52", "Huge Growth", "↑ +7 Hasar#↑ +30 Menzil#↑ +Boy artar#Taşları kır!#:Efekt oda boyunca sürer"},
	{"53", "Ancient Recall", "3 Rastgele kart çıkartır"},
	{"54", "Era Walk", "Düşmanları yavaşlatır#↓ -0.5 Hız azalır#-1 Gözyaşı hızı azalır#Efekt oda boyunca sürer"},
}


---------- Pills ----------

EID.descriptions["tr_tr"].unidentifiedPill = "Tanımlanmamış Hap"

EID.descriptions["tr_tr"].pills={
	{"0", "Bad Gas", "Gaz bulutu çıkartır"},
	{"1", "Bad Trip", "Sana 1 kalp hasar verir"},
	{"2", "Balls of Steel", "+2 Ruh Kalbi"},
	{"3", "Bombs are Key", "Switches number of bombs with keys"},
	{"4", "Explosive Diarrhea", "Bulunduğun yerde 5 troll bombası çıkartır"},
	{"5", "Full Health", "Full can"},
	{"6", "Health Down", "↓ HP azalır"},
	{"7", "Health Up", "↑ HP"},
	{"8", "I Found Pills", "Efekt yok"},
	{"9", "Puberty", "3 Tane kullanmak Olgun tranformastonunu sağlar (+1 Red Heart)"},
	{"10", "Pretty Fly", "1 Mavi sinek"},
	{"11", "Range Down", "↓ -2 Range down"},
	{"12", "Range Up", "↑ +2.5 Range up"},
	{"13", "Speed Down", "↓ -0.12 Hız azalır"},
	{"14", "Speed Up", "↑ +0.15 Hız"},
	{"15", "Tears Down", "↓ -0.28 Gözyaşı azalır"},
	{"16", "Tears Up", "↑ +0.35 Gözyaşı"},
	{"17", "Luck Down", "↓ -1 Şans azalır"},
	{"18", "Luck Up", "↑ +1 Şans"},
	{"19", "Telepills", "Rastgele bir odaya ışınlar"},
	{"20", "48 Hour Energy!", "Aktif itemini doldurur#1-2 pil düşürür"},
	{"21", "Hematemesis", "Biri dışında bütün kalpleri boşaltır#1-4 kırmızı kalp düşürür"},
	{"22", "Paralysis", "2 Saniye hareket edemezsin"},
	{"23", "I can see forever!", "Kattaki gizli oda kapılarını açar"},
	{"24", "Pheromones", "Odadaki tüm düşmanları aşık eder"},
	{"25", "Amnesia", "Kat haritasını gizler"},
	{"26", "Lemon Party", "Yerde düşmanlara hasar veren büyük sarı bir havuz bırakır"},
	{"27", "R U A Wizard?", "30 Saniye çapraz ateş et"},
	{"28", "Percs!", "Oda için sadece yarım kalp hasar al"},
	{"29", "Addicted!", "Oda için sadece tam kalp hasar al"},
	{"30", "Re-Lax", "2 Saniye yürümek bok çıkmasına sebep olur"},
	{"31", "???", "Kat için labirent laneti efekti"},
	{"32", "One makes you larger", "Büyürsün#Hitboxına etki etmez"},
	{"33", "One makes you small", "Küçülürsün#Hitboxın da küçülür"},
	{"34", "Infested!", "Odadaki her bok için 1 mavi sinek çıkartır"},
	{"35", "Infested?", "Odadaki her düşman için 1 mavi örümcek çıkartır#Odada düşman yok ise 1-3 mavi örümcek çıkartır"},
	{"36", "Power Pill!", "Kısa süreli dokunulmazlık efekti"},
	{"37", "Retro Vision", "30 Saniyeliğine ekranı pikselleştirir"},
	{"38", "Friends Till The End!", "3 mavi sinek"},
	{"39", "X-Lax", "Kaygan sıvı havuzu bırakır"},
	{"40", "Something's wrong...", "Yavaşlatan sıvı havuzu bırakır"},
	{"41", "I'm Drowsy...", "Slow all enemies in room"},
	{"42", "I'm Excited!!!", "Speed up for all enemies in room"},
	{"43", "Gulp!", "Trinketi yutar ve efektine kalıcı olarak sahip olur"},
	{"44", "Horf!", "Bir ipecac gözyaşı atar"},
	{"45", "Feels like I'm walking on sunshine!", "Kısa süreli dokunulmazlık efekti"},
	{"46", "Vurp!", "Son kullanılan hapı çıkartır"},
} 

---------- Sacrifice Room ----------
EID.descriptions["tr_tr"].sacrificeHeader = "[Sonraki feda odası ödülü]"

EID.descriptions["tr_tr"].sacrifice={
	{"1", "", "50% ihtimal ile 1 Altın#100% ihtimal ile 1 Bomba, B1de iken 1dk altında boss öldürüldüğünde"},
	{"2", "", "50% ihtimal ile 1 Altın#100% ihtimal ile 1 Bomba, B1de iken 1dk altında boss öldürüldüğünde"},
	{"3", "", "67% ihtimal ile arttırışmış Melek{{AngelRoom}} odası şansı"},
	{"4", "", "50% ihtimal ile 1 rastgele Kasa"},
	{"5", "", "33% ihtimal ile 3 Altın#67% ihtimal ile arttırışmış Melek{{AngelRoom}} odası şansı"},
	{"6", "", "33% ihtimal ile Melek{{AngelRoom}}/Şeytan{{DevilRoom}} Odasına ışınlan#67% ihtimal ile rastgele Kasa"},
	{"7", "", "33% ihtimal ile 1 rastgele Melek{{AngelRoom}} Odası itemi#67% ihtimal ile 1 ruh kalbi"},
	{"8", "", "100% ihtimal ile 7 troll Bombası"},
	{"9", "", "100% ihtimal ile \"Uriel\" bossunu çıkart"},
	{"10", "", "50% ihtimal ile 7 Ruh Kalbi#50% ihtimal ile 30 Altın"},
	{"11", "", "100% ihtimal ile \"Gabriel\" bossunu çıkart"},
	{"12", "", "50% ihtimal ile \"Dark Room\" katına ışınla"},
}

---------- Dice Room ----------
EID.descriptions["tr_tr"].diceHeader = "[Zar efekti]"

EID.descriptions["tr_tr"].dice={
	{"1", "", "Tüm itemlerini değiştirir#(sadece toplanabilir itemleri etkiler)"},
	{"2", "", "Odadaki tüm pickupları değiştir"},
	{"3", "", "Kattaki tüm pickupları değiştir"},
	{"4", "", "Kattaki tüm itemleri değiştir#Şeytan anlaşmasını etkilemez"},
	{"5", "", "Kattaki değiştir ve tekrar başlat"},
	{"6", "", "Kattaki tüm pickupları ve itemleri, üzerindeki itemleri değiştir"}
}

---------- Transformations ----------
EID.descriptions["tr_tr"].transformations = {
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Lord of the Flies",-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Mom",				-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}
