---------------------------------------
-----  Basic English descriptions -----
---------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

local languageCode = "uk_ua"

-- init en_us table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "Ukrainian"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = {{name="default"}, {name="inverted"}, {name="borderless"}}


---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "Сумна цибуля", "↑ {{Tears}} +0.7 Tears up"},
	{"2", "Внутрішнє око", "Triple shot#↓ {{Tears}} Tears down"},
	{"3", "Згинач ложок", "Homing tears"},
	{"4", "Голова Крікета", "↑ {{Damage}} +0.5 Damage up#↑ {{Damage}} +50% Damage Multiplier"},
	{"5", "Моє відображення", "Isaac's tears get a boomerang effect#↑ {{Range}} +1.5 Range up#↑ {{Shotspeed}} +0.6 Shot Speed up#↑ +1 Tear Height"},
	{"6", "Номер один", "↑ {{Tears}} +1.5 Tears up#↓ {{Range}} -17.62 Range down#↑ +0.76 Tear Height"},
	{"7", "Кров мученика", "↑ {{Damage}} +1 Damage up#{{Collectible34}} +50% Damage if Isaac has the Book of Belial or Devil Card effect active"},
	{"8", "Брат Боббі", "Fires normal tears#Deals 3.5 damage per tear"},
	{"9", "Скатол", "All fly enemies are friendly"},
	{"10", "Вінець з мух", "+2 fly orbitals#Blocks enemy projectiles"},
	{"11", "+1!", "↑ +1 life#Respawn with full health"},
	{"12", "Чарівний гриб", "↑ +1 Health up#{{Heart}} Full health#↑ {{Damage}} +0.3 Damage up#↑ {{Damage}} +50% Damage Multiplier#↑ {{Range}} +5.25 Range up#↑ {{Speed}} +0.3 Speed up#↑ +0.5 Tear Height#Size up"},
	{"13", "Вірус", "{{Poison}} Touching enemies poisons them#↓ {{Speed}} -0.1 Speed down#{{BlackHeart}} Poisoned enemies can drop Black Hearts"},
	{"14", "Гнів Роїда", "↑ {{Speed}} +0.6 Speed up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"15", "<3", "↑ {{Heart}} +1 Health up#{{Heart}} Full health"},
	{"16", "Сира печінка", "↑ {{Heart}} +2 Health up#{{Heart}} Full health"},
	{"17", "Ключ скелета", "{{Key}} +99 Keys"},
	{"18", "Долар", "{{Coin}} +99 coins"},
	{"19", "Бум!", "{{Bomb}} +10 Bombs"},
	{"20", "Трансцендентність", "Grants flight"},
	{"21", "Компас", "Reveals icons on the map#Does not reveal the layout of the map"},
	{"22", "Обід", "↑ {{Heart}} +1 Health up"},
	{"23", "Вечеря", "↑ {{Heart}} +1 Health up"},
	{"24", "Десерт", "↑ {{Heart}} +1 Health up"},
	{"25", "Сніданок", "↑ {{Heart}} +1 Health up"},
	{"26", "Гниле м'ясо", "↑ {{Heart}} +1 Health up"},
	{"27", "Дерев'яна ложка", "↑ {{Speed}} +0.3 Speed up"},
	{"28", "Пасок", "↑ {{Speed}} +0.3 Speed up"},
	{"29", "Матусині трусики", "↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"30", "Матусині каблуки", "↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"31", "Матусина помада", "↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"32", "Вішак для одягу", "↑ {{Tears}} +0.7 Tears up"},
	{"33", "Біблія", "Grants flight for the current room#{{MomsHeart}} Kills Mom's Foot and Mom's Heart instantly#{{Warning}} Kills Isaac when used on Satan"},
	{"34", "Книга Беліала", "↑ {{Damage}} +2 Damage up#{{Collectible7}} +50% Damage if Isaac has Blood of the Martyr#{{AngelDevilChance}} +12.5% Devil/Angel Room chance while held"},
	{"35", "Некрономікон", "Deals 40 damage to all enemies in the room"},
	{"36", "Лайно", "Spawns one poop and knocks back enemies#Can be placed next to a pit and destroyed with a bomb to make a bridge"},
	{"37", "Містер Бум", "Drops a large bomb below Isaac which deals 110 damage"},
	{"38", "Голова Таммі", "Fires 10 tears in a circle around Isaac#The tears copy Isaac's tear effects, plus 25 damage"},
	{"39", "Матусин бюстгальтер", "Freezes all enemies in the current room for 4 seconds"},
	{"40", "Камікадзе!", "Causes an explosion at Isaac's location#Deals 40 damage"},
	{"41", "Матусина прокладка", "{{Fear}} Fears all enemies in the current room for 5 seconds"},
	{"42", "Гнила голова Боба", "Using the item and firing in a direction throws the head#{{Poison}} The head explodes where it lands and poisons enemies caught in the blast"},
	{"43", "", "<item does not exist>"},
	{"44", "Телепорт!", "Teleports Isaac into a random room except I AM ERROR rooms"},
	{"45", "Смачне серце", "Heals 1 Red Heart"},
	{"46", "Щаслива ніжка", "↑ {{Luck}} +1 Luck up#+8% room clear reward chance#Better chance to win while gambling"},
	{"47", "Пульт доктора Зародка", "{{Collectible168}} On use, start aiming a crosshair#A missile lands on the crosshair after 1.5 seconds#Deals 20x damage"},
	{"48", "Стріла Купідона", "Piercing tears"},
	{"49", "Шуп-да-Вуп!", "Using the item and shooting in a direction fires a high damage Brimstone laser"},
	{"50", "Стівен", "↑ {{Damage}} +1 Damage up"},
	{"51", "Пентаграма", "↑ {{Damage}} +1 Damage up#{{AngelDevilChance}} +10% Devil/Angel Room chance"},
	{"52", "Доктор Зародок", "{{Bomb}} Isaac shoots bombs instead of tears#Each bomb deals 5x damage + 30#↓ {{Tears}} Tear Delay x 2.5"},
	{"53", "Магнето", "Pickups are attracted to Isaac"},
	{"54", "Карта скарбів", "Reveals the floor layout#Does not reveal room icons"},
	{"55", "Матусине око", "50% chance to shoot a tear backwards#{{Luck}} 100% chance at 2 Luck"},
	{"56", "Лимонна невдача", "Spills a pool of creep#The creep deals 24 contact damage per second"},
	{"57", "Фанат на відстані", "Mid-range fly orbital#Deals 75 contact damage per second"},
	{"58", "Книга Тіней", "Makes Isaac invincible for 10 seconds"},
	{"59", "", "<item does not exist>"},
	{"60", "Драбина", "Allows Isaac to cross 1-tile gaps"},
	{"61", "", "<item does not exist>"},
	{"62", "Чарівність вампіра", "{{HalfHeart}} Killing 13 enemies heals half a heart"},
	{"63", "Батарея", "Active items can be charged up twice and used twice in a row"},
	{"64", "Знижки Steam", "{{Shop}} Shop items cost 50% less#Owning two Steam Sales makes all paid items free"},
	{"65", "Кулінарна книга анархіста", "Spawns 6 troll bombs near the center of the room"},
	{"66", "Пісочний годинник", "{{Slow}} Slows enemies down for 8 seconds"},
	{"67", "Сестра Меггі", "Shoots normal tears#Deals 3.5 damage per tear"},
	{"68", "Технології", "Isaac fires lasers instead of tears"},
	{"69", "Шоколадне молоко", "{{Chargeable}} Chargeable tears#↑ {{Damage}} Fully charged tears deal 400% Damage#↓ {{Tears}} Tears down"},
	{"70", "Гормони росту", "↑ {{Damage}} +1 Damage up#↑ {{Speed}} +0.4 Speed up"},
	{"71", "Грибочок", "↑ {{Speed}} +0.3 Speed up#↓ {{Range}} -4.25 Range down*#↑ +1.5 Tear Height*#(*both add up to a slight Range up)#↑ Size down"},
	{"72", "Вервиця", "{{SoulHeart}} +3 Soul Hearts#{{Collectible33}} The Bible is added to all item pools"},
	{"73", "Кубик м'яса", "LVL1: Orbital#LVL2: Shooting orbital#LVL3: Meat Boy LVL1#LVL4: Meat Boy LVL2"},
	{"74", "Четвертак", "{{Coin}} +25 coins"},
	{"75", "Доктор наук", "{{Pill}} Changes bad pills into good pills#Spawns 1 pill on pickup#{{Heart}} Heals 2 Red Hearts#{{BloodDonationMachine}} Blood Donation Machines and {{Collectible135}} IV Bag give more coins"},
	{"76", "Рентгенівське бачення", "{{SecretRoom}} Opens all secret room entrances"},
	{"77", "Мій маленький єдиноріг", "Makes Isaac invincible and grants +0.28 Speed up#Isaac deals 40 contact damage per second while invincible#{{Timer}} Effects last 6 seconds"},
	{"78", "Книга Одкровень", "{{SoulHeart}} +1 Soul Heart#Higher Horseman boss chance if used#{{AngelDevilChance}} +17.5% Devil/Angel Room chance while held"},
	{"79", "Мітка", "↑ {{Damage}} +1 Damage up#↑ {{Speed}} +0.2 Speed up#{{SoulHeart}} +1 Soul Heart"},
	{"80", "Договір", "↑ {{Damage}} +0.5 Damage up#↑ {{Tears}} +0.7 Tears up#{{SoulHeart}} +2 Soul Hearts"},
	{"81", "Мертвий кіт", "↑ +9 lives#Respawn with 1 HP#↓ Removes all Red Heart containers but one#{{Warning}} Characters that can't have Red Hearts get set to 1 Soul/Black Heart"},
	{"82", "Володар ями", "Flight#↑ {{Speed}} +0.3 Speed up"},
	{"83", "Цвях", "{{SoulHeart}} +1 Soul Heart#↑ {{Damage}} +0.7 Damage up#↓ {{Speed}} -0.18 Speed down#Isaac deals 40 contact damage per second#Allows Isaac to destroy rocks by walking into them"},
	{"84", "Треба йти глибше!", "Opens a trapdoor to the next floor#{{LadderRoom}} 10% chance to open a crawlspace trapdoor"},
	{"85", "Колода карт", "{{Card}} Spawns 1 Card"},
	{"86", "Зуб Монстро", "Monstro falls on an enemy and deals 120 damage#{{Warning}} Monstro falls on Isaac if the room has no enemies"},
	{"87", "Ріжки Локі", "25% chance to shoot in 4 directions#{{Luck}} 100% chance at 7 Luck"},
	{"88", "Маленький Чаббі", "Charges forward in the direction Isaac is shooting#Deals 52.5 contact damage per second"},
	{"89", "Укус павука", "{{Slow}} 25% chance to shoot slowing tears#{{Luck}} 100% chance at 15 Luck"},
	{"90", "Маленький камінь", "↑ {{Damage}} +1 Damage up#↑ {{Tears}} +0.2 Tears up#↓ {{Speed}} -0.2 Speed down"},
	{"91", "Шолом спелеолога", "Reveals the room type of adjacent rooms#{{SecretRoom}} Can reveal Secret and Super Secret Rooms"},
	{"92", "Супер пластир", "↑ {{Heart}} +1 Health up#{{SoulHeart}} +2 Soul Hearts#{{Heart}} Heals 1 Red Heart"},
	{"93", "Геймкід", "Grants invincibility#{{Fear}} Fears all enemies in the room#Isaac deals 40 contact damage per second#{{HalfHeart}} Killing 2 enemies replenishes half a heart#{{Timer}} Effect lasts for 6.5 seconds"},
	{"94", "Мішок пенні", "{{Coin}} Drops a random coin every 2 rooms"},
	{"95", "Робо-Дитя", "Shoots lasers#Deals 3.5 damage per shot"},
	{"96", "Маленький Ч.А.Д.", "{{HalfHeart}} Drops half a heart every 3 rooms"},
	{"97", "Книга Гріхів", "Spawns a random pickup"},
	{"98", "Реліквія", "{{SoulHeart}} Spawns 1 Soul Heart every 5-6 rooms"},
	{"99", "Маленький Гіш", "{{Slow}} Slowing tears#Deals 3.5 damage per shot"},
	{"100", "Маленький Стівен", "Shoots homing tears#Deals 3.5 damage per shot"},
	{"101", "Німб", "↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.3 Damage up#↑ {{Tears}} +0.2 Tears up#↑ {{Range}} +0.25 Range up#↑ {{Speed}} +0.3 Speed up#↑ +0.5 Tear Height"},
	{"102", "Матусина пляшечка для пігулок", "{{Pill}} Spawns 1 Pill"},
	{"103", "Застуда", "{{Poison}} 25% chance to shoot Poison tears#{{Luck}} 100% chance at 12 Luck"},
	{"104", "Паразит", "Tears split in two on contact#Split tears deal half damage"},
	{"105", "D6", "Rerolls pedestal items in the current room"},
	{"106", "Містер Мега", "↑ Bomb damage x2.25#{{Bomb}} +5 Bombs"},
	{"107", "Зубчасті ножиці", "Flight#Isaac's body separates from his head and attacks enemies with 82.5 contact damage per second"},
	{"108", "Проскура", "Reduces all damage taken to half a heart"},
	{"109", "Гроші = Сила", "↑ {{Damage}} +0.04 Damage up for every {{Coin}}coin Isaac has"},
	{"110", "Матусині лінзи", "20% chance to shoot petrifying tears#↑ +0.25 Range up#↑ +0.5 Tear Height"},
	{"111", "Біб", "{{Poison}} Farts a poison cloud#The poison deals Isaac's damage 6 times"},
	{"112", "Ангел-Охоронець", "Orbital#Speeds up all other orbitals#Blocks projectiles#Deals 105 contact damage per second"},
	{"113", "Малюк Диявол", "Shoots enemies that get close to him#Deals 3 damage per shot"},
	{"114", "Матусин ніж", "Isaac's tears are replaced by a throwable knife#The knife deals 2x Isaac's damage while held and 6x damage at the furthest possible distance"},
	{"115", "Дошка Уіджа", "Spectral tears"},
	{"116", "9 Вольт", "Automatically charges the first bar of active items#{{Battery}} Fully recharges the current active item"},
	{"117", "Мертвий птах", "Getting hit spawns a bird#The bird deals 4 contact damage per second"},
	{"118", "Сірка", "{{Chargeable}} Isaac's tears are replaced by a chargeable blood laser"},
	{"119", "Мішок крові", "↑ {{Heart}} +1 Health up#↑ {{Speed}} +0.3 Speed up#{{Heart}} Heals 4 Hearts"},
	{"120", "Дивний гриб (Тонкий)", "↑ {{Tears}} +1.7 Tears up#↑ {{Speed}} +0.3 Speed up#↓ {{Damage}} -38% Damage Multiplier#Penalty shrinks with Damage Ups from other items"},
	{"121", "Дивний гриб (Великий)", "↑ {{EmptyHeart}} +1 Empty heart container#↑ {{Damage}} +0.3 Damage up#↑ {{Range}} +0.25 Range up#↓ {{Speed}} -0.1 Speed down#↑ +0.5 Tear Height"},
	{"122", "Вавилонська повія", "When on half a Red Heart or less:#↑ {{Damage}} +1.5 Damage up#↑ {{Speed}} +0.3 Speed up"},
	{"123", "Книга Монстрів", "Spawns a random familiar for the current room"},
	{"124", "Сувої Мертвого моря", "Triggers a random active item effect"},
	{"125", "Боббі-бомба", "Homing bombs#{{Bomb}} +5 Bombs"},
	{"126", "Лезо бритви", "↑ {{Damage}} +1.2 Damage up for the current room#{{Warning}} Deals 1 heart of damage to Isaac#Removes Red Hearts first"},
	{"127", "Забудь мене зараз", "{{Warning}} SINGLE USE {{Warning}}#Rerolls and restarts the entire floor"},
	{"128", "Навіки самотній", "Long range fly orbital#Deals 30 contact damage per second"},
	{"129", "Відро смальцю", "↑ +2 Empty heart container#↓ -0.2 Speed down#Heals half a heart"},
	{"130", "Поні", "Grants flight while held#{{Speed}} Sets your Speed to at least 1.5#Using the item dashes in the direction of Isaac's movement"},
	{"131", "Сумка з бомбами", "{{Bomb}} Drops 1 Bomb pickup every 2-3 rooms"},
	{"132", "Кусок вугілля", "{{Damage}} Tears deal more damage the further they travel"},
	{"133", "Лапка Гаппі", "Converts 1 heart container into 3 Soul Hearts"},
	{"134", "Хвіст Гаппі", "{{Chest}} 33% chance to replace the room clear reward with a chest#33% chance to spawn no room clear reward"},
	{"135", "Крапельниця", "Hurts Isaac for half a heart and spawns 1-3 coins#{{Player14}} Spawns 0-1 coin as Keeper"},
	{"136", "Найкращий друг", "Spawns a decoy Isaac that attracts enemies and explodes after 5 seconds"},
	{"137", "Дистанційний детонатор", "{{Bomb}} +5 bombs#Isaac's bombs no longer explode automatically#Using the item detonates all of Isaac's bombs at once"},
	{"138", "Розп'яття", "↑ +1 Health up#↑ {{Damage}} +0.3 Damage up"},
	{"139", "Матусина сумочка", "{{Trinket}} Isaac can hold 2 trinkets"},
	{"140", "Прокляття Боба", "{{Poison}} Isaac's bombs poison enemies caught in the blast#{{Bomb}} +5 bombs"},
	{"141", "Видатний хлопчик", "{{Coin}} Spawns 7 random coins"},
	{"142", "Скапулярій", "{{SoulHeart}} Isaac gains 1 Soul Heart when damaged down to half a heart#Can only happen once per room#Exiting and re-entering the room allows the effect to trigger again"},
	{"143", "Спідбол", "↑ {{Speed}} +0.3 Speed up#↑ {{Shotspeed}} +0.2 Shot Speed up"},
	{"144", "Друг-жебрак", "{{Coin}} Picks up coins and spawns random pickups in return"},
	{"145", "Голова Гаппі", "Spawns 2-4 blue flies"},
	{"146", "Молитовна картка", "{{EternalHeart}} +1 Eternal Heart"},
	{"147", "Вищерблене кайло", "Allows Isaac to break rocks and Secret Room walls by walking into them"},
	{"148", "Зараження", "Taking damage spawns blue flies"},
	{"149", "Іпекак", "Isaac's tears are fired in an arc#{{Poison}} The tears explode and poison enemies where they land#↑ {{Damage}} +40 Damage up#↓ {{Tears}} Tears down"},
	{"150", "Жорстока любов", "10% chance to shoot teeth#{{Damage}} Teeth deal 3.2x Isaac's damage#{{Luck}} 100% chance at 9 Luck"},
	{"151", "Маліган", "Hitting an enemy with a tear has a 1/6 chance to spawn a fly"},
	{"152", "Технологія 2", "Replaces Isaac's right eye tears with a continuous laser#Laser deals 20% of Isaac's damage#↓ {{Damage}} -35% Damage down#↓ {{Tears}} Tear Delay x 2"},
	{"153", "Павук-мутант", "Isaac fires 4 tears at once#↓ {{Tears}} Tears down"},
	{"154", "Хімічний опік", "↑ {{Damage}} +2 Damage up for the left eye"},
	{"155", "Споглядач", "Floats around the room#Deals 17.1 contact damage per second"},
	{"156", "Ряса", "{{Battery}} Taking damage adds 1 charge to the active item"},
	{"157", "Кривава жага", "↑ {{Damage}} Taking damage grants a damage up#Applies up to 6 times per floor#Lasts for the whole floor"},
	{"158", "Кришталева куля", "Reveals the map#Drops a Card or a Soul Heart"},
	{"159", "Дух ночі", "Flight#Spectral tears"},
	{"160", "Розколи небеса", "Spawns 5 beams of light near enemies#Deals Isaac's damage + 20"},
	{"161", "Анкх", "{{Player4}} Respawn as ??? (Blue Baby) on death"},
	{"162", "Кельтський хрест", "Taking damage can make Isaac temporarily invincible"},
	{"163", "Дитина-привид", "Spectral tears familiar#Deals 3.5 damage per shot"},
	{"164", "Свічка", "Throws a blue flame#The flame deals contact damage, blocks enemy tears, and despawns after 2 seconds"},
	{"165", "Дев'ятихвоста кішка", "↑ {{Damage}} +1 Damage up#↑ {{Shotspeed}} +0.23 Shot speed up"},
	{"166", "D20", "Rerolls all pickups in the room"},
	{"167", "Малюк Арлекін", "Shoots two tears in a V-shaped pattern#Deals 4 damage per shot"},
	{"168", "Епічний Зародок", "Instead of tears, aim a crosshair#A rocket lands on the crosshair after 1.5 seconds#Rockets deal 20 times Isaac's damage"},
	{"169", "Поліфем", "↑ {{Damage}} +100% Damage up#↑ {{Damage}} +4 additional Damage up#↓ {{Tears}} Tears down#Tears keep going after killing an enemy"},
	{"170", "Довгоногий татусь", "Randomly stomps on an enemy#Deals 40 damage per second"},
	{"171", "Павуча дупка", "Slows down enemies for 4 seconds#Deals 10 damage to all enemies"},
	{"172", "Ніж для жертвопринесень", "Orbital#Blocks enemy shots#Deals 225 damage per second"},
	{"173", "Митра", "{{SoulHeart}} Higher chance to find Soul Hearts"},
	{"174", "Веселковий малюк", "Shoots random tears#Deals 3-5 damage per shot"},
	{"175", "Татусевий ключ", "Opens all doors in the room, including {{SecretRoom}}{{SuperSecretRoom}}Secret Rooms, {{ChallengeRoom}}{{BossRushRoom}}Challenge Rooms, and the Mega Satan door"},
	{"176", "Стовбурові клітини", "↑ {{Heart}} +1 Health up#↑ {{Shotspeed}} +0.16 Shot Speed up"},
	{"177", "Переносний автомат", "Portable slot machine#Spend 1 coin for a chance to spawn a pickup"},
	{"178", "Свята вода", "Taking damage spills a pool of creep#The creep deals 24 damage per second"},
	{"179", "Доля", "Flight#{{EternalHeart}} +1 Eternal Heart"},
	{"180", "Чорна квасоля", "Isaac farts when touched"},
	{"181", "Білий поні", "Grants flight while held#{{Speed}} Sets your Speed to at least 1.5#Using the item dashes in the direction of Isaac's movement, leaving behind beams of light"},
	{"182", "Святе серце", "↑ +1 Health up#{{Heart}} Full health#↑ 230% + 1 Damage up#↓ -0.4 Tears down#↓ -0.25 Shot Speed down#↑ +0.38 Range up#↑ +0.75 Tear Height#Homing tears"},
	{"183", "Зубочистки", "↑ {{Tears}} +0.7 Tears up#↑ {{Shotspeed}} +0.16 Shot Speed up"},
	{"184", "Святий Грааль", "Flight#↑ +1 Health up"},
	{"185", "Мертвий голуб", "Flight#Spectral tears"},
	{"186", "Криваві права", "Deals 40 damage to every enemy#{{Warning}} Deals 1 heart of damage to Isaac#Removes Red Hearts first"},
	{"187", "Клубок шерсті Гаппі", "Moving swings the hairball around#The ball grows when it kills an enemy#The ball deals more damage the bigger it is"},
	{"188", "Авель", "Mirrors Isaac's movement#Shoots towards Isaac#Deals 3.5 damage per shot"},
	{"189", "Суперфанат SMB", "↑ +1 Health up#{{Heart}} Full health#↑ +0.3 Damage up#↑ +0.2 Tears up#↑ +0.5 Range up#↑ +0.2 Speed up#↑ +1 Tear Height"},
	{"190", "Пайро", "{{Bomb}} +99 Bombs"},
	{"191", "Тридоларова купюра", "Isaac's tears get random effects every 2-3 seconds"},
	{"192", "Телепатія для чайників", "Grants homing tears for the current room"},
	{"193", "М'ЯСО!", "↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.3 Damage up"},
	{"194", "Чарівна куля 8", "↑ {{Shotspeed}} +0.16 Shot speed up#{{Card}} +1 card"},
	{"195", "Матусин гаманець", "{{Pill}} Drops 4 Pills"},
	{"196", "Стискання", "{{SoulHeart}} Spawns 2 Soul Hearts#↑ {{Tears}} +0.4 Tears up"},
	{"197", "Йсусів сік", "↑ {{Damage}} +0.5 Damage up#↑ {{Range}} +0.25 Range up#↑ +0.5 Tear Height"},
	{"198", "Коробка", "Spawns 1 pickup of each type"},
	{"199", "Матусин ключ", "{{Key}} +2 Keys#Chests contain more pickups"},
	{"200", "Матусині тіні", "{{Charm}} 10% chance to shoot charming tears"},
	{"201", "Залізний зливок", "↑ {{Damage}} +0.3 Damage up#{{Confusion}} 10% chance to shoot concussive tears"},
	{"202", "Дотик Мідаса", "Touching enemies turns them gold#Isaac deals contact damage based on his coin count#{{Coin}} Killing a golden enemy drops coins#Poop spawned by Isaac has a high chance to be Golden Poop"},
	{"203", "Скромний згорток", "Pickups spawned are doubled if possible"},
	{"204", "Поясна сумка", "Taking damage has a 50% chance to drop a random pickup"},
	{"205", "Гострий штекер", "{{Battery}} Using an uncharged active item fully recharges it at the cost of 2 Hearts#Only works when item has no charges"},
	{"206", "Гільйотина", "↑ {{Damage}} +1 Damage up#↑ {{Tears}} Tears up#Isaac's head becomes an orbital that shoots, doesn't take damage and deals 105 contact damage"},
	{"207", "Клубок бинтів", "LVL1: Orbital#LVL2: Shooting orbital#LVL3: Bandage Girl LVL1#LVL4: Bandage Girl LVL2"},
	{"208", "Чемпіонський пояс", "↑ {{Damage}} +1 Damage up#+15% chance for champion enemies"},
	{"209", "Дупні бомби", "{{Bomb}} +5 Bombs#{{Confusion}} Explosions concuss and damage every enemy in the room"},
	{"210", "Покусаний листочок", "Standing still for 1 second makes Isaac invincible"},
	{"211", "Павучок", "Taking damage spawns 1-2 blue spiders"},
	{"212", "Нашийник Гаппі", "50% chance to revive with half a heart on death"},
	{"213", "Втрачена лінза", "Isaac's tears destroy enemy shots#↓ {{Shotspeed}} -0.15 Shot Speed down"},
	{"214", "Анемія", "↑ {{Range}} +5 Range up#Taking damage spills a trail of toxic blood for the duration of the room"},
	{"215", "Голова козла", "{{AngelDevilChance}} 100% chance for Devil/Angel Rooms to open"},
	{"216", "Церемоніальна мантія", "↑ {{Damage}} +1 Damage up#{{BlackHeart}} +3 Black Hearts"},
	{"217", "Матусина перука", "Shooting tears has a random chance to spawn a blue spider#{{Heart}} Heals 1 Red Heart"},
	{"218", "Плацента", "↑ {{Heart}} +1 Health up#{{HalfHeart}} Chance to heal half a heart every minute"},
	{"219", "Стара пов'язка", "↑ {{EmptyHeart}} +1 Empty heart container#{{Heart}} Taking damage has a random chance to drop a Red Heart"},
	{"220", "Плаксиві бомби", "Isaac's bombs fire 10 tears in a circle when they explode#{{Bomb}} +5 Bombs"},
	{"221", "Гумовий клей", "Isaac's tears bounce off enemies and obstacles"},
	{"222", "Антигравітація", "Holding the fire buttons causes tears to hover in midair#Releasing the fire buttons shoots them in the direction they were fired#↑ {{Tears}} -2 Tear Delay"},
	{"223", "Піроманіяк", "Getting hit by explosions heals 1 Red Heart instead of damaging Isaac#Grants immunity to rock wave attacks and Mom and Satan's stomp attacks#{{Bomb}} +5 Bombs"},
	{"224", "Тіло Крікета", "Tears split up in 4 on hit#Split tears deal half damage#↑ {{Tears}} +1 Tears up#↓ {{Range}} -10 Range down"},
	{"225", "Покора", "{{SoulHeart}} Taking damage has a chance to spawn a Soul Heart#{{HalfHeart}} Enemies have a chance to drop a Half Red Heart on death"},
	{"226", "Чорний лотос", "↑ {{Heart}} +1 Health up#{{SoulHeart}} +1 Soul Heart#{{BlackHeart}} +1 Black Heart"},
	{"227", "Свинка-скарбничка", "{{Coin}} +3 coins#Taking damage spawns 1-2 coins#{{Player14}} 0-1 coin as Keeper"},
	{"228", "Матусині парфуми", "{{Fear}} 15% chance to shoot Fear tears#↑ {{Tears}} +1 Tears up"},
	{"229", "Легеня Монстро", "{{Chargeable}} Tears are charged and released in a shotgun style attack#↓ {{Tears}} 4.3x Tear Delay up"},
	{"230", "Абаддон", "↑ {{Damage}} +1.5 Damage up#↑ {{Speed}} +0.2 Speed up#{{Fear}} Fear tears#↓ {{EmptyHeart}} Removes all heart containers#{{BlackHeart}} +6 Black Hearts"},
	{"231", "Куля з дьогтю", "{{Slow}} 10% chance to shoot slowing tears#{{Luck}} 100% chance at 18 Luck#Isaac leaves a trail of slowing creep"},
	{"232", "Секундомір", "{{Slow}} Taking damage slows all enemies in the room permanently#↑ +0.3 Speed up"},
	{"233", "Крихітна планета", "Isaac's tears orbit around him#↑ {{Range}} Range way up#↑ +7 Tear Height#Spectral tears"},
	{"234", "Зараження 2", "Killing an enemy spawns a blue spider"},
	{"235", "", "<item does not exist>"},
	{"236", "Кишкова паличка", "Touching an enemy turns it into poop"},
	{"237", "Дотик смерті", "↑ {{Damage}} +1.5 Damage up#↑ Tear size up#↓ {{Tears}} -0.3 Tears down#Piercing tears"},
	{"238", "1 частина ключа", "{{Warning}} Getting both parts of the key opens a big golden door#{{AngelChance}} 25% higher Angel Room chance#{{EternalHeart}} +2% chance for Eternal Hearts"},
	{"239", "2 частина ключа", "{{Warning}} Getting both parts of the key opens a big golden door#{{AngelChance}} 25% higher Angel Room chance#{{EternalHeart}} +2% chance for Eternal Hearts"},
	{"240", "Експериментальна терапія", "All Stats ↑/↓ a random number"},
	{"241", "Контракт знизу", "Doubles all room clear rewards#33% chance for no room clear reward#{{GreedMode}} Doesn't affect Greed Mode"},
	{"242", "Безславність", "50% chance to block tears"},
	{"243", "Трисвятий щит", "Blocks enemy shots coming from the direction Isaac is firing"},
	{"244", "Технологія 0.5", "Occasionally fire lasers in addition to Isaac's tears"},
	{"245", "20/20", "Isaac fires 2 tears at once"},
	{"246", "Синя карта", "{{SecretRoom}} Reveals secret room locations on the map"},
	{"247", "Найкращі друзі назавжди!", "Familiars deal double damage"},
	{"248", "Вуликовий розум", "Blue Spiders and Flies deal double damage"},
	{"249", "У тебе є вибір", "Allows Isaac to choose between 2 items after beating a boss"},
	{"250", "Подвійні бомби", "{{Bomb}} All bomb drops become double bombs"},
	{"251", "Стартова колода", "{{Card}} Isaac can carry 2 Cards#Turns all Pills into Cards#Spawns 1 card on pickup"},
	{"252", "Маленький мішечок", "{{Pill}} Isaac can carry 2 Pills#Turns all Cards into Pills#Spawns 1 pill on pickup"},
	{"253", "Чарівний струп", "↑ {{Luck}} +1 Luck up#↑ {{Heart}} +1 Health up"},
	{"254", "Згусток крові", "↑ {{Damage}} +1 Damage up#↑ {{Range}} +5 Range up#Applies to the left eye only"},
	{"255", "Гвинт", "↑ {{Tears}} +0.5 Tears up#↑ {{Shotspeed}} +0.2 Shot Speed up"},
	{"256", "Гарячі бомби", "{{Burning}} Isaac's bombs leave a flame where they explode#{{Bomb}} +5 Bombs"},
	{"257", "Вогняні думки", "{{Burning}} Isaac's tears light enemies on fire#Chance for tears to explode on enemy impact#{{Luck}} 100% chance to explode at 13 Luck#{{Warning}} The explosion can hurt Isaac"},
	{"258", "Загублений біт", "Rerolls all of Isaac's items and stats on pickup and at every new floor"},
	{"259", "Чорна матерія", "↑ {{Damage}} +1 Damage up#{{Fear}} 33% chance to shoot Fear tears#{{Luck}} 100% chance at 20 Luck"},
	{"260", "Чорна свічка", "{{CurseBlind}} Grants immunity to curses#{{BlackHeart}} +1 Black Heart#{{AngelDevilChance}} +15% Devil/Angel Room chance"},
	{"261", "Проптоз", "↑ {{Damage}} +100% Damage up#↓ Tears deal less Damage the further they travel"},
	{"262", "Втрачена сторінка 2", "{{BlackHeart}} +1 Black Heart#Taking damage down to 1 heart damages all enemies in the room"},
	{"263", "", "<item does not exist>"},
	{"264", "Розумна мушка", "Orbital#Attacks enemies when Isaac takes damage#Deals 22.5 damage per second"},
	{"265", "Висушене дитя", "10% chance to damage all enemies in the room when it is hit by an enemy tear"},
	{"266", "Соковитий мішечок", "Leaves slowing creep#Spawns 1-2 friendly spiders after clearing a room"},
	{"267", "Робо-дитя 2.0", "Shoots lasers#Deals 3.5 damage per shot#Moves in the direction Isaac is firing"},
	{"268", "Гниле дитя", "Spawns blue flies when Isaac shoots"},
	{"269", "Безголове дитя", "Leaves creep which deals 6 damage per second"},
	{"270", "П'явка", "Chases enemies#{{HalfHeart}} Heals Isaac for half a heart when it kills an enemy#Deals 3.2 damage per second"},
	{"271", "Загадковий мішечок", "Drops a random pickup every few rooms"},
	{"272", "ВЧМ", "Friendly exploding fly#The explosion deals 60 damage#{{Warning}} The explosion can hurt Isaac"},
	{"273", "Мозок Боба", "Dashes in the direction Isaac is shooting#Explodes when it hits an enemy#The explosion deals 60 damage and can hurt Isaac"},
	{"274", "Найкращий друг", "Taking damage spawns one midrange orbital for the room#The orbital deals 75 damage per second"},
	{"275", "Сірчаний крихітка", "{{Collectible118}} Familiar that charges and shoots a Brimstone laser#Deals 31.5 damage per second"},
	{"276", "Серце Ісаака", "Isaac becomes invincible#Spawns a heart familiar that follows Isaac#{{Warning}} If the heart familiar gets hit, Isaac takes damage"},
	{"277", "Крихітний привид", "Chases and fears enemies#Deals 4 damage per second"},
	{"278", "Темний жебрак", "{{Heart}} Picks up Red Hearts from the floor#Spawns a Soul/Black Heart or spider for every 1.5 Red Hearts picked up"},
	{"279", "Великий фанат", "Large orbital#Deals 30 damage per second"},
	{"280", "Сісся Довгоногий", "Randomly spawns blue spiders while in hostile rooms"},
	{"281", "Боксерська груша", "Decoy familiar#Enemies target him instead of Isaac"},
	{"282", "Як правильно стрибати", "Allows Isaac to jump over gaps and obstacles"},
	{"283", "D100", "Reroll all pickups and pedestal items in the room, and all of Isaac's passive items"},
	{"284", "D4", "Reroll all of Isaac's passive items"},
	{"285", "D10", "Reroll all enemies in the room"},
	{"286", "Порожня карта", "Triggers the effect of the card Isaac holds without using it"},
	{"287", "Книга Таїнств", "Activates one of these effects for the floor:#{{Collectible54}} Treasure Map#{{Collectible21}} Compass#{{Collectible246}} Blue Map"},
	{"288", "Коробка з павуками", "Spawns 1-4 blue spiders"},
	{"289", "Червона свічка", "Throws a red flame#The flame disappears when it has dealt damage or blocked shots 5 times"},
	{"290", "Банка", "{{Heart}} Picking up Red Hearts while at full health stores up to 4 of them in the Jar#Using the item drops all stored hearts on the floor"},
	{"291", "Змив!", "Turns all non-boss enemies into poop#Instantly kills poop enemies and bosses"},
	{"292", "Сатанинська біблія", "{{BlackHeart}} +1 Black Heart"},
	{"293", "Голова Крампуса", "Shoot brimstone lasers in all 4 directions"},
	{"294", "Масляний біб", "Knocks back nearby enemies and projectiles#10% chance to turn into the stronger {{Collectible484}}Wait What? when swapping it with a different active item and picking it up again"},
	{"295", "Чарівні пальчики", "Deals 2x Isaac's damage to all enemies#{{Warning}} Costs 1 coin to use"},
	{"296", "Перетворювач", "Converts 2 Soul/Black Hearts into 1 Red Heart Container"},
	--NOTE FOR LOCALIZERS: There is code to highlight the text of your current floor
	--For it to work, only use line breaks or semicolons to separate floor details, and use the same order as English
	{"297", "Скринька Пандори", "{{Warning}} SINGLE USE, spawns rewards based on floor:#B1: 2{{SoulHeart}}; B2: 2{{Bomb}} + 2{{Key}}#C1: Boss item; C2: B1+C1#D1: 4{{SoulHeart}}; D2: 20{{Coin}}#W1: 2 Boss items#W2: {{Collectible33}} The Bible#???/Void: Nothing#Sheol: Devil item + 1{{BlackHeart}}#Cathe: Angel item + 1{{EternalHeart}}#Dark Room: Unlocks {{Collectible523}} Moving Box; Chest: 1{{Coin}}"},
	{"298", "Копито Єдинорога", "Invincibility and +0.28 speed up for 6 seconds#Doesn't grant contact damage"},
	{"299", "Телець", "↓ {{Speed}} -0.3 Speed down#↑ {{Speed}} Slowly gain speed while in hostile rooms#At 2 speed, Isaac becomes invincible and deals contact damage#Afterwards, lose the Taurus speed boost for the room"},
	{"300", "Овен", "↑ {{Speed}} +0.25 Speed up#Touching enemies deals contact damage"},
	{"301", "Рак", "{{SoulHeart}} +3 Soul Hearts#Taking damage reduces all future damage in the room to half a heart"},
	{"302", "Лев", "Isaac can destroy rocks by walking into them#Size up"},
	{"303", "Діва", "Taking damage can make Isaac temporarily invincible#{{Luck}} 100% chance at 10 Luck#{{Pill}} Converts negative pills into positive ones"},
	{"304", "Терези", "+6 Coins, Keys, and Bombs#Balances Isaac's stats#Future stat changes will be spread across all stats"},
	{"305", "Скорпіон", "{{Poison}} Poison tears"},
	{"306", "Стрілець", "↑ {{Speed}} +0.2 Speed up#Piercing tears"},
	{"307", "Козоріг", "↑ {{Heart}} +1 Health up#↑ {{Damage}} +0.5 Damage up#↑ {{Speed}} +0.1 Speed up#↑ {{Range}} +1.5 Range up#↑ {{Tears}} Tears up#+1 Bomb, Coin, and Key"},
	{"308", "Водолій", "Isaac leaves a trail of creep#The creep deals 6 damage per second"},
	{"309", "Риби", "↑ {{Tears}} -1 Tear Delay#Increases knockback"},
	{"310", "Туш Єви", "↑ {{Damage}} +100% Damage up#↓ {{Tears}} -50% Tears down#↓ {{Shotspeed}} -0.5 Shot speed down"},
	{"311", "Тінь Юди", "{{Player12}} When dead, respawn as Dark Judas with a 2x Damage Multiplier"},
	{"312", "Бантик Меггі", "↑ {{Heart}} +1 Health up#{{Heart}} Heals 1 Red Heart#All Red Hearts heal double their value"},
	{"313", "Свята мантія", "Negates the first hit taken once per room"},
	{"314", "Громові стегна", "↑ {{Heart}} +1 Health up#↓ {{Speed}} -0.4 Speed down#Isaac can destroy rocks by walking into them"},
	{"315", "Дивна принада", "Isaac's tears attract enemies, pickups and trinkets"},
	{"316", "Прокляте око", "Charged wave of 4 tears#{{Warning}} Taking damage while partially charged teleports Isaac to a random room#{{Collectible260}} Black Candle removes the teleportation effect"},
	{"317", "Загадкова рідина", "Isaac's tears leave creep#The creep deals 30 damage per second"},
	{"318", "Близнюки", "Close combat familiar#Deals 6 contact damage per second"},
	{"319", "Інше око Каїна", "Bounces around the room#Shoots towards Isaac#{{Damage}} Deals the same damage as Isaac"},
	{"320", "Єдиний друг ???", "Controllable Fly#Deals 37.5 contact damage per second"},
	{"321", "Кайдани Самсона", "Draggable ball that can destroy rocks#Deals 10.7 contact damage per second"},
	{"322", "Дитя Монго", "Mimics one of Isaac's familiars#Deals double its damage"},
	{"323", "Сльози Ісаака", "Shoots 8 tears in all directions#The tears copy Isaac's tear effects#Recharges by shooting tears"},
	{"324", "Невизначено", "Teleports Isaac to the {{TreasureRoom}} Treasure, {{SecretRoom}} Secret, {{SuperSecretRoom}} Super Secret or {{ErrorRoom}} I AM ERROR Room"},
	{"325", "Ножиці", "Isaac's head turns into a stationary familiar#The body is controlled separately"},
	{"326", "Подих життя", "Holding down the USE button empties the charge bar#Isaac is temporarily invincible when the charge bar is empty#{{Warning}} Holding it for too long deals damage to Isaac"},
	{"327", "Полароїд", "Taking damage at half a Red Heart or none makes isaac temporarily invincible"},
	{"328", "Негатив", "Taking damage at half a Red Heart or none damages all enemies in the room"},
	{"329", "Технологія Людовіко", "Replaces Isaac's tears with one giant controllable tear"},
	{"330", "Соєве молоко", "↑ {{Tears}} Tears way up: (delay /4) - 2#↓ {{Damage}} Damage way down: -80%"},
	{"331", "Божество", "Homing tears#↑ {{Damage}} +0.5 Damage up#↑ {{Range}} +1.2 Range up#↓ {{Tears}} -0.3 Tears down#↓ {{Shotspeed}} -0.3 Shot Speed down#↑ +0.8 Tear Height#Tears gain a damaging aura"},
	{"332", "Ганчір'я Лазаря", "{{Player11}} When dead, revive as Lazarus (Risen)"},
	{"333", "Розум", "Full mapping effect"},
	{"334", "Тіло", "↑ {{Heart}} +3 Health up"},
	{"335", "Душа", "{{SoulHeart}} +2 Soul Hearts#Grants an aura that repels enemies and projectiles"},
	{"336", "Гнила цибуля", "Piercing + spectral tears#↑ {{Range}} +0.25 Range up#↓ {{Shotspeed}} -0.4 Shot Speed down#↓ -0.5 Tear Height#↑ {{Tearsize}} +50% Tear size"},
	{"337", "Зламаний секундомір", "Slows down every 4th room#13% chance to speed up the room instead"},
	{"338", "Бумеранг", "Throwable boomerang#Stuns enemies and deals 2x Isaac's damage#Can grab and bring back items"},
	{"339", "Шпилька", "↑ {{Range}} +5.25 Range up#↑ {{Shotspeed}} +0.16 Shot Speed up#↑ +0.5 Tear Height#{{BlackHeart}} +1 Black Heart"},
	{"340", "Кофеїнова пігулка", "↑ {{Speed}} +0.3 Speed up#↑ Size down#{{Pill}} Spawns a random pill"},
	{"341", "Розірване фото", "↑ {{Tears}} +0.7 Tears up#↑ {{Shotspeed}} +0.16 Shot Speed up"},
	{"342", "Синя шапочка", "↑ {{Heart}} +1 Health up#↑ {{Tears}} +0.7 Tears up#↓ {{Shotspeed}} -16% Shot Speed down"},
	{"343", "Запасний ключ", "↑ {{Luck}} +1 Luck up#{{SoulHeart}} +1 Soul Heart#{{Key}} Spawns 2 keys"},
	{"344", "Сірникова коробка", "{{BlackHeart}} +1 Black Heart#{{Bomb}} Spawns 3 Bomb pickups"},
	{"345", "Синтол", "↑ {{Damage}} +1 Damage up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height"},
	{"346", "Перекус", "↑ {{Heart}} +1 Health up"},
	{"347", "Диплопія", "{{Warning}} SINGLE USE {{Warning}}#Duplicates any pedestals and consumables in the current room"},
	{"348", "Плацебо", "{{Pill}} Triggers the effect of the pill Isaac holds without using it"},
	{"349", "Дерев'яний нікель", "50% chance to spawn a random coin"},
	{"350", "Токсичний шок", "{{Poison}} Entering a room poisons all enemies#Enemies killed leave a puddle of creep"},
	{"351", "Мега біб", "Freeze all enemies in the current room#Deals 5 damage and poisons any enemies nearby#Sends a rock wave in the direction Isaac is moving#The rock wave can open secret rooms and break rocks"},
	{"352", "Скляна гармата", "↓ Firing the cannon reduces Isaac's health down to half a heart#Fires a large piercing spectral tear that does 10x damage"},
	{"353", "Хлопчик-Підривник", "{{Bomb}} +5 bombs#Bombs explode in a cross-shaped pattern"},
	{"354", "Хрусткий Джек", "↑ {{Heart}} +1 Health up#{{Trinket}} Spawns a random trinket"},
	{"355", "Матусине намисто", "↑ {{Range}} +1.25 Range up#↑ {{Luck}} +1 Luck up#↑ +0.5 Tear Height"},
	{"356", "Автомобільний акумулятор", "Using an active item triggers its effect twice"},
	{"357", "Коробка з друзями", "Duplicates all familiars for the current room#Spawns {{Collectible113}}Demon Baby if Isaac has no familiars"},
	{"358", "Чаклун", "Isaac fires 2 tears at once diagonally#Spectral tears"},
	{"359", "8-дюймові цвяхи", "↑ {{Damage}} +1.5 Damage up#Increases knockback"},
	{"360", "Інкуб", "Shoots tears with the same stats and effects as Isaac"},
	{"361", "Нагорода долі", "Shoots tears with the same damage and effects as Isaac#Shoots at half the rate of other familiars"},
	{"362", "Крихітна скринька", "Spawns a random pickup every few rooms"},
	{"363", "Затятий захисник", "Orbital#Deals 105 contact damage per second#Blocks and attracts bullets#Blocking 10 tears in one room drops an Eternal Heart"},
	{"364", "Френдзона", "Midrange fly orbital#Deals 45 contact damage per second"},
	{"365", "Розгублена мушка", "Moves along walls/obstacles#Deals 105 contact damage per second"},
	{"366", "Розкидні бомби", "{{Bomb}} +5 bombs#Isaac's bombs scatter into 2-4 tiny bombs"},
	{"367", "Липкі бомби", "{{Bomb}} +5 bombs#Killing an enemy with a bomb spawns blue spiders#Isaac's bombs stick to enemies"},
	{"368", "Епіфора", "Shooting in one direction gradually decreases tear delay by up to 200%"},
	{"369", "Континуум", "↑ {{Range}} +2.25 Range up#↑ +1.5 Tear Height#Spectral tears#Tears can travel through one side of the screen and come out the other side"},
	{"370", "Містер Лялька", "↑ {{Tears}} +0.7 Tears up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height#{{UnknownHeart}} Spawns 3 random hearts when picked up"},
	{"371", "Прокляття вежі", "Taking damage spawns 6 troll bombs#The troll bombs inherit Isaac's bomb effects"},
	{"372", "Заряджене дитя", "Every 30 seconds while in an uncleared room, the familiar can:#Spawn a Battery (max 2 per room)#Add one charge to the active item (max 2 per room)#Freeze all enemies in the room"},
	{"373", "Мертве око", "↑ {{Damage}} Consecutive tear hits on enemies grant +25% Damage up(max +100%)#Missing has a chance to reset the multiplier"},
	{"374", "Святе світло", "10% chance to shoot Holy tears, which spawn a beam of light on hit#The beam deals 4x Isaac's damage#{{Luck}} 50% chance at 9 Luck"},
	{"375", "Капелюх Господаря", "Grants immunity to explosions#Grants immunity to rock wave attacks and Mom and Satan's stomp attacks#25% chance to reflect enemy shots"},
	{"376", "Поповнення", "Spawns 3 random Pickups#Buying an item from a shop restocks it instantly"},
	{"377", "Розірваний кокон", "Spider enemies no longer target or deal contact damage to Isaac"},
	{"378", "Номер 2", "Firing tears for 3 seconds spawns a lit Butt Bomb"},
	{"379", "Роздвоєні зіниці", "Isaac's tears get a much larger hitbox#Spectral tears"},
	{"380", "Плати та грай", "{{Coin}} +5 coins#Single-key doors must be opened with coins instead of keys"},
	{"381", "Едемове благословення", "↑ {{Tears}} +0.7 Tears up#Grants a random item at the start of the next run"},
	{"382", "Дружній м'яч", "Can be thrown at enemies to capture them#Using the item after capturing an enemy spawns the capture as a friendly companion"},
	{"383", "Підривник сліз", "Splits all of Isaac's tears currently on screen in a circle of 6 tears"},
	{"384", "Крихітка Гарді", "{{Chargeable}} Launches and bounces around the room with speed based on charge amount#Deals 5-90 contact damage per second depending on speed"},
	{"385", "Жебрало", "Picks up nearby coins#Levels up after getting 6, 12, and 24 coins#LVL2: Chance to spawn item after room clears#LVL3: Fires tears that can drop coins on hit#LVL4: Chases enemies, occasionally dropping bombs, can spawn item on coin pickup"},
	{"386", "D12", "Rerolls any obstacle into another random obstacle (e.g. poop, pots, TNT, red poop, stone blocks etc.)"},
	{"387", "Кадило", "Familiar surrounded by a huge aura of light that slows down enemies and projectiles in it"},
	{"388", "Жебрак-ключник", "Picks up keys and spawns random chests"},
	{"389", "Мішечок для рун", "{{Rune}} Drops a random rune every 5-6 rooms"},
	{"390", "Серафим", "Fires Sacred Heart tears#Deals 10 damage per shot"},
	{"391", "Зрадник", "{{Charm}} Taking damage charms all enemies in the room"},
	{"392", "Зодіак", "Grants a random zodiac item effect every floor"},
	{"393", "Зміїний поцілунок", "{{Poison}} 15% chance to shoot poison tears#{{Poison}} Poison enemies on contact#{{BlackHeart}} Poisoned enemies have a chance to drop a Black Heart on death"},
	{"394", "Мічений", "Isaac automatically fires tears at a movable red target on the ground#↑ {{Tears}} +0.7 Tears up#↑ {{Range}} +3.15 Range up#↑ +0.3 Tear Height"},
	{"395", "Технологія X", "{{Chargeable}} Isaac's tears are replaced by a chargeable laser ring#Ring size increases with charge time"},
	{"396", "Наскрізне лезо", "Creates up to two portals to travel between#Can be placed in different rooms"},
	{"397", "Промінь тягача", "Isaac's tears always travel along a beam of light in front of him#↑ {{Tears}} +0.5 Tears up#↑ {{Range}} +5.25 Range up#↑ {{Shotspeed}} +0.16 Shot Speed up#↑ +0.5 Tear Height"},
	{"398", "Божественна плоть", "Tears can shrink enemies#Shrunken enemies can be crushed and killed by walking over them"},
	{"399", "Паща Порожнечі", "↑ {{Damage}} +1 Damage up#{{Chargeable}} Firing tears for 3 seconds and releasing the fire button creates a black brimstone ring around Isaac#{{BlackHeart}} Enemies killed by the black ring have a chance to drop Black Hearts"},
	{"400", "Спис Долі", "Isaac holds a spear in front of him#The spear deals twice his damage and can fear enemies on contact"},
	{"401", "Вибухівчик", "25% chance to shoot sticky bomb tears#Sticky bomb tears do not deal damage on hit and explode after a few seconds"},
	{"402", "Хаос", "All items are chosen from random item pools#Spawns 1-6 random pickups"},
	{"403", "Робо-павук", "Displays tear damage and health bars of all enemies#Inflicts random status effects to enemies on contact#Randomly drops batteries"},
	{"404", "Малюк Пердун", "Blocks projectiles#When hit, 10% chance to fart and charm, poison or knockback enemies"},
	{"405", "Ігровий баг", "Bounces around the room#Deals 120 damage per second and applies random status effects to enemies on contact"},
	{"406", "D8", "Multiplies Isaac's damage, tears, range and speed stats by between 0.5x and 2x#The multipliers are rerolled each use"},
	{"407", "Чистота", "↑ Boosts one of Isaac's stats depending on the color of the aura#Taking damage removes the effect, and gives Isaac a new effect in the next room#{{ColorRed}}Red{{CR}} = {{Damage}} +4 Damage#{{ColorBlue}}Blue{{CR}} = {{Tears}} -4 Tear Delay#{{ColorYellow}}Yellow{{CR}} = {{Speed}} +0.5 Speed up#{{ColorOrange}}Orange{{CR}} = {{Range}} +7.5 Range up, +1 Tear Height"},
	{"408", "Атаме", "Taking damage creates a black brimstone ring around Isaac#{{BlackHeart}} Enemies killed by the ring have a chance to drop a Black Heart"},
	{"409", "Пуста посудина", "{{BlackHeart}} +2 Black Hearts#{{Blank}} When Isaac has no Red Hearts:#Grants flight#Every 40 seconds while in a hostile room, gain a shield for 10 seconds"},
	{"410", "Зле око", "3.33% chance to shoot an eye#The eye moves in a straight line and fires tears in the same direction as Isaac"},
	{"411", "Ненаситна кров", "↑ {{Damage}} +0.5 Damage up for each enemy killed in the room#Caps at +5 Damage up after 10 kills"},
	{"412", "Демонічне зачаття", "Taking damage 15 times spawns a permanent demon familiar#After two familiars, it takes 30 instead of 15#Caps at 4 familiars"},
	{"413", "Непорочне зачаття", "Picking up 15 hearts spawns a permanent angelic familiar#Caps at 5 familiars#If all familiars have been granted, spawns a Soul Heart instead"},
	{"414", "Більше можливостей", "{{TreasureRoom}} Allows Isaac to choose between 2 items in treasure rooms"},
	{"415", "Світлова корона", "{{SoulHeart}} +2 Soul Hearts#{{Blank}} If Isaac has no damaged Red Heart containers:#↑ {{Damage}} +100% Damage up#↑ {{Range}} +5.25 Range up#↑ +0.5 Tear Height#↓ {{Shotspeed}} -0.3 Shot Speed down#{{Blank}}#Taking any damage removes the effect for the current room"},
	{"416", "Глибокі кишені", "Allows Isaac to carry two cards/pills/runes"},
	{"417", "Сукуб", "Bounces around the room surrounded by a damaging aura that deals 129% of Isaac's damage every second#↑ {{Damage}} +50% Damage while standing in the aura"},
	{"418", "Фруктовий пиріг", "Each one of Isaac's tears gets a different effect"},
	{"419", "Телепорт 2.0", "Teleports Isaac to a room that has not been cleared yet#Hierarchy: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}{{BossRushRoom}}>{{IsaacsRoom}}{{BarrenRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}>{{ErrorRoom}}"},
	{"420", "Чорний порошок", "Walking in a circle draws a pentagram on the floor, which deals 10 damage per tick"},
	{"421", "Квасоля", "{{Charm}} Charms and deals 5 damage to all enemies in close range"},
	{"422", "Сяйливий годинник", "Brings Isaac back to the previous room and reverses all actions done in the room the item was used in"},
	{"423", "Захисне коло", "Surrounds Isaac with a large halo that deals his damage on contact every second#Chance to reflect enemy projectiles"},
	{"424", "Голова-мішок", "Pickups have a 33% chance to be replaced with a sack#Spawns a sack"},
	{"425", "Нічник", "Spawns a slowing cone of light in front of Isaac"},
	{"426", "Закоханий фанат", "Mimics Isaac's exact movement on a 3 second delay#Deals 30 contact damage per second"},
	{"427", "Шахтарська вибухівка", "Spawns a pushable TNT barrel#Using the item a second time in the same room remotely detonates the barrel"},
	{"428", "Піжама", "{{SoulHeart}} +4 Soul Hearts#Fully heals red hearts"},
	{"429", "Голова Хранителя", "{{Coin}} Hitting an enemy with a tear has a 5% chance to drop a Penny"},
	{"430", "Татусь Муха", "Mimics Isaac's movement on a 1 second delay#Fires tears at nearby enemies that deal Isaac's damage"},
	{"431", "Міжвимірне дитя", "Mimics Isaac's movement on a 2 second delay#Tears that pass through it are doubled and gain a speed boost"},
	{"432", "Блискучі бомби", "{{Bomb}} +5 bombs#Isaac's bombs have a 25% chance to drop a random pickup and a 15% chance to charm enemies when they explode"},
	{"433", "Моя тінь", "Taking damage fears all enemies in the room and spawns a friendly black charger#The charger deals 5 damage per second"},
	{"434", "Банка з мухами", "Killing an enemy adds a blue fly to the Jar, up to 20 flies#Using the item releases all the flies"},
	{"435", "Крихітка Локі", "Shoots 4 tears in a cross pattern#Deals 3.5 damage per shot"},
	{"436", "Молоко!", "{{Tears}} Taking damage grants a Tears up for the duration of the room"},
	{"437", "D7", "Restarts a room and respawns all enemies#Can be used to get multiple room clear rewards from a single room#If used after a Greed fight, rerolls the room into a normal Shop/Secret Room"},
	{"438", "Пипка", "{{SoulHeart}} +1 Soul Heart#↑ {{Tears}} +0.75 Tears up#↑ Size down"},
	{"439", "Матусина коробка", "{{Trinket}} Spawns a random trinket#While held, doubles trinket effects#↑ {{Luck}} +1 Luck while held"},
	{"440", "Нирковий камінь", "Isaac occasionally stops firing and charges an attack that releases a burst of tears and a kidney stone#↓ -0.2 Speed down#↓ -17 Range down#↑ +2 Tear Height"},
	{"441", "Мегазаряд", "Fires a huge Mega Satan laser for 15 seconds#The laser persists between rooms and floors"},
	{"442", "Корона Темного Принца", "{{Blank}} While at 1 full Red Heart:#↑ {{Range}} +1.5 Range up#↑ {{Tears}} +0.75 Tears up#↑ {{Shotspeed}} +0.2 Shot Speed up#↑ +1 Tear Height#Does not work on characters without Red Hearts"}, -- Dark Princes Crown (apostrophe added to the name in Repentance)
	{"443", "Яблуко!", "Isaac sometimes fires razor blades which deal 400% damage#{{Luck}} 100% chance at 14 Luck#↑ {{Tears}} +0.3 Tears up"},
	{"444", "Графітовий олівець", "Isaac fires a cluster of tears every 15 tears#Tears in the cluster deal double damage"},
	{"445", "Собачий зуб", "↑ {{Damage}} +0.3 Damage up#↑ {{Speed}} +0.1 Speed up#{{SecretRoom}} A wolf howls in rooms adjacent to a Secret/Super Secret Room#{{LadderRoom}} A dog barks in rooms with a crawlspace under a rock"},
	{"446", "Мертвий зуб", "While firing, Isaac is surrounded by a green aura that poisons enemies"},
	{"447", "Довгий біб", "Firing without pause for 7.5 seconds spawns a poop cloud#The cloud deals Isaac's damage 5 times a second#The cloud lasts 15 seconds and can be moved by shooting it"},
	{"448", "Кусок скла", "Upon taking damage:#{{Heart}} 25% chance to drop a Red Heart#{{Collectible214}} 10% chance to get ↑ +5 Range and leave a trail of blood creep for the current room"},
	{"449", "Металева пластина", "{{SoulHeart}} +1 Soul Heart#{{Confusion}} Enemy bullets have a 25% chance to be reflected as concussive tears"},
	{"450", "Око Жадібності", "Every 20 tears, Isaac shoots a coin tear that deals double damage#Enemies hit with the coin turn into gold#Killing a gold enemy drops 1-4 coins#Firing a coin tear costs 1 coin"},
	{"451", "Сукно таро", "{{Card}} Drops a card#{{Card}} Card effects are doubled"},
	{"452", "Варикозні вени", "Taking damage fires 10 tears in a circle around Isaac#The tears deal Isaac's damage + 25"},
	{"453", "Перелом", "Tears shatter into 1-3 small bone shards upon hitting anything#↑ +1.5 Range up#↑ +1 Tear Height"},
	{"454", "Полідактилія", "Allows Isaac to carry 2 cards, runes or pills#Spawns a card, pill or rune on pickup"},
	{"455", "Татусева втрачена монета", "↑ {{Range}} +1.5 Range up#↑ +1 Tear Height#Spawns a lucky penny"},
	{"456", "Опівнічний перекус", "↑ {{Heart}} +1 Health up"},
	{"457", "Яйцеголовий", "{{SoulHeart}} +1 Soul Heart#20% chance to negate damage taken"},
	{"458", "Пупок", "{{Trinket}} Allows Isaac to carry 2 trinkets#{{Trinket}} Spawns a random trinket on pickup"},
	{"459", "Синусит", "20% chance to shoot a sticky booger#Boogers deal Isaac's damage once a second and stick for 60 seconds"},
	{"460", "Глаукома", "{{Confusion}} 5% chance to shoot concussive tears#Makes the screen slightly darker"},
	{"461", "Паразитоїд", "15% chance to shoot egg sacks#{{Luck}} 50% chance at 5 Luck#Egg sacks spawn slowing creep and a blue spider or fly on hit"},
	{"462", "Око Беліала", "↑ {{Range}} +1.5 Range up#↑ +1 Tear Height#Piercing tears#Hitting an enemy makes the tear homing and doubles its damage"},
	{"463", "Сульфатна кислота", "↑ {{Damage}} +0.3 Damage up#Isaac's tears can destroy rocks and open doors"},
	{"464", "Гліф рівноваги", "{{SoulHeart}} +2 Soul Hearts#Champion enemies drop whatever pickup Isaac needs the most"},
	{"465", "Аналоговий джойстик", "↑ {{Tears}} +0.3 Tears up#Allows Isaac to fire tears in any direction"},
	{"466", "Зараза", "{{Poison}} The first enemy killed in a room explodes and poison all nearby enemies"},
	{"467", "Пальчик!", "{{Damage}} Constantly deals 10% of Isaac's damage in the direction it points"},
	{"468", "Тінь", "Follows Isaac's movement on a 1 second delay#Deals 30 contact damage per second#After it deals 600 damage, it is absorbed by Isaac, increasing his contact damage"},
	{"469", "Депресія", "Leaves a trail of creep#The creep deals 6 damage per second#Enemies that touch the cloud can be hit by a holy light beam"},
	{"470", "Мовчун", "Bounces around the room#Deals contact damage#Stops moving when Isaac shoots#Blocks projectiles when stopped"},
	{"471", "Крихітка Монстро", "{{Chargeable}} Charges a shotgun attack similar to {{Collectible229}} Monstro's Lung#Each tear deals 3.5 damage"},
	{"472", "Дитя Король", "Other familiars follow it#Stops moving when Isaac shoots#Teleports back to Isaac when he stops shooting"},
	{"473", "Великий Чаббі", "Very slowly charges forwards#Blocks shots#Deals 40.5 contact damage per second"},
	{"474", "Мигдалик", "Blocks enemy projectiles"},
	{"475", "План C", "{{Warning}} SINGLE USE {{Warning}}#Deals 9,999,999 damage to all enemies#Kills Isaac 3 seconds later"},
	{"476", "D1", "Duplicates 1 random pickup in the current room"},
	{"477", "Порожнеча", "Consumes all pedestal items in the room#Active items: Their effects activate, and will activate with every future use of Void#↑ Passive items: Grant two random stats up"},
	{"478", "Пауза", "Freezes all enemies in the room until Isaac shoots#Touching a frozen enemy still deals damage to Isaac#Enemies unfreeze after 30 seconds"},
	{"479", "Плавильня", "{{Trinket}} Consumes Isaac's held trinkets and grants their effects permanently#Increases the spawn rate of trinkets"},
	{"480", "Компост", "Converts pickups into blue flies or spiders#Doubles all blue flies and spiders#Spawns 1 blue fly or spider if Isaac has none"},
	{"481", "Датамайнер", "↑ Random stat up#↓ Random stat down#Random tear effect for the room#Corrupts all sprites and music in the room"},
	{"482", "Клікер", "Changes your character to a random character#Removes the last item collected"},
	{"483", "Мама Мега!", "{{Warning}} SINGLE USE {{Warning}}#Affects the whole floor#Explodes all objects#Deals 200 damage to all enemies#Opens the door to Boss Rush, Hush and all secret rooms#Having a Golden Bomb when using the item consumes it and allows for another use of Mama Mega"},
	{"484", "Стривай, що?", "Upon use, pushes enemies away and spawns a rock wave around Isaac#The rock wave can open rooms and break rocks"},
	{"485", "Зігнутий пенні", "50% chance to double all items, consumables and chests in room#50% chance to remove items / pickups in room and spawn 1 coin"},
	{"486", "Тупе лезо", "Hurts Isaac without removing health#Triggers any on-hit item effects"},
	{"487", "Картоплечистка", "Removes one Red Heart Container and grants: #↑ {{Damage}} +0.2 Damage up#{{Collectible73}} A Cube of Meat#↑ {{Range}} +5 Range and leave a trail of blood creep for the current room"},
	{"488", "Метроном", "Grants a random item effect for the current room"},
	{"489", "D Безмежність", "Triggers a random dice effect each use"},
	{"490", "Едемова душа", "{{Warning}} SINGLE USE {{Warning}}#Spawns 2 random items depending on the current room's item pool#Starts with no charges"},
	{"491", "Кислотне дитя", "{{Pill}} Drops a random pill every 3 rooms#{{Poison}} Using a pill poisons all enemies in the room"},
	{"492", "ХЕЙ, СЛУХАЙ!", "↑ {{Luck}} +1 Luck up#Highlights the location of {{SecretRoom}} secret rooms, tinted rocks and crawlspaces"},
	{"493", "Адреналін", "For every empty heart container:#↑ +0.2 Damage up"},
	{"494", "Драбина Якова", "Tears spawn 1-2 sparks of electricity on impact#Sparks deal half of Isaac's damage"},
	{"495", "Перець-привид", "Chance to shoot a red flame that blocks enemy shots and deals contact damage#The flame disappears after dealing damage or blocking shots 5 times"},
	{"496", "Евтаназія", "3.33% chance to shoot a needle#{{Luck}} 100% chance at 15 Luck#Needles kill normal enemies instantly, bursting them into 10 tears#Needles deal 3x damage against bosses"},
	{"497", "Камуфляжні труси", "Entering a room confuses all enemies until Isaac starts shooting"},
	{"498", "Подвійність", "{{AngelDevilChance}} Spawns both an Angel and Devil room if either would have spawned#Entering one makes the other disappear"},
	{"499", "Євхаристія", "{{AngelChance}} 100% chance for Angel Rooms to spawn"},
	{"500", "Мішечок монет", "Spawns a sack every 5-6 rooms"},
	{"501", "Стравохід Жадібності", "Gain 1 Heart Container for every 25 coins gained after getting Greed's Gullet#{{Player14}} Keeper can gain additional Coin Hearts"},
	{"502", "Гігантський прищ", "Firing occasionally shoots a white creep tear that deals double damage#Taking damage shoots a white creep tear"},
	{"503", "Маленький ріг", "5% chance to shoot tears that instantly kill enemies#Isaac deals 3.5 contact damage"},
	{"504", "Коричневий самородок", "Spawns a fly turret that shoots at enemies#Each shot deals 2 damage"},
	{"505", "Покемончик", "Entering a hostile room has a chance to spawn a charmed enemy"},
	{"506", "І ти, Бруте?", "Hitting an enemy in the back deals double damage and causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds"},
	{"507", "Гостра соломинка", "{{Damage}} Deals Isaac's damage + 10% of the enemy's max health to all enemies#{{HalfHeart}} Dealing damage with the Straw can drop half hearts#{{HalfSoulHeart}} Having no red HP drops Soul Hearts instead"},
	{"508", "Матусина бритва", "Orbital that causes bleeding, which deals 10% damage of the enemy's max health every 5 seconds#Deals 3x Isaac's damage on contact per second#Does not block shots"},
	{"509", "Криваве око", "Orbital that shoots a tear in a random direction every 2 seconds#Deals 3.5 damage per tear#Deals 30 contact damage per second#Does not block shots"},
	{"510", "Несамовитий", "Spawns a friendly delirium version of a boss for the current room"},
	{"511", "Розлючена муха", "Orbits a random enemy until that enemy dies#Deals 30 contact damage per second to other enemies"},
	{"512", "Чорна діра", "Throwable black hole, which sucks in everything#Deals 0.4 damage every tick#Destroys nearby rocks#Lasts 6 seconds"},
	{"513", "Бозо", "↑ +0.1 Damage up#+1 Soul Heart#Randomly charms/fears enemies#Taking damage has a random chance to spawn a rainbow poop"},
	{"514", "Зламаний модем", "Causes some enemies and projectiles to briefly freeze at random intervals#25% chance to double room clear drops"},
	{"515", "Загадковий подарунок", "{{Warning}} SINGLE USE {{Warning}}#Spawns a random item from the current room's item pool#Chance to spawn Lump of Coal or The Poop instead"},
	{"516", "Зрошувач", "Spawns a Sprinkler that shoots the same tears as Isaac in a circle around itself"},
	{"517", "Швидкі бомби", "{{Bomb}} +7 Bombs#Removes the delay between bomb placements"},
	{"518", "Друзяка в коробці", "Familiar which looks like a random coop Baby#Has random tear effects#Effects change every floor"},
	{"519", "Крихітка Делліріум", "Transforms into a random familiar every 10 seconds"},
	{"520", "Кабель-перемичка", "Killing 15 enemies adds 1 charge to the active item"},
	{"521", "Купон", "Makes one random item in the {{Shop}} Shop or {{DevilRoom}} Devil Room free#Holding the item guarantees one Shop item is on sale"},
	{"522", "Телекінез", "Stops all enemy projectiles that come close to Isaac for 3 seconds and throws them away from him afterwards"},
	{"523", "Коробка для перенесень", "Stores all pickups and items from the current room#Using the item again drops everything back on the floor#Allows Isaac to move things between rooms"},
	{"524", "Технологія Нуль", "Isaac's tears are connected with beams of electricity#The beams deal the same damage as Isaac"},
	{"525", "Проказа", "Taking damage spawns a projectile blocking orbital#Caps at 3 orbitals#Orbitals are destroyed if they take too much damage"},
	{"526", "7 Печаток", "Spawns a small horseman familiar that spawns locusts#The horseman and its locust changes every 10 seconds"},
	{"527", "Містер Я!", "Displays a movable cursor for a few seconds, then summons a ghost that will, depending on the cursor position:#Open doors or chests#Fetch an item#50% chance to steal from the shop / Devil#Attack an enemy until it dies#Explode walls, rocks, shopkeepers, angel statues, machines, beggars"},
	{"528", "Янгельська призма", "Orbital prism#Friendly tears hitting it split into 4"},
	{"529", "Хлюп!", "Isaac's tears bounce off each other and disappear when they stop moving"},
	{"530", "Список смерті", "Killing enemies in the order dictated by the mark {{DeathMark}} above them grants a random pickup or stat increase"},
	{"531", "Гемолакрія", "Isaac's tears fly in an arc and burst into smaller tears on impact#↓ Tears down#↑ 31% Damage up"},
	{"532", "Сльозотеча", "Isaac's tears progressively slow down, stop, then explode into 8 smaller tears#Tears can merge and become bigger"},
	{"533", "Трисвяте", "Replaces Isaac's tears with piercing beams of light#The beams deal 33% damage but can hit enemies multiple times"},
	{"534", "Рюкзак", "Allows Isaac to hold 2 active items#The items can be swapped using the Drop button ({{ButtonRT}})"},
	{"535", "Ковдра", "{{SoulHeart}} +1 Soul Heart#{{Heart}} Heals 1 Red Heart#{{Collectible313}} Entering a boss room grants a {{HolyMantleSmall}} Holy Mantle shield"},
	{"536", "Вівтар для жертвопринесень", "{{Warning}} SINGLE USE {{Warning}}#Sacrifices up to 2 familiars and spawns a Devil item for each sacrifice#Turns blue spiders/flies into coins"},
	{"537", "Крихітка Ригачка", "{{Pill}} Spawns a random pill on pickup#Fires a line of creep#The type of creep changes with each pill use"},
	{"538", "Камінці", "{{Trinket}} Spawns 3 random trinkets#{{Collectible479}} Taking damage can remove Isaac's held trinket and grant its effects permanently"},
	{"539", "Загадкове яйце", "Taking damage spawns a charmed enemy#Spawns stronger friends the more rooms are cleared without taking damage"},
	{"540", "Плаский камінь", "Isaac's tears bounce off the floor and cause splash damage on every bounce"},
	{"541", "Кістковий мозок", "{{EmptyBoneHeart}} +1 Bone Heart#{{Heart}} Spawns 3 Red Hearts"},
	{"542", "Зміщене ребро", "Orbital#Reflects enemy projectiles"},
	{"543", "Свята земля", "Taking damage spawns a white poop#While inside the poop's aura:#↑ {{Tears}} -50% Tear Delay#Chance to block damage"},
	{"544", "Загострене ребро", "Levitates in front of Isaac#Deals Isaac's damage 6 times per second"},
	{"545", "Книга Мертвих", "Spawns a bone orbital or charmed bony per enemy killed in the room"},
	{"546", "Татусеве кільце", "Grants an aura that freezes enemies in place"},
	{"547", "Документи про розлучення", "{{EmptyBoneHeart}} +1 Bone Heart#↑ {{Tears}} +0.7 Tears up#{{Trinket21}} Spawns the Mysterious Paper trinket"},
	{"548", "Щелепна кістка", "Boomerang-like familiar#Deals 7 contact damage#Can grab and bring back pickups"},
	{"549", "Крихкі кістки", "{{EmptyBoneHeart}} Replaces all of Isaac's Red Heart containers with 6 empty Bone Hearts#Upon losing a Bone Heart:#Fires 8 bone tears in all directions#↑ {{Tears}} +0.5 permanent Tears up"},
	{"550", "Зламана лопата", "Mom's Foot constantly tries to stomp Isaac#Using the item stops the stomping for the room#{{Warning}} (Try to beat Boss Rush with it!)"},
	{"551", "Зламана лопата", "Completes Mom's Shovel#{{Warning}} Use the shovel on the hill of dirt in the \"Dark Room\""},
	{"552", "Матусина лопата", "Spawns a trapdoor to the next floor#10% chance for {{LadderRoom}}crawlspace trapdoor#{{Warning}} Use the shovel on the hill of dirt in the \"Dark Room\""},
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "Проковтнутий пенні", "{{Coin}} Taking damage spawns 1 coin"},
	{"2", "Скам'яніла какашка", "50% chance to get drops from poop"},
	{"3", "AAA Батарейка", "-1 charge needed for active items"},
	{"4", "Зламаний пульт", "{{Collectible44}} Using an active item teleports Isaac to a random room"},
	{"5", "Фіолетове серце", "2x chance for champion enemies"},
	{"6", "Зламаний магніт", "Attracts coins to Isaac"},
	{"7", "Намистина з вервиці", "{{AngelChance}} 50% higher Angel Room chance#{{Collectible33}} Higher chance to find The Bible in {{Shop}} Shops and {{Library}} Libraries"},
	{"8", "Картридж", "{{Collectible93}} Taking damage has a 5% chance to trigger the Gamekid effect"},
	{"9", "Пульсуючий черв", "Isaac's tears pulsate#Affects tear hitbox"},
	{"10", "Хвилястий черв", "Isaac's tears move in waves#↑ {{Tears}} +0.3 Tears up"},
	{"11", "Кільчастий черв", "Isaac's tears move in spirals with high speed"},
	{"12", "Плаский черв", "50% wider tears#Increases knockback"},
	{"13", "Кредит", "{{Shop}} Allows Isaac to take 1 shop item for free"},
	{"14", "Мозоль", "Grants immunity to creep and floor spikes"},
	{"15", "Щасливий камінь", "{{Coin}} Destroying rocks spawns coins"},
	{"16", "Матусин ніготь", "Mom's Foot stomps a random spot in the room every 60 seconds"},
	{"17", "Чорна помада", "{{BlackHeart}} +10% chance for random Soul Hearts to spawn as Black Hearts"}, -- base chance is +5%
	{"18", "Біблійний трактат", "{{EternalHeart}} +3% chance for Eternal Hearts"}, -- base chance is 1.667%
	{"19", "Скріпка", "Gold Chests {{GoldenChest}} can be opened for free"},
	{"20", "Мавпяча лапа", "{{BlackHeart}} Spawns 1 Black Heart when Isaac's health gets down to half a heart#{{Warning}} Disappears after spawning 3 black hearts"},
	{"21", "Загадковий листок", "{{Blank}} Randomly grants the effect of: #{{Collectible327}} The Polaroid#{{Collectible328}} The Negative#{{Trinket48}} A Missing Page#{{Trinket23}} Missing Poster"},
	{"22", "Хвіст демона", "{{Heart}} Decreases spawn rate of hearts to 20%#{{BlackHeart}} All Heart pickups turn into Black Hearts#{{Key}} Increases the drop chance of keys"},
	{"23", "Плакат зниклого безвісти", "{{Player10}} Respawn as The Lost on death#Dying in a {{SacrificeRoom}} Sacrifice Room while holding this trinket unlocks The Lost"},
	{"24", "Дуповий пенні", "{{Coin}} 20% higher chance for coins to spawn from poop#Picking up coins makes Isaac fart"},
	{"25", "Загадкова цукерка", "Isaac farts or spawns poop every 30 seconds"},
	{"26", "Гаковий черв", "Isaac's tears move in angular patterns#↑ {{Range}} +10 Range"},
	{"27", "Батоговий черв", "↑ {{Shotspeed}} +0.5 Shot Speed up"},
	{"28", "Зламаний хрест", "{{Player4}} 22% chance to respawn as ??? (Blue Baby) on death"},
	{"29", "Голова риби", "Taking damage spawns 1 blue fly"},
	{"30", "Кон'юнктивіт", "{{Poison}} 10% chance to shoot poison tears"},
	{"31", "Канцелярська кнопка", "10% chance to shoot piercing spectral tears"},
	{"32", "Шапка свободи", "25% chance for a random mushroom effect per room#Can reveal special rooms on the minimap"},
	{"33", "Пуповина", "Grants {{Collectible100}} Little Steven for the current room when Isaac's health is reduced to half a heart"},
	{"34", "Дитяче серце", "{{Heart}} 10% chance for the room clear reward to be a random heart#Chance for a bonus heart from chests, tinted rocks and destroyed machines"},
	{"35", "Загнутий ріг", "↑ {{Damage}} +2 Damage up"},
	{"36", "Іржавий ключ", "{{Key}} 10% chance for the room clear reward to be a key#{{Key}} Chance for a bonus key from chests, tinted rocks and destroyed machines"},
	{"37", "Козляча ратиця", "↑ {{Speed}} +0.15 Speed up"},
	{"38", "Матусина перлина", "+10% chance for heart drops to be {{SoulHeart}} Soul Hearts, {{BlackHeart}} Black Hearts or {{EmptyBoneHeart}} Bone Hearts"}, -- base chance is 10%
	{"39", "Рак", "↑ {{Tears}} -2 Tear Delay"},
	{"40", "Червона латка", "{{Damage}} Taking damage has a 20% chance to grant +1.8 Damage up#{{Luck}} 100% chance at 8 Luck#{{Timer}} Effect lasts for the current room"},
	{"41", "Сірник", "{{Bomb}} 10% chance for the room clear reward to be a bomb#{{Bomb}} Chance for a bonus bomb from chests, tinted rocks and destroyed machines#{{Warning}} Removes {{Trinket53}}Tick"},
	{"42", "Щасливий палець", "↑ {{Luck}} +1 Luck up#+8% room clear reward chance#Extra pickups from chests, tinted rocks, and destroyed machines"},
	{"43", "Проклятий череп", "When damaged down to half a heart or less, Isaac is teleported to a random room"},
	{"44", "Захисний ковпачок", "{{Pill}} 10% chance for the room clear reward to be a pill#{{Pill}} Chance for a bonus pill from chests, tinted rocks and destroyed machines"},
	{"45", "Піковий туз", "{{Card}} 10% chance for the room clear reward to be a card#{{Card}} Chance for a bonus card from chests, tinted rocks and destroyed machines"},
	{"46", "Ісаакова виделка", "{{HalfHeart}} Clearing a room has a 10% chance to heal half a heart"},
	{"47", "", "<Item does not exist>"},
	{"48", "Загублена сторінка", "Taking damage has a 5% chance to deal 40 damage to all enemies in the room"},
	{"49", "Кривавий пенні", "{{HalfHeart}} Picking up a coin has a 50% chance to drop half a heart"},
	{"50", "Спалений пенні", "{{Bomb}} Picking up a coin has a 50% chance to drop a bomb"},
	{"51", "Плаский пенні", "{{Key}} Picking up a coin has a 50% chance to drop a key"},
	{"52", "Фальшивий пенні", "{{Coin}} Picking up a coin has a 50% chance to add another coin to the counter"},
	{"53", "Кліщ", "-15% boss health#{{BossRoom}} Heals 1 Red Heart when entering a Boss Room#{{Warning}} Once picked up, it can't be removed#Only removeable with {{Trinket41}} Match Stick or gulping"},
	{"54", "Голова Ісаака", "Familiar with piercing tears#Deals 3.5 damage per tear"},
	{"55", "Віра Меггі", "{{EternalHeart}} Entering a new floor grants +1 Eternal Heart"},
	{"56", "Язик Юди", "{{DevilRoom}} Reduces all Devil Deal prices to 1 heart container#Doesn't reduce 3 Soul Heart prices"},
	{"57", "Душа ???", "Familiar that bounces around the room#Shoots in the same direction as Isaac#Deals 3.5 damage per tear"},
	{"58", "Пасмо волосся Самсона", "{{Damage}} Killing an enemy has a 1/15 chance to grant +0.5 Damage up#{{Luck}} 100% chance at 10 Luck#{{Timer}} Effect lasts for the current room"},
	{"59", "Око Каїна", "Entering a new floor has a 25% chance to reveal map icons#100% chance at 3 Luck"},
	{"60", "Лапка пташки Єви", "{{Collectible117}} Killing an enemy has a 5% chance to spawn a Dead Bird#{{Luck}} 100% chance at 8 Luck"},
	{"61", "Ліва рука", "Turns all chests into red chests"},
	{"62", "Блискучий камінь", "Crawlspace rocks and tinted rocks blink every 10 seconds"},
	{"63", "Безпечні ножиці", "Turns troll bombs into bomb pickups"},
	{"64", "Веселковий черв", "Grants a random worm effect every 3 seconds"},
	{"65", "Стрічковий черв", "↑ {{Range}} x2 Range#↓ x0.5 Tear Height"},
	{"66", "Лінивий черв", "↓ {{Shotspeed}} -0.4 Shot Speed down#↑ {{Range}} +4 Range up#↑ +2 Tear Height"},
	{"67", "Розбитий ігровий кубик", "Taking damage has a 50% chance to trigger one of these effects:#{{Collectible105}} D6#{{Collectible406}} D8#{{Collectible386}} D12 #{{Collectible166}} D20"},
	{"68", "Супермагніт", "Isaac attracts pickups and enemies"},
	{"69", "Вицвілий полароїд", "Randomly camouflages Isaac#Confuses enemies"},
	{"70", "Воша", "Occasionally spawns a blue spider in hostile rooms"},
	{"71", "Сечовий міхур Боба", "Isaac's bombs leave damaging creep"},
	{"72", "Запасна батарейка", "6.66% chance for the room clear reward to be a battery#+10% chance for random pickups to be a battery#5% chance to add 1 charge to held active item when clearing a room"},
	{"73", "Вибуховий ковпачок", "10% chance for exploding bombs to drop a bomb pickup"},
	{"74", "Шукач", "Breaking a rock has a 0.5% chance to reveal a {{LadderRoom}} crawlspace"},
	{"75", "Помилка", "Grants a random trinket effect every room"},
	{"76", "Фішка для покеру", "↑ 50% chance for chests to spawn extra pickups#↓ 50% chance for chests to contain a single fly"},
	{"77", "Пухир", "Increases knockback"},
	{"78", "Друга рука", "Status effects applied to enemies last twice as long"},
	{"79", "Безіменна нескінченність", "Using a pill, card or rune has a 25% chance to drop a copy of that pill, card or rune"},
	{"80", "Чорна пір'їна", "↑ {{Damage}} +0.2 Damage up for each \"Evil up\" item held"},
	{"81", "Сліпа лють", "Invincibility frames after taking damage last twice as long"},
	{"82", "Золота підкова", "{{TreasureRoom}} Future Treasure Rooms have +15% chance to let Isaac choose between two items"},
	{"83", "Ключ до магазину", "{{Shop}} Lets Isaac open Shops for free"},
	{"84", "Ребро Жадібності", "5% more coins and fewer hearts from room clear rewards#Greed and Super Greed no longer appear in {{Shop}}Shops or {{SecretRoom}}Secret Rooms"},
	{"85", "Карма", "{{DonationMachine}} Using a Donation Machine can:#{{Heart}} Heal 1 heart#{{Coin}} Give 1 coin#{{Luck}} Grant +1 Luck up#{{Beggar}} Spawn a Beggar"},
	{"86", "Крихітна личинка", "Destroying poop spawns 1 blue fly"},
	{"87", "Матусин медальйон", "Using a key heals half a heart#Turns half hearts into full hearts"},
	{"88", "НІ!", "Prevents active items from spawning"},
	{"89", "Дитячий повідок", "Familiars stay closer to Isaac"},
	{"90", "Коричневий ковпачок", "Poop explodes for 100 damage when destroyed"},
	{"91", "Меконій", "33% chance for Black Poops to spawn#Destroying Black Poop has a 5% chance to spawn a Black Heart"},
	{"92", "Зламана корона", "↑ Stat increases are 33% more effective#↑ +0.2 Tears up#↑ -1 Tear Delay"},
	{"93", "Використаний підгузок", "15% chance per room for all Fly enemies to become friendly"},
	{"94", "Риб'ячий хвіст", "Doubles all Blue Fly / Spider spawns"},
	{"95", "Чорний зуб", "3% chance to shoot poison tooth tears"},
	{"96", "Черв'як Уроборос", "Isaac's tears move quickly in a spiral pattern#Spectral tears#↑ {{Range}} +4 Range up#↑ +2 Tear Height"},
	{"97", "Мигдалик", "Taking damage 12-20 times spawns a projectile blocking familiar#Caps at 2 Familiars"},
	{"98", "Ніс гобліна", "10% chance to shoot homing sticky tears#Boogers deal Isaac's damage once per second#Boogers stick for 60 seconds"},
	{"99", "Пострибунчик", "10% chance to shoot bouncing tears"},
	{"100", "Яскрава лампочка", "Holding a fully charged active item grants:#↑ {{Damage}} +0.5 Damage#↑ {{Speed}} +0.25 Speed#↑ {{Range}} +0.75 Range#↑ {{Tears}} +0.2 Tears#↑ {{Shotspeed}} +0.1 Shot speed#↑ {{Luck}} +1 Luck"},
	{"101", "Згасла лампочка", "Holding a completely uncharged active item grants:#↑ {{Damage}} +1.5 Damage#↑ {{Speed}} +0.5 Speed#↑ {{Range}} +1.5 Range#↑ {{Tears}} +0.4 Tears#↑ {{Shotspeed}} +0.3 Shot Speed#↑ {{Luck}} +2 Luck"},
	{"102", "Фрагментована карточка", "{{SecretRoom}} +1 extra Secret Room per floor while held"},
	{"103", "Рівність!", "{{Warning}} Turns single consumables into double consumables when Isaac's coin, key and bomb counts are equal"},
	{"104", "Кістка бажання", "2% chance to spawn a pedestal item when hit#Gets destroyed afterwards"},
	{"105", "Сумка з обідом", "{{Collectible22}} 2% chance to spawn Lunch when hit#Gets destroyed afterwards"},
	{"106", "Втрачений корок", "Increases the radius of friendly creep"},
	{"107", "Вороняче серце", "Taking damage depletes Red Hearts before Soul/Black Hearts#This red heart damage does not reduce Devil/Angel Room chances"},
	{"108", "Волоський горіх", "Getting hit by 1-9 explosions destroys the trinket and drops a key, coin, heart, and random trinket#Taking damage isn't required"},
	{"109", "Клейка стрічка", "Familiars are stuck in one spot and cannot move"},
	{"110", "Срібний долар", "{{Shop}} Shops appear in the Womb"},
	{"111", "Кривава корона", "{{TreasureRoom}} Treasure Rooms appear in the Womb"},
	{"112", "Плати, щоб виграти", "{{RestockMachine}} Restock boxes always spawn in {{TreasureRoom}} Treasure Rooms"},
	{"113", "Сарана Війни", "Entering a hostile room spawns an exploding attack fly #The fly deals twice Isaac's damage + explosion damage"},
	{"114", "Сарана Чуми", "Entering a hostile room spawns a poison attack fly#The fly deals twice Isaac's damage"},
	{"115", "Сарана Голоду", "Entering a hostile room spawns a slowing attack fly#The fly deals twice Isaac's damage"},
	{"116", "Сарана Смерті", "Entering a hostile room spawns an attack fly#The fly deals 4 times Isaac's damage"},
	{"117", "Сарана Завоювання", "Entering a hostile room spawns 1-4 attack flies#Each fly deals twice Isaac's damage"},
	{"118", "Кажаняче крило", "Killing an enemy has a 5% chance to grant flight for the current room"},
	{"119", "Стовбурова клітина", "Entering a new floor heals half a heart"},
	{"120", "Шпилька для волосся", "Entering an uncleared boss room fully recharges active items"},
	{"121", "Дерев'яний хрест", "{{Collectible313}} Negates the first damage taken on the floor"},
	{"122", "Масло!", "Using an active item drops it on a pedestal on the ground#Taking damage has a 2% chance to drop one of Isaac's passive items"},
	{"123", "Філігранне перо", "Angel bosses drop Angel items instead of Key Pieces"},
	{"124", "Підпірка для дверей", "The last door used stays open"},
	{"125", "Подовжувач", "Connects all familiars with beams of electricity#The beams deal 6 damage"},
	{"126", "Гнилий пенні", "Picking up a coin spawns a blue fly"},
	{"127", "Дитяча ложка", "Grants all familiars homing shots"},
	{"128", "Кістка з пальця", "{{EmptyBoneHeart}} Taking damage has a 2% chance to grant a Bone Heart"},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "0 - Дурень", "Телепортує персонажа до першої кімнати на поверсі"},
	{"2", "I - Чарівник", "Самонавідні сльози для поточної кімнати"},
	{"3", "II - Верховна жриця", "Матусина Нога чавить ворога#Якщо в кімнаті немає ворогів, Нога намагається попасти в персонажа"},
	{"4", "III - Імператриця", "Для поточної кімнати: #↑ {{Damage}} +2.35 Шкоду збільшено#↑ {{Speed}} +0.3 Швидкість збільшено"},
	{"5", "IV - Імператор", "{{BossRoom}} Телепортує персонажа в кімнату боса"},
	{"6", "V - Первосвященик", "{{SoulHeart}} Створює 2 серця Душі"},
	{"7", "VI - Коханці", "{{Heart}} Створює 2 червоні серця"},
	{"8", "VII - Колісниця", "Невразливість + контактна шкода на 6 секунд"},
	{"9", "VIII - Справедливість", "Створює 1 бомбу, 1 ключ, 1 монетку, 1 серце"},
	{"10", "IX - Відлюдник", "{{Shop}} Телепортує персонажа у Магазин"},
	{"11", "X - Колесо фортуни", "Створює {{Slotmachine}} Ігровий Автомат або {{FortuneTeller}} Автомат з Передбаченнями"},
	{"12", "XI - Сила", "Для поточної кімнати: #↑ {{Heart}} +1 Здоров'я збільшено#↑ {{Damage}} +0.3 Шкоду збільшено#↑ {{Damage}} +50% Шкоди#↑ {{Range}} +5.25 Дальність збільшено#↑ +0.5 Висота Польоту Сліз#↑ {{Speed}} +0.3 Швидкість збільшено"},
	{"13", "XII - Повішений", "Політ для поточної кімнати"},
	{"14", "XIII - Смерть", "Наносить 40 шкоди усім ворогам у кімнаті"},
	{"15", "XIV - Терпіння", "Створює {{DonationMachine}} Автомат Прийому Крові#{{GreedMode}} Створює Жебрака-Диявола у режимі Жадібності"},
	{"16", "XV - Диявол", "Для поточної кімнати: #↑ {{Damage}} +2 Шкоду збільшено"},
	{"17", "XVI - Башта", "Створює 6 Троль-бомб"},
	{"18", "XVII - Зірки", "{{TreasureRoom}} Телепортує персонажа у Скарбницю (Золоту кімнату)"},
	{"19", "XVIII - Місяць", "{{SecretRoom}} Телепортує персонажа в Секретну кімнату"},
	{"20", "XIX - Сонце", "Наносить 100 шкоди усім ворогам в кімнаті#Повне здоров'я#Відкриває карту цілого поверху"},
	{"21", "XX - Суд", "Створює Жебрака чи Жебрака-Диявола"},
	{"22", "XXI - Світ", "Відкриває карту поверху та типи кімнат"},
	{"23", "2 Трефа", "{{Bomb}} Подвоює кількість бомб в інвентарі персонажа"},
	{"24", "2 Бубни", "{{Coin}} Подвоює кількість монет в інвентарі персонажа"},
	{"25", "2 Піки", "{{Key}} Подвоює кількість ключів в інвентарі персонажа"},
	{"26", "2 Черви", "{{Heart}} Подвоює кількість червоних сердець#Має лише лікувальний ефект"},
	{"27", "Трефовий туз", "{{Bomb}} Перетворює усі розхідники в кімнаті на бомби"},
	{"28", "Бубновий туз", "{{Coin}} Перетворює усі розхідники в кімнаті на монети"},
	{"29", "Піковий туз", "{{Key}} Перетворює усі розхідники в кімнаті на ключі"},
	{"30", "Червовий туз", "{{Heart}} Перетворює усі розхідники в кімнаті на серця"},
	{"31", "Джокер", "{{AngelDevilChance}} Телепортує персонажа в кімнату Диявола чи Ангела"},
	{"32", "Хаґалаз", "Знищує усі камені в кімнаті"},
	{"33", "Джера", "Дублює усі розхідники в кімнаті"},
	{"34", "Еваз", "Створює люк на наступний поверх#8% шанс, що люк буде вести до {{LadderRoom}}Криївки"},
	{"35", "Даґаз", "{{SoulHeart}} +1 серце Душі#{{CurseCursed}} Знімає усі прокляття"},
	{"36", "Ансуз", "Відкриває карту поверху та типи кімнат"},
	{"37", "Пертро", "Реролить п'єдестальні предмети в кімнаті"},
	{"38", "Беркано", "Створює 3 синіх павуків та 3 синіх мух"},
	{"39", "Альґіз", "Ефект невразливості на 30 секунд"},
	{"40", "Порожня руна", "Triggers a random rune effect#25% chance to duplicate itself when used"},
	{"41", "Чорна руна", "Наносить 40 шкоди усім ворогам в кімнаті#Перетворює п'єдестальні предмети на випадкові покращення характеристик#Перетворює усі розхідники в кімнаті на синіх мух"},
	{"42", "Картка хаосу", "При використанні, персонаж метає картою в напрямку свого руху#Карта миттєво вбиває БУДЬ-ЯКОГО ворога (окрім Деліріума)"},
	{"43", "Кредитка", "Усі предмети та розіхдники в {{Shop}} Магазині чи {{DevilRoom}} Кімнаті Диявола стають безкоштовними"},
	{"44", "Картка з правилами", "Відображає \"корисні\" поради"},
	{"45", "Картка проти людства", "Повністю заповнює кімнату купками лайна"},
	{"46", "Король-самогубець", "Миттєво вбиває персонажа та створює 10 розхідників чи предметів на підлозі"},
	{"47", "Картка \"Вийди з в'язниці\"", "Відкриває всі двері в поточній кімнаті"},
	{"48", "? Картка", "Безкоштовно застосовує активний предмет персонажа"},
	{"49", "Уламок кубика", "Реролить усі п'єдестальні предмети та розхідники в кімнаті"},
	{"50", "Аварійний виклик", "Дві Матусині Руки падають та хапають ворогів"},
	{"51", "Свята картка", "{{Collectible313}} Ефект щита {{HolyMantleSmall}} Святої Мантії на 1 кімнату#(Одноразовий захист від шкоди)#25% шанс створити ще одну Святу Картку"},
	{"52", "Гігантський ріст", "↑ {{Damage}} +7 Шкоду збільшено#↑ {{Range}} +30 Дальність збільшено#Дозволяє персонажу топтати камені та інші перешкоди на шляху#Розмір збільшено#{{Timer}} Ефект триває 1 кімнату"},
	{"53", "Виклик Древніх", "{{Card}} Створює 3 випадкові карти"},
	{"54", "Епохальна прогулянка", "{{Slow}} Сповільнює ворогів#↑ {{Speed}} +0.5 Швидкість збільшено#↓ {{Shotspeed}} -1 Швидкість Стрільби зменшено#{{Timer}} Ефект триває 1 кімнату"},
}

---------- Pills ----------
EID.descriptions[languageCode].unidentifiedPill = "Невідома пігулка"

EID.descriptions[languageCode].pills={
	{"0", "Кепський газ", "Персонаж пукає й отруює ворогів поблизу"},
	{"1", "Кепський прихід", "Наносить 1 серце шкоди персонажу#Перетворюється на Повне Здоров'я, якщо у персонажа 1 серце чи менше"},
	{"2", "Сталеві яйця", "{{SoulHeart}} +2 серця Душі"},
	{"3", "Бомби - це ключі", "Кількість ключів і бомб в інвентарі міняються місцями"},
	{"4", "Вибухова діарея", "Персонаж швидко створює 5 підпалених бомб"},
	{"5", "Повне Здоров'я", "Повністю відновлює червоне здоров'я"},
	{"6", "Здоров'я Знижено", "↓ {{Heart}} Забирає 1 контейнер червоних сердець#Перетворюється на Здоров'я Підвищено, якщо у персонажа 0 чи 1 контейнер"},
	{"7", "Здоров'я Підвищено", "↑ {{EmptyHeart}} +1 пустий контейнер червоних сердець"},
	{"8", "Я знайшов пігулки", "Без ефекту"},
	{"9", "Пубертат", "Без ефекту#Випийте 3 такі пігулки, щоб перетворитися на Дорослого (+1 повний контейнер червоних сердець)"},
	{"10", "Гарненька мушка", "1 муха-орбіталь"},
	{"11", "Знижена Дальність", "↓ {{Range}} -2 Дальність зменшено"}, -- Range
	{"12", "Підвищена Дальність", "↑ {{Range}} +2.5 Дальність збільшено"},
	{"13", "Знижена Швидкість", "↓ {{Speed}} -0.12 Швидкість зменшено"}, -- Speed
	{"14", "Підвищена Швидкість", "↑ {{Speed}} +0.15 Швидкість збільшено"},
	{"15", "Знижений Темп Стрільби", "↓ {{Tears}} -0.28 Темп Стрільби зменшено"}, -- Tears
	{"16", "Підвищений Темп Стрільби", "↑ {{Tears}} +0.35 Темп Стрільби збільшено"},
	{"17", "Знижена Удача", "↓ {{Luck}} -1 Удачу зменшено"}, -- Luck
	{"18", "Підвищена Удача", "↑ {{Luck}} +1 Удачу збільшено"},
	{"19", "Теле-пігулки", "Телепортує персонажа у випадкову кімнату#{{ErrorRoom}} Маленький шанс потрапити у Я - ПОМИЛКА"},
	{"20", "48 годин енергії!", "Повністю перезаряджає активний предмет#Створює 1-2 батарейки"},
	{"21", "Гематемезис", "Спустошує усі, крім одного, контейнери червоних сердець#Створює 1-4 Червоні серця"},
	{"22", "Параліч", "Персонаж не може рухатись та стріляти протягом 2 секунд"},
	{"23", "Я бачу Вічність!", "{{SecretRoom}} Відкриває всі проходи до секретних кімнат на поверсі"},
	{"24", "Феромони", "{{Charm}} Зачаровує всіх ворогів в кімнаті"},
	{"25", "Амнезія", "{{CurseLost}} Приховує карту поверху"},
	{"26", "Лимонна вечірка", "Створює велику калюжу, яка наносить ворогам контактну шкоду"},
	{"27", "Ти чарівник?", "Персонаж протягом 30 секунд стріляє діагонально"},
	{"28", "Знеболювальне!", "Зменшує всю шкоду до половинки серця за удар у поточній кімнаті"},
	{"29", "Залежність!", "Підвищує усю шкоду до повного серця за удар у поточній кімнаті"},
	{"30", "Роз-слабся", "Персонаж какає під себе протягом 2 секунд"},
	{"31", "???", "{{CurseMaze}} Прокляття Лабіринту для поточного поверху"},
	{"32", "Ця зробить тебе більшим", "Збільшує розмір персонажа#Не впливає на його хітбокс"},
	{"33", "Ця зробить тебе меншим", "Зменшує розміри персонажа#Також зменшує його хітбокс"},
	{"34", "Інфікований!", "Створює 1 синього павука за кожну купку лайна в кімнаті"},
	{"35", "Інфікований?", "Створює 1 синього павука за кожного ворога в кімнаті#Створює 1-3 павуків, якщо в кімнаті немає ворогів"},
	{"36", "Пігулка сили!", "Короткостроково робить персонажа невразливим#{{Fear}} Лякає усіх ворогів у кімнаті#Злякані вороги отримують 40 контактної шкоди в секунду#{{HalfHeart}} Поїдання 2 ворогів відновлює половинку червоного серця"},
	{"37", "Ретро-погляд", "Графіка стає піксельною тричі за 30 секунд"},
	{"38", "Друзі до кінця!", "Створює 3 сині мухи"},
	{"39", "Проносне", "Створює калюжу слизької рідини у вас під ногами"},
	{"40", "Щось не так...", "{{Slow}} Створює калюжу сповільнювальної рідини"},
	{"41", "Я сонний...", "{{Slow}} Сповільнює всіх ворогів у кімнаті"},
	{"42", "Я збуджений!!", "Прискорює всіх ворогів у кімнаті"},
	{"43", "Ковть!", "{{Trinket}} Персонаж ковтає свій брелок та отримує його ефект перманентно"},
	{"44", "Тьху!", "{{Collectible149}} Вистрілює однією сльозою Іпекаку"},
	{"45", "Відчуття, ніби крокую сонячним сяйвом!", "Тимчасово робить персонажа невразливим"},
	{"46", "Вурп!", "Створює останню пігулку, випиту перед Вурп!"},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Наступна винагорода Кімнати Жертвопринесень]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "{{Coin}} 50% шанс на 1 монетку#{{Bomb}} 100% шанс на 1 бомбу, якщо ви на П1 і вбили боса менш ніж за 1 хвилину"}, -- П1 == B1
	{"2", "", "{{Coin}} 50% шанс на 1 монетку#{{Bomb}} 100% шанс на 1 бомбу, якщо ви на П1 і вбили боса менш ніж за 1 хвилину"}, -- п1 == b1
	{"3", "", "{{AngelChance}} 67% шанс збільшити ймовірність появи Кімнати Ангела"},
	{"4", "", "{{Chest}} 50% шанс на 1 випадкову скриню"},
	{"5", "", "{{Coin}} 33% шанс на 3 монетки#{{AngelChance}} 67% шанс збільшити ймовірність появи Кімнати Ангела"},
	{"6", "", "{{AngelRoom}} 33% шанс телепортуватися в Кімнату Ангела#{{DevilRoom}} Телепортує в Кімнату Диявола, якщо двері туди вже з'явилися на поточному поверсі#{{Chest}} 67% шанс на випадкову скриню"},
	{"7", "", "{{AngelRoom}} 33% шанс на 1 випадковий предмет з пулу Кімнати Ангела#{{SoulHeart}} 67% шанс на 1 серце Душі"},
	{"8", "", "100% шанс на 7 троль-бомб"},
	{"9", "", "100% шанс появи ангела \"Уріеля\""},
	{"10", "", "{{SoulHeart}} 50% шанс на 7 сердець Душі#{{Coin}} 50% шанс на 30 монет"},
	{"11", "", "100% шанс появи ангела \"Габріеля\""},
	{"12", "", "50% шанс телепортуватися на поверх \"Темна Кімната\""},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Ефекти Кімнати Кубиків]"

EID.descriptions[languageCode].dice={
	{"1", "", "Реролить усі предмети персонажа на випадкові предмети з пулу кімнат, у яких вони були отримані"},
	{"2", "", "Реролить усі розхідники в кімнаті"},
	{"3", "", "Реролить усі розхідники та брелки на поверсі#Не впливає на кімнати {{DevilRoom}}Диявола чи {{AngelRoom}}Ангела"},
	{"4", "", "Реролить усі п'єдестальні артефакти на поверсі#Не впливає на кімнати {{DevilRoom}}Диявола чи {{AngelRoom}}Ангела"},
	{"5", "", "Реролить та перезапускає поточний поверх"},
	{"6", "", "Реролить усі предмети персонажа#Реролить усі розіхдники, брелки та п'єдестальні предмети на поверсі"},
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Ґаппі",			-- 1
	"Веселий чувак",	-- 2
	"Вельзевул",		-- 3
	"З'єднаний",		-- 4
	"Обдовбаний",		-- 5
	"Так, Мамо?",		-- 6
	"От лайно..",		-- 7
	"Боб",				-- 8
	"Левіафан",			-- 9
	"Серафим",			-- 10
	"Супер-жебрак!",	-- 11
	"Книжковий черв'як",-- 12
	"Павуча дитинка",	-- 13
	"Дорослий",			-- 14
	"Топтань"			-- 15
}


---------- MISC ----------

EID.descriptions[languageCode].VoidText = "If absorbed, gain:"
-- {1} will become the number text (like "{1} Tears up" -> "+0.5 Tears up")
EID.descriptions[languageCode].VoidNames = {"{1} Speed up", "{1} Tears up", "{1} Damage up", "{1} Range up", "{1} Shot Speed up", "{1} Luck up"}

EID.descriptions[languageCode].CollectionPageInfo = "This item needs to be picked up for the collection page!"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Demo Object Name",
	DemoObjectTransformation = "Demo Transformation",
	DemoObjectText = "This text is in english#A very cool and long description to simulate linebreaks caused by EID textbox width!#{{Collectible4}} This is also a cool line#{{Heart}} This line loves you#{{AngelDevilChance}} This line can be your angel or your devil#\1 {{Damage}} +1 Stat Change up",
}

EID.descriptions[languageCode].HoldMapTitle = "Item Reminder"
-- the Hold Map description will predict the abilities of items with a header like "Item Name Result"
EID.descriptions[languageCode].HoldMapHeader = " Result"

-- https://wofsauge.github.io/IsaacDocs/rep/enums/RoomType.html
-- Includes Repentance room types for localization convenience
EID.descriptions[languageCode].RoomTypeNames = { "Normal Room", "Shop", "I AM ERROR Room", "Treasure Room", "Boss Room", "Miniboss Room", "Secret Room", "Super Secret Room", "Arcade Room", "Curse Room", "Challenge Room", "Library", "Sacrifice Room", "Devil Room", "Angel Room", "Crawlspace Room", "Boss Rush Room", "Isaac's Room", "Barren Room", "Chest Room", "Dice Room", "Black Market", "Exit Room", "Planetarium", "Teleporter Entrance", "Teleporter Exit", "Alt Path Trapdoor", "Blue Key Room", "Ultra Secret Room",
-- Not technically room types but still potentially useful to have localized
[666] = "Angel/Devil Room", [1024] = "Red Room", [1025] = "Special Red Room" }

-- currently used for D1
EID.descriptions[languageCode].PickupNames = {
	["5.0"] = "None",
	
	["5.10"] = "{{Heart}} Heart",
	["5.10.1"] = "{{Heart}} Heart", ["5.10.2"] = "{{HalfHeart}} Half Heart", ["5.10.3"] = "{{SoulHeart}} Soul Heart", ["5.10.4"] = "{{EternalHeart}} Eternal Heart", ["5.10.5"] = "{{Heart}} Double Heart", ["5.10.6"] = "{{BlackHeart}} Black Heart", ["5.10.7"] = "{{GoldHeart}} Gold Heart", ["5.10.8"] = "{{HalfSoulHeart}} Half Soul Heart", ["5.10.9"] = "{{Heart}} Scared Heart", ["5.10.10"] = "{{BlendedHeart}} Blended Heart", ["5.10.11"] = "{{EmptyBoneHeart}} Bone Heart", ["5.10.12"] = "{{RottenHeart}} Rotten Heart",
	
	["5.20"] = "{{Coin}} Coin",
	["5.20.1"] = "{{Crafting8}} Penny", ["5.20.2"] = "{{Crafting9}} Nickel", ["5.20.3"] = "{{Crafting10}} Dime", ["5.20.4"] = "{{Crafting8}} Double Penny", ["5.20.5"] = "{{Crafting11}} Lucky Penny", ["5.20.6"] = "{{Crafting9}} Sticky Nickel", ["5.20.7"] = "{{Crafting26}} Golden Penny",
	
	["5.30"] = "{{Key}} Key",
	["5.30.1"] = "{{Crafting12}} Key", ["5.30.2"] = "{{Crafting13}} Golden Key", ["5.30.3"] = "{{Crafting12}} Key Ring", ["5.30.4"] = "{{Crafting14}} Charged Key",
	
	["5.40"] = "{{Bomb}} Bomb",
	["5.40.1"] = "{{Crafting15}} Bomb", ["5.40.2"] = "{{Crafting15}} Double Bomb", ["5.40.3"] = "{{Crafting15}} Troll Bomb", ["5.40.4"] = "{{Crafting16}} Golden Bomb", ["5.40.5"] = "{{Crafting15}} Megatroll Bomb", ["5.40.7"] = "{{Crafting17}} Giga Bomb",
	
	["5.90"] = "{{Battery}} Battery",
	["5.90.0"] = "{{Crafting19}} Lil' Battery", --AB+ didn't have subtypes for batteries
	["5.90.1"] = "{{Crafting19}} Lil' Battery", ["5.90.2"] = "{{Crafting18}} Micro Battery", ["5.90.3"] = "{{Crafting20}} Mega Battery", ["5.90.4"] = "{{Crafting28}} Golden Battery",
	
	["5.50"] = "{{Chest}} Chest", ["5.51"] = "{{BombChest}} Bomb Chest", ["5.52"] = "{{SpikedChest}} Spiked Chest", ["5.53"] = "{{EternalChest}} Eternal Chest", ["5.54"] = "{{MimicChest}} Mimic Chest", ["5.55"] = "{{OldChest}} Old Chest", ["5.56"] = "{{WoodenChest}} Wooden Chest", ["5.57"] = "{{MegaChest}} Mega Chest", ["5.58"] = "{{HauntedChest}} Haunted Chest", ["5.60"] = "{{GoldenChest}} Golden Chest", ["5.360"] = "{{RedChest}} Red Chest",  
	
	["5.69"] = "{{GrabBag}} Grab Bag", ["5.69.1"] = "{{GrabBag}} Grab Bag", ["5.69.2"] = "{{BlackSack}} Black Sack",
	
	["5.70"] = "{{Pill}} Pill",
	["5.300"] = "{{Card}} Card",
	["5.301"] = "{{Rune}} Rune", -- not a real id
	["5.350"] = "{{Trinket}} Trinket",

}
