-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "bul"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Тъжният лук", -- The Sad Onion
    [C_ID .. 2] = "Трето око", -- The Inner Eye
    [C_ID .. 3] = "Огъната лъжица", -- Spoon Bender
    [C_ID .. 4] = "Главата на Крикет", -- Cricket's Head
    [C_ID .. 5] = "Моето отражение", -- My Reflection
    [C_ID .. 6] = "Номер едно", -- Number One
    [C_ID .. 7] = "Кръвта на мъченика", -- Blood of the Martyr
    [C_ID .. 8] = "Брат Боби", -- Brother Bobby
    [C_ID .. 9] = "Скатол", -- Skatole
    [C_ID .. 10] = "Ореол от мухи", -- Halo of Flies
    [C_ID .. 11] = "1up!", -- 1up!
    [C_ID .. 12] = "Вълшебна гъба", -- Magic Mushroom
    [C_ID .. 13] = "Вирус", -- The Virus
    [C_ID .. 14] = "Стероидна злоба", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Суров черен дроб", -- Raw Liver
    [C_ID .. 17] = "Скелетен ключ", -- Skeleton Key
    [C_ID .. 18] = "Долар", -- A Dollar
    [C_ID .. 19] = "Бум!", -- Boom!
    [C_ID .. 20] = "Възнасяне", -- Transcendence
    [C_ID .. 21] = "Компас", -- The Compass
    [C_ID .. 22] = "Обяд", -- Lunch
    [C_ID .. 23] = "Вечеря", -- Dinner
    [C_ID .. 24] = "Десерт", -- Dessert
    [C_ID .. 25] = "Закуска", -- Breakfast
    [C_ID .. 26] = "Развалено месо", -- Rotten Meat
    [C_ID .. 27] = "Дървена лъжица", -- Wooden Spoon
    [C_ID .. 28] = "Коланът", -- The Belt
    [C_ID .. 29] = "Бельото на мама", -- Mom's Underwear
    [C_ID .. 30] = "Токчетата на мама", -- Mom's Heels
    [C_ID .. 31] = "Червилото на мама", -- Mom's Lipstick
    [C_ID .. 32] = "Закачалка", -- Wire Coat Hanger
    [C_ID .. 33] = "Библията", -- The Bible
    [C_ID .. 34] = "Книгата на Белиал", -- The Book of Belial
    [C_ID .. 35] = "Некрономикон", -- The Necronomicon
    [C_ID .. 36] = "Ако", -- The Poop
    [C_ID .. 37] = "Мистър Бум", -- Mr. Boom
    [C_ID .. 38] = "Главата на Тами", -- Tammy's Head
    [C_ID .. 39] = "Сутиенът на мама", -- Mom's Bra
    [C_ID .. 40] = "Камикадзе!", -- Kamikaze!
    [C_ID .. 41] = "Превръзката на мама", -- Mom's Pad
    [C_ID .. 42] = "Изгнилата глава на Боб", -- Bob's Rotten Head
    [C_ID .. 43] = "000", -- 
    [C_ID .. 44] = "Телепорт!", -- Teleport!
    [C_ID .. 45] = "Вкусно сърце", -- Yum Heart
    [C_ID .. 46] = "Късметлийски крак", -- Lucky Foot
    [C_ID .. 47] = "Дистанционното на доктора", -- Doctor's Remote
    [C_ID .. 48] = "Стрелата на Купидон", -- Cupid's Arrow
    [C_ID .. 49] = "Шуп Да Хуп!", -- Shoop da Whoop!
    [C_ID .. 50] = "Стивън", -- Steven
    [C_ID .. 51] = "Пентаграм", -- Pentagram
    [C_ID .. 52] = "Д-р Ембрион", -- Dr. Fetus
    [C_ID .. 53] = "Магнит", -- Magneto
    [C_ID .. 54] = "Карта на съкровище", -- Treasure Map
    [C_ID .. 55] = "Окото на мама", -- Mom's Eye
    [C_ID .. 56] = "Лимонова злополука", -- Lemon Mishap
    [C_ID .. 57] = "Отдалечено възхищение", -- Distant Admiration
    [C_ID .. 58] = "Книга на сенките", -- Book of Shadows
    [C_ID .. 59] = "000", -- The Book of Belial
    [C_ID .. 60] = "Стълбата", -- The Ladder
    [C_ID .. 61] = "000", -- 
    [C_ID .. 62] = "Чарът на вампира", -- Charm of the Vampire
    [C_ID .. 63] = "Батерията", -- The Battery
    [C_ID .. 64] = "Разпродажба в Steam", -- Steam Sale
    [C_ID .. 65] = "Анархистична готварска книга", -- Anarchist Cookbook
    [C_ID .. 66] = "Пясъчен часовник", -- The Hourglass
    [C_ID .. 67] = "Сестра Маги", -- Sister Maggy
    [C_ID .. 68] = "Технология", -- Technology
    [C_ID .. 69] = "Шоколадово мляко", -- Chocolate Milk
    [C_ID .. 70] = "Хормони за растеж", -- Growth Hormones
    [C_ID .. 71] = "Малка гъба", -- Mini Mush
    [C_ID .. 72] = "Молитвена броеница", -- Rosary
    [C_ID .. 73] = "Куб от месо", -- Cube of Meat
    [C_ID .. 74] = "Монета от 25 стотинки", -- A Quarter
    [C_ID .. 75] = "Лиценз за лекар", -- PHD
    [C_ID .. 76] = "Рентгеново зрение", -- X-Ray Vision
    [C_ID .. 77] = "Моят малък еднорог", -- My Little Unicorn
    [C_ID .. 78] = "Книга на откровенията", -- Book of Revelations
    [C_ID .. 79] = "Белегът", -- The Mark
    [C_ID .. 80] = "Пактът", -- The Pact
    [C_ID .. 81] = "Мъртва котка", -- Dead Cat
    [C_ID .. 82] = "Властелинът на ямата", -- Lord of the Pit
    [C_ID .. 83] = "Пиронът", -- The Nail
    [C_ID .. 84] = "Трябва да идем по-дълбоко!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Тесте карти", -- Deck of Cards
    [C_ID .. 86] = "Зъбът на Монстро", -- Monstro's Tooth
    [C_ID .. 87] = "Рогата на Локи", -- Loki's Horns
    [C_ID .. 88] = "Малкият Чъби", -- Little Chubby
    [C_ID .. 89] = "Паякова захапка", -- Spider Bite
    [C_ID .. 90] = "Малкият камък", -- The Small Rock
    [C_ID .. 91] = "Миньорска шапка", -- Spelunker Hat
    [C_ID .. 92] = "Супер лепенка", -- Super Bandage
    [C_ID .. 93] = "Геймкид", -- The Gamekid
    [C_ID .. 94] = "Кесия с монети", -- Sack of Pennies
    [C_ID .. 95] = "Робо-бебе", -- Robo-Baby
    [C_ID .. 96] = "Малък Ч.А.Д.", -- Little C.H.A.D.
    [C_ID .. 97] = "Книгата на греховете", -- The Book of Sin
    [C_ID .. 98] = "Реликвата", -- The Relic
    [C_ID .. 99] = "Малък Гиш", -- Little Gish
    [C_ID .. 100] = "Малък Стивън", -- Little Steven
    [C_ID .. 101] = "Ореолът", -- The Halo
    [C_ID .. 102] = "Флаконът с хапчета на мама", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Настинка", -- The Common Cold
    [C_ID .. 104] = "Паразитът", -- The Parasite
    [C_ID .. 105] = "D6", -- The D6
    [C_ID .. 106] = "Мистър Мега", -- Mr. Mega
    [C_ID .. 107] = "Шивашки ножици", -- The Pinking Shears
    [C_ID .. 108] = "Вафлата", -- The Wafer
    [C_ID .. 109] = "Пари = Сила", -- Money = Power
    [C_ID .. 110] = "Лещите на мама", -- Mom's Contacts
    [C_ID .. 111] = "Бобчето", -- The Bean
    [C_ID .. 112] = "Ангел пазител", -- Guardian Angel
    [C_ID .. 113] = "Бебе демон", -- Demon Baby
    [C_ID .. 114] = "Ножът на мама", -- Mom's Knife
    [C_ID .. 115] = "Уиджа дъска", -- Ouija Board
    [C_ID .. 116] = "9 волтова батерия", -- 9 Volt
    [C_ID .. 117] = "Мъртва птица", -- Dead Bird
    [C_ID .. 118] = "Сяра", -- Brimstone
    [C_ID .. 119] = "Пакет с кръв", -- Blood Bag
    [C_ID .. 120] = "Странна гъба (тънка)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Странна гъба (дебела)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Вавилонска блудница", -- Whore of Babylon
    [C_ID .. 123] = "Наръчник за чудовища", -- Monster Manual
    [C_ID .. 124] = "Свитъци от Мъртво море", -- Dead Sea Scrolls
    [C_ID .. 125] = "Боби-Бомба", -- Bobby-Bomb
    [C_ID .. 126] = "Бръснарско ножче", -- Razor Blade
    [C_ID .. 127] = "Забрави за мен", -- Forget Me Now
    [C_ID .. 128] = "Завинаги сам", -- Forever Alone
    [C_ID .. 129] = "Кофа с маз", -- Bucket of Lard
    [C_ID .. 130] = "Пони", -- A Pony
    [C_ID .. 131] = "Торба с бомби", -- Bomb Bag
    [C_ID .. 132] = "Парче въглен", -- A Lump of Coal
    [C_ID .. 133] = "Лапата на Гъпи", -- Guppy's Paw
    [C_ID .. 134] = "Опашката на Гъпи", -- Guppy's Tail
    [C_ID .. 135] = "Кръвна банка", -- IV Bag
    [C_ID .. 136] = "Най-добър приятел", -- Best Friend
    [C_ID .. 137] = "Детонатор", -- Remote Detonator
    [C_ID .. 138] = "Стигмата", -- Stigmata
    [C_ID .. 139] = "Чантата на мама", -- Mom's Purse
    [C_ID .. 140] = "Проклятието на Боб", -- Bob's Curse
    [C_ID .. 141] = "Артистично момче", -- Pageant Boy
    [C_ID .. 142] = "Скапуляр", -- Scapular
    [C_ID .. 143] = "Спидбол", -- Speed Ball
    [C_ID .. 144] = "Просяк-приятел", -- Bum Friend
    [C_ID .. 145] = "Главата на Гъпи", -- Guppy's Head
    [C_ID .. 146] = "Молитвена карта", -- Prayer Card
    [C_ID .. 147] = "Кирка", -- Notched Axe
    [C_ID .. 148] = "Нашествие", -- Infestation
    [C_ID .. 149] = "Буркан с отрова", -- Ipecac
    [C_ID .. 150] = "Трудна любов", -- Tough Love
    [C_ID .. 151] = "Мълиганът", -- The Mulligan
    [C_ID .. 152] = "Технология 2", -- Technology 2
    [C_ID .. 153] = "Паяк Мутант", -- Mutant Spider
    [C_ID .. 154] = "Химическо Изгаряне", -- Chemical Peel
    [C_ID .. 155] = "Зъркелът", -- The Peeper
    [C_ID .. 156] = "Калугерска одежда", -- Habit
    [C_ID .. 157] = "Жажда за кръв", -- Bloody Lust
    [C_ID .. 158] = "Кристална топка", -- Crystal Ball
    [C_ID .. 159] = "Дух на нощта", -- Spirit of the Night
    [C_ID .. 160] = "Удар от небето", -- Crack the Sky
    [C_ID .. 161] = "Анкх", -- Ankh
    [C_ID .. 162] = "Келтски кръст", -- Celtic Cross
    [C_ID .. 163] = "Бебе дух", -- Ghost Baby
    [C_ID .. 164] = "Свещта", -- The Candle
    [C_ID .. 165] = "Котка с девет опашки", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Бебе Арлекин", -- Harlequin Baby
    [C_ID .. 168] = "Епичен Ембрион", -- Epic Fetus
    [C_ID .. 169] = "Полифем", -- Polyphemus
    [C_ID .. 170] = "Татко Дълги Крака", -- Daddy Longlegs
    [C_ID .. 171] = "Паяшки задник", -- Spider Butt
    [C_ID .. 172] = "Жертвена кама", -- Sacrificial Dagger
    [C_ID .. 173] = "Митра", -- Mitre
    [C_ID .. 174] = "Бебе дъга", -- Rainbow Baby
    [C_ID .. 175] = "Ключа на тати", -- Dad's Key
    [C_ID .. 176] = "Стволови клетки", -- Stem Cells
    [C_ID .. 177] = "Преносим слот", -- Portable Slot
    [C_ID .. 178] = "Светена Вода", -- Holy Water
    [C_ID .. 179] = "Съдба", -- Fate
    [C_ID .. 180] = "Черен боб", -- The Black Bean
    [C_ID .. 181] = "Бяло пони", -- White Pony
    [C_ID .. 182] = "Свещено сърце", -- Sacred Heart
    [C_ID .. 183] = "Клечки за зъби", -- Tooth Picks
    [C_ID .. 184] = "Светия Граал", -- Holy Grail
    [C_ID .. 185] = "Мъртъв гълъб", -- Dead Dove
    [C_ID .. 186] = "Кръвни права", -- Blood Rights
    [C_ID .. 187] = "Топката косми на Гъпи", -- Guppy's Hairball
    [C_ID .. 188] = "Авел", -- Abel
    [C_ID .. 189] = "Фен на Super Meat Boy", -- SMB Super Fan
    [C_ID .. 190] = "Пиро", -- Pyro
    [C_ID .. 191] = "Тридоларова банкнота", -- 3 Dollar Bill
    [C_ID .. 192] = "Телепатия за Глупаци", -- Telepathy for Dummies
    [C_ID .. 193] = "МЕСО!", -- MEAT!
    [C_ID .. 194] = "Вълшебна топка 8", -- Magic 8 Ball
    [C_ID .. 195] = "Портмонето на мама", -- Mom's Coin Purse
    [C_ID .. 196] = "Играчка за стискане", -- Squeezy
    [C_ID .. 197] = "Сокът на Исус", -- Jesus Juice
    [C_ID .. 198] = "Кутия", -- Box
    [C_ID .. 199] = "Ключът на мама", -- Mom's Key
    [C_ID .. 200] = "Сенките на мама", -- Mom's Eyeshadow
    [C_ID .. 201] = "Желязно кюлче", -- Iron Bar
    [C_ID .. 202] = "Докосването на Мидас", -- Midas' Touch
    [C_ID .. 203] = "Скромен комплект", -- Humbleing Bundle
    [C_ID .. 204] = "Раменна чанта", -- Fanny Pack
    [C_ID .. 205] = "Остър щепсел", -- Sharp Plug
    [C_ID .. 206] = "Гилотина", -- Guillotine
    [C_ID .. 207] = "Топка от лепенки", -- Ball of Bandages
    [C_ID .. 208] = "Шампионски пояс", -- Champion Belt
    [C_ID .. 209] = "Бомби от задник", -- Butt Bombs
    [C_ID .. 210] = "Изгризано листо", -- Gnawed Leaf
    [C_ID .. 211] = "Бебе паяк", -- Spiderbaby
    [C_ID .. 212] = "Яката на Гъпи", -- Guppy's Collar
    [C_ID .. 213] = "Изгубена контактна леща", -- Lost Contact
    [C_ID .. 214] = "Анемия", -- Anemic
    [C_ID .. 215] = "Козя глава", -- Goat Head
    [C_ID .. 216] = "Церемониална роба", -- Ceremonial Robes
    [C_ID .. 217] = "Перуката на мама", -- Mom's Wig
    [C_ID .. 218] = "Плацента", -- Placenta
    [C_ID .. 219] = "Стара лепенка", -- Old Bandage
    [C_ID .. 220] = "Тъжни бомби", -- Sad Bombs
    [C_ID .. 221] = "Гумено лепило", -- Rubber Cement
    [C_ID .. 222] = "Анти-гравитация", -- Anti-Gravity
    [C_ID .. 223] = "Пироман", -- Pyromaniac
    [C_ID .. 224] = "Тялото на Крикет", -- Cricket's Body
    [C_ID .. 225] = "Гимпи", -- Gimpy
    [C_ID .. 226] = "Черен лотос", -- Black Lotus
    [C_ID .. 227] = "Прасе касичка", -- Piggy Bank
    [C_ID .. 228] = "Парфюмът на мама", -- Mom's Perfume
    [C_ID .. 229] = "Белият дроб на Монстро", -- Monstro's Lung
    [C_ID .. 230] = "Абадон", -- Abaddon
    [C_ID .. 231] = "Топка смола", -- Ball of Tar
    [C_ID .. 232] = "Секундомер", -- Stop Watch
    [C_ID .. 233] = "Малка планета", -- Tiny Planet
    [C_ID .. 234] = "Нашествие 2", -- Infestation 2
    [C_ID .. 235] = "000", -- 
    [C_ID .. 236] = "Ешерихия коли", -- E. Coli
    [C_ID .. 237] = "Докосването на смъртта", -- Death's Touch
    [C_ID .. 238] = "Парче от ключ 1", -- Key Piece 1
    [C_ID .. 239] = "Парче от ключ 2", -- Key Piece 2
    [C_ID .. 240] = "Експериментално лечение", -- Experimental Treatment
    [C_ID .. 241] = "Споразумение с Подземния свят", -- Contract from Below
    [C_ID .. 242] = "Позор", -- Infamy
    [C_ID .. 243] = "Щит на Троицата", -- Trinity Shield
    [C_ID .. 244] = "Техно.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Синя карта", -- Blue Map
    [C_ID .. 247] = "Най-добри приятели завинаги!", -- BFFS!
    [C_ID .. 248] = "Кошерен ум", -- Hive Mind
    [C_ID .. 249] = "Има опции", -- There's Options
    [C_ID .. 250] = "Двойни бомби", -- Bogo Bombs
    [C_ID .. 251] = "Начално тесте", -- Starter Deck
    [C_ID .. 252] = "Малка торбичка", -- Little Baggy
    [C_ID .. 253] = "Вълшебна кора", -- Magic Scab
    [C_ID .. 254] = "Кръвен съсирек", -- Blood Clot
    [C_ID .. 255] = "Винт", -- Screw
    [C_ID .. 256] = "Горещи бомби", -- Hot Bombs
    [C_ID .. 257] = "Огнен ум", -- Fire Mind
    [C_ID .. 258] = "Изгубен №", -- Missing No.
    [C_ID .. 259] = "Тъмна материя", -- Dark Matter
    [C_ID .. 260] = "Черна свещ", -- Black Candle
    [C_ID .. 261] = "Проптоза", -- Proptosis
    [C_ID .. 262] = "Изгубена страница 2", -- Missing Page 2
    [C_ID .. 263] = "000", -- Clear Rune
    [C_ID .. 264] = "Умна муха", -- Smart Fly
    [C_ID .. 265] = "Сухо бебе", -- Dry Baby
    [C_ID .. 266] = "Сочен пашкул", -- Juicy Sack
    [C_ID .. 267] = "Робо-бебе 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Гнило бебе", -- Rotten Baby
    [C_ID .. 269] = "Бебе без глава", -- Headless Baby
    [C_ID .. 270] = "Пиявица", -- Leech
    [C_ID .. 271] = "Тайнствена торбичка", -- Mystery Sack
    [C_ID .. 272] = "Голяма красива муха", -- BBF
    [C_ID .. 273] = "Мозъкът на Боб", -- Bob's Brain
    [C_ID .. 274] = "Най-добър другар", -- Best Bud
    [C_ID .. 275] = "Бебе малка сяра", -- Lil Brimstone
    [C_ID .. 276] = "Сърцето на Исаак", -- Isaac's Heart
    [C_ID .. 277] = "Малкият призрак", -- Lil Haunt
    [C_ID .. 278] = "Тъмният просяк", -- Dark Bum
    [C_ID .. 279] = "Голям фен", -- Big Fan
    [C_ID .. 280] = "Сиси дългите крака", -- Sissy Longlegs
    [C_ID .. 281] = "Боксова круша", -- Punching Bag
    [C_ID .. 282] = "Ръководство за скачане", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Празна карта", -- Blank Card
    [C_ID .. 287] = "Книга на тайните", -- Book of Secrets
    [C_ID .. 288] = "Кутия с паяци", -- Box of Spiders
    [C_ID .. 289] = "Червена свещ", -- Red Candle
    [C_ID .. 290] = "Бурканът", -- The Jar
    [C_ID .. 291] = "Тоалетна!", -- Flush!
    [C_ID .. 292] = "Сатанистка Библия", -- Satanic Bible
    [C_ID .. 293] = "Главата на Крампус", -- Head of Krampus
    [C_ID .. 294] = "Маслен боб", -- Butter Bean
    [C_ID .. 295] = "Вълшебни пръсти", -- Magic Fingers
    [C_ID .. 296] = "Конвертор", -- Converter
    [C_ID .. 297] = "Кутията на Пандора", -- Pandora's Box
    [C_ID .. 298] = "Копито от еднорог", -- Unicorn Stump
    [C_ID .. 299] = "Телец", -- Taurus
    [C_ID .. 300] = "Овен", -- Aries
    [C_ID .. 301] = "Рак", -- Cancer
    [C_ID .. 302] = "Лъв", -- Leo
    [C_ID .. 303] = "Дева", -- Virgo
    [C_ID .. 304] = "Везни", -- Libra
    [C_ID .. 305] = "Скорпион", -- Scorpio
    [C_ID .. 306] = "Стрелец", -- Sagittarius
    [C_ID .. 307] = "Козирог", -- Capricorn
    [C_ID .. 308] = "Водолей", -- Aquarius
    [C_ID .. 309] = "Риби", -- Pisces
    [C_ID .. 310] = "Спиралата на Ева", -- Eve's Mascara
    [C_ID .. 311] = "Сянката на Юда", -- Judas' Shadow
    [C_ID .. 312] = "Панделката на Маги", -- Maggy's Bow
    [C_ID .. 313] = "Свещена мантия", -- Holy Mantle
    [C_ID .. 314] = "Гръмотевични бедра", -- Thunder Thighs
    [C_ID .. 315] = "Странно привличане", -- Strange Attractor
    [C_ID .. 316] = "Прокълнато око", -- Cursed Eye
    [C_ID .. 317] = "Мистериозна течност", -- Mysterious Liquid
    [C_ID .. 318] = "Близнаци", -- Gemini
    [C_ID .. 319] = "Другото око на Каин", -- Cain's Other Eye
    [C_ID .. 320] = "Единственият приятел на ???", -- ???'s Only Friend
    [C_ID .. 321] = "Веригите на Самсон", -- Samson's Chains
    [C_ID .. 322] = "Бебе Монго", -- Mongo Baby
    [C_ID .. 323] = "Сълзите на Исаак", -- Isaac's Tears
    [C_ID .. 324] = "Неопределено", -- Undefined
    [C_ID .. 325] = "Ножици", -- Scissors
    [C_ID .. 326] = "Глътка живот", -- Breath of Life
    [C_ID .. 327] = "Полароид", -- The Polaroid
    [C_ID .. 328] = "Негатив", -- The Negative
    [C_ID .. 329] = "Техниката Лудовико", -- The Ludovico Technique
    [C_ID .. 330] = "Соево мляко", -- Soy Milk
    [C_ID .. 331] = "Божественост", -- Godhead
    [C_ID .. 332] = "Дрипите на Лазар", -- Lazarus' Rags
    [C_ID .. 333] = "Разум", -- The Mind
    [C_ID .. 334] = "Тяло", -- The Body
    [C_ID .. 335] = "Душа", -- The Soul
    [C_ID .. 336] = "Мъртъв лук", -- Dead Onion
    [C_ID .. 337] = "Счупен часовник", -- Broken Watch
    [C_ID .. 338] = "Бумеранг", -- The Boomerang
    [C_ID .. 339] = "Безопасна игла", -- Safety Pin
    [C_ID .. 340] = "Кофеиново хапче", -- Caffeine Pill
    [C_ID .. 341] = "Разкъсана фотография", -- Torn Photo
    [C_ID .. 342] = "Синя шапка", -- Blue Cap
    [C_ID .. 343] = "Ключ за външна врата", -- Latch Key
    [C_ID .. 344] = "Кибритена кутия", -- Match Book
    [C_ID .. 345] = "Синтетично масло", -- Synthoil
    [C_ID .. 346] = "Лека закуска", -- A Snack
    [C_ID .. 347] = "Диплопия", -- Diplopia
    [C_ID .. 348] = "Плацебо", -- Placebo
    [C_ID .. 349] = "Дървен никел", -- Wooden Nickel
    [C_ID .. 350] = "Токсичен шок", -- Toxic Shock
    [C_ID .. 351] = "Мега боб", -- Mega Bean
    [C_ID .. 352] = "Стъклено оръдие", -- Glass Cannon
    [C_ID .. 353] = "Момче-бомбардировач", -- Bomber Boy
    [C_ID .. 354] = "Хрупкав Джак", -- Crack Jacks
    [C_ID .. 355] = "Огърлицата на мама", -- Mom's Pearls
    [C_ID .. 356] = "Акумулаторна батерия", -- Car Battery
    [C_ID .. 357] = "Кутия с приятели", -- Box of Friends
    [C_ID .. 358] = "Вещер", -- The Wiz
    [C_ID .. 359] = "8 инчови пирони", -- 8 Inch Nails
    [C_ID .. 360] = "Инкуб", -- Incubus
    [C_ID .. 361] = "Подарък от съдбата", -- Fate's Reward
    [C_ID .. 362] = "Малък сандък", -- Lil Chest
    [C_ID .. 363] = "Заклет протектор", -- Sworn Protector
    [C_ID .. 364] = "Зона \"Дружба\"", -- Friend Zone
    [C_ID .. 365] = "Изгубена муха", -- Lost Fly
    [C_ID .. 366] = "Разпръснати бомби", -- Scatter Bombs
    [C_ID .. 367] = "Залепващи се бомби", -- Sticky Bombs
    [C_ID .. 368] = "Епифора", -- Epiphora
    [C_ID .. 369] = "Континуум", -- Continuum
    [C_ID .. 370] = "Мистър Кукла", -- Mr. Dolly
    [C_ID .. 371] = "Проклятието на кулата", -- Curse of the Tower
    [C_ID .. 372] = "Заредено бебе", -- Charged Baby
    [C_ID .. 373] = "Мъртво око", -- Dead Eye
    [C_ID .. 374] = "Божествена светлина", -- Holy Light
    [C_ID .. 375] = "Шапка наблюдател", -- Host Hat
    [C_ID .. 376] = "Презареждане", -- Restock
    [C_ID .. 377] = "Разкъсан пашкул", -- Bursting Sack
    [C_ID .. 378] = "Номер 2", -- No. 2
    [C_ID .. 379] = "Двойна визия", -- Pupula Duplex
    [C_ID .. 380] = "Плати и Играй", -- Pay To Play
    [C_ID .. 381] = "Благословията на Едем", -- Eden's Blessing
    [C_ID .. 382] = "Приятелска топка", -- Friendly Ball
    [C_ID .. 383] = "Детонатор за сълзи", -- Tear Detonator
    [C_ID .. 384] = "Малкият Гърди", -- Lil Gurdy
    [C_ID .. 385] = "Бъмбо", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Кадилница", -- Censer
    [C_ID .. 388] = "Просяк за ключове", -- Key Bum
    [C_ID .. 389] = "Торбичка с руни", -- Rune Bag
    [C_ID .. 390] = "Серафим", -- Seraphim
    [C_ID .. 391] = "Предателство", -- Betrayal
    [C_ID .. 392] = "Зодиак", -- Zodiac
    [C_ID .. 393] = "Змийска целувка", -- Serpent's Kiss
    [C_ID .. 394] = "Белязан", -- Marked
    [C_ID .. 395] = "Технология X", -- Tech X
    [C_ID .. 396] = "Камерен бръснач", -- Ventricle Razor
    [C_ID .. 397] = "Привличащ лъч", -- Tractor Beam
    [C_ID .. 398] = "Плът на бога", -- God's Flesh
    [C_ID .. 399] = "Паст от пустотата", -- Maw of the Void
    [C_ID .. 400] = "Копието на съдбата", -- Spear of Destiny
    [C_ID .. 401] = "Експлозивен", -- Explosivo
    [C_ID .. 402] = "Хаос", -- Chaos
    [C_ID .. 403] = "Паячна модификация", -- Spider Mod
    [C_ID .. 404] = "Детето Пръдня", -- Farting Baby
    [C_ID .. 405] = "Фатален бъг", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Чистота", -- Purity
    [C_ID .. 408] = "Атаме", -- Athame
    [C_ID .. 409] = "Празен съд", -- Empty Vessel
    [C_ID .. 410] = "Зло око", -- Evil Eye
    [C_ID .. 411] = "Жадуваща кръв", -- Lusty Blood
    [C_ID .. 412] = "Демонично зачатие", -- Cambion Conception
    [C_ID .. 413] = "Непорочно зачатие", -- Immaculate Conception
    [C_ID .. 414] = "Повече опции", -- More Options
    [C_ID .. 415] = "Корона от светлина", -- Crown Of Light
    [C_ID .. 416] = "Дълбоки джобове", -- Deep Pockets
    [C_ID .. 417] = "Сукуб", -- Succubus
    [C_ID .. 418] = "Плодов пай", -- Fruit Cake
    [C_ID .. 419] = "Телепорт 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Черен прах", -- Black Powder
    [C_ID .. 421] = "Бъбречен боб", -- Kidney Bean
    [C_ID .. 422] = "Светещ пясъчен часовник", -- Glowing Hourglass
    [C_ID .. 423] = "Кръг на защитата", -- Circle of Protection
    [C_ID .. 424] = "Торбичка за глава", -- Sack Head
    [C_ID .. 425] = "Фенерче", -- Night Light
    [C_ID .. 426] = "Обсебен фен", -- Obsessed Fan
    [C_ID .. 427] = "Миньор", -- Mine Crafter
    [C_ID .. 428] = "Пижама", -- PJs
    [C_ID .. 429] = "Главата на Търговеца", -- Head of the Keeper
    [C_ID .. 430] = "Бащина муха", -- Papa Fly
    [C_ID .. 431] = "Многоизмерно дете", -- Multidimensional Baby
    [C_ID .. 432] = "Лъскави бомби", -- Glitter Bombs
    [C_ID .. 433] = "Моята сянка", -- My Shadow
    [C_ID .. 434] = "Буркан с мухи", -- Jar of Flies
    [C_ID .. 435] = "Малкият Локи", -- Lil Loki
    [C_ID .. 436] = "Мляко!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Биберон", -- Binky
    [C_ID .. 439] = "Кутията на мама", -- Mom's Box
    [C_ID .. 440] = "Камък в бъбрека", -- Kidney Stone
    [C_ID .. 441] = "Мега Заряд", -- Mega Blast
    [C_ID .. 442] = "Короната на тъмния принц", -- Dark Prince's Crown
    [C_ID .. 443] = "Ябълка!", -- Apple!
    [C_ID .. 444] = "Графитен молив", -- Lead Pencil
    [C_ID .. 445] = "Кучешки зъб", -- Dog Tooth
    [C_ID .. 446] = "Мъртъв зъб", -- Dead Tooth
    [C_ID .. 447] = "Задържащ се боб", -- Linger Bean
    [C_ID .. 448] = "Парче стъкло", -- Shard of Glass
    [C_ID .. 449] = "Метална пластина", -- Metal Plate
    [C_ID .. 450] = "Окото на Алчността", -- Eye of Greed
    [C_ID .. 451] = "Таро покривка", -- Tarot Cloth
    [C_ID .. 452] = "Разширени вени", -- Varicose Veins
    [C_ID .. 453] = "Отворена фрактура", -- Compound Fracture
    [C_ID .. 454] = "Полидактилия", -- Polydactyly
    [C_ID .. 455] = "Изгубената монета на татко", -- Dad's Lost Coin
    [C_ID .. 456] = "Мухлясал хляб", -- Midnight Snack
    [C_ID .. 457] = "Конична глава", -- Cone Head
    [C_ID .. 458] = "Пъп", -- Belly Button
    [C_ID .. 459] = "Синузит", -- Sinus Infection
    [C_ID .. 460] = "Глаукома", -- Glaucoma
    [C_ID .. 461] = "Паразитоид", -- Parasitoid
    [C_ID .. 462] = "Окото на Белиал", -- Eye of Belial
    [C_ID .. 463] = "Сярна киселина", -- Sulfuric Acid
    [C_ID .. 464] = "Символ за баланс", -- Glyph of Balance
    [C_ID .. 465] = "Аналогов стик", -- Analog Stick
    [C_ID .. 466] = "Зараза", -- Contagion
    [C_ID .. 467] = "Палец!", -- Finger!
    [C_ID .. 468] = "Сянка", -- Shade
    [C_ID .. 469] = "Депресия", -- Depression
    [C_ID .. 470] = "Хъши", -- Hushy
    [C_ID .. 471] = "Малък Монстро", -- Lil Monstro
    [C_ID .. 472] = "Бебе крал", -- King Baby
    [C_ID .. 473] = "Голям Чъби", -- Big Chubby
    [C_ID .. 474] = "Сливица", -- Broken Glass Cannon
    [C_ID .. 475] = "План C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Пустота", -- Void
    [C_ID .. 478] = "Пауза", -- Pause
    [C_ID .. 479] = "Леярна", -- Smelter
    [C_ID .. 480] = "Компост", -- Compost
    [C_ID .. 481] = "Анализатор", -- Dataminer
    [C_ID .. 482] = "Превключване", -- Clicker
    [C_ID .. 483] = "Мама Мега!", -- Mama Mega!
    [C_ID .. 484] = "Чакай, какво?", -- Wait What?
    [C_ID .. 485] = "Изкривено пени", -- Crooked Penny
    [C_ID .. 486] = "Тъп бръснач", -- Dull Razor
    [C_ID .. 487] = "Картофобелачка", -- Potato Peeler
    [C_ID .. 488] = "Метроном", -- Metronome
    [C_ID .. 489] = "D-безкрайност", -- D Infinity
    [C_ID .. 490] = "Душата на Едем", -- Eden's Soul
    [C_ID .. 491] = "Киселинно бебе", -- Acid Baby
    [C_ID .. 492] = "ХЕЙ, СЛУШАЙ!", -- YO LISTEN!
    [C_ID .. 493] = "Адреналин", -- Adrenaline
    [C_ID .. 494] = "Стълбата на Яков", -- Jacob's Ladder
    [C_ID .. 495] = "Фантом чушка", -- Ghost Pepper
    [C_ID .. 496] = "Евтаназия", -- Euthanasia
    [C_ID .. 497] = "Камуфлажни гащи", -- Camo Undies
    [C_ID .. 498] = "Двойственост", -- Duality
    [C_ID .. 499] = "Причастие", -- Eucharist
    [C_ID .. 500] = "Торбичка с торбички", -- Sack of Sacks
    [C_ID .. 501] = "Торбичка на Алчността", -- Greed's Gullet
    [C_ID .. 502] = "Голяма пъпка", -- Large Zit
    [C_ID .. 503] = "Малкия рог", -- Little Horn
    [C_ID .. 504] = "Кафяво късче", -- Brown Nugget
    [C_ID .. 505] = "Poke Go", -- Poke Go
    [C_ID .. 506] = "Предател", -- Backstabber
    [C_ID .. 507] = "Остра сламка", -- Sharp Straw
    [C_ID .. 508] = "Бръсначът на мама", -- Mom's Razor
    [C_ID .. 509] = "Кърваво око", -- Bloodshot Eye
    [C_ID .. 510] = "Бълнуващ", -- Delirious
    [C_ID .. 511] = "Ядосана муха", -- Angry Fly
    [C_ID .. 512] = "Черна дупка", -- Black Hole
    [C_ID .. 513] = "Бозо", -- Bozo
    [C_ID .. 514] = "Счупен модем", -- Broken Modem
    [C_ID .. 515] = "Тайнствен подарък", -- Mystery Gift
    [C_ID .. 516] = "Пръскачка", -- Sprinkler
    [C_ID .. 517] = "Бързи бомби", -- Fast Bombs
    [C_ID .. 518] = "Приятел в кутия", -- Buddy in a Box
    [C_ID .. 519] = "Малката лудост", -- Lil Delirium
    [C_ID .. 520] = "Кабели за стартов ток", -- Jumper Cables
    [C_ID .. 521] = "Купон", -- Coupon
    [C_ID .. 522] = "Телекинеза", -- Telekinesis
    [C_ID .. 523] = "Кутия за доставка", -- Moving Box
    [C_ID .. 524] = "Технология Нула", -- Technology Zero
    [C_ID .. 525] = "Проказа", -- Leprosy
    [C_ID .. 526] = "7 печата", -- 7 Seals
    [C_ID .. 527] = "Мистър МИ!", -- Mr. ME!
    [C_ID .. 528] = "Ангелска призма", -- Angelic Prism
    [C_ID .. 529] = "Пук!", -- Pop!
    [C_ID .. 530] = "Списък на смъртта", -- Death's List
    [C_ID .. 531] = "Хемолакрия", -- Haemolacria
    [C_ID .. 532] = "Лакрифагия", -- Lachryphagy
    [C_ID .. 533] = "Трисвятост", -- Trisagion
    [C_ID .. 534] = "Ученическа раница", -- Schoolbag
    [C_ID .. 535] = "Одеяло", -- Blanket
    [C_ID .. 536] = "Жертвен олтар", -- Sacrificial Altar
    [C_ID .. 537] = "Малкият плювач", -- Lil Spewer
    [C_ID .. 538] = "Стъклени топчета", -- Marbles
    [C_ID .. 539] = "Тайнствено яйце", -- Mystery Egg
    [C_ID .. 540] = "Плосък камък", -- Flat Stone
    [C_ID .. 541] = "Костен мозък", -- Marrow
    [C_ID .. 542] = "Ставно ребро", -- Slipped Rib
    [C_ID .. 543] = "Света земя", -- Hallowed Ground
    [C_ID .. 544] = "Наточено ребро", -- Pointy Rib
    [C_ID .. 545] = "Книга на мъртвите", -- Book of the Dead
    [C_ID .. 546] = "Пръстенът на татко", -- Dad's Ring
    [C_ID .. 547] = "Документи за развод", -- Divorce Papers
    [C_ID .. 548] = "Челюстна кост", -- Jaw Bone
    [C_ID .. 549] = "Крехки кости", -- Brittle Bones
    [C_ID .. 550] = "Счупена лопата", -- Broken Shovel
    [C_ID .. 551] = "Счупена лопата", -- Broken Shovel
    [C_ID .. 552] = "Лопатата на мама", -- Mom's Shovel
    [C_ID .. 553] = "", -- Mucormycosis
    [C_ID .. 554] = "", -- 2Spooky
    [C_ID .. 555] = "", -- Golden Razor
    [C_ID .. 556] = "", -- Sulfur
    [C_ID .. 557] = "", -- Fortune Cookie
    [C_ID .. 558] = "", -- Eye Sore
    [C_ID .. 559] = "", -- 120 Volt
    [C_ID .. 560] = "", -- It Hurts
    [C_ID .. 561] = "", -- Almond Milk
    [C_ID .. 562] = "", -- Rock Bottom
    [C_ID .. 563] = "", -- Nancy Bombs
    [C_ID .. 564] = "", -- A Bar of Soap
    [C_ID .. 565] = "", -- Blood Puppy
    [C_ID .. 566] = "", -- Dream Catcher
    [C_ID .. 567] = "", -- Paschal Candle
    [C_ID .. 568] = "", -- Divine Intervention
    [C_ID .. 569] = "", -- Blood Oath
    [C_ID .. 570] = "", -- Playdough Cookie
    [C_ID .. 571] = "", -- Orphan Socks
    [C_ID .. 572] = "", -- Eye of the Occult
    [C_ID .. 573] = "", -- Immaculate Heart
    [C_ID .. 574] = "", -- Monstrance
    [C_ID .. 575] = "", -- The Intruder
    [C_ID .. 576] = "", -- Dirty Mind
    [C_ID .. 577] = "", -- Damocles
    [C_ID .. 578] = "", -- Free Lemonade
    [C_ID .. 579] = "", -- Spirit Sword
    [C_ID .. 580] = "", -- Red Key
    [C_ID .. 581] = "", -- Psy Fly
    [C_ID .. 582] = "", -- Wavy Cap
    [C_ID .. 583] = "", -- Rocket in a Jar
    [C_ID .. 584] = "", -- Book of Virtues
    [C_ID .. 585] = "", -- Alabaster Box
    [C_ID .. 586] = "", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "", -- Sol
    [C_ID .. 589] = "", -- Luna
    [C_ID .. 590] = "", -- Mercurius
    [C_ID .. 591] = "", -- Venus
    [C_ID .. 592] = "", -- Terra
    [C_ID .. 593] = "", -- Mars
    [C_ID .. 594] = "", -- Jupiter
    [C_ID .. 595] = "", -- Saturnus
    [C_ID .. 596] = "", -- Uranus
    [C_ID .. 597] = "", -- Neptunus
    [C_ID .. 598] = "", -- Pluto
    [C_ID .. 599] = "", -- Voodoo Head
    [C_ID .. 600] = "", -- Eye Drops
    [C_ID .. 601] = "", -- Act of Contrition
    [C_ID .. 602] = "", -- Member Card
    [C_ID .. 603] = "", -- Battery Pack
    [C_ID .. 604] = "", -- Mom's Bracelet
    [C_ID .. 605] = "", -- The Scooper
    [C_ID .. 606] = "", -- Ocular Rift
    [C_ID .. 607] = "", -- Boiled Baby
    [C_ID .. 608] = "", -- Freezer Baby
    [C_ID .. 609] = "", -- Eternal D6
    [C_ID .. 610] = "", -- Bird Cage
    [C_ID .. 611] = "", -- Larynx
    [C_ID .. 612] = "", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "", -- Blood Bombs
    [C_ID .. 615] = "", -- Lil Dumpy
    [C_ID .. 616] = "", -- Bird's Eye
    [C_ID .. 617] = "", -- Lodestone
    [C_ID .. 618] = "", -- Rotten Tomato
    [C_ID .. 619] = "", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "", -- Red Stew
    [C_ID .. 622] = "", -- Genesis
    [C_ID .. 623] = "", -- Sharp Key
    [C_ID .. 624] = "", -- Booster Pack
    [C_ID .. 625] = "", -- Mega Mush
    [C_ID .. 626] = "", -- Knife Piece 1
    [C_ID .. 627] = "", -- Knife Piece 2
    [C_ID .. 628] = "", -- Death Certificate
    [C_ID .. 629] = "", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "", -- Meat Cleaver
    [C_ID .. 632] = "", -- Evil Charm
    [C_ID .. 633] = "", -- Dogma
    [C_ID .. 634] = "", -- Purgatory
    [C_ID .. 635] = "", -- Stitches
    [C_ID .. 636] = "", -- R Key
    [C_ID .. 637] = "", -- Knockout Drops
    [C_ID .. 638] = "", -- Eraser
    [C_ID .. 639] = "", -- Yuck Heart
    [C_ID .. 640] = "", -- Urn of Souls
    [C_ID .. 641] = "", -- Akeldama
    [C_ID .. 642] = "", -- Magic Skin
    [C_ID .. 643] = "", -- Revelation
    [C_ID .. 644] = "", -- Consolation Prize
    [C_ID .. 645] = "", -- Tinytoma
    [C_ID .. 646] = "", -- Brimstone Bombs
    [C_ID .. 647] = "", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "", -- Fruity Plum
    [C_ID .. 650] = "", -- Plum Flute
    [C_ID .. 651] = "", -- Star of Bethlehem
    [C_ID .. 652] = "", -- Cube Baby
    [C_ID .. 653] = "", -- Vade Retro
    [C_ID .. 654] = "", -- False PHD
    [C_ID .. 655] = "", -- Spin to Win
    [C_ID .. 656] = "", -- Damocles
    [C_ID .. 657] = "", -- Vasculitis
    [C_ID .. 658] = "", -- Giant Cell
    [C_ID .. 659] = "", -- Tropicamide
    [C_ID .. 660] = "", -- Card Reading
    [C_ID .. 661] = "", -- Quints
    [C_ID .. 662] = "", -- 
    [C_ID .. 663] = "", -- Tooth and Nail
    [C_ID .. 664] = "", -- Binge Eater
    [C_ID .. 665] = "", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "", -- Strawman
    [C_ID .. 668] = "", -- Dad's Note
    [C_ID .. 669] = "", -- Sausage
    [C_ID .. 670] = "", -- Options?
    [C_ID .. 671] = "", -- Candy Heart
    [C_ID .. 672] = "", -- A Pound of Flesh
    [C_ID .. 673] = "", -- Redemption
    [C_ID .. 674] = "", -- Spirit Shackles
    [C_ID .. 675] = "", -- Cracked Orb
    [C_ID .. 676] = "", -- Empty Heart
    [C_ID .. 677] = "", -- Astral Projection
    [C_ID .. 678] = "", -- C Section
    [C_ID .. 679] = "", -- Lil Abaddon
    [C_ID .. 680] = "", -- Montezuma's Revenge
    [C_ID .. 681] = "", -- Lil Portal
    [C_ID .. 682] = "", -- Worm Friend
    [C_ID .. 683] = "", -- Bone Spurs
    [C_ID .. 684] = "", -- Hungry Soul
    [C_ID .. 685] = "", -- Jar of Wisps
    [C_ID .. 686] = "", -- Soul Locket
    [C_ID .. 687] = "", -- Friend Finder
    [C_ID .. 688] = "", -- Inner Child
    [C_ID .. 689] = "", -- Glitched Crown
    [C_ID .. 690] = "", -- Belly Jelly
    [C_ID .. 691] = "", -- Sacred Orb
    [C_ID .. 692] = "", -- Sanguine Bond
    [C_ID .. 693] = "", -- The Swarm
    [C_ID .. 694] = "", -- Heartbreak
    [C_ID .. 695] = "", -- Bloody Gust
    [C_ID .. 696] = "", -- Salvation
    [C_ID .. 697] = "", -- Vanishing Twin
    [C_ID .. 698] = "", -- Twisted Pair
    [C_ID .. 699] = "", -- Azazel's Rage
    [C_ID .. 700] = "", -- Echo Chamber
    [C_ID .. 701] = "", -- Isaac's Tomb
    [C_ID .. 702] = "", -- Vengeful Spirit
    [C_ID .. 703] = "", -- Esau Jr.
    [C_ID .. 704] = "", -- Berserk!
    [C_ID .. 705] = "", -- Dark Arts
    [C_ID .. 706] = "", -- Abyss
    [C_ID .. 707] = "", -- Supper
    [C_ID .. 708] = "", -- Stapler
    [C_ID .. 709] = "", -- Suplex!
    [C_ID .. 710] = "", -- Bag of Crafting
    [C_ID .. 711] = "", -- Flip
    [C_ID .. 712] = "", -- Lemegeton
    [C_ID .. 713] = "", -- Sumptorium
    [C_ID .. 714] = "", -- Recall
    [C_ID .. 715] = "", -- Hold
    [C_ID .. 716] = "", -- Keeper's Sack
    [C_ID .. 717] = "", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "", -- Keeper's Box
    [C_ID .. 720] = "", -- Everything Jar
    [C_ID .. 721] = "", -- TMTRAINER
    [C_ID .. 722] = "", -- Anima Sola
    [C_ID .. 723] = "", -- Spindown Dice
    [C_ID .. 724] = "", -- Hypercoagulation
    [C_ID .. 725] = "", -- IBS
    [C_ID .. 726] = "", -- Hemoptysis
    [C_ID .. 727] = "", -- Ghost Bombs
    [C_ID .. 728] = "", -- Gello
    [C_ID .. 729] = "", -- Decap Attack
    [C_ID .. 730] = "", -- Glass Eye
    [C_ID .. 731] = "", -- Stye
    [C_ID .. 732] = "", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Погълната монета", -- Swallowed Penny
    [T_ID .. 2] = "Вкаменено ако", -- Petrified Poop
    [T_ID .. 3] = "AAA батерия", -- AAA Battery
    [T_ID .. 4] = "Счупено дистанционно", -- Broken Remote
    [T_ID .. 5] = "Лилаво сърце", -- Purple Heart
    [T_ID .. 6] = "Счупен магнит", -- Broken Magnet
    [T_ID .. 7] = "Мънисто от броеница", -- Rosary Bead
    [T_ID .. 8] = "Игрова дискета", -- Cartridge
    [T_ID .. 9] = "Пулсиращ червей", -- Pulse Worm
    [T_ID .. 10] = "Извиващ се червей", -- Wiggle Worm
    [T_ID .. 11] = "Червей пръстен", -- Ring Worm
    [T_ID .. 12] = "Сплескан червей", -- Flat Worm
    [T_ID .. 13] = "Кредит за магазин", -- Store Credit
    [T_ID .. 14] = "Гъбички", -- Callus
    [T_ID .. 15] = "Късметлийски камък", -- Lucky Rock
    [T_ID .. 16] = "Нокътят на мама", -- Mom's Toenail
    [T_ID .. 17] = "Черно червило", -- Black Lipstick
    [T_ID .. 18] = "Библейска брошура", -- Bible Tract
    [T_ID .. 19] = "Кламер", -- Paper Clip
    [T_ID .. 20] = "Маймунска лапа", -- Monkey Paw
    [T_ID .. 21] = "Тайнствена хартия", -- Mysterious Paper
    [T_ID .. 22] = "Опашка от Демон", -- Daemon's Tail
    [T_ID .. 23] = "Плакат за изгубен", -- Missing Poster
    [T_ID .. 24] = "Монета за дупето", -- Butt Penny
    [T_ID .. 25] = "Мистериозен шоколад", -- Mysterious Candy
    [T_ID .. 26] = "Кука червей", -- Hook Worm
    [T_ID .. 27] = "Прав червей", -- Whip Worm
    [T_ID .. 28] = "Счупен Анкх", -- Broken Ankh
    [T_ID .. 29] = "Рибешка глава", -- Fish Head
    [T_ID .. 30] = "Зачервено око", -- Pinky Eye
    [T_ID .. 31] = "Пинче", -- Push Pin
    [T_ID .. 32] = "Псилоцибинова гъба", -- Liberty Cap
    [T_ID .. 33] = "Пъпна връв", -- Umbilical Cord
    [T_ID .. 34] = "Детско сърце", -- Child's Heart
    [T_ID .. 35] = "Извит рог", -- Curved Horn
    [T_ID .. 36] = "Ръждив ключ", -- Rusted Key
    [T_ID .. 37] = "Козе копито", -- Goat Hoof
    [T_ID .. 38] = "Перлата на мама", -- Mom's Pearl
    [T_ID .. 39] = "Рак", -- Cancer
    [T_ID .. 40] = "Червена кръпка", -- Red Patch
    [T_ID .. 41] = "Кибритена клечка", -- Match Stick
    [T_ID .. 42] = "Късметлийски пръст", -- Lucky Toe
    [T_ID .. 43] = "Прокълнат череп", -- Cursed Skull
    [T_ID .. 44] = "Безопасно покритие", -- Safety Cap
    [T_ID .. 45] = "Асо Пика", -- Ace of Spades
    [T_ID .. 46] = "Вилицата на Исаак", -- Isaac's Fork
    [T_ID .. 47] = "000", -- 
    [T_ID .. 48] = "Изгубена страница", -- A Missing Page
    [T_ID .. 49] = "Кърваво пени", -- Bloody Penny
    [T_ID .. 50] = "Изгорено пени", -- Burnt Penny
    [T_ID .. 51] = "Плоско пени", -- Flat Penny
    [T_ID .. 52] = "Фалшиво пени", -- Counterfeit Penny
    [T_ID .. 53] = "Кърлеж", -- Tick
    [T_ID .. 54] = "Главата на Исаак", -- Isaac's Head
    [T_ID .. 55] = "Вярата на Маги", -- Maggy's Faith
    [T_ID .. 56] = "Езикът на Юда", -- Judas' Tongue
    [T_ID .. 57] = "Душата на ???", -- ???'s Soul
    [T_ID .. 58] = "Къдрицата на Самсон", -- Samson's Lock
    [T_ID .. 59] = "Окото на Каин", -- Cain's Eye
    [T_ID .. 60] = "Кракът на Ева", -- Eve's Bird Foot
    [T_ID .. 61] = "Лява ръка", -- The Left Hand
    [T_ID .. 62] = "Блестящ камък", -- Shiny Rock
    [T_ID .. 63] = "Безопасни ножици", -- Safety Scissors
    [T_ID .. 64] = "Дъгов червей", -- Rainbow Worm
    [T_ID .. 65] = "Тения", -- Tape Worm
    [T_ID .. 66] = "Мързелив червей", -- Lazy Worm
    [T_ID .. 67] = "Пропукан зар", -- Cracked Dice
    [T_ID .. 68] = "Супер магнит", -- Super Magnet
    [T_ID .. 69] = "Избледнял полaроид", -- Faded Polaroid
    [T_ID .. 70] = "Въшка", -- Louse
    [T_ID .. 71] = "Бъбрекът на Боб", -- Bob's Bladder
    [T_ID .. 72] = "Батерия за часовник", -- Watch Battery
    [T_ID .. 73] = "Експлодираща шапка", -- Blasting Cap
    [T_ID .. 74] = "Търсач на съкровища", -- Stud Finder
    [T_ID .. 75] = "Грешка", -- Error
    [T_ID .. 76] = "Покер чип", -- Poker Chip
    [T_ID .. 77] = "Блистер", -- Blister
    [T_ID .. 78] = "Втора ръка", -- Second Hand
    [T_ID .. 79] = "Неизследвана безкрайност", -- Endless Nameless
    [T_ID .. 80] = "Черно перо", -- Black Feather
    [T_ID .. 81] = "Сляпа ярост", -- Blind Rage
    [T_ID .. 82] = "Златна подкова", -- Golden Horse Shoe
    [T_ID .. 83] = "Ключ от магазина", -- Store Key
    [T_ID .. 84] = "Ребро на Алчността", -- Rib of Greed
    [T_ID .. 85] = "Карма", -- Karma
    [T_ID .. 86] = "Малка ларва", -- Lil Larva
    [T_ID .. 87] = "Медальонът на Мама", -- Mom's Locket
    [T_ID .. 88] = "НЕ!", -- NO!
    [T_ID .. 89] = "Детска каишка", -- Child Leash
    [T_ID .. 90] = "Кафява шапка", -- Brown Cap
    [T_ID .. 91] = "Меконий", -- Meconium
    [T_ID .. 92] = "Напукана корона", -- Cracked Crown
    [T_ID .. 93] = "Използвана пелена", -- Used Diaper
    [T_ID .. 94] = "Рибешка опашка", -- Fish Tail
    [T_ID .. 95] = "Черен зъб", -- Black Tooth
    [T_ID .. 96] = "Червей Уроборос", -- Ouroboros Worm
    [T_ID .. 97] = "Сливица", -- Tonsil
    [T_ID .. 98] = "Сопол", -- Nose Goblin
    [T_ID .. 99] = "Супер топка", -- Super Ball
    [T_ID .. 100] = "Осветяваща крушка", -- Vibrant Bulb
    [T_ID .. 101] = "Затъмнена крушка", -- Dim Bulb
    [T_ID .. 102] = "Разкъсана карта", -- Fragmented Card
    [T_ID .. 103] = "Равенство!", -- Equality!
    [T_ID .. 104] = "Ядец", -- Wish Bone
    [T_ID .. 105] = "Торба с обяд", -- Bag Lunch
    [T_ID .. 106] = "Изгубен корк", -- Lost Cork
    [T_ID .. 107] = "Гарваново сърце", -- Crow Heart
    [T_ID .. 108] = "Орехче", -- Walnut
    [T_ID .. 109] = "Скоч", -- Duct Tape
    [T_ID .. 110] = "Сребърен долар", -- Silver Dollar
    [T_ID .. 111] = "Кървава корона", -- Bloody Crown
    [T_ID .. 112] = "Платете и спечелете", -- Pay To Win
    [T_ID .. 113] = "Насекомо на Войната", -- Locust of War
    [T_ID .. 114] = "Насекомо на Заразата", -- Locust of Pestilence
    [T_ID .. 115] = "Насекомо на Глада", -- Locust of Famine
    [T_ID .. 116] = "Насекомо на Смъртта", -- Locust of Death
    [T_ID .. 117] = "Насекомо на Завоевателя", -- Locust of Conquest
    [T_ID .. 118] = "Крило от прилеп", -- Bat Wing
    [T_ID .. 119] = "Стволова клетка", -- Stem Cell
    [T_ID .. 120] = "Фиба за коса", -- Hairpin
    [T_ID .. 121] = "Дървен кръст", -- Wooden Cross
    [T_ID .. 122] = "Масло!", -- Butter!
    [T_ID .. 123] = "Филигранно перо", -- Filigree Feather
    [T_ID .. 124] = "Стопер за врата", -- Door Stop
    [T_ID .. 125] = "Удължител", -- Extension Cord
    [T_ID .. 126] = "Гнило пени", -- Rotten Penny
    [T_ID .. 127] = "Детски огъвател", -- Baby-Bender
    [T_ID .. 128] = "Кост от пръст", -- Finger Bone
    [T_ID .. 129] = "", -- Jawbreaker
    [T_ID .. 130] = "", -- Chewed Pen
    [T_ID .. 131] = "", -- Blessed Penny
    [T_ID .. 132] = "", -- Broken Syringe
    [T_ID .. 133] = "", -- Short Fuse
    [T_ID .. 134] = "", -- Gigante Bean
    [T_ID .. 135] = "", -- A Lighter
    [T_ID .. 136] = "", -- Broken Padlock
    [T_ID .. 137] = "", -- Myosotis
    [T_ID .. 138] = "", -- 'M
    [T_ID .. 139] = "", -- Teardrop Charm
    [T_ID .. 140] = "", -- Apple of Sodom
    [T_ID .. 141] = "", -- Forgotten Lullaby
    [T_ID .. 142] = "", -- Beth's Faith
    [T_ID .. 143] = "", -- Old Capacitor
    [T_ID .. 144] = "", -- Brain Worm
    [T_ID .. 145] = "", -- Perfection
    [T_ID .. 146] = "", -- Devil's Crown
    [T_ID .. 147] = "", -- Charged Penny
    [T_ID .. 148] = "", -- Friendship Necklace
    [T_ID .. 149] = "", -- Panic Button
    [T_ID .. 150] = "", -- Blue Key
    [T_ID .. 151] = "", -- Flat File
    [T_ID .. 152] = "", -- Telescope Lens
    [T_ID .. 153] = "", -- Mom's Lock
    [T_ID .. 154] = "", -- Dice Bag
    [T_ID .. 155] = "", -- Holy Crown
    [T_ID .. 156] = "", -- Mother's Kiss
    [T_ID .. 157] = "", -- Torn Card
    [T_ID .. 158] = "", -- Torn Pocket
    [T_ID .. 159] = "", -- Gilded Key
    [T_ID .. 160] = "", -- Lucky Sack
    [T_ID .. 161] = "", -- Wicked Crown
    [T_ID .. 162] = "", -- Azazel's Stump
    [T_ID .. 163] = "", -- Dingle Berry
    [T_ID .. 164] = "", -- Ring Cap
    [T_ID .. 165] = "", -- Nuh Uh!
    [T_ID .. 166] = "", -- Modeling Clay
    [T_ID .. 167] = "", -- Polished Bone
    [T_ID .. 168] = "", -- Hollow Heart
    [T_ID .. 169] = "", -- Kid's Drawing
    [T_ID .. 170] = "", -- Crystal Key
    [T_ID .. 171] = "", -- Keeper's Bargain
    [T_ID .. 172] = "", -- Cursed Penny
    [T_ID .. 173] = "", -- Your Soul
    [T_ID .. 174] = "", -- Number Magnet
    [T_ID .. 175] = "", -- Strange Key
    [T_ID .. 176] = "", -- Lil Clot
    [T_ID .. 177] = "", -- Temporary Tattoo
    [T_ID .. 178] = "", -- Swallowed M80
    [T_ID .. 179] = "", -- RC Remote
    [T_ID .. 180] = "", -- Found Soul
    [T_ID .. 181] = "", -- Expansion Pack
    [T_ID .. 182] = "", -- Beth's Essence
    [T_ID .. 183] = "", -- The Twins
    [T_ID .. 184] = "", -- Adoption Papers
    [T_ID .. 185] = "", -- Cricket Leg
    [T_ID .. 186] = "", -- Apollyon's Best Friend
    [T_ID .. 187] = "", -- Broken Glasses
    [T_ID .. 188] = "", -- Ice Cube
    [T_ID .. 189] = "", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Глупакът", -- 0 - The Fool
    [Card_ID .. 2] = "I - Магьосникът", -- I - The Magician
    [Card_ID .. 3] = "II - Върховната жрица", -- II - The High Priestess
    [Card_ID .. 4] = "III - Императрицата", -- III - The Empress
    [Card_ID .. 5] = "IV - Императорът", -- IV - The Emperor
    [Card_ID .. 6] = "V - Йерофантът", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Влюбените", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Колесницата", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Справедливост", -- VIII - Justice
    [Card_ID .. 10] = "IX - Отшелникът", -- IX - The Hermit
    [Card_ID .. 11] = "X - Колелото на съдбата", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Сила", -- XI - Strength
    [Card_ID .. 13] = "XII - Обесеният", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Смърт", -- XIII - Death
    [Card_ID .. 15] = "XIV - Умереност", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Дяволът", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Кулата", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Звездите", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Луната", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Слънцето", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Съд", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Светът", -- XXI - The World
    [Card_ID .. 23] = "Двойка спатии", -- 2 of Clubs
    [Card_ID .. 24] = "Двойка кари", -- 2 of Diamonds
    [Card_ID .. 25] = "Двойка пики", -- 2 of Spades
    [Card_ID .. 26] = "Двойка купи", -- 2 of Hearts
    [Card_ID .. 27] = "Асо спатии", -- Ace of Clubs
    [Card_ID .. 28] = "Асо кари", -- Ace of Diamonds
    [Card_ID .. 29] = "Асо пики", -- Ace of Spades
    [Card_ID .. 30] = "Асо купи", -- Ace of Hearts
    [Card_ID .. 31] = "Жокер", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Празна руна", -- Blank Rune
    [Card_ID .. 41] = "Черна руна", -- Black Rune
    [Card_ID .. 42] = "Хаос карта", -- Chaos Card
    [Card_ID .. 43] = "Кредитна карта", -- Credit Card
    [Card_ID .. 44] = "Карта с правила", -- Rules Card
    [Card_ID .. 45] = "Карта срещу човечеството", -- A Card Against Humanity
    [Card_ID .. 46] = "Крал-самоубиец", -- Suicide King
    [Card_ID .. 47] = "Карта \"Излез от затвора\"", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "? карта", -- ? Card
    [Card_ID .. 49] = "Парче от зарче", -- Dice Shard
    [Card_ID .. 50] = "Спешен контакт", -- Emergency Contact
    [Card_ID .. 51] = "Свещена карта", -- Holy Card
    [Card_ID .. 52] = "Огромен растеж", -- Huge Growth
    [Card_ID .. 53] = "Древен спомен", -- Ancient Recall
    [Card_ID .. 54] = "Вековен поход", -- Era Walk
    [Card_ID .. 55] = "", -- Rune Shard
    [Card_ID .. 56] = "", -- 0 - The Fool?
    [Card_ID .. 57] = "", -- I - The Magician?
    [Card_ID .. 58] = "", -- II - The High Priestess?
    [Card_ID .. 59] = "", -- III - The Empress?
    [Card_ID .. 60] = "", -- IV - The Emperor?
    [Card_ID .. 61] = "", -- V - The Hierophant?
    [Card_ID .. 62] = "", -- VI - The Lovers?
    [Card_ID .. 63] = "", -- VII - The Chariot?
    [Card_ID .. 64] = "", -- VIII - Justice?
    [Card_ID .. 65] = "", -- IX - The Hermit?
    [Card_ID .. 66] = "", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "", -- XI - Strength?
    [Card_ID .. 68] = "", -- XII - The Hanged Man?
    [Card_ID .. 69] = "", -- XIII - Death?
    [Card_ID .. 70] = "", -- XIV - Temperance?
    [Card_ID .. 71] = "", -- XV - The Devil?
    [Card_ID .. 72] = "", -- XVI - The Tower?
    [Card_ID .. 73] = "", -- XVII - The Stars?
    [Card_ID .. 74] = "", -- XVIII - The Moon?
    [Card_ID .. 75] = "", -- XIX - The Sun?
    [Card_ID .. 76] = "", -- XX - Judgement?
    [Card_ID .. 77] = "", -- XXI - The World?
    [Card_ID .. 78] = "", -- Cracked Key
    [Card_ID .. 79] = "", -- Queen of Hearts
    [Card_ID .. 80] = "", -- Wild Card
    [Card_ID .. 81] = "", -- Soul of Isaac
    [Card_ID .. 82] = "", -- Soul of Magdalene
    [Card_ID .. 83] = "", -- Soul of Cain
    [Card_ID .. 84] = "", -- Soul of Judas
    [Card_ID .. 85] = "", -- Soul of ???
    [Card_ID .. 86] = "", -- Soul of Eve
    [Card_ID .. 87] = "", -- Soul of Samson
    [Card_ID .. 88] = "", -- Soul of Azazel
    [Card_ID .. 89] = "", -- Soul of Lazarus
    [Card_ID .. 90] = "", -- Soul of Eden
    [Card_ID .. 91] = "", -- Soul of the Lost
    [Card_ID .. 92] = "", -- Soul of Lilith
    [Card_ID .. 93] = "", -- Soul of the Keeper
    [Card_ID .. 94] = "", -- Soul of Apollyon
    [Card_ID .. 95] = "", -- Soul of the Forgotten
    [Card_ID .. 96] = "", -- Soul of Bethany
    [Card_ID .. 97] = "", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "Неприятен газ", -- Bad Gas
    [Pill_ID .. 2] = "Лошо преживяване", -- Bad Trip
    [Pill_ID .. 3] = "Стоманени топки", -- Balls of Steel
    [Pill_ID .. 4] = "Бомбите са Ключ", -- Bombs are Key
    [Pill_ID .. 5] = "Екплозивна диария", -- Explosive Diarrhea
    [Pill_ID .. 6] = "Пълно здраве", -- Full Health
    [Pill_ID .. 7] = "По-малко здраве", -- Health Down
    [Pill_ID .. 8] = "Повече здраве", -- Health Up
    [Pill_ID .. 9] = "Намерих хапче", -- I Found Pills
    [Pill_ID .. 10] = "Пубертет", -- Puberty
    [Pill_ID .. 11] = "Хубава муха", -- Pretty Fly
    [Pill_ID .. 12] = "По-малко обхват", -- Range Down
    [Pill_ID .. 13] = "Повече обхват", -- Range Up
    [Pill_ID .. 14] = "По-малко скорост", -- Speed Down
    [Pill_ID .. 15] = "Повече скорост", -- Speed Up
    [Pill_ID .. 16] = "По-малко скорост на стреляне", -- Tears Down
    [Pill_ID .. 17] = "Повече скорост на стреляне", -- Tears Up
    [Pill_ID .. 18] = "По-малко късмет", -- Luck Down
    [Pill_ID .. 19] = "Повече късмет", -- Luck Up
    [Pill_ID .. 20] = "Телехапче", -- Telepills
    [Pill_ID .. 21] = "48-часова енергия!", -- 48 Hour Energy!
    [Pill_ID .. 22] = "Хематемеза", -- Hematemesis
    [Pill_ID .. 23] = "Парализа", -- Paralysis
    [Pill_ID .. 24] = "Мога да видя всичко!", -- I can see forever!
    [Pill_ID .. 25] = "Феромони", -- Pheromones
    [Pill_ID .. 26] = "Амнезия", -- Amnesia
    [Pill_ID .. 27] = "Лимоново парти", -- Lemon Party
    [Pill_ID .. 28] = "Ти магьосник ли си?", -- R U A Wizard?
    [Pill_ID .. 29] = "Обезболяващи", -- Percs!
    [Pill_ID .. 30] = "Пристрастен!", -- Addicted!
    [Pill_ID .. 31] = "Ре-Лакс", -- Re-Lax
    [Pill_ID .. 32] = "???", -- ???
    [Pill_ID .. 33] = "От едно ставаш по-голям", -- One makes you larger
    [Pill_ID .. 34] = "От едно ставаш по-малък", -- One makes you small
    [Pill_ID .. 35] = "Заразен!", -- Infested!
    [Pill_ID .. 36] = "Заразен?", -- Infested?
    [Pill_ID .. 37] = "Силово хапче!", -- Power Pill!
    [Pill_ID .. 38] = "Ретро визия", -- Retro Vision
    [Pill_ID .. 39] = "Приятели до края!", -- Friends Till The End!
    [Pill_ID .. 40] = "Екс-лакс", -- X-Lax
    [Pill_ID .. 41] = "Нещо не е наред...", -- Something's wrong...
    [Pill_ID .. 42] = "Сънлив съм...", -- I'm Drowsy...
    [Pill_ID .. 43] = "Възбуден съм!!!", -- I'm Excited!!
    [Pill_ID .. 44] = "Глът!", -- Gulp!
    [Pill_ID .. 45] = "Horf!", -- Horf!
    [Pill_ID .. 46] = "Сякаш ходя по дъгата!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "Vurp!", -- Vurp!
    [Pill_ID .. 48] = "", -- Shot speed Down
    [Pill_ID .. 49] = "", -- Shot speed Up
    [Pill_ID .. 9999] = "Zlatá Pilulka", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])