-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "cs_cz"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Smutná Cibulka", -- The Sad Onion
    [C_ID .. 2] = "Vnitřní Oko", -- The Inner Eye
    [C_ID .. 3] = "Ohnutá Lžíce", -- Spoon Bender
    [C_ID .. 4] = "Kriketova Hlava", -- Cricket's Head
    [C_ID .. 5] = "Můj Odraz", -- My Reflection
    [C_ID .. 6] = "Číslo Jedna", -- Number One
    [C_ID .. 7] = "Krev Mučedníka", -- Blood of the Martyr
    [C_ID .. 8] = "Bráška Bobby", -- Brother Bobby
    [C_ID .. 9] = "Skatol", -- Skatole
    [C_ID .. 10] = "Kruh z Much", -- Halo of Flies
    [C_ID .. 11] = "1 Život!", -- 1up!
    [C_ID .. 12] = "Kouzelná Houba", -- Magic Mushroom
    [C_ID .. 13] = "Virus", -- The Virus
    [C_ID .. 14] = "Steroidový Vztek", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Syrová Játra", -- Raw Liver
    [C_ID .. 17] = "Kostlivcův Klíč", -- Skeleton Key
    [C_ID .. 18] = "Dolar", -- A Dollar
    [C_ID .. 19] = "Bum!", -- Boom!
    [C_ID .. 20] = "Transcendence", -- Transcendence
    [C_ID .. 21] = "Kompas", -- The Compass
    [C_ID .. 22] = "Oběd", -- Lunch
    [C_ID .. 23] = "Večeře", -- Dinner
    [C_ID .. 24] = "Dezert", -- Dessert
    [C_ID .. 25] = "Snídaně", -- Breakfast
    [C_ID .. 26] = "Shnilé Maso", -- Rotten Meat
    [C_ID .. 27] = "Vařečka", -- Wooden Spoon
    [C_ID .. 28] = "Pásek", -- The Belt
    [C_ID .. 29] = "Mámino Spodní Prádlo", -- Mom's Underwear
    [C_ID .. 30] = "Máminy Podpatky", -- Mom's Heels
    [C_ID .. 31] = "Mámina Rtěnka", -- Mom's Lipstick
    [C_ID .. 32] = "Drátěný Věšák", -- Wire Coat Hanger
    [C_ID .. 33] = "Bible", -- The Bible
    [C_ID .. 34] = "Kniha Belialova", -- The Book of Belial
    [C_ID .. 35] = "Necronomicon", -- The Necronomicon
    [C_ID .. 36] = "Hovno", -- The Poop
    [C_ID .. 37] = "Pan Bum!", -- Mr. Boom
    [C_ID .. 38] = "Tammyho Hlava", -- Tammy's Head
    [C_ID .. 39] = "Mámina Podprsenka", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Mámina Vložka", -- Mom's Pad
    [C_ID .. 42] = "Bobova Shnilá Hlava", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teleport", -- Teleport!
    [C_ID .. 45] = "Mňamka Srdce", -- Yum Heart
    [C_ID .. 46] = "Šťastná Noha", -- Lucky Foot
    [C_ID .. 47] = "Doktorův Dálkový Ovladač", -- Doctor's Remote
    [C_ID .. 48] = "Amorův Šíp", -- Cupid's Arrow
    [C_ID .. 49] = "Shoop da Whoop!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagram", -- Pentagram
    [C_ID .. 52] = "Dr. Zárodek", -- Dr. Fetus
    [C_ID .. 53] = "Magneto", -- Magneto
    [C_ID .. 54] = "Mapa Pokladů", -- Treasure Map
    [C_ID .. 55] = "Mámino Oko", -- Mom's Eye
    [C_ID .. 56] = "Citronová Nehoda", -- Lemon Mishap
    [C_ID .. 57] = "Vzdálený Obdiv", -- Distant Admiration
    [C_ID .. 58] = "Kniha Stínů", -- Book of Shadows
    [C_ID .. 59] = "Kniha Belialova", -- The Book of Belial
    [C_ID .. 60] = "Žebřík", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Okouzlení Upíra", -- Charm of the Vampire
    [C_ID .. 63] = "Baterie", -- The Battery
    [C_ID .. 64] = "Výprodej na Steamu", -- Steam Sale
    [C_ID .. 65] = "Anarchistická Kuchařka", -- Anarchist Cookbook
    [C_ID .. 66] = "Přesýpací Hodiny", -- The Hourglass
    [C_ID .. 67] = "Ségra Maggy", -- Sister Maggy
    [C_ID .. 68] = "Technologie", -- Technology
    [C_ID .. 69] = "Čokoládové Mléko", -- Chocolate Milk
    [C_ID .. 70] = "Růstové Hormony", -- Growth Hormones
    [C_ID .. 71] = "Mini Houbička", -- Mini Mush
    [C_ID .. 72] = "Růženec", -- Rosary
    [C_ID .. 73] = "Kostka Masa", -- Cube of Meat
    [C_ID .. 74] = "Čtvrťák", -- A Quarter
    [C_ID .. 75] = "PHD", -- PHD
    [C_ID .. 76] = "Rentgenové Vidění", -- X-Ray Vision
    [C_ID .. 77] = "Můj Malý Jednorožec", -- My Little Unicorn
    [C_ID .. 78] = "Kniha Zjevení", -- Book of Revelations
    [C_ID .. 79] = "Značka", -- The Mark
    [C_ID .. 80] = "Pakt", -- The Pact
    [C_ID .. 81] = "Mrtvá Kočka", -- Dead Cat
    [C_ID .. 82] = "Lord Podzemí", -- Lord of the Pit
    [C_ID .. 83] = "Hřebík", -- The Nail
    [C_ID .. 84] = "Musíme jít hlouběji!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Balíček Karet", -- Deck of Cards
    [C_ID .. 86] = "Monstrův Zub", -- Monstro's Tooth
    [C_ID .. 87] = "Lokiho Rohy", -- Loki's Horns
    [C_ID .. 88] = "Malý Tlouštík", -- Little Chubby
    [C_ID .. 89] = "Pavoučí Kousnutí", -- Spider Bite
    [C_ID .. 90] = "Malý Kamínek", -- The Small Rock
    [C_ID .. 91] = "Horníkova Helma", -- Spelunker Hat
    [C_ID .. 92] = "Super Obvaz", -- Super Bandage
    [C_ID .. 93] = "Gamekid", -- The Gamekid
    [C_ID .. 94] = "Pytel Peněz", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Děcko", -- Robo-Baby
    [C_ID .. 96] = "Malý C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "Kniha Hříchu", -- The Book of Sin
    [C_ID .. 98] = "Relikvie", -- The Relic
    [C_ID .. 99] = "Malý Gish", -- Little Gish
    [C_ID .. 100] = "Malý Steven", -- Little Steven
    [C_ID .. 101] = "Svatozář", -- The Halo
    [C_ID .. 102] = "Mámina Lahvička s Pilulky", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Běžná Chřipka", -- The Common Cold
    [C_ID .. 104] = "Parazit", -- The Parasite
    [C_ID .. 105] = "D6", -- The D6
    [C_ID .. 106] = "Pan Mega", -- Mr. Mega
    [C_ID .. 107] = "Velké Nůžky", -- The Pinking Shears
    [C_ID .. 108] = "Oplatka", -- The Wafer
    [C_ID .. 109] = "Peníze = Moc", -- Money = Power
    [C_ID .. 110] = "Mámina Kontaktní Čočka", -- Mom's Contacts
    [C_ID .. 111] = "Fazole", -- The Bean
    [C_ID .. 112] = "Anděl Strážný", -- Guardian Angel
    [C_ID .. 113] = "Démoní Děcko", -- Demon Baby
    [C_ID .. 114] = "Mámin Nůž", -- Mom's Knife
    [C_ID .. 115] = "Ouija Deska", -- Ouija Board
    [C_ID .. 116] = "9-Voltovka", -- 9 Volt
    [C_ID .. 117] = "Mrtvý Pták", -- Dead Bird
    [C_ID .. 118] = "Brimstone", -- Brimstone
    [C_ID .. 119] = "Sáček s Krví", -- Blood Bag
    [C_ID .. 120] = "Zvláštní Houba (malá)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Zvláštní Houba (Velká)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Děvka Babylonská", -- Whore of Babylon
    [C_ID .. 123] = "Manuál Příšer", -- Monster Manual
    [C_ID .. 124] = "Svitky od Mrtvého Moře", -- Dead Sea Scrolls
    [C_ID .. 125] = "Polda-Bomba", -- Bobby-Bomb
    [C_ID .. 126] = "Žiletka", -- Razor Blade
    [C_ID .. 127] = "Zapomeň na Mě", -- Forget Me Now
    [C_ID .. 128] = "Navždy Sám", -- Forever Alone
    [C_ID .. 129] = "Kbelík Sádla", -- Bucket of Lard
    [C_ID .. 130] = "Poník", -- A Pony
    [C_ID .. 131] = "Pytel Bomb", -- Bomb Bag
    [C_ID .. 132] = "Hrouda Uhlí", -- A Lump of Coal
    [C_ID .. 133] = "Guppyho Tlapka", -- Guppy's Paw
    [C_ID .. 134] = "Guppyho Ocas", -- Guppy's Tail
    [C_ID .. 135] = "Infuzní vak", -- IV Bag
    [C_ID .. 136] = "Nejlepší Kámoš", -- Best Friend
    [C_ID .. 137] = "Dálková Rozbuška", -- Remote Detonator
    [C_ID .. 138] = "Stigmata", -- Stigmata
    [C_ID .. 139] = "Mámina Kabelka", -- Mom's Purse
    [C_ID .. 140] = "Bobova Kletba", -- Bob's Curse
    [C_ID .. 141] = "Král Krásy", -- Pageant Boy
    [C_ID .. 142] = "Škapulíř", -- Scapular
    [C_ID .. 143] = "Rychlokoule", -- Speed Ball
    [C_ID .. 144] = "Žebrácký Kámoš", -- Bum Friend
    [C_ID .. 145] = "Guppyho Hlava", -- Guppy's Head
    [C_ID .. 146] = "Modlitební Obrázek", -- Prayer Card
    [C_ID .. 147] = "Notchův Krumpáč", -- Notched Axe
    [C_ID .. 148] = "Zamoření", -- Infestation
    [C_ID .. 149] = "Ipekak", -- Ipecac
    [C_ID .. 150] = "Tvrdá Láska", -- Tough Love
    [C_ID .. 151] = "Mulligan", -- The Mulligan
    [C_ID .. 152] = "Technologie 2", -- Technology 2
    [C_ID .. 153] = "Mutantní Pavouk", -- Mutant Spider
    [C_ID .. 154] = "Chemické Oloupání", -- Chemical Peel
    [C_ID .. 155] = "Kukadlo", -- The Peeper
    [C_ID .. 156] = "Hábit", -- Habit
    [C_ID .. 157] = "Krvavá Chtíč", -- Bloody Lust
    [C_ID .. 158] = "Křišťálová Koule", -- Crystal Ball
    [C_ID .. 159] = "Přízrak Soumraku", -- Spirit of the Night
    [C_ID .. 160] = "Prolomení Oblohy", -- Crack the Sky
    [C_ID .. 161] = "Ankh", -- Ankh
    [C_ID .. 162] = "Keltský Kříž", -- Celtic Cross
    [C_ID .. 163] = "Duchařské dítě", -- Ghost Baby
    [C_ID .. 164] = "Modrá Svíčka", -- The Candle
    [C_ID .. 165] = "Devítiocasá Kočka", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Harlekýnské Dítě", -- Harlequin Baby
    [C_ID .. 168] = "Epický Zárodek", -- Epic Fetus
    [C_ID .. 169] = "Polyfémos", -- Polyphemus
    [C_ID .. 170] = "Taťka Dlouhonožka", -- Daddy Longlegs
    [C_ID .. 171] = "Pavoučí Prdel", -- Spider Butt
    [C_ID .. 172] = "Obětní Dýka", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitra", -- Mitre
    [C_ID .. 174] = "Duhové Dítě", -- Rainbow Baby
    [C_ID .. 175] = "Tátův Klíč", -- Dad's Key
    [C_ID .. 176] = "Kmenové Buňky", -- Stem Cells
    [C_ID .. 177] = "Přenosný Automat", -- Portable Slot
    [C_ID .. 178] = "Svěcená Voda", -- Holy Water
    [C_ID .. 179] = "Osud", -- Fate
    [C_ID .. 180] = "Černá Fazole", -- The Black Bean
    [C_ID .. 181] = "Bílý Poník", -- White Pony
    [C_ID .. 182] = "Nejsvětější Srdce", -- Sacred Heart
    [C_ID .. 183] = "Párátka", -- Tooth Picks
    [C_ID .. 184] = "Svatý Grál", -- Holy Grail
    [C_ID .. 185] = "Mrtvá Holubice", -- Dead Dove
    [C_ID .. 186] = "Pokrevní Práva", -- Blood Rights
    [C_ID .. 187] = "Guppyho Chlupatá Koule", -- Guppy's Hairball
    [C_ID .. 188] = "Ábel", -- Abel
    [C_ID .. 189] = "SMB Super Fanda", -- SMB Super Fan
    [C_ID .. 190] = "Pyro", -- Pyro
    [C_ID .. 191] = "3 Dolarová Bankovka", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepatie pro Blbečky", -- Telepathy for Dummies
    [C_ID .. 193] = "MASO!", -- MEAT!
    [C_ID .. 194] = "Magická Koule 8", -- Magic 8 Ball
    [C_ID .. 195] = "Mámina Peněženka", -- Mom's Coin Purse
    [C_ID .. 196] = "Mačkátko", -- Squeezy
    [C_ID .. 197] = "Ježíšův Džus", -- Jesus Juice
    [C_ID .. 198] = "Krabice", -- Box
    [C_ID .. 199] = "Mámin Klíč", -- Mom's Key
    [C_ID .. 200] = "Máminy Oční Stíny", -- Mom's Eyeshadow
    [C_ID .. 201] = "Železná Cihla", -- Iron Bar
    [C_ID .. 202] = "Midasův Dotek", -- Midas' Touch
    [C_ID .. 203] = "Skromný Balíček", -- Humbleing Bundle
    [C_ID .. 204] = "Ledvinka", -- Fanny Pack
    [C_ID .. 205] = "Ostrá Zástrčka", -- Sharp Plug
    [C_ID .. 206] = "Gilotina", -- Guillotine
    [C_ID .. 207] = "Koule z Obvazů", -- Ball of Bandages
    [C_ID .. 208] = "Pás Šampionů", -- Champion Belt
    [C_ID .. 209] = "Prdelní Bomby", -- Butt Bombs
    [C_ID .. 210] = "Ohlodaný List", -- Gnawed Leaf
    [C_ID .. 211] = "Pavoučí Miláček", -- Spiderbaby
    [C_ID .. 212] = "Guppyho Obojek", -- Guppy's Collar
    [C_ID .. 213] = "Ztracená Čočka", -- Lost Contact
    [C_ID .. 214] = "Anémie (Chudokrevost)", -- Anemic
    [C_ID .. 215] = "Kozí Hlava", -- Goat Head
    [C_ID .. 216] = "Obřadní Róba", -- Ceremonial Robes
    [C_ID .. 217] = "Maminčina Paruka", -- Mom's Wig
    [C_ID .. 218] = "Placenta", -- Placenta
    [C_ID .. 219] = "Starý Obvaz", -- Old Bandage
    [C_ID .. 220] = "Smutné Bomby", -- Sad Bombs
    [C_ID .. 221] = "Gumový Cement", -- Rubber Cement
    [C_ID .. 222] = "Anti-Gravitace", -- Anti-Gravity
    [C_ID .. 223] = "Pyromaniak", -- Pyromaniac
    [C_ID .. 224] = "Kriketovo Tělo", -- Cricket's Body
    [C_ID .. 225] = "Fetišista", -- Gimpy
    [C_ID .. 226] = "Černý Lotus", -- Black Lotus
    [C_ID .. 227] = "Prasátko", -- Piggy Bank
    [C_ID .. 228] = "Maminčin Parfém", -- Mom's Perfume
    [C_ID .. 229] = "Monstrova plíce", -- Monstro's Lung
    [C_ID .. 230] = "Abaddón", -- Abaddon
    [C_ID .. 231] = "Koule Dehtu", -- Ball of Tar
    [C_ID .. 232] = "Stopky", -- Stop Watch
    [C_ID .. 233] = "Maličká Planetka", -- Tiny Planet
    [C_ID .. 234] = "Zamoření 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "Dotek Smrti", -- Death's Touch
    [C_ID .. 238] = "První Část Klíče", -- Key Piece 1
    [C_ID .. 239] = "Druhá Část Klíče", -- Key Piece 2
    [C_ID .. 240] = "Experimentální Léčba", -- Experimental Treatment
    [C_ID .. 241] = "Smlouva z Podzemí", -- Contract from Below
    [C_ID .. 242] = "Hanba", -- Infamy
    [C_ID .. 243] = "Štít Nejsvětější Trojice", -- Trinity Shield
    [C_ID .. 244] = "Tech.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Modrá Mapa", -- Blue Map
    [C_ID .. 247] = "NEJKY!", -- BFFS!
    [C_ID .. 248] = "Úlové Myšlení", -- Hive Mind
    [C_ID .. 249] = "Jsou Tu Možnosti", -- There's Options
    [C_ID .. 250] = "1+1 Bomby", -- Bogo Bombs
    [C_ID .. 251] = "Začátečnický Balíček", -- Starter Deck
    [C_ID .. 252] = "Malý Pytlík", -- Little Baggy
    [C_ID .. 253] = "Kouzelný Strup", -- Magic Scab
    [C_ID .. 254] = "Krevní Sraženina", -- Blood Clot
    [C_ID .. 255] = "Šroub", -- Screw
    [C_ID .. 256] = "Horké Bomby", -- Hot Bombs
    [C_ID .. 257] = "Ohnivá Mysl", -- Fire Mind
    [C_ID .. 258] = "Chybějící č.", -- Missing No.
    [C_ID .. 259] = "Temná Hmota", -- Dark Matter
    [C_ID .. 260] = "Černá Svíčka", -- Black Candle
    [C_ID .. 261] = "Proptóza", -- Proptosis
    [C_ID .. 262] = "Chybějící stránka 2", -- Missing Page 2
    [C_ID .. 263] = "Čistá Runa", -- Clear Rune
    [C_ID .. 264] = "Chytrá Muška", -- Smart Fly
    [C_ID .. 265] = "Vysušené Dítě", -- Dry Baby
    [C_ID .. 266] = "Šťavnatý Kokon", -- Juicy Sack
    [C_ID .. 267] = "Robo-Děcko 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Shnilé Děcko", -- Rotten Baby
    [C_ID .. 269] = "Bezhlavé Dítě", -- Headless Baby
    [C_ID .. 270] = "Pijavice", -- Leech
    [C_ID .. 271] = "Tajemný Pytel", -- Mystery Sack
    [C_ID .. 272] = "VKM (Velká Kamarádská Moucha)", -- BBF
    [C_ID .. 273] = "Bobův Mozek", -- Bob's Brain
    [C_ID .. 274] = "Nejlepší Kámoš", -- Best Bud
    [C_ID .. 275] = "Malej Brimstone", -- Lil Brimstone
    [C_ID .. 276] = "Izákovo Srdce", -- Isaac's Heart
    [C_ID .. 277] = "Maličký Bubák", -- Lil Haunt
    [C_ID .. 278] = "Temný Žebrák", -- Dark Bum
    [C_ID .. 279] = "Velký Fanda", -- Big Fan
    [C_ID .. 280] = "Sissy Dlouhonožka", -- Sissy Longlegs
    [C_ID .. 281] = "Boxovací Pytel", -- Punching Bag
    [C_ID .. 282] = "Jak Skákat", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Prázdná Karta", -- Blank Card
    [C_ID .. 287] = "Kniha Tajemství", -- Book of Secrets
    [C_ID .. 288] = "Krabice Plná Pavouků", -- Box of Spiders
    [C_ID .. 289] = "Červená Svíčka", -- Red Candle
    [C_ID .. 290] = "Sklenice", -- The Jar
    [C_ID .. 291] = "Spláchnutej!", -- Flush!
    [C_ID .. 292] = "Satanská Bible", -- Satanic Bible
    [C_ID .. 293] = "Krampusova Hlava", -- Head of Krampus
    [C_ID .. 294] = "Máslová Fazole", -- Butter Bean
    [C_ID .. 295] = "Kouzelné Prstíky", -- Magic Fingers
    [C_ID .. 296] = "Konvertor", -- Converter
    [C_ID .. 297] = "Pandořina Skříňka", -- Pandora's Box
    [C_ID .. 298] = "Jednorožčí Kopyto", -- Unicorn Stump
    [C_ID .. 299] = "Býk", -- Taurus
    [C_ID .. 300] = "Beran", -- Aries
    [C_ID .. 301] = "Rak", -- Cancer
    [C_ID .. 302] = "Lev", -- Leo
    [C_ID .. 303] = "Panna", -- Virgo
    [C_ID .. 304] = "Váha", -- Libra
    [C_ID .. 305] = "Štír", -- Scorpio
    [C_ID .. 306] = "Střelec", -- Sagittarius
    [C_ID .. 307] = "Kozoroh", -- Capricorn
    [C_ID .. 308] = "Vodnář", -- Aquarius
    [C_ID .. 309] = "Ryby", -- Pisces
    [C_ID .. 310] = "Evina Řasenka", -- Eve's Mascara
    [C_ID .. 311] = "Jidášův Stín", -- Judas' Shadow
    [C_ID .. 312] = "Maggyina Mašle", -- Maggy's Bow
    [C_ID .. 313] = "Svatý Plášť", -- Holy Mantle
    [C_ID .. 314] = "Boky Jako Skříň", -- Thunder Thighs
    [C_ID .. 315] = "Podivný Přitahovák", -- Strange Attractor
    [C_ID .. 316] = "Prokleté Oko", -- Cursed Eye
    [C_ID .. 317] = "Záhadná Kapalina", -- Mysterious Liquid
    [C_ID .. 318] = "Blíženec", -- Gemini
    [C_ID .. 319] = "Kainovo Druhé Oko", -- Cain's Other Eye
    [C_ID .. 320] = "Jediný Přítel ???", -- ???'s Only Friend
    [C_ID .. 321] = "Samsonovy Řetězy", -- Samson's Chains
    [C_ID .. 322] = "Divné Dítě", -- Mongo Baby
    [C_ID .. 323] = "Izákovy Slzy", -- Isaac's Tears
    [C_ID .. 324] = "Nedefinováno", -- Undefined
    [C_ID .. 325] = "Nůžky", -- Scissors
    [C_ID .. 326] = "Dech Života", -- Breath of Life
    [C_ID .. 327] = "Polaroid", -- The Polaroid
    [C_ID .. 328] = "Negativ", -- The Negative
    [C_ID .. 329] = "Technika Ludovico", -- The Ludovico Technique
    [C_ID .. 330] = "Sójové Mléko", -- Soy Milk
    [C_ID .. 331] = "Božství", -- Godhead
    [C_ID .. 332] = "Lazarovy Hadry", -- Lazarus' Rags
    [C_ID .. 333] = "Mysl", -- The Mind
    [C_ID .. 334] = "Tělo", -- The Body
    [C_ID .. 335] = "Duše", -- The Soul
    [C_ID .. 336] = "Mrtvá Cibulka", -- Dead Onion
    [C_ID .. 337] = "Rozbité Hodinky", -- Broken Watch
    [C_ID .. 338] = "Bumerang", -- The Boomerang
    [C_ID .. 339] = "Spínací Špendlík", -- Safety Pin
    [C_ID .. 340] = "Kofeinová Pilulka", -- Caffeine Pill
    [C_ID .. 341] = "Roztrhaná Fotografie", -- Torn Photo
    [C_ID .. 342] = "Modrý Klobouček", -- Blue Cap
    [C_ID .. 343] = "Klíč od Petlice", -- Latch Key
    [C_ID .. 344] = "Zápalky", -- Match Book
    [C_ID .. 345] = "Synthol (steroidy)", -- Synthoil
    [C_ID .. 346] = "Svačina", -- A Snack
    [C_ID .. 347] = "Diplopie", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Dřevěný Niklák", -- Wooden Nickel
    [C_ID .. 350] = "Toxický Šok", -- Toxic Shock
    [C_ID .. 351] = "Mega Fazole", -- Mega Bean
    [C_ID .. 352] = "Skleněné Dělo", -- Glass Cannon
    [C_ID .. 353] = "Bomber Kluk", -- Bomber Boy
    [C_ID .. 354] = "Crack-Jackův Karamelový Popcorn", -- Crack Jacks
    [C_ID .. 355] = "Máminy Perly", -- Mom's Pearls
    [C_ID .. 356] = "Autobaterie", -- Car Battery
    [C_ID .. 357] = "Krabice s Kamarády", -- Box of Friends
    [C_ID .. 358] = "Čaroděj", -- The Wiz
    [C_ID .. 359] = "8 Palcové Hřebíky", -- 8 Inch Nails
    [C_ID .. 360] = "Inkubus", -- Incubus
    [C_ID .. 361] = "Odměna Osudu", -- Fate's Reward
    [C_ID .. 362] = "Maličká Truhla", -- Lil Chest
    [C_ID .. 363] = "Zapřísáhlý Ochránce", -- Sworn Protector
    [C_ID .. 364] = "Friend Zone", -- Friend Zone
    [C_ID .. 365] = "Ztracená Moucha", -- Lost Fly
    [C_ID .. 366] = "Rozptylové Bomby", -- Scatter Bombs
    [C_ID .. 367] = "Lepkavé Bomby", -- Sticky Bombs
    [C_ID .. 368] = "Epifora", -- Epiphora
    [C_ID .. 369] = "Kontinuum", -- Continuum
    [C_ID .. 370] = "Panenka", -- Mr. Dolly
    [C_ID .. 371] = "Prokletí Věže", -- Curse of the Tower
    [C_ID .. 372] = "Nabité Dítě", -- Charged Baby
    [C_ID .. 373] = "Ostrostřelec", -- Dead Eye
    [C_ID .. 374] = "Posvátné Světlo", -- Holy Light
    [C_ID .. 375] = "Hostitelova Lebka", -- Host Hat
    [C_ID .. 376] = "Doplnění Zásob", -- Restock
    [C_ID .. 377] = "Prasklý Kokon", -- Bursting Sack
    [C_ID .. 378] = "Číslo Dva", -- No. 2
    [C_ID .. 379] = "Duplexní Pupila", -- Pupula Duplex
    [C_ID .. 380] = "Zaplať za hraní", -- Pay To Play
    [C_ID .. 381] = "Edenovo Požehnání", -- Eden's Blessing
    [C_ID .. 382] = "Kamarádský Míček", -- Friendly Ball
    [C_ID .. 383] = "Slzní Rozbuška", -- Tear Detonator
    [C_ID .. 384] = "Malý Gurdy", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Kadidelnice", -- Censer
    [C_ID .. 388] = "Klíčový Žebrák", -- Key Bum
    [C_ID .. 389] = "Pytlíček Run", -- Rune Bag
    [C_ID .. 390] = "Serafim", -- Seraphim
    [C_ID .. 391] = "Zrada", -- Betrayal
    [C_ID .. 392] = "Zvěrokruh", -- Zodiac
    [C_ID .. 393] = "Hadí Polibek", -- Serpent's Kiss
    [C_ID .. 394] = "Označený", -- Marked
    [C_ID .. 395] = "Technologie X", -- Tech X
    [C_ID .. 396] = "Komorová Břitva", -- Ventricle Razor
    [C_ID .. 397] = "Vlečný Paprsek", -- Tractor Beam
    [C_ID .. 398] = "Boží Maso", -- God's Flesh
    [C_ID .. 399] = "Chřtán Prázdnoty", -- Maw of the Void
    [C_ID .. 400] = "Kopí Osudu", -- Spear of Destiny
    [C_ID .. 401] = "Explozívo", -- Explosivo
    [C_ID .. 402] = "Chaos", -- Chaos
    [C_ID .. 403] = "Pavoučí Bot", -- Spider Mod
    [C_ID .. 404] = "Prdící Děcko", -- Farting Baby
    [C_ID .. 405] = "Hru Rozbíjející Chyba", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Čistota", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Prázdná Nádoba", -- Empty Vessel
    [C_ID .. 410] = "Oko Zla", -- Evil Eye
    [C_ID .. 411] = "Chutná Krev", -- Lusty Blood
    [C_ID .. 412] = "Početí Kambionu", -- Cambion Conception
    [C_ID .. 413] = "Neposkvrněné Početí", -- Immaculate Conception
    [C_ID .. 414] = "Více Možností", -- More Options
    [C_ID .. 415] = "Koruna Světla", -- Crown Of Light
    [C_ID .. 416] = "Hluboké Kapsy", -- Deep Pockets
    [C_ID .. 417] = "Sukubus", -- Succubus
    [C_ID .. 418] = "Ovocný Dort", -- Fruit Cake
    [C_ID .. 419] = "Teleport 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Černý Prášek", -- Black Powder
    [C_ID .. 421] = "Červená Fazole", -- Kidney Bean
    [C_ID .. 422] = "Zářící Přesýpací Hodiny", -- Glowing Hourglass
    [C_ID .. 423] = "Kruh Ochrany", -- Circle of Protection
    [C_ID .. 424] = "Pytel na Hlavu", -- Sack Head
    [C_ID .. 425] = "Noční Světlo", -- Night Light
    [C_ID .. 426] = "Posedlý Fanoušek", -- Obsessed Fan
    [C_ID .. 427] = "Mine Crafťák", -- Mine Crafter
    [C_ID .. 428] = "Pyžamo", -- PJs
    [C_ID .. 429] = "Keeperova Hlava", -- Head of the Keeper
    [C_ID .. 430] = "Táta Moucha", -- Papa Fly
    [C_ID .. 431] = "Multidimenzionální Dítě", -- Multidimensional Baby
    [C_ID .. 432] = "Třpytivé Bomby", -- Glitter Bombs
    [C_ID .. 433] = "Můj Stín", -- My Shadow
    [C_ID .. 434] = "Sklenice Much", -- Jar of Flies
    [C_ID .. 435] = "Maličký Loki", -- Lil Loki
    [C_ID .. 436] = "Mléko!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Dudlík", -- Binky
    [C_ID .. 439] = "Mámina Krabička", -- Mom's Box
    [C_ID .. 440] = "Ledvinový Kámen", -- Kidney Stone
    [C_ID .. 441] = "Mega Výstřel", -- Mega Blast
    [C_ID .. 442] = "Koruna Temného Prince", -- Dark Prince's Crown
    [C_ID .. 443] = "Jablko!", -- Apple!
    [C_ID .. 444] = "Tužka", -- Lead Pencil
    [C_ID .. 445] = "Psí Zub", -- Dog Tooth
    [C_ID .. 446] = "Mrtvý Zub", -- Dead Tooth
    [C_ID .. 447] = "Loudavá Fazole", -- Linger Bean
    [C_ID .. 448] = "Střípek Skla", -- Shard of Glass
    [C_ID .. 449] = "Kovový Plát", -- Metal Plate
    [C_ID .. 450] = "Greedovo Oko", -- Eye of Greed
    [C_ID .. 451] = "Tarotový Ubrus", -- Tarot Cloth
    [C_ID .. 452] = "Křečové Žíly", -- Varicose Veins
    [C_ID .. 453] = "Otevřená Zlomenina", -- Compound Fracture
    [C_ID .. 454] = "Polydaktylie", -- Polydactyly
    [C_ID .. 455] = "Tátova Ztracená Mince", -- Dad's Lost Coin
    [C_ID .. 456] = "Půlnoční Sváča", -- Midnight Snack
    [C_ID .. 457] = "Kuželová Hlava", -- Cone Head
    [C_ID .. 458] = "Pupík", -- Belly Button
    [C_ID .. 459] = "Sinusitida", -- Sinus Infection
    [C_ID .. 460] = "Glaukom", -- Glaucoma
    [C_ID .. 461] = "Parazitoid", -- Parasitoid
    [C_ID .. 462] = "Oko Belialovo", -- Eye of Belial
    [C_ID .. 463] = "Kyselina Sírová", -- Sulfuric Acid
    [C_ID .. 464] = "Symbol Rovnováhy", -- Glyph of Balance
    [C_ID .. 465] = "Analogová Páčka", -- Analog Stick
    [C_ID .. 466] = "Nákaza", -- Contagion
    [C_ID .. 467] = "Prst!", -- Finger!
    [C_ID .. 468] = "Stínovač", -- Shade
    [C_ID .. 469] = "Deprese", -- Depression
    [C_ID .. 470] = "Hushy", -- Hushy
    [C_ID .. 471] = "Maličký Monstro", -- Lil Monstro
    [C_ID .. 472] = "Královské Dítě", -- King Baby
    [C_ID .. 473] = "Velký Tlouštík", -- Big Chubby
    [C_ID .. 474] = "Rozbité Skleněné Dělo", -- Broken Glass Cannon
    [C_ID .. 475] = "Plán C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Prázdnota", -- Void
    [C_ID .. 478] = "Pauza", -- Pause
    [C_ID .. 479] = "Tavící Pec", -- Smelter
    [C_ID .. 480] = "Kompost", -- Compost
    [C_ID .. 481] = "Data Těžič", -- Dataminer
    [C_ID .. 482] = "TV Ovladač", -- Clicker
    [C_ID .. 483] = "Máma Mega!", -- Mama Mega!
    [C_ID .. 484] = "Počkat Co?", -- Wait What?
    [C_ID .. 485] = "Pokřivená Mince", -- Crooked Penny
    [C_ID .. 486] = "Tupá Žiletka", -- Dull Razor
    [C_ID .. 487] = "Škrabka na Brambory", -- Potato Peeler
    [C_ID .. 488] = "Metronom", -- Metronome
    [C_ID .. 489] = "D Nekonečno", -- D Infinity
    [C_ID .. 490] = "Edenova Duše", -- Eden's Soul
    [C_ID .. 491] = "LSD Dítě", -- Acid Baby
    [C_ID .. 492] = "HEJ POSLOUCHEJ!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenalin", -- Adrenaline
    [C_ID .. 494] = "Jákobův Žebřík", -- Jacob's Ladder
    [C_ID .. 495] = "Naga Jolokia (Chilli Paprička)", -- Ghost Pepper
    [C_ID .. 496] = "Eutanázie", -- Euthanasia
    [C_ID .. 497] = "Maskáčové Spodní Prádlo", -- Camo Undies
    [C_ID .. 498] = "Dualita", -- Duality
    [C_ID .. 499] = "Eucharistie", -- Eucharist
    [C_ID .. 500] = "Pytel Pytlů", -- Sack of Sacks
    [C_ID .. 501] = "Greedův Jícen", -- Greed's Gullet
    [C_ID .. 502] = "Velký Jebák", -- Large Zit
    [C_ID .. 503] = "Malej Horn", -- Little Horn
    [C_ID .. 504] = "Hnědý Nuget", -- Brown Nugget
    [C_ID .. 505] = "Poké Go", -- Poke Go
    [C_ID .. 506] = "Kudlou Do Zad", -- Backstabber
    [C_ID .. 507] = "Ostré Brčko", -- Sharp Straw
    [C_ID .. 508] = "Maminčin Holicí Strojek", -- Mom's Razor
    [C_ID .. 509] = "Krví Podlité Oko", -- Bloodshot Eye
    [C_ID .. 510] = "Blouznivec", -- Delirious
    [C_ID .. 511] = "Naštvaná Moucha", -- Angry Fly
    [C_ID .. 512] = "Černá Díra", -- Black Hole
    [C_ID .. 513] = "Klaun Bozo", -- Bozo
    [C_ID .. 514] = "Rozbitý Modem", -- Broken Modem
    [C_ID .. 515] = "Tajemný Dárek", -- Mystery Gift
    [C_ID .. 516] = "Rozstřikovač", -- Sprinkler
    [C_ID .. 517] = "Rychlo-Bomby", -- Fast Bombs
    [C_ID .. 518] = "Kamarád v Bedně", -- Buddy in a Box
    [C_ID .. 519] = "Maličký Delirium", -- Lil Delirium
    [C_ID .. 520] = "Startovací Kabely", -- Jumper Cables
    [C_ID .. 521] = "Kupón", -- Coupon
    [C_ID .. 522] = "Telekineze", -- Telekinesis
    [C_ID .. 523] = "Stěhovací Krabice", -- Moving Box
    [C_ID .. 524] = "Technologie Nula", -- Technology Zero
    [C_ID .. 525] = "Lepra", -- Leprosy
    [C_ID .. 526] = "7 Pečetí", -- 7 Seals
    [C_ID .. 527] = "Pan JÁ!", -- Mr. ME!
    [C_ID .. 528] = "Andělský Hranol", -- Angelic Prism
    [C_ID .. 529] = "Plup!", -- Pop!
    [C_ID .. 530] = "Seznam Smrti", -- Death's List
    [C_ID .. 531] = "Hemolakrie", -- Haemolacria
    [C_ID .. 532] = "Lachryfagie", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Školní Aktovka", -- Schoolbag
    [C_ID .. 535] = "Přikrývka", -- Blanket
    [C_ID .. 536] = "Obětní Oltář", -- Sacrificial Altar
    [C_ID .. 537] = "Maličký Plivač", -- Lil Spewer
    [C_ID .. 538] = "Kuličky", -- Marbles
    [C_ID .. 539] = "Tajemné Vejce", -- Mystery Egg
    [C_ID .. 540] = "Plochý Kámen", -- Flat Stone
    [C_ID .. 541] = "Kostní Dřeň", -- Marrow
    [C_ID .. 542] = "Vyklouzlé Žebro", -- Slipped Rib
    [C_ID .. 543] = "Posvátné Hovno", -- Hallowed Ground
    [C_ID .. 544] = "Špičaté Žebro", -- Pointy Rib
    [C_ID .. 545] = "Kniha Mrtvých", -- Book of the Dead
    [C_ID .. 546] = "Tátův Prsten", -- Dad's Ring
    [C_ID .. 547] = "Rozvodové Papíry", -- Divorce Papers
    [C_ID .. 548] = "Čelistní Kost", -- Jaw Bone
    [C_ID .. 549] = "Křehké Kosti", -- Brittle Bones
    [C_ID .. 550] = "Rozbitá Lopata", -- Broken Shovel
    [C_ID .. 551] = "Rozbitá Lopata", -- Broken Shovel
    [C_ID .. 552] = "Mámina lopata", -- Mom's Shovel
    [C_ID .. 553] = "Mukormykóza", -- Mucormycosis
    [C_ID .. 554] = "2Spooky", -- 2Spooky
    [C_ID .. 555] = "Zlatá Žiletka", -- Golden Razor
    [C_ID .. 556] = "Síra", -- Sulfur
    [C_ID .. 557] = "Koláček Štěstí", -- Fortune Cookie
    [C_ID .. 558] = "Bolest Očí", -- Eye Sore
    [C_ID .. 559] = "120 Voltů", -- 120 Volt
    [C_ID .. 560] = "To bolí", -- It Hurts
    [C_ID .. 561] = "Mandlové Mléko", -- Almond Milk
    [C_ID .. 562] = "Samé Dno", -- Rock Bottom
    [C_ID .. 563] = "Vzrušující Bomby", -- Nancy Bombs
    [C_ID .. 564] = "Kostka Mýdla", -- A Bar of Soap
    [C_ID .. 565] = "Krvavé Štěně", -- Blood Puppy
    [C_ID .. 566] = "Lapač Snů", -- Dream Catcher
    [C_ID .. 567] = "Paškál", -- Paschal Candle
    [C_ID .. 568] = "Boží Zásah", -- Divine Intervention
    [C_ID .. 569] = "Pokrevní Přísaha", -- Blood Oath
    [C_ID .. 570] = "Playdough Sušenka", -- Playdough Cookie
    [C_ID .. 571] = "Sirotkovy Ponožky", -- Orphan Socks
    [C_ID .. 572] = "Okultní Oko", -- Eye of the Occult
    [C_ID .. 573] = "Neposkvrněné Srdce", -- Immaculate Heart
    [C_ID .. 574] = "Monstrance", -- Monstrance
    [C_ID .. 575] = "Vetřelec", -- The Intruder
    [C_ID .. 576] = "Špinavá Mysl", -- Dirty Mind
    [C_ID .. 577] = "Damoklův Meč", -- Damocles
    [C_ID .. 578] = "Limča Zadáčo", -- Free Lemonade
    [C_ID .. 579] = "Duchovní Meč", -- Spirit Sword
    [C_ID .. 580] = "Červený Klíč", -- Red Key
    [C_ID .. 581] = "Psychická Muška", -- Psy Fly
    [C_ID .. 582] = "Lysohlávka", -- Wavy Cap
    [C_ID .. 583] = "Raketa ve Sklenici", -- Rocket in a Jar
    [C_ID .. 584] = "Kniha Ctností", -- Book of Virtues
    [C_ID .. 585] = "Alabastrová krabička", -- Alabaster Box
    [C_ID .. 586] = "Schodiště", -- The Stairway
    [C_ID .. 587] = "Menora (Nepoužité, ale naskriptované)", -- 
    [C_ID .. 588] = "Slunce", -- Sol
    [C_ID .. 589] = "Měsíc", -- Luna
    [C_ID .. 590] = "Merkur", -- Mercurius
    [C_ID .. 591] = "Venuše", -- Venus
    [C_ID .. 592] = "Země", -- Terra
    [C_ID .. 593] = "Mars", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturn", -- Saturnus
    [C_ID .. 596] = "Uran", -- Uranus
    [C_ID .. 597] = "Neptun", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Voodoo Hlava", -- Voodoo Head
    [C_ID .. 600] = "Oční Kapky", -- Eye Drops
    [C_ID .. 601] = "Akt Lítosti", -- Act of Contrition
    [C_ID .. 602] = "Členská Karta", -- Member Card
    [C_ID .. 603] = "Balíček baterií", -- Battery Pack
    [C_ID .. 604] = "Maminčin Náramek", -- Mom's Bracelet
    [C_ID .. 605] = "Lžíce Na Zmrzlinu", -- The Scooper
    [C_ID .. 606] = "Oční Trhlina", -- Ocular Rift
    [C_ID .. 607] = "Uvařené Dítě", -- Boiled Baby
    [C_ID .. 608] = "Zmrazené Děcko", -- Freezer Baby
    [C_ID .. 609] = "Věčná D6", -- Eternal D6
    [C_ID .. 610] = "Ptačí Klec", -- Bird Cage
    [C_ID .. 611] = "Hrtan", -- Larynx
    [C_ID .. 612] = "Ztracená Duše", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Krvavé Bomby", -- Blood Bombs
    [C_ID .. 615] = "Malej Dumpy", -- Lil Dumpy
    [C_ID .. 616] = "Ptačí Oko (Chilli Paprička)", -- Bird's Eye
    [C_ID .. 617] = "Magnetovec", -- Lodestone
    [C_ID .. 618] = "Shnilé Rajče", -- Rotten Tomato
    [C_ID .. 619] = "Prvorozenství", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Červený Guláš", -- Red Stew
    [C_ID .. 622] = "Genesis", -- Genesis
    [C_ID .. 623] = "Ostrý Klíč", -- Sharp Key
    [C_ID .. 624] = "Startovací Balíček Karet", -- Booster Pack
    [C_ID .. 625] = "Mega Houba", -- Mega Mush
    [C_ID .. 626] = "Kus Nože 1", -- Knife Piece 1
    [C_ID .. 627] = "Kus Nože 2", -- Knife Piece 2
    [C_ID .. 628] = "Úmrtní List", -- Death Certificate
    [C_ID .. 629] = "Robo-Moucha", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Sekáček Na Maso", -- Meat Cleaver
    [C_ID .. 632] = "Zlé Kouzlo", -- Evil Charm
    [C_ID .. 633] = "Dogma", -- Dogma
    [C_ID .. 634] = "Očistec", -- Purgatory
    [C_ID .. 635] = "Steháček", -- Stitches
    [C_ID .. 636] = "Klávesa R ", -- R Key
    [C_ID .. 637] = "Knockout Kapky", -- Knockout Drops
    [C_ID .. 638] = "Guma", -- Eraser
    [C_ID .. 639] = "Fuj Srdce", -- Yuck Heart
    [C_ID .. 640] = "Urna duší", -- Urn of Souls
    [C_ID .. 641] = "Akeldama", -- Akeldama
    [C_ID .. 642] = "Kouzelná Kůže", -- Magic Skin
    [C_ID .. 643] = "Zjevení", -- Revelation
    [C_ID .. 644] = "Cena Útěchy", -- Consolation Prize
    [C_ID .. 645] = "Malý Teratom", -- Tinytoma
    [C_ID .. 646] = "Brimstonové Bomby", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Voltovka", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Švestička", -- Fruity Plum
    [C_ID .. 650] = "Švestkova Flétna", -- Plum Flute
    [C_ID .. 651] = "Betlémská Hvězda", -- Star of Bethlehem
    [C_ID .. 652] = "Ledové Dítě", -- Cube Baby
    [C_ID .. 653] = "Ustup", -- Vade Retro
    [C_ID .. 654] = "Falešné PHD", -- False PHD
    [C_ID .. 655] = "Káča", -- Spin to Win
    [C_ID .. 656] = "Damoklův Meč", -- Damocles
    [C_ID .. 657] = "Vaskulitida", -- Vasculitis
    [C_ID .. 658] = "Obrovská Buňka", -- Giant Cell
    [C_ID .. 659] = "Tropikamid", -- Tropicamide
    [C_ID .. 660] = "Čtení z Karet", -- Card Reading
    [C_ID .. 661] = "Paterčata", -- Quints
    [C_ID .. 662] = "Pacifista (Cut item)", -- 
    [C_ID .. 663] = "Zuby-Nehty", -- Tooth and Nail
    [C_ID .. 664] = "Záchvatové Přejídání", -- Binge Eater
    [C_ID .. 665] = "Guppyho Oko", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Slamák", -- Strawman
    [C_ID .. 668] = "Tátův Dopis", -- Dad's Note
    [C_ID .. 669] = "Klobása", -- Sausage
    [C_ID .. 670] = "Možnosti?", -- Options?
    [C_ID .. 671] = "Cukrové Srdce", -- Candy Heart
    [C_ID .. 672] = "Kilo masa", -- A Pound of Flesh
    [C_ID .. 673] = "Vykoupení", -- Redemption
    [C_ID .. 674] = "Duševní Pouta", -- Spirit Shackles
    [C_ID .. 675] = "Popraskaný Orb", -- Cracked Orb
    [C_ID .. 676] = "Prázdné Srdce", -- Empty Heart
    [C_ID .. 677] = "Astrální Projekce", -- Astral Projection
    [C_ID .. 678] = "Císařský Řez", -- C Section
    [C_ID .. 679] = "Malej Abaddón", -- Lil Abaddon
    [C_ID .. 680] = "Montezumova Pomsta", -- Montezuma's Revenge
    [C_ID .. 681] = "Malý Portál", -- Lil Portal
    [C_ID .. 682] = "Červí Kámoš", -- Worm Friend
    [C_ID .. 683] = "Kostní Ostruha", -- Bone Spurs
    [C_ID .. 684] = "Hladová Duše", -- Hungry Soul
    [C_ID .. 685] = "Nádoba s Bludičkami", -- Jar of Wisps
    [C_ID .. 686] = "Duševní Medailónek", -- Soul Locket
    [C_ID .. 687] = "Hledač Přátel", -- Friend Finder
    [C_ID .. 688] = "Vnitřní Dítě", -- Inner Child
    [C_ID .. 689] = "Poškozená Koruna", -- Glitched Crown
    [C_ID .. 690] = "Břišní Želé", -- Belly Jelly
    [C_ID .. 691] = "Posvátný Orb", -- Sacred Orb
    [C_ID .. 692] = "Krvežíznivé Pouto", -- Sanguine Bond
    [C_ID .. 693] = "Roj", -- The Swarm
    [C_ID .. 694] = "Zlomené Srdce", -- Heartbreak
    [C_ID .. 695] = "Krvavý Závan", -- Bloody Gust
    [C_ID .. 696] = "Spása", -- Salvation
    [C_ID .. 697] = "Mizející Dvojče", -- Vanishing Twin
    [C_ID .. 698] = "Zvrácený Pár", -- Twisted Pair
    [C_ID .. 699] = "Azazelův Hněv", -- Azazel's Rage
    [C_ID .. 700] = "Echo Komora", -- Echo Chamber
    [C_ID .. 701] = "Izákova Hrobka", -- Isaac's Tomb
    [C_ID .. 702] = "Pomstychtivá Duše", -- Vengeful Spirit
    [C_ID .. 703] = "Ezau ml.", -- Esau Jr.
    [C_ID .. 704] = "Zběsilost!", -- Berserk!
    [C_ID .. 705] = "Temné Umění", -- Dark Arts
    [C_ID .. 706] = "Hlubina", -- Abyss
    [C_ID .. 707] = "Hostina", -- Supper
    [C_ID .. 708] = "Sešívačka", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Craftovací Pytlík", -- Bag of Crafting
    [C_ID .. 711] = "Převrácení", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Přivolání", -- Recall
    [C_ID .. 715] = "Podrž to", -- Hold
    [C_ID .. 716] = "Keeperův Pytel", -- Keeper's Sack
    [C_ID .. 717] = "Keeperovi Příbuzní", -- Keeper's Kin
    [C_ID .. 718] = "Keeperovo Roucho (Cut item)", -- 
    [C_ID .. 719] = "Keeperova Bedna", -- Keeper's Box
    [C_ID .. 720] = "Sklenice Všeho Možného", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Osamělá Duše", -- Anima Sola
    [C_ID .. 723] = "Roztáčející Kostka", -- Spindown Dice
    [C_ID .. 724] = "Hyperkoagulace", -- Hypercoagulation
    [C_ID .. 725] = "Syndrom Dráždivého Střeva", -- IBS
    [C_ID .. 726] = "Hemoptýza", -- Hemoptysis
    [C_ID .. 727] = "Strašidelné Bomby", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Bezhlavý Útok", -- Decap Attack
    [C_ID .. 730] = "Skleněné Oko", -- Glass Eye
    [C_ID .. 731] = "Ječné Zrno", -- Stye
    [C_ID .. 732] = "Mámin Prsten", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Spolknutá Mince", -- Swallowed Penny
    [T_ID .. 2] = "Zkamenělé Hovínko", -- Petrified Poop
    [T_ID .. 3] = "AAA Baterie", -- AAA Battery
    [T_ID .. 4] = "Rozbitý Ovladač", -- Broken Remote
    [T_ID .. 5] = "Fialové Srdce", -- Purple Heart
    [T_ID .. 6] = "Rozbitý Magnet", -- Broken Magnet
    [T_ID .. 7] = "Korálek z Růžence", -- Rosary Bead
    [T_ID .. 8] = "Kazeta", -- Cartridge
    [T_ID .. 9] = "Pulzující Červ", -- Pulse Worm
    [T_ID .. 10] = "Vrtivý Červ", -- Wiggle Worm
    [T_ID .. 11] = "Prstencový Červ", -- Ring Worm
    [T_ID .. 12] = "Plochý Červ", -- Flat Worm
    [T_ID .. 13] = "Obchodní Kredit", -- Store Credit
    [T_ID .. 14] = "Mozol", -- Callus
    [T_ID .. 15] = "Kamínek Štěstí", -- Lucky Rock
    [T_ID .. 16] = "Mámin Nehet", -- Mom's Toenail
    [T_ID .. 17] = "Černá Rtěnka", -- Black Lipstick
    [T_ID .. 18] = "Trakt z Bible", -- Bible Tract
    [T_ID .. 19] = "Kancelářská Svorka", -- Paper Clip
    [T_ID .. 20] = "Opičí Tlapka", -- Monkey Paw
    [T_ID .. 21] = "Tajemný Papír", -- Mysterious Paper
    [T_ID .. 22] = "Démonův Ocas", -- Daemon's Tail
    [T_ID .. 23] = "Pohřešující Plakát", -- Missing Poster
    [T_ID .. 24] = "Prdelní Mince", -- Butt Penny
    [T_ID .. 25] = "Tajemná Sladkost", -- Mysterious Candy
    [T_ID .. 26] = "Hákový Červ", -- Hook Worm
    [T_ID .. 27] = "Bičový Červ", -- Whip Worm
    [T_ID .. 28] = "Rozbitý Ankh", -- Broken Ankh
    [T_ID .. 29] = "Rybí Hlava", -- Fish Head
    [T_ID .. 30] = "Zrudlé Oko", -- Pinky Eye
    [T_ID .. 31] = "Špendlík", -- Push Pin
    [T_ID .. 32] = "Lysohlávka", -- Liberty Cap
    [T_ID .. 33] = "Pupeční Šňůra", -- Umbilical Cord
    [T_ID .. 34] = "Dětské Srdce", -- Child's Heart
    [T_ID .. 35] = "Zakřivený Roh", -- Curved Horn
    [T_ID .. 36] = "Zrezivělý Klíč", -- Rusted Key
    [T_ID .. 37] = "Kozí Kopyto", -- Goat Hoof
    [T_ID .. 38] = "Mámina Perla", -- Mom's Pearl
    [T_ID .. 39] = "Rakovina", -- Cancer
    [T_ID .. 40] = "Červená Záplata", -- Red Patch
    [T_ID .. 41] = "Zápalka", -- Match Stick
    [T_ID .. 42] = "Palec Štěstí", -- Lucky Toe
    [T_ID .. 43] = "Prokletá Lebka", -- Cursed Skull
    [T_ID .. 44] = "Bezpečnostní Uzávěr", -- Safety Cap
    [T_ID .. 45] = "Pikové Eso", -- Ace of Spades
    [T_ID .. 46] = "Izákova Vidlička", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "Chybějící Stránka", -- A Missing Page
    [T_ID .. 49] = "Krvavá Mince", -- Bloody Penny
    [T_ID .. 50] = "Spálená Mince", -- Burnt Penny
    [T_ID .. 51] = "Plochá Mince", -- Flat Penny
    [T_ID .. 52] = "Padělaná Mince", -- Counterfeit Penny
    [T_ID .. 53] = "Klíště", -- Tick
    [T_ID .. 54] = "Izákova Hlava", -- Isaac's Head
    [T_ID .. 55] = "Maggyina Víra", -- Maggy's Faith
    [T_ID .. 56] = "Jidášův Jazyk", -- Judas' Tongue
    [T_ID .. 57] = "Duše ???", -- ???'s Soul
    [T_ID .. 58] = "Samsonovy Kadeře", -- Samson's Lock
    [T_ID .. 59] = "Kainovo Oko", -- Cain's Eye
    [T_ID .. 60] = "Evina Ptačí Noha", -- Eve's Bird Foot
    [T_ID .. 61] = "Levá Ruka", -- The Left Hand
    [T_ID .. 62] = "Lesklý Kamínek", -- Shiny Rock
    [T_ID .. 63] = "Bezpečnostní Nůžky", -- Safety Scissors
    [T_ID .. 64] = "Duhový Červ", -- Rainbow Worm
    [T_ID .. 65] = "Tasemnice", -- Tape Worm
    [T_ID .. 66] = "Líný Červ", -- Lazy Worm
    [T_ID .. 67] = "Prasklá Kostka", -- Cracked Dice
    [T_ID .. 68] = "Super Magnet", -- Super Magnet
    [T_ID .. 69] = "Vybledlý Polaroid", -- Faded Polaroid
    [T_ID .. 70] = "Veš", -- Louse
    [T_ID .. 71] = "Bobův Měchýř", -- Bob's Bladder
    [T_ID .. 72] = "Baterka do Hodinek", -- Watch Battery
    [T_ID .. 73] = "Rozbuška", -- Blasting Cap
    [T_ID .. 74] = "Detektor Kovů", -- Stud Finder
    [T_ID .. 75] = "Chyba 404", -- Error
    [T_ID .. 76] = "Pokerový Žeton", -- Poker Chip
    [T_ID .. 77] = "Puchýř", -- Blister
    [T_ID .. 78] = "Vteřinová Ručička", -- Second Hand
    [T_ID .. 79] = "Nekonečný Bezejmenný", -- Endless Nameless
    [T_ID .. 80] = "Černé Pírko", -- Black Feather
    [T_ID .. 81] = "Slepý Hněv", -- Blind Rage
    [T_ID .. 82] = "Zlatá Podkova", -- Golden Horse Shoe
    [T_ID .. 83] = "Klíč od Obchodu", -- Store Key
    [T_ID .. 84] = "Greedovo Žebro", -- Rib of Greed
    [T_ID .. 85] = "Karma", -- Karma
    [T_ID .. 86] = "Malá Larva", -- Lil Larva
    [T_ID .. 87] = "Maminčin Medailon", -- Mom's Locket
    [T_ID .. 88] = "NE!", -- NO!
    [T_ID .. 89] = "Dětské Vodítko", -- Child Leash
    [T_ID .. 90] = "Hnědá Rozbuška", -- Brown Cap
    [T_ID .. 91] = "Smolka", -- Meconium
    [T_ID .. 92] = "Popraskaná Koruna", -- Cracked Crown
    [T_ID .. 93] = "Použitá Plenka", -- Used Diaper
    [T_ID .. 94] = "Rybí Ocas", -- Fish Tail
    [T_ID .. 95] = "Černý Zub", -- Black Tooth
    [T_ID .. 96] = "Červ Ouroboros", -- Ouroboros Worm
    [T_ID .. 97] = "Mandle", -- Tonsil
    [T_ID .. 98] = "Nosní Goblin (Sopel)", -- Nose Goblin
    [T_ID .. 99] = "Super Míček", -- Super Ball
    [T_ID .. 100] = "Živá Žárovka", -- Vibrant Bulb
    [T_ID .. 101] = "Tlumená Žárovka", -- Dim Bulb
    [T_ID .. 102] = "Roztržená Karta", -- Fragmented Card
    [T_ID .. 103] = "Rovnost!", -- Equality!
    [T_ID .. 104] = "Kost Přání", -- Wish Bone
    [T_ID .. 105] = "Oběd v Sáčku", -- Bag Lunch
    [T_ID .. 106] = "Ztracený Korek", -- Lost Cork
    [T_ID .. 107] = "Vraní Srdce", -- Crow Heart
    [T_ID .. 108] = "Vlašský Ořech", -- Walnut
    [T_ID .. 109] = "Lepící Páska", -- Duct Tape
    [T_ID .. 110] = "Stříbrný Dolar", -- Silver Dollar
    [T_ID .. 111] = "Krvavá Koruna", -- Bloody Crown
    [T_ID .. 112] = "Zaplať za Výhru", -- Pay To Win
    [T_ID .. 113] = "Kobylka Války", -- Locust of War
    [T_ID .. 114] = "Kobylka Moru", -- Locust of Pestilence
    [T_ID .. 115] = "Kobylka Hladomoru", -- Locust of Famine
    [T_ID .. 116] = "Kobylka Smrti", -- Locust of Death
    [T_ID .. 117] = "Kobylka Podmanění", -- Locust of Conquest
    [T_ID .. 118] = "Netopýří Křídlo", -- Bat Wing
    [T_ID .. 119] = "Kmenová Buňka", -- Stem Cell
    [T_ID .. 120] = "Sponka do Vlasů", -- Hairpin
    [T_ID .. 121] = "Dřevěný Kříž", -- Wooden Cross
    [T_ID .. 122] = "Máslo!", -- Butter!
    [T_ID .. 123] = "Filigránové Peříčko", -- Filigree Feather
    [T_ID .. 124] = "Zarážka za Dveře", -- Door Stop
    [T_ID .. 125] = "Prodlužovačka", -- Extension Cord
    [T_ID .. 126] = "Zkažená Mince", -- Rotten Penny
    [T_ID .. 127] = "Ohnutá Dětská Lžička", -- Baby-Bender
    [T_ID .. 128] = "Kost z Prstu", -- Finger Bone
    [T_ID .. 129] = "Jawbreaker (bonbón)", -- Jawbreaker
    [T_ID .. 130] = "Okousané Pero", -- Chewed Pen
    [T_ID .. 131] = "Požehnaná Mince", -- Blessed Penny
    [T_ID .. 132] = "Rozbitá Stříkačka", -- Broken Syringe
    [T_ID .. 133] = "Krátká Pojistka", -- Short Fuse
    [T_ID .. 134] = "Obrovská Fazole", -- Gigante Bean
    [T_ID .. 135] = "Zapalovač", -- A Lighter
    [T_ID .. 136] = "Rozbitý Visací Zámek", -- Broken Padlock
    [T_ID .. 137] = "Pomněnka", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Slzný Přívěšek", -- Teardrop Charm
    [T_ID .. 140] = "Sodomské Jablko", -- Apple of Sodom
    [T_ID .. 141] = "Zapomenutá Ukolébavka", -- Forgotten Lullaby
    [T_ID .. 142] = "Bethina Víra", -- Beth's Faith
    [T_ID .. 143] = "Starý Kondenzátor", -- Old Capacitor
    [T_ID .. 144] = "Mozkový Červ", -- Brain Worm
    [T_ID .. 145] = "Dokonalost", -- Perfection
    [T_ID .. 146] = "Ďáblova Koruna", -- Devil's Crown
    [T_ID .. 147] = "Nabitá Mince", -- Charged Penny
    [T_ID .. 148] = "Řetízek Přátelství", -- Friendship Necklace
    [T_ID .. 149] = "Tlačítko na Paniku", -- Panic Button
    [T_ID .. 150] = "Modrý Klíč", -- Blue Key
    [T_ID .. 151] = "Pilník", -- Flat File
    [T_ID .. 152] = "Objektiv Dalekohledu", -- Telescope Lens
    [T_ID .. 153] = "Mámina Kadeř", -- Mom's Lock
    [T_ID .. 154] = "Sáček s Kostkami", -- Dice Bag
    [T_ID .. 155] = "Svatá Koruna", -- Holy Crown
    [T_ID .. 156] = "Maminčin Polibek", -- Mother's Kiss
    [T_ID .. 157] = "Roztrhaná Karta", -- Torn Card
    [T_ID .. 158] = "Roztrhaná Kapsa", -- Torn Pocket
    [T_ID .. 159] = "Pozlacený Klíč", -- Gilded Key
    [T_ID .. 160] = "Pytlíček Štěstěny", -- Lucky Sack
    [T_ID .. 161] = "Zlá Koruna", -- Wicked Crown
    [T_ID .. 162] = "Azazelův Pahýl", -- Azazel's Stump
    [T_ID .. 163] = "Dingle Berry", -- Dingle Berry
    [T_ID .. 164] = "Prstencový Uzávěr", -- Ring Cap
    [T_ID .. 165] = "Ne Ne!", -- Nuh Uh!
    [T_ID .. 166] = "Modelářská Hlína", -- Modeling Clay
    [T_ID .. 167] = "Vyleštěná Kost", -- Polished Bone
    [T_ID .. 168] = "Duté Srdce", -- Hollow Heart
    [T_ID .. 169] = "Dětská Kresba", -- Kid's Drawing
    [T_ID .. 170] = "Křišťálový Klíč", -- Crystal Key
    [T_ID .. 171] = "Keeperova Smlouva", -- Keeper's Bargain
    [T_ID .. 172] = "Prokletá Mince", -- Cursed Penny
    [T_ID .. 173] = "Tvoje Duše", -- Your Soul
    [T_ID .. 174] = "Magnetka", -- Number Magnet
    [T_ID .. 175] = "Podivný Klíč", -- Strange Key
    [T_ID .. 176] = "Malá Sraženina", -- Lil Clot
    [T_ID .. 177] = "Dočasné Tetování", -- Temporary Tattoo
    [T_ID .. 178] = "Spolknutá M80", -- Swallowed M80
    [T_ID .. 179] = "RC Dálkové Ovládání", -- RC Remote
    [T_ID .. 180] = "Nalezená Duše", -- Found Soul
    [T_ID .. 181] = "Rozšiřující Balíček", -- Expansion Pack
    [T_ID .. 182] = "Bethina Esence", -- Beth's Essence
    [T_ID .. 183] = "Dvojčata", -- The Twins
    [T_ID .. 184] = "Adopční Papíry", -- Adoption Papers
    [T_ID .. 185] = "Noha Kobylky", -- Cricket Leg
    [T_ID .. 186] = "Apollyónův Nejlepší Kámoš", -- Apollyon's Best Friend
    [T_ID .. 187] = "Rozbité Brýle", -- Broken Glasses
    [T_ID .. 188] = "Kostka Ledu", -- Ice Cube
    [T_ID .. 189] = "Bafometova Pečeť", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Blázen", -- 0 - The Fool
    [Card_ID .. 2] = "I - Mág", -- I - The Magician
    [Card_ID .. 3] = "II - Velekněžka", -- II - The High Priestess
    [Card_ID .. 4] = "III - Císařovna", -- III - The Empress
    [Card_ID .. 5] = "IV - Císař", -- IV - The Emperor
    [Card_ID .. 6] = "V - Velekněz", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Zamilovaní", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Vůz", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Spravedlnost", -- VIII - Justice
    [Card_ID .. 10] = "IX - Poustevník", -- IX - The Hermit
    [Card_ID .. 11] = "X - Kolo štěstí", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Síla", -- XI - Strength
    [Card_ID .. 13] = "XII - Viselec", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Smrt", -- XIII - Death
    [Card_ID .. 15] = "XIV - Umírněnost", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Ďábel", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Věž", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Hvězda", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Měsíc", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Slunce", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Soud", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Svět", -- XXI - The World
    [Card_ID .. 23] = "Křížová 2", -- 2 of Clubs
    [Card_ID .. 24] = "Kárová 2", -- 2 of Diamonds
    [Card_ID .. 25] = "Piková 2", -- 2 of Spades
    [Card_ID .. 26] = "Srdcová 2", -- 2 of Hearts
    [Card_ID .. 27] = "Křížové Eso", -- Ace of Clubs
    [Card_ID .. 28] = "Kárové Eso", -- Ace of Diamonds
    [Card_ID .. 29] = "Pikové Eso", -- Ace of Spades
    [Card_ID .. 30] = "Srdcové Eso", -- Ace of Hearts
    [Card_ID .. 31] = "Žolík", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Slepá Runa", -- Blank Rune
    [Card_ID .. 41] = "Černá Runa", -- Black Rune
    [Card_ID .. 42] = "Chaos Karta", -- Chaos Card
    [Card_ID .. 43] = "Kreditka", -- Credit Card
    [Card_ID .. 44] = "Pravidla", -- Rules Card
    [Card_ID .. 45] = "Karta Proti Lidskosti", -- A Card Against Humanity
    [Card_ID .. 46] = "Sebevražedný Král", -- Suicide King
    [Card_ID .. 47] = "Karta Dostaň se z Věžení", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "? Karta", -- ? Card
    [Card_ID .. 49] = "Úlomek Kostky", -- Dice Shard
    [Card_ID .. 50] = "Nouzový Kontakt", -- Emergency Contact
    [Card_ID .. 51] = "Svatá Karta", -- Holy Card
    [Card_ID .. 52] = "Obrovský Růst", -- Huge Growth
    [Card_ID .. 53] = "Starověké Odvolání", -- Ancient Recall
    [Card_ID .. 54] = "Érová Chůze", -- Era Walk
    [Card_ID .. 55] = "Střípek Runy", -- Rune Shard
    [Card_ID .. 56] = "0 - Blázen?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Mág?", -- I - The Magician?
    [Card_ID .. 58] = "II - Velekněžka?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - Císařovna?", -- III - The Empress?
    [Card_ID .. 60] = "IV - Císař?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Velekněz?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Zamilovaní?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Vůz?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Spravedlnost?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - Poustevník?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Kolo štěstí?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Síla?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Viselec?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Smrt?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Umírněnost?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Ďábel?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - Věž?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Hvězda?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - Měsíc?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Slunce?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Soud?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Svět?", -- XXI - The World?
    [Card_ID .. 78] = "Prasklý Klíč", -- Cracked Key
    [Card_ID .. 79] = "Srdcová Královna", -- Queen of Hearts
    [Card_ID .. 80] = "Divoká Karta", -- Wild Card
    [Card_ID .. 81] = "Izákova Duše", -- Soul of Isaac
    [Card_ID .. 82] = "Magdalénina Duše", -- Soul of Magdalene
    [Card_ID .. 83] = "Kainova Duše", -- Soul of Cain
    [Card_ID .. 84] = "Jidášova Duše", -- Soul of Judas
    [Card_ID .. 85] = "??? Duše", -- Soul of ???
    [Card_ID .. 86] = "Evina Duše", -- Soul of Eve
    [Card_ID .. 87] = "Samsonova Duše", -- Soul of Samson
    [Card_ID .. 88] = "Azazelova Duše", -- Soul of Azazel
    [Card_ID .. 89] = "Lazarova Duše", -- Soul of Lazarus
    [Card_ID .. 90] = "Edenova Duše", -- Soul of Eden
    [Card_ID .. 91] = "Duše Ztraceného", -- Soul of the Lost
    [Card_ID .. 92] = "Lilithina Duše", -- Soul of Lilith
    [Card_ID .. 93] = "Keeperova Duše", -- Soul of the Keeper
    [Card_ID .. 94] = "Apollyónova Duše", -- Soul of Apollyon
    [Card_ID .. 95] = "Duše Zapomenutého", -- Soul of the Forgotten
    [Card_ID .. 96] = "Bethina Duše", -- Soul of Bethany
    [Card_ID .. 97] = "Duše Jákoba a Ezaua", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "Otravný Prd", -- Bad Gas
    [Pill_ID .. 2] = "Špatnej Trip", -- Bad Trip
    [Pill_ID .. 3] = "Koule z Oceli", -- Balls of Steel
    [Pill_ID .. 4] = "Bomby jsou klíčem", -- Bombs are Key
    [Pill_ID .. 5] = "Výbušný Průjem", -- Explosive Diarrhea
    [Pill_ID .. 6] = "Plné zdraví", -- Full Health
    [Pill_ID .. 7] = "Snížení Zdraví", -- Health Down
    [Pill_ID .. 8] = "Zvýšení Zdraví", -- Health Up
    [Pill_ID .. 9] = "Našel Jsem Pilulky", -- I Found Pills
    [Pill_ID .. 10] = "Puberta", -- Puberty
    [Pill_ID .. 11] = "Pěkná Moucha", -- Pretty Fly
    [Pill_ID .. 12] = "Menší Dostřel", -- Range Down
    [Pill_ID .. 13] = "Větší Dostřel", -- Range Up
    [Pill_ID .. 14] = "Snížení Rychlosti", -- Speed Down
    [Pill_ID .. 15] = "Zvýšení Rychlosti", -- Speed Up
    [Pill_ID .. 16] = "Méně Slz", -- Tears Down
    [Pill_ID .. 17] = "Více Slz", -- Tears Up
    [Pill_ID .. 18] = "Snížení Štěstí", -- Luck Down
    [Pill_ID .. 19] = "Zvýšení Štěstí", -- Luck Up
    [Pill_ID .. 20] = "Telepilulky", -- Telepills
    [Pill_ID .. 21] = "48 Hodinová Energie!", -- 48 Hour Energy!
    [Pill_ID .. 22] = "Hematemeze", -- Hematemesis
    [Pill_ID .. 23] = "Paralýza", -- Paralysis
    [Pill_ID .. 24] = "Vidím Navždy!", -- I can see forever!
    [Pill_ID .. 25] = "Feromony", -- Pheromones
    [Pill_ID .. 26] = "Amnézie", -- Amnesia
    [Pill_ID .. 27] = "Citronová Párty", -- Lemon Party
    [Pill_ID .. 28] = "Jsi Čaroděj Harry!", -- R U A Wizard?
    [Pill_ID .. 29] = "Proti-Bol!", -- Percs!
    [Pill_ID .. 30] = "Závislák!", -- Addicted!
    [Pill_ID .. 31] = "Re-Laxuj", -- Re-Lax
    [Pill_ID .. 32] = "???", -- ???
    [Pill_ID .. 33] = "Jedna Tě Zvětší", -- One makes you larger
    [Pill_ID .. 34] = "Jedna Tě Zmenší", -- One makes you small
    [Pill_ID .. 35] = "Zamoření!", -- Infested!
    [Pill_ID .. 36] = "Zamoření?", -- Infested?
    [Pill_ID .. 37] = "Power Pilulka!", -- Power Pill!
    [Pill_ID .. 38] = "Retro Vize", -- Retro Vision
    [Pill_ID .. 39] = "Přátelé až do Konce!", -- Friends Till The End!
    [Pill_ID .. 40] = "X-Lax", -- X-Lax
    [Pill_ID .. 41] = "Něco je špatně...", -- Something's wrong...
    [Pill_ID .. 42] = "Jsem ospalý...", -- I'm Drowsy...
    [Pill_ID .. 43] = "Jsem vzrušený!!!", -- I'm Excited!!
    [Pill_ID .. 44] = "Polk!", -- Gulp!
    [Pill_ID .. 45] = "Blink!", -- Horf!
    [Pill_ID .. 46] = "Jako bych kráčel po slunečním svitu!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "Brk!", -- Vurp!
    [Pill_ID .. 48] = "Menší Rychlost Střel", -- Shot speed Down
    [Pill_ID .. 49] = "Vyšší Rychlost Střel", -- Shot speed Up
    [Pill_ID .. 50] = "Experimentální Pilulka", -- Experimental Pill
    [Pill_ID .. 9999] = "", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])