-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "de"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Die traurige Zwiebel", -- The Sad Onion
    [C_ID .. 2] = "Das Innere Auge", -- The Inner Eye
    [C_ID .. 3] = "Löffelbieger", -- Spoon Bender
    [C_ID .. 4] = "Grillenkopf", -- Cricket's Head
    [C_ID .. 5] = "Meine Reflexion", -- My Reflection
    [C_ID .. 6] = "Nummer Eins", -- Number One
    [C_ID .. 7] = "Blut des Märtyrers", -- Blood of the Martyr
    [C_ID .. 8] = "Bruder Bobby", -- Brother Bobby
    [C_ID .. 9] = "Skatol", -- Skatole
    [C_ID .. 10] = "Fliegen-Halo", -- Halo of Flies
    [C_ID .. 11] = "1-Up!", -- 1up!
    [C_ID .. 12] = "Magischer Pilz", -- Magic Mushroom
    [C_ID .. 13] = "Das Virus", -- The Virus
    [C_ID .. 14] = "Wut-Raserei", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Rohe Leber", -- Raw Liver
    [C_ID .. 17] = "Skelettschlüssel", -- Skeleton Key
    [C_ID .. 18] = "Ein Dollar", -- A Dollar
    [C_ID .. 19] = "Bumm!", -- Boom!
    [C_ID .. 20] = "Transzendenz", -- Transcendence
    [C_ID .. 21] = "Der Kompass", -- The Compass
    [C_ID .. 22] = "Mittagessen", -- Lunch
    [C_ID .. 23] = "Abendessen", -- Dinner
    [C_ID .. 24] = "Nachtisch", -- Dessert
    [C_ID .. 25] = "Frühstück", -- Breakfast
    [C_ID .. 26] = "Verdorbenes Fleisch", -- Rotten Meat
    [C_ID .. 27] = "Holzlöffel", -- Wooden Spoon
    [C_ID .. 28] = "Der Gürtel", -- The Belt
    [C_ID .. 29] = "Mamas Unterwäsche", -- Mom's Underwear
    [C_ID .. 30] = "Mamas Absätze", -- Mom's Heels
    [C_ID .. 31] = "Mamas Lippenstift", -- Mom's Lipstick
    [C_ID .. 32] = "Drahtkleiderbügel", -- Wire Coat Hanger
    [C_ID .. 33] = "Die Bibel", -- The Bible
    [C_ID .. 34] = "Das Buch Belial", -- The Book of Belial
    [C_ID .. 35] = "Das Necronomicon", -- The Necronomicon
    [C_ID .. 36] = "Der Schiss", -- The Poop
    [C_ID .. 37] = "Herr Boom", -- Mr. Boom
    [C_ID .. 38] = "Tammys Kopf", -- Tammy's Head
    [C_ID .. 39] = "Mamas BH", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Mamas Binde", -- Mom's Pad
    [C_ID .. 42] = "Bobs Fauliger Kopf", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teleportieren!", -- Teleport!
    [C_ID .. 45] = "Leckeres Herz", -- Yum Heart
    [C_ID .. 46] = "Glücklicher Fuß", -- Lucky Foot
    [C_ID .. 47] = "Doktor-Fernbedienung", -- Doctor's Remote
    [C_ID .. 48] = "Amors Pfeil", -- Cupid's Arrow
    [C_ID .. 49] = "Shoop da Whoop!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagramm", -- Pentagram
    [C_ID .. 52] = "Doktor Fetus", -- Dr. Fetus
    [C_ID .. 53] = "Magneto", -- Magneto
    [C_ID .. 54] = "Schatzkarte", -- Treasure Map
    [C_ID .. 55] = "Mamas Auge", -- Mom's Eye
    [C_ID .. 56] = "Zitronen-Missgeschick", -- Lemon Mishap
    [C_ID .. 57] = "Ferne Bewunderung", -- Distant Admiration
    [C_ID .. 58] = "Buch der Schatten", -- Book of Shadows
    [C_ID .. 59] = "Das Buch von Belial", -- The Book of Belial
    [C_ID .. 60] = "Die Leiter", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Der Vampirzauber", -- Charm of the Vampire
    [C_ID .. 63] = "Die Batterie", -- The Battery
    [C_ID .. 64] = "Sonderangebot", -- Steam Sale
    [C_ID .. 65] = "Anarchisten-Kochbuch", -- Anarchist Cookbook
    [C_ID .. 66] = "Die Sanduhr", -- The Hourglass
    [C_ID .. 67] = "Schwester Maggy", -- Sister Maggy
    [C_ID .. 68] = "Technologie", -- Technology
    [C_ID .. 69] = "Schokoladenmilch", -- Chocolate Milk
    [C_ID .. 70] = "Wachstumshormone", -- Growth Hormones
    [C_ID .. 71] = "Mini Mush", -- Mini Mush
    [C_ID .. 72] = "Rosenkranz", -- Rosary
    [C_ID .. 73] = "Fleischwürfel", -- Cube of Meat
    [C_ID .. 74] = "Ein Vierteldollar", -- A Quarter
    [C_ID .. 75] = "PHD", -- PHD
    [C_ID .. 76] = "Röntgenblick", -- X-Ray Vision
    [C_ID .. 77] = "Mein kleines Einhorn", -- My Little Unicorn
    [C_ID .. 78] = "Buch der Offenbarung", -- Book of Revelations
    [C_ID .. 79] = "Das Zeichen", -- The Mark
    [C_ID .. 80] = "Der Pakt", -- The Pact
    [C_ID .. 81] = "Tote Katze", -- Dead Cat
    [C_ID .. 82] = "Herr der Höllengrube", -- Lord of the Pit
    [C_ID .. 83] = "Der Nagel", -- The Nail
    [C_ID .. 84] = "Wir müssen tiefer gehen!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Kartenspiel", -- Deck of Cards
    [C_ID .. 86] = "Monstros Zahn", -- Monstro's Tooth
    [C_ID .. 87] = "Lokis Hörner", -- Loki's Horns
    [C_ID .. 88] = "Dickerchen", -- Little Chubby
    [C_ID .. 89] = "Spinnenbiss", -- Spider Bite
    [C_ID .. 90] = "Der kleine Felsen", -- The Small Rock
    [C_ID .. 91] = "Spelunker-Hut", -- Spelunker Hat
    [C_ID .. 92] = "Superverband", -- Super Bandage
    [C_ID .. 93] = "Das Zocker-Kid", -- The Gamekid
    [C_ID .. 94] = "Sack voller Pennies", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Baby", -- Robo-Baby
    [C_ID .. 96] = "Kleiner C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "Das Buch der Sünde", -- The Book of Sin
    [C_ID .. 98] = "Die Reliquie", -- The Relic
    [C_ID .. 99] = "Kleiner Gish", -- Little Gish
    [C_ID .. 100] = "Kleiner Steven", -- Little Steven
    [C_ID .. 101] = "Der Heiligenschein", -- The Halo
    [C_ID .. 102] = "Mamas Pillenflasche", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Die Erkältung", -- The Common Cold
    [C_ID .. 104] = "Der Parasit", -- The Parasite
    [C_ID .. 105] = "Der W6", -- The D6
    [C_ID .. 106] = "Herr Mega", -- Mr. Mega
    [C_ID .. 107] = "Die Zackenschere", -- The Pinking Shears
    [C_ID .. 108] = "Die Hostie", -- The Wafer
    [C_ID .. 109] = "Geld = Macht", -- Money = Power
    [C_ID .. 110] = "Mamas Kontakte", -- Mom's Contacts
    [C_ID .. 111] = "Die Bohne", -- The Bean
    [C_ID .. 112] = "Schutzengel", -- Guardian Angel
    [C_ID .. 113] = "Dämonenbaby", -- Demon Baby
    [C_ID .. 114] = "Mamas Messer", -- Mom's Knife
    [C_ID .. 115] = "Ouija-Brett", -- Ouija Board
    [C_ID .. 116] = "9 Volt", -- 9 Volt
    [C_ID .. 117] = "Toter Vogel", -- Dead Bird
    [C_ID .. 118] = "Schwefel", -- Brimstone
    [C_ID .. 119] = "Blutbeutel", -- Blood Bag
    [C_ID .. 120] = "Seltsamer Pilz (Dünn)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Seltsamer Pilz (Groß)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Hure Babylon", -- Whore of Babylon
    [C_ID .. 123] = "Monsterhandbuch", -- Monster Manual
    [C_ID .. 124] = "Schriftrollen vom Toten Meer", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bombe", -- Bobby-Bomb
    [C_ID .. 126] = "Rasierklinge", -- Razor Blade
    [C_ID .. 127] = "Vergissmeinjetzt", -- Forget Me Now
    [C_ID .. 128] = "Für immer alleine", -- Forever Alone
    [C_ID .. 129] = "Eimer mit Talg", -- Bucket of Lard
    [C_ID .. 130] = "Ein Pony", -- A Pony
    [C_ID .. 131] = "Bombentasche", -- Bomb Bag
    [C_ID .. 132] = "Ein Klumpen Kohle", -- A Lump of Coal
    [C_ID .. 133] = "Guppys Pfote", -- Guppy's Paw
    [C_ID .. 134] = "Guppys Schwanz", -- Guppy's Tail
    [C_ID .. 135] = "Infusionsbeutel", -- IV Bag
    [C_ID .. 136] = "Bester Freund", -- Best Friend
    [C_ID .. 137] = "Fernzünder", -- Remote Detonator
    [C_ID .. 138] = "Stigmata", -- Stigmata
    [C_ID .. 139] = "Mamas Geldbeutel", -- Mom's Purse
    [C_ID .. 140] = "Bobs Fluch", -- Bob's Curse
    [C_ID .. 141] = "Geschmückter Junge", -- Pageant Boy
    [C_ID .. 142] = "Skapulier", -- Scapular
    [C_ID .. 143] = "Tempo machen", -- Speed Ball
    [C_ID .. 144] = "Pennerfreund", -- Bum Friend
    [C_ID .. 145] = "Guppys Kopf", -- Guppy's Head
    [C_ID .. 146] = "Gebetskarte", -- Prayer Card
    [C_ID .. 147] = "Eingeritzte Axt", -- Notched Axe
    [C_ID .. 148] = "Infestation", -- Infestation
    [C_ID .. 149] = "Ipecac", -- Ipecac
    [C_ID .. 150] = "Auf die Fresse", -- Tough Love
    [C_ID .. 151] = "Der Mulligan", -- The Mulligan
    [C_ID .. 152] = "Technologie 2", -- Technology 2
    [C_ID .. 153] = "Mutant Spider", -- Mutant Spider
    [C_ID .. 154] = "Chemisches Peeling", -- Chemical Peel
    [C_ID .. 155] = "Der Peeper", -- The Peeper
    [C_ID .. 156] = "Habit", -- Habit
    [C_ID .. 157] = "Blutdurst", -- Bloody Lust
    [C_ID .. 158] = "Kristallkugel", -- Crystal Ball
    [C_ID .. 159] = "Geist der Nacht", -- Spirit of the Night
    [C_ID .. 160] = "Zerbrich den Himmel", -- Crack the Sky
    [C_ID .. 161] = "Ankh", -- Ankh
    [C_ID .. 162] = "Keltisches Kreuz", -- Celtic Cross
    [C_ID .. 163] = "Geisterbaby", -- Ghost Baby
    [C_ID .. 164] = "Die Kerze", -- The Candle
    [C_ID .. 165] = "9-schwänzige Katze", -- Cat-o-nine-tails
    [C_ID .. 166] = "W20", -- D20
    [C_ID .. 167] = "Harlekin-Baby", -- Harlequin Baby
    [C_ID .. 168] = "Epischer Fötus", -- Epic Fetus
    [C_ID .. 169] = "Polyphemus", -- Polyphemus
    [C_ID .. 170] = "Papi Langbein", -- Daddy Longlegs
    [C_ID .. 171] = "Spinnenhintern", -- Spider Butt
    [C_ID .. 172] = "Opferdolch", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitra", -- Mitre
    [C_ID .. 174] = "Regenbogenbaby", -- Rainbow Baby
    [C_ID .. 175] = "Papas Schlüssel", -- Dad's Key
    [C_ID .. 176] = "Stammzellen", -- Stem Cells
    [C_ID .. 177] = "Mobiler Spielautomat", -- Portable Slot
    [C_ID .. 178] = "Heiliges Wasser", -- Holy Water
    [C_ID .. 179] = "Schicksal", -- Fate
    [C_ID .. 180] = "Die schwarze Bohne", -- The Black Bean
    [C_ID .. 181] = "Weißes Pony", -- White Pony
    [C_ID .. 182] = "Heiliges Herz", -- Sacred Heart
    [C_ID .. 183] = "Zahnstocher", -- Tooth Picks
    [C_ID .. 184] = "Heiliger Gral", -- Holy Grail
    [C_ID .. 185] = "Tote Taube", -- Dead Dove
    [C_ID .. 186] = "Blutrechte", -- Blood Rights
    [C_ID .. 187] = "Guppys Haarball", -- Guppy's Hairball
    [C_ID .. 188] = "Abel", -- Abel
    [C_ID .. 189] = "SMB Super Fan", -- SMB Super Fan
    [C_ID .. 190] = "Pyro", -- Pyro
    [C_ID .. 191] = "3-Dollar-Schein", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepathie für Dummies", -- Telepathy for Dummies
    [C_ID .. 193] = "FLEISCH!", -- MEAT!
    [C_ID .. 194] = "Magische 8-Kugel", -- Magic 8 Ball
    [C_ID .. 195] = "Mamas Geldbörse", -- Mom's Coin Purse
    [C_ID .. 196] = "Quetschi", -- Squeezy
    [C_ID .. 197] = "Jesus-Saft", -- Jesus Juice
    [C_ID .. 198] = "Box", -- Box
    [C_ID .. 199] = "Mamas Schlüssel", -- Mom's Key
    [C_ID .. 200] = "Mamas Lidschatten", -- Mom's Eyeshadow
    [C_ID .. 201] = "Eisenstange", -- Iron Bar
    [C_ID .. 202] = "Midas' Berührung", -- Midas' Touch
    [C_ID .. 203] = "Bescheidenes Bündel", -- Humbleing Bundle
    [C_ID .. 204] = "Gürteltasche", -- Fanny Pack
    [C_ID .. 205] = "Scharfes Plug", -- Sharp Plug
    [C_ID .. 206] = "Guillotine", -- Guillotine
    [C_ID .. 207] = "Verbandsknäuel", -- Ball of Bandages
    [C_ID .. 208] = "Championgürtel", -- Champion Belt
    [C_ID .. 209] = "Arschbomben", -- Butt Bombs
    [C_ID .. 210] = "Angenagtes Blatt", -- Gnawed Leaf
    [C_ID .. 211] = "Spinnenbaby", -- Spiderbaby
    [C_ID .. 212] = "Guppys Halsband", -- Guppy's Collar
    [C_ID .. 213] = "Verlorene Linse", -- Lost Contact
    [C_ID .. 214] = "Anämie", -- Anemic
    [C_ID .. 215] = "Ziegenkopf", -- Goat Head
    [C_ID .. 216] = "Zeremonielle Robe", -- Ceremonial Robes
    [C_ID .. 217] = "Mamas Perücke", -- Mom's Wig
    [C_ID .. 218] = "Plazenta", -- Placenta
    [C_ID .. 219] = "Alter Verband", -- Old Bandage
    [C_ID .. 220] = "Traurige Bomben", -- Sad Bombs
    [C_ID .. 221] = "Gummizement", -- Rubber Cement
    [C_ID .. 222] = "Anti-Gravitation", -- Anti-Gravity
    [C_ID .. 223] = "Pyromane", -- Pyromaniac
    [C_ID .. 224] = "Crickets Körper", -- Cricket's Body
    [C_ID .. 225] = "Gimpy", -- Gimpy
    [C_ID .. 226] = "Schwarze Lotusblüte", -- Black Lotus
    [C_ID .. 227] = "Piggy Bank", -- Piggy Bank
    [C_ID .. 228] = "Mamas Parfum", -- Mom's Perfume
    [C_ID .. 229] = "Monstros Lunge", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Ball of Tar", -- Ball of Tar
    [C_ID .. 232] = "Stoppuhr", -- Stop Watch
    [C_ID .. 233] = "Winziger Planet", -- Tiny Planet
    [C_ID .. 234] = "Infestation 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "Death's Touch", -- Death's Touch
    [C_ID .. 238] = "Key Piece 1", -- Key Piece 1
    [C_ID .. 239] = "Key Piece 2", -- Key Piece 2
    [C_ID .. 240] = "Experimental Treatment", -- Experimental Treatment
    [C_ID .. 241] = "Contract from Below", -- Contract from Below
    [C_ID .. 242] = "Infamy", -- Infamy
    [C_ID .. 243] = "Trinity Shield", -- Trinity Shield
    [C_ID .. 244] = "Tech.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Blue Map", -- Blue Map
    [C_ID .. 247] = "BFFS!", -- BFFS!
    [C_ID .. 248] = "Bienenstock-Verstand", -- Hive Mind
    [C_ID .. 249] = "There's Options", -- There's Options
    [C_ID .. 250] = "Bogo Bomben", -- Bogo Bombs
    [C_ID .. 251] = "Starter Deck", -- Starter Deck
    [C_ID .. 252] = "Little Baggy", -- Little Baggy
    [C_ID .. 253] = "Magische Kruste", -- Magic Scab
    [C_ID .. 254] = "Blutklumpen", -- Blood Clot
    [C_ID .. 255] = "Screw", -- Screw
    [C_ID .. 256] = "Heiße Bomben", -- Hot Bombs
    [C_ID .. 257] = "Fire Mind", -- Fire Mind
    [C_ID .. 258] = "Missing No.", -- Missing No.
    [C_ID .. 259] = "Dark Matter", -- Dark Matter
    [C_ID .. 260] = "Black Candle", -- Black Candle
    [C_ID .. 261] = "Proptose", -- Proptosis
    [C_ID .. 262] = "Fehlende Seite 2", -- Missing Page 2
    [C_ID .. 263] = "Klare Rune", -- Clear Rune
    [C_ID .. 264] = "Kluge Fliege", -- Smart Fly
    [C_ID .. 265] = "Dry Baby", -- Dry Baby
    [C_ID .. 266] = "Juicy Sack", -- Juicy Sack
    [C_ID .. 267] = "Robo-Baby 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Rotten Baby", -- Rotten Baby
    [C_ID .. 269] = "Headless Baby", -- Headless Baby
    [C_ID .. 270] = "Leech", -- Leech
    [C_ID .. 271] = "Mystery Sack", -- Mystery Sack
    [C_ID .. 272] = "BBF", -- BBF
    [C_ID .. 273] = "Bobs Gehirn", -- Bob's Brain
    [C_ID .. 274] = "Bester Kumpel", -- Best Bud
    [C_ID .. 275] = "Lil Brimstone", -- Lil Brimstone
    [C_ID .. 276] = "Isaacs Herz", -- Isaac's Heart
    [C_ID .. 277] = "Lil Haunt", -- Lil Haunt
    [C_ID .. 278] = "Dunkler Bum", -- Dark Bum
    [C_ID .. 279] = "Big Fan", -- Big Fan
    [C_ID .. 280] = "Sissy Langbein", -- Sissy Longlegs
    [C_ID .. 281] = "Boxsack", -- Punching Bag
    [C_ID .. 282] = "How to Jump", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Blanko-Karte", -- Blank Card
    [C_ID .. 287] = "Buch der Geheimnisse", -- Book of Secrets
    [C_ID .. 288] = "Spinnenbox", -- Box of Spiders
    [C_ID .. 289] = "Rote Kerze", -- Red Candle
    [C_ID .. 290] = "The Jar", -- The Jar
    [C_ID .. 291] = "Spülen!", -- Flush!
    [C_ID .. 292] = "Satanische Bibel", -- Satanic Bible
    [C_ID .. 293] = "Head of Krampus", -- Head of Krampus
    [C_ID .. 294] = "Butterbohne", -- Butter Bean
    [C_ID .. 295] = "Magische Finger", -- Magic Fingers
    [C_ID .. 296] = "Konverter", -- Converter
    [C_ID .. 297] = "Pandoras Box", -- Pandora's Box
    [C_ID .. 298] = "Unicorn Stump", -- Unicorn Stump
    [C_ID .. 299] = "Taurus", -- Taurus
    [C_ID .. 300] = "Widder", -- Aries
    [C_ID .. 301] = "Cancer", -- Cancer
    [C_ID .. 302] = "Leo", -- Leo
    [C_ID .. 303] = "Virgo", -- Virgo
    [C_ID .. 304] = "Libra", -- Libra
    [C_ID .. 305] = "Scorpio", -- Scorpio
    [C_ID .. 306] = "Sagittarius", -- Sagittarius
    [C_ID .. 307] = "Steinbock", -- Capricorn
    [C_ID .. 308] = "Wassermann", -- Aquarius
    [C_ID .. 309] = "Fische", -- Pisces
    [C_ID .. 310] = "Evas Mascara", -- Eve's Mascara
    [C_ID .. 311] = "Judas' Shadow", -- Judas' Shadow
    [C_ID .. 312] = "Maggy's Bow", -- Maggy's Bow
    [C_ID .. 313] = "Holy Mantle", -- Holy Mantle
    [C_ID .. 314] = "Donner-Oberschenkel", -- Thunder Thighs
    [C_ID .. 315] = "Seltsamer Anzieher", -- Strange Attractor
    [C_ID .. 316] = "Verfluchte Träne", -- Cursed Eye
    [C_ID .. 317] = "Mysterious Liquid", -- Mysterious Liquid
    [C_ID .. 318] = "Gemini", -- Gemini
    [C_ID .. 319] = "Cains Anderes Auge", -- Cain's Other Eye
    [C_ID .. 320] = "???s Einziger Freund", -- ???'s Only Friend
    [C_ID .. 321] = "Samson's Chains", -- Samson's Chains
    [C_ID .. 322] = "Mongo Baby", -- Mongo Baby
    [C_ID .. 323] = "Isaacs Tränen", -- Isaac's Tears
    [C_ID .. 324] = "Undefined", -- Undefined
    [C_ID .. 325] = "Scissors", -- Scissors
    [C_ID .. 326] = "Atem Des Lebens", -- Breath of Life
    [C_ID .. 327] = "The Polaroid", -- The Polaroid
    [C_ID .. 328] = "Das Negative", -- The Negative
    [C_ID .. 329] = "Die Ludovico-Technik", -- The Ludovico Technique
    [C_ID .. 330] = "Sojamilch", -- Soy Milk
    [C_ID .. 331] = "Götterkopf", -- Godhead
    [C_ID .. 332] = "Lazarus' Rags", -- Lazarus' Rags
    [C_ID .. 333] = "The Mind", -- The Mind
    [C_ID .. 334] = "The Body", -- The Body
    [C_ID .. 335] = "The Soul", -- The Soul
    [C_ID .. 336] = "Tote Zwiebel", -- Dead Onion
    [C_ID .. 337] = "Broken Watch", -- Broken Watch
    [C_ID .. 338] = "The Boomerang", -- The Boomerang
    [C_ID .. 339] = "Sicherheitsnadel", -- Safety Pin
    [C_ID .. 340] = "Caffeine Pill", -- Caffeine Pill
    [C_ID .. 341] = "Torn Photo", -- Torn Photo
    [C_ID .. 342] = "Blaue Mütze", -- Blue Cap
    [C_ID .. 343] = "Latch Key", -- Latch Key
    [C_ID .. 344] = "Streichholzschachtel", -- Match Book
    [C_ID .. 345] = "Synthöl", -- Synthoil
    [C_ID .. 346] = "Ein Snack", -- A Snack
    [C_ID .. 347] = "Diplopia", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Wooden Nickel", -- Wooden Nickel
    [C_ID .. 350] = "Toxic Shock", -- Toxic Shock
    [C_ID .. 351] = "Mega Bohne", -- Mega Bean
    [C_ID .. 352] = "Glas-Kanone", -- Glass Cannon
    [C_ID .. 353] = "Bomber Boy", -- Bomber Boy
    [C_ID .. 354] = "Crack Jacks", -- Crack Jacks
    [C_ID .. 355] = "Mamas Perlen", -- Mom's Pearls
    [C_ID .. 356] = "Car Battery", -- Car Battery
    [C_ID .. 357] = "Box of Friends", -- Box of Friends
    [C_ID .. 358] = "The Wiz", -- The Wiz
    [C_ID .. 359] = "8 Inch Nails", -- 8 Inch Nails
    [C_ID .. 360] = "Brutus", -- Incubus
    [C_ID .. 361] = "Fate's Reward", -- Fate's Reward
    [C_ID .. 362] = "Lil Chest", -- Lil Chest
    [C_ID .. 363] = "Sworn Protector", -- Sworn Protector
    [C_ID .. 364] = "Friend Zone", -- Friend Zone
    [C_ID .. 365] = "Verlorene Fliege", -- Lost Fly
    [C_ID .. 366] = "Streubomben", -- Scatter Bombs
    [C_ID .. 367] = "Klebrige Bomben", -- Sticky Bombs
    [C_ID .. 368] = "Epiphora", -- Epiphora
    [C_ID .. 369] = "Kontinuum", -- Continuum
    [C_ID .. 370] = "Mr. Dolly", -- Mr. Dolly
    [C_ID .. 371] = "Curse of the Tower", -- Curse of the Tower
    [C_ID .. 372] = "Charged Baby", -- Charged Baby
    [C_ID .. 373] = "Dead Eye", -- Dead Eye
    [C_ID .. 374] = "Heiliges Licht", -- Holy Light
    [C_ID .. 375] = "Sternenhut", -- Host Hat
    [C_ID .. 376] = "Auffüllen", -- Restock
    [C_ID .. 377] = "Bursting Sack", -- Bursting Sack
    [C_ID .. 378] = "No. 2", -- No. 2
    [C_ID .. 379] = "Pupula Duplex", -- Pupula Duplex
    [C_ID .. 380] = "Bezahle zum Spielen", -- Pay To Play
    [C_ID .. 381] = "Eden's Blessing", -- Eden's Blessing
    [C_ID .. 382] = "Freundesball", -- Friendly Ball
    [C_ID .. 383] = "Tear Detonator", -- Tear Detonator
    [C_ID .. 384] = "Lil Gurdy", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Censer", -- Censer
    [C_ID .. 388] = "Key Bum", -- Key Bum
    [C_ID .. 389] = "Runenbeutel", -- Rune Bag
    [C_ID .. 390] = "Seraphim", -- Seraphim
    [C_ID .. 391] = "Verrat", -- Betrayal
    [C_ID .. 392] = "Zodiac", -- Zodiac
    [C_ID .. 393] = "Schlangenkuss", -- Serpent's Kiss
    [C_ID .. 394] = "Markiert", -- Marked
    [C_ID .. 395] = "Tech X", -- Tech X
    [C_ID .. 396] = "Ventricle Razor", -- Ventricle Razor
    [C_ID .. 397] = "Traktorstrahl", -- Tractor Beam
    [C_ID .. 398] = "God's Flesh", -- God's Flesh
    [C_ID .. 399] = "Schlund der Leere", -- Maw of the Void
    [C_ID .. 400] = "Spear of Destiny", -- Spear of Destiny
    [C_ID .. 401] = "Explosivo", -- Explosivo
    [C_ID .. 402] = "Chaos", -- Chaos
    [C_ID .. 403] = "Spider Mod", -- Spider Mod
    [C_ID .. 404] = "Furz-Baby", -- Farting Baby
    [C_ID .. 405] = "GB Bug", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Reinheit", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Empty Vessel", -- Empty Vessel
    [C_ID .. 410] = "Evil Eye", -- Evil Eye
    [C_ID .. 411] = "Lusty Blood", -- Lusty Blood
    [C_ID .. 412] = "Cambion Conception", -- Cambion Conception
    [C_ID .. 413] = "Immaculate Conception", -- Immaculate Conception
    [C_ID .. 414] = "More Options", -- More Options
    [C_ID .. 415] = "Krone des Lichts", -- Crown Of Light
    [C_ID .. 416] = "Tiefe Taschen", -- Deep Pockets
    [C_ID .. 417] = "Succubus", -- Succubus
    [C_ID .. 418] = "Fruit Cake", -- Fruit Cake
    [C_ID .. 419] = "Teleport 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Black Powder", -- Black Powder
    [C_ID .. 421] = "Nierenbohne", -- Kidney Bean
    [C_ID .. 422] = "Leuchtende Sanduhr", -- Glowing Hourglass
    [C_ID .. 423] = "Circle of Protection", -- Circle of Protection
    [C_ID .. 424] = "Sack Head", -- Sack Head
    [C_ID .. 425] = "Night Light", -- Night Light
    [C_ID .. 426] = "Besessener Fan", -- Obsessed Fan
    [C_ID .. 427] = "Mine Crafter", -- Mine Crafter
    [C_ID .. 428] = "PJs", -- PJs
    [C_ID .. 429] = "Head of the Keeper", -- Head of the Keeper
    [C_ID .. 430] = "Papa-Fliege", -- Papa Fly
    [C_ID .. 431] = "Multidimensionales Baby", -- Multidimensional Baby
    [C_ID .. 432] = "Glitzerbomben", -- Glitter Bombs
    [C_ID .. 433] = "Mein Schatten", -- My Shadow
    [C_ID .. 434] = "Jar of Flies", -- Jar of Flies
    [C_ID .. 435] = "Lil Loki", -- Lil Loki
    [C_ID .. 436] = "Milch!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Binky", -- Binky
    [C_ID .. 439] = "Mom's Box", -- Mom's Box
    [C_ID .. 440] = "Nierenstein", -- Kidney Stone
    [C_ID .. 441] = "Mega Blast", -- Mega Blast
    [C_ID .. 442] = "Krone des Dunklen Prinzen", -- Dark Prince's Crown
    [C_ID .. 443] = "Apple!", -- Apple!
    [C_ID .. 444] = "Bleistift", -- Lead Pencil
    [C_ID .. 445] = "Dog Tooth", -- Dog Tooth
    [C_ID .. 446] = "Dead Tooth", -- Dead Tooth
    [C_ID .. 447] = "Gartenbohne", -- Linger Bean
    [C_ID .. 448] = "Glasscherbe", -- Shard of Glass
    [C_ID .. 449] = "Metal Plate", -- Metal Plate
    [C_ID .. 450] = "Auge der Gier", -- Eye of Greed
    [C_ID .. 451] = "Tarot-Tuch", -- Tarot Cloth
    [C_ID .. 452] = "Varicose Veins", -- Varicose Veins
    [C_ID .. 453] = "Knochenbruch", -- Compound Fracture
    [C_ID .. 454] = "Polydactyly", -- Polydactyly
    [C_ID .. 455] = "Papas Verlorenes Geld", -- Dad's Lost Coin
    [C_ID .. 456] = "Mitternachtssnack", -- Midnight Snack
    [C_ID .. 457] = "Cone Head", -- Cone Head
    [C_ID .. 458] = "Belly Button", -- Belly Button
    [C_ID .. 459] = "Naseninfektion", -- Sinus Infection
    [C_ID .. 460] = "Glaucoma", -- Glaucoma
    [C_ID .. 461] = "Parasitoid", -- Parasitoid
    [C_ID .. 462] = "Auge von Belial", -- Eye of Belial
    [C_ID .. 463] = "Sulfuric Acid", -- Sulfuric Acid
    [C_ID .. 464] = "Glyphe des Gleichgewichts", -- Glyph of Balance
    [C_ID .. 465] = "Analog Stick", -- Analog Stick
    [C_ID .. 466] = "Contagion", -- Contagion
    [C_ID .. 467] = "Finger!", -- Finger!
    [C_ID .. 468] = "Schatten", -- Shade
    [C_ID .. 469] = "Depression", -- Depression
    [C_ID .. 470] = "Hushy", -- Hushy
    [C_ID .. 471] = "Lil Monstro", -- Lil Monstro
    [C_ID .. 472] = "Königsbaby", -- King Baby
    [C_ID .. 473] = "Big Chubby", -- Big Chubby
    [C_ID .. 474] = "Zerbrochene Glasskanone", -- Broken Glass Cannon
    [C_ID .. 475] = "Plan C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Leere", -- Void
    [C_ID .. 478] = "Pause", -- Pause
    [C_ID .. 479] = "Smelter", -- Smelter
    [C_ID .. 480] = "Compost", -- Compost
    [C_ID .. 481] = "Data-Miner", -- Dataminer
    [C_ID .. 482] = "Klicker", -- Clicker
    [C_ID .. 483] = "Mama Mega!", -- Mama Mega!
    [C_ID .. 484] = "Wait What?", -- Wait What?
    [C_ID .. 485] = "Crooked Penny", -- Crooked Penny
    [C_ID .. 486] = "Dull Razor", -- Dull Razor
    [C_ID .. 487] = "Kartoffelschäler", -- Potato Peeler
    [C_ID .. 488] = "Metronome", -- Metronome
    [C_ID .. 489] = "D Unendlichkeit", -- D Infinity
    [C_ID .. 490] = "Eden's Soul", -- Eden's Soul
    [C_ID .. 491] = "Säure-Baby", -- Acid Baby
    [C_ID .. 492] = "YO LISTEN!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenalin", -- Adrenaline
    [C_ID .. 494] = "Jacobs Leiter", -- Jacob's Ladder
    [C_ID .. 495] = "Geisterpfeffer", -- Ghost Pepper
    [C_ID .. 496] = "Euthanasie", -- Euthanasia
    [C_ID .. 497] = "Camo-Unterhosen", -- Camo Undies
    [C_ID .. 498] = "Duality", -- Duality
    [C_ID .. 499] = "Eucharist", -- Eucharist
    [C_ID .. 500] = "Sack of Sacks", -- Sack of Sacks
    [C_ID .. 501] = "Gier-Magen", -- Greed's Gullet
    [C_ID .. 502] = "Large Zit", -- Large Zit
    [C_ID .. 503] = "Kleines Horn", -- Little Horn
    [C_ID .. 504] = "Braune Pepitas", -- Brown Nugget
    [C_ID .. 505] = "Poke Go", -- Poke Go
    [C_ID .. 506] = "Hinterlistiger Mörder", -- Backstabber
    [C_ID .. 507] = "Scharfe Strohhalme", -- Sharp Straw
    [C_ID .. 508] = "Mamas Rasiermesser", -- Mom's Razor
    [C_ID .. 509] = "Blutiges Auge", -- Bloodshot Eye
    [C_ID .. 510] = "Im Delirium", -- Delirious
    [C_ID .. 511] = "Angry Fly", -- Angry Fly
    [C_ID .. 512] = "Black Hole", -- Black Hole
    [C_ID .. 513] = "Bozo", -- Bozo
    [C_ID .. 514] = "Kaputtes Modem", -- Broken Modem
    [C_ID .. 515] = "Mystery Gift", -- Mystery Gift
    [C_ID .. 516] = "Sprinkler", -- Sprinkler
    [C_ID .. 517] = "Schnellbomben", -- Fast Bombs
    [C_ID .. 518] = "Buddy in a Box", -- Buddy in a Box
    [C_ID .. 519] = "Lil Delirium", -- Lil Delirium
    [C_ID .. 520] = "Jumper Cables", -- Jumper Cables
    [C_ID .. 521] = "Coupon", -- Coupon
    [C_ID .. 522] = "Telekinesis", -- Telekinesis
    [C_ID .. 523] = "Umzugskarton", -- Moving Box
    [C_ID .. 524] = "Technologie Null", -- Technology Zero
    [C_ID .. 525] = "Leprosy", -- Leprosy
    [C_ID .. 526] = "7 Seals", -- 7 Seals
    [C_ID .. 527] = "Mr. ME!", -- Mr. ME!
    [C_ID .. 528] = "Angelic Prism", -- Angelic Prism
    [C_ID .. 529] = "Pop!", -- Pop!
    [C_ID .. 530] = "Death's List", -- Death's List
    [C_ID .. 531] = "Hämolyse", -- Haemolacria
    [C_ID .. 532] = "Lachryphagy", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Schoolbag", -- Schoolbag
    [C_ID .. 535] = "Blanket", -- Blanket
    [C_ID .. 536] = "Sacrificial Altar", -- Sacrificial Altar
    [C_ID .. 537] = "Lil Spewer", -- Lil Spewer
    [C_ID .. 538] = "Marbles", -- Marbles
    [C_ID .. 539] = "Mystery Egg", -- Mystery Egg
    [C_ID .. 540] = "Flat Stone", -- Flat Stone
    [C_ID .. 541] = "Marrow", -- Marrow
    [C_ID .. 542] = "Slipped Rib", -- Slipped Rib
    [C_ID .. 543] = "Heiliger Boden", -- Hallowed Ground
    [C_ID .. 544] = "Pointy Rib", -- Pointy Rib
    [C_ID .. 545] = "Book of the Dead", -- Book of the Dead
    [C_ID .. 546] = "Dad's Ring", -- Dad's Ring
    [C_ID .. 547] = "Divorce Papers", -- Divorce Papers
    [C_ID .. 548] = "Jaw Bone", -- Jaw Bone
    [C_ID .. 549] = "Brüchige Knochen", -- Brittle Bones
    [C_ID .. 550] = "Broken Shovel", -- Broken Shovel
    [C_ID .. 551] = "Broken Shovel", -- Broken Shovel
    [C_ID .. 552] = "Mamas Schaufel", -- Mom's Shovel
    [C_ID .. 553] = "Mukormykose", -- Mucormycosis
    [C_ID .. 554] = "2Spooky", -- 2Spooky
    [C_ID .. 555] = "Goldenes Rasiermesser", -- Golden Razor
    [C_ID .. 556] = "Schwefelsäure", -- Sulfur
    [C_ID .. 557] = "Glückskeks", -- Fortune Cookie
    [C_ID .. 558] = "Störendes Auge", -- Eye Sore
    [C_ID .. 559] = "120 Volt", -- 120 Volt
    [C_ID .. 560] = "Das tut weh", -- It Hurts
    [C_ID .. 561] = "Mandelmilch", -- Almond Milk
    [C_ID .. 562] = "Grundgestein", -- Rock Bottom
    [C_ID .. 563] = "Nancy-Bomben", -- Nancy Bombs
    [C_ID .. 564] = "Ein Stück Seife", -- A Bar of Soap
    [C_ID .. 565] = "Blutwelpe", -- Blood Puppy
    [C_ID .. 566] = "Traumfänger", -- Dream Catcher
    [C_ID .. 567] = "Osterkerze", -- Paschal Candle
    [C_ID .. 568] = "Göttliche Intervention", -- Divine Intervention
    [C_ID .. 569] = "Blutpakt", -- Blood Oath
    [C_ID .. 570] = "Play-Doh-Keks", -- Playdough Cookie
    [C_ID .. 571] = "Waisensocken", -- Orphan Socks
    [C_ID .. 572] = "Auge des Okkulten", -- Eye of the Occult
    [C_ID .. 573] = "Unbeflecktes Herz", -- Immaculate Heart
    [C_ID .. 574] = "Monstranz", -- Monstrance
    [C_ID .. 575] = "Der Eindringling", -- The Intruder
    [C_ID .. 576] = "Schmutziger Verstand", -- Dirty Mind
    [C_ID .. 577] = "Damokles", -- Damocles
    [C_ID .. 578] = "Gratislimonade", -- Free Lemonade
    [C_ID .. 579] = "Geistschwert", -- Spirit Sword
    [C_ID .. 580] = "Roter Schlüssel", -- Red Key
    [C_ID .. 581] = "Psy-Fliege", -- Psy Fly
    [C_ID .. 582] = "Wellenmütze", -- Wavy Cap
    [C_ID .. 583] = "Rakete im Glas", -- Rocket in a Jar
    [C_ID .. 584] = "Buch der Tugenden", -- Book of Virtues
    [C_ID .. 585] = "Alabaster-Box", -- Alabaster Box
    [C_ID .. 586] = "Die Treppe", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Mond", -- Luna
    [C_ID .. 590] = "Merkur", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Erde", -- Terra
    [C_ID .. 593] = "Mars", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturn", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptun", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Voodoopuppe", -- Voodoo Head
    [C_ID .. 600] = "Augentropfen", -- Eye Drops
    [C_ID .. 601] = "Akt der Reue", -- Act of Contrition
    [C_ID .. 602] = "Mitgliedskarte", -- Member Card
    [C_ID .. 603] = "Batteriepaket", -- Battery Pack
    [C_ID .. 604] = "Mamas Armband", -- Mom's Bracelet
    [C_ID .. 605] = "Die Schaufel", -- The Scooper
    [C_ID .. 606] = "Okularriss", -- Ocular Rift
    [C_ID .. 607] = "Gekochtes Baby", -- Boiled Baby
    [C_ID .. 608] = "Gefrierbaby", -- Freezer Baby
    [C_ID .. 609] = "Ewiges D6", -- Eternal D6
    [C_ID .. 610] = "Vogelkäfig", -- Bird Cage
    [C_ID .. 611] = "Kehlkopf", -- Larynx
    [C_ID .. 612] = "Verlorene Seele", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Blutbomben", -- Blood Bombs
    [C_ID .. 615] = "Lil Dumpy", -- Lil Dumpy
    [C_ID .. 616] = "Vogelperspektive", -- Bird's Eye
    [C_ID .. 617] = "Magneteisen", -- Lodestone
    [C_ID .. 618] = "Verfaulte Tomate", -- Rotten Tomato
    [C_ID .. 619] = "Geburtsrecht", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Roter Eintopf", -- Red Stew
    [C_ID .. 622] = "Genesis", -- Genesis
    [C_ID .. 623] = "Scharfer Schlüssel", -- Sharp Key
    [C_ID .. 624] = "Booster-Pack", -- Booster Pack
    [C_ID .. 625] = "Mega-Pilz", -- Mega Mush
    [C_ID .. 626] = "Messerstück 1", -- Knife Piece 1
    [C_ID .. 627] = "Messerstück 2", -- Knife Piece 2
    [C_ID .. 628] = "Totenschein", -- Death Certificate
    [C_ID .. 629] = "Bot Fliege", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Fleischermesser", -- Meat Cleaver
    [C_ID .. 632] = "Böser Schutzstein", -- Evil Charm
    [C_ID .. 633] = "Dogma", -- Dogma
    [C_ID .. 634] = "Fegefeuer", -- Purgatory
    [C_ID .. 635] = "Stiche", -- Stitches
    [C_ID .. 636] = "R-Taste", -- R Key
    [C_ID .. 637] = "K.O.-Tropfen", -- Knockout Drops
    [C_ID .. 638] = "Radiergummi", -- Eraser
    [C_ID .. 639] = "Ekelherz", -- Yuck Heart
    [C_ID .. 640] = "Urne Der Seelen", -- Urn of Souls
    [C_ID .. 641] = "Blutacker", -- Akeldama
    [C_ID .. 642] = "Zauberhaut", -- Magic Skin
    [C_ID .. 643] = "Offenbarung", -- Revelation
    [C_ID .. 644] = "Trostpreis", -- Consolation Prize
    [C_ID .. 645] = "Tinytoma", -- Tinytoma
    [C_ID .. 646] = "Schwefelbomben", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volt", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Fruchtiger Plum", -- Fruity Plum
    [C_ID .. 650] = "Plum-Flöte", -- Plum Flute
    [C_ID .. 651] = "Stern von Bethlehem", -- Star of Bethlehem
    [C_ID .. 652] = "Würfelbaby", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "Falsches PHD", -- False PHD
    [C_ID .. 655] = "Drehe Zum Gewinnen", -- Spin to Win
    [C_ID .. 656] = "Damokles", -- Damocles
    [C_ID .. 657] = "Vaskulitis", -- Vasculitis
    [C_ID .. 658] = "Riesenzelle", -- Giant Cell
    [C_ID .. 659] = "Tropicamid", -- Tropicamide
    [C_ID .. 660] = "Kartenlesen", -- Card Reading
    [C_ID .. 661] = "Quints", -- Quints
    [C_ID .. 662] = "", -- 
    [C_ID .. 663] = "Zahn und Nagel", -- Tooth and Nail
    [C_ID .. 664] = "Vielfraß", -- Binge Eater
    [C_ID .. 665] = "Guppys Auge", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Strohmann", -- Strawman
    [C_ID .. 668] = "Papas Notiz", -- Dad's Note
    [C_ID .. 669] = "Wurst", -- Sausage
    [C_ID .. 670] = "Optionen?", -- Options?
    [C_ID .. 671] = "Bonbonherz", -- Candy Heart
    [C_ID .. 672] = "Ein Pfund Fleisch", -- A Pound of Flesh
    [C_ID .. 673] = "Erlösung", -- Redemption
    [C_ID .. 674] = "Geistschellen", -- Spirit Shackles
    [C_ID .. 675] = "Rissige Kugel", -- Cracked Orb
    [C_ID .. 676] = "Leeres Herz", -- Empty Heart
    [C_ID .. 677] = "Astrale Projektion", -- Astral Projection
    [C_ID .. 678] = "Kaiserschnitt", -- C Section
    [C_ID .. 679] = "Lil Abaddon", -- Lil Abaddon
    [C_ID .. 680] = "Montezumas Rache", -- Montezuma's Revenge
    [C_ID .. 681] = "Kleines Portal", -- Lil Portal
    [C_ID .. 682] = "Wurmfreund", -- Worm Friend
    [C_ID .. 683] = "Knochensporn", -- Bone Spurs
    [C_ID .. 684] = "Hungrige Seele", -- Hungry Soul
    [C_ID .. 685] = "Glas mit Irrlichtern", -- Jar of Wisps
    [C_ID .. 686] = "Seelenamulett", -- Soul Locket
    [C_ID .. 687] = "Freundesfinder", -- Friend Finder
    [C_ID .. 688] = "Inneres Kind", -- Inner Child
    [C_ID .. 689] = "Geflickte Krone", -- Glitched Crown
    [C_ID .. 690] = "Bauchgelee", -- Belly Jelly
    [C_ID .. 691] = "Heilige Kugel", -- Sacred Orb
    [C_ID .. 692] = "Sanguine Bindung", -- Sanguine Bond
    [C_ID .. 693] = "Der Schwarm", -- The Swarm
    [C_ID .. 694] = "Herzschmerz", -- Heartbreak
    [C_ID .. 695] = "Blutiger Windstoß", -- Bloody Gust
    [C_ID .. 696] = "Heilung", -- Salvation
    [C_ID .. 697] = "Verschwindender Zwilling", -- Vanishing Twin
    [C_ID .. 698] = "Verdrehtes Paar", -- Twisted Pair
    [C_ID .. 699] = "Azazels Zorn", -- Azazel's Rage
    [C_ID .. 700] = "Echo-Kammer", -- Echo Chamber
    [C_ID .. 701] = "Isaacs Grab", -- Isaac's Tomb
    [C_ID .. 702] = "Racheerfüllter Geist", -- Vengeful Spirit
    [C_ID .. 703] = "Esau Jr.", -- Esau Jr.
    [C_ID .. 704] = "Berserker!", -- Berserk!
    [C_ID .. 705] = "Dunkle Künste", -- Dark Arts
    [C_ID .. 706] = "Abgrund", -- Abyss
    [C_ID .. 707] = "Abendessen", -- Supper
    [C_ID .. 708] = "Tacker", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Tasche des Handwerks", -- Bag of Crafting
    [C_ID .. 711] = "Wenden", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Abruf", -- Recall
    [C_ID .. 715] = "Festhalten", -- Hold
    [C_ID .. 716] = "Sack Des Keepers", -- Keeper's Sack
    [C_ID .. 717] = "Keepers Sippe", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "Keepers Kiste", -- Keeper's Box
    [C_ID .. 720] = "Allesglas", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Spindown-Würfel", -- Spindown Dice
    [C_ID .. 724] = "Hyperkoagulation", -- Hypercoagulation
    [C_ID .. 725] = "IBS", -- IBS
    [C_ID .. 726] = "Hämoptysis", -- Hemoptysis
    [C_ID .. 727] = "Geisterbomben", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Enthauptungsangriff", -- Decap Attack
    [C_ID .. 730] = "Glasauge", -- Glass Eye
    [C_ID .. 731] = "Gerstenkorn", -- Stye
    [C_ID .. 732] = "Mamas Ring", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "", -- Swallowed Penny
    [T_ID .. 2] = "", -- Petrified Poop
    [T_ID .. 3] = "", -- AAA Battery
    [T_ID .. 4] = "", -- Broken Remote
    [T_ID .. 5] = "", -- Purple Heart
    [T_ID .. 6] = "", -- Broken Magnet
    [T_ID .. 7] = "", -- Rosary Bead
    [T_ID .. 8] = "", -- Cartridge
    [T_ID .. 9] = "", -- Pulse Worm
    [T_ID .. 10] = "Wiggle Worm", -- Wiggle Worm
    [T_ID .. 11] = "Ring Worm", -- Ring Worm
    [T_ID .. 12] = "", -- Flat Worm
    [T_ID .. 13] = "", -- Store Credit
    [T_ID .. 14] = "", -- Callus
    [T_ID .. 15] = "Lucky Rock", -- Lucky Rock
    [T_ID .. 16] = "Mamas Zehennagel", -- Mom's Toenail
    [T_ID .. 17] = "", -- Black Lipstick
    [T_ID .. 18] = "", -- Bible Tract
    [T_ID .. 19] = "", -- Paper Clip
    [T_ID .. 20] = "", -- Monkey Paw
    [T_ID .. 21] = "", -- Mysterious Paper
    [T_ID .. 22] = "", -- Daemon's Tail
    [T_ID .. 23] = "", -- Missing Poster
    [T_ID .. 24] = "Po-Penny", -- Butt Penny
    [T_ID .. 25] = "", -- Mysterious Candy
    [T_ID .. 26] = "Hakenschwanz", -- Hook Worm
    [T_ID .. 27] = "", -- Whip Worm
    [T_ID .. 28] = "", -- Broken Ankh
    [T_ID .. 29] = "", -- Fish Head
    [T_ID .. 30] = "", -- Pinky Eye
    [T_ID .. 31] = "", -- Push Pin
    [T_ID .. 32] = "Freiheitskappe", -- Liberty Cap
    [T_ID .. 33] = "Nabelschnur", -- Umbilical Cord
    [T_ID .. 34] = "", -- Child's Heart
    [T_ID .. 35] = "", -- Curved Horn
    [T_ID .. 36] = "", -- Rusted Key
    [T_ID .. 37] = "", -- Goat Hoof
    [T_ID .. 38] = "", -- Mom's Pearl
    [T_ID .. 39] = "Krebs", -- Cancer
    [T_ID .. 40] = "", -- Red Patch
    [T_ID .. 41] = "", -- Match Stick
    [T_ID .. 42] = "", -- Lucky Toe
    [T_ID .. 43] = "", -- Cursed Skull
    [T_ID .. 44] = "", -- Safety Cap
    [T_ID .. 45] = "", -- Ace of Spades
    [T_ID .. 46] = "", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "Eine fehlende Seite", -- A Missing Page
    [T_ID .. 49] = "Blutige Münze", -- Bloody Penny
    [T_ID .. 50] = "Verbrannte Münze", -- Burnt Penny
    [T_ID .. 51] = "Flache Münze", -- Flat Penny
    [T_ID .. 52] = "", -- Counterfeit Penny
    [T_ID .. 53] = "Zecke", -- Tick
    [T_ID .. 54] = "", -- Isaac's Head
    [T_ID .. 55] = "", -- Maggy's Faith
    [T_ID .. 56] = "", -- Judas' Tongue
    [T_ID .. 57] = "", -- ???'s Soul
    [T_ID .. 58] = "", -- Samson's Lock
    [T_ID .. 59] = "", -- Cain's Eye
    [T_ID .. 60] = "", -- Eve's Bird Foot
    [T_ID .. 61] = "", -- The Left Hand
    [T_ID .. 62] = "", -- Shiny Rock
    [T_ID .. 63] = "", -- Safety Scissors
    [T_ID .. 64] = "", -- Rainbow Worm
    [T_ID .. 65] = "Klebebandwurm", -- Tape Worm
    [T_ID .. 66] = "Faule Made", -- Lazy Worm
    [T_ID .. 67] = "Rissiger Würfel", -- Cracked Dice
    [T_ID .. 68] = "", -- Super Magnet
    [T_ID .. 69] = "Verblasste Polaroid", -- Faded Polaroid
    [T_ID .. 70] = "", -- Louse
    [T_ID .. 71] = "", -- Bob's Bladder
    [T_ID .. 72] = "", -- Watch Battery
    [T_ID .. 73] = "", -- Blasting Cap
    [T_ID .. 74] = "", -- Stud Finder
    [T_ID .. 75] = "", -- Error
    [T_ID .. 76] = "", -- Poker Chip
    [T_ID .. 77] = "", -- Blister
    [T_ID .. 78] = "", -- Second Hand
    [T_ID .. 79] = "", -- Endless Nameless
    [T_ID .. 80] = "Schwarze Feder", -- Black Feather
    [T_ID .. 81] = "", -- Blind Rage
    [T_ID .. 82] = "", -- Golden Horse Shoe
    [T_ID .. 83] = "", -- Store Key
    [T_ID .. 84] = "", -- Rib of Greed
    [T_ID .. 85] = "", -- Karma
    [T_ID .. 86] = "", -- Lil Larva
    [T_ID .. 87] = "", -- Mom's Locket
    [T_ID .. 88] = "", -- NO!
    [T_ID .. 89] = "", -- Child Leash
    [T_ID .. 90] = "", -- Brown Cap
    [T_ID .. 91] = "", -- Meconium
    [T_ID .. 92] = "Rissige Krone", -- Cracked Crown
    [T_ID .. 93] = "", -- Used Diaper
    [T_ID .. 94] = "", -- Fish Tail
    [T_ID .. 95] = "", -- Black Tooth
    [T_ID .. 96] = "Ouroboros-Wurm", -- Ouroboros Worm
    [T_ID .. 97] = "Mandel", -- Tonsil
    [T_ID .. 98] = "Nasengoblin", -- Nose Goblin
    [T_ID .. 99] = "", -- Super Ball
    [T_ID .. 100] = "", -- Vibrant Bulb
    [T_ID .. 101] = "Dimmbare Glühbirne", -- Dim Bulb
    [T_ID .. 102] = "", -- Fragmented Card
    [T_ID .. 103] = "", -- Equality!
    [T_ID .. 104] = "Wunschknochen", -- Wish Bone
    [T_ID .. 105] = "Lunchpaket", -- Bag Lunch
    [T_ID .. 106] = "", -- Lost Cork
    [T_ID .. 107] = "Krähenherz", -- Crow Heart
    [T_ID .. 108] = "", -- Walnut
    [T_ID .. 109] = "", -- Duct Tape
    [T_ID .. 110] = "Silberdollar", -- Silver Dollar
    [T_ID .. 111] = "Blutige Krone", -- Bloody Crown
    [T_ID .. 112] = "", -- Pay To Win
    [T_ID .. 113] = "", -- Locust of War
    [T_ID .. 114] = "", -- Locust of Pestilence
    [T_ID .. 115] = "", -- Locust of Famine
    [T_ID .. 116] = "", -- Locust of Death
    [T_ID .. 117] = "", -- Locust of Conquest
    [T_ID .. 118] = "", -- Bat Wing
    [T_ID .. 119] = "Stammzelle", -- Stem Cell
    [T_ID .. 120] = "", -- Hairpin
    [T_ID .. 121] = "", -- Wooden Cross
    [T_ID .. 122] = "", -- Butter!
    [T_ID .. 123] = "", -- Filigree Feather
    [T_ID .. 124] = "", -- Door Stop
    [T_ID .. 125] = "", -- Extension Cord
    [T_ID .. 126] = "", -- Rotten Penny
    [T_ID .. 127] = "", -- Baby-Bender
    [T_ID .. 128] = "Fingerknochen", -- Finger Bone
    [T_ID .. 129] = "Kieferbrecher", -- Jawbreaker
    [T_ID .. 130] = "Zerkauter Stift", -- Chewed Pen
    [T_ID .. 131] = "Gesegnete Münze", -- Blessed Penny
    [T_ID .. 132] = "Defekte Spritze", -- Broken Syringe
    [T_ID .. 133] = "Kurze Zündschnur", -- Short Fuse
    [T_ID .. 134] = "Riesenbohne", -- Gigante Bean
    [T_ID .. 135] = "Ein Feuerzeug", -- A Lighter
    [T_ID .. 136] = "Kaputtes Vorhängeschloss", -- Broken Padlock
    [T_ID .. 137] = "Vergissmeinnicht", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Tränentropfen-Charme", -- Teardrop Charm
    [T_ID .. 140] = "Apfel von Sodom", -- Apple of Sodom
    [T_ID .. 141] = "Vergessene Wiegenlied", -- Forgotten Lullaby
    [T_ID .. 142] = "Beths Glaube", -- Beth's Faith
    [T_ID .. 143] = "Alte Kapazität", -- Old Capacitor
    [T_ID .. 144] = "Gehirnwurm", -- Brain Worm
    [T_ID .. 145] = "Vollkommenheit", -- Perfection
    [T_ID .. 146] = "Teufelskrone", -- Devil's Crown
    [T_ID .. 147] = "Geladene Münze", -- Charged Penny
    [T_ID .. 148] = "Freundschaftskette", -- Friendship Necklace
    [T_ID .. 149] = "Panikknopf", -- Panic Button
    [T_ID .. 150] = "Blauer Schlüssel", -- Blue Key
    [T_ID .. 151] = "Flache Feile", -- Flat File
    [T_ID .. 152] = "Teleskoplinse", -- Telescope Lens
    [T_ID .. 153] = "Mamas Schloss", -- Mom's Lock
    [T_ID .. 154] = "Würfelbeutel", -- Dice Bag
    [T_ID .. 155] = "Heilige Krone", -- Holy Crown
    [T_ID .. 156] = "Mutters Kuss", -- Mother's Kiss
    [T_ID .. 157] = "Zerrissene Karte", -- Torn Card
    [T_ID .. 158] = "Zerrissene Tasche", -- Torn Pocket
    [T_ID .. 159] = "Vergoldeter Schlüssel", -- Gilded Key
    [T_ID .. 160] = "Glückssack", -- Lucky Sack
    [T_ID .. 161] = "Böse Krone", -- Wicked Crown
    [T_ID .. 162] = "Azazels Stumpf", -- Azazel's Stump
    [T_ID .. 163] = "Dingle Berry", -- Dingle Berry
    [T_ID .. 164] = "Ringkappe", -- Ring Cap
    [T_ID .. 165] = "Nuh Uh!", -- Nuh Uh!
    [T_ID .. 166] = "Modelliermasse", -- Modeling Clay
    [T_ID .. 167] = "Polierter Knochen", -- Polished Bone
    [T_ID .. 168] = "Hohles Herz", -- Hollow Heart
    [T_ID .. 169] = "Kinderzeichnung", -- Kid's Drawing
    [T_ID .. 170] = "Kristallschlüssel", -- Crystal Key
    [T_ID .. 171] = "Des Keepers Schnäppchen", -- Keeper's Bargain
    [T_ID .. 172] = "Verfluchte Münze", -- Cursed Penny
    [T_ID .. 173] = "Deine Seele", -- Your Soul
    [T_ID .. 174] = "Zahlenmagnet", -- Number Magnet
    [T_ID .. 175] = "Seltsamer Schlüssel", -- Strange Key
    [T_ID .. 176] = "Lil Gerinnsel", -- Lil Clot
    [T_ID .. 177] = "Temporäres Tattoo", -- Temporary Tattoo
    [T_ID .. 178] = "Verschluckte M80", -- Swallowed M80
    [T_ID .. 179] = "RC-Fernbedienung", -- RC Remote
    [T_ID .. 180] = "Gefundene Seele", -- Found Soul
    [T_ID .. 181] = "Erweiterungspack", -- Expansion Pack
    [T_ID .. 182] = "Beths Essenz", -- Beth's Essence
    [T_ID .. 183] = "Die Zwillinge", -- The Twins
    [T_ID .. 184] = "Adoptionspapiere", -- Adoption Papers
    [T_ID .. 185] = "Crickets Bein", -- Cricket Leg
    [T_ID .. 186] = "Apollyons bester Freund", -- Apollyon's Best Friend
    [T_ID .. 187] = "Kaputte Brille", -- Broken Glasses
    [T_ID .. 188] = "Eiswürfel", -- Ice Cube
    [T_ID .. 189] = "Siegel von Baphomet", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "", -- 0 - The Fool
    [Card_ID .. 2] = "I - Der Magier", -- I - The Magician
    [Card_ID .. 3] = "", -- II - The High Priestess
    [Card_ID .. 4] = "", -- III - The Empress
    [Card_ID .. 5] = "", -- IV - The Emperor
    [Card_ID .. 6] = "", -- V - The Hierophant
    [Card_ID .. 7] = "", -- VI - The Lovers
    [Card_ID .. 8] = "", -- VII - The Chariot
    [Card_ID .. 9] = "", -- VIII - Justice
    [Card_ID .. 10] = "", -- IX - The Hermit
    [Card_ID .. 11] = "X - Glücksrad", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Die Kraft", -- XI - Strength
    [Card_ID .. 13] = "", -- XII - The Hanged Man
    [Card_ID .. 14] = "", -- XIII - Death
    [Card_ID .. 15] = "", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Der Teufel", -- XV - The Devil
    [Card_ID .. 17] = "", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Die Sterne", -- XVII - The Stars
    [Card_ID .. 19] = "", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Die Sonne", -- XIX - The Sun
    [Card_ID .. 21] = "", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Die Welt", -- XXI - The World
    [Card_ID .. 23] = "", -- 2 of Clubs
    [Card_ID .. 24] = "", -- 2 of Diamonds
    [Card_ID .. 25] = "", -- 2 of Spades
    [Card_ID .. 26] = "", -- 2 of Hearts
    [Card_ID .. 27] = "Karo Ass", -- Ace of Clubs
    [Card_ID .. 28] = "Kreuz Ass", -- Ace of Diamonds
    [Card_ID .. 29] = "Pik Ass", -- Ace of Spades
    [Card_ID .. 30] = "Herz Ass", -- Ace of Hearts
    [Card_ID .. 31] = "", -- Joker
    [Card_ID .. 32] = "", -- Hagalaz
    [Card_ID .. 33] = "", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "", -- Dagaz
    [Card_ID .. 36] = "", -- Ansuz
    [Card_ID .. 37] = "", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "", -- Blank Rune
    [Card_ID .. 41] = "", -- Black Rune
    [Card_ID .. 42] = "Chaoskarte", -- Chaos Card
    [Card_ID .. 43] = "", -- Credit Card
    [Card_ID .. 44] = "", -- Rules Card
    [Card_ID .. 45] = "", -- A Card Against Humanity
    [Card_ID .. 46] = "", -- Suicide King
    [Card_ID .. 47] = "", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "", -- ? Card
    [Card_ID .. 49] = "", -- Dice Shard
    [Card_ID .. 50] = "", -- Emergency Contact
    [Card_ID .. 51] = "Heilige Karte", -- Holy Card
    [Card_ID .. 52] = "Riesiges Wachstum", -- Huge Growth
    [Card_ID .. 53] = "", -- Ancient Recall
    [Card_ID .. 54] = "", -- Era Walk
    [Card_ID .. 55] = "Runenscherbe", -- Rune Shard
    [Card_ID .. 56] = "0 - Der Narr?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Der Magier?", -- I - The Magician?
    [Card_ID .. 58] = "II - Die Hohepriesterin?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - Die Kaiserin?", -- III - The Empress?
    [Card_ID .. 60] = "IV - Der Kaiser?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Der Hierophant?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Die Liebenden?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Der Wagen?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Die Gerechtigkeit?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - Der Eremit?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Rad des Schicksals?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Die Stärke?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Der Gehängte?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Tod?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Mäßigkeit?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Der Teufel?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - Der Turm?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Die Sterne?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - Der Mond?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Die Sonne?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Das Gericht?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Die Welt?", -- XXI - The World?
    [Card_ID .. 78] = "Geplatzter Schlüssel", -- Cracked Key
    [Card_ID .. 79] = "Herzdame", -- Queen of Hearts
    [Card_ID .. 80] = "Wilde Karte", -- Wild Card
    [Card_ID .. 81] = "Seele von Isaac", -- Soul of Isaac
    [Card_ID .. 82] = "Seele von Magdalena", -- Soul of Magdalene
    [Card_ID .. 83] = "Seele von Kain", -- Soul of Cain
    [Card_ID .. 84] = "Seele von Judas", -- Soul of Judas
    [Card_ID .. 85] = "Seele von ???", -- Soul of ???
    [Card_ID .. 86] = "Seele von Eva", -- Soul of Eve
    [Card_ID .. 87] = "Seele von Samson", -- Soul of Samson
    [Card_ID .. 88] = "Seele von Azazel", -- Soul of Azazel
    [Card_ID .. 89] = "Seele von Lazarus", -- Soul of Lazarus
    [Card_ID .. 90] = "Seele von Eden", -- Soul of Eden
    [Card_ID .. 91] = "Seele von The Lost", -- Soul of the Lost
    [Card_ID .. 92] = "Seele von Lilith", -- Soul of Lilith
    [Card_ID .. 93] = "Seele von Keeper", -- Soul of the Keeper
    [Card_ID .. 94] = "Seele von Apollyon", -- Soul of Apollyon
    [Card_ID .. 95] = "Seele von The Forgotten ", -- Soul of the Forgotten
    [Card_ID .. 96] = "Seele von Bethany", -- Soul of Bethany
    [Card_ID .. 97] = "Seele von Jacob und Esau", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "", -- Bad Gas
    [Pill_ID .. 2] = "", -- Bad Trip
    [Pill_ID .. 3] = "", -- Balls of Steel
    [Pill_ID .. 4] = "Bomben sind Schlüssel", -- Bombs are Key
    [Pill_ID .. 5] = "", -- Explosive Diarrhea
    [Pill_ID .. 6] = "", -- Full Health
    [Pill_ID .. 7] = "", -- Health Down
    [Pill_ID .. 8] = "", -- Health Up
    [Pill_ID .. 9] = "", -- I Found Pills
    [Pill_ID .. 10] = "", -- Puberty
    [Pill_ID .. 11] = "", -- Pretty Fly
    [Pill_ID .. 12] = "Reichweite runter", -- Range Down
    [Pill_ID .. 13] = "Reichweite rauf", -- Range Up
    [Pill_ID .. 14] = "", -- Speed Down
    [Pill_ID .. 15] = "", -- Speed Up
    [Pill_ID .. 16] = "", -- Tears Down
    [Pill_ID .. 17] = "", -- Tears Up
    [Pill_ID .. 18] = "", -- Luck Down
    [Pill_ID .. 19] = "", -- Luck Up
    [Pill_ID .. 20] = "", -- Telepills
    [Pill_ID .. 21] = "", -- 48 Hour Energy!
    [Pill_ID .. 22] = "", -- Hematemesis
    [Pill_ID .. 23] = "", -- Paralysis
    [Pill_ID .. 24] = "", -- I can see forever!
    [Pill_ID .. 25] = "", -- Pheromones
    [Pill_ID .. 26] = "", -- Amnesia
    [Pill_ID .. 27] = "", -- Lemon Party
    [Pill_ID .. 28] = "", -- R U A Wizard?
    [Pill_ID .. 29] = "", -- Percs!
    [Pill_ID .. 30] = "", -- Addicted!
    [Pill_ID .. 31] = "", -- Re-Lax
    [Pill_ID .. 32] = "", -- ???
    [Pill_ID .. 33] = "", -- One makes you larger
    [Pill_ID .. 34] = "", -- One makes you small
    [Pill_ID .. 35] = "", -- Infested!
    [Pill_ID .. 36] = "", -- Infested?
    [Pill_ID .. 37] = "", -- Power Pill!
    [Pill_ID .. 38] = "Retro Vision", -- Retro Vision
    [Pill_ID .. 39] = "", -- Friends Till The End!
    [Pill_ID .. 40] = "", -- X-Lax
    [Pill_ID .. 41] = "", -- Something's wrong...
    [Pill_ID .. 42] = "Ich bin müde...", -- I'm Drowsy...
    [Pill_ID .. 43] = "Ich bin aufgeregt!!", -- I'm Excited!!
    [Pill_ID .. 44] = "", -- Gulp!
    [Pill_ID .. 45] = "", -- Horf!
    [Pill_ID .. 46] = "", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "", -- Vurp!
    [Pill_ID .. 48] = "Schussspeed runter", -- Shot speed Down
    [Pill_ID .. 49] = "Schussspeed rauf", -- Shot speed Up
    [Pill_ID .. 50] = "Experimentelle Pille", -- Experimental Pill
    [Pill_ID .. 9999] = "Goldene Pille", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])