-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.

local languageCode = "en_us"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "The Sad Onion", -- The Sad Onion
    [C_ID .. 2] = "The Inner Eye", -- The Inner Eye
    [C_ID .. 3] = "Spoon Bender", -- Spoon Bender
    [C_ID .. 4] = "Cricket's Head", -- Cricket's Head
    [C_ID .. 5] = "My Reflection", -- My Reflection
    [C_ID .. 6] = "Number One", -- Number One
    [C_ID .. 7] = "Blood of the Martyr", -- Blood of the Martyr
    [C_ID .. 8] = "Brother Bobby", -- Brother Bobby
    [C_ID .. 9] = "Skatole", -- Skatole
    [C_ID .. 10] = "Halo of Flies", -- Halo of Flies
    [C_ID .. 11] = "1up!", -- 1up!
    [C_ID .. 12] = "Magic Mushroom", -- Magic Mushroom
    [C_ID .. 13] = "The Virus", -- The Virus
    [C_ID .. 14] = "Roid Rage", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Raw Liver", -- Raw Liver
    [C_ID .. 17] = "Skeleton Key", -- Skeleton Key
    [C_ID .. 18] = "A Dollar", -- A Dollar
    [C_ID .. 19] = "Boom!", -- Boom!
    [C_ID .. 20] = "Transcendence", -- Transcendence
    [C_ID .. 21] = "The Compass", -- The Compass
    [C_ID .. 22] = "Lunch", -- Lunch
    [C_ID .. 23] = "Dinner", -- Dinner
    [C_ID .. 24] = "Dessert", -- Dessert
    [C_ID .. 25] = "Breakfast", -- Breakfast
    [C_ID .. 26] = "Rotten Meat", -- Rotten Meat
    [C_ID .. 27] = "Wooden Spoon", -- Wooden Spoon
    [C_ID .. 28] = "The Belt", -- The Belt
    [C_ID .. 29] = "Mom's Underwear", -- Mom's Underwear
    [C_ID .. 30] = "Mom's Heels", -- Mom's Heels
    [C_ID .. 31] = "Mom's Lipstick", -- Mom's Lipstick
    [C_ID .. 32] = "Wire Coat Hanger", -- Wire Coat Hanger
    [C_ID .. 33] = "The Bible", -- The Bible
    [C_ID .. 34] = "The Book of Belial", -- The Book of Belial
    [C_ID .. 35] = "The Necronomicon", -- The Necronomicon
    [C_ID .. 36] = "The Poop", -- The Poop
    [C_ID .. 37] = "Mr. Boom", -- Mr. Boom
    [C_ID .. 38] = "Tammy's Head", -- Tammy's Head
    [C_ID .. 39] = "Mom's Bra", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Mom's Pad", -- Mom's Pad
    [C_ID .. 42] = "Bob's Rotten Head", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teleport!", -- Teleport!
    [C_ID .. 45] = "Yum Heart", -- Yum Heart
    [C_ID .. 46] = "Lucky Foot", -- Lucky Foot
    [C_ID .. 47] = "Doctor's Remote", -- Doctor's Remote
    [C_ID .. 48] = "Cupid's Arrow", -- Cupid's Arrow
    [C_ID .. 49] = "Shoop da Whoop!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagram", -- Pentagram
    [C_ID .. 52] = "Dr. Fetus", -- Dr. Fetus
    [C_ID .. 53] = "Magneto", -- Magneto
    [C_ID .. 54] = "Treasure Map", -- Treasure Map
    [C_ID .. 55] = "Mom's Eye", -- Mom's Eye
    [C_ID .. 56] = "Lemon Mishap", -- Lemon Mishap
    [C_ID .. 57] = "Distant Admiration", -- Distant Admiration
    [C_ID .. 58] = "Book of Shadows", -- Book of Shadows
    [C_ID .. 59] = "The Book of Belial", -- The Book of Belial
    [C_ID .. 60] = "The Ladder", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Charm of the Vampire", -- Charm of the Vampire
    [C_ID .. 63] = "The Battery", -- The Battery
    [C_ID .. 64] = "Steam Sale", -- Steam Sale
    [C_ID .. 65] = "Anarchist Cookbook", -- Anarchist Cookbook
    [C_ID .. 66] = "The Hourglass", -- The Hourglass
    [C_ID .. 67] = "Sister Maggy", -- Sister Maggy
    [C_ID .. 68] = "Technology", -- Technology
    [C_ID .. 69] = "Chocolate Milk", -- Chocolate Milk
    [C_ID .. 70] = "Growth Hormones", -- Growth Hormones
    [C_ID .. 71] = "Mini Mush", -- Mini Mush
    [C_ID .. 72] = "Rosary", -- Rosary
    [C_ID .. 73] = "Cube of Meat", -- Cube of Meat
    [C_ID .. 74] = "A Quarter", -- A Quarter
    [C_ID .. 75] = "PHD", -- PHD
    [C_ID .. 76] = "X-Ray Vision", -- X-Ray Vision
    [C_ID .. 77] = "My Little Unicorn", -- My Little Unicorn
    [C_ID .. 78] = "Book of Revelations", -- Book of Revelations
    [C_ID .. 79] = "The Mark", -- The Mark
    [C_ID .. 80] = "The Pact", -- The Pact
    [C_ID .. 81] = "Dead Cat", -- Dead Cat
    [C_ID .. 82] = "Lord of the Pit", -- Lord of the Pit
    [C_ID .. 83] = "The Nail", -- The Nail
    [C_ID .. 84] = "We Need To Go Deeper!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Deck of Cards", -- Deck of Cards
    [C_ID .. 86] = "Monstro's Tooth", -- Monstro's Tooth
    [C_ID .. 87] = "Loki's Horns", -- Loki's Horns
    [C_ID .. 88] = "Little Chubby", -- Little Chubby
    [C_ID .. 89] = "Spider Bite", -- Spider Bite
    [C_ID .. 90] = "The Small Rock", -- The Small Rock
    [C_ID .. 91] = "Spelunker Hat", -- Spelunker Hat
    [C_ID .. 92] = "Super Bandage", -- Super Bandage
    [C_ID .. 93] = "The Gamekid", -- The Gamekid
    [C_ID .. 94] = "Sack of Pennies", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Baby", -- Robo-Baby
    [C_ID .. 96] = "Little C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "The Book of Sin", -- The Book of Sin
    [C_ID .. 98] = "The Relic", -- The Relic
    [C_ID .. 99] = "Little Gish", -- Little Gish
    [C_ID .. 100] = "Little Steven", -- Little Steven
    [C_ID .. 101] = "The Halo", -- The Halo
    [C_ID .. 102] = "Mom's Bottle of Pills", -- Mom's Bottle of Pills
    [C_ID .. 103] = "The Common Cold", -- The Common Cold
    [C_ID .. 104] = "The Parasite", -- The Parasite
    [C_ID .. 105] = "The D6", -- The D6
    [C_ID .. 106] = "Mr. Mega", -- Mr. Mega
    [C_ID .. 107] = "The Pinking Shears", -- The Pinking Shears
    [C_ID .. 108] = "The Wafer", -- The Wafer
    [C_ID .. 109] = "Money = Power", -- Money = Power
    [C_ID .. 110] = "Mom's Contacts", -- Mom's Contacts
    [C_ID .. 111] = "The Bean", -- The Bean
    [C_ID .. 112] = "Guardian Angel", -- Guardian Angel
    [C_ID .. 113] = "Demon Baby", -- Demon Baby
    [C_ID .. 114] = "Mom's Knife", -- Mom's Knife
    [C_ID .. 115] = "Ouija Board", -- Ouija Board
    [C_ID .. 116] = "9 Volt", -- 9 Volt
    [C_ID .. 117] = "Dead Bird", -- Dead Bird
    [C_ID .. 118] = "Brimstone", -- Brimstone
    [C_ID .. 119] = "Blood Bag", -- Blood Bag
    [C_ID .. 120] = "Odd Mushroom (Thin)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Odd Mushroom (Large)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Whore of Babylon", -- Whore of Babylon
    [C_ID .. 123] = "Monster Manual", -- Monster Manual
    [C_ID .. 124] = "Dead Sea Scrolls", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bomb", -- Bobby-Bomb
    [C_ID .. 126] = "Razor Blade", -- Razor Blade
    [C_ID .. 127] = "Forget Me Now", -- Forget Me Now
    [C_ID .. 128] = "Forever Alone", -- Forever Alone
    [C_ID .. 129] = "Bucket of Lard", -- Bucket of Lard
    [C_ID .. 130] = "A Pony", -- A Pony
    [C_ID .. 131] = "Bomb Bag", -- Bomb Bag
    [C_ID .. 132] = "A Lump of Coal", -- A Lump of Coal
    [C_ID .. 133] = "Guppy's Paw", -- Guppy's Paw
    [C_ID .. 134] = "Guppy's Tail", -- Guppy's Tail
    [C_ID .. 135] = "IV Bag", -- IV Bag
    [C_ID .. 136] = "Best Friend", -- Best Friend
    [C_ID .. 137] = "Remote Detonator", -- Remote Detonator
    [C_ID .. 138] = "Stigmata", -- Stigmata
    [C_ID .. 139] = "Mom's Purse", -- Mom's Purse
    [C_ID .. 140] = "Bob's Curse", -- Bob's Curse
    [C_ID .. 141] = "Pageant Boy", -- Pageant Boy
    [C_ID .. 142] = "Scapular", -- Scapular
    [C_ID .. 143] = "Speed Ball", -- Speed Ball
    [C_ID .. 144] = "Bum Friend", -- Bum Friend
    [C_ID .. 145] = "Guppy's Head", -- Guppy's Head
    [C_ID .. 146] = "Prayer Card", -- Prayer Card
    [C_ID .. 147] = "Notched Axe", -- Notched Axe
    [C_ID .. 148] = "Infestation", -- Infestation
    [C_ID .. 149] = "Ipecac", -- Ipecac
    [C_ID .. 150] = "Tough Love", -- Tough Love
    [C_ID .. 151] = "The Mulligan", -- The Mulligan
    [C_ID .. 152] = "Technology 2", -- Technology 2
    [C_ID .. 153] = "Mutant Spider", -- Mutant Spider
    [C_ID .. 154] = "Chemical Peel", -- Chemical Peel
    [C_ID .. 155] = "The Peeper", -- The Peeper
    [C_ID .. 156] = "Habit", -- Habit
    [C_ID .. 157] = "Bloody Lust", -- Bloody Lust
    [C_ID .. 158] = "Crystal Ball", -- Crystal Ball
    [C_ID .. 159] = "Spirit of the Night", -- Spirit of the Night
    [C_ID .. 160] = "Crack the Sky", -- Crack the Sky
    [C_ID .. 161] = "Ankh", -- Ankh
    [C_ID .. 162] = "Celtic Cross", -- Celtic Cross
    [C_ID .. 163] = "Ghost Baby", -- Ghost Baby
    [C_ID .. 164] = "The Candle", -- The Candle
    [C_ID .. 165] = "Cat-o-nine-tails", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Harlequin Baby", -- Harlequin Baby
    [C_ID .. 168] = "Epic Fetus", -- Epic Fetus
    [C_ID .. 169] = "Polyphemus", -- Polyphemus
    [C_ID .. 170] = "Daddy Longlegs", -- Daddy Longlegs
    [C_ID .. 171] = "Spider Butt", -- Spider Butt
    [C_ID .. 172] = "Sacrificial Dagger", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitre", -- Mitre
    [C_ID .. 174] = "Rainbow Baby", -- Rainbow Baby
    [C_ID .. 175] = "Dad's Key", -- Dad's Key
    [C_ID .. 176] = "Stem Cells", -- Stem Cells
    [C_ID .. 177] = "Portable Slot", -- Portable Slot
    [C_ID .. 178] = "Holy Water", -- Holy Water
    [C_ID .. 179] = "Fate", -- Fate
    [C_ID .. 180] = "The Black Bean", -- The Black Bean
    [C_ID .. 181] = "White Pony", -- White Pony
    [C_ID .. 182] = "Sacred Heart", -- Sacred Heart
    [C_ID .. 183] = "Tooth Picks", -- Tooth Picks
    [C_ID .. 184] = "Holy Grail", -- Holy Grail
    [C_ID .. 185] = "Dead Dove", -- Dead Dove
    [C_ID .. 186] = "Blood Rights", -- Blood Rights
    [C_ID .. 187] = "Guppy's Hairball", -- Guppy's Hairball
    [C_ID .. 188] = "Abel", -- Abel
    [C_ID .. 189] = "SMB Super Fan", -- SMB Super Fan
    [C_ID .. 190] = "Pyro", -- Pyro
    [C_ID .. 191] = "3 Dollar Bill", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepathy for Dummies", -- Telepathy for Dummies
    [C_ID .. 193] = "MEAT!", -- MEAT!
    [C_ID .. 194] = "Magic 8 Ball", -- Magic 8 Ball
    [C_ID .. 195] = "Mom's Coin Purse", -- Mom's Coin Purse
    [C_ID .. 196] = "Squeezy", -- Squeezy
    [C_ID .. 197] = "Jesus Juice", -- Jesus Juice
    [C_ID .. 198] = "Box", -- Box
    [C_ID .. 199] = "Mom's Key", -- Mom's Key
    [C_ID .. 200] = "Mom's Eyeshadow", -- Mom's Eyeshadow
    [C_ID .. 201] = "Iron Bar", -- Iron Bar
    [C_ID .. 202] = "Midas' Touch", -- Midas' Touch
    [C_ID .. 203] = "Humbleing Bundle", -- Humbleing Bundle
    [C_ID .. 204] = "Fanny Pack", -- Fanny Pack
    [C_ID .. 205] = "Sharp Plug", -- Sharp Plug
    [C_ID .. 206] = "Guillotine", -- Guillotine
    [C_ID .. 207] = "Ball of Bandages", -- Ball of Bandages
    [C_ID .. 208] = "Champion Belt", -- Champion Belt
    [C_ID .. 209] = "Butt Bombs", -- Butt Bombs
    [C_ID .. 210] = "Gnawed Leaf", -- Gnawed Leaf
    [C_ID .. 211] = "Spiderbaby", -- Spiderbaby
    [C_ID .. 212] = "Guppy's Collar", -- Guppy's Collar
    [C_ID .. 213] = "Lost Contact", -- Lost Contact
    [C_ID .. 214] = "Anemic", -- Anemic
    [C_ID .. 215] = "Goat Head", -- Goat Head
    [C_ID .. 216] = "Ceremonial Robes", -- Ceremonial Robes
    [C_ID .. 217] = "Mom's Wig", -- Mom's Wig
    [C_ID .. 218] = "Placenta", -- Placenta
    [C_ID .. 219] = "Old Bandage", -- Old Bandage
    [C_ID .. 220] = "Sad Bombs", -- Sad Bombs
    [C_ID .. 221] = "Rubber Cement", -- Rubber Cement
    [C_ID .. 222] = "Anti-Gravity", -- Anti-Gravity
    [C_ID .. 223] = "Pyromaniac", -- Pyromaniac
    [C_ID .. 224] = "Cricket's Body", -- Cricket's Body
    [C_ID .. 225] = "Gimpy", -- Gimpy
    [C_ID .. 226] = "Black Lotus", -- Black Lotus
    [C_ID .. 227] = "Piggy Bank", -- Piggy Bank
    [C_ID .. 228] = "Mom's Perfume", -- Mom's Perfume
    [C_ID .. 229] = "Monstro's Lung", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Ball of Tar", -- Ball of Tar
    [C_ID .. 232] = "Stop Watch", -- Stop Watch
    [C_ID .. 233] = "Tiny Planet", -- Tiny Planet
    [C_ID .. 234] = "Infestation 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "Death's Touch", -- Death's Touch
    [C_ID .. 238] = "Key Piece 1", -- Key Piece 1
    [C_ID .. 239] = "Key Piece 2", -- Key Piece 2
    [C_ID .. 240] = "Experimental Treatment", -- Experimental Treatment
    [C_ID .. 241] = "Contract from Below", -- Contract from Below
    [C_ID .. 242] = "Infamy", -- Infamy
    [C_ID .. 243] = "Trinity Shield", -- Trinity Shield
    [C_ID .. 244] = "Tech.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Blue Map", -- Blue Map
    [C_ID .. 247] = "BFFS!", -- BFFS!
    [C_ID .. 248] = "Hive Mind", -- Hive Mind
    [C_ID .. 249] = "There's Options", -- There's Options
    [C_ID .. 250] = "Bogo Bombs", -- Bogo Bombs
    [C_ID .. 251] = "Starter Deck", -- Starter Deck
    [C_ID .. 252] = "Little Baggy", -- Little Baggy
    [C_ID .. 253] = "Magic Scab", -- Magic Scab
    [C_ID .. 254] = "Blood Clot", -- Blood Clot
    [C_ID .. 255] = "Screw", -- Screw
    [C_ID .. 256] = "Hot Bombs", -- Hot Bombs
    [C_ID .. 257] = "Fire Mind", -- Fire Mind
    [C_ID .. 258] = "Missing No.", -- Missing No.
    [C_ID .. 259] = "Dark Matter", -- Dark Matter
    [C_ID .. 260] = "Black Candle", -- Black Candle
    [C_ID .. 261] = "Proptosis", -- Proptosis
    [C_ID .. 262] = "Missing Page 2", -- Missing Page 2
    [C_ID .. 263] = "Clear Rune", -- Clear Rune
    [C_ID .. 264] = "Smart Fly", -- Smart Fly
    [C_ID .. 265] = "Dry Baby", -- Dry Baby
    [C_ID .. 266] = "Juicy Sack", -- Juicy Sack
    [C_ID .. 267] = "Robo-Baby 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Rotten Baby", -- Rotten Baby
    [C_ID .. 269] = "Headless Baby", -- Headless Baby
    [C_ID .. 270] = "Leech", -- Leech
    [C_ID .. 271] = "Mystery Sack", -- Mystery Sack
    [C_ID .. 272] = "BBF", -- BBF
    [C_ID .. 273] = "Bob's Brain", -- Bob's Brain
    [C_ID .. 274] = "Best Bud", -- Best Bud
    [C_ID .. 275] = "Lil Brimstone", -- Lil Brimstone
    [C_ID .. 276] = "Isaac's Heart", -- Isaac's Heart
    [C_ID .. 277] = "Lil Haunt", -- Lil Haunt
    [C_ID .. 278] = "Dark Bum", -- Dark Bum
    [C_ID .. 279] = "Big Fan", -- Big Fan
    [C_ID .. 280] = "Sissy Longlegs", -- Sissy Longlegs
    [C_ID .. 281] = "Punching Bag", -- Punching Bag
    [C_ID .. 282] = "How to Jump", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Blank Card", -- Blank Card
    [C_ID .. 287] = "Book of Secrets", -- Book of Secrets
    [C_ID .. 288] = "Box of Spiders", -- Box of Spiders
    [C_ID .. 289] = "Red Candle", -- Red Candle
    [C_ID .. 290] = "The Jar", -- The Jar
    [C_ID .. 291] = "Flush!", -- Flush!
    [C_ID .. 292] = "Satanic Bible", -- Satanic Bible
    [C_ID .. 293] = "Head of Krampus", -- Head of Krampus
    [C_ID .. 294] = "Butter Bean", -- Butter Bean
    [C_ID .. 295] = "Magic Fingers", -- Magic Fingers
    [C_ID .. 296] = "Converter", -- Converter
    [C_ID .. 297] = "Pandora's Box", -- Pandora's Box
    [C_ID .. 298] = "Unicorn Stump", -- Unicorn Stump
    [C_ID .. 299] = "Taurus", -- Taurus
    [C_ID .. 300] = "Aries", -- Aries
    [C_ID .. 301] = "Cancer", -- Cancer
    [C_ID .. 302] = "Leo", -- Leo
    [C_ID .. 303] = "Virgo", -- Virgo
    [C_ID .. 304] = "Libra", -- Libra
    [C_ID .. 305] = "Scorpio", -- Scorpio
    [C_ID .. 306] = "Sagittarius", -- Sagittarius
    [C_ID .. 307] = "Capricorn", -- Capricorn
    [C_ID .. 308] = "Aquarius", -- Aquarius
    [C_ID .. 309] = "Pisces", -- Pisces
    [C_ID .. 310] = "Eve's Mascara", -- Eve's Mascara
    [C_ID .. 311] = "Judas' Shadow", -- Judas' Shadow
    [C_ID .. 312] = "Maggy's Bow", -- Maggy's Bow
    [C_ID .. 313] = "Holy Mantle", -- Holy Mantle
    [C_ID .. 314] = "Thunder Thighs", -- Thunder Thighs
    [C_ID .. 315] = "Strange Attractor", -- Strange Attractor
    [C_ID .. 316] = "Cursed Eye", -- Cursed Eye
    [C_ID .. 317] = "Mysterious Liquid", -- Mysterious Liquid
    [C_ID .. 318] = "Gemini", -- Gemini
    [C_ID .. 319] = "Cain's Other Eye", -- Cain's Other Eye
    [C_ID .. 320] = "???'s Only Friend", -- ???'s Only Friend
    [C_ID .. 321] = "Samson's Chains", -- Samson's Chains
    [C_ID .. 322] = "Mongo Baby", -- Mongo Baby
    [C_ID .. 323] = "Isaac's Tears", -- Isaac's Tears
    [C_ID .. 324] = "Undefined", -- Undefined
    [C_ID .. 325] = "Scissors", -- Scissors
    [C_ID .. 326] = "Breath of Life", -- Breath of Life
    [C_ID .. 327] = "The Polaroid", -- The Polaroid
    [C_ID .. 328] = "The Negative", -- The Negative
    [C_ID .. 329] = "The Ludovico Technique", -- The Ludovico Technique
    [C_ID .. 330] = "Soy Milk", -- Soy Milk
    [C_ID .. 331] = "Godhead", -- Godhead
    [C_ID .. 332] = "Lazarus' Rags", -- Lazarus' Rags
    [C_ID .. 333] = "The Mind", -- The Mind
    [C_ID .. 334] = "The Body", -- The Body
    [C_ID .. 335] = "The Soul", -- The Soul
    [C_ID .. 336] = "Dead Onion", -- Dead Onion
    [C_ID .. 337] = "Broken Watch", -- Broken Watch
    [C_ID .. 338] = "The Boomerang", -- The Boomerang
    [C_ID .. 339] = "Safety Pin", -- Safety Pin
    [C_ID .. 340] = "Caffeine Pill", -- Caffeine Pill
    [C_ID .. 341] = "Torn Photo", -- Torn Photo
    [C_ID .. 342] = "Blue Cap", -- Blue Cap
    [C_ID .. 343] = "Latch Key", -- Latch Key
    [C_ID .. 344] = "Match Book", -- Match Book
    [C_ID .. 345] = "Synthoil", -- Synthoil
    [C_ID .. 346] = "A Snack", -- A Snack
    [C_ID .. 347] = "Diplopia", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Wooden Nickel", -- Wooden Nickel
    [C_ID .. 350] = "Toxic Shock", -- Toxic Shock
    [C_ID .. 351] = "Mega Bean", -- Mega Bean
    [C_ID .. 352] = "Glass Cannon", -- Glass Cannon
    [C_ID .. 353] = "Bomber Boy", -- Bomber Boy
    [C_ID .. 354] = "Crack Jacks", -- Crack Jacks
    [C_ID .. 355] = "Mom's Pearls", -- Mom's Pearls
    [C_ID .. 356] = "Car Battery", -- Car Battery
    [C_ID .. 357] = "Box of Friends", -- Box of Friends
    [C_ID .. 358] = "The Wiz", -- The Wiz
    [C_ID .. 359] = "8 Inch Nails", -- 8 Inch Nails
    [C_ID .. 360] = "Incubus", -- Incubus
    [C_ID .. 361] = "Fate's Reward", -- Fate's Reward
    [C_ID .. 362] = "Lil Chest", -- Lil Chest
    [C_ID .. 363] = "Sworn Protector", -- Sworn Protector
    [C_ID .. 364] = "Friend Zone", -- Friend Zone
    [C_ID .. 365] = "Lost Fly", -- Lost Fly
    [C_ID .. 366] = "Scatter Bombs", -- Scatter Bombs
    [C_ID .. 367] = "Sticky Bombs", -- Sticky Bombs
    [C_ID .. 368] = "Epiphora", -- Epiphora
    [C_ID .. 369] = "Continuum", -- Continuum
    [C_ID .. 370] = "Mr. Dolly", -- Mr. Dolly
    [C_ID .. 371] = "Curse of the Tower", -- Curse of the Tower
    [C_ID .. 372] = "Charged Baby", -- Charged Baby
    [C_ID .. 373] = "Dead Eye", -- Dead Eye
    [C_ID .. 374] = "Holy Light", -- Holy Light
    [C_ID .. 375] = "Host Hat", -- Host Hat
    [C_ID .. 376] = "Restock", -- Restock
    [C_ID .. 377] = "Bursting Sack", -- Bursting Sack
    [C_ID .. 378] = "No. 2", -- No. 2
    [C_ID .. 379] = "Pupula Duplex", -- Pupula Duplex
    [C_ID .. 380] = "Pay To Play", -- Pay To Play
    [C_ID .. 381] = "Eden's Blessing", -- Eden's Blessing
    [C_ID .. 382] = "Friendly Ball", -- Friendly Ball
    [C_ID .. 383] = "Tear Detonator", -- Tear Detonator
    [C_ID .. 384] = "Lil Gurdy", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Censer", -- Censer
    [C_ID .. 388] = "Key Bum", -- Key Bum
    [C_ID .. 389] = "Rune Bag", -- Rune Bag
    [C_ID .. 390] = "Seraphim", -- Seraphim
    [C_ID .. 391] = "Betrayal", -- Betrayal
    [C_ID .. 392] = "Zodiac", -- Zodiac
    [C_ID .. 393] = "Serpent's Kiss", -- Serpent's Kiss
    [C_ID .. 394] = "Marked", -- Marked
    [C_ID .. 395] = "Tech X", -- Tech X
    [C_ID .. 396] = "Ventricle Razor", -- Ventricle Razor
    [C_ID .. 397] = "Tractor Beam", -- Tractor Beam
    [C_ID .. 398] = "God's Flesh", -- God's Flesh
    [C_ID .. 399] = "Maw of the Void", -- Maw of the Void
    [C_ID .. 400] = "Spear of Destiny", -- Spear of Destiny
    [C_ID .. 401] = "Explosivo", -- Explosivo
    [C_ID .. 402] = "Chaos", -- Chaos
    [C_ID .. 403] = "Spider Mod", -- Spider Mod
    [C_ID .. 404] = "Farting Baby", -- Farting Baby
    [C_ID .. 405] = "GB Bug", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Purity", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Empty Vessel", -- Empty Vessel
    [C_ID .. 410] = "Evil Eye", -- Evil Eye
    [C_ID .. 411] = "Lusty Blood", -- Lusty Blood
    [C_ID .. 412] = "Cambion Conception", -- Cambion Conception
    [C_ID .. 413] = "Immaculate Conception", -- Immaculate Conception
    [C_ID .. 414] = "More Options", -- More Options
    [C_ID .. 415] = "Crown Of Light", -- Crown Of Light
    [C_ID .. 416] = "Deep Pockets", -- Deep Pockets
    [C_ID .. 417] = "Succubus", -- Succubus
    [C_ID .. 418] = "Fruit Cake", -- Fruit Cake
    [C_ID .. 419] = "Teleport 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Black Powder", -- Black Powder
    [C_ID .. 421] = "Kidney Bean", -- Kidney Bean
    [C_ID .. 422] = "Glowing Hourglass", -- Glowing Hourglass
    [C_ID .. 423] = "Circle of Protection", -- Circle of Protection
    [C_ID .. 424] = "Sack Head", -- Sack Head
    [C_ID .. 425] = "Night Light", -- Night Light
    [C_ID .. 426] = "Obsessed Fan", -- Obsessed Fan
    [C_ID .. 427] = "Mine Crafter", -- Mine Crafter
    [C_ID .. 428] = "PJs", -- PJs
    [C_ID .. 429] = "Head of the Keeper", -- Head of the Keeper
    [C_ID .. 430] = "Papa Fly", -- Papa Fly
    [C_ID .. 431] = "Multidimensional Baby", -- Multidimensional Baby
    [C_ID .. 432] = "Glitter Bombs", -- Glitter Bombs
    [C_ID .. 433] = "My Shadow", -- My Shadow
    [C_ID .. 434] = "Jar of Flies", -- Jar of Flies
    [C_ID .. 435] = "Lil Loki", -- Lil Loki
    [C_ID .. 436] = "Milk!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Binky", -- Binky
    [C_ID .. 439] = "Mom's Box", -- Mom's Box
    [C_ID .. 440] = "Kidney Stone", -- Kidney Stone
    [C_ID .. 441] = "Mega Blast", -- Mega Blast
    [C_ID .. 442] = "Dark Prince's Crown", -- Dark Prince's Crown
    [C_ID .. 443] = "Apple!", -- Apple!
    [C_ID .. 444] = "Lead Pencil", -- Lead Pencil
    [C_ID .. 445] = "Dog Tooth", -- Dog Tooth
    [C_ID .. 446] = "Dead Tooth", -- Dead Tooth
    [C_ID .. 447] = "Linger Bean", -- Linger Bean
    [C_ID .. 448] = "Shard of Glass", -- Shard of Glass
    [C_ID .. 449] = "Metal Plate", -- Metal Plate
    [C_ID .. 450] = "Eye of Greed", -- Eye of Greed
    [C_ID .. 451] = "Tarot Cloth", -- Tarot Cloth
    [C_ID .. 452] = "Varicose Veins", -- Varicose Veins
    [C_ID .. 453] = "Compound Fracture", -- Compound Fracture
    [C_ID .. 454] = "Polydactyly", -- Polydactyly
    [C_ID .. 455] = "Dad's Lost Coin", -- Dad's Lost Coin
    [C_ID .. 456] = "Midnight Snack", -- Midnight Snack
    [C_ID .. 457] = "Cone Head", -- Cone Head
    [C_ID .. 458] = "Belly Button", -- Belly Button
    [C_ID .. 459] = "Sinus Infection", -- Sinus Infection
    [C_ID .. 460] = "Glaucoma", -- Glaucoma
    [C_ID .. 461] = "Parasitoid", -- Parasitoid
    [C_ID .. 462] = "Eye of Belial", -- Eye of Belial
    [C_ID .. 463] = "Sulfuric Acid", -- Sulfuric Acid
    [C_ID .. 464] = "Glyph of Balance", -- Glyph of Balance
    [C_ID .. 465] = "Analog Stick", -- Analog Stick
    [C_ID .. 466] = "Contagion", -- Contagion
    [C_ID .. 467] = "Finger!", -- Finger!
    [C_ID .. 468] = "Shade", -- Shade
    [C_ID .. 469] = "Depression", -- Depression
    [C_ID .. 470] = "Hushy", -- Hushy
    [C_ID .. 471] = "Lil Monstro", -- Lil Monstro
    [C_ID .. 472] = "King Baby", -- King Baby
    [C_ID .. 473] = "Big Chubby", -- Big Chubby
    [C_ID .. 474] = "Broken Glass Cannon", -- Broken Glass Cannon
    [C_ID .. 475] = "Plan C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Void", -- Void
    [C_ID .. 478] = "Pause", -- Pause
    [C_ID .. 479] = "Smelter", -- Smelter
    [C_ID .. 480] = "Compost", -- Compost
    [C_ID .. 481] = "Dataminer", -- Dataminer
    [C_ID .. 482] = "Clicker", -- Clicker
    [C_ID .. 483] = "Mama Mega!", -- Mama Mega!
    [C_ID .. 484] = "Wait What?", -- Wait What?
    [C_ID .. 485] = "Crooked Penny", -- Crooked Penny
    [C_ID .. 486] = "Dull Razor", -- Dull Razor
    [C_ID .. 487] = "Potato Peeler", -- Potato Peeler
    [C_ID .. 488] = "Metronome", -- Metronome
    [C_ID .. 489] = "D Infinity", -- D Infinity
    [C_ID .. 490] = "Eden's Soul", -- Eden's Soul
    [C_ID .. 491] = "Acid Baby", -- Acid Baby
    [C_ID .. 492] = "YO LISTEN!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenaline", -- Adrenaline
    [C_ID .. 494] = "Jacob's Ladder", -- Jacob's Ladder
    [C_ID .. 495] = "Ghost Pepper", -- Ghost Pepper
    [C_ID .. 496] = "Euthanasia", -- Euthanasia
    [C_ID .. 497] = "Camo Undies", -- Camo Undies
    [C_ID .. 498] = "Duality", -- Duality
    [C_ID .. 499] = "Eucharist", -- Eucharist
    [C_ID .. 500] = "Sack of Sacks", -- Sack of Sacks
    [C_ID .. 501] = "Greed's Gullet", -- Greed's Gullet
    [C_ID .. 502] = "Large Zit", -- Large Zit
    [C_ID .. 503] = "Little Horn", -- Little Horn
    [C_ID .. 504] = "Brown Nugget", -- Brown Nugget
    [C_ID .. 505] = "Poke Go", -- Poke Go
    [C_ID .. 506] = "Backstabber", -- Backstabber
    [C_ID .. 507] = "Sharp Straw", -- Sharp Straw
    [C_ID .. 508] = "Mom's Razor", -- Mom's Razor
    [C_ID .. 509] = "Bloodshot Eye", -- Bloodshot Eye
    [C_ID .. 510] = "Delirious", -- Delirious
    [C_ID .. 511] = "Angry Fly", -- Angry Fly
    [C_ID .. 512] = "Black Hole", -- Black Hole
    [C_ID .. 513] = "Bozo", -- Bozo
    [C_ID .. 514] = "Broken Modem", -- Broken Modem
    [C_ID .. 515] = "Mystery Gift", -- Mystery Gift
    [C_ID .. 516] = "Sprinkler", -- Sprinkler
    [C_ID .. 517] = "Fast Bombs", -- Fast Bombs
    [C_ID .. 518] = "Buddy in a Box", -- Buddy in a Box
    [C_ID .. 519] = "Lil Delirium", -- Lil Delirium
    [C_ID .. 520] = "Jumper Cables", -- Jumper Cables
    [C_ID .. 521] = "Coupon", -- Coupon
    [C_ID .. 522] = "Telekinesis", -- Telekinesis
    [C_ID .. 523] = "Moving Box", -- Moving Box
    [C_ID .. 524] = "Technology Zero", -- Technology Zero
    [C_ID .. 525] = "Leprosy", -- Leprosy
    [C_ID .. 526] = "7 Seals", -- 7 Seals
    [C_ID .. 527] = "Mr. ME!", -- Mr. ME!
    [C_ID .. 528] = "Angelic Prism", -- Angelic Prism
    [C_ID .. 529] = "Pop!", -- Pop!
    [C_ID .. 530] = "Death's List", -- Death's List
    [C_ID .. 531] = "Haemolacria", -- Haemolacria
    [C_ID .. 532] = "Lachryphagy", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Schoolbag", -- Schoolbag
    [C_ID .. 535] = "Blanket", -- Blanket
    [C_ID .. 536] = "Sacrificial Altar", -- Sacrificial Altar
    [C_ID .. 537] = "Lil Spewer", -- Lil Spewer
    [C_ID .. 538] = "Marbles", -- Marbles
    [C_ID .. 539] = "Mystery Egg", -- Mystery Egg
    [C_ID .. 540] = "Flat Stone", -- Flat Stone
    [C_ID .. 541] = "Marrow", -- Marrow
    [C_ID .. 542] = "Slipped Rib", -- Slipped Rib
    [C_ID .. 543] = "Hallowed Ground", -- Hallowed Ground
    [C_ID .. 544] = "Pointy Rib", -- Pointy Rib
    [C_ID .. 545] = "Book of the Dead", -- Book of the Dead
    [C_ID .. 546] = "Dad's Ring", -- Dad's Ring
    [C_ID .. 547] = "Divorce Papers", -- Divorce Papers
    [C_ID .. 548] = "Jaw Bone", -- Jaw Bone
    [C_ID .. 549] = "Brittle Bones", -- Brittle Bones
    [C_ID .. 550] = "Broken Shovel", -- Broken Shovel
    [C_ID .. 551] = "Broken Shovel", -- Broken Shovel
    [C_ID .. 552] = "Mom's Shovel", -- Mom's Shovel
    [C_ID .. 553] = "Mucormycosis", -- Mucormycosis
    [C_ID .. 554] = "2Spooky", -- 2Spooky
    [C_ID .. 555] = "Golden Razor", -- Golden Razor
    [C_ID .. 556] = "Sulfur", -- Sulfur
    [C_ID .. 557] = "Fortune Cookie", -- Fortune Cookie
    [C_ID .. 558] = "Eye Sore", -- Eye Sore
    [C_ID .. 559] = "120 Volt", -- 120 Volt
    [C_ID .. 560] = "It Hurts", -- It Hurts
    [C_ID .. 561] = "Almond Milk", -- Almond Milk
    [C_ID .. 562] = "Rock Bottom", -- Rock Bottom
    [C_ID .. 563] = "Nancy Bombs", -- Nancy Bombs
    [C_ID .. 564] = "A Bar of Soap", -- A Bar of Soap
    [C_ID .. 565] = "Blood Puppy", -- Blood Puppy
    [C_ID .. 566] = "Dream Catcher", -- Dream Catcher
    [C_ID .. 567] = "Paschal Candle", -- Paschal Candle
    [C_ID .. 568] = "Divine Intervention", -- Divine Intervention
    [C_ID .. 569] = "Blood Oath", -- Blood Oath
    [C_ID .. 570] = "Playdough Cookie", -- Playdough Cookie
    [C_ID .. 571] = "Orphan Socks", -- Orphan Socks
    [C_ID .. 572] = "Eye of the Occult", -- Eye of the Occult
    [C_ID .. 573] = "Immaculate Heart", -- Immaculate Heart
    [C_ID .. 574] = "Monstrance", -- Monstrance
    [C_ID .. 575] = "The Intruder", -- The Intruder
    [C_ID .. 576] = "Dirty Mind", -- Dirty Mind
    [C_ID .. 577] = "Damocles", -- Damocles
    [C_ID .. 578] = "Free Lemonade", -- Free Lemonade
    [C_ID .. 579] = "Spirit Sword", -- Spirit Sword
    [C_ID .. 580] = "Red Key", -- Red Key
    [C_ID .. 581] = "Psy Fly", -- Psy Fly
    [C_ID .. 582] = "Wavy Cap", -- Wavy Cap
    [C_ID .. 583] = "Rocket in a Jar", -- Rocket in a Jar
    [C_ID .. 584] = "Book of Virtues", -- Book of Virtues
    [C_ID .. 585] = "Alabaster Box", -- Alabaster Box
    [C_ID .. 586] = "The Stairway", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Luna", -- Luna
    [C_ID .. 590] = "Mercurius", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Terra", -- Terra
    [C_ID .. 593] = "Mars", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturnus", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptunus", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Voodoo Head", -- Voodoo Head
    [C_ID .. 600] = "Eye Drops", -- Eye Drops
    [C_ID .. 601] = "Act of Contrition", -- Act of Contrition
    [C_ID .. 602] = "Member Card", -- Member Card
    [C_ID .. 603] = "Battery Pack", -- Battery Pack
    [C_ID .. 604] = "Mom's Bracelet", -- Mom's Bracelet
    [C_ID .. 605] = "The Scooper", -- The Scooper
    [C_ID .. 606] = "Ocular Rift", -- Ocular Rift
    [C_ID .. 607] = "Boiled Baby", -- Boiled Baby
    [C_ID .. 608] = "Freezer Baby", -- Freezer Baby
    [C_ID .. 609] = "Eternal D6", -- Eternal D6
    [C_ID .. 610] = "Bird Cage", -- Bird Cage
    [C_ID .. 611] = "Larynx", -- Larynx
    [C_ID .. 612] = "Lost Soul", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Blood Bombs", -- Blood Bombs
    [C_ID .. 615] = "Lil Dumpy", -- Lil Dumpy
    [C_ID .. 616] = "Bird's Eye", -- Bird's Eye
    [C_ID .. 617] = "Lodestone", -- Lodestone
    [C_ID .. 618] = "Rotten Tomato", -- Rotten Tomato
    [C_ID .. 619] = "Birthright", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Red Stew", -- Red Stew
    [C_ID .. 622] = "Genesis", -- Genesis
    [C_ID .. 623] = "Sharp Key", -- Sharp Key
    [C_ID .. 624] = "Booster Pack", -- Booster Pack
    [C_ID .. 625] = "Mega Mush", -- Mega Mush
    [C_ID .. 626] = "Knife Piece 1", -- Knife Piece 1
    [C_ID .. 627] = "Knife Piece 2", -- Knife Piece 2
    [C_ID .. 628] = "Death Certificate", -- Death Certificate
    [C_ID .. 629] = "Bot Fly", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Meat Cleaver", -- Meat Cleaver
    [C_ID .. 632] = "Evil Charm", -- Evil Charm
    [C_ID .. 633] = "Dogma", -- Dogma
    [C_ID .. 634] = "Purgatory", -- Purgatory
    [C_ID .. 635] = "Stitches", -- Stitches
    [C_ID .. 636] = "R Key", -- R Key
    [C_ID .. 637] = "Knockout Drops", -- Knockout Drops
    [C_ID .. 638] = "Eraser", -- Eraser
    [C_ID .. 639] = "Yuck Heart", -- Yuck Heart
    [C_ID .. 640] = "Urn of Souls", -- Urn of Souls
    [C_ID .. 641] = "Akeldama", -- Akeldama
    [C_ID .. 642] = "Magic Skin", -- Magic Skin
    [C_ID .. 643] = "Revelation", -- Revelation
    [C_ID .. 644] = "Consolation Prize", -- Consolation Prize
    [C_ID .. 645] = "Tinytoma", -- Tinytoma
    [C_ID .. 646] = "Brimstone Bombs", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volt", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Fruity Plum", -- Fruity Plum
    [C_ID .. 650] = "Plum Flute", -- Plum Flute
    [C_ID .. 651] = "Star of Bethlehem", -- Star of Bethlehem
    [C_ID .. 652] = "Cube Baby", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "False PHD", -- False PHD
    [C_ID .. 655] = "Spin to Win", -- Spin to Win
    [C_ID .. 656] = "Damocles", -- Damocles
    [C_ID .. 657] = "Vasculitis", -- Vasculitis
    [C_ID .. 658] = "Giant Cell", -- Giant Cell
    [C_ID .. 659] = "Tropicamide", -- Tropicamide
    [C_ID .. 660] = "Card Reading", -- Card Reading
    [C_ID .. 661] = "Quints", -- Quints
    [C_ID .. 662] = "", -- 
    [C_ID .. 663] = "Tooth and Nail", -- Tooth and Nail
    [C_ID .. 664] = "Binge Eater", -- Binge Eater
    [C_ID .. 665] = "Guppy's Eye", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Strawman", -- Strawman
    [C_ID .. 668] = "Dad's Note", -- Dad's Note
    [C_ID .. 669] = "Sausage", -- Sausage
    [C_ID .. 670] = "Options?", -- Options?
    [C_ID .. 671] = "Candy Heart", -- Candy Heart
    [C_ID .. 672] = "A Pound of Flesh", -- A Pound of Flesh
    [C_ID .. 673] = "Redemption", -- Redemption
    [C_ID .. 674] = "Spirit Shackles", -- Spirit Shackles
    [C_ID .. 675] = "Cracked Orb", -- Cracked Orb
    [C_ID .. 676] = "Empty Heart", -- Empty Heart
    [C_ID .. 677] = "Astral Projection", -- Astral Projection
    [C_ID .. 678] = "C Section", -- C Section
    [C_ID .. 679] = "Lil Abaddon", -- Lil Abaddon
    [C_ID .. 680] = "Montezuma's Revenge", -- Montezuma's Revenge
    [C_ID .. 681] = "Lil Portal", -- Lil Portal
    [C_ID .. 682] = "Worm Friend", -- Worm Friend
    [C_ID .. 683] = "Bone Spurs", -- Bone Spurs
    [C_ID .. 684] = "Hungry Soul", -- Hungry Soul
    [C_ID .. 685] = "Jar of Wisps", -- Jar of Wisps
    [C_ID .. 686] = "Soul Locket", -- Soul Locket
    [C_ID .. 687] = "Friend Finder", -- Friend Finder
    [C_ID .. 688] = "Inner Child", -- Inner Child
    [C_ID .. 689] = "Glitched Crown", -- Glitched Crown
    [C_ID .. 690] = "Belly Jelly", -- Belly Jelly
    [C_ID .. 691] = "Sacred Orb", -- Sacred Orb
    [C_ID .. 692] = "Sanguine Bond", -- Sanguine Bond
    [C_ID .. 693] = "The Swarm", -- The Swarm
    [C_ID .. 694] = "Heartbreak", -- Heartbreak
    [C_ID .. 695] = "Bloody Gust", -- Bloody Gust
    [C_ID .. 696] = "Salvation", -- Salvation
    [C_ID .. 697] = "Vanishing Twin", -- Vanishing Twin
    [C_ID .. 698] = "Twisted Pair", -- Twisted Pair
    [C_ID .. 699] = "Azazel's Rage", -- Azazel's Rage
    [C_ID .. 700] = "Echo Chamber", -- Echo Chamber
    [C_ID .. 701] = "Isaac's Tomb", -- Isaac's Tomb
    [C_ID .. 702] = "Vengeful Spirit", -- Vengeful Spirit
    [C_ID .. 703] = "Esau Jr.", -- Esau Jr.
    [C_ID .. 704] = "Berserk!", -- Berserk!
    [C_ID .. 705] = "Dark Arts", -- Dark Arts
    [C_ID .. 706] = "Abyss", -- Abyss
    [C_ID .. 707] = "Supper", -- Supper
    [C_ID .. 708] = "Stapler", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Bag of Crafting", -- Bag of Crafting
    [C_ID .. 711] = "Flip", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Recall", -- Recall
    [C_ID .. 715] = "Hold", -- Hold
    [C_ID .. 716] = "Keeper's Sack", -- Keeper's Sack
    [C_ID .. 717] = "Keeper's Kin", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "Keeper's Box", -- Keeper's Box
    [C_ID .. 720] = "Everything Jar", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Spindown Dice", -- Spindown Dice
    [C_ID .. 724] = "Hypercoagulation", -- Hypercoagulation
    [C_ID .. 725] = "IBS", -- IBS
    [C_ID .. 726] = "Hemoptysis", -- Hemoptysis
    [C_ID .. 727] = "Ghost Bombs", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Decap Attack", -- Decap Attack
    [C_ID .. 730] = "Glass Eye", -- Glass Eye
    [C_ID .. 731] = "Stye", -- Stye
    [C_ID .. 732] = "Mom's Ring", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Swallowed Penny", -- Swallowed Penny
    [T_ID .. 2] = "Petrified Poop", -- Petrified Poop
    [T_ID .. 3] = "AAA Battery", -- AAA Battery
    [T_ID .. 4] = "Broken Remote", -- Broken Remote
    [T_ID .. 5] = "Purple Heart", -- Purple Heart
    [T_ID .. 6] = "Broken Magnet", -- Broken Magnet
    [T_ID .. 7] = "Rosary Bead", -- Rosary Bead
    [T_ID .. 8] = "Cartridge", -- Cartridge
    [T_ID .. 9] = "Pulse Worm", -- Pulse Worm
    [T_ID .. 10] = "Wiggle Worm", -- Wiggle Worm
    [T_ID .. 11] = "Ring Worm", -- Ring Worm
    [T_ID .. 12] = "Flat Worm", -- Flat Worm
    [T_ID .. 13] = "Store Credit", -- Store Credit
    [T_ID .. 14] = "Callus", -- Callus
    [T_ID .. 15] = "Lucky Rock", -- Lucky Rock
    [T_ID .. 16] = "Mom's Toenail", -- Mom's Toenail
    [T_ID .. 17] = "Black Lipstick", -- Black Lipstick
    [T_ID .. 18] = "Bible Tract", -- Bible Tract
    [T_ID .. 19] = "Paper Clip", -- Paper Clip
    [T_ID .. 20] = "Monkey Paw", -- Monkey Paw
    [T_ID .. 21] = "Mysterious Paper", -- Mysterious Paper
    [T_ID .. 22] = "Daemon's Tail", -- Daemon's Tail
    [T_ID .. 23] = "Missing Poster", -- Missing Poster
    [T_ID .. 24] = "Butt Penny", -- Butt Penny
    [T_ID .. 25] = "Mysterious Candy", -- Mysterious Candy
    [T_ID .. 26] = "Hook Worm", -- Hook Worm
    [T_ID .. 27] = "Whip Worm", -- Whip Worm
    [T_ID .. 28] = "Broken Ankh", -- Broken Ankh
    [T_ID .. 29] = "Fish Head", -- Fish Head
    [T_ID .. 30] = "Pinky Eye", -- Pinky Eye
    [T_ID .. 31] = "Push Pin", -- Push Pin
    [T_ID .. 32] = "Liberty Cap", -- Liberty Cap
    [T_ID .. 33] = "Umbilical Cord", -- Umbilical Cord
    [T_ID .. 34] = "Child's Heart", -- Child's Heart
    [T_ID .. 35] = "Curved Horn", -- Curved Horn
    [T_ID .. 36] = "Rusted Key", -- Rusted Key
    [T_ID .. 37] = "Goat Hoof", -- Goat Hoof
    [T_ID .. 38] = "Mom's Pearl", -- Mom's Pearl
    [T_ID .. 39] = "Cancer", -- Cancer
    [T_ID .. 40] = "Red Patch", -- Red Patch
    [T_ID .. 41] = "Match Stick", -- Match Stick
    [T_ID .. 42] = "Lucky Toe", -- Lucky Toe
    [T_ID .. 43] = "Cursed Skull", -- Cursed Skull
    [T_ID .. 44] = "Safety Cap", -- Safety Cap
    [T_ID .. 45] = "Ace of Spades", -- Ace of Spades
    [T_ID .. 46] = "Isaac's Fork", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "A Missing Page", -- A Missing Page
    [T_ID .. 49] = "Bloody Penny", -- Bloody Penny
    [T_ID .. 50] = "Burnt Penny", -- Burnt Penny
    [T_ID .. 51] = "Flat Penny", -- Flat Penny
    [T_ID .. 52] = "Counterfeit Penny", -- Counterfeit Penny
    [T_ID .. 53] = "Tick", -- Tick
    [T_ID .. 54] = "Isaac's Head", -- Isaac's Head
    [T_ID .. 55] = "Maggy's Faith", -- Maggy's Faith
    [T_ID .. 56] = "Judas' Tongue", -- Judas' Tongue
    [T_ID .. 57] = "???'s Soul", -- ???'s Soul
    [T_ID .. 58] = "Samson's Lock", -- Samson's Lock
    [T_ID .. 59] = "Cain's Eye", -- Cain's Eye
    [T_ID .. 60] = "Eve's Bird Foot", -- Eve's Bird Foot
    [T_ID .. 61] = "The Left Hand", -- The Left Hand
    [T_ID .. 62] = "Shiny Rock", -- Shiny Rock
    [T_ID .. 63] = "Safety Scissors", -- Safety Scissors
    [T_ID .. 64] = "Rainbow Worm", -- Rainbow Worm
    [T_ID .. 65] = "Tape Worm", -- Tape Worm
    [T_ID .. 66] = "Lazy Worm", -- Lazy Worm
    [T_ID .. 67] = "Cracked Dice", -- Cracked Dice
    [T_ID .. 68] = "Super Magnet", -- Super Magnet
    [T_ID .. 69] = "Faded Polaroid", -- Faded Polaroid
    [T_ID .. 70] = "Louse", -- Louse
    [T_ID .. 71] = "Bob's Bladder", -- Bob's Bladder
    [T_ID .. 72] = "Watch Battery", -- Watch Battery
    [T_ID .. 73] = "Blasting Cap", -- Blasting Cap
    [T_ID .. 74] = "Stud Finder", -- Stud Finder
    [T_ID .. 75] = "Error", -- Error
    [T_ID .. 76] = "Poker Chip", -- Poker Chip
    [T_ID .. 77] = "Blister", -- Blister
    [T_ID .. 78] = "Second Hand", -- Second Hand
    [T_ID .. 79] = "Endless Nameless", -- Endless Nameless
    [T_ID .. 80] = "Black Feather", -- Black Feather
    [T_ID .. 81] = "Blind Rage", -- Blind Rage
    [T_ID .. 82] = "Golden Horse Shoe", -- Golden Horse Shoe
    [T_ID .. 83] = "Store Key", -- Store Key
    [T_ID .. 84] = "Rib of Greed", -- Rib of Greed
    [T_ID .. 85] = "Karma", -- Karma
    [T_ID .. 86] = "Lil Larva", -- Lil Larva
    [T_ID .. 87] = "Mom's Locket", -- Mom's Locket
    [T_ID .. 88] = "NO!", -- NO!
    [T_ID .. 89] = "Child Leash", -- Child Leash
    [T_ID .. 90] = "Brown Cap", -- Brown Cap
    [T_ID .. 91] = "Meconium", -- Meconium
    [T_ID .. 92] = "Cracked Crown", -- Cracked Crown
    [T_ID .. 93] = "Used Diaper", -- Used Diaper
    [T_ID .. 94] = "Fish Tail", -- Fish Tail
    [T_ID .. 95] = "Black Tooth", -- Black Tooth
    [T_ID .. 96] = "Ouroboros Worm", -- Ouroboros Worm
    [T_ID .. 97] = "Tonsil", -- Tonsil
    [T_ID .. 98] = "Nose Goblin", -- Nose Goblin
    [T_ID .. 99] = "Super Ball", -- Super Ball
    [T_ID .. 100] = "Vibrant Bulb", -- Vibrant Bulb
    [T_ID .. 101] = "Dim Bulb", -- Dim Bulb
    [T_ID .. 102] = "Fragmented Card", -- Fragmented Card
    [T_ID .. 103] = "Equality!", -- Equality!
    [T_ID .. 104] = "Wish Bone", -- Wish Bone
    [T_ID .. 105] = "Bag Lunch", -- Bag Lunch
    [T_ID .. 106] = "Lost Cork", -- Lost Cork
    [T_ID .. 107] = "Crow Heart", -- Crow Heart
    [T_ID .. 108] = "Walnut", -- Walnut
    [T_ID .. 109] = "Duct Tape", -- Duct Tape
    [T_ID .. 110] = "Silver Dollar", -- Silver Dollar
    [T_ID .. 111] = "Bloody Crown", -- Bloody Crown
    [T_ID .. 112] = "Pay To Win", -- Pay To Win
    [T_ID .. 113] = "Locust of War", -- Locust of War
    [T_ID .. 114] = "Locust of Pestilence", -- Locust of Pestilence
    [T_ID .. 115] = "Locust of Famine", -- Locust of Famine
    [T_ID .. 116] = "Locust of Death", -- Locust of Death
    [T_ID .. 117] = "Locust of Conquest", -- Locust of Conquest
    [T_ID .. 118] = "Bat Wing", -- Bat Wing
    [T_ID .. 119] = "Stem Cell", -- Stem Cell
    [T_ID .. 120] = "Hairpin", -- Hairpin
    [T_ID .. 121] = "Wooden Cross", -- Wooden Cross
    [T_ID .. 122] = "Butter!", -- Butter!
    [T_ID .. 123] = "Filigree Feather", -- Filigree Feather
    [T_ID .. 124] = "Door Stop", -- Door Stop
    [T_ID .. 125] = "Extension Cord", -- Extension Cord
    [T_ID .. 126] = "Rotten Penny", -- Rotten Penny
    [T_ID .. 127] = "Baby-Bender", -- Baby-Bender
    [T_ID .. 128] = "Finger Bone", -- Finger Bone
    [T_ID .. 129] = "Jawbreaker", -- Jawbreaker
    [T_ID .. 130] = "Chewed Pen", -- Chewed Pen
    [T_ID .. 131] = "Blessed Penny", -- Blessed Penny
    [T_ID .. 132] = "Broken Syringe", -- Broken Syringe
    [T_ID .. 133] = "Short Fuse", -- Short Fuse
    [T_ID .. 134] = "Gigante Bean", -- Gigante Bean
    [T_ID .. 135] = "A Lighter", -- A Lighter
    [T_ID .. 136] = "Broken Padlock", -- Broken Padlock
    [T_ID .. 137] = "Myosotis", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Teardrop Charm", -- Teardrop Charm
    [T_ID .. 140] = "Apple of Sodom", -- Apple of Sodom
    [T_ID .. 141] = "Forgotten Lullaby", -- Forgotten Lullaby
    [T_ID .. 142] = "Beth's Faith", -- Beth's Faith
    [T_ID .. 143] = "Old Capacitor", -- Old Capacitor
    [T_ID .. 144] = "Brain Worm", -- Brain Worm
    [T_ID .. 145] = "Perfection", -- Perfection
    [T_ID .. 146] = "Devil's Crown", -- Devil's Crown
    [T_ID .. 147] = "Charged Penny", -- Charged Penny
    [T_ID .. 148] = "Friendship Necklace", -- Friendship Necklace
    [T_ID .. 149] = "Panic Button", -- Panic Button
    [T_ID .. 150] = "Blue Key", -- Blue Key
    [T_ID .. 151] = "Flat File", -- Flat File
    [T_ID .. 152] = "Telescope Lens", -- Telescope Lens
    [T_ID .. 153] = "Mom's Lock", -- Mom's Lock
    [T_ID .. 154] = "Dice Bag", -- Dice Bag
    [T_ID .. 155] = "Holy Crown", -- Holy Crown
    [T_ID .. 156] = "Mother's Kiss", -- Mother's Kiss
    [T_ID .. 157] = "Torn Card", -- Torn Card
    [T_ID .. 158] = "Torn Pocket", -- Torn Pocket
    [T_ID .. 159] = "Gilded Key", -- Gilded Key
    [T_ID .. 160] = "Lucky Sack", -- Lucky Sack
    [T_ID .. 161] = "Wicked Crown", -- Wicked Crown
    [T_ID .. 162] = "Azazel's Stump", -- Azazel's Stump
    [T_ID .. 163] = "Dingle Berry", -- Dingle Berry
    [T_ID .. 164] = "Ring Cap", -- Ring Cap
    [T_ID .. 165] = "Nuh Uh!", -- Nuh Uh!
    [T_ID .. 166] = "Modeling Clay", -- Modeling Clay
    [T_ID .. 167] = "Polished Bone", -- Polished Bone
    [T_ID .. 168] = "Hollow Heart", -- Hollow Heart
    [T_ID .. 169] = "Kid's Drawing", -- Kid's Drawing
    [T_ID .. 170] = "Crystal Key", -- Crystal Key
    [T_ID .. 171] = "Keeper's Bargain", -- Keeper's Bargain
    [T_ID .. 172] = "Cursed Penny", -- Cursed Penny
    [T_ID .. 173] = "Your Soul", -- Your Soul
    [T_ID .. 174] = "Number Magnet", -- Number Magnet
    [T_ID .. 175] = "Strange Key", -- Strange Key
    [T_ID .. 176] = "Lil Clot", -- Lil Clot
    [T_ID .. 177] = "Temporary Tattoo", -- Temporary Tattoo
    [T_ID .. 178] = "Swallowed M80", -- Swallowed M80
    [T_ID .. 179] = "RC Remote", -- RC Remote
    [T_ID .. 180] = "Found Soul", -- Found Soul
    [T_ID .. 181] = "Expansion Pack", -- Expansion Pack
    [T_ID .. 182] = "Beth's Essence", -- Beth's Essence
    [T_ID .. 183] = "The Twins", -- The Twins
    [T_ID .. 184] = "Adoption Papers", -- Adoption Papers
    [T_ID .. 185] = "Cricket Leg", -- Cricket Leg
    [T_ID .. 186] = "Apollyon's Best Friend", -- Apollyon's Best Friend
    [T_ID .. 187] = "Broken Glasses", -- Broken Glasses
    [T_ID .. 188] = "Ice Cube", -- Ice Cube
    [T_ID .. 189] = "Sigil of Baphomet", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - The Fool", -- 0 - The Fool
    [Card_ID .. 2] = "I - The Magician", -- I - The Magician
    [Card_ID .. 3] = "II - The High Priestess", -- II - The High Priestess
    [Card_ID .. 4] = "III - The Empress", -- III - The Empress
    [Card_ID .. 5] = "IV - The Emperor", -- IV - The Emperor
    [Card_ID .. 6] = "V - The Hierophant", -- V - The Hierophant
    [Card_ID .. 7] = "VI - The Lovers", -- VI - The Lovers
    [Card_ID .. 8] = "VII - The Chariot", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Justice", -- VIII - Justice
    [Card_ID .. 10] = "IX - The Hermit", -- IX - The Hermit
    [Card_ID .. 11] = "X - Wheel of Fortune", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Strength", -- XI - Strength
    [Card_ID .. 13] = "XII - The Hanged Man", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Death", -- XIII - Death
    [Card_ID .. 15] = "XIV - Temperance", -- XIV - Temperance
    [Card_ID .. 16] = "XV - The Devil", -- XV - The Devil
    [Card_ID .. 17] = "XVI - The Tower", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - The Stars", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - The Moon", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - The Sun", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Judgement", -- XX - Judgement
    [Card_ID .. 22] = "XXI - The World", -- XXI - The World
    [Card_ID .. 23] = "2 of Clubs", -- 2 of Clubs
    [Card_ID .. 24] = "2 of Diamonds", -- 2 of Diamonds
    [Card_ID .. 25] = "2 of Spades", -- 2 of Spades
    [Card_ID .. 26] = "2 of Hearts", -- 2 of Hearts
    [Card_ID .. 27] = "Ace of Clubs", -- Ace of Clubs
    [Card_ID .. 28] = "Ace of Diamonds", -- Ace of Diamonds
    [Card_ID .. 29] = "Ace of Spades", -- Ace of Spades
    [Card_ID .. 30] = "Ace of Hearts", -- Ace of Hearts
    [Card_ID .. 31] = "Joker", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Blank Rune", -- Blank Rune
    [Card_ID .. 41] = "Black Rune", -- Black Rune
    [Card_ID .. 42] = "Chaos Card", -- Chaos Card
    [Card_ID .. 43] = "Credit Card", -- Credit Card
    [Card_ID .. 44] = "Rules Card", -- Rules Card
    [Card_ID .. 45] = "A Card Against Humanity", -- A Card Against Humanity
    [Card_ID .. 46] = "Suicide King", -- Suicide King
    [Card_ID .. 47] = "Get Out Of Jail Free Card", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "? Card", -- ? Card
    [Card_ID .. 49] = "Dice Shard", -- Dice Shard
    [Card_ID .. 50] = "Emergency Contact", -- Emergency Contact
    [Card_ID .. 51] = "Holy Card", -- Holy Card
    [Card_ID .. 52] = "Huge Growth", -- Huge Growth
    [Card_ID .. 53] = "Ancient Recall", -- Ancient Recall
    [Card_ID .. 54] = "Era Walk", -- Era Walk
    [Card_ID .. 55] = "Rune Shard", -- Rune Shard
    [Card_ID .. 56] = "0 - The Fool?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - The Magician?", -- I - The Magician?
    [Card_ID .. 58] = "II - The High Priestess?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - The Empress?", -- III - The Empress?
    [Card_ID .. 60] = "IV - The Emperor?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - The Hierophant?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - The Lovers?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - The Chariot?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Justice?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - The Hermit?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Wheel of Fortune?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Strength?", -- XI - Strength?
    [Card_ID .. 68] = "XII - The Hanged Man?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Death?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Temperance?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - The Devil?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - The Tower?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - The Stars?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - The Moon?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - The Sun?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Judgement?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - The World?", -- XXI - The World?
    [Card_ID .. 78] = "Cracked Key", -- Cracked Key
    [Card_ID .. 79] = "Queen of Hearts", -- Queen of Hearts
    [Card_ID .. 80] = "Wild Card", -- Wild Card
    [Card_ID .. 81] = "Soul of Isaac", -- Soul of Isaac
    [Card_ID .. 82] = "Soul of Magdalene", -- Soul of Magdalene
    [Card_ID .. 83] = "Soul of Cain", -- Soul of Cain
    [Card_ID .. 84] = "Soul of Judas", -- Soul of Judas
    [Card_ID .. 85] = "Soul of ???", -- Soul of ???
    [Card_ID .. 86] = "Soul of Eve", -- Soul of Eve
    [Card_ID .. 87] = "Soul of Samson", -- Soul of Samson
    [Card_ID .. 88] = "Soul of Azazel", -- Soul of Azazel
    [Card_ID .. 89] = "Soul of Lazarus", -- Soul of Lazarus
    [Card_ID .. 90] = "Soul of Eden", -- Soul of Eden
    [Card_ID .. 91] = "Soul of the Lost", -- Soul of the Lost
    [Card_ID .. 92] = "Soul of Lilith", -- Soul of Lilith
    [Card_ID .. 93] = "Soul of the Keeper", -- Soul of the Keeper
    [Card_ID .. 94] = "Soul of Apollyon", -- Soul of Apollyon
    [Card_ID .. 95] = "Soul of the Forgotten", -- Soul of the Forgotten
    [Card_ID .. 96] = "Soul of Bethany", -- Soul of Bethany
    [Card_ID .. 97] = "Soul of Jacob and Esau", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 0] = "Bad Gas", -- Bad Gas
    [Pill_ID .. 1] = "Bad Trip", -- Bad Trip
    [Pill_ID .. 2] = "Balls of Steel", -- Balls of Steel
    [Pill_ID .. 3] = "Bombs are Key", -- Bombs are Key
    [Pill_ID .. 4] = "Explosive Diarrhea", -- Explosive Diarrhea
    [Pill_ID .. 5] = "Full Health", -- Full Health
    [Pill_ID .. 6] = "Health Down", -- Health Down
    [Pill_ID .. 7] = "Health Up", -- Health Up
    [Pill_ID .. 8] = "I Found Pills", -- I Found Pills
    [Pill_ID .. 9] = "Puberty", -- Puberty
    [Pill_ID .. 10] = "Pretty Fly", -- Pretty Fly
    [Pill_ID .. 11] = "Range Down", -- Range Down
    [Pill_ID .. 12] = "Range Up", -- Range Up
    [Pill_ID .. 13] = "Speed Down", -- Speed Down
    [Pill_ID .. 14] = "Speed Up", -- Speed Up
    [Pill_ID .. 15] = "Tears Down", -- Tears Down
    [Pill_ID .. 16] = "Tears Up", -- Tears Up
    [Pill_ID .. 17] = "Luck Down", -- Luck Down
    [Pill_ID .. 18] = "Luck Up", -- Luck Up
    [Pill_ID .. 19] = "Telepills", -- Telepills
    [Pill_ID .. 20] = "48 Hour Energy!", -- 48 Hour Energy!
    [Pill_ID .. 21] = "Hematemesis", -- Hematemesis
    [Pill_ID .. 22] = "Paralysis", -- Paralysis
    [Pill_ID .. 23] = "I can see forever!", -- I can see forever!
    [Pill_ID .. 24] = "Pheromones", -- Pheromones
    [Pill_ID .. 25] = "Amnesia", -- Amnesia
    [Pill_ID .. 26] = "Lemon Party", -- Lemon Party
    [Pill_ID .. 27] = "R U A Wizard?", -- R U A Wizard?
    [Pill_ID .. 28] = "Percs!", -- Percs!
    [Pill_ID .. 29] = "Addicted!", -- Addicted!
    [Pill_ID .. 30] = "Re-Lax", -- Re-Lax
    [Pill_ID .. 31] = "???", -- ???
    [Pill_ID .. 32] = "One makes you larger", -- One makes you larger
    [Pill_ID .. 33] = "One makes you small", -- One makes you small
    [Pill_ID .. 34] = "Infested!", -- Infested!
    [Pill_ID .. 35] = "Infested?", -- Infested?
    [Pill_ID .. 36] = "Power Pill!", -- Power Pill!
    [Pill_ID .. 37] = "Retro Vision", -- Retro Vision
    [Pill_ID .. 38] = "Friends Till The End!", -- Friends Till The End!
    [Pill_ID .. 39] = "X-Lax", -- X-Lax
    [Pill_ID .. 40] = "Something's wrong...", -- Something's wrong...
    [Pill_ID .. 41] = "I'm Drowsy...", -- I'm Drowsy...
    [Pill_ID .. 42] = "I'm Excited!!", -- I'm Excited!!
    [Pill_ID .. 43] = "Gulp!", -- Gulp!
    [Pill_ID .. 44] = "Horf!", -- Horf!
    [Pill_ID .. 45] = "Feels like I'm walking on sunshine!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 46] = "Vurp!", -- Vurp!
    [Pill_ID .. 47] = "Shot speed Down", -- Shot speed Down
    [Pill_ID .. 48] = "Shot speed Up", -- Shot speed Up
    [Pill_ID .. 49] = "Experimental Pill", -- Experimental Pill
    [Pill_ID .. 9999] = "Golden Pill", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])