local languageCode = "fr"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Oignon Triste", -- The Sad Onion
    [C_ID .. 2] = "Troisième Œil", -- The Inner Eye
    [C_ID .. 3] = "Cuillère Tordue", -- Spoon Bender
    [C_ID .. 4] = "Tête de Cricket", -- Cricket's Head
    [C_ID .. 5] = "Mon Reflet", -- My Reflection
    [C_ID .. 6] = "Petite Commission", -- Number One
    [C_ID .. 7] = "Sang du Martyr", -- Blood of the Martyr
    [C_ID .. 8] = "Frère Bobby", -- Brother Bobby
    [C_ID .. 9] = "Scatol", -- Skatole
    [C_ID .. 10] = "Couronne de Mouches", -- Halo of Flies
    [C_ID .. 11] = "1-UP !", -- 1up!
    [C_ID .. 12] = "Champignon Magique", -- Magic Mushroom
    [C_ID .. 13] = "Le Virus", -- The Virus
    [C_ID .. 14] = "Crise d'Hormones", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Foie Cru", -- Raw Liver
    [C_ID .. 17] = "Clé Squelette", -- Skeleton Key
    [C_ID .. 18] = "Un Dollar", -- A Dollar
    [C_ID .. 19] = "Boum !", -- Boom!
    [C_ID .. 20] = "Transcendance", -- Transcendence
    [C_ID .. 21] = "Boussole", -- The Compass
    [C_ID .. 22] = "Déjeuner", -- Lunch
    [C_ID .. 23] = "Dîner", -- Dinner
    [C_ID .. 24] = "Dessert", -- Dessert
    [C_ID .. 25] = "Petit Déjeuner", -- Breakfast
    [C_ID .. 26] = "Viande Avariée", -- Rotten Meat
    [C_ID .. 27] = "Cuillère en Bois", -- Wooden Spoon
    [C_ID .. 28] = "Ceinture", -- The Belt
    [C_ID .. 29] = "Culotte de Maman", -- Mom's Underwear
    [C_ID .. 30] = "Escarpins de Maman", -- Mom's Heels
    [C_ID .. 31] = "Rouge à Lèvres de Maman", -- Mom's Lipstick
    [C_ID .. 32] = "Cintre", -- Wire Coat Hanger
    [C_ID .. 33] = "Bible", -- The Bible
    [C_ID .. 34] = "Livre de Bélial", -- The Book of Belial
    [C_ID .. 35] = "Necronomicon", -- The Necronomicon
    [C_ID .. 36] = "Tas de Caca", -- The Poop
    [C_ID .. 37] = "M. Boum", -- Mr. Boom
    [C_ID .. 38] = "Tête de Tammy", -- Tammy's Head
    [C_ID .. 39] = "Soutien-Gorge de Maman", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze !", -- Kamikaze!
    [C_ID .. 41] = "Serviette de Maman", -- Mom's Pad
    [C_ID .. 42] = "Tête de Bob", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Téléportation !", -- Teleport!
    [C_ID .. 45] = "Joli Cœur", -- Yum Heart
    [C_ID .. 46] = "Pied Chanceux", -- Lucky Foot
    [C_ID .. 47] = "Télécommande du Docteur", -- Doctor's Remote
    [C_ID .. 48] = "Flèche de Cupidon", -- Cupid's Arrow
    [C_ID .. 49] = "Super Laser de la Mort", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagramme", -- Pentagram
    [C_ID .. 52] = "Dr. Fœtus", -- Dr. Fetus
    [C_ID .. 53] = "Gros Aimant", -- Magneto
    [C_ID .. 54] = "Carte au Trésor", -- Treasure Map
    [C_ID .. 55] = "Œil de Maman", -- Mom's Eye
    [C_ID .. 56] = "Petit Acident", -- Lemon Mishap
    [C_ID .. 57] = "Admiration Distante", -- Distant Admiration
    [C_ID .. 58] = "Livre des Ombres", -- Book of Shadows
    [C_ID .. 59] = "Livre de Bélial (passif)", -- The Book of Belial
    [C_ID .. 60] = "Échelle en Bois", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Morsure de Vampire", -- Charm of the Vampire
    [C_ID .. 63] = "Pile Électrique", -- The Battery
    [C_ID .. 64] = "Soldes", -- Steam Sale
    [C_ID .. 65] = "Guide du Petit Anarchiste", -- Anarchist Cookbook
    [C_ID .. 66] = "Sablier", -- The Hourglass
    [C_ID .. 67] = "Sœurette Marie", -- Sister Maggy
    [C_ID .. 68] = "Technologie", -- Technology
    [C_ID .. 69] = "Chocolat Chaud", -- Chocolate Milk
    [C_ID .. 70] = "Hormones de Croissance", -- Growth Hormones
    [C_ID .. 71] = "Mini Champi", -- Mini Mush
    [C_ID .. 72] = "Rosaire", -- Rosary
    [C_ID .. 73] = "Cube de Viande", -- Cube of Meat
    [C_ID .. 74] = "Une Petite Pièce", -- A Quarter
    [C_ID .. 75] = "Doctorat", -- PHD
    [C_ID .. 76] = "Lunettes à Rayon X", -- X-Ray Vision
    [C_ID .. 77] = "Licorne Arc-En-Ciel", -- My Little Unicorn
    [C_ID .. 78] = "Livre de la Révélation", -- Book of Revelations
    [C_ID .. 79] = "Le Nombre de la Bête", -- The Mark
    [C_ID .. 80] = "Le Pacte", -- The Pact
    [C_ID .. 81] = "Chat Mort", -- Dead Cat
    [C_ID .. 82] = "Empereur de la Fosse", -- Lord of the Pit
    [C_ID .. 83] = "Clou Pointu", -- The Nail
    [C_ID .. 84] = "Aller au Fond des Choses", -- We Need To Go Deeper!
    [C_ID .. 85] = "Jeu de Cartes", -- Deck of Cards
    [C_ID .. 86] = "Dent de Monstro", -- Monstro's Tooth
    [C_ID .. 87] = "Cornes de Loki", -- Loki's Horns
    [C_ID .. 88] = "P'tit Dodu", -- Little Chubby
    [C_ID .. 89] = "Morsure d'Araignée", -- Spider Bite
    [C_ID .. 90] = "Gros Caillou", -- The Small Rock
    [C_ID .. 91] = "Casque de Spéléologue", -- Spelunker Hat
    [C_ID .. 92] = "Super Pansement", -- Super Bandage
    [C_ID .. 93] = "Jeu-Garçon", -- The Gamekid
    [C_ID .. 94] = "Bourse", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Bébé", -- Robo-Baby
    [C_ID .. 96] = "P'tit C.H.A.D", -- Little C.H.A.D.
    [C_ID .. 97] = "Livre du Péché", -- The Book of Sin
    [C_ID .. 98] = "Relique", -- The Relic
    [C_ID .. 99] = "P'tit Gish", -- Little Gish
    [C_ID .. 100] = "P'tit Steven", -- Little Steven
    [C_ID .. 101] = "Auréole", -- The Halo
    [C_ID .. 102] = "Flacon de Pilules de Maman", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Rhume", -- The Common Cold
    [C_ID .. 104] = "Parasite", -- The Parasite
    [C_ID .. 105] = "D6", -- The D6
    [C_ID .. 106] = "M. Méga", -- Mr. Mega
    [C_ID .. 107] = "Ciseaux Cranteurs", -- The Pinking Shears
    [C_ID .. 108] = "Hostie", -- The Wafer
    [C_ID .. 109] = "Avidité", -- Money = Power
    [C_ID .. 110] = "Lentille de Maman", -- Mom's Contacts
    [C_ID .. 111] = "Haricot", -- The Bean
    [C_ID .. 112] = "Ange Gardien", -- Guardian Angel
    [C_ID .. 113] = "Bébé Démoniaque", -- Demon Baby
    [C_ID .. 114] = "Couteau de Maman", -- Mom's Knife
    [C_ID .. 115] = "Planche de Ouija", -- Ouija Board
    [C_ID .. 116] = "Pile 9 Volts", -- 9 Volt
    [C_ID .. 117] = "Oiseau Mort", -- Dead Bird
    [C_ID .. 118] = "Soufre", -- Brimstone
    [C_ID .. 119] = "Poche de Sang", -- Blood Bag
    [C_ID .. 120] = "Champignon Suspect", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Champignon Suspect", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Grande Prostituée", -- Whore of Babylon
    [C_ID .. 123] = "Manuel des Monstres", -- Monster Manual
    [C_ID .. 124] = "Manuscrits de la Mer Morte", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bombes", -- Bobby-Bomb
    [C_ID .. 126] = "Lame de Rasoir", -- Razor Blade
    [C_ID .. 127] = "Pilule Tranquillisante", -- Forget Me Now
    [C_ID .. 128] = "Seul à Jamais", -- Forever Alone
    [C_ID .. 129] = "Seau de Saindoux", -- Bucket of Lard
    [C_ID .. 130] = "Poney Noir", -- A Pony
    [C_ID .. 131] = "Sac de Bombes", -- Bomb Bag
    [C_ID .. 132] = "Morceau de Charbon", -- A Lump of Coal
    [C_ID .. 133] = "Patte de Guppy", -- Guppy's Paw
    [C_ID .. 134] = "Queue de Guppy", -- Guppy's Tail
    [C_ID .. 135] = "Perfusion", -- IV Bag
    [C_ID .. 136] = "Mon Meilleur Ami", -- Best Friend
    [C_ID .. 137] = "Détonateur Télécommandé", -- Remote Detonator
    [C_ID .. 138] = "Stigmates", -- Stigmata
    [C_ID .. 139] = "Sac à Main de Maman", -- Mom's Purse
    [C_ID .. 140] = "Malédiction de Bob", -- Bob's Curse
    [C_ID .. 141] = "Bête de Foire", -- Pageant Boy
    [C_ID .. 142] = "Scapulaire", -- Scapular
    [C_ID .. 143] = "Pot Belge", -- Speed Ball
    [C_ID .. 144] = "Ami Mendiant", -- Bum Friend
    [C_ID .. 145] = "Tête de Guppy", -- Guppy's Head
    [C_ID .. 146] = "Carte Pieuse", -- Prayer Card
    [C_ID .. 147] = "Pioche en Fer", -- Notched Axe
    [C_ID .. 148] = "Infestation", -- Infestation
    [C_ID .. 149] = "Ipéca", -- Ipecac
    [C_ID .. 150] = "Poing Américain", -- Tough Love
    [C_ID .. 151] = "Mulligan", -- The Mulligan
    [C_ID .. 152] = "Technologie 2", -- Technology 2
    [C_ID .. 153] = "Araignée Mutante", -- Mutant Spider
    [C_ID .. 154] = "Masque à l'Acide", -- Chemical Peel
    [C_ID .. 155] = "Œil Baladeur", -- The Peeper
    [C_ID .. 156] = "Voile de Nonne", -- Habit
    [C_ID .. 157] = "Soif de Sang", -- Bloody Lust
    [C_ID .. 158] = "Boule de Cristal", -- Crystal Ball
    [C_ID .. 159] = "Esprit de la Nuit", -- Spirit of the Night
    [C_ID .. 160] = "Fissure Céleste", -- Crack the Sky
    [C_ID .. 161] = "Ânkh", -- Ankh
    [C_ID .. 162] = "Croix Celte", -- Celtic Cross
    [C_ID .. 163] = "Bébé Fantôme", -- Ghost Baby
    [C_ID .. 164] = "Bougie Bleue", -- The Candle
    [C_ID .. 165] = "Chat à Neuf Queues", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Bébé Arlequin", -- Harlequin Baby
    [C_ID .. 168] = "Super Fœtus", -- Epic Fetus
    [C_ID .. 169] = "Polyphème", -- Polyphemus
    [C_ID .. 170] = "Le Faucheux", -- Daddy Longlegs
    [C_ID .. 171] = "Filière d'Araignée", -- Spider Butt
    [C_ID .. 172] = "Dague Sacrificielle", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitre", -- Mitre
    [C_ID .. 174] = "Bébé Arc-en-Ciel", -- Rainbow Baby
    [C_ID .. 175] = "Clé de Papa", -- Dad's Key
    [C_ID .. 176] = "Cellules Souches", -- Stem Cells
    [C_ID .. 177] = "Casino Portatif", -- Portable Slot
    [C_ID .. 178] = "Eau Bénite", -- Holy Water
    [C_ID .. 179] = "Destin", -- Fate
    [C_ID .. 180] = "Haricot Noir", -- The Black Bean
    [C_ID .. 181] = "Poney Blanc", -- White Pony
    [C_ID .. 182] = "Sacré-Cœur", -- Sacred Heart
    [C_ID .. 183] = "Cure-Dents", -- Tooth Picks
    [C_ID .. 184] = "Saint Graal", -- Holy Grail
    [C_ID .. 185] = "Colombe Morte", -- Dead Dove
    [C_ID .. 186] = "Droits du Sang", -- Blood Rights
    [C_ID .. 187] = "Boule de Poils de Guppy", -- Guppy's Hairball
    [C_ID .. 188] = "Abel", -- Abel
    [C_ID .. 189] = "Super Fan de SMB", -- SMB Super Fan
    [C_ID .. 190] = "Pyro", -- Pyro
    [C_ID .. 191] = "Billet de Trois", -- 3 Dollar Bill
    [C_ID .. 192] = "La Télépathie pour les Nuls", -- Telepathy for Dummies
    [C_ID .. 193] = "DE LA VIANDE !", -- MEAT!
    [C_ID .. 194] = "Boule Magique", -- Magic 8 Ball
    [C_ID .. 195] = "Porte-Monnaie de Maman", -- Mom's Coin Purse
    [C_ID .. 196] = "Jouet Anti-Stress", -- Squeezy
    [C_ID .. 197] = "Sang du Christ", -- Jesus Juice
    [C_ID .. 198] = "Boîte", -- Box
    [C_ID .. 199] = "Clé de Maman", -- Mom's Key
    [C_ID .. 200] = "Fard à Paupières de Maman", -- Mom's Eyeshadow
    [C_ID .. 201] = "Lingot de Fer", -- Iron Bar
    [C_ID .. 202] = "Malédiction de Midas", -- Midas' Touch
    [C_ID .. 203] = "Offre Spéciale", -- Humbleing Bundle
    [C_ID .. 204] = "Sac Banane", -- Fanny Pack
    [C_ID .. 205] = "Prise de Sang", -- Sharp Plug
    [C_ID .. 206] = "Guillotine", -- Guillotine
    [C_ID .. 207] = "Boule de Pansements", -- Ball of Bandages
    [C_ID .. 208] = "Ceinture du Champion", -- Champion Belt
    [C_ID .. 209] = "Bombes Bronze", -- Butt Bombs
    [C_ID .. 210] = "Feuille Grignotée", -- Gnawed Leaf
    [C_ID .. 211] = "Bébé Araignée", -- Spiderbaby
    [C_ID .. 212] = "Collier de Guppy", -- Guppy's Collar
    [C_ID .. 213] = "Lentille Égarée", -- Lost Contact
    [C_ID .. 214] = "Anémie", -- Anemic
    [C_ID .. 215] = "Tête de Bouc", -- Goat Head
    [C_ID .. 216] = "Robe de Cérémonie", -- Ceremonial Robes
    [C_ID .. 217] = "Perruque de Maman", -- Mom's Wig
    [C_ID .. 218] = "Placenta", -- Placenta
    [C_ID .. 219] = "Vieux Pansement", -- Old Bandage
    [C_ID .. 220] = "Bombes Pleureuses", -- Sad Bombs
    [C_ID .. 221] = "Colle Caoutchouc", -- Rubber Cement
    [C_ID .. 222] = "Antigravité", -- Anti-Gravity
    [C_ID .. 223] = "Pyromanie", -- Pyromaniac
    [C_ID .. 224] = "Corps de Cricket", -- Cricket's Body
    [C_ID .. 225] = "Latex", -- Gimpy
    [C_ID .. 226] = "Lotus Noir", -- Black Lotus
    [C_ID .. 227] = "Tirelire Cochon", -- Piggy Bank
    [C_ID .. 228] = "Parfum de Maman", -- Mom's Perfume
    [C_ID .. 229] = "Poumon de Monstro", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Boule de Goudron", -- Ball of Tar
    [C_ID .. 232] = "Chronomètre", -- Stop Watch
    [C_ID .. 233] = "Planète Naine", -- Tiny Planet
    [C_ID .. 234] = "Infestation 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "La Faucheuse", -- Death's Touch
    [C_ID .. 238] = "1er Fragment de Clé", -- Key Piece 1
    [C_ID .. 239] = "2è Fragment de Clé", -- Key Piece 2
    [C_ID .. 240] = "Traitement Expérimental", -- Experimental Treatment
    [C_ID .. 241] = "Contrat des Profondeurs", -- Contract from Below
    [C_ID .. 242] = "Infamie", -- Infamy
    [C_ID .. 243] = "Bouclier de la Trinité", -- Trinity Shield
    [C_ID .. 244] = "Tech 0,5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Carte Perdue", -- Blue Map
    [C_ID .. 247] = "Meilleurs Amis pour la Vie", -- BFFS!
    [C_ID .. 248] = "Conscience Collective", -- Hive Mind
    [C_ID .. 249] = "L'Embarras du Choix", -- There's Options
    [C_ID .. 250] = "Soldes Explosives", -- Bogo Bombs
    [C_ID .. 251] = "Deck du Débutant", -- Starter Deck
    [C_ID .. 252] = "Petit Sachet", -- Little Baggy
    [C_ID .. 253] = "Croûte Magique", -- Magic Scab
    [C_ID .. 254] = "Caillot de Sang", -- Blood Clot
    [C_ID .. 255] = "Vis", -- Screw
    [C_ID .. 256] = "Bombes Brûlantes", -- Hot Bombs
    [C_ID .. 257] = "Esprit de Feu", -- Fire Mind
    [C_ID .. 258] = "Missing No.", -- Missing No.
    [C_ID .. 259] = "Matière Noire", -- Dark Matter
    [C_ID .. 260] = "Bougie Noire", -- Black Candle
    [C_ID .. 261] = "Proptose", -- Proptosis
    [C_ID .. 262] = "Page Déchirée 2", -- Missing Page 2
    [C_ID .. 263] = "Rune de Cristal", -- Clear Rune
    [C_ID .. 264] = "Mouche Maline", -- Smart Fly
    [C_ID .. 265] = "Bébé Désséché", -- Dry Baby
    [C_ID .. 266] = "Cocon Juteux", -- Juicy Sack
    [C_ID .. 267] = "Robo-Bébé 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Bébé Putride", -- Rotten Baby
    [C_ID .. 269] = "Bébé Décapité", -- Headless Baby
    [C_ID .. 270] = "Sangsue", -- Leech
    [C_ID .. 271] = "Pochon Mystère", -- Mystery Sack
    [C_ID .. 272] = "BGM", -- BBF
    [C_ID .. 273] = "Cerveau de Bob", -- Bob's Brain
    [C_ID .. 274] = "Meilleure Pote", -- Best Bud
    [C_ID .. 275] = "P'tit Soufre", -- Lil Brimstone
    [C_ID .. 276] = "Cœur d'Isaac", -- Isaac's Heart
    [C_ID .. 277] = "P'tit Revenu", -- Lil Haunt
    [C_ID .. 278] = "Mendiant des Ombres", -- Dark Bum
    [C_ID .. 279] = "Mon Plus Gros Fan", -- Big Fan
    [C_ID .. 280] = "Sissy la Faucheuse", -- Sissy Longlegs
    [C_ID .. 281] = "Théodule", -- Punching Bag
    [C_ID .. 282] = "Manuel de Saut", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Carte Blanche", -- Blank Card
    [C_ID .. 287] = "Livre des Secrets", -- Book of Secrets
    [C_ID .. 288] = "Boîte d'Araignées", -- Box of Spiders
    [C_ID .. 289] = "Bougie Rouge", -- Red Candle
    [C_ID .. 290] = "Bocal en Verre", -- The Jar
    [C_ID .. 291] = "Chasse d'Eau", -- Flush!
    [C_ID .. 292] = "Bible Satanique", -- Satanic Bible
    [C_ID .. 293] = "Head of Krampus", -- Head of Krampus
    [C_ID .. 294] = "Haricot Beurre", -- Butter Bean
    [C_ID .. 295] = "Pot de Vin", -- Magic Fingers
    [C_ID .. 296] = "Adaptateur", -- Converter
    [C_ID .. 297] = "Boîte de Pandore", -- Pandora's Box
    [C_ID .. 298] = "Corne Brisée", -- Unicorn Stump
    [C_ID .. 299] = "Taureau", -- Taurus
    [C_ID .. 300] = "Bélier", -- Aries
    [C_ID .. 301] = "Cancer", -- Cancer
    [C_ID .. 302] = "Lion", -- Leo
    [C_ID .. 303] = "Vierge", -- Virgo
    [C_ID .. 304] = "Balance", -- Libra
    [C_ID .. 305] = "Scorpion", -- Scorpio
    [C_ID .. 306] = "Sagittaire", -- Sagittarius
    [C_ID .. 307] = "Capricorne", -- Capricorn
    [C_ID .. 308] = "Verseau", -- Aquarius
    [C_ID .. 309] = "Poissons", -- Pisces
    [C_ID .. 310] = "Mascara d'Ève", -- Eve's Mascara
    [C_ID .. 311] = "Ombre de Judas", -- Judas' Shadow
    [C_ID .. 312] = "Chouchou de Marie", -- Maggy's Bow
    [C_ID .. 313] = "Voile Sacré", -- Holy Mantle
    [C_ID .. 314] = "Seau de Fromage", -- Thunder Thighs
    [C_ID .. 315] = "Attracteur Étrange", -- Strange Attractor
    [C_ID .. 316] = "Œil Maudit", -- Cursed Eye
    [C_ID .. 317] = "Liquide Mystérieux", -- Mysterious Liquid
    [C_ID .. 318] = "Gémeaux", -- Gemini
    [C_ID .. 319] = "Œil Gauche de Caïn", -- Cain's Other Eye
    [C_ID .. 320] = "La Seule Amie de ???", -- ???'s Only Friend
    [C_ID .. 321] = "Boulet de Samson", -- Samson's Chains
    [C_ID .. 322] = "Bébé Moqueur", -- Mongo Baby
    [C_ID .. 323] = "Bocal de Larmes", -- Isaac's Tears
    [C_ID .. 324] = "erreur", -- Undefined
    [C_ID .. 325] = "Paire de Ciseaux", -- Scissors
    [C_ID .. 326] = "Souffle de Vie", -- Breath of Life
    [C_ID .. 327] = "Le Positif", -- The Polaroid
    [C_ID .. 328] = "Le Négatif", -- The Negative
    [C_ID .. 329] = "La Technique Ludovico", -- The Ludovico Technique
    [C_ID .. 330] = "Lait de Soja", -- Soy Milk
    [C_ID .. 331] = "Œil de la Providence", -- Godhead
    [C_ID .. 332] = "Loques de Lazare", -- Lazarus' Rags
    [C_ID .. 333] = "L'Esprit", -- The Mind
    [C_ID .. 334] = "Le Corps", -- The Body
    [C_ID .. 335] = "L'Âme", -- The Soul
    [C_ID .. 336] = "Oignon Pourri", -- Dead Onion
    [C_ID .. 337] = "Chronomètre Cassé", -- Broken Watch
    [C_ID .. 338] = "Boomerang", -- The Boomerang
    [C_ID .. 339] = "Épingle à Nourrice", -- Safety Pin
    [C_ID .. 340] = "Pilule de Caféine", -- Caffeine Pill
    [C_ID .. 341] = "Photo Déchirée", -- Torn Photo
    [C_ID .. 342] = "Lactarius Indigo", -- Blue Cap
    [C_ID .. 343] = "Collier à Clé", -- Latch Key
    [C_ID .. 344] = "Boîte d'Allumettes", -- Match Book
    [C_ID .. 345] = "Synthol", -- Synthoil
    [C_ID .. 346] = "Casse-Croûte", -- A Snack
    [C_ID .. 347] = "Diplopie", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Pièce en Bois", -- Wooden Nickel
    [C_ID .. 350] = "Choc Toxique", -- Toxic Shock
    [C_ID .. 351] = "Haricot Géant", -- Mega Bean
    [C_ID .. 352] = "Canon de Verre", -- Glass Cannon
    [C_ID .. 353] = "Homme Bombeur", -- Bomber Boy
    [C_ID .. 354] = "Boîte de Céréales", -- Crack Jacks
    [C_ID .. 355] = "Collier de Maman", -- Mom's Pearls
    [C_ID .. 356] = "Batterie de Voiture", -- Car Battery
    [C_ID .. 357] = "Boîte de Potes", -- Box of Friends
    [C_ID .. 358] = "Bonnet d'Âne", -- The Wiz
    [C_ID .. 359] = "Gros Clous", -- 8 Inch Nails
    [C_ID .. 360] = "Incube", -- Incubus
    [C_ID .. 361] = "Récompense du Destin", -- Fate's Reward
    [C_ID .. 362] = "P'tit Coffre", -- Lil Chest
    [C_ID .. 363] = "Protecteur Dévoué", -- Sworn Protector
    [C_ID .. 364] = "Relation à Distance", -- Friend Zone
    [C_ID .. 365] = "Mouche Égarée", -- Lost Fly
    [C_ID .. 366] = "Bombes à Fragmentation", -- Scatter Bombs
    [C_ID .. 367] = "Bombes Arachnides", -- Sticky Bombs
    [C_ID .. 368] = "Épiphora", -- Epiphora
    [C_ID .. 369] = "Continuum", -- Continuum
    [C_ID .. 370] = "Mme Poupée", -- Mr. Dolly
    [C_ID .. 371] = "Fléau de la Maison Dieu", -- Curse of the Tower
    [C_ID .. 372] = "Bébé Chargé", -- Charged Baby
    [C_ID .. 373] = "Œil de Lynx", -- Dead Eye
    [C_ID .. 374] = "Saint Éclat", -- Holy Light
    [C_ID .. 375] = "Crâne d'Hôte", -- Host Hat
    [C_ID .. 376] = "Réapprovisionnement", -- Restock
    [C_ID .. 377] = "Cocon Éclaté", -- Bursting Sack
    [C_ID .. 378] = "Grosse Commission", -- No. 2
    [C_ID .. 379] = "Polycorie", -- Pupula Duplex
    [C_ID .. 380] = "Fente Magique", -- Pay To Play
    [C_ID .. 381] = "Bénédiction d'Éden", -- Eden's Blessing
    [C_ID .. 382] = "Boule à Monstres", -- Friendly Ball
    [C_ID .. 383] = "Détonateur Lacrymal", -- Tear Detonator
    [C_ID .. 384] = "P'tit Boris", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Encensoir", -- Censer
    [C_ID .. 388] = "Cléchard", -- Key Bum
    [C_ID .. 389] = "Sac de Runes", -- Rune Bag
    [C_ID .. 390] = "Séraphin", -- Seraphim
    [C_ID .. 391] = "Trahison", -- Betrayal
    [C_ID .. 392] = "Zodiaque", -- Zodiac
    [C_ID .. 393] = "Baiser du Serpent", -- Serpent's Kiss
    [C_ID .. 394] = "Ligne de Mire", -- Marked
    [C_ID .. 395] = "Tech X", -- Tech X
    [C_ID .. 396] = "Scalpel Ventriculaire", -- Ventricle Razor
    [C_ID .. 397] = "Rayon Tracteur", -- Tractor Beam
    [C_ID .. 398] = "Chair des Dieux", -- God's Flesh
    [C_ID .. 399] = "Gouffre du Néant", -- Maw of the Void
    [C_ID .. 400] = "Sainte Lance", -- Spear of Destiny
    [C_ID .. 401] = "Explosivo", -- Explosivo
    [C_ID .. 402] = "Chaos", -- Chaos
    [C_ID .. 403] = "Roboraignée", -- Spider Mod
    [C_ID .. 404] = "Bébé Péteur", -- Farting Baby
    [C_ID .. 405] = "Bug", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Pureté", -- Purity
    [C_ID .. 408] = "Athamé", -- Athame
    [C_ID .. 409] = "Flacon Vide", -- Empty Vessel
    [C_ID .. 410] = "Mauvais Œil", -- Evil Eye
    [C_ID .. 411] = "Sang Salace", -- Lusty Blood
    [C_ID .. 412] = "Conception Impure", -- Cambion Conception
    [C_ID .. 413] = "Immaculée Conception", -- Immaculate Conception
    [C_ID .. 414] = "Plus d'Options", -- More Options
    [C_ID .. 415] = "Couronne de Lumière", -- Crown Of Light
    [C_ID .. 416] = "Poches Profondes", -- Deep Pockets
    [C_ID .. 417] = "Succube", -- Succubus
    [C_ID .. 418] = "Cake aux Fruits", -- Fruit Cake
    [C_ID .. 419] = "Téléportation 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Poudre Noire", -- Black Powder
    [C_ID .. 421] = "Haricot Rouge", -- Kidney Bean
    [C_ID .. 422] = "Sablier Luisant", -- Glowing Hourglass
    [C_ID .. 423] = "Cercle de Protection", -- Circle of Protection
    [C_ID .. 424] = "Sac en Papier", -- Sack Head
    [C_ID .. 425] = "Veilleuse", -- Night Light
    [C_ID .. 426] = "Admiratrice Obsessionnelle", -- Obsessed Fan
    [C_ID .. 427] = "Bloc de TNT", -- Mine Crafter
    [C_ID .. 428] = "Pyjama", -- PJs
    [C_ID .. 429] = "Tête du Gardien", -- Head of the Keeper
    [C_ID .. 430] = "Papa Mouche", -- Papa Fly
    [C_ID .. 431] = "Bébé Interdimensionnel", -- Multidimensional Baby
    [C_ID .. 432] = "Bombes à Paillettes", -- Glitter Bombs
    [C_ID .. 433] = "Mon Ombre", -- My Shadow
    [C_ID .. 434] = "Bocal de Mouches", -- Jar of Flies
    [C_ID .. 435] = "P'tit Loki", -- Lil Loki
    [C_ID .. 436] = "Tasse de Lait", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Tétine", -- Binky
    [C_ID .. 439] = "Boîte de Maman", -- Mom's Box
    [C_ID .. 440] = "Calcul Rénal", -- Kidney Stone
    [C_ID .. 441] = "Souffle du Diable", -- Mega Blast
    [C_ID .. 442] = "Couronne des Ténèbres", -- Dark Prince's Crown
    [C_ID .. 443] = "Pomme !", -- Apple!
    [C_ID .. 444] = "Crayon de Papier", -- Lead Pencil
    [C_ID .. 445] = "Dent de Chien", -- Dog Tooth
    [C_ID .. 446] = "Dent Pourrie", -- Dead Tooth
    [C_ID .. 447] = "Haricot Péteux", -- Linger Bean
    [C_ID .. 448] = "Bris de Verre", -- Shard of Glass
    [C_ID .. 449] = "Plaque de Fer", -- Metal Plate
    [C_ID .. 450] = "Œil d'Avarice", -- Eye of Greed
    [C_ID .. 451] = "Nappe de Tarot", -- Tarot Cloth
    [C_ID .. 452] = "Varices", -- Varicose Veins
    [C_ID .. 453] = "Fracture Ouverte", -- Compound Fracture
    [C_ID .. 454] = "Polydactylie", -- Polydactyly
    [C_ID .. 455] = "Médaille de Papa", -- Dad's Lost Coin
    [C_ID .. 456] = "Encas de Minuit", -- Midnight Snack
    [C_ID .. 457] = "Crâne d'Œuf", -- Cone Head
    [C_ID .. 458] = "Nombril", -- Belly Button
    [C_ID .. 459] = "Sinusite", -- Sinus Infection
    [C_ID .. 460] = "Glaucome", -- Glaucoma
    [C_ID .. 461] = "Parasitoïde", -- Parasitoid
    [C_ID .. 462] = "Œil de Bélial", -- Eye of Belial
    [C_ID .. 463] = "Acide Sulfurique", -- Sulfuric Acid
    [C_ID .. 464] = "Marque d'Harmonie", -- Glyph of Balance
    [C_ID .. 465] = "Stick Analogique", -- Analog Stick
    [C_ID .. 466] = "Contagion", -- Contagion
    [C_ID .. 467] = "Doigt Accusateur", -- Finger!
    [C_ID .. 468] = "Ombre", -- Shade
    [C_ID .. 469] = "Dépression", -- Depression
    [C_ID .. 470] = "P'tit Murmure", -- Hushy
    [C_ID .. 471] = "P'tit Monstro", -- Lil Monstro
    [C_ID .. 472] = "Bébé Roi", -- King Baby
    [C_ID .. 473] = "Gros Dodu", -- Big Chubby
    [C_ID .. 474] = "Canon de Verre Brisé", -- Broken Glass Cannon
    [C_ID .. 475] = "Suppo de Satan", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Néant", -- Void
    [C_ID .. 478] = "Pause !", -- Pause
    [C_ID .. 479] = "Fondeuse", -- Smelter
    [C_ID .. 480] = "Composte", -- Compost
    [C_ID .. 481] = "Pioche Pirate", -- Dataminer
    [C_ID .. 482] = "Télécommande", -- Clicker
    [C_ID .. 483] = "Mama Méga", -- Mama Mega!
    [C_ID .. 484] = "Attends, Quoi ?", -- Wait What?
    [C_ID .. 485] = "Pièce Tordue", -- Crooked Penny
    [C_ID .. 486] = "Lame Émoussée", -- Dull Razor
    [C_ID .. 487] = "Épluche-Légumes", -- Potato Peeler
    [C_ID .. 488] = "Métronome", -- Metronome
    [C_ID .. 489] = "Dé Infini", -- D Infinity
    [C_ID .. 490] = "Âme d'Éden", -- Eden's Soul
    [C_ID .. 491] = "Bébé Drogué", -- Acid Baby
    [C_ID .. 492] = "Fée Agaçante", -- YO LISTEN!
    [C_ID .. 493] = "Adrénaline", -- Adrenaline
    [C_ID .. 494] = "Échelle de Jacob", -- Jacob's Ladder
    [C_ID .. 495] = "Piment Fantôme", -- Ghost Pepper
    [C_ID .. 496] = "Euthanasie", -- Euthanasia
    [C_ID .. 497] = "Slip Camouflage", -- Camo Undies
    [C_ID .. 498] = "Dualité", -- Duality
    [C_ID .. 499] = "Eucharistie", -- Eucharist
    [C_ID .. 500] = "Sac de Sacs", -- Sack of Sacks
    [C_ID .. 501] = "Gosier d'Avarice", -- Greed's Gullet
    [C_ID .. 502] = "Grosse Pustule", -- Large Zit
    [C_ID .. 503] = "P'tite Corne", -- Little Horn
    [C_ID .. 504] = "Bout de Crotte", -- Brown Nugget
    [C_ID .. 505] = "Poké Go", -- Poke Go
    [C_ID .. 506] = "Traîtrise", -- Backstabber
    [C_ID .. 507] = "Paille Aiguisée", -- Sharp Straw
    [C_ID .. 508] = "Rasoir de Maman", -- Mom's Razor
    [C_ID .. 509] = "Nœnœil", -- Bloodshot Eye
    [C_ID .. 510] = "Délire", -- Delirious
    [C_ID .. 511] = "Mouche Enragée", -- Angry Fly
    [C_ID .. 512] = "Trou Noir", -- Black Hole
    [C_ID .. 513] = "Bozo", -- Bozo
    [C_ID .. 514] = "Routeur Cassé", -- Broken Modem
    [C_ID .. 515] = "Cadeau Surprise", -- Mystery Gift
    [C_ID .. 516] = "Arroseur Automatique", -- Sprinkler
    [C_ID .. 517] = "Bombes Éclair", -- Fast Bombs
    [C_ID .. 518] = "Pote en Boîte", -- Buddy in a Box
    [C_ID .. 519] = "P'tit Delirium", -- Lil Delirium
    [C_ID .. 520] = "Câbles de Démarrage", -- Jumper Cables
    [C_ID .. 521] = "Coupon", -- Coupon
    [C_ID .. 522] = "Télékinésie", -- Telekinesis
    [C_ID .. 523] = "Carton de Déménagement", -- Moving Box
    [C_ID .. 524] = "Technologie Zéro", -- Technology Zero
    [C_ID .. 525] = "Lèpre", -- Leprosy
    [C_ID .. 526] = "Livre des 7 Sceaux", -- 7 Seals
    [C_ID .. 527] = "Boîte à Larbin", -- Mr. ME!
    [C_ID .. 528] = "Prisme Angélique", -- Angelic Prism
    [C_ID .. 529] = "Pop !", -- Pop!
    [C_ID .. 530] = "La Liste de la Mort", -- Death's List
    [C_ID .. 531] = "Haemolacria", -- Haemolacria
    [C_ID .. 532] = "Lachryphagie", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Cartable", -- Schoolbag
    [C_ID .. 535] = "Couverture", -- Blanket
    [C_ID .. 536] = "Autel Sacrificiel", -- Sacrificial Altar
    [C_ID .. 537] = "P'tit Spewer", -- Lil Spewer
    [C_ID .. 538] = "Sac de Billes", -- Marbles
    [C_ID .. 539] = "Œuf Mystère", -- Mystery Egg
    [C_ID .. 540] = "Pierre Plate", -- Flat Stone
    [C_ID .. 541] = "Moelle", -- Marrow
    [C_ID .. 542] = "Côte Cassée", -- Slipped Rib
    [C_ID .. 543] = "Terre Sacrée", -- Hallowed Ground
    [C_ID .. 544] = "Côte Pointue", -- Pointy Rib
    [C_ID .. 545] = "Livre des Morts", -- Book of the Dead
    [C_ID .. 546] = "Bague de Papa", -- Dad's Ring
    [C_ID .. 547] = "Acte de Divorce", -- Divorce Papers
    [C_ID .. 548] = "Mandibule", -- Jaw Bone
    [C_ID .. 549] = "Os de Verre", -- Brittle Bones
    [C_ID .. 550] = "Pelle Brisée", -- Broken Shovel
    [C_ID .. 551] = "Pelle Brisée", -- Broken Shovel
    [C_ID .. 552] = "Pelle de Maman", -- Mom's Shovel
    [C_ID .. 553] = "Mucormycose", -- Mucormycosis
    [C_ID .. 554] = "BOUH", -- 2Spooky
    [C_ID .. 555] = "Lame de Rasoir Dorée", -- Golden Razor
    [C_ID .. 556] = "Sulfure", -- Sulfur
    [C_ID .. 557] = "Biscuit Chinois", -- Fortune Cookie
    [C_ID .. 558] = "Les Yeux de la Tête", -- Eye Sore
    [C_ID .. 559] = "120 Volts", -- 120 Volt
    [C_ID .. 560] = "Motus", -- It Hurts
    [C_ID .. 561] = "Lait d'Amande", -- Almond Milk
    [C_ID .. 562] = "Au Fond du Trou", -- Rock Bottom
    [C_ID .. 563] = "Bombes Fabuleuses", -- Nancy Bombs
    [C_ID .. 564] = "Savonnette", -- A Bar of Soap
    [C_ID .. 565] = "Chiot de Sang", -- Blood Puppy
    [C_ID .. 566] = "Attrape-Rêve", -- Dream Catcher
    [C_ID .. 567] = "Cierge Pascal", -- Paschal Candle
    [C_ID .. 568] = "Intervention Divine", -- Divine Intervention
    [C_ID .. 569] = "Serment du Sang", -- Blood Oath
    [C_ID .. 570] = "Cookie en Pâte à Modeler", -- Playdough Cookie
    [C_ID .. 571] = "Chaussettes Orphelines", -- Orphan Socks
    [C_ID .. 572] = "Œil Occulte", -- Eye of the Occult
    [C_ID .. 573] = "Cœur Immaculé", -- Immaculate Heart
    [C_ID .. 574] = "Monstrance", -- Monstrance
    [C_ID .. 575] = "L'Envahisseur", -- The Intruder
    [C_ID .. 576] = "Coprophilie", -- Dirty Mind
    [C_ID .. 577] = "Damoclès", -- Damocles
    [C_ID .. 578] = "Carafe de Limonade", -- Free Lemonade
    [C_ID .. 579] = "Épée de l'Esprit", -- Spirit Sword
    [C_ID .. 580] = "Clé Rouge", -- Red Key
    [C_ID .. 581] = "Mouche Oracle", -- Psy Fly
    [C_ID .. 582] = "Psilocybe Cyanescens", -- Wavy Cap
    [C_ID .. 583] = "Fusée en Bocal", -- Rocket in a Jar
    [C_ID .. 584] = "Livre des Vertus", -- Book of Virtues
    [C_ID .. 585] = "Boîte d'Albâtre", -- Alabaster Box
    [C_ID .. 586] = "Échelle Vers les Cieux", -- The Stairway
    [C_ID .. 587] = "Menorah", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Luna", -- Luna
    [C_ID .. 590] = "Mercurius", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Terra", -- Terra
    [C_ID .. 593] = "Mars", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturnus", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptunus", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Tête Réduite", -- Voodoo Head
    [C_ID .. 600] = "Collyre", -- Eye Drops
    [C_ID .. 601] = "Acte de Contrition", -- Act of Contrition
    [C_ID .. 602] = "Carte de Membre", -- Member Card
    [C_ID .. 603] = "Batterie", -- Battery Pack
    [C_ID .. 604] = "Bracelet de Maman", -- Mom's Bracelet
    [C_ID .. 605] = "Cuillère à Glace", -- The Scooper
    [C_ID .. 606] = "Faille Oculaire", -- Ocular Rift
    [C_ID .. 607] = "Bébé Furoncle", -- Boiled Baby
    [C_ID .. 608] = "Bébé Surgelé", -- Freezer Baby
    [C_ID .. 609] = "D6 Éternel", -- Eternal D6
    [C_ID .. 610] = "Gros Piaf", -- Bird Cage
    [C_ID .. 611] = "Larynx", -- Larynx
    [C_ID .. 612] = "Âme Égarée", -- Lost Soul
    [C_ID .. 613] = "Salière", -- 
    [C_ID .. 614] = "Hémoglobombes", -- Blood Bombs
    [C_ID .. 615] = "P'tit Prout", -- Lil Dumpy
    [C_ID .. 616] = "Piment Oiseau", -- Bird's Eye
    [C_ID .. 617] = "Magnétite", -- Lodestone
    [C_ID .. 618] = "Tomate Pourrie", -- Rotten Tomato
    [C_ID .. 619] = "Droit d'Aînesse", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Potage de Lentilles", -- Red Stew
    [C_ID .. 622] = "Genèse", -- Genesis
    [C_ID .. 623] = "Clé Aiguisée", -- Sharp Key
    [C_ID .. 624] = "Paquet d'Extension", -- Booster Pack
    [C_ID .. 625] = "Méga Champi", -- Mega Mush
    [C_ID .. 626] = "1er Morceau de Couteau", -- Knife Piece 1
    [C_ID .. 627] = "2è Morceau de Couteau", -- Knife Piece 2
    [C_ID .. 628] = "Acte de Décès", -- Death Certificate
    [C_ID .. 629] = "Robomouche", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Couteau de Boucher", -- Meat Cleaver
    [C_ID .. 632] = "Pendentif Maléfique", -- Evil Charm
    [C_ID .. 633] = "Dogma", -- Dogma
    [C_ID .. 634] = "Purgatoire", -- Purgatory
    [C_ID .. 635] = "Marionnette", -- Stitches
    [C_ID .. 636] = "Touche R", -- R Key
    [C_ID .. 637] = "Gouttes K.O.", -- Knockout Drops
    [C_ID .. 638] = "Gomme", -- Eraser
    [C_ID .. 639] = "Cœur Moisi", -- Yuck Heart
    [C_ID .. 640] = "Urne des Âmes", -- Urn of Souls
    [C_ID .. 641] = "Haqeldemah", -- Akeldama
    [C_ID .. 642] = "Peau de Chagrin", -- Magic Skin
    [C_ID .. 643] = "Révélation", -- Revelation
    [C_ID .. 644] = "Prix de Consolation", -- Consolation Prize
    [C_ID .. 645] = "P'tit Tératome", -- Tinytoma
    [C_ID .. 646] = "Bombes Sulfureuses", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volts", -- 4.5 Volt
    [C_ID .. 648] = "Broyeur de Pilules", -- 
    [C_ID .. 649] = "P'tite Prunelle", -- Fruity Plum
    [C_ID .. 650] = "Flute Prunelle", -- Plum Flute
    [C_ID .. 651] = "Star of Bethlehem", -- Star of Bethlehem
    [C_ID .. 652] = "Bébé Congelé", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "Doctorat Falsifié", -- False PHD
    [C_ID .. 655] = "Toupie", -- Spin to Win
    [C_ID .. 656] = "Damoclès", -- Damocles
    [C_ID .. 657] = "Vascularite", -- Vasculitis
    [C_ID .. 658] = "Cellule Géante", -- Giant Cell
    [C_ID .. 659] = "Tropicamide", -- Tropicamide
    [C_ID .. 660] = "Cartomancie", -- Card Reading
    [C_ID .. 661] = "Quintuplés", -- Quints
    [C_ID .. 662] = "Pacifisme", -- 
    [C_ID .. 663] = "Bec et Ongles", -- Tooth and Nail
    [C_ID .. 664] = "Goinfrerie", -- Binge Eater
    [C_ID .. 665] = "Œil de Guppy", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Gardien en Peluche", -- Strawman
    [C_ID .. 668] = "Lettre de Papa", -- Dad's Note
    [C_ID .. 669] = "Saucisson", -- Sausage
    [C_ID .. 670] = "Plus d'Options ?", -- Options?
    [C_ID .. 671] = "Cœur Confit", -- Candy Heart
    [C_ID .. 672] = "Une Livre de Chair", -- A Pound of Flesh
    [C_ID .. 673] = "Rédemption", -- Redemption
    [C_ID .. 674] = "Chaînes de l'Esprit", -- Spirit Shackles
    [C_ID .. 675] = "Orbe Fêlé", -- Cracked Orb
    [C_ID .. 676] = "Cœur Vide", -- Empty Heart
    [C_ID .. 677] = "Projection Astrale", -- Astral Projection
    [C_ID .. 678] = "Césarienne", -- C Section
    [C_ID .. 679] = "P'tit Abaddon", -- Lil Abaddon
    [C_ID .. 680] = "Tourista", -- Montezuma's Revenge
    [C_ID .. 681] = "P'tit Vortex", -- Lil Portal
    [C_ID .. 682] = "Ver de Nerf", -- Worm Friend
    [C_ID .. 683] = "Épines Osseuses", -- Bone Spurs
    [C_ID .. 684] = "Âme Affamée", -- Hungry Soul
    [C_ID .. 685] = "Bocal de Feux Follets", -- Jar of Wisps
    [C_ID .. 686] = "Pendentif des Âmes", -- Soul Locket
    [C_ID .. 687] = "Amis Imaginaires", -- Friend Finder
    [C_ID .. 688] = "Enfant Intérieur", -- Inner Child
    [C_ID .. 689] = "Couronne Corrompue", -- Glitched Crown
    [C_ID .. 690] = "Haricot Confit", -- Belly Jelly
    [C_ID .. 691] = "Orbe Sacré", -- Sacred Orb
    [C_ID .. 692] = "Pacte de Sang", -- Sanguine Bond
    [C_ID .. 693] = "La Nuée", -- The Swarm
    [C_ID .. 694] = "Brise-Cœur", -- Heartbreak
    [C_ID .. 695] = "Souffle de Sang", -- Bloody Gust
    [C_ID .. 696] = "Salvation", -- Salvation
    [C_ID .. 697] = "Jumeau Évanescent", -- Vanishing Twin
    [C_ID .. 698] = "Jumeaux Malicieux", -- Twisted Pair
    [C_ID .. 699] = "Rage d'Azazel", -- Azazel's Rage
    [C_ID .. 700] = "Résonance", -- Echo Chamber
    [C_ID .. 701] = "Tombeau d'Isaac", -- Isaac's Tomb
    [C_ID .. 702] = "Esprit Vengeur", -- Vengeful Spirit
    [C_ID .. 703] = "Ésaü Junior", -- Esau Jr.
    [C_ID .. 704] = "Frénésie", -- Berserk!
    [C_ID .. 705] = "Arts Obscurs", -- Dark Arts
    [C_ID .. 706] = "Abysse", -- Abyss
    [C_ID .. 707] = "Souper", -- Supper
    [C_ID .. 708] = "Agrafeuse", -- Stapler
    [C_ID .. 709] = "Suplex !", -- Suplex!
    [C_ID .. 710] = "Sac de Fabrication", -- Bag of Crafting
    [C_ID .. 711] = "Inversion", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Rappel", -- Recall
    [C_ID .. 715] = "Garder", -- Hold
    [C_ID .. 716] = "Bourse du Gardien", -- Keeper's Sack
    [C_ID .. 717] = "Amies du Gardien", -- Keeper's Kin
    [C_ID .. 718] = "Corde du Gardien", -- 
    [C_ID .. 719] = "Boîte du Gardien", -- Keeper's Box
    [C_ID .. 720] = "Bocal de N'Importe Quoi", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Dé Compteur", -- Spindown Dice
    [C_ID .. 724] = "Hypercoagulation", -- Hypercoagulation
    [C_ID .. 725] = "Intestin Irrité", -- IBS
    [C_ID .. 726] = "Hémoptysie", -- Hemoptysis
    [C_ID .. 727] = "Bombes Fantômes", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Décapitation", -- Decap Attack
    [C_ID .. 730] = "Œil de Verre", -- Glass Eye
    [C_ID .. 731] = "Orgelet", -- Stye
    [C_ID .. 732] = "Bague de Maman", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Pièce Avalée", -- Swallowed Penny
    [T_ID .. 2] = "Caca Pétrifié", -- Petrified Poop
    [T_ID .. 3] = "Pile AAA", -- AAA Battery
    [T_ID .. 4] = "Télécommande Cassée", -- Broken Remote
    [T_ID .. 5] = "Cœur Violet", -- Purple Heart
    [T_ID .. 6] = "Aimant Démagnétisé", -- Broken Magnet
    [T_ID .. 7] = "Perle de Rosaire", -- Rosary Bead
    [T_ID .. 8] = "Cartouche", -- Cartridge
    [T_ID .. 9] = "Ver Pulsant", -- Pulse Worm
    [T_ID .. 10] = "Ver Remuant", -- Wiggle Worm
    [T_ID .. 11] = "Ver Circulaire", -- Ring Worm
    [T_ID .. 12] = "Ver Plat", -- Flat Worm
    [T_ID .. 13] = "Bon d'Achat", -- Store Credit
    [T_ID .. 14] = "Callosités", -- Callus
    [T_ID .. 15] = "Caillou Porte-Bonheur", -- Lucky Rock
    [T_ID .. 16] = "Ongle de Pied de Maman", -- Mom's Toenail
    [T_ID .. 17] = "Noir à Lèvres", -- Black Lipstick
    [T_ID .. 18] = "Brochure Religieuse", -- Bible Tract
    [T_ID .. 19] = "Trombone", -- Paper Clip
    [T_ID .. 20] = "Patte de Singe", -- Monkey Paw
    [T_ID .. 21] = "Papier Mystérieux", -- Mysterious Paper
    [T_ID .. 22] = "Queue de Diablotin", -- Daemon's Tail
    [T_ID .. 23] = "Avis de Recherche", -- Missing Poster
    [T_ID .. 24] = "Pièce de Fesse", -- Butt Penny
    [T_ID .. 25] = "Chocolat Douteux", -- Mysterious Candy
    [T_ID .. 26] = "Ver Droit", -- Hook Worm
    [T_ID .. 27] = "Ver Long", -- Whip Worm
    [T_ID .. 28] = "Ânkh Brisée", -- Broken Ankh
    [T_ID .. 29] = "Tête de Poisson", -- Fish Head
    [T_ID .. 30] = "Conjonctivite", -- Pinky Eye
    [T_ID .. 31] = "Punaise", -- Push Pin
    [T_ID .. 32] = "Psilocybe Lancéolé", -- Liberty Cap
    [T_ID .. 33] = "Cordon Ombilical", -- Umbilical Cord
    [T_ID .. 34] = "Cœur d'Enfant", -- Child's Heart
    [T_ID .. 35] = "Corne Tordue", -- Curved Horn
    [T_ID .. 36] = "Clé Rouillée", -- Rusted Key
    [T_ID .. 37] = "Sabot de Chèvre", -- Goat Hoof
    [T_ID .. 38] = "Perle de Maman", -- Mom's Pearl
    [T_ID .. 39] = "Cancer", -- Cancer
    [T_ID .. 40] = "Lambeau de Tissu", -- Red Patch
    [T_ID .. 41] = "Allumette", -- Match Stick
    [T_ID .. 42] = "Orteil Porte-Bonheur", -- Lucky Toe
    [T_ID .. 43] = "Crâne Maudit", -- Cursed Skull
    [T_ID .. 44] = "Bouchon de Sécurité", -- Safety Cap
    [T_ID .. 45] = "As de Pique", -- Ace of Spades
    [T_ID .. 46] = "Fourchette d'Isaac", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "Page Déchirée", -- A Missing Page
    [T_ID .. 49] = "Pièce Sanglante", -- Bloody Penny
    [T_ID .. 50] = "Pièce Brûlée", -- Burnt Penny
    [T_ID .. 51] = "Pièce Plate", -- Flat Penny
    [T_ID .. 52] = "Pièce de Contrefaçon", -- Counterfeit Penny
    [T_ID .. 53] = "Tique", -- Tick
    [T_ID .. 54] = "Tête d'Isaac", -- Isaac's Head
    [T_ID .. 55] = "Foi de Marie", -- Maggy's Faith
    [T_ID .. 56] = "Langue de Judas", -- Judas' Tongue
    [T_ID .. 57] = "Âme de ???", -- ???'s Soul
    [T_ID .. 58] = "Mèche de Samson", -- Samson's Lock
    [T_ID .. 59] = "Œil de Caïn", -- Cain's Eye
    [T_ID .. 60] = "Serre de l'Oiseau d'Ève", -- Eve's Bird Foot
    [T_ID .. 61] = "Main Gauche", -- The Left Hand
    [T_ID .. 62] = "Caillou Étincelant", -- Shiny Rock
    [T_ID .. 63] = "Ciseaux à Bout Rond", -- Safety Scissors
    [T_ID .. 64] = "Ver Arc-en-Ciel", -- Rainbow Worm
    [T_ID .. 65] = "Ver Solitaire", -- Tape Worm
    [T_ID .. 66] = "Ver Fainéant", -- Lazy Worm
    [T_ID .. 67] = "Dé Fêlé", -- Cracked Dice
    [T_ID .. 68] = "Aimant au Néodyme", -- Super Magnet
    [T_ID .. 69] = "Positif Décoloré", -- Faded Polaroid
    [T_ID .. 70] = "Lente", -- Louse
    [T_ID .. 71] = "Vessie de Bob", -- Bob's Bladder
    [T_ID .. 72] = "Pile Bouton", -- Watch Battery
    [T_ID .. 73] = "Détonateur", -- Blasting Cap
    [T_ID .. 74] = "Détecteur de Métaux", -- Stud Finder
    [T_ID .. 75] = "404", -- Error
    [T_ID .. 76] = "Jeton de Poker", -- Poker Chip
    [T_ID .. 77] = "Cloque", -- Blister
    [T_ID .. 78] = "Grande Aiguille", -- Second Hand
    [T_ID .. 79] = "Histoire Sans Fin", -- Endless Nameless
    [T_ID .. 80] = "Plume Noire", -- Black Feather
    [T_ID .. 81] = "Rage Aveugle", -- Blind Rage
    [T_ID .. 82] = "Fer à Cheval Doré", -- Golden Horse Shoe
    [T_ID .. 83] = "Clé du Magasin", -- Store Key
    [T_ID .. 84] = "Côte d'Avarice", -- Rib of Greed
    [T_ID .. 85] = "Karma", -- Karma
    [T_ID .. 86] = "Petite Larve", -- Lil Larva
    [T_ID .. 87] = "Médaillon de Maman", -- Mom's Locket
    [T_ID .. 88] = "NON !", -- NO!
    [T_ID .. 89] = "Laisse Pour Enfants", -- Child Leash
    [T_ID .. 90] = "Bouchon Brun", -- Brown Cap
    [T_ID .. 91] = "Méconium", -- Meconium
    [T_ID .. 92] = "Couronne Fêlée", -- Cracked Crown
    [T_ID .. 93] = "Couche Usagée", -- Used Diaper
    [T_ID .. 94] = "Queue de Poisson", -- Fish Tail
    [T_ID .. 95] = "Dent Noircie", -- Black Tooth
    [T_ID .. 96] = "Ver d'Ouroboros", -- Ouroboros Worm
    [T_ID .. 97] = "Amygdale", -- Tonsil
    [T_ID .. 98] = "Crotte de Nez", -- Nose Goblin
    [T_ID .. 99] = "Balle Rebondissante", -- Super Ball
    [T_ID .. 100] = "Ampoule Allumée", -- Vibrant Bulb
    [T_ID .. 101] = "Ampoule Éteinte", -- Dim Bulb
    [T_ID .. 102] = "Carte Scindée", -- Fragmented Card
    [T_ID .. 103] = "Égalité !", -- Equality!
    [T_ID .. 104] = "Os de Poulet", -- Wish Bone
    [T_ID .. 105] = "Sac de Friandises", -- Bag Lunch
    [T_ID .. 106] = "Bouchon de Liège", -- Lost Cork
    [T_ID .. 107] = "Cœur de Corbeau", -- Crow Heart
    [T_ID .. 108] = "Noix", -- Walnut
    [T_ID .. 109] = "Ruban Adhésif", -- Duct Tape
    [T_ID .. 110] = "Pièce d'Argent", -- Silver Dollar
    [T_ID .. 111] = "Couronne Sanglante", -- Bloody Crown
    [T_ID .. 112] = "Microtransactions", -- Pay To Win
    [T_ID .. 113] = "Locuste de Guerre", -- Locust of War
    [T_ID .. 114] = "Locuste d'Épidémie", -- Locust of Pestilence
    [T_ID .. 115] = "Locuste de Famine", -- Locust of Famine
    [T_ID .. 116] = "Locuste de Mort", -- Locust of Death
    [T_ID .. 117] = "Locuste de Conquête", -- Locust of Conquest
    [T_ID .. 118] = "Aile de Chauve-Souris", -- Bat Wing
    [T_ID .. 119] = "Cellule Souche", -- Stem Cell
    [T_ID .. 120] = "Épingle à Cheveux", -- Hairpin
    [T_ID .. 121] = "Croix de Bois", -- Wooden Cross
    [T_ID .. 122] = "Plaquette de Beurre", -- Butter!
    [T_ID .. 123] = "Plume Angélique", -- Filigree Feather
    [T_ID .. 124] = "Cale-Porte", -- Door Stop
    [T_ID .. 125] = "Rallonge Électrique", -- Extension Cord
    [T_ID .. 126] = "Pièce Moisie", -- Rotten Penny
    [T_ID .. 127] = "P'tite Cuillère", -- Baby-Bender
    [T_ID .. 128] = "Os de Doigt", -- Finger Bone
    [T_ID .. 129] = "Boule de Mammouth", -- Jawbreaker
    [T_ID .. 130] = "Stylo Mâchouillé", -- Chewed Pen
    [T_ID .. 131] = "Pièce Bénie", -- Blessed Penny
    [T_ID .. 132] = "Seringue Cassée", -- Broken Syringe
    [T_ID .. 133] = "Pétard", -- Short Fuse
    [T_ID .. 134] = "Haricot Géant", -- Gigante Bean
    [T_ID .. 135] = "Briquet", -- A Lighter
    [T_ID .. 136] = "Cadenas Cassé", -- Broken Padlock
    [T_ID .. 137] = "Myosotis", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Larmulette", -- Teardrop Charm
    [T_ID .. 140] = "Pomme de Sodome", -- Apple of Sodom
    [T_ID .. 141] = "Berceuse Oubliée", -- Forgotten Lullaby
    [T_ID .. 142] = "Foi de Béthanie", -- Beth's Faith
    [T_ID .. 143] = "Condensateur", -- Old Capacitor
    [T_ID .. 144] = "Parasite Cérébral", -- Brain Worm
    [T_ID .. 145] = "Perfection", -- Perfection
    [T_ID .. 146] = "Couronne du Diable", -- Devil's Crown
    [T_ID .. 147] = "Pièce Électrisée", -- Charged Penny
    [T_ID .. 148] = "Collier d'Amitié", -- Friendship Necklace
    [T_ID .. 149] = "Bouton Rouge", -- Panic Button
    [T_ID .. 150] = "Clé Bleue", -- Blue Key
    [T_ID .. 151] = "Lime Plate", -- Flat File
    [T_ID .. 152] = "Lentille de Télescope", -- Telescope Lens
    [T_ID .. 153] = "Mèche de Maman", -- Mom's Lock
    [T_ID .. 154] = "Sac de Dés", -- Dice Bag
    [T_ID .. 155] = "Couronne Sacrée", -- Holy Crown
    [T_ID .. 156] = "Bisou de Maman", -- Mother's Kiss
    [T_ID .. 157] = "Carte Déchirée", -- Torn Card
    [T_ID .. 158] = "Poche Trouée", -- Torn Pocket
    [T_ID .. 159] = "Clé Dorée", -- Gilded Key
    [T_ID .. 160] = "Bourse Trèfle", -- Lucky Sack
    [T_ID .. 161] = "Couronne Impure", -- Wicked Crown
    [T_ID .. 162] = "Corne d'Azazel", -- Azazel's Stump
    [T_ID .. 163] = "Colombin", -- Dingle Berry
    [T_ID .. 164] = "Amorces", -- Ring Cap
    [T_ID .. 165] = "Ah Non !", -- Nuh Uh!
    [T_ID .. 166] = "Pâte à Modeler", -- Modeling Clay
    [T_ID .. 167] = "Os Poli", -- Polished Bone
    [T_ID .. 168] = "Cœur Creux", -- Hollow Heart
    [T_ID .. 169] = "Dessin d'Enfant", -- Kid's Drawing
    [T_ID .. 170] = "Clé de Cristal", -- Crystal Key
    [T_ID .. 171] = "Aubaine du Gardien", -- Keeper's Bargain
    [T_ID .. 172] = "Pièce Maudite", -- Cursed Penny
    [T_ID .. 173] = "Ton Âme", -- Your Soul
    [T_ID .. 174] = "Chiffre Magnétique", -- Number Magnet
    [T_ID .. 175] = "Étrange Clé", -- Strange Key
    [T_ID .. 176] = "P'tit Pâté", -- Lil Clot
    [T_ID .. 177] = "Tatouage Temporaire", -- Temporary Tattoo
    [T_ID .. 178] = "Explosifs Avalés", -- Swallowed M80
    [T_ID .. 179] = "Télécommande Radio", -- RC Remote
    [T_ID .. 180] = "Âme Retrouvée", -- Found Soul
    [T_ID .. 181] = "Pack d'Extension", -- Expansion Pack
    [T_ID .. 182] = "Essence de Béthanie", -- Beth's Essence
    [T_ID .. 183] = "Les Jumeaux", -- The Twins
    [T_ID .. 184] = "Actes d'Adoption", -- Adoption Papers
    [T_ID .. 185] = "Patte de Grillon", -- Cricket Leg
    [T_ID .. 186] = "Le Meilleur Ami d'Apollyon", -- Apollyon's Best Friend
    [T_ID .. 187] = "Lunettes Cassées", -- Broken Glasses
    [T_ID .. 188] = "Glaçon", -- Ice Cube
    [T_ID .. 189] = "Sigil de Baphomet", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Le Mat", -- 0 - The Fool
    [Card_ID .. 2] = "I - Le Bateleur", -- I - The Magician
    [Card_ID .. 3] = "II - La Papesse", -- II - The High Priestess
    [Card_ID .. 4] = "III - L'Impératrice", -- III - The Empress
    [Card_ID .. 5] = "IV - L'Empereur", -- IV - The Emperor
    [Card_ID .. 6] = "V - Le Pape", -- V - The Hierophant
    [Card_ID .. 7] = "VI - L'Amoureux", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Le Chariot", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - La Justice", -- VIII - Justice
    [Card_ID .. 10] = "IX - L'Ermite", -- IX - The Hermit
    [Card_ID .. 11] = "X - La Roue de Fortune", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - La Force", -- XI - Strength
    [Card_ID .. 13] = "XII - Le Pendu", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - La Mort", -- XIII - Death
    [Card_ID .. 15] = "XIV - Tempérance", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Le Diable", -- XV - The Devil
    [Card_ID .. 17] = "XVI - La Maison Dieu", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - L'Étoile", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - La Lune", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Le Soleil", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Le Jugement", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Le Monde", -- XXI - The World
    [Card_ID .. 23] = "2 de Trèfle", -- 2 of Clubs
    [Card_ID .. 24] = "2 de Carreau", -- 2 of Diamonds
    [Card_ID .. 25] = "2 de Pique", -- 2 of Spades
    [Card_ID .. 26] = "2 de Cœur", -- 2 of Hearts
    [Card_ID .. 27] = "As de Trèfle", -- Ace of Clubs
    [Card_ID .. 28] = "As de Carreau", -- Ace of Diamonds
    [Card_ID .. 29] = "As de Pique", -- Ace of Spades
    [Card_ID .. 30] = "As de Cœur", -- Ace of Hearts
    [Card_ID .. 31] = "Joker", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Rune Vierge", -- Blank Rune
    [Card_ID .. 41] = "Rune Noire", -- Black Rune
    [Card_ID .. 42] = "Carte Chaos", -- Chaos Card
    [Card_ID .. 43] = "Carte de Crédit", -- Credit Card
    [Card_ID .. 44] = "Carte des Règles", -- Rules Card
    [Card_ID .. 45] = "Une Carte Limite Limite", -- A Card Against Humanity
    [Card_ID .. 46] = "Roi Suicidaire", -- Suicide King
    [Card_ID .. 47] = "Carte Chance", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "Carte ?", -- ? Card
    [Card_ID .. 49] = "Fragment de Dé", -- Dice Shard
    [Card_ID .. 50] = "Appel d'Urgence", -- Emergency Contact
    [Card_ID .. 51] = "Carte Sacrée", -- Holy Card
    [Card_ID .. 52] = "Croissance Colossale", -- Huge Growth
    [Card_ID .. 53] = "Rappel Ancestral", -- Ancient Recall
    [Card_ID .. 54] = "Marche Temporelle", -- Era Walk
    [Card_ID .. 55] = "Fragment de Rune", -- Rune Shard
    [Card_ID .. 56] = "0 - Le Mat ?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Le Bateleur ?", -- I - The Magician?
    [Card_ID .. 58] = "II - La Papesse ?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - L'Impératrice ?", -- III - The Empress?
    [Card_ID .. 60] = "IV - L'Empereur ?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Le Pape ?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - L'Amoureux ?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Le Chariot ?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - La Justice ?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - L'Ermite ?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - La Roue de Fortune ?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - La Force ?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Le Pendu ?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - La Mort ?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Tempérance ?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Le Diable ?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - La Maison Dieu ?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - L'Étoile ?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - La Lune ?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Le Soleil ?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Le Jugement ?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Le Monde ?", -- XXI - The World?
    [Card_ID .. 78] = "Clé Brisée", -- Cracked Key
    [Card_ID .. 79] = "Dame de Cœur", -- Queen of Hearts
    [Card_ID .. 80] = "Dernière Carte", -- Wild Card
    [Card_ID .. 81] = "Âme d'Isaac", -- Soul of Isaac
    [Card_ID .. 82] = "Âme de Marie", -- Soul of Magdalene
    [Card_ID .. 83] = "Âme de Caïn", -- Soul of Cain
    [Card_ID .. 84] = "Âme de Judas", -- Soul of Judas
    [Card_ID .. 85] = "Âme de ???", -- Soul of ???
    [Card_ID .. 86] = "Âme d'Ève", -- Soul of Eve
    [Card_ID .. 87] = "Âme de Samson", -- Soul of Samson
    [Card_ID .. 88] = "Âme d'Azazel", -- Soul of Azazel
    [Card_ID .. 89] = "Âme de Lazare", -- Soul of Lazarus
    [Card_ID .. 90] = "Âme d'Éden", -- Soul of Eden
    [Card_ID .. 91] = "Âme de l'Égaré", -- Soul of the Lost
    [Card_ID .. 92] = "Âme de Lilith", -- Soul of Lilith
    [Card_ID .. 93] = "Âme du Gardien", -- Soul of the Keeper
    [Card_ID .. 94] = "Âme d'Apollyon", -- Soul of Apollyon
    [Card_ID .. 95] = "Âme du Délaissé", -- Soul of the Forgotten
    [Card_ID .. 96] = "Âme de Béthanie", -- Soul of Bethany
    [Card_ID .. 97] = "Âme de Jacob & Ésaü", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "Flatulences", -- Bad Gas
    [Pill_ID .. 2] = "Coup dur", -- Bad Trip
    [Pill_ID .. 3] = "Digoxine", -- Balls of Steel
    [Pill_ID .. 4] = "Bombes à la clé", -- Bombs are Key
    [Pill_ID .. 5] = "Diarrhée explosive", -- Explosive Diarrhea
    [Pill_ID .. 6] = "Soin complet", -- Full Health
    [Pill_ID .. 7] = "PV diminués", -- Health Down
    [Pill_ID .. 8] = "PV augmentés", -- Health Up
    [Pill_ID .. 9] = "J'ai trouvé une pilule !", -- I Found Pills
    [Pill_ID .. 10] = "Puberté", -- Puberty
    [Pill_ID .. 11] = "Jolie mouche", -- Pretty Fly
    [Pill_ID .. 12] = "Portée diminuée", -- Range Down
    [Pill_ID .. 13] = "Portée augmentée", -- Range Up
    [Pill_ID .. 14] = "Vitesse diminuée", -- Speed Down
    [Pill_ID .. 15] = "Vitesse augmentée", -- Speed Up
    [Pill_ID .. 16] = "Débit diminué", -- Tears Down
    [Pill_ID .. 17] = "Débit augmenté", -- Tears Up
    [Pill_ID .. 18] = "Chance diminuée", -- Luck Down
    [Pill_ID .. 19] = "Chance augmentée", -- Luck Up
    [Pill_ID .. 20] = "Télépilule", -- Telepills
    [Pill_ID .. 21] = "Survolté !", -- 48 Hour Energy!
    [Pill_ID .. 22] = "Hématémèse", -- Hematemesis
    [Pill_ID .. 23] = "Paralysie", -- Paralysis
    [Pill_ID .. 24] = "Sésame, ouvre-toi !", -- I can see forever!
    [Pill_ID .. 25] = "Phéromones", -- Pheromones
    [Pill_ID .. 26] = "Amnésie", -- Amnesia
    [Pill_ID .. 27] = "Petite fuite...", -- Lemon Party
    [Pill_ID .. 28] = "C'est louche...", -- R U A Wizard?
    [Pill_ID .. 29] = "Anesthésie", -- Percs!
    [Pill_ID .. 30] = "Accro !", -- Addicted!
    [Pill_ID .. 31] = "Re-lax", -- Re-Lax
    [Pill_ID .. 32] = "???", -- ???
    [Pill_ID .. 33] = "L'une te fait grandir...", -- One makes you larger
    [Pill_ID .. 34] = "...L'une te rapetisse", -- One makes you small
    [Pill_ID .. 35] = "Infesté !", -- Infested!
    [Pill_ID .. 36] = "Infesté ?", -- Infested?
    [Pill_ID .. 37] = "Vitamines !", -- Power Pill!
    [Pill_ID .. 38] = "Vision Rétro", -- Retro Vision
    [Pill_ID .. 39] = "Amis pour la vie !", -- Friends Till The End!
    [Pill_ID .. 40] = "X-Lax", -- X-Lax
    [Pill_ID .. 41] = "C'est pas normal, ça...", -- Something's wrong...
    [Pill_ID .. 42] = "Somnolence", -- I'm Drowsy...
    [Pill_ID .. 43] = "Gonflé à bloc !!!", -- I'm Excited!!
    [Pill_ID .. 44] = "Gloups !", -- Gulp!
    [Pill_ID .. 45] = "Bleuargh !", -- Horf!
    [Pill_ID .. 46] = "Morphine", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "Bleurp !", -- Vurp!
    [Pill_ID .. 48] = "Vitesse des tirs diminuée", -- Shot speed Down
    [Pill_ID .. 49] = "Vitesse des tirs augmentée ", -- Shot speed Up
    [Pill_ID .. 50] = "Pilule expérimentale", -- Experimental Pill
    [Pill_ID .. 9999] = "Pilule dorée", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])