local languageCode = "it"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "La Cipolla Triste", -- The Sad Onion
    [C_ID .. 2] = "Il Terzo Occhio", -- The Inner Eye
    [C_ID .. 3] = "Piega-cucchiai", -- Spoon Bender
    [C_ID .. 4] = "Testa di Cricket", -- Cricket's Head
    [C_ID .. 5] = "Il Mio Riflesso", -- My Reflection
    [C_ID .. 6] = "La Numero Uno", -- Number One
    [C_ID .. 7] = "Sangue Del Martire", -- Blood of the Martyr
    [C_ID .. 8] = "Fratello Bobby", -- Brother Bobby
    [C_ID .. 9] = "Scatolo", -- Skatole
    [C_ID .. 10] = "Aureola Di Mosche", -- Halo of Flies
    [C_ID .. 11] = "1up!", -- 1up!
    [C_ID .. 12] = "Fungo Magico", -- Magic Mushroom
    [C_ID .. 13] = "Il Virus", -- The Virus
    [C_ID .. 14] = "Iniezione di Ferocia", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Fegato Crudo", -- Raw Liver
    [C_ID .. 17] = "Passepartout", -- Skeleton Key
    [C_ID .. 18] = "Un Dollaro", -- A Dollar
    [C_ID .. 19] = "Bum!", -- Boom!
    [C_ID .. 20] = "Trascendenza", -- Transcendence
    [C_ID .. 21] = "La Bussola", -- The Compass
    [C_ID .. 22] = "Pranzo", -- Lunch
    [C_ID .. 23] = "Cena", -- Dinner
    [C_ID .. 24] = "Dessert", -- Dessert
    [C_ID .. 25] = "Colazione", -- Breakfast
    [C_ID .. 26] = "Carne Marcia", -- Rotten Meat
    [C_ID .. 27] = "Mestolo", -- Wooden Spoon
    [C_ID .. 28] = "La Cintura", -- The Belt
    [C_ID .. 29] = "Mutande di Mamma", -- Mom's Underwear
    [C_ID .. 30] = "Tacchi di Mamma", -- Mom's Heels
    [C_ID .. 31] = "Rossetto di Mamma", -- Mom's Lipstick
    [C_ID .. 32] = "Gruccia di Ferro", -- Wire Coat Hanger
    [C_ID .. 33] = "La Bibbia", -- The Bible
    [C_ID .. 34] = "Il Libro di Belial", -- The Book of Belial
    [C_ID .. 35] = "Il Necronomicon", -- The Necronomicon
    [C_ID .. 36] = "La Cacca", -- The Poop
    [C_ID .. 37] = "Sig. Bum", -- Mr. Boom
    [C_ID .. 38] = "Testa di Tammy", -- Tammy's Head
    [C_ID .. 39] = "Reggiseno di Mamma", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Assorbente di Mamma", -- Mom's Pad
    [C_ID .. 42] = "Testa Marcia di Bob", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teletrasporto!", -- Teleport!
    [C_ID .. 45] = "Cuore Gustoso", -- Yum Heart
    [C_ID .. 46] = "Piede Fortunato", -- Lucky Foot
    [C_ID .. 47] = "Telecomando del Dottore", -- Doctor's Remote
    [C_ID .. 48] = "Freccia di Cupido", -- Cupid's Arrow
    [C_ID .. 49] = "Shoop da Whoop!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagramma", -- Pentagram
    [C_ID .. 52] = "Dr. Fetus", -- Dr. Fetus
    [C_ID .. 53] = "Magneto", -- Magneto
    [C_ID .. 54] = "Mappa del Tesoro", -- Treasure Map
    [C_ID .. 55] = "Occhio di Mamma", -- Mom's Eye
    [C_ID .. 56] = "Limonata Accidentale", -- Lemon Mishap
    [C_ID .. 57] = "Ammiratore Segreto", -- Distant Admiration
    [C_ID .. 58] = "Libro delle Ombre", -- Book of Shadows
    [C_ID .. 59] = "Il Libro di Belial", -- The Book of Belial
    [C_ID .. 60] = "La Scala", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Fascino del Vampiro", -- Charm of the Vampire
    [C_ID .. 63] = "La Pila", -- The Battery
    [C_ID .. 64] = "Saldi di Steam", -- Steam Sale
    [C_ID .. 65] = "Ricette dell'Anarchico", -- Anarchist Cookbook
    [C_ID .. 66] = "La Clessidra", -- The Hourglass
    [C_ID .. 67] = "Sorella Maggy", -- Sister Maggy
    [C_ID .. 68] = "Tecnologia", -- Technology
    [C_ID .. 69] = "Latte al Cioccolato", -- Chocolate Milk
    [C_ID .. 70] = "Ormoni Della Crescita", -- Growth Hormones
    [C_ID .. 71] = "Mini Fungo", -- Mini Mush
    [C_ID .. 72] = "Rosario", -- Rosary
    [C_ID .. 73] = "Cubo di Carne", -- Cube of Meat
    [C_ID .. 74] = "Un Quarto", -- A Quarter
    [C_ID .. 75] = "Dottorato", -- PHD
    [C_ID .. 76] = "Vista a Raggi-X", -- X-Ray Vision
    [C_ID .. 77] = "Il mio Piccolo Unicorno", -- My Little Unicorn
    [C_ID .. 78] = "Libro dell'Apocalisse", -- Book of Revelations
    [C_ID .. 79] = "Il Marchio", -- The Mark
    [C_ID .. 80] = "Il Patto", -- The Pact
    [C_ID .. 81] = "Gatto Morto", -- Dead Cat
    [C_ID .. 82] = "Signore dell'Abisso", -- Lord of the Pit
    [C_ID .. 83] = "Il Chiodo", -- The Nail
    [C_ID .. 84] = "Scaviamo più a Fondo!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Mazzo di Carte", -- Deck of Cards
    [C_ID .. 86] = "Dente di Monstro", -- Monstro's Tooth
    [C_ID .. 87] = "Corna di Loki", -- Loki's Horns
    [C_ID .. 88] = "Cicciottella", -- Little Chubby
    [C_ID .. 89] = "Morso di Ragno", -- Spider Bite
    [C_ID .. 90] = "La Pietruzza", -- The Small Rock
    [C_ID .. 91] = "Casco da Minatore", -- Spelunker Hat
    [C_ID .. 92] = "Super Cerotto", -- Super Bandage
    [C_ID .. 93] = "Il Gamekid", -- The Gamekid
    [C_ID .. 94] = "Sacco di Penny", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Bebè", -- Robo-Baby
    [C_ID .. 96] = "Piccola C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "Il Libro del Peccato", -- The Book of Sin
    [C_ID .. 98] = "La Reliquia", -- The Relic
    [C_ID .. 99] = "Piccolo Gish", -- Little Gish
    [C_ID .. 100] = "Piccolo Steven", -- Little Steven
    [C_ID .. 101] = "L'Aureola", -- The Halo
    [C_ID .. 102] = "Boccetta di Mamma", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Il Raffreddore", -- The Common Cold
    [C_ID .. 104] = "Il Parassita", -- The Parasite
    [C_ID .. 105] = "Il D6", -- The D6
    [C_ID .. 106] = "Sig. Mega", -- Mr. Mega
    [C_ID .. 107] = "Forbici Seghettate", -- The Pinking Shears
    [C_ID .. 108] = "L'Ostia", -- The Wafer
    [C_ID .. 109] = "Soldi = Forza", -- Money = Power
    [C_ID .. 110] = "Lentine di Mamma", -- Mom's Contacts
    [C_ID .. 111] = "Il Fagiolo", -- The Bean
    [C_ID .. 112] = "Angelo Custode", -- Guardian Angel
    [C_ID .. 113] = "Bebè Demone", -- Demon Baby
    [C_ID .. 114] = "Coltello di Mamma", -- Mom's Knife
    [C_ID .. 115] = "Tavola Ouija", -- Ouija Board
    [C_ID .. 116] = "9 Volt", -- 9 Volt
    [C_ID .. 117] = "Uccello Morto", -- Dead Bird
    [C_ID .. 118] = "Zolfo Fuso", -- Brimstone
    [C_ID .. 119] = "Sacca di sangue", -- Blood Bag
    [C_ID .. 120] = "Buffungo (Piccolo)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Buffungo (Grande)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Meretrice di Babilonia", -- Whore of Babylon
    [C_ID .. 123] = "Manuale dei Mostri", -- Monster Manual
    [C_ID .. 124] = "Pergamene del Mar Morto", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bomba", -- Bobby-Bomb
    [C_ID .. 126] = "Lametta", -- Razor Blade
    [C_ID .. 127] = "NonTiRicordarDiMe", -- Forget Me Now
    [C_ID .. 128] = "Forever Alone", -- Forever Alone
    [C_ID .. 129] = "Secchio di Lardo", -- Bucket of Lard
    [C_ID .. 130] = "Un Pony", -- A Pony
    [C_ID .. 131] = "Sacco di Bombe", -- Bomb Bag
    [C_ID .. 132] = "Un Pezzo di Carbone", -- A Lump of Coal
    [C_ID .. 133] = "Zampa di Guppy", -- Guppy's Paw
    [C_ID .. 134] = "Coda di Guppy", -- Guppy's Tail
    [C_ID .. 135] = "Flebo", -- IV Bag
    [C_ID .. 136] = "Amico del Cuore", -- Best Friend
    [C_ID .. 137] = "Detonatore", -- Remote Detonator
    [C_ID .. 138] = "Stimmate", -- Stigmata
    [C_ID .. 139] = "Borsetta di Mamma", -- Mom's Purse
    [C_ID .. 140] = "Maledizione di Bob", -- Bob's Curse
    [C_ID .. 141] = "Reginello", -- Pageant Boy
    [C_ID .. 142] = "Scapolare", -- Scapular
    [C_ID .. 143] = "Speed Ball", -- Speed Ball
    [C_ID .. 144] = "Amico Scrocco", -- Bum Friend
    [C_ID .. 145] = "Testa di Guppy", -- Guppy's Head
    [C_ID .. 146] = "Santino", -- Prayer Card
    [C_ID .. 147] = "Piccone Minatorio", -- Notched Axe
    [C_ID .. 148] = "Infestazione", -- Infestation
    [C_ID .. 149] = "Ipecac", -- Ipecac
    [C_ID .. 150] = "Amor Duro", -- Tough Love
    [C_ID .. 151] = "Mosca al Naso", -- The Mulligan
    [C_ID .. 152] = "Tecnologia 2", -- Technology 2
    [C_ID .. 153] = "Ragno Mutante", -- Mutant Spider
    [C_ID .. 154] = "Esfoliazione Chimica", -- Chemical Peel
    [C_ID .. 155] = "Il Guardone", -- The Peeper
    [C_ID .. 156] = "Soggolo", -- Habit
    [C_ID .. 157] = "Furia Sanguinolenta", -- Bloody Lust
    [C_ID .. 158] = "Sfera di Cristallo", -- Crystal Ball
    [C_ID .. 159] = "Spirito della Notte", -- Spirit of the Night
    [C_ID .. 160] = "Apriti Cielo", -- Crack the Sky
    [C_ID .. 161] = "Ankh", -- Ankh
    [C_ID .. 162] = "Croce Celtica", -- Celtic Cross
    [C_ID .. 163] = "Bebè Fantasma", -- Ghost Baby
    [C_ID .. 164] = "La Candela", -- The Candle
    [C_ID .. 165] = "Gatto a Nove Code", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Bebè Arlecchino", -- Harlequin Baby
    [C_ID .. 168] = "Epic Fetus", -- Epic Fetus
    [C_ID .. 169] = "Polifemo", -- Polyphemus
    [C_ID .. 170] = "Papà Gambalunga", -- Daddy Longlegs
    [C_ID .. 171] = "Chiappe Ragnesche", -- Spider Butt
    [C_ID .. 172] = "Lama Sacrificale", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitra", -- Mitre
    [C_ID .. 174] = "Bimbo Arcobaleno", -- Rainbow Baby
    [C_ID .. 175] = "Chiave di Papà", -- Dad's Key
    [C_ID .. 176] = "Cellule Staminali", -- Stem Cells
    [C_ID .. 177] = "Slot Portatile", -- Portable Slot
    [C_ID .. 178] = "Acqua Santa", -- Holy Water
    [C_ID .. 179] = "Destino", -- Fate
    [C_ID .. 180] = "Il Fagiolo Nero", -- The Black Bean
    [C_ID .. 181] = "Pony Bianco", -- White Pony
    [C_ID .. 182] = "Sacro Cuore", -- Sacred Heart
    [C_ID .. 183] = "Stuzzicadenti", -- Tooth Picks
    [C_ID .. 184] = "Sacro Graal", -- Holy Grail
    [C_ID .. 185] = "Colomba Morta", -- Dead Dove
    [C_ID .. 186] = "Eredità di Sangue", -- Blood Rights
    [C_ID .. 187] = "Palla di Pelo di Guppy", -- Guppy's Hairball
    [C_ID .. 188] = "Abele", -- Abel
    [C_ID .. 189] = "Super Fan di SMB", -- SMB Super Fan
    [C_ID .. 190] = "Bombarolo", -- Pyro
    [C_ID .. 191] = "Banconota da 3 Dollari", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepatia per Negati", -- Telepathy for Dummies
    [C_ID .. 193] = "CARNE!", -- MEAT!
    [C_ID .. 194] = "Palla Magica", -- Magic 8 Ball
    [C_ID .. 195] = "Borsellino di Mamma", -- Mom's Coin Purse
    [C_ID .. 196] = "Anti-stress", -- Squeezy
    [C_ID .. 197] = "Succhino di Cristo", -- Jesus Juice
    [C_ID .. 198] = "Scatola", -- Box
    [C_ID .. 199] = "Chiave di Mamma", -- Mom's Key
    [C_ID .. 200] = "Ombretto di Mamma", -- Mom's Eyeshadow
    [C_ID .. 201] = "Lingotto di Ferro", -- Iron Bar
    [C_ID .. 202] = "Tocco di Mida", -- Midas' Touch
    [C_ID .. 203] = "Offerta Imperdibile", -- Humbleing Bundle
    [C_ID .. 204] = "Marsupio", -- Fanny Pack
    [C_ID .. 205] = "Presa Diretta", -- Sharp Plug
    [C_ID .. 206] = "Ghigliottina", -- Guillotine
    [C_ID .. 207] = "Palla di Cerotti", -- Ball of Bandages
    [C_ID .. 208] = "Cintura del Campione", -- Champion Belt
    [C_ID .. 209] = "Bombe Popò", -- Butt Bombs
    [C_ID .. 210] = "Foglia Mangiucchiata", -- Gnawed Leaf
    [C_ID .. 211] = "Bimboragno", -- Spiderbaby
    [C_ID .. 212] = "Collare di Guppy", -- Guppy's Collar
    [C_ID .. 213] = "Lentina Persa", -- Lost Contact
    [C_ID .. 214] = "Anemia", -- Anemic
    [C_ID .. 215] = "Testa di Capra", -- Goat Head
    [C_ID .. 216] = "Vesti Cerimoniali", -- Ceremonial Robes
    [C_ID .. 217] = "Parrucca di Mamma", -- Mom's Wig
    [C_ID .. 218] = "Placenta", -- Placenta
    [C_ID .. 219] = "Cerotto Vecchio", -- Old Bandage
    [C_ID .. 220] = "Bombe Tristi", -- Sad Bombs
    [C_ID .. 221] = "Mastice", -- Rubber Cement
    [C_ID .. 222] = "Anti-Gravità", -- Anti-Gravity
    [C_ID .. 223] = "Piromane", -- Pyromaniac
    [C_ID .. 224] = "Corpo di Cricket", -- Cricket's Body
    [C_ID .. 225] = "Latex", -- Gimpy
    [C_ID .. 226] = "Loto Nero", -- Black Lotus
    [C_ID .. 227] = "Salvadanaio", -- Piggy Bank
    [C_ID .. 228] = "Profumo di Mamma", -- Mom's Perfume
    [C_ID .. 229] = "Polmone di Monstro", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Palla di Catrame", -- Ball of Tar
    [C_ID .. 232] = "Cipollotto", -- Stop Watch
    [C_ID .. 233] = "Pianetino", -- Tiny Planet
    [C_ID .. 234] = "Infestazione 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "Tocco Mortale", -- Death's Touch
    [C_ID .. 238] = "Pezzo di Chiave 1", -- Key Piece 1
    [C_ID .. 239] = "Pezzo di Chiave 2", -- Key Piece 2
    [C_ID .. 240] = "Trattamento Sperimentale", -- Experimental Treatment
    [C_ID .. 241] = "Contratto con gli Abissi", -- Contract from Below
    [C_ID .. 242] = "Infamia", -- Infamy
    [C_ID .. 243] = "Scutum Fidei", -- Trinity Shield
    [C_ID .. 244] = "Tecn. 0.5", -- Tech.5
    [C_ID .. 245] = "Dieci Decimi", -- 20/20
    [C_ID .. 246] = "Mappa Blu", -- Blue Map
    [C_ID .. 247] = "AMICI PER LA PELLE!", -- BFFS!
    [C_ID .. 248] = "Mente Alveare", -- Hive Mind
    [C_ID .. 249] = "Ci sono alternative", -- There's Options
    [C_ID .. 250] = "Bombe 2x1", -- Bogo Bombs
    [C_ID .. 251] = "Mazzo Introduttivo", -- Starter Deck
    [C_ID .. 252] = "Portapillole", -- Little Baggy
    [C_ID .. 253] = "Scabbia Magica", -- Magic Scab
    [C_ID .. 254] = "Grumo di Sangue", -- Blood Clot
    [C_ID .. 255] = "Vite", -- Screw
    [C_ID .. 256] = "Bombe Incendiarie", -- Hot Bombs
    [C_ID .. 257] = "Mente in Fiamme", -- Fire Mind
    [C_ID .. 258] = "Missing No.", -- Missing No.
    [C_ID .. 259] = "Materia Oscura", -- Dark Matter
    [C_ID .. 260] = "Candela Nera", -- Black Candle
    [C_ID .. 261] = "Proptosi", -- Proptosis
    [C_ID .. 262] = "Pagina Mancante 2", -- Missing Page 2
    [C_ID .. 263] = "Runa Limpida", -- Clear Rune
    [C_ID .. 264] = "Moscastuta", -- Smart Fly
    [C_ID .. 265] = "Bebè Asciutto", -- Dry Baby
    [C_ID .. 266] = "Sacca Colante", -- Juicy Sack
    [C_ID .. 267] = "Robo-Bebè 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Bebè Marcio", -- Rotten Baby
    [C_ID .. 269] = "Bebè Decapitato", -- Headless Baby
    [C_ID .. 270] = "Sanguisuga", -- Leech
    [C_ID .. 271] = "Sacco delle Meraviglie", -- Mystery Sack
    [C_ID .. 272] = "BMF", -- BBF
    [C_ID .. 273] = "Cervello di Bob", -- Bob's Brain
    [C_ID .. 274] = "Scudiero", -- Best Bud
    [C_ID .. 275] = "Mini Zolfo Fuso", -- Lil Brimstone
    [C_ID .. 276] = "Cuore di Isaac", -- Isaac's Heart
    [C_ID .. 277] = "Mini Tormento", -- Lil Haunt
    [C_ID .. 278] = "Scroccoscuro", -- Dark Bum
    [C_ID .. 279] = "Grande Fan", -- Big Fan
    [C_ID .. 280] = "Sorellina Gambalunga", -- Sissy Longlegs
    [C_ID .. 281] = "Sacco da Boxe", -- Punching Bag
    [C_ID .. 282] = "Come Saltare", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Carta Bianca", -- Blank Card
    [C_ID .. 287] = "Libro dei Segreti", -- Book of Secrets
    [C_ID .. 288] = "Scatola di Ragni", -- Box of Spiders
    [C_ID .. 289] = "Candela Rossa", -- Red Candle
    [C_ID .. 290] = "La Giara di Vetro", -- The Jar
    [C_ID .. 291] = "Sciacquone!", -- Flush!
    [C_ID .. 292] = "Bibbia Satanica", -- Satanic Bible
    [C_ID .. 293] = "Testa di Krampus", -- Head of Krampus
    [C_ID .. 294] = "Fagiolo di Lima", -- Butter Bean
    [C_ID .. 295] = "Dita Magiche", -- Magic Fingers
    [C_ID .. 296] = "Convertitore", -- Converter
    [C_ID .. 297] = "Scrigno di Pandora", -- Pandora's Box
    [C_ID .. 298] = "Moncherino di Unicorno", -- Unicorn Stump
    [C_ID .. 299] = "Toro", -- Taurus
    [C_ID .. 300] = "Ariete", -- Aries
    [C_ID .. 301] = "Cancro", -- Cancer
    [C_ID .. 302] = "Leone", -- Leo
    [C_ID .. 303] = "Vergine", -- Virgo
    [C_ID .. 304] = "Bilancia", -- Libra
    [C_ID .. 305] = "Scorpione", -- Scorpio
    [C_ID .. 306] = "Sagittario", -- Sagittarius
    [C_ID .. 307] = "Capricorno", -- Capricorn
    [C_ID .. 308] = "Acquario", -- Aquarius
    [C_ID .. 309] = "Pesci", -- Pisces
    [C_ID .. 310] = "Mascara di Eva", -- Eve's Mascara
    [C_ID .. 311] = "Ombra di Giuda", -- Judas' Shadow
    [C_ID .. 312] = "Fiocco di Madda", -- Maggy's Bow
    [C_ID .. 313] = "Manto Sacro", -- Holy Mantle
    [C_ID .. 314] = "Coscione", -- Thunder Thighs
    [C_ID .. 315] = "Calamita Strana", -- Strange Attractor
    [C_ID .. 316] = "Occhio Maledetto", -- Cursed Eye
    [C_ID .. 317] = "liquame Misterioso", -- Mysterious Liquid
    [C_ID .. 318] = "Gemelli", -- Gemini
    [C_ID .. 319] = "L'Altro Occhio di Caino", -- Cain's Other Eye
    [C_ID .. 320] = "L'Unico Amico di ???", -- ???'s Only Friend
    [C_ID .. 321] = "Catene di Sansone", -- Samson's Chains
    [C_ID .. 322] = "Bebè Scemotto", -- Mongo Baby
    [C_ID .. 323] = "Lacrime di Isaac", -- Isaac's Tears
    [C_ID .. 324] = "Indefinito", -- Undefined
    [C_ID .. 325] = "Forbici", -- Scissors
    [C_ID .. 326] = "Alito di Vita", -- Breath of Life
    [C_ID .. 327] = "La Polaroid", -- The Polaroid
    [C_ID .. 328] = "Il Negativo", -- The Negative
    [C_ID .. 329] = "Il Trattamento Ludovico", -- The Ludovico Technique
    [C_ID .. 330] = "Latte di Soia", -- Soy Milk
    [C_ID .. 331] = "Divinità", -- Godhead
    [C_ID .. 332] = "Bende di Lazzaro", -- Lazarus' Rags
    [C_ID .. 333] = "La Mente", -- The Mind
    [C_ID .. 334] = "Il Corpo", -- The Body
    [C_ID .. 335] = "L'Anima", -- The Soul
    [C_ID .. 336] = "Cipolla Morta", -- Dead Onion
    [C_ID .. 337] = "Cipollotto Rotto", -- Broken Watch
    [C_ID .. 338] = "Il Boomerang", -- The Boomerang
    [C_ID .. 339] = "Spilla da Balia", -- Safety Pin
    [C_ID .. 340] = "Pillola di Caffeina", -- Caffeine Pill
    [C_ID .. 341] = "Foto Strappata", -- Torn Photo
    [C_ID .. 342] = "Cappello Blu", -- Blue Cap
    [C_ID .. 343] = "Chiave dell'Ometto", -- Latch Key
    [C_ID .. 344] = "Scatola di Cerini", -- Match Book
    [C_ID .. 345] = "Sintolio", -- Synthoil
    [C_ID .. 346] = "Uno Snack", -- A Snack
    [C_ID .. 347] = "Diplopia", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Nichelino di Legno", -- Wooden Nickel
    [C_ID .. 350] = "Shock Tossico", -- Toxic Shock
    [C_ID .. 351] = "Mega Fagiolo", -- Mega Bean
    [C_ID .. 352] = "Cannone di Vetro", -- Glass Cannon
    [C_ID .. 353] = "Bomber Boy", -- Bomber Boy
    [C_ID .. 354] = "Crack Jack", -- Crack Jacks
    [C_ID .. 355] = "Perle di Mamma", -- Mom's Pearls
    [C_ID .. 356] = "Batteria per Auto", -- Car Battery
    [C_ID .. 357] = "Scatola degli Amici", -- Box of Friends
    [C_ID .. 358] = "Il Genio", -- The Wiz
    [C_ID .. 359] = "Chiodo schiaccia Chiodo", -- 8 Inch Nails
    [C_ID .. 360] = "Incubo", -- Incubus
    [C_ID .. 361] = "Dono del Destino", -- Fate's Reward
    [C_ID .. 362] = "Bauletto", -- Lil Chest
    [C_ID .. 363] = "Eterno Protettore", -- Sworn Protector
    [C_ID .. 364] = "Friend Zone", -- Friend Zone
    [C_ID .. 365] = "Mosca Smarrita", -- Lost Fly
    [C_ID .. 366] = "Bomba a Grappolo", -- Scatter Bombs
    [C_ID .. 367] = "Bombe Appiccicose", -- Sticky Bombs
    [C_ID .. 368] = "Epifora", -- Epiphora
    [C_ID .. 369] = "Continuum", -- Continuum
    [C_ID .. 370] = "Sig. Bambolotto", -- Mr. Dolly
    [C_ID .. 371] = "Maledizione della Torre", -- Curse of the Tower
    [C_ID .. 372] = "Bebè Carico", -- Charged Baby
    [C_ID .. 373] = "Cecchino", -- Dead Eye
    [C_ID .. 374] = "Luce Santa", -- Holy Light
    [C_ID .. 375] = "Cascospite", -- Host Hat
    [C_ID .. 376] = "Rifornimento", -- Restock
    [C_ID .. 377] = "Sacca Brulicante", -- Bursting Sack
    [C_ID .. 378] = "La Numero Due", -- No. 2
    [C_ID .. 379] = "Pupula Duplex", -- Pupula Duplex
    [C_ID .. 380] = "Pay To Play", -- Pay To Play
    [C_ID .. 381] = "Benedizione di Eden", -- Eden's Blessing
    [C_ID .. 382] = "Sfera Amikè", -- Friendly Ball
    [C_ID .. 383] = "Detonatore di Lacrime", -- Tear Detonator
    [C_ID .. 384] = "Mini Gastrina", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Incensiere", -- Censer
    [C_ID .. 388] = "Scrocchiave", -- Key Bum
    [C_ID .. 389] = "Sacco di Rune", -- Rune Bag
    [C_ID .. 390] = "Serafino", -- Seraphim
    [C_ID .. 391] = "Tradimento", -- Betrayal
    [C_ID .. 392] = "Zodiaco", -- Zodiac
    [C_ID .. 393] = "Bacio del Serpente", -- Serpent's Kiss
    [C_ID .. 394] = "Mirino", -- Marked
    [C_ID .. 395] = "Tecn. X", -- Tech X
    [C_ID .. 396] = "Bisturi", -- Ventricle Razor
    [C_ID .. 397] = "Raggio Traente", -- Tractor Beam
    [C_ID .. 398] = "Trip Divino", -- God's Flesh
    [C_ID .. 399] = "Fauci dell'Oblio", -- Maw of the Void
    [C_ID .. 400] = "Lancia del Destino", -- Spear of Destiny
    [C_ID .. 401] = "Explosivo", -- Explosivo
    [C_ID .. 402] = "Caos", -- Chaos
    [C_ID .. 403] = "Ragno Moddato", -- Spider Mod
    [C_ID .. 404] = "Bebè Scoreggione", -- Farting Baby
    [C_ID .. 405] = "Bug Rompigioco", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Purezza", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Recipiente Vuoto", -- Empty Vessel
    [C_ID .. 410] = "Malocchio", -- Evil Eye
    [C_ID .. 411] = "Sangue Furente", -- Lusty Blood
    [C_ID .. 412] = "Immorale Concezione", -- Cambion Conception
    [C_ID .. 413] = "Immacolata Concezione", -- Immaculate Conception
    [C_ID .. 414] = "Più Alternative", -- More Options
    [C_ID .. 415] = "Corona di Luce", -- Crown Of Light
    [C_ID .. 416] = "Tasche Profonde", -- Deep Pockets
    [C_ID .. 417] = "Succuba", -- Succubus
    [C_ID .. 418] = "Torta di Canditi", -- Fruit Cake
    [C_ID .. 419] = "Teletrasporto 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Polvere nera", -- Black Powder
    [C_ID .. 421] = "Fagiolo Rosso", -- Kidney Bean
    [C_ID .. 422] = "Clessidra Luminosa", -- Glowing Hourglass
    [C_ID .. 423] = "Cerchio Protettivo", -- Circle of Protection
    [C_ID .. 424] = "Testa di Sacco", -- Sack Head
    [C_ID .. 425] = "Luce Notturna", -- Night Light
    [C_ID .. 426] = "Fan Ossessionato", -- Obsessed Fan
    [C_ID .. 427] = "Blocco di TNT", -- Mine Crafter
    [C_ID .. 428] = "Pigiamino", -- PJs
    [C_ID .. 429] = "Testa del Mercante", -- Head of the Keeper
    [C_ID .. 430] = "Papà Mosca", -- Papa Fly
    [C_ID .. 431] = "Bebè Multidimensionale", -- Multidimensional Baby
    [C_ID .. 432] = "Bombe Glitter", -- Glitter Bombs
    [C_ID .. 433] = "La mia Ombra", -- My Shadow
    [C_ID .. 434] = "Barattolo di Mosche", -- Jar of Flies
    [C_ID .. 435] = "Mini Loki", -- Lil Loki
    [C_ID .. 436] = "Latte!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Ciuccio", -- Binky
    [C_ID .. 439] = "Scatola di Mamma", -- Mom's Box
    [C_ID .. 440] = "Calcolo Renale", -- Kidney Stone
    [C_ID .. 441] = "Mega Sbotto", -- Mega Blast
    [C_ID .. 442] = "Corona del Principe delle Tenebre", -- Dark Prince's Crown
    [C_ID .. 443] = "Mela!", -- Apple!
    [C_ID .. 444] = "Matita", -- Lead Pencil
    [C_ID .. 445] = "Canino", -- Dog Tooth
    [C_ID .. 446] = "Dente Marcio", -- Dead Tooth
    [C_ID .. 447] = "Fagiolo Aleggiante", -- Linger Bean
    [C_ID .. 448] = "Scheggia di Vetro", -- Shard of Glass
    [C_ID .. 449] = "Placca di Metallo", -- Metal Plate
    [C_ID .. 450] = "Occhio di Avarizia", -- Eye of Greed
    [C_ID .. 451] = "Tappetino del Cartomante", -- Tarot Cloth
    [C_ID .. 452] = "Vene Varicose", -- Varicose Veins
    [C_ID .. 453] = "Frattura Esposta", -- Compound Fracture
    [C_ID .. 454] = "Polidattilia", -- Polydactyly
    [C_ID .. 455] = "Moneta Perduta di Papà", -- Dad's Lost Coin
    [C_ID .. 456] = "Spuntino di Mezzanotte", -- Midnight Snack
    [C_ID .. 457] = "Testa Conica", -- Cone Head
    [C_ID .. 458] = "Ombelico", -- Belly Button
    [C_ID .. 459] = "Sinusite", -- Sinus Infection
    [C_ID .. 460] = "Glaucoma", -- Glaucoma
    [C_ID .. 461] = "Parassitoide", -- Parasitoid
    [C_ID .. 462] = "Occhio di Belial", -- Eye of Belial
    [C_ID .. 463] = "Acido Solforico", -- Sulfuric Acid
    [C_ID .. 464] = "Glifo dell'Equilibrio", -- Glyph of Balance
    [C_ID .. 465] = "Levetta Analogica", -- Analog Stick
    [C_ID .. 466] = "Contagio", -- Contagion
    [C_ID .. 467] = "Dito!", -- Finger!
    [C_ID .. 468] = "Ombroso", -- Shade
    [C_ID .. 469] = "Depressione", -- Depression
    [C_ID .. 470] = "Calmina", -- Hushy
    [C_ID .. 471] = "Mini Monstro", -- Lil Monstro
    [C_ID .. 472] = "Re Bebè", -- King Baby
    [C_ID .. 473] = "Cicciottona", -- Big Chubby
    [C_ID .. 474] = "Cannone di Vetro Infranto", -- Broken Glass Cannon
    [C_ID .. 475] = "Piano C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Vuoto", -- Void
    [C_ID .. 478] = "Pausa", -- Pause
    [C_ID .. 479] = "Fonderia", -- Smelter
    [C_ID .. 480] = "Compost", -- Compost
    [C_ID .. 481] = "Dataminer", -- Dataminer
    [C_ID .. 482] = "Telecomando", -- Clicker
    [C_ID .. 483] = "Mamma Mega!", -- Mama Mega!
    [C_ID .. 484] = "Aspe', Cosa?", -- Wait What?
    [C_ID .. 485] = "Penny Storto", -- Crooked Penny
    [C_ID .. 486] = "Lametta Smussata", -- Dull Razor
    [C_ID .. 487] = "Pelapatate", -- Potato Peeler
    [C_ID .. 488] = "Metronomo", -- Metronome
    [C_ID .. 489] = "D Infinito", -- D Infinity
    [C_ID .. 490] = "Anima di Eden", -- Eden's Soul
    [C_ID .. 491] = "Bebè Acido", -- Acid Baby
    [C_ID .. 492] = "YO SENTI QUA!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenalina", -- Adrenaline
    [C_ID .. 494] = "Scala di Giacobbe", -- Jacob's Ladder
    [C_ID .. 495] = "Peperoncino Fantasma", -- Ghost Pepper
    [C_ID .. 496] = "Eutanasia", -- Euthanasia
    [C_ID .. 497] = "Mutande Camo", -- Camo Undies
    [C_ID .. 498] = "Dualismo", -- Duality
    [C_ID .. 499] = "Eucaristia", -- Eucharist
    [C_ID .. 500] = "Sacco di Sacchi", -- Sack of Sacks
    [C_ID .. 501] = "Gozzo di Avarizia", -- Greed's Gullet
    [C_ID .. 502] = "Brufolone", -- Large Zit
    [C_ID .. 503] = "Piccolo Corno", -- Little Horn
    [C_ID .. 504] = "Pepita Marrone", -- Brown Nugget
    [C_ID .. 505] = "Pokè Go", -- Poke Go
    [C_ID .. 506] = "Pugnalatore", -- Backstabber
    [C_ID .. 507] = "Cannuccia Appuntita", -- Sharp Straw
    [C_ID .. 508] = "Rasoio di Mamma", -- Mom's Razor
    [C_ID .. 509] = "Occhio Insanguinato", -- Bloodshot Eye
    [C_ID .. 510] = "Delirante", -- Delirious
    [C_ID .. 511] = "Moscarrabbiata", -- Angry Fly
    [C_ID .. 512] = "Buco Nero", -- Black Hole
    [C_ID .. 513] = "Pagliaccio", -- Bozo
    [C_ID .. 514] = "Modem Sfasciato", -- Broken Modem
    [C_ID .. 515] = "Dono Segreto", -- Mystery Gift
    [C_ID .. 516] = "Irrigatore", -- Sprinkler
    [C_ID .. 517] = "Bombe Leste", -- Fast Bombs
    [C_ID .. 518] = "Amico in Scatola", -- Buddy in a Box
    [C_ID .. 519] = "Mini Delirio", -- Lil Delirium
    [C_ID .. 520] = "Morsetti", -- Jumper Cables
    [C_ID .. 521] = "Coupon", -- Coupon
    [C_ID .. 522] = "Telecinesi", -- Telekinesis
    [C_ID .. 523] = "Scatola per Traslochi", -- Moving Box
    [C_ID .. 524] = "Tecnologia Zero", -- Technology Zero
    [C_ID .. 525] = "Lebbra", -- Leprosy
    [C_ID .. 526] = "7 Sigilli", -- 7 Seals
    [C_ID .. 527] = "Mr. GUARDI!", -- Mr. ME!
    [C_ID .. 528] = "Prisma Angelico", -- Angelic Prism
    [C_ID .. 529] = "Pop!", -- Pop!
    [C_ID .. 530] = "Lista Nera", -- Death's List
    [C_ID .. 531] = "Emolacria", -- Haemolacria
    [C_ID .. 532] = "Lacrifagia", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Zainetto", -- Schoolbag
    [C_ID .. 535] = "Copertina", -- Blanket
    [C_ID .. 536] = "Altare Sacrificale", -- Sacrificial Altar
    [C_ID .. 537] = "Mini Conato", -- Lil Spewer
    [C_ID .. 538] = "Biglie", -- Marbles
    [C_ID .. 539] = "Uovo Misterioso", -- Mystery Egg
    [C_ID .. 540] = "Sasso Piatto", -- Flat Stone
    [C_ID .. 541] = "Midollo", -- Marrow
    [C_ID .. 542] = "Costola Fluttuante", -- Slipped Rib
    [C_ID .. 543] = "Terra Consacrata", -- Hallowed Ground
    [C_ID .. 544] = "Costola Appuntita", -- Pointy Rib
    [C_ID .. 545] = "Libro dei Morti", -- Book of the Dead
    [C_ID .. 546] = "Anello di Papà", -- Dad's Ring
    [C_ID .. 547] = "Documenti per il Divorzio", -- Divorce Papers
    [C_ID .. 548] = "Mandibola", -- Jaw Bone
    [C_ID .. 549] = "Osteogenesi Imperfetta", -- Brittle Bones
    [C_ID .. 550] = "Pala Rotta", -- Broken Shovel
    [C_ID .. 551] = "Pala Rotta", -- Broken Shovel
    [C_ID .. 552] = "Pala di Mamma", -- Mom's Shovel
    [C_ID .. 553] = "Mucormicosi", -- Mucormycosis
    [C_ID .. 554] = "2Spooky", -- 2Spooky
    [C_ID .. 555] = "Lametta Dorata", -- Golden Razor
    [C_ID .. 556] = "Zolfo", -- Sulfur
    [C_ID .. 557] = "Biscotto della Fortuna", -- Fortune Cookie
    [C_ID .. 558] = "Obbrobrio", -- Eye Sore
    [C_ID .. 559] = "120 Volt", -- 120 Volt
    [C_ID .. 560] = "Fa Male", -- It Hurts
    [C_ID .. 561] = "Latte di Mandorla", -- Almond Milk
    [C_ID .. 562] = "Caduto in Basso", -- Rock Bottom
    [C_ID .. 563] = "Bombe Frufru", -- Nancy Bombs
    [C_ID .. 564] = "Una Saponetta", -- A Bar of Soap
    [C_ID .. 565] = "Cucciolo Sanguinario", -- Blood Puppy
    [C_ID .. 566] = "Acchiappasogni", -- Dream Catcher
    [C_ID .. 567] = "Cero Pasquale", -- Paschal Candle
    [C_ID .. 568] = "Intervento Divino", -- Divine Intervention
    [C_ID .. 569] = "Patto di Sangue", -- Blood Oath
    [C_ID .. 570] = "Biscotto di Pongo", -- Playdough Cookie
    [C_ID .. 571] = "Calzini Orfani", -- Orphan Socks
    [C_ID .. 572] = "Occhio dell'Occulto", -- Eye of the Occult
    [C_ID .. 573] = "Cuore Immacolato", -- Immaculate Heart
    [C_ID .. 574] = "Ostensorio", -- Monstrance
    [C_ID .. 575] = "L'Intruso", -- The Intruder
    [C_ID .. 576] = "Mente Sporca", -- Dirty Mind
    [C_ID .. 577] = "Damocle", -- Damocles
    [C_ID .. 578] = "Limonata Gratis", -- Free Lemonade
    [C_ID .. 579] = "Spada dello Spirito", -- Spirit Sword
    [C_ID .. 580] = "Chiave Rossa", -- Red Key
    [C_ID .. 581] = "Mosca Psichica", -- Psy Fly
    [C_ID .. 582] = "Fungo Allucinogeno", -- Wavy Cap
    [C_ID .. 583] = "Razzo in una Giara", -- Rocket in a Jar
    [C_ID .. 584] = "Libro delle Virtù", -- Book of Virtues
    [C_ID .. 585] = "Scatola di Alabastro", -- Alabaster Box
    [C_ID .. 586] = "La Scalinata", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Luna", -- Luna
    [C_ID .. 590] = "Mercurius", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Terra", -- Terra
    [C_ID .. 593] = "Mars", -- Mars
    [C_ID .. 594] = "Iupiter", -- Jupiter
    [C_ID .. 595] = "Saturnus", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptunus", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Testa Voodoo", -- Voodoo Head
    [C_ID .. 600] = "Collirio", -- Eye Drops
    [C_ID .. 601] = "Atto di Dolore", -- Act of Contrition
    [C_ID .. 602] = "Tessera Membri", -- Member Card
    [C_ID .. 603] = "Accumulatore", -- Battery Pack
    [C_ID .. 604] = "Braccialetto di Mamma", -- Mom's Bracelet
    [C_ID .. 605] = "Porzionatore", -- The Scooper
    [C_ID .. 606] = "Squarcio Oculare", -- Ocular Rift
    [C_ID .. 607] = "Bebè Bollito", -- Boiled Baby
    [C_ID .. 608] = "Bebè Ghiacciato", -- Freezer Baby
    [C_ID .. 609] = "D6 Eterno", -- Eternal D6
    [C_ID .. 610] = "Gabbia per Uccelli", -- Bird Cage
    [C_ID .. 611] = "Laringe", -- Larynx
    [C_ID .. 612] = "Anima Smarrita", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Bombe di Sangue", -- Blood Bombs
    [C_ID .. 615] = "Mini Chiappotte", -- Lil Dumpy
    [C_ID .. 616] = "Peperoncino nell'Occhio", -- Bird's Eye
    [C_ID .. 617] = "Magnetite", -- Lodestone
    [C_ID .. 618] = "Pomodoro Marcio", -- Rotten Tomato
    [C_ID .. 619] = "Primogenitura", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Stufato Rosso", -- Red Stew
    [C_ID .. 622] = "Genesi", -- Genesis
    [C_ID .. 623] = "Chiave Puntuta", -- Sharp Key
    [C_ID .. 624] = "Bustina di Espansione", -- Booster Pack
    [C_ID .. 625] = "Mega Fungo", -- Mega Mush
    [C_ID .. 626] = "Pezzo del Coltello 1", -- Knife Piece 1
    [C_ID .. 627] = "Pezzo del Coltello 2", -- Knife Piece 2
    [C_ID .. 628] = "Certificato di Morte", -- Death Certificate
    [C_ID .. 629] = "Mosca-Bot", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Mannaia", -- Meat Cleaver
    [C_ID .. 632] = "Nazar", -- Evil Charm
    [C_ID .. 633] = "Dogma", -- Dogma
    [C_ID .. 634] = "Purgatorio", -- Purgatory
    [C_ID .. 635] = "Feticcio", -- Stitches
    [C_ID .. 636] = "Tasto R", -- R Key
    [C_ID .. 637] = "Pugno nell'Occhio", -- Knockout Drops
    [C_ID .. 638] = "Gomma per Cancellare", -- Eraser
    [C_ID .. 639] = "Cuore Schifoso", -- Yuck Heart
    [C_ID .. 640] = "Urna di Anime", -- Urn of Souls
    [C_ID .. 641] = "Akeldama", -- Akeldama
    [C_ID .. 642] = "Pelle Magica", -- Magic Skin
    [C_ID .. 643] = "Rivelazione", -- Revelation
    [C_ID .. 644] = "Premio di Consolazione", -- Consolation Prize
    [C_ID .. 645] = "Minitoma", -- Tinytoma
    [C_ID .. 646] = "Bombe Zolfo Fuso", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volt", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Plum Fruttato", -- Fruity Plum
    [C_ID .. 650] = "Flauto Plum", -- Plum Flute
    [C_ID .. 651] = "Stella di Betlemme", -- Star of Bethlehem
    [C_ID .. 652] = "Bebè Cubetto", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "Dottorato Falsificato", -- False PHD
    [C_ID .. 655] = "Ruota per Vincere", -- Spin to Win
    [C_ID .. 656] = "Damocle", -- Damocles
    [C_ID .. 657] = "Vasculite", -- Vasculitis
    [C_ID .. 658] = "Cellula Gigante", -- Giant Cell
    [C_ID .. 659] = "Tropicamide", -- Tropicamide
    [C_ID .. 660] = "Lettura delle Carte", -- Card Reading
    [C_ID .. 661] = "Quintetto", -- Quints
    [C_ID .. 662] = "Pacifista (Cut item)", -- 
    [C_ID .. 663] = "Unghie e Denti", -- Tooth and Nail
    [C_ID .. 664] = "Abbuffata", -- Binge Eater
    [C_ID .. 665] = "Occhio di Guppy", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Fantoccio", -- Strawman
    [C_ID .. 668] = "Biglietto di Papà", -- Dad's Note
    [C_ID .. 669] = "Insaccato", -- Sausage
    [C_ID .. 670] = "Alternative?", -- Options?
    [C_ID .. 671] = "Dolce Cuore", -- Candy Heart
    [C_ID .. 672] = "Un Etto di Carne", -- A Pound of Flesh
    [C_ID .. 673] = "Redenzione", -- Redemption
    [C_ID .. 674] = "Catene Spirituali", -- Spirit Shackles
    [C_ID .. 675] = "Sfera Incrinata", -- Cracked Orb
    [C_ID .. 676] = "Cuore Vuoto", -- Empty Heart
    [C_ID .. 677] = "Proiezione Astrale", -- Astral Projection
    [C_ID .. 678] = "Taglio Cesareo", -- C Section
    [C_ID .. 679] = "Mini Abbadon", -- Lil Abaddon
    [C_ID .. 680] = "Vendetta di Montezuma", -- Montezuma's Revenge
    [C_ID .. 681] = "Mini Portale", -- Lil Portal
    [C_ID .. 682] = "Amico Verme", -- Worm Friend
    [C_ID .. 683] = "Speroni Ossei", -- Bone Spurs
    [C_ID .. 684] = "Anima Affamata", -- Hungry Soul
    [C_ID .. 685] = "Giara di Fiammelle", -- Jar of Wisps
    [C_ID .. 686] = "Ciondolo Celeste", -- Soul Locket
    [C_ID .. 687] = "Cerca Amici", -- Friend Finder
    [C_ID .. 688] = "Fanciullo Interiore", -- Inner Child
    [C_ID .. 689] = "Corona Glitchata", -- Glitched Crown
    [C_ID .. 690] = "Gelatina di Fagiolo", -- Belly Jelly
    [C_ID .. 691] = "Sfera Sacra", -- Sacred Orb
    [C_ID .. 692] = "Legame di Sangue", -- Sanguine Bond
    [C_ID .. 693] = "Lo Sciame", -- The Swarm
    [C_ID .. 694] = "Crepacuore", -- Heartbreak
    [C_ID .. 695] = "Soffio Furente", -- Bloody Gust
    [C_ID .. 696] = "Salvezza", -- Salvation
    [C_ID .. 697] = "Gemello Evanescente", -- Vanishing Twin
    [C_ID .. 698] = "Diabolico Duo", -- Twisted Pair
    [C_ID .. 699] = "Furia di Azazel", -- Azazel's Rage
    [C_ID .. 700] = "Camera di Risonanza", -- Echo Chamber
    [C_ID .. 701] = "Tomba di Isaac", -- Isaac's Tomb
    [C_ID .. 702] = "Spirito Vendicativo", -- Vengeful Spirit
    [C_ID .. 703] = "Esau Jr.", -- Esau Jr.
    [C_ID .. 704] = "Violenza!", -- Berserk!
    [C_ID .. 705] = "Arti Oscure", -- Dark Arts
    [C_ID .. 706] = "Abisso", -- Abyss
    [C_ID .. 707] = "Cena", -- Supper
    [C_ID .. 708] = "Pinzatrice", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Sacco del Fai da Te", -- Bag of Crafting
    [C_ID .. 711] = "Limbo", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Richiamo", -- Recall
    [C_ID .. 715] = "Vasetto", -- Hold
    [C_ID .. 716] = "Sacca del Mercante", -- Keeper's Sack
    [C_ID .. 717] = "Strirpe del Mercante", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "Scatola del Mercante", -- Keeper's Box
    [C_ID .. 720] = "Giara Universale", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Dado Decrementale", -- Spindown Dice
    [C_ID .. 724] = "Trombofilia", -- Hypercoagulation
    [C_ID .. 725] = "Sindrome del Colon Irritabile", -- IBS
    [C_ID .. 726] = "Emottisi", -- Hemoptysis
    [C_ID .. 727] = "Bombe Fantasma", -- Ghost Bombs
    [C_ID .. 728] = "Gellò", -- Gello
    [C_ID .. 729] = "Decapita Azione", -- Decap Attack
    [C_ID .. 730] = "Occhio di Vetro", -- Glass Eye
    [C_ID .. 731] = "Orzaiolo", -- Stye
    [C_ID .. 732] = "Anello di Mamma", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Penny Ingerito", -- Swallowed Penny
    [T_ID .. 2] = "Cacca Pietrificata", -- Petrified Poop
    [T_ID .. 3] = "Pila AAA", -- AAA Battery
    [T_ID .. 4] = "Telecomando Rotto", -- Broken Remote
    [T_ID .. 5] = "Purple Heart", -- Purple Heart
    [T_ID .. 6] = "Magnete Rotto", -- Broken Magnet
    [T_ID .. 7] = "Grano del Rosario", -- Rosary Bead
    [T_ID .. 8] = "Cartuccia", -- Cartridge
    [T_ID .. 9] = "Verme Pulsante", -- Pulse Worm
    [T_ID .. 10] = "Verme Ondulato", -- Wiggle Worm
    [T_ID .. 11] = "Verme Anello", -- Ring Worm
    [T_ID .. 12] = "Verme Piatto", -- Flat Worm
    [T_ID .. 13] = "Buono Acquisto", -- Store Credit
    [T_ID .. 14] = "Callo", -- Callus
    [T_ID .. 15] = "Pietra Fortunata", -- Lucky Rock
    [T_ID .. 16] = "Unghia dei Piedi di Mamma", -- Mom's Toenail
    [T_ID .. 17] = "Rossetto Nero", -- Black Lipstick
    [T_ID .. 18] = "Passo della Bibbia", -- Bible Tract
    [T_ID .. 19] = "Graffetta", -- Paper Clip
    [T_ID .. 20] = "Zampa di Scimmia", -- Monkey Paw
    [T_ID .. 21] = "Foglio Misterioso", -- Mysterious Paper
    [T_ID .. 22] = "Coda del Demonio", -- Daemon's Tail
    [T_ID .. 23] = "Volantino 'Smarrito'", -- Missing Poster
    [T_ID .. 24] = "Penny Popò", -- Butt Penny
    [T_ID .. 25] = "Caramella Misteriosa", -- Mysterious Candy
    [T_ID .. 26] = "Verme Uncino", -- Hook Worm
    [T_ID .. 27] = "Verme Frusta", -- Whip Worm
    [T_ID .. 28] = "Ankh Rotto", -- Broken Ankh
    [T_ID .. 29] = "Testa di Pesce", -- Fish Head
    [T_ID .. 30] = "Congiuntivite", -- Pinky Eye
    [T_ID .. 31] = "Puntina", -- Push Pin
    [T_ID .. 32] = "Fungo della Libertà", -- Liberty Cap
    [T_ID .. 33] = "Cordone Ombelicale", -- Umbilical Cord
    [T_ID .. 34] = "Cuore di Bambino", -- Child's Heart
    [T_ID .. 35] = "Corno Ricurvo", -- Curved Horn
    [T_ID .. 36] = "Chiave Arrugginita", -- Rusted Key
    [T_ID .. 37] = "Zoccolo di Capra", -- Goat Hoof
    [T_ID .. 38] = "Perla di Mamma", -- Mom's Pearl
    [T_ID .. 39] = "Cancro", -- Cancer
    [T_ID .. 40] = "Toppa Rossa", -- Red Patch
    [T_ID .. 41] = "Fiammifero", -- Match Stick
    [T_ID .. 42] = "Alluce Fortunato", -- Lucky Toe
    [T_ID .. 43] = "Teschio Maledetto", -- Cursed Skull
    [T_ID .. 44] = "Tappino di Sicurezza", -- Safety Cap
    [T_ID .. 45] = "Asso di Picche", -- Ace of Spades
    [T_ID .. 46] = "Forchetta di Isaac", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "Una Pagina Mancante", -- A Missing Page
    [T_ID .. 49] = "Penny Sanguinolento", -- Bloody Penny
    [T_ID .. 50] = "Penny Bruciato", -- Burnt Penny
    [T_ID .. 51] = "Penny Piatto", -- Flat Penny
    [T_ID .. 52] = "Penny Contraffatto", -- Counterfeit Penny
    [T_ID .. 53] = "Zecca", -- Tick
    [T_ID .. 54] = "Testa Di Isaac", -- Isaac's Head
    [T_ID .. 55] = "Fede di Madda", -- Maggy's Faith
    [T_ID .. 56] = "Lingua di Giuda", -- Judas' Tongue
    [T_ID .. 57] = "Anima di ???", -- ???'s Soul
    [T_ID .. 58] = "Ciocca di Sansone", -- Samson's Lock
    [T_ID .. 59] = "Occhio di Caino", -- Cain's Eye
    [T_ID .. 60] = "Zampa d'Uccello di Eva", -- Eve's Bird Foot
    [T_ID .. 61] = "La Mano Sinistra", -- The Left Hand
    [T_ID .. 62] = "Pietra Brillante", -- Shiny Rock
    [T_ID .. 63] = "Forbicine", -- Safety Scissors
    [T_ID .. 64] = "Verme Arcobaleno", -- Rainbow Worm
    [T_ID .. 65] = "Verme Solitario", -- Tape Worm
    [T_ID .. 66] = "Verme Pigro", -- Lazy Worm
    [T_ID .. 67] = "Dado Incrinato", -- Cracked Dice
    [T_ID .. 68] = "Super Magnete", -- Super Magnet
    [T_ID .. 69] = "Polaroid Sbiadita", -- Faded Polaroid
    [T_ID .. 70] = "Pidocchio", -- Louse
    [T_ID .. 71] = "Vescica di Bob", -- Bob's Bladder
    [T_ID .. 72] = "Pila dell'Orologio", -- Watch Battery
    [T_ID .. 73] = "Minicicciolo", -- Blasting Cap
    [T_ID .. 74] = "Rilevatore", -- Stud Finder
    [T_ID .. 75] = "Errore", -- Error
    [T_ID .. 76] = "Fiche da Poker", -- Poker Chip
    [T_ID .. 77] = "Vescicola", -- Blister
    [T_ID .. 78] = "Lancetta dei Secondi", -- Second Hand
    [T_ID .. 79] = "Senza Nome, Senza Fine", -- Endless Nameless
    [T_ID .. 80] = "Piuma Nera", -- Black Feather
    [T_ID .. 81] = "Furia Cieca", -- Blind Rage
    [T_ID .. 82] = "Ferro di Cavallo Dorato", -- Golden Horse Shoe
    [T_ID .. 83] = "Chiave del Negozio", -- Store Key
    [T_ID .. 84] = "Costola di Avarizia", -- Rib of Greed
    [T_ID .. 85] = "Karma", -- Karma
    [T_ID .. 86] = "Piccola Larva", -- Lil Larva
    [T_ID .. 87] = "Ciondolo di Mamma", -- Mom's Locket
    [T_ID .. 88] = "NO!", -- NO!
    [T_ID .. 89] = "Guinzaglio per Bambini", -- Child Leash
    [T_ID .. 90] = "Ministercolo", -- Brown Cap
    [T_ID .. 91] = "Meconio", -- Meconium
    [T_ID .. 92] = "Corona Incrinata", -- Cracked Crown
    [T_ID .. 93] = "Pannolino Usato", -- Used Diaper
    [T_ID .. 94] = "Coda di Pesce", -- Fish Tail
    [T_ID .. 95] = "Dente Nero", -- Black Tooth
    [T_ID .. 96] = "Verme Uroboro", -- Ouroboros Worm
    [T_ID .. 97] = "Tonsilla", -- Tonsil
    [T_ID .. 98] = "Pepita Verde", -- Nose Goblin
    [T_ID .. 99] = "Super Ball", -- Super Ball
    [T_ID .. 100] = "Lampadina Vivida", -- Vibrant Bulb
    [T_ID .. 101] = "Lampadina Fioca", -- Dim Bulb
    [T_ID .. 102] = "Carta Stracciata", -- Fragmented Card
    [T_ID .. 103] = "Uguaglianza!", -- Equality!
    [T_ID .. 104] = "Osso dei Desideri", -- Wish Bone
    [T_ID .. 105] = "Sacchetto per il Pranzo", -- Bag Lunch
    [T_ID .. 106] = "Tappo di Sughero Smarrito", -- Lost Cork
    [T_ID .. 107] = "Cuore di Corvo", -- Crow Heart
    [T_ID .. 108] = "Noce", -- Walnut
    [T_ID .. 109] = "Nastro Adesivo", -- Duct Tape
    [T_ID .. 110] = "Dollaro d'Argento", -- Silver Dollar
    [T_ID .. 111] = "Corona Sanguinolenta", -- Bloody Crown
    [T_ID .. 112] = "Pay To Win", -- Pay To Win
    [T_ID .. 113] = "Locusta della Guerra", -- Locust of War
    [T_ID .. 114] = "Locusta della Pestilenza", -- Locust of Pestilence
    [T_ID .. 115] = "Locusta della Carestia", -- Locust of Famine
    [T_ID .. 116] = "Locusta dela Morte", -- Locust of Death
    [T_ID .. 117] = "Locusta della Conquista", -- Locust of Conquest
    [T_ID .. 118] = "Ali di Pipistrello", -- Bat Wing
    [T_ID .. 119] = "Cellula Staminale", -- Stem Cell
    [T_ID .. 120] = "Forcina per Capelli", -- Hairpin
    [T_ID .. 121] = "Croce di Legno", -- Wooden Cross
    [T_ID .. 122] = "Burro!", -- Butter!
    [T_ID .. 123] = "Piuma di Filigrana", -- Filigree Feather
    [T_ID .. 124] = "Fermaporte", -- Door Stop
    [T_ID .. 125] = "Prolunga", -- Extension Cord
    [T_ID .. 126] = "Penny Marcio", -- Rotten Penny
    [T_ID .. 127] = "Piega-cucchiaini", -- Baby-Bender
    [T_ID .. 128] = "Falangi", -- Finger Bone
    [T_ID .. 129] = "Spaccamascella", -- Jawbreaker
    [T_ID .. 130] = "Penna Masticata", -- Chewed Pen
    [T_ID .. 131] = "Penny Benedetto", -- Blessed Penny
    [T_ID .. 132] = "Siringa Rotta", -- Broken Syringe
    [T_ID .. 133] = "Miccia Corta", -- Short Fuse
    [T_ID .. 134] = "Fagiolo Gigante", -- Gigante Bean
    [T_ID .. 135] = "Un Accendino", -- A Lighter
    [T_ID .. 136] = "Lucchetto Rotto", -- Broken Padlock
    [T_ID .. 137] = "Myosotis", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Amuleto Lacrima", -- Teardrop Charm
    [T_ID .. 140] = "Pomo di Sodoma", -- Apple of Sodom
    [T_ID .. 141] = "Ninna Nanna Dimenticata", -- Forgotten Lullaby
    [T_ID .. 142] = "Fede di Bet", -- Beth's Faith
    [T_ID .. 143] = "Vecchio Condensatore", -- Old Capacitor
    [T_ID .. 144] = "Verme Cerebrale", -- Brain Worm
    [T_ID .. 145] = "Perfezione", -- Perfection
    [T_ID .. 146] = "Corona del Diavolo", -- Devil's Crown
    [T_ID .. 147] = "Penny Carico", -- Charged Penny
    [T_ID .. 148] = "Collana dell'Amicizia", -- Friendship Necklace
    [T_ID .. 149] = "Pulsante Antipanico", -- Panic Button
    [T_ID .. 150] = "Chiave Blu", -- Blue Key
    [T_ID .. 151] = "Lima", -- Flat File
    [T_ID .. 152] = "Lente del Telescopio", -- Telescope Lens
    [T_ID .. 153] = "Ciocca di Mamma", -- Mom's Lock
    [T_ID .. 154] = "Sacchetto dei Dadi", -- Dice Bag
    [T_ID .. 155] = "Corona Santa", -- Holy Crown
    [T_ID .. 156] = "Bacio di Mamma", -- Mother's Kiss
    [T_ID .. 157] = "Carta Strappata", -- Torn Card
    [T_ID .. 158] = "Tasca Strappata", -- Torn Pocket
    [T_ID .. 159] = "Chiave Dorata", -- Gilded Key
    [T_ID .. 160] = "Sacco Fortunato", -- Lucky Sack
    [T_ID .. 161] = "Corona Empia", -- Wicked Crown
    [T_ID .. 162] = "Moncherino di Azazel", -- Azazel's Stump
    [T_ID .. 163] = "Tarzanello", -- Dingle Berry
    [T_ID .. 164] = "Munizioni Giocattolo", -- Ring Cap
    [T_ID .. 165] = "No No!", -- Nuh Uh!
    [T_ID .. 166] = "Plastilina", -- Modeling Clay
    [T_ID .. 167] = "Osso Levigato", -- Polished Bone
    [T_ID .. 168] = "Cuore Cavo", -- Hollow Heart
    [T_ID .. 169] = "Disegno di un Bimbo", -- Kid's Drawing
    [T_ID .. 170] = "Chiave di Cristallo", -- Crystal Key
    [T_ID .. 171] = "Affarone del Mercante", -- Keeper's Bargain
    [T_ID .. 172] = "Penny Maledetto", -- Cursed Penny
    [T_ID .. 173] = "La Tua Anima", -- Your Soul
    [T_ID .. 174] = "Magnete Numero:", -- Number Magnet
    [T_ID .. 175] = "Chiave Strana", -- Strange Key
    [T_ID .. 176] = "Mini Grumo", -- Lil Clot
    [T_ID .. 177] = "Tatuaggio Temporaneo", -- Temporary Tattoo
    [T_ID .. 178] = "M80 Ingerito", -- Swallowed M80
    [T_ID .. 179] = "Radiocomando", -- RC Remote
    [T_ID .. 180] = "Anima Ritrovata", -- Found Soul
    [T_ID .. 181] = "Pacchetto Espansione", -- Expansion Pack
    [T_ID .. 182] = "Essenza di Bet", -- Beth's Essence
    [T_ID .. 183] = "I Gemelli", -- The Twins
    [T_ID .. 184] = "Carte per l'Adozione", -- Adoption Papers
    [T_ID .. 185] = "Zampa di Grillo", -- Cricket Leg
    [T_ID .. 186] = "Migliore Amica di Apollion", -- Apollyon's Best Friend
    [T_ID .. 187] = "Occhiali Rotti", -- Broken Glasses
    [T_ID .. 188] = "Cubo di Ghiaccio", -- Ice Cube
    [T_ID .. 189] = "Sigillo di Bafometto", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Il Matto", -- 0 - The Fool
    [Card_ID .. 2] = "I - Il Bagatto", -- I - The Magician
    [Card_ID .. 3] = "II - La Papessa", -- II - The High Priestess
    [Card_ID .. 4] = "III - L'Imperatrice", -- III - The Empress
    [Card_ID .. 5] = "IV - L'Imperatore", -- IV - The Emperor
    [Card_ID .. 6] = "V - Il Papa", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Gli Amanti", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Il Carro", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Giustizia", -- VIII - Justice
    [Card_ID .. 10] = "IX - L'Eremita", -- IX - The Hermit
    [Card_ID .. 11] = "X - Ruota della Fortuna", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Forza", -- XI - Strength
    [Card_ID .. 13] = "XII - L'Appeso", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Morte", -- XIII - Death
    [Card_ID .. 15] = "XIV - Temperanza", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Il Diavolo", -- XV - The Devil
    [Card_ID .. 17] = "XVI - La Torre", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Le Stelle", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - La Luna", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Il Sole", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Il Giudizio", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Il Mondo", -- XXI - The World
    [Card_ID .. 23] = "2 di Fiori", -- 2 of Clubs
    [Card_ID .. 24] = "2 di Quadri", -- 2 of Diamonds
    [Card_ID .. 25] = "2 di Picche", -- 2 of Spades
    [Card_ID .. 26] = "2 di Cuori", -- 2 of Hearts
    [Card_ID .. 27] = "Asso di Fiori", -- Ace of Clubs
    [Card_ID .. 28] = "Asso di Quadri", -- Ace of Diamonds
    [Card_ID .. 29] = "Asso di Picche", -- Ace of Spades
    [Card_ID .. 30] = "Asso di Cuori", -- Ace of Hearts
    [Card_ID .. 31] = "Jolly", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Runa Muta", -- Blank Rune
    [Card_ID .. 41] = "Runa Nera", -- Black Rune
    [Card_ID .. 42] = "Carta del Caos", -- Chaos Card
    [Card_ID .. 43] = "Carta di Credito", -- Credit Card
    [Card_ID .. 44] = "Carta delle Regole", -- Rules Card
    [Card_ID .. 45] = "Cards Against Humanity", -- A Card Against Humanity
    [Card_ID .. 46] = "Re Suicida", -- Suicide King
    [Card_ID .. 47] = "Carta Esci Gratis di Prigione", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "Carta ?", -- ? Card
    [Card_ID .. 49] = "Scheggia di Dado", -- Dice Shard
    [Card_ID .. 50] = "Contatto di Emergenza", -- Emergency Contact
    [Card_ID .. 51] = "Carta Santa", -- Holy Card
    [Card_ID .. 52] = "Crescita Gigante", -- Huge Growth
    [Card_ID .. 53] = "Richiamo Antico", -- Ancient Recall
    [Card_ID .. 54] = "Passo Epocale", -- Era Walk
    [Card_ID .. 55] = "Frammento di Runa", -- Rune Shard
    [Card_ID .. 56] = "0 - Il Matto?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Il Bagatto?", -- I - The Magician?
    [Card_ID .. 58] = "II - La Papessa?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - L'Imperatrice?", -- III - The Empress?
    [Card_ID .. 60] = "IV - L'Imperatore?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Il Papa?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Gli Amanti?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Il Carro?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Giustizia?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - L'Eremita?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Ruota della Fortuna?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Forza?", -- XI - Strength?
    [Card_ID .. 68] = "XII - L'Appeso?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Morte?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Temperanza?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Il Diavolo?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - La Torre?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Le Stelle?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - La Luna?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Il Sole?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Il Giudizio?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Il Mondo?", -- XXI - The World?
    [Card_ID .. 78] = "Chiave Spezzata", -- Cracked Key
    [Card_ID .. 79] = "Regina di Cuori", -- Queen of Hearts
    [Card_ID .. 80] = "Carta Jolly", -- Wild Card
    [Card_ID .. 81] = "Anima di Isaac", -- Soul of Isaac
    [Card_ID .. 82] = "Anima di Maddalena", -- Soul of Magdalene
    [Card_ID .. 83] = "Anima di Caino", -- Soul of Cain
    [Card_ID .. 84] = "Anima di Giuda", -- Soul of Judas
    [Card_ID .. 85] = "Anima di ???", -- Soul of ???
    [Card_ID .. 86] = "Anima di Eva", -- Soul of Eve
    [Card_ID .. 87] = "Anima di Sansone", -- Soul of Samson
    [Card_ID .. 88] = "Anima di Azazel", -- Soul of Azazel
    [Card_ID .. 89] = "Anima di Lazzaro", -- Soul of Lazarus
    [Card_ID .. 90] = "Anima di Eden", -- Soul of Eden
    [Card_ID .. 91] = "Anima dello Smarrito", -- Soul of the Lost
    [Card_ID .. 92] = "Anima di Lilith", -- Soul of Lilith
    [Card_ID .. 93] = "Anima del Mercante", -- Soul of the Keeper
    [Card_ID .. 94] = "Anima di Apollion", -- Soul of Apollyon
    [Card_ID .. 95] = "Anima del Dimenticato", -- Soul of the Forgotten
    [Card_ID .. 96] = "Anima di Betania", -- Soul of Bethany
    [Card_ID .. 97] = "Anima di Giacobbe ed Esaù", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "Gas Nocivo", -- Bad Gas
    [Pill_ID .. 2] = "Brutto Trip", -- Bad Trip
    [Pill_ID .. 3] = "Palle D'Acciaio", -- Balls of Steel
    [Pill_ID .. 4] = "Le Bombe sono Chiavi", -- Bombs are Key
    [Pill_ID .. 5] = "Diarrea Esplosiva", -- Explosive Diarrhea
    [Pill_ID .. 6] = "Salute al Massimo", -- Full Health
    [Pill_ID .. 7] = "Meno Salute", -- Health Down
    [Pill_ID .. 8] = "Più Salute", -- Health Up
    [Pill_ID .. 9] = "Ho Trovato delle Pillole", -- I Found Pills
    [Pill_ID .. 10] = "Pubertà", -- Puberty
    [Pill_ID .. 11] = "Moscarina", -- Pretty Fly
    [Pill_ID .. 12] = "Meno Gittata", -- Range Down
    [Pill_ID .. 13] = "Più Gittata", -- Range Up
    [Pill_ID .. 14] = "Meno Velocità", -- Speed Down
    [Pill_ID .. 15] = "Più Velocità", -- Speed Up
    [Pill_ID .. 16] = "Meno Lacrime", -- Tears Down
    [Pill_ID .. 17] = "Più Lacrime", -- Tears Up
    [Pill_ID .. 18] = "Meno Fortuna", -- Luck Down
    [Pill_ID .. 19] = "Più Fortuna", -- Luck Up
    [Pill_ID .. 20] = "Telepillole", -- Telepills
    [Pill_ID .. 21] = "Energia per 48 Ore!", -- 48 Hour Energy!
    [Pill_ID .. 22] = "Ematemesi", -- Hematemesis
    [Pill_ID .. 23] = "Paralisi", -- Paralysis
    [Pill_ID .. 24] = "Ho Visto Tutto!", -- I can see forever!
    [Pill_ID .. 25] = "Feromoni", -- Pheromones
    [Pill_ID .. 26] = "Amnesia", -- Amnesia
    [Pill_ID .. 27] = "Limonata", -- Lemon Party
    [Pill_ID .. 28] = "Ma 6 1 Mago?", -- R U A Wizard?
    [Pill_ID .. 29] = "Percocet!", -- Percs!
    [Pill_ID .. 30] = "Astinenza!", -- Addicted!
    [Pill_ID .. 31] = "Re-Lax", -- Re-Lax
    [Pill_ID .. 32] = "???", -- ???
    [Pill_ID .. 33] = "Una ti Rende Più Grande", -- One makes you larger
    [Pill_ID .. 34] = "Una ti Rende più Piccolo", -- One makes you small
    [Pill_ID .. 35] = "Infestato!", -- Infested!
    [Pill_ID .. 36] = "Infestato?", -- Infested?
    [Pill_ID .. 37] = "Pillola del Potere!", -- Power Pill!
    [Pill_ID .. 38] = "Rétro Visione", -- Retro Vision
    [Pill_ID .. 39] = "Amici fino alla Fine!", -- Friends Till The End!
    [Pill_ID .. 40] = "Liqui-Lax", -- X-Lax
    [Pill_ID .. 41] = "Qualcosa Non Quadra...", -- Something's wrong...
    [Pill_ID .. 42] = "Ho Sonno...", -- I'm Drowsy...
    [Pill_ID .. 43] = "Sono Euforico!!!", -- I'm Excited!!
    [Pill_ID .. 44] = "Gulp!", -- Gulp!
    [Pill_ID .. 45] = "Orf!", -- Horf!
    [Pill_ID .. 46] = "Baciato dal Sole!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "Vurp!", -- Vurp!
    [Pill_ID .. 48] = "Meno Velocità Colpi", -- Shot speed Down
    [Pill_ID .. 49] = "Più Velocità Colpi", -- Shot speed Up
    [Pill_ID .. 50] = "Pillola Sperimentale", -- Experimental Pill
    [Pill_ID .. 9999] = "Pillola Dorata", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])