-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "ko_kr"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "슬픈 양파", -- The Sad Onion
    [C_ID .. 2] = "내면의 눈", -- The Inner Eye
    [C_ID .. 3] = "초능력자", -- Spoon Bender
    [C_ID .. 4] = "크리켓의 머리", -- Cricket's Head
    [C_ID .. 5] = "나의 모습", -- My Reflection
    [C_ID .. 6] = "오줌싸개", -- Number One
    [C_ID .. 7] = "순교자의 피", -- Blood of the Martyr
    [C_ID .. 8] = "보비", -- Brother Bobby
    [C_ID .. 9] = "스카톨", -- Skatole
    [C_ID .. 10] = "파리떼", -- Halo of Flies
    [C_ID .. 11] = "", -- 1up!
    [C_ID .. 12] = "마법의 버섯", -- Magic Mushroom
    [C_ID .. 13] = "바이러스", -- The Virus
    [C_ID .. 14] = "불량 스테로이드", -- Roid Rage
    [C_ID .. 15] = "♡", -- <3
    [C_ID .. 16] = "생간", -- Raw Liver
    [C_ID .. 17] = "해골 열쇠", -- Skeleton Key
    [C_ID .. 18] = "달러", -- A Dollar
    [C_ID .. 19] = "꽈광!", -- Boom!
    [C_ID .. 20] = "초월", -- Transcendence
    [C_ID .. 21] = "나침반", -- The Compass
    [C_ID .. 22] = "점심밥", -- Lunch
    [C_ID .. 23] = "저녁밥", -- Dinner
    [C_ID .. 24] = "간식", -- Dessert
    [C_ID .. 25] = "아침밥", -- Breakfast
    [C_ID .. 26] = "썩은 고기", -- Rotten Meat
    [C_ID .. 27] = "나무 숟가락", -- Wooden Spoon
    [C_ID .. 28] = "벨트", -- The Belt
    [C_ID .. 29] = "엄마의 속옷", -- Mom's Underwear
    [C_ID .. 30] = "엄마의 하이힐", -- Mom's Heels
    [C_ID .. 31] = "엄마의 립스틱", -- Mom's Lipstick
    [C_ID .. 32] = "철제 옷걸이", -- Wire Coat Hanger
    [C_ID .. 33] = "성경", -- The Bible
    [C_ID .. 34] = "벨리알의 책", -- The Book of Belial
    [C_ID .. 35] = "네크로노미콘", -- The Necronomicon
    [C_ID .. 36] = "똥", -- The Poop
    [C_ID .. 37] = "미스터 붐", -- Mr. Boom
    [C_ID .. 38] = "태미의 머리", -- Tammy's Head
    [C_ID .. 39] = "엄마의 브래지어", -- Mom's Bra
    [C_ID .. 40] = "카미카제!", -- Kamikaze!
    [C_ID .. 41] = "엄마의 패드", -- Mom's Pad
    [C_ID .. 42] = "밥의 썩은 머리통", -- Bob's Rotten Head
    [C_ID .. 43] = "Pills here!", -- 
    [C_ID .. 44] = "순간이동!", -- Teleport!
    [C_ID .. 45] = "맛난 하트", -- Yum Heart
    [C_ID .. 46] = "행운의 발", -- Lucky Foot
    [C_ID .. 47] = "박사의 원격 조종기", -- Doctor's Remote
    [C_ID .. 48] = "큐피드의 화살", -- Cupid's Arrow
    [C_ID .. 49] = "모두 다 사라져빔!!", -- Shoop da Whoop!
    [C_ID .. 50] = "스티븐", -- Steven
    [C_ID .. 51] = "오망성", -- Pentagram
    [C_ID .. 52] = "태아 박사", -- Dr. Fetus
    [C_ID .. 53] = "자석", -- Magneto
    [C_ID .. 54] = "보물 지도", -- Treasure Map
    [C_ID .. 55] = "엄마의 눈알", -- Mom's Eye
    [C_ID .. 56] = "레몬빛 실수", -- Lemon Mishap
    [C_ID .. 57] = "짝사랑", -- Distant Admiration
    [C_ID .. 58] = "그림자의 책", -- Book of Shadows
    [C_ID .. 59] = "벨리알의 책", -- The Book of Belial
    [C_ID .. 60] = "사다리", -- The Ladder
    [C_ID .. 61] = "Tarot card", -- 
    [C_ID .. 62] = "뱀파이어의 부적", -- Charm of the Vampire
    [C_ID .. 63] = "건전지", -- The Battery
    [C_ID .. 64] = "스팀 세일", -- Steam Sale
    [C_ID .. 65] = "무정부주의자의 요리책", -- Anarchist Cookbook
    [C_ID .. 66] = "모래시계", -- The Hourglass
    [C_ID .. 67] = "매기", -- Sister Maggy
    [C_ID .. 68] = "기계장치", -- Technology
    [C_ID .. 69] = "초콜릿 우유", -- Chocolate Milk
    [C_ID .. 70] = "성장 호르몬", -- Growth Hormones
    [C_ID .. 71] = "미니 버섯", -- Mini Mush
    [C_ID .. 72] = "묵주", -- Rosary
    [C_ID .. 73] = "고기조각", -- Cube of Meat
    [C_ID .. 74] = "쿼터", -- A Quarter
    [C_ID .. 75] = "박사학위", -- PHD
    [C_ID .. 76] = "투시 안경", -- X-Ray Vision
    [C_ID .. 77] = "나의 작은 유니콘", -- My Little Unicorn
    [C_ID .. 78] = "요한묵시록", -- Book of Revelations
    [C_ID .. 79] = "낙인", -- The Mark
    [C_ID .. 80] = "계약", -- The Pact
    [C_ID .. 81] = "죽은 고양이", -- Dead Cat
    [C_ID .. 82] = "구덩이의 제왕", -- Lord of the Pit
    [C_ID .. 83] = "대못", -- The Nail
    [C_ID .. 84] = "더 깊이 내려가야 해!", -- We Need To Go Deeper!
    [C_ID .. 85] = "카드 덱", -- Deck of Cards
    [C_ID .. 86] = "몬스트로의 이빨", -- Monstro's Tooth
    [C_ID .. 87] = "로키의 뿔", -- Loki's Horns
    [C_ID .. 88] = "리틀 처비", -- Little Chubby
    [C_ID .. 89] = "거미물림", -- Spider Bite
    [C_ID .. 90] = "작은 돌", -- The Small Rock
    [C_ID .. 91] = "탐험가 모자", -- Spelunker Hat
    [C_ID .. 92] = "슈퍼 밴디지", -- Super Bandage
    [C_ID .. 93] = "게임키드", -- The Gamekid
    [C_ID .. 94] = "동전 주머니", -- Sack of Pennies
    [C_ID .. 95] = "로보베이비", -- Robo-Baby
    [C_ID .. 96] = "리틀 차드", -- Little C.H.A.D.
    [C_ID .. 97] = "죄악의 책", -- The Book of Sin
    [C_ID .. 98] = "성유물", -- The Relic
    [C_ID .. 99] = "리틀 기쉬", -- Little Gish
    [C_ID .. 100] = "리틀 스티븐", -- Little Steven
    [C_ID .. 101] = "광륜", -- The Halo
    [C_ID .. 102] = "엄마의 약병", -- Mom's Bottle of Pills
    [C_ID .. 103] = "감기", -- The Common Cold
    [C_ID .. 104] = "기생충", -- The Parasite
    [C_ID .. 105] = "주사위", -- The D6
    [C_ID .. 106] = "미스터 메가", -- Mr. Mega
    [C_ID .. 107] = "핑킹 가위", -- The Pinking Shears
    [C_ID .. 108] = "제병", -- The Wafer
    [C_ID .. 109] = "돈 = 힘", -- Money = Power
    [C_ID .. 110] = "엄마의 콘텍트렌즈", -- Mom's Contacts
    [C_ID .. 111] = "콩", -- The Bean
    [C_ID .. 112] = "수호천사", -- Guardian Angel
    [C_ID .. 113] = "악마 아기", -- Demon Baby
    [C_ID .. 114] = "엄마의 식칼", -- Mom's Knife
    [C_ID .. 115] = "분신사바", -- Ouija Board
    [C_ID .. 116] = "9볼트 건전지", -- 9 Volt
    [C_ID .. 117] = "죽은 새", -- Dead Bird
    [C_ID .. 118] = "유황", -- Brimstone
    [C_ID .. 119] = "혈액 팩", -- Blood Bag
    [C_ID .. 120] = "이상한 버섯", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "이상한 버섯", -- Odd Mushroom (Large)
    [C_ID .. 122] = "바빌론의 창녀", -- Whore of Babylon
    [C_ID .. 123] = "몬스터 도감", -- Monster Manual
    [C_ID .. 124] = "사해사본", -- Dead Sea Scrolls
    [C_ID .. 125] = "보비 폭탄", -- Bobby-Bomb
    [C_ID .. 126] = "면도날", -- Razor Blade
    [C_ID .. 127] = "날 잊어 주세요", -- Forget Me Now
    [C_ID .. 128] = "영원한 솔로", -- Forever Alone
    [C_ID .. 129] = "돼지기름 한 통", -- Bucket of Lard
    [C_ID .. 130] = "조랑말", -- A Pony
    [C_ID .. 131] = "폭탄 주머니", -- Bomb Bag
    [C_ID .. 132] = "석탄 한 덩이", -- A Lump of Coal
    [C_ID .. 133] = "구피의 발", -- Guppy's Paw
    [C_ID .. 134] = "구피의 꼬리", -- Guppy's Tail
    [C_ID .. 135] = "수혈 팩", -- IV Bag
    [C_ID .. 136] = "최고의 친구", -- Best Friend
    [C_ID .. 137] = "원격 폭파기", -- Remote Detonator
    [C_ID .. 138] = "성흔", -- Stigmata
    [C_ID .. 139] = "엄마의 지갑", -- Mom's Purse
    [C_ID .. 140] = "밥의 저주", -- Bob's Curse
    [C_ID .. 141] = "분장 소년", -- Pageant Boy
    [C_ID .. 142] = "성의", -- Scapular
    [C_ID .. 143] = "스피드볼 마약", -- Speed Ball
    [C_ID .. 144] = "거지 친구", -- Bum Friend
    [C_ID .. 145] = "구피의 머리", -- Guppy's Head
    [C_ID .. 146] = "기도 카드", -- Prayer Card
    [C_ID .. 147] = "각진 곡괭이", -- Notched Axe
    [C_ID .. 148] = "감염", -- Infestation
    [C_ID .. 149] = "구토제", -- Ipecac
    [C_ID .. 150] = "사랑의 매", -- Tough Love
    [C_ID .. 151] = "물리건", -- The Mulligan
    [C_ID .. 152] = "기계장치 2", -- Technology 2
    [C_ID .. 153] = "돌연변이 거미", -- Mutant Spider
    [C_ID .. 154] = "화학 박피제", -- Chemical Peel
    [C_ID .. 155] = "엿보기 눈깔", -- The Peeper
    [C_ID .. 156] = "수녀복", -- Habit
    [C_ID .. 157] = "피의 욕망", -- Bloody Lust
    [C_ID .. 158] = "수정구슬", -- Crystal Ball
    [C_ID .. 159] = "밤의 영혼", -- Spirit of the Night
    [C_ID .. 160] = "하늘을 가르다", -- Crack the Sky
    [C_ID .. 161] = "앙크", -- Ankh
    [C_ID .. 162] = "켈트 십자가", -- Celtic Cross
    [C_ID .. 163] = "유령 아기", -- Ghost Baby
    [C_ID .. 164] = "양초", -- The Candle
    [C_ID .. 165] = "아홉 가닥 채찍", -- Cat-o-nine-tails
    [C_ID .. 166] = "20면 주사위", -- D20
    [C_ID .. 167] = "할리퀸 아기", -- Harlequin Baby
    [C_ID .. 168] = "쩌는 태아", -- Epic Fetus
    [C_ID .. 169] = "폴리페무스", -- Polyphemus
    [C_ID .. 170] = "장님거미", -- Daddy Longlegs
    [C_ID .. 171] = "거미 엉덩이", -- Spider Butt
    [C_ID .. 172] = "희생의 단도", -- Sacrificial Dagger
    [C_ID .. 173] = "주교관", -- Mitre
    [C_ID .. 174] = "무지개 아기", -- Rainbow Baby
    [C_ID .. 175] = "아빠의 열쇠", -- Dad's Key
    [C_ID .. 176] = "줄기세포", -- Stem Cells
    [C_ID .. 177] = "휴대용 슬롯머신", -- Portable Slot
    [C_ID .. 178] = "성수", -- Holy Water
    [C_ID .. 179] = "운명", -- Fate
    [C_ID .. 180] = "검은 콩", -- The Black Bean
    [C_ID .. 181] = "하얀 조랑말", -- White Pony
    [C_ID .. 182] = "성스러운 심장", -- Sacred Heart
    [C_ID .. 183] = "이쑤시개", -- Tooth Picks
    [C_ID .. 184] = "신성한 성배", -- Holy Grail
    [C_ID .. 185] = "죽은 비둘기", -- Dead Dove
    [C_ID .. 186] = "피의 권리", -- Blood Rights
    [C_ID .. 187] = "구피의 털뭉치", -- Guppy's Hairball
    [C_ID .. 188] = "아벨", -- Abel
    [C_ID .. 189] = "슈미보 광팬", -- SMB Super Fan
    [C_ID .. 190] = "폭탄마", -- Pyro
    [C_ID .. 191] = "3달러 지폐", -- 3 Dollar Bill
    [C_ID .. 192] = "천재반을 위한 텔레파시법", -- Telepathy for Dummies
    [C_ID .. 193] = "고기!", -- MEAT!
    [C_ID .. 194] = "마법의 8번 공", -- Magic 8 Ball
    [C_ID .. 195] = "엄마의 동전 지갑", -- Mom's Coin Purse
    [C_ID .. 196] = "쥐어짜기 장난감", -- Squeezy
    [C_ID .. 197] = "예수 주스", -- Jesus Juice
    [C_ID .. 198] = "상자", -- Box
    [C_ID .. 199] = "엄마의 열쇠", -- Mom's Key
    [C_ID .. 200] = "엄마의 아이섀도우", -- Mom's Eyeshadow
    [C_ID .. 201] = "철괴", -- Iron Bar
    [C_ID .. 202] = "미다스의 손길", -- Midas' Touch
    [C_ID .. 203] = "험블 번들", -- Humbleing Bundle
    [C_ID .. 204] = "주머니 가방", -- Fanny Pack
    [C_ID .. 205] = "날카로운 플러그", -- Sharp Plug
    [C_ID .. 206] = "단두대", -- Guillotine
    [C_ID .. 207] = "밴드 덩어리", -- Ball of Bandages
    [C_ID .. 208] = "챔피언 벨트", -- Champion Belt
    [C_ID .. 209] = "궁둥이 폭탄", -- Butt Bombs
    [C_ID .. 210] = "갉아먹힌 나뭇잎", -- Gnawed Leaf
    [C_ID .. 211] = "새끼 거미", -- Spiderbaby
    [C_ID .. 212] = "구피의 목걸이", -- Guppy's Collar
    [C_ID .. 213] = "잃어버린 렌즈", -- Lost Contact
    [C_ID .. 214] = "빈혈증", -- Anemic
    [C_ID .. 215] = "염소 머리", -- Goat Head
    [C_ID .. 216] = "의식용 로브", -- Ceremonial Robes
    [C_ID .. 217] = "엄마의 가발", -- Mom's Wig
    [C_ID .. 218] = "태반", -- Placenta
    [C_ID .. 219] = "낡은 밴드", -- Old Bandage
    [C_ID .. 220] = "눈물 폭탄", -- Sad Bombs
    [C_ID .. 221] = "고무 접착제", -- Rubber Cement
    [C_ID .. 222] = "반중력", -- Anti-Gravity
    [C_ID .. 223] = "방화광", -- Pyromaniac
    [C_ID .. 224] = "크리켓의 몸", -- Cricket's Body
    [C_ID .. 225] = "김피", -- Gimpy
    [C_ID .. 226] = "검은 연꽃", -- Black Lotus
    [C_ID .. 227] = "돼지 저금통", -- Piggy Bank
    [C_ID .. 228] = "엄마의 향수", -- Mom's Perfume
    [C_ID .. 229] = "몬스트로의 폐", -- Monstro's Lung
    [C_ID .. 230] = "아바돈", -- Abaddon
    [C_ID .. 231] = "타르 덩어리", -- Ball of Tar
    [C_ID .. 232] = "스톱워치", -- Stop Watch
    [C_ID .. 233] = "소행성", -- Tiny Planet
    [C_ID .. 234] = "감염 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "대장균", -- E. Coli
    [C_ID .. 237] = "죽음의 손길", -- Death's Touch
    [C_ID .. 238] = "열쇠 조각 1", -- Key Piece 1
    [C_ID .. 239] = "열쇠 조각 2", -- Key Piece 2
    [C_ID .. 240] = "임상시험", -- Experimental Treatment
    [C_ID .. 241] = "지하로부터의 계약", -- Contract from Below
    [C_ID .. 242] = "악명", -- Infamy
    [C_ID .. 243] = "삼위일체 방패", -- Trinity Shield
    [C_ID .. 244] = "기계 0.5", -- Tech.5
    [C_ID .. 245] = "시력 2.0", -- 20/20
    [C_ID .. 246] = "파란 지도", -- Blue Map
    [C_ID .. 247] = "베프들!", -- BFFS!
    [C_ID .. 248] = "군체의식", -- Hive Mind
    [C_ID .. 249] = "추가 선택권", -- There's Options
    [C_ID .. 250] = "1+1 폭탄", -- Bogo Bombs
    [C_ID .. 251] = "스타터 덱", -- Starter Deck
    [C_ID .. 252] = "작은 주머니", -- Little Baggy
    [C_ID .. 253] = "마법의 딱쟁이", -- Magic Scab
    [C_ID .. 254] = "응고혈", -- Blood Clot
    [C_ID .. 255] = "나사못", -- Screw
    [C_ID .. 256] = "불폭탄", -- Hot Bombs
    [C_ID .. 257] = "불타는 마음", -- Fire Mind
    [C_ID .. 258] = "", -- Missing No.
    [C_ID .. 259] = "암흑 물질", -- Dark Matter
    [C_ID .. 260] = "검은 양초", -- Black Candle
    [C_ID .. 261] = "안구 돌출증", -- Proptosis
    [C_ID .. 262] = "찢어진 페이지 2", -- Missing Page 2
    [C_ID .. 263] = "투명한 룬", -- Clear Rune
    [C_ID .. 264] = "똑똑한 파리", -- Smart Fly
    [C_ID .. 265] = "마른 아기", -- Dry Baby
    [C_ID .. 266] = "축축한 알집", -- Juicy Sack
    [C_ID .. 267] = "로보 아기 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "썩은 아기", -- Rotten Baby
    [C_ID .. 269] = "머리없는 아기", -- Headless Baby
    [C_ID .. 270] = "거머리", -- Leech
    [C_ID .. 271] = "수수께끼의 주머니", -- Mystery Sack
    [C_ID .. 272] = "베프", -- BBF
    [C_ID .. 273] = "밥의 뇌", -- Bob's Brain
    [C_ID .. 274] = "최고의 짝꿍", -- Best Bud
    [C_ID .. 275] = "꼬마 유황", -- Lil Brimstone
    [C_ID .. 276] = "아이작의 심장", -- Isaac's Heart
    [C_ID .. 277] = "꼬마 유령", -- Lil Haunt
    [C_ID .. 278] = "악마 거지", -- Dark Bum
    [C_ID .. 279] = "왕팬", -- Big Fan
    [C_ID .. 280] = "눈나 거미", -- Sissy Longlegs
    [C_ID .. 281] = "샌드백", -- Punching Bag
    [C_ID .. 282] = "점프 하는 법", -- How to Jump
    [C_ID .. 283] = "100면 주사위", -- D100
    [C_ID .. 284] = "4면 주사위", -- D4
    [C_ID .. 285] = "10면 주사위", -- D10
    [C_ID .. 286] = "빈 카드", -- Blank Card
    [C_ID .. 287] = "비밀의 책", -- Book of Secrets
    [C_ID .. 288] = "거미 상자", -- Box of Spiders
    [C_ID .. 289] = "빨간 양초", -- Red Candle
    [C_ID .. 290] = "유리병", -- The Jar
    [C_ID .. 291] = "쏴아!", -- Flush!
    [C_ID .. 292] = "사탄경", -- Satanic Bible
    [C_ID .. 293] = "크람푸스의 머리", -- Head of Krampus
    [C_ID .. 294] = "흰강낭콩", -- Butter Bean
    [C_ID .. 295] = "침대 안마기", -- Magic Fingers
    [C_ID .. 296] = "변환기", -- Converter
    [C_ID .. 297] = "판도라의 상자", -- Pandora's Box
    [C_ID .. 298] = "유니콘의 잘린 뿔", -- Unicorn Stump
    [C_ID .. 299] = "황소자리", -- Taurus
    [C_ID .. 300] = "양자리", -- Aries
    [C_ID .. 301] = "게자리", -- Cancer
    [C_ID .. 302] = "사자자리", -- Leo
    [C_ID .. 303] = "처녀자리", -- Virgo
    [C_ID .. 304] = "천칭자리", -- Libra
    [C_ID .. 305] = "전갈자리", -- Scorpio
    [C_ID .. 306] = "사수자리", -- Sagittarius
    [C_ID .. 307] = "염소자리", -- Capricorn
    [C_ID .. 308] = "물병자리", -- Aquarius
    [C_ID .. 309] = "물고기자리", -- Pisces
    [C_ID .. 310] = "이브의 마스카라", -- Eve's Mascara
    [C_ID .. 311] = "유다의 그림자", -- Judas' Shadow
    [C_ID .. 312] = "매기의 리본", -- Maggy's Bow
    [C_ID .. 313] = "신성한 망토", -- Holy Mantle
    [C_ID .. 314] = "살찐 허벅지", -- Thunder Thighs
    [C_ID .. 315] = "이상한 끌개", -- Strange Attractor
    [C_ID .. 316] = "저주받은 눈알", -- Cursed Eye
    [C_ID .. 317] = "이상한 액체", -- Mysterious Liquid
    [C_ID .. 318] = "쌍둥이자리", -- Gemini
    [C_ID .. 319] = "카인의 왼쪽 눈", -- Cain's Other Eye
    [C_ID .. 320] = "???의 하나뿐인 친구", -- ???'s Only Friend
    [C_ID .. 321] = "삼손의 쇠사슬", -- Samson's Chains
    [C_ID .. 322] = "누더기 아기", -- Mongo Baby
    [C_ID .. 323] = "아이작의 눈물", -- Isaac's Tears
    [C_ID .. 324] = "", -- Undefined
    [C_ID .. 325] = "가위", -- Scissors
    [C_ID .. 326] = "생명의 숨결", -- Breath of Life
    [C_ID .. 327] = "즉석사진", -- The Polaroid
    [C_ID .. 328] = "반전사진", -- The Negative
    [C_ID .. 329] = "루도비코 요법", -- The Ludovico Technique
    [C_ID .. 330] = "두유", -- Soy Milk
    [C_ID .. 331] = "신", -- Godhead
    [C_ID .. 332] = "나사로의 붕대", -- Lazarus' Rags
    [C_ID .. 333] = "정신", -- The Mind
    [C_ID .. 334] = "육체", -- The Body
    [C_ID .. 335] = "영혼", -- The Soul
    [C_ID .. 336] = "죽은 양파", -- Dead Onion
    [C_ID .. 337] = "부서진 시계", -- Broken Watch
    [C_ID .. 338] = "부메랑", -- The Boomerang
    [C_ID .. 339] = "안전핀", -- Safety Pin
    [C_ID .. 340] = "카페인 정", -- Caffeine Pill
    [C_ID .. 341] = "찢어진 사진", -- Torn Photo
    [C_ID .. 342] = "파란 환각버섯", -- Blue Cap
    [C_ID .. 343] = "현관 열쇠", -- Latch Key
    [C_ID .. 344] = "종이 성냥", -- Match Book
    [C_ID .. 345] = "합성 스테로이드", -- Synthoil
    [C_ID .. 346] = "과자", -- A Snack
    [C_ID .. 347] = "복시", -- Diplopia
    [C_ID .. 348] = "위약", -- Placebo
    [C_ID .. 349] = "나무 동전", -- Wooden Nickel
    [C_ID .. 350] = "독성 쇼크", -- Toxic Shock
    [C_ID .. 351] = "대빵 큰 콩", -- Mega Bean
    [C_ID .. 352] = "유리 대포", -- Glass Cannon
    [C_ID .. 353] = "봄버맨", -- Bomber Boy
    [C_ID .. 354] = "식품 완구", -- Crack Jacks
    [C_ID .. 355] = "엄마의 진주목걸이", -- Mom's Pearls
    [C_ID .. 356] = "자동차 건전지", -- Car Battery
    [C_ID .. 357] = "친구 상자", -- Box of Friends
    [C_ID .. 358] = "법사", -- The Wiz
    [C_ID .. 359] = "8인치 대못", -- 8 Inch Nails
    [C_ID .. 360] = "인큐버스", -- Incubus
    [C_ID .. 361] = "운명의 보상", -- Fate's Reward
    [C_ID .. 362] = "꼬마 상자", -- Lil Chest
    [C_ID .. 363] = "맹세한 수호자", -- Sworn Protector
    [C_ID .. 364] = "사랑과 우정 사이", -- Friend Zone
    [C_ID .. 365] = "길잃은 파리", -- Lost Fly
    [C_ID .. 366] = "분산형 폭탄", -- Scatter Bombs
    [C_ID .. 367] = "끈끈이 폭탄", -- Sticky Bombs
    [C_ID .. 368] = "유루증", -- Epiphora
    [C_ID .. 369] = "연속체", -- Continuum
    [C_ID .. 370] = "돌리 씨", -- Mr. Dolly
    [C_ID .. 371] = "탑의 저주", -- Curse of the Tower
    [C_ID .. 372] = "충전지 아기", -- Charged Baby
    [C_ID .. 373] = "명사수의 눈", -- Dead Eye
    [C_ID .. 374] = "신성한 빛", -- Holy Light
    [C_ID .. 375] = "호스트 모자", -- Host Hat
    [C_ID .. 376] = "재입고", -- Restock
    [C_ID .. 377] = "터진 알주머니", -- Bursting Sack
    [C_ID .. 378] = "똥싸개", -- No. 2
    [C_ID .. 379] = "두개의 눈동자", -- Pupula Duplex
    [C_ID .. 380] = "정액제", -- Pay To Play
    [C_ID .. 381] = "에덴의 축복", -- Eden's Blessing
    [C_ID .. 382] = "익숙한 공", -- Friendly Ball
    [C_ID .. 383] = "눈물 기폭제", -- Tear Detonator
    [C_ID .. 384] = "꼬마 거디", -- Lil Gurdy
    [C_ID .. 385] = "범보", -- Bumbo
    [C_ID .. 386] = "12면 주사위", -- D12
    [C_ID .. 387] = "향로", -- Censer
    [C_ID .. 388] = "열쇠 거지", -- Key Bum
    [C_ID .. 389] = "룬 가방", -- Rune Bag
    [C_ID .. 390] = "세라핌", -- Seraphim
    [C_ID .. 391] = "배신", -- Betrayal
    [C_ID .. 392] = "황도궁", -- Zodiac
    [C_ID .. 393] = "독뱀의 키스", -- Serpent's Kiss
    [C_ID .. 394] = "조준", -- Marked
    [C_ID .. 395] = "기계 X", -- Tech X
    [C_ID .. 396] = "심실 절단기", -- Ventricle Razor
    [C_ID .. 397] = "조종 광선", -- Tractor Beam
    [C_ID .. 398] = "신의 살점", -- God's Flesh
    [C_ID .. 399] = "공허의 구렁텅이", -- Maw of the Void
    [C_ID .. 400] = "운명의 창", -- Spear of Destiny
    [C_ID .. 401] = "폭발물", -- Explosivo
    [C_ID .. 402] = "혼돈", -- Chaos
    [C_ID .. 403] = "스파이더모드", -- Spider Mod
    [C_ID .. 404] = "방귀쟁이 아기", -- Farting Baby
    [C_ID .. 405] = "게임 버그", -- GB Bug
    [C_ID .. 406] = "8면 주사위", -- D8
    [C_ID .. 407] = "순도", -- Purity
    [C_ID .. 408] = "마법 단검", -- Athame
    [C_ID .. 409] = "빈 그릇", -- Empty Vessel
    [C_ID .. 410] = "악마의 눈", -- Evil Eye
    [C_ID .. 411] = "욕망의 피", -- Lusty Blood
    [C_ID .. 412] = "몽마의 자식들", -- Cambion Conception
    [C_ID .. 413] = "원죄없는 잉태", -- Immaculate Conception
    [C_ID .. 414] = "더 많은 선택권", -- More Options
    [C_ID .. 415] = "빛의 왕관", -- Crown Of Light
    [C_ID .. 416] = "넓은 가방", -- Deep Pockets
    [C_ID .. 417] = "서큐버스", -- Succubus
    [C_ID .. 418] = "과일 케이크", -- Fruit Cake
    [C_ID .. 419] = "순간이동 2.0", -- Teleport 2.0
    [C_ID .. 420] = "검은 가루", -- Black Powder
    [C_ID .. 421] = "강낭콩", -- Kidney Bean
    [C_ID .. 422] = "빛나는 모래시계", -- Glowing Hourglass
    [C_ID .. 423] = "보호의 고리", -- Circle of Protection
    [C_ID .. 424] = "자루 머리", -- Sack Head
    [C_ID .. 425] = "손전등", -- Night Light
    [C_ID .. 426] = "집착하는 추종자", -- Obsessed Fan
    [C_ID .. 427] = "마인크래프터", -- Mine Crafter
    [C_ID .. 428] = "잠옷", -- PJs
    [C_ID .. 429] = "키퍼의 머리", -- Head of the Keeper
    [C_ID .. 430] = "파리 아저씨", -- Papa Fly
    [C_ID .. 431] = "다차원 아기", -- Multidimensional Baby
    [C_ID .. 432] = "반짝이 폭탄", -- Glitter Bombs
    [C_ID .. 433] = "내 그림자", -- My Shadow
    [C_ID .. 434] = "파리 담은 병", -- Jar of Flies
    [C_ID .. 435] = "꼬마 로키", -- Lil Loki
    [C_ID .. 436] = "우유!", -- Milk!
    [C_ID .. 437] = "7면체 주사위", -- D7
    [C_ID .. 438] = "쪽쪽이", -- Binky
    [C_ID .. 439] = "엄마의 상자", -- Mom's Box
    [C_ID .. 440] = "신장 결석", -- Kidney Stone
    [C_ID .. 441] = "메가 블래스트", -- Mega Blast
    [C_ID .. 442] = "어둠 왕자의 왕관", -- Dark Prince's Crown
    [C_ID .. 443] = "사과!", -- Apple!
    [C_ID .. 444] = "연필", -- Lead Pencil
    [C_ID .. 445] = "개 이빨", -- Dog Tooth
    [C_ID .. 446] = "죽은 이빨", -- Dead Tooth
    [C_ID .. 447] = "납작한 콩", -- Linger Bean
    [C_ID .. 448] = "유리 조각", -- Shard of Glass
    [C_ID .. 449] = "강철판", -- Metal Plate
    [C_ID .. 450] = "탐욕의 눈", -- Eye of Greed
    [C_ID .. 451] = "타로 천", -- Tarot Cloth
    [C_ID .. 452] = "정맥류", -- Varicose Veins
    [C_ID .. 453] = "복합 골절", -- Compound Fracture
    [C_ID .. 454] = "다지증", -- Polydactyly
    [C_ID .. 455] = "아빠의 잃어버린 동전", -- Dad's Lost Coin
    [C_ID .. 456] = "곰팡이 핀 빵", -- Midnight Snack
    [C_ID .. 457] = "콘헤드", -- Cone Head
    [C_ID .. 458] = "배꼽", -- Belly Button
    [C_ID .. 459] = "축농증", -- Sinus Infection
    [C_ID .. 460] = "녹내장", -- Glaucoma
    [C_ID .. 461] = "기생자", -- Parasitoid
    [C_ID .. 462] = "벨리알의 눈", -- Eye of Belial
    [C_ID .. 463] = "황산", -- Sulfuric Acid
    [C_ID .. 464] = "균형의 문장", -- Glyph of Balance
    [C_ID .. 465] = "아날로그 스틱", -- Analog Stick
    [C_ID .. 466] = "전염병", -- Contagion
    [C_ID .. 467] = "손가락!", -- Finger!
    [C_ID .. 468] = "셰이드", -- Shade
    [C_ID .. 469] = "우울증", -- Depression
    [C_ID .. 470] = "허쉬", -- Hushy
    [C_ID .. 471] = "꼬마 몬스트로", -- Lil Monstro
    [C_ID .. 472] = "아기 왕", -- King Baby
    [C_ID .. 473] = "커다란 처비", -- Big Chubby
    [C_ID .. 474] = "부서진 유리 대포", -- Broken Glass Cannon
    [C_ID .. 475] = "플랜 C", -- Plan C
    [C_ID .. 476] = "1면 주사위", -- D1
    [C_ID .. 477] = "공허", -- Void
    [C_ID .. 478] = "일시정지", -- Pause
    [C_ID .. 479] = "용광로", -- Smelter
    [C_ID .. 480] = "퇴비", -- Compost
    [C_ID .. 481] = "데이터마이너", -- Dataminer
    [C_ID .. 482] = "클리커", -- Clicker
    [C_ID .. 483] = "맘마 메가!", -- Mama Mega!
    [C_ID .. 484] = "잠깐 뭐야?", -- Wait What?
    [C_ID .. 485] = "구부러진 동전", -- Crooked Penny
    [C_ID .. 486] = "무딘 면도칼", -- Dull Razor
    [C_ID .. 487] = "감자칼", -- Potato Peeler
    [C_ID .. 488] = "메트로놈", -- Metronome
    [C_ID .. 489] = "무한 주사위", -- D Infinity
    [C_ID .. 490] = "에덴의 영혼", -- Eden's Soul
    [C_ID .. 491] = "산성 아기", -- Acid Baby
    [C_ID .. 492] = "", -- YO LISTEN!
    [C_ID .. 493] = "아드레날린", -- Adrenaline
    [C_ID .. 494] = "야곱의 사다리", -- Jacob's Ladder
    [C_ID .. 495] = "고스트 페퍼", -- Ghost Pepper
    [C_ID .. 496] = "안락사", -- Euthanasia
    [C_ID .. 497] = "위장 속옷", -- Camo Undies
    [C_ID .. 498] = "이중성", -- Duality
    [C_ID .. 499] = "성찬", -- Eucharist
    [C_ID .. 500] = "자루 주머니", -- Sack of Sacks
    [C_ID .. 501] = "탐욕의 식도", -- Greed's Gullet
    [C_ID .. 502] = "대왕 여드름", -- Large Zit
    [C_ID .. 503] = "작은 뿔", -- Little Horn
    [C_ID .. 504] = "갈색 너겟", -- Brown Nugget
    [C_ID .. 505] = "포켓 GO", -- Poke Go
    [C_ID .. 506] = "배신자", -- Backstabber
    [C_ID .. 507] = "날카로운 빨대", -- Sharp Straw
    [C_ID .. 508] = "엄마의 면도칼", -- Mom's Razor
    [C_ID .. 509] = "피눈물 눈알", -- Bloodshot Eye
    [C_ID .. 510] = "정신착란", -- Delirious
    [C_ID .. 511] = "성난 파리", -- Angry Fly
    [C_ID .. 512] = "블랙홀", -- Black Hole
    [C_ID .. 513] = "멍청이", -- Bozo
    [C_ID .. 514] = "고장난 모뎀", -- Broken Modem
    [C_ID .. 515] = "수수께끼의 선물", -- Mystery Gift
    [C_ID .. 516] = "스프링클러", -- Sprinkler
    [C_ID .. 517] = "빠른 폭탄", -- Fast Bombs
    [C_ID .. 518] = "친구 든 상자", -- Buddy in a Box
    [C_ID .. 519] = "꼬마 델리리움", -- Lil Delirium
    [C_ID .. 520] = "점퍼 케이블", -- Jumper Cables
    [C_ID .. 521] = "쿠폰", -- Coupon
    [C_ID .. 522] = "염동력", -- Telekinesis
    [C_ID .. 523] = "수납상자", -- Moving Box
    [C_ID .. 524] = "기계장치 0", -- Technology Zero
    [C_ID .. 525] = "문둥병", -- Leprosy
    [C_ID .. 526] = "7개의 도장", -- 7 Seals
    [C_ID .. 527] = "미 씨!", -- Mr. ME!
    [C_ID .. 528] = "천사빛 프리즘", -- Angelic Prism
    [C_ID .. 529] = "뽁!", -- Pop!
    [C_ID .. 530] = "죽음의 살생부", -- Death's List
    [C_ID .. 531] = "피눈물병", -- Haemolacria
    [C_ID .. 532] = "눈물먹이", -- Lachryphagy
    [C_ID .. 533] = "삼성송", -- Trisagion
    [C_ID .. 534] = "책가방", -- Schoolbag
    [C_ID .. 535] = "담요", -- Blanket
    [C_ID .. 536] = "희생의 제단", -- Sacrificial Altar
    [C_ID .. 537] = "꼬마 구토쟁이", -- Lil Spewer
    [C_ID .. 538] = "구슬", -- Marbles
    [C_ID .. 539] = "이상한 알", -- Mystery Egg
    [C_ID .. 540] = "납작한 돌", -- Flat Stone
    [C_ID .. 541] = "골수", -- Marrow
    [C_ID .. 542] = "빠진 갈비뼈", -- Slipped Rib
    [C_ID .. 543] = "성지", -- Hallowed Ground
    [C_ID .. 544] = "날카로운 갈비뼈", -- Pointy Rib
    [C_ID .. 545] = "망자의 책", -- Book of the Dead
    [C_ID .. 546] = "아빠의 반지", -- Dad's Ring
    [C_ID .. 547] = "이혼 서류", -- Divorce Papers
    [C_ID .. 548] = "턱뼈", -- Jaw Bone
    [C_ID .. 549] = "최약골", -- Brittle Bones
    [C_ID .. 550] = "부러진 삽", -- Broken Shovel
    [C_ID .. 551] = "부러진 삽", -- Broken Shovel
    [C_ID .. 552] = "엄마의 삽", -- Mom's Shovel
    [C_ID .. 553] = "털곰팡이균", -- Mucormycosis
    [C_ID .. 554] = "넘나 무서운 것", -- 2Spooky
    [C_ID .. 555] = "황금 면도날", -- Golden Razor
    [C_ID .. 556] = "황", -- Sulfur
    [C_ID .. 557] = "포츈 쿠키", -- Fortune Cookie
    [C_ID .. 558] = "흉물", -- Eye Sore
    [C_ID .. 559] = "120 볼트", -- 120 Volt
    [C_ID .. 560] = "너무 아파", -- It Hurts
    [C_ID .. 561] = "아몬드 우유", -- Almond Milk
    [C_ID .. 562] = "밑바닥", -- Rock Bottom
    [C_ID .. 563] = "낸시 폭탄", -- Nancy Bombs
    [C_ID .. 564] = "비누 한 덩이", -- A Bar of Soap
    [C_ID .. 565] = "핏덩이 강아지", -- Blood Puppy
    [C_ID .. 566] = "드림캐쳐", -- Dream Catcher
    [C_ID .. 567] = "부활절 양초", -- Paschal Candle
    [C_ID .. 568] = "신의 개입", -- Divine Intervention
    [C_ID .. 569] = "피의 맹세", -- Blood Oath
    [C_ID .. 570] = "찰흙 쿠키", -- Playdough Cookie
    [C_ID .. 571] = "짝짝이 양말", -- Orphan Socks
    [C_ID .. 572] = "오컬트의 눈", -- Eye of the Occult
    [C_ID .. 573] = "원죄없는 심장", -- Immaculate Heart
    [C_ID .. 574] = "성광", -- Monstrance
    [C_ID .. 575] = "침입자", -- The Intruder
    [C_ID .. 576] = "더러운 군집", -- Dirty Mind
    [C_ID .. 577] = "다모클레스", -- Damocles
    [C_ID .. 578] = "공짜 레몬에이드", -- Free Lemonade
    [C_ID .. 579] = "영혼검", -- Spirit Sword
    [C_ID .. 580] = "붉은 열쇠", -- Red Key
    [C_ID .. 581] = "초능력 파리", -- Psy Fly
    [C_ID .. 582] = "어지러운 버섯", -- Wavy Cap
    [C_ID .. 583] = "로켓 든 병", -- Rocket in a Jar
    [C_ID .. 584] = "미덕의 책", -- Book of Virtues
    [C_ID .. 585] = "석고 옥합", -- Alabaster Box
    [C_ID .. 586] = "천국의 계단", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "태양", -- Sol
    [C_ID .. 589] = "달", -- Luna
    [C_ID .. 590] = "수성", -- Mercurius
    [C_ID .. 591] = "금성", -- Venus
    [C_ID .. 592] = "지구", -- Terra
    [C_ID .. 593] = "화성", -- Mars
    [C_ID .. 594] = "목성", -- Jupiter
    [C_ID .. 595] = "토성", -- Saturnus
    [C_ID .. 596] = "천왕성", -- Uranus
    [C_ID .. 597] = "해왕성", -- Neptunus
    [C_ID .. 598] = "명왕성", -- Pluto
    [C_ID .. 599] = "부두 머리", -- Voodoo Head
    [C_ID .. 600] = "점안약", -- Eye Drops
    [C_ID .. 601] = "참회의 기도", -- Act of Contrition
    [C_ID .. 602] = "멤버쉽 카드", -- Member Card
    [C_ID .. 603] = "배터리 팩", -- Battery Pack
    [C_ID .. 604] = "엄마의 팔찌", -- Mom's Bracelet
    [C_ID .. 605] = "둥근 숟갈", -- The Scooper
    [C_ID .. 606] = "오큘러 리프트", -- Ocular Rift
    [C_ID .. 607] = "종양 아기", -- Boiled Baby
    [C_ID .. 608] = "얼려버리는 아기", -- Freezer Baby
    [C_ID .. 609] = "이터널 주사위", -- Eternal D6
    [C_ID .. 610] = "새장", -- Bird Cage
    [C_ID .. 611] = "후두", -- Larynx
    [C_ID .. 612] = "잃어버린 영혼", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "혈액 폭탄", -- Blood Bombs
    [C_ID .. 615] = "꼬마 덤피", -- Lil Dumpy
    [C_ID .. 616] = "버즈아이", -- Bird's Eye
    [C_ID .. 617] = "자철석", -- Lodestone
    [C_ID .. 618] = "썩은 토마토", -- Rotten Tomato
    [C_ID .. 619] = "생득권", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "붉은 스튜", -- Red Stew
    [C_ID .. 622] = "창세기", -- Genesis
    [C_ID .. 623] = "날카로운 열쇠", -- Sharp Key
    [C_ID .. 624] = "부스터 팩", -- Booster Pack
    [C_ID .. 625] = "거대버섯", -- Mega Mush
    [C_ID .. 626] = "칼 조각 1", -- Knife Piece 1
    [C_ID .. 627] = "칼 조각 2", -- Knife Piece 2
    [C_ID .. 628] = "사망 증명서", -- Death Certificate
    [C_ID .. 629] = "로봇 파리", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "고기 도축칼", -- Meat Cleaver
    [C_ID .. 632] = "사악한 부적", -- Evil Charm
    [C_ID .. 633] = "신조", -- Dogma
    [C_ID .. 634] = "연옥", -- Purgatory
    [C_ID .. 635] = "봉제인형", -- Stitches
    [C_ID .. 636] = "R 키", -- R Key
    [C_ID .. 637] = "KO 물약", -- Knockout Drops
    [C_ID .. 638] = "지우개", -- Eraser
    [C_ID .. 639] = "역겨운 하트", -- Yuck Heart
    [C_ID .. 640] = "영혼의 항아리", -- Urn of Souls
    [C_ID .. 641] = "아겔다마", -- Akeldama
    [C_ID .. 642] = "마법의 피부", -- Magic Skin
    [C_ID .. 643] = "계시", -- Revelation
    [C_ID .. 644] = "위로상", -- Consolation Prize
    [C_ID .. 645] = "타이니토마", -- Tinytoma
    [C_ID .. 646] = "유황불 폭탄", -- Brimstone Bombs
    [C_ID .. 647] = "4.5볼트 건전지", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "탱탱한 플럼", -- Fruity Plum
    [C_ID .. 650] = "플럼 피리", -- Plum Flute
    [C_ID .. 651] = "베들레헴의 별", -- Star of Bethlehem
    [C_ID .. 652] = "큐브 아기", -- Cube Baby
    [C_ID .. 653] = "사탄아 물렀거라", -- Vade Retro
    [C_ID .. 654] = "위조 학위", -- False PHD
    [C_ID .. 655] = "룰렛 팽이", -- Spin to Win
    [C_ID .. 656] = "다모클레스", -- Damocles
    [C_ID .. 657] = "혈관염", -- Vasculitis
    [C_ID .. 658] = "거대한 세포", -- Giant Cell
    [C_ID .. 659] = "산동약", -- Tropicamide
    [C_ID .. 660] = "카드점", -- Card Reading
    [C_ID .. 661] = "다섯 쌍둥이", -- Quints
    [C_ID .. 662] = "평화주의자", -- 
    [C_ID .. 663] = "이빨과 손톱", -- Tooth and Nail
    [C_ID .. 664] = "폭식가", -- Binge Eater
    [C_ID .. 665] = "구피의 눈", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "밀짚인형", -- Strawman
    [C_ID .. 668] = "아빠의 쪽지", -- Dad's Note
    [C_ID .. 669] = "소세지", -- Sausage
    [C_ID .. 670] = "선택권?", -- Options?
    [C_ID .. 671] = "캔디 하트", -- Candy Heart
    [C_ID .. 672] = "살점 한 덩이", -- A Pound of Flesh
    [C_ID .. 673] = "회개", -- Redemption
    [C_ID .. 674] = "영혼의 족쇄", -- Spirit Shackles
    [C_ID .. 675] = "깨진 오브", -- Cracked Orb
    [C_ID .. 676] = "비어있는 심장", -- Empty Heart
    [C_ID .. 677] = "유체이탈", -- Astral Projection
    [C_ID .. 678] = "제왕절개", -- C Section
    [C_ID .. 679] = "꼬마 아바돈", -- Lil Abaddon
    [C_ID .. 680] = "몬테주마의 복수", -- Montezuma's Revenge
    [C_ID .. 681] = "꼬마 포탈", -- Lil Portal
    [C_ID .. 682] = "지렁이 친구", -- Worm Friend
    [C_ID .. 683] = "골국", -- Bone Spurs
    [C_ID .. 684] = "굶주린 영혼", -- Hungry Soul
    [C_ID .. 685] = "도깨비불 든 병", -- Jar of Wisps
    [C_ID .. 686] = "영혼 로켓", -- Soul Locket
    [C_ID .. 687] = "친구 찾기", -- Friend Finder
    [C_ID .. 688] = "내면의 아이", -- Inner Child
    [C_ID .. 689] = "글리치 왕관", -- Glitched Crown
    [C_ID .. 690] = "벨리 젤리", -- Belly Jelly
    [C_ID .. 691] = "성스러운 오브", -- Sacred Orb
    [C_ID .. 692] = "핏빛 결속", -- Sanguine Bond
    [C_ID .. 693] = "파리 군단", -- The Swarm
    [C_ID .. 694] = "비탄", -- Heartbreak
    [C_ID .. 695] = "피의 돌풍", -- Bloody Gust
    [C_ID .. 696] = "구원", -- Salvation
    [C_ID .. 697] = "사라진 쌍둥이", -- Vanishing Twin
    [C_ID .. 698] = "뒤틀린 한 쌍", -- Twisted Pair
    [C_ID .. 699] = "아자젤의 분노", -- Azazel's Rage
    [C_ID .. 700] = "반향효과", -- Echo Chamber
    [C_ID .. 701] = "아이작의 무덤", -- Isaac's Tomb
    [C_ID .. 702] = "복수심의 영혼", -- Vengeful Spirit
    [C_ID .. 703] = "에사우 주니어", -- Esau Jr.
    [C_ID .. 704] = "폭주!", -- Berserk!
    [C_ID .. 705] = "흑마술", -- Dark Arts
    [C_ID .. 706] = "무저갱", -- Abyss
    [C_ID .. 707] = "만찬", -- Supper
    [C_ID .. 708] = "스테이플러", -- Stapler
    [C_ID .. 709] = "수플렉스!", -- Suplex!
    [C_ID .. 710] = "조합 가방", -- Bag of Crafting
    [C_ID .. 711] = "뒤집기", -- Flip
    [C_ID .. 712] = "마도서 레메게톤", -- Lemegeton
    [C_ID .. 713] = "섬토리움", -- Sumptorium
    [C_ID .. 714] = "복귀", -- Recall
    [C_ID .. 715] = "저장", -- Hold
    [C_ID .. 716] = "키퍼의 자루", -- Keeper's Sack
    [C_ID .. 717] = "키퍼의 친척", -- Keeper's Kin
    [C_ID .. 718] = "키퍼의 망토", -- 
    [C_ID .. 719] = "키퍼의 상자", -- Keeper's Box
    [C_ID .. 720] = "모든 게 담긴 병", -- Everything Jar
    [C_ID .. 721] = "", -- TMTRAINER
    [C_ID .. 722] = "아니마 솔라", -- Anima Sola
    [C_ID .. 723] = "스핀다운 주사위", -- Spindown Dice
    [C_ID .. 724] = "과응고", -- Hypercoagulation
    [C_ID .. 725] = "", -- IBS
    [C_ID .. 726] = "각혈", -- Hemoptysis
    [C_ID .. 727] = "유령 폭탄", -- Ghost Bombs
    [C_ID .. 728] = "겔로", -- Gello
    [C_ID .. 729] = "참수 공격", -- Decap Attack
    [C_ID .. 730] = "의안", -- Glass Eye
    [C_ID .. 731] = "다래끼", -- Stye
    [C_ID .. 732] = "엄마의 반지", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "삼킨 동전", -- Swallowed Penny
    [T_ID .. 2] = "굳은 똥", -- Petrified Poop
    [T_ID .. 3] = "AAA 건전지", -- AAA Battery
    [T_ID .. 4] = "고장난 조종기", -- Broken Remote
    [T_ID .. 5] = "퍼플 하트 훈장", -- Purple Heart
    [T_ID .. 6] = "깨진 자석", -- Broken Magnet
    [T_ID .. 7] = "묵주 구슬", -- Rosary Bead
    [T_ID .. 8] = "카트리지", -- Cartridge
    [T_ID .. 9] = "파동벌레", -- Pulse Worm
    [T_ID .. 10] = "씰룩벌레", -- Wiggle Worm
    [T_ID .. 11] = "둥글벌레", -- Ring Worm
    [T_ID .. 12] = "납작벌레", -- Flat Worm
    [T_ID .. 13] = "상점 상품권", -- Store Credit
    [T_ID .. 14] = "굳은살", -- Callus
    [T_ID .. 15] = "행운의 돌조각", -- Lucky Rock
    [T_ID .. 16] = "엄마의 발톱", -- Mom's Toenail
    [T_ID .. 17] = "검은 립스틱", -- Black Lipstick
    [T_ID .. 18] = "성경 책자", -- Bible Tract
    [T_ID .. 19] = "종이 클립", -- Paper Clip
    [T_ID .. 20] = "원숭이 손", -- Monkey Paw
    [T_ID .. 21] = "신비한 종이", -- Mysterious Paper
    [T_ID .. 22] = "악마 꼬리", -- Daemon's Tail
    [T_ID .. 23] = "실종 포스터", -- Missing Poster
    [T_ID .. 24] = "똥전", -- Butt Penny
    [T_ID .. 25] = "이상한 초콜릿", -- Mysterious Candy
    [T_ID .. 26] = "꺾기벌레", -- Hook Worm
    [T_ID .. 27] = "채찍벌레", -- Whip Worm
    [T_ID .. 28] = "부서진 앙크", -- Broken Ankh
    [T_ID .. 29] = "생선 머리", -- Fish Head
    [T_ID .. 30] = "분홍 눈알", -- Pinky Eye
    [T_ID .. 31] = "고정핀", -- Push Pin
    [T_ID .. 32] = "환각버섯", -- Liberty Cap
    [T_ID .. 33] = "탯줄", -- Umbilical Cord
    [T_ID .. 34] = "아이의 심장", -- Child's Heart
    [T_ID .. 35] = "휘어진 뿔", -- Curved Horn
    [T_ID .. 36] = "녹슨 열쇠", -- Rusted Key
    [T_ID .. 37] = "염소 발굽", -- Goat Hoof
    [T_ID .. 38] = "엄마의 진주", -- Mom's Pearl
    [T_ID .. 39] = "암", -- Cancer
    [T_ID .. 40] = "빨간 누더기", -- Red Patch
    [T_ID .. 41] = "성냥개비", -- Match Stick
    [T_ID .. 42] = "행운의 발가락", -- Lucky Toe
    [T_ID .. 43] = "저주받은 해골", -- Cursed Skull
    [T_ID .. 44] = "안전 마개", -- Safety Cap
    [T_ID .. 45] = "스페이드 A", -- Ace of Spades
    [T_ID .. 46] = "아이작의 포크", -- Isaac's Fork
    [T_ID .. 47] = "The Polariod", -- 
    [T_ID .. 48] = "찢어진 페이지", -- A Missing Page
    [T_ID .. 49] = "피 묻은 동전", -- Bloody Penny
    [T_ID .. 50] = "타버린 동전", -- Burnt Penny
    [T_ID .. 51] = "납작한 동전", -- Flat Penny
    [T_ID .. 52] = "가짜 동전", -- Counterfeit Penny
    [T_ID .. 53] = "진드기", -- Tick
    [T_ID .. 54] = "아이작의 머리", -- Isaac's Head
    [T_ID .. 55] = "매기의 믿음", -- Maggy's Faith
    [T_ID .. 56] = "유다의 혀", -- Judas' Tongue
    [T_ID .. 57] = "???의 영혼", -- ???'s Soul
    [T_ID .. 58] = "삼손의 머리채", -- Samson's Lock
    [T_ID .. 59] = "카인의 오른쪽 눈", -- Cain's Eye
    [T_ID .. 60] = "이브의 새 다리", -- Eve's Bird Foot
    [T_ID .. 61] = "왼손목", -- The Left Hand
    [T_ID .. 62] = "빛나는 돌", -- Shiny Rock
    [T_ID .. 63] = "안전 가위", -- Safety Scissors
    [T_ID .. 64] = "무지개 벌레", -- Rainbow Worm
    [T_ID .. 65] = "테이프 벌레", -- Tape Worm
    [T_ID .. 66] = "게으른 벌레", -- Lazy Worm
    [T_ID .. 67] = "금이 간 주사위", -- Cracked Dice
    [T_ID .. 68] = "네오디뮴 자석", -- Super Magnet
    [T_ID .. 69] = "흐려진 즉석사진", -- Faded Polaroid
    [T_ID .. 70] = "머릿니", -- Louse
    [T_ID .. 71] = "밥의 방광", -- Bob's Bladder
    [T_ID .. 72] = "손목시계용 전지", -- Watch Battery
    [T_ID .. 73] = "폭파용 뇌관", -- Blasting Cap
    [T_ID .. 74] = "벽체 탐지기", -- Stud Finder
    [T_ID .. 75] = "오류", -- Error
    [T_ID .. 76] = "포커 칩", -- Poker Chip
    [T_ID .. 77] = "물집", -- Blister
    [T_ID .. 78] = "초침", -- Second Hand
    [T_ID .. 79] = "끝없는 무명", -- Endless Nameless
    [T_ID .. 80] = "검은 깃털", -- Black Feather
    [T_ID .. 81] = "눈먼 분노", -- Blind Rage
    [T_ID .. 82] = "황금 말발굽", -- Golden Horse Shoe
    [T_ID .. 83] = "상점 열쇠", -- Store Key
    [T_ID .. 84] = "그리드의 갈비뼈", -- Rib of Greed
    [T_ID .. 85] = "업보", -- Karma
    [T_ID .. 86] = "꼬마 라바", -- Lil Larva
    [T_ID .. 87] = "엄마의 로켓", -- Mom's Locket
    [T_ID .. 88] = "필요없어!", -- NO!
    [T_ID .. 89] = "미아 방지끈", -- Child Leash
    [T_ID .. 90] = "갈색 마개", -- Brown Cap
    [T_ID .. 91] = "태변", -- Meconium
    [T_ID .. 92] = "금이 간 왕관", -- Cracked Crown
    [T_ID .. 93] = "다 쓴 기저귀", -- Used Diaper
    [T_ID .. 94] = "생선 꼬리", -- Fish Tail
    [T_ID .. 95] = "검은 이빨", -- Black Tooth
    [T_ID .. 96] = "우주뱀 벌레", -- Ouroboros Worm
    [T_ID .. 97] = "편도선", -- Tonsil
    [T_ID .. 98] = "콧물딱지", -- Nose Goblin
    [T_ID .. 99] = "탱탱볼", -- Super Ball
    [T_ID .. 100] = "밝은 전구", -- Vibrant Bulb
    [T_ID .. 101] = "꺼진 전구", -- Dim Bulb
    [T_ID .. 102] = "조각난 카드", -- Fragmented Card
    [T_ID .. 103] = "똑같다!", -- Equality!
    [T_ID .. 104] = "창사골", -- Wish Bone
    [T_ID .. 105] = "점심 도시락", -- Bag Lunch
    [T_ID .. 106] = "잃어버린 코르크", -- Lost Cork
    [T_ID .. 107] = "까마귀 심장", -- Crow Heart
    [T_ID .. 108] = "호두", -- Walnut
    [T_ID .. 109] = "청테이프", -- Duct Tape
    [T_ID .. 110] = "은화", -- Silver Dollar
    [T_ID .. 111] = "피투성이 왕관", -- Bloody Crown
    [T_ID .. 112] = "과금전사", -- Pay To Win
    [T_ID .. 113] = "전쟁의 메뚜기", -- Locust of War
    [T_ID .. 114] = "역병의 메뚜기", -- Locust of Pestilence
    [T_ID .. 115] = "기근의 메뚜기", -- Locust of Famine
    [T_ID .. 116] = "죽음의 메뚜기", -- Locust of Death
    [T_ID .. 117] = "정복의 메뚜기", -- Locust of Conquest
    [T_ID .. 118] = "박쥐 날개", -- Bat Wing
    [T_ID .. 119] = "줄기 세포", -- Stem Cell
    [T_ID .. 120] = "머리핀", -- Hairpin
    [T_ID .. 121] = "나무 십자가", -- Wooden Cross
    [T_ID .. 122] = "버터!", -- Butter!
    [T_ID .. 123] = "세공 깃털", -- Filigree Feather
    [T_ID .. 124] = "문 받침대", -- Door Stop
    [T_ID .. 125] = "연장 코드", -- Extension Cord
    [T_ID .. 126] = "썩은 동전", -- Rotten Penny
    [T_ID .. 127] = "아기 초능력자", -- Baby-Bender
    [T_ID .. 128] = "손가락 뼈", -- Finger Bone
    [T_ID .. 129] = "눈깔사탕", -- Jawbreaker
    [T_ID .. 130] = "씹던 펜", -- Chewed Pen
    [T_ID .. 131] = "축복받은 동전", -- Blessed Penny
    [T_ID .. 132] = "깨진 주사기", -- Broken Syringe
    [T_ID .. 133] = "짧은 도화선", -- Short Fuse
    [T_ID .. 134] = "대왕 콩", -- Gigante Bean
    [T_ID .. 135] = "라이터", -- A Lighter
    [T_ID .. 136] = "부서진 자물쇠", -- Broken Padlock
    [T_ID .. 137] = "물망초", -- Myosotis
    [T_ID .. 138] = "", -- 'M
    [T_ID .. 139] = "눈물방울 부적", -- Teardrop Charm
    [T_ID .. 140] = "소돔의 사과", -- Apple of Sodom
    [T_ID .. 141] = "잊혀진 자장가", -- Forgotten Lullaby
    [T_ID .. 142] = "베다니의 축복", -- Beth's Faith
    [T_ID .. 143] = "오래된 축전기", -- Old Capacitor
    [T_ID .. 144] = "두뇌 벌레", -- Brain Worm
    [T_ID .. 145] = "올백", -- Perfection
    [T_ID .. 146] = "악마의 왕관", -- Devil's Crown
    [T_ID .. 147] = "충전된 동전", -- Charged Penny
    [T_ID .. 148] = "우정의 목걸이", -- Friendship Necklace
    [T_ID .. 149] = "패닉 버튼", -- Panic Button
    [T_ID .. 150] = "푸른 열쇠", -- Blue Key
    [T_ID .. 151] = "쇠줄", -- Flat File
    [T_ID .. 152] = "망원경 렌즈", -- Telescope Lens
    [T_ID .. 153] = "엄마의 머리뭉치", -- Mom's Lock
    [T_ID .. 154] = "주사위 가방", -- Dice Bag
    [T_ID .. 155] = "신성한 왕관", -- Holy Crown
    [T_ID .. 156] = "어머니의 키스", -- Mother's Kiss
    [T_ID .. 157] = "찢어진 카드", -- Torn Card
    [T_ID .. 158] = "찢어진 주머니", -- Torn Pocket
    [T_ID .. 159] = "도금 열쇠", -- Gilded Key
    [T_ID .. 160] = "복주머니", -- Lucky Sack
    [T_ID .. 161] = "사악한 왕관", -- Wicked Crown
    [T_ID .. 162] = "아자젤의 뿔대", -- Azazel's Stump
    [T_ID .. 163] = "딩글 베리", -- Dingle Berry
    [T_ID .. 164] = "딱총 화약", -- Ring Cap
    [T_ID .. 165] = "아니거든!", -- Nuh Uh!
    [T_ID .. 166] = "조형 찰흙", -- Modeling Clay
    [T_ID .. 167] = "연마한 뼈", -- Polished Bone
    [T_ID .. 168] = "텅 빈 심장", -- Hollow Heart
    [T_ID .. 169] = "아이의 그림", -- Kid's Drawing
    [T_ID .. 170] = "수정 열쇠", -- Crystal Key
    [T_ID .. 171] = "키퍼의 흥정", -- Keeper's Bargain
    [T_ID .. 172] = "저주받은 동전", -- Cursed Penny
    [T_ID .. 173] = "네 영혼", -- Your Soul
    [T_ID .. 174] = "숫자 자석", -- Number Magnet
    [T_ID .. 175] = "이상한 열쇠", -- Strange Key
    [T_ID .. 176] = "꼬마 클롯", -- Lil Clot
    [T_ID .. 177] = "스티커 문신", -- Temporary Tattoo
    [T_ID .. 178] = "삼킨 M80", -- Swallowed M80
    [T_ID .. 179] = "RC 리모콘", -- RC Remote
    [T_ID .. 180] = "되찾은 영혼", -- Found Soul
    [T_ID .. 181] = "확장팩", -- Expansion Pack
    [T_ID .. 182] = "베다니의 정수", -- Beth's Essence
    [T_ID .. 183] = "쌍둥이", -- The Twins
    [T_ID .. 184] = "입양 서류", -- Adoption Papers
    [T_ID .. 185] = "귀뚜라미 다리", -- Cricket Leg
    [T_ID .. 186] = "아폴리온의 절친", -- Apollyon's Best Friend
    [T_ID .. 187] = "깨진 안경", -- Broken Glasses
    [T_ID .. 188] = "얼음 큐브", -- Ice Cube
    [T_ID .. 189] = "바포메트의 인장", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - 바보", -- 0 - The Fool
    [Card_ID .. 2] = "I - 마법사", -- I - The Magician
    [Card_ID .. 3] = "II - 여교황", -- II - The High Priestess
    [Card_ID .. 4] = "III - 여제", -- III - The Empress
    [Card_ID .. 5] = "IV - 황제", -- IV - The Emperor
    [Card_ID .. 6] = "V - 교황", -- V - The Hierophant
    [Card_ID .. 7] = "VI - 연인", -- VI - The Lovers
    [Card_ID .. 8] = "VII - 전차", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - 정의", -- VIII - Justice
    [Card_ID .. 10] = "IX - 은둔자", -- IX - The Hermit
    [Card_ID .. 11] = "X - 운명의 수레바퀴", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - 힘", -- XI - Strength
    [Card_ID .. 13] = "XII - 매달린 남자", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - 죽음", -- XIII - Death
    [Card_ID .. 15] = "XIV - 절제", -- XIV - Temperance
    [Card_ID .. 16] = "XV - 악마", -- XV - The Devil
    [Card_ID .. 17] = "XVI - 탑", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - 별", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - 달", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - 해", -- XIX - The Sun
    [Card_ID .. 21] = "XX - 심판", -- XX - Judgement
    [Card_ID .. 22] = "XXI - 세계", -- XXI - The World
    [Card_ID .. 23] = "클로버 2", -- 2 of Clubs
    [Card_ID .. 24] = "다이아 2", -- 2 of Diamonds
    [Card_ID .. 25] = "스페이드 2", -- 2 of Spades
    [Card_ID .. 26] = "하트 2", -- 2 of Hearts
    [Card_ID .. 27] = "클로버 A", -- Ace of Clubs
    [Card_ID .. 28] = "다이아 A", -- Ace of Diamonds
    [Card_ID .. 29] = "스페이드 A", -- Ace of Spades
    [Card_ID .. 30] = "하트 A", -- Ace of Hearts
    [Card_ID .. 31] = "조커", -- Joker
    [Card_ID .. 32] = "하갈라즈", -- Hagalaz
    [Card_ID .. 33] = "제라", -- Jera
    [Card_ID .. 34] = "에와즈", -- Ehwaz
    [Card_ID .. 35] = "다가즈", -- Dagaz
    [Card_ID .. 36] = "엔수즈", -- Ansuz
    [Card_ID .. 37] = "페트로", -- Perthro
    [Card_ID .. 38] = "벨카노", -- Berkano
    [Card_ID .. 39] = "알기즈", -- Algiz
    [Card_ID .. 40] = "비어있는 룬", -- Blank Rune
    [Card_ID .. 41] = "검은 룬", -- Black Rune
    [Card_ID .. 42] = "혼돈 카드", -- Chaos Card
    [Card_ID .. 43] = "신용카드", -- Credit Card
    [Card_ID .. 44] = "규칙 카드", -- Rules Card
    [Card_ID .. 45] = "비인간적인 카드", -- A Card Against Humanity
    [Card_ID .. 46] = "자살 왕", -- Suicide King
    [Card_ID .. 47] = "감옥 탈출 카드", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "? 카드", -- ? Card
    [Card_ID .. 49] = "주사위 파편", -- Dice Shard
    [Card_ID .. 50] = "비상 연락처", -- Emergency Contact
    [Card_ID .. 51] = "신성한 카드", -- Holy Card
    [Card_ID .. 52] = "거대한 성장", -- Huge Growth
    [Card_ID .. 53] = "고대의 부름", -- Ancient Recall
    [Card_ID .. 54] = "시간 여행", -- Era Walk
    [Card_ID .. 55] = "룬 조각", -- Rune Shard
    [Card_ID .. 56] = "0 - 바보?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - 마법사?", -- I - The Magician?
    [Card_ID .. 58] = "II - 여교황?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - 여제?", -- III - The Empress?
    [Card_ID .. 60] = "IV - 황제?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - 교황?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - 연인?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - 전차?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - 정의?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - 은둔자?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - 운명의 수레바퀴?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - 힘?", -- XI - Strength?
    [Card_ID .. 68] = "XII - 매달린 남자?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - 죽음?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - 절제?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - 악마?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - 탑?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - 별?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - 달?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - 해?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - 심판?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - 세계?", -- XXI - The World?
    [Card_ID .. 78] = "깨진 열쇠", -- Cracked Key
    [Card_ID .. 79] = "하트 Q", -- Queen of Hearts
    [Card_ID .. 80] = "와일드 카드", -- Wild Card
    [Card_ID .. 81] = "아이작의 영혼", -- Soul of Isaac
    [Card_ID .. 82] = "막달레나의 영혼", -- Soul of Magdalene
    [Card_ID .. 83] = "카인의 영혼", -- Soul of Cain
    [Card_ID .. 84] = "유다의 영혼", -- Soul of Judas
    [Card_ID .. 85] = "???의 영혼", -- Soul of ???
    [Card_ID .. 86] = "이브의 영혼", -- Soul of Eve
    [Card_ID .. 87] = "삼손의 영혼", -- Soul of Samson
    [Card_ID .. 88] = "아자젤의 영혼", -- Soul of Azazel
    [Card_ID .. 89] = "나사로의 영혼", -- Soul of Lazarus
    [Card_ID .. 90] = "에덴의 영혼", -- Soul of Eden
    [Card_ID .. 91] = "로스트의 영혼", -- Soul of the Lost
    [Card_ID .. 92] = "릴리스의 영혼", -- Soul of Lilith
    [Card_ID .. 93] = "키퍼의 영혼", -- Soul of the Keeper
    [Card_ID .. 94] = "아폴리온의 영혼", -- Soul of Apollyon
    [Card_ID .. 95] = "포가튼의 영혼", -- Soul of the Forgotten
    [Card_ID .. 96] = "베서니의 영혼", -- Soul of Bethany
    [Card_ID .. 97] = "야곱과 에서의 영혼", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 0] = "질나쁜 방귀", -- Bad Gas
    [Pill_ID .. 1] = "질나쁜 환각", -- Bad Trip
    [Pill_ID .. 2] = "강철같은 알약", -- Balls of Steel
    [Pill_ID .. 3] = "폭탄은 곧 열쇠", -- Bombs are Key
    [Pill_ID .. 4] = "폭탄 설사", -- Explosive Diarrhea
    [Pill_ID .. 5] = "체력 회복", -- Full Health
    [Pill_ID .. 6] = "체력 감소", -- Health Down
    [Pill_ID .. 7] = "체력 증가", -- Health Up
    [Pill_ID .. 8] = "알약을 찾았어", -- I Found Pills
    [Pill_ID .. 9]  = "사춘기", -- Puberty
    [Pill_ID .. 10] = "멋진 파리", -- Pretty Fly
    [Pill_ID .. 11] = "사거리 감소", -- Range Down
    [Pill_ID .. 12] = "사거리 증가", -- Range Up
    [Pill_ID .. 13] = "이동속도 감소", -- Speed Down
    [Pill_ID .. 14] = "이동속도 증가", -- Speed Up
    [Pill_ID .. 15] = "연사 감소", -- Tears Down
    [Pill_ID .. 16] = "연사 증가", -- Tears Up
    [Pill_ID .. 17] = "행운 감소", -- Luck Down
    [Pill_ID .. 18] = "행운 증가", -- Luck Up
    [Pill_ID .. 19] = "순간이동약", -- Telepills
    [Pill_ID .. 20] = "48시간 풀충전!", -- 48 Hour Energy!
    [Pill_ID .. 21] = "토혈", -- Hematemesis
    [Pill_ID .. 22] = "마비", -- Paralysis
    [Pill_ID .. 23] = "모두 볼 수 있어!", -- I can see forever!
    [Pill_ID .. 24] = "페로몬", -- Pheromones
    [Pill_ID .. 25] = "건망증", -- Amnesia
    [Pill_ID .. 26] = "레몬 파티", -- Lemon Party
    [Pill_ID .. 27] = "님 마술43?", -- R U A Wizard?
    [Pill_ID .. 28] = "진통제!", -- Percs!
    [Pill_ID .. 29] = "과다복용!", -- Addicted!
    [Pill_ID .. 30] = "휴-식", -- Re-Lax
    [Pill_ID .. 31] = "???", -- ???
    [Pill_ID .. 32] = "커지는 알약", -- One makes you larger
    [Pill_ID .. 33] = "작아지는 알약", -- One makes you small
    [Pill_ID .. 34] = "감염!", -- Infested!
    [Pill_ID .. 35] = "감염?", -- Infested?
    [Pill_ID .. 36] = "최강 알약!", -- Power Pill!
    [Pill_ID .. 37] = "전자오락 시야경", -- Retro Vision
    [Pill_ID .. 38] = "마지막까지 친구야!", -- Friends Till The End!
    [Pill_ID .. 39] = "조절실패", -- X-Lax
    [Pill_ID .. 40] = "뭔가 잘못됐어...", -- Something's wrong...
    [Pill_ID .. 41] = "완전 지루해...", -- I'm Drowsy...
    [Pill_ID .. 42] = "완전 신나!!!", -- I'm Excited!!
    [Pill_ID .. 43] = "꿀꺽!", -- Gulp!
    [Pill_ID .. 44] = "퉤엣!", -- Horf!
    [Pill_ID .. 45] = "햇살 위를 걷는 기분이야!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 46] = "끄어억!", -- Vurp!
    [Pill_ID .. 47] = "탄속 감소", -- Shot speed Down
    [Pill_ID .. 48] = "탄속 증가", -- Shot speed Up
    [Pill_ID .. 49] = "실험용 알약", -- Experimental Pill
    [Pill_ID .. 9999] = "황금 알약", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])