-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "pl"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Smutna Cebula", -- The Sad Onion
    [C_ID .. 2] = "Wewnętrzne Oko", -- The Inner Eye
    [C_ID .. 3] = "Wygięta Łyżka", -- Spoon Bender
    [C_ID .. 4] = "Głowa Cricketa", -- Cricket's Head
    [C_ID .. 5] = "Moje Odbicie", -- My Reflection
    [C_ID .. 6] = "Numer Jeden", -- Number One
    [C_ID .. 7] = "Krew Męczennika", -- Blood of the Martyr
    [C_ID .. 8] = "Braciszek Robercik", -- Brother Bobby
    [C_ID .. 9] = "Skatol", -- Skatole
    [C_ID .. 10] = "Aureola z Much", -- Halo of Flies
    [C_ID .. 11] = "1up!", -- 1up!
    [C_ID .. 12] = "Magiczny Grzyb", -- Magic Mushroom
    [C_ID .. 13] = "Wirus", -- The Virus
    [C_ID .. 14] = "Furia na Sterydach", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Surowa Wątroba", -- Raw Liver
    [C_ID .. 17] = "Klucz Uniwersalny", -- Skeleton Key
    [C_ID .. 18] = "Dolar", -- A Dollar
    [C_ID .. 19] = "Bum!", -- Boom!
    [C_ID .. 20] = "Transcendencja", -- Transcendence
    [C_ID .. 21] = "Kompas", -- The Compass
    [C_ID .. 22] = "Drugie Śniadanie", -- Lunch
    [C_ID .. 23] = "Obiad", -- Dinner
    [C_ID .. 24] = "Deser", -- Dessert
    [C_ID .. 25] = "Śniadanie", -- Breakfast
    [C_ID .. 26] = "Zgniłe Mięso", -- Rotten Meat
    [C_ID .. 27] = "Drewniana Łyżka", -- Wooden Spoon
    [C_ID .. 28] = "Pas", -- The Belt
    [C_ID .. 29] = "Bielizna Mamy", -- Mom's Underwear
    [C_ID .. 30] = "Szpilki Mamy", -- Mom's Heels
    [C_ID .. 31] = "Szminka Mamy", -- Mom's Lipstick
    [C_ID .. 32] = "Druciany Wieszak", -- Wire Coat Hanger
    [C_ID .. 33] = "Biblia", -- The Bible
    [C_ID .. 34] = "Księga Beliala", -- The Book of Belial
    [C_ID .. 35] = "Nekronomikon", -- The Necronomicon
    [C_ID .. 36] = "Kupa", -- The Poop
    [C_ID .. 37] = "Pan Bum", -- Mr. Boom
    [C_ID .. 38] = "Głowa Tammy", -- Tammy's Head
    [C_ID .. 39] = "Stanik Mamy", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Podpaska Mamy", -- Mom's Pad
    [C_ID .. 42] = "Zgniły Łeb Boba", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teleport!", -- Teleport!
    [C_ID .. 45] = "Serduszko", -- Yum Heart
    [C_ID .. 46] = "Szczęśliwa Stopa", -- Lucky Foot
    [C_ID .. 47] = "Pilot Doktora", -- Doctor's Remote
    [C_ID .. 48] = "Strzała Kupidyna", -- Cupid's Arrow
    [C_ID .. 49] = "Shoop da Whoop!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagram", -- Pentagram
    [C_ID .. 52] = "Dr. Fetus", -- Dr. Fetus
    [C_ID .. 53] = "Magneto", -- Magneto
    [C_ID .. 54] = "Mapa Skarbów", -- Treasure Map
    [C_ID .. 55] = "Oko Mamy", -- Mom's Eye
    [C_ID .. 56] = "Wypadek z Cytryną", -- Lemon Mishap
    [C_ID .. 57] = "Podziw z Daleka", -- Distant Admiration
    [C_ID .. 58] = "Księga Cieni", -- Book of Shadows
    [C_ID .. 59] = "", -- The Book of Belial
    [C_ID .. 60] = "Drabina", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Urok Wampira", -- Charm of the Vampire
    [C_ID .. 63] = "Bateria", -- The Battery
    [C_ID .. 64] = "Wyprzedaż Steam", -- Steam Sale
    [C_ID .. 65] = "Książka Kucharska Anarchisty", -- Anarchist Cookbook
    [C_ID .. 66] = "Klepsydra", -- The Hourglass
    [C_ID .. 67] = "Siostra Madzia", -- Sister Maggy
    [C_ID .. 68] = "Technologia", -- Technology
    [C_ID .. 69] = "Mleko Czekoladowe", -- Chocolate Milk
    [C_ID .. 70] = "Hormony Wzrostu", -- Growth Hormones
    [C_ID .. 71] = "Mini Grzybek", -- Mini Mush
    [C_ID .. 72] = "Różaniec", -- Rosary
    [C_ID .. 73] = "Kostka Mięsa", -- Cube of Meat
    [C_ID .. 74] = "Ćwierćdolarówka", -- A Quarter
    [C_ID .. 75] = "Doktorat", -- PHD
    [C_ID .. 76] = "X-Ray w Oczach", -- X-Ray Vision
    [C_ID .. 77] = "Mój Mały Jednorożec", -- My Little Unicorn
    [C_ID .. 78] = "Księga Objawień", -- Book of Revelations
    [C_ID .. 79] = "Znak", -- The Mark
    [C_ID .. 80] = "Pakt", -- The Pact
    [C_ID .. 81] = "Martwy Kot", -- Dead Cat
    [C_ID .. 82] = "Pan Otchłani", -- Lord of the Pit
    [C_ID .. 83] = "Gwóźdź", -- The Nail
    [C_ID .. 84] = "Musimy Kopać Dalej!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Talia Kart", -- Deck of Cards
    [C_ID .. 86] = "Ząb Monstro", -- Monstro's Tooth
    [C_ID .. 87] = "Rogi Loki'ego", -- Loki's Horns
    [C_ID .. 88] = "Mały Chubby", -- Little Chubby
    [C_ID .. 89] = "Ugryzienie Pająka", -- Spider Bite
    [C_ID .. 90] = "Kamyczek", -- The Small Rock
    [C_ID .. 91] = "Czapka Speleologa", -- Spelunker Hat
    [C_ID .. 92] = "Super Bandaż", -- Super Bandage
    [C_ID .. 93] = "Gamekid", -- The Gamekid
    [C_ID .. 94] = "Sakiewa z Monetami", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Dziecko", -- Robo-Baby
    [C_ID .. 96] = "Mały C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "Księga Grzechu", -- The Book of Sin
    [C_ID .. 98] = "Relikt", -- The Relic
    [C_ID .. 99] = "Mały Gish", -- Little Gish
    [C_ID .. 100] = "Mały Steven", -- Little Steven
    [C_ID .. 101] = "Aureola", -- The Halo
    [C_ID .. 102] = "Butelka Pigułek Mamy", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Przeziębienie", -- The Common Cold
    [C_ID .. 104] = "Pasożyt", -- The Parasite
    [C_ID .. 105] = "D6", -- The D6
    [C_ID .. 106] = "Pan Mega", -- Mr. Mega
    [C_ID .. 107] = "Nożyce do Tkaniny", -- The Pinking Shears
    [C_ID .. 108] = "Opłatek", -- The Wafer
    [C_ID .. 109] = "Pieniądze = Siła", -- Money = Power
    [C_ID .. 110] = "Soczewki Mamy", -- Mom's Contacts
    [C_ID .. 111] = "Fasola", -- The Bean
    [C_ID .. 112] = "Anioł Stróż", -- Guardian Angel
    [C_ID .. 113] = "Demoniczne Dziecko", -- Demon Baby
    [C_ID .. 114] = "Nóż Mamy", -- Mom's Knife
    [C_ID .. 115] = "Plansza Ouija", -- Ouija Board
    [C_ID .. 116] = "Bateria 9V", -- 9 Volt
    [C_ID .. 117] = "Martwy Ptak", -- Dead Bird
    [C_ID .. 118] = "Ogień Piekielny", -- Brimstone
    [C_ID .. 119] = "Worek na Krew", -- Blood Bag
    [C_ID .. 120] = "Dziwaczny Grzyb", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Dziwny Grzyb", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Nierządnica z Babilonu", -- Whore of Babylon
    [C_ID .. 123] = "Księga Potworów", -- Monster Manual
    [C_ID .. 124] = "Zwoje znad Morza Martwego", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bomba", -- Bobby-Bomb
    [C_ID .. 126] = "Żyletka", -- Razor Blade
    [C_ID .. 127] = "Zapominajka", -- Forget Me Now
    [C_ID .. 128] = "Wiecznie Samotny", -- Forever Alone
    [C_ID .. 129] = "Wiadro Smalcu", -- Bucket of Lard
    [C_ID .. 130] = "Kucyk", -- A Pony
    [C_ID .. 131] = "Torba na Bomby", -- Bomb Bag
    [C_ID .. 132] = "Bryła Węgla", -- A Lump of Coal
    [C_ID .. 133] = "Łapka Guppy'ego", -- Guppy's Paw
    [C_ID .. 134] = "Ogon Guppy'ego", -- Guppy's Tail
    [C_ID .. 135] = "Kroplówka", -- IV Bag
    [C_ID .. 136] = "Najlepszy Przyjaciel", -- Best Friend
    [C_ID .. 137] = "Zdalny Detonator", -- Remote Detonator
    [C_ID .. 138] = "Znamię", -- Stigmata
    [C_ID .. 139] = "Torebka Mamy", -- Mom's Purse
    [C_ID .. 140] = "Przekleństwo Boba", -- Bob's Curse
    [C_ID .. 141] = "Balowy Chłopak", -- Pageant Boy
    [C_ID .. 142] = "Szkaplerz", -- Scapular
    [C_ID .. 143] = "Mieszanka", -- Speed Ball
    [C_ID .. 144] = "Przybłęda", -- Bum Friend
    [C_ID .. 145] = "Głowa Guppy'ego", -- Guppy's Head
    [C_ID .. 146] = "Modlitewnik", -- Prayer Card
    [C_ID .. 147] = "Karbowana Siekiera", -- Notched Axe
    [C_ID .. 148] = "Zarażenie", -- Infestation
    [C_ID .. 149] = "Wymiotnica", -- Ipecac
    [C_ID .. 150] = "Miłosne Poświęcenie", -- Tough Love
    [C_ID .. 151] = "Mucharz", -- The Mulligan
    [C_ID .. 152] = "Technologia 2", -- Technology 2
    [C_ID .. 153] = "Zmutowany Pająk", -- Mutant Spider
    [C_ID .. 154] = "Peeling Chemiczny", -- Chemical Peel
    [C_ID .. 155] = "Podglądacz", -- The Peeper
    [C_ID .. 156] = "Habit", -- Habit
    [C_ID .. 157] = "Krwawa Żądza", -- Bloody Lust
    [C_ID .. 158] = "Kryształowa Kula", -- Crystal Ball
    [C_ID .. 159] = "Duch Nocy", -- Spirit of the Night
    [C_ID .. 160] = "Rozerwanie Nieba", -- Crack the Sky
    [C_ID .. 161] = "Anch", -- Ankh
    [C_ID .. 162] = "Krzyż Celtycki", -- Celtic Cross
    [C_ID .. 163] = "Dziecko-Duch", -- Ghost Baby
    [C_ID .. 164] = "Świeca", -- The Candle
    [C_ID .. 165] = "Kańczug", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Arlekinowe Dziecko", -- Harlequin Baby
    [C_ID .. 168] = "Epicki Fetus", -- Epic Fetus
    [C_ID .. 169] = "Polifem", -- Polyphemus
    [C_ID .. 170] = "Tatuś Kosarzy", -- Daddy Longlegs
    [C_ID .. 171] = "Tyłek Pająka", -- Spider Butt
    [C_ID .. 172] = "Sztylet Ofiarny", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitra", -- Mitre
    [C_ID .. 174] = "Tęczowe Dziecko", -- Rainbow Baby
    [C_ID .. 175] = "Klucz Taty", -- Dad's Key
    [C_ID .. 176] = "Komórki Macierzyste", -- Stem Cells
    [C_ID .. 177] = "Przenośny Automat", -- Portable Slot
    [C_ID .. 178] = "Woda Święcona", -- Holy Water
    [C_ID .. 179] = "Przeznaczenie", -- Fate
    [C_ID .. 180] = "Czarna Fasola", -- The Black Bean
    [C_ID .. 181] = "Biały Kucyk", -- White Pony
    [C_ID .. 182] = "Najświętsze Serce", -- Sacred Heart
    [C_ID .. 183] = "Wykałaczki", -- Tooth Picks
    [C_ID .. 184] = "Święty Graal", -- Holy Grail
    [C_ID .. 185] = "Martwy Gołąb", -- Dead Dove
    [C_ID .. 186] = "Prawo Krwi", -- Blood Rights
    [C_ID .. 187] = "Kłaczek Guppy'ego", -- Guppy's Hairball
    [C_ID .. 188] = "Abel", -- Abel
    [C_ID .. 189] = "Super Fan SMB", -- SMB Super Fan
    [C_ID .. 190] = "Piromania", -- Pyro
    [C_ID .. 191] = "Banknot 3 Dolarowy", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepatia Dla Opornych", -- Telepathy for Dummies
    [C_ID .. 193] = "MIĘSO!", -- MEAT!
    [C_ID .. 194] = "Magiczna Kula nr 8", -- Magic 8 Ball
    [C_ID .. 195] = "Portmonetka Mamy", -- Mom's Coin Purse
    [C_ID .. 196] = "Gniotek", -- Squeezy
    [C_ID .. 197] = "Sok z Winogron", -- Jesus Juice
    [C_ID .. 198] = "Pudełko", -- Box
    [C_ID .. 199] = "Klucz Mamy", -- Mom's Key
    [C_ID .. 200] = "Cień do Powiek Mamy", -- Mom's Eyeshadow
    [C_ID .. 201] = "Sztabka Żelaza", -- Iron Bar
    [C_ID .. 202] = "Dotyk Midasa", -- Midas' Touch
    [C_ID .. 203] = "Pokorny Pakiet", -- Humbleing Bundle
    [C_ID .. 204] = "Nerka", -- Fanny Pack
    [C_ID .. 205] = "Ostra Wtyczka", -- Sharp Plug
    [C_ID .. 206] = "Gilotyna", -- Guillotine
    [C_ID .. 207] = "Kula z Bandaży", -- Ball of Bandages
    [C_ID .. 208] = "Pas Mistrza", -- Champion Belt
    [C_ID .. 209] = "Dupne Bomby", -- Butt Bombs
    [C_ID .. 210] = "Nadgryziony Listek", -- Gnawed Leaf
    [C_ID .. 211] = "Pajęcze Dziecię", -- Spiderbaby
    [C_ID .. 212] = "Obroża Guppy'ego", -- Guppy's Collar
    [C_ID .. 213] = "Zgubiona Soczewka", -- Lost Contact
    [C_ID .. 214] = "Anemik", -- Anemic
    [C_ID .. 215] = "Kozia Głowa", -- Goat Head
    [C_ID .. 216] = "Szaty Ceremonialne", -- Ceremonial Robes
    [C_ID .. 217] = "Peruka Mamy", -- Mom's Wig
    [C_ID .. 218] = "Łożysko", -- Placenta
    [C_ID .. 219] = "Stary Bandaż", -- Old Bandage
    [C_ID .. 220] = "Smutne Bomby", -- Sad Bombs
    [C_ID .. 221] = "Klej Kauczukowy", -- Rubber Cement
    [C_ID .. 222] = "Antygrawitacja", -- Anti-Gravity
    [C_ID .. 223] = "Piroman", -- Pyromaniac
    [C_ID .. 224] = "Ciało Cricketa", -- Cricket's Body
    [C_ID .. 225] = "Pokraka", -- Gimpy
    [C_ID .. 226] = "Czarny Lotos", -- Black Lotus
    [C_ID .. 227] = "Świnka Skarbonka", -- Piggy Bank
    [C_ID .. 228] = "Perfumy Mamy", -- Mom's Perfume
    [C_ID .. 229] = "Płuco Monstro", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Kulka Smoły", -- Ball of Tar
    [C_ID .. 232] = "Stop-Er", -- Stop Watch
    [C_ID .. 233] = "Tycia Planeta", -- Tiny Planet
    [C_ID .. 234] = "Zarażenie 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "Pałeczka Okrężnicy", -- E. Coli
    [C_ID .. 237] = "Dotyk Śmierci", -- Death's Touch
    [C_ID .. 238] = "Fragment Klucza 1", -- Key Piece 1
    [C_ID .. 239] = "Fragment Klucza 2", -- Key Piece 2
    [C_ID .. 240] = "Terapia Eksperymentalna", -- Experimental Treatment
    [C_ID .. 241] = "Kontrakt Spod Ziemi", -- Contract from Below
    [C_ID .. 242] = "Niesława", -- Infamy
    [C_ID .. 243] = "Tarcza Trójcy", -- Trinity Shield
    [C_ID .. 244] = "Tech.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Niebieska Mapa", -- Blue Map
    [C_ID .. 247] = "BFFS!", -- BFFS!
    [C_ID .. 248] = "Jeden Umysł", -- Hive Mind
    [C_ID .. 249] = "Istnieją Możliwości", -- There's Options
    [C_ID .. 250] = "Druga Bomba Gratis", -- Bogo Bombs
    [C_ID .. 251] = "Talia Startowa", -- Starter Deck
    [C_ID .. 252] = "Torebeczka", -- Little Baggy
    [C_ID .. 253] = "Magiczny Strup", -- Magic Scab
    [C_ID .. 254] = "Zakrzep", -- Blood Clot
    [C_ID .. 255] = "Śrubka", -- Screw
    [C_ID .. 256] = "Gorące Bomby", -- Hot Bombs
    [C_ID .. 257] = "Płomienny Umysł", -- Fire Mind
    [C_ID .. 258] = "Missing No.", -- Missing No.
    [C_ID .. 259] = "Ciemna Materia", -- Dark Matter
    [C_ID .. 260] = "Czarna Świeca", -- Black Candle
    [C_ID .. 261] = "Wytrzeszcz", -- Proptosis
    [C_ID .. 262] = "Zgubiona Kartka 2", -- Missing Page 2
    [C_ID .. 263] = "Przejrzysta Runa", -- Clear Rune
    [C_ID .. 264] = "Mądra Muszka", -- Smart Fly
    [C_ID .. 265] = "Bezwodnik", -- Dry Baby
    [C_ID .. 266] = "Soczysty Wór", -- Juicy Sack
    [C_ID .. 267] = "Robo-Dziecko 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Zgniłe Dziecko", -- Rotten Baby
    [C_ID .. 269] = "Bezgłowe Dziecko", -- Headless Baby
    [C_ID .. 270] = "Pijawka", -- Leech
    [C_ID .. 271] = "Sakiewka Tajemnic", -- Mystery Sack
    [C_ID .. 272] = "DPM", -- BBF
    [C_ID .. 273] = "Mózg Boba", -- Bob's Brain
    [C_ID .. 274] = "Najlepszy Kumpel", -- Best Bud
    [C_ID .. 275] = "Mały Piekielnik", -- Lil Brimstone
    [C_ID .. 276] = "Serce Izaaka", -- Isaac's Heart
    [C_ID .. 277] = "Straszak", -- Lil Haunt
    [C_ID .. 278] = "Mroczny Przybłęda", -- Dark Bum
    [C_ID .. 279] = "Duży Fan", -- Big Fan
    [C_ID .. 280] = "Siostrzyczka Kosarzy", -- Sissy Longlegs
    [C_ID .. 281] = "Kumpel Do Bicia", -- Punching Bag
    [C_ID .. 282] = "Poradnik do Skakania", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Czysta Karta", -- Blank Card
    [C_ID .. 287] = "Księga Tajemnic", -- Book of Secrets
    [C_ID .. 288] = "Pudełko Pająków", -- Box of Spiders
    [C_ID .. 289] = "Czerwona Świeca", -- Red Candle
    [C_ID .. 290] = "Słoik", -- The Jar
    [C_ID .. 291] = "Spłuczka!", -- Flush!
    [C_ID .. 292] = "Biblia Szatana", -- Satanic Bible
    [C_ID .. 293] = "Głowa Krampusa", -- Head of Krampus
    [C_ID .. 294] = "Maślana Fasola", -- Butter Bean
    [C_ID .. 295] = "Cudowne Pudełeczko", -- Magic Fingers
    [C_ID .. 296] = "Przetwornik", -- Converter
    [C_ID .. 297] = "Puszka Pandory", -- Pandora's Box
    [C_ID .. 298] = "Odłamek Jednorożca", -- Unicorn Stump
    [C_ID .. 299] = "Byk", -- Taurus
    [C_ID .. 300] = "Baran", -- Aries
    [C_ID .. 301] = "Rak", -- Cancer
    [C_ID .. 302] = "Lew", -- Leo
    [C_ID .. 303] = "Panna", -- Virgo
    [C_ID .. 304] = "Waga", -- Libra
    [C_ID .. 305] = "Skorpion", -- Scorpio
    [C_ID .. 306] = "Strzelec", -- Sagittarius
    [C_ID .. 307] = "Koziorożec", -- Capricorn
    [C_ID .. 308] = "Wodnik", -- Aquarius
    [C_ID .. 309] = "Ryby", -- Pisces
    [C_ID .. 310] = "Maskara Ewy", -- Eve's Mascara
    [C_ID .. 311] = "Cień Judasza", -- Judas' Shadow
    [C_ID .. 312] = "Kokardka Madzi", -- Maggy's Bow
    [C_ID .. 313] = "Święte Okrycie", -- Holy Mantle
    [C_ID .. 314] = "Masywne Uda", -- Thunder Thighs
    [C_ID .. 315] = "Nietypowy Przyciągacz", -- Strange Attractor
    [C_ID .. 316] = "Przeklęte Oko", -- Cursed Eye
    [C_ID .. 317] = "Tajemnicza Ciecz", -- Mysterious Liquid
    [C_ID .. 318] = "Bliźnięta", -- Gemini
    [C_ID .. 319] = "Drugie Oko Kaina", -- Cain's Other Eye
    [C_ID .. 320] = "Jedyny Przyjaciel ???", -- ???'s Only Friend
    [C_ID .. 321] = "Łańcuch Samsona", -- Samson's Chains
    [C_ID .. 322] = "Mały Naśladowca", -- Mongo Baby
    [C_ID .. 323] = "Łzy Izaaka", -- Isaac's Tears
    [C_ID .. 324] = "Niezdefiniowane", -- Undefined
    [C_ID .. 325] = "Nożyczki", -- Scissors
    [C_ID .. 326] = "Tchnienie Życia", -- Breath of Life
    [C_ID .. 327] = "Polaroid", -- The Polaroid
    [C_ID .. 328] = "Negatyw", -- The Negative
    [C_ID .. 329] = "Technika Ludovica", -- The Ludovico Technique
    [C_ID .. 330] = "Mleko Sojowe", -- Soy Milk
    [C_ID .. 331] = "Bóstwo", -- Godhead
    [C_ID .. 332] = "Łachmany Łazarza", -- Lazarus' Rags
    [C_ID .. 333] = "Umysł", -- The Mind
    [C_ID .. 334] = "Ciało", -- The Body
    [C_ID .. 335] = "Dusza", -- The Soul
    [C_ID .. 336] = "Martwa Cebula", -- Dead Onion
    [C_ID .. 337] = "Zepsuty Zegarek", -- Broken Watch
    [C_ID .. 338] = "Bumerang", -- The Boomerang
    [C_ID .. 339] = "Agrafka", -- Safety Pin
    [C_ID .. 340] = "Kofeina w Kapsułce", -- Caffeine Pill
    [C_ID .. 341] = "Rozdarte Zdjęcie", -- Torn Photo
    [C_ID .. 342] = "Niebieściak", -- Blue Cap
    [C_ID .. 343] = "Klucz od Mieszkania", -- Latch Key
    [C_ID .. 344] = "Pudełko Zapałek", -- Match Book
    [C_ID .. 345] = "Synthol", -- Synthoil
    [C_ID .. 346] = "Przekąska", -- A Snack
    [C_ID .. 347] = "Diplopia", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Drewniany Pieniążek", -- Wooden Nickel
    [C_ID .. 350] = "Wstrząs Toksyczny", -- Toxic Shock
    [C_ID .. 351] = "Mega Fasola", -- Mega Bean
    [C_ID .. 352] = "Szklana Armata", -- Glass Cannon
    [C_ID .. 353] = "Bombowy Chłopak", -- Bomber Boy
    [C_ID .. 354] = "Przysmak z Niespodzianką", -- Crack Jacks
    [C_ID .. 355] = "Perły Mamy", -- Mom's Pearls
    [C_ID .. 356] = "Akumulator Samochodowy", -- Car Battery
    [C_ID .. 357] = "Pudełko z Przyjaciółmi", -- Box of Friends
    [C_ID .. 358] = "Czaruś", -- The Wiz
    [C_ID .. 359] = "Stalowe Gwoździe", -- 8 Inch Nails
    [C_ID .. 360] = "Inkub", -- Incubus
    [C_ID .. 361] = "Nagroda od Losu", -- Fate's Reward
    [C_ID .. 362] = "Skrzyneczka", -- Lil Chest
    [C_ID .. 363] = "Zaprzysiężony Obrońca", -- Sworn Protector
    [C_ID .. 364] = "Strefa Przyjaźni", -- Friend Zone
    [C_ID .. 365] = "Utracona Mucha", -- Lost Fly
    [C_ID .. 366] = "Bomby Rozpryskowe", -- Scatter Bombs
    [C_ID .. 367] = "Lepkie Bomby", -- Sticky Bombs
    [C_ID .. 368] = "Łzawienie", -- Epiphora
    [C_ID .. 369] = "Kontinuum", -- Continuum
    [C_ID .. 370] = "Pan Laleczka", -- Mr. Dolly
    [C_ID .. 371] = "Klątwa Wieży", -- Curse of the Tower
    [C_ID .. 372] = "Energiczne Dziecko", -- Charged Baby
    [C_ID .. 373] = "Prosto w Cel", -- Dead Eye
    [C_ID .. 374] = "Święta Światłość", -- Holy Light
    [C_ID .. 375] = "Kapelusz Żywiciela", -- Host Hat
    [C_ID .. 376] = "Uzupełniacz", -- Restock
    [C_ID .. 377] = "Pękający Wór", -- Bursting Sack
    [C_ID .. 378] = "Numer Dwa", -- No. 2
    [C_ID .. 379] = "Podwójna Źrenica", -- Pupula Duplex
    [C_ID .. 380] = "Płać By Grać", -- Pay To Play
    [C_ID .. 381] = "Błogosławieństwo Edena", -- Eden's Blessing
    [C_ID .. 382] = "Kula Przyjaźni", -- Friendly Ball
    [C_ID .. 383] = "Detonator Łez", -- Tear Detonator
    [C_ID .. 384] = "Tyci Gurdy", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Kadzielnica", -- Censer
    [C_ID .. 388] = "Klucznik", -- Key Bum
    [C_ID .. 389] = "Wór na Runy", -- Rune Bag
    [C_ID .. 390] = "Serafin", -- Seraphim
    [C_ID .. 391] = "Zdrada", -- Betrayal
    [C_ID .. 392] = "Zodiak", -- Zodiac
    [C_ID .. 393] = "Pocałunek Węża", -- Serpent's Kiss
    [C_ID .. 394] = "Oznaczony", -- Marked
    [C_ID .. 395] = "Tech X", -- Tech X
    [C_ID .. 396] = "Przekrojowa Brzytwa", -- Ventricle Razor
    [C_ID .. 397] = "Wiązka Holownicza", -- Tractor Beam
    [C_ID .. 398] = "Święty Grzyb", -- God's Flesh
    [C_ID .. 399] = "Paszcza z Pustki", -- Maw of the Void
    [C_ID .. 400] = "Włócznia Przeznaczenia", -- Spear of Destiny
    [C_ID .. 401] = "Explosivo", -- Explosivo
    [C_ID .. 402] = "Chaos", -- Chaos
    [C_ID .. 403] = "Spider Mod", -- Spider Mod
    [C_ID .. 404] = "Pierdzący Dzieciak", -- Farting Baby
    [C_ID .. 405] = "GB Bug", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Czystość", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Puste Naczynie", -- Empty Vessel
    [C_ID .. 410] = "Złe Oko", -- Evil Eye
    [C_ID .. 411] = "Żądna Krew", -- Lusty Blood
    [C_ID .. 412] = "Poczęcie Kambiona", -- Cambion Conception
    [C_ID .. 413] = "Niepokalane Poczęcie", -- Immaculate Conception
    [C_ID .. 414] = "Więcej Możliwości", -- More Options
    [C_ID .. 415] = "Korona Światłości", -- Crown Of Light
    [C_ID .. 416] = "Głębokie Kieszenie", -- Deep Pockets
    [C_ID .. 417] = "Sukkub", -- Succubus
    [C_ID .. 418] = "Ciasto Owocowe", -- Fruit Cake
    [C_ID .. 419] = "Teleport 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Czarny Proszek", -- Black Powder
    [C_ID .. 421] = "Fasola Nerkowata", -- Kidney Bean
    [C_ID .. 422] = "Świecąca Klepsydra", -- Glowing Hourglass
    [C_ID .. 423] = "Okrąg Ochrony", -- Circle of Protection
    [C_ID .. 424] = "Sakiewkowa Głowa", -- Sack Head
    [C_ID .. 425] = "Lampka Nocna", -- Night Light
    [C_ID .. 426] = "Fan z Obsesją", -- Obsessed Fan
    [C_ID .. 427] = "Górnik", -- Mine Crafter
    [C_ID .. 428] = "Piżamka", -- PJs
    [C_ID .. 429] = "Głowa Dozorcy", -- Head of the Keeper
    [C_ID .. 430] = "Tata-Mucha", -- Papa Fly
    [C_ID .. 431] = "Wielowymiarowe Dziecko", -- Multidimensional Baby
    [C_ID .. 432] = "Brokatowe Bomby", -- Glitter Bombs
    [C_ID .. 433] = "Mój Cień", -- My Shadow
    [C_ID .. 434] = "Słój na Muchy", -- Jar of Flies
    [C_ID .. 435] = "Mały Loki", -- Lil Loki
    [C_ID .. 436] = "Mleko!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Smoczek", -- Binky
    [C_ID .. 439] = "Pudełko Mamy", -- Mom's Box
    [C_ID .. 440] = "Kamień Nerkowy", -- Kidney Stone
    [C_ID .. 441] = "Mega Strzał", -- Mega Blast
    [C_ID .. 442] = "Korona Księcia Mroku", -- Dark Prince's Crown
    [C_ID .. 443] = "Jabłko!", -- Apple!
    [C_ID .. 444] = "Ołówek", -- Lead Pencil
    [C_ID .. 445] = "Psi Ząb", -- Dog Tooth
    [C_ID .. 446] = "Martwy Ząb", -- Dead Tooth
    [C_ID .. 447] = "Uporczywa Fasola", -- Linger Bean
    [C_ID .. 448] = "Kawałek Szkła", -- Shard of Glass
    [C_ID .. 449] = "Płyta Metalowa", -- Metal Plate
    [C_ID .. 450] = "Chciwe Oko", -- Eye of Greed
    [C_ID .. 451] = "Obrus do Tarota", -- Tarot Cloth
    [C_ID .. 452] = "Żylaki", -- Varicose Veins
    [C_ID .. 453] = "Złamanie Otwarte", -- Compound Fracture
    [C_ID .. 454] = "Polidaktylia", -- Polydactyly
    [C_ID .. 455] = "Zgubiona Moneta Taty", -- Dad's Lost Coin
    [C_ID .. 456] = "Nocna Przekąska", -- Midnight Snack
    [C_ID .. 457] = "Stożkogłowy", -- Cone Head
    [C_ID .. 458] = "Pępek", -- Belly Button
    [C_ID .. 459] = "Zapalenie Zatok", -- Sinus Infection
    [C_ID .. 460] = "Jaskra", -- Glaucoma
    [C_ID .. 461] = "Parazytoid", -- Parasitoid
    [C_ID .. 462] = "Oko Beliala", -- Eye of Belial
    [C_ID .. 463] = "Kwas Siarkowy", -- Sulfuric Acid
    [C_ID .. 464] = "Glif Równowagi", -- Glyph of Balance
    [C_ID .. 465] = "Gałka Analogowa", -- Analog Stick
    [C_ID .. 466] = "Zakażenie", -- Contagion
    [C_ID .. 467] = "Paluch!", -- Finger!
    [C_ID .. 468] = "Cień", -- Shade
    [C_ID .. 469] = "Depresja", -- Depression
    [C_ID .. 470] = "Hushy", -- Hushy
    [C_ID .. 471] = "Tyci Monstro", -- Lil Monstro
    [C_ID .. 472] = "Dziecięcy Król", -- King Baby
    [C_ID .. 473] = "Big Chubby", -- Big Chubby
    [C_ID .. 474] = "Zepsuta Szklana Armata", -- Broken Glass Cannon
    [C_ID .. 475] = "Plan C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Pustka", -- Void
    [C_ID .. 478] = "Pauza", -- Pause
    [C_ID .. 479] = "Wytapiacz", -- Smelter
    [C_ID .. 480] = "Kompost", -- Compost
    [C_ID .. 481] = "Kopacz Danych", -- Dataminer
    [C_ID .. 482] = "Klikacz", -- Clicker
    [C_ID .. 483] = "Mama Mega!", -- Mama Mega!
    [C_ID .. 484] = "Czekaj, Co?", -- Wait What?
    [C_ID .. 485] = "Skrzywiony Pieniążek", -- Crooked Penny
    [C_ID .. 486] = "Tępa Żyletka", -- Dull Razor
    [C_ID .. 487] = "Obieraczka do Ziemniaków", -- Potato Peeler
    [C_ID .. 488] = "Metronom", -- Metronome
    [C_ID .. 489] = "D Nieskończoność", -- D Infinity
    [C_ID .. 490] = "Dusza Edena", -- Eden's Soul
    [C_ID .. 491] = "Kwaśne Dziecko", -- Acid Baby
    [C_ID .. 492] = "EJ, SŁUCHAJ!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenalina", -- Adrenaline
    [C_ID .. 494] = "Drabina Jakuba", -- Jacob's Ladder
    [C_ID .. 495] = "wyZionięcie Ducha", -- Ghost Pepper
    [C_ID .. 496] = "Eutanazja", -- Euthanasia
    [C_ID .. 497] = "Portki Kamuflarzu", -- Camo Undies
    [C_ID .. 498] = "Dualizm", -- Duality
    [C_ID .. 499] = "Eucharystia", -- Eucharist
    [C_ID .. 500] = "Sakiewka na Sakiewki", -- Sack of Sacks
    [C_ID .. 501] = "Przełyk Chciwości", -- Greed's Gullet
    [C_ID .. 502] = "Spory Pryszcz", -- Large Zit
    [C_ID .. 503] = "Mały Róg", -- Little Horn
    [C_ID .. 504] = "Brązowy Bobek", -- Brown Nugget
    [C_ID .. 505] = "Poke Go", -- Poke Go
    [C_ID .. 506] = "Nóż w Plecy", -- Backstabber
    [C_ID .. 507] = "Ostra Słomka", -- Sharp Straw
    [C_ID .. 508] = "Żyletka Mamy", -- Mom's Razor
    [C_ID .. 509] = "Przekrwione Oko", -- Bloodshot Eye
    [C_ID .. 510] = "Delirious", -- Delirious
    [C_ID .. 511] = "Wściekła Mucha", -- Angry Fly
    [C_ID .. 512] = "Czarna Dziura", -- Black Hole
    [C_ID .. 513] = "Bozo", -- Bozo
    [C_ID .. 514] = "Zepsuty Modem", -- Broken Modem
    [C_ID .. 515] = "Tajemniczy Prezent", -- Mystery Gift
    [C_ID .. 516] = "Zraszacz", -- Sprinkler
    [C_ID .. 517] = "Szybkie Bomby", -- Fast Bombs
    [C_ID .. 518] = "Kumpel z Pudełka", -- Buddy in a Box
    [C_ID .. 519] = "Tyci Delirium", -- Lil Delirium
    [C_ID .. 520] = "Kable Rozruchowe", -- Jumper Cables
    [C_ID .. 521] = "Kupon", -- Coupon
    [C_ID .. 522] = "Telekineza", -- Telekinesis
    [C_ID .. 523] = "Pudło na Przenosiny", -- Moving Box
    [C_ID .. 524] = "Technology Zero", -- Technology Zero
    [C_ID .. 525] = "Trąd", -- Leprosy
    [C_ID .. 526] = "7 Pieczęci", -- 7 Seals
    [C_ID .. 527] = "Pan JA!", -- Mr. ME!
    [C_ID .. 528] = "Anielski Pryzmat", -- Angelic Prism
    [C_ID .. 529] = "Pop!", -- Pop!
    [C_ID .. 530] = "Lista Śmierci", -- Death's List
    [C_ID .. 531] = "Hemolakria", -- Haemolacria
    [C_ID .. 532] = "Wygłodniałe Łzy", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Plecak Szkolny", -- Schoolbag
    [C_ID .. 535] = "Kocyk", -- Blanket
    [C_ID .. 536] = "Ołtarz Ofiarny", -- Sacrificial Altar
    [C_ID .. 537] = "Tyci Spewer", -- Lil Spewer
    [C_ID .. 538] = "Marmurki", -- Marbles
    [C_ID .. 539] = "Jajko Niespodzianka", -- Mystery Egg
    [C_ID .. 540] = "Płaski Kamień", -- Flat Stone
    [C_ID .. 541] = "Szpik", -- Marrow
    [C_ID .. 542] = "Przesunięte Żebro", -- Slipped Rib
    [C_ID .. 543] = "Poświęcona Ziemia", -- Hallowed Ground
    [C_ID .. 544] = "Spiczaste Żebro", -- Pointy Rib
    [C_ID .. 545] = "Księga Umarłych", -- Book of the Dead
    [C_ID .. 546] = "Pierścień Taty", -- Dad's Ring
    [C_ID .. 547] = "Papiery Rozwodowe", -- Divorce Papers
    [C_ID .. 548] = "Szczęka", -- Jaw Bone
    [C_ID .. 549] = "Łamliwe Kości", -- Brittle Bones
    [C_ID .. 550] = "Rozwalona Łopata", -- Broken Shovel
    [C_ID .. 551] = "Rozwalona Łopata", -- Broken Shovel
    [C_ID .. 552] = "Łopata Mamy", -- Mom's Shovel
    [C_ID .. 553] = "Mucormycosis", -- Mucormycosis
    [C_ID .. 554] = "2Spooky", -- 2Spooky
    [C_ID .. 555] = "Złota żyletka", -- Golden Razor
    [C_ID .. 556] = "Sulfur", -- Sulfur
    [C_ID .. 557] = "Cistko z wróżbą", -- Fortune Cookie
    [C_ID .. 558] = "Wrzód oka", -- Eye Sore
    [C_ID .. 559] = "120 Volt", -- 120 Volt
    [C_ID .. 560] = "To boli", -- It Hurts
    [C_ID .. 561] = "Mleko migdałowe", -- Almond Milk
    [C_ID .. 562] = "Kamień z dna", -- Rock Bottom
    [C_ID .. 563] = "Nancy Bombs", -- Nancy Bombs
    [C_ID .. 564] = "Kostka Mydła", -- A Bar of Soap
    [C_ID .. 565] = "Krwawy zwierzak", -- Blood Puppy
    [C_ID .. 566] = "Łapacz snów", -- Dream Catcher
    [C_ID .. 567] = "Świeca Paschalna", -- Paschal Candle
    [C_ID .. 568] = "Boska Ingerencja", -- Divine Intervention
    [C_ID .. 569] = "Krwawa przysięga", -- Blood Oath
    [C_ID .. 570] = "Ciastko PlayDough", -- Playdough Cookie
    [C_ID .. 571] = "Skarpetki sieroty", -- Orphan Socks
    [C_ID .. 572] = "Okultystyczne oko", -- Eye of the Occult
    [C_ID .. 573] = "Nieskalane serce", -- Immaculate Heart
    [C_ID .. 574] = "Monstrancja", -- Monstrance
    [C_ID .. 575] = "Intruz", -- The Intruder
    [C_ID .. 576] = "Brudne myśli", -- Dirty Mind
    [C_ID .. 577] = "Damocles", -- Damocles
    [C_ID .. 578] = "Darmowa lemoniada", -- Free Lemonade
    [C_ID .. 579] = "Duchowe ostrze", -- Spirit Sword
    [C_ID .. 580] = "Czerwony Klucz", -- Red Key
    [C_ID .. 581] = "Psy Fly", -- Psy Fly
    [C_ID .. 582] = "Wavy Cap", -- Wavy Cap
    [C_ID .. 583] = "Rakieta w słoiku", -- Rocket in a Jar
    [C_ID .. 584] = "Księga płomyków", -- Book of Virtues
    [C_ID .. 585] = "Alabasterowe pudełko", -- Alabaster Box
    [C_ID .. 586] = "Przejście", -- The Stairway
    [C_ID .. 587] = "Menorah (Unused but skripted)", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Luna", -- Luna
    [C_ID .. 590] = "Mercurius", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Terra", -- Terra
    [C_ID .. 593] = "Mars", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturnus", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptunus", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Głowa Voodoo", -- Voodoo Head
    [C_ID .. 600] = "Eye Drops", -- Eye Drops
    [C_ID .. 601] = "Act of Contrition", -- Act of Contrition
    [C_ID .. 602] = "Karta Członkowska", -- Member Card
    [C_ID .. 603] = "Paczka Baterii", -- Battery Pack
    [C_ID .. 604] = "Bransoletka Mamy", -- Mom's Bracelet
    [C_ID .. 605] = "Szufelka", -- The Scooper
    [C_ID .. 606] = "Ocular Rift", -- Ocular Rift
    [C_ID .. 607] = "Ugotowane dziecko", -- Boiled Baby
    [C_ID .. 608] = "Mroźne dziecko", -- Freezer Baby
    [C_ID .. 609] = "Wieczne D6", -- Eternal D6
    [C_ID .. 610] = "Klatka dla ptaków", -- Bird Cage
    [C_ID .. 611] = "Larynx", -- Larynx
    [C_ID .. 612] = "Zagubiona dusza", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Krwawe bomby", -- Blood Bombs
    [C_ID .. 615] = "Lil Dumpy", -- Lil Dumpy
    [C_ID .. 616] = "oko ptaka", -- Bird's Eye
    [C_ID .. 617] = "Magnetyt", -- Lodestone
    [C_ID .. 618] = "Zgniły pomidor", -- Rotten Tomato
    [C_ID .. 619] = "Prawo Urodzenia", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Czerwony gulasz", -- Red Stew
    [C_ID .. 622] = "Geneza", -- Genesis
    [C_ID .. 623] = "Ostry Klucz", -- Sharp Key
    [C_ID .. 624] = "Paczka z kartami", -- Booster Pack
    [C_ID .. 625] = "Mega grzyb", -- Mega Mush
    [C_ID .. 626] = "Knife Piece 1", -- Knife Piece 1
    [C_ID .. 627] = "Knife Piece 2", -- Knife Piece 2
    [C_ID .. 628] = "Certyfikat śmierci", -- Death Certificate
    [C_ID .. 629] = "Bot Fly", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Tasak do Mięsa", -- Meat Cleaver
    [C_ID .. 632] = "Zły Urok", -- Evil Charm
    [C_ID .. 633] = "Dogma", -- Dogma
    [C_ID .. 634] = "Czyściec", -- Purgatory
    [C_ID .. 635] = "Szewkuś", -- Stitches
    [C_ID .. 636] = "Klawisz R", -- R Key
    [C_ID .. 637] = "Dropsy Nokautu", -- Knockout Drops
    [C_ID .. 638] = "Gumka", -- Eraser
    [C_ID .. 639] = "Zgniłe serce", -- Yuck Heart
    [C_ID .. 640] = "Urna dusz", -- Urn of Souls
    [C_ID .. 641] = "Akeldama", -- Akeldama
    [C_ID .. 642] = "magiczna skóra", -- Magic Skin
    [C_ID .. 643] = "Objawienie", -- Revelation
    [C_ID .. 644] = "Nagroda pocieszenia", -- Consolation Prize
    [C_ID .. 645] = "Minitoma", -- Tinytoma
    [C_ID .. 646] = "Bomby Brimstonowe", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volt", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Owocowy Plum", -- Fruity Plum
    [C_ID .. 650] = "Flet Plum", -- Plum Flute
    [C_ID .. 651] = "Gwiazda Betlejemska", -- Star of Bethlehem
    [C_ID .. 652] = "Dziecko kostka", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "Fałszywe PHD", -- False PHD
    [C_ID .. 655] = "Spin to Win", -- Spin to Win
    [C_ID .. 656] = "Damocles", -- Damocles
    [C_ID .. 657] = "zapalenie Naczynek", -- Vasculitis
    [C_ID .. 658] = "Gigantyczna komórka", -- Giant Cell
    [C_ID .. 659] = "Tropikamd", -- Tropicamide
    [C_ID .. 660] = "Wróżby w kartach", -- Card Reading
    [C_ID .. 661] = "Quints", -- Quints
    [C_ID .. 662] = "Pacifist (Cut item)", -- 
    [C_ID .. 663] = "Zębowy panokieć", -- Tooth and Nail
    [C_ID .. 664] = "Binge Eater", -- Binge Eater
    [C_ID .. 665] = "Oko Guppyego", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Straszydło", -- Strawman
    [C_ID .. 668] = "Notka taty", -- Dad's Note
    [C_ID .. 669] = "Kiełbasa", -- Sausage
    [C_ID .. 670] = "Opcje?", -- Options?
    [C_ID .. 671] = "Cukrowe serduszko", -- Candy Heart
    [C_ID .. 672] = "Porcja mięsa", -- A Pound of Flesh
    [C_ID .. 673] = "Odkupienie", -- Redemption
    [C_ID .. 674] = "Duchowe kajdany", -- Spirit Shackles
    [C_ID .. 675] = "Popękana kula", -- Cracked Orb
    [C_ID .. 676] = "Puste serce", -- Empty Heart
    [C_ID .. 677] = "Astralna Projekcja", -- Astral Projection
    [C_ID .. 678] = "Sekcja C", -- C Section
    [C_ID .. 679] = "Lil Abaddon", -- Lil Abaddon
    [C_ID .. 680] = "Zemsta Montezumy", -- Montezuma's Revenge
    [C_ID .. 681] = "Lil Portal", -- Lil Portal
    [C_ID .. 682] = "Przyjaciel robak", -- Worm Friend
    [C_ID .. 683] = "Ostre Kostki", -- Bone Spurs
    [C_ID .. 684] = "Głodna dusza", -- Hungry Soul
    [C_ID .. 685] = "Słoik ogników", -- Jar of Wisps
    [C_ID .. 686] = "Medalik Duszy", -- Soul Locket
    [C_ID .. 687] = "Znajdywacz przyjaciół", -- Friend Finder
    [C_ID .. 688] = "Wewnętrzne dziecko", -- Inner Child
    [C_ID .. 689] = "Zglitchowana Korona", -- Glitched Crown
    [C_ID .. 690] = "Belly Jelly", -- Belly Jelly
    [C_ID .. 691] = "Sacred Orb", -- Sacred Orb
    [C_ID .. 692] = "Krwista więź", -- Sanguine Bond
    [C_ID .. 693] = "rój", -- The Swarm
    [C_ID .. 694] = "złamane serce", -- Heartbreak
    [C_ID .. 695] = "Krwawy zryw", -- Bloody Gust
    [C_ID .. 696] = "Salvation", -- Salvation
    [C_ID .. 697] = "Zanikający bliźniak", -- Vanishing Twin
    [C_ID .. 698] = "Pokręcona para", -- Twisted Pair
    [C_ID .. 699] = "Wściekłośc Azazela", -- Azazel's Rage
    [C_ID .. 700] = "Echo Komnata", -- Echo Chamber
    [C_ID .. 701] = "Grobowiec Isaaca", -- Isaac's Tomb
    [C_ID .. 702] = "Mściwy duch", -- Vengeful Spirit
    [C_ID .. 703] = "Esau Jr.", -- Esau Jr.
    [C_ID .. 704] = "Berserk!", -- Berserk!
    [C_ID .. 705] = "Mroczne Techniki", -- Dark Arts
    [C_ID .. 706] = "Otchłań", -- Abyss
    [C_ID .. 707] = "Kolacja", -- Supper
    [C_ID .. 708] = "zszywacz", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Torba tworzenia", -- Bag of Crafting
    [C_ID .. 711] = "Flip", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Recall", -- Recall
    [C_ID .. 715] = "Hold", -- Hold
    [C_ID .. 716] = "Sakiewka Keepera", -- Keeper's Sack
    [C_ID .. 717] = "Rodzinka keepera", -- Keeper's Kin
    [C_ID .. 718] = "Keepers Robe (Cut item)", -- 
    [C_ID .. 719] = "Pudełko Keepera", -- Keeper's Box
    [C_ID .. 720] = "Wszystkosłój", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Spindown Dice", -- Spindown Dice
    [C_ID .. 724] = "Nadkrzepliwość", -- Hypercoagulation
    [C_ID .. 725] = "IBS", -- IBS
    [C_ID .. 726] = "Krwioplucoe", -- Hemoptysis
    [C_ID .. 727] = "Duchowe bomby", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Dakapito atak", -- Decap Attack
    [C_ID .. 730] = "", -- Glass Eye
    [C_ID .. 731] = "", -- Stye
    [C_ID .. 732] = "", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Połknięty Pieniążek", -- Swallowed Penny
    [T_ID .. 2] = "Skamieniała Kupa", -- Petrified Poop
    [T_ID .. 3] = "Bateria AAA", -- AAA Battery
    [T_ID .. 4] = "Zepsuty Pilot", -- Broken Remote
    [T_ID .. 5] = "Purpurowe Serce", -- Purple Heart
    [T_ID .. 6] = "Zepsuty Magnes", -- Broken Magnet
    [T_ID .. 7] = "Koralik Różańcowy", -- Rosary Bead
    [T_ID .. 8] = "Kartridż", -- Cartridge
    [T_ID .. 9] = "Pulsujący Robak", -- Pulse Worm
    [T_ID .. 10] = "Rozhuśtany Robak", -- Wiggle Worm
    [T_ID .. 11] = "Pierścienny Robak", -- Ring Worm
    [T_ID .. 12] = "Płaski Robak", -- Flat Worm
    [T_ID .. 13] = "Bon Podarunkowy", -- Store Credit
    [T_ID .. 14] = "Modzel", -- Callus
    [T_ID .. 15] = "Szczęśliwy Kamyczek", -- Lucky Rock
    [T_ID .. 16] = "Paznokieć Mamy", -- Mom's Toenail
    [T_ID .. 17] = "Czarna Szminka", -- Black Lipstick
    [T_ID .. 18] = "Fragment Biblii", -- Bible Tract
    [T_ID .. 19] = "Spinacz", -- Paper Clip
    [T_ID .. 20] = "Małpia Łapka", -- Monkey Paw
    [T_ID .. 21] = "Tajemnicza Kartka", -- Mysterious Paper
    [T_ID .. 22] = "Ogon Demona", -- Daemon's Tail
    [T_ID .. 23] = "Plakat Zaginionego", -- Missing Poster
    [T_ID .. 24] = "Dupny Pieniążek", -- Butt Penny
    [T_ID .. 25] = "Tajemnicze Ciuciu", -- Mysterious Candy
    [T_ID .. 26] = "Haczykowaty Robak", -- Hook Worm
    [T_ID .. 27] = "Batowy Robak", -- Whip Worm
    [T_ID .. 28] = "Złamany Anch", -- Broken Ankh
    [T_ID .. 29] = "Głowa Ryby", -- Fish Head
    [T_ID .. 30] = "Czerwone Oko", -- Pinky Eye
    [T_ID .. 31] = "Pinezka", -- Push Pin
    [T_ID .. 32] = "Czapka Wolności", -- Liberty Cap
    [T_ID .. 33] = "Pępowina", -- Umbilical Cord
    [T_ID .. 34] = "Serce Dziecka", -- Child's Heart
    [T_ID .. 35] = "Zakrzywiony Róg", -- Curved Horn
    [T_ID .. 36] = "Zardzewiały Klucz", -- Rusted Key
    [T_ID .. 37] = "Kozie Kopyto", -- Goat Hoof
    [T_ID .. 38] = "Perła Mamy", -- Mom's Pearl
    [T_ID .. 39] = "Rak", -- Cancer
    [T_ID .. 40] = "Czerwona Łatka", -- Red Patch
    [T_ID .. 41] = "Zapałka", -- Match Stick
    [T_ID .. 42] = "Szczęśliwy Paluch", -- Lucky Toe
    [T_ID .. 43] = "Przeklęta Czaszka", -- Cursed Skull
    [T_ID .. 44] = "Nakrętka Bezpieczna", -- Safety Cap
    [T_ID .. 45] = "As Pik", -- Ace of Spades
    [T_ID .. 46] = "Widelec Izaaka", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "Brakująca Kartka", -- A Missing Page
    [T_ID .. 49] = "Krwawy Pieniążek", -- Bloody Penny
    [T_ID .. 50] = "Spalony Pieniążek", -- Burnt Penny
    [T_ID .. 51] = "Płaski Pieniążek", -- Flat Penny
    [T_ID .. 52] = "Podrobiony Pieniążek", -- Counterfeit Penny
    [T_ID .. 53] = "Kleszcz", -- Tick
    [T_ID .. 54] = "Głowa Izaaka", -- Isaac's Head
    [T_ID .. 55] = "Wiara Madzi", -- Maggy's Faith
    [T_ID .. 56] = "Język Judasza", -- Judas' Tongue
    [T_ID .. 57] = "Dusza ???", -- ???'s Soul
    [T_ID .. 58] = "Włosy Samsona", -- Samson's Lock
    [T_ID .. 59] = "Oko Kaina", -- Cain's Eye
    [T_ID .. 60] = "Skok Ptaka Ewy", -- Eve's Bird Foot
    [T_ID .. 61] = "Lewa Ręka", -- The Left Hand
    [T_ID .. 62] = "", -- Shiny Rock
    [T_ID .. 63] = "", -- Safety Scissors
    [T_ID .. 64] = "", -- Rainbow Worm
    [T_ID .. 65] = "Tape Worm", -- Tape Worm
    [T_ID .. 66] = "Lazy Worm", -- Lazy Worm
    [T_ID .. 67] = "", -- Cracked Dice
    [T_ID .. 68] = "", -- Super Magnet
    [T_ID .. 69] = "Faded Polaroid", -- Faded Polaroid
    [T_ID .. 70] = "", -- Louse
    [T_ID .. 71] = "", -- Bob's Bladder
    [T_ID .. 72] = "", -- Watch Battery
    [T_ID .. 73] = "", -- Blasting Cap
    [T_ID .. 74] = "", -- Stud Finder
    [T_ID .. 75] = "", -- Error
    [T_ID .. 76] = "", -- Poker Chip
    [T_ID .. 77] = "", -- Blister
    [T_ID .. 78] = "", -- Second Hand
    [T_ID .. 79] = "", -- Endless Nameless
    [T_ID .. 80] = "Czarne pióro", -- Black Feather
    [T_ID .. 81] = "", -- Blind Rage
    [T_ID .. 82] = "", -- Golden Horse Shoe
    [T_ID .. 83] = "", -- Store Key
    [T_ID .. 84] = "", -- Rib of Greed
    [T_ID .. 85] = "", -- Karma
    [T_ID .. 86] = "", -- Lil Larva
    [T_ID .. 87] = "", -- Mom's Locket
    [T_ID .. 88] = "", -- NO!
    [T_ID .. 89] = "", -- Child Leash
    [T_ID .. 90] = "", -- Brown Cap
    [T_ID .. 91] = "", -- Meconium
    [T_ID .. 92] = "Pęknięta Korona", -- Cracked Crown
    [T_ID .. 93] = "", -- Used Diaper
    [T_ID .. 94] = "", -- Fish Tail
    [T_ID .. 95] = "", -- Black Tooth
    [T_ID .. 96] = "", -- Ouroboros Worm
    [T_ID .. 97] = "", -- Tonsil
    [T_ID .. 98] = "", -- Nose Goblin
    [T_ID .. 99] = "", -- Super Ball
    [T_ID .. 100] = "", -- Vibrant Bulb
    [T_ID .. 101] = "Dim Bulb", -- Dim Bulb
    [T_ID .. 102] = "", -- Fragmented Card
    [T_ID .. 103] = "", -- Equality!
    [T_ID .. 104] = "", -- Wish Bone
    [T_ID .. 105] = "", -- Bag Lunch
    [T_ID .. 106] = "", -- Lost Cork
    [T_ID .. 107] = "", -- Crow Heart
    [T_ID .. 108] = "", -- Walnut
    [T_ID .. 109] = "", -- Duct Tape
    [T_ID .. 110] = "Silver Dollar", -- Silver Dollar
    [T_ID .. 111] = "Krwawa Korona", -- Bloody Crown
    [T_ID .. 112] = "", -- Pay To Win
    [T_ID .. 113] = "", -- Locust of War
    [T_ID .. 114] = "", -- Locust of Pestilence
    [T_ID .. 115] = "", -- Locust of Famine
    [T_ID .. 116] = "", -- Locust of Death
    [T_ID .. 117] = "", -- Locust of Conquest
    [T_ID .. 118] = "", -- Bat Wing
    [T_ID .. 119] = "Komórka Macierzysta", -- Stem Cell
    [T_ID .. 120] = "", -- Hairpin
    [T_ID .. 121] = "", -- Wooden Cross
    [T_ID .. 122] = "", -- Butter!
    [T_ID .. 123] = "", -- Filigree Feather
    [T_ID .. 124] = "", -- Door Stop
    [T_ID .. 125] = "", -- Extension Cord
    [T_ID .. 126] = "", -- Rotten Penny
    [T_ID .. 127] = "", -- Baby-Bender
    [T_ID .. 128] = "Kość z palca", -- Finger Bone
    [T_ID .. 129] = "Łamiszczęka", -- Jawbreaker
    [T_ID .. 130] = "Pogryziony Długopis", -- Chewed Pen
    [T_ID .. 131] = "Pobogosławiony Cent", -- Blessed Penny
    [T_ID .. 132] = "Rozbita Strzykawka", -- Broken Syringe
    [T_ID .. 133] = "Temperament", -- Short Fuse
    [T_ID .. 134] = "Gigantyczna Fasola", -- Gigante Bean
    [T_ID .. 135] = "Zapaliczka", -- A Lighter
    [T_ID .. 136] = "Pęknięta kłódka", -- Broken Padlock
    [T_ID .. 137] = "Niezapominajka", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Urokliwa łza", -- Teardrop Charm
    [T_ID .. 140] = "Jabłko sodu", -- Apple of Sodom
    [T_ID .. 141] = "Zapomniana Kołysanka", -- Forgotten Lullaby
    [T_ID .. 142] = "Wiara Elżbiety", -- Beth's Faith
    [T_ID .. 143] = "Stary Kondensator", -- Old Capacitor
    [T_ID .. 144] = "Pasożyt Neurotropowy", -- Brain Worm
    [T_ID .. 145] = "Perfekcja", -- Perfection
    [T_ID .. 146] = "Diabelska Korona", -- Devil's Crown
    [T_ID .. 147] = "Naładowany Cent", -- Charged Penny
    [T_ID .. 148] = "Naszyjnik Przyjaźni", -- Friendship Necklace
    [T_ID .. 149] = "Przycisk Alarmowy", -- Panic Button
    [T_ID .. 150] = "Niebieski Klucz", -- Blue Key
    [T_ID .. 151] = "Kartotekowa baza danych", -- Flat File
    [T_ID .. 152] = "Soczewka Teleskopu", -- Telescope Lens
    [T_ID .. 153] = "Kucyk Matki", -- Mom's Lock
    [T_ID .. 154] = "Worek kości do gry", -- Dice Bag
    [T_ID .. 155] = "Święta korona", -- Holy Crown
    [T_ID .. 156] = "Matczyny pocałunek", -- Mother's Kiss
    [T_ID .. 157] = "Podarta karta", -- Torn Card
    [T_ID .. 158] = "Podarta sakiewka", -- Torn Pocket
    [T_ID .. 159] = "Pozłacany klucz", -- Gilded Key
    [T_ID .. 160] = "Szczęśliwa sakwa", -- Lucky Sack
    [T_ID .. 161] = "Niegodziwa korona", -- Wicked Crown
    [T_ID .. 162] = "Kikut Azazela", -- Azazel's Stump
    [T_ID .. 163] = "Kupko jagoda", -- Dingle Berry
    [T_ID .. 164] = "Kapiszony", -- Ring Cap
    [T_ID .. 165] = "Nuh Uh!", -- Nuh Uh!
    [T_ID .. 166] = "Modelina", -- Modeling Clay
    [T_ID .. 167] = "Wypolerowana kośc", -- Polished Bone
    [T_ID .. 168] = "Puste serce", -- Hollow Heart
    [T_ID .. 169] = "Dziecięcy obrazek", -- Kid's Drawing
    [T_ID .. 170] = "Kryształowy klucz", -- Crystal Key
    [T_ID .. 171] = "Okazja Keepera", -- Keeper's Bargain
    [T_ID .. 172] = "Przeklęty cent", -- Cursed Penny
    [T_ID .. 173] = "Twoja dusza", -- Your Soul
    [T_ID .. 174] = "Magnes cyfrowy", -- Number Magnet
    [T_ID .. 175] = "Dziwny klucz", -- Strange Key
    [T_ID .. 176] = "Mały zakrzep", -- Lil Clot
    [T_ID .. 177] = "Tymczasowy tatuaż", -- Temporary Tattoo
    [T_ID .. 178] = "Połknięta Petarda", -- Swallowed M80
    [T_ID .. 179] = "Zdalny kontrolel", -- RC Remote
    [T_ID .. 180] = "Znaleziona dusza", -- Found Soul
    [T_ID .. 181] = "Paczka rozszerzeń", -- Expansion Pack
    [T_ID .. 182] = "Istota Elżbiety", -- Beth's Essence
    [T_ID .. 183] = "bliźniaki", -- The Twins
    [T_ID .. 184] = "Dokumenty Adopcyjne", -- Adoption Papers
    [T_ID .. 185] = "Noga Crickieta", -- Cricket Leg
    [T_ID .. 186] = "Najlepszy ziomo Appolyona", -- Apollyon's Best Friend
    [T_ID .. 187] = "Połamane Okulary", -- Broken Glasses
    [T_ID .. 188] = "Kostka lodu", -- Ice Cube
    [T_ID .. 189] = "Pieczęć Bahometa", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Głupiec", -- 0 - The Fool
    [Card_ID .. 2] = "I - Mag", -- I - The Magician
    [Card_ID .. 3] = "II - Kapłanka", -- II - The High Priestess
    [Card_ID .. 4] = "III - Cesarzowa", -- III - The Empress
    [Card_ID .. 5] = "IV - Cesarz", -- IV - The Emperor
    [Card_ID .. 6] = "V - Hierofant", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Kochankowie", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Rydwan", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Sprawiedliwość", -- VIII - Justice
    [Card_ID .. 10] = "IX - Eremita", -- IX - The Hermit
    [Card_ID .. 11] = "X - Koło Fortuny", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Siła", -- XI - Strength
    [Card_ID .. 13] = "XII - Wisielec", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Śmierć", -- XIII - Death
    [Card_ID .. 15] = "XIV - Umiarkowanie", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Diabeł", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Wieża", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Gwiazda", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Księżyc", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Słońce", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Sąd Ostateczny", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Świat", -- XXI - The World
    [Card_ID .. 23] = "2 Trefl", -- 2 of Clubs
    [Card_ID .. 24] = "2 Karo", -- 2 of Diamonds
    [Card_ID .. 25] = "2 Pik", -- 2 of Spades
    [Card_ID .. 26] = "2 Kier", -- 2 of Hearts
    [Card_ID .. 27] = "As Trefl", -- Ace of Clubs
    [Card_ID .. 28] = "As Karo", -- Ace of Diamonds
    [Card_ID .. 29] = "As Pik", -- Ace of Spades
    [Card_ID .. 30] = "As Kier", -- Ace of Hearts
    [Card_ID .. 31] = "Joker", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Pusta Runa", -- Blank Rune
    [Card_ID .. 41] = "Czarna Runa", -- Black Rune
    [Card_ID .. 42] = "Karta Chaosu", -- Chaos Card
    [Card_ID .. 43] = "Karta Kredytowa", -- Credit Card
    [Card_ID .. 44] = "Karta Zasad", -- Rules Card
    [Card_ID .. 45] = "Karta Przeciw Ludzkości", -- A Card Against Humanity
    [Card_ID .. 46] = "Król Samobójca", -- Suicide King
    [Card_ID .. 47] = "Karta Wyjścia z Więzienia", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "Karta ?", -- ? Card
    [Card_ID .. 49] = "Odłamek Kości", -- Dice Shard
    [Card_ID .. 50] = "W Nagłym Wypadku", -- Emergency Contact
    [Card_ID .. 51] = "Święta Karta", -- Holy Card
    [Card_ID .. 52] = "Wielkie Bydle", -- Huge Growth
    [Card_ID .. 53] = "Starożytne Wezwanie", -- Ancient Recall
    [Card_ID .. 54] = "Historyczna Przechadzka", -- Era Walk
    [Card_ID .. 55] = "Odłamek Runy", -- Rune Shard
    [Card_ID .. 56] = "0 - Głupiec?", -- 0 - The Fool?
    [Card_ID .. 57] = "", -- I - The Magician?
    [Card_ID .. 58] = "II - Kapłanka?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - Cesarzowa?", -- III - The Empress?
    [Card_ID .. 60] = "IV - Cesarz?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Hierofant?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Kochankowie?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Rydwan?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Sprawiedliwość?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - Eremita?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Koło Fortuny?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Siła?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Wisielec?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Śmierć?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Umiarkowanie?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Diabeł?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - Wieża?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Gwiazda?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - Księżyc?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Słońce?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Sąd Ostateczny?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Świat?", -- XXI - The World?
    [Card_ID .. 78] = "Złamany Klucz", -- Cracked Key
    [Card_ID .. 79] = "Królowa Kier", -- Queen of Hearts
    [Card_ID .. 80] = "Dzika Karta", -- Wild Card
    [Card_ID .. 81] = "Dusza Izaaka", -- Soul of Isaac
    [Card_ID .. 82] = "Dusza Magdaleny", -- Soul of Magdalene
    [Card_ID .. 83] = "Dusza Kaina", -- Soul of Cain
    [Card_ID .. 84] = "Dusza Judasza", -- Soul of Judas
    [Card_ID .. 85] = "Dusza ???", -- Soul of ???
    [Card_ID .. 86] = "Dusza Ewy", -- Soul of Eve
    [Card_ID .. 87] = "Dusza Samsona", -- Soul of Samson
    [Card_ID .. 88] = "Dusza Azazela", -- Soul of Azazel
    [Card_ID .. 89] = "Dusza Łazarza", -- Soul of Lazarus
    [Card_ID .. 90] = "Dusza Edena", -- Soul of Eden
    [Card_ID .. 91] = "Dusza Zaginionego", -- Soul of the Lost
    [Card_ID .. 92] = "Dusza Lilit", -- Soul of Lilith
    [Card_ID .. 93] = "Dusza Dozorcy", -- Soul of the Keeper
    [Card_ID .. 94] = "Dusza Apollyona", -- Soul of Apollyon
    [Card_ID .. 95] = "Dusza Zapomnianego", -- Soul of the Forgotten
    [Card_ID .. 96] = "Dusza Betani", -- Soul of Bethany
    [Card_ID .. 97] = "Dusza Jakuba i Ezawa", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "Wzdęcia", -- Bad Gas
    [Pill_ID .. 2] = "Potknięcie", -- Bad Trip
    [Pill_ID .. 3] = "Jaja ze Stali", -- Balls of Steel
    [Pill_ID .. 4] = "Bomby to Klucze", -- Bombs are Key
    [Pill_ID .. 5] = "Ostra Biegunka", -- Explosive Diarrhea
    [Pill_ID .. 6] = "Pełne Zdrowie", -- Full Health
    [Pill_ID .. 7] = "Mniej Zdrowia", -- Health Down
    [Pill_ID .. 8] = "Więcej Zdrowia", -- Health Up
    [Pill_ID .. 9] = "Znalazłem Pigułki", -- I Found Pills
    [Pill_ID .. 10] = "Dorastanie", -- Puberty
    [Pill_ID .. 11] = "Muszka", -- Pretty Fly
    [Pill_ID .. 12] = "Zasięg Maleje", -- Range Down
    [Pill_ID .. 13] = "Zasięg Wzrasta", -- Range Up
    [Pill_ID .. 14] = "Prędkość Maleje", -- Speed Down
    [Pill_ID .. 15] = "Prędkość Wzrasta", -- Speed Up
    [Pill_ID .. 16] = "Szybkostrzelność Maleje", -- Tears Down
    [Pill_ID .. 17] = "Szybkostrzelność Wzrasta", -- Tears Up
    [Pill_ID .. 18] = "Szczęście Maleje", -- Luck Down
    [Pill_ID .. 19] = "Szczęście Wzrasta", -- Luck Up
    [Pill_ID .. 20] = "Telepigułka", -- Telepills
    [Pill_ID .. 21] = "Energia na 48h!", -- 48 Hour Energy!
    [Pill_ID .. 22] = "Krwawe Wymioty", -- Hematemesis
    [Pill_ID .. 23] = "Paraliż", -- Paralysis
    [Pill_ID .. 24] = "Mam wieczne widzenie!", -- I can see forever!
    [Pill_ID .. 25] = "Feromony", -- Pheromones
    [Pill_ID .. 26] = "Amnezja", -- Amnesia
    [Pill_ID .. 27] = "Cytrynowa Zabawa", -- Lemon Party
    [Pill_ID .. 28] = "JESTEŚ CZARODZIEJEM?", -- R U A Wizard?
    [Pill_ID .. 29] = "Paracetamol", -- Percs!
    [Pill_ID .. 30] = "Uzależniony!", -- Addicted!
    [Pill_ID .. 31] = "Poluzowanie!", -- Re-Lax
    [Pill_ID .. 32] = "???", -- ???
    [Pill_ID .. 33] = "Czyni cię większym", -- One makes you larger
    [Pill_ID .. 34] = "Czyni cię małym", -- One makes you small
    [Pill_ID .. 35] = "Zarażony!", -- Infested!
    [Pill_ID .. 36] = "Zarażony?", -- Infested?
    [Pill_ID .. 37] = "Pigułka Mocy!", -- Power Pill!
    [Pill_ID .. 38] = "Retro-Widok", -- Retro Vision
    [Pill_ID .. 39] = "Przyjaciele do końca", -- Friends Till The End!
    [Pill_ID .. 40] = "Przeczyszczenie", -- X-Lax
    [Pill_ID .. 41] = "Coś jest nie tak...", -- Something's wrong...
    [Pill_ID .. 42] = "Jestem śpiący...", -- I'm Drowsy...
    [Pill_ID .. 43] = "Ekscytacja!", -- I'm Excited!!
    [Pill_ID .. 44] = "Łyk!", -- Gulp!
    [Pill_ID .. 45] = "Paw!", -- Horf!
    [Pill_ID .. 46] = "Jakbym stąpał po promykach słońca!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "Refluks!", -- Vurp!
    [Pill_ID .. 48] = "Prędkość Strzałów Maleje", -- Shot speed Down
    [Pill_ID .. 49] = "Prędkość Strzałów Wzrasta", -- Shot speed Up
    [Pill_ID .. 50] = "Eksperymentalna Pigułka", -- Experimental Pill
    [Pill_ID .. 9999] = "Złota Pigułka", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])