-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "ro_ro"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Ceapa Tristă", -- The Sad Onion
    [C_ID .. 2] = "Ochiul Interior", -- The Inner Eye
    [C_ID .. 3] = "Lingura Îndoită", -- Spoon Bender
    [C_ID .. 4] = "Cap de Greier", -- Cricket's Head
    [C_ID .. 5] = "Reflexia Mea", -- My Reflection
    [C_ID .. 6] = "Numărul Unu", -- Number One
    [C_ID .. 7] = "Sângele Martirului", -- Blood of the Martyr
    [C_ID .. 8] = "Fratele Bobby", -- Brother Bobby
    [C_ID .. 9] = "Skatole", -- Skatole
    [C_ID .. 10] = "Aureola de Muște", -- Halo of Flies
    [C_ID .. 11] = "1sus!", -- 1up!
    [C_ID .. 12] = "Ciupercă Magică", -- Magic Mushroom
    [C_ID .. 13] = "Virusul", -- The Virus
    [C_ID .. 14] = "Furie cu Steroizi", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Ficat Crud", -- Raw Liver
    [C_ID .. 17] = "Cheia Schelet", -- Skeleton Key
    [C_ID .. 18] = "Un Leu", -- A Dollar
    [C_ID .. 19] = "Boom!", -- Boom!
    [C_ID .. 20] = "Transcendență", -- Transcendence
    [C_ID .. 21] = "Busola", -- The Compass
    [C_ID .. 22] = "Prânz", -- Lunch
    [C_ID .. 23] = "Cină", -- Dinner
    [C_ID .. 24] = "Desert", -- Dessert
    [C_ID .. 25] = "Mic Dejun", -- Breakfast
    [C_ID .. 26] = "Carne Stricată", -- Rotten Meat
    [C_ID .. 27] = "Lingură de Lemn", -- Wooden Spoon
    [C_ID .. 28] = "Cureaua", -- The Belt
    [C_ID .. 29] = "Chiloții Mamei", -- Mom's Underwear
    [C_ID .. 30] = "Tocurile Mamei", -- Mom's Heels
    [C_ID .. 31] = "Rujul Mamei", -- Mom's Lipstick
    [C_ID .. 32] = "Cuier de Sârmă", -- Wire Coat Hanger
    [C_ID .. 33] = "Biblia", -- The Bible
    [C_ID .. 34] = "Cartea lui Belial", -- The Book of Belial
    [C_ID .. 35] = "The Necronomicon", -- The Necronomicon
    [C_ID .. 36] = "Rahatul", -- The Poop
    [C_ID .. 37] = "Dl. Bum", -- Mr. Boom
    [C_ID .. 38] = "Capul lui Tammy", -- Tammy's Head
    [C_ID .. 39] = "Sutienul Mamei", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Tamponul Mamei", -- Mom's Pad
    [C_ID .. 42] = "Capul putrezit a lui Bob", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teleportare!", -- Teleport!
    [C_ID .. 45] = "Yum, Inimă", -- Yum Heart
    [C_ID .. 46] = "Piciorul Norocos", -- Lucky Foot
    [C_ID .. 47] = "Telecomanda Doctorului", -- Doctor's Remote
    [C_ID .. 48] = "Săgeata lui Cupid", -- Cupid's Arrow
    [C_ID .. 49] = "Kamehame..!!!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagramă", -- Pentagram
    [C_ID .. 52] = "Dl. Fetus", -- Dr. Fetus
    [C_ID .. 53] = "Magnet", -- Magneto
    [C_ID .. 54] = "Harta Comorilor", -- Treasure Map
    [C_ID .. 55] = "Ochiul Mamei", -- Mom's Eye
    [C_ID .. 56] = "Accidentul Lămâii", -- Lemon Mishap
    [C_ID .. 57] = "Admirație Distantă", -- Distant Admiration
    [C_ID .. 58] = "Cartea Umbrelor", -- Book of Shadows
    [C_ID .. 59] = "Cartea lui Belial", -- The Book of Belial
    [C_ID .. 60] = "Scara", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Farmecul Vampirului", -- Charm of the Vampire
    [C_ID .. 63] = "Bateria", -- The Battery
    [C_ID .. 64] = "Vânzarea Steam", -- Steam Sale
    [C_ID .. 65] = "Cartea de Bucate a Anarhistului", -- Anarchist Cookbook
    [C_ID .. 66] = "Clepsidra", -- The Hourglass
    [C_ID .. 67] = "Surioara Maggy", -- Sister Maggy
    [C_ID .. 68] = "Tehnologie", -- Technology
    [C_ID .. 69] = "Lapte cu Ciocolată", -- Chocolate Milk
    [C_ID .. 70] = "Hormoni de Creștere", -- Growth Hormones
    [C_ID .. 71] = "Mini Ciupercă", -- Mini Mush
    [C_ID .. 72] = "Rozariu", -- Rosary
    [C_ID .. 73] = "Un Cub de Carne", -- Cube of Meat
    [C_ID .. 74] = "Un Sfert", -- A Quarter
    [C_ID .. 75] = "PHD", -- PHD
    [C_ID .. 76] = "Viziune X-Ray", -- X-Ray Vision
    [C_ID .. 77] = "Micul Meu Unicorn", -- My Little Unicorn
    [C_ID .. 78] = "Cartea Apocalipsei", -- Book of Revelations
    [C_ID .. 79] = "Semnul", -- The Mark
    [C_ID .. 80] = "Pactul", -- The Pact
    [C_ID .. 81] = "Pisica Moartă", -- Dead Cat
    [C_ID .. 82] = "Stăpânul Gropii", -- Lord of the Pit
    [C_ID .. 83] = "Cuiul", -- The Nail
    [C_ID .. 84] = "Trebuie Să Ajungem Mai Adânc!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Set de Cărți", -- Deck of Cards
    [C_ID .. 86] = "Dintele lui Monstro", -- Monstro's Tooth
    [C_ID .. 87] = "Coarnele lui Loki", -- Loki's Horns
    [C_ID .. 88] = "Micul Dolofan", -- Little Chubby
    [C_ID .. 89] = "Mușcătură de Păianjen", -- Spider Bite
    [C_ID .. 90] = "Mica Piatră", -- The Small Rock
    [C_ID .. 91] = "Cască de Miner", -- Spelunker Hat
    [C_ID .. 92] = "Super Bandajul", -- Super Bandage
    [C_ID .. 93] = "Gamekid-ul", -- The Gamekid
    [C_ID .. 94] = "Sac de Bănuți", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Bebeluș", -- Robo-Baby
    [C_ID .. 96] = "Micul C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "Cartea Păcatului", -- The Book of Sin
    [C_ID .. 98] = "Relicva", -- The Relic
    [C_ID .. 99] = "Micul Gish", -- Little Gish
    [C_ID .. 100] = "Micul Steven", -- Little Steven
    [C_ID .. 101] = "Aureola", -- The Halo
    [C_ID .. 102] = "Sticla de Pastile a Mamei", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Răceala Comună", -- The Common Cold
    [C_ID .. 104] = "Parazitul", -- The Parasite
    [C_ID .. 105] = "D6-le", -- The D6
    [C_ID .. 106] = "Dl. Mega", -- Mr. Mega
    [C_ID .. 107] = "Foarfece Zig-Zag", -- The Pinking Shears
    [C_ID .. 108] = "Napolitana", -- The Wafer
    [C_ID .. 109] = "Bani = Putere", -- Money = Power
    [C_ID .. 110] = "Lentilele Mamei", -- Mom's Contacts
    [C_ID .. 111] = "Fasolea", -- The Bean
    [C_ID .. 112] = "Îngerul Protector", -- Guardian Angel
    [C_ID .. 113] = "Bebelușul Demon", -- Demon Baby
    [C_ID .. 114] = "Cuțitul Mamei", -- Mom's Knife
    [C_ID .. 115] = "Tablă Ouija", -- Ouija Board
    [C_ID .. 116] = "9 Volți", -- 9 Volt
    [C_ID .. 117] = "Pasăre Moartă", -- Dead Bird
    [C_ID .. 118] = "Brimstone", -- Brimstone
    [C_ID .. 119] = "Pungă cu Sânge", -- Blood Bag
    [C_ID .. 120] = "Ciupercă Ciudată (Subțire)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Ciupercă Ciudată(Mare)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Prostituata Babilonului", -- Whore of Babylon
    [C_ID .. 123] = "Manualul Monștrilor", -- Monster Manual
    [C_ID .. 124] = "Pergamentele Mării Moarte", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bombă", -- Bobby-Bomb
    [C_ID .. 126] = "Lamă de Ras", -- Razor Blade
    [C_ID .. 127] = "Uită-mă Acum", -- Forget Me Now
    [C_ID .. 128] = "Singur Mereu", -- Forever Alone
    [C_ID .. 129] = "Găleată cu Untură", -- Bucket of Lard
    [C_ID .. 130] = "Un Ponei", -- A Pony
    [C_ID .. 131] = "Plasă cu Bombe", -- Bomb Bag
    [C_ID .. 132] = "O Bucată de Cărbune", -- A Lump of Coal
    [C_ID .. 133] = "Laba lui Guppy", -- Guppy's Paw
    [C_ID .. 134] = "Coada lui Guppy", -- Guppy's Tail
    [C_ID .. 135] = "Perfuzie", -- IV Bag
    [C_ID .. 136] = "Cel Mai Bun Prieten", -- Best Friend
    [C_ID .. 137] = "Detonator Telecomandă", -- Remote Detonator
    [C_ID .. 138] = "Stigmate", -- Stigmata
    [C_ID .. 139] = "Poșeta Mamei", -- Mom's Purse
    [C_ID .. 140] = "Blestemul lui Bob", -- Bob's Curse
    [C_ID .. 141] = "Băiatul Misterios", -- Pageant Boy
    [C_ID .. 142] = "Scapular", -- Scapular
    [C_ID .. 143] = "Minge Rapidă", -- Speed Ball
    [C_ID .. 144] = "Prieten Vagabond", -- Bum Friend
    [C_ID .. 145] = "Capul lui Guppy", -- Guppy's Head
    [C_ID .. 146] = "Carte de Rugăciuni", -- Prayer Card
    [C_ID .. 147] = "Târnăcopul lui Notch", -- Notched Axe
    [C_ID .. 148] = "Infestare", -- Infestation
    [C_ID .. 149] = "Ipecac", -- Ipecac
    [C_ID .. 150] = "Dragoste Dură", -- Tough Love
    [C_ID .. 151] = "Mulligan-ul", -- The Mulligan
    [C_ID .. 152] = "Tehnologia 2", -- Technology 2
    [C_ID .. 153] = "Păianjen Mutant", -- Mutant Spider
    [C_ID .. 154] = "Coajă Chimică", -- Chemical Peel
    [C_ID .. 155] = "Ochiul Rătăcit", -- The Peeper
    [C_ID .. 156] = "Obicei", -- Habit
    [C_ID .. 157] = "Poftă Sângeroasă", -- Bloody Lust
    [C_ID .. 158] = "Minge de Cristal", -- Crystal Ball
    [C_ID .. 159] = "Spiritul Nopții", -- Spirit of the Night
    [C_ID .. 160] = "Crapă Cerul", -- Crack the Sky
    [C_ID .. 161] = "Ankh", -- Ankh
    [C_ID .. 162] = "Crucea Celtică", -- Celtic Cross
    [C_ID .. 163] = "Bebelușul Fantomă", -- Ghost Baby
    [C_ID .. 164] = "Lumânarea", -- The Candle
    [C_ID .. 165] = "Pisica-cu-9-cozi", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Bebelușul Harlequin", -- Harlequin Baby
    [C_ID .. 168] = "Fătul Epic", -- Epic Fetus
    [C_ID .. 169] = "Polifem", -- Polyphemus
    [C_ID .. 170] = "Tăticul Picioare-Mari", -- Daddy Longlegs
    [C_ID .. 171] = "Fund de Păianjen", -- Spider Butt
    [C_ID .. 172] = "Cuțit de Jertfă", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitră", -- Mitre
    [C_ID .. 174] = "Bebeluș Curcubeu", -- Rainbow Baby
    [C_ID .. 175] = "Cheile Tatălui", -- Dad's Key
    [C_ID .. 176] = "Celule Stem", -- Stem Cells
    [C_ID .. 177] = "Păcăneaua Portabilă", -- Portable Slot
    [C_ID .. 178] = "Apă Sfințită", -- Holy Water
    [C_ID .. 179] = "Soartă", -- Fate
    [C_ID .. 180] = "Fasolea Neagră", -- The Black Bean
    [C_ID .. 181] = "Ponei Alb", -- White Pony
    [C_ID .. 182] = "Inimă Sacră", -- Sacred Heart
    [C_ID .. 183] = "Scobitori", -- Tooth Picks
    [C_ID .. 184] = "Sfântul Graal", -- Holy Grail
    [C_ID .. 185] = "Porumbel Mort", -- Dead Dove
    [C_ID .. 186] = "Drepturi de Sânge", -- Blood Rights
    [C_ID .. 187] = "Mingea de Păr a lui Guppy", -- Guppy's Hairball
    [C_ID .. 188] = "Abel", -- Abel
    [C_ID .. 189] = "SMB Super Fan", -- SMB Super Fan
    [C_ID .. 190] = "Pyro", -- Pyro
    [C_ID .. 191] = "Bancnota de 3 Lei", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepatie pentru Proști", -- Telepathy for Dummies
    [C_ID .. 193] = "CARNE!", -- MEAT!
    [C_ID .. 194] = "Mingea Adevărului", -- Magic 8 Ball
    [C_ID .. 195] = "Portofelul Mamei", -- Mom's Coin Purse
    [C_ID .. 196] = "Squeezy", -- Squeezy
    [C_ID .. 197] = "Sucul lui Iisus", -- Jesus Juice
    [C_ID .. 198] = "Cutie", -- Box
    [C_ID .. 199] = "Cheia Mamei", -- Mom's Key
    [C_ID .. 200] = "Fardul Mamei", -- Mom's Eyeshadow
    [C_ID .. 201] = "Țeavă din Fier", -- Iron Bar
    [C_ID .. 202] = "Atingerea lui Midas", -- Midas' Touch
    [C_ID .. 203] = "Pachet Modest", -- Humbleing Bundle
    [C_ID .. 204] = "Borsetă", -- Fanny Pack
    [C_ID .. 205] = "Ștecher Ascuțit", -- Sharp Plug
    [C_ID .. 206] = "Gilotină", -- Guillotine
    [C_ID .. 207] = "Minge din Bandaje", -- Ball of Bandages
    [C_ID .. 208] = "Cureaua Campionului", -- Champion Belt
    [C_ID .. 209] = "Bombe Fund", -- Butt Bombs
    [C_ID .. 210] = "Frunză Roasă", -- Gnawed Leaf
    [C_ID .. 211] = "Păianjen Bebeluș", -- Spiderbaby
    [C_ID .. 212] = "Zgarda lui Guppy", -- Guppy's Collar
    [C_ID .. 213] = "Contact Pierdut", -- Lost Contact
    [C_ID .. 214] = "Anemic", -- Anemic
    [C_ID .. 215] = "Cap de Capră", -- Goat Head
    [C_ID .. 216] = "Robe Ceremoniale", -- Ceremonial Robes
    [C_ID .. 217] = "Peruca Mamei", -- Mom's Wig
    [C_ID .. 218] = "Placentă", -- Placenta
    [C_ID .. 219] = "Bandaj Vechi", -- Old Bandage
    [C_ID .. 220] = "Bombe Triste", -- Sad Bombs
    [C_ID .. 221] = "Ciment de Cauciuc", -- Rubber Cement
    [C_ID .. 222] = "Anti-Gravitație", -- Anti-Gravity
    [C_ID .. 223] = "Piromaniac", -- Pyromaniac
    [C_ID .. 224] = "Corpul lui Cricket", -- Cricket's Body
    [C_ID .. 225] = "Masca Plăcerii", -- Gimpy
    [C_ID .. 226] = "Lotusul Negru", -- Black Lotus
    [C_ID .. 227] = "Pușculița Porcușor", -- Piggy Bank
    [C_ID .. 228] = "Parfumul Mamei", -- Mom's Perfume
    [C_ID .. 229] = "Plămânii lui Monstro", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Minge din Smoală", -- Ball of Tar
    [C_ID .. 232] = "Cronometru", -- Stop Watch
    [C_ID .. 233] = "Planeta Micuță", -- Tiny Planet
    [C_ID .. 234] = "Infestare 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "Atingerea Morții", -- Death's Touch
    [C_ID .. 238] = "Piesă de cheie 1", -- Key Piece 1
    [C_ID .. 239] = "Piesă de cheie 2", -- Key Piece 2
    [C_ID .. 240] = "Tratament Experimental", -- Experimental Treatment
    [C_ID .. 241] = "Contractul de Dedesubt", -- Contract from Below
    [C_ID .. 242] = "Infamie", -- Infamy
    [C_ID .. 243] = "Scutul Treimii", -- Trinity Shield
    [C_ID .. 244] = "Tehn.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Hartă Albastră", -- Blue Map
    [C_ID .. 247] = "CMMP!", -- BFFS!
    [C_ID .. 248] = "Mintea Stupului", -- Hive Mind
    [C_ID .. 249] = "Sunt Opțiuni", -- There's Options
    [C_ID .. 250] = "Bombe Bogo", -- Bogo Bombs
    [C_ID .. 251] = "Pachetul Începătorului", -- Starter Deck
    [C_ID .. 252] = "Mica Punguță", -- Little Baggy
    [C_ID .. 253] = "Crusta Magică", -- Magic Scab
    [C_ID .. 254] = "Cheag de Sânge", -- Blood Clot
    [C_ID .. 255] = "Șurub", -- Screw
    [C_ID .. 256] = "Bombe Fierbinți", -- Hot Bombs
    [C_ID .. 257] = "Mintea de Foc", -- Fire Mind
    [C_ID .. 258] = "Nr. Lipsă", -- Missing No.
    [C_ID .. 259] = "Materie Neagră", -- Dark Matter
    [C_ID .. 260] = "Lumânarea Neagră", -- Black Candle
    [C_ID .. 261] = "Exoftalmie", -- Proptosis
    [C_ID .. 262] = "Pagina Pierdută 2", -- Missing Page 2
    [C_ID .. 263] = "Rună Clară", -- Clear Rune
    [C_ID .. 264] = "Musca Inteligentă", -- Smart Fly
    [C_ID .. 265] = "Bebeluș Uscat", -- Dry Baby
    [C_ID .. 266] = "Sac Suculent", -- Juicy Sack
    [C_ID .. 267] = "Robo-Bebeluș 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Bebeluș Putrezit", -- Rotten Baby
    [C_ID .. 269] = "Bebeluș Fără Cap", -- Headless Baby
    [C_ID .. 270] = "Lipitoare", -- Leech
    [C_ID .. 271] = "Sac Misterios", -- Mystery Sack
    [C_ID .. 272] = "CMBP", -- BBF
    [C_ID .. 273] = "Creierul lui Bob", -- Bob's Brain
    [C_ID .. 274] = "Cel Mai Bun Amic", -- Best Bud
    [C_ID .. 275] = "Micul Brimstone", -- Lil Brimstone
    [C_ID .. 276] = "Inima lui Isaac", -- Isaac's Heart
    [C_ID .. 277] = "Micul Bântuit", -- Lil Haunt
    [C_ID .. 278] = "Cerșetor Întunecat", -- Dark Bum
    [C_ID .. 279] = "Fan mare", -- Big Fan
    [C_ID .. 280] = "Sissy Picioare-Lungi", -- Sissy Longlegs
    [C_ID .. 281] = "Sac de Box", -- Punching Bag
    [C_ID .. 282] = "Cum să sari", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Carte Albă", -- Blank Card
    [C_ID .. 287] = "Cartea Secretelor", -- Book of Secrets
    [C_ID .. 288] = "Cutie cu Păianjeni", -- Box of Spiders
    [C_ID .. 289] = "Lumânarea Roșie", -- Red Candle
    [C_ID .. 290] = "Borcanul", -- The Jar
    [C_ID .. 291] = "Flush!", -- Flush!
    [C_ID .. 292] = "Biblia Satanică", -- Satanic Bible
    [C_ID .. 293] = "Capul lui Krampus", -- Head of Krampus
    [C_ID .. 294] = "Fasole cu Unt", -- Butter Bean
    [C_ID .. 295] = "Degete Magice", -- Magic Fingers
    [C_ID .. 296] = "Convertor", -- Converter
    [C_ID .. 297] = "Cutia Pandorei", -- Pandora's Box
    [C_ID .. 298] = "Unicorn Stump", -- Unicorn Stump
    [C_ID .. 299] = "Taurus", -- Taurus
    [C_ID .. 300] = "Berbec", -- Aries
    [C_ID .. 301] = "Cancer", -- Cancer
    [C_ID .. 302] = "Leo", -- Leo
    [C_ID .. 303] = "Virgo", -- Virgo
    [C_ID .. 304] = "Libra", -- Libra
    [C_ID .. 305] = "Scorpio", -- Scorpio
    [C_ID .. 306] = "Sagittarius", -- Sagittarius
    [C_ID .. 307] = "Capricorn", -- Capricorn
    [C_ID .. 308] = "Vărsător", -- Aquarius
    [C_ID .. 309] = "Pești", -- Pisces
    [C_ID .. 310] = "Rimelul Evei", -- Eve's Mascara
    [C_ID .. 311] = "Judas' Shadow", -- Judas' Shadow
    [C_ID .. 312] = "Maggy's Bow", -- Maggy's Bow
    [C_ID .. 313] = "Holy Mantle", -- Holy Mantle
    [C_ID .. 314] = "Coapse Grase", -- Thunder Thighs
    [C_ID .. 315] = "Atractor Ciudat", -- Strange Attractor
    [C_ID .. 316] = "Ochi Blestemat", -- Cursed Eye
    [C_ID .. 317] = "Mysterious Liquid", -- Mysterious Liquid
    [C_ID .. 318] = "Gemini", -- Gemini
    [C_ID .. 319] = "Celalat Ochi a lui Cain", -- Cain's Other Eye
    [C_ID .. 320] = "Singurul Prieten a lui ???", -- ???'s Only Friend
    [C_ID .. 321] = "Samson's Chains", -- Samson's Chains
    [C_ID .. 322] = "Mongo Baby", -- Mongo Baby
    [C_ID .. 323] = "Lacrimile lui Isaac", -- Isaac's Tears
    [C_ID .. 324] = "Undefined", -- Undefined
    [C_ID .. 325] = "Foarfece", -- Scissors
    [C_ID .. 326] = "Respirația Vieții", -- Breath of Life
    [C_ID .. 327] = "The Polaroid", -- The Polaroid
    [C_ID .. 328] = "Negativul", -- The Negative
    [C_ID .. 329] = "The Ludovico Technique", -- The Ludovico Technique
    [C_ID .. 330] = "Lapte de Soia", -- Soy Milk
    [C_ID .. 331] = "Zeitate", -- Godhead
    [C_ID .. 332] = "Lazarus' Rags", -- Lazarus' Rags
    [C_ID .. 333] = "The Mind", -- The Mind
    [C_ID .. 334] = "The Body", -- The Body
    [C_ID .. 335] = "The Soul", -- The Soul
    [C_ID .. 336] = "Ceapă Moartă", -- Dead Onion
    [C_ID .. 337] = "Broken Watch", -- Broken Watch
    [C_ID .. 338] = "The Boomerang", -- The Boomerang
    [C_ID .. 339] = "Ac de Siguranță", -- Safety Pin
    [C_ID .. 340] = "Caffeine Pill", -- Caffeine Pill
    [C_ID .. 341] = "Torn Photo", -- Torn Photo
    [C_ID .. 342] = "Ciupercă Albastră", -- Blue Cap
    [C_ID .. 343] = "Latch Key", -- Latch Key
    [C_ID .. 344] = "Cutie de Chibrituri", -- Match Book
    [C_ID .. 345] = "Synthol", -- Synthoil
    [C_ID .. 346] = "O Gustare", -- A Snack
    [C_ID .. 347] = "Diplopia", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Monedă de Lemn", -- Wooden Nickel
    [C_ID .. 350] = "Toxic Shock", -- Toxic Shock
    [C_ID .. 351] = "Fasole Gigant", -- Mega Bean
    [C_ID .. 352] = "Tun de Sticlă", -- Glass Cannon
    [C_ID .. 353] = "Bomber Boy", -- Bomber Boy
    [C_ID .. 354] = "Popcorn Caramelizat", -- Crack Jacks
    [C_ID .. 355] = "Perlele Mamei", -- Mom's Pearls
    [C_ID .. 356] = "Car Battery", -- Car Battery
    [C_ID .. 357] = "Box of Friends", -- Box of Friends
    [C_ID .. 358] = "The Wiz", -- The Wiz
    [C_ID .. 359] = "8 Inch Nails", -- 8 Inch Nails
    [C_ID .. 360] = "Incubus", -- Incubus
    [C_ID .. 361] = "Fate's Reward", -- Fate's Reward
    [C_ID .. 362] = "Lil Chest", -- Lil Chest
    [C_ID .. 363] = "Sworn Protector", -- Sworn Protector
    [C_ID .. 364] = "Friend Zone", -- Friend Zone
    [C_ID .. 365] = "Musca Pierdută", -- Lost Fly
    [C_ID .. 366] = "Bombe Împrăștiate", -- Scatter Bombs
    [C_ID .. 367] = "Bombe Lipicioase", -- Sticky Bombs
    [C_ID .. 368] = "Epiforă", -- Epiphora
    [C_ID .. 369] = "Continuum", -- Continuum
    [C_ID .. 370] = "Dl. Dolly", -- Mr. Dolly
    [C_ID .. 371] = "Curse of the Tower", -- Curse of the Tower
    [C_ID .. 372] = "Charged Baby", -- Charged Baby
    [C_ID .. 373] = "Dead Eye", -- Dead Eye
    [C_ID .. 374] = "Lumină Sfântă", -- Holy Light
    [C_ID .. 375] = "Pălărie Host", -- Host Hat
    [C_ID .. 376] = "Reprovizionare", -- Restock
    [C_ID .. 377] = "Bursting Sack", -- Bursting Sack
    [C_ID .. 378] = "No. 2", -- No. 2
    [C_ID .. 379] = "Pupula Duplex", -- Pupula Duplex
    [C_ID .. 380] = "Plătește pentru a Juca", -- Pay To Play
    [C_ID .. 381] = "Eden's Blessing", -- Eden's Blessing
    [C_ID .. 382] = "Minge Prietenoasă", -- Friendly Ball
    [C_ID .. 383] = "Tear Detonator", -- Tear Detonator
    [C_ID .. 384] = "Micul Gurdy", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Censer", -- Censer
    [C_ID .. 388] = "Key Bum", -- Key Bum
    [C_ID .. 389] = "Sac cu Rune", -- Rune Bag
    [C_ID .. 390] = "Seraphim", -- Seraphim
    [C_ID .. 391] = "Trădare", -- Betrayal
    [C_ID .. 392] = "Zodiac", -- Zodiac
    [C_ID .. 393] = "Sărutul Șarpelui", -- Serpent's Kiss
    [C_ID .. 394] = "Marcat", -- Marked
    [C_ID .. 395] = "Tehnologie X", -- Tech X
    [C_ID .. 396] = "Ventricle Razor", -- Ventricle Razor
    [C_ID .. 397] = "Rază Tractoare", -- Tractor Beam
    [C_ID .. 398] = "God's Flesh", -- God's Flesh
    [C_ID .. 399] = "Gura Abisului", -- Maw of the Void
    [C_ID .. 400] = "Spear of Destiny", -- Spear of Destiny
    [C_ID .. 401] = "Exploziv", -- Explosivo
    [C_ID .. 402] = "Chaos", -- Chaos
    [C_ID .. 403] = "Spider Mod", -- Spider Mod
    [C_ID .. 404] = "Bebeluș Beșinos", -- Farting Baby
    [C_ID .. 405] = "GB Bug", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Puritate", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Empty Vessel", -- Empty Vessel
    [C_ID .. 410] = "Evil Eye", -- Evil Eye
    [C_ID .. 411] = "Lusty Blood", -- Lusty Blood
    [C_ID .. 412] = "Cambion Conception", -- Cambion Conception
    [C_ID .. 413] = "Immaculate Conception", -- Immaculate Conception
    [C_ID .. 414] = "More Options", -- More Options
    [C_ID .. 415] = "Coroană de Lumină", -- Crown Of Light
    [C_ID .. 416] = "Buzunare Adânci", -- Deep Pockets
    [C_ID .. 417] = "Succubus", -- Succubus
    [C_ID .. 418] = "Fruit Cake", -- Fruit Cake
    [C_ID .. 419] = "Teleport 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Black Powder", -- Black Powder
    [C_ID .. 421] = "Fasole Roșie", -- Kidney Bean
    [C_ID .. 422] = "Clepsidră Strălucitoare", -- Glowing Hourglass
    [C_ID .. 423] = "Circle of Protection", -- Circle of Protection
    [C_ID .. 424] = "Sack Head", -- Sack Head
    [C_ID .. 425] = "Night Light", -- Night Light
    [C_ID .. 426] = "Fan Obsedat", -- Obsessed Fan
    [C_ID .. 427] = "Mine Crafter", -- Mine Crafter
    [C_ID .. 428] = "PJs", -- PJs
    [C_ID .. 429] = "Head of the Keeper", -- Head of the Keeper
    [C_ID .. 430] = "Tata Muscă", -- Papa Fly
    [C_ID .. 431] = "Bebeluș Multi-dimensional", -- Multidimensional Baby
    [C_ID .. 432] = "Bombe cu Sclipici", -- Glitter Bombs
    [C_ID .. 433] = "Umbra Mea", -- My Shadow
    [C_ID .. 434] = "Jar of Flies", -- Jar of Flies
    [C_ID .. 435] = "Lil Loki", -- Lil Loki
    [C_ID .. 436] = "Lapte!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Binky", -- Binky
    [C_ID .. 439] = "Mom's Box", -- Mom's Box
    [C_ID .. 440] = "Piatră la Rinichi", -- Kidney Stone
    [C_ID .. 441] = "Mega Blast", -- Mega Blast
    [C_ID .. 442] = "Coroana Prințului Întunecat", -- Dark Prince's Crown
    [C_ID .. 443] = "Apple!", -- Apple!
    [C_ID .. 444] = "Creion cu Plumb", -- Lead Pencil
    [C_ID .. 445] = "Dog Tooth", -- Dog Tooth
    [C_ID .. 446] = "Dead Tooth", -- Dead Tooth
    [C_ID .. 447] = "Fasole Persistentă", -- Linger Bean
    [C_ID .. 448] = "Bucată de Sticlă", -- Shard of Glass
    [C_ID .. 449] = "Metal Plate", -- Metal Plate
    [C_ID .. 450] = "Ochiul Lăcomiei", -- Eye of Greed
    [C_ID .. 451] = "Tapiserie de Tarot", -- Tarot Cloth
    [C_ID .. 452] = "Varicose Veins", -- Varicose Veins
    [C_ID .. 453] = "Fractură Deschisă", -- Compound Fracture
    [C_ID .. 454] = "Polydactyly", -- Polydactyly
    [C_ID .. 455] = "Bănuțul Pierdut a lui Tata", -- Dad's Lost Coin
    [C_ID .. 456] = "Gustare de Seară", -- Midnight Snack
    [C_ID .. 457] = "Cone Head", -- Cone Head
    [C_ID .. 458] = "Belly Button", -- Belly Button
    [C_ID .. 459] = "Sinuzită", -- Sinus Infection
    [C_ID .. 460] = "Glaucoma", -- Glaucoma
    [C_ID .. 461] = "Parasitoid", -- Parasitoid
    [C_ID .. 462] = "Ochiul lui Belial", -- Eye of Belial
    [C_ID .. 463] = "Sulfuric Acid", -- Sulfuric Acid
    [C_ID .. 464] = "Glifă de Balanță", -- Glyph of Balance
    [C_ID .. 465] = "Analog Stick", -- Analog Stick
    [C_ID .. 466] = "Contagion", -- Contagion
    [C_ID .. 467] = "Finger!", -- Finger!
    [C_ID .. 468] = "Umbra", -- Shade
    [C_ID .. 469] = "Depression", -- Depression
    [C_ID .. 470] = "Hushy", -- Hushy
    [C_ID .. 471] = "Lil Monstro", -- Lil Monstro
    [C_ID .. 472] = "Regele Bebeluș", -- King Baby
    [C_ID .. 473] = "Big Chubby", -- Big Chubby
    [C_ID .. 474] = "Tun de Sticlă Spart", -- Broken Glass Cannon
    [C_ID .. 475] = "Plan C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Vidul", -- Void
    [C_ID .. 478] = "Pause", -- Pause
    [C_ID .. 479] = "Smelter", -- Smelter
    [C_ID .. 480] = "Compost", -- Compost
    [C_ID .. 481] = "Dataminer", -- Dataminer
    [C_ID .. 482] = "Clicker", -- Clicker
    [C_ID .. 483] = "Mama Mega!", -- Mama Mega!
    [C_ID .. 484] = "Wait What?", -- Wait What?
    [C_ID .. 485] = "Crooked Penny", -- Crooked Penny
    [C_ID .. 486] = "Dull Razor", -- Dull Razor
    [C_ID .. 487] = "Curățăor de Cartofi", -- Potato Peeler
    [C_ID .. 488] = "Metronome", -- Metronome
    [C_ID .. 489] = "D Infinit", -- D Infinity
    [C_ID .. 490] = "Eden's Soul", -- Eden's Soul
    [C_ID .. 491] = "Bebeluș Acid", -- Acid Baby
    [C_ID .. 492] = "YO LISTEN!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenalină", -- Adrenaline
    [C_ID .. 494] = "Scara lui Iacob", -- Jacob's Ladder
    [C_ID .. 495] = "Ardei Fantomă", -- Ghost Pepper
    [C_ID .. 496] = "Eutanasiere", -- Euthanasia
    [C_ID .. 497] = "Chioți de Camunflat", -- Camo Undies
    [C_ID .. 498] = "Duality", -- Duality
    [C_ID .. 499] = "Eucharist", -- Eucharist
    [C_ID .. 500] = "Sacul cu Saci", -- Sack of Sacks
    [C_ID .. 501] = "Esofagul lui Greed", -- Greed's Gullet
    [C_ID .. 502] = "Large Zit", -- Large Zit
    [C_ID .. 503] = "Corn Micuț", -- Little Horn
    [C_ID .. 504] = "Pepită Maro", -- Brown Nugget
    [C_ID .. 505] = "Poke Go", -- Poke Go
    [C_ID .. 506] = "Înjunghie în Spate", -- Backstabber
    [C_ID .. 507] = "Pai Ascuțit", -- Sharp Straw
    [C_ID .. 508] = "Briciul Mamei", -- Mom's Razor
    [C_ID .. 509] = "Ochi Însângerat", -- Bloodshot Eye
    [C_ID .. 510] = "Delirant", -- Delirious
    [C_ID .. 511] = "Angry Fly", -- Angry Fly
    [C_ID .. 512] = "Black Hole", -- Black Hole
    [C_ID .. 513] = "Bozo", -- Bozo
    [C_ID .. 514] = "Modem Stricat", -- Broken Modem
    [C_ID .. 515] = "Mystery Gift", -- Mystery Gift
    [C_ID .. 516] = "Sprinkler", -- Sprinkler
    [C_ID .. 517] = "Bombe Rapide", -- Fast Bombs
    [C_ID .. 518] = "Buddy in a Box", -- Buddy in a Box
    [C_ID .. 519] = "Lil Delirium", -- Lil Delirium
    [C_ID .. 520] = "Jumper Cables", -- Jumper Cables
    [C_ID .. 521] = "Coupon", -- Coupon
    [C_ID .. 522] = "Telekineză", -- Telekinesis
    [C_ID .. 523] = "Cutie de Mutat", -- Moving Box
    [C_ID .. 524] = "Technologie Zero", -- Technology Zero
    [C_ID .. 525] = "Leprosy", -- Leprosy
    [C_ID .. 526] = "7 Seals", -- 7 Seals
    [C_ID .. 527] = "Mr. ME!", -- Mr. ME!
    [C_ID .. 528] = "Angelic Prism", -- Angelic Prism
    [C_ID .. 529] = "Pop!", -- Pop!
    [C_ID .. 530] = "Death's List", -- Death's List
    [C_ID .. 531] = "Hemolacrie", -- Haemolacria
    [C_ID .. 532] = "Lachryphagy", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Schoolbag", -- Schoolbag
    [C_ID .. 535] = "Blanket", -- Blanket
    [C_ID .. 536] = "Sacrificial Altar", -- Sacrificial Altar
    [C_ID .. 537] = "Lil Spewer", -- Lil Spewer
    [C_ID .. 538] = "Marbles", -- Marbles
    [C_ID .. 539] = "Mystery Egg", -- Mystery Egg
    [C_ID .. 540] = "Flat Stone", -- Flat Stone
    [C_ID .. 541] = "Marrow", -- Marrow
    [C_ID .. 542] = "Slipped Rib", -- Slipped Rib
    [C_ID .. 543] = "Rahat Binecuvântat", -- Hallowed Ground
    [C_ID .. 544] = "Pointy Rib", -- Pointy Rib
    [C_ID .. 545] = "Book of the Dead", -- Book of the Dead
    [C_ID .. 546] = "Dad's Ring", -- Dad's Ring
    [C_ID .. 547] = "Divorce Papers", -- Divorce Papers
    [C_ID .. 548] = "Jaw Bone", -- Jaw Bone
    [C_ID .. 549] = "Oase Fragile", -- Brittle Bones
    [C_ID .. 550] = "Broken Shovel", -- Broken Shovel
    [C_ID .. 551] = "Broken Shovel", -- Broken Shovel
    [C_ID .. 552] = "Lopata Mamei", -- Mom's Shovel
    [C_ID .. 553] = "Mucormicoza", -- Mucormycosis
    [C_ID .. 554] = "DeSpaimă", -- 2Spooky
    [C_ID .. 555] = "Brici de Aur", -- Golden Razor
    [C_ID .. 556] = "Sulf", -- Sulfur
    [C_ID .. 557] = "Prăjitură cu Răvaș", -- Fortune Cookie
    [C_ID .. 558] = "Durere de Ochi", -- Eye Sore
    [C_ID .. 559] = "230 V", -- 120 Volt
    [C_ID .. 560] = "Doare", -- It Hurts
    [C_ID .. 561] = "Lapte de Migdale", -- Almond Milk
    [C_ID .. 562] = "La Pământ", -- Rock Bottom
    [C_ID .. 563] = "Bombe Homo", -- Nancy Bombs
    [C_ID .. 564] = "O Bucată de Săpun", -- A Bar of Soap
    [C_ID .. 565] = "Cățeluș Însângerat", -- Blood Puppy
    [C_ID .. 566] = "Prinzător de Vise", -- Dream Catcher
    [C_ID .. 567] = "Lumânare Pascală", -- Paschal Candle
    [C_ID .. 568] = "Intervenție Divină", -- Divine Intervention
    [C_ID .. 569] = "Jurământul de Sânge", -- Blood Oath
    [C_ID .. 570] = "Biscuite de Plasterină", -- Playdough Cookie
    [C_ID .. 571] = "Șosete de Orfan", -- Orphan Socks
    [C_ID .. 572] = "Ochiul Ocultului", -- Eye of the Occult
    [C_ID .. 573] = "Inimă Imaculată", -- Immaculate Heart
    [C_ID .. 574] = "Monstranţă", -- Monstrance
    [C_ID .. 575] = "Intrusul", -- The Intruder
    [C_ID .. 576] = "Minte Murdară", -- Dirty Mind
    [C_ID .. 577] = "Damocles", -- Damocles
    [C_ID .. 578] = "Limonadă Gratis", -- Free Lemonade
    [C_ID .. 579] = "Sabie Spirit", -- Spirit Sword
    [C_ID .. 580] = "Cheie Roșie", -- Red Key
    [C_ID .. 581] = "Muscă Psihică", -- Psy Fly
    [C_ID .. 582] = "Ciupercă Îndoită", -- Wavy Cap
    [C_ID .. 583] = "Rachetă într-un Borcan", -- Rocket in a Jar
    [C_ID .. 584] = "Cartea Virtuților", -- Book of Virtues
    [C_ID .. 585] = "Cutie de Alabastru", -- Alabaster Box
    [C_ID .. 586] = "Scara", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Luna", -- Luna
    [C_ID .. 590] = "Mercur", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Terra", -- Terra
    [C_ID .. 593] = "Marte", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturn", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptun", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Cap Voodoo", -- Voodoo Head
    [C_ID .. 600] = "Picături de Ochi", -- Eye Drops
    [C_ID .. 601] = "Act de Contriție", -- Act of Contrition
    [C_ID .. 602] = "Card de Membru", -- Member Card
    [C_ID .. 603] = "Pachet cu Baterii", -- Battery Pack
    [C_ID .. 604] = "Brățara Mamei", -- Mom's Bracelet
    [C_ID .. 605] = "Lingură pentru Înghețată", -- The Scooper
    [C_ID .. 606] = "Ruptură oculară", -- Ocular Rift
    [C_ID .. 607] = "Bebeluș Fiert", -- Boiled Baby
    [C_ID .. 608] = "Bebeluș Congelat", -- Freezer Baby
    [C_ID .. 609] = "D6 Etern", -- Eternal D6
    [C_ID .. 610] = "Colivie pentru Păsări", -- Bird Cage
    [C_ID .. 611] = "Laringe", -- Larynx
    [C_ID .. 612] = "Suflet Pierdut", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Bombe cu Sânge", -- Blood Bombs
    [C_ID .. 615] = "Micul Dumpy", -- Lil Dumpy
    [C_ID .. 616] = "Ochi de Pasăre", -- Bird's Eye
    [C_ID .. 617] = "Piatră Magnetică", -- Lodestone
    [C_ID .. 618] = "Roșie Stricată", -- Rotten Tomato
    [C_ID .. 619] = "Drept Ereditar", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Tocană Roșie", -- Red Stew
    [C_ID .. 622] = "Geneză", -- Genesis
    [C_ID .. 623] = "Chieie Ascuțită", -- Sharp Key
    [C_ID .. 624] = "Pachet Suplimentar", -- Booster Pack
    [C_ID .. 625] = "Mega Ciupercă", -- Mega Mush
    [C_ID .. 626] = "Bucată de Cuțit 1", -- Knife Piece 1
    [C_ID .. 627] = "Bucată de Cuțit 2", -- Knife Piece 2
    [C_ID .. 628] = "Certificat de Deces", -- Death Certificate
    [C_ID .. 629] = "Muscă Robot", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Satâr de Carne", -- Meat Cleaver
    [C_ID .. 632] = "Farmec Malefic", -- Evil Charm
    [C_ID .. 633] = "Dogmă", -- Dogma
    [C_ID .. 634] = "Purgatoriu", -- Purgatory
    [C_ID .. 635] = "Copci", -- Stitches
    [C_ID .. 636] = "R Key", -- R Key
    [C_ID .. 637] = "Picături de Impact", -- Knockout Drops
    [C_ID .. 638] = "Gumă de Șters", -- Eraser
    [C_ID .. 639] = "Inimă Dezgustătoare", -- Yuck Heart
    [C_ID .. 640] = "Urna Sufletelor", -- Urn of Souls
    [C_ID .. 641] = "Acheldama", -- Akeldama
    [C_ID .. 642] = "Piele Magică", -- Magic Skin
    [C_ID .. 643] = "Revelație", -- Revelation
    [C_ID .. 644] = "Premiu de Consolare", -- Consolation Prize
    [C_ID .. 645] = "Minitoma", -- Tinytoma
    [C_ID .. 646] = "Bombe Brimstone", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volți", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Prune Fructate", -- Fruity Plum
    [C_ID .. 650] = "Fluierul lui Plum", -- Plum Flute
    [C_ID .. 651] = "Steaua din Betleem", -- Star of Bethlehem
    [C_ID .. 652] = "Bebeluș Cub", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "Doctorat Fals", -- False PHD
    [C_ID .. 655] = "Învârte să Câștigi", -- Spin to Win
    [C_ID .. 656] = "Damocles", -- Damocles
    [C_ID .. 657] = "Vasculită", -- Vasculitis
    [C_ID .. 658] = "Celulă Gigant", -- Giant Cell
    [C_ID .. 659] = "Tropicamida ", -- Tropicamide
    [C_ID .. 660] = "Citit în Cărți", -- Card Reading
    [C_ID .. 661] = "Cvadrupleți", -- Quints
    [C_ID .. 662] = "", -- 
    [C_ID .. 663] = "Dinte și Unghii", -- Tooth and Nail
    [C_ID .. 664] = "Hiperfagie", -- Binge Eater
    [C_ID .. 665] = "Ochiul lui Guppy", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Sperietoare", -- Strawman
    [C_ID .. 668] = "Biletul Tatălui", -- Dad's Note
    [C_ID .. 669] = "Cârnat", -- Sausage
    [C_ID .. 670] = "Opțiuni?", -- Options?
    [C_ID .. 671] = "Inimă Bomboană", -- Candy Heart
    [C_ID .. 672] = "Un Kg de Carne", -- A Pound of Flesh
    [C_ID .. 673] = "Mântuire", -- Redemption
    [C_ID .. 674] = "Lanțuri Spirit", -- Spirit Shackles
    [C_ID .. 675] = "Sferă Spartă", -- Cracked Orb
    [C_ID .. 676] = "Inimă Goală", -- Empty Heart
    [C_ID .. 677] = "Proiecție Astrală", -- Astral Projection
    [C_ID .. 678] = "Cezariană", -- C Section
    [C_ID .. 679] = "Micul Abaddon", -- Lil Abaddon
    [C_ID .. 680] = "Răzbunarea lui Montezuma", -- Montezuma's Revenge
    [C_ID .. 681] = "Micul Portal", -- Lil Portal
    [C_ID .. 682] = "Prieten Vierme", -- Worm Friend
    [C_ID .. 683] = "Pinten Osos", -- Bone Spurs
    [C_ID .. 684] = "Suflet Înfometat", -- Hungry Soul
    [C_ID .. 685] = "Borcan cu Musculițe", -- Jar of Wisps
    [C_ID .. 686] = "Medalion Suflet", -- Soul Locket
    [C_ID .. 687] = "Găsitor de Prieteni", -- Friend Finder
    [C_ID .. 688] = "Copilul Interior", -- Inner Child
    [C_ID .. 689] = "Coroană Glichuită", -- Glitched Crown
    [C_ID .. 690] = "Belly Jelly", -- Belly Jelly
    [C_ID .. 691] = "Glob Sacru", -- Sacred Orb
    [C_ID .. 692] = "Legătură de Sânge", -- Sanguine Bond
    [C_ID .. 693] = "Roiul", -- The Swarm
    [C_ID .. 694] = "Rănit în Dragoste", -- Heartbreak
    [C_ID .. 695] = "Rafală Sângeroasă", -- Bloody Gust
    [C_ID .. 696] = "Mântuire", -- Salvation
    [C_ID .. 697] = "Geamănul Dispărut", -- Vanishing Twin
    [C_ID .. 698] = "Pereche Răsucită", -- Twisted Pair
    [C_ID .. 699] = "Furia lui Azazel", -- Azazel's Rage
    [C_ID .. 700] = "Ecou", -- Echo Chamber
    [C_ID .. 701] = "Sarcofagul lui Isaac", -- Isaac's Tomb
    [C_ID .. 702] = "Spirit Răzbunător", -- Vengeful Spirit
    [C_ID .. 703] = "Esau Jr.", -- Esau Jr.
    [C_ID .. 704] = "Berserk!", -- Berserk!
    [C_ID .. 705] = "Artă Negre", -- Dark Arts
    [C_ID .. 706] = "Abyss", -- Abyss
    [C_ID .. 707] = "Masă de seară", -- Supper
    [C_ID .. 708] = "Capsator", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Geantă de Meșteșuguri", -- Bag of Crafting
    [C_ID .. 711] = "Flip", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Chemat", -- Recall
    [C_ID .. 715] = "Ține", -- Hold
    [C_ID .. 716] = "Sacul lui Keeper", -- Keeper's Sack
    [C_ID .. 717] = "Ruda lui Keeper", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "Cutia lui Keeper", -- Keeper's Box
    [C_ID .. 720] = "Borcan cu de Toate", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Zar Coborâtor", -- Spindown Dice
    [C_ID .. 724] = "Hipercoagulare", -- Hypercoagulation
    [C_ID .. 725] = "SII", -- IBS
    [C_ID .. 726] = "Hemoptizie", -- Hemoptysis
    [C_ID .. 727] = "Bombe Fantome", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Atac Decapitat", -- Decap Attack
    [C_ID .. 730] = "Ochi de Sticlă", -- Glass Eye
    [C_ID .. 731] = "Orjelet ", -- Stye
    [C_ID .. 732] = "Inelul Mamei", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Swallowed Penny", -- Swallowed Penny
    [T_ID .. 2] = "Petrified Poop", -- Petrified Poop
    [T_ID .. 3] = "AAA Battery", -- AAA Battery
    [T_ID .. 4] = "Broken Remote", -- Broken Remote
    [T_ID .. 5] = "Purple Heart", -- Purple Heart
    [T_ID .. 6] = "Broken Magnet", -- Broken Magnet
    [T_ID .. 7] = "Rosary Bead", -- Rosary Bead
    [T_ID .. 8] = "Cartridge", -- Cartridge
    [T_ID .. 9] = "Pulse Worm", -- Pulse Worm
    [T_ID .. 10] = "Vierme Neastâmpărat", -- Wiggle Worm
    [T_ID .. 11] = "Vierme Inel", -- Ring Worm
    [T_ID .. 12] = "Flat Worm", -- Flat Worm
    [T_ID .. 13] = "Store Credit", -- Store Credit
    [T_ID .. 14] = "Callus", -- Callus
    [T_ID .. 15] = "Piatră Norocoasă", -- Lucky Rock
    [T_ID .. 16] = "Unghia Mamei", -- Mom's Toenail
    [T_ID .. 17] = "Black Lipstick", -- Black Lipstick
    [T_ID .. 18] = "Bible Tract", -- Bible Tract
    [T_ID .. 19] = "Paper Clip", -- Paper Clip
    [T_ID .. 20] = "Monkey Paw", -- Monkey Paw
    [T_ID .. 21] = "Mysterious Paper", -- Mysterious Paper
    [T_ID .. 22] = "Daemon's Tail", -- Daemon's Tail
    [T_ID .. 23] = "Missing Poster", -- Missing Poster
    [T_ID .. 24] = "Bănuț Murdar", -- Butt Penny
    [T_ID .. 25] = "Mysterious Candy", -- Mysterious Candy
    [T_ID .. 26] = "Ancylostoma", -- Hook Worm
    [T_ID .. 27] = "Whip Worm", -- Whip Worm
    [T_ID .. 28] = "Broken Ankh", -- Broken Ankh
    [T_ID .. 29] = "Fish Head", -- Fish Head
    [T_ID .. 30] = "Pinky Eye", -- Pinky Eye
    [T_ID .. 31] = "Push Pin", -- Push Pin
    [T_ID .. 32] = "Ciupercă Pălarie", -- Liberty Cap
    [T_ID .. 33] = "Cordonul Ombilicald", -- Umbilical Cord
    [T_ID .. 34] = "Child's Heart", -- Child's Heart
    [T_ID .. 35] = "Curved Horn", -- Curved Horn
    [T_ID .. 36] = "Rusted Key", -- Rusted Key
    [T_ID .. 37] = "Goat Hoof", -- Goat Hoof
    [T_ID .. 38] = "Mom's Pearl", -- Mom's Pearl
    [T_ID .. 39] = "Cancer", -- Cancer
    [T_ID .. 40] = "Red Patch", -- Red Patch
    [T_ID .. 41] = "Match Stick", -- Match Stick
    [T_ID .. 42] = "Lucky Toe", -- Lucky Toe
    [T_ID .. 43] = "Cursed Skull", -- Cursed Skull
    [T_ID .. 44] = "Safety Cap", -- Safety Cap
    [T_ID .. 45] = "Ace of Spades", -- Ace of Spades
    [T_ID .. 46] = "Isaac's Fork", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "O Pagină Lipsă", -- A Missing Page
    [T_ID .. 49] = "Bănuț Însângerat", -- Bloody Penny
    [T_ID .. 50] = "Bănuț Ars", -- Burnt Penny
    [T_ID .. 51] = "Bănuț Plat", -- Flat Penny
    [T_ID .. 52] = "Counterfeit Penny", -- Counterfeit Penny
    [T_ID .. 53] = "Tick", -- Tick
    [T_ID .. 54] = "Isaac's Head", -- Isaac's Head
    [T_ID .. 55] = "Maggy's Faith", -- Maggy's Faith
    [T_ID .. 56] = "Judas' Tongue", -- Judas' Tongue
    [T_ID .. 57] = "???'s Soul", -- ???'s Soul
    [T_ID .. 58] = "Samson's Lock", -- Samson's Lock
    [T_ID .. 59] = "Cain's Eye", -- Cain's Eye
    [T_ID .. 60] = "Eve's Bird Foot", -- Eve's Bird Foot
    [T_ID .. 61] = "The Left Hand", -- The Left Hand
    [T_ID .. 62] = "Shiny Rock", -- Shiny Rock
    [T_ID .. 63] = "Safety Scissors", -- Safety Scissors
    [T_ID .. 64] = "Rainbow Worm", -- Rainbow Worm
    [T_ID .. 65] = "Tenie", -- Tape Worm
    [T_ID .. 66] = "Vierme Leneș", -- Lazy Worm
    [T_ID .. 67] = "Zar Spart", -- Cracked Dice
    [T_ID .. 68] = "Super Magnet", -- Super Magnet
    [T_ID .. 69] = "Polaroid Decolorat", -- Faded Polaroid
    [T_ID .. 70] = "Louse", -- Louse
    [T_ID .. 71] = "Bob's Bladder", -- Bob's Bladder
    [T_ID .. 72] = "Watch Battery", -- Watch Battery
    [T_ID .. 73] = "Blasting Cap", -- Blasting Cap
    [T_ID .. 74] = "Stud Finder", -- Stud Finder
    [T_ID .. 75] = "Error", -- Error
    [T_ID .. 76] = "Poker Chip", -- Poker Chip
    [T_ID .. 77] = "Blister", -- Blister
    [T_ID .. 78] = "Second Hand", -- Second Hand
    [T_ID .. 79] = "Endless Nameless", -- Endless Nameless
    [T_ID .. 80] = "Pană Neagră", -- Black Feather
    [T_ID .. 81] = "Blind Rage", -- Blind Rage
    [T_ID .. 82] = "Golden Horse Shoe", -- Golden Horse Shoe
    [T_ID .. 83] = "Store Key", -- Store Key
    [T_ID .. 84] = "Rib of Greed", -- Rib of Greed
    [T_ID .. 85] = "Karma", -- Karma
    [T_ID .. 86] = "Lil Larva", -- Lil Larva
    [T_ID .. 87] = "Mom's Locket", -- Mom's Locket
    [T_ID .. 88] = "NO!", -- NO!
    [T_ID .. 89] = "Child Leash", -- Child Leash
    [T_ID .. 90] = "Brown Cap", -- Brown Cap
    [T_ID .. 91] = "Meconium", -- Meconium
    [T_ID .. 92] = "Coroană Crăpată", -- Cracked Crown
    [T_ID .. 93] = "Used Diaper", -- Used Diaper
    [T_ID .. 94] = "Fish Tail", -- Fish Tail
    [T_ID .. 95] = "Black Tooth", -- Black Tooth
    [T_ID .. 96] = "Ouroboros Worm", -- Ouroboros Worm
    [T_ID .. 97] = "Tonsil", -- Tonsil
    [T_ID .. 98] = "Muci de Goblin", -- Nose Goblin
    [T_ID .. 99] = "Super Ball", -- Super Ball
    [T_ID .. 100] = "Vibrant Bulb", -- Vibrant Bulb
    [T_ID .. 101] = "Bec Stins", -- Dim Bulb
    [T_ID .. 102] = "Fragmented Card", -- Fragmented Card
    [T_ID .. 103] = "Equality!", -- Equality!
    [T_ID .. 104] = "Wish Bone", -- Wish Bone
    [T_ID .. 105] = "Bag Lunch", -- Bag Lunch
    [T_ID .. 106] = "Lost Cork", -- Lost Cork
    [T_ID .. 107] = "Inimă de Cioară", -- Crow Heart
    [T_ID .. 108] = "Walnut", -- Walnut
    [T_ID .. 109] = "Duct Tape", -- Duct Tape
    [T_ID .. 110] = "Dolar de Argint", -- Silver Dollar
    [T_ID .. 111] = "Coroană Însângerată", -- Bloody Crown
    [T_ID .. 112] = "Pay To Win", -- Pay To Win
    [T_ID .. 113] = "Locust of War", -- Locust of War
    [T_ID .. 114] = "Locust of Pestilence", -- Locust of Pestilence
    [T_ID .. 115] = "Locust of Famine", -- Locust of Famine
    [T_ID .. 116] = "Locust of Death", -- Locust of Death
    [T_ID .. 117] = "Locust of Conquest", -- Locust of Conquest
    [T_ID .. 118] = "Bat Wing", -- Bat Wing
    [T_ID .. 119] = "Celule Stem", -- Stem Cell
    [T_ID .. 120] = "Hairpin", -- Hairpin
    [T_ID .. 121] = "Wooden Cross", -- Wooden Cross
    [T_ID .. 122] = "Butter!", -- Butter!
    [T_ID .. 123] = "Filigree Feather", -- Filigree Feather
    [T_ID .. 124] = "Door Stop", -- Door Stop
    [T_ID .. 125] = "Extension Cord", -- Extension Cord
    [T_ID .. 126] = "Rotten Penny", -- Rotten Penny
    [T_ID .. 127] = "Baby-Bender", -- Baby-Bender
    [T_ID .. 128] = "Osul Degetului", -- Finger Bone
    [T_ID .. 129] = "Sfarmă-fălciz", -- Jawbreaker
    [T_ID .. 130] = "Pix Ros", -- Chewed Pen
    [T_ID .. 131] = "Bănuț Binecuvântat", -- Blessed Penny
    [T_ID .. 132] = "Seringă Spartă", -- Broken Syringe
    [T_ID .. 133] = "Short Fuse", -- Short Fuse
    [T_ID .. 134] = "Fasole Gigant", -- Gigante Bean
    [T_ID .. 135] = "O Brichetă", -- A Lighter
    [T_ID .. 136] = "Lacăt Spart", -- Broken Padlock
    [T_ID .. 137] = "Nu-mă-uita", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Amuletă Lacrimă", -- Teardrop Charm
    [T_ID .. 140] = "Apple of Sodom", -- Apple of Sodom
    [T_ID .. 141] = "Forgotten Lullaby", -- Forgotten Lullaby
    [T_ID .. 142] = "Beth's Faith", -- Beth's Faith
    [T_ID .. 143] = "Old Capacitor", -- Old Capacitor
    [T_ID .. 144] = "Brain Worm", -- Brain Worm
    [T_ID .. 145] = "Perfection", -- Perfection
    [T_ID .. 146] = "Devil's Crown", -- Devil's Crown
    [T_ID .. 147] = "Charged Penny", -- Charged Penny
    [T_ID .. 148] = "Friendship Necklace", -- Friendship Necklace
    [T_ID .. 149] = "Panic Button", -- Panic Button
    [T_ID .. 150] = "Blue Key", -- Blue Key
    [T_ID .. 151] = "Flat File", -- Flat File
    [T_ID .. 152] = "Telescope Lens", -- Telescope Lens
    [T_ID .. 153] = "Mom's Lock", -- Mom's Lock
    [T_ID .. 154] = "Dice Bag", -- Dice Bag
    [T_ID .. 155] = "Holy Crown", -- Holy Crown
    [T_ID .. 156] = "Mother's Kiss", -- Mother's Kiss
    [T_ID .. 157] = "Torn Card", -- Torn Card
    [T_ID .. 158] = "Torn Pocket", -- Torn Pocket
    [T_ID .. 159] = "Gilded Key", -- Gilded Key
    [T_ID .. 160] = "Lucky Sack", -- Lucky Sack
    [T_ID .. 161] = "Wicked Crown", -- Wicked Crown
    [T_ID .. 162] = "Azazel's Stump", -- Azazel's Stump
    [T_ID .. 163] = "Dingle Berry", -- Dingle Berry
    [T_ID .. 164] = "Ring Cap", -- Ring Cap
    [T_ID .. 165] = "Nuh Uh!", -- Nuh Uh!
    [T_ID .. 166] = "Modeling Clay", -- Modeling Clay
    [T_ID .. 167] = "Polished Bone", -- Polished Bone
    [T_ID .. 168] = "Hollow Heart", -- Hollow Heart
    [T_ID .. 169] = "Kid's Drawing", -- Kid's Drawing
    [T_ID .. 170] = "Crystal Key", -- Crystal Key
    [T_ID .. 171] = "Keeper's Bargain", -- Keeper's Bargain
    [T_ID .. 172] = "Cursed Penny", -- Cursed Penny
    [T_ID .. 173] = "Your Soul", -- Your Soul
    [T_ID .. 174] = "Number Magnet", -- Number Magnet
    [T_ID .. 175] = "Strange Key", -- Strange Key
    [T_ID .. 176] = "Lil Clot", -- Lil Clot
    [T_ID .. 177] = "Temporary Tattoo", -- Temporary Tattoo
    [T_ID .. 178] = "Swallowed M80", -- Swallowed M80
    [T_ID .. 179] = "RC Remote", -- RC Remote
    [T_ID .. 180] = "Found Soul", -- Found Soul
    [T_ID .. 181] = "Expansion Pack", -- Expansion Pack
    [T_ID .. 182] = "Beth's Essence", -- Beth's Essence
    [T_ID .. 183] = "The Twins", -- The Twins
    [T_ID .. 184] = "Adoption Papers", -- Adoption Papers
    [T_ID .. 185] = "Cricket Leg", -- Cricket Leg
    [T_ID .. 186] = "Apollyon's Best Friend", -- Apollyon's Best Friend
    [T_ID .. 187] = "Broken Glasses", -- Broken Glasses
    [T_ID .. 188] = "Ice Cube", -- Ice Cube
    [T_ID .. 189] = "Sigil of Baphomet", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Nebunul", -- 0 - The Fool
    [Card_ID .. 2] = "I - Magicianul", -- I - The Magician
    [Card_ID .. 3] = "II - Marea Preoteasă", -- II - The High Priestess
    [Card_ID .. 4] = "III - Împărăteasa", -- III - The Empress
    [Card_ID .. 5] = "IV - Împăratul", -- IV - The Emperor
    [Card_ID .. 6] = "V - Marele Preot", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Îndrăgostiții", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Faetonul", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Dreptate", -- VIII - Justice
    [Card_ID .. 10] = "IX - Eremitul", -- IX - The Hermit
    [Card_ID .. 11] = "X - Roata norocului", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Forța", -- XI - Strength
    [Card_ID .. 13] = "XII - Spânzuratul", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Moartea", -- XIII - Death
    [Card_ID .. 15] = "XIV - Echilibrul", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Diavolul", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Turnul", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Steaua", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Luna", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Soarele", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Judecata", -- XX - Judgement
    [Card_ID .. 22] = "", -- XXI - The World
    [Card_ID .. 23] = "", -- 2 of Clubs
    [Card_ID .. 24] = "", -- 2 of Diamonds
    [Card_ID .. 25] = "", -- 2 of Spades
    [Card_ID .. 26] = "", -- 2 of Hearts
    [Card_ID .. 27] = "", -- Ace of Clubs
    [Card_ID .. 28] = "", -- Ace of Diamonds
    [Card_ID .. 29] = "", -- Ace of Spades
    [Card_ID .. 30] = "", -- Ace of Hearts
    [Card_ID .. 31] = "", -- Joker
    [Card_ID .. 32] = "", -- Hagalaz
    [Card_ID .. 33] = "", -- Jera
    [Card_ID .. 34] = "", -- Ehwaz
    [Card_ID .. 35] = "", -- Dagaz
    [Card_ID .. 36] = "", -- Ansuz
    [Card_ID .. 37] = "", -- Perthro
    [Card_ID .. 38] = "", -- Berkano
    [Card_ID .. 39] = "", -- Algiz
    [Card_ID .. 40] = "", -- Blank Rune
    [Card_ID .. 41] = "", -- Black Rune
    [Card_ID .. 42] = "", -- Chaos Card
    [Card_ID .. 43] = "", -- Credit Card
    [Card_ID .. 44] = "", -- Rules Card
    [Card_ID .. 45] = "", -- A Card Against Humanity
    [Card_ID .. 46] = "", -- Suicide King
    [Card_ID .. 47] = "", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "", -- ? Card
    [Card_ID .. 49] = "", -- Dice Shard
    [Card_ID .. 50] = "", -- Emergency Contact
    [Card_ID .. 51] = "", -- Holy Card
    [Card_ID .. 52] = "", -- Huge Growth
    [Card_ID .. 53] = "", -- Ancient Recall
    [Card_ID .. 54] = "", -- Era Walk
    [Card_ID .. 55] = "", -- Rune Shard
    [Card_ID .. 56] = "", -- 0 - The Fool?
    [Card_ID .. 57] = "", -- I - The Magician?
    [Card_ID .. 58] = "", -- II - The High Priestess?
    [Card_ID .. 59] = "", -- III - The Empress?
    [Card_ID .. 60] = "", -- IV - The Emperor?
    [Card_ID .. 61] = "", -- V - The Hierophant?
    [Card_ID .. 62] = "", -- VI - The Lovers?
    [Card_ID .. 63] = "", -- VII - The Chariot?
    [Card_ID .. 64] = "", -- VIII - Justice?
    [Card_ID .. 65] = "", -- IX - The Hermit?
    [Card_ID .. 66] = "", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "", -- XI - Strength?
    [Card_ID .. 68] = "", -- XII - The Hanged Man?
    [Card_ID .. 69] = "", -- XIII - Death?
    [Card_ID .. 70] = "", -- XIV - Temperance?
    [Card_ID .. 71] = "", -- XV - The Devil?
    [Card_ID .. 72] = "", -- XVI - The Tower?
    [Card_ID .. 73] = "", -- XVII - The Stars?
    [Card_ID .. 74] = "", -- XVIII - The Moon?
    [Card_ID .. 75] = "", -- XIX - The Sun?
    [Card_ID .. 76] = "", -- XX - Judgement?
    [Card_ID .. 77] = "", -- XXI - The World?
    [Card_ID .. 78] = "", -- Cracked Key
    [Card_ID .. 79] = "", -- Queen of Hearts
    [Card_ID .. 80] = "", -- Wild Card
    [Card_ID .. 81] = "", -- Soul of Isaac
    [Card_ID .. 82] = "", -- Soul of Magdalene
    [Card_ID .. 83] = "", -- Soul of Cain
    [Card_ID .. 84] = "", -- Soul of Judas
    [Card_ID .. 85] = "", -- Soul of ???
    [Card_ID .. 86] = "", -- Soul of Eve
    [Card_ID .. 87] = "", -- Soul of Samson
    [Card_ID .. 88] = "", -- Soul of Azazel
    [Card_ID .. 89] = "", -- Soul of Lazarus
    [Card_ID .. 90] = "", -- Soul of Eden
    [Card_ID .. 91] = "", -- Soul of the Lost
    [Card_ID .. 92] = "", -- Soul of Lilith
    [Card_ID .. 93] = "", -- Soul of the Keeper
    [Card_ID .. 94] = "", -- Soul of Apollyon
    [Card_ID .. 95] = "", -- Soul of the Forgotten
    [Card_ID .. 96] = "", -- Soul of Bethany
    [Card_ID .. 97] = "", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "", -- Bad Gas
    [Pill_ID .. 2] = "", -- Bad Trip
    [Pill_ID .. 3] = "", -- Balls of Steel
    [Pill_ID .. 4] = "", -- Bombs are Key
    [Pill_ID .. 5] = "", -- Explosive Diarrhea
    [Pill_ID .. 6] = "", -- Full Health
    [Pill_ID .. 7] = "", -- Health Down
    [Pill_ID .. 8] = "", -- Health Up
    [Pill_ID .. 9] = "", -- I Found Pills
    [Pill_ID .. 10] = "", -- Puberty
    [Pill_ID .. 11] = "", -- Pretty Fly
    [Pill_ID .. 12] = "", -- Range Down
    [Pill_ID .. 13] = "", -- Range Up
    [Pill_ID .. 14] = "", -- Speed Down
    [Pill_ID .. 15] = "", -- Speed Up
    [Pill_ID .. 16] = "", -- Tears Down
    [Pill_ID .. 17] = "", -- Tears Up
    [Pill_ID .. 18] = "", -- Luck Down
    [Pill_ID .. 19] = "", -- Luck Up
    [Pill_ID .. 20] = "", -- Telepills
    [Pill_ID .. 21] = "", -- 48 Hour Energy!
    [Pill_ID .. 22] = "", -- Hematemesis
    [Pill_ID .. 23] = "", -- Paralysis
    [Pill_ID .. 24] = "", -- I can see forever!
    [Pill_ID .. 25] = "", -- Pheromones
    [Pill_ID .. 26] = "", -- Amnesia
    [Pill_ID .. 27] = "", -- Lemon Party
    [Pill_ID .. 28] = "", -- R U A Wizard?
    [Pill_ID .. 29] = "", -- Percs!
    [Pill_ID .. 30] = "", -- Addicted!
    [Pill_ID .. 31] = "", -- Re-Lax
    [Pill_ID .. 32] = "", -- ???
    [Pill_ID .. 33] = "", -- One makes you larger
    [Pill_ID .. 34] = "", -- One makes you small
    [Pill_ID .. 35] = "", -- Infested!
    [Pill_ID .. 36] = "", -- Infested?
    [Pill_ID .. 37] = "", -- Power Pill!
    [Pill_ID .. 38] = "", -- Retro Vision
    [Pill_ID .. 39] = "", -- Friends Till The End!
    [Pill_ID .. 40] = "", -- X-Lax
    [Pill_ID .. 41] = "", -- Something's wrong...
    [Pill_ID .. 42] = "", -- I'm Drowsy...
    [Pill_ID .. 43] = "", -- I'm Excited!!
    [Pill_ID .. 44] = "", -- Gulp!
    [Pill_ID .. 45] = "", -- Horf!
    [Pill_ID .. 46] = "", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "", -- Vurp!
    [Pill_ID .. 48] = "", -- Shot speed Down
    [Pill_ID .. 49] = "", -- Shot speed Up
    [Pill_ID .. 50] = "", -- Experimental Pill
    [Pill_ID .. 9999] = "", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])