-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "ro_ro"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Ceapa Tristă", -- The Sad Onion
    [C_ID .. 2] = "Ochiul Interior", -- The Inner Eye
    [C_ID .. 3] = "Lingura Îndoită", -- Spoon Bender
    [C_ID .. 4] = "Cap de Greier", -- Cricket's Head
    [C_ID .. 5] = "Reflexia Mea", -- My Reflection
    [C_ID .. 6] = "Numărul Unu", -- Number One
    [C_ID .. 7] = "Sângele Martirului", -- Blood of the Martyr
    [C_ID .. 8] = "Fratele Bobby", -- Brother Bobby
    [C_ID .. 9] = "Skatole", -- Skatole
    [C_ID .. 10] = "Aureola de Muște", -- Halo of Flies
    [C_ID .. 11] = "1sus!", -- 1up!
    [C_ID .. 12] = "Ciupercă Magică", -- Magic Mushroom
    [C_ID .. 13] = "Virusul", -- The Virus
    [C_ID .. 14] = "Furie cu Steroizi", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Ficat Crud", -- Raw Liver
    [C_ID .. 17] = "Cheia Schelet", -- Skeleton Key
    [C_ID .. 18] = "Un Leu", -- A Dollar
    [C_ID .. 19] = "Boom!", -- Boom!
    [C_ID .. 20] = "Transcendență", -- Transcendence
    [C_ID .. 21] = "Busola", -- The Compass
    [C_ID .. 22] = "Prânz", -- Lunch
    [C_ID .. 23] = "Cină", -- Dinner
    [C_ID .. 24] = "Desert", -- Dessert
    [C_ID .. 25] = "Mic Dejun", -- Breakfast
    [C_ID .. 26] = "Carne Stricată", -- Rotten Meat
    [C_ID .. 27] = "Lingură de Lemn", -- Wooden Spoon
    [C_ID .. 28] = "Cureaua", -- The Belt
    [C_ID .. 29] = "Chiloții Mamei", -- Mom's Underwear
    [C_ID .. 30] = "Tocurile Mamei", -- Mom's Heels
    [C_ID .. 31] = "Rujul Mamei", -- Mom's Lipstick
    [C_ID .. 32] = "Cuier de Sârmă", -- Wire Coat Hanger
    [C_ID .. 33] = "Biblia", -- The Bible
    [C_ID .. 34] = "Cartea lui Belial", -- The Book of Belial
    [C_ID .. 35] = "Necronomiconul", -- The Necronomicon
    [C_ID .. 36] = "Rahatul", -- The Poop
    [C_ID .. 37] = "Dl. Bum", -- Mr. Boom
    [C_ID .. 38] = "Capul lui Tammy", -- Tammy's Head
    [C_ID .. 39] = "Sutienul Mamei", -- Mom's Bra
    [C_ID .. 40] = "Kamikaze!", -- Kamikaze!
    [C_ID .. 41] = "Tamponul Mamei", -- Mom's Pad
    [C_ID .. 42] = "Capul putrezit a lui Bob", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Teleportare!", -- Teleport!
    [C_ID .. 45] = "Yum, Inimă", -- Yum Heart
    [C_ID .. 46] = "Piciorul Norocos", -- Lucky Foot
    [C_ID .. 47] = "Telecomanda Doctorului", -- Doctor's Remote
    [C_ID .. 48] = "Săgeata lui Cupid", -- Cupid's Arrow
    [C_ID .. 49] = "Kamehame..!!!", -- Shoop da Whoop!
    [C_ID .. 50] = "Steven", -- Steven
    [C_ID .. 51] = "Pentagramă", -- Pentagram
    [C_ID .. 52] = "Dl. Fetus", -- Dr. Fetus
    [C_ID .. 53] = "Magnet", -- Magneto
    [C_ID .. 54] = "Harta Comorilor", -- Treasure Map
    [C_ID .. 55] = "Ochiul Mamei", -- Mom's Eye
    [C_ID .. 56] = "Accidentul Lămâii", -- Lemon Mishap
    [C_ID .. 57] = "Admirație Distantă", -- Distant Admiration
    [C_ID .. 58] = "Cartea Umbrelor", -- Book of Shadows
    [C_ID .. 59] = "Cartea lui Belial", -- The Book of Belial
    [C_ID .. 60] = "Scara", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Farmecul Vampirului", -- Charm of the Vampire
    [C_ID .. 63] = "Bateria", -- The Battery
    [C_ID .. 64] = "Vânzarea Steam", -- Steam Sale
    [C_ID .. 65] = "Cartea de Bucate a Anarhistului", -- Anarchist Cookbook
    [C_ID .. 66] = "Clepsidra", -- The Hourglass
    [C_ID .. 67] = "Surioara Maggy", -- Sister Maggy
    [C_ID .. 68] = "Tehnologie", -- Technology
    [C_ID .. 69] = "Lapte cu Ciocolată", -- Chocolate Milk
    [C_ID .. 70] = "Hormoni de Creștere", -- Growth Hormones
    [C_ID .. 71] = "Mini Ciupercă", -- Mini Mush
    [C_ID .. 72] = "Rozariu", -- Rosary
    [C_ID .. 73] = "Un Cub de Carne", -- Cube of Meat
    [C_ID .. 74] = "Un Sfert", -- A Quarter
    [C_ID .. 75] = "PHD", -- PHD
    [C_ID .. 76] = "Viziune X-Ray", -- X-Ray Vision
    [C_ID .. 77] = "Micul Meu Unicorn", -- My Little Unicorn
    [C_ID .. 78] = "Cartea Apocalipsei", -- Book of Revelations
    [C_ID .. 79] = "Semnul", -- The Mark
    [C_ID .. 80] = "Pactul", -- The Pact
    [C_ID .. 81] = "Pisica Moartă", -- Dead Cat
    [C_ID .. 82] = "Stăpânul Gropii", -- Lord of the Pit
    [C_ID .. 83] = "Cuiul", -- The Nail
    [C_ID .. 84] = "Trebuie Să Ajungem Mai Adânc!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Set de Cărți", -- Deck of Cards
    [C_ID .. 86] = "Dintele lui Monstro", -- Monstro's Tooth
    [C_ID .. 87] = "Coarnele lui Loki", -- Loki's Horns
    [C_ID .. 88] = "Micul Dolofan", -- Little Chubby
    [C_ID .. 89] = "Mușcătură de Păianjen", -- Spider Bite
    [C_ID .. 90] = "Mica Piatră", -- The Small Rock
    [C_ID .. 91] = "Cască de Miner", -- Spelunker Hat
    [C_ID .. 92] = "Super Bandajul", -- Super Bandage
    [C_ID .. 93] = "Gamekid-ul", -- The Gamekid
    [C_ID .. 94] = "Sac de Bănuți", -- Sack of Pennies
    [C_ID .. 95] = "Robo-Bebeluș", -- Robo-Baby
    [C_ID .. 96] = "Micul C.H.A.D.", -- Little C.H.A.D.
    [C_ID .. 97] = "Cartea Păcatului", -- The Book of Sin
    [C_ID .. 98] = "Relicva", -- The Relic
    [C_ID .. 99] = "Micul Gish", -- Little Gish
    [C_ID .. 100] = "Micul Steven", -- Little Steven
    [C_ID .. 101] = "Aureola", -- The Halo
    [C_ID .. 102] = "Sticla de Pastile a Mamei", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Răceala Comună", -- The Common Cold
    [C_ID .. 104] = "Parazitul", -- The Parasite
    [C_ID .. 105] = "D6-le", -- The D6
    [C_ID .. 106] = "Dl. Mega", -- Mr. Mega
    [C_ID .. 107] = "Foarfece Zig-Zag", -- The Pinking Shears
    [C_ID .. 108] = "Napolitana", -- The Wafer
    [C_ID .. 109] = "Bani = Putere", -- Money = Power
    [C_ID .. 110] = "Lentilele Mamei", -- Mom's Contacts
    [C_ID .. 111] = "Fasolea", -- The Bean
    [C_ID .. 112] = "Îngerul Protector", -- Guardian Angel
    [C_ID .. 113] = "Bebelușul Demon", -- Demon Baby
    [C_ID .. 114] = "Cuțitul Mamei", -- Mom's Knife
    [C_ID .. 115] = "Tablă Ouija", -- Ouija Board
    [C_ID .. 116] = "9 Volți", -- 9 Volt
    [C_ID .. 117] = "Pasăre Moartă", -- Dead Bird
    [C_ID .. 118] = "Brimstone", -- Brimstone
    [C_ID .. 119] = "Pungă cu Sânge", -- Blood Bag
    [C_ID .. 120] = "Ciupercă Ciudată (Subțire)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Ciupercă Ciudată(Mare)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Prostituata Babilonului", -- Whore of Babylon
    [C_ID .. 123] = "Manualul Monștrilor", -- Monster Manual
    [C_ID .. 124] = "Pergamentele Mării Moarte", -- Dead Sea Scrolls
    [C_ID .. 125] = "Bobby-Bombă", -- Bobby-Bomb
    [C_ID .. 126] = "Lamă de Ras", -- Razor Blade
    [C_ID .. 127] = "Uită-mă Acum", -- Forget Me Now
    [C_ID .. 128] = "Singur Mereu", -- Forever Alone
    [C_ID .. 129] = "Găleată cu Untură", -- Bucket of Lard
    [C_ID .. 130] = "Un Ponei", -- A Pony
    [C_ID .. 131] = "Plasă cu Bombe", -- Bomb Bag
    [C_ID .. 132] = "O Bucată de Cărbune", -- A Lump of Coal
    [C_ID .. 133] = "Laba lui Guppy", -- Guppy's Paw
    [C_ID .. 134] = "Coada lui Guppy", -- Guppy's Tail
    [C_ID .. 135] = "Perfuzie", -- IV Bag
    [C_ID .. 136] = "Cel Mai Bun Prieten", -- Best Friend
    [C_ID .. 137] = "Detonator Telecomandă", -- Remote Detonator
    [C_ID .. 138] = "Stigmate", -- Stigmata
    [C_ID .. 139] = "Poșeta Mamei", -- Mom's Purse
    [C_ID .. 140] = "Blestemul lui Bob", -- Bob's Curse
    [C_ID .. 141] = "Băiatul Misterios", -- Pageant Boy
    [C_ID .. 142] = "Scapular", -- Scapular
    [C_ID .. 143] = "Minge Rapidă", -- Speed Ball
    [C_ID .. 144] = "Prieten Vagabond", -- Bum Friend
    [C_ID .. 145] = "Capul lui Guppy", -- Guppy's Head
    [C_ID .. 146] = "Carte de Rugăciuni", -- Prayer Card
    [C_ID .. 147] = "Târnăcopul lui Notch", -- Notched Axe
    [C_ID .. 148] = "Infestare", -- Infestation
    [C_ID .. 149] = "Ipecac", -- Ipecac
    [C_ID .. 150] = "Dragoste Dură", -- Tough Love
    [C_ID .. 151] = "Mulligan-ul", -- The Mulligan
    [C_ID .. 152] = "Tehnologia 2", -- Technology 2
    [C_ID .. 153] = "Păianjen Mutant", -- Mutant Spider
    [C_ID .. 154] = "Coajă Chimică", -- Chemical Peel
    [C_ID .. 155] = "Ochiul Rătăcit", -- The Peeper
    [C_ID .. 156] = "Obicei", -- Habit
    [C_ID .. 157] = "Poftă Sângeroasă", -- Bloody Lust
    [C_ID .. 158] = "Minge de Cristal", -- Crystal Ball
    [C_ID .. 159] = "Spiritul Nopții", -- Spirit of the Night
    [C_ID .. 160] = "Crapă Cerul", -- Crack the Sky
    [C_ID .. 161] = "Ankh", -- Ankh
    [C_ID .. 162] = "Crucea Celtică", -- Celtic Cross
    [C_ID .. 163] = "Bebelușul Fantomă", -- Ghost Baby
    [C_ID .. 164] = "Lumânarea", -- The Candle
    [C_ID .. 165] = "Pisica-cu-9-cozi", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Bebelușul Harlequin", -- Harlequin Baby
    [C_ID .. 168] = "Fătul Epic", -- Epic Fetus
    [C_ID .. 169] = "Polifem", -- Polyphemus
    [C_ID .. 170] = "Tăticul Picioare-Mari", -- Daddy Longlegs
    [C_ID .. 171] = "Fund de Păianjen", -- Spider Butt
    [C_ID .. 172] = "Cuțit de Jertfă", -- Sacrificial Dagger
    [C_ID .. 173] = "Mitră", -- Mitre
    [C_ID .. 174] = "Bebeluș Curcubeu", -- Rainbow Baby
    [C_ID .. 175] = "Cheile Tatălui", -- Dad's Key
    [C_ID .. 176] = "Celule Stem", -- Stem Cells
    [C_ID .. 177] = "Păcăneaua Portabilă", -- Portable Slot
    [C_ID .. 178] = "Apă Sfințită", -- Holy Water
    [C_ID .. 179] = "Soartă", -- Fate
    [C_ID .. 180] = "Fasolea Neagră", -- The Black Bean
    [C_ID .. 181] = "Ponei Alb", -- White Pony
    [C_ID .. 182] = "Inimă Sacră", -- Sacred Heart
    [C_ID .. 183] = "Scobitori", -- Tooth Picks
    [C_ID .. 184] = "Sfântul Graal", -- Holy Grail
    [C_ID .. 185] = "Porumbel Mort", -- Dead Dove
    [C_ID .. 186] = "Drepturi de Sânge", -- Blood Rights
    [C_ID .. 187] = "Mingea de Păr a lui Guppy", -- Guppy's Hairball
    [C_ID .. 188] = "Abel", -- Abel
    [C_ID .. 189] = "SMB Super Fan", -- SMB Super Fan
    [C_ID .. 190] = "Pyro", -- Pyro
    [C_ID .. 191] = "Bancnota de 3 Lei", -- 3 Dollar Bill
    [C_ID .. 192] = "Telepatie pentru Proști", -- Telepathy for Dummies
    [C_ID .. 193] = "CARNE!", -- MEAT!
    [C_ID .. 194] = "Mingea Adevărului", -- Magic 8 Ball
    [C_ID .. 195] = "Portofelul Mamei", -- Mom's Coin Purse
    [C_ID .. 196] = "Squeezy", -- Squeezy
    [C_ID .. 197] = "Sucul lui Iisus", -- Jesus Juice
    [C_ID .. 198] = "Cutie", -- Box
    [C_ID .. 199] = "Cheia Mamei", -- Mom's Key
    [C_ID .. 200] = "Fardul Mamei", -- Mom's Eyeshadow
    [C_ID .. 201] = "Țeavă din Fier", -- Iron Bar
    [C_ID .. 202] = "Atingerea lui Midas", -- Midas' Touch
    [C_ID .. 203] = "Pachet Modest", -- Humbleing Bundle
    [C_ID .. 204] = "Borsetă", -- Fanny Pack
    [C_ID .. 205] = "Ștecher Ascuțit", -- Sharp Plug
    [C_ID .. 206] = "Gilotină", -- Guillotine
    [C_ID .. 207] = "Minge din Bandaje", -- Ball of Bandages
    [C_ID .. 208] = "Cureaua Campionului", -- Champion Belt
    [C_ID .. 209] = "Bombe Fund", -- Butt Bombs
    [C_ID .. 210] = "Frunză Roasă", -- Gnawed Leaf
    [C_ID .. 211] = "Păianjen Bebeluș", -- Spiderbaby
    [C_ID .. 212] = "Zgarda lui Guppy", -- Guppy's Collar
    [C_ID .. 213] = "Contact Pierdut", -- Lost Contact
    [C_ID .. 214] = "Anemic", -- Anemic
    [C_ID .. 215] = "Cap de Capră", -- Goat Head
    [C_ID .. 216] = "Robe Ceremoniale", -- Ceremonial Robes
    [C_ID .. 217] = "Peruca Mamei", -- Mom's Wig
    [C_ID .. 218] = "Placentă", -- Placenta
    [C_ID .. 219] = "Bandaj Vechi", -- Old Bandage
    [C_ID .. 220] = "Bombe Triste", -- Sad Bombs
    [C_ID .. 221] = "Ciment de Cauciuc", -- Rubber Cement
    [C_ID .. 222] = "Anti-Gravitație", -- Anti-Gravity
    [C_ID .. 223] = "Piromaniac", -- Pyromaniac
    [C_ID .. 224] = "Corpul lui Cricket", -- Cricket's Body
    [C_ID .. 225] = "Masca Plăcerii", -- Gimpy
    [C_ID .. 226] = "Lotusul Negru", -- Black Lotus
    [C_ID .. 227] = "Pușculița Porcușor", -- Piggy Bank
    [C_ID .. 228] = "Parfumul Mamei", -- Mom's Perfume
    [C_ID .. 229] = "Plămânii lui Monstro", -- Monstro's Lung
    [C_ID .. 230] = "Abaddon", -- Abaddon
    [C_ID .. 231] = "Minge din Smoală", -- Ball of Tar
    [C_ID .. 232] = "Cronometru", -- Stop Watch
    [C_ID .. 233] = "Planeta Micuță", -- Tiny Planet
    [C_ID .. 234] = "Infestare 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "E. Coli", -- E. Coli
    [C_ID .. 237] = "Atingerea Morții", -- Death's Touch
    [C_ID .. 238] = "Piesă de cheie 1", -- Key Piece 1
    [C_ID .. 239] = "Piesă de cheie 2", -- Key Piece 2
    [C_ID .. 240] = "Tratament Experimental", -- Experimental Treatment
    [C_ID .. 241] = "Contractul de Dedesubt", -- Contract from Below
    [C_ID .. 242] = "Infamie", -- Infamy
    [C_ID .. 243] = "Scutul Treimii", -- Trinity Shield
    [C_ID .. 244] = "Tehn.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Hartă Albastră", -- Blue Map
    [C_ID .. 247] = "CMMP!", -- BFFS!
    [C_ID .. 248] = "Mintea Stupului", -- Hive Mind
    [C_ID .. 249] = "Sunt Opțiuni", -- There's Options
    [C_ID .. 250] = "Bombe Bogo", -- Bogo Bombs
    [C_ID .. 251] = "Pachetul Începătorului", -- Starter Deck
    [C_ID .. 252] = "Mica Punguță", -- Little Baggy
    [C_ID .. 253] = "Crusta Magică", -- Magic Scab
    [C_ID .. 254] = "Cheag de Sânge", -- Blood Clot
    [C_ID .. 255] = "Șurub", -- Screw
    [C_ID .. 256] = "Bombe Fierbinți", -- Hot Bombs
    [C_ID .. 257] = "Mintea de Foc", -- Fire Mind
    [C_ID .. 258] = "Nr. Lipsă", -- Missing No.
    [C_ID .. 259] = "Materie Neagră", -- Dark Matter
    [C_ID .. 260] = "Lumânarea Neagră", -- Black Candle
    [C_ID .. 261] = "Exoftalmie", -- Proptosis
    [C_ID .. 262] = "Pagina Pierdută 2", -- Missing Page 2
    [C_ID .. 263] = "Rună Clară", -- Clear Rune
    [C_ID .. 264] = "Musca Inteligentă", -- Smart Fly
    [C_ID .. 265] = "Bebeluș Uscat", -- Dry Baby
    [C_ID .. 266] = "Sac Suculent", -- Juicy Sack
    [C_ID .. 267] = "Robo-Bebeluș 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Bebeluș Putrezit", -- Rotten Baby
    [C_ID .. 269] = "Bebeluș Fără Cap", -- Headless Baby
    [C_ID .. 270] = "Lipitoare", -- Leech
    [C_ID .. 271] = "Sac Misterios", -- Mystery Sack
    [C_ID .. 272] = "CMBP", -- BBF
    [C_ID .. 273] = "Creierul lui Bob", -- Bob's Brain
    [C_ID .. 274] = "Cel Mai Bun Amic", -- Best Bud
    [C_ID .. 275] = "Micul Brimstone", -- Lil Brimstone
    [C_ID .. 276] = "Inima lui Isaac", -- Isaac's Heart
    [C_ID .. 277] = "Micul Bântuit", -- Lil Haunt
    [C_ID .. 278] = "Cerșetor Întunecat", -- Dark Bum
    [C_ID .. 279] = "Fan mare", -- Big Fan
    [C_ID .. 280] = "Sissy Picioare-Lungi", -- Sissy Longlegs
    [C_ID .. 281] = "Sac de Box", -- Punching Bag
    [C_ID .. 282] = "Cum să sari", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Carte Albă", -- Blank Card
    [C_ID .. 287] = "Cartea Secretelor", -- Book of Secrets
    [C_ID .. 288] = "Cutie cu Păianjeni", -- Box of Spiders
    [C_ID .. 289] = "Lumânarea Roșie", -- Red Candle
    [C_ID .. 290] = "Borcanul", -- The Jar
    [C_ID .. 291] = "Flush!", -- Flush!
    [C_ID .. 292] = "Biblia Satanică", -- Satanic Bible
    [C_ID .. 293] = "Capul lui Krampus", -- Head of Krampus
    [C_ID .. 294] = "Fasole cu Unt", -- Butter Bean
    [C_ID .. 295] = "Degete Magice", -- Magic Fingers
    [C_ID .. 296] = "Convertor", -- Converter
    [C_ID .. 297] = "Cutia Pandorei", -- Pandora's Box
    [C_ID .. 298] = "Buturugă de unicorn", -- Unicorn Stump
    [C_ID .. 299] = "Taur", -- Taurus
    [C_ID .. 300] = "Berbec", -- Aries
    [C_ID .. 301] = "Rac", -- Cancer
    [C_ID .. 302] = "Leu", -- Leo
    [C_ID .. 303] = "Fecioară", -- Virgo
    [C_ID .. 304] = "Balanță", -- Libra
    [C_ID .. 305] = "Scorpion", -- Scorpio
    [C_ID .. 306] = "Săgetător", -- Sagittarius
    [C_ID .. 307] = "Capricorn", -- Capricorn
    [C_ID .. 308] = "Vărsător", -- Aquarius
    [C_ID .. 309] = "Pești", -- Pisces
    [C_ID .. 310] = "Rimelul Evei", -- Eve's Mascara
    [C_ID .. 311] = "Umbra lui Iuda", -- Judas' Shadow
    [C_ID .. 312] = "Arcul lui Maggy", -- Maggy's Bow
    [C_ID .. 313] = "Mantia Sfântă", -- Holy Mantle
    [C_ID .. 314] = "Coapse Grase", -- Thunder Thighs
    [C_ID .. 315] = "Atractor Ciudat", -- Strange Attractor
    [C_ID .. 316] = "Ochi Blestemat", -- Cursed Eye
    [C_ID .. 317] = "Lichid misterios", -- Mysterious Liquid
    [C_ID .. 318] = "Gemeni", -- Gemini
    [C_ID .. 319] = "Celălalt Ochi a lui Cain", -- Cain's Other Eye
    [C_ID .. 320] = "Singurul Prieten a lui ???", -- ???'s Only Friend
    [C_ID .. 321] = "Lanțurile lui Samson", -- Samson's Chains
    [C_ID .. 322] = "Bebeluș Mongo", -- Mongo Baby
    [C_ID .. 323] = "Lacrimile lui Isaac", -- Isaac's Tears
    [C_ID .. 324] = "Undefined", -- Undefined
    [C_ID .. 325] = "Foarfece", -- Scissors
    [C_ID .. 326] = "Respirația Vieții", -- Breath of Life
    [C_ID .. 327] = "Polaroidul", -- The Polaroid
    [C_ID .. 328] = "Negativul", -- The Negative
    [C_ID .. 329] = "Tehnica Ludovico", -- The Ludovico Technique
    [C_ID .. 330] = "Lapte de Soia", -- Soy Milk
    [C_ID .. 331] = "Capul de zeu", -- Godhead
    [C_ID .. 332] = "Zdrențele lui Lazarus", -- Lazarus' Rags
    [C_ID .. 333] = "Mintea", -- The Mind
    [C_ID .. 334] = "Corpul", -- The Body
    [C_ID .. 335] = "Sufletul", -- The Soul
    [C_ID .. 336] = "Ceapă Moartă", -- Dead Onion
    [C_ID .. 337] = "Ceas stricat", -- Broken Watch
    [C_ID .. 338] = "Bumerangul", -- The Boomerang
    [C_ID .. 339] = "Ac de Siguranță", -- Safety Pin
    [C_ID .. 340] = "Pastilă cu cofeină", -- Caffeine Pill
    [C_ID .. 341] = "Fotografie ruptă", -- Torn Photo
    [C_ID .. 342] = "Ciupercă Albastră", -- Blue Cap
    [C_ID .. 343] = "Cheie cu zăvor", -- Latch Key
    [C_ID .. 344] = "Cutie de Chibrituri", -- Match Book
    [C_ID .. 345] = "Synthol", -- Synthoil
    [C_ID .. 346] = "O Gustare", -- A Snack
    [C_ID .. 347] = "Diplopia", -- Diplopia
    [C_ID .. 348] = "Placebo", -- Placebo
    [C_ID .. 349] = "Monedă de Lemn", -- Wooden Nickel
    [C_ID .. 350] = "Șoc Toxic", -- Toxic Shock
    [C_ID .. 351] = "Fasole Gigant", -- Mega Bean
    [C_ID .. 352] = "Tun de Sticlă", -- Glass Cannon
    [C_ID .. 353] = "Băiat Bombardier", -- Bomber Boy
    [C_ID .. 354] = "Popcorn Caramelizat", -- Crack Jacks
    [C_ID .. 355] = "Perlele Mamei", -- Mom's Pearls
    [C_ID .. 356] = "Baterie de Mașină", -- Car Battery
    [C_ID .. 357] = "Cutie de Prieteni", -- Box of Friends
    [C_ID .. 358] = "Vrăjitorul", -- The Wiz
    [C_ID .. 359] = "Cuie de 8 Inci", -- 8 Inch Nails
    [C_ID .. 360] = "Incubus", -- Incubus
    [C_ID .. 361] = "Răsplata Destinului", -- Fate's Reward
    [C_ID .. 362] = "Micul Cufăr", -- Lil Chest
    [C_ID .. 363] = "Protector Jurat", -- Sworn Protector
    [C_ID .. 364] = "Zona Prietenilor", -- Friend Zone
    [C_ID .. 365] = "Musca Pierdută", -- Lost Fly
    [C_ID .. 366] = "Bombe Împrăștiate", -- Scatter Bombs
    [C_ID .. 367] = "Bombe Lipicioase", -- Sticky Bombs
    [C_ID .. 368] = "Epiforă", -- Epiphora
    [C_ID .. 369] = "Continuum", -- Continuum
    [C_ID .. 370] = "Dl. Dolly", -- Mr. Dolly
    [C_ID .. 371] = "Blestemul Turnului", -- Curse of the Tower
    [C_ID .. 372] = "Bebeluș Încărcat", -- Charged Baby
    [C_ID .. 373] = "Ochii Morți", -- Dead Eye
    [C_ID .. 374] = "Lumină Sfântă", -- Holy Light
    [C_ID .. 375] = "Pălărie Host", -- Host Hat
    [C_ID .. 376] = "Reprovizionare", -- Restock
    [C_ID .. 377] = "Sacul Exploziv", -- Bursting Sack
    [C_ID .. 378] = "Nr. 2", -- No. 2
    [C_ID .. 379] = "Pupila Duplex", -- Pupula Duplex
    [C_ID .. 380] = "Plătește pentru a Juca", -- Pay To Play
    [C_ID .. 381] = "Binecuvântarea lui Eden", -- Eden's Blessing
    [C_ID .. 382] = "Minge Prietenoasă", -- Friendly Ball
    [C_ID .. 383] = "Detonator de Lacrimi", -- Tear Detonator
    [C_ID .. 384] = "Micul Gurdy", -- Lil Gurdy
    [C_ID .. 385] = "Bumbo", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Censer", -- Censer
    [C_ID .. 388] = "Cerșetor de Chei", -- Key Bum
    [C_ID .. 389] = "Sac cu Rune", -- Rune Bag
    [C_ID .. 390] = "Seraphim", -- Seraphim
    [C_ID .. 391] = "Trădare", -- Betrayal
    [C_ID .. 392] = "Zodiac", -- Zodiac
    [C_ID .. 393] = "Sărutul Șarpelui", -- Serpent's Kiss
    [C_ID .. 394] = "Marcat", -- Marked
    [C_ID .. 395] = "Tehnologie X", -- Tech X
    [C_ID .. 396] = "Brici Ventricular", -- Ventricle Razor
    [C_ID .. 397] = "Rază Tractoare", -- Tractor Beam
    [C_ID .. 398] = "Carnea lui Dumnezeu", -- God's Flesh
    [C_ID .. 399] = "Gura Abisului", -- Maw of the Void
    [C_ID .. 400] = "Sulița Destinului", -- Spear of Destiny
    [C_ID .. 401] = "Exploziv", -- Explosivo
    [C_ID .. 402] = "Haos", -- Chaos
    [C_ID .. 403] = "Mod Păianjen", -- Spider Mod
    [C_ID .. 404] = "Bebeluș Beșinos", -- Farting Baby
    [C_ID .. 405] = "Gândac GB", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Puritate", -- Purity
    [C_ID .. 408] = "Athame", -- Athame
    [C_ID .. 409] = "Vas Gol", -- Empty Vessel
    [C_ID .. 410] = "Ochi Rău", -- Evil Eye
    [C_ID .. 411] = "Sânge Pătimaș", -- Lusty Blood
    [C_ID .. 412] = "Zămislire de Cambion", -- Cambion Conception
    [C_ID .. 413] = "Zămislire Imaculată", -- Immaculate Conception
    [C_ID .. 414] = "Mai Multe Opțiuni", -- More Options
    [C_ID .. 415] = "Coroană de Lumină", -- Crown Of Light
    [C_ID .. 416] = "Buzunare Adânci", -- Deep Pockets
    [C_ID .. 417] = "Succubus", -- Succubus
    [C_ID .. 418] = "Prăjitură cu Fructe", -- Fruit Cake
    [C_ID .. 419] = "Teleportare 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Pudră Neagră", -- Black Powder
    [C_ID .. 421] = "Fasole Roșie", -- Kidney Bean
    [C_ID .. 422] = "Clepsidră Strălucitoare", -- Glowing Hourglass
    [C_ID .. 423] = "Cercul de Protecție", -- Circle of Protection
    [C_ID .. 424] = "Cap de Sac", -- Sack Head
    [C_ID .. 425] = "Lumină de Noapte", -- Night Light
    [C_ID .. 426] = "Fan Obsedat", -- Obsessed Fan
    [C_ID .. 427] = "Miner Artizan", -- Mine Crafter
    [C_ID .. 428] = "Pijamale", -- PJs
    [C_ID .. 429] = "Capul Păzitorului", -- Head of the Keeper
    [C_ID .. 430] = "Tata Muscă", -- Papa Fly
    [C_ID .. 431] = "Bebeluș Multi-dimensional", -- Multidimensional Baby
    [C_ID .. 432] = "Bombe cu Sclipici", -- Glitter Bombs
    [C_ID .. 433] = "Umbra Mea", -- My Shadow
    [C_ID .. 434] = "Borcan de Muște", -- Jar of Flies
    [C_ID .. 435] = "Micul Loki", -- Lil Loki
    [C_ID .. 436] = "Lapte!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Binky", -- Binky
    [C_ID .. 439] = "Cutia Mamei", -- Mom's Box
    [C_ID .. 440] = "Piatră la Rinichi", -- Kidney Stone
    [C_ID .. 441] = "Mega Explozie", -- Mega Blast
    [C_ID .. 442] = "Coroana Prințului Întunecat", -- Dark Prince's Crown
    [C_ID .. 443] = "Măr!", -- Apple!
    [C_ID .. 444] = "Creion cu Plumb", -- Lead Pencil
    [C_ID .. 445] = "Dintele Câinelui", -- Dog Tooth
    [C_ID .. 446] = "Dintele Mort", -- Dead Tooth
    [C_ID .. 447] = "Fasole Persistentă", -- Linger Bean
    [C_ID .. 448] = "Bucată de Sticlă", -- Shard of Glass
    [C_ID .. 449] = "Placă de Metal", -- Metal Plate
    [C_ID .. 450] = "Ochiul Lăcomiei", -- Eye of Greed
    [C_ID .. 451] = "Tapiserie de Tarot", -- Tarot Cloth
    [C_ID .. 452] = "Vene Varicoase", -- Varicose Veins
    [C_ID .. 453] = "Fractură Deschisă", -- Compound Fracture
    [C_ID .. 454] = "Polidactilie", -- Polydactyly
    [C_ID .. 455] = "Bănuțul Pierdut a lui Tata", -- Dad's Lost Coin
    [C_ID .. 456] = "Gustare de Seară", -- Midnight Snack
    [C_ID .. 457] = "Cap de Con", -- Cone Head
    [C_ID .. 458] = "Buric", -- Belly Button
    [C_ID .. 459] = "Sinuzită", -- Sinus Infection
    [C_ID .. 460] = "Glaucom", -- Glaucoma
    [C_ID .. 461] = "Parazitoid", -- Parasitoid
    [C_ID .. 462] = "Ochiul lui Belial", -- Eye of Belial
    [C_ID .. 463] = "Acid Sulfuric", -- Sulfuric Acid
    [C_ID .. 464] = "Glifă de Balanță", -- Glyph of Balance
    [C_ID .. 465] = "Băț Analog", -- Analog Stick
    [C_ID .. 466] = "Contagion", -- Contagion
    [C_ID .. 467] = "Deget!", -- Finger!
    [C_ID .. 468] = "Umbra", -- Shade
    [C_ID .. 469] = "Depresie", -- Depression
    [C_ID .. 470] = "Hushy", -- Hushy
    [C_ID .. 471] = "Micul Monstro", -- Lil Monstro
    [C_ID .. 472] = "Regele Bebeluș", -- King Baby
    [C_ID .. 473] = "Marele Grăsuț", -- Big Chubby
    [C_ID .. 474] = "Tun de Sticlă Spart", -- Broken Glass Cannon
    [C_ID .. 475] = "Planul C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Vidul", -- Void
    [C_ID .. 478] = "Pauză", -- Pause
    [C_ID .. 479] = "Topitor", -- Smelter
    [C_ID .. 480] = "Compost", -- Compost
    [C_ID .. 481] = "Dataminer", -- Dataminer
    [C_ID .. 482] = "Clicker", -- Clicker
    [C_ID .. 483] = "Mama Mega!", -- Mama Mega!
    [C_ID .. 484] = "Stai, ce?", -- Wait What?
    [C_ID .. 485] = "Monedă Strâmbă", -- Crooked Penny
    [C_ID .. 486] = "Briciul Tocit", -- Dull Razor
    [C_ID .. 487] = "Curățăor de Cartofi", -- Potato Peeler
    [C_ID .. 488] = "Metronom", -- Metronome
    [C_ID .. 489] = "D Infinit", -- D Infinity
    [C_ID .. 490] = "Sufletul lui Eden", -- Eden's Soul
    [C_ID .. 491] = "Bebeluș Acid", -- Acid Baby
    [C_ID .. 492] = "YO ASCULTĂ!", -- YO LISTEN!
    [C_ID .. 493] = "Adrenalină", -- Adrenaline
    [C_ID .. 494] = "Scara lui Iacob", -- Jacob's Ladder
    [C_ID .. 495] = "Ardei Fantomă", -- Ghost Pepper
    [C_ID .. 496] = "Eutanasiere", -- Euthanasia
    [C_ID .. 497] = "Chioți de Camunflat", -- Camo Undies
    [C_ID .. 498] = "Dualitate", -- Duality
    [C_ID .. 499] = "Euharistie", -- Eucharist
    [C_ID .. 500] = "Sacul cu Saci", -- Sack of Sacks
    [C_ID .. 501] = "Esofagul lui Greed", -- Greed's Gullet
    [C_ID .. 502] = "Coș Mare", -- Large Zit
    [C_ID .. 503] = "Corn Micuț", -- Little Horn
    [C_ID .. 504] = "Pepită Maro", -- Brown Nugget
    [C_ID .. 505] = "Poke Go", -- Poke Go
    [C_ID .. 506] = "Înjunghie în Spate", -- Backstabber
    [C_ID .. 507] = "Pai Ascuțit", -- Sharp Straw
    [C_ID .. 508] = "Briciul Mamei", -- Mom's Razor
    [C_ID .. 509] = "Ochi Însângerat", -- Bloodshot Eye
    [C_ID .. 510] = "Delirant", -- Delirious
    [C_ID .. 511] = "Musca Furioasă", -- Angry Fly
    [C_ID .. 512] = "Gaura Neagră", -- Black Hole
    [C_ID .. 513] = "Bozo", -- Bozo
    [C_ID .. 514] = "Modem Stricat", -- Broken Modem
    [C_ID .. 515] = "Cadou Misterios", -- Mystery Gift
    [C_ID .. 516] = "Stropitor", -- Sprinkler
    [C_ID .. 517] = "Bombe Rapide", -- Fast Bombs
    [C_ID .. 518] = "Prieten în Cutie", -- Buddy in a Box
    [C_ID .. 519] = "Micul Delirium", -- Lil Delirium
    [C_ID .. 520] = "Cabluri de Pornire", -- Jumper Cables
    [C_ID .. 521] = "Cupon", -- Coupon
    [C_ID .. 522] = "Telekineză", -- Telekinesis
    [C_ID .. 523] = "Cutie de Mutat", -- Moving Box
    [C_ID .. 524] = "Technologie Zero", -- Technology Zero
    [C_ID .. 525] = "Lepră", -- Leprosy
    [C_ID .. 526] = "7 Sigilii", -- 7 Seals
    [C_ID .. 527] = "Dl. EU!", -- Mr. ME!
    [C_ID .. 528] = "Prismă Angelică", -- Angelic Prism
    [C_ID .. 529] = "Sparge!", -- Pop!
    [C_ID .. 530] = "Lista Morții", -- Death's List
    [C_ID .. 531] = "Hemolacrie", -- Haemolacria
    [C_ID .. 532] = "Lachryphagy", -- Lachryphagy
    [C_ID .. 533] = "Trisagion", -- Trisagion
    [C_ID .. 534] = "Ghiozdan", -- Schoolbag
    [C_ID .. 535] = "Pătură", -- Blanket
    [C_ID .. 536] = "Altar Sacrificial", -- Sacrificial Altar
    [C_ID .. 537] = "Micul Vomer", -- Lil Spewer
    [C_ID .. 538] = "Mărgele", -- Marbles
    [C_ID .. 539] = "Ou Misterios", -- Mystery Egg
    [C_ID .. 540] = "Piatra Plată", -- Flat Stone
    [C_ID .. 541] = "Măduvă", -- Marrow
    [C_ID .. 542] = "Coastă Alunecoasă", -- Slipped Rib
    [C_ID .. 543] = "Rahat Binecuvântat", -- Hallowed Ground
    [C_ID .. 544] = "Coastă Ascuțită", -- Pointy Rib
    [C_ID .. 545] = "Cartea Morților", -- Book of the Dead
    [C_ID .. 546] = "Inelul Tatălui", -- Dad's Ring
    [C_ID .. 547] = "Acte de Divorț", -- Divorce Papers
    [C_ID .. 548] = "Mandibulă", -- Jaw Bone
    [C_ID .. 549] = "Oase Fragile", -- Brittle Bones
    [C_ID .. 550] = "Lopată Stricată", -- Broken Shovel
    [C_ID .. 551] = "Lopată Stricată", -- Broken Shovel
    [C_ID .. 552] = "Lopata Mamei", -- Mom's Shovel
    [C_ID .. 553] = "Mucormicoza", -- Mucormycosis
    [C_ID .. 554] = "DeSpaimă", -- 2Spooky
    [C_ID .. 555] = "Brici de Aur", -- Golden Razor
    [C_ID .. 556] = "Sulf", -- Sulfur
    [C_ID .. 557] = "Prăjitură cu Răvaș", -- Fortune Cookie
    [C_ID .. 558] = "Durere de Ochi", -- Eye Sore
    [C_ID .. 559] = "230 V", -- 120 Volt
    [C_ID .. 560] = "Doare", -- It Hurts
    [C_ID .. 561] = "Lapte de Migdale", -- Almond Milk
    [C_ID .. 562] = "La Pământ", -- Rock Bottom
    [C_ID .. 563] = "Bombe Homo", -- Nancy Bombs
    [C_ID .. 564] = "O Bucată de Săpun", -- A Bar of Soap
    [C_ID .. 565] = "Cățeluș Însângerat", -- Blood Puppy
    [C_ID .. 566] = "Prinzător de Vise", -- Dream Catcher
    [C_ID .. 567] = "Lumânare Pascală", -- Paschal Candle
    [C_ID .. 568] = "Intervenție Divină", -- Divine Intervention
    [C_ID .. 569] = "Jurământul de Sânge", -- Blood Oath
    [C_ID .. 570] = "Biscuite de Plasterină", -- Playdough Cookie
    [C_ID .. 571] = "Șosete de Orfan", -- Orphan Socks
    [C_ID .. 572] = "Ochiul Ocultului", -- Eye of the Occult
    [C_ID .. 573] = "Inimă Imaculată", -- Immaculate Heart
    [C_ID .. 574] = "Monstranţă", -- Monstrance
    [C_ID .. 575] = "Intrusul", -- The Intruder
    [C_ID .. 576] = "Minte Murdară", -- Dirty Mind
    [C_ID .. 577] = "Damocles", -- Damocles
    [C_ID .. 578] = "Limonadă Gratis", -- Free Lemonade
    [C_ID .. 579] = "Sabie Spirit", -- Spirit Sword
    [C_ID .. 580] = "Cheie Roșie", -- Red Key
    [C_ID .. 581] = "Muscă Psihică", -- Psy Fly
    [C_ID .. 582] = "Ciupercă Îndoită", -- Wavy Cap
    [C_ID .. 583] = "Rachetă într-un Borcan", -- Rocket in a Jar
    [C_ID .. 584] = "Cartea Virtuților", -- Book of Virtues
    [C_ID .. 585] = "Cutie de Alabastru", -- Alabaster Box
    [C_ID .. 586] = "Scara", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "Sol", -- Sol
    [C_ID .. 589] = "Luna", -- Luna
    [C_ID .. 590] = "Mercur", -- Mercurius
    [C_ID .. 591] = "Venus", -- Venus
    [C_ID .. 592] = "Terra", -- Terra
    [C_ID .. 593] = "Marte", -- Mars
    [C_ID .. 594] = "Jupiter", -- Jupiter
    [C_ID .. 595] = "Saturn", -- Saturnus
    [C_ID .. 596] = "Uranus", -- Uranus
    [C_ID .. 597] = "Neptun", -- Neptunus
    [C_ID .. 598] = "Pluto", -- Pluto
    [C_ID .. 599] = "Cap Voodoo", -- Voodoo Head
    [C_ID .. 600] = "Picături de Ochi", -- Eye Drops
    [C_ID .. 601] = "Act de Contriție", -- Act of Contrition
    [C_ID .. 602] = "Card de Membru", -- Member Card
    [C_ID .. 603] = "Pachet cu Baterii", -- Battery Pack
    [C_ID .. 604] = "Brățara Mamei", -- Mom's Bracelet
    [C_ID .. 605] = "Lingură pentru Înghețată", -- The Scooper
    [C_ID .. 606] = "Ruptură oculară", -- Ocular Rift
    [C_ID .. 607] = "Bebeluș Fiert", -- Boiled Baby
    [C_ID .. 608] = "Bebeluș Congelat", -- Freezer Baby
    [C_ID .. 609] = "D6 Etern", -- Eternal D6
    [C_ID .. 610] = "Colivie pentru Păsări", -- Bird Cage
    [C_ID .. 611] = "Laringe", -- Larynx
    [C_ID .. 612] = "Suflet Pierdut", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Bombe cu Sânge", -- Blood Bombs
    [C_ID .. 615] = "Micul Dumpy", -- Lil Dumpy
    [C_ID .. 616] = "Ochi de Pasăre", -- Bird's Eye
    [C_ID .. 617] = "Piatră Magnetică", -- Lodestone
    [C_ID .. 618] = "Roșie Stricată", -- Rotten Tomato
    [C_ID .. 619] = "Drept Ereditar", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Tocană Roșie", -- Red Stew
    [C_ID .. 622] = "Geneză", -- Genesis
    [C_ID .. 623] = "Cheie Ascuțită", -- Sharp Key
    [C_ID .. 624] = "Pachet Suplimentar", -- Booster Pack
    [C_ID .. 625] = "Mega Ciupercă", -- Mega Mush
    [C_ID .. 626] = "Bucată de Cuțit 1", -- Knife Piece 1
    [C_ID .. 627] = "Bucată de Cuțit 2", -- Knife Piece 2
    [C_ID .. 628] = "Certificat de Deces", -- Death Certificate
    [C_ID .. 629] = "Muscă Robot", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Satâr de Carne", -- Meat Cleaver
    [C_ID .. 632] = "Farmec Malefic", -- Evil Charm
    [C_ID .. 633] = "Dogmă", -- Dogma
    [C_ID .. 634] = "Purgatoriu", -- Purgatory
    [C_ID .. 635] = "Copci", -- Stitches
    [C_ID .. 636] = "Cheia R", -- R Key
    [C_ID .. 637] = "Picături de Impact", -- Knockout Drops
    [C_ID .. 638] = "Gumă de Șters", -- Eraser
    [C_ID .. 639] = "Inimă Dezgustătoare", -- Yuck Heart
    [C_ID .. 640] = "Urna Sufletelor", -- Urn of Souls
    [C_ID .. 641] = "Acheldama", -- Akeldama
    [C_ID .. 642] = "Piele Magică", -- Magic Skin
    [C_ID .. 643] = "Revelație", -- Revelation
    [C_ID .. 644] = "Premiu de Consolare", -- Consolation Prize
    [C_ID .. 645] = "Minitoma", -- Tinytoma
    [C_ID .. 646] = "Bombe Brimstone", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Volți", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Prune Fructate", -- Fruity Plum
    [C_ID .. 650] = "Fluierul lui Plum", -- Plum Flute
    [C_ID .. 651] = "Steaua din Betleem", -- Star of Bethlehem
    [C_ID .. 652] = "Bebeluș Cub", -- Cube Baby
    [C_ID .. 653] = "Vade Retro", -- Vade Retro
    [C_ID .. 654] = "Doctorat Fals", -- False PHD
    [C_ID .. 655] = "Învârte să Câștigi", -- Spin to Win
    [C_ID .. 656] = "Damocles", -- Damocles
    [C_ID .. 657] = "Vasculită", -- Vasculitis
    [C_ID .. 658] = "Celulă Gigant", -- Giant Cell
    [C_ID .. 659] = "Tropicamida ", -- Tropicamide
    [C_ID .. 660] = "Citit în Cărți", -- Card Reading
    [C_ID .. 661] = "Cvadrupleți", -- Quints
    [C_ID .. 662] = "", -- 
    [C_ID .. 663] = "Dinte și Unghii", -- Tooth and Nail
    [C_ID .. 664] = "Hiperfagie", -- Binge Eater
    [C_ID .. 665] = "Ochiul lui Guppy", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Sperietoare", -- Strawman
    [C_ID .. 668] = "Biletul Tatălui", -- Dad's Note
    [C_ID .. 669] = "Cârnat", -- Sausage
    [C_ID .. 670] = "Opțiuni?", -- Options?
    [C_ID .. 671] = "Inimă Bomboană", -- Candy Heart
    [C_ID .. 672] = "Un Kg de Carne", -- A Pound of Flesh
    [C_ID .. 673] = "Mântuire", -- Redemption
    [C_ID .. 674] = "Lanțuri Spirit", -- Spirit Shackles
    [C_ID .. 675] = "Sferă Spartă", -- Cracked Orb
    [C_ID .. 676] = "Inimă Goală", -- Empty Heart
    [C_ID .. 677] = "Proiecție Astrală", -- Astral Projection
    [C_ID .. 678] = "Cezariană", -- C Section
    [C_ID .. 679] = "Micul Abaddon", -- Lil Abaddon
    [C_ID .. 680] = "Răzbunarea lui Montezuma", -- Montezuma's Revenge
    [C_ID .. 681] = "Micul Portal", -- Lil Portal
    [C_ID .. 682] = "Prieten Vierme", -- Worm Friend
    [C_ID .. 683] = "Pinten Osos", -- Bone Spurs
    [C_ID .. 684] = "Suflet Înfometat", -- Hungry Soul
    [C_ID .. 685] = "Borcan cu Musculițe", -- Jar of Wisps
    [C_ID .. 686] = "Medalion Suflet", -- Soul Locket
    [C_ID .. 687] = "Găsitor de Prieteni", -- Friend Finder
    [C_ID .. 688] = "Copilul Interior", -- Inner Child
    [C_ID .. 689] = "Coroană Glichuită", -- Glitched Crown
    [C_ID .. 690] = "Burtă de Jeleu", -- Belly Jelly
    [C_ID .. 691] = "Glob Sacru", -- Sacred Orb
    [C_ID .. 692] = "Legătură de Sânge", -- Sanguine Bond
    [C_ID .. 693] = "Roiul", -- The Swarm
    [C_ID .. 694] = "Rănit în Dragoste", -- Heartbreak
    [C_ID .. 695] = "Rafală Sângeroasă", -- Bloody Gust
    [C_ID .. 696] = "Mântuire", -- Salvation
    [C_ID .. 697] = "Geamănul Dispărut", -- Vanishing Twin
    [C_ID .. 698] = "Pereche Răsucită", -- Twisted Pair
    [C_ID .. 699] = "Furia lui Azazel", -- Azazel's Rage
    [C_ID .. 700] = "Ecou", -- Echo Chamber
    [C_ID .. 701] = "Sarcofagul lui Isaac", -- Isaac's Tomb
    [C_ID .. 702] = "Spirit Răzbunător", -- Vengeful Spirit
    [C_ID .. 703] = "Esau Jr.", -- Esau Jr.
    [C_ID .. 704] = "Berserk!", -- Berserk!
    [C_ID .. 705] = "Artă Neagră", -- Dark Arts
    [C_ID .. 706] = "Abis", -- Abyss
    [C_ID .. 707] = "Masă de seară", -- Supper
    [C_ID .. 708] = "Capsator", -- Stapler
    [C_ID .. 709] = "Suplex!", -- Suplex!
    [C_ID .. 710] = "Geantă de Meșteșuguri", -- Bag of Crafting
    [C_ID .. 711] = "Flip", -- Flip
    [C_ID .. 712] = "Lemegeton", -- Lemegeton
    [C_ID .. 713] = "Sumptorium", -- Sumptorium
    [C_ID .. 714] = "Chemat", -- Recall
    [C_ID .. 715] = "Ține", -- Hold
    [C_ID .. 716] = "Sacul lui Keeper", -- Keeper's Sack
    [C_ID .. 717] = "Ruda lui Keeper", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "Cutia lui Keeper", -- Keeper's Box
    [C_ID .. 720] = "Borcan cu de Toate", -- Everything Jar
    [C_ID .. 721] = "TMTRAINER", -- TMTRAINER
    [C_ID .. 722] = "Anima Sola", -- Anima Sola
    [C_ID .. 723] = "Zar Coborâtor", -- Spindown Dice
    [C_ID .. 724] = "Hipercoagulare", -- Hypercoagulation
    [C_ID .. 725] = "SII", -- IBS
    [C_ID .. 726] = "Hemoptizie", -- Hemoptysis
    [C_ID .. 727] = "Bombe Fantome", -- Ghost Bombs
    [C_ID .. 728] = "Gello", -- Gello
    [C_ID .. 729] = "Atac Decapitat", -- Decap Attack
    [C_ID .. 730] = "Ochi de Sticlă", -- Glass Eye
    [C_ID .. 731] = "Orjelet ", -- Stye
    [C_ID .. 732] = "Inelul Mamei", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Bănuț Înghițit", -- Swallowed Penny
    [T_ID .. 2] = "Cacat Pietrificat", -- Petrified Poop
    [T_ID .. 3] = "Baterie AAA", -- AAA Battery
    [T_ID .. 4] = "Telecomandă Stricată", -- Broken Remote
    [T_ID .. 5] = "Inimă Violetă", -- Purple Heart
    [T_ID .. 6] = "Magnet Stricat", -- Broken Magnet
    [T_ID .. 7] = "Mărgea Rozariu", -- Rosary Bead
    [T_ID .. 8] = "Cartuș", -- Cartridge
    [T_ID .. 9] = "Vierme Pulsator", -- Pulse Worm
    [T_ID .. 10] = "Vierme Neastâmpărat", -- Wiggle Worm
    [T_ID .. 11] = "Vierme Inel", -- Ring Worm
    [T_ID .. 12] = "Vierme Plat", -- Flat Worm
    [T_ID .. 13] = "Credit de Magazin", -- Store Credit
    [T_ID .. 14] = "Bășică", -- Callus
    [T_ID .. 15] = "Piatră Norocoasă", -- Lucky Rock
    [T_ID .. 16] = "Unghia Mamei", -- Mom's Toenail
    [T_ID .. 17] = "Ruj Negru", -- Black Lipstick
    [T_ID .. 18] = "Tract Biblic", -- Bible Tract
    [T_ID .. 19] = "Agrafă", -- Paper Clip
    [T_ID .. 20] = "Laba Maimuței", -- Monkey Paw
    [T_ID .. 21] = "Hârtie Misterioasă", -- Mysterious Paper
    [T_ID .. 22] = "Coada Demonului", -- Daemon's Tail
    [T_ID .. 23] = "Poster Lipsă", -- Missing Poster
    [T_ID .. 24] = "Bănuț Murdar", -- Butt Penny
    [T_ID .. 25] = "Bomboană Misterioasă", -- Mysterious Candy
    [T_ID .. 26] = "Ancylostoma", -- Hook Worm
    [T_ID .. 27] = "Vierme Bici", -- Whip Worm
    [T_ID .. 28] = "Ankh Stricat", -- Broken Ankh
    [T_ID .. 29] = "Cap de Pește", -- Fish Head
    [T_ID .. 30] = "Ochi Roz", -- Pinky Eye
    [T_ID .. 31] = "Pinișor", -- Push Pin
    [T_ID .. 32] = "Ciupercă Pălarie", -- Liberty Cap
    [T_ID .. 33] = "Cordonul Ombilicald", -- Umbilical Cord
    [T_ID .. 34] = "Inima Copilului", -- Child's Heart
    [T_ID .. 35] = "Corn Curbat", -- Curved Horn
    [T_ID .. 36] = "Cheie Ruginita", -- Rusted Key
    [T_ID .. 37] = "Copita de Capra", -- Goat Hoof
    [T_ID .. 38] = "Perla Mamei", -- Mom's Pearl
    [T_ID .. 39] = "Rac", -- Cancer
    [T_ID .. 40] = "Petic Roșie", -- Red Patch
    [T_ID .. 41] = "Chibrit", -- Match Stick
    [T_ID .. 42] = "Deget Norocos", -- Lucky Toe
    [T_ID .. 43] = "Craniu Blestemat", -- Cursed Skull
    [T_ID .. 44] = "Capac de Siguranță", -- Safety Cap
    [T_ID .. 45] = "As de Pică", -- Ace of Spades
    [T_ID .. 46] = "Furculița lui Isaac", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "O Pagină Lipsă", -- A Missing Page
    [T_ID .. 49] = "Bănuț Însângerat", -- Bloody Penny
    [T_ID .. 50] = "Bănuț Ars", -- Burnt Penny
    [T_ID .. 51] = "Bănuț Plat", -- Flat Penny
    [T_ID .. 52] = "Bănuț Fals", -- Counterfeit Penny
    [T_ID .. 53] = "Căpușă", -- Tick
    [T_ID .. 54] = "Capul lui Isaac", -- Isaac's Head
    [T_ID .. 55] = "Credința lui Maggy", -- Maggy's Faith
    [T_ID .. 56] = "Limba lui Judas", -- Judas' Tongue
    [T_ID .. 57] = "Sufletul lui ???", -- ???'s Soul
    [T_ID .. 58] = "Încuietoarea lui Samson", -- Samson's Lock
    [T_ID .. 59] = "Ochii lui Cain", -- Cain's Eye
    [T_ID .. 60] = "Piciorul de pasăre al Evei", -- Eve's Bird Foot
    [T_ID .. 61] = "Mana Stângă", -- The Left Hand
    [T_ID .. 62] = "Piatră Strălucitoare", -- Shiny Rock
    [T_ID .. 63] = "Foarfece de Siguranță", -- Safety Scissors
    [T_ID .. 64] = "Vierme Curcubeu", -- Rainbow Worm
    [T_ID .. 65] = "Tenie", -- Tape Worm
    [T_ID .. 66] = "Vierme Leneș", -- Lazy Worm
    [T_ID .. 67] = "Zar Spart", -- Cracked Dice
    [T_ID .. 68] = "Magnet Super", -- Super Magnet
    [T_ID .. 69] = "Polaroid Decolorat", -- Faded Polaroid
    [T_ID .. 70] = "Păduche", -- Louse
    [T_ID .. 71] = "Vezica lui Bob", -- Bob's Bladder
    [T_ID .. 72] = "Baterie de Ceas", -- Watch Battery
    [T_ID .. 73] = "Cap de Detonator", -- Blasting Cap
    [T_ID .. 74] = "Detector de Stâlpi", -- Stud Finder
    [T_ID .. 75] = "Eroare", -- Error
    [T_ID .. 76] = "Fise de Poker", -- Poker Chip
    [T_ID .. 77] = "Bășică", -- Blister
    [T_ID .. 78] = "A Doua Mână", -- Second Hand
    [T_ID .. 79] = "Nesfârșit Fără Nume", -- Endless Nameless
    [T_ID .. 80] = "Pană Neagră", -- Black Feather
    [T_ID .. 81] = "Furie Orbitoare", -- Blind Rage
    [T_ID .. 82] = "Potcoavă de Aur", -- Golden Horse Shoe
    [T_ID .. 83] = "Cheia Magazinului", -- Store Key
    [T_ID .. 84] = "Coasta Lăcomiei", -- Rib of Greed
    [T_ID .. 85] = "Karma", -- Karma
    [T_ID .. 86] = "Mica Larvă", -- Lil Larva
    [T_ID .. 87] = "Medalionul Mamei", -- Mom's Locket
    [T_ID .. 88] = "NU!", -- NO!
    [T_ID .. 89] = "Lesă de Copil", -- Child Leash
    [T_ID .. 90] = "Șapcă Maro", -- Brown Cap
    [T_ID .. 91] = "Meconiu", -- Meconium
    [T_ID .. 92] = "Coroană Crăpată", -- Cracked Crown
    [T_ID .. 93] = "Scutec Folosit", -- Used Diaper
    [T_ID .. 94] = "Coada de Pește", -- Fish Tail
    [T_ID .. 95] = "Dinți Negri", -- Black Tooth
    [T_ID .. 96] = "Vierme Ouroboros", -- Ouroboros Worm
    [T_ID .. 97] = "Amigdala", -- Tonsil
    [T_ID .. 98] = "Muci de Goblin", -- Nose Goblin
    [T_ID .. 99] = "Super Minge", -- Super Ball
    [T_ID .. 100] = "Bec Vibrant", -- Vibrant Bulb
    [T_ID .. 101] = "Bec Stins", -- Dim Bulb
    [T_ID .. 102] = "Carte Fragmentată", -- Fragmented Card
    [T_ID .. 103] = "Egalitate!", -- Equality!
    [T_ID .. 104] = "Osul Dorinței", -- Wish Bone
    [T_ID .. 105] = "Pachet de Prânz", -- Bag Lunch
    [T_ID .. 106] = "Dop Pierdut", -- Lost Cork
    [T_ID .. 107] = "Inimă de Cioară", -- Crow Heart
    [T_ID .. 108] = "Nucă", -- Walnut
    [T_ID .. 109] = "Bandă Adezivă", -- Duct Tape
    [T_ID .. 110] = "Dolar de Argint", -- Silver Dollar
    [T_ID .. 111] = "Coroană Însângerată", -- Bloody Crown
    [T_ID .. 112] = "Plătește pentru a Câștiga", -- Pay To Win
    [T_ID .. 113] = "ăcustă a Războiului", -- Locust of War
    [T_ID .. 114] = "ăcustă a Ciumei", -- Locust of Pestilence
    [T_ID .. 115] = "ăcustă a Foametei", -- Locust of Famine
    [T_ID .. 116] = "ăcustă a Morții", -- Locust of Death
    [T_ID .. 117] = "ăcustă a Cuceririi", -- Locust of Conquest
    [T_ID .. 118] = "Aripă de Liliac", -- Bat Wing
    [T_ID .. 119] = "Celule Stem", -- Stem Cell
    [T_ID .. 120] = "Agrafă", -- Hairpin
    [T_ID .. 121] = "Cruce de Lemn", -- Wooden Cross
    [T_ID .. 122] = "Unt!", -- Butter!
    [T_ID .. 123] = "Pana Filigranată", -- Filigree Feather
    [T_ID .. 124] = "Opritor de Ușă", -- Door Stop
    [T_ID .. 125] = "Prelungitor", -- Extension Cord
    [T_ID .. 126] = "Bănuț Putrezit", -- Rotten Penny
    [T_ID .. 127] = "Îndoirea Bebelușului", -- Baby-Bender
    [T_ID .. 128] = "Osul Degetului", -- Finger Bone
    [T_ID .. 129] = "Sfarmă-fălciz", -- Jawbreaker
    [T_ID .. 130] = "Pix Ros", -- Chewed Pen
    [T_ID .. 131] = "Bănuț Binecuvântat", -- Blessed Penny
    [T_ID .. 132] = "Seringă Spartă", -- Broken Syringe
    [T_ID .. 133] = "Fitil Scurt", -- Short Fuse
    [T_ID .. 134] = "Fasole Gigant", -- Gigante Bean
    [T_ID .. 135] = "O Brichetă", -- A Lighter
    [T_ID .. 136] = "Lacăt Spart", -- Broken Padlock
    [T_ID .. 137] = "Nu-mă-uita", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Amuletă Lacrimă", -- Teardrop Charm
    [T_ID .. 140] = "Mărul din Sodom", -- Apple of Sodom
    [T_ID .. 141] = "Lullaby Uitată", -- Forgotten Lullaby
    [T_ID .. 142] = "Credința lui Beth", -- Beth's Faith
    [T_ID .. 143] = "Condensator Vechi", -- Old Capacitor
    [T_ID .. 144] = "Vierme de Creier", -- Brain Worm
    [T_ID .. 145] = "Perfecțiune", -- Perfection
    [T_ID .. 146] = "Coroană a Diavolului", -- Devil's Crown
    [T_ID .. 147] = "Bănuț Încărcat", -- Charged Penny
    [T_ID .. 148] = "Colier al Prieteniei", -- Friendship Necklace
    [T_ID .. 149] = "Buton de Panic", -- Panic Button
    [T_ID .. 150] = "Cheie Albastră", -- Blue Key
    [T_ID .. 151] = "Dosar Plat", -- Flat File
    [T_ID .. 152] = "Lentilă de Telescop", -- Telescope Lens
    [T_ID .. 153] = "Lacătul Mamei", -- Mom's Lock
    [T_ID .. 154] = "Sacul cu Zaruri", -- Dice Bag
    [T_ID .. 155] = "Coroană Sfântă", -- Holy Crown
    [T_ID .. 156] = "Sărutul Mamei", -- Mother's Kiss
    [T_ID .. 157] = "Carte Sfâșiată", -- Torn Card
    [T_ID .. 158] = "Buzunar Sfâșiat", -- Torn Pocket
    [T_ID .. 159] = "Cheie Aurită", -- Gilded Key
    [T_ID .. 160] = "Sacul Norocos", -- Lucky Sack
    [T_ID .. 161] = "Coroană Vicleană", -- Wicked Crown
    [T_ID .. 162] = "Ciotul lui Azazel", -- Azazel's Stump
    [T_ID .. 163] = "Bobiță Dingle", -- Dingle Berry
    [T_ID .. 164] = "Capac de Inel", -- Ring Cap
    [T_ID .. 165] = "Nici Vorbă!", -- Nuh Uh!
    [T_ID .. 166] = "Plastilină", -- Modeling Clay
    [T_ID .. 167] = "Os Lustruit", -- Polished Bone
    [T_ID .. 168] = "Inimă Goală", -- Hollow Heart
    [T_ID .. 169] = "Desenul Copilului", -- Kid's Drawing
    [T_ID .. 170] = "Cheie de Cristal", -- Crystal Key
    [T_ID .. 171] = "Tranzacția Păstrătorului", -- Keeper's Bargain
    [T_ID .. 172] = "Bănuț Blestemat", -- Cursed Penny
    [T_ID .. 173] = "Sufletul Tău", -- Your Soul
    [T_ID .. 174] = "Magnet de Numere", -- Number Magnet
    [T_ID .. 175] = "Cheie Ciudată", -- Strange Key
    [T_ID .. 176] = "Micul Cheag", -- Lil Clot
    [T_ID .. 177] = "Tatuaj Temporar", -- Temporary Tattoo
    [T_ID .. 178] = "M80 Înghițit", -- Swallowed M80
    [T_ID .. 179] = "Telecomandă RC", -- RC Remote
    [T_ID .. 180] = "Suflet găsit", -- Found Soul
    [T_ID .. 181] = "Pachet de expansiune", -- Expansion Pack
    [T_ID .. 182] = "Esența lui Beth", -- Beth's Essence
    [T_ID .. 183] = "Gemenii", -- The Twins
    [T_ID .. 184] = "Acte de adopție", -- Adoption Papers
    [T_ID .. 185] = "Picior de greier", -- Cricket Leg
    [T_ID .. 186] = "Cel mai bun prieten al lui Apollyon", -- Apollyon's Best Friend
    [T_ID .. 187] = "Ochelari sparți", -- Broken Glasses
    [T_ID .. 188] = "Cub de gheață", -- Ice Cube
    [T_ID .. 189] = "Sigiliul lui Baphomet", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Nebunul", -- 0 - The Fool
    [Card_ID .. 2] = "I - Magicianul", -- I - The Magician
    [Card_ID .. 3] = "II - Marea Preoteasă", -- II - The High Priestess
    [Card_ID .. 4] = "III - Împărăteasa", -- III - The Empress
    [Card_ID .. 5] = "IV - Împăratul", -- IV - The Emperor
    [Card_ID .. 6] = "V - Marele Preot", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Îndrăgostiții", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Faetonul", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Dreptate", -- VIII - Justice
    [Card_ID .. 10] = "IX - Eremitul", -- IX - The Hermit
    [Card_ID .. 11] = "X - Roata norocului", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Forța", -- XI - Strength
    [Card_ID .. 13] = "XII - Spânzuratul", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Moartea", -- XIII - Death
    [Card_ID .. 15] = "XIV - Echilibrul", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Diavolul", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Turnul", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Steaua", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Luna", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Soarele", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Judecata", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Lumea", -- XXI - The World
    [Card_ID .. 23] = "2 de Treflă", -- 2 of Clubs
    [Card_ID .. 24] = "2 de Caro", -- 2 of Diamonds
    [Card_ID .. 25] = "2 de Pică", -- 2 of Spades
    [Card_ID .. 26] = "2 de Cupă", -- 2 of Hearts
    [Card_ID .. 27] = "As de Treflă", -- Ace of Clubs
    [Card_ID .. 28] = "As de Caro", -- Ace of Diamonds
    [Card_ID .. 29] = "As de Pică", -- Ace of Spades
    [Card_ID .. 30] = "As de Cupă", -- Ace of Hearts
    [Card_ID .. 31] = "Joker", -- Joker
    [Card_ID .. 32] = "Hagalaz", -- Hagalaz
    [Card_ID .. 33] = "Jera", -- Jera
    [Card_ID .. 34] = "Ehwaz", -- Ehwaz
    [Card_ID .. 35] = "Dagaz", -- Dagaz
    [Card_ID .. 36] = "Ansuz", -- Ansuz
    [Card_ID .. 37] = "Perthro", -- Perthro
    [Card_ID .. 38] = "Berkano", -- Berkano
    [Card_ID .. 39] = "Algiz", -- Algiz
    [Card_ID .. 40] = "Rună goală", -- Blank Rune
    [Card_ID .. 41] = "Rună neagră", -- Black Rune
    [Card_ID .. 42] = "Carte a Haosului", -- Chaos Card
    [Card_ID .. 43] = "Card de credit", -- Credit Card
    [Card_ID .. 44] = "Card cu reguli", -- Rules Card
    [Card_ID .. 45] = "O carte împotriva umanității", -- A Card Against Humanity
    [Card_ID .. 46] = "Regele sinucigaș", -- Suicide King
    [Card_ID .. 47] = "Card de eliberare din închisoare", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "Card ?", -- ? Card
    [Card_ID .. 49] = "Fragment de zar", -- Dice Shard
    [Card_ID .. 50] = "Contact de urgență", -- Emergency Contact
    [Card_ID .. 51] = "Card sfânt", -- Holy Card
    [Card_ID .. 52] = "Creștere uriașă", -- Huge Growth
    [Card_ID .. 53] = "Reamintire antică", -- Ancient Recall
    [Card_ID .. 54] = "Plimbare prin eră", -- Era Walk
    [Card_ID .. 55] = "Fragment de rună", -- Rune Shard
    [Card_ID .. 56] = "0 - Nebunul?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Magicianul?", -- I - The Magician?
    [Card_ID .. 58] = "II - Marea Preoteasă?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - Împărăteasa?", -- III - The Empress?
    [Card_ID .. 60] = "IV - Împăratul?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Marele Preot?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Îndrăgostiții?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Faetonul?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Dreptate?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - Eremitul?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Roata norocului?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Forța?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Spânzuratul?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Moartea?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Echilibrul?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Diavolul?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - Turnul?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Steaua?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - Luna?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Soarele?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Judecata?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Lumea?", -- XXI - The World?
    [Card_ID .. 78] = "Cheie crăpată", -- Cracked Key
    [Card_ID .. 79] = "Regina de Cupă", -- Queen of Hearts
    [Card_ID .. 80] = "Carte sălbatică", -- Wild Card
    [Card_ID .. 81] = "Sufletul lui Isaac", -- Soul of Isaac
    [Card_ID .. 82] = "Sufletul Magdalenei", -- Soul of Magdalene
    [Card_ID .. 83] = "Sufletul lui Cain", -- Soul of Cain
    [Card_ID .. 84] = "Sufletul lui Iuda", -- Soul of Judas
    [Card_ID .. 85] = "Sufletul lui ???", -- Soul of ???
    [Card_ID .. 86] = "Sufletul Evei", -- Soul of Eve
    [Card_ID .. 87] = "Sufletul lui Samson", -- Soul of Samson
    [Card_ID .. 88] = "Sufletul lui Azazel", -- Soul of Azazel
    [Card_ID .. 89] = "Sufletul lui Lazarus", -- Soul of Lazarus
    [Card_ID .. 90] = "Sufletul lui Eden", -- Soul of Eden
    [Card_ID .. 91] = "Sufletul Celui Pierdut", -- Soul of the Lost
    [Card_ID .. 92] = "Sufletul lui Lilith", -- Soul of Lilith
    [Card_ID .. 93] = "Sufletul Păzitorului", -- Soul of the Keeper
    [Card_ID .. 94] = "Sufletul lui Apollyon", -- Soul of Apollyon
    [Card_ID .. 95] = "Sufletul Celui Uitat", -- Soul of the Forgotten
    [Card_ID .. 96] = "Sufletul lui Bethany", -- Soul of Bethany
    [Card_ID .. 97] = "Sufletul lui Iacob și Esau", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 0] = "Gaz rău", -- Bad Gas
    [Pill_ID .. 1] = "Călătorie rea", -- Bad Trip
    [Pill_ID .. 2] = "Bile de oțel", -- Balls of Steel
    [Pill_ID .. 3] = "Bombele sunt chei", -- Bombs are Key
    [Pill_ID .. 4] = "Diaree explozivă", -- Explosive Diarrhea
    [Pill_ID .. 5] = "Sănătate completă", -- Full Health
    [Pill_ID .. 6] = "Sănătate scăzută", -- Health Down
    [Pill_ID .. 7] = "Sănătate crescută", -- Health Up
    [Pill_ID .. 8] = "Am găsit pastile", -- I Found Pills
    [Pill_ID .. 9]  = "Pubertate", -- Puberty
    [Pill_ID .. 10] = "Muscă drăguță", -- Pretty Fly
    [Pill_ID .. 11] = "Rază scăzută", -- Range Down
    [Pill_ID .. 12] = "Rază crescută", -- Range Up
    [Pill_ID .. 13] = "Viteză scăzută", -- Speed Down
    [Pill_ID .. 14] = "Viteză crescută", -- Speed Up
    [Pill_ID .. 15] = "Viteză de atac scăzută", -- Tears Down
    [Pill_ID .. 16] = "Viteză de atac crescută", -- Tears Up
    [Pill_ID .. 17] = "Noroc scăzut", -- Luck Down
    [Pill_ID .. 18] = "Noroc crescut", -- Luck Up
    [Pill_ID .. 19] = "Telepastile", -- Telepills
    [Pill_ID .. 20] = "Energie 48 de ore!", -- 48 Hour Energy!
    [Pill_ID .. 21] = "Hematemeză", -- Hematemesis
    [Pill_ID .. 22] = "Paralizie", -- Paralysis
    [Pill_ID .. 23] = "Pot vedea pentru totdeauna!", -- I can see forever!
    [Pill_ID .. 24] = "Feromoni", -- Pheromones
    [Pill_ID .. 25] = "Amnezie", -- Amnesia
    [Pill_ID .. 26] = "Petrecere cu lămâi", -- Lemon Party
    [Pill_ID .. 27] = "Ești un vrăjitor?", -- R U A Wizard?
    [Pill_ID .. 28] = "Percs!", -- Percs!
    [Pill_ID .. 29] = "Dependent!", -- Addicted!
    [Pill_ID .. 30] = "Re-Lax", -- Re-Lax
    [Pill_ID .. 31] = "???", -- ???
    [Pill_ID .. 32] = "Una te face mai mare", -- One makes you larger
    [Pill_ID .. 33] = "Una te face mic", -- One makes you small
    [Pill_ID .. 34] = "Infestat!", -- Infested!
    [Pill_ID .. 35] = "Infestat?", -- Infested?
    [Pill_ID .. 36] = "Pastilă de putere!", -- Power Pill!
    [Pill_ID .. 37] = "Viziune retro", -- Retro Vision
    [Pill_ID .. 38] = "Prieteni până la sfârșit!", -- Friends Till The End!
    [Pill_ID .. 39] = "X-Lax", -- X-Lax
    [Pill_ID .. 40] = "Ceva nu e în regulă...", -- Something's wrong...
    [Pill_ID .. 41] = "Sunt amețit...", -- I'm Drowsy...
    [Pill_ID .. 42] = "Sunt entuziasmat!!", -- I'm Excited!!
    [Pill_ID .. 43] = "Înghite!", -- Gulp!
    [Pill_ID .. 44] = "Horf!", -- Horf!
    [Pill_ID .. 45] = "Parcă merg pe raze de soare!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 46] = "Vurp!", -- Vurp!
    [Pill_ID .. 47] = "Viteza atacurilor scăzută", -- Shot speed Down
    [Pill_ID .. 48] = "Viteza atacurilor crescută", -- Shot speed Up
    [Pill_ID .. 49] = "Pastilă experimentală", -- Experimental Pill
    [Pill_ID .. 9999] = "Pastilă de Aur", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])
