-- This file contains translateable names for all collectibles, trinkets, cards and pills in the game.
-- If an entry is missing or empty, the English name will be used instead.

local languageCode = "ru"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Грустный лук", -- The Sad Onion
    [C_ID .. 2] = "Внутренний глаз", -- The Inner Eye
    [C_ID .. 3] = "Сгибатель ложек", -- Spoon Bender
    [C_ID .. 4] = "Голова Крикета", -- Cricket's Head
    [C_ID .. 5] = "Моё отражение", -- My Reflection
    [C_ID .. 6] = "Номер один", -- Number One
    [C_ID .. 7] = "Кровь мученика", -- Blood of the Martyr
    [C_ID .. 8] = "Братик Бобби", -- Brother Bobby
    [C_ID .. 9] = "Скатол", -- Skatole
    [C_ID .. 10] = "Нимб из мух", -- Halo of Flies
    [C_ID .. 11] = "1UP", -- 1up!
    [C_ID .. 12] = "Волшебный гриб", -- Magic Mushroom
    [C_ID .. 13] = "Вирус", -- The Virus
    [C_ID .. 14] = "Стероидная ярость", -- Roid Rage
    [C_ID .. 15] = "Меньше трёх", -- <3
    [C_ID .. 16] = "Сырая печень", -- Raw Liver
    [C_ID .. 17] = "Скелетный ключ", -- Skeleton Key
    [C_ID .. 18] = "Доллар", -- A Dollar
    [C_ID .. 19] = "Бум!", -- Boom!
    [C_ID .. 20] = "Трансцендентность", -- Transcendence
    [C_ID .. 21] = "Компас", -- The Compass
    [C_ID .. 22] = "Полдник", -- Lunch
    [C_ID .. 23] = "Обед", -- Dinner
    [C_ID .. 24] = "Десерт", -- Dessert
    [C_ID .. 25] = "Завтрак", -- Breakfast
    [C_ID .. 26] = "Гнилое мясо", -- Rotten Meat
    [C_ID .. 27] = "Деревянная ложка", -- Wooden Spoon
    [C_ID .. 28] = "Ремень", -- The Belt
    [C_ID .. 29] = "Мамино бельё", -- Mom's Underwear
    [C_ID .. 30] = "Мамины туфли", -- Mom's Heels
    [C_ID .. 31] = "Мамина губная помада", -- Mom's Lipstick
    [C_ID .. 32] = "Проволочная вешалка", -- Wire Coat Hanger
    [C_ID .. 33] = "Библия", -- The Bible
    [C_ID .. 34] = "Книга Белиала", -- The Book of Belial
    [C_ID .. 35] = "Некрономикон", -- The Necronomicon
    [C_ID .. 36] = "Какашка", -- The Poop
    [C_ID .. 37] = "Мистер Бум", -- Mr. Boom
    [C_ID .. 38] = "Голова Тамми", -- Tammy's Head
    [C_ID .. 39] = "Мамин лифчик", -- Mom's Bra
    [C_ID .. 40] = "Камикадзе!", -- Kamikaze!
    [C_ID .. 41] = "Мамина прокладка", -- Mom's Pad
    [C_ID .. 42] = "Гнилая голова Боба", -- Bob's Rotten Head
    [C_ID .. 43] = "ID в игре не задействован", -- 
    [C_ID .. 44] = "Телепорт", -- Teleport!
    [C_ID .. 45] = "Ням сердце", -- Yum Heart
    [C_ID .. 46] = "Счастливая нога", -- Lucky Foot
    [C_ID .. 47] = "ПДУ Доктора", -- Doctor's Remote
    [C_ID .. 48] = "Стрела Купидона", -- Cupid's Arrow
    [C_ID .. 49] = "Шуп Да Вуп!", -- Shoop da Whoop!
    [C_ID .. 50] = "Стивен", -- Steven
    [C_ID .. 51] = "Пентаграмма", -- Pentagram
    [C_ID .. 52] = "Доктор Зародыш", -- Dr. Fetus
    [C_ID .. 53] = "Магнето", -- Magneto
    [C_ID .. 54] = "Карта сокровищ", -- Treasure Map
    [C_ID .. 55] = "Мамин глаз", -- Mom's Eye
    [C_ID .. 56] = "Лимонная авария", -- Lemon Mishap
    [C_ID .. 57] = "Сдержанное восхищение", -- Distant Admiration
    [C_ID .. 58] = "Книга Теней", -- Book of Shadows
    [C_ID .. 59] = "Книга Белиала", -- The Book of Belial
    [C_ID .. 60] = "Лесенка", -- The Ladder
    [C_ID .. 61] = "ID в игре не задействован", -- 
    [C_ID .. 62] = "Очарование вампира", -- Charm of the Vampire
    [C_ID .. 63] = "Батарейка", -- The Battery
    [C_ID .. 64] = "Распродажа в Стиме", -- Steam Sale
    [C_ID .. 65] = "Поваренная книга анархиста", -- Anarchist Cookbook
    [C_ID .. 66] = "Песочные часы", -- The Hourglass
    [C_ID .. 67] = "Сестра Мэгги", -- Sister Maggy
    [C_ID .. 68] = "Технология", -- Technology
    [C_ID .. 69] = "Шоколадное молоко", -- Chocolate Milk
    [C_ID .. 70] = "Гормоны роста", -- Growth Hormones
    [C_ID .. 71] = "Мини гриб", -- Mini Mush
    [C_ID .. 72] = "Чётки", -- Rosary
    [C_ID .. 73] = "Кубик мяса", -- Cube of Meat
    [C_ID .. 74] = "Четвертак", -- A Quarter
    [C_ID .. 75] = "Докторская степень", -- PHD
    [C_ID .. 76] = "Рентгеновское зрение", -- X-Ray Vision
    [C_ID .. 77] = "Мой маленький единорог", -- My Little Unicorn
    [C_ID .. 78] = "Книга Откровений", -- Book of Revelations
    [C_ID .. 79] = "Метка", -- The Mark
    [C_ID .. 80] = "Договор", -- The Pact
    [C_ID .. 81] = "Мёртвый кот", -- Dead Cat
    [C_ID .. 82] = "Повелитель ямы", -- Lord of the Pit
    [C_ID .. 83] = "Гвоздь", -- The Nail
    [C_ID .. 84] = "Нам нужно глубже!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Колода карт", -- Deck of Cards
    [C_ID .. 86] = "Зуб Монстро", -- Monstro's Tooth
    [C_ID .. 87] = "Рога Локи", -- Loki's Horns
    [C_ID .. 88] = "Маленький Чабби", -- Little Chubby
    [C_ID .. 89] = "Укус паука", -- Spider Bite
    [C_ID .. 90] = "Маленький камень", -- The Small Rock
    [C_ID .. 91] = "Каска спелеолога", -- Spelunker Hat
    [C_ID .. 92] = "Суперпластырь", -- Super Bandage
    [C_ID .. 93] = "Геймкид", -- The Gamekid
    [C_ID .. 94] = "Мешочек с монетами", -- Sack of Pennies
    [C_ID .. 95] = "Робо-малыш", -- Robo-Baby
    [C_ID .. 96] = "Маленький Чад", -- Little C.H.A.D.
    [C_ID .. 97] = "Книга Греха", -- The Book of Sin
    [C_ID .. 98] = "Реликвия", -- The Relic
    [C_ID .. 99] = "Маленький Гиш", -- Little Gish
    [C_ID .. 100] = "Маленький Стивен", -- Little Steven
    [C_ID .. 101] = "Нимб", -- The Halo
    [C_ID .. 102] = "Мамин пузырёк с пилюлями", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Простуда", -- The Common Cold
    [C_ID .. 104] = "Паразит", -- The Parasite
    [C_ID .. 105] = "D6", -- The D6
    [C_ID .. 106] = "Мистер Мега", -- Mr. Mega
    [C_ID .. 107] = "Фестонные ножницы", -- The Pinking Shears
    [C_ID .. 108] = "Облатка", -- The Wafer
    [C_ID .. 109] = "Деньги равно Сила", -- Money = Power
    [C_ID .. 110] = "Мамины линзы", -- Mom's Contacts
    [C_ID .. 111] = "Боб", -- The Bean
    [C_ID .. 112] = "Ангел-хранитель", -- Guardian Angel
    [C_ID .. 113] = "Малыш демон", -- Demon Baby
    [C_ID .. 114] = "Мамин нож", -- Mom's Knife
    [C_ID .. 115] = "Доска Уиджа", -- Ouija Board
    [C_ID .. 116] = "9 вольт", -- 9 Volt
    [C_ID .. 117] = "Мёртвая птичка", -- Dead Bird
    [C_ID .. 118] = "Сера", -- Brimstone
    [C_ID .. 119] = "Пакет с кровью", -- Blood Bag
    [C_ID .. 120] = "Странный гриб", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Странный гриб (большой)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Вавилонская блудница", -- Whore of Babylon
    [C_ID .. 123] = "Руководство по монстрам", -- Monster Manual
    [C_ID .. 124] = "Свитки Мёртвого моря", -- Dead Sea Scrolls
    [C_ID .. 125] = "Бобби-Бомба", -- Bobby-Bomb
    [C_ID .. 126] = "Лезвие бритвы", -- Razor Blade
    [C_ID .. 127] = "Забудь меня", -- Forget Me Now
    [C_ID .. 128] = "Один навсегда", -- Forever Alone
    [C_ID .. 129] = "Ведро сала", -- Bucket of Lard
    [C_ID .. 130] = "Пони", -- A Pony
    [C_ID .. 131] = "Мешочек с бомбами", -- Bomb Bag
    [C_ID .. 132] = "Кусок угля", -- A Lump of Coal
    [C_ID .. 133] = "Лапка Гаппи", -- Guppy's Paw
    [C_ID .. 134] = "Хвост Гаппи", -- Guppy's Tail
    [C_ID .. 135] = "Капельница", -- IV Bag
    [C_ID .. 136] = "Лучший друг", -- Best Friend
    [C_ID .. 137] = "Дистанционный детонатор", -- Remote Detonator
    [C_ID .. 138] = "Стигмата", -- Stigmata
    [C_ID .. 139] = "Мамина сумочка", -- Mom's Purse
    [C_ID .. 140] = "Проклятье Боба", -- Bob's Curse
    [C_ID .. 141] = "Эффектный мальчик", -- Pageant Boy
    [C_ID .. 142] = "Скапулярий", -- Scapular
    [C_ID .. 143] = "Спидбол", -- Speed Ball
    [C_ID .. 144] = "Друг-бездельник", -- Bum Friend
    [C_ID .. 145] = "Голова Гаппи", -- Guppy's Head
    [C_ID .. 146] = "Молитвенная карточка", -- Prayer Card
    [C_ID .. 147] = "Кирка Нотча", -- Notched Axe
    [C_ID .. 148] = "Заражение", -- Infestation
    [C_ID .. 149] = "Рвотный корень", -- Ipecac
    [C_ID .. 150] = "Жёсткая любовь", -- Tough Love
    [C_ID .. 151] = "Плакса", -- The Mulligan
    [C_ID .. 152] = "Технология 2", -- Technology 2
    [C_ID .. 153] = "Паук-мутант", -- Mutant Spider
    [C_ID .. 154] = "Химический ожог", -- Chemical Peel
    [C_ID .. 155] = "Моргало", -- The Peeper
    [C_ID .. 156] = "Одеяние", -- Habit
    [C_ID .. 157] = "Жажда крови", -- Bloody Lust
    [C_ID .. 158] = "Хрустальный шар", -- Crystal Ball
    [C_ID .. 159] = "Дух ночи", -- Spirit of the Night
    [C_ID .. 160] = "Разверзшиеся небеса", -- Crack the Sky
    [C_ID .. 161] = "Анх", -- Ankh
    [C_ID .. 162] = "Кельтский крест", -- Celtic Cross
    [C_ID .. 163] = "Малыш призрак", -- Ghost Baby
    [C_ID .. 164] = "Свеча", -- The Candle
    [C_ID .. 165] = "Девятихвостая плеть", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Малыш арлекин", -- Harlequin Baby
    [C_ID .. 168] = "Эпичный Зародыш", -- Epic Fetus
    [C_ID .. 169] = "Полифем", -- Polyphemus
    [C_ID .. 170] = "Папочка Длинные Ноги", -- Daddy Longlegs
    [C_ID .. 171] = "Паучья задница", -- Spider Butt
    [C_ID .. 172] = "Жертвенный кинжал", -- Sacrificial Dagger
    [C_ID .. 173] = "Митра", -- Mitre
    [C_ID .. 174] = "Радужный малыш", -- Rainbow Baby
    [C_ID .. 175] = "Папин ключ", -- Dad's Key
    [C_ID .. 176] = "Стволовые клетки", -- Stem Cells
    [C_ID .. 177] = "Переносной автомат", -- Portable Slot
    [C_ID .. 178] = "Святая вода", -- Holy Water
    [C_ID .. 179] = "Судьба", -- Fate
    [C_ID .. 180] = "Чёрный боб", -- The Black Bean
    [C_ID .. 181] = "Белый пони", -- White Pony
    [C_ID .. 182] = "Священное сердце", -- Sacred Heart
    [C_ID .. 183] = "Зубочистки", -- Tooth Picks
    [C_ID .. 184] = "Святой Грааль", -- Holy Grail
    [C_ID .. 185] = "Мёртвая голубка", -- Dead Dove
    [C_ID .. 186] = "Право на кровь", -- Blood Rights
    [C_ID .. 187] = "Комок шерсти Гаппи", -- Guppy's Hairball
    [C_ID .. 188] = "Авель", -- Abel
    [C_ID .. 189] = "Супер фанат SMB", -- SMB Super Fan
    [C_ID .. 190] = "Пиро", -- Pyro
    [C_ID .. 191] = "Трёхдолларовая банкнота", -- 3 Dollar Bill
    [C_ID .. 192] = "Телепатия для чайников", -- Telepathy for Dummies
    [C_ID .. 193] = "МЯСО!", -- MEAT!
    [C_ID .. 194] = "Магический Шар 8", -- Magic 8 Ball
    [C_ID .. 195] = "Мамин кошелёк", -- Mom's Coin Purse
    [C_ID .. 196] = "Давление", -- Squeezy
    [C_ID .. 197] = "Сок Иисуса", -- Jesus Juice
    [C_ID .. 198] = "Коробка", -- Box
    [C_ID .. 199] = "Мамин ключ", -- Mom's Key
    [C_ID .. 200] = "Мамины тени", -- Mom's Eyeshadow
    [C_ID .. 201] = "Железный слиток", -- Iron Bar
    [C_ID .. 202] = "Прикосновение Мидаса", -- Midas' Touch
    [C_ID .. 203] = "Скромный набор", -- Humbleing Bundle
    [C_ID .. 204] = "Сумка на ремне", -- Fanny Pack
    [C_ID .. 205] = "Острый штепсель", -- Sharp Plug
    [C_ID .. 206] = "Гильотина", -- Guillotine
    [C_ID .. 207] = "Шар из пластырей", -- Ball of Bandages
    [C_ID .. 208] = "Пояс чемпиона", -- Champion Belt
    [C_ID .. 209] = "Бомбы из задницы", -- Butt Bombs
    [C_ID .. 210] = "Обглоданный лист", -- Gnawed Leaf
    [C_ID .. 211] = "Паук малыш", -- Spiderbaby
    [C_ID .. 212] = "Ошейник Гаппи", -- Guppy's Collar
    [C_ID .. 213] = "Потерянная линза", -- Lost Contact
    [C_ID .. 214] = "Анемия", -- Anemic
    [C_ID .. 215] = "Козья голова", -- Goat Head
    [C_ID .. 216] = "Церемониальная мантия", -- Ceremonial Robes
    [C_ID .. 217] = "Мамин парик", -- Mom's Wig
    [C_ID .. 218] = "Плацента", -- Placenta
    [C_ID .. 219] = "Старый пластырь", -- Old Bandage
    [C_ID .. 220] = "Грустные бомбы", -- Sad Bombs
    [C_ID .. 221] = "Резиновый клей", -- Rubber Cement
    [C_ID .. 222] = "Анти-гравитация", -- Anti-Gravity
    [C_ID .. 223] = "Пироманьяк", -- Pyromaniac
    [C_ID .. 224] = "Тело Крикета", -- Cricket's Body
    [C_ID .. 225] = "Убогий", -- Gimpy
    [C_ID .. 226] = "Чёрный лотос", -- Black Lotus
    [C_ID .. 227] = "Свинка копилка", -- Piggy Bank
    [C_ID .. 228] = "Мамины духи", -- Mom's Perfume
    [C_ID .. 229] = "Лёгкое Монстро", -- Monstro's Lung
    [C_ID .. 230] = "Абаддон", -- Abaddon
    [C_ID .. 231] = "Шар смолы", -- Ball of Tar
    [C_ID .. 232] = "Секундомер", -- Stop Watch
    [C_ID .. 233] = "Крошечная планета", -- Tiny Planet
    [C_ID .. 234] = "Заражение 2", -- Infestation 2
    [C_ID .. 235] = "ID в игре не задействован", -- 
    [C_ID .. 236] = "Кишечная палочка", -- E. Coli
    [C_ID .. 237] = "Прикосновение Смерти", -- Death's Touch
    [C_ID .. 238] = "Первая часть Ключа", -- Key Piece 1
    [C_ID .. 239] = "Вторая часть Ключа", -- Key Piece 2
    [C_ID .. 240] = "Экспериментальное лечение", -- Experimental Treatment
    [C_ID .. 241] = "Договор с Преисподней", -- Contract from Below
    [C_ID .. 242] = "Позор", -- Infamy
    [C_ID .. 243] = "Триединый щит", -- Trinity Shield
    [C_ID .. 244] = "Технология.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Голубая карта", -- Blue Map
    [C_ID .. 247] = "Лучшие друзья навсегда!", -- BFFS!
    [C_ID .. 248] = "Разум улья", -- Hive Mind
    [C_ID .. 249] = "Выбор есть", -- There's Options
    [C_ID .. 250] = "Парные бомбы", -- Bogo Bombs
    [C_ID .. 251] = "Базовая колода", -- Starter Deck
    [C_ID .. 252] = "Маленький мешочек", -- Little Baggy
    [C_ID .. 253] = "Волшебная корка", -- Magic Scab
    [C_ID .. 254] = "Сгусток крови", -- Blood Clot
    [C_ID .. 255] = "Шуруп", -- Screw
    [C_ID .. 256] = "Горячие бомбы", -- Hot Bombs
    [C_ID .. 257] = "Огненный разум", -- Fire Mind
    [C_ID .. 258] = "Потерянный №", -- Missing No.
    [C_ID .. 259] = "Тёмная материя", -- Dark Matter
    [C_ID .. 260] = "Чёрная свеча", -- Black Candle
    [C_ID .. 261] = "Проптоз", -- Proptosis
    [C_ID .. 262] = "Потерянная страница 2", -- Missing Page 2
    [C_ID .. 263] = "Чистая руна", -- Clear Rune
    [C_ID .. 264] = "Умная муха", -- Smart Fly
    [C_ID .. 265] = "Высушенный ребёнок", -- Dry Baby
    [C_ID .. 266] = "Сочащийся кокон", -- Juicy Sack
    [C_ID .. 267] = "Робо-малыш 2.0 ", -- Robo-Baby 2.0
    [C_ID .. 268] = "Гнилой малыш", -- Rotten Baby
    [C_ID .. 269] = "Безголовый малыш", -- Headless Baby
    [C_ID .. 270] = "Пиявка", -- Leech
    [C_ID .. 271] = "Загадочный мешочек", -- Mystery Sack
    [C_ID .. 272] = "Большая красивая муха", -- BBF
    [C_ID .. 273] = "Мозг Боба", -- Bob's Brain
    [C_ID .. 274] = "Лучший приятель", -- Best Bud
    [C_ID .. 275] = "Малютка сера", -- Lil Brimstone
    [C_ID .. 276] = "Сердце Исаака", -- Isaac's Heart
    [C_ID .. 277] = "Маленький призрак", -- Lil Haunt
    [C_ID .. 278] = "Тёмный бездельник", -- Dark Bum
    [C_ID .. 279] = "Большой фанат", -- Big Fan
    [C_ID .. 280] = "Сисси Длинные Ноги", -- Sissy Longlegs
    [C_ID .. 281] = "Боксерская груша", -- Punching Bag
    [C_ID .. 282] = "Руководство по прыжкам", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Пустая карта", -- Blank Card
    [C_ID .. 287] = "Книга тайн", -- Book of Secrets
    [C_ID .. 288] = "Коробка с пауками", -- Box of Spiders
    [C_ID .. 289] = "Красная свеча", -- Red Candle
    [C_ID .. 290] = "Банка", -- The Jar
    [C_ID .. 291] = "Слив!", -- Flush!
    [C_ID .. 292] = "Сатанинская Библия", -- Satanic Bible
    [C_ID .. 293] = "Голова Крампуса", -- Head of Krampus
    [C_ID .. 294] = "Масленый боб", -- Butter Bean
    [C_ID .. 295] = "Магические пальцы", -- Magic Fingers
    [C_ID .. 296] = "Преобразователь", -- Converter
    [C_ID .. 297] = "Ящик Пандоры", -- Pandora's Box
    [C_ID .. 298] = "Копыто единорога", -- Unicorn Stump
    [C_ID .. 299] = "Телец", -- Taurus
    [C_ID .. 300] = "Овен", -- Aries
    [C_ID .. 301] = "Рак", -- Cancer
    [C_ID .. 302] = "Лев", -- Leo
    [C_ID .. 303] = "Дева", -- Virgo
    [C_ID .. 304] = "Весы", -- Libra
    [C_ID .. 305] = "Скорпион", -- Scorpio
    [C_ID .. 306] = "Стрелец", -- Sagittarius
    [C_ID .. 307] = "Козерог", -- Capricorn
    [C_ID .. 308] = "Водолей", -- Aquarius
    [C_ID .. 309] = "Рыбы", -- Pisces
    [C_ID .. 310] = "Тушь Евы", -- Eve's Mascara
    [C_ID .. 311] = "Тень Иуды", -- Judas' Shadow
    [C_ID .. 312] = "Бант Мэгги", -- Maggy's Bow
    [C_ID .. 313] = "Святая мантия", -- Holy Mantle
    [C_ID .. 314] = "Громовые бёдра", -- Thunder Thighs
    [C_ID .. 315] = "Странное влечение", -- Strange Attractor
    [C_ID .. 316] = "Проклятый глаз", -- Cursed Eye
    [C_ID .. 317] = "Загадочная жидкость", -- Mysterious Liquid
    [C_ID .. 318] = "Близнецы", -- Gemini
    [C_ID .. 319] = "Другой глаз Каина", -- Cain's Other Eye
    [C_ID .. 320] = "Единственный друг ???", -- ???'s Only Friend
    [C_ID .. 321] = "Цепи Самсона", -- Samson's Chains
    [C_ID .. 322] = "Малыш монго", -- Mongo Baby
    [C_ID .. 323] = "Слезы Исаака", -- Isaac's Tears
    [C_ID .. 324] = "Неопределённый", -- Undefined
    [C_ID .. 325] = "Ножницы", -- Scissors
    [C_ID .. 326] = "Дыхание жизни", -- Breath of Life
    [C_ID .. 327] = "Фотокарточка", -- The Polaroid
    [C_ID .. 328] = "Негатив", -- The Negative
    [C_ID .. 329] = "Техника Людовика", -- The Ludovico Technique
    [C_ID .. 330] = "Соевое молоко", -- Soy Milk
    [C_ID .. 331] = "Божественность", -- Godhead
    [C_ID .. 332] = "Лохмотья Лазаря", -- Lazarus' Rags
    [C_ID .. 333] = "Разум", -- The Mind
    [C_ID .. 334] = "Тело", -- The Body
    [C_ID .. 335] = "Душа", -- The Soul
    [C_ID .. 336] = "Мертвый лук", -- Dead Onion
    [C_ID .. 337] = "Сломанные часы", -- Broken Watch
    [C_ID .. 338] = "Бумеранг", -- The Boomerang
    [C_ID .. 339] = "Безопасная булавка", -- Safety Pin
    [C_ID .. 340] = "Кофеиновая пилюля", -- Caffeine Pill
    [C_ID .. 341] = "Порванная фотография", -- Torn Photo
    [C_ID .. 342] = "Голубая шляпка", -- Blue Cap
    [C_ID .. 343] = "Отмычка", -- Latch Key
    [C_ID .. 344] = "Коробок спичек", -- Match Book
    [C_ID .. 345] = "Синтол", -- Synthoil
    [C_ID .. 346] = "Закуска", -- A Snack
    [C_ID .. 347] = "Диплопия", -- Diplopia
    [C_ID .. 348] = "Плацебо", -- Placebo
    [C_ID .. 349] = "Деревянный пятак", -- Wooden Nickel
    [C_ID .. 350] = "Токсический шок", -- Toxic Shock
    [C_ID .. 351] = "Мега боб", -- Mega Bean
    [C_ID .. 352] = "Стеклянная пушка", -- Glass Cannon
    [C_ID .. 353] = "Бомбербой", -- Bomber Boy
    [C_ID .. 354] = "Хрустящий Джек", -- Crack Jacks
    [C_ID .. 355] = "Мамин жемчуг", -- Mom's Pearls
    [C_ID .. 356] = "Аккумулятор", -- Car Battery
    [C_ID .. 357] = "Коробка с друзьями", -- Box of Friends
    [C_ID .. 358] = "Колдун", -- The Wiz
    [C_ID .. 359] = "Восьмидюймовые гвозди", -- 8 Inch Nails
    [C_ID .. 360] = "Инкуб", -- Incubus
    [C_ID .. 361] = "Дар судьбы", -- Fate's Reward
    [C_ID .. 362] = "Маленький сундучок", -- Lil Chest
    [C_ID .. 363] = "Присягнувший защитник", -- Sworn Protector
    [C_ID .. 364] = "Френдзона", -- Friend Zone
    [C_ID .. 365] = "Потерянная муха", -- Lost Fly
    [C_ID .. 366] = "Разбросанные бомбы", -- Scatter Bombs
    [C_ID .. 367] = "Липкие бомбы", -- Sticky Bombs
    [C_ID .. 368] = "Эпифора", -- Epiphora
    [C_ID .. 369] = "Континуум", -- Continuum
    [C_ID .. 370] = "Мистер Куколка", -- Mr. Dolly
    [C_ID .. 371] = "Проклятие башни", -- Curse of the Tower
    [C_ID .. 372] = "Заряженный малыш", -- Charged Baby
    [C_ID .. 373] = "Мёртвый глаз", -- Dead Eye
    [C_ID .. 374] = "Божественный свет", -- Holy Light
    [C_ID .. 375] = "Шляпа Наблюдателя", -- Host Hat
    [C_ID .. 376] = "Пополнение", -- Restock
    [C_ID .. 377] = "Разорванный кокон", -- Bursting Sack
    [C_ID .. 378] = "Номер 2", -- No. 2
    [C_ID .. 379] = "Двойной взгляд", -- Pupula Duplex
    [C_ID .. 380] = "Плати и играй", -- Pay To Play
    [C_ID .. 381] = "Благословение Эдема", -- Eden's Blessing
    [C_ID .. 382] = "Дружелюбный шар", -- Friendly Ball
    [C_ID .. 383] = "Слезный детонатор", -- Tear Detonator
    [C_ID .. 384] = "Малютка Гёрди", -- Lil Gurdy
    [C_ID .. 385] = "Бамбо", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Кадило", -- Censer
    [C_ID .. 388] = "Ключник-бездельник", -- Key Bum
    [C_ID .. 389] = "Мешочек с рунами", -- Rune Bag
    [C_ID .. 390] = "Серафим", -- Seraphim
    [C_ID .. 391] = "Предательство", -- Betrayal
    [C_ID .. 392] = "Зодиак", -- Zodiac
    [C_ID .. 393] = "Змеиный поцелуй", -- Serpent's Kiss
    [C_ID .. 394] = "Отмеченный", -- Marked
    [C_ID .. 395] = "Технология X", -- Tech X
    [C_ID .. 396] = "Желудочная бритва", -- Ventricle Razor
    [C_ID .. 397] = "Тяговый луч", -- Tractor Beam
    [C_ID .. 398] = "Плоть Бога", -- God's Flesh
    [C_ID .. 399] = "Пасть бездны", -- Maw of the Void
    [C_ID .. 400] = "Копье Судьбы", -- Spear of Destiny
    [C_ID .. 401] = "Взрывчатко", -- Explosivo
    [C_ID .. 402] = "Хаос", -- Chaos
    [C_ID .. 403] = "Паучья модификация", -- Spider Mod
    [C_ID .. 404] = "Пукающий малыш", -- Farting Baby
    [C_ID .. 405] = "Игровой баг", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Чистота", -- Purity
    [C_ID .. 408] = "Атаме", -- Athame
    [C_ID .. 409] = "Пустой сосуд", -- Empty Vessel
    [C_ID .. 410] = "Злой глаз", -- Evil Eye
    [C_ID .. 411] = "Вожделенная кровь", -- Lusty Blood
    [C_ID .. 412] = "Зачатие Камбиона", -- Cambion Conception
    [C_ID .. 413] = "Непорочное зачатие", -- Immaculate Conception
    [C_ID .. 414] = "Больше вариантов", -- More Options
    [C_ID .. 415] = "Корона света", -- Crown Of Light
    [C_ID .. 416] = "Глубокие карманы", -- Deep Pockets
    [C_ID .. 417] = "Суккуб", -- Succubus
    [C_ID .. 418] = "Фруктовый пирог", -- Fruit Cake
    [C_ID .. 419] = "Телепорт 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Чёрный порошок", -- Black Powder
    [C_ID .. 421] = "Почечный боб", -- Kidney Bean
    [C_ID .. 422] = "Светящиеся песочные часы", -- Glowing Hourglass
    [C_ID .. 423] = "Круг защиты", -- Circle of Protection
    [C_ID .. 424] = "Пакет на голову", -- Sack Head
    [C_ID .. 425] = "Ночник", -- Night Light
    [C_ID .. 426] = "Одержимый фанат", -- Obsessed Fan
    [C_ID .. 427] = "Шахтёр", -- Mine Crafter
    [C_ID .. 428] = "Пижама", -- PJs
    [C_ID .. 429] = "Голова Хранителя", -- Head of the Keeper
    [C_ID .. 430] = "Папа-мух", -- Papa Fly
    [C_ID .. 431] = "Многомерный малыш", -- Multidimensional Baby
    [C_ID .. 432] = "Блестящие бомбы", -- Glitter Bombs
    [C_ID .. 433] = "Моя тень", -- My Shadow
    [C_ID .. 434] = "Банка с мухами", -- Jar of Flies
    [C_ID .. 435] = "Малыш Локи", -- Lil Loki
    [C_ID .. 436] = "Молоко!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Соска-пустышка", -- Binky
    [C_ID .. 439] = "Мамина коробка", -- Mom's Box
    [C_ID .. 440] = "Почечный камень", -- Kidney Stone
    [C_ID .. 441] = "Мега заряд", -- Mega Blast
    [C_ID .. 442] = "Корона тёмного принца", -- Dark Prince's Crown
    [C_ID .. 443] = "Яблоко!", -- Apple!
    [C_ID .. 444] = "Графитовый карандаш", -- Lead Pencil
    [C_ID .. 445] = "Собачий зуб", -- Dog Tooth
    [C_ID .. 446] = "Мёртвый зуб", -- Dead Tooth
    [C_ID .. 447] = "Тормозной боб", -- Linger Bean
    [C_ID .. 448] = "Осколок стекла", -- Shard of Glass
    [C_ID .. 449] = "Металлическая пластина", -- Metal Plate
    [C_ID .. 450] = "Глаз Алчности", -- Eye of Greed
    [C_ID .. 451] = "Сукно Таро", -- Tarot Cloth
    [C_ID .. 452] = "Варикозные вены", -- Varicose Veins
    [C_ID .. 453] = "Перелом", -- Compound Fracture
    [C_ID .. 454] = "Полидактилия", -- Polydactyly
    [C_ID .. 455] = "Папина потерянная монета", -- Dad's Lost Coin
    [C_ID .. 456] = "Полуночный перекус", -- Midnight Snack
    [C_ID .. 457] = "Яйцеголовый", -- Cone Head
    [C_ID .. 458] = "Пупок", -- Belly Button
    [C_ID .. 459] = "Синусит", -- Sinus Infection
    [C_ID .. 460] = "Глаукома", -- Glaucoma
    [C_ID .. 461] = "Паразитоид", -- Parasitoid
    [C_ID .. 462] = "Глаз Белиала", -- Eye of Belial
    [C_ID .. 463] = "Серная кислота", -- Sulfuric Acid
    [C_ID .. 464] = "Символ баланса", -- Glyph of Balance
    [C_ID .. 465] = "Аналоговый стик", -- Analog Stick
    [C_ID .. 466] = "Инфекция", -- Contagion
    [C_ID .. 467] = "Палец!", -- Finger!
    [C_ID .. 468] = "Тень", -- Shade
    [C_ID .. 469] = "Депрессия", -- Depression
    [C_ID .. 470] = "Молчун", -- Hushy
    [C_ID .. 471] = "Маленький Монстро", -- Lil Monstro
    [C_ID .. 472] = "Малыш король", -- King Baby
    [C_ID .. 473] = "Большой Чабби", -- Big Chubby
    [C_ID .. 474] = "Разбитая стеклянная пушка", -- Broken Glass Cannon
    [C_ID .. 475] = "План C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Пустота", -- Void
    [C_ID .. 478] = "Пауза", -- Pause
    [C_ID .. 479] = "Плавильня", -- Smelter
    [C_ID .. 480] = "Компост", -- Compost
    [C_ID .. 481] = "Анализатор", -- Dataminer
    [C_ID .. 482] = "Переключатель", -- Clicker
    [C_ID .. 483] = "Мама Мега!", -- Mama Mega!
    [C_ID .. 484] = "Подождите, что?", -- Wait What?
    [C_ID .. 485] = "Погнутый пенни", -- Crooked Penny
    [C_ID .. 486] = "Тупая бритва", -- Dull Razor
    [C_ID .. 487] = "Картофелечистка", -- Potato Peeler
    [C_ID .. 488] = "Метроном", -- Metronome
    [C_ID .. 489] = "D Бесконечность", -- D Infinity
    [C_ID .. 490] = "Душа Эдема", -- Eden's Soul
    [C_ID .. 491] = "Кислотный малыш", -- Acid Baby
    [C_ID .. 492] = "Эй, слушай!", -- YO LISTEN!
    [C_ID .. 493] = "Адреналин", -- Adrenaline
    [C_ID .. 494] = "Лестница Иакова", -- Jacob's Ladder
    [C_ID .. 495] = "Призрачный перец", -- Ghost Pepper
    [C_ID .. 496] = "Эвтаназия", -- Euthanasia
    [C_ID .. 497] = "Камуфляжные трусы", -- Camo Undies
    [C_ID .. 498] = "Двойственность", -- Duality
    [C_ID .. 499] = "Причастие", -- Eucharist
    [C_ID .. 500] = "Мешок мешков", -- Sack of Sacks
    [C_ID .. 501] = "Пищевод Алчности", -- Greed's Gullet
    [C_ID .. 502] = "Большой прыщ", -- Large Zit
    [C_ID .. 503] = "Маленький рог", -- Little Horn
    [C_ID .. 504] = "Коричневый самородок", -- Brown Nugget
    [C_ID .. 505] = "Поке Гоу", -- Poke Go
    [C_ID .. 506] = "Предатель", -- Backstabber
    [C_ID .. 507] = "Острая соломинка", -- Sharp Straw
    [C_ID .. 508] = "Мамина бритва", -- Mom's Razor
    [C_ID .. 509] = "Кровавый глаз", -- Bloodshot Eye
    [C_ID .. 510] = "Бредящий", -- Delirious
    [C_ID .. 511] = "Сердитая муха", -- Angry Fly
    [C_ID .. 512] = "Чёрная дыра", -- Black Hole
    [C_ID .. 513] = "Бозо", -- Bozo
    [C_ID .. 514] = "Сломанный модем", -- Broken Modem
    [C_ID .. 515] = "Загадочный подарок", -- Mystery Gift
    [C_ID .. 516] = "Ороситель", -- Sprinkler
    [C_ID .. 517] = "Быстрые бомбы", -- Fast Bombs
    [C_ID .. 518] = "Друг в коробке", -- Buddy in a Box
    [C_ID .. 519] = "Малютка Сумасшествие", -- Lil Delirium
    [C_ID .. 520] = "Соединительные кабели", -- Jumper Cables
    [C_ID .. 521] = "Купон", -- Coupon
    [C_ID .. 522] = "Телепатия", -- Telekinesis
    [C_ID .. 523] = "Коробка для перевозки", -- Moving Box
    [C_ID .. 524] = "Технология Ноль", -- Technology Zero
    [C_ID .. 525] = "Проказа", -- Leprosy
    [C_ID .. 526] = "7 печатей", -- 7 Seals
    [C_ID .. 527] = "Мистер Ми!", -- Mr. ME!
    [C_ID .. 528] = "Ангельская призма", -- Angelic Prism
    [C_ID .. 529] = "Хлоп!", -- Pop!
    [C_ID .. 530] = "Список смерти", -- Death's List
    [C_ID .. 531] = "Гемолакрия", -- Haemolacria
    [C_ID .. 532] = "Лакрифагия", -- Lachryphagy
    [C_ID .. 533] = "Трисвятое", -- Trisagion
    [C_ID .. 534] = "Школьный портфель", -- Schoolbag
    [C_ID .. 535] = "Одеяло", -- Blanket
    [C_ID .. 536] = "Жертвенный алтарь", -- Sacrificial Altar
    [C_ID .. 537] = "Маленький Спевер", -- Lil Spewer
    [C_ID .. 538] = "Шарики", -- Marbles
    [C_ID .. 539] = "Загадочное яйцо", -- Mystery Egg
    [C_ID .. 540] = "Плоский камень", -- Flat Stone
    [C_ID .. 541] = "Костный мозг", -- Marrow
    [C_ID .. 542] = "Скользящее ребро", -- Slipped Rib
    [C_ID .. 543] = "Священная земля", -- Hallowed Ground
    [C_ID .. 544] = "Заострённое ребро", -- Pointy Rib
    [C_ID .. 545] = "Книга мёртвых", -- Book of the Dead
    [C_ID .. 546] = "Отцовское кольцо", -- Dad's Ring
    [C_ID .. 547] = "Бумаги о разводе", -- Divorce Papers
    [C_ID .. 548] = "Челюстная кость", -- Jaw Bone
    [C_ID .. 549] = "Хрупкие кости", -- Brittle Bones
    [C_ID .. 550] = "Первая часть Маминой лопаты", -- Broken Shovel
    [C_ID .. 551] = "Вторая часть Маминой лопаты", -- Broken Shovel
    [C_ID .. 552] = "Мамина лопата", -- Mom's Shovel
    [C_ID .. 553] = "Мукормикос", -- Mucormycosis
    [C_ID .. 554] = "Очжутко", -- 2Spooky
    [C_ID .. 555] = "Золотая бритва", -- Golden Razor
    [C_ID .. 556] = "Сульфур", -- Sulfur
    [C_ID .. 557] = "Печенье с предсказанием", -- Fortune Cookie
    [C_ID .. 558] = "Бельмо", -- Eye Sore
    [C_ID .. 559] = "120 вольт", -- 120 Volt
    [C_ID .. 560] = "Больно", -- It Hurts
    [C_ID .. 561] = "Миндальное молоко", -- Almond Milk
    [C_ID .. 562] = "Каменное дно", -- Rock Bottom
    [C_ID .. 563] = "Девчачьи бомбы", -- Nancy Bombs
    [C_ID .. 564] = "Кусок мыла", -- A Bar of Soap
    [C_ID .. 565] = "Кровавый щенок", -- Blood Puppy
    [C_ID .. 566] = "Ловец снов", -- Dream Catcher
    [C_ID .. 567] = "Пасхальная свеча", -- Paschal Candle
    [C_ID .. 568] = "Божественное вмешательство", -- Divine Intervention
    [C_ID .. 569] = "Кровавая клятва", -- Blood Oath
    [C_ID .. 570] = "Пластилиновое печенье", -- Playdough Cookie
    [C_ID .. 571] = "Сиротские носки", -- Orphan Socks
    [C_ID .. 572] = "Оккультный глаз", -- Eye of the Occult
    [C_ID .. 573] = "Чистое сердце", -- Immaculate Heart
    [C_ID .. 574] = "Дароносица", -- Monstrance
    [C_ID .. 575] = "Вторженец", -- The Intruder
    [C_ID .. 576] = "Грязные мысли", -- Dirty Mind
    [C_ID .. 577] = "Дамокл", -- Damocles
    [C_ID .. 578] = "Бесплатный лимонад", -- Free Lemonade
    [C_ID .. 579] = "Духовный меч", -- Spirit Sword
    [C_ID .. 580] = "Красный ключ", -- Red Key
    [C_ID .. 581] = "Псимуха", -- Psy Fly
    [C_ID .. 582] = "Волнистая шляпка", -- Wavy Cap
    [C_ID .. 583] = "Ракета в банке", -- Rocket in a Jar
    [C_ID .. 584] = "Книга добродетелей", -- Book of Virtues
    [C_ID .. 585] = "Алебастровая шкатулка", -- Alabaster Box
    [C_ID .. 586] = "Лестница", -- The Stairway
    [C_ID .. 587] = "", -- 
    [C_ID .. 588] = "Солнце", -- Sol
    [C_ID .. 589] = "Луна", -- Luna
    [C_ID .. 590] = "Меркурий", -- Mercurius
    [C_ID .. 591] = "Венера", -- Venus
    [C_ID .. 592] = "Земля", -- Terra
    [C_ID .. 593] = "Марс", -- Mars
    [C_ID .. 594] = "Юпитер", -- Jupiter
    [C_ID .. 595] = "Сатурн", -- Saturnus
    [C_ID .. 596] = "Уран", -- Uranus
    [C_ID .. 597] = "Нептун", -- Neptunus
    [C_ID .. 598] = "Плутон", -- Pluto
    [C_ID .. 599] = "Голова вуду", -- Voodoo Head
    [C_ID .. 600] = "Глазные капли", -- Eye Drops
    [C_ID .. 601] = "Покаяние", -- Act of Contrition
    [C_ID .. 602] = "Членская карточка", -- Member Card
    [C_ID .. 603] = "Запас батареек", -- Battery Pack
    [C_ID .. 604] = "Мамин браслет", -- Mom's Bracelet
    [C_ID .. 605] = "Ковырялка", -- The Scooper
    [C_ID .. 606] = "Глазной разлом", -- Ocular Rift
    [C_ID .. 607] = "Малыш нарыв", -- Boiled Baby
    [C_ID .. 608] = "Замораживающий малыш", -- Freezer Baby
    [C_ID .. 609] = "Вечный D6", -- Eternal D6
    [C_ID .. 610] = "Птичья клетка", -- Bird Cage
    [C_ID .. 611] = "Глотка", -- Larynx
    [C_ID .. 612] = "Потерянная душа", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Кровавые бомбы", -- Blood Bombs
    [C_ID .. 615] = "Малютка Дампи", -- Lil Dumpy
    [C_ID .. 616] = "Птичий глаз", -- Bird's Eye
    [C_ID .. 617] = "Магнит", -- Lodestone
    [C_ID .. 618] = "Тухлый помидор", -- Rotten Tomato
    [C_ID .. 619] = "Право первородства", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Красная похлёбка", -- Red Stew
    [C_ID .. 622] = "Генезис", -- Genesis
    [C_ID .. 623] = "Острый ключ", -- Sharp Key
    [C_ID .. 624] = "Бустер-пак", -- Booster Pack
    [C_ID .. 625] = "Мегагриб", -- Mega Mush
    [C_ID .. 626] = "Первая часть ножа", -- Knife Piece 1
    [C_ID .. 627] = "Вторая часть ножа", -- Knife Piece 2
    [C_ID .. 628] = "Свидетельство о смерти", -- Death Certificate
    [C_ID .. 629] = "Муха-бот", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Мясной тесак", -- Meat Cleaver
    [C_ID .. 632] = "Злой амулет", -- Evil Charm
    [C_ID .. 633] = "Догма", -- Dogma
    [C_ID .. 634] = "Чистилище", -- Purgatory
    [C_ID .. 635] = "Шов", -- Stitches
    [C_ID .. 636] = "Клавиша R", -- R Key
    [C_ID .. 637] = "Нокаутные капли", -- Knockout Drops
    [C_ID .. 638] = "Ластик", -- Eraser
    [C_ID .. 639] = "Фу-сердце", -- Yuck Heart
    [C_ID .. 640] = "Урна душ", -- Urn of Souls
    [C_ID .. 641] = "Акелдама", -- Akeldama
    [C_ID .. 642] = "Магическая кожа", -- Magic Skin
    [C_ID .. 643] = "Откровение", -- Revelation
    [C_ID .. 644] = "Утешительный приз", -- Consolation Prize
    [C_ID .. 645] = "Минитома", -- Tinytoma
    [C_ID .. 646] = "Серные бомбы", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 вольт", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Фруктовый малыш", -- Fruity Plum
    [C_ID .. 650] = "Сливовая флейта", -- Plum Flute
    [C_ID .. 651] = "Вифлеемская звезда", -- Star of Bethlehem
    [C_ID .. 652] = "Малыш в кубе", -- Cube Baby
    [C_ID .. 653] = "Возвратися воспять", -- Vade Retro
    [C_ID .. 654] = "Фальшивая докторская степень", -- False PHD
    [C_ID .. 655] = "Крути, чтоб выиграть", -- Spin to Win
    [C_ID .. 656] = "", -- Damocles
    [C_ID .. 657] = "Васкулит", -- Vasculitis
    [C_ID .. 658] = "Огромная клетка", -- Giant Cell
    [C_ID .. 659] = "Тропикамид", -- Tropicamide
    [C_ID .. 660] = "Гадание на картах", -- Card Reading
    [C_ID .. 661] = "Пятерняшки", -- Quints
    [C_ID .. 662] = "", -- 
    [C_ID .. 663] = "Зуб и гвоздь", -- Tooth and Nail
    [C_ID .. 664] = "Кутёжник", -- Binge Eater
    [C_ID .. 665] = "Глаз Гаппи", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Соломенное чучело", -- Strawman
    [C_ID .. 668] = "Папина записка", -- Dad's Note
    [C_ID .. 669] = "Сосиска", -- Sausage
    [C_ID .. 670] = "Выбор?", -- Options?
    [C_ID .. 671] = "Конфетное сердце", -- Candy Heart
    [C_ID .. 672] = "Фунт плоти", -- A Pound of Flesh
    [C_ID .. 673] = "Искупление", -- Redemption
    [C_ID .. 674] = "Духовные цепи", -- Spirit Shackles
    [C_ID .. 675] = "Треснувший шар", -- Cracked Orb
    [C_ID .. 676] = "Пустое сердце", -- Empty Heart
    [C_ID .. 677] = "Астральная проекция", -- Astral Projection
    [C_ID .. 678] = "Кесарево", -- C Section
    [C_ID .. 679] = "Малютка Абаддон", -- Lil Abaddon
    [C_ID .. 680] = "Месть Монтесумы", -- Montezuma's Revenge
    [C_ID .. 681] = "Малютка портал", -- Lil Portal
    [C_ID .. 682] = "Червячок-друг", -- Worm Friend
    [C_ID .. 683] = "Костяные выступы", -- Bone Spurs
    [C_ID .. 684] = "Голодная душа", -- Hungry Soul
    [C_ID .. 685] = "Банка огоньков", -- Jar of Wisps
    [C_ID .. 686] = "Медальон души", -- Soul Locket
    [C_ID .. 687] = "Поиск друзей", -- Friend Finder
    [C_ID .. 688] = "Внутренний ребёнок", -- Inner Child
    [C_ID .. 689] = "Глючная корона", -- Glitched Crown
    [C_ID .. 690] = "Жевательное драже", -- Belly Jelly
    [C_ID .. 691] = "Священный шар", -- Sacred Orb
    [C_ID .. 692] = "Кровавые узы", -- Sanguine Bond
    [C_ID .. 693] = "Рой", -- The Swarm
    [C_ID .. 694] = "Горе", -- Heartbreak
    [C_ID .. 695] = "Кровавый порыв", -- Bloody Gust
    [C_ID .. 696] = "Спасение", -- Salvation
    [C_ID .. 697] = "Исчезающий близнец", -- Vanishing Twin
    [C_ID .. 698] = "Нечестивая парочка", -- Twisted Pair
    [C_ID .. 699] = "Ярость Азазеля", -- Azazel's Rage
    [C_ID .. 700] = "Эхо-камера", -- Echo Chamber
    [C_ID .. 701] = "Гробница Исаака", -- Isaac's Tomb
    [C_ID .. 702] = "Мстительный дух", -- Vengeful Spirit
    [C_ID .. 703] = "Исав Младший", -- Esau Jr.
    [C_ID .. 704] = "Берсерк!", -- Berserk!
    [C_ID .. 705] = "Тёмные силы", -- Dark Arts
    [C_ID .. 706] = "Бездна", -- Abyss
    [C_ID .. 707] = "Ужин", -- Supper
    [C_ID .. 708] = "Степлер", -- Stapler
    [C_ID .. 709] = "Суплекс!", -- Suplex!
    [C_ID .. 710] = "Мешок создания", -- Bag of Crafting
    [C_ID .. 711] = "Кувырок", -- Flip
    [C_ID .. 712] = "Лемегетон", -- Lemegeton
    [C_ID .. 713] = "Свищ", -- Sumptorium
    [C_ID .. 714] = "Отзыв", -- Recall
    [C_ID .. 715] = "Баночка", -- Hold
    [C_ID .. 716] = "Мешок Хранителя", -- Keeper's Sack
    [C_ID .. 717] = "Родня Хранителя", -- Keeper's Kin
    [C_ID .. 718] = "", -- 
    [C_ID .. 719] = "Коробок Хранителя", -- Keeper's Box
    [C_ID .. 720] = "Банка для всего", -- Everything Jar
    [C_ID .. 721] = "ТМТРЕЙНЕР", -- TMTRAINER
    [C_ID .. 722] = "Анима сола", -- Anima Sola
    [C_ID .. 723] = "Кубик с вычетом", -- Spindown Dice
    [C_ID .. 724] = "Гиперкоагуляция", -- Hypercoagulation
    [C_ID .. 725] = "СРК", -- IBS
    [C_ID .. 726] = "Кровохарканье", -- Hemoptysis
    [C_ID .. 727] = "Призрачные бомбы", -- Ghost Bombs
    [C_ID .. 728] = "Гелло", -- Gello
    [C_ID .. 729] = "Голову с плеч", -- Decap Attack
    [C_ID .. 730] = "Стеклянный Глаз", -- Glass Eye
    [C_ID .. 731] = "Ячмень", -- Stye
    [C_ID .. 732] = "Мамино Кольцо", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Проглоченный Пенни", -- Swallowed Penny
    [T_ID .. 2] = "Окаменевшая какашка", -- Petrified Poop
    [T_ID .. 3] = "Батарейка ААА", -- AAA Battery
    [T_ID .. 4] = "Сломанный пульт", -- Broken Remote
    [T_ID .. 5] = "Пурпурное сердце", -- Purple Heart
    [T_ID .. 6] = "Сломанный магнит", -- Broken Magnet
    [T_ID .. 7] = "Бусинка от четок", -- Rosary Bead
    [T_ID .. 8] = "Картридж", -- Cartridge
    [T_ID .. 9] = "Пульсирующий червь", -- Pulse Worm
    [T_ID .. 10] = "Извивающийся червь", -- Wiggle Worm
    [T_ID .. 11] = "Кольцевой червь", -- Ring Worm
    [T_ID .. 12] = "Сплющенный червь", -- Flat Worm
    [T_ID .. 13] = "Кредит в магазине", -- Store Credit
    [T_ID .. 14] = "Мозоль", -- Callus
    [T_ID .. 15] = "Счастливый камень", -- Lucky Rock
    [T_ID .. 16] = "Ноготь Мамы", -- Mom's Toenail
    [T_ID .. 17] = "Чёрная помада", -- Black Lipstick
    [T_ID .. 18] = "Библейский трактат", -- Bible Tract
    [T_ID .. 19] = "Скрепка", -- Paper Clip
    [T_ID .. 20] = "Обезьянья Лапка", -- Monkey Paw
    [T_ID .. 21] = "Загадочная бумажка", -- Mysterious Paper
    [T_ID .. 22] = "Хвост демона", -- Daemon's Tail
    [T_ID .. 23] = "Плакат о пропавшем без вести", -- Missing Poster
    [T_ID .. 24] = "Пенни из задницы", -- Butt Penny
    [T_ID .. 25] = "Загадочная шоколадка", -- Mysterious Candy
    [T_ID .. 26] = "Крюкообразный червяк", -- Hook Worm
    [T_ID .. 27] = "Прямой червь", -- Whip Worm
    [T_ID .. 28] = "Сломанный анх", -- Broken Ankh
    [T_ID .. 29] = "Рыбья голова", -- Fish Head
    [T_ID .. 30] = "Розовый глаз", -- Pinky Eye
    [T_ID .. 31] = "Кнопка", -- Push Pin
    [T_ID .. 32] = "Вольная шляпка", -- Liberty Cap
    [T_ID .. 33] = "Пуповина", -- Umbilical Cord
    [T_ID .. 34] = "Сердце ребенка", -- Child's Heart
    [T_ID .. 35] = "Изогнутый рог", -- Curved Horn
    [T_ID .. 36] = "Ржавый ключ", -- Rusted Key
    [T_ID .. 37] = "Козлиное копыто", -- Goat Hoof
    [T_ID .. 38] = "Мамина жемчужина", -- Mom's Pearl
    [T_ID .. 39] = "Рак", -- Cancer
    [T_ID .. 40] = "Красная заплатка", -- Red Patch
    [T_ID .. 41] = "Спичка", -- Match Stick
    [T_ID .. 42] = "Счастливый палец", -- Lucky Toe
    [T_ID .. 43] = "Проклятый череп", -- Cursed Skull
    [T_ID .. 44] = "Безопасная крышка", -- Safety Cap
    [T_ID .. 45] = "Туз пик", -- Ace of Spades
    [T_ID .. 46] = "Вилка Исаака", -- Isaac's Fork
    [T_ID .. 47] = "ID в игре не задействован", -- 
    [T_ID .. 48] = "Потерянная страница", -- A Missing Page
    [T_ID .. 49] = "Кровавый пенни", -- Bloody Penny
    [T_ID .. 50] = "Сгоревший пенни", -- Burnt Penny
    [T_ID .. 51] = "Сплющенный пенни", -- Flat Penny
    [T_ID .. 52] = "Поддельный пенни", -- Counterfeit Penny
    [T_ID .. 53] = "Клещ", -- Tick
    [T_ID .. 54] = "Голова Исаака", -- Isaac's Head
    [T_ID .. 55] = "Вера Мэгги", -- Maggy's Faith
    [T_ID .. 56] = "Язык Иуды", -- Judas' Tongue
    [T_ID .. 57] = "Душа ???", -- ???'s Soul
    [T_ID .. 58] = "Локон Самсона", -- Samson's Lock
    [T_ID .. 59] = "Глаз Каина", -- Cain's Eye
    [T_ID .. 60] = "Лапка птички Евы", -- Eve's Bird Foot
    [T_ID .. 61] = "Левая рука", -- The Left Hand
    [T_ID .. 62] = "Сияющий камень", -- Shiny Rock
    [T_ID .. 63] = "Безопасные ножницы", -- Safety Scissors
    [T_ID .. 64] = "Радужный червь", -- Rainbow Worm
    [T_ID .. 65] = "Ленточный червь", -- Tape Worm
    [T_ID .. 66] = "Ленивый червь", -- Lazy Worm
    [T_ID .. 67] = "Сломанный Кубик", -- Cracked Dice
    [T_ID .. 68] = "Супер магнит", -- Super Magnet
    [T_ID .. 69] = "Выцветшая фотокарточка", -- Faded Polaroid
    [T_ID .. 70] = "Вошь", -- Louse
    [T_ID .. 71] = "Мочевой пузырь Боба", -- Bob's Bladder
    [T_ID .. 72] = "Часовая батарейка", -- Watch Battery
    [T_ID .. 73] = "Взрывающаяся крышка", -- Blasting Cap
    [T_ID .. 74] = "Кладоискатель", -- Stud Finder
    [T_ID .. 75] = "Ошибка", -- Error
    [T_ID .. 76] = "Фишка для покера", -- Poker Chip
    [T_ID .. 77] = "Блистер", -- Blister
    [T_ID .. 78] = "Секундная стрелка", -- Second Hand
    [T_ID .. 79] = "Неизведанная бесконечность", -- Endless Nameless
    [T_ID .. 80] = "Черное перо", -- Black Feather
    [T_ID .. 81] = "Слепая ярость", -- Blind Rage
    [T_ID .. 82] = "Золотая подкова", -- Golden Horse Shoe
    [T_ID .. 83] = "Ключ от магазина", -- Store Key
    [T_ID .. 84] = "Ребро Жадности", -- Rib of Greed
    [T_ID .. 85] = "Карма", -- Karma
    [T_ID .. 86] = "Малютка личинка", -- Lil Larva
    [T_ID .. 87] = "Мамин медальон", -- Mom's Locket
    [T_ID .. 88] = "Нет!", -- NO!
    [T_ID .. 89] = "Детский поводок", -- Child Leash
    [T_ID .. 90] = "Коричневая крышка", -- Brown Cap
    [T_ID .. 91] = "Меконий", -- Meconium
    [T_ID .. 92] = "Треснувшая корона", -- Cracked Crown
    [T_ID .. 93] = "Использованный подгузник", -- Used Diaper
    [T_ID .. 94] = "Рыбий хвост", -- Fish Tail
    [T_ID .. 95] = "Чёрный зуб", -- Black Tooth
    [T_ID .. 96] = "Червь Уроборос", -- Ouroboros Worm
    [T_ID .. 97] = "Миндалина", -- Tonsil
    [T_ID .. 98] = "Козявка", -- Nose Goblin
    [T_ID .. 99] = "Супер мяч", -- Super Ball
    [T_ID .. 100] = "Вибрирующая лампочка", -- Vibrant Bulb
    [T_ID .. 101] = "Тусклая лампочка", -- Dim Bulb
    [T_ID .. 102] = "Разорванная карта", -- Fragmented Card
    [T_ID .. 103] = "Равенство!", -- Equality!
    [T_ID .. 104] = "Кость желаний", -- Wish Bone
    [T_ID .. 105] = "Пакет с обедом", -- Bag Lunch
    [T_ID .. 106] = "Потерянная пробка", -- Lost Cork
    [T_ID .. 107] = "Сердце ворона", -- Crow Heart
    [T_ID .. 108] = "Грецкий орех", -- Walnut
    [T_ID .. 109] = "Скотч", -- Duct Tape
    [T_ID .. 110] = "Серебряный доллар", -- Silver Dollar
    [T_ID .. 111] = "Кровавая корона", -- Bloody Crown
    [T_ID .. 112] = "Заплати чтобы выиграть", -- Pay To Win
    [T_ID .. 113] = "Саранча Войны", -- Locust of War
    [T_ID .. 114] = "Саранча Чумы", -- Locust of Pestilence
    [T_ID .. 115] = "Саранча Голода", -- Locust of Famine
    [T_ID .. 116] = "Саранча Смерти", -- Locust of Death
    [T_ID .. 117] = "Саранча Завоевателя", -- Locust of Conquest
    [T_ID .. 118] = "Крыло летучей мыши", -- Bat Wing
    [T_ID .. 119] = "Стволовая клетка", -- Stem Cell
    [T_ID .. 120] = "Заколка", -- Hairpin
    [T_ID .. 121] = "Деревянный крест", -- Wooden Cross
    [T_ID .. 122] = "Масло", -- Butter!
    [T_ID .. 123] = "Филигранное перо", -- Filigree Feather
    [T_ID .. 124] = "Дверной ограничитель", -- Door Stop
    [T_ID .. 125] = "Удлинитель", -- Extension Cord
    [T_ID .. 126] = "Гнилой пенни", -- Rotten Penny
    [T_ID .. 127] = "Малыш-сгибатель", -- Baby-Bender
    [T_ID .. 128] = "Кость пальца", -- Finger Bone
    [T_ID .. 129] = "Зубодробилка", -- Jawbreaker
    [T_ID .. 130] = "Жеваная ручка", -- Chewed Pen
    [T_ID .. 131] = "Благословенный пенни", -- Blessed Penny
    [T_ID .. 132] = "Сломанный шприц", -- Broken Syringe
    [T_ID .. 133] = "Короткий запал", -- Short Fuse
    [T_ID .. 134] = "Гигантская фасоль", -- Gigante Bean
    [T_ID .. 135] = "Зажигалка", -- A Lighter
    [T_ID .. 136] = "Сломанный замок", -- Broken Padlock
    [T_ID .. 137] = "Незабудка", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Каплевидный амулет", -- Teardrop Charm
    [T_ID .. 140] = "Содомское яблоко", -- Apple of Sodom
    [T_ID .. 141] = "Забытая колыбельная", -- Forgotten Lullaby
    [T_ID .. 142] = "Вера Вифы", -- Beth's Faith
    [T_ID .. 143] = "Старый конденсатор", -- Old Capacitor
    [T_ID .. 144] = "Мозговой червь", -- Brain Worm
    [T_ID .. 145] = "Совершенство", -- Perfection
    [T_ID .. 146] = "Корона дьявола", -- Devil's Crown
    [T_ID .. 147] = "Заряженный пенни", -- Charged Penny
    [T_ID .. 148] = "Ожерелье дружбы", -- Friendship Necklace
    [T_ID .. 149] = "Тревожная кнопка", -- Panic Button
    [T_ID .. 150] = "Синий ключ", -- Blue Key
    [T_ID .. 151] = "Плоский напильник", -- Flat File
    [T_ID .. 152] = "Линза телескопа", -- Telescope Lens
    [T_ID .. 153] = "Мамин локон", -- Mom's Lock
    [T_ID .. 154] = "Мешочек для костей", -- Dice Bag
    [T_ID .. 155] = "Святая корона", -- Holy Crown
    [T_ID .. 156] = "Мамин поцелуй", -- Mother's Kiss
    [T_ID .. 157] = "Порванная карта", -- Torn Card
    [T_ID .. 158] = "Порванный карман", -- Torn Pocket
    [T_ID .. 159] = "Позолоченный ключ", -- Gilded Key
    [T_ID .. 160] = "Счастливый мешок", -- Lucky Sack
    [T_ID .. 161] = "Порочная корона", -- Wicked Crown
    [T_ID .. 162] = "Обрубок Азазеля", -- Azazel's Stump
    [T_ID .. 163] = "Плод Дингла", -- Dingle Berry
    [T_ID .. 164] = "Кольцевая крышка", -- Ring Cap
    [T_ID .. 165] = "Не-а!", -- Nuh Uh!
    [T_ID .. 166] = "Пластилин для лепки", -- Modeling Clay
    [T_ID .. 167] = "Полированная кость", -- Polished Bone
    [T_ID .. 168] = "Полое сердце", -- Hollow Heart
    [T_ID .. 169] = "Детский рисунок", -- Kid's Drawing
    [T_ID .. 170] = "Хрустальный ключ", -- Crystal Key
    [T_ID .. 171] = "Сделка Хранителя", -- Keeper's Bargain
    [T_ID .. 172] = "Проклятый пенни", -- Cursed Penny
    [T_ID .. 173] = "Твоя душа", -- Your Soul
    [T_ID .. 174] = "Числовой магнит", -- Number Magnet
    [T_ID .. 175] = "Странный ключ", -- Strange Key
    [T_ID .. 176] = "Малыш сгусток", -- Lil Clot
    [T_ID .. 177] = "Временная татуировка", -- Temporary Tattoo
    [T_ID .. 178] = "Проглоченный М80", -- Swallowed M80
    [T_ID .. 179] = "Пульт радиоуправления", -- RC Remote
    [T_ID .. 180] = "Найденная душа", -- Found Soul
    [T_ID .. 181] = "Пакет расширения", -- Expansion Pack
    [T_ID .. 182] = "Сущность Вифы", -- Beth's Essence
    [T_ID .. 183] = "Близнецы", -- The Twins
    [T_ID .. 184] = "Документы об усыновлении", -- Adoption Papers
    [T_ID .. 185] = "Нога сверчка", -- Cricket Leg
    [T_ID .. 186] = "Лучший друг Аполлиона", -- Apollyon's Best Friend
    [T_ID .. 187] = "Разбитые очки", -- Broken Glasses
    [T_ID .. 188] = "Кубик льда", -- Ice Cube
    [T_ID .. 189] = "Знак Бафомета", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Дурак", -- 0 - The Fool
    [Card_ID .. 2] = "I - Маг", -- I - The Magician
    [Card_ID .. 3] = "II - Верховная жрица", -- II - The High Priestess
    [Card_ID .. 4] = "III - Импepaтpицa", -- III - The Empress
    [Card_ID .. 5] = "IV - Император", -- IV - The Emperor
    [Card_ID .. 6] = "V - Иерофант", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Влюблённые", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Колесница", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Правосудие", -- VIII - Justice
    [Card_ID .. 10] = "IX - Отшельник", -- IX - The Hermit
    [Card_ID .. 11] = "X - Колесо фортуны", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Сила", -- XI - Strength
    [Card_ID .. 13] = "XII - Повешенный", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Смерть", -- XIII - Death
    [Card_ID .. 15] = "XIV - Умеренность", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Дьявол", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Башня", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Звёзды", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Луна", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Солнце", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Суд", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Мир", -- XXI - The World
    [Card_ID .. 23] = "Двойка Треф", -- 2 of Clubs
    [Card_ID .. 24] = "Двойка Бубен", -- 2 of Diamonds
    [Card_ID .. 25] = "Двойка Пик", -- 2 of Spades
    [Card_ID .. 26] = "Двойка Червей", -- 2 of Hearts
    [Card_ID .. 27] = "Туз Треф", -- Ace of Clubs
    [Card_ID .. 28] = "Туз Бубен", -- Ace of Diamonds
    [Card_ID .. 29] = "Туз Пик", -- Ace of Spades
    [Card_ID .. 30] = "Туз Червей", -- Ace of Hearts
    [Card_ID .. 31] = "Джокер", -- Joker
    [Card_ID .. 32] = "Хагалаз", -- Hagalaz
    [Card_ID .. 33] = "Йера", -- Jera
    [Card_ID .. 34] = "Эваз", -- Ehwaz
    [Card_ID .. 35] = "Дагаз", -- Dagaz
    [Card_ID .. 36] = "Ансуз", -- Ansuz
    [Card_ID .. 37] = "Пертро", -- Perthro
    [Card_ID .. 38] = "Беркано", -- Berkano
    [Card_ID .. 39] = "Альгиз", -- Algiz
    [Card_ID .. 40] = "Пустая руна", -- Blank Rune
    [Card_ID .. 41] = "Черная руна", -- Black Rune
    [Card_ID .. 42] = "Карта хаоса", -- Chaos Card
    [Card_ID .. 43] = "Кредитная карта", -- Credit Card
    [Card_ID .. 44] = "Карта правил", -- Rules Card
    [Card_ID .. 45] = "Карта против человечества", -- A Card Against Humanity
    [Card_ID .. 46] = "Карта Короля-самоубийцы", -- Suicide King
    [Card_ID .. 47] = "Свободный Выход", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "? Карта", -- ? Card
    [Card_ID .. 49] = "Осколок кости", -- Dice Shard
    [Card_ID .. 50] = "Экстренный контакт", -- Emergency Contact
    [Card_ID .. 51] = "Святая карта", -- Holy Card
    [Card_ID .. 52] = "Огромный рост", -- Huge Growth
    [Card_ID .. 53] = "Древний зов", -- Ancient Recall
    [Card_ID .. 54] = "Прогулка по Эпохе", -- Era Walk
    [Card_ID .. 55] = "Осколок Руны", -- Rune Shard
    [Card_ID .. 56] = "0 - Дурак? ", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Маг?", -- I - The Magician?
    [Card_ID .. 58] = "II - Верховная жрица?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - Императрица?", -- III - The Empress?
    [Card_ID .. 60] = "IV - Император?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Иерофант?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Влюблённые?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Колесница?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Правосудие?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - Отшельник?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Колесо фортуны?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Сила?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Повешенный?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Смерть?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Умеренность?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Дьявол?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - Башня?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Звёзды?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - Луна?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Солнце?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Суд?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Мир?", -- XXI - The World?
    [Card_ID .. 78] = "Треснувший ключ", -- Cracked Key
    [Card_ID .. 79] = "Дама Червей", -- Queen of Hearts
    [Card_ID .. 80] = "Шальная карта", -- Wild Card
    [Card_ID .. 81] = "Душа Исаака", -- Soul of Isaac
    [Card_ID .. 82] = "Душа Магдалины", -- Soul of Magdalene
    [Card_ID .. 83] = "Душа Каина", -- Soul of Cain
    [Card_ID .. 84] = "Душа Иуды", -- Soul of Judas
    [Card_ID .. 85] = "Душа ???", -- Soul of ???
    [Card_ID .. 86] = "Душа Евы", -- Soul of Eve
    [Card_ID .. 87] = "Душа Самсона", -- Soul of Samson
    [Card_ID .. 88] = "Душа Азазеля", -- Soul of Azazel
    [Card_ID .. 89] = "Душа Лазаря", -- Soul of Lazarus
    [Card_ID .. 90] = "Душа Эдема", -- Soul of Eden
    [Card_ID .. 91] = "Душа Потерянного", -- Soul of the Lost
    [Card_ID .. 92] = "Душа Лилит", -- Soul of Lilith
    [Card_ID .. 93] = "Душа Хранителя", -- Soul of the Keeper
    [Card_ID .. 94] = "Душа Аполлиона", -- Soul of Apollyon
    [Card_ID .. 95] = "Душа Забытого", -- Soul of the Forgotten
    [Card_ID .. 96] = "Душа Вифании", -- Soul of Bethany
    [Card_ID .. 97] = "Душа Иакова и Исава", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 0] = "Вонючий газ", -- Bad Gas
    [Pill_ID .. 1] = "Плохой приход", -- Bad Trip
    [Pill_ID .. 2] = "Стальные яйца", -- Balls of Steel
    [Pill_ID .. 3] = "Бомбы = Ключи", -- Bombs are Key
    [Pill_ID .. 4] = "Взрывная диарея", -- Explosive Diarrhea
    [Pill_ID .. 5] = "Полное здоровье", -- Full Health
    [Pill_ID .. 6] = "- Здоровье", -- Health Down
    [Pill_ID .. 7] = "+ Здоровье", -- Health Up
    [Pill_ID .. 8] = "Я нашел пилюли", -- I Found Pills
    [Pill_ID .. 9]  = "Зрелость", -- Puberty
    [Pill_ID .. 10] = "Милая мушка", -- Pretty Fly
    [Pill_ID .. 11] = "Дальность ↓", -- Range Down
    [Pill_ID .. 12] = "Дальность ↑", -- Range Up
    [Pill_ID .. 13] = "Скорость ↓", -- Speed Down
    [Pill_ID .. 14] = "Скорость ↑", -- Speed Up
    [Pill_ID .. 15] = "Скорострельность ↓", -- Tears Down
    [Pill_ID .. 16] = "Скорострельность ↑", -- Tears Up
    [Pill_ID .. 17] = "Удача ↓", -- Luck Down
    [Pill_ID .. 18] = "Удача ↑", -- Luck Up
    [Pill_ID .. 19] = "Телепилюли", -- Telepills
    [Pill_ID .. 20] = "Энергия на 48 часов", -- 48 Hour Energy!
    [Pill_ID .. 21] = "Кровавая рвота", -- Hematemesis
    [Pill_ID .. 22] = "Паралич", -- Paralysis
    [Pill_ID .. 23] = "Я могу видеть вечно", -- I can see forever!
    [Pill_ID .. 24] = "Феромоны", -- Pheromones
    [Pill_ID .. 25] = "Амнезия", -- Amnesia
    [Pill_ID .. 26] = "Лимонная вечеринка", -- Lemon Party
    [Pill_ID .. 27] = "А ты волшебник?", -- R U A Wizard?
    [Pill_ID .. 28] = "Обезболивающее", -- Percs!
    [Pill_ID .. 29] = "Зависимый", -- Addicted!
    [Pill_ID .. 30] = "Расслабься", -- Re-Lax
    [Pill_ID .. 31] = "???", -- ???
    [Pill_ID .. 32] = "Что-то делает тебя крупнее", -- One makes you larger
    [Pill_ID .. 33] = "Что-то делает тебя меньше", -- One makes you small
    [Pill_ID .. 34] = "Зараженный!", -- Infested!
    [Pill_ID .. 35] = "Зараженный?", -- Infested?
    [Pill_ID .. 36] = "Пилюля силы!", -- Power Pill!
    [Pill_ID .. 37] = "Ретро зрение", -- Retro Vision
    [Pill_ID .. 38] = "Друзья до конца!", -- Friends Till The End!
    [Pill_ID .. 39] = "Вялый", -- X-Lax
    [Pill_ID .. 40] = "Что-то не так...", -- Something's wrong...
    [Pill_ID .. 41] = "Я сонный", -- I'm Drowsy...
    [Pill_ID .. 42] = "Я возбужден!!!", -- I'm Excited!!
    [Pill_ID .. 43] = "Глотай!", -- Gulp!
    [Pill_ID .. 44] = "Хорф!", -- Horf!
    [Pill_ID .. 45] = "Похоже, я иду на рассвет!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 46] = "Вурп!", -- Vurp!
    [Pill_ID .. 47] = "Скорость слезы ↓", -- Shot speed Down
    [Pill_ID .. 48] = "Скорость слезы ↑", -- Shot speed Up
    [Pill_ID .. 49] = "Экспериментальная пилюля", -- Experimental Pill
    [Pill_ID .. 9999] = "Золотая пилюля", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])