local languageCode = "uk_ua"
local C_ID = "5.100."
local T_ID = "5.350."
local Pill_ID = "5.70."
local Card_ID = "5.300."
EID.ItemNames[languageCode] = {}


---------collectibles---------
local collectibles = {
    [C_ID .. 1] = "Сумна цибуля", -- The Sad Onion
    [C_ID .. 2] = "Внутрiшнє Око", -- The Inner Eye
    [C_ID .. 3] = "Згинач ложок", -- Spoon Bender
    [C_ID .. 4] = "Голова Крікета", -- Cricket's Head
    [C_ID .. 5] = "Моє Вiдображення", -- My Reflection
    [C_ID .. 6] = "Номер Один", -- Number One
    [C_ID .. 7] = "Кров мученика", -- Blood of the Martyr
    [C_ID .. 8] = "Брат Боббі", -- Brother Bobby
    [C_ID .. 9] = "Скатол", -- Skatole
    [C_ID .. 10] = "Вінець з мух", -- Halo of Flies
    [C_ID .. 11] = "+1!", -- 1up!
    [C_ID .. 12] = "Чарівний гриб", -- Magic Mushroom
    [C_ID .. 13] = "Вірус", -- The Virus
    [C_ID .. 14] = "Гнів Роїда", -- Roid Rage
    [C_ID .. 15] = "<3", -- <3
    [C_ID .. 16] = "Сира печінка", -- Raw Liver
    [C_ID .. 17] = "Ключ скелета", -- Skeleton Key
    [C_ID .. 18] = "Долар", -- A Dollar
    [C_ID .. 19] = "Бум!", -- Boom!
    [C_ID .. 20] = "Трансцендентність", -- Transcendence
    [C_ID .. 21] = "Компас", -- The Compass
    [C_ID .. 22] = "Обід", -- Lunch
    [C_ID .. 23] = "Вечеря", -- Dinner
    [C_ID .. 24] = "Десерт", -- Dessert
    [C_ID .. 25] = "Сніданок", -- Breakfast
    [C_ID .. 26] = "Гниле м'ясо", -- Rotten Meat
    [C_ID .. 27] = "Дерев'яна ложка", -- Wooden Spoon
    [C_ID .. 28] = "Пасок", -- The Belt
    [C_ID .. 29] = "Матусині трусики", -- Mom's Underwear
    [C_ID .. 30] = "Матусині каблуки", -- Mom's Heels
    [C_ID .. 31] = "Матусина помада", -- Mom's Lipstick
    [C_ID .. 32] = "Вішак для одягу", -- Wire Coat Hanger
    [C_ID .. 33] = "Біблія", -- The Bible
    [C_ID .. 34] = "Книга Беліала", -- The Book of Belial
    [C_ID .. 35] = "Некрономікон", -- The Necronomicon
    [C_ID .. 36] = "Лайно", -- The Poop
    [C_ID .. 37] = "Містер Бум", -- Mr. Boom
    [C_ID .. 38] = "Голова Таммі", -- Tammy's Head
    [C_ID .. 39] = "Матусин бюстгальтер", -- Mom's Bra
    [C_ID .. 40] = "Камікадзе!", -- Kamikaze!
    [C_ID .. 41] = "Матусина прокладка", -- Mom's Pad
    [C_ID .. 42] = "Гнила Голова Боба", -- Bob's Rotten Head
    [C_ID .. 43] = "", -- 
    [C_ID .. 44] = "Телепорт!", -- Teleport!
    [C_ID .. 45] = "Смачне Серце", -- Yum Heart
    [C_ID .. 46] = "Щаслива ніжка", -- Lucky Foot
    [C_ID .. 47] = "Пульт доктора Зародка", -- Doctor's Remote
    [C_ID .. 48] = "Стріла Купідона", -- Cupid's Arrow
    [C_ID .. 49] = "Шуп-да-Вуп!", -- Shoop da Whoop!
    [C_ID .. 50] = "Стівен", -- Steven
    [C_ID .. 51] = "Пентаграма", -- Pentagram
    [C_ID .. 52] = "Доктор Фетус", -- Dr. Fetus
    [C_ID .. 53] = "Магнето", -- Magneto
    [C_ID .. 54] = "Карта скарбів", -- Treasure Map
    [C_ID .. 55] = "Матусине око", -- Mom's Eye
    [C_ID .. 56] = "Лимонна невдача", -- Lemon Mishap
    [C_ID .. 57] = "Фанат на відстані", -- Distant Admiration
    [C_ID .. 58] = "Книга Тіней", -- Book of Shadows
    [C_ID .. 59] = "Книга Беліала", -- The Book of Belial
    [C_ID .. 60] = "Драбина", -- The Ladder
    [C_ID .. 61] = "", -- 
    [C_ID .. 62] = "Чарівність Вампіра", -- Charm of the Vampire
    [C_ID .. 63] = "Батарея", -- The Battery
    [C_ID .. 64] = "Знижки Steam", -- Steam Sale
    [C_ID .. 65] = "Кулінарна книга анархіста", -- Anarchist Cookbook
    [C_ID .. 66] = "Пісочний годинник", -- The Hourglass
    [C_ID .. 67] = "Сестра Меггі", -- Sister Maggy
    [C_ID .. 68] = "Технології", -- Technology
    [C_ID .. 69] = "Шоколадне молоко", -- Chocolate Milk
    [C_ID .. 70] = "Гормони Росту", -- Growth Hormones
    [C_ID .. 71] = "Грибочок", -- Mini Mush
    [C_ID .. 72] = "Вервиця", -- Rosary
    [C_ID .. 73] = "Кубик м'яса", -- Cube of Meat
    [C_ID .. 74] = "Четвертак", -- A Quarter
    [C_ID .. 75] = "Доктор наук", -- PHD
    [C_ID .. 76] = "Рентгенівське бачення", -- X-Ray Vision
    [C_ID .. 77] = "Мій маленький єдиноріг", -- My Little Unicorn
    [C_ID .. 78] = "Книга Одкровень", -- Book of Revelations
    [C_ID .. 79] = "Позначка", -- The Mark
    [C_ID .. 80] = "Договір", -- The Pact
    [C_ID .. 81] = "Мертвий кіт", -- Dead Cat
    [C_ID .. 82] = "Володар ями", -- Lord of the Pit
    [C_ID .. 83] = "Цвях", -- The Nail
    [C_ID .. 84] = "Треба йти глибше!", -- We Need To Go Deeper!
    [C_ID .. 85] = "Колода карт", -- Deck of Cards
    [C_ID .. 86] = "Зуб Монстро", -- Monstro's Tooth
    [C_ID .. 87] = "Ріжки Локі", -- Loki's Horns
    [C_ID .. 88] = "Маленький Чаббі", -- Little Chubby
    [C_ID .. 89] = "Укус павука", -- Spider Bite
    [C_ID .. 90] = "Маленький камінь", -- The Small Rock
    [C_ID .. 91] = "Шолом Спелеолога", -- Spelunker Hat
    [C_ID .. 92] = "Супер пластир", -- Super Bandage
    [C_ID .. 93] = "Геймкід", -- The Gamekid
    [C_ID .. 94] = "Мішок пенні", -- Sack of Pennies
    [C_ID .. 95] = "Робо-Дитя", -- Robo-Baby
    [C_ID .. 96] = "Маленький Ч.А.Д.", -- Little C.H.A.D.
    [C_ID .. 97] = "Книга Гріхів", -- The Book of Sin
    [C_ID .. 98] = "Реліквія", -- The Relic
    [C_ID .. 99] = "Маленький Гіш", -- Little Gish
    [C_ID .. 100] = "Маленький Стівен", -- Little Steven
    [C_ID .. 101] = "Німб", -- The Halo
    [C_ID .. 102] = "Матусина пляшечка для пігулок", -- Mom's Bottle of Pills
    [C_ID .. 103] = "Застуда", -- The Common Cold
    [C_ID .. 104] = "Паразит", -- The Parasite
    [C_ID .. 105] = "D6", -- The D6
    [C_ID .. 106] = "Містер Мега", -- Mr. Mega
    [C_ID .. 107] = "Зубчасті ножиці", -- The Pinking Shears
    [C_ID .. 108] = "Проскура", -- The Wafer
    [C_ID .. 109] = "Гроші = Сила", -- Money = Power
    [C_ID .. 110] = "Матусині Лінзи", -- Mom's Contacts
    [C_ID .. 111] = "Біб", -- The Bean
    [C_ID .. 112] = "Ангел-Охоронець", -- Guardian Angel
    [C_ID .. 113] = "Малюк Диявол", -- Demon Baby
    [C_ID .. 114] = "Матусин ніж", -- Mom's Knife
    [C_ID .. 115] = "Дошка Уіджа", -- Ouija Board
    [C_ID .. 116] = "9 Вольтів", -- 9 Volt
    [C_ID .. 117] = "Мертвий птах", -- Dead Bird
    [C_ID .. 118] = "Сірка", -- Brimstone
    [C_ID .. 119] = "Мішок крові", -- Blood Bag
    [C_ID .. 120] = "Дивний гриб (Тонкий)", -- Odd Mushroom (Thin)
    [C_ID .. 121] = "Дивний Гриб (Великий)", -- Odd Mushroom (Large)
    [C_ID .. 122] = "Вавилонська повія", -- Whore of Babylon
    [C_ID .. 123] = "Книга Монстрів", -- Monster Manual
    [C_ID .. 124] = "Сувої Мертвого моря", -- Dead Sea Scrolls
    [C_ID .. 125] = "Боббі-бомба", -- Bobby-Bomb
    [C_ID .. 126] = "Лезо бритви", -- Razor Blade
    [C_ID .. 127] = "Забудь мене зараз", -- Forget Me Now
    [C_ID .. 128] = "Навіки самотній", -- Forever Alone
    [C_ID .. 129] = "Відро Смальцю", -- Bucket of Lard
    [C_ID .. 130] = "Поні", -- A Pony
    [C_ID .. 131] = "Сумка з бомбами", -- Bomb Bag
    [C_ID .. 132] = "Кусок вугілля", -- A Lump of Coal
    [C_ID .. 133] = "Лапка Гаппі", -- Guppy's Paw
    [C_ID .. 134] = "Хвіст Гаппі", -- Guppy's Tail
    [C_ID .. 135] = "Крапельниця", -- IV Bag
    [C_ID .. 136] = "Найкращий друг", -- Best Friend
    [C_ID .. 137] = "Дистанційний детонатор", -- Remote Detonator
    [C_ID .. 138] = "Стигма", -- Stigmata
    [C_ID .. 139] = "Матусин Гаманець", -- Mom's Purse
    [C_ID .. 140] = "Прокляття Боба", -- Bob's Curse
    [C_ID .. 141] = "Видатний хлопчик", -- Pageant Boy
    [C_ID .. 142] = "Скапулярій", -- Scapular
    [C_ID .. 143] = "Спідбол", -- Speed Ball
    [C_ID .. 144] = "Друг-жебрак", -- Bum Friend
    [C_ID .. 145] = "Голова Гаппі", -- Guppy's Head
    [C_ID .. 146] = "Молитовна картка", -- Prayer Card
    [C_ID .. 147] = "Вищерблене Кайло", -- Notched Axe
    [C_ID .. 148] = "Зараження", -- Infestation
    [C_ID .. 149] = "Іпекак", -- Ipecac
    [C_ID .. 150] = "Жорстока любов", -- Tough Love
    [C_ID .. 151] = "Маліган", -- The Mulligan
    [C_ID .. 152] = "Технологія 2", -- Technology 2
    [C_ID .. 153] = "Павук-Мутант", -- Mutant Spider
    [C_ID .. 154] = "Хімічний опік", -- Chemical Peel
    [C_ID .. 155] = "Споглядач", -- The Peeper
    [C_ID .. 156] = "Ряса", -- Habit
    [C_ID .. 157] = "Кривава жага", -- Bloody Lust
    [C_ID .. 158] = "Кришталева Куля", -- Crystal Ball
    [C_ID .. 159] = "Дух ночі", -- Spirit of the Night
    [C_ID .. 160] = "Розколи небеса", -- Crack the Sky
    [C_ID .. 161] = "Анкх", -- Ankh
    [C_ID .. 162] = "Кельтський хрест", -- Celtic Cross
    [C_ID .. 163] = "Дитина-привид", -- Ghost Baby
    [C_ID .. 164] = "Свічка", -- The Candle
    [C_ID .. 165] = "Дев'ятихвоста кішка", -- Cat-o-nine-tails
    [C_ID .. 166] = "D20", -- D20
    [C_ID .. 167] = "Малюк Арлекін", -- Harlequin Baby
    [C_ID .. 168] = "Епічний Зародок", -- Epic Fetus
    [C_ID .. 169] = "Поліфем", -- Polyphemus
    [C_ID .. 170] = "Довгоногий татусь", -- Daddy Longlegs
    [C_ID .. 171] = "Павуча Дупка", -- Spider Butt
    [C_ID .. 172] = "Жертовний Клинок", -- Sacrificial Dagger
    [C_ID .. 173] = "Митра", -- Mitre
    [C_ID .. 174] = "Веселковий малюк", -- Rainbow Baby
    [C_ID .. 175] = "Татусів ключ", -- Dad's Key
    [C_ID .. 176] = "Стовбурові Клітини", -- Stem Cells
    [C_ID .. 177] = "Переносний автомат", -- Portable Slot
    [C_ID .. 178] = "Свята Вода", -- Holy Water
    [C_ID .. 179] = "Доля", -- Fate
    [C_ID .. 180] = "Чорна квасоля", -- The Black Bean
    [C_ID .. 181] = "Білий поні", -- White Pony
    [C_ID .. 182] = "Святе Серце", -- Sacred Heart
    [C_ID .. 183] = "Зубочистки", -- Tooth Picks
    [C_ID .. 184] = "Святий Грааль", -- Holy Grail
    [C_ID .. 185] = "Мертвий голуб", -- Dead Dove
    [C_ID .. 186] = "Криваві права", -- Blood Rights
    [C_ID .. 187] = "Клубок шерсті Гаппі", -- Guppy's Hairball
    [C_ID .. 188] = "Авель", -- Abel
    [C_ID .. 189] = "Суперфанат SMB!", -- SMB Super Fan
    [C_ID .. 190] = "Пайро", -- Pyro
    [C_ID .. 191] = "Тридоларова купюра", -- 3 Dollar Bill
    [C_ID .. 192] = "Телепатія для Чайників", -- Telepathy for Dummies
    [C_ID .. 193] = "М'ЯСО!", -- MEAT!
    [C_ID .. 194] = "Чарівна Куля 8", -- Magic 8 Ball
    [C_ID .. 195] = "Матусин гаманець", -- Mom's Coin Purse
    [C_ID .. 196] = "Стискання", -- Squeezy
    [C_ID .. 197] = "Йсусів Сік", -- Jesus Juice
    [C_ID .. 198] = "Коробка", -- Box
    [C_ID .. 199] = "Матусин ключ", -- Mom's Key
    [C_ID .. 200] = "Матусині тіні", -- Mom's Eyeshadow
    [C_ID .. 201] = "Залізний зливок", -- Iron Bar
    [C_ID .. 202] = "Дотик Мідаса", -- Midas' Touch
    [C_ID .. 203] = "Скромний Згорток", -- Humbleing Bundle
    [C_ID .. 204] = "Поясна сумка", -- Fanny Pack
    [C_ID .. 205] = "Гострий Штекер", -- Sharp Plug
    [C_ID .. 206] = "Гільйотина", -- Guillotine
    [C_ID .. 207] = "Клубок бинтів", -- Ball of Bandages
    [C_ID .. 208] = "Чемпіонський пояс", -- Champion Belt
    [C_ID .. 209] = "Дупні бомби", -- Butt Bombs
    [C_ID .. 210] = "Покусаний листочок", -- Gnawed Leaf
    [C_ID .. 211] = "Павучок", -- Spiderbaby
    [C_ID .. 212] = "Нашийник Гаппі", -- Guppy's Collar
    [C_ID .. 213] = "Втрачена лінза", -- Lost Contact
    [C_ID .. 214] = "Анемія", -- Anemic
    [C_ID .. 215] = "Голова козла", -- Goat Head
    [C_ID .. 216] = "Церемоніальна мантія", -- Ceremonial Robes
    [C_ID .. 217] = "Матусина перука", -- Mom's Wig
    [C_ID .. 218] = "Плацента", -- Placenta
    [C_ID .. 219] = "Стара пов'язка", -- Old Bandage
    [C_ID .. 220] = "Плаксиві бомби", -- Sad Bombs
    [C_ID .. 221] = "Гумовий клей", -- Rubber Cement
    [C_ID .. 222] = "Антигравітація", -- Anti-Gravity
    [C_ID .. 223] = "Піроманіяк", -- Pyromaniac
    [C_ID .. 224] = "Тіло Крікета", -- Cricket's Body
    [C_ID .. 225] = "Покора", -- Gimpy
    [C_ID .. 226] = "Чорний лотос", -- Black Lotus
    [C_ID .. 227] = "Свинка-скарбничка", -- Piggy Bank
    [C_ID .. 228] = "Матусині Парфуми", -- Mom's Perfume
    [C_ID .. 229] = "Легеня Монстро", -- Monstro's Lung
    [C_ID .. 230] = "Абаддон", -- Abaddon
    [C_ID .. 231] = "Куля з дьогтю", -- Ball of Tar
    [C_ID .. 232] = "Секундомір", -- Stop Watch
    [C_ID .. 233] = "Крихітна Планета", -- Tiny Planet
    [C_ID .. 234] = "Зараження 2", -- Infestation 2
    [C_ID .. 235] = "", -- 
    [C_ID .. 236] = "Кишкова паличка", -- E. Coli
    [C_ID .. 237] = "Дотик смерті", -- Death's Touch
    [C_ID .. 238] = "1 частина ключа", -- Key Piece 1
    [C_ID .. 239] = "2 частина ключа", -- Key Piece 2
    [C_ID .. 240] = "Експериментальне лікування", -- Experimental Treatment
    [C_ID .. 241] = "Контракт знизу", -- Contract from Below
    [C_ID .. 242] = "Безславність", -- Infamy
    [C_ID .. 243] = "Трисвятий щит", -- Trinity Shield
    [C_ID .. 244] = "Технологія 0.5", -- Tech.5
    [C_ID .. 245] = "20/20", -- 20/20
    [C_ID .. 246] = "Синя карта", -- Blue Map
    [C_ID .. 247] = "Найкращі друзі назавжди!", -- BFFS!
    [C_ID .. 248] = "Вуликовий Розум", -- Hive Mind
    [C_ID .. 249] = "У тебе є вибір", -- There's Options
    [C_ID .. 250] = "Подвійні бомби", -- Bogo Bombs
    [C_ID .. 251] = "Стартова колода", -- Starter Deck
    [C_ID .. 252] = "Маленький мішечок", -- Little Baggy
    [C_ID .. 253] = "Чарівний Струп", -- Magic Scab
    [C_ID .. 254] = "Згусток Крові", -- Blood Clot
    [C_ID .. 255] = "Гвинт", -- Screw
    [C_ID .. 256] = "Гарячі Бомби", -- Hot Bombs
    [C_ID .. 257] = "Вогняні думки", -- Fire Mind
    [C_ID .. 258] = "Загублений біт", -- Missing No.
    [C_ID .. 259] = "Чорна матерія", -- Dark Matter
    [C_ID .. 260] = "Чорна свічка", -- Black Candle
    [C_ID .. 261] = "Проптоз", -- Proptosis
    [C_ID .. 262] = "Втрачена сторінка 2", -- Missing Page 2
    [C_ID .. 263] = "Чиста руна", -- Clear Rune
    [C_ID .. 264] = "Розумна мушка", -- Smart Fly
    [C_ID .. 265] = "Висушене дитя", -- Dry Baby
    [C_ID .. 266] = "Соковитий мішечок", -- Juicy Sack
    [C_ID .. 267] = "Робо-дитя 2.0", -- Robo-Baby 2.0
    [C_ID .. 268] = "Гниле дитя", -- Rotten Baby
    [C_ID .. 269] = "Безголове дитя", -- Headless Baby
    [C_ID .. 270] = "П'явка", -- Leech
    [C_ID .. 271] = "Загадковий мішечок", -- Mystery Sack
    [C_ID .. 272] = "ВЧМ", -- BBF
    [C_ID .. 273] = "Мозок Боба", -- Bob's Brain
    [C_ID .. 274] = "Найкращий друг", -- Best Bud
    [C_ID .. 275] = "Сірчаний крихітка", -- Lil Brimstone
    [C_ID .. 276] = "Серце Ісаака", -- Isaac's Heart
    [C_ID .. 277] = "Крихітний привид", -- Lil Haunt
    [C_ID .. 278] = "Темний жебрак", -- Dark Bum
    [C_ID .. 279] = "Великий фанат", -- Big Fan
    [C_ID .. 280] = "Сісся Довгоногий", -- Sissy Longlegs
    [C_ID .. 281] = "Боксерська груша", -- Punching Bag
    [C_ID .. 282] = "Як правильно стрибати", -- How to Jump
    [C_ID .. 283] = "D100", -- D100
    [C_ID .. 284] = "D4", -- D4
    [C_ID .. 285] = "D10", -- D10
    [C_ID .. 286] = "Порожня карта", -- Blank Card
    [C_ID .. 287] = "Книга Таїнств", -- Book of Secrets
    [C_ID .. 288] = "Коробка з павуками", -- Box of Spiders
    [C_ID .. 289] = "Червона свічка", -- Red Candle
    [C_ID .. 290] = "Банка", -- The Jar
    [C_ID .. 291] = "Злив!", -- Flush!
    [C_ID .. 292] = "Сатанинська біблія", -- Satanic Bible
    [C_ID .. 293] = "Голова Крампуса", -- Head of Krampus
    [C_ID .. 294] = "Масляний біб", -- Butter Bean
    [C_ID .. 295] = "Чарівні пальчики", -- Magic Fingers
    [C_ID .. 296] = "Перетворювач", -- Converter
    [C_ID .. 297] = "Скринька Пандори", -- Pandora's Box
    [C_ID .. 298] = "Копито Єдинорога", -- Unicorn Stump
    [C_ID .. 299] = "Телець", -- Taurus
    [C_ID .. 300] = "Овен", -- Aries
    [C_ID .. 301] = "Рак", -- Cancer
    [C_ID .. 302] = "Лев", -- Leo
    [C_ID .. 303] = "Діва", -- Virgo
    [C_ID .. 304] = "Терези", -- Libra
    [C_ID .. 305] = "Скорпіон", -- Scorpio
    [C_ID .. 306] = "Стрілець", -- Sagittarius
    [C_ID .. 307] = "Козоріг", -- Capricorn
    [C_ID .. 308] = "Водолій", -- Aquarius
    [C_ID .. 309] = "Риби", -- Pisces
    [C_ID .. 310] = "Туш Єви", -- Eve's Mascara
    [C_ID .. 311] = "Тінь Юди", -- Judas' Shadow
    [C_ID .. 312] = "Бантик Меггі", -- Maggy's Bow
    [C_ID .. 313] = "Свята мантія", -- Holy Mantle
    [C_ID .. 314] = "Громові стегна", -- Thunder Thighs
    [C_ID .. 315] = "Дивна принада", -- Strange Attractor
    [C_ID .. 316] = "Прокляте око", -- Cursed Eye
    [C_ID .. 317] = "Загадкова рідина", -- Mysterious Liquid
    [C_ID .. 318] = "Близнюки", -- Gemini
    [C_ID .. 319] = "Інше око Каїна", -- Cain's Other Eye
    [C_ID .. 320] = "Єдиний друг ???", -- ???'s Only Friend
    [C_ID .. 321] = "Кайдани Самсона", -- Samson's Chains
    [C_ID .. 322] = "Дитя Монго", -- Mongo Baby
    [C_ID .. 323] = "Сльози Ісаака", -- Isaac's Tears
    [C_ID .. 324] = "Невизначено", -- Undefined
    [C_ID .. 325] = "Ножиці", -- Scissors
    [C_ID .. 326] = "Подих життя", -- Breath of Life
    [C_ID .. 327] = "Полароїд", -- The Polaroid
    [C_ID .. 328] = "Негатив", -- The Negative
    [C_ID .. 329] = "Технологія Людовіко", -- The Ludovico Technique
    [C_ID .. 330] = "Соєве молоко", -- Soy Milk
    [C_ID .. 331] = "Божество", -- Godhead
    [C_ID .. 332] = "Ганчір'я Лазаря", -- Lazarus' Rags
    [C_ID .. 333] = "Розум", -- The Mind
    [C_ID .. 334] = "Тіло", -- The Body
    [C_ID .. 335] = "Душа", -- The Soul
    [C_ID .. 336] = "Гнила цибуля", -- Dead Onion
    [C_ID .. 337] = "Зламаний секундомір", -- Broken Watch
    [C_ID .. 338] = "Бумеранг", -- The Boomerang
    [C_ID .. 339] = "Безпечна шпилька", -- Safety Pin
    [C_ID .. 340] = "Кофеїнова пігулка", -- Caffeine Pill
    [C_ID .. 341] = "Розірване фото", -- Torn Photo
    [C_ID .. 342] = "Синя шапочка", -- Blue Cap
    [C_ID .. 343] = "Запасний ключ", -- Latch Key
    [C_ID .. 344] = "Сірникова коробка", -- Match Book
    [C_ID .. 345] = "Синтол", -- Synthoil
    [C_ID .. 346] = "Перекус", -- A Snack
    [C_ID .. 347] = "Диплопія", -- Diplopia
    [C_ID .. 348] = "Плацебо", -- Placebo
    [C_ID .. 349] = "Дерев'яний нікель", -- Wooden Nickel
    [C_ID .. 350] = "Токсичний шок", -- Toxic Shock
    [C_ID .. 351] = "Мега біб", -- Mega Bean
    [C_ID .. 352] = "Скляна гармата", -- Glass Cannon
    [C_ID .. 353] = "Хлопчик-Підривник", -- Bomber Boy
    [C_ID .. 354] = "Хрусткий Джек", -- Crack Jacks
    [C_ID .. 355] = "Матусине намисто", -- Mom's Pearls
    [C_ID .. 356] = "Автомобільний акумулятор", -- Car Battery
    [C_ID .. 357] = "Коробка з друзями", -- Box of Friends
    [C_ID .. 358] = "Чаклун", -- The Wiz
    [C_ID .. 359] = "8-дюймові цвяхи", -- 8 Inch Nails
    [C_ID .. 360] = "Інкуб", -- Incubus
    [C_ID .. 361] = "Нагорода долі", -- Fate's Reward
    [C_ID .. 362] = "Крихітна скринька", -- Lil Chest
    [C_ID .. 363] = "Затятий захисник", -- Sworn Protector
    [C_ID .. 364] = "Френдзона", -- Friend Zone
    [C_ID .. 365] = "Розгублена муха", -- Lost Fly
    [C_ID .. 366] = "Розкидні бомби", -- Scatter Bombs
    [C_ID .. 367] = "Липкі бомби", -- Sticky Bombs
    [C_ID .. 368] = "Епіфора", -- Epiphora
    [C_ID .. 369] = "Континуум", -- Continuum
    [C_ID .. 370] = "Містер Лялька", -- Mr. Dolly
    [C_ID .. 371] = "Прокляття вежі", -- Curse of the Tower
    [C_ID .. 372] = "Заряджене дитя", -- Charged Baby
    [C_ID .. 373] = "Мертве око", -- Dead Eye
    [C_ID .. 374] = "Святе світло", -- Holy Light
    [C_ID .. 375] = "Капелюх Господаря", -- Host Hat
    [C_ID .. 376] = "Поповнення", -- Restock
    [C_ID .. 377] = "Розірваний кокон", -- Bursting Sack
    [C_ID .. 378] = "Номер 2", -- No. 2
    [C_ID .. 379] = "Роздвоєні зіниці", -- Pupula Duplex
    [C_ID .. 380] = "Плати і грай", -- Pay To Play
    [C_ID .. 381] = "Едемове благословення", -- Eden's Blessing
    [C_ID .. 382] = "Дружній м'яч", -- Friendly Ball
    [C_ID .. 383] = "Підривник сліз", -- Tear Detonator
    [C_ID .. 384] = "Крихітка Гарді", -- Lil Gurdy
    [C_ID .. 385] = "Жебрало", -- Bumbo
    [C_ID .. 386] = "D12", -- D12
    [C_ID .. 387] = "Кадило", -- Censer
    [C_ID .. 388] = "Жебрак-ключник", -- Key Bum
    [C_ID .. 389] = "Мішечок для рун", -- Rune Bag
    [C_ID .. 390] = "Серафим", -- Seraphim
    [C_ID .. 391] = "Зрадник", -- Betrayal
    [C_ID .. 392] = "Зодіак", -- Zodiac
    [C_ID .. 393] = "Зміїний поцілунок", -- Serpent's Kiss
    [C_ID .. 394] = "Мічений", -- Marked
    [C_ID .. 395] = "Технологія X", -- Tech X
    [C_ID .. 396] = "Наскрізне лезо", -- Ventricle Razor
    [C_ID .. 397] = "Промінь тягача", -- Tractor Beam
    [C_ID .. 398] = "Божественна плоть", -- God's Flesh
    [C_ID .. 399] = "Паща Порожнечі", -- Maw of the Void
    [C_ID .. 400] = "Спис Долі", -- Spear of Destiny
    [C_ID .. 401] = "Вибухівчик", -- Explosivo
    [C_ID .. 402] = "Хаос", -- Chaos
    [C_ID .. 403] = "Робо-павук", -- Spider Mod
    [C_ID .. 404] = "Малюк Пердун", -- Farting Baby
    [C_ID .. 405] = "Ігровий баг", -- GB Bug
    [C_ID .. 406] = "D8", -- D8
    [C_ID .. 407] = "Чистота", -- Purity
    [C_ID .. 408] = "Атаме", -- Athame
    [C_ID .. 409] = "Пуста посудина", -- Empty Vessel
    [C_ID .. 410] = "Зле око", -- Evil Eye
    [C_ID .. 411] = "Ненаситна кров", -- Lusty Blood
    [C_ID .. 412] = "Демонічне зачаття", -- Cambion Conception
    [C_ID .. 413] = "Непорочне зачаття", -- Immaculate Conception
    [C_ID .. 414] = "Більше можливостей", -- More Options
    [C_ID .. 415] = "Світлова корона", -- Crown Of Light
    [C_ID .. 416] = "Глибокі кишені", -- Deep Pockets
    [C_ID .. 417] = "Сукуб", -- Succubus
    [C_ID .. 418] = "Фруктовий пиріг", -- Fruit Cake
    [C_ID .. 419] = "Телепорт 2.0", -- Teleport 2.0
    [C_ID .. 420] = "Чорний порошок", -- Black Powder
    [C_ID .. 421] = "Квасоля", -- Kidney Bean
    [C_ID .. 422] = "Сяйливий годинник", -- Glowing Hourglass
    [C_ID .. 423] = "Захисне коло", -- Circle of Protection
    [C_ID .. 424] = "Голова-мішок", -- Sack Head
    [C_ID .. 425] = "Нічник", -- Night Light
    [C_ID .. 426] = "Закоханий фанат", -- Obsessed Fan
    [C_ID .. 427] = "Шахтарська вибухівка", -- Mine Crafter
    [C_ID .. 428] = "Піжама", -- PJs
    [C_ID .. 429] = "Голова Хранителя", -- Head of the Keeper
    [C_ID .. 430] = "Татусь Муха", -- Papa Fly
    [C_ID .. 431] = "Міжвимірне дитя", -- Multidimensional Baby
    [C_ID .. 432] = "Блискучі бомби", -- Glitter Bombs
    [C_ID .. 433] = "Моя тінь", -- My Shadow
    [C_ID .. 434] = "Банка з мухами", -- Jar of Flies
    [C_ID .. 435] = "Крихітка Локі", -- Lil Loki
    [C_ID .. 436] = "Молоко!", -- Milk!
    [C_ID .. 437] = "D7", -- D7
    [C_ID .. 438] = "Пипка", -- Binky
    [C_ID .. 439] = "Матусина коробка", -- Mom's Box
    [C_ID .. 440] = "Нирковий камінь", -- Kidney Stone
    [C_ID .. 441] = "Мегазаряд", -- Mega Blast
    [C_ID .. 442] = "Корона Темного Принца", -- Dark Prince's Crown
    [C_ID .. 443] = "Яблуко!", -- Apple!
    [C_ID .. 444] = "Графітовий олівець", -- Lead Pencil
    [C_ID .. 445] = "Собачий зуб", -- Dog Tooth
    [C_ID .. 446] = "Мертвий зуб", -- Dead Tooth
    [C_ID .. 447] = "Довгий біб", -- Linger Bean
    [C_ID .. 448] = "Кусок скла", -- Shard of Glass
    [C_ID .. 449] = "Металева пластина", -- Metal Plate
    [C_ID .. 450] = "Око Жадібності", -- Eye of Greed
    [C_ID .. 451] = "Сукно таро", -- Tarot Cloth
    [C_ID .. 452] = "Варикозні вени", -- Varicose Veins
    [C_ID .. 453] = "Перелом", -- Compound Fracture
    [C_ID .. 454] = "Полідактилія", -- Polydactyly
    [C_ID .. 455] = "Татусева втрачена монета", -- Dad's Lost Coin
    [C_ID .. 456] = "Опівнічний перекус", -- Midnight Snack
    [C_ID .. 457] = "Яйцеголовий", -- Cone Head
    [C_ID .. 458] = "Пупок", -- Belly Button
    [C_ID .. 459] = "Синусит", -- Sinus Infection
    [C_ID .. 460] = "Глаукома", -- Glaucoma
    [C_ID .. 461] = "Паразитоїд", -- Parasitoid
    [C_ID .. 462] = "Око Беліала", -- Eye of Belial
    [C_ID .. 463] = "Сульфатна кислота", -- Sulfuric Acid
    [C_ID .. 464] = "Гліф рівноваги", -- Glyph of Balance
    [C_ID .. 465] = "Аналоговий джойстик", -- Analog Stick
    [C_ID .. 466] = "Зараза", -- Contagion
    [C_ID .. 467] = "Пальчик!", -- Finger!
    [C_ID .. 468] = "Тінь", -- Shade
    [C_ID .. 469] = "Депресія", -- Depression
    [C_ID .. 470] = "Мовчун", -- Hushy
    [C_ID .. 471] = "Крихітка Монстро", -- Lil Monstro
    [C_ID .. 472] = "Дитя Король", -- King Baby
    [C_ID .. 473] = "Великий Чаббі", -- Big Chubby
    [C_ID .. 474] = "Розбита скляна гармата", -- Broken Glass Cannon
    [C_ID .. 475] = "План C", -- Plan C
    [C_ID .. 476] = "D1", -- D1
    [C_ID .. 477] = "Порожнеча", -- Void
    [C_ID .. 478] = "Пауза", -- Pause
    [C_ID .. 479] = "Плавильня", -- Smelter
    [C_ID .. 480] = "Компост", -- Compost
    [C_ID .. 481] = "Датамайнер", -- Dataminer
    [C_ID .. 482] = "Клікер", -- Clicker
    [C_ID .. 483] = "Мама Мега!", -- Mama Mega!
    [C_ID .. 484] = "Стривай, що?", -- Wait What?
    [C_ID .. 485] = "Зігнутий пенні", -- Crooked Penny
    [C_ID .. 486] = "Тупе лезо", -- Dull Razor
    [C_ID .. 487] = "Картоплечистка", -- Potato Peeler
    [C_ID .. 488] = "Метроном", -- Metronome
    [C_ID .. 489] = "D Безмежність", -- D Infinity
    [C_ID .. 490] = "Едемова душа", -- Eden's Soul
    [C_ID .. 491] = "Кислотне дитя", -- Acid Baby
    [C_ID .. 492] = "ХЕЙ, СЛУХАЙ!", -- YO LISTEN!
    [C_ID .. 493] = "Адреналін", -- Adrenaline
    [C_ID .. 494] = "Драбина Якова", -- Jacob's Ladder
    [C_ID .. 495] = "Перець-привид", -- Ghost Pepper
    [C_ID .. 496] = "Евтаназія", -- Euthanasia
    [C_ID .. 497] = "Камуфляжні труси", -- Camo Undies
    [C_ID .. 498] = "Подвійність", -- Duality
    [C_ID .. 499] = "Євхаристія", -- Eucharist
    [C_ID .. 500] = "Мішечок монет", -- Sack of Sacks
    [C_ID .. 501] = "Стравохід Жадібності", -- Greed's Gullet
    [C_ID .. 502] = "Гігантський прищ", -- Large Zit
    [C_ID .. 503] = "Маленький Ріг", -- Little Horn
    [C_ID .. 504] = "Коричневий самородок", -- Brown Nugget
    [C_ID .. 505] = "Покемончик", -- Poke Go
    [C_ID .. 506] = "І ти, Бруте?", -- Backstabber
    [C_ID .. 507] = "Гостра соломинка", -- Sharp Straw
    [C_ID .. 508] = "Матусина бритва", -- Mom's Razor
    [C_ID .. 509] = "Криваве око", -- Bloodshot Eye
    [C_ID .. 510] = "Несамовитий", -- Delirious
    [C_ID .. 511] = "Розлючена муха", -- Angry Fly
    [C_ID .. 512] = "Чорна діра", -- Black Hole
    [C_ID .. 513] = "Бозо", -- Bozo
    [C_ID .. 514] = "Зламаний модем", -- Broken Modem
    [C_ID .. 515] = "Загадковий подарунок", -- Mystery Gift
    [C_ID .. 516] = "Зрошувач", -- Sprinkler
    [C_ID .. 517] = "Швидкі бомби", -- Fast Bombs
    [C_ID .. 518] = "Друзяка в коробці", -- Buddy in a Box
    [C_ID .. 519] = "Крихітка Делліріум", -- Lil Delirium
    [C_ID .. 520] = "Кабель-перемичка", -- Jumper Cables
    [C_ID .. 521] = "Купон", -- Coupon
    [C_ID .. 522] = "Телекінез", -- Telekinesis
    [C_ID .. 523] = "Коробка для перенесень", -- Moving Box
    [C_ID .. 524] = "Технологія Нуль", -- Technology Zero
    [C_ID .. 525] = "Проказа", -- Leprosy
    [C_ID .. 526] = "7 Печаток", -- 7 Seals
    [C_ID .. 527] = "Містер Я!", -- Mr. ME!
    [C_ID .. 528] = "Ангельська призма", -- Angelic Prism
    [C_ID .. 529] = "Хлюп!", -- Pop!
    [C_ID .. 530] = "Список смерті", -- Death's List
    [C_ID .. 531] = "Гемолакрія", -- Haemolacria
    [C_ID .. 532] = "Сльозотеча", -- Lachryphagy
    [C_ID .. 533] = "Трисвяте", -- Trisagion
    [C_ID .. 534] = "Рюкзак", -- Schoolbag
    [C_ID .. 535] = "Ковдра", -- Blanket
    [C_ID .. 536] = "Вівтар для жертвопринесень", -- Sacrificial Altar
    [C_ID .. 537] = "Крихітка Ригачка", -- Lil Spewer
    [C_ID .. 538] = "Камінці", -- Marbles
    [C_ID .. 539] = "Загадкове яйце", -- Mystery Egg
    [C_ID .. 540] = "Плаский камінь", -- Flat Stone
    [C_ID .. 541] = "Кістковий мозок", -- Marrow
    [C_ID .. 542] = "Зміщене ребро", -- Slipped Rib
    [C_ID .. 543] = "Свята земля", -- Hallowed Ground
    [C_ID .. 544] = "Загострене ребро", -- Pointy Rib
    [C_ID .. 545] = "Книга Мертвих", -- Book of the Dead
    [C_ID .. 546] = "Татусеве кільце", -- Dad's Ring
    [C_ID .. 547] = "Документи про розлучення", -- Divorce Papers
    [C_ID .. 548] = "Щелепна кістка", -- Jaw Bone
    [C_ID .. 549] = "Крихкі кістки", -- Brittle Bones
    [C_ID .. 550] = "Зламана лопата", -- Broken Shovel
    [C_ID .. 551] = "Зламана лопата", -- Broken Shovel
    [C_ID .. 552] = "Матусина лопата", -- Mom's Shovel
    [C_ID .. 553] = "Мукормікоз", -- Mucormycosis
    [C_ID .. 554] = "Страшко", -- 2Spooky
    [C_ID .. 555] = "Золота бритва", -- Golden Razor
    [C_ID .. 556] = "Сульфур", -- Sulfur
    [C_ID .. 557] = "Печиво з передбаченнями", -- Fortune Cookie
    [C_ID .. 558] = "Окаїстий", -- Eye Sore
    [C_ID .. 559] = "120 Вольт", -- 120 Volt
    [C_ID .. 560] = "Болить!", -- It Hurts
    [C_ID .. 561] = "Мигдалеве молоко", -- Almond Milk
    [C_ID .. 562] = "Кам'яне дно", -- Rock Bottom
    [C_ID .. 563] = "Гарненькі бомбочки", -- Nancy Bombs
    [C_ID .. 564] = "Кусок мила", -- A Bar of Soap
    [C_ID .. 565] = "Кривавий цуцик", -- Blood Puppy
    [C_ID .. 566] = "Ловець снів", -- Dream Catcher
    [C_ID .. 567] = "Пасхальна свічка", -- Paschal Candle
    [C_ID .. 568] = "Божественне втручання", -- Divine Intervention
    [C_ID .. 569] = "Присяга на крові", -- Blood Oath
    [C_ID .. 570] = "Пластилінове печиво", -- Playdough Cookie
    [C_ID .. 571] = "Сирітські шкарпетки", -- Orphan Socks
    [C_ID .. 572] = "Окультне око", -- Eye of the Occult
    [C_ID .. 573] = "Бездоганне серце", -- Immaculate Heart
    [C_ID .. 574] = "Дароносиця", -- Monstrance
    [C_ID .. 575] = "Загарбник", -- The Intruder
    [C_ID .. 576] = "Брудні думки", -- Dirty Mind
    [C_ID .. 577] = "Дамокл", -- Damocles
    [C_ID .. 578] = "Безкоштовний лимонад", -- Free Lemonade
    [C_ID .. 579] = "Меч Духа", -- Spirit Sword
    [C_ID .. 580] = "Червоний ключ", -- Red Key
    [C_ID .. 581] = "Психо-Муха", -- Psy Fly
    [C_ID .. 582] = "Хвиляста шапочка", -- Wavy Cap
    [C_ID .. 583] = "Ракета в банці", -- Rocket in a Jar
    [C_ID .. 584] = "Книга Чеснот", -- Book of Virtues
    [C_ID .. 585] = "Алебастрова скринька", -- Alabaster Box
    [C_ID .. 586] = "Сходи", -- The Stairway
    [C_ID .. 587] = "Менора (Не використовується, але заскриптовано)", -- 
    [C_ID .. 588] = "Сонце", -- Sol
    [C_ID .. 589] = "Місяць", -- Luna
    [C_ID .. 590] = "Меркурій", -- Mercurius
    [C_ID .. 591] = "Венера", -- Venus
    [C_ID .. 592] = "Земля", -- Terra
    [C_ID .. 593] = "Марс", -- Mars
    [C_ID .. 594] = "Юпітер", -- Jupiter
    [C_ID .. 595] = "Сатурн", -- Saturnus
    [C_ID .. 596] = "Уран", -- Uranus
    [C_ID .. 597] = "Нептун", -- Neptunus
    [C_ID .. 598] = "Плутон", -- Pluto
    [C_ID .. 599] = "Голова вуду", -- Voodoo Head
    [C_ID .. 600] = "Очні краплі", -- Eye Drops
    [C_ID .. 601] = "Каяття", -- Act of Contrition
    [C_ID .. 602] = "Членська карта", -- Member Card
    [C_ID .. 603] = "Акумуляторна батарея", -- Battery Pack
    [C_ID .. 604] = "Матусин браслет", -- Mom's Bracelet
    [C_ID .. 605] = "Колупачка", -- The Scooper
    [C_ID .. 606] = "Очний розлом", -- Ocular Rift
    [C_ID .. 607] = "Чирякове Дитя", -- Boiled Baby
    [C_ID .. 608] = "Морозне Дитя", -- Freezer Baby
    [C_ID .. 609] = "Вічний D6", -- Eternal D6
    [C_ID .. 610] = "Пташина клітка", -- Bird Cage
    [C_ID .. 611] = "Гортань", -- Larynx
    [C_ID .. 612] = "Загублена душа", -- Lost Soul
    [C_ID .. 613] = "", -- 
    [C_ID .. 614] = "Кров'яні бомби", -- Blood Bombs
    [C_ID .. 615] = "Малюк Дампі", -- Lil Dumpy
    [C_ID .. 616] = "Пташине око", -- Bird's Eye
    [C_ID .. 617] = "Магнітна руда", -- Lodestone
    [C_ID .. 618] = "Гнилий томат", -- Rotten Tomato
    [C_ID .. 619] = "Право первородства", -- Birthright
    [C_ID .. 620] = "", -- 
    [C_ID .. 621] = "Червоне рагу", -- Red Stew
    [C_ID .. 622] = "Генезис", -- Genesis
    [C_ID .. 623] = "Гострий ключ", -- Sharp Key
    [C_ID .. 624] = "Бустер-пак", -- Booster Pack
    [C_ID .. 625] = "Мегагриб", -- Mega Mush
    [C_ID .. 626] = "1 частина ножа", -- Knife Piece 1
    [C_ID .. 627] = "2 частина ножа", -- Knife Piece 2
    [C_ID .. 628] = "Свідоцтво про смерть", -- Death Certificate
    [C_ID .. 629] = "Робомуха", -- Bot Fly
    [C_ID .. 630] = "", -- 
    [C_ID .. 631] = "Тесак м'ясника", -- Meat Cleaver
    [C_ID .. 632] = "Амулет зла", -- Evil Charm
    [C_ID .. 633] = "Догма", -- Dogma
    [C_ID .. 634] = "Чистилище", -- Purgatory
    [C_ID .. 635] = "Стібок", -- Stitches
    [C_ID .. 636] = "Клавіша R", -- R Key
    [C_ID .. 637] = "Нокаутні краплі", -- Knockout Drops
    [C_ID .. 638] = "Стирачка", -- Eraser
    [C_ID .. 639] = "Гидотне серце", -- Yuck Heart
    [C_ID .. 640] = "Урна душ", -- Urn of Souls
    [C_ID .. 641] = "Акелдама", -- Akeldama
    [C_ID .. 642] = "Чарівна шкіра", -- Magic Skin
    [C_ID .. 643] = "Одкровення", -- Revelation
    [C_ID .. 644] = "Втішний приз", -- Consolation Prize
    [C_ID .. 645] = "Мінітома", -- Tinytoma
    [C_ID .. 646] = "Сірчані бомби", -- Brimstone Bombs
    [C_ID .. 647] = "4.5 Вольт", -- 4.5 Volt
    [C_ID .. 648] = "", -- 
    [C_ID .. 649] = "Мала Слива", -- Fruity Plum
    [C_ID .. 650] = "Сливова флейта", -- Plum Flute
    [C_ID .. 651] = "Вифлеємська зірка", -- Star of Bethlehem
    [C_ID .. 652] = "Дитя в кубі", -- Cube Baby
    [C_ID .. 653] = "Повернись!", -- Vade Retro
    [C_ID .. 654] = "Фальшивий Доктор Наук", -- False PHD
    [C_ID .. 655] = "Крути, щоб виграти", -- Spin to Win
    [C_ID .. 656] = "Дамокл", -- Damocles
    [C_ID .. 657] = "Васкуліт", -- Vasculitis
    [C_ID .. 658] = "Гігантська клітина", -- Giant Cell
    [C_ID .. 659] = "Тропікамід", -- Tropicamide
    [C_ID .. 660] = "Ворожіння на картах", -- Card Reading
    [C_ID .. 661] = "П'ятірня", -- Quints
    [C_ID .. 662] = "Пацифіст (Видалено)", -- 
    [C_ID .. 663] = "Зуб і цвях", -- Tooth and Nail
    [C_ID .. 664] = "Ненажера", -- Binge Eater
    [C_ID .. 665] = "Око Гаппі", -- Guppy's Eye
    [C_ID .. 666] = "", -- 
    [C_ID .. 667] = "Опудало", -- Strawman
    [C_ID .. 668] = "Записка від батька", -- Dad's Note
    [C_ID .. 669] = "Ковбаска", -- Sausage
    [C_ID .. 670] = "Варіанти?", -- Options?
    [C_ID .. 671] = "Цукеркове серце", -- Candy Heart
    [C_ID .. 672] = "Фунт м'яса", -- A Pound of Flesh
    [C_ID .. 673] = "Спокута", -- Redemption
    [C_ID .. 674] = "Духовні кайдани", -- Spirit Shackles
    [C_ID .. 675] = "Розбита куля", -- Cracked Orb
    [C_ID .. 676] = "Порожнє серце", -- Empty Heart
    [C_ID .. 677] = "Астральна проекція", -- Astral Projection
    [C_ID .. 678] = "Кесарів розтин", -- C Section
    [C_ID .. 679] = "Крихітний Абаддон", -- Lil Abaddon
    [C_ID .. 680] = "Помста Монтезуми", -- Montezuma's Revenge
    [C_ID .. 681] = "Крихітний портал", -- Lil Portal
    [C_ID .. 682] = "Друг Черв'ячок", -- Worm Friend
    [C_ID .. 683] = "Кісткові шпори", -- Bone Spurs
    [C_ID .. 684] = "Голодна душа", -- Hungry Soul
    [C_ID .. 685] = "Банка вогників", -- Jar of Wisps
    [C_ID .. 686] = "Медальйон душі", -- Soul Locket
    [C_ID .. 687] = "Пошук друзів", -- Friend Finder
    [C_ID .. 688] = "Внутрішня дитина", -- Inner Child
    [C_ID .. 689] = "Глючна корона", -- Glitched Crown
    [C_ID .. 690] = "Желейка", -- Belly Jelly
    [C_ID .. 691] = "Священна куля", -- Sacred Orb
    [C_ID .. 692] = "Кривавий зв'язок", -- Sanguine Bond
    [C_ID .. 693] = "Рій", -- The Swarm
    [C_ID .. 694] = "Розрив серця", -- Heartbreak
    [C_ID .. 695] = "Кривавий порив", -- Bloody Gust
    [C_ID .. 696] = "Спасіння", -- Salvation
    [C_ID .. 697] = "Зникаючий близнюк", -- Vanishing Twin
    [C_ID .. 698] = "Химерна парочка", -- Twisted Pair
    [C_ID .. 699] = "Лють Азазеля", -- Azazel's Rage
    [C_ID .. 700] = "Ехокамера", -- Echo Chamber
    [C_ID .. 701] = "Айзекова могила", -- Isaac's Tomb
    [C_ID .. 702] = "Мстивий дух", -- Vengeful Spirit
    [C_ID .. 703] = "Ісав молодший", -- Esau Jr.
    [C_ID .. 704] = "Берсерк!", -- Berserk!
    [C_ID .. 705] = "Темні мистецтва", -- Dark Arts
    [C_ID .. 706] = "Безодня", -- Abyss
    [C_ID .. 707] = "Вечеря", -- Supper
    [C_ID .. 708] = "Степлер", -- Stapler
    [C_ID .. 709] = "Суплекс!", -- Suplex!
    [C_ID .. 710] = "Сумка для рукоділля", -- Bag of Crafting
    [C_ID .. 711] = "Перевернись", -- Flip
    [C_ID .. 712] = "Лемеґетон", -- Lemegeton
    [C_ID .. 713] = "Сумпторіум", -- Sumptorium
    [C_ID .. 714] = "Виклик", -- Recall
    [C_ID .. 715] = "Притримай", -- Hold
    [C_ID .. 716] = "Мішок Хранителя", -- Keeper's Sack
    [C_ID .. 717] = "Рідня Хранителя", -- Keeper's Kin
    [C_ID .. 718] = "Мотузка Хранителя (Вирізано)", -- 
    [C_ID .. 719] = "Коробка Хранителя", -- Keeper's Box
    [C_ID .. 720] = "Банка всього", -- Everything Jar
    [C_ID .. 721] = "ТМТРЕЙНЕР", -- TMTRAINER
    [C_ID .. 722] = "Аніма Сола", -- Anima Sola
    [C_ID .. 723] = "Кубик прокрутки", -- Spindown Dice
    [C_ID .. 724] = "Гіперкоагуляція", -- Hypercoagulation
    [C_ID .. 725] = "СПК", -- IBS
    [C_ID .. 726] = "Кровохаркання", -- Hemoptysis
    [C_ID .. 727] = "Бомби-привиди", -- Ghost Bombs
    [C_ID .. 728] = "Гелло", -- Gello
    [C_ID .. 729] = "Голову з пліч", -- Decap Attack
    [C_ID .. 730] = "Скляне око", -- Glass Eye
    [C_ID .. 731] = "Ячмінь", -- Stye
    [C_ID .. 732] = "Матусине кільце", -- Mom's Ring
}
EID:updateDescriptionsViaTable(collectibles, EID.ItemNames[languageCode])

---------trinkets---------
local trinkets = {
    [T_ID .. 1] = "Проковтнутий пенні", -- Swallowed Penny
    [T_ID .. 2] = "Скам'яніла какашка", -- Petrified Poop
    [T_ID .. 3] = "AAA Батарейка", -- AAA Battery
    [T_ID .. 4] = "Зламаний пульт", -- Broken Remote
    [T_ID .. 5] = "Фіолетове серце", -- Purple Heart
    [T_ID .. 6] = "Зламаний магніт", -- Broken Magnet
    [T_ID .. 7] = "Намистина з вервиці", -- Rosary Bead
    [T_ID .. 8] = "Картридж", -- Cartridge
    [T_ID .. 9] = "Пульсуючий черв", -- Pulse Worm
    [T_ID .. 10] = "Хвилястий черв", -- Wiggle Worm
    [T_ID .. 11] = "Кільчастий черв", -- Ring Worm
    [T_ID .. 12] = "Плаский черв", -- Flat Worm
    [T_ID .. 13] = "Кредит", -- Store Credit
    [T_ID .. 14] = "Мозоль", -- Callus
    [T_ID .. 15] = "Щасливий камінь", -- Lucky Rock
    [T_ID .. 16] = "Матусин ніготь", -- Mom's Toenail
    [T_ID .. 17] = "Чорна помада", -- Black Lipstick
    [T_ID .. 18] = "Біблійний трактат", -- Bible Tract
    [T_ID .. 19] = "Скріпка", -- Paper Clip
    [T_ID .. 20] = "Мавпяча лапа", -- Monkey Paw
    [T_ID .. 21] = "Загадковий листок", -- Mysterious Paper
    [T_ID .. 22] = "Хвіст демона", -- Daemon's Tail
    [T_ID .. 23] = "Загублений плакат", -- Missing Poster
    [T_ID .. 24] = "Дуповий пенні", -- Butt Penny
    [T_ID .. 25] = "Загадкова цукерка", -- Mysterious Candy
    [T_ID .. 26] = "Гаковий черв", -- Hook Worm
    [T_ID .. 27] = "Батоговий черв", -- Whip Worm
    [T_ID .. 28] = "Зламаний хрест", -- Broken Ankh
    [T_ID .. 29] = "Голова риби", -- Fish Head
    [T_ID .. 30] = "Кон'юнктивіт", -- Pinky Eye
    [T_ID .. 31] = "Канцелярська кнопка", -- Push Pin
    [T_ID .. 32] = "Шапка свободи", -- Liberty Cap
    [T_ID .. 33] = "Пуповина", -- Umbilical Cord
    [T_ID .. 34] = "Дитяче серце", -- Child's Heart
    [T_ID .. 35] = "Загнутий ріг", -- Curved Horn
    [T_ID .. 36] = "Іржавий ключ", -- Rusted Key
    [T_ID .. 37] = "Козляча ратиця", -- Goat Hoof
    [T_ID .. 38] = "Матусина перлина", -- Mom's Pearl
    [T_ID .. 39] = "Рак", -- Cancer
    [T_ID .. 40] = "Червона латка", -- Red Patch
    [T_ID .. 41] = "Сірник", -- Match Stick
    [T_ID .. 42] = "Щасливий палець", -- Lucky Toe
    [T_ID .. 43] = "Проклятий череп", -- Cursed Skull
    [T_ID .. 44] = "Захисний ковпачок", -- Safety Cap
    [T_ID .. 45] = "Піковий туз", -- Ace of Spades
    [T_ID .. 46] = "Ісаакова виделка", -- Isaac's Fork
    [T_ID .. 47] = "", -- 
    [T_ID .. 48] = "Загублена сторінка", -- A Missing Page
    [T_ID .. 49] = "Кривавий пенні", -- Bloody Penny
    [T_ID .. 50] = "Спалений пенні", -- Burnt Penny
    [T_ID .. 51] = "Плаский пенні", -- Flat Penny
    [T_ID .. 52] = "Фальшивий пенні", -- Counterfeit Penny
    [T_ID .. 53] = "Кліщ", -- Tick
    [T_ID .. 54] = "Голова Ісаака", -- Isaac's Head
    [T_ID .. 55] = "Віра Меггі", -- Maggy's Faith
    [T_ID .. 56] = "Язик Юди", -- Judas' Tongue
    [T_ID .. 57] = "Душа ???", -- ???'s Soul
    [T_ID .. 58] = "Пасмо волосся Самсона", -- Samson's Lock
    [T_ID .. 59] = "Око Каїна", -- Cain's Eye
    [T_ID .. 60] = "Лапка пташки Єви", -- Eve's Bird Foot
    [T_ID .. 61] = "Ліва рука", -- The Left Hand
    [T_ID .. 62] = "Блискучий камінь", -- Shiny Rock
    [T_ID .. 63] = "Безпечні ножиці", -- Safety Scissors
    [T_ID .. 64] = "Веселковий черв", -- Rainbow Worm
    [T_ID .. 65] = "Стрічковий черв", -- Tape Worm
    [T_ID .. 66] = "Лінивий черв", -- Lazy Worm
    [T_ID .. 67] = "Розбитий ігровий кубик", -- Cracked Dice
    [T_ID .. 68] = "Супермагніт", -- Super Magnet
    [T_ID .. 69] = "Вицвілий полароїд", -- Faded Polaroid
    [T_ID .. 70] = "Воша", -- Louse
    [T_ID .. 71] = "Сечовий міхур Боба", -- Bob's Bladder
    [T_ID .. 72] = "Запасна батарейка", -- Watch Battery
    [T_ID .. 73] = "Вибуховий ковпачок", -- Blasting Cap
    [T_ID .. 74] = "Шукач", -- Stud Finder
    [T_ID .. 75] = "Помилка", -- Error
    [T_ID .. 76] = "Фішка для покеру", -- Poker Chip
    [T_ID .. 77] = "Пухир", -- Blister
    [T_ID .. 78] = "Секундна стрілка", -- Second Hand
    [T_ID .. 79] = "Безіменна нескінченність", -- Endless Nameless
    [T_ID .. 80] = "Чорне Перо", -- Black Feather
    [T_ID .. 81] = "Сліпа лють", -- Blind Rage
    [T_ID .. 82] = "Золота підкова", -- Golden Horse Shoe
    [T_ID .. 83] = "Ключ до магазину", -- Store Key
    [T_ID .. 84] = "Ребро Жадібності", -- Rib of Greed
    [T_ID .. 85] = "Карма", -- Karma
    [T_ID .. 86] = "Крихітна личинка", -- Lil Larva
    [T_ID .. 87] = "Матусин медальйон", -- Mom's Locket
    [T_ID .. 88] = "НІ!", -- NO!
    [T_ID .. 89] = "Дитячий повідок", -- Child Leash
    [T_ID .. 90] = "Коричневий ковпачок", -- Brown Cap
    [T_ID .. 91] = "Меконій", -- Meconium
    [T_ID .. 92] = "Зламана корона", -- Cracked Crown
    [T_ID .. 93] = "Використаний підгузок", -- Used Diaper
    [T_ID .. 94] = "Риб'ячий хвіст", -- Fish Tail
    [T_ID .. 95] = "Чорний зуб", -- Black Tooth
    [T_ID .. 96] = "Черв'як Уроборос", -- Ouroboros Worm
    [T_ID .. 97] = "Мигдалик", -- Tonsil
    [T_ID .. 98] = "Ніс гобліна", -- Nose Goblin
    [T_ID .. 99] = "Пострибунчик", -- Super Ball
    [T_ID .. 100] = "Яскрава лампочка", -- Vibrant Bulb
    [T_ID .. 101] = "Згасла лампа", -- Dim Bulb
    [T_ID .. 102] = "Фрагментована карточка", -- Fragmented Card
    [T_ID .. 103] = "Рівність!", -- Equality!
    [T_ID .. 104] = "Кістка бажань", -- Wish Bone
    [T_ID .. 105] = "Сумка з обідом", -- Bag Lunch
    [T_ID .. 106] = "Втрачений корок", -- Lost Cork
    [T_ID .. 107] = "Серце Ворона", -- Crow Heart
    [T_ID .. 108] = "Волоський горіх", -- Walnut
    [T_ID .. 109] = "Клейка стрічка", -- Duct Tape
    [T_ID .. 110] = "Срібний долар", -- Silver Dollar
    [T_ID .. 111] = "Кривава корона", -- Bloody Crown
    [T_ID .. 112] = "Плати, щоб виграти", -- Pay To Win
    [T_ID .. 113] = "Сарана Війни", -- Locust of War
    [T_ID .. 114] = "Сарана Чуми", -- Locust of Pestilence
    [T_ID .. 115] = "Сарана Голоду", -- Locust of Famine
    [T_ID .. 116] = "Сарана Смерті", -- Locust of Death
    [T_ID .. 117] = "Сарана Завоювання", -- Locust of Conquest
    [T_ID .. 118] = "Кажаняче крило", -- Bat Wing
    [T_ID .. 119] = "Стовбурова клітина", -- Stem Cell
    [T_ID .. 120] = "Шпилька для волосся", -- Hairpin
    [T_ID .. 121] = "Дерев'яний хрест", -- Wooden Cross
    [T_ID .. 122] = "Масло!", -- Butter!
    [T_ID .. 123] = "Філігранне перо", -- Filigree Feather
    [T_ID .. 124] = "Підпірка для дверей", -- Door Stop
    [T_ID .. 125] = "Подовжувач", -- Extension Cord
    [T_ID .. 126] = "Гнилий пенні", -- Rotten Penny
    [T_ID .. 127] = "Дитяча ложка", -- Baby-Bender
    [T_ID .. 128] = "Кістка з пальця", -- Finger Bone
    [T_ID .. 129] = "Щелеполом", -- Jawbreaker
    [T_ID .. 130] = "Пожована ручка", -- Chewed Pen
    [T_ID .. 131] = "Благословенний пенні", -- Blessed Penny
    [T_ID .. 132] = "Зламаний шприц", -- Broken Syringe
    [T_ID .. 133] = "Вкорочений ґніт", -- Short Fuse
    [T_ID .. 134] = "Гігантська квасоля", -- Gigante Bean
    [T_ID .. 135] = "Запальничка", -- A Lighter
    [T_ID .. 136] = "Зламаний замок", -- Broken Padlock
    [T_ID .. 137] = "Міозотія", -- Myosotis
    [T_ID .. 138] = "'M", -- 'M
    [T_ID .. 139] = "Сльозо-амулет", -- Teardrop Charm
    [T_ID .. 140] = "Яблуко Содому", -- Apple of Sodom
    [T_ID .. 141] = "Забута Колискова", -- Forgotten Lullaby
    [T_ID .. 142] = "Віра Бет", -- Beth's Faith
    [T_ID .. 143] = "Cтарий конденсатор", -- Old Capacitor
    [T_ID .. 144] = "Мозковий черв", -- Brain Worm
    [T_ID .. 145] = "Ідеал", -- Perfection
    [T_ID .. 146] = "Корона демона", -- Devil's Crown
    [T_ID .. 147] = "Заряджений пенні", -- Charged Penny
    [T_ID .. 148] = "Намисто дружби", -- Friendship Necklace
    [T_ID .. 149] = "Кнопка тривоги", -- Panic Button
    [T_ID .. 150] = "Синій ключ", -- Blue Key
    [T_ID .. 151] = "Напилок", -- Flat File
    [T_ID .. 152] = "Лінза телескопа", -- Telescope Lens
    [T_ID .. 153] = "Матусин локон", -- Mom's Lock
    [T_ID .. 154] = "Мішок для кубиків", -- Dice Bag
    [T_ID .. 155] = "Свята корона", -- Holy Crown
    [T_ID .. 156] = "Матусин цілунок", -- Mother's Kiss
    [T_ID .. 157] = "Рвана карта", -- Torn Card
    [T_ID .. 158] = "Порвана кишеня", -- Torn Pocket
    [T_ID .. 159] = "Позолочений ключ", -- Gilded Key
    [T_ID .. 160] = "Щасливий мішечок", -- Lucky Sack
    [T_ID .. 161] = "Зла корона", -- Wicked Crown
    [T_ID .. 162] = "Обрубок Азазеля", -- Azazel's Stump
    [T_ID .. 163] = "Какаха", -- Dingle Berry
    [T_ID .. 164] = "Пістон", -- Ring Cap
    [T_ID .. 165] = "Ні-і!", -- Nuh Uh!
    [T_ID .. 166] = "Пластилін", -- Modeling Clay
    [T_ID .. 167] = "Полірована кістка", -- Polished Bone
    [T_ID .. 168] = "Порожнє серце", -- Hollow Heart
    [T_ID .. 169] = "Дитячі малюнки", -- Kid's Drawing
    [T_ID .. 170] = "Кришталевий ключ", -- Crystal Key
    [T_ID .. 171] = "Угода Хранителя", -- Keeper's Bargain
    [T_ID .. 172] = "Проклятий пенні", -- Cursed Penny
    [T_ID .. 173] = "Твій дух", -- Your Soul
    [T_ID .. 174] = "Магніт з цифрами", -- Number Magnet
    [T_ID .. 175] = "Дивний ключ", -- Strange Key
    [T_ID .. 176] = "Малий згусток", -- Lil Clot
    [T_ID .. 177] = "Тимчасове тату", -- Temporary Tattoo
    [T_ID .. 178] = "Проковтнутий M80", -- Swallowed M80
    [T_ID .. 179] = "Пульт дистанційного керування", -- RC Remote
    [T_ID .. 180] = "Знайдена душа", -- Found Soul
    [T_ID .. 181] = "Набір розширень", -- Expansion Pack
    [T_ID .. 182] = "Сутність Бет", -- Beth's Essence
    [T_ID .. 183] = "Близнюки", -- The Twins
    [T_ID .. 184] = "Документи про усиновлення", -- Adoption Papers
    [T_ID .. 185] = "Нога Крікета", -- Cricket Leg
    [T_ID .. 186] = "Найкращий друг Аполліона", -- Apollyon's Best Friend
    [T_ID .. 187] = "Розбиті окуляри", -- Broken Glasses
    [T_ID .. 188] = "Куб Льоду", -- Ice Cube
    [T_ID .. 189] = "Сигіл Бафомета", -- Sigil of Baphomet
}
EID:updateDescriptionsViaTable(trinkets, EID.ItemNames[languageCode])

---------cards---------
local cards = {
    [Card_ID .. 1] = "0 - Дурень", -- 0 - The Fool
    [Card_ID .. 2] = "I - Чарівник", -- I - The Magician
    [Card_ID .. 3] = "II - Верховна жриця", -- II - The High Priestess
    [Card_ID .. 4] = "III - Імператриця", -- III - The Empress
    [Card_ID .. 5] = "IV - Імператор", -- IV - The Emperor
    [Card_ID .. 6] = "V - Первосвященик", -- V - The Hierophant
    [Card_ID .. 7] = "VI - Коханці", -- VI - The Lovers
    [Card_ID .. 8] = "VII - Колісниця", -- VII - The Chariot
    [Card_ID .. 9] = "VIII - Справедливість", -- VIII - Justice
    [Card_ID .. 10] = "IX - Відлюдник", -- IX - The Hermit
    [Card_ID .. 11] = "X - Колесо фортуни", -- X - Wheel of Fortune
    [Card_ID .. 12] = "XI - Сила", -- XI - Strength
    [Card_ID .. 13] = "XII - Повішений", -- XII - The Hanged Man
    [Card_ID .. 14] = "XIII - Смерть", -- XIII - Death
    [Card_ID .. 15] = "XIV - Терпіння", -- XIV - Temperance
    [Card_ID .. 16] = "XV - Диявол", -- XV - The Devil
    [Card_ID .. 17] = "XVI - Башта", -- XVI - The Tower
    [Card_ID .. 18] = "XVII - Зірки", -- XVII - The Stars
    [Card_ID .. 19] = "XVIII - Місяць", -- XVIII - The Moon
    [Card_ID .. 20] = "XIX - Сонце", -- XIX - The Sun
    [Card_ID .. 21] = "XX - Суд", -- XX - Judgement
    [Card_ID .. 22] = "XXI - Світ", -- XXI - The World
    [Card_ID .. 23] = "2 Трефа", -- 2 of Clubs
    [Card_ID .. 24] = "2 Бубни", -- 2 of Diamonds
    [Card_ID .. 25] = "2 Піки", -- 2 of Spades
    [Card_ID .. 26] = "2 Черви", -- 2 of Hearts
    [Card_ID .. 27] = "Трефовий туз", -- Ace of Clubs
    [Card_ID .. 28] = "Бубновий туз", -- Ace of Diamonds
    [Card_ID .. 29] = "Піковий туз", -- Ace of Spades
    [Card_ID .. 30] = "Червовий туз", -- Ace of Hearts
    [Card_ID .. 31] = "Джокер", -- Joker
    [Card_ID .. 32] = "Хаґалаз", -- Hagalaz
    [Card_ID .. 33] = "Джера", -- Jera
    [Card_ID .. 34] = "Еваз", -- Ehwaz
    [Card_ID .. 35] = "Даґаз", -- Dagaz
    [Card_ID .. 36] = "Ансуз", -- Ansuz
    [Card_ID .. 37] = "Пертро", -- Perthro
    [Card_ID .. 38] = "Беркано", -- Berkano
    [Card_ID .. 39] = "Алґіз", -- Algiz
    [Card_ID .. 40] = "Порожня руна", -- Blank Rune
    [Card_ID .. 41] = "Чорна руна", -- Black Rune
    [Card_ID .. 42] = "Картка хаосу", -- Chaos Card
    [Card_ID .. 43] = "Кредитка", -- Credit Card
    [Card_ID .. 44] = "Картка з правилами", -- Rules Card
    [Card_ID .. 45] = "Картка проти людства", -- A Card Against Humanity
    [Card_ID .. 46] = "Король-самогубець", -- Suicide King
    [Card_ID .. 47] = "Картка \"Вийди з в'язниці\"", -- Get Out Of Jail Free Card
    [Card_ID .. 48] = "? Картка", -- ? Card
    [Card_ID .. 49] = "Уламок кубика", -- Dice Shard
    [Card_ID .. 50] = "Аварійний виклик", -- Emergency Contact
    [Card_ID .. 51] = "Свята картка", -- Holy Card
    [Card_ID .. 52] = "Гігантський ріст", -- Huge Growth
    [Card_ID .. 53] = "Виклик Древніх", -- Ancient Recall
    [Card_ID .. 54] = "Епохальна прогулянка", -- Era Walk
    [Card_ID .. 55] = "Осколок руни", -- Rune Shard
    [Card_ID .. 56] = "0 - Дурень?", -- 0 - The Fool?
    [Card_ID .. 57] = "I - Чарівник?", -- I - The Magician?
    [Card_ID .. 58] = "II - Верховна жриця?", -- II - The High Priestess?
    [Card_ID .. 59] = "III - Імператриця?", -- III - The Empress?
    [Card_ID .. 60] = "IV - Імператор?", -- IV - The Emperor?
    [Card_ID .. 61] = "V - Первосвященик?", -- V - The Hierophant?
    [Card_ID .. 62] = "VI - Коханці?", -- VI - The Lovers?
    [Card_ID .. 63] = "VII - Колісниця?", -- VII - The Chariot?
    [Card_ID .. 64] = "VIII - Справедливість?", -- VIII - Justice?
    [Card_ID .. 65] = "IX - Відлюдник?", -- IX - The Hermit?
    [Card_ID .. 66] = "X - Колесо Фортуни?", -- X - Wheel of Fortune?
    [Card_ID .. 67] = "XI - Сила?", -- XI - Strength?
    [Card_ID .. 68] = "XII - Повішений?", -- XII - The Hanged Man?
    [Card_ID .. 69] = "XIII - Смерть?", -- XIII - Death?
    [Card_ID .. 70] = "XIV - Терпіння?", -- XIV - Temperance?
    [Card_ID .. 71] = "XV - Диявол?", -- XV - The Devil?
    [Card_ID .. 72] = "XVI - Башта?", -- XVI - The Tower?
    [Card_ID .. 73] = "XVII - Зірки?", -- XVII - The Stars?
    [Card_ID .. 74] = "XVIII - Місяць?", -- XVIII - The Moon?
    [Card_ID .. 75] = "XIX - Сонце?", -- XIX - The Sun?
    [Card_ID .. 76] = "XX - Суд?", -- XX - Judgement?
    [Card_ID .. 77] = "XXI - Світ?", -- XXI - The World?
    [Card_ID .. 78] = "Зламаний Ключ", -- Cracked Key
    [Card_ID .. 79] = "Червова королева", -- Queen of Hearts
    [Card_ID .. 80] = "Дика картка", -- Wild Card
    [Card_ID .. 81] = "Душа Ісаака", -- Soul of Isaac
    [Card_ID .. 82] = "Душа Магдалени", -- Soul of Magdalene
    [Card_ID .. 83] = "Душа Каїна", -- Soul of Cain
    [Card_ID .. 84] = "Душа Юди", -- Soul of Judas
    [Card_ID .. 85] = "Душа ???", -- Soul of ???
    [Card_ID .. 86] = "Душа Єви", -- Soul of Eve
    [Card_ID .. 87] = "Душа Самсона", -- Soul of Samson
    [Card_ID .. 88] = "Душа Азазеля", -- Soul of Azazel
    [Card_ID .. 89] = "Душа Лазаря", -- Soul of Lazarus
    [Card_ID .. 90] = "Душа Едема", -- Soul of Eden
    [Card_ID .. 91] = "Душа Загубленого", -- Soul of the Lost
    [Card_ID .. 92] = "Душа Ліліт", -- Soul of Lilith
    [Card_ID .. 93] = "Душа Хранителя", -- Soul of the Keeper
    [Card_ID .. 94] = "Душа Аполліона", -- Soul of Apollyon
    [Card_ID .. 95] = "Душа Забутого", -- Soul of the Forgotten
    [Card_ID .. 96] = "Душа Бетані", -- Soul of Bethany
    [Card_ID .. 97] = "Душа Якова й Ісава", -- Soul of Jacob and Esau
}
EID:updateDescriptionsViaTable(cards, EID.ItemNames[languageCode])

---------pills---------
local pills = {
    [Pill_ID .. 1] = "Кепський газ", -- Bad Gas
    [Pill_ID .. 2] = "Кепський прихід", -- Bad Trip
    [Pill_ID .. 3] = "Сталеві яйця", -- Balls of Steel
    [Pill_ID .. 4] = "Бомби - це ключі", -- Bombs are Key
    [Pill_ID .. 5] = "Вибухова діарея", -- Explosive Diarrhea
    [Pill_ID .. 6] = "Повне Здоров'я", -- Full Health
    [Pill_ID .. 7] = "Здоров'я Знижено", -- Health Down
    [Pill_ID .. 8] = "Здоров'я Підвищено", -- Health Up
    [Pill_ID .. 9] = "Я знайшов пігулки", -- I Found Pills
    [Pill_ID .. 10] = "Пубертат", -- Puberty
    [Pill_ID .. 11] = "Гарненька мушка", -- Pretty Fly
    [Pill_ID .. 12] = "Зменшена Дальність", -- Range Down
    [Pill_ID .. 13] = "Підвищена Дальність", -- Range Up
    [Pill_ID .. 14] = "Знижена Швидкість", -- Speed Down
    [Pill_ID .. 15] = "Підвищена Швидкість", -- Speed Up
    [Pill_ID .. 16] = "Знижений Темп Стрільби", -- Tears Down
    [Pill_ID .. 17] = "Підвищений Темп Стрільби", -- Tears Up
    [Pill_ID .. 18] = "Знижена Удача", -- Luck Down
    [Pill_ID .. 19] = "Підвищена Удача", -- Luck Up
    [Pill_ID .. 20] = "Теле-пігулки", -- Telepills
    [Pill_ID .. 21] = "48 годин енергії!", -- 48 Hour Energy!
    [Pill_ID .. 22] = "Гематемезис", -- Hematemesis
    [Pill_ID .. 23] = "Параліч", -- Paralysis
    [Pill_ID .. 24] = "Я бачу Вічність!", -- I can see forever!
    [Pill_ID .. 25] = "Феромони", -- Pheromones
    [Pill_ID .. 26] = "Амнезія", -- Amnesia
    [Pill_ID .. 27] = "Лимонна вечірка", -- Lemon Party
    [Pill_ID .. 28] = "Ти чарівник?", -- R U A Wizard?
    [Pill_ID .. 29] = "Знеболювальне!", -- Percs!
    [Pill_ID .. 30] = "Залежність!", -- Addicted!
    [Pill_ID .. 31] = "Роз-слабся", -- Re-Lax
    [Pill_ID .. 32] = "???", -- ???
    [Pill_ID .. 33] = "Ця зробить тебе більшим", -- One makes you larger
    [Pill_ID .. 34] = "Ця зробить тебе меншим", -- One makes you small
    [Pill_ID .. 35] = "Інфікований!", -- Infested!
    [Pill_ID .. 36] = "Інфікований?", -- Infested?
    [Pill_ID .. 37] = "Пігулка сили!", -- Power Pill!
    [Pill_ID .. 38] = "Ретро-погляд", -- Retro Vision
    [Pill_ID .. 39] = "Друзі до кінця!", -- Friends Till The End!
    [Pill_ID .. 40] = "Проносне", -- X-Lax
    [Pill_ID .. 41] = "Щось не так...", -- Something's wrong...
    [Pill_ID .. 42] = "Я сонний...", -- I'm Drowsy...
    [Pill_ID .. 43] = "Я збуджений!!", -- I'm Excited!!
    [Pill_ID .. 44] = "Ковть!", -- Gulp!
    [Pill_ID .. 45] = "Тьху!", -- Horf!
    [Pill_ID .. 46] = "Відчуття, ніби крокую сонячним сяйвом!", -- Feels like I'm walking on sunshine!
    [Pill_ID .. 47] = "Вурп!", -- Vurp!
    [Pill_ID .. 48] = "Знижена Швидкість Стрільби", -- Shot speed Down
    [Pill_ID .. 49] = "Підвищена Швидкість Стрільби", -- Shot speed Up
    [Pill_ID .. 50] = "Експериментальна пігулка", -- Experimental Pill
    [Pill_ID .. 9999] = "Золота пігулка", -- Golden Pill
}
EID:updateDescriptionsViaTable(pills, EID.ItemNames[languageCode])